### ISSUE TITLE
Typo on the color resource type explanation

### ISSUE THREAD

**Issue by HankiDesign** [MicrosoftDocs/xamarin-docs#1]
There's an extra word (make) in the second sentence of the color resource type explanation. Here's what it should be: 
*"XML files that describe a state list of colors. To understand color state lists, consider a UI widget such as a Button. It may
~~make~~ have different states such as pressed or disabled, and the button may change color with each change in state. The list is expressed in a state list."*

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7d118756-bf0f-0fc9-b6df-c3437397b2cf
* Version Independent ID: 37627877-5b22-e8c2-f22b-252afb12e78b
* Content: [Default Resources - Xamarin | Microsoft Docs](https://docs.microsoft.com/en-us/xamarin/android/app-fundamentals/resources-in-android/default-resources?tabs=vswin)
* Content Source: [docs/android/app-fundamentals/resources-in-android/default-resources.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/android/app-fundamentals/resources-in-android/default-resources.md)
* Service: **unspecified**
* GitHub Login: @mgmclemore
* Microsoft Alias: **mamcle**

**Comment by mgmclemore** [comment]
Fixed and the change should be published soon. Thank you for pointing this out!
