### ISSUE TITLE
Deprecation notice

### ISSUE THREAD

**Issue by appsourcers** [MicrosoftDocs/xamarin-docs#10]
Above in the document it says 
### Use `/Library/Frameworks/Mono.framework/Commands/xbuild` on OS X

But xbuild is being deprecated. See here http://www.mono-project.com/docs/about-mono/releases/5.0.0/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aa951c69-0f9f-d6f8-b879-0a3427436e3c
* Version Independent ID: 7807523a-115c-5f73-b22a-a914792467a4
* Content: [Build Process - Xamarin | Microsoft Docs](https://docs.microsoft.com/en-us/xamarin/android/deploy-test/building-apps/build-process#feedback)
* Content Source: [docs/android/deploy-test/building-apps/build-process.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/android/deploy-test/building-apps/build-process.md)
* Service: **unspecified**
* GitHub Login: @mgmclemore
* Microsoft Alias: **mamcle**

**Comment by mgmclemore** [comment]
Thank you for pointing this out! `xbuild` has indeed been deprecated in favor of `msbuild`. The updated version of this topic should appear shortly.
