### ISSUE TITLE
iOS: clarification about "Library" directory wrt user data files?

### ISSUE THREAD

**Issue by knocte** [MicrosoftDocs/xamarin-docs#1001]
The iOS section of this documentation has an hyperlink called "Library" which points to this link: https://developer.apple.com/library/archive/documentation/FileManagement/Conceptual/FileSystemProgrammingGuide/FileSystemOverview/FileSystemOverview.html

In this link (apple page), it is said about the "Library/" directory that its purpose is "for any files that are not user data files". However, given that Xamarin.Essentials only provides "FileSystem.CacheDirectory" and "FileSystem.AppDataDirectory", its obvious that devs shouldn't choose the former (CacheDirectory) for user data files. Then should Xamarin.Essentials expose the "Documents/" iOS directory too? Will it support it in the future? Or is it fine to disregard this recommendation from Apple and use the "Library/" directory for user data files?

A clarification on the documentation would be appreciated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 91d50947-38a1-44b7-2684-63b17d5bac66
* Version Independent ID: b449b3f5-7a68-fdea-041b-71cc39a46a48
* Content: [Xamarin.Essentials: File System Helpers - Xamarin](https://docs.microsoft.com/en-us/xamarin/essentials/file-system-helpers?context=xamarin%2Fxamarin-forms&tabs=ios)
* Content Source: [docs/essentials/file-system-helpers.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/essentials/file-system-helpers.md)
* Product: **xamarin**
* GitHub Login: @jamesmontemagno
* Microsoft Alias: **jamont**

**Comment by jamesmontemagno** [comment]
We document where these map to:

https://docs.microsoft.com/en-us/xamarin/essentials/file-system-helpers?context=xamarin%2Fxamarin-forms&tabs=ios#platform-implementation-specifics

Android
* CacheDirectory – Returns the CacheDir of the current context.
* AppDataDirectory – Returns the FilesDir of the current context and are backed up using Auto Backup starting on API 23 and above.

iOS:
* CacheDirectory – Returns the Library/Caches directory.
* AppDataDirectory – Returns the Library directory that is backed up by iTunes and iCloud.

UWP:
* CacheDirectory – Returns the LocalCacheFolder directory..
* AppDataDirectory – Returns the LocalFolder directory that is backed up to the cloud.

We only map Cache and AppData folders. We originally had a "UserDataDirectory", but it didn't map on Android or UWP at all so it wasn't helpful and we don't plan on adding it. Library has always been the recommended spot for this.

**Comment by conceptdev** [comment]
I hope that answers your question @knocte. If you have specific product feedback or a feature request, visit the [open source repo feedback page](https://github.com/xamarin/Essentials/blob/master/PRODUCT-FEEDBACK.md).
Thanks for posting.
