### ISSUE TITLE
Native Forms for Android is outdated

### ISSUE THREAD

**Issue by mallibone** [MicrosoftDocs/xamarin-docs#1006]
Since Xamarin Forms 3.3 uses the support library for creating the fragment the sample code provided under [Native Forms](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/platform/native-forms.md ) is no longer up to date.

**Comment by davidbritch** [comment]
Hi @mallibone 

Thanks for pointing this out. I've updated the doc and sample, although it'll be later in the day before the doc PR goes live.

Thanks again.
