### ISSUE TITLE
Java vs. C# differences

### ISSUE THREAD

**Issue by yu-eric** [MicrosoftDocs/xamarin-docs#1008]
In the "Xamarin for Java Developers" documentation, it mentions that "Java does not support implicitly-typed local variables (C# supports the var keyword)." However, since the release of Java 10, Java does support the use of the var keyword.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cbb2ed12-d9b5-ea5c-9575-bf57bf19fc4e
* Version Independent ID: 0fdfc765-e358-a9bb-3289-680170e9570b
* Content: [Xamarin for Java Developers - Xamarin](https://docs.microsoft.com/en-us/xamarin/android/get-started/java-developers)
* Content Source: [docs/android/get-started/java-developers.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/android/get-started/java-developers.md)
* Product: **xamarin**
* GitHub Login: @conceptdev
* Microsoft Alias: **crdun**

**Comment by conceptdev** [comment]
Thanks for the feedback @yu-eric. Although Java 10 might not be available for Android developers just yet, we certainly want our content to be clear and accurate. We'll update the content to better reflect current Java and Android realities.

**Comment by conceptdev** [comment]
We added a note to clarify the page is comparing the Java which is available to Android developers, and that Java 10 might have capabilities not available on Android.
