### ISSUE TITLE
Issues with the PCL case study

### ISSUE THREAD

**Issue by HankiDesign** [MicrosoftDocs/xamarin-docs#101]
- The questions on this page are missing a space after the ### characters and don't show up as headers. Also, is there a specification for how to format this kind of QA pages? The answer headers seem redundant and the flow would be much better with the question in a header and the answer below.

- There are some numbers that should be spelled out in whole:

> This limitation leads to ~~3~~ three layers of errors

- The second bullet point in the *Details about the 3 layers of errors* section seems to be out of date. There are currently 18 overloads of the `WriteEvent` method and they all exist in the mono implementation. For comparison: [Mono](https://github.com/mono/mono/blob/master/mcs/class/corlib/System.Diagnostics.Tracing/EventSource.cs#L171), [Microsoft](https://referencesource.microsoft.com/#mscorlib/system/diagnostics/eventing/eventsource.cs,767). Also, the bug referenced was marked as _VERIFIED FIXED_ two years ago.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a821ad0c-0b05-0f65-ca05-33b95d9fc084
* Version Independent ID: 0bee25b1-cf9a-701c-7703-488fb7beb7f6
* Content: [PCL case study: How can I resolve problems related to System.Diagnostics.Tracing for the Microsoft TPL Dataflow NuGet package? - Xamarin](https://docs.microsoft.com/en-us/xamarin/cross-platform/troubleshooting/questions/pcl-case-study)
* Content Source: [docs/cross-platform/troubleshooting/questions/pcl-case-study.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/cross-platform/troubleshooting/questions/pcl-case-study.md)
* Service: **unspecified**
* GitHub Login: @asb3993
* Microsoft Alias: **amburns**

**Comment by asb3993** [comment]
Hey @HankiDesign, thanks so much for the keen eye for detail. I'm submitting a PR for the first two points. For the last point, I want to verify the entire doc, as it seems like it was written some time ago.

**Comment by conceptdev** [comment]
@HankiDesign the [doc update](https://docs.microsoft.com/en-us/xamarin/cross-platform/troubleshooting/questions/pcl-case-study) was published yesterday. Thanks again for the detailed feedback.
