### ISSUE TITLE
DataBinding Application.Current.Properties vs Xam.Plugins.Settings

### ISSUE THREAD

**Issue by stmax82** [MicrosoftDocs/xamarin-docs#102]
The justifications for using Xam.Plugins.Settings instead of Application.Current.Properties seem far fetched:

> A downside to storing data using the Xamarin.Forms persistent dictionary is that it's not easily data bound to.

In the provided example all access to the settings is encapsulated in the Settings class. For data binding it makes no difference if the Settings class uses Xam.Plugins.Settings or Application.Current.Properties.

> The Xam.Plugins.Settings library provides a [...] type-safe [...] approach for persisting and retrieving app and user settings

Xam.Plugins.Settings is not any more type safe than Application.Current.Properties:

CrossSettings.Current.AddOrUpdateValue("MySetting", "foo"); // save a string
CrossSettings.Current.GetValueOrDefault("MySetting", 42); // read it back as int

... of course results in a ClassCastException: "java.lang.String cannot be cast to java.lang.Integer".

Exactly the same happens with Application.Current.Properties:

Application.Current.Properties["MySetting"] = "foo";
int value = (int)Application.Current.Properties["MySetting"];

... InvalidCastException.

I still like the API of the settings plugin more because of the GetValueOrDefault method, which saves you an "if" that checks if the key exists. And its independence from Xamarin.Forms (even though we only have Forms apps).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0fb06291-59d5-9a7a-07e5-0716f9a4d716
* Version Independent ID: 93a6d320-f41c-22df-44c0-75a53799408a
* Content: [Configuration Management - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/enterprise-application-patterns/configuration-management)
* Content Source: [docs/xamarin-forms/enterprise-application-patterns/configuration-management.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/enterprise-application-patterns/configuration-management.md)
* Service: **unspecified**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Thanks for the feedback. I don't disagree with you.

v2 of the app/eBook/docs will no longer uses Xam.Plugin.Settings, so this content will be re-written.

**Comment by balaameex** [comment]
Hi,

May I know where the Application.Current.Properties are saved in a physical file system, Is it possible to get the values from the device?
Balakrishnan
