### ISSUE TITLE
Step 7

### ISSUE THREAD

**Issue by zopagaduanjr** [MicrosoftDocs/xamarin-docs#1034]
Step 7 was very vague. I was following both the youtube and the written instructions. Couldn't get my app to run instantly when i click "Start without debugging". Turns out I explicitly need to go to the app drawer and find App1.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 64faeef1-f3b9-df53-33d2-d050ef1d6a98
* Version Independent ID: 17bf9211-d2a6-e3bb-8cfc-357828d84e3d
* Content: [Build your first Xamarin.Forms app - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/get-started/first-app/index?pivots=windows)
* Content Source: [docs/xamarin-forms/get-started/first-app/index.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/get-started/first-app/index.md)
* Product: **xamarin**
* GitHub Login: @conceptdev
* Microsoft Alias: **crdun**

**Comment by conceptdev** [comment]
Thanks for your feedback @zopagaduanjr. Step 7 is very brief - we will expand it to be more helpful.

Regarding your experience, if you choose either **Start**/**Run** or **Debug**, the application _should_ automatically appear in the emulator or on your device. If you find that does not work, perhaps check [Developer Community](https://developercommunity.visualstudio.com/) for possible causes and fixes.
