### ISSUE TITLE
Stable Release?

### ISSUE THREAD

**Issue by ckrempp91** [MicrosoftDocs/xamarin-docs#1035]
Is this functionality ever going to be released within a stable version? This has been in preview for over a year now, at least.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 711d54ad-842b-2141-95b3-fc71d053dbac
* Version Independent ID: be8e8253-7014-1065-ee9b-27a41d35b1ec
* Content: [Xamarin.Forms Themes - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/themes/)
* Content Source: [docs/xamarin-forms/user-interface/themes/index.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/themes/index.md)
* Product: **xamarin**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by conceptdev** [comment]
@ckrempp91, thanks for your feedback.

You can communicate directly with the engineering team via the Issues list on the [open source Xamarin.Forms repo](https://github.com/xamarin/xamarin.forms), as well as monitor work on the code.

For now, as far as the documentation is concerned, it remains a Preview feature.
