### ISSUE TITLE
Call base in DidFinishLaunching

### ISSUE THREAD

**Issue by DamianMehers** [MicrosoftDocs/xamarin-docs#1059]
I'm running the very latest bits (I cloned the Xamarin Forms master and built locally), and I'm finding the Window doesn't appear unless I call

``` C#
    base.DidFinishLaunching(notification);
```

in `DidFinishLaunching`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9bdf7861-f51a-48de-4163-b578a62826d2
* Version Independent ID: ec6bf29e-1c46-7eb9-31ed-acf7e8d1d2cc
* Content: [Mac Platform Setup - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/platform/mac)
* Content Source: [docs/xamarin-forms/platform/mac.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/platform/mac.md)
* Product: **xamarin**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by DamianMehers** [comment]
```
    public override void DidFinishLaunching(NSNotification notification) {
      Forms.Init();
      LoadApplication(new App());
      base.DidFinishLaunching(notification);
    }
```

**Comment by spatialguy** [comment]
I had the same problem.  Calling base.DidFinishLaunching(notification) solves the problem.

**Comment by conceptdev** [comment]
Thanks for the feedback, the docs actually used to contain that method, but [it was removed](https://github.com/MicrosoftDocs/xamarin-docs/commit/c98419bc6a9bbd8a636d5c1713a66bd86fed269e).

I'll speak to the engineering team to confirm the correct guidance, but for now check the comments [on that commit](https://github.com/MicrosoftDocs/xamarin-docs/commit/c98419bc6a9bbd8a636d5c1713a66bd86fed269e) and validate the behavior you see on both Mojave and older versions of macOS.

**Comment by conceptdev** [comment]
the `FinishedLaunching` method was re-added to the documentation in this commit https://github.com/MicrosoftDocs/xamarin-docs/commit/f3f28722198e172d81c16bdeab0cb0a581a08dd0#diff-6abea1e8f30d3233c80b41c56299753f

Thanks for letting us know!
