### ISSUE TITLE
Clear introduction

### ISSUE THREAD

**Issue by GT85** [MicrosoftDocs/xamarin-docs#106]
Just need to be used and checked

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 87a439c7-acce-7197-b791-f9d92d2fb4c8
* Version Independent ID: 43a30e21-a01b-c1cb-19ba-6350c8e6493a
* Content: [Introduction - Xamarin](https://docs.microsoft.com/en-gb/xamarin/ios/data-cloud/data/introduction)
* Content Source: [docs/ios/data-cloud/data/introduction.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/ios/data-cloud/data/introduction.md)
* Service: **unspecified**
* GitHub Login: @bradumbaugh
* Microsoft Alias: **brumbaug**

**Comment by bradumbaugh** [comment]
Hi @GT85 - thanks for the comment. It would help to have more specific information - is there a particular doc in this section that you're seeing an issue with? Appreciate the help.
