### ISSUE TITLE
XAML Page links broken

### ISSUE THREAD

**Issue by torrobinson** [MicrosoftDocs/xamarin-docs#108]
A few of the "XAML Page" links on this page are missing - either broken links to GitHub or missing pages from Microsoft's domain

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 07b7fe9d-eda5-ea03-1f95-b2ddcea26ec5
* Version Independent ID: 3c89f3d3-65f3-08d7-f0a4-bce5442221a8
* Content: [Xamarin.Forms Layouts - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/controls/layouts)
* Content Source: [docs/xamarin-forms/user-interface/controls/layouts.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/controls/layouts.md)
* Service: **unspecified**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by conceptdev** [comment]
@torrobinson you're right - StackLayout, Grid, AbsoluteLayout, RelativeLayout - all had bad links to github. Thanks for letting us know - fix incoming!
