### ISSUE TITLE
So, how do I tie this with my project?

### ISSUE THREAD

**Issue by dannyatftecu** [MicrosoftDocs/xamarin-docs#109]
I created the Notification Content Extension as documented above.  Now, how do I invoke it from my app?  The Xamarin iOS example ios-samples-master/ios10/MonkeyNotify doesn't seem to call the Extension since setting a break point in "DidReceiveNotificationRequest" (in NotificationService.cs in the MonkeyNotifyServiceExtension project) fails to do anything after pressing the Custom Action button.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 31483a25-9149-664a-2d03-ff4f96a130e0
* Version Independent ID: 9df90ceb-39cc-6371-7141-f53e49433851
* Content: [Advanced User Notifications - Xamarin](https://docs.microsoft.com/en-us/xamarin/ios/platform/user-notifications/advanced-user-notifications?tabs=vsmac)
* Content Source: [docs/ios/platform/user-notifications/advanced-user-notifications.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/ios/platform/user-notifications/advanced-user-notifications.md)
* Service: **unspecified**
* GitHub Login: @bradumbaugh
* Microsoft Alias: **brumbaug**

**Comment by conceptdev** [comment]
@dannyatftecu unfortunately we can't answer specific questions here; however we'll [take a look](https://github.com/xamarin/ios-samples/issues/224) at the sample to make sure it's working as expected.

If you need further support options, visit https://www.visualstudio.com/vs/support/
