### ISSUE TITLE
UI Testing with Xamarin - single set of docs

### ISSUE THREAD

**Issue by JesseLiberty** [MicrosoftDocs/xamarin-docs#11]
There are pretty good docs on getting started with UI testing in Xamarin, but what is desperately needed is one or more pages of commands, what they do and short examples.  It is very difficult, given the current documentation, to figure out how to, for example, go back from one page to another (Back()) much less figure out how to add id's (StyleId and its setup).  Putting it all in one place would be terrific.

Thanks
@jesseliberty
jesseliberty@gmail.com
339-234-8675

**Comment by conceptdev** [comment]
Hey @JesseLiberty, now that UITest is part of Visual Studio App Center, the [App Center docs](https://docs.microsoft.com/en-us/appcenter/test-cloud/uitest/) are the right place to look for comprehensive UITest information.

**Comment by conceptdev** [comment]
Not at all Jesse, just trying to clarify that with respect to UI Testing, the docs for App Center is where you can expect to find the most detailed coverage. As the product grows and changes over time, they're much better positioned to keep those docs updated than if we had duplicate coverage in the Xamarin docs. Your best bet for seeking out detailed information on how to use UITest (e.g.. "how to go back") is from that content.

You _can_ expect the Xamarin docs to cover some introductory material, such as [this doc](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/deploy-test/uitest-and-test-cloud), which introduces the Xamarin.Forms-specific `AutomationId` to help you get started.

I've also passed your feedback on to the App Center Test team.

**Comment by JesseLiberty** [comment]
Thanks Craig, I appreciate it.
