### ISSUE TITLE
Discrepancy between Xamarin.Android and Xamarin.iOS on which name space to put PreserveAttribute

### ISSUE THREAD

**Issue by Cheesebaron** [MicrosoftDocs/xamarin-docs#111]
The [Xamarin.Android documentation](https://docs.microsoft.com/en-us/xamarin/android/deploy-test/linker#preserving-code) says to put the `PreserveAttribute` in the `Android.Runtime` namespace. The [Xamarin.iOS documentation](https://docs.microsoft.com/en-us/xamarin/ios/deploy-test/linker?tabs=vsmac#preserving-code) says to put it in any name space as it is looked up by the name.

Which one is it?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ab92cdf-ac95-4451-e452-6dedd80ae5cf
* Version Independent ID: 36488aca-43cb-8d55-1d6b-b7bad09b1301
* Content: [Linking on Android - Xamarin](https://docs.microsoft.com/en-us/xamarin/android/deploy-test/linker#feedback)
* Content Source: [docs/android/deploy-test/linker.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/android/deploy-test/linker.md)
* Service: **unspecified**
* GitHub Login: @mgmclemore
* Microsoft Alias: **mamcle**

**Comment by mgmclemore** [comment]
Hi @Cheesebaron, you can put the `PreserveAttribute` in any name space with Xamarin.Android as you can with Xamarin.iOS (the Xamarin.Android doc needs to be updated). We'll fix that right away. Thanks for your feedback!

**Comment by mgmclemore** [comment]
Topic updated, the changes will be published soon.
