### ISSUE TITLE
Update ~/ links in docs

### ISSUE THREAD

**Issue by nschonni** [MicrosoftDocs/xamarin-docs#1116]
Docs guidance was updated to discourage the use of those (which are valid DocFx) because they don't play nice with GitHub https://docs.microsoft.com/en-us/contribute/how-to-write-links#links-from-one-article-to-another

**Comment by conceptdev** [comment]
I think that guidance misses an important part of our CI/build system, which is certain formats of internal link are 'validated' as part of the PR, while other forms are not. It also ignores the fact that cross-docset links will _never_ be navigable in GitHub, regardless of which form is used (a fully qualified link, ie `https://docs.microsoft.com/visualstudio` would still 'work', but not source-to-source), and neither will the build-time type-checked API reference links `xref:` (which you will find a lot in the Xamarin.Forms docs).

For now, I believe the link validation behavior contributes more to our documentation quality than "some" links working in GitHub. Over time I expect the CI to become more sophisticated and we will revisit this, but for now I have no plans to active remove the `~/` syntax from our docset. "Non-validate-able" links in a PR submission will most likely be transformed as part of the review/merge process.

Thanks for reaching out, I hope the above makes sense.

**Comment by nschonni** [comment]
That's fine I'm guessing it would come down to a general MicrosoftDocs organization internal cleanup exercise. I think the other repos that have cleaned this up changed to relative links instead of fully qualified docs.microsoft.com links for the ones that are internal to the repo (but those are also not consistent 😉 )

**Comment by conceptdev** [comment]
"consistently inconsistent" 🙂
I didn't mention the other reason `~/` is so prevalent to start with, which is related to the history of our docs on a totally different (custom) publishing platform prior to migrating to docs.microsoft.com. Also, I have a huge aversion to "../../../something" 🙈

Our standards and practices will no doubt grow and evolve with the tooling, so stay tuned.

Once again, appreciate your interest; and also let me take the opportunity to say thanks for the last few days of PRs and your commitment to improving our docs!
