### ISSUE TITLE
Portable Class Libraries (PCL) no longer supported

### ISSUE THREAD

**Issue by Mikilll94** [MicrosoftDocs/xamarin-docs#1117]
This article is outdated. Portable Class Libraries are no longer supported in Visual Studio.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2b502915-30a5-be66-7e45-d45ea9984b6b
* Version Independent ID: e0f0abee-aa7b-a3c7-6e74-e577500d5abb
* Content: [Part 3 - Setting Up A Xamarin Cross Platform Solution - Xamarin](https://docs.microsoft.com/en-us/xamarin/cross-platform/app-fundamentals/building-cross-platform-applications/setting-up-a-xamarin-cross-platform-solution)
* Content Source: [docs/cross-platform/app-fundamentals/building-cross-platform-applications/setting-up-a-xamarin-cross-platform-solution.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/cross-platform/app-fundamentals/building-cross-platform-applications/setting-up-a-xamarin-cross-platform-solution.md)
* Product: **xamarin**
* GitHub Login: @asb3993
* Microsoft Alias: **amburns**

**Comment by conceptdev** [comment]
While .NET Standard is the recommended approach for new applications, [PCL is still supported in Visual Studio 2017](https://docs.microsoft.com/en-us/dotnet/standard/cross-platform/cross-platform-development-with-the-portable-class-library).

We will be revising this page to ensure .NET Standard is clearly recommended over other older alternatives.
