### ISSUE TITLE
Compatibility with 2017

### ISSUE THREAD

**Issue by samirgunic** [MicrosoftDocs/xamarin-docs#112]
Is this emulator compatible with Visual Studio 2017 or not? It's not very clear from this document.

> This guide explains how to configure and use the Visual Studio Android Emulator to develop Xamarin.Android apps in Visual Studio 2015.

Which means you have not had the time to test it with Visual Studio 2017 or that it is in fact incompatible with Visual Studio 2017?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0546ef4d-4237-66c4-d7b0-f86b57dc91b3
* Version Independent ID: 85fa9e0e-cf82-e63b-2557-c3869a3888b4
* Content: [Visual Studio Android Emulator - Xamarin](https://docs.microsoft.com/en-us/xamarin/android/deploy-test/debugging/visual-studio-android-emulator#feedback)
* Content Source: [docs/android/deploy-test/debugging/visual-studio-android-emulator.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/android/deploy-test/debugging/visual-studio-android-emulator.md)
* Service: **unspecified**
* GitHub Login: @mgmclemore
* Microsoft Alias: **mamcle**

**Comment by mgmclemore** [comment]
Hi @samirgunic, the Visual Studio Android Emulator only works with Visual Studio 2015. We'll update the doc to make that clear.  Thanks for your feedback!

**Comment by mgmclemore** [comment]
Doc updated with a note to make clear the compatibility level of this emulator. Should be published soon.

**Comment by mxa0079** [comment]
Ok, so if the emulator is incompatible with VS2017 - then what is the recommended approach to debug Xamarin Android applications on VS2017? It seems like there is a huge gap as other emulators are not compatible with Hyper-v. This is specially troublesome for those of use that have a dependency on Hyper-V (e.g. Docker) but also need to run the Android emulator.

**Comment by AntRemo** [comment]
Hi @mgmclemore 

I too would like to know what the recommended approach is, as I just upgraded to 2017 only to find the emulator not available :(

Thanks

**Comment by AntRemo** [comment]
Thanks for the speedy reply and link @conceptdev ! :)

I came across that doc this morning and was able to get everything working.

**Comment by samirgunic** [comment]
@mxa0079, @AntRemo I can tell you that the "Visual Studio Emulator for Android" by Microsoft is indeed compatible with Visual Studio 2017, if you are willing to put in some effort to make it so. As I recall, I had to add or modify a key in the Windows registry in order make the emulated devices appear on the target device drop-down menu in Visual Studio. Once I did that, I was able to deploy and debug using the VS Emulator for Android, as if it was Visual Studio 2015.

But truth to be told, VS Emulator for Android is not officially supported by Visual Studio 2017. As evident by my need to do registry hacks to enable it. The emulator itself can be obtained independently, outside of Visual Studio Installer. You can visit the [Visual Studio website](https://www.visualstudio.com/vs/msft-android-emulator/) to get it, or click on this Microsoft [short link](https://aka.ms/vscomemudownload).

So yes, you can hack it, but it's not meant to be enabled in Visual Studio 2017. Moreover, VS Emulator for Android is deprecated and is no longer being developed. The latest Android image available is 6.0. Microsoft has made this clear recently by adding the following note on the linked website above.

> After we released the Visual Studio Emulator for Android, Google updated their Android emulator to use hardware acceleration through Intel’s HAXM. We recommend you use Google’s emulator when you can, as it offers access to the latest Android OS images and Google Play services.

So there you go, the official way to emulate Android devices with Visual Studio 2017 on Windows is to use the Android emulator by Google which is included with the Google SDK.

One major drawback of the Google emulator that you should know about is that it is not Hyper-V compatible, and there is no AMD equivalent to the Intel HAXM hypervisor, so the performance hit you get without hardware acceleration will render this emulator unusable if you are using a computer based on an AMD processor. If that is the case, you may want to look at ways to enable the old emulator in Visual Studio 2017 if you are developing on Windows. Alternatively, you can run Windows in a VM with Linux as your development environment and have the guest OS connect to an Android emulator running on Linux. That way you can leverage AMD-V and get the hardware acceleration you need. However, if your computer is based on an Intel processor then you should be all set, regardless.

**Comment by AntRemo** [comment]
Hi @samirgunic!

Thanks so much for the super detailed reply.

I was able to get the Google Android Emulator to work, (Intel based PCs) but the other info your provided is useful to know as well. 

Thanks again :)
