### ISSUE TITLE
Small amounts of text - what exactly is small?

### ISSUE THREAD

**Issue by alexsorokoletov** [MicrosoftDocs/xamarin-docs#1123]
&gt;This API is intended to store small amounts of text. Performance may be slow if you try to use it to store large amounts of text.

Wondering what exactly means small amounts of text

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: da75050f-bfda-4792-40d9-b9a25d649d3e
* Version Independent ID: 5c44f996-765b-f6e4-c807-9446c534d50b
* Content: [Xamarin.Essentials: Secure Storage - Xamarin](https://docs.microsoft.com/en-us/xamarin/essentials/secure-storage?tabs=ios)
* Content Source: [docs/essentials/secure-storage.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/essentials/secure-storage.md)
* Product: **xamarin**
* GitHub Login: @jamesmontemagno
* Microsoft Alias: **jamont**

**Comment by iMrTidy** [comment]
I guess you can store quite a lot but it will slow down the app since crypt/decrypt takes more CPU time the more data to be processed.

**Comment by conceptdev** [comment]
Hi @alexsorokoletov, as Xamarin.Essentials is open-source, you can actually review the code implementing this feature on [GitHub](https://github.com/xamarin/essentials). You could also raise an issue there enquiring about the exact size limitation.

As performance is affected by a number of factors, including the processor and memory on each device, I do not have an exact size for the text. I would suggest that hundreds of characters is probably an acceptable amount of text for this API, but thousands of characters might be too much. Consider limiting this feature for storing hashed identifiers or other data that is generated by your code, and therefore you control how big it is. Avoid storing free-text data entered by the user where the size could be unlimited.
