### ISSUE TITLE
Cannot update the bound collection

### ISSUE THREAD

**Issue by Katydude** [MicrosoftDocs/xamarin-docs#1124]
This control is incomplete because it does not respond to changes to the bound ItemsSource collection. This forces developers to extend a basic control just so it will reconstruct the list of items. Most real-world applications load a list of objects asynchronously and then update the bound collection. The Picker will not reflect those changes. This really needs to be addressed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8c1318ca-d61b-4a2d-a360-d485f86ade97
* Version Independent ID: f948089f-2dc8-fd3a-8bc4-26958148d0de
* Content: [Setting a Picker's ItemsSource Property - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/picker/populating-itemssource)
* Content Source: [docs/xamarin-forms/user-interface/picker/populating-itemssource.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/picker/populating-itemssource.md)
* Product: **xamarin**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @Katydude 

This is an issue for the [engineering repo](https://github.com/xamarin/Xamarin.Forms/), in the form of an enhancement request.
