### ISSUE TITLE
AppInfo.ShowSettingsUI() should be AppInfo.OpenSettings()

### ISSUE THREAD

**Issue by itoledo** [MicrosoftDocs/xamarin-docs#1126]
Seems that the signature is wrong, at least on Xamarin.Essentials 0.11.0-pre.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2c4b0c52-127c-0e6b-28d1-3071c522e507
* Version Independent ID: 61f6a36e-9c85-bf57-49f0-76719d8a47c1
* Content: [Xamarin.Essentials: App Information - Xamarin](https://docs.microsoft.com/en-us/xamarin/essentials/app-information?context=xamarin/xamarin-forms)
* Content Source: [docs/essentials/app-information.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/essentials/app-information.md)
* Product: **xamarin**
* GitHub Login: @jamesmontemagno
* Microsoft Alias: **jamont**

**Comment by james-alt** [comment]
Hey @davidbritch, should probably close this issue as well since it was handled by #1135
