### ISSUE TITLE
Running sample outside of VS2017

### ISSUE THREAD

**Issue by mores** [MicrosoftDocs/xamarin-docs#113]
The UWP launches and runs fine when using the Start Button inside of VS2017.
I close VS2017, navigate to the exe double click - nothing happens.
Tried from the command line, no error message.
What is the process to deliver this Phoneword App into the hands of a non-developer ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2de3e72c-8948-4dd5-e37f-9cf81e62c127
* Version Independent ID: 7b7c5c7f-4102-8e91-fbe6-7d21fcc8f5be
* Content: [Xamarin.Forms Quickstart - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/get-started/hello-xamarin-forms/quickstart?tabs=vswin)
* Content Source: [docs/xamarin-forms/get-started/hello-xamarin-forms/quickstart.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/get-started/hello-xamarin-forms/quickstart.md)
* Service: **unspecified**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by conceptdev** [comment]
Hi @mores, please refer to the UWP docs for application packaging

https://docs.microsoft.com/en-us/windows/uwp/packaging/packaging-uwp-apps

As a getting started guide, this is beyond the scope of this doc.
