### ISSUE TITLE
Screenshot

### ISSUE THREAD

**Issue by ryanharding** [MicrosoftDocs/xamarin-docs#1131]
Where do screenshots get saved to ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 18072f31-4d0e-f9b4-c085-fcaa66f278fc
* Version Independent ID: a9ba3155-0f55-f303-e27a-93360433cf0f
* Content: [Remoted iOS Simulator for Windows - Xamarin](https://docs.microsoft.com/en-us/xamarin/tools/ios-simulator/)
* Content Source: [docs/tools/ios-simulator/index.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/tools/ios-simulator/index.md)
* Product: **xamarin**
* GitHub Login: @lobrien
* Microsoft Alias: **laobri**

**Comment by conceptdev** [comment]
Hi @ryanharding, the screen captures are saved in the Windows **Pictures** folder, in a subdirectory **/Xamarin/iOS Simulator/**.

I'll update the document with this info; thanks for the feedback.
