### ISSUE TITLE
Mis-Redirection from Xamarin.Android page

### ISSUE THREAD

**Issue by mehul19851** [MicrosoftDocs/xamarin-docs#1132]
Currently, there is a link on Deep Dive page which is related to Cross-platform applications, however the current scope of document is Xamarin.Android. Hence, this link would deviate a user or mislead from Xamarin.Android to cross-platform apps halfway through.

Kindly investigate on the same.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f4b7d0a1-1c45-0ef1-c11e-491e85d32991
* Version Independent ID: c7acc4e2-78a4-98f0-2e64-5e395c974c81
* Content: [Hello, Android Multiscreen: Deep Dive - Xamarin](https://docs.microsoft.com/en-us/xamarin/android/get-started/hello-android-multiscreen/hello-android-multiscreen-deepdive)
* Content Source: [docs/android/get-started/hello-android-multiscreen/hello-android-multiscreen-deepdive.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/android/get-started/hello-android-multiscreen/hello-android-multiscreen-deepdive.md)
* Product: **xamarin**
* GitHub Login: @conceptdev
* Microsoft Alias: **crdun**

**Comment by conceptdev** [comment]
Hi @mehul19851, thanks for your feedback. A large number of Xamarin developers are interesting in cross-platform development, either with Android and iOS, or sharing existing .NET code with their Android apps. 

The link you are referring to is at the end of the document, and is prefaced with an explanation of what is in the link: "Next, you'll learn to build cross-platform applications with Xamarin".

The very first item is then [Understanding the Xamarin Mobile Platform](https://docs.microsoft.com/en-us/xamarin/cross-platform/app-fundamentals/building-cross-platform-applications/understanding-the-xamarin-mobile-platform), which we think can be useful for all Xamarin developers.

I hope that helps explain why the link is provided.
