### ISSUE TITLE
When do we subscribe?

### ISSUE THREAD

**Issue by Katydude** [MicrosoftDocs/xamarin-docs#1133]
The examples do not make it clear where to do the subscription. Should this be in the OnCreate method, a constructor, or at some other place in the Activity class? Also, what using statements are needed in order to make this work? Xamarin.Forms only?

The code will compile if placed inside OnCreate. The code will not compile if placed at the top of the class definition but other examples I've seen suggest this is where it should go so I am confused. Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4d80a771-2198-328b-b9fa-fe25f16261cd
* Version Independent ID: be0408fe-d00b-baf6-8a9c-e24659029c4b
* Content: [Xamarin.Forms MessagingCenter - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/messaging-center#using-the-messagingcenter)
* Content Source: [docs/xamarin-forms/app-fundamentals/messaging-center.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/app-fundamentals/messaging-center.md)
* Product: **xamarin**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @Katydude 

Subscribe to the message in the class that needs to know about the message. For more info, see [Communicating Between Loosely Coupled Components](https://docs.microsoft.com/xamarin/xamarin-forms/enterprise-application-patterns/communicating-between-loosely-coupled-components).

**Comment by Katydude** [comment]
Thanks for the link. I don't think you read my question closely enough. (I imagine you have hundreds of these questions to race through every couple of days so it is understandable.)

Obviously, we need to subscribe to the message in the class that needs to receive it. My question was where to put the subscription, in the OnCreate method of the class or somewhere else? Or does it even matter? There is no context for the subscription code block. Thanks.

**Comment by davidbritch** [comment]
Largely, depending on what you're trying to achieve, it doesn't matter. When the message is received, the anonymous method defined by the lambda will be executed, regardless of in which method the `MessagingCenter.Subscribe` statement is.

**Comment by Katydude** [comment]
Gotcha. Well, I tried subscribing at the top of the class (where I would normally put fields, assign constants, etc) but it would not compile there. 

Thanks again.
