### ISSUE TITLE
Xamarin.Tizen, Xamarin.Android & Xamarin.iOS issue with Azure Pipelines and Mobile Center

### ISSUE THREAD

**Issue by rafsanulhasan** [MicrosoftDocs/xamarin-docs#1139]
Hello, 
I, as a full-stack .NET Web Developer, am a big fan of Xamarin as its evolving the cross platform for smart devices in the open source community. In addition to React Native, I really love Building Google's Android (Mobile, tvOS and watchOS), Apple's OSX (macOS, iOS, tvOS and watchOS), Microsoft's Windows (WPF, UWP & Desktop) and other IoT devices including Raspberry Pi. Prior to Xamarin, I used Apache Cordova/Angular/React to build cross platform apps which are very web stack specific. In native app development world, both React Native and Xamarin has become increasingly popular and people are using it to develop native apps. In React Native, I can leverage my existing Web Development skills while in Xamarin I can leverage my existing C# skills plus OOP, implementing design patterns and so on that are generally used in Software Engineering. 

With Azure Mobile Center, Azure DevOps and Azure Pipelines I can manage the process/project management things and build CICD Pipelines to Build, Test, Deploy & Manage Release and Maintenance (crash and other Reports).

I'm writing this to clarify some of my potential misconceptions and ask some important things to figure out. 

First of all, it seems that it is possible to Build, Test & Release Xamarin Mobile Apps in Azure Pipelines. Same thing applies to Mobile Center also. So what the use case of Mobile Center since I can also run and manage these DevOps processes is the Pipelines. Obviously Mobile center has some unique things that does not exists in Mobile Center like Crash Reports, Testing in different platforms, idioms and devices of different sizes.  Apart from testing, my query is what is the use case of **Build process** of Mobile Center then? I can customize my builds in Pipelines while it is not possible in Mobile Center. So why and when should I use the build process in Mobile Center?

Second and the most crucial thing for me is, Can I build watchOS & tvOS (for both Apple's & Google's one) apps built with Xamarin in Pipelines? I've tried and succeeded to Build UWP, Android Mobile, iOS and Web apps in the Pipelines. UWP, Android Mobile and iOS in Mobile Center. It it possible to Build macOS, tvOS, watchOS, Android TV, Android Watch apps for apple in Pipelines/Mobile Center. If yes, would you give me a proper guidance so that I can run the Build process in Pipelines/Mobile Center. If not, how long it will take to include the build process there because it is potentially a very big and usable feature for the Xamarin cross-platform app developers in the community. 

Thirdly, I found that it also supports developing Samsung's Tizen apps in Xamarin. is it possible to Build Tizen apps in Pipelines/Mobile Center?

Last but not the least, I discovered that Xamarin supports developing apps for Linux also with GTK in Mono. Is it possible to Build these apps in Pipelines/Mobile Center.

To summarize, I'm listing my questions in bullet format below:

1. Why and when should I use the **"Build Process"** in Mobile Center along with Azure Pipelines?
2. Is it possible to **Build _tvOS_, _watchOS_** (_Android_ & _Apple_) apps in Pipelines/Mobile Center. 
    - [ ] **Azure Pipelines**
       - [ ] Android Watch with **Xamarin** is available
       - [ ] Android TV with **Xamarin**
       - [ ] Apple Watch with **Xamarin**
       - [ ] Apple TV with **Xamarin**
    - [ ] **Mobile Center**
       - [x] Android Watch with **Xamarin** is available
       - [ ] Android TV with **Xamarin**
       - [ ] Apple Watch with **Xamarin**
       - [ ] Apple TV with **Xamarin**
3. Is it possible to **Build _macOS_** apps in Pipelines/Mobile Center. 
    - [ ] **Azure Pipelines**
       - [ ] macOS apps with **Xamarin**
    - [ ] **Mobile Center**
       - [x] macOS apps with **Swift** is available
       - [ ] macOS apps with **Xamarin**
4. Is it possible to **Build and Test _Tizen_** apps in Pipelines/Mobile Center. 
    - [ ] **Azure Pipelines**
       - [ ] Mobile Apps
       - [ ] TV apps
       - [ ] Watch apps
    - [ ] **Mobile Center**
       - [ ] Mobile Apps
       - [ ] TV apps
       - [ ] Watch apps
5. Is it possible to **Build _GTK_** apps for **Linux** in Pipelines/Mobile Center. 
    - [ ] **Azure Pipelines**
    - [ ] **Mobile Center**

**If yes how? (I found macOS apps built with swift can be built in Mobile Center)**
**If no, how long should we wait for this feature**
* **NB** Please use the checkbox if your answer is yes

I don't know if this is the right place to ask these questions. If not I really am sorry for that. 

Thanks in advance.
Rafsanul Hasan
MCP, MCTS

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bf0400c4-a6cd-6883-6c17-89c83d7930d3
* Version Independent ID: 02e3e10a-dff0-cf2c-0b1f-26e5d4a7ddca
* Content: [Introduction to Continuous Integration with Xamarin - Xamarin](https://docs.microsoft.com/en-us/xamarin/tools/ci/)
* Content Source: [docs/tools/ci/index.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/tools/ci/index.md)
* Product: **xamarin**
* GitHub Login: @lobrien
* Microsoft Alias: **laobri**

**Comment by conceptdev** [comment]
These are questions for the App Center and Azure DevOps teams. 

App Center incorporate the Intercom feedback system (it appears on every page when logged in to https://github.com/MicrosoftDocs/xamarin-docs-pr/pull/758) - that would be one place to ask. Some of those questions might also be answered in the [App Center docs](https://docs.microsoft.com/appcenter).

For Azure Pipelines, start with [their docs](https://docs.microsoft.com/azure/devops/pipelines/).
