### ISSUE TITLE
ConfigureAuth method missing??

### ISSUE THREAD

**Issue by NandC** [MicrosoftDocs/xamarin-docs#114]
In the mobile solution ConfigureAuth method could not be located

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5d805ca5-97c4-23e4-b635-9de16b6d7f78
* Version Independent ID: ec5b37f1-1bd1-c66e-6461-57c104ed543a
* Content: [Authentication and Authorization - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/enterprise-application-patterns/authentication-and-authorization)
* Content Source: [docs/xamarin-forms/enterprise-application-patterns/authentication-and-authorization.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/enterprise-application-patterns/authentication-and-authorization.md)
* Service: **unspecified**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by conceptdev** [comment]
Thanks @NandC, the mobile solution has had a [number of changes](https://github.com/dotnet-architecture/eShopOnContainers/commits/dev/src/Mobile/eShopOnContainers) since this article was written. We will review and update the page as required.
