### ISSUE TITLE
This document states that Location Updates needs to be enabled for CloudKit, but it does not.

### ISSUE THREAD

**Issue by johnnysbug** [MicrosoftDocs/xamarin-docs#1140]
In this document, it specifically states that Location updates need to be enabled in the Info.plist file in order to enable CloudKit. This is not the case, and if an implementor is not using any type of location services in their app, enabling Location updates will result in an AppStore rejection. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 178a563e-59db-62ce-4f8c-b94f2618daca
* Version Independent ID: 313d4e1a-5d5b-fe32-a4b6-c7025d406f15
* Content: [CloudKit in Xamarin.iOS - Xamarin](https://docs.microsoft.com/en-us/xamarin/ios/data-cloud/intro-to-cloudkit)
* Content Source: [docs/ios/data-cloud/intro-to-cloudkit.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/ios/data-cloud/intro-to-cloudkit.md)
* Product: **xamarin**
* GitHub Login: @lobrien
* Microsoft Alias: **laobri**

**Comment by conceptdev** [comment]
Hi @johnnysbug. Thanks for your feedback.

The instructions are very unclear - the advice given regarding the **Location updates** permission is specific to the _CloudKitAtlas_ sample that is being discussed later in the page. In [step 4](https://docs.microsoft.com/en-us/xamarin/ios/data-cloud/intro-to-cloudkit#supported-predicates) it uses `CLLocation`. 

You are correct that it is presented as a requirement for CloudKit use, which is incorrect. We'll update the page to clarify this.

**Comment by johnnysbug** [comment]
Thanks for the prompt response, @conceptdev!

**Comment by conceptdev** [comment]
Sorry this wasn't actually closed sooner. Doc has been tweaked to avoid confusion.
