### ISSUE TITLE
Dead link

### ISSUE THREAD

**Issue by aldrashan** [MicrosoftDocs/xamarin-docs#1142]
The related links "Distributing Enterprise Apps for iOS Devices" link doesn't work anymore.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0f26ad57-ecf3-c284-efc8-310c6560cf3b
* Version Independent ID: 38d89ef9-cac9-b1ce-1d1d-49688109dc8c
* Content: [IPA Support in Xamarin.iOS - Xamarin](https://docs.microsoft.com/en-us/xamarin/ios/deploy-test/app-distribution/ipa-support?tabs=macos#customizing-the-ipa-location)
* Content Source: [docs/ios/deploy-test/app-distribution/ipa-support.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/ios/deploy-test/app-distribution/ipa-support.md)
* Product: **xamarin**
* GitHub Login: @lobrien
* Microsoft Alias: **laobri**

**Comment by conceptdev** [comment]
Thanks for letting us know, updated links are being published now.
