### ISSUE TITLE
Xamarin Forms Previewer for WPF platform?

### ISSUE THREAD

**Issue by GregaMohorko** [MicrosoftDocs/xamarin-docs#1145]
Currently, the only supported platforms in the Xamarin Forms Previewer are Android and iOS.
I strongly believe that supporting the WPF platform would be a really good thing. It would probably work way faster than other platforms.

**Comment by conceptdev** [comment]
Thanks for your feedback @GregaMohorko. You can also provide feedback directly to the Xamarin.Forms product team on the [open source Xamarin.Forms repo](https://github.com/xamarin/Xamarin.Forms).
