### ISSUE TITLE
DI containers and IoC principles

### ISSUE THREAD

**Issue by rafsanulhasan** [MicrosoftDocs/xamarin-docs#1146]
Hello,
I found Prism (with Unity DI container or others) more useful than that of DependencyService in Xamarin because it supports applying IoC principles such as constructor injection. Though, the current built in one is productive, it would be nice if it had a capability of doing such things. I felt the essence of this because it provides a number of flexibility including loosely coupling, test-ability and so on. I can use prism with unity or anything else, but I (and probably other developers in the community out there) would love Xamarin more than ever before if such functionality is incorporated in Xamarin by default because there might be someone out there like me who don't want to rely on third-party libraries rather they rely on Xamarin itself. Additionally it would be great if it has such functionality to integrate with third party libraries for DI containers only like the DI container ..NET Core uses by default in ASP.NET Core project.

Thanks in advance.

**Comment by davidbritch** [comment]
Hi @rafsanulhasan 

Thanks for the feedback. This repo is purely for logging issues with the Xamarin documentation. The issue you've raised is more a conversation for the engineers, so please use the [engineering repo](https://github.com/xamarin/Xamarin.Forms/).
