### ISSUE TITLE
Phoneword Project Error on MainPage.Xaml.cs

### ISSUE THREAD

**Issue by keyus4** [MicrosoftDocs/xamarin-docs#1147]
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0103	The name 'phoneNumberText' does not exist in the current context	Phoneword	C:\Users\XXX\source\repos\Phoneword\Phoneword\Phoneword\MainPage.xaml.cs	17	Active

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0103	The name 'callButton' does not exist in the current context	Phoneword	C:\Users\XXX\source\repos\Phoneword\Phoneword\Phoneword\MainPage.xaml.cs	20	Active

**Comment by davidbritch** [comment]
Hi @keyus4 

I built the entire xamarin-forms-samples repo last Friday, on iOS, Android, and UWP, and can confirm that there were zero build failures.

I've just double checked by building the Phoneword project in both VS2017 (15.9) and VSMac and it builds correctly in both IDEs.
