### ISSUE TITLE
good article with nice example

### ISSUE THREAD

**Issue by javazanon** [MicrosoftDocs/xamarin-docs#115]
good article with nice example

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7eeb0e65-143b-0f5e-a8fb-c75309689338
* Version Independent ID: 6b984264-a950-4310-483f-99f908b0a8b0
* Content: [Images - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/images?tabs=vswin)
* Content Source: [docs/xamarin-forms/user-interface/images.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/images.md)
* Service: **unspecified**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by asb3993** [comment]
Hi @javazanon, Thank you! We're really glad that you like the article and appreciate your kind words.
