### ISSUE TITLE
Read content of the sqlite db from visual studio

### ISSUE THREAD

**Issue by BrayanKhosravian** [MicrosoftDocs/xamarin-docs#1151]
Is there a way to read the content of the Sqlite database from visual studio and/or manually insert entries or delete them without running the application?

Sincerely

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3ab6098a-39c7-151f-124b-f88aa62c4659
* Version Independent ID: dc27c1e4-ff12-c1af-646a-c2617def0bcd
* Content: [Xamarin.Forms Local Databases - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/databases)
* Content Source: [docs/xamarin-forms/app-fundamentals/databases.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/app-fundamentals/databases.md)
* Product: **xamarin**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @BrayanKhosravian 

It can be done but it's not necessarily a quick solution.

https://forums.xamarin.com/discussion/93238/is-it-possible-to-view-the-contents-of-sqlite-database

https://stackoverflow.com/questions/33448255/how-to-browse-sqlite-data-in-xamarin
