### ISSUE TITLE
Page needs updating for ImageButton and any other new views

### ISSUE THREAD

**Issue by johnshardman** [MicrosoftDocs/xamarin-docs#1158]
Page at https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/custom-renderer/renderers needs updating for new ImageButton and any other new views.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cfee594b-8ecc-0d4d-9384-e4afe792b3dd
* Version Independent ID: 9957d9e1-1ebc-aadb-90bb-5e80b595bade
* Content: [Renderer Base Classes and Native Controls - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/custom-renderer/renderers)
* Content Source: [docs/xamarin-forms/app-fundamentals/custom-renderer/renderers.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/app-fundamentals/custom-renderer/renderers.md)
* Product: **xamarin**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @johnshardman 

This has already been done. It just hasn't been published yet. It'll go out any day now.
