### ISSUE TITLE
Public i Container insted of private

### ISSUE THREAD

**Issue by BrayanKhosravian** [MicrosoftDocs/xamarin-docs#1159]
How would i resolve dependencies within other classes when the icontainer at the composition root saccess modified as private?

Shouldn't it be modified as public? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 496aefc1-60e7-3484-12d1-ba383cfc099b
* Version Independent ID: 35133eba-8bc2-a54e-b341-d873f9a3c468
* Content: [Dependency Injection - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/enterprise-application-patterns/dependency-injection)
* Content Source: [docs/xamarin-forms/enterprise-application-patterns/dependency-injection.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/enterprise-application-patterns/dependency-injection.md)
* Product: **xamarin**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @BrayanKhosravian 

If you look at the [source code](https://github.com/dotnet-architecture/eShopOnContainers/blob/dev/src/Mobile/eShopOnContainers/eShopOnContainers.Core/ViewModels/Base/ViewModelLocator.cs) for the `ViewModelLocator` class you'll see that while the container is private, the class exposes public `Register` and `Resolve` methods that can be consumed as appropriate from other classes.
