### ISSUE TITLE
How to change size of rectangle by touch and drag?

### ISSUE THREAD

**Issue by nguyenthanhliemfc** [MicrosoftDocs/xamarin-docs#116]
First, I want to send you Thank you because your SkiaSharp help me easy drawing in X.forms!
Then, How to change size of rectangle by touch and drag on the corner of that rectangle?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e94288f0-f661-6a8c-bf43-01332272a777
* Version Independent ID: 5bd102bf-ffee-c2f9-4abc-27f14111bb21
* Content: [Using SkiaSharp in Xamarin.Forms - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/graphics/skiasharp/#related-links)
* Content Source: [docs/xamarin-forms/user-interface/graphics/skiasharp/index.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/graphics/skiasharp/index.md)
* Service: **unspecified**
* GitHub Login: @charlespetzold
* Microsoft Alias: **chape**

**Comment by charlespetzold** [comment]
A new section has been added to the Touch Manipulations page that describes how to scale a rectangle by dragging a corner:

https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/graphics/skiasharp/transforms/touch#single-finger-scaling
