### ISSUE TITLE
Confusing documentation on property value enumeration about XAML

### ISSUE THREAD

**Issue by Weldryn** [MicrosoftDocs/xamarin-docs#1166]
For example:

&gt;The Direction property is of type FlexDirection, an enumeration with four members:
&gt;
&gt;    `Column`
    `ColumnReverse` (or "column-reverse" in XAML)
    `Row`, the default
    `RowReverse` (or "row-reverse" in XAML)

`column-reverse` or `row-reverse` is actually not XAML, it is CSS, like in:

&gt;    .login-container {
    background-color: #803A3F44;
    width:300;
    height:380;
    flex-direction: column-reverse;
    }

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b954b795-b38e-61ff-3ba1-26a0623b97e6
* Version Independent ID: 65795b50-24d3-1997-038e-ffdb609eb20b
* Content: [The Xamarin.Forms FlexLayout - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/layouts/flex-layout#the-bindable-properties-in-detail)
* Content Source: [docs/xamarin-forms/user-interface/layouts/flex-layout.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/layouts/flex-layout.md)
* Product: **xamarin**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @weldryn,

Both you and the doc are correct! "column-reverse" is CSS, but if you look at the paragraph after the bullets it explains that "column-reverse" is CSS, but can also be used in XAML due to the `FlexDirectionTypeConverter` class. I've tried it myself and can confirm it works.
