### ISSUE TITLE
Bug in code

### ISSUE THREAD

**Issue by thaneplummer** [MicrosoftDocs/xamarin-docs#1168]
The AppDelegate has a bug; the TabController instance should not be local, but should be the class instance.

// WRONG - code in this page
var tabController = new TabController ();

// RIGHT - please update the page as below.
tabController = new TabController ();

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8853aece-5bbb-6121-ce6d-f600719ad820
* Version Independent ID: 8037b07e-5bdd-390c-e3be-b3c9233d5249
* Content: [Tab Bars and Tab Bar Controllers in Xamarin.iOS - Xamarin](https://docs.microsoft.com/en-us/xamarin/ios/user-interface/controls/creating-tabbed-applications)
* Content Source: [docs/ios/user-interface/controls/creating-tabbed-applications.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/ios/user-interface/controls/creating-tabbed-applications.md)
* Product: **xamarin**
* GitHub Login: @lobrien
* Microsoft Alias: **laobri**

**Comment by conceptdev** [comment]
Fixed thanks to @james-alt !
