### ISSUE TITLE
Small Typo

### ISSUE THREAD

**Issue by codebeaulieu** [MicrosoftDocs/xamarin-docs#1171]
Step 1. stroyboard should be storyboard

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e8f475f5-a857-b12e-b0b9-e5d0a129f427
* Version Independent ID: 4563aa33-d9a4-6d3f-a48a-eb053f266284
* Content: [.storyboard/.xib-less user interface design in Xamarin.Mac - Xamarin](https://docs.microsoft.com/en-us/xamarin/mac/app-fundamentals/xibless-ui)
* Content Source: [docs/mac/app-fundamentals/xibless-ui.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/mac/app-fundamentals/xibless-ui.md)
* Product: **xamarin**
* GitHub Login: @lobrien
* Microsoft Alias: **laobri**

**Comment by conceptdev** [comment]
fixed in https://github.com/MicrosoftDocs/xamarin-docs/pull/1176
