### ISSUE TITLE
Consistency

### ISSUE THREAD

**Issue by zopagaduanjr** [MicrosoftDocs/xamarin-docs#1172]
In step 10, it says to add a new class file named PhoneTranslator, but in step 11, the class name now becomes PhonewordTranslator. Might have complications for some people doing this step by step without knowing classes.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2de3e72c-8948-4dd5-e37f-9cf81e62c127
* Version Independent ID: 7b7c5c7f-4102-8e91-fbe6-7d21fcc8f5be
* Content: [Xamarin.Forms Quickstart - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/get-started/hello-xamarin-forms/quickstart?pivots=windows)
* Content Source: [docs/xamarin-forms/get-started/hello-xamarin-forms/quickstart.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/get-started/hello-xamarin-forms/quickstart.md)
* Product: **xamarin**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @zopagaduanjr,

I'm going to leave this as it is. While there is a discrepancy here, it's only minor and as long as users follow the steps, the solution will build. In addition, this quick start will soon be replaced with a new one.
