### ISSUE TITLE
UI  Bug with "Choose your development environment" section.

### ISSUE THREAD

**Issue by denis-panov** [MicrosoftDocs/xamarin-docs#1175]
I see html tags in buttons when location is "ru-ru":
<img width="1392" alt="screenshot 2018-11-26 at 13 12 13" src="https://user-images.githubusercontent.com/40772628/49007938-b71ae800-f17d-11e8-9943-a8f36bb02862.png">

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b2f6b353-936e-2536-37cb-b8190aea7743
* Version Independent ID: 4f27ec32-a6f7-3de5-2635-87bacf04e724
* Content: [Automating Xamarin.Forms Testing with App Center - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/deploy-test/uitest-and-test-cloud?pivots=windows)
* Content Source: [docs/xamarin-forms/deploy-test/uitest-and-test-cloud.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/deploy-test/uitest-and-test-cloud.md)
* Product: **xamarin**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by conceptdev** [comment]
@denis-panov thank you for your feedback. This appears to be affecting all localized versions of our content. We are investigating!

**Comment by CeciAc** [comment]
Hi team, 
this is fixed, you can close this issue

Kind regards,
#PleaseClose

**Comment by conceptdev** [comment]
Thanks @CeciAc and @denis-panov. The engineering team was able to fix it the same day that it was reported!
