### ISSUE TITLE
Can't wrap Binding flag inside Label.Text 

### ISSUE THREAD

**Issue by ColeXm** [MicrosoftDocs/xamarin-docs#1179]
Error was thrown when i write 
&lt;Label&gt;
   &lt;Label.Text&gt;
        &lt;Binding Path="Blue"

It says "Property Text does not support values of type 'Binding' "  even though i downgrade xamarin.forms from 3.4 to 2.5 .

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d0407ea7-37f7-c702-cc25-08ac66435563
* Version Independent ID: 3217006f-30cc-70f6-23a8-b93bda13f108
* Content: [Xamarin.Forms Binding Value Converters - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/data-binding/converters)
* Content Source: [docs/xamarin-forms/app-fundamentals/data-binding/converters.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/app-fundamentals/data-binding/converters.md)
* Product: **xamarin**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by samhouts** [comment]
This issue was moved to xamarin/Xamarin.Forms#4572
