### ISSUE TITLE
Page does not explain what the title says

### ISSUE THREAD

**Issue by johnshardman** [MicrosoftDocs/xamarin-docs#118]
The title of this page is "How can I downgrade Xcode?". The body of the page says where to find the downloads for the different XCode versions, but does not say how to perform the downgrade.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0778731c-1469-1d5d-8266-4766d408d151
* Version Independent ID: 6a0a36d3-9be7-c298-866e-d2d13c7ea2bf
* Content: [How can I downgrade Xcode? - Xamarin](https://docs.microsoft.com/en-us/xamarin/ios/troubleshooting/questions/downgrade-xcode)
* Content Source: [docs/ios/troubleshooting/questions/downgrade-xcode.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/ios/troubleshooting/questions/downgrade-xcode.md)
* Service: **unspecified**
* GitHub Login: @bradumbaugh
* Microsoft Alias: **brumbaug**

**Comment by bradumbaugh** [comment]
Hi @johnshardman - thanks for calling out the inconsistency. I went ahead and renamed the document so that it better reflects the content.
