### ISSUE TITLE
Focused not firing keyboard

### ISSUE THREAD

**Issue by achrafbenalaya** [MicrosoftDocs/xamarin-docs#1180]
In this example , the keyboard is not firing only after focusing 2 time on entry , I tried this a lot and seems there is an issue right here . 
&lt;VisualState x:Name="Focused"&gt;
                                &lt;VisualState.Setters&gt;
                                    &lt;Setter Property="FontSize" Value="36" /&gt;
                                    &lt;Setter Property="BackgroundColor" Value="Lime" /&gt;
                                &lt;/VisualState.Setters&gt;
                            &lt;/VisualState&gt;

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b744a13f-16ad-4f35-cdf2-bdfd6fa90df1
* Version Independent ID: 7a08549b-07a5-085b-0c93-255d9e84d7a3
* Content: [The Xamarin.Forms Visual State Manager - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/visual-state-manager)
* Content Source: [docs/xamarin-forms/user-interface/visual-state-manager.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/visual-state-manager.md)
* Product: **xamarin**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by samhouts** [comment]
This issue was moved to xamarin/Xamarin.Forms#4573
