### ISSUE TITLE
Adding Entitlements.plist to Custom Entitlements 

### ISSUE THREAD

**Issue by ChrisAllisonMalta** [MicrosoftDocs/xamarin-docs#1183]
When I add this, as per above I get a “I can’t find a proviosing profile” build error when trying to run in the iOS simulator 

But when I don’t have it it says I don’t have Entitlements to add to the keychain

Catch 22 to debug locally! 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: da75050f-bfda-4792-40d9-b9a25d649d3e
* Version Independent ID: 5c44f996-765b-f6e4-c807-9446c534d50b
* Content: [Xamarin.Essentials: Secure Storage - Xamarin](https://docs.microsoft.com/en-us/xamarin/essentials/secure-storage?context=xamarin%2Fxamarin-forms&tabs=ios)
* Content Source: [docs/essentials/secure-storage.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/essentials/secure-storage.md)
* Product: **xamarin**
* GitHub Login: @jamesmontemagno
* Microsoft Alias: **jamont**

**Comment by iMrTidy** [comment]
I have got the same issue.

**Comment by ChrisAllisonMalta** [comment]
it works when I have a apple developer profile set up in VS to test on device

**Comment by iMrTidy** [comment]
I guess it works this way but what if I don't have a developer profile at the moment but still would need to test?

**Comment by conceptdev** [comment]
Please read our [doc on free provisioning](https://docs.microsoft.com/xamarin/ios/get-started/installation/device-provisioning/free-provisioning) - there are a few limitations listed but in general it works the same as a paid account. This [list of supported capabilities on Apple's site](https://help.apple.com/developer-account/#/dev21218dfd6) shows that the keychain capability is supported in free accounts.

**Comment by SelectMany** [comment]
So to be clear if I want to use the Secure Storage and IOS simulator I have to setup provisoning? Thanks
