### ISSUE TITLE
StyleClass?

### ISSUE THREAD

**Issue by grahampcharles** [MicrosoftDocs/xamarin-docs#1184]
You mention StyleClass only in the summary -- not anywhere else. Is it out of date? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f28d1a17-189a-7791-b44b-b84e94d8f7b6
* Version Independent ID: 3ad8e76d-eaa6-18f9-c121-9cf4c2c1720f
* Content: [Creating a Custom Xamarin.Forms Theme - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/themes/custom)
* Content Source: [docs/xamarin-forms/user-interface/themes/custom.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/themes/custom.md)
* Product: **xamarin**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @grahampcharles 

No - `StyleClass` is valid and useful. However, for various reason, it doesn't get much of a mention in the docs. I've created a backlog issue to rectify this.

Thanks for raising the issue.
