### ISSUE TITLE
error in sample code

### ISSUE THREAD

**Issue by grahampcharles** [MicrosoftDocs/xamarin-docs#1186]
I used your sample code *exactly* as written, and I get a compile error at ` &lt;StyleSheet Source="/Assets/Styles.css" /&gt;`: Source only accepts Relative URLs. To get this code to work, I had to use dot syntax: ` &lt;StyleSheet Source="./Assets/Styles.css" /&gt;`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7a410a97-17d3-aff7-c875-ee9291658957
* Version Independent ID: f415dc53-c941-b0e5-5823-9bafa53f0d9a
* Content: [Styling Xamarin.Forms Apps using Cascading Style Sheets (CSS) - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/styles/css/index)
* Content Source: [docs/xamarin-forms/user-interface/styles/css/index.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/styles/css/index.md)
* Product: **xamarin**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by conceptdev** [comment]
@grahampcharles what platform and version were you using?

The complete sample is [available for download](https://developer.xamarin.com/samples/xamarin-forms/UserInterface/Styles/MonkeyAppCSS/) (and also the [source on GitHub](https://github.com/xamarin/xamarin-forms-samples/blob/master/UserInterface/Styles/MonkeyAppCSS/MonkeyApp/MonkeyApp/App.xaml#L6)). I can compile and run it with both Xamarin.Forms 3.3 and 3.4 in Visual Studio for Mac, and run on iOS and Android.
