### ISSUE TITLE
The plist images

### ISSUE THREAD

**Issue by cyberjetx** [MicrosoftDocs/xamarin-docs#1187]
These images do not represent the current state.

**Comment by conceptdev** [comment]
@cyberjetx can you point to which pages you noticed this issue? Thanks.

**Comment by cyberjetx** [comment]
Sure and sorry,  I thought the link from the page carried over when you clicked it.  

https://docs.microsoft.com/en-us/xamarin/ios/deploy-test/provisioning/entitlements?tabs=windows 
Specifically:
![](https://docs.microsoft.com/en-us/xamarin/ios/deploy-test/provisioning/entitlements-images/servicevs02.png)
and
![](https://docs.microsoft.com/en-us/xamarin/ios/deploy-test/provisioning/entitlements-images/servicevs01.png)

**Comment by conceptdev** [comment]
Thanks, we'll take a look.

**Comment by conceptdev** [comment]
Updated today (finally).
