### ISSUE TITLE
Unregister a device

### ISSUE THREAD

**Issue by nhwilly** [MicrosoftDocs/xamarin-docs#119]
I would love to see the example extended to include how to unregister a device.  Not really sure where to put it, how to trigger it and so on.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8d9bfb2a-2e5d-d505-337f-919251a85de3
* Version Independent ID: 695bff64-ae87-8c0f-5616-20b67893fdf0
* Content: [Remote Notifications with Firebase Cloud Messaging - Xamarin](https://docs.microsoft.com/en-us/xamarin/android/data-cloud/google-messaging/remote-notifications-with-fcm?tabs=vswin)
* Content Source: [docs/android/data-cloud/google-messaging/remote-notifications-with-fcm.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/android/data-cloud/google-messaging/remote-notifications-with-fcm.md)
* Service: **unspecified**
* GitHub Login: @mgmclemore
* Microsoft Alias: **mamcle**

**Comment by mgmclemore** [comment]
Hi @nhwilly, thank you for the suggestion!  I'll make note to have this topic expanded to cover unregistering from FCM.
