### ISSUE TITLE
Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by coeus89** [MicrosoftDocs/xamarin-docs#1191]
![2018-11-30 8](https://user-images.githubusercontent.com/18616316/49315009-39771500-f4ba-11e8-8981-ce55abe753e0.png)

Hi,

When i go through all of the steps for the Phoneword project, after I click through the warning about the deployment errors and " the property Default is set more than once, I get another dialog with the warning "Object reference not set to an instance of an object". This is displayed in the picture that i attached. It then fails to run the Phoneword.Android example. This does not appear in the errors list. The build works fine but the run fails. The UWP version build and run both work fine. Can you investigate and get back to me?

Edit: I went and downloaded the phoneword project from here and ran into the same issue.

**Comment by coeus89** [comment]
I am using windows 10 pro version 1809 and visual studio 2017 version 15.9.1

**Comment by coeus89** [comment]
I will look at it tonight and see. What is commonly used in terms of android emulation? There are a lot of options when installing different parts of visual studio and it is possible i don't have a certain emulation piece installed.

**Comment by conceptdev** [comment]
This is covered in our [Android emulator docs](https://docs.microsoft.com/en-us/xamarin/android/get-started/installation/android-emulator/).

**Comment by coeus89** [comment]
It appears that the issue was that i didn't have the Hyper-V powered emulator installed. I did that and then used one of the wizards to create an android 8.1 VM and then deployed the project to it from visual studio. That appears to have worked.

**Comment by coeus89** [comment]
Thank you for your quick responses :)

**Comment by conceptdev** [comment]
Glad you got it working!
