### ISSUE TITLE
ImageButton spelling error

### ISSUE THREAD

**Issue by RikDriever** [MicrosoftDocs/xamarin-docs#1194]
The title says ImageButon (with a single T)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8fdac83c-6d89-7423-b09c-d9a8c7e77d92
* Version Independent ID: 1888bc98-338a-dba3-58bd-96023925b5a7
* Content: [Xamarin.Forms User Interface Views - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/)
* Content Source: [docs/xamarin-forms/user-interface/index.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/index.md)
* Product: **xamarin**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @RikDriever 

Thanks for pointing out the typo. It's fixed in a PR that will go out later.
