### ISSUE TITLE
Picker View invalid selection iOS 12

### ISSUE THREAD

**Issue by faranrasheed** [MicrosoftDocs/xamarin-docs#1196]
Below is the sample code already shared in docs.

```
 <Picker.ItemsSource>
    <x:Array Type="{x:Type x:String}">
      <x:String>Baboon</x:String>
      <x:String>Capuchin Monkey</x:String>
      <x:String>Blue Monkey</x:String>
      <x:String>Squirrel Monkey</x:String>
      <x:String>Golden Lion Tamarin</x:String>
      <x:String>Howler Monkey</x:String>
      <x:String>Japanese Macaque</x:String>
    </x:Array>
  </Picker.ItemsSource>
</Picker>
```

When running this code in iOS 12 simulator, it works but when you tap done button, selected item is changed and is assigned to 4th item in the list from the selected item. 

For Example, if you select Baboon from above list and tap done button, selected item will be changed to Golden Lion Tamarin.

I am not sure if the issue is only related iOS 12 or not. I am downloading previous version simulators to see.

Thanks,

**Comment by conceptdev** [comment]
@faranrasheed can you also provide links to the docs/samples you are referring to? Thanks.

**Comment by faranrasheed** [comment]
> @faranrasheed can you also provide links to the docs/samples you are referring to? Thanks.

Here is the link: [https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/picker/populating-itemssource](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/picker/populating-itemssource)

**Comment by faranrasheed** [comment]
The issue was with simulator.
For details -> [View Stackoverflow question](https://stackoverflow.com/questions/53611105/xamarin-picker-view-invalid-selection-ios-12/53630821#53630821)
