### ISSUE TITLE
What Next?

### ISSUE THREAD

**Issue by PatrickRyder** [MicrosoftDocs/xamarin-docs#1197]
This page seems to cover what I need. My application required audio and Bluetooth background support. This page tells me how to request these.  But how do I actually write code to work with this?  There is no link to what I do next.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 281b4ed1-c53d-6b67-432c-f1e213d869be
* Version Independent ID: 3600b602-cf27-dc3b-efd2-3c179942bc3e
* Content: [Registering Xamarin.iOS Apps to Run in the Background - Xamarin](https://docs.microsoft.com/en-us/xamarin/ios/app-fundamentals/backgrounding/ios-backgrounding-techniques/registering-applications-to-run-in-background)
* Content Source: [docs/ios/app-fundamentals/backgrounding/ios-backgrounding-techniques/registering-applications-to-run-in-background.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/ios/app-fundamentals/backgrounding/ios-backgrounding-techniques/registering-applications-to-run-in-background.md)
* Product: **xamarin**
* GitHub Login: @lobrien
* Microsoft Alias: **laobri**

**Comment by conceptdev** [comment]
Hi @PatrickRyder, the iOS SDK is very extensive, with a huge number of APIs for building iOS apps. Xamarin provides C# access to all these SDKs, however we are not able to build sample apps or documentation for every scenario. We do not currently have any instructions for using audio with bluetooth, however you can find some audio-related samples here https://github.com/xamarin/ios-samples
Alternatively, you may find an Objective-C or Swift sample that you can port to C#.
