### ISSUE TITLE
Please support Vietnamese docs!

### ISSUE THREAD

**Issue by nguyenthanhliemfc** [MicrosoftDocs/xamarin-docs#12]
Thank you for your document. But my English is very bad I have use Bing, Google Translate to read the document. But have a lot of words  Translate tool can not translate exactly that word mean in development. So I can not complete understand all docs. Please support Vietnamese. Thank you!

---
#### Chi tiết tài liệu

⚠ *Không chỉnh sửa phần này. Điều này là bắt buộc cho docs.microsoft.com ➟ Vấn đề khi liên kết GitHub.*

* ID: 90eadee6-b0e8-c89f-7d7d-d3d1485ef855
* Version Independent ID: 634488c8-b12d-21ae-0d9f-c4730ce9d316
* Content: [Getting Started with Xamarin.Forms - Xamarin | Microsoft Docs](https://docs.microsoft.com/vi-vn/xamarin/xamarin-forms/get-started/index)
* Content Source: [docs/xamarin-forms/get-started/index.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/get-started/index.md)
* Service: **unspecified**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by conceptdev** [comment]
Thank you for your suggestion.

We will consider Vietnamese language translation for a future release.
