### ISSUE TITLE
How to take a photo using CustomRendererView sample?

### ISSUE THREAD

**Issue by nguyenthanhliemfc** [MicrosoftDocs/xamarin-docs#120]
Hi! I'm follow CustomRendererView sample in my app. Now I can see camera preview, How to take a photo using this sample? (Take a picture from camera preview programmatically)
Note: I DO NOT use MediaPlugin because it will open a camera UI, it break my app design concept!

---
#### Chi tiết tài liệu

⚠ *Không chỉnh sửa phần này. Điều này là bắt buộc cho docs.microsoft.com ➟ Vấn đề khi liên kết GitHub.*

* ID: e3b172d5-2dc1-88e7-ca23-96e87ae24a42
* Version Independent ID: 1ca93300-738f-4af7-b47c-0e170b7205a4
* Content: [Implementing a View - Xamarin](https://docs.microsoft.com/vi-vn/xamarin/xamarin-forms/app-fundamentals/custom-renderer/view)
* Content Source: [docs/xamarin-forms/app-fundamentals/custom-renderer/view.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/app-fundamentals/custom-renderer/view.md)
* Service: **unspecified**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by conceptdev** [comment]
Hi @nguyenthanhliemfc - the purpose of this doc is merely to demonstrate the concepts for creating custom renderers. We cannot offer specific answers or support via this site.

You might find the source code for the MediaPlugin useful: https://github.com/jamesmontemagno/MediaPlugin/blob/master/src/Media.Plugin.iOS/MediaImplementation.cs#L107

You can also visit https://www.visualstudio.com/vs/support/ for available support options.

**Comment by nguyenthanhliemfc** [comment]
Thank you!
