### ISSUE TITLE
Please include supported Xamarin Forms Version for your notes in the future

### ISSUE THREAD

**Issue by sam9116** [MicrosoftDocs/xamarin-docs#1204]
overriding GetIconDrawable is only available for Xamarin.Forms 3.4.0 and up.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0c81c589-e81e-d98c-9656-695a3520a12d
* Version Independent ID: c235f6f9-47ce-15f3-b4da-cb12e219df92
* Content: [Xamarin.Forms Tabbed Page - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/navigation/tabbed-page)
* Content Source: [docs/xamarin-forms/app-fundamentals/navigation/tabbed-page.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/app-fundamentals/navigation/tabbed-page.md)
* Product: **xamarin**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @sam9116 

Thanks for the feedback. The docs tend to reflect the latest stable release of Xamarin.Forms. Previous experience has shown that the text becomes quite unwieldy when it states what release the feature was introduced in.
