### ISSUE TITLE
Offline Availability

### ISSUE THREAD

**Issue by Emmanuel-GD** [MicrosoftDocs/xamarin-docs#1206]
I am using this documentation and it is very helpful but what about making it available in visual studio as offline book? So that anyone offline will have access to it from help viewer.
Thank You.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5823a3fa-87be-0b27-155b-b44130c67e84
* Version Independent ID: c90633f5-22b9-f7dd-fd08-c9affc251dd4
* Content: [Splash Screen - Xamarin](https://docs.microsoft.com/en-us/xamarin/android
* Content Source: [docs/android/user-interface/splash-screen.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/android/
* Product: **xamarin**
* GitHub Login: @conceptdev
* Microsoft Alias: **crdun**

**Comment by conceptdev** [comment]
Thanks for the suggestion @Emmanuel-GD. 

While these docs are not currently available in the Visual Studio offline books, did you know that it is possible to download a PDF version? Look for the **Download PDF** link at the bottom of the page under the navigation tree:

![download-pdf](https://user-images.githubusercontent.com/199373/49606399-221baa00-f948-11e8-8308-af147a557a6c.png)

**Comment by Emmanuel-GD** [comment]
Thanks. And is there anything planned taking the documentation to visual studio offline books?

**Comment by conceptdev** [comment]
We have no plans for the offline books at this time, but your request is helpful for us in future planning.
