### ISSUE TITLE
Touch with Master/Detail View in iOS only

### ISSUE THREAD

**Issue by tpsands** [MicrosoftDocs/xamarin-docs#1207]
When in iOS dragging things within a Detail page of a Master/Detail page, the touch event is intercepted by the gesture to drag the detail page to the side and show the Master page - the TouchesEnded never fires. This does not behave this way in Android or UWP. To combat this, I overrode OnAppearing on the detail page, found the master page and set IsGestureEnabled to false. I didn't do this on the master page itself because I still wanted that functionality there.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 908530d1-f21d-5532-c530-1727e3356b64
* Version Independent ID: e01f2543-3b7d-0b60-8d79-c012feab83de
* Content: [Invoking Events from Effects - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/effects/touch-tracking)
* Content Source: [docs/xamarin-forms/app-fundamentals/effects/touch-tracking.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/app-fundamentals/effects/touch-tracking.md)
* Product: **xamarin**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by conceptdev** [comment]
Thanks for the feedback @tpsands. It sounds like this might be a bug in Xamarin.Forms? If so, you can report it on the [Xamarin.Forms GitHub repo](https://github.com/xamarin/Xamarin.Forms/issues). We'll take a look to see what we can address in the doc.

**Comment by tpsands** [comment]
I neglected to mention I am using Xamarin.Forms version 3.2.0.871581 and can't upgrade my project yet to the latest Xamarin.Forms. I'll spin up a quick project with the latest to test.

**Comment by tpsands** [comment]
Upgraded to latest Production version of Xamarin.Forms (3.4.0.1008975). Bug remains. I'll open an Issue over there.

**Comment by conceptdev** [comment]
Too bad it's still present, but thanks for taking it over to the team.
