### ISSUE TITLE
Xamarin.Forms.Image User Interaction not enabled in iOS

### ISSUE THREAD

**Issue by tpsands** [MicrosoftDocs/xamarin-docs#1208]
If you use this sample and just swap the BoxViews for Images, it won't work because user interaction isn't enabled for Images in iOS. In order to make it work for Images, in the iOS-specific TouchEffect class, you have to add a statement once you've obtained the view in the OnAttached override:

`view.UserInteractionEnabled = true;`

I am not sure what other types have this limitation but it is worth mentioning to save later developers time when dragging may not work in iOS.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 908530d1-f21d-5532-c530-1727e3356b64
* Version Independent ID: e01f2543-3b7d-0b60-8d79-c012feab83de
* Content: [Invoking Events from Effects - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/effects/touch-tracking)
* Content Source: [docs/xamarin-forms/app-fundamentals/effects/touch-tracking.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/app-fundamentals/effects/touch-tracking.md)
* Product: **xamarin**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @tpsands 

Thanks for the suggestion. A doc update will be in bound.
