### ISSUE TITLE
Actual call functionality is not working (at least for Android)

### ISSUE THREAD

**Issue by n-develop** [MicrosoftDocs/xamarin-docs#121]
I followed the tutorial and started the app using Xamarin Live Player on my Android phone. But every time I use the call button in the app and confirm the alert, nothing happens. After a short debugging session, I realized, that `MainActivity.Instance` is `null`. Maybe "OnCreate" is not called? But that would be weird, because the UI is configured correctly and working fine. Any ideas?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2de3e72c-8948-4dd5-e37f-9cf81e62c127
* Version Independent ID: 7b7c5c7f-4102-8e91-fbe6-7d21fcc8f5be
* Content: [Xamarin.Forms Quickstart - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/get-started/hello-xamarin-forms/quickstart?tabs=vswin)
* Content Source: [docs/xamarin-forms/get-started/hello-xamarin-forms/quickstart.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/get-started/hello-xamarin-forms/quickstart.md)
* Service: **unspecified**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by conceptdev** [comment]
Hi @n-develop, this is most likely related to a limitation of Live Player. There are certain actions that apps can perform (including things like accessing photos, the microphone or camera, and making calls) that require the app to request permissions, and require the C# code to interact with Android native classes. These are some things Live Player just cannot do with its dynamic nature.

We have not explicitly called this out on the [limitations page](https://docs.microsoft.com/en-us/xamarin/tools/live-player/limitations?tabs=android) but we might have to add that to prevent others from hitting the same issue (without explanation).
