### ISSUE TITLE
How to Configure the VS Service Reference Tool for iOS and Android?

### ISSUE THREAD

**Issue by alaskanrogue** [MicrosoftDocs/xamarin-docs#1216]
How do you configure the VS Service Reference tool for generating full asynchronous method (TaskFactory?) classes for iOS and Android development from a VS-generated WSDL to support await functions accessing SOAP services in addition to UWP's being generated in a Xamarin cross-platform solution?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72b7ac73-7fd9-4abe-e73a-e1a88e1d2b11
* Version Independent ID: bd6ee8cf-dd83-c974-8849-83a27553b378
* Content: [Consuming an ASP.NET Web Service (ASMX) - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/data-cloud/consuming/asmx)
* Content Source: [docs/xamarin-forms/data-cloud/consuming/asmx.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/data-cloud/consuming/asmx.md)
* Product: **xamarin**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @alaskanrogue 

Unfortunately the Mono implementation of WCF doesn't support the task-based asynchronous pattern. Instead, it supports the old asynchronous programming model (APM begin/end) only.

However, there are some workarounds. For more details, see https://github.com/dotnet/wcf/issues/2463
