### ISSUE TITLE
Customizing the checkbox - info needed

### ISSUE THREAD

**Issue by u0107** [MicrosoftDocs/xamarin-docs#1217]
Hello,

Adding a checkbox is relatively easy - but how can one customize the checkbox programmatically?

For example, when the checkbox is checked, how do I change the background color?

How do I vertically center the accompanying text of a checkbox?

There seems to be NO straightforward explanation of how this can be programmatically customized.

Thank you in advance.

Uttam

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a7d0ca3a-00fd-3e20-0eac-314abee33c73
* Version Independent ID: cde4f1bf-659c-3cf3-b861-5cbe87581a98
* Content: [CheckBox - Xamarin](https://docs.microsoft.com/en-us/xamarin/android/user-interface/controls/buttons/check-box)
* Content Source: [docs/android/user-interface/controls/buttons/check-box.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/android/user-interface/controls/buttons/check-box.md)
* Product: **xamarin**
* GitHub Login: @conceptdev
* Microsoft Alias: **crdun**

**Comment by conceptdev** [comment]
@u0107 thanks for your feedback. We do not currently have any information specifically about styling the checkbox control. Perhaps this page about the [Material theme](https://docs.microsoft.com/xamarin/android/user-interface/material-theme) can help?
