### ISSUE TITLE
I can't find the Shared Project Template in VS15.9.3

### ISSUE THREAD

**Issue by kgreed** [MicrosoftDocs/xamarin-docs#1218]
https://stackoverflow.com/questions/53690103/missing-shared-visual-studio-project-template

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 675ea80e-9a66-9b44-adb7-e8fbdc533f34
* Version Independent ID: 5d602c56-fbbb-194e-9b31-b6df8cbfcc2c
* Content: [Use Shared Projects to Share Code - Xamarin](https://docs.microsoft.com/en-us/xamarin/cross-platform/app-fundamentals/shared-projects?tabs=windows)
* Content Source: [docs/cross-platform/app-fundamentals/shared-projects.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/cross-platform/app-fundamentals/shared-projects.md)
* Product: **xamarin**
* GitHub Login: @conceptdev
* Microsoft Alias: **crdun**

**Comment by conceptdev** [comment]
.NET Standard projects are now recommended instead of Shared Projects for most uses. I was not aware that the template had been removed from the latest version of Visual Studio - we'll investigate and update the page if necessary. Thanks for letting us know.

**Comment by kgreed** [comment]
Thanks @conceptdev  If the shared project uses Winforms what is recommended?

**Comment by conceptdev** [comment]
If the shared project _uses_ WinForms, then it is not a good candidate for inclusion in a Xamarin app. You would need to refactor the code to separate WinForms code from the business logic, and then reference the project containing the business logic only from your Xamarin app.
