### ISSUE TITLE
Using Navigation inside TabbedPage

### ISSUE THREAD

**Issue by connelevalsam** [MicrosoftDocs/xamarin-docs#1219]
hello, i have a little problem with this. i have a login, signup and dashboard. The dashboard is the tabbed page so already, it's in a navigation page because the rootpage is the mainpage where you have to choose login or signup

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0c81c589-e81e-d98c-9656-695a3520a12d
* Version Independent ID: c235f6f9-47ce-15f3-b4da-cb12e219df92
* Content: [Xamarin.Forms Tabbed Page - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/navigation/tabbed-page)
* Content Source: [docs/xamarin-forms/app-fundamentals/navigation/tabbed-page.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/app-fundamentals/navigation/tabbed-page.md)
* Product: **xamarin**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @connelevalsam 

You can still invoke navigation as normal, from inside your ContentPage, which is in a TabbedPage, which is in a NavigationPage.
