### ISSUE TITLE
AMD Ryzen support

### ISSUE THREAD

**Issue by samirgunic** [MicrosoftDocs/xamarin-docs#122]
What do you guys recommend for those of us that have a system based on the AMD Ryzen processor? How do we get the same benefit of hardware assisted virtualization as those of us with an Intel processor?

We could switch to Linux, run Windows 10 in a VM, and install Visual Studio with the Xamarin workload in the VM. But then... why not just develop Android apps natively using Java and Android Studio on Linux or Windows? If one does not need the benefit of cross-platform development with Xamarin, this is a viable option I think. Assuming of course you know how to java or are willing to learn it.

Either way, you should put up some kind of guideline for those that land on this page and have the new AMD processor. Even if it's something as disheartening as "AMD processors not supported".

> You cannot run HAXM on a virtual machine.

I'm not sure what you mean here... but you could say something like:

> You cannot run HAXM on an AMD processor.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4e37d642-2051-8d70-9968-dfb484122a6a
* Version Independent ID: 178ea80c-2b99-0c44-eeb6-9db319439b33
* Content: [Android Emulator Hardware Acceleration - Xamarin](https://docs.microsoft.com/en-us/xamarin/android/get-started/installation/android-emulator/hardware-acceleration?tabs=vswin)
* Content Source: [docs/android/get-started/installation/android-emulator/hardware-acceleration.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/android/get-started/installation/android-emulator/hardware-acceleration.md)
* Service: **unspecified**
* GitHub Login: @mgmclemore
* Microsoft Alias: **mamcle**

**Comment by mgmclemore** [comment]
Extra information about AMD processors and nested virtualization added. Should be published soon.

**Comment by himadrinath** [comment]
@samirgunic  right now we have only one option [genymotion](https://www.genymotion.com)

**Comment by samirgunic** [comment]
@himadrinath yes, I know about Genymotion. But it comes with a price tag. It's not a good option for poor programming students. There is a "fun zone" [personal edition](https://www.genymotion.com/fun-zone/) which is a free tier. But does it support debugging over ADB? It's not made clear on their website how it differs from the paid versions. Also, Genymotion is not Hyper-V compatible and relies on VirtualBox, which is a type 2 hypervisor, so I don't expect the performance to be very good with that combination.

There was a Hyper-V compatible, and free Android emulator from Microsoft called "Visual Studio Emulator for Android". You can still [download it](https://www.visualstudio.com/vs/msft-android-emulator/) from the Visual Studio website. Sadly, it has been deprecated and is no longer maintained. You can't get the latest Android system images for it, and you have to hack the Windows registry a little bit to enable it in Visual Studio 2017. It was originally designed for Visual Studio 2015.

The way I see it, if you want to avoid all these intricate complexities of different software layers, you only have two main options.

- Intel based Windows computer with Intel VT-x support
  - Programming in C# with Xamarin and Visual Studio
  - Programming in Java with Android Studio or IntelliJ IDEA

- Intel or AMD based Linux computer with AMD-V support
  - Programming in Java with Android Studio or IntelliJ IDEA

While both Visual Studio and IntelliJ IDEA are commercial software, they both have full featured and free to use Community editions. I hope this helps you better understand your options.
