### ISSUE TITLE
Screenshots missing?

### ISSUE THREAD

**Issue by Hansonaplane** [MicrosoftDocs/xamarin-docs#1220]
The articles mentions examples being displayed on screenshots several times. However, no screenshot seems to be contained on the page. Is it possible to include them? This seems to be an issue on other similar pages (e.g. CarouselPage), too.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0c81c589-e81e-d98c-9656-695a3520a12d
* Version Independent ID: c235f6f9-47ce-15f3-b4da-cb12e219df92
* Content: [Xamarin.Forms Tabbed Page - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/navigation/tabbed-page)
* Content Source: [docs/xamarin-forms/app-fundamentals/navigation/tabbed-page.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/app-fundamentals/navigation/tabbed-page.md)
* Product: **xamarin**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by conceptdev** [comment]
@Hansonaplane the screenshots should render for you, here's an example:

![screen shot 2018-12-10 at 12 46 31 pm](https://user-images.githubusercontent.com/199373/49760571-a1c3b480-fc79-11e8-83e8-085149be7a81.png)

Is there a chance you had connection issues (or a slow connection)? Our build system validates the image tags and should ensure that our images are always working/rendering.

**Comment by Hansonaplane** [comment]
You are absolutely right, I am sorry. The problem most likely results from my browser (Firefox) on the computer I was using yesterday. It did not affect all articles on MS docs, that's why I did not see the problem resulting from my equipment. Thank you!
