### ISSUE TITLE
From Part 1 to Part 2

### ISSUE THREAD

**Issue by davidortinau** [MicrosoftDocs/xamarin-docs#1221]
Could we have a button at the bottom the Part 1 page that takes me to Part 2?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9eaecafc-e9cf-567e-8fb3-51b09592a20b
* Version Independent ID: aa4365c2-2dd1-27a2-694c-25670f0a5702
* Content: [Xamarin.Forms Quickstart - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/get-started/hello-xamarin-forms/quickstart?pivots=windows)
* Content Source: [docs/xamarin-forms/get-started/hello-xamarin-forms/quickstart.experimental.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/get-started/hello-xamarin-forms/quickstart.experimental.md)
* Product: **xamarin**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by conceptdev** [comment]
There is a link **next topic**, which perhaps was not immediately obvious.

![screen shot 2018-12-10 at 1 03 23 pm](https://user-images.githubusercontent.com/199373/49761477-113aa380-fc7c-11e8-81f7-a0aa92565792.png)

We are re-writing these docs, and will be sure to include clearer navigation.
