### ISSUE TITLE
Prerequisites and Concepts Covered

### ISSUE THREAD

**Issue by davidortinau** [MicrosoftDocs/xamarin-docs#1222]
Could we have a bullet list at the top that lists prerequisites and concepts covered? Would help to know what I'm going to learn or at least touch on at a glance.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9eaecafc-e9cf-567e-8fb3-51b09592a20b
* Version Independent ID: aa4365c2-2dd1-27a2-694c-25670f0a5702
* Content: [Xamarin.Forms Quickstart - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/get-started/hello-xamarin-forms/quickstart?pivots=windows)
* Content Source: [docs/xamarin-forms/get-started/hello-xamarin-forms/quickstart.experimental.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/get-started/hello-xamarin-forms/quickstart.experimental.md)
* Product: **xamarin**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
This is an interesting topic.

10 years ago, anything I wrote for Microsoft had to have Learning outcomes (LOs) and pre-req's at the top of the doc. It was a standard and best practice. On top of that, academic courses on teaching and learning, and industry courses on instructional design, always preach it as a best practice. Back then, as a writer it was required that you have knowledge of how people learn, different taxonomies etc.

Fast forward to the present day and it no longer happens, seemingly for a number of reasons:

- 10 years ago, just as software releases were slower processes, so were doc releases. Docs would be reviewed for accuracy by devs, and by instructional designers for appropriate use of teaching & learning theory. This has all been streamlined now: devs don't review content, AFAIK there aren't any instructional designers at MS anymore, and content devs don't necessarily have any background in teaching and learning.
- I recall some doc testing that was performed on users (~2011), and one of the findings was that the majority of users skipped over the pre-amble that included pre-reqs and LOs. I particularly remember being gutted that my LOs were ignored (I always agonised over their accuracy). Users just wanted to get on with doing something (clicking the mouse, hitting the keyboard).

With that said, I think there's a strong argument to be made for including pre-reqs and LOs in our getting started docs. It will focus user expectations by clarifying what's being covered and what's not being covered.

**Comment by davidbritch** [comment]
Moving this issue to the private repo.
