### ISSUE TITLE
Related Links

### ISSUE THREAD

**Issue by davidortinau** [MicrosoftDocs/xamarin-docs#1223]
Inline and at the bottom would be good to have links to Emulators (I've never had success with the one you show in the image) like you have for Mac Pairing. Maybe some other concepts in here that would be helpful to link out to.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9eaecafc-e9cf-567e-8fb3-51b09592a20b
* Version Independent ID: aa4365c2-2dd1-27a2-694c-25670f0a5702
* Content: [Xamarin.Forms Quickstart - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/get-started/hello-xamarin-forms/quickstart?pivots=windows)
* Content Source: [docs/xamarin-forms/get-started/hello-xamarin-forms/quickstart.experimental.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/get-started/hello-xamarin-forms/quickstart.experimental.md)
* Product: **xamarin**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Moved to the private repo.
