### ISSUE TITLE
No funciona

### ISSUE THREAD

**Issue by CeciAc** [MicrosoftDocs/xamarin-docs#1227]
@jfranpino commented on [Mon Dec 10 2018](https://github.com/MicrosoftDocs/xamarin-docs.es-es/issues/34)

He intentado varias veces hacerlo y no funciona, resulta con múltiples errores.

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: bfbead94-9441-acc3-8559-6d09713f5274
* Version Independent ID: 15fb3cb2-7408-ba72-4795-c7889caeb8da
* Content: [Tutorial: uso de notificaciones locales en Xamarin.Android - Xamarin](https://docs.microsoft.com/es-es/xamarin/android/app-fundamentals/notifications/local-notifications-walkthrough)
* Content Source: [docs/android/app-fundamentals/notifications/local-notifications-walkthrough.md](https://github.com/MicrosoftDocs/xamarin-docs.es-ES/blob/live/docs/android/app-fundamentals/notifications/local-notifications-walkthrough.md)
* Product: **xamarin**
* GitHub Login: @conceptdev
* Microsoft Alias: **crdun**

---

@CeciAc commented on [Mon Dec 10 2018](https://github.com/MicrosoftDocs/xamarin-docs.es-es/issues/34#issuecomment-445987520)

Hola, @jfranpino 

Agradecemos enormemente su colaboración. Nuestro equipo solo puede responder a comentarios relacionados con la documentación. 

Registre los comentarios de su producto mediante el botón "Comentarios sobre el producto" en la parte inferior de la página de DOCS. 

Si tiene comentarios relacionados con la documentación, regístrelos a través de este canal. 

Apreciamos su contribución a nuestros artículos.  

Atentamente, 
Equipo internacional de Microsoft Docs 

---

@jfranpino commented on [Tue Dec 11 2018](https://github.com/MicrosoftDocs/xamarin-docs.es-es/issues/34#issuecomment-446128584)

Gracias por la respuesta. referente a esta documentación, en el método:
void CreateNotificationChannel() 
y en la linea
var name = Resources.GetString(Resource.String.channel_name);

No debería ser:
var name = Resources.GetString(Resource.Strings.channel_name);

Creo que hay un error de un caracter o no es así?

Y en el SecondActivity.cs falta la siguiente línea:
using LocalNotifications.Droid;

**Comment by CeciAc** [comment]
Hi team, 
I'm moving this one here since the user is reporting an error in the code.

> Regarding this documentation, in the method:
> void CreateNotificationChannel ()
> and on the line
> var name = Resources.GetString (Resource.String.channel_name);
> 
> Should not it be like this?
> var name = Resources.GetString (Resource.Strings.channel_name);
> I think there is an error of a character, isn't it? 
> 
> And in the SecondActivity.cs the following line is missing:
> using LocalNotifications.Droid;

**Comment by conceptdev** [comment]
This is the correct syntax ([this code](https://github.com/xamarin/monodroid-samples/blob/master/LocalNotifications/Notifications.Android/MainActivity.cs) compiles fine):
`var name = Resources.GetString(Resource.String.channel_name);`

[**SecondActivity.cs**](https://github.com/xamarin/monodroid-samples/blob/master/LocalNotifications/Notifications.Android/SecondActivity.cs) does not need any addition using statements.

`MyButton` is declared in [**Main.axml**](https://github.com/xamarin/monodroid-samples/blob/master/LocalNotifications/Notifications.Android/Resources/Layout/Main.axml#L7).

Thanks for the feedback.
