### ISSUE TITLE
Could not install Mono on Mac

### ISSUE THREAD

**Issue by Maethorin** [MicrosoftDocs/xamarin-docs#1228]
Xamarin.Messaging.Ssh.SshCommands|Error|0|Could not find a Mono installation on the Server
Xamarin.Messaging.Ssh.SshCommands|Error|0|Probed locations for Mono on the Server: mono64, /Library/Frameworks/Mono.framework/Versions/Current/bin/mono64, /usr/bin/mono64, /bin/mono64, /usr/local/bin/mono64, /usr/sbin/mono64, /sbin/mono64, /Users/inceresdev/Library/Caches/Xamarin/XMA/Runtimes/mono/bin/mono64, mono, /Library/Frameworks/Mono.framework/Versions/Current/bin/mono, /usr/bin/mono, /bin/mono, /usr/local/bin/mono, /usr/sbin/mono, /sbin/mono, /Users/inceresdev/Library/Caches/Xamarin/XMA/Runtimes/mono/bin/mono
Xamarin.Messaging.Integration.State.ServerStateContext|Information|0|Checking host configuration for connecting to '192.168.1.88'...
Xamarin.Messaging.Integration.State.ServerStateContext|Information|0|Server State transition from ConfiguringState to DisconnectingState on 192.168.1.88 (192.168.1.88)
Xamarin.Messaging.Integration.State.ServerStateContext|Information|0|Starting disconnection from 192.168.1.88...
Xamarin.Messaging.Integration.State.ServerStateContext|Information|0|Starting disconnection from 192.168.1.88...
Xamarin.Messaging.Integration.State.ServerStateContext|Information|0|Server State transition from DisconnectingState to DisconnectedState on 192.168.1.88 (192.168.1.88)
Xamarin.Messaging.Integration.State.ServerStateContext|Information|0|The connection to '192.168.1.88' has been finished
Xamarin.Messaging.Integration.State.ServerStateContext|Error|0|Mono is not installed on the Mac and the required version to install it automatically couldn't be determined. The connection will be aborted. Please try to install a compatible Mono and try again.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 98c96bcc-1743-8d9f-f1b2-3c30d5b2a6e2
* Version Independent ID: f57a6157-332a-3f31-c785-7efa99e62711
* Content: [Pair to Mac for Xamarin.iOS Development - Xamarin](https://docs.microsoft.com/en-us/xamarin/ios/get-started/installation/windows/connecting-to-mac/index#automatic-mac-provisioning)
* Content Source: [docs/ios/get-started/installation/windows/connecting-to-mac/index.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/ios/get-started/installation/windows/connecting-to-mac/index.md)
* Product: **xamarin**
* GitHub Login: @lobrien
* Microsoft Alias: **laobri**

**Comment by conceptdev** [comment]
Hi @Maethorin can you please report this issue [using Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio-2017?view=vs-2017). The built-in reporting tool provides our team with additional logs and info to help diagnose and fix issues. You will also be able to communicate with them via [Developer Community](https://developercommunity.visualstudio.com/) while they investigate.
Thanks.
