### ISSUE TITLE
Incorrect property name in snippet.

### ISSUE THREAD

**Issue by UnreachableCode** [MicrosoftDocs/xamarin-docs#1229]
ConnectivityChangedEventArgs does not contain a definition for 'ConnectionProfiles'. The correct property name is 'Profiles'.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 33758e0e-bd5d-0829-b458-6cdfabe98b44
* Version Independent ID: d3ed3057-798b-44b9-b5a0-35e657f7a4b8
* Content: [Xamarin.Essentials: Connectivity - Xamarin](https://docs.microsoft.com/en-us/xamarin/essentials/connectivity?context=xamarin%2Fxamarin-forms&tabs=android)
* Content Source: [docs/essentials/connectivity.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/essentials/connectivity.md)
* Product: **xamarin**
* GitHub Login: @jamesmontemagno
* Microsoft Alias: **jamont**

**Comment by jamesmontemagno** [comment]
This is correct, this API was changed in v 1.0.0

**Comment by jamesmontemagno** [comment]
See: https://github.com/xamarin/Essentials/wiki/Release-Notes

**Comment by Nesyne** [comment]
thanks for the update 👍

**Comment by Nesyne** [comment]
Is there a way to figure out signal strength(WIFI, cellular) through connectivity?

**Comment by jamesmontemagno** [comment]
Nor currently no, however we do have a PR for WiFi strength which we are reviewing.

**Comment by Nesyne** [comment]
Thanks James. When do you think the PR for WiFi will come out?

**Comment by conceptdev** [comment]
For information on new features and updates, watch the [open source repo for Xamarin.Essentials](https://github.com/xamarin/essentials).

**Comment by UnreachableCode** [comment]
Thanks @jamesmontemagno
