### ISSUE TITLE
[Xamarin.Forms] Typo in Button.Focus() intellisense

### ISSUE THREAD

**Issue by samhouts** [MicrosoftDocs/xamarin-docs#1231]
![image](https://user-images.githubusercontent.com/7827070/49838224-79fa4c80-fd5e-11e8-9b18-425687587bf1.png)

**Comment by conceptdev** [comment]
Closing this issue, since it seems like it's now 'in process' on the [API docs repo](https://github.com/xamarin/Xamarin.Forms-api-docs/).
