### ISSUE TITLE
Type 'Keyboard' is not usable as an object element because it is not public or does not define a public parameterless constructor or a type converter

### ISSUE THREAD

**Issue by MNHarun** [MicrosoftDocs/xamarin-docs#1238]
&lt;Entry Text="{Binding CurrentRecord.Profession}" Placeholder="Musician, Doctor, Lawyer... "&gt;
    &lt;Entry.Keyboard&gt;
        &lt;Keyboard x:FactoryMethod="Create"&gt;
            &lt;x:Arguments&gt;
                &lt;KeyboardFlags&gt;CapitalizeCharacter&lt;/KeyboardFlags&gt;
            &lt;/x:Arguments&gt;
        &lt;/Keyboard&gt;
    &lt;/Entry.Keyboard&gt;
&lt;/Entry&gt;

The attribute 'FactoryMethod' from the XAML namespace is not defined.

Xamarin   4.11.0.779 (d15-8@ff915e800)
Xamarin Designer   4.15.12 (d7ff6f39c)
Xamarin Templates   1.1.118 (4217ee9)
Xamarin.Android SDK   9.0.0.19 (HEAD/a8a3b0ec7)
Xamarin.Android Reference Assemblies and MSBuild support.
Xamarin.iOS and Xamarin.Mac SDK   12.1.0.15 (cbfb047)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c5afa3c9-4bcb-4986-2161-1bf2feb856b7
* Version Independent ID: 39fc31bd-4b1d-65f3-aaf8-6eb464e9b38a
* Content: [Xamarin.Forms Entry - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/text/entry)
* Content Source: [docs/xamarin-forms/user-interface/text/entry.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/text/entry.md)
* Product: **xamarin**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @MNHarun 

Have you tried the [sample](https://developer.xamarin.com/samples/xamarin-forms/UserInterface/Text/). It's working fine for me.

**Comment by Moltroon** [comment]
Too

**Comment by danielmeza** [comment]
have this issue too

**Comment by upskydownshoes** [comment]
Me too
