### ISSUE TITLE
Wrong advise about Android localization

### ISSUE THREAD

**Issue by Tunduk** [MicrosoftDocs/xamarin-docs#124]
I have tried localize my app and I have used [this article](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/localization?tabs=vswin).
Unfortunately, this note is wrong. In my case, if "Fast assembly deployment" NOT ticked then app will crash with NullReference.  I have spend about 2hrs for random testing and after ticking "Fast assembly deployment" app work as should.
> WARNING: If the translated strings are working in your RELEASE Android builds but not while debugging, right-click on the Android Project and select Options > Build > Android Build and ensure that the Fast assembly deployment is NOT ticked. This option causes problems with loading resources and should not be used if you are testing localized apps.

**Comment by conceptdev** [comment]
Thanks for the feedback. If you believe you have found a bug or issue with the product, please visit https://developercommunity.visualstudio.com/ to report the problem.
