### ISSUE TITLE
Typo in "ShouldShowRequestPermissionRationale"

### ISSUE THREAD

**Issue by fragmer** [MicrosoftDocs/xamarin-docs#1240]
The last letter is missing from the word "Rationale" in the name of this method, under "Runtime Permission Checks in Android 6.0" heading.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 85d5d1c5-9b5b-0e6c-0ac2-0cc76dff410b
* Version Independent ID: 21a07f8c-706c-e69e-43db-8f5c61dd6be1
* Content: [Permissions In Xamarin.Android - Xamarin](https://docs.microsoft.com/en-us/xamarin/android/app-fundamentals/permissions?tabs=windows#runtime-permission-checks-in-android-60)
* Content Source: [docs/android/app-fundamentals/permissions.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/android/app-fundamentals/permissions.md)
* Product: **xamarin**
* GitHub Login: @conceptdev
* Microsoft Alias: **crdun**

**Comment by conceptdev** [comment]
Thanks for letting us know, it's been updated and will be published soon.
