### ISSUE TITLE
Name changed

### ISSUE THREAD

**Issue by jmdon1** [MicrosoftDocs/xamarin-docs#1243]
Worth noting that this has now been re-named to DataTransfer https://github.com/xamarin/Essentials/tree/master/Xamarin.Essentials/Share

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e86cfbdf-277d-29ae-3999-33f73d91efc6
* Version Independent ID: cf9bfb50-9d1e-3c5d-139f-392dfc9550eb
* Content: [Xamarin.Essentials: Share - Xamarin](https://docs.microsoft.com/en-us/xamarin/essentials/share?tabs=android)
* Content Source: [docs/essentials/share.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/essentials/share.md)
* Product: **xamarin**
* GitHub Login: @jamesmontemagno
* Microsoft Alias: **jamont**

**Comment by jamesmontemagno** [comment]
DataTransfer was the old name, it was changed to Share in version 1.0
