### ISSUE TITLE
How can we prevent VS for Mac downloading the MS-Dist OpenJDK?

### ISSUE THREAD

**Issue by kinosang** [MicrosoftDocs/xamarin-docs#1246]
I think there's must some guys like me who has already install an OpenJDK (such as Amazon Coretto) on their mac, install MS-Dist OpenJDK seems useless to us, how can we prevent VS for Mac downloading and installing the OpenJDK automatically?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 97e1cd96-e7a2-ec22-8d79-ac949e890ccb
* Version Independent ID: 922a3fdf-7bab-7d9d-5518-904db9e75ee3
* Content: [Microsoft's Mobile OpenJDK Distribution - Xamarin](https://docs.microsoft.com/en-us/xamarin/android/get-started/installation/openjdk#feedback)
* Content Source: [docs/android/get-started/installation/openjdk.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/android/get-started/installation/openjdk.md)
* Product: **xamarin**
* GitHub Login: @vyedin
* Microsoft Alias: **vyedin**

**Comment by vyedin** [comment]
Hi Chino, unfortunately we don't test or officially support other JDK distributions, and because we really want to make sure people have a working setup ootb, we install the JDK we support.
