### ISSUE TITLE
What is the actual point to use Xamarin?

### ISSUE THREAD

**Issue by KFindley** [MicrosoftDocs/xamarin-docs#1248]
I am very upset at Microsoft none of the online tutorials videos say I need a mac to finish a ios app. since just got a mac why just use swift instead. What is the actual point if Xamarin? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 90eadee6-b0e8-c89f-7d7d-d3d1485ef855
* Version Independent ID: 634488c8-b12d-21ae-0d9f-c4730ce9d316
* Content: [Getting Started with Xamarin.Forms - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/get-started/index)
* Content Source: [docs/xamarin-forms/get-started/index.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/get-started/index.md)
* Product: **xamarin**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @KFindley 

It's a licensing restriction of Apple that a Mac is required to build iOS apps.

Xamarin technology permits app development in .NET, and the ability to write cross-platform apps from one code base.
