### ISSUE TITLE
This document seems to be out of sink wiht https://docs.microsoft.com/en-us/xamarin/android/get-started/hello-android/hello-android-quickstart?pivots=windows

### ISSUE THREAD

**Issue by AndreMilota** [MicrosoftDocs/xamarin-docs#1250]
To start with there is not file called Main.axml it seems to be called activity_main.axml  but this guess may end up costing me the afternoon if I am wrong.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 672a11c0-fb8f-4b75-f42c-23429f52c35a
* Version Independent ID: 51f9c1e4-fa5d-b6ac-6081-c4c3189191f7
* Content: [Hello, Android Multiscreen: Quickstart - Xamarin](https://docs.microsoft.com/en-us/xamarin/android/get-started/hello-android-multiscreen/hello-android-multiscreen-quickstart?pivots=windows)
* Content Source: [docs/android/get-started/hello-android-multiscreen/hello-android-multiscreen-quickstart.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/android/get-started/hello-android-multiscreen/hello-android-multiscreen-quickstart.md)
* Product: **xamarin**
* GitHub Login: @conceptdev
* Microsoft Alias: **crdun**

**Comment by conceptdev** [comment]
Thanks for your feedback. Unfortunately, the **File>New** template differs between the Windows and macOS versions of Visual Studio: one uses `Main.axml` and the other uses `main_activity.axml`. We are working to correct this oversight in a future version, and also to correct the documentation. Other than this difference, the instructions should work as shown.
