### ISSUE TITLE
What does this mean?

### ISSUE THREAD

**Issue by jemunk** [MicrosoftDocs/xamarin-docs#1255]
"so this setting will be ignored on pre-app compat activities"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d1dff514-7c22-db86-7818-fc0bb7dd2d59
* Version Independent ID: 07523386-32c7-b2d3-566f-6c6023fa307b
* Content: [Xamarin.Forms Fast Renderers - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/internals/fast-renderers)
* Content Source: [docs/xamarin-forms/internals/fast-renderers.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/internals/fast-renderers.md)
* Product: **xamarin**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @jemunk 

If your `MainActivity` class derives from `FormsAppCompatActivity`, you can use fast renderers. If, however, your `MainActivity` class derives from `FormsApplicationActivity`, you can't use fast renderers.

**Comment by jemunk** [comment]
Thanks! Now it makes sense :-)
