### ISSUE TITLE
A lack of one more image

### ISSUE THREAD

**Issue by sadqiang** [MicrosoftDocs/xamarin-docs#1258]
The passage says "The screenshots from left to right show an iPhone, an Android phone, and a Windows 10 Mobile phone."

However there are only two images. One more image is forgotten?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0951037b-bdc8-f98e-e8c3-fe1f4acaa6bf
* Version Independent ID: 218f322f-ddb1-02a6-9611-63c079b9bbff
* Content: [Summary of Chapter 1. How does Xamarin.Forms fit in? - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/creating-mobile-apps-xamarin-forms/summaries/chapter01)
* Content Source: [docs/xamarin-forms/creating-mobile-apps-xamarin-forms/summaries/chapter01.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/creating-mobile-apps-xamarin-forms/summaries/chapter01.md)
* Product: **xamarin**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by conceptdev** [comment]
Thanks @sadqiang the page has been updated.
