### ISSUE TITLE
If linking all assemblies generates error, then when is it useful or appropriate to use?

### ISSUE THREAD

**Issue by MuziburRahman** [MicrosoftDocs/xamarin-docs#1263]
Please provide the project link with dtails steps to reproduce the 2.7 MB app. Using linker has always been a stressful thing for me.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ab92cdf-ac95-4451-e452-6dedd80ae5cf
* Version Independent ID: 36488aca-43cb-8d55-1d6b-b7bad09b1301
* Content: [Linking on Android - Xamarin](https://docs.microsoft.com/en-us/xamarin/android/deploy-test/linker)
* Content Source: [docs/android/deploy-test/linker.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/android/deploy-test/linker.md)
* Product: **xamarin**
* GitHub Login: @conceptdev
* Microsoft Alias: **crdun**

**Comment by conceptdev** [comment]
The size comparison here is given only as an example of the improvements in linker behavior in the latest versions of Xamarin.Android. As noted on the page, the example uses the [Hello, Android](https://developer.xamarin.com/samples/HelloM4A/) sample app. Real-world apps will have more code, and use more features of the .NET Framework, and will therefore be larger. They will also include images, icons, etc (and potentially other resources) that increase the package size.

In general, **Link SDK Assemblies** is a good setting to use for your release build.

You should only use **Link All Assemblies** if you have a big problem with your bundle size, and understand fully the impact of your code potentially being removed if there are no static references. This is especially true in Xamarin.Forms when using XAML and data binding.
