### ISSUE TITLE
Better mapping than iPhone Wiki

### ISSUE THREAD

**Issue by xperseguers** [MicrosoftDocs/xamarin-docs#1266]
Instead of referencing the iPhone Wiki page, I would suggest users interested into a real useful mapping to use https://github.com/dannycabrera/Get-iOS-Model which works really easily and well.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c918dea8-217e-8886-73ad-c1dcb9cc1e1e
* Version Independent ID: 238f8427-325c-dc77-caaf-1f3a8e44df88
* Content: [Xamarin.Essentials: Device Information - Xamarin](https://docs.microsoft.com/en-us/xamarin/essentials/device-information?tabs=ios)
* Content Source: [docs/essentials/device-information.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/essentials/device-information.md)
* Product: **xamarin**
* GitHub Login: @jamesmontemagno
* Microsoft Alias: **jamont**

**Comment by jamesmontemagno** [comment]
You could do a PR to reference both I think is fine.

**Comment by conceptdev** [comment]
PR has been submitted https://github.com/MicrosoftDocs/xamarin-docs/pull/2190 waiting review.
