### ISSUE TITLE
ios issue on xamarin essentials geocoding

### ISSUE THREAD

**Issue by technololy** [MicrosoftDocs/xamarin-docs#1268]
android works fine. iOS gives the error below

{Foundation.NSErrorException: Error Domain=kCLErrorDomain Code=8 "(null)"
  at Xamarin.Essentials.Geocoding+&lt;PlatformGetLocationsAsync&gt;d__4.MoveNext () [0x00075] in &lt;80b8ae4e16374c93b74637a8a9a92836&gt;:0 
--- End of stack trace from previous location where exception was thrown ---
  at 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2ebb7d82-4f75-9c6d-8305-7d40afc3a4aa
* Version Independent ID: cd18ee2b-c941-cc79-c6de-8004294a5e08
* Content: [Xamarin.Essentials: Geocoding - Xamarin](https://docs.microsoft.com/en-us/xamarin/essentials/geocoding?tabs=ios)
* Content Source: [docs/essentials/geocoding.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/essentials/geocoding.md)
* Product: **xamarin**
* GitHub Login: @jamesmontemagno
* Microsoft Alias: **jamont**

**Comment by jamesmontemagno** [comment]
Please open an issue at: https://github.com/xamarin/essentials

**Comment by technololy** [comment]
Gotten james
