### ISSUE TITLE
Lacking details on how to create view content

### ISSUE THREAD

**Issue by dreappdev** [MicrosoftDocs/xamarin-docs#1269]
The article says "We are going to ..." and then shows a picture of the completed View. No details on how the View was actually built. For newbies to this item, this is rather frustrating. There are slight details in the actual Xamarin and Xcode apps from the article (which also has minor but annoying grammatical errors in it) which make it difficult to follow and reproduce the sample. Please fix these issues.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 24c0f1b1-958a-db9c-466b-17f614bf8430
* Version Independent ID: 41818953-feba-6fce-d1cc-8c505e8be821
* Content: [Storyboards in Xamarin.Mac – Quick Start - Xamarin](https://docs.microsoft.com/en-us/xamarin/mac/platform/storyboards/quickstart)
* Content Source: [docs/mac/platform/storyboards/quickstart.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/mac/platform/storyboards/quickstart.md)
* Product: **xamarin**
* GitHub Login: @lobrien
* Microsoft Alias: **laobri**

**Comment by conceptdev** [comment]
The "completed view" you refer to is actually what is always present (by default) when a new Xamarin.Mac app is created. No details are provided on how it was built, because that it always the starting point. 
The rest of the document does attempt to provide step-by-step instructions on what to add, or delete, or edit, on the storyboard.

Thanks for the feedback about the grammatical errors, we'll review the document in future to address these.

**Comment by dreappdev** [comment]
That is not true. The layout starts with a Window Controller and a View Controller. But the View is not one of the specialized Views (like the Split View described here). And it certainly does not have any of the other controls added to it that the developer wants to add. Look again at page https://docs.microsoft.com/en-us/xamarin/mac/platform/storyboards/quickstart, about have way down.

**Comment by lobrien** [comment]
Are you talking about the first image in the "Defining a Presentation Segue" section? The image that shows a `UIView` that shows a text-formatting dialog? I think maybe that's the confusion, since the text "We are going to..." appears a few times in the text.

**Comment by lobrien** [comment]
Thanks for your feedback @dreappdev . I've reopened this issue because this document hasn't been revisited in a while, and any issues with clarity / missing steps should be addressed.

**Comment by dreappdev** [comment]
Thanks for your integrity and diligence. That will make those instructions superb. I will try to give you feedback, using a “newbie” to Xamarin viewpoint.

Thanks, DErik

**Comment by davidbritch** [comment]
Thanks for submitting an issue and we apologize for the delayed response. The requested updates haven't been made since the creation of the issue, and the timeline for resolution may vary based on resourcing, so the issue is being moved to an internal repo to better track it.
