### ISSUE TITLE
Different topics

### ISSUE THREAD

**Issue by pouyamiralayi** [MicrosoftDocs/xamarin-docs#1271]
Hi !
in the guide here:
`https://docs.microsoft.com/en-us/xamarin/xamarin-forms/get-started/hello-xamarin-forms/quickstart?pivots=windows`
the topic covered is a note app, but the getting deeper section after this, is covering a number dialing  app, assuming that interfaces and instructions on how to create this project is already told in the getting started. but it is not.
Thanks in advance.

**Comment by conceptdev** [comment]
Thanks for your feedback, @pouyamiralayi . We are in the process of rolling out a completely new tutorial based on the Notes app (which will completely replace Phoneword). The new part 2 page will be published early in the new year. I hope you found the Notes page and sample useful?

**Comment by pouyamiralayi** [comment]
Thanks in advance.
