### ISSUE TITLE
Part I and Part II of "Hello, Xamarin.Forms" don't match

### ISSUE THREAD

**Issue by bpechkis** [MicrosoftDocs/xamarin-docs#1272]
In "Part 1: Quickstart", you build a notes app.  However, when you continue on to "Part 2: Deep Dive", it begins with "In the Xamarin.Forms Quickstart, the Phoneword application was built", and continues to talk about a completely different app from the one in Part I.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 540c35eb-3db5-7e73-e6eb-07c4b70df1b0
* Version Independent ID: d8bd33e1-164d-2b2a-75de-42a95c75e6ad
* Content: [Xamarin.Forms Deep Dive - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/get-started/hello-xamarin-forms/deepdive?pivots=windows)
* Content Source: [docs/xamarin-forms/get-started/hello-xamarin-forms/deepdive.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/get-started/hello-xamarin-forms/deepdive.md)
* Product: **xamarin**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by conceptdev** [comment]
Thanks for your feedback, @bpechkis. We are in the process of rolling out a completely new tutorial based on the Notes app (which will completely replace Phoneword). The new part 2 page will be published early in the new year. I hope you found the Notes page and sample useful?
