### ISSUE TITLE
Fehler in TranslateButton.Click Code

### ISSUE THREAD

**Issue by CeciAc** [MicrosoftDocs/xamarin-docs#1274]
@pantalooon commented on [Wed Dec 26 2018](https://github.com/MicrosoftDocs/xamarin-docs.de-de/issues/24)

translatedNumber = PhonewordTranslator.ToNumber(phoneNumberText.Text);

müsste

translatedNumber = Core.PhonewordTranslator.ToNumber(phoneNumberText.Text);

lauten

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 672a11c0-fb8f-4b75-f42c-23429f52c35a
* Version Independent ID: 51f9c1e4-fa5d-b6ac-6081-c4c3189191f7
* Content: [Schnellstart für „Hallo, Android“-Multiscreen - Xamarin](https://docs.microsoft.com/de-de/xamarin/android/get-started/hello-android-multiscreen/hello-android-multiscreen-quickstart?pivots=windows)
* Content Source: [docs/android/get-started/hello-android-multiscreen/hello-android-multiscreen-quickstart.md](https://github.com/MicrosoftDocs/xamarin-docs.de-DE/blob/live/docs/android/get-started/hello-android-multiscreen/hello-android-multiscreen-quickstart.md)
* Product: **xamarin**
* GitHub Login: @conceptdev
* Microsoft Alias: **crdun**

**Comment by conceptdev** [comment]
Thanks, I've made the change suggested by the customer (which also matches the code on [this page](https://docs.microsoft.com/xamarin/android/get-started/hello-android/hello-android-quickstart#wire-up-the-user-interface)).
