### ISSUE TITLE
I'm trying to access the user name with Android essentials

### ISSUE THREAD

**Issue by ephraimf** [MicrosoftDocs/xamarin-docs#1276]
The documentation asks for a "key", but there is no list describing the available keys, or, specifically, what key to use to get the user name.

Is it in Preferences?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a7a399b1-a8a2-9cbd-c479-1bd98af46988
* Version Independent ID: 91a6ae06-508b-b668-52aa-cbdeabb2b46a
* Content: [Xamarin.Essentials: Preferences - Xamarin](https://docs.microsoft.com/en-us/xamarin/essentials/preferences?tabs=android)
* Content Source: [docs/essentials/preferences.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/essentials/preferences.md)
* Product: **xamarin**
* GitHub Login: @jamesmontemagno
* Microsoft Alias: **jamont**

**Comment by conceptdev** [comment]
The preferences API lets you store and retrieve values from your code. The keys are defined by you (the developer).

This is _not_ an API that lets you query user information (such as user name).

**Comment by ephraimf** [comment]
Is there an API that lets you get the user's name from the phone?

**Comment by conceptdev** [comment]
You can try [`DeviceInfo.Name`](https://docs.microsoft.com/xamarin/essentials/device-information?context=xamarin%2Fxamarin-forms), but it is not the user's name but what they called their phone. There is no "user name" that you can easily retrieve across all supported platforms.

**Comment by ephraimf** [comment]
Thank you.
