### ISSUE TITLE
Outdated link?

### ISSUE THREAD

**Issue by EddieLotter** [MicrosoftDocs/xamarin-docs#1277]
> In the Xamarin.Forms Quickstart, the Phoneword application was built.

The "Xamarin.Forms Quickstart" link in the introduction links to a "Notes" tutorial, not a "Phoneword" tutorial.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 540c35eb-3db5-7e73-e6eb-07c4b70df1b0
* Version Independent ID: d8bd33e1-164d-2b2a-75de-42a95c75e6ad
* Content: [Xamarin.Forms Deep Dive - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/get-started/hello-xamarin-forms/deepdive?pivots=windows)
* Content Source: [docs/xamarin-forms/get-started/hello-xamarin-forms/deepdive.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/get-started/hello-xamarin-forms/deepdive.md)
* Product: **xamarin**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @EddieLotter 

Thanks for your feedback. We are in the process of rolling out a completely new tutorial based on the Notes app (which will completely replace Phoneword). The new part 2 page will be published early in the new year.

**Comment by EddieLotter** [comment]
Awesome. Thanks @davidbritch
