### ISSUE TITLE
Link broken

### ISSUE THREAD

**Issue by queryquandary** [MicrosoftDocs/xamarin-docs#1278]
In the FirebaseApp is not Initialized section above, there is a link to a forum discussion which doesn't work.  Here is the URL:
https://forums.xamarin.com/discussion/96263/default-firebaseapp-is-not-initialized-in-this-process

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8d9bfb2a-2e5d-d505-337f-919251a85de3
* Version Independent ID: 695bff64-ae87-8c0f-5616-20b67893fdf0
* Content: [Remote Notifications with Firebase Cloud Messaging - Xamarin](https://docs.microsoft.com/en-us/xamarin/android/data-cloud/google-messaging/remote-notifications-with-fcm?tabs=macos)
* Content Source: [docs/android/data-cloud/google-messaging/remote-notifications-with-fcm.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/android/data-cloud/google-messaging/remote-notifications-with-fcm.md)
* Product: **xamarin**
* GitHub Login: @conceptdev
* Microsoft Alias: **crdun**

**Comment by conceptdev** [comment]
That forum thread has been deleted, I'll remove the link from this page.
