### ISSUE TITLE
Xamarin Firebase Messaging package pre-release checkbox

### ISSUE THREAD

**Issue by queryquandary** [MicrosoftDocs/xamarin-docs#1279]
It's unclear why this document instructs the user to "Check Show pre-release packages and search for Xamarin.Firebase.Messaging."  Is this still Microsoft's recommendation, and if so then why?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8d9bfb2a-2e5d-d505-337f-919251a85de3
* Version Independent ID: 695bff64-ae87-8c0f-5616-20b67893fdf0
* Content: [Remote Notifications with Firebase Cloud Messaging - Xamarin](https://docs.microsoft.com/en-us/xamarin/android/data-cloud/google-messaging/remote-notifications-with-fcm?tabs=macos)
* Content Source: [docs/android/data-cloud/google-messaging/remote-notifications-with-fcm.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/android/data-cloud/google-messaging/remote-notifications-with-fcm.md)
* Product: **xamarin**
* GitHub Login: @conceptdev
* Microsoft Alias: **crdun**

**Comment by conceptdev** [comment]
Most likely this has been accidentally left in the page, from when it was first written and the pre-release version of the NuGet was required (especially since this instruction only appears in the Mac tab, and not the Windows).

The page will be updated soon.
