### ISSUE TITLE
Text doesn't always show up as it should

### ISSUE THREAD

**Issue by AzyIsCool** [MicrosoftDocs/xamarin-docs#1281]
It seems that some characters seem to be messed up (e.g. ' shows as ```&apos;```)
This doesn't happen when using a Dialog

![capture2](https://user-images.githubusercontent.com/21204235/50539123-b3122980-0b72-11e9-807c-36f5725388bf.PNG)

![capture](https://user-images.githubusercontent.com/21204235/50539129-b7d6dd80-0b72-11e9-820b-32a3b0299fc4.PNG)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2bbded77-0d91-3707-2d36-d8c7de4e840d
* Version Independent ID: 6fae8fd3-298e-bddb-0ba5-4fb37d817a53
* Content: [GTK# Platform Setup - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/platform/gtk?tabs=windows)
* Content Source: [docs/xamarin-forms/platform/gtk.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/platform/gtk.md)
* Product: **xamarin**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by conceptdev** [comment]
Thanks for your feedback. This issue should be reported as a bug on the [Xamarin.Forms open source repo](https://github.com/xamarin/xamarin.forms/issues).
