### ISSUE TITLE
Installing openJDK on macOS Mojave manually from zip

### ISSUE THREAD

**Issue by eellund** [MicrosoftDocs/xamarin-docs#1282]
Tools &gt; SDK Manager dialog does not accept the jdk path where other path fields are blank, the Okay button is disabled. This issue was found with VS for Mac Community 7.7.2 (build 21); microsoft_dist_openjdk_1.8.0.9.zip

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 97e1cd96-e7a2-ec22-8d79-ac949e890ccb
* Version Independent ID: 922a3fdf-7bab-7d9d-5518-904db9e75ee3
* Content: [Microsoft's Mobile OpenJDK Distribution - Xamarin](https://docs.microsoft.com/en-us/xamarin/android/get-started/installation/openjdk)
* Content Source: [docs/android/get-started/installation/openjdk.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/android/get-started/installation/openjdk.md)
* Product: **xamarin**
* GitHub Login: @vyedin
* Microsoft Alias: **vyedin**

**Comment by conceptdev** [comment]
Please report this issue via [Visual Studio for Mac](https://docs.microsoft.com/en-us/visualstudio/mac/report-a-problem) - version information and logs will be included that will help diagnose the issue.
