### ISSUE TITLE
SmsMessage constructor does not accept phone number as string

### ISSUE THREAD

**Issue by JamesNyamu** [MicrosoftDocs/xamarin-docs#1284]
The SmsMessage constructor does not accept a string phone number as indicated in the documentation.

https://docs.microsoft.com/en-us/xamarin/essentials/sms?context=xamarin/xamarin-forms

The decompiled code asserts this
```
public static partial class Sms
    {
        public static Task ComposeAsync()
            => ComposeAsync(null);

        public static Task ComposeAsync(SmsMessage message)
        {
            if (!IsComposeSupported)
                throw new FeatureNotSupportedException();

            if (message == null)
                message = new SmsMessage();

            if (message?.Recipients == null)
                message.Recipients = new List<string>();

            return PlatformComposeAsync(message);
        }
    }

    public class SmsMessage
    {
        public SmsMessage()
        {
        }

        public SmsMessage(string body, IEnumerable<string> recipients)
        {
            Body = body;
            Recipients = recipients?.Where(x => !string.IsNullOrWhiteSpace(x)).ToList();
        }

        public string Body { get; set; }

        public List<string> Recipients { get; set; }
    }
```
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1b80826a-6389-7b3b-9c60-0682f735e7d2
* Version Independent ID: 0987fc15-6ca4-faf3-56af-85f0bb22b92c
* Content: [Xamarin.Essentials: SMS - Xamarin](https://docs.microsoft.com/en-us/xamarin/essentials/sms?context=xamarin/xamarin-forms)
* Content Source: [docs/essentials/sms.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/essentials/sms.md)
* Product: **xamarin**
* GitHub Login: @jamesmontemagno
* Microsoft Alias: **jamont**

**Comment by jamesmontemagno** [comment]
Put in PR: https://github.com/MicrosoftDocs/xamarin-docs/compare/live...jamesmontemagno:patch-17


we should also have that constructor though... so opened an issue: https://github.com/xamarin/Essentials/issues/672

**Comment by conceptdev** [comment]
Documentation has been updated, thanks for letting us know.
