### ISSUE TITLE
UWP Access to the path 'C:\Users' is denied.'

### ISSUE THREAD

**Issue by nguyenthanhliemfc** [MicrosoftDocs/xamarin-docs#1287]
I have use 

string fileName = Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData), "temp.txt");

and get this error

System.UnauthorizedAccessException: 'Access to the path 'C:\Users' is denied.'

---
#### Chi tiết tài liệu

⚠ *Không chỉnh sửa phần này. Điều này là bắt buộc cho docs.microsoft.com ➟ Vấn đề khi liên kết GitHub.*

* ID: 8fb68890-cda3-6b2a-deba-55a171963da5
* Version Independent ID: 675d1663-d7ea-3e47-dbdd-772944acce5a
* Content: [File Handling in Xamarin.Forms - Xamarin](https://docs.microsoft.com/vi-vn/xamarin/xamarin-forms/app-fundamentals/files?tabs=windows#saving-and-loading-files)
* Content Source: [docs/xamarin-forms/app-fundamentals/files.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/app-fundamentals/files.md)
* Product: **xamarin**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @nguyenthanhliemfc 

UWP apps are sandboxed and so you can't write to an arbitrary location. For more info, see https://docs.microsoft.com/en-us/windows/uwp/files/file-access-permissions

**Comment by nguyenthanhliemfc** [comment]
Thank you!
