### ISSUE TITLE
Pushing "Call" button does nothing on real devices

### ISSUE THREAD

**Issue by LisandroSu** [MicrosoftDocs/xamarin-docs#1288]
@damkow1981 commented on [Fri Dec 28 2018](https://github.com/MicrosoftDocs/xamarin-docs.pl-pl/issues/4)

Hello,
I've tested solution on two different Android devices (Android 5.1 and 8.0). Pushing "CALL" button does nothing. No switching to dial screen happens. On the other hand, it works perfectly with the android emulator, provided with Xamarin. It asks "Would You like to call .... ?" and then it switches to dial screen. May it be connected to some settings within the mobile devices? Thank You for Your reply.
BR
Damian

---
#### Szczegóły dokumentu

⚠ *Nie edytuj tej sekcji. Jest ona wymagana dla docs.microsoft.com ➟ Dołączanie problemu w usłudze GitHub.*

* ID: 2de3e72c-8948-4dd5-e37f-9cf81e62c127
* Version Independent ID: 7b7c5c7f-4102-8e91-fbe6-7d21fcc8f5be
* Content: [Przewodnik Szybki Start platformy Xamarin.Forms - Xamarin](https://docs.microsoft.com/pl-pl/xamarin/xamarin-forms/get-started/hello-xamarin-forms/quickstart?pivots=windows)
* Content Source: [docs/xamarin-forms/get-started/hello-xamarin-forms/quickstart.md](https://github.com/MicrosoftDocs/xamarin-docs.pl-PL/blob/live/docs/xamarin-forms/get-started/hello-xamarin-forms/quickstart.md)
* Product: **xamarin**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by LisandroSu** [comment]
Hi team,

Please check the issue reported above.

Thanks!

**Comment by davidbritch** [comment]
Hi @damkow1981

Making phone calls from an app in Android is problematic as it (1) depends on the API and (2) requires using the Permissions API to grant permission for the app to make phone calls.

For many reasons, including the above, we're in the process of rolling out a completely new tutorial based on the Notes app (which will completely replace Phoneword).
