### ISSUE TITLE
Any explanation for setting AllowedCorsOrigins for a Xamarin client?

### ISSUE THREAD

**Issue by JohnH-Work** [MicrosoftDocs/xamarin-docs#1296]
The example shows "AllowedCorsOrigins = { "http://eshopxamarin" }" but where does "http://eshopxamarin" come from? I searched the whole eShopOnContainers solution for "eshopxamarin" and the only place it exists is in the line that sets AllowedCorsOrigins. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5d805ca5-97c4-23e4-b635-9de16b6d7f78
* Version Independent ID: ec5b37f1-1bd1-c66e-6461-57c104ed543a
* Content: [Authentication and Authorization - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/enterprise-application-patterns/authentication-and-authorization)
* Content Source: [docs/xamarin-forms/enterprise-application-patterns/authentication-and-authorization.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/enterprise-application-patterns/authentication-and-authorization.md)
* Product: **xamarin**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @JohnH-Work 

Apologies for the delayed response.  IdentityServer normally only has to build a CORS policy for JavaScript clients, so it looks like you've spotted a bit of configuration that's not actually required for the Xamarin client.

I've opened a [bug](https://github.com/dotnet-architecture/eShopOnContainers/issues/905) in the eShopOnContainers repo for this issue, so I'm closing it here.
