### ISSUE TITLE
Use named arguments in sample code.

### ISSUE THREAD

**Issue by JeroMiya** [MicrosoftDocs/xamarin-docs#1297]
In the sample code to create an `OAuth2Authenticator` it uses a constructor with lots of arguments, including some that aren't self explanatory (e.g. boolean or null values). It helps if you use named arguments in the sample code so it's more clear what a `null` value is in the argument list, and especially if you're looking back and forth between the sample and the explanation of what each argument is doing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aa8bb9e0-5898-0d11-0213-fd4d8c8d0297
* Version Independent ID: 2f46e1f7-164f-2f32-70c0-f28919d16c5c
* Content: [Authenticating Users with an Identity Provider - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/data-cloud/authentication/oauth)
* Content Source: [docs/xamarin-forms/data-cloud/authentication/oauth.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/data-cloud/authentication/oauth.md)
* Product: **xamarin**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @JeroMiya 

Thanks for the suggestion. I agree and will ensure this happens in future.
