### ISSUE TITLE
MonoNativeFunctionWrapperAttribute is not explained

### ISSUE THREAD

**Issue by mellinoe** [MicrosoftDocs/xamarin-docs#130]
In order to use a delegate type in Marshal.GetDelegateForFunctionPointer, it needs to be annotated with MonoNativeFunctionWrapperAttribute. This isn't explained on the page, but the error message you get if you omit the attribute links to here.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 500b8f87-12fb-9f14-9655-06cd3f1d91d2
* Version Independent ID: b199d974-6356-af0e-9d96-81e54953b65d
* Content: [Limitations - Xamarin](https://docs.microsoft.com/en-us/xamarin/ios/internals/limitations#no-dynamic-code-generation)
* Content Source: [docs/ios/internals/limitations.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/ios/internals/limitations.md)
* Service: **unspecified**
* GitHub Login: @bradumbaugh
* Microsoft Alias: **brumbaug**

**Comment by bradumbaugh** [comment]
Thanks for calling this out, @mellinoe - much appreciated. I have a PR pending review to get this fixed, so you should see an update soon.

Thanks again!
