### ISSUE TITLE
It's will be great when have API to access Bluetooth!

### ISSUE THREAD

**Issue by nguyenthanhliemfc** [MicrosoftDocs/xamarin-docs#1302]
Thank you for great Xamarin!
It's will be great when have API to interact Bluetooth!
Thank!

---
#### Chi tiết tài liệu

⚠ *Không chỉnh sửa phần này. Điều này là bắt buộc cho docs.microsoft.com ➟ Vấn đề khi liên kết GitHub.*

* ID: c420b152-7303-918a-dbc8-8d1e539c64ec
* Version Independent ID: fe85e24f-c3fc-3763-b1db-6b360fb08067
* Content: [Xamarin.Essentials - Xamarin](https://docs.microsoft.com/vi-vn/xamarin/essentials/index?context=xamarin/xamarin-forms)
* Content Source: [docs/essentials/index.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/essentials/index.md)
* Product: **xamarin**
* GitHub Login: @jamesmontemagno
* Microsoft Alias: **jamont**

**Comment by jamesmontemagno** [comment]
Thanks for the issue, we track all feature requests for Essentials at: https://github.com/xamarin/Essentials

We have one open for Bluetooth already: https://github.com/xamarin/Essentials/issues/242
