### ISSUE TITLE
Java.Lang.Object inheritance

### ISSUE THREAD

**Issue by CarlosACepeda** [MicrosoftDocs/xamarin-docs#1306]
Creating a new class that inherits from Java.Lang.Object will also be covered by this?:
'all Java.Lang.Object and Java.Lang.Throwable subclasses. Instances of these types have two "halfs" a managed peer and a native peer. The managed peer is an instance of the C# class. The native peer is an instance of a Java class within the Android runtime VM, and the C# IJavaObject.Handle property contains a JNI global reference to the native peer.' 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 626dace3-cf0d-1c6e-6320-ca8007a0b97e
* Version Independent ID: b71ec0ef-9178-bfee-b693-dbcaac002879
* Content: [Garbage Collection - Xamarin](https://docs.microsoft.com/en-us/xamarin/android/internals/garbage-collection)
* Content Source: [docs/android/internals/garbage-collection.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/android/internals/garbage-collection.md)
* Product: **xamarin**
* GitHub Login: @conceptdev
* Microsoft Alias: **crdun**

**Comment by oliverw** [comment]
Yes, of course.

**Comment by conceptdev** [comment]
Thanks @oliverw, if that answers your questions @CarlosACepeda I'll close this issue?

**Comment by CarlosACepeda** [comment]
Thanks @oliverw  @conceptdev !
