### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by dstrube1** [MicrosoftDocs/xamarin-docs#1308]
In the sentence that begins "The new NSAllowsArbitraryLoadsInWebContent key can be add to the an app's Info.plist file", "add" should be changed to "added".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5df6c7bd-9958-38b0-f22e-73127697d0eb
* Version Independent ID: 6e3dfcbc-ee6a-18df-4c28-b641cc2ff0a2
* Content: [iOS Security and Privacy Features - Xamarin](https://docs.microsoft.com/en-us/xamarin/ios/app-fundamentals/security-privacy?tabs=macos)
* Content Source: [docs/ios/app-fundamentals/security-privacy.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/ios/app-fundamentals/security-privacy.md)
* Product: **xamarin**
* GitHub Login: @lobrien
* Microsoft Alias: **laobri**

**Comment by conceptdev** [comment]
Thanks @dstrube1 fixing that now!
