### ISSUE TITLE
Update documentation screenshot to latest VS for mac

### ISSUE THREAD

**Issue by albilaga** [MicrosoftDocs/xamarin-docs#1309]
Update actual screenshot to using VS for mac and also update the screenshot with actual screenshot that already checked according to tutorial. (As example in the first and second screenshot the one that needed to be checked from tutorial not checked in the screenshot). Also following the tutorial from this make the app cannot running

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 47fa9c3a-75e5-c82b-d390-218398717a43
* Version Independent ID: 943faa88-7b5f-dffa-443e-365d5d39d3c1
* Content: [Bundling for the Mac App Store - Xamarin](https://docs.microsoft.com/en-us/xamarin/mac/deploy-test/publishing-to-the-app-store/bundling)
* Content Source: [docs/mac/deploy-test/publishing-to-the-app-store/bundling.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/mac/deploy-test/publishing-to-the-app-store/bundling.md)
* Product: **xamarin**
* GitHub Login: @lobrien
* Microsoft Alias: **laobri**

**Comment by conceptdev** [comment]
Screenshots have been updated; thanks for highlighting the issue.
