### ISSUE TITLE
Missing Switch Documentation

### ISSUE THREAD

**Issue by jamesmontemagno** [MicrosoftDocs/xamarin-docs#1314]
Looks like this exists in API docs: https://docs.microsoft.com/en-us/dotnet/api/xamarin.forms.switch?view=xamarin-forms, but it is no where to be found in the User Interface section.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8fdac83c-6d89-7423-b09c-d9a8c7e77d92
* Version Independent ID: 1888bc98-338a-dba3-58bd-96023925b5a7
* Content: [Xamarin.Forms User Interface Views - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/index)
* Content Source: [docs/xamarin-forms/user-interface/index.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/index.md)
* Product: **xamarin**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @jamesmontemagno 

Yes - this is already in our backlog so I'll close the issue here.
