### ISSUE TITLE
Xarmin 

### ISSUE THREAD

**Issue by vcgato29** [MicrosoftDocs/xamarin-docs#1316]
I just started with my development project Opensusefunkymios. Before i use to use libimobiledevice and had in xamp whenever i pluged in idevice it would create my pubic and private keys,pems,my CAs and a guid text for device without the mac. Then i had a virtual machine running el capitan and in  my my mac i had ever social media authentication plugin bundle to connect through ttys or console and open up a term on  both when booting up. this is my first time useing Visual Studipo asnd need help .Can anyone help please. 
Severity	Code	Description	Project	File	Line	Suppression State
Error		NuGet Package restore failed for project XamNativeIoTSuiteDevice.iOS: The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.. Please see Error List window for detailed warnings and errors.				

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c420b152-7303-918a-dbc8-8d1e539c64ec
* Version Independent ID: fe85e24f-c3fc-3763-b1db-6b360fb08067
* Content: [Xamarin.Essentials - Xamarin](https://docs.microsoft.com/en-us/xamarin/essentials/)
* Content Source: [docs/essentials/index.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/essentials/index.md)
* Product: **xamarin**
* GitHub Login: @jamesmontemagno
* Microsoft Alias: **jamont**

**Comment by jamesmontemagno** [comment]
On Windows there is a limit to the length of the folder structure and file path.

Try to copy the code to: "C:/code" or something like that.

**Comment by conceptdev** [comment]
James' suggestion above should solve the issue. We also have a [troubleshooting guide](https://docs.microsoft.com/xamarin/android/troubleshooting/questions/path-too-long-exception) on the error.
