### ISSUE TITLE
BatteryChanged event

### ISSUE THREAD

**Issue by abubakrtaha** [MicrosoftDocs/xamarin-docs#1317]
Using Xamarin.Forms at the moment and the event is now BatteryInfoChanged not BatteryChanged

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 38198725-c8f2-3b90-d179-24f86284c4cb
* Version Independent ID: 1dd34451-25d2-9c50-a7f6-bb5b9f763ba0
* Content: [Xamarin.Essentials: Battery - Xamarin](https://docs.microsoft.com/en-us/xamarin/essentials/battery?context=xamarin%2Fios&tabs=android)
* Content Source: [docs/essentials/battery.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/essentials/battery.md)
* Product: **xamarin**
* GitHub Login: @jamesmontemagno
* Microsoft Alias: **jamont**

**Comment by jamesmontemagno** [comment]
PR in: https://github.com/MicrosoftDocs/xamarin-docs/pull/1320 always feel free to submit a PR :) just hit the edit button up top on the doc
