### ISSUE TITLE
Is there have a snipet code to create bindable property

### ISSUE THREAD

**Issue by nguyenthanhliemfc** [MicrosoftDocs/xamarin-docs#1322]
Thank for your docs!
Is there have a snipet code to create bindable property, accessor, etc?
Thank!

---
#### Chi tiết tài liệu

⚠ *Không chỉnh sửa phần này. Điều này là bắt buộc cho docs.microsoft.com ➟ Vấn đề khi liên kết GitHub.*

* ID: b054a909-6f7f-0b32-5059-eb5c8a9b366b
* Version Independent ID: 723af07b-8f4e-ebe3-a520-99cdcf5efc5a
* Content: [Bindable Properties - Xamarin](https://docs.microsoft.com/vi-vn/xamarin/xamarin-forms/xaml/bindable-properties)
* Content Source: [docs/xamarin-forms/xaml/bindable-properties.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/xaml/bindable-properties.md)
* Product: **xamarin**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @nguyenthanhliemfc 

It's easy enough to create your own. If you're using Visual Studio for Mac, follow [these](https://docs.microsoft.com/visualstudio/mac/snippets) instructions. If you're using Visual Studio 2017, follow [these](https://docs.microsoft.com/visualstudio/ide/walkthrough-creating-a-code-snippet?view=vs-2017) instructions (and perhaps use the propdp snippet as the snippet to modify).

**Comment by nguyenthanhliemfc** [comment]
Thank you!
