### ISSUE TITLE
Please advice users to use ImageSource.FromResource("ID.png"typeof(CURRENTCLASS).GetTypeInfo().Assembly) in 3rd party controls

### ISSUE THREAD

**Issue by MagicAndre1981** [MicrosoftDocs/xamarin-docs#133]
advice users to use ImageSource.FromResource("ID.png",typeof(CURRENTCLASS).GetTypeInfo().Assembly) if they use this in a control/library.

An used 3rd party components failed to load the embedded images for me in Xamarin UWP project (Min/Target 16299 and .net standard 2.0 as code sharing option) for me. I got a 'System.Reflection.TargetException' which was hard for me to debug, even the support of the 3rd party controls had no idea:

https://stackoverflow.com/a/49682890

Adding this ",typeof(CURRENTCLASS).GetTypeInfo().Assembly" to the 3rd party code fixed the control for me.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7eeb0e65-143b-0f5e-a8fb-c75309689338
* Version Independent ID: 6b984264-a950-4310-483f-99f908b0a8b0
* Content: [Images - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/images?tabs=vswin#embedded-images)
* Content Source: [docs/xamarin-forms/user-interface/images.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/images.md)
* Service: **unspecified**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by conceptdev** [comment]
Thanks, this is a good tip. We'll look at add it to the docs shortly.

**Comment by MagicAndre1981** [comment]
ok, I see it is fixed if the 3rd party control uses .net standard 2.0:

https://github.com/xamarin/Xamarin.Forms/pull/1369

But Syncfusion still uses PCL so I still got this issue.

**Comment by conceptdev** [comment]
Thanks for the update, yeah as we all migrate to .NET Standard 2.0 a lot of things become easier!

**Comment by davidbritch** [comment]
Hi @MagicAndre1981 

Thanks for the tip. I've added it to docs in a PR that will be merged within a few days.

Thanks again.
