### ISSUE TITLE
Google App Id code is wrong

### ISSUE THREAD

**Issue by NGumby** [MicrosoftDocs/xamarin-docs#134]
Log.Debug(TAG, "google app id: " + Resource.String.google_app_id);
should be
Log.Debug(TAG, "google app id: " + GetString(Resource.String.google_app_id));

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8d9bfb2a-2e5d-d505-337f-919251a85de3
* Version Independent ID: 695bff64-ae87-8c0f-5616-20b67893fdf0
* Content: [Remote Notifications with Firebase Cloud Messaging - Xamarin](https://docs.microsoft.com/en-us/xamarin/android/data-cloud/google-messaging/remote-notifications-with-fcm?tabs=vswin)
* Content Source: [docs/android/data-cloud/google-messaging/remote-notifications-with-fcm.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/android/data-cloud/google-messaging/remote-notifications-with-fcm.md)
* Service: **unspecified**
* GitHub Login: @mgmclemore
* Microsoft Alias: **mamcle**

**Comment by mgmclemore** [comment]
Hi @NGumby, thanks for your feedback!  I'll make a note to update the topic accordingly.
