### ISSUE TITLE
mainactivity.instance

### ISSUE THREAD

**Issue by alaskanrogue** [MicrosoftDocs/xamarin-docs#1343]
In the Android code sample, MainActivity.Instance is referenced in the line "speaker = new TextToSpeech(MainActivity.Instance, this);". However "Instance" is not defined in "MainActivity". What object should be used as the parameter?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a54f238a-e556-1a51-3ab0-59f6cc525ae0
* Version Independent ID: 7fe8af4e-ff14-6d77-df53-5ffc6c85f4a9
* Content: [Implementing Text-to-Speech - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/dependency-service/text-to-speech)
* Content Source: [docs/xamarin-forms/app-fundamentals/dependency-service/text-to-speech.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/app-fundamentals/dependency-service/text-to-speech.md)
* Product: **xamarin**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by alaskanrogue** [comment]
Answer: To the MainActivity class of the Droid project add:

            internal static MainActivity Instance { get; private set; }

**Comment by davidbritch** [comment]
Hi @alaskanrogue 

Thanks for pointing this out. The sample the doc links to was updated a while ago to include the `Instance` declaration in the **MainActivity** class. However, it looks like the doc wasn't. I'll rectify that today.

**Comment by deepakyogi1995** [comment]
Hello @alaskanrogue 

I used  `internal static MainActivity Instance { get; private set; }` but my web view is null.

`var web_view = MainActivity.Instance.FindViewById<Android.Webkit.WebView>(Resource.Id.webview);`

**Comment by alaskanrogue** [comment]
@deepakyogi1995 Does `Resource.Id.webview` actually exist and have a value? The parent objects? In the current version of the `Resource.Id`, `webview `is not defined. I would try eliminating it.
