### ISSUE TITLE
Wrong link

### ISSUE THREAD

**Issue by Newbilius** [MicrosoftDocs/xamarin-docs#1347]
Link to bug 56111 show message "You are not authorized to access bug #56111."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 617189a6-7bbf-4ed9-946a-e512e4f274ad
* Version Independent ID: 18a0babb-ae99-210e-81b7-85a3504f26c2
* Content: [Troubleshooting Tips - Xamarin](https://docs.microsoft.com/en-us/xamarin/android/troubleshooting/troubleshooting)
* Content Source: [docs/android/troubleshooting/troubleshooting.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/android/troubleshooting/troubleshooting.md)
* Product: **xamarin**
* GitHub Login: @conceptdev
* Microsoft Alias: **crdun**

**Comment by conceptdev** [comment]
Thanks for the advice, that bug system has been shut down so I've removed the link.
