### ISSUE TITLE
Missing Exception handler for FeatureNotEnabledException

### ISSUE THREAD

**Issue by mr5z** [MicrosoftDocs/xamarin-docs#1348]
As seen from [the source line](https://github.com/xamarin/Essentials/blob/master/Xamarin.Essentials/Geolocation/Geolocation.android.cs#L48) in Android. Not sure about in iOS

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f0acf3fa-b705-f0cc-b676-eeca60176dfa
* Version Independent ID: 1788a5d5-a3cb-15c8-927c-b6a24810245a
* Content: [Xamarin.Essentials: Geolocation - Xamarin](https://docs.microsoft.com/en-us/xamarin/essentials/geolocation?tabs=ios)
* Content Source: [docs/essentials/geolocation.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/essentials/geolocation.md)
* Product: **xamarin**
* GitHub Login: @jamesmontemagno
* Microsoft Alias: **jamont**

**Comment by jamesmontemagno** [comment]
PR: https://github.com/MicrosoftDocs/xamarin-docs/pull/1352

Feel free to always hit the edit button on top of the document and send a PR
