### ISSUE TITLE
links of release version from identityserver4 are not working

### ISSUE THREAD

**Issue by PingPongSet** [MicrosoftDocs/xamarin-docs#1349]
Links of release version from identityserver4 are not working. For example, one of the links at this article below is not working

https://identityserver4.readthedocs.io/en/release/quickstarts/0_overview.html

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5d805ca5-97c4-23e4-b635-9de16b6d7f78
* Version Independent ID: ec5b37f1-1bd1-c66e-6461-57c104ed543a
* Content: [Authentication and Authorization - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/enterprise-application-patterns/authentication-and-authorization#authentication)
* Content Source: [docs/xamarin-forms/enterprise-application-patterns/authentication-and-authorization.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/enterprise-application-patterns/authentication-and-authorization.md)
* Product: **xamarin**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @PingPongSet 

Thanks for letting me know. I've just updated the relevant links in a PR, which will go out later.
