### ISSUE TITLE
Not a Good Introduction

### ISSUE THREAD

**Issue by swinterrowd** [MicrosoftDocs/xamarin-docs#135]
I have been looking at this ToDo code for a day or so now and am not impressed with it as an introduction to using a local database with Xamarin Forms. I am attempting to learn the basics of Xamarin Forms with a sqlite database. I am considering changing a WPF project I wrote to run on an Android. I am also trying to determine if Xamarin Forms or Xamarin is the platform I should use. I was under the impression that this sample was supposed to be a simple introduction about how to do this. There does not appear to be any other examples available. As an introduction, this code is to complex. The sample program has way more code than what is needed to grasp the required concepts. There are many modifications and commented out sections in the sample code that make it more difficult to follow than it has to be. For example, what's with the whole text to speech thing and how does that fit into the basic concepts of trying to use a local database? If this code is is supposed to be for learning how to use a local database with Xamarin Forms, dumb it down. Don't make it more complex than it has to be. There is plenty to try and figure out without additional and seemingly needless complexity.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3ab6098a-39c7-151f-124b-f88aa62c4659
* Version Independent ID: dc27c1e4-ff12-c1af-646a-c2617def0bcd
* Content: [Local Databases - Xamarin](https://docs.microsoft.com/en-au/xamarin/xamarin-forms/app-fundamentals/databases#using-sqlite)
* Content Source: [docs/xamarin-forms/app-fundamentals/databases.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/app-fundamentals/databases.md)
* Service: **unspecified**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by conceptdev** [comment]
Thanks @swinterrowd, I received your feedback via https://github.com/MicrosoftDocs/xamarin-docs/issues/83 and will be making sure we address it.

**Comment by swinterrowd** [comment]
Thanks @conceptdev. I wanted to provide some constructive feedback that I hope you guys will consider in your process. It seems to me this "introduction to using a local database" could be broken into a few different scenarios. One scenario could be the asynchronous methodology you use in the given scenario (minus all the unnecessary stuff). A more simple approach would be to show the same sample using non-asynchronous methods. Another example that would have helped me would have been to show how to use a previously existing SQLite database file. I finally figured it out by adding it as an Asset in the Android app and adding a method to the IFileHelper/FileHelper to copy it into the Android app's file structure. However, that required me to extrapolate data and techniques from many different internet sites. I want to use Xamarin Forms for this project because of my previous WPF/XAML experience. Apparently, the Xamarin Forms/Portable Class Library thing is moving fast. Some of the methods I found being suggested are deprecated and the documentation and training seems to be lagging behind. I am still trying to figure it all out. This sample was a big help to me. However, I wanted you to know how I think it could be better.

**Comment by conceptdev** [comment]
That's useful additional context. We have two pieces of work in progress to address some of this: we're going to try and simplify _this_ doc for the first-timer (per your initial suggestion) and we are also working to update everything to .NET Standard. The PCL > .NET Standard shift has definitely been a big one.

After that, those other suggestions: async, and shipping/loading an existing db; are both things we can consider adding. Once again, appreciate your input.
