### ISSUE TITLE
Cannot find these methods in eShopContainer code

### ISSUE THREAD

**Issue by PingPongSet** [MicrosoftDocs/xamarin-docs#1351]
I cannot see any of these methods in eShopContainer code:
AddInMemoryApiResources
AddInMemoryIdentityResources
AddInMemoryClients
Code under section Configuring IdentityServer to Perform Authorization

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5d805ca5-97c4-23e4-b635-9de16b6d7f78
* Version Independent ID: ec5b37f1-1bd1-c66e-6461-57c104ed543a
* Content: [Authentication and Authorization - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/enterprise-application-patterns/authentication-and-authorization)
* Content Source: [docs/xamarin-forms/enterprise-application-patterns/authentication-and-authorization.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/enterprise-application-patterns/authentication-and-authorization.md)
* Product: **xamarin**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @PingPongSet 

eShopOnContainers is an active development project, and so the code is constantly changing. We've got an issue in our backlog to update these docs, so I'll close the issue here for now.
