### ISSUE TITLE
Quickstart and Deep Dive Reference Two Different Projects

### ISSUE THREAD

**Issue by sambasile** [MicrosoftDocs/xamarin-docs#1353]
The Quickstart project is "Notes" while the Deep Dive references Phoneword.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 540c35eb-3db5-7e73-e6eb-07c4b70df1b0
* Version Independent ID: d8bd33e1-164d-2b2a-75de-42a95c75e6ad
* Content: [Xamarin.Forms Deep Dive - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/get-started/hello-xamarin-forms/deepdive?pivots=windows)
* Content Source: [docs/xamarin-forms/get-started/hello-xamarin-forms/deepdive.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/get-started/hello-xamarin-forms/deepdive.md)
* Product: **xamarin**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by sambasile** [comment]
Sorry, a copy of https://github.com/MicrosoftDocs/xamarin-docs/issues/1277.

Why is this closed if the issue has not been completely resolved?

**Comment by conceptdev** [comment]
Thanks for your feedback @sambasile. The updated content mentioned in https://github.com/MicrosoftDocs/xamarin-docs/issues/1277 will be published soon, at which time the Phoneword sample will be completely removed and prevent further confusion.
