### ISSUE TITLE
PathTooLongException not resolved

### ISSUE THREAD

**Issue by Gioele-Bencivenga** [MicrosoftDocs/xamarin-docs#1359]
I tried both methods with a newly created project, both of them have failed in solving my error and it's still impossible for me to create a working Xamarin.Forms project.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 500cca09-76fd-5df5-6bd9-90cc51fae84d
* Version Independent ID: 3a9bfdcc-ac3a-6cdf-ab20-9fc425c56b71
* Content: [How do I resolve a PathTooLongException error? - Xamarin](https://docs.microsoft.com/en-us/xamarin/android/troubleshooting/questions/path-too-long-exception)
* Content Source: [docs/android/troubleshooting/questions/path-too-long-exception.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/android/troubleshooting/questions/path-too-long-exception.md)
* Product: **xamarin**
* GitHub Login: @conceptdev
* Microsoft Alias: **crdun**

**Comment by conceptdev** [comment]
You could also try creating your solution in a short path, like **C:/App/**.

If that also fails, please [report the problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio-2017) in Visual Studio.
