### ISSUE TITLE
Video and documentation needs updating, Xamarin.Forms.AppLinks package has changed

### ISSUE THREAD

**Issue by faceoffers28** [MicrosoftDocs/xamarin-docs#136]
I updated from Xamarin.Forms.AppLinks 2.4.0.282 to 2.5.0.280555. In doing so, Xamarin.Firebase.AppIndexing 42.1021.1 was installed.

I'm now getting this error. Java.Lang.IllegalStateException: Default FirebaseApp is not initialized in this process com.domainname.appname. Make sure to call FirebaseApp.initializeApp(Context)

There are no instructions here (see link below) and I really can't find any official Xamarin or Microsoft documentation that explains the change or what to do.

https://github.com/xamarin/Xamarin.Forms/tree/master/Xamarin.Forms.Platform.Android.AppLinks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3bba007d-2548-dfbf-a582-2994d2469f97
* Version Independent ID: 4c57e20a-3f37-5e18-a57e-3e095e6f53c8
* Content: [Application Indexing and Deep Linking - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/platform/deep-linking)
* Content Source: [docs/xamarin-forms/platform/deep-linking.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/platform/deep-linking.md)
* Service: **unspecified**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by faceoffers28** [comment]
I add this FirebaseApp.InitializeApp(this); to my OnCreate method.

AndroidAppLinks.Init(this);
FirebaseApp.InitializeApp(this);

I'm now getting this exception on the AndroidAppLinks.Init(this); line of code.

System.TypeLoadException: Could not load type of field 'Xamarin.Forms.Platform.Android.AppLinks.AndroidAppLinks:_client' (0) due to: Could not resolve type with token 01000013 (from typeref, class/assembly Android.Gms.Common.Apis.GoogleApiClient, Xamarin.GooglePlayServices.Basement, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null) assembly:Xamarin.GooglePlayServices.Basement, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null type:Android.Gms.Common.Apis.GoogleApiClient member:<none>

I was running Xamarin.Forms.AppLinks 2.4.0.282 using Visual Studio 2015 Enterprise and Xamarin.Android 7.1.0.43 and everything was working just fine.

I upgraded to Visual Studio 2017 Enterprise and Xamarin.Android 8.2.0.16 (HEAD/a78295902). That's when I started seeing issues with Xamarin.Forms.AppLinks 2.4.0.282, Xamarin.GooglePlayServices.AppIndexing 29.0.0.1, Xamarin.GooglePlayServices.Base 29.0.0.1 andXamarin.GooglePlayServices.Basement 29.0.0.1. I updated to Xamarin.Forms.AppLinks 2.5.0.280555 and now I'm running into all sorts of problems.

My Target Framework is  Android 7.1.

**Comment by conceptdev** [comment]
@faceoffers28 thanks for the additional info and bug link. We'll update the docs and sample, taking that information into account. Really appreciate you taking the time to look into it in such detail.

**Comment by faceoffers28** [comment]
@conceptdev Here is another bug. https://bugzilla.xamarin.com/show_bug.cgi?id=60907 I am experiencing the same problem as this guy. 

https://forums.xamarin.com/discussion/107391/new-version-of-applinks-registerlink-didnt-work-on-android

https://forums.xamarin.com/discussion/125062/xamarin-forms-applinks-no-longer-working-correctly-after-upgrade

**Comment by faceoffers28** [comment]
@conceptdev Do you know if the Deep Linking Android indexing bug has been addressed in a recent release of either Xamarin.Forms or Xamarin.Forms.AppLinks? I looked at all the GitHub issues and read the Xamarin.Forms release notes, but I could not find anything. I also did not find a comment in BugZilla that would indicate where it is now being tracked. Thanks!

**Comment by conceptdev** [comment]
I have not seen any mention of AppLinks recently. The [Xamarin.Forms GitHub repo](https://github.com/xamarin/xamarin.forms) is probably the best place to track, since you can see the issues list and also commits on the feature.
