### ISSUE TITLE
Live Player: Visualization Error

### ISSUE THREAD

**Issue by pldeschamps** [MicrosoftDocs/xamarin-docs#1363]
Xamarin Live Player did never work.

VS community 2017 Version 15.9.4
Live Player Version 1.5.241 (741)

In IDE :
Built with 0 message
Deploy to HUAWEI ANE-LX1 Player succeded

In Live Player:
Visualization Error
Assembly must be a runtime Assembly object.
(ArgumentException)

Any idea how to solve this issue?

**Comment by conceptdev** [comment]
Hi @pldeschamps please report bugs or product issues [from within Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio-2017), so that our team gets all relevant environment information.

Please note that Live Player is a Preview technology.
