### ISSUE TITLE
Azure AppCenter - Documention  for Xamarin.Forms Android

### ISSUE THREAD

**Issue by ericbrunner** [MicrosoftDocs/xamarin-docs#1364]
Please add some reference documention on how to sign an android XF app in AppCenter usung Azure DevOps as repository. You have ro add the signing key file to your repisitory and commit it in the Azure DevOps repo. Then in AppCentrr you have to select the signing key. Remember to note doen on a secure place your entered credentials while creation of the signing key. 

Simething like that in conext of the Xamarin.Forms developer usung Azure DevOps + Azure AppCenter + Xamarin.Forms

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d22ceddd-69d4-3a5d-2947-a5abddbbd3aa
* Version Independent ID: e238051f-b809-5541-4049-f1205dd0a3a5
* Content: [Signing the Android Application Package - Xamarin](https://docs.microsoft.com/en-us/xamarin/android/deploy-test/signing/?tabs=windows)
* Content Source: [docs/android/deploy-test/signing/index.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/android/deploy-test/signing/index.md)
* Product: **xamarin**
* GitHub Login: @conceptdev
* Microsoft Alias: **crdun**

**Comment by conceptdev** [comment]
Hi @ericbrunner, thanks for your feedback. This sounds like a great suggestion for the [App Center docs](https://docs.microsoft.com/appcenter/), since it is product specific I'm not sure it belongs here in the general guidance.

**Comment by ericbrunner** [comment]
Well as a developer a look first in the domain where I develop and that is XF. A cross reference in both areas would be the best fit.
