### ISSUE TITLE
Absolutlely useless documentation

### ISSUE THREAD

**Issue by Hopfenspirger** [MicrosoftDocs/xamarin-docs#1365]
A documentation repeating the name of the function in more words is absolutely useless!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7c1f2b61-3eb5-c9b3-11bb-7294c4fed8d8
* Version Independent ID: cbd69f97-2e1f-d337-2e1b-dd9eff2a31a3
* Content: [IWKUrlSchemeTask.DidReceiveResponse(NSUrlResponse) Method (WebKit)](https://docs.microsoft.com/en-us/dotnet/api/webkit.iwkurlschemetask.didreceiveresponse?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev15.query%3FappId%3DDev15IDEF1%26l%3DEN-US%26k%3Dk(WebKit.IWKUrlSchemeTask.DidReceiveResponse)%3Bk(TargetFrameworkMoniker-Xamarin.iOS%2CVersion%3Dv1.0)%3Bk(DevLang-csharp)%26rd%3Dtrue)
* Content Source: [en/WebKit/IWKUrlSchemeTask.xml](https://github.com/xamarin/apple-api-docs/blob/live/en/WebKit/IWKUrlSchemeTask.xml)
* Product: **xamarin**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by conceptdev** [comment]
Thanks for your feedback @Hopfenspirger. The iOS SDK surface is very large, and we do our best to provide relevant info for each API. I'll pass on your suggestion about the article link.
