### ISSUE TITLE
How to use this library

### ISSUE THREAD

**Issue by MilkBiscuit** [MicrosoftDocs/xamarin-docs#1366]
After creating a .NET Standard Library, how do I import it in a Xamarin.Forms Project?
Isn't this the most important thing?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 483b01c5-75b5-a35b-c90c-c564535416f1
* Version Independent ID: dc8b1e89-e8f9-0e50-5d4d-248ccdab9c91
* Content: [Use .NET Standard Libraries to Share Code - Xamarin](https://docs.microsoft.com/en-us/xamarin/cross-platform/app-fundamentals/net-standard?tabs=macos)
* Content Source: [docs/cross-platform/app-fundamentals/net-standard.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/cross-platform/app-fundamentals/net-standard.md)
* Product: **xamarin**
* GitHub Login: @conceptdev
* Microsoft Alias: **crdun**

**Comment by conceptdev** [comment]
You can use the project references feature of Visual Studio to reference any compatible project type from any other project. This includes a Xamarin.Forms project referencing a .NET Standard library. 

Note that when you create a new Xamarin.Forms project, it already includes a .NET Standard library that contains the default `App` class and initial page. You can just add your shared code to this project, without needing additional .NET Standard projects.

A description of how to manage project references is in the [Visual Studio documentation](https://docs.microsoft.com/visualstudio/ide/how-to-add-or-remove-references-by-using-the-reference-manager?view=vs-2017#projects-tab).
