### ISSUE TITLE
add sidenote about Device.BeginInvokeOnMainThread?

### ISSUE THREAD

**Issue by knocte** [MicrosoftDocs/xamarin-docs#1368]
I liked the section that starts with "You might wonder if you should check if code is running on a secondary thread before calling BeginInvokeOnMainThread", and I was wondering, if this also applies to Xamarin.Forms.Device.BeginInvokeOnMainThread? would be nice to add a sidenote about it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 86178166-6c3e-2168-7764-4a4f8573a9c5
* Version Independent ID: dd3987de-9fc6-f84c-c68c-a50c9f6c57f5
* Content: [Xamarin.Essentials: MainThread - Xamarin](https://docs.microsoft.com/en-us/xamarin/essentials/main-thread#feedback)
* Content Source: [docs/essentials/main-thread.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/essentials/main-thread.md)
* Product: **xamarin**
* GitHub Login: @jamesmontemagno
* Microsoft Alias: **jamont**

**Comment by FreakyAli** [comment]
Yes, it applies to Xamarin.Forms.Device.BeginInvokeOnMainThread as well, And yes Microsoft should add this bit as a sidenote but without Xamarin Essentials you would have to come up with our own version of IsMainThread implementation on all the required OS, which could be a pain in the neck for a newbie XF user...

**Comment by knocte** [comment]
That is not the point, because after that paragraph and showing the IsMainThread usage in a code snippet, it says later "However, this check is not necessary." It is simply not clear if this statement is true for Xamarin.Forms as well.

**Comment by jamesmontemagno** [comment]
No need as BeginInvokeOnMain thread checks it for you.

**Comment by knocte** [comment]
> No need as BeginInvokeOnMain thread checks it for you.

But the point of filing this bug is to put this info in the docs, why do you close this issue?
