### ISSUE TITLE
DataTemplate for ListView does not have to be a ViewCell derived type

### ISSUE THREAD

**Issue by Krumelur** [MicrosoftDocs/xamarin-docs#1369]
In chapter "Creating an inline template" (https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/templates/data-templates/creating#creating-an-inline-datatemplate) it is stated:

"The child of an inline DataTemplate must be of, or derive from, type ViewCell."

That's not completely right. The type that is required is just "Cell", not "ViewCell". For example, you can create a data template using "TextCell" as the type. "TextCell" is deriving from "Cell" and not "ViewCell".

Reference: https://github.com/xamarin/Xamarin.Forms/blob/master/Xamarin.Forms.Core/Cells/TextCell.cs#L6

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 17bb2db5-a734-9c3d-68b7-4ae00bbcbfd5
* Version Independent ID: 3d7221f5-1db1-eeca-4383-777ce2022296
* Content: [Creating a Xamarin.Forms DataTemplate - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/templates/data-templates/creating#creating-an-inline-datatemplate)
* Content Source: [docs/xamarin-forms/app-fundamentals/templates/data-templates/creating.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/app-fundamentals/templates/data-templates/creating.md)
* Product: **xamarin**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @Krumelur 

Fixed in a PR that'll go out later.
