### ISSUE TITLE
Instructions not working

### ISSUE THREAD

**Issue by jpvosloo** [MicrosoftDocs/xamarin-docs#137]
Please correct the list of requirements for the instructions on this page, as it is currently it misleads the reader.
This page states the only requirement is: "your Xamarin.iOS for Visual Studio installation requires a connection to a networked Mac OS X computer"

This is not correct because the following page has a different set of requirements:
https://docs.microsoft.com/en-au/xamarin/ios/get-started/installation/windows/index

Mac
A Mac running macOS Sierra (10.12) or higher (although the latest stable version is recommended).
Xamarin iOS SDK. This is installed when downloading Visual Studio for Mac
Apple’s Xcode IDE and iOS SDK (The latest stable version from the Mac App Store is recommended).
The Windows computer must be able to reach the Mac via the network.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 98c96bcc-1743-8d9f-f1b2-3c30d5b2a6e2
* Version Independent ID: f57a6157-332a-3f31-c785-7efa99e62711
* Content: [Connecting to the Mac - Xamarin](https://docs.microsoft.com/en-au/xamarin/ios/get-started/installation/windows/connecting-to-mac/)
* Content Source: [docs/ios/get-started/installation/windows/connecting-to-mac/index.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/ios/get-started/installation/windows/connecting-to-mac/index.md)
* Service: **unspecified**
* GitHub Login: @bradumbaugh
* Microsoft Alias: **brumbaug**

**Comment by conceptdev** [comment]
Thanks @jpvosloo - macOS is the correct requirement. There is already an update in progress for this doc that will address your concern, it will be published soon.
