### ISSUE TITLE
Xamarin Mac and uwp support

### ISSUE THREAD

**Issue by mdonogma** [MicrosoftDocs/xamarin-docs#1370]
Xamarin Mac and uwp support? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e8eebbec-c116-fa16-14f3-83e5905e28b2
* Version Independent ID: 9124edfa-2df2-0ef2-6722-0efc0e1134da
* Content: [Xamarin.Forms Shell - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/shell?tabs=ios)
* Content Source: [docs/xamarin-forms/app-fundamentals/shell.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/app-fundamentals/shell.md)
* Product: **xamarin**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @mdonogma 

Afraid it's iOS and Android only at the moment. You can register your interest in other platforms on the [Shell spec](https://github.com/xamarin/Xamarin.Forms/issues/2415).
