### ISSUE TITLE
Tab image size

### ISSUE THREAD

**Issue by dmitrymal** [MicrosoftDocs/xamarin-docs#1371]
Could you clarify the section that talks about the Tab image sizes? The section in this document says the sizes should be 30px, 60px for @2x or 90px for @3x. 
The apple documentation suggests something different: https://developer.apple.com/design/human-interface-guidelines/ios/icons-and-images/custom-icons/
What should it be?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8853aece-5bbb-6121-ce6d-f600719ad820
* Version Independent ID: 8037b07e-5bdd-390c-e3be-b3c9233d5249
* Content: [Tab Bars and Tab Bar Controllers in Xamarin.iOS - Xamarin](https://docs.microsoft.com/en-us/xamarin/ios/user-interface/controls/creating-tabbed-applications#feedback)
* Content Source: [docs/ios/user-interface/controls/creating-tabbed-applications.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/ios/user-interface/controls/creating-tabbed-applications.md)
* Product: **xamarin**
* GitHub Login: @lobrien
* Microsoft Alias: **laobri**

**Comment by conceptdev** [comment]
Thanks for your feedback @dmitrymal - I'm sure the Apple-specified values are most correct. Our suggestion was probably intended to be a simple guideline that worked for most situations, and is pretty close to Apple's bounds for tall/wide glyphs (31pt and 28pt respectively).

This is a useful link that you've included - we'll update the doc with this more specific information, to help other readers in future. Thanks again!

**Comment by conceptdev** [comment]
Page was updated with the link you provided, thanks.
