### ISSUE TITLE
Public fields

### ISSUE THREAD

**Issue by vpkopylov** [MicrosoftDocs/xamarin-docs#1372]
Why do we have mPhotoID and mCaption public fields in the Photo class? Maybe it's better to replace them with readonly-properties and set them in the constructor?
Same question mPhotoAlbum field in the PhotoAlbumAdapter class.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9019c299-4a90-bc6a-0eb8-1259d0a49aa9
* Version Independent ID: 7883af21-d4ae-4f9c-ecc9-0123f1d81a3e
* Content: [A Basic RecyclerView Example - Xamarin](https://docs.microsoft.com/en-us/xamarin/android/user-interface/layouts/recycler-view/recyclerview-example)
* Content Source: [docs/android/user-interface/layouts/recycler-view/recyclerview-example.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/android/user-interface/layouts/recycler-view/recyclerview-example.md)
* Product: **xamarin**
* GitHub Login: @conceptdev
* Microsoft Alias: **crdun**

**Comment by conceptdev** [comment]
@vpkopylov you're right, it's not good encapsulation. I made some minor changes in [this PR](https://github.com/xamarin/monodroid-samples/pull/310/) that addresses your feedback. Thanks for commenting.
