### ISSUE TITLE
"Sliders, Steppers, and Segmented Controls" Link

### ISSUE THREAD

**Issue by DigitalNut** [MicrosoftDocs/xamarin-docs#1374]
"Sliders, Steppers, and Segmented Controls" link...should this be "Sliders, Switches, and Segmented Controls" (Steppers -&gt; Switches). When you click the link it takes you to a page with the title: "Sliders, Switches, and Segmented Controls"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: efb29e1f-1b2e-29bc-a8e7-98ea2fc01a1e
* Version Independent ID: 929dac6f-c184-8375-668d-1ad93b68ffca
* Content: [User Interface Controls in Xamarin.iOS - Xamarin](https://docs.microsoft.com/en-us/xamarin/ios/user-interface/controls/index)
* Content Source: [docs/ios/user-interface/controls/index.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/ios/user-interface/controls/index.md)
* Product: **xamarin**
* GitHub Login: @lobrien
* Microsoft Alias: **laobri**

**Comment by conceptdev** [comment]
@DigitalNut yeah, I think you're right! Thanks for the note, fixing it now.
