### ISSUE TITLE
Why isn't this linked in the Getting Started section?

### ISSUE THREAD

**Issue by kkarakk** [MicrosoftDocs/xamarin-docs#1379]
Can you put a link to this content in the getting started section? Would be really helpful...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 298f0c2c-4109-c641-7cf8-47edb36452bf
* Version Independent ID: 097b0a43-3081-221b-8e07-e6f692ccdc41
* Content: [Xamarin.Essentials: Troubleshooting - Xamarin](https://docs.microsoft.com/en-us/xamarin/essentials/troubleshooting?context=xamarin/ios)
* Content Source: [docs/essentials/troubleshooting.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/essentials/troubleshooting.md)
* Product: **xamarin**
* GitHub Login: @jamesmontemagno
* Microsoft Alias: **jamont**

**Comment by jamesmontemagno** [comment]
It is in the Android section for installing the nuget. maybe we can link it at the bottom? Would that be more discoverable?

**Comment by conceptdev** [comment]
As James said, there _is_ a link in the Android setup info, which is the main relevant place it would be needed.
