### ISSUE TITLE
Please mention how to get Notification when running Xamarin.Mac as a console application

### ISSUE THREAD

**Issue by rakshith-ravi** [MicrosoftDocs/xamarin-docs#1381]
I'm using this tutorial:
https://docs.microsoft.com/en-us/xamarin/mac/app-fundamentals/console

I'm trying to get an application to run in the background and show a notification on start. The notification call throws an NullPointerException when I try to run it. So I tried adding `NSApplication.Main(args)` to the code, and it says `mono[8582:331438] No Info.plist file in application bundle or no NSPrincipalClass in the Info.plist file, exiting`. 

Please mention how to make Xamarin calls from a console application to this documentation

**Comment by conceptdev** [comment]
@rakshith-ravi the fourth paragraph on the page says:

> Headless applications do not need a user interface, **and do not need to run as part of an application bundle.**

If you wish to access macOS user-interface elements, you should probably create a regular Xamarin.Mac Cocoa app.
