### ISSUE TITLE
Connectivity working but not as expected.

### ISSUE THREAD

**Issue by Swdvader** [MicrosoftDocs/xamarin-docs#1385]
Connectivity working but not as expected.
I installed Xamarin Essentials 1.01.  When testing the Connectivity I am finding the following.
When I switch to Airplane mode it will display local.  If check the status again it will show none. 
If i put a 1 sec sleep at the top of the connectivity changed it works correctly. It looks like when I go into airplane mode the phone makes two changes.  It will go from internet to local and then local to none once airplane mode is turned on.  The first change to locaI is triggering a connectivity change so I see local, but the second change to none doesn't trigger the event again so even though its none I am not getting that response unless I recheck the values.  Am I doing something wrong or is the delay the only solutions?

 private void Connectivity_ConnectivityChanged(object sender, ConnectivityChangedEventArgs e)
        {
            System.Threading.Thread.Sleep(1000);

Device is Galaxy s9+ android.

**Comment by conceptdev** [comment]
Thanks for your feedback @Swdvader. This sounds like a product issue, which you can raise by clicking [Product feedback](https://github.com/xamarin/Essentials/blob/master/PRODUCT-FEEDBACK.md) at the end of the [Connectivity doc](https://docs.microsoft.com/en-us/xamarin/essentials/connectivity).
