### ISSUE TITLE
StackPanel or StakLayout on MainPage.xaml?

### ISSUE THREAD

**Issue by jeongjoonl** [MicrosoftDocs/xamarin-docs#1386]
Step 5 says, Edit MainPage.xaml, adding this XAML before the end of the &lt;/StackPanel&gt;
But the blank template shows &lt;StackLayout&gt; instead of the &lt;StackPanel&gt;

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b4445585-af8f-09d3-5d35-762c3aac187b
* Version Independent ID: fa9263db-60d6-eb98-eb74-842351ba5387
* Content: [Build your first Xamarin.Forms app - Xamarin](https://docs.microsoft.com/en-us/xamarin/get-started/first-app/?pivots=windows)
* Content Source: [docs/get-started/first-app/index.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/get-started/first-app/index.md)
* Product: **xamarin**
* GitHub Login: @conceptdev
* Microsoft Alias: **crdun**

**Comment by conceptdev** [comment]
Thanks @jeongjoonl you are correct. Just fixing it now.
