### ISSUE TITLE
request for clarity re vs versions

### ISSUE THREAD

**Issue by petemidg32** [MicrosoftDocs/xamarin-docs#1388]
I have vs2015 and no access to vs versions above that; it would therefore be very useful to know the points at which xamarin versions should not be updated to if using vs2015. I have found the hard way that things break and it is very hard to get things back where they are working; however if development of android/ios apps at the current store levels is going to be impossible at vs2015 I need to know that too.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d2371968-1e20-6e4c-09f4-b9420df331ea
* Version Independent ID: cd24b40c-ac2a-eec0-bda9-46d30053d8a7
* Content: [Xamarin.Forms Requirements - Xamarin](https://docs.microsoft.com/en-us/xamarin/get-started/installation?tabs=windows#android)
* Content Source: [docs/get-started/installation.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/get-started/installation.md)
* Product: **xamarin**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by pierceboggan** [comment]
Hi!

Thanks for the feedback, and great question! When using Xamarin in Visual Studio 2015, you'll be using the [version 15.6 release](https://releases.xamarin.com/release-15-7/) of Xamarin. If you wish to use versions higher than 15.6 (released spring 2018), you will need to use Visual Studio 2017. If you qualify, there is a [free community edition of Visual Studio 2017](https://visualstudio.microsoft.com/downloads/), which includes our latest releases with support for the latest-and-greatest.

Thanks,
Pierce Boggan
