### ISSUE TITLE
Documentation not up to date

### ISSUE THREAD

**Issue by SaskiaL** [MicrosoftDocs/xamarin-docs#1389]
The documentation mentions SqliteConnection.SetConfig(SQLiteConfig.Serialized);
But the sqlite-net-pcl package doesn't have this method.
I would like to know how to configure my database to use multiple threads.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c07438f1-7799-35a5-c6aa-86ce411694b1
* Version Independent ID: 7d3ccdcd-5165-99cf-9184-dcc966dbd25e
* Content: [Using SQLite.NET with Android - Xamarin](https://docs.microsoft.com/en-us/xamarin/android/data-cloud/data-access/using-sqlite-orm)
* Content Source: [docs/android/data-cloud/data-access/using-sqlite-orm.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/android/data-cloud/data-access/using-sqlite-orm.md)
* Product: **xamarin**
* GitHub Login: @conceptdev
* Microsoft Alias: **crdun**

**Comment by conceptdev** [comment]
Hi @SaskiaL it seems like the documentation is not specific enough. The type `SqliteConnection` is actually in the `Mono.Data.Sqlite` namespace, so you can either add 

```
using Mono.Data.Sqlite;
```

to the top of your code file, or specify it explicitly, like this:

```csharp
Mono.Data.Sqlite.SqliteConnection.SetConfig(Mono.Data.Sqlite.SQLiteConfig.Serialized);
```

For information on asynchronous access, see this [Xamarin.Forms local databases page](https://docs.microsoft.com/xamarin/xamarin-forms/app-fundamentals/databases), which also applies to Android projects.
