### ISSUE TITLE
Galaxy not listed in physical devices drop down

### ISSUE THREAD

**Issue by Triwaters** [MicrosoftDocs/xamarin-docs#139]
Why is that? I'm confused. Something I don't understand about Galaxy phones? Are they on this list by another name?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77921f62-3d69-ff6e-57a8-ebe4bffde990
* Version Independent ID: d12d0c6d-5e03-533e-a6cc-fe940ff18206
* Content: [Xamarin Android Device Manager - Xamarin](https://docs.microsoft.com/en-us/xamarin/android/get-started/installation/android-emulator/xamarin-device-manager?tabs=vswin)
* Content Source: [docs/android/get-started/installation/android-emulator/xamarin-device-manager.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/android/get-started/installation/android-emulator/xamarin-device-manager.md)
* Service: **unspecified**
* GitHub Login: @mgmclemore
* Microsoft Alias: **mamcle**

**Comment by mgmclemore** [comment]
Hi @Triwaters, thanks for the feedback. Galaxy devices are listed as **Galaxy Nexus** and **4.65" 720p (Galaxy Nexus)** in the device drop-down. If you think you've found a bug, it's best to file it [here](https://github.com/xamarin/xamarin-android/issues) (the **xamarin-docs** repo is for feedback about documentation). Hope this helps.
