### ISSUE TITLE
How do I resolve a PathTooLongException error?

### ISSUE THREAD

**Issue by nbi1** [MicrosoftDocs/xamarin-docs#1390]
I nearly fell off my chair when I saw: 
https://docs.microsoft.com/en-us/xamarin/android/troubleshooting/questions/path-too-long-exception
Is this a joke? Don't try to get the end user involved in poorly thought out hacks. Fix this in your software so that it doesn't happen in the first place!!!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 500cca09-76fd-5df5-6bd9-90cc51fae84d
* Version Independent ID: 3a9bfdcc-ac3a-6cdf-ab20-9fc425c56b71
* Content: [How do I resolve a PathTooLongException error? - Xamarin](https://docs.microsoft.com/en-us/xamarin/android/troubleshooting/questions/path-too-long-exception)
* Content Source: [docs/android/troubleshooting/questions/path-too-long-exception.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/android/troubleshooting/questions/path-too-long-exception.md)
* Product: **xamarin**
* GitHub Login: @conceptdev
* Microsoft Alias: **crdun**

**Comment by conceptdev** [comment]
As the [linked article](https://docs.microsoft.com/en-us/windows/desktop/FileIO/naming-a-file) explains, the 260 character limit is a Windows limitation.

We have no control over the naming or depth that a customer may choose when creating their directories and projects, and [explained in the article](https://docs.microsoft.com/en-us/xamarin/android/troubleshooting/questions/path-too-long-exception#fix) we are doing our best to fix the issue (as it affects Xamarin.Android developers) with this troubleshooting tip. Our tools interact with products from other sources (such as the Android SDK), so we must work within some limitations. 

Thanks for your feedback.
