### ISSUE TITLE
Publishing via App Center is missing

### ISSUE THREAD

**Issue by kkarakk** [MicrosoftDocs/xamarin-docs#1391]
Isn't Appcenter an MS product? why isn't there atleast a link on how to publish via it?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d9425655-db7a-8e59-d0a0-ca6e1b8d3368
* Version Independent ID: edef2fc1-404a-e385-0a57-48184d70b067
* Content: [Publishing an Application - Xamarin](https://docs.microsoft.com/en-us/xamarin/android/deploy-test/publishing/)
* Content Source: [docs/android/deploy-test/publishing/index.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/android/deploy-test/publishing/index.md)
* Product: **xamarin**
* GitHub Login: @conceptdev
* Microsoft Alias: **crdun**

**Comment by conceptdev** [comment]
Thanks for the suggestion, adding now.
