### ISSUE TITLE
Please update the reference link for the "Binding from a Control Template" topic?

### ISSUE THREAD

**Issue by mshwf** [MicrosoftDocs/xamarin-docs#1393]
The ref link in the page goes to a "404 - Page not found" page

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4aad53c7-7e3e-9018-9781-060d9cab9e6c
* Version Independent ID: d78c65af-9f3d-8871-b486-fba96b39247d
* Content: [Consuming XAML Markup Extensions - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/xaml/markup-extensions/consuming)
* Content Source: [docs/xamarin-forms/xaml/markup-extensions/consuming.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/xaml/markup-extensions/consuming.md)
* Product: **xamarin**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by conceptdev** [comment]
Thanks for letting us know, fixing now.
