### ISSUE TITLE
Do we must implement Xamarin.Auth in CustomRenderer?

### ISSUE THREAD

**Issue by nguyenthanhliemfc** [MicrosoftDocs/xamarin-docs#1395]
Hi! I'm working with Xamarin.Forms, as the title. Do we must implement Xamarin.Auth in CustomRenderer?
Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aa8bb9e0-5898-0d11-0213-fd4d8c8d0297
* Version Independent ID: 2f46e1f7-164f-2f32-70c0-f28919d16c5c
* Content: [Authenticating Users with an Identity Provider - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/data-cloud/authentication/oauth)
* Content Source: [docs/xamarin-forms/data-cloud/authentication/oauth.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/data-cloud/authentication/oauth.md)
* Product: **xamarin**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by conceptdev** [comment]
There is a sample [linked at the start and end of the page](https://developer.xamarin.com/samples/xamarin-forms/WebServices/OAuthNativeFlow/), it does not appear to use a custom renderer, however platform-specific code is required in both the iOS and Android projects (such as the initialization code on both platforms, the `OpenUrl` method on iOS, and `CustomUrlSchemeInterceptorActivity` on Android).

**Comment by nguyenthanhliemfc** [comment]
Thank you Sir!
Is there any update for this package, it's too long from last update?
