### ISSUE TITLE
error in set FontFamily for Android

### ISSUE THREAD

**Issue by Mohsnb** [MicrosoftDocs/xamarin-docs#1399]
When set `FontFamily` to Android needed name, when type '#' in name then error in Design panel :
![fontfamily](https://user-images.githubusercontent.com/25475989/52519411-36459580-2c70-11e9-8b53-d9b671458911.png)

example code :
`<Setter Property="FontFamily" Value="Vazir.ttf#Vazir"/>`

**Comment by conceptdev** [comment]
Hi @Mohsnb thanks for your feedback. Please report this bug [using Visual Studio's reporting feature](https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio-2017) which will supply our team with additional information that will help to diagnose and fix the problem. Thanks!
