### ISSUE TITLE
Support for Spanish documentation

### ISSUE THREAD

**Issue by DarryStonem** [MicrosoftDocs/xamarin-docs#14]
Support for Spanish documentation as the other `MicrosoftDocs` documentation.

**Comment by conceptdev** [comment]
Hi @DarryStonem, you can choose Spanish – Español (España) – from the language menu in the footer of each page, or use this link:

https://docs.microsoft.com/es-es/xamarin/

**Comment by DarryStonem** [comment]
Yes, I know I can do that. But maybe something like this other project: [https://github.com/MicrosoftDocs/azure-docs.es-es](https://github.com/MicrosoftDocs/azure-docs.es-es) ?

**Comment by conceptdev** [comment]
Ok, thanks @DarryStonem. We are investigating open-sourcing the localized content in a future release.

**Comment by conceptdev** [comment]
The Edit button (Editar) should now appear on the Spanish content.

**Comment by DarryStonem** [comment]
@conceptdev Awesome! Thanks!
