### ISSUE TITLE
https://docs.microsoft.com/xamarin/ios/internals/limitations page needs updating

### ISSUE THREAD

**Issue by marek-safar** [MicrosoftDocs/xamarin-docs#140]
### The section Reverse Callbacks needs updating

The link points to url which does not exist (https://developer.xamarin.com/api/type/ObjCRuntime.MonoPInvokeCallbackAttribute)

### The missing section about MonoNativeFunctionWrapperAttribute

You could copy it from https://developer.xamarin.com/api/type/MonoMac.MonoNativeFunctionWrapperAttribute/

but update it as we should recommend using `UnmanagedFunctionPointerAttribute` attribute instead which is cross-platform and works with netstandard as well.

#130 is similar issue

**Comment by bradumbaugh** [comment]
Thanks @marek-safar.

- The first link (which is correct) will resolve as expected once another internal issue is fixed: https://github.com/xamarin/ios-api-docs/issues/53.
- I've put together a PR for the second issue; that is currently pending review.

Thanks for your help!

**Comment by bradumbaugh** [comment]
- Fixed [with this commit](https://github.com/MicrosoftDocs/xamarin-docs-pr/commit/22aab53d1b7d00bdda67edcd84840fb33539fd31).
- Should be published soon. Thanks @marek-safar and @mellinoe!
