### ISSUE TITLE
Missing folder/directory handling

### ISSUE THREAD

**Issue by jmroyb** [MicrosoftDocs/xamarin-docs#1400]
Where is folder/directory Handling in Xamarin.Forms?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8fb68890-cda3-6b2a-deba-55a171963da5
* Version Independent ID: 675d1663-d7ea-3e47-dbdd-772944acce5a
* Content: [File Handling in Xamarin.Forms - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/files?tabs=windows)
* Content Source: [docs/xamarin-forms/app-fundamentals/files.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/app-fundamentals/files.md)
* Product: **xamarin**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @jmroyb 

Files/folder functionality is provided by the `System.IO` namespaces, rather than Xamarin.Forms.
