### ISSUE TITLE
sample uri scheme

### ISSUE THREAD

**Issue by MSiccDev** [MicrosoftDocs/xamarin-docs#1401]
the navigation scheme in the sample above should be app: with only two slashes, not three. Otherwise, navigation, be it within or outside of the shell using the uri, will always end with an exception.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e8eebbec-c116-fa16-14f3-83e5905e28b2
* Version Independent ID: 9124edfa-2df2-0ef2-6722-0efc0e1134da
* Content: [Xamarin.Forms Shell - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/shell?tabs=android#flyout)
* Content Source: [docs/xamarin-forms/app-fundamentals/shell.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/app-fundamentals/shell.md)
* Product: **xamarin**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @MSiccDev 

Thanks for pointing this out. It's fixed in a PR that'll go out later.
