### ISSUE TITLE
Ambiguity

### ISSUE THREAD

**Issue by 6pac** [MicrosoftDocs/xamarin-docs#1402]
right at the bottom of the page:
  Note that Forms.Init() must be called in App.xaml.cs around line 63.

Is this referring to the App.xaml.cs in YOUR_NAMESPACE? It appears to be referring to the UWP App class that we have just heard is unrelated to Xamarin.Forms and hence we assume is irrelevant? Sone clarification would be great.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f9c4a77e-2256-cfe7-42b2-63041b588b68
* Version Independent ID: 5ade4bab-b189-eeeb-b8c8-1f6546d287d5
* Content: [Xamarin.Forms App Class - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/application-class)
* Content Source: [docs/xamarin-forms/app-fundamentals/application-class.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/app-fundamentals/application-class.md)
* Product: **xamarin**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @6pac 

The doc, at that stage, is referring to the App.xaml.cs file in the UWP project. If you create a blank Xamarin.Forms app that targets UWP, you'll see that App.xaml.cs in the UWP project calls Forms.Init().

**Comment by 6pac** [comment]
No worries, I think I finally worked it out. However since I came to that page seeking to work out why there was a local App.xaml.cs in the UWP project as well as one in the shared project, it was confusing. There are a lot of unclear statements in that section. You could, for example, say (still not sure if this is 100% right - still not sure what that final Forms.Init() is for):

See Setup Windows Projects for information about UWP support in Xamarin.Forms. This page covers the modifications needed to a plain UWP project when it is created without the Xamarin shared project template.
Key points are as follows:  
...

The UWP App.xaml.cs file is still needed for startup by the UWP project. Once it loads MainPage, the code behind for that page should call the shared (Xamarin Forms) project LoadApplication method like so:
......

**Comment by davidbritch** [comment]
Hi @6pac

`Forms.Init()` initialises Xamarin.Forms on each platform. This initialisation includes setting the type of device the app is running on (tablet, desktop), the flow direction for text (left to right, or right to left), and registers some attributes that Xamarin.Forms uses to locate certain types like renderers. Ultimately, if it's not called from **App.xaml.cs** in the UWP project, Xamarin.Forms won't work.
