### ISSUE TITLE
void OnMainDisplayInfoChanged signature seem wrong

### ISSUE THREAD

**Issue by arvindrajachourasiya** [MicrosoftDocs/xamarin-docs#1403]
This 

void OnMainDisplayInfoChanged(DisplayInfoChangedEventArgs  e)
    {
        // Process changes
        var displayInfo = e.DisplayInfo;
    }

Shouldn't it  be 

private void DeviceDisplay_MainDisplayInfoChanged(object sender, DisplayInfoChangedEventArgs e)
{
   var displayInfo = e.DisplayInfo;
}

Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: baaf5be9-c6c2-5c43-c131-6cb01cda6502
* Version Independent ID: 7020d1c9-9b6b-18af-72b9-3e75c0c26340
* Content: [Xamarin.Essentials: Device Display Information - Xamarin](https://docs.microsoft.com/en-us/xamarin/essentials/device-display?context=xamarin%2Fios&tabs=android)
* Content Source: [docs/essentials/device-display.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/essentials/device-display.md)
* Product: **xamarin**
* GitHub Login: @jamesmontemagno
* Microsoft Alias: **jamont**

**Comment by jamesmontemagno** [comment]
Can be closed out with this PR: https://github.com/MicrosoftDocs/xamarin-docs/pull/1404

**Comment by conceptdev** [comment]
PR was merged.
