### ISSUE TITLE
Sample app doesn't work 

### ISSUE THREAD

**Issue by DatuPuti** [MicrosoftDocs/xamarin-docs#1406]
I have tried to following the step in this article but I am unable to reproduce the same app. When I add the 3 controls they are stacked one on top of the other. I have follow the instruction and my .axml is identical to the one in this document but I can't get the controls to flow. Either this document is missing step and/or information or VS 2017 is broken.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 660b0f7c-9941-2db3-63bf-fc8a97765b1e
* Version Independent ID: 5aa1e6f6-534a-05b9-c44a-1f62b24c201a
* Content: [Hello, Android: Quickstart - Xamarin](https://docs.microsoft.com/en-us/xamarin/android/get-started/hello-android/hello-android-quickstart?pivots=windows)
* Content Source: [docs/android/get-started/hello-android/hello-android-quickstart.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/android/get-started/hello-android/hello-android-quickstart.md)
* Product: **xamarin**
* GitHub Login: @conceptdev
* Microsoft Alias: **crdun**

**Comment by conceptdev** [comment]
Thanks for your feedback @DatuPuti 

The instructions do appear to be missing the `android:layout_below` attributes which are used to ensure each control appears below the other, when using the `<RelativeLayout>` that appears by default in the Visual Studio new app template. You can see the correct code in the screenshots.

The [sample](https://github.com/xamarin/monodroid-samples/blob/master/Phoneword/Phoneword/Resources/layout/Main.axml) uses a `<LinearLayout>` (which is what the template uses in Visual Studio for Mac), which would automatically position the controls below each other. I suspect the instructions were originally written assuming this control was in the template, and when the screenshots were updated, the author didn't notice the change to relative layout.

I hope that's enough to get you started. We'll fix the page soon.

**Comment by DatuPuti** [comment]
Hi, Thank you for your response. Looking at the page closer you will see that android:layout_below is there, also it is in my .axml file and I still have the issue with controls stacked on one another. I have included my .axml if that help any.

<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent">
	<TextView
		android:text="Enter a Phoneword"
		android:textAppearance="?android:attr/textAppearanceLarge"
		android:layout_width="wrap_content"
		android:layout_height="wrap_content"
		android:minWidth="25px"
		android:minHeight="25px"
		android:id="@+id/textView1" />
	<EditText
		android:layout_width="wrap_content"
		android:layout_height="wrap_content"
		android:layout_below="@id/textView1"
		android:id="@+id/PhoneNumberText"
		android:text="1-855-XAMARIN" />
	<Button
		android:text="Button"
		android:layout_width="wrap_content"
		android:layout_height="wrap_content"
		android:layout_below="@id/PhoneNumberText"
		android:id="@+id/TranslateButton"
		android:text="Translate" />
	<TextView
		android:text=""
		android:layout_width="wrap_content"
		android:layout_height="wrap_content"
		android:layout_below="@id/TranslateButton"
		android:id="@+id/TranslatedPhoneword" />
</RelativeLayout>

**Comment by DatuPuti** [comment]
`<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent">
	<TextView
		android:text="Enter a Phoneword"
		android:textAppearance="?android:attr/textAppearanceLarge"
		android:layout_width="wrap_content"
		android:layout_height="wrap_content"
		android:minWidth="25px"
		android:minHeight="25px"
		android:id="@+id/textView1" />
	<EditText
		android:layout_width="wrap_content"
		android:layout_height="wrap_content"
		android:layout_below="@id/textView1"
		android:id="@+id/PhoneNumberText"
		android:text="1-855-XAMARIN" />
	<Button
		android:text="Button"
		android:layout_width="wrap_content"
		android:layout_height="wrap_content"
		android:layout_below="@id/PhoneNumberText"
		android:id="@+id/TranslateButton"
		android:text="Translate" />
	<TextView
		android:text=""
		android:layout_width="wrap_content"
		android:layout_height="wrap_content"
		android:layout_below="@id/TranslateButton"
		android:id="@+id/TranslatedPhoneword" />
</RelativeLayout>`

**Comment by Helios976** [comment]
I am still a n00b so not really sure why it behaves the way it does. I had the same problem. We were missing a '+' so change android:layout_below="@id/textView1" to android:layout_below="@+id/textView1" and it should work (in the process of deleting and adding things I ended up adding the '+' )
No idea why it doesn't default to having a +, but again I still don't know what I am doing.( Do the same for the other widgets) 
Cheers!
