### ISSUE TITLE
'Font' XAML attribute is obsolete as of 1.3.0

### ISSUE THREAD

**Issue by ryansama** [MicrosoftDocs/xamarin-docs#1407]
The `Font` attribute that can specify multiple font settings with `"[font-face],[attributes],[size]"` is obsolete as of version 1.3.0

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe0572c4-91be-fc86-d130-242db2bf470b
* Version Independent ID: 1238fdd7-c378-6d0d-654e-55656a70d386
* Content: [Fonts in Xamarin.Forms - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/text/fonts)
* Content Source: [docs/xamarin-forms/user-interface/text/fonts.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/text/fonts.md)
* Product: **xamarin**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @ryansama 

Apologies for the delayed response. I'm not seeing that in the Xamarin.Forms source code:

https://github.com/xamarin/Xamarin.Forms/blob/master/Xamarin.Forms.Core/Label.cs#L31
https://github.com/xamarin/Xamarin.Forms/blob/master/Xamarin.Forms.Core/FontElement.cs#L7
https://github.com/xamarin/Xamarin.Forms/blob/master/Xamarin.Forms.Core/Font.cs
https://github.com/xamarin/Xamarin.Forms/blob/master/Xamarin.Forms.Core/FontTypeConverter.cs

Can you enlighten me?

**Comment by ryansama** [comment]
Hi @davidbritch, I was referring to the documentation being out of date, as I noticed that the `Font` attribute for the `Label` element is noted as obsolete when developing (Xamarin version 3.5): 

![image](https://user-images.githubusercontent.com/9670619/53270850-b07b0e80-36a1-11e9-8977-658a9862e7e6.png)

It doesn't look like the documentation mentions that it is obsolete.

**Comment by davidbritch** [comment]
Understood @ryansama 

I'll investigate further.

**Comment by davidbritch** [comment]
@ryansama Fixed in a PR that will be pushed live later.
