### ISSUE TITLE
Document is very out of date

### ISSUE THREAD

**Issue by aggieben** [MicrosoftDocs/xamarin-docs#1408]
As best I can tell from searching, this document is at least a year out of date, if not more.  This feature should be out of preview by now, and `xamarinmac20` is no longer necessary as the tooling supports .NET Standard 2.0.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 35a28b49-e47c-fca9-69e4-c261f2869e9a
* Version Independent ID: db9d6201-0042-eb0c-7b86-80089b543674
* Content: [Mac Platform Setup - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/platform/other/mac)
* Content Source: [docs/xamarin-forms/platform/other/mac.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/platform/other/mac.md)
* Product: **xamarin**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @aggieben 

I've just made a couple of minor updates to the doc via a PR, which will go out later. However, I can also confirm, after checking with the engineering team, that Mac platform support in Xamarin.Forms is still in preview.
