### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by NGumby** [MicrosoftDocs/xamarin-docs#141]
namemspace ThemesDemo
should be
namespace ThemesDemo

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f28d1a17-189a-7791-b44b-b84e94d8f7b6
* Version Independent ID: 3ad8e76d-eaa6-18f9-c121-9cf4c2c1720f
* Content: [Creating a Custom Theme - Xamarin](https://docs.microsoft.com/en-ca/xamarin/xamarin-forms/user-interface/themes/custom)
* Content Source: [docs/xamarin-forms/user-interface/themes/custom.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/themes/custom.md)
* Service: **unspecified**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by conceptdev** [comment]
Thanks for the tip!
