### ISSUE TITLE
Lacks EntityFrameworkCore for .NET Standard

### ISSUE THREAD

**Issue by Canvee** [MicrosoftDocs/xamarin-docs#1411]
I searched for a local database infrastructure and I never heard of the possibility to have a local database with .NET Standard. I feel PCL outdated. 
Some sentences would be nice to mention.
I found a really useful example. https://github.com/cwrea/XamarinTodo

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3ab6098a-39c7-151f-124b-f88aa62c4659
* Version Independent ID: dc27c1e4-ff12-c1af-646a-c2617def0bcd
* Content: [Xamarin.Forms Local Databases - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/databases)
* Content Source: [docs/xamarin-forms/app-fundamentals/databases.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/app-fundamentals/databases.md)
* Product: **xamarin**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by conceptdev** [comment]
Hi @Canvee thanks for the pointer to that EF sample. 

While the recommended NuGet package still has "pcl" in the name, it is actually a .NETStandard 1.1 library, so it's not outdated.

EFCore is also great, and we'll investigate adding a mention of that to the page.

Thanks again for your feedback.
