### ISSUE TITLE
Can there be some explanation of what all the geocoding naming fields mean in context?

### ISSUE THREAD

**Issue by kkarakk** [MicrosoftDocs/xamarin-docs#1412]
Subadmin  vs admin area, thoroughfare vs subthoroughfare, what do these names mean? in india these usually spit out the same value so it's confusing as to which i should use. 

is subthoroughfare more accurate than thoroughfare for example? should i check if these values match instead of just ignoring some? what is the advice on this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2ebb7d82-4f75-9c6d-8305-7d40afc3a4aa
* Version Independent ID: cd18ee2b-c941-cc79-c6de-8004294a5e08
* Content: [Xamarin.Essentials: Geocoding - Xamarin](https://docs.microsoft.com/en-us/xamarin/essentials/geocoding?context=xamarin%2Fxamarin-forms&tabs=android)
* Content Source: [docs/essentials/geocoding.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/essentials/geocoding.md)
* Product: **xamarin**
* GitHub Login: @jamesmontemagno
* Microsoft Alias: **jamont**

**Comment by jamesmontemagno** [comment]
Referenced in API docs: https://docs.microsoft.com/en-us/dotnet/api/xamarin.essentials.placemark?view=xamarin-essentials-android

Let me know if that helps.

**Comment by kkarakk** [comment]
yes i've looked at that document, the problem is the fields aren't described very effectively.   
for eg - 
> SubAdminArea | Gets or sets the sub-administrative area name of the address, for example, "Santa Clara County", or null if it is unknown.

How does Santa Clara County equate to MY region? India doesn't have counties(a direct equivalent would be "district") but some cities do not have any equivalent of that.    

Maybe a link to this document by microsoft bing maps team would be useful to have 
https://docs.microsoft.com/en-us/bingmaps/rest-services/common-parameters-and-types/location-and-area-types

**Comment by jamesmontemagno** [comment]
Would map there to adminDistrict2: A string specifying the subdivision name in the country or region for an address. This element is used when there is another level of subdivision information for a location, such as the county. 

If there is no county then it will map to null.

here is what they map to on each platform:

iOS: https://developer.apple.com/documentation/corelocation/clplacemark/1423776-subadministrativearea
Android: https://developer.android.com/reference/android/location/Address.html#getSubAdminArea()
UWP: https://docs.microsoft.com/en-us/uwp/api/windows.services.maps.mapaddress.district#Windows_Services_Maps_MapAddress_District

Code can be found here for mappings:

iOS: https://github.com/xamarin/Essentials/blob/master/Xamarin.Essentials/Types/PlacemarkExtensions.ios.cs
Android: https://github.com/xamarin/Essentials/blob/master/Xamarin.Essentials/Types/PlacemarkExtensions.android.cs
UWP: https://github.com/xamarin/Essentials/blob/master/Xamarin.Essentials/Types/PlacemarkExtensions.uwp.cs
