### ISSUE TITLE
localize folder extension

### ISSUE THREAD

**Issue by shalinasanga** [MicrosoftDocs/xamarin-docs#1413]
hi,
make following line bold and most highlighted section of entire iOS localizing doc
"named directories with an .lproj suffix (note the first letter of the extension is a lower-case "L")."
oh god !!! this almost suck my life from me

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 629ae54b-10fe-61ff-6a6e-cb54b5206079
* Version Independent ID: fcb311ea-1552-86e4-d648-5fe7832d863a
* Content: [Localization in Xamarin.iOS - Xamarin](https://docs.microsoft.com/en-us/xamarin/ios/app-fundamentals/localization/index)
* Content Source: [docs/ios/app-fundamentals/localization/index.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/ios/app-fundamentals/localization/index.md)
* Product: **xamarin**
* GitHub Login: @lobrien
* Microsoft Alias: **laobri**

**Comment by conceptdev** [comment]
Hi @shalinasanga we include that warning to help customers who might not immediately notice the correct spelling (either by copy/pasting from the doc, or looking at the attached sample). Hope everything is working for you now.
