### ISSUE TITLE
Dead link for Intel HAXM

### ISSUE THREAD

**Issue by StefanKern** [MicrosoftDocs/xamarin-docs#1414]
https://software.intel.com/android/articles/intel-hardware-accelerated-execution-manager is a dead link (404).
Is the correct link: https://github.com/intel/haxm ? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4e37d642-2051-8d70-9968-dfb484122a6a
* Version Independent ID: 178ea80c-2b99-0c44-eeb6-9db319439b33
* Content: [Hardware Acceleration for Emulator Performance (Hyper-V & HAXM) - Xamarin](https://docs.microsoft.com/en-us/xamarin/android/get-started/installation/android-emulator/hardware-acceleration?tabs=vswin&pivots=windows)
* Content Source: [docs/android/get-started/installation/android-emulator/hardware-acceleration.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/android/get-started/installation/android-emulator/hardware-acceleration.md)
* Product: **xamarin**
* GitHub Login: @conceptdev
* Microsoft Alias: **crdun**

**Comment by conceptdev** [comment]
Hi @StefanKern it does not 404 for me, but redirects to the URL you shared. Nevertheless I've removed the link to avoid confusion.

Now that Google's emulator works with Hyper-V, that's the recommended approach if your computer supports it.

Thanks for your feedback!
