### ISSUE TITLE
Samples: ResourceTrees and ResourceSharing

### ISSUE THREAD

**Issue by joewang1967** [MicrosoftDocs/xamarin-docs#1415]
&lt;x:String x:Key="fontSize"&gt;Large&lt;/x:String&gt;
FontSize="{StaticResource fontSize}" 
:
Unhandled Exception:
System.InvalidCastException: Specified cast is not valid. occurred

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2f1236a9-aeda-7a4d-4023-3eb60067bb80
* Version Independent ID: d748dc44-7b87-6a53-d7a2-a60b4ec0a6bd
* Content: [Summary of Chapter 10. XAML markup extensions - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/creating-mobile-apps-xamarin-forms/summaries/chapter10)
* Content Source: [docs/xamarin-forms/creating-mobile-apps-xamarin-forms/summaries/chapter10.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/creating-mobile-apps-xamarin-forms/summaries/chapter10.md)
* Product: **xamarin**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @joewang1967 

I just tried the ResourceSharing sample in VSMac, updated it to Xamarin.Forms 3.5 and it worked fine on both iOS and Android (the `Button` text was displayed with a `Large` font size).

**Comment by joewang1967** [comment]
Thank you very much!

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by timmi4sa** [comment]
Well this exception is back in Xamarin Forms 5.0.0.2083. Anything we can do about it?
