### ISSUE TITLE
iOS culture to .net culture issue

### ISSUE THREAD

**Issue by shalinasanga** [MicrosoftDocs/xamarin-docs#1416]
hi,

in iOSToDotnetLanguage method, instead of using "  var netLanguage = iOSLanguage;" , better use   var netLanguage = iOSLanguage.Replace("\_","-");
because older code return exception since .net culture doesn't support underscore "\_"

thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: af66394d-81c5-0c2e-1682-a2bb7eeb3c3e
* Version Independent ID: 27542a45-2f25-4042-cf48-b9517025635c
* Content: [String and Image Localization - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/localization/text?tabs=windows)
* Content Source: [docs/xamarin-forms/app-fundamentals/localization/text.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/app-fundamentals/localization/text.md)
* Product: **xamarin**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @shalinasanga 

Thanks for pointing this out. I've updated the doc/sample, and the updates will be pushed out later today.
