### ISSUE TITLE
show/hide connectivity status with Prism

### ISSUE THREAD

**Issue by patricksegantine** [MicrosoftDocs/xamarin-docs#1419]
Hi James, so... what's tehe best way to use this API with Prism? Do I put a property in the ViewModelBase or leave it int the views code behind? Do you have an example to help me?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 33758e0e-bd5d-0829-b458-6cdfabe98b44
* Version Independent ID: d3ed3057-798b-44b9-b5a0-35e657f7a4b8
* Content: [Xamarin.Essentials: Connectivity - Xamarin](https://docs.microsoft.com/en-us/xamarin/essentials/connectivity?context=xamarin%2Fxamarin-forms&tabs=android)
* Content Source: [docs/essentials/connectivity.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/essentials/connectivity.md)
* Product: **xamarin**
* GitHub Login: @jamesmontemagno
* Microsoft Alias: **jamont**

**Comment by jamesmontemagno** [comment]
You can do it in either. Up to you and where you want to put it and if you need to mock it out.
