### ISSUE TITLE
Overuse of var in examples

### ISSUE THREAD

**Issue by sdoiel61** [MicrosoftDocs/xamarin-docs#1421]
It is more difficult to read code that makes excessive use of var types.  While it might make it faster to write code, it often makes it more difficult to follow.
Please avoid using var in examples.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b5d7a251-6fd9-d6c9-63c6-ad2ca82a8b46
* Version Independent ID: 853f0d5e-e93f-b2d7-f01b-75c80cff8df3
* Content: [The Model-View-ViewModel Pattern - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/enterprise-application-patterns/mvvm)
* Content Source: [docs/xamarin-forms/enterprise-application-patterns/mvvm.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/enterprise-application-patterns/mvvm.md)
* Product: **xamarin**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @sdoiel61 

Thanks for the feedback. I agree completely, and it's something we'll be adopting in future (not over using var).
