### ISSUE TITLE
Wrong ISO reference

### ISSUE THREAD

**Issue by thms-dwld** [MicrosoftDocs/xamarin-docs#1422]
ISO 8166:2003 specifies a procedure to be used for the evaluation of the life of spot welding electrodes when welding uncoated and coated steels, stainless steels, aluminium and aluminium alloys using constant machine settings which are not changed during the test. (cfr. https://www.iso.org/standard/33246.html)

ISO 3166 is the one that needs to be reference here. (cfr. https://www.iso.org/iso-3166-country-codes.html)
I believe the standard used by CLPlacemark.ISOcountryCode is ISO 3166-1.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fb7c0794-42f7-81ea-4f9a-99f5f809d2b6
* Version Independent ID: a461ce09-9140-77c4-3038-24149df4c25c
* Content: [CLPlacemark.IsoCountryCode Property (CoreLocation)](https://docs.microsoft.com/en-us/dotnet/api/corelocation.clplacemark.isocountrycode)
* Content Source: [en/CoreLocation/CLPlacemark.xml](https://github.com/xamarin/apple-api-docs/blob/live/en/CoreLocation/CLPlacemark.xml)
* Product: **xamarin**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by conceptdev** [comment]
Keen eye @thms-dwld, thanks for your feedback. We'll fix it up soon.
