### ISSUE TITLE
MyPictures folder is wrong

### ISSUE THREAD

**Issue by wutever0** [MicrosoftDocs/xamarin-docs#1425]
Under "Working with Internal Storage", the MyPictures special folder should map to INTERNAL_STORAGE/Pictures not INTERNAL_STORAGE/Music

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cdfb32ba-3510-a171-c451-4b3bac673c7c
* Version Independent ID: 7299b788-36f9-f4e2-2ba2-45893f466c19
* Content: [File access with Xamarin.Android - Xamarin](https://docs.microsoft.com/en-us/xamarin/android/platform/files/)
* Content Source: [docs/android/platform/files/index.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/android/platform/files/index.md)
* Product: **xamarin**
* GitHub Login: @conceptdev
* Microsoft Alias: **crdun**

**Comment by conceptdev** [comment]
This was fixed a while back, in https://github.com/MicrosoftDocs/xamarin-docs/pull/1604. Thanks for raising the issue!
