### ISSUE TITLE
SQLite MissingMethodException

### ISSUE THREAD

**Issue by cizzi1990** [MicrosoftDocs/xamarin-docs#1426]
I've cloned the ToDo project, and I get this error at runtime:
```System.MissingMethodException: void SQLite.SQLiteAsyncConnection..ctor(string,bool)```

It seems to happen at ToDoItemDatabase instantiation, but the debugging is unclear and the call stack of the exception is external.
I tried different versions of sqlite-net-pcl and it still throws this error. Any ideas?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3ab6098a-39c7-151f-124b-f88aa62c4659
* Version Independent ID: dc27c1e4-ff12-c1af-646a-c2617def0bcd
* Content: [Xamarin.Forms Local Databases - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/databases)
* Content Source: [docs/xamarin-forms/app-fundamentals/databases.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/app-fundamentals/databases.md)
* Product: **xamarin**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @cizzi1990 

I've just tried this in Visual Studio for Mac and the sample built and ran just fine on both iOS and Android. However, the same can't be said for VS2017. I've just checked in an update which sees it all working from VS2017.

If you clone the xamarin-forms-samples repo you'll get the .csproj updates. However, it'll be a few hours before the downloadable zip is updated.
