### ISSUE TITLE
Needed to make two small changes that the article does not mention.

### ISSUE THREAD

**Issue by clharrysmith** [MicrosoftDocs/xamarin-docs#1428]
You need to change the line "public class SplashActivity : Activity" to "public class SplashActivity : AppCompatActivity" in the SplashActivity.cs file.
You need to add the line "&lt;color name="splash_background"&gt;#4040FF&lt;/color&gt;" in the colors.xml file. (For a nice blue color. You can pick your own.)

Other that that it worked great. Thanks Harry...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5823a3fa-87be-0b27-155b-b44130c67e84
* Version Independent ID: c90633f5-22b9-f7dd-fd08-c9affc251dd4
* Content: [Splash Screen - Xamarin](https://docs.microsoft.com/en-us/xamarin/android/user-interface/splash-screen)
* Content Source: [docs/android/user-interface/splash-screen.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/android/user-interface/splash-screen.md)
* Product: **xamarin**
* GitHub Login: @conceptdev
* Microsoft Alias: **crdun**

**Comment by profexorgeek** [comment]
This change appears to have been applied but this comment was not closed. Closing now.
