### ISSUE TITLE
Intent needs to be redone.

### ISSUE THREAD

**Issue by clharrysmith** [MicrosoftDocs/xamarin-docs#1429]
I pastes the wrong content this is what it should be

            Intent MainActivityIntent = new Intent(Application.Context, typeof(MainActivity));
            MainActivityIntent.SetFlags(ActivityFlags.NewTask);
            MainActivityIntent.SetFlags(ActivityFlags.ClearTask);
            StartActivity(MainActivityIntent);

I needed to do this to keep Google Play Store happy.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5823a3fa-87be-0b27-155b-b44130c67e84
* Version Independent ID: c90633f5-22b9-f7dd-fd08-c9affc251dd4
* Content: [Splash Screen - Xamarin](https://docs.microsoft.com/en-us/xamarin/android/user-interface/splash-screen)
* Content Source: [docs/android/user-interface/splash-screen.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/android/user-interface/splash-screen.md)
* Product: **xamarin**
* GitHub Login: @conceptdev
* Microsoft Alias: **crdun**

**Comment by profexorgeek** [comment]
The current sample uses this code to start the main activity:
```
StartActivity(new Intent(Application.Context, typeof (MainActivity)));
```

I tested this on both the emulator and a physical device without issues.
