### ISSUE TITLE
Xamarin Essentials UWP Version not clear if Min or Target version

### ISSUE THREAD

**Issue by DigitalNut** [MicrosoftDocs/xamarin-docs#1430]
In the "Get Started with Xamarin.Essentials" page, the UWP version listed is not clear if it should be the 'Min' version or the 'Target' version. I assumed the target version and my UWP project using Xamarin.Essentials would throw a exception, until I changed the 'Min' version to what is listed on this page (Version 10.0.16299.0). My Target version was higher then listed in the doc.

**Comment by jamesmontemagno** [comment]
We recently put out a document on platform support: https://docs.microsoft.com/en-us/xamarin/essentials/platform-feature-support?context=xamarin/android
