### ISSUE TITLE
Unknown return value

### ISSUE THREAD

**Issue by Ulf-Ason** [MicrosoftDocs/xamarin-docs#1431]
The documentation doesn't tell what the return value would be, if the key is not found in the SecureStorage

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8675ea19-07ee-45d4-c51b-a7d9141cde2b
* Version Independent ID: 29473b7e-93b0-307b-edc6-fe8271913962
* Content: [SecureStorage.GetAsync(String) Method (Xamarin.Essentials)](https://docs.microsoft.com/en-us/dotnet/api/xamarin.essentials.securestorage.getasync?view=xamarin-essentials-android)
* Content Source: [docs/en/Xamarin.Essentials/SecureStorage.xml](https://github.com/xamarin/Essentials/blob/live/docs/en/Xamarin.Essentials/SecureStorage.xml)
* Product: **xamarin**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by SittenSpynne** [comment]
It seems like it returns null, but I hate relying on "this is what it did when I tried it.

**Comment by jamesmontemagno** [comment]
Fixed via: https://github.com/xamarin/Essentials/pull/1048

**Comment by jamesmontemagno** [comment]
Also confirmed that it is in standard documentation.

**Comment by contravarianceisuseful** [comment]
Should this be throwing some sort of key not found exception instead of returning null?
