### ISSUE TITLE
RefreshControlColor property in ListView is missing

### ISSUE THREAD

**Issue by CraftedPvP** [MicrosoftDocs/xamarin-docs#1435]
It's not available on Xamarin. Kindly mail me if there's an update to this part.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1b0eed28-8065-951a-1b3f-325c59414a7c
* Version Independent ID: eac566b7-faba-2bea-f9c4-bdadff5169f6
* Content: [ListView Interactivity - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/listview/interactivity)
* Content Source: [docs/xamarin-forms/user-interface/listview/interactivity.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/listview/interactivity.md)
* Product: **xamarin**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @CraftedPvP 

It's available in Xamarin.Forms 3.5.

**Comment by stefanvesely** [comment]
Hi, I don't know how to leave feedback of my own. So I am posting it and attaching it to this guys work with the hopes of letting you know.
I am having an issue of this working for tabbed pages, maybe it is my issue, but adding context actions doesn't show when I have a tabbed page.
