### ISSUE TITLE
Should we use .watchkit or .watchkitapp extension?

### ISSUE THREAD

**Issue by vchelaru** [MicrosoftDocs/xamarin-docs#1437]
This document says to suffix "watchkitapp" on the bundle identifier for the watch app, but the sample here (which does compile) has a .watchkit suffix instead of watchkitapp:

https://developer.xamarin.com/samples/monotouch/watchOS/SimpleWatchConnectivity/

Which is right - this documentation or the sample?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 58e2a2c9-930f-e8e3-dc1e-7f07988350ba
* Version Independent ID: 7e21117e-7331-d4b0-977b-d467a91922e9
* Content: [watchOS Project References in Xamarin - Xamarin](https://docs.microsoft.com/en-us/xamarin/ios/watchos/get-started/project-references?tabs=windows)
* Content Source: [docs/ios/watchos/get-started/project-references.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/ios/watchos/get-started/project-references.md)
* Product: **xamarin**
* GitHub Login: @lobrien
* Microsoft Alias: **laobri**

**Comment by conceptdev** [comment]
Hey @vchelaru, the actual string itself does not need to be one or the other for the app to work, it just has to _match_ in the few places it is used across the Info.plist files in the iOS and watch projects. 

I generally try to use the same string suffix that Apple's Xcode templates use, and ideally our doc & sample would agree. Will take a look and update one or the other.
