### ISSUE TITLE
Update Effects docs to use nameof() instead of hardcode string

### ISSUE THREAD

**Issue by ajpinedam** [MicrosoftDocs/xamarin-docs#1439]

**Comment by davidbritch** [comment]
Thanks for the PR @ajpinedam, your help is much appreciated.

Most of our pages have a sample on https://github.com/xamarin/xamarin-forms-samples, which needs to be kept in sync with the doc. If you have the time, a companion PR to the sample would be much appreciated.

**Comment by davidbritch** [comment]
PR has been merged.
