### ISSUE TITLE
No key pair after command line build

### ISSUE THREAD

**Issue by DevMatthias** [MicrosoftDocs/xamarin-docs#144]
There is no key pair generated after building on the command line with /p:ServerPassword. I have to issue the password paramater all the time and the authorized_keys on the Mac are empty too. Maybe a bug or wrong doc?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 98c96bcc-1743-8d9f-f1b2-3c30d5b2a6e2
* Version Independent ID: f57a6157-332a-3f31-c785-7efa99e62711
* Content: [Connecting to the Mac - Xamarin](https://docs.microsoft.com/en-us/xamarin/ios/get-started/installation/windows/connecting-to-mac/#comments-container)
* Content Source: [docs/ios/get-started/installation/windows/connecting-to-mac/index.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/ios/get-started/installation/windows/connecting-to-mac/index.md)
* Service: **unspecified**
* GitHub Login: @bradumbaugh
* Microsoft Alias: **brumbaug**

**Comment by bradumbaugh** [comment]
Hi @DevMatthias, thanks for noting this. If you believe you're seeing a bug, please file it here: https://developercommunity.visualstudio.com/.

It may not be directly related, but you might also look at this issue in the same forum: https://developercommunity.visualstudio.com/content/problem/101957/xamarin-mac-agent-unable-to-generate-ssh-keys.html.

Thanks again.
