### ISSUE TITLE
Clarify the app server

### ISSUE THREAD

**Issue by devmikew** [MicrosoftDocs/xamarin-docs#1443]
It isn't clear what the app server's evnironment is. For example can it be a wcf service running on windows server?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 360c5865-2902-68da-5a8d-7252c26394c6
* Version Independent ID: d9df0129-27be-54dc-3c82-bb407b9f8c5b
* Content: [Firebase Cloud Messaging - Xamarin](https://docs.microsoft.com/en-us/xamarin/android/data-cloud/google-messaging/firebase-cloud-messaging)
* Content Source: [docs/android/data-cloud/google-messaging/firebase-cloud-messaging.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/android/data-cloud/google-messaging/firebase-cloud-messaging.md)
* Product: **xamarin**
* GitHub Login: @conceptdev
* Microsoft Alias: **crdun**

**Comment by conceptdev** [comment]
The [Firebase Cloud Messaging in action section](https://docs.microsoft.com/xamarin/android/data-cloud/google-messaging/firebase-cloud-messaging#fcm-in-action) links to https://firebase.google.com/docs/cloud-messaging/server and https://firebase.google.com/docs/admin/setup which describes what the server might run. There is an Admin .NET SDK.

You could also use [App Center Push](https://docs.microsoft.com/appcenter/sdk/push/xamarin-android).
