### ISSUE TITLE
WKInterfaceController.OpenParentApplication does not exist.

### ISSUE THREAD

**Issue by danJohnsonBuzz** [MicrosoftDocs/xamarin-docs#1445]
The first code snippet gives an error, indicating that the "WKInterfaceController does not contain a definition for OpenParentApplication. What is the up to date technique for watchOS Series 3 and greater.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b2fa4235-a31c-1383-1220-8bbc95562a64
* Version Independent ID: 47d188c0-b06a-801c-a4bc-a43f890107a8
* Content: [Working with the watchOS Parent Application in Xamarin - Xamarin](https://docs.microsoft.com/en-us/xamarin//ios/watchos/app-fundamentals/parent-app#feedback)
* Content Source: [docs/ios/watchos/app-fundamentals/parent-app.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/ios/watchos/app-fundamentals/parent-app.md)
* Product: **xamarin**
* GitHub Login: @lobrien
* Microsoft Alias: **laobri**

**Comment by danJohnsonBuzz** [comment]
Forgive me, just read the important warning at the top that says "Accessing the parent application using the examples below only works on watchOS 1 watch apps". Ignore my last comment. However, do you have any up to date examples?

**Comment by lobrien** [comment]
Do the resources at https://docs.microsoft.com/en-us/xamarin/ios/watchos/ address your needs?

**Comment by conceptdev** [comment]
These two samples work on newer watchOS versions:

https://docs.microsoft.com/en-us/samples/xamarin/ios-samples/watchos-simplewatchconnectivity/

https://docs.microsoft.com/en-us/samples/xamarin/ios-samples/watchos-watchconnectivity/

Given the content on this page is so old, we're considering removing it to prevent confusion in future.
