### ISSUE TITLE
Missing event

### ISSUE THREAD

**Issue by robinne** [MicrosoftDocs/xamarin-docs#1449]
Entry.Unfocused

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c5afa3c9-4bcb-4986-2161-1bf2feb856b7
* Version Independent ID: 39fc31bd-4b1d-65f3-aaf8-6eb464e9b38a
* Content: [Xamarin.Forms Entry - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/text/entry)
* Content Source: [docs/xamarin-forms/user-interface/text/entry.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/text/entry.md)
* Product: **xamarin**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @robinne 

Thanks for the feedback. Focused/unfocused events were never mentioned as they are actually inherited from the `VisualElement` class. However, I've added a note that links to them.
