### ISSUE TITLE
Missing XamarinForms3.0's FlexLayout

### ISSUE THREAD

**Issue by knocte** [MicrosoftDocs/xamarin-docs#145]
Looking forward to the docs about this new layout

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3ccf3ece-9054-92a0-8b70-9e1c44390663
* Version Independent ID: 3e37b016-4f1c-7b92-7086-ec10c22a86f6
* Content: [Layouts - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/layouts/)
* Content Source: [docs/xamarin-forms/user-interface/layouts/index.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/layouts/index.md)
* Service: **unspecified**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by conceptdev** [comment]
This feature is still in preview, keep an eye on the release notes for additional information.
