### ISSUE TITLE
Instructions are contradictory or do not consider other uses of Hyper-V

### ISSUE THREAD

**Issue by lorenjerickson** [MicrosoftDocs/xamarin-docs#1453]
I have an intel CPU that definitely supports virtualization.  I had Docker running on it until I tried following these instructions. I ensured that Hyper-V was "turned on" per the instructions here, then proceed to installing Intel HAXM.  This fails with a "VT is not supported" error.  A telling point of the detailed error message is "Please ensure that Hyper-V is disabled"!  Wha?!  I had an older version of HAXM installed and removed it since apparently the package is not smart enough to do an in-place upgrade.  Didn't help. Regardless, which is it Microsoft?  Enable Hyper-V or not?  Maybe you and the HAXM guys at Intel need to have a chat....  BTW, Intel product page for my processor definitely says it supports VT-x.  Complete text of the error message follows: "This computer does not support Intel Virtualization Technology (VT-x) or it is being exclusively used by Hyper-V. HAXM cannot be installed. Please ensure that Hyper-V is disabled in Windows Features, or refer to the Intel HAXM documentation for more information."  Definition of a rock and a hard place.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4e37d642-2051-8d70-9968-dfb484122a6a
* Version Independent ID: 178ea80c-2b99-0c44-eeb6-9db319439b33
* Content: [Hardware Acceleration for Emulator Performance (Hyper-V & HAXM) - Xamarin](https://docs.microsoft.com/en-us/xamarin/android/get-started/installation/android-emulator/hardware-acceleration?tabs=vswin&pivots=windows)
* Content Source: [docs/android/get-started/installation/android-emulator/hardware-acceleration.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/android/get-started/installation/android-emulator/hardware-acceleration.md)
* Product: **xamarin**
* GitHub Login: @conceptdev
* Microsoft Alias: **crdun**

**Comment by lorenjerickson** [comment]
wow, have to read the fine print I guess.  Completely missed this little gem in the paragraph under Accelerating with HAXM. 
"if your computer does not support Hyper-V"
Don't you think it's kind of important to represent these options as alternatives.  As written they appear to be sequence of steps.  Do this, then do that.  Completely understand now why my HAXM install didn't work.

**Comment by conceptdev** [comment]
Thanks for the feedback @lorenjerickson - sometimes an alternate point of view is helpful to challenge our assumptions and improve our content. We'll revisit the page to see if we can make this distinction clearer, to help future readers.

**Comment by JonDouglas** [comment]
We will take this into account and make it easier to select the appropriate sections of docs related to your machine's hardware and the proper hypervisor you should use.

Just to answer your question: 

> You have an Intel processor and **do not need** to run Hyper-V at the same time as the Android Emulator.

Use Intel HAXM

> You have an Intel processor and **do need** to run Hyper-V at the same time as the Android Emulator.

Use Windows Hypervisor Platform

> You have an AMD processor.

Use Windows Hypervisor Platform

While Hyper-V is enabled on your machine, it will disable detection of VT-x as it's being used. You must disable the respective Hypervisor in order for some tools to detect the usage like HAXM. In other words, if one is installed and being used, you cannot install or enable the other.

**Comment by conceptdev** [comment]
The page referenced in this issue has been updated a few times since February. Please open a new issue there are still questions on the content.
