### ISSUE TITLE
NSAppTransportSecurity setting needed for iOS

### ISSUE THREAD

**Issue by wegascee** [MicrosoftDocs/xamarin-docs#1456]
For iOS to make it actually work you need this (taken from the sample project).

```
<key>NSAppTransportSecurity</key>
<dict>
	<key>NSAllowsArbitraryLoads</key>
	<true/>
</dict>
```

Could you perhaps add a note to the doc for this?

Also one could mention the location and build setting for the index.html.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9c1bd30c-6e7a-df38-8c20-dff7361e901f
* Version Independent ID: 013c6027-db9a-6039-3404-2e4f717133a9
* Content: [Implementing a HybridWebView - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/custom-renderer/hybridwebview#creating-the-hybridwebview)
* Content Source: [docs/xamarin-forms/app-fundamentals/custom-renderer/hybridwebview.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/app-fundamentals/custom-renderer/hybridwebview.md)
* Product: **xamarin**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by conceptdev** [comment]
Thanks for the feedback @wegascee, we'll definitely take a look.

**Comment by davidbritch** [comment]
Hi @wegascee 

Thanks for the feedback. I've updated the doc as per your suggestion, in a PR that will go live later.
