### ISSUE TITLE
MobileServiceInvalidOperationException: You do not have permission to view this directory or page.

### ISSUE THREAD

**Issue by cjaworski** [MicrosoftDocs/xamarin-docs#1457]
We created detailed question with screenshots on StackOverflow.
https://stackoverflow.com/questions/54929268/azure-ad-b2c-azure-mobile-apps-mobileserviceinvalidoperationexception
I would like to ask for help with that.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 16864cab-cbfa-98f3-c1da-7ed88cfe2579
* Version Independent ID: c1731783-e6da-af46-3fce-5e4bcc50dd61
* Content: [Integrating Azure Active Directory B2C with Azure Mobile Apps - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/data-cloud/authentication/azure-ad-b2c-mobile-app#azure-mobile-app-configuration)
* Content Source: [docs/xamarin-forms/data-cloud/authentication/azure-ad-b2c-mobile-app.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/data-cloud/authentication/azure-ad-b2c-mobile-app.md)
* Product: **xamarin**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by vidya091209** [comment]
I am facing the same issue. i tried different combination like.
creating separate app for mobile service. 
did you tried using access token here
payload["access_token"] = authenticationResult.IdToken;

**Comment by AjayKumar-MSFT** [comment]
@davidbritch, Requesting your assistance on this issue.

**Comment by DashleenBhandari-MSFT** [comment]
We’ve taken a look at this document/sample and can confirm that that it’s in need of a major refresh, as it’s no longer accurate. We are working internally to refresh it.

**Comment by davidbritch** [comment]
This doc has now been updated, so I'm closing the issue.
