### ISSUE TITLE
Xamarin.Essentials.Platform.Init(this, bundle); Big misstake!

### ISSUE THREAD

**Issue by nguyenthanhliemfc** [MicrosoftDocs/xamarin-docs#1460]
Xamarin.Essentials.Platform.Init(this, bundle); Big misstake!

---
#### Chi tiết tài liệu

⚠ *Không chỉnh sửa phần này. Điều này là bắt buộc cho docs.microsoft.com ➟ Vấn đề khi liên kết GitHub.*

* ID: f0acf3fa-b705-f0cc-b676-eeca60176dfa
* Version Independent ID: 1788a5d5-a3cb-15c8-927c-b6a24810245a
* Content: [Xamarin.Essentials: Geolocation - Xamarin](https://docs.microsoft.com/vi-vn/xamarin/essentials/geolocation?context=xamarin%2Fxamarin-forms&tabs=android)
* Content Source: [docs/essentials/geolocation.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/essentials/geolocation.md)
* Product: **xamarin**
* GitHub Login: @jamesmontemagno
* Microsoft Alias: **jamont**

**Comment by jamesmontemagno** [comment]
Was there an issue that you ran into?

**Comment by nguyenthanhliemfc** [comment]
I have found what I miss it in Getting Started, thank Sir!
