### ISSUE TITLE
Cannot find definition of MyGestureListener

### ISSUE THREAD

**Issue by Ambusy** [MicrosoftDocs/xamarin-docs#1462]
In the text to copy to create this example it is written
GestureOverlayView.IOnGestureListener myListener = new MyGestureListener();
I have no idea how or where the MyGestureListener is defined. The next chapter Walkthrough contains a listener, but not without a parameter. Same for the 2 samples named on this page.
Please add some reference to this class contents, or add the text of the class.

---
#### Detalii document

⚠ *Nu editați această secțiune. Este necesară pentru asocierea prin link a problemelor între docs.microsoft.com și GitHub.*

* ID: 93d8bf42-a928-0e2d-12df-22b3f4ff6ec8
* Version Independent ID: 32aabf5b-c4d1-6d6d-1348-a8179a1fe461
* Content: [Touch in Android - Xamarin](https://docs.microsoft.com/ro-ro/xamarin/android/app-fundamentals/touch/touch-in-android)
* Content Source: [docs/android/app-fundamentals/touch/touch-in-android.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/android/app-fundamentals/touch/touch-in-android.md)
* Product: **xamarin**
* GitHub Login: @conceptdev
* Microsoft Alias: **crdun**

**Comment by conceptdev** [comment]
Hi @Ambusy have you been able to run the [sample code](https://developer.xamarin.com/samples/monodroid/ApplicationFundamentals/Touch_final) for this page?

**Comment by Ambusy** [comment]
the sample code runs and does what the article promises. Txs.
