### ISSUE TITLE
Wrong format for teaching

### ISSUE THREAD

**Issue by fireman422** [MicrosoftDocs/xamarin-docs#1463]
This is way too common, imho.  Topics are presented as a sample application instead of precisely showing how something works.  I don't want to end up with a functional address book application.  These little sample applications, instead of showing how to use a fragment, this one includes two fragments.  All I'm getting is copy the code into a project and then it either works or it doesn't, well of course it doesn't, and I haven't been told how it works, so I can't figure it out for myself.  The best I can do with this is pick through the code and try to understand it but seriously another google search is my best option.  And on top of that ignoring anything Microsoft that comes up in the search is best practice.  I don't buy books presented this way either.  Wrox Press comes to mind.

**Comment by conceptdev** [comment]
Thanks for your feedback. I understand that everyone learns differently and that our style might not suit everyone. Have you tried  the [Xamarin University](https://university.xamarin.com/) course videos relating to Android? There are a subset of Self-Guided Learning modules that are free to access, and the training material might better fit your expectations.
