### ISSUE TITLE
Dead link

### ISSUE THREAD

**Issue by gjkhw** [MicrosoftDocs/xamarin-docs#1465]
[Enter feedback here]

The page provides a link to https://github.com/mono/linker/tree/master/analyzer - this link returns a 404.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aa951c69-0f9f-d6f8-b879-0a3427436e3c
* Version Independent ID: 7807523a-115c-5f73-b22a-a914792467a4
* Content: [Build Process - Xamarin](https://docs.microsoft.com/en-us/xamarin/android/deploy-test/building-apps/build-process#feedback)
* Content Source: [docs/android/deploy-test/building-apps/build-process.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/android/deploy-test/building-apps/build-process.md)
* Product: **xamarin**
* GitHub Login: @conceptdev
* Microsoft Alias: **crdun**

**Comment by conceptdev** [comment]
Thanks for the heads-up - fixing now!
