### ISSUE TITLE
No troubleshooting details related to the iOS simulator

### ISSUE THREAD

**Issue by aszalacinski** [MicrosoftDocs/xamarin-docs#1467]
I am not able to run the iOS simulator now after installing VS2019 Preview; going through the whole uninstall everything to see if that fixes it.

I get a "fatal server error has occurred" and it just hangs, preventing me from testing on the simulator.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 18072f31-4d0e-f9b4-c085-fcaa66f278fc
* Version Independent ID: a9ba3155-0f55-f303-e27a-93360433cf0f
* Content: [Remoted iOS Simulator for Windows - Xamarin](https://docs.microsoft.com/en-us/xamarin/tools/ios-simulator/index)
* Content Source: [docs/tools/ios-simulator/index.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/tools/ios-simulator/index.md)
* Product: **xamarin**
* GitHub Login: @lobrien
* Microsoft Alias: **laobri**

**Comment by conceptdev** [comment]
As Visual Studio 2019 is still in Preview, this could be a bug. Please [report a problem](https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio) via Visual Studio so that relevant environment and debugging information can be submitted.
