### ISSUE TITLE
Visual Studio Project template for C/C++ Library in Cross-Platform Apps

### ISSUE THREAD

**Issue by stefangeorgeclaudiu** [MicrosoftDocs/xamarin-docs#1469]
A Visual Studio project template would be much appreciated. There are just so many repetitive, error-prone steps in this tutorial.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e40fbe03-a099-3b24-4654-162103003d6a
* Version Independent ID: 01e8c667-ed94-7054-758d-2399e879714a
* Content: [Use C/C++ libraries with Xamarin - Xamarin](https://docs.microsoft.com/en-us/xamarin/cross-platform/cpp/)
* Content Source: [docs/cross-platform/cpp/index.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/cross-platform/cpp/index.md)
* Product: **xamarin**
* GitHub Login: @mikeparker104
* Microsoft Alias: **miparker**

**Comment by conceptdev** [comment]
Thanks for the feedback. There are no plans for a template, but you can suggest features on [Visual Studio Developer Community](https://developercommunity.visualstudio.com/).
