### ISSUE TITLE
Typing mistakes in code + missing dialog in VS

### ISSUE THREAD

**Issue by CeciAc** [MicrosoftDocs/xamarin-docs#1470]
@nielsenvancura commented on [Mon Mar 04 2019](https://github.com/MicrosoftDocs/xamarin-docs.cs-cz/issues/2)

1) class is called - "name the new file PhoneTranslator", but inside class you have "public static class PhonewordTranslator"
2) I am at Mac with Visual Studio Community 7.8.2 - can not find Project Option dialog as stated in "After all the icons are copi ..", only Project - Solution Option where "Android aplication" is missing

---
#### Podrobnosti dokumentu

⚠ *Neupravujte tuto část. Vyžaduje se k propojení problémů docs.microsoft.com ➟ GitHub.*

* ID: 660b0f7c-9941-2db3-63bf-fc8a97765b1e
* Version Independent ID: 5aa1e6f6-534a-05b9-c44a-1f62b24c201a
* Content: [Hello, Android: Rychlý start - Xamarin](https://docs.microsoft.com/cs-cz/xamarin/android/get-started/hello-android/hello-android-quickstart?pivots=macos#feedback)
* Content Source: [docs/android/get-started/hello-android/hello-android-quickstart.md](https://github.com/MicrosoftDocs/xamarin-docs.cs-CZ/blob/live/docs/android/get-started/hello-android/hello-android-quickstart.md)
* Product: **xamarin**
* GitHub Login: @conceptdev
* Microsoft Alias: **crdun**

---

@conceptdev commented on [Mon Mar 04 2019](https://github.com/MicrosoftDocs/xamarin-docs.cs-cz/issues/2#issuecomment-469304838)

1. Thanks for your feedback. The filename does seem confusing, since the class name won't match the documentation. The sample code has the same filename, so we'll need to update both the sample & the doc, but we will update it.

2. This does not refer to the **Project** menu, you must "open the **Project Options** dialog by right clicking on the project in the **Solution Pad**". If you right-click on your Android project node in the solution, you will see the **Project Options** dialog.

---

@CeciAc commented on [Mon Mar 04 2019](https://github.com/MicrosoftDocs/xamarin-docs.cs-cz/issues/2#issuecomment-469305576)

Thanks for stepping in, @conceptdev 
I'm moving this issue to the en-us repo. 
You can follow up from there

Kind regards,

**Comment by davidbritch** [comment]
Thanks for submitting an issue and we apologize for the delayed response. The requested updates haven't been made since the creation of the issue, and the timeline for resolution may vary based on resourcing, so the issue is being moved to an internal repo to better track it.

**Comment by davidbritch** [comment]
Thanks for submitting an issue and we apologize for the delayed response. The requested updates haven't been made since the creation of the issue, and the timeline for resolution may vary based on resourcing, so the issue is being moved to an internal repo to better track it.
