### ISSUE TITLE
Microsoft Account Example

### ISSUE THREAD

**Issue by aszalacinski** [MicrosoftDocs/xamarin-docs#1473]
Is it possible to get a Microsoft Account example? The documentation claims implementing other identity providers is just as easy but that is misleading. A link is provided to google documentation but no links to other identity providers. It would be helpful for new Xamarin developer to have the documentation provide links to Microsoft Account, Azure AD, Azure AD B2C, Twitter, Facebook identity provider details and not leave us searching the web for what might or might not be proper documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aa8bb9e0-5898-0d11-0213-fd4d8c8d0297
* Version Independent ID: 2f46e1f7-164f-2f32-70c0-f28919d16c5c
* Content: [Authenticating Users with an Identity Provider - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/data-cloud/authentication/oauth)
* Content Source: [docs/xamarin-forms/data-cloud/authentication/oauth.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/data-cloud/authentication/oauth.md)
* Product: **xamarin**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @aszalacinski 

I've added your suggestion to our backlog.
