### ISSUE TITLE
MessagingCenter Subcriptions and Garbage Collection?

### ISSUE THREAD

**Issue by tbutterfus** [MicrosoftDocs/xamarin-docs#1477]
When an object subscribes to a MessagingCenter message, does that prevent the subscriber object from being garbage collected? Doesn't subscribing to an event on a static object keep the subscriber object alive? If garbage collection of the subscriber is prevented, that could inadvertently cause memory problems and should be mentioned in the docs.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4d80a771-2198-328b-b9fa-fe25f16261cd
* Version Independent ID: be0408fe-d00b-baf6-8a9c-e24659029c4b
* Content: [Xamarin.Forms MessagingCenter - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/messaging-center#feedback)
* Content Source: [docs/xamarin-forms/app-fundamentals/messaging-center.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/app-fundamentals/messaging-center.md)
* Product: **xamarin**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @tbutterfus 

Internally, the `MessagingCenter` class uses weak references. This means that it will not keep objects alive, and will allow them to be garbage collected. Therefore, it should only be necessary to unsubscribe from a message when a class no longer wishes to receive the message.

[This doc ](https://docs.microsoft.com/xamarin/xamarin-forms/enterprise-application-patterns/communicating-between-loosely-coupled-components) explains it in more detail. I'll add a link from the MessagingCenter doc to it.
