### ISSUE TITLE
Content description and example code out of sync

### ISSUE THREAD

**Issue by jraldrin** [MicrosoftDocs/xamarin-docs#1480]
Looked thru example code and there is no code showing how to create a attached prop.  Example is a MUCH more complicated example.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ce1d57d-d599-89c2-3cd4-9c3048dc75f7
* Version Independent ID: 2bf6d771-008b-6e79-4136-114c3dd77733
* Content: [Attached Properties - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/xaml/attached-properties)
* Content Source: [docs/xamarin-forms/xaml/attached-properties.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/xaml/attached-properties.md)
* Product: **xamarin**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @jraldrin 

The only difference between creating an attached property and a bindable property is that the `CreateAttached` method is used to create an attached property, while the `Create` method is used to create a bindable property. 

I see example code in the doc that shows creating an attached property, and it's accessors.

**Comment by mohitatray** [comment]
1 more difference is that in attached property accessors are 2 static methods (GetPropertyName & SetPropertyName) whereas in Bindable property, accessor is a single non-static property with get and set.
