### ISSUE TITLE
Is this applicable anymore

### ISSUE THREAD

**Issue by jraldrin** [MicrosoftDocs/xamarin-docs#1481]
Cant find nuget package with visual studio. Not much activity in repo.  Long thread about repo being dead.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 492ecdea-9257-a3b5-f155-0e55ddcf39d0
* Version Independent ID: d863a7c8-4e21-a8c7-618d-3c4e26704aa3
* Content: [XAML Standard (Preview) - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/xaml/standard/?tabs=windows)
* Content Source: [docs/xamarin-forms/xaml/standard/index.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/xaml/standard/index.md)
* Product: **xamarin**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @jraldrin 

All I can say is that it's never left the preview stage.
