### ISSUE TITLE
SQLLite Nuget 

### ISSUE THREAD

**Issue by sarshad009** [MicrosoftDocs/xamarin-docs#1482]
How about System.Data.Sqlite pkg released by SQL lite recently  in 2019 ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a3059afc-7e56-a214-0463-c87bd9b5ca21
* Version Independent ID: a879cca8-1d5e-bab9-1b2d-32a9ece48022
* Content: [Using SQLite.NET with Xamarin.iOS - Xamarin](https://docs.microsoft.com/en-us/xamarin/ios/data-cloud/data/using-sqlite-orm#feedback)
* Content Source: [docs/ios/data-cloud/data/using-sqlite-orm.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/ios/data-cloud/data/using-sqlite-orm.md)
* Product: **xamarin**
* GitHub Login: @lobrien
* Microsoft Alias: **laobri**

**Comment by conceptdev** [comment]
@sarshad009 I'm not sure what your question is. When you're using SQLite on iOS, you are interacting with the database engine that is shipped with iOS. Xamarin.iOS provides a System.Data API to execute SQL against it; and the SQLite-net NuGet package provides an ORM-like wrapper.
