### ISSUE TITLE
Will the .NET API Browser for Xamarin.Forms > Latest ever get updated to 3.6+ at some point?

### ISSUE THREAD

**Issue by anthcool** [MicrosoftDocs/xamarin-docs#1483]
Hi,

I hope this is the right place.  If not, please steer me in the right place if you would.  Thanks.

I've been trying to use the .NET API Browser > Xamarin.Forms > Latest but it never seems to be...the latest.  Is there a definitive location I can go to for up to date APIs?  Is there such a place?  Or do we have to bookmark version release blog posts forever more?  Cuz I'd rather have up-to-date API docs than announcement blog posts.  Trying to find details on the new Xamarin.Forms.Visual, but nope....

**Comment by lobrien** [comment]
https://docs.microsoft.com/en-us/dotnet/api/xamarin.forms?view=xamarin-forms was updated to Xamarin.Forms 3.6.0 last night.
