### ISSUE TITLE
The link for Custom Renderers (Xamarin University Video) Sample is broken

### ISSUE THREAD

**Issue by hot33331** [MicrosoftDocs/xamarin-docs#1484]
When I click the last link here: https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/custom-renderer/
 I get a 404 page from dropbox.

**Comment by davidbritch** [comment]
Hi @hot33331 

I've removed the sample link, as unfortunately it's no longer available. Xamarin University is currently migrating to Microsoft Learn, and once that's complete there'll be lots of great Xamarin University content.
