### ISSUE TITLE
Very Minor misleading instruction.

### ISSUE THREAD

**Issue by RidhwanDev** [MicrosoftDocs/xamarin-docs#1487]
In stage 2, on step 13. It says to click OK. this should be on 14. Its minor and wouldn't probably give most people a hard time but as somebody who never uses VS Mac It had be wasting a good 20-25 Mintues looking for compiler settings everywhere. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e40fbe03-a099-3b24-4654-162103003d6a
* Version Independent ID: 01e8c667-ed94-7054-758d-2399e879714a
* Content: [Use C/C++ libraries with Xamarin - Xamarin](https://docs.microsoft.com/en-us/xamarin/cross-platform/cpp/#feedback)
* Content Source: [docs/cross-platform/cpp/index.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/cross-platform/cpp/index.md)
* Product: **xamarin**
* GitHub Login: @mikeparker104
* Microsoft Alias: **miparker**

**Comment by lobrien** [comment]
I confirmed that the "Click OK" line is too early and made the necessary edit in https://github.com/MicrosoftDocs/xamarin-docs/compare/live...lobrien-patch-2?quick_pull=1
