### ISSUE TITLE
Wrong ScrollBar Visibility description

### ISSUE THREAD

**Issue by eveldee0680** [MicrosoftDocs/xamarin-docs#1488]
> *Always* indicates that scroll bars will be visible, even when the content **doesn't** fit in the view.

Should be

> *Always* indicates that scroll bars will be visible, even when the content fit in the view.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7c0643eb-b23e-9283-39eb-6fb0b97a1b83
* Version Independent ID: c1f024de-3443-d7a2-7c0a-1d78d619aea4
* Content: [Customizing ListView Appearance - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/listview/customizing-list-appearance)
* Content Source: [docs/xamarin-forms/user-interface/listview/customizing-list-appearance.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/listview/customizing-list-appearance.md)
* Product: **xamarin**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @eveldee0680 

Good catch! Thanks for pointing it out. I've updated it in a PR that will go out later.
