### ISSUE TITLE
Please explain Spellcheck behavoir

### ISSUE THREAD

**Issue by jraldrin** [MicrosoftDocs/xamarin-docs#1489]
Please explain what Spellcheck will do with a misspelled word.  Color? Beep? Underline? 

thanx

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c5afa3c9-4bcb-4986-2161-1bf2feb856b7
* Version Independent ID: 39fc31bd-4b1d-65f3-aaf8-6eb464e9b38a
* Content: [Xamarin.Forms Entry - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/text/entry)
* Content Source: [docs/xamarin-forms/user-interface/text/entry.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/text/entry.md)
* Product: **xamarin**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by conceptdev** [comment]
The `IsSpellCheckEnabled` property is using the spell checking feature provided by the underlying operating system, so it will be different on Android, iOS, Windows, etc. On iOS, for example, a red dotted underline appears, and when you tap the word the corrections are shown. The spell check is not a Xamarin.Forms feature.
