### ISSUE TITLE
sourcesanspro.xml

### ISSUE THREAD

**Issue by SpiegelSoft** [MicrosoftDocs/xamarin-docs#149]
In the sourcesanspro.xml file, the regular font name in inconsistent. There is also no explanation of how the font attribute should relate to the font file names.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c533e61a-a127-7c39-37f8-89d4004147d0
* Version Independent ID: f7a5e26e-c060-1386-24ba-890022a45603
* Content: [Fonts - Xamarin](https://docs.microsoft.com/en-us/xamarin/android/app-fundamentals/resources-in-android/fonts#feedback)
* Content Source: [docs/android/app-fundamentals/resources-in-android/fonts.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/android/app-fundamentals/resources-in-android/fonts.md)
* Service: **unspecified**
* GitHub Login: @topgenorth
* Microsoft Alias: **toopge**

**Comment by topgenorth** [comment]
Thanks for bringing this to our attention. We're in the process of updating this guide based on your feedback.

**Comment by c-lamont** [comment]
No update on this? Where do we reference the actual `.otf` or `.ttf` file?

**Comment by topgenorth** [comment]
Typically apps will  reference the fonts by either using a [font family](https://docs.microsoft.com/en-us/xamarin/android/app-fundamentals/resources-in-android/fonts#font-families) resource, [programmatically by using the `GetFont` method](https://docs.microsoft.com/en-us/xamarin/android/app-fundamentals/resources-in-android/fonts#programmatically-assigning-fonts).

**Comment by asnyder** [comment]
This is still absurd. Again, from your demo you have  app:font="@font/sourcesanspro_regular", does this mean the file is named "sourcesanspro_regular.otf"? Please just give an answer as this is the most vaguely written guide. It's shocking how difficult it is to do something basic like using fonts in Xamarin.
