### ISSUE TITLE
Basic fonts

### ISSUE THREAD

**Issue by yelinzh** [MicrosoftDocs/xamarin-docs#1490]
Are there any basic fonts like Arial or Times Roman the exist across all platforms?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe0572c4-91be-fc86-d130-242db2bf470b
* Version Independent ID: 1238fdd7-c378-6d0d-654e-55656a70d386
* Content: [Fonts in Xamarin.Forms - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/text/fonts)
* Content Source: [docs/xamarin-forms/user-interface/text/fonts.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/text/fonts.md)
* Product: **xamarin**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by conceptdev** [comment]
Xamarin.Forms runs on a lot of platforms, I'm not aware of any font that's guaranteed to be on all of them. I'd recommend not specifying the `FontFamily` (which means your app will use the default) or specify a specific font for each platform that you have tested and know works.
