### ISSUE TITLE
Toolbar discussed in XamarinForms docs?

### ISSUE THREAD

**Issue by jraldrin** [MicrosoftDocs/xamarin-docs#1491]
Hi,

I can't find any mention of the Toolbar in the Xamarin Forms docs(can find class ref in api and blog entry in community blog: https://xamarinhelp.com/xamarin-forms-toolbar/).  

Thanx

John A

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 35a3ba3a-3a14-45a7-9fdd-9ef948962d0b
* Version Independent ID: b1c9a8f2-1b6a-cbc0-ef57-b9b540de7320
* Content: [Hierarchical Navigation - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/navigation/hierarchical)
* Content Source: [docs/xamarin-forms/app-fundamentals/navigation/hierarchical.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/app-fundamentals/navigation/hierarchical.md)
* Product: **xamarin**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @jraldrin 

Although we use the Toolbar/ToolbarItem types throughout our docs/samples, there currently isn't a doc that details the types. I've added an item to our backlog to deal with this.

Thanks for pointing it out.
