### ISSUE TITLE
Reverse GeoCode API does not appear to exist.

### ISSUE THREAD

**Issue by gceaser** [MicrosoftDocs/xamarin-docs#1492]
The write up states there is a way to reversegeocode to a placemark from coordinates but the documentation does not show such an API.  Can you please clarify,

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2ebb7d82-4f75-9c6d-8305-7d40afc3a4aa
* Version Independent ID: cd18ee2b-c941-cc79-c6de-8004294a5e08
* Content: [Xamarin.Essentials: Geocoding - Xamarin](https://docs.microsoft.com/en-us/xamarin/essentials/geocoding?context=xamarin%2Fandroid&tabs=ios#feedback)
* Content Source: [docs/essentials/geocoding.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/essentials/geocoding.md)
* Product: **xamarin**
* GitHub Login: @jamesmontemagno
* Microsoft Alias: **jamont**

**Comment by jamesmontemagno** [comment]
They are both specified in the doc. There is getlocationsasync and getpositionsasync.

Covers both.

**Comment by gceaser** [comment]
Ah - OK I was doing a quick scan for Reverse Geo Coding since that was the verbiage used in the first sentence of the doco.

**Comment by jamesmontemagno** [comment]
https://github.com/MicrosoftDocs/xamarin-docs/pull/1496
