### ISSUE TITLE
Clarification on method "public void InvokeAction (string data)" in class "HybridWebView"

### ISSUE THREAD

**Issue by gsauzet** [MicrosoftDocs/xamarin-docs#1493]
On this line: if (action == null || data == null) {
What is the reasoning behind it not being string.IsNullOrWhiteSpace(data)
Is an empty string an expected data to pass into the action, if yes, why is a null data not expected as well.
Thank you.
 

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9c1bd30c-6e7a-df38-8c20-dff7361e901f
* Version Independent ID: 013c6027-db9a-6039-3404-2e4f717133a9
* Content: [Implementing a HybridWebView - Xamarin](https://docs.microsoft.com/en-gb/xamarin/xamarin-forms/app-fundamentals/custom-renderer/hybridwebview#feedback)
* Content Source: [docs/xamarin-forms/app-fundamentals/custom-renderer/hybridwebview.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/app-fundamentals/custom-renderer/hybridwebview.md)
* Product: **xamarin**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @gsauzet 

`string.IsNullOrWhiteSpace` applies here. The example has changed over time, and didn't originally use string data.
