### ISSUE TITLE
AlignSelf attached property's usage

### ISSUE THREAD

**Issue by landl0526** [MicrosoftDocs/xamarin-docs#1495]
FlexAlign.SetAlignSelf(label, FlexAlignSelf.Center); should be adjusted to FlexLayout.SetAlignSelf(label, FlexAlignSelf.Center);
So do the XAML's attached bindable properties' usage.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b954b795-b38e-61ff-3ba1-26a0623b97e6
* Version Independent ID: 65795b50-24d3-1997-038e-ffdb609eb20b
* Content: [The Xamarin.Forms FlexLayout - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/layouts/flex-layout#the-attached-bindable-properties-in-detail)
* Content Source: [docs/xamarin-forms/user-interface/layouts/flex-layout.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/layouts/flex-layout.md)
* Product: **xamarin**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @landl0526 

Thanks for pointing this out. I've just fixed this in a PR that will go out later.
