### ISSUE TITLE
content issue

### ISSUE THREAD

**Issue by XfHua** [MicrosoftDocs/xamarin-docs#1498]
In the paragraph: Here’s the final complete XAML file with three buttons accessing six shared values....

&lt;x:String x:Key="fontSize"&gt;Large&lt;/x:String&gt; is not working right now.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 673a2420-3d41-aa5d-a8e4-3383cf10da6e
* Version Independent ID: ecdf7b35-97d1-524d-d448-9b7865b5b66a
* Content: [Part 3. XAML Markup Extensions - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/xaml/xaml-basics/xaml-markup-extensions#shared-resources)
* Content Source: [docs/xamarin-forms/xaml/xaml-basics/xaml-markup-extensions.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/xaml/xaml-basics/xaml-markup-extensions.md)
* Product: **xamarin**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @XfHua 

Thanks for pointing this out.

`<x:String x:Key="fontSize">Large</x:String>` is fine when XAMLC is disabled, but errors when XAMLC is enabled.

I've updated the code in the doc, in a PR that will go out later, to `<x:Double x:Key="fontSize">24</x:Double>`, which works fine with XAMLC.
