### ISSUE TITLE
Unzipping .aar files

### ISSUE THREAD

**Issue by crehmann** [MicrosoftDocs/xamarin-docs#15]
In addition to manually downloading and Installing the m2repository files, I had also to unzip the .aar files. For me this was was necessary after copying the .jar, .aar and .pom (step 8) into the embedded folder.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c15260a1-cdda-66da-dbeb-21910fe39948
* Version Independent ID: a063162a-1ae5-8ea1-f2ed-6e9f5c7b7adb
* Content: [Resolving Library Installation Errors - Xamarin | Microsoft Docs](https://docs.microsoft.com/en-us/xamarin/android/troubleshooting/resolving-library-installation-errors#feedback)
* Content Source: [docs/android/troubleshooting/resolving-library-installation-errors.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/android/troubleshooting/resolving-library-installation-errors.md)
* Service: **unspecified**
* GitHub Login: @mgmclemore
* Microsoft Alias: **mamcle**

**Comment by mgmclemore** [comment]
@crehmann, thank you for the suggestion for the extra step!  Changes should be published soon.

**Comment by tejasklodha** [comment]
I am Getting below error.

Severity	Code	Description	Project	File	Line	Suppression State
Error		An error occurred trying to install required android components on Project 'CustomerOutstanding.Android'.
Project 'CustomerOutstanding.Android' requires the following components installed on your machine: 
Xamarin.Android.Support.Animated.Vector.Drawable
JavaLibraryReference: https://dl-ssl.google.com/android/repository/android_m2repository_r29.zip-m2repository/com/android/support/animated-vector-drawable/23.3.0/animated-vector-drawable-23.3.0.aar-23.3.0.0
AndroidResources: https://dl-ssl.google.com/android/repository/android_m2repository_r29.zip-m2repository/com/android/support/animated-vector-drawable/23.3.0/animated-vector-drawable-23.3.0.aar-23.3.0.0
Xamarin.Android.Support.Design
JavaLibraryReference: https://dl-ssl.google.com/android/repository/android_m2repository_r29.zip-m2repository/com/android/support/design/23.3.0/design-23.3.0.aar-23.3.0.0
AndroidResources: https://dl-ssl.google.com/android/repository/android_m2repository_r29.zip-m2repository/com/android/support/design/23.3.0/design-23.3.0.aar-23.3.0.0
Xamarin.Android.Support.v4
JavaLibraryReference: https://dl-ssl.google.com/android/repository/android_m2repository_r29.zip-m2repository/com/android/support/support-v4/23.3.0/support-v4-23.3.0.aar-23.3.0.0
JavaLibraryReference: https://dl-ssl.google.com/android/repository/android_m2repository_r29.zip-m2repository/com/android/support/support-v4/23.3.0/support-v4-23.3.0.aar-23.3.0.0
AndroidResources: https://dl-ssl.google.com/android/repository/android_m2repository_r29.zip-m2repository/com/android/support/support-v4/23.3.0/support-v4-23.3.0.aar-23.3.0.0
Xamarin.Android.Support.v7.AppCompat
JavaLibraryReference: https://dl-ssl.google.com/android/repository/android_m2repository_r29.zip-m2repository/com/android/support/appcompat-v7/23.3.0/appcompat-v7-23.3.0.aar-23.3.0.0
AndroidResources: https://dl-ssl.google.com/android/repository/android_m2repository_r29.zip-m2repository/com/android/support/appcompat-v7/23.3.0/appcompat-v7-23.3.0.aar-23.3.0.0
Xamarin.Android.Support.v7.CardView
JavaLibraryReference: https://dl-ssl.google.com/android/repository/android_m2repository_r29.zip-m2repository/com/android/support/cardview-v7/23.3.0/cardview-v7-23.3.0.aar-23.3.0.0
AndroidResources: https://dl-ssl.google.com/android/repository/android_m2repository_r29.zip-m2repository/com/android/support/cardview-v7/23.3.0/cardview-v7-23.3.0.aar-23.3.0.0
Xamarin.Android.Support.v7.MediaRouter
JavaLibraryReference: https://dl-ssl.google.com/android/repository/android_m2repository_r29.zip-m2repository/com/android/support/mediarouter-v7/23.3.0/mediarouter-v7-23.3.0.aar-23.3.0.0
JavaLibraryReference: https://dl-ssl.google.com/android/repository/android_m2repository_r29.zip-m2repository/com/android/support/mediarouter-v7/23.3.0/mediarouter-v7-23.3.0.aar-23.3.0.0
AndroidResources: https://dl-ssl.google.com/android/repository/android_m2repository_r29.zip-m2repository/com/android/support/mediarouter-v7/23.3.0/mediarouter-v7-23.3.0.aar-23.3.0.0
Xamarin.Android.Support.v7.RecyclerView
JavaLibraryReference: https://dl-ssl.google.com/android/repository/android_m2repository_r29.zip-m2repository/com/android/support/recyclerview-v7/23.3.0/recyclerview-v7-23.3.0.aar-23.3.0.0
AndroidResources: https://dl-ssl.google.com/android/repository/android_m2repository_r29.zip-m2repository/com/android/support/recyclerview-v7/23.3.0/recyclerview-v7-23.3.0.aar-23.3.0.0
Xamarin.Android.Support.v8.RenderScript
JavaLibraryReference: http://dl-ssl.google.com/android/repository/build-tools_r23-macosx.zip--23
NativeLibraryReference: http://dl-ssl.google.com/android/repository/build-tools_r23-macosx.zip--23
NativeLibraryReference: http://dl-ssl.google.com/android/repository/build-tools_r23-macosx.zip--23
NativeLibraryReference: http://dl-ssl.google.com/android/repository/build-tools_r23-macosx.zip--23
NativeLibraryReference: http://dl-ssl.google.com/android/repository/build-tools_r23-macosx.zip--23
Xamarin.Android.Support.Vector.Drawable
JavaLibraryReference: https://dl-ssl.google.com/android/repository/android_m2repository_r29.zip-m2repository/com/android/support/support-vector-drawable/23.3.0/support-vector-drawable-23.3.0.aar-23.3.0.0
AndroidResources: https://dl-ssl.google.com/android/repository/android_m2repository_r29.zip-m2repository/com/android/support/support-vector-drawable/23.3.0/support-vector-drawable-23.3.0.aar-23.3.0.0


Please double-click here to install it.

Intallation Errors: XA5207 Please install package: 'Xamarin.Android.Support.Animated.Vector.Drawable' available in SDK installer. Java library file 'C:\Users\FMIJ9T7BH2\AppData\Local\Xamarin\Xamarin.Android.Support.Animated.Vector.Drawable\23.3.0.0\embedded\classes.jar' doesn't exist.
XA5207 Please install package: 'Xamarin.Android.Support.Design' available in SDK installer. Java library file 'C:\Users\FMIJ9T7BH2\AppData\Local\Xamarin\Xamarin.Android.Support.Design\23.3.0.0\content\classes.jar' doesn't exist.
XA5207 Please install package: 'Xamarin.Android.Support.v4' available in SDK installer. Java library file 'C:\Users\FMIJ9T7BH2\AppData\Local\Xamarin\Xamarin.Android.Support.v4\23.3.0.0\content\classes.jar' doesn't exist.
XA5207 Please install package: 'Xamarin.Android.Support.v4' available in SDK installer. Java library file 'C:\Users\FMIJ9T7BH2\AppData\Local\Xamarin\Xamarin.Android.Support.v4\23.3.0.0\content\libs/internal_impl-23.3.0.jar' doesn't exist.
XA5207 Please install package: 'Xamarin.Android.Support.v7.AppCompat' available in SDK installer. Java library file 'C:\Users\FMIJ9T7BH2\AppData\Local\Xamarin\Xamarin.Android.Support.v7.AppCompat\23.3.0.0\content\classes.jar' doesn't exist.
XA5207 Please install package: 'Xamarin.Android.Support.v7.CardView' available in SDK installer. Java library file 'C:\Users\FMIJ9T7BH2\AppData\Local\Xamarin\Xamarin.Android.Support.v7.CardView\23.3.0.0\content\classes.jar' doesn't exist.
XA5207 Please install package: 'Xamarin.Android.Support.v7.MediaRouter' available in SDK installer. Java library file 'C:\Users\FMIJ9T7BH2\AppData\Local\Xamarin\Xamarin.Android.Support.v7.MediaRouter\23.3.0.0\content\classes.jar' doesn't exist.
XA5207 Please install package: 'Xamarin.Android.Support.v7.MediaRouter' available in SDK installer. Java library file 'C:\Users\FMIJ9T7BH2\AppData\Local\Xamarin\Xamarin.Android.Support.v7.MediaRouter\23.3.0.0\content\libs/internal_impl-23.3.0.jar' doesn't exist.
XA5207 Please install package: 'Xamarin.Android.Support.v7.RecyclerView' available in SDK installer. Java library file 'C:\Users\FMIJ9T7BH2\AppData\Local\Xamarin\Xamarin.Android.Support.v7.RecyclerView\23.3.0.0\content\classes.jar' doesn't exist.
XA5207 Please install package: 'Android Support Library v8' available in SDK installer. Java library file 'C:\Users\FMIJ9T7BH2\AppData\Local\Xamarin\Xamarin.Android.Support.v8.RenderScript\23\content\android-6.0/renderscript/lib/renderscript-v8.jar' doesn't exist.
XA5210 Please install package: 'Android Support Library v8' available in SDK installer. Native library file 'C:\Users\FMIJ9T7BH2\AppData\Local\Xamarin\Xamarin.Android.Support.v8.RenderScript\23\content\android-6.0/renderscript/lib/packaged/armeabi-v7a/librsjni.so' doesn't exist.
XA5210 Please install package: 'Android Support Library v8' available in SDK installer. Native library file 'C:\Users\FMIJ9T7BH2\AppData\Local\Xamarin\Xamarin.Android.Support.v8.RenderScript\23\content\android-6.0/renderscript/lib/packaged/armeabi-v7a/libRSSupport.so' doesn't exist.
XA5210 Please install package: 'Android Support Library v8' available in SDK installer. Native library file 'C:\Users\FMIJ9T7BH2\AppData\Local\Xamarin\Xamarin.Android.Support.v8.RenderScript\23\content\android-6.0/renderscript/lib/packaged/x86/librsjni.so' doesn't exist.
XA5210 Please install package: 'Android Support Library v8' available in SDK installer. Native library file 'C:\Users\FMIJ9T7BH2\AppData\Local\Xamarin\Xamarin.Android.Support.v8.RenderScript\23\content\android-6.0/renderscript/lib/packaged/x86/libRSSupport.so' doesn't exist.
XA5207 Please install package: 'Xamarin.Android.Support.Vector.Drawable' available in SDK installer. Java library file 'C:\Users\FMIJ9T7BH2\AppData\Local\Xamarin\Xamarin.Android.Support.Vector.Drawable\23.3.0.0\content\classes.jar' doesn't exist.		 	0	

and tried above steps but problem is not resolved.

Tejas

**Comment by mgmclemore** [comment]
Hi @tejasklodha, this repository is intended to be used for feedback about documentation. If you think you've found a bug, it's best to file it [here](https://github.com/xamarin/xamarin-android/issues) (this is where issues are now tracked). Hope this helps. Thanks again for the feedback!
