### ISSUE TITLE
Localization for related activities - like push notifications

### ISSUE THREAD

**Issue by nhwilly** [MicrosoftDocs/xamarin-docs#150]
Great article. Helped a lot. 

It might also be helpful if some mention was made of the fact that inbound push notifications using `ms-resource` for localization do not work with RESX files and in fact only work with RESW files for UWP apps.  It's a completely different folder structure, etc.   Took me a while to figure out why my stuff wouldn't translate.

 A link to the UWP localization page, maybe iOS/Android, too, would be useful.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8b266d6b-e06e-4f00-5f2d-1c59f6d867e5
* Version Independent ID: d2ecb827-c44e-97e2-0352-b4c5082d81c8
* Content: [Localization - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/localization?tabs=vswin#localizing-platform-specific-elements)
* Content Source: [docs/xamarin-forms/app-fundamentals/localization.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/app-fundamentals/localization.md)
* Service: **unspecified**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @nhwilly 

Apologies for the delayed response to your issue.

I've updated the localization page as per your suggestion, and it will go live once the PR is merged.

Thanks again.
