### ISSUE TITLE
Typo: "includes this such as"

### ISSUE THREAD

**Issue by alataffective** [MicrosoftDocs/xamarin-docs#1501]
Typo in Rendering section: "includes this such as"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d241cf7c-c6ba-d783-cbf0-9b5219b03cee
* Version Independent ID: 747012d7-266a-66d8-7471-e19f28a9f7a4
* Content: [WPF vs. Xamarin.Forms App Lifecycle - Xamarin](https://docs.microsoft.com/en-us/xamarin/cross-platform/desktop/lifecycle#feedback)
* Content Source: [docs/cross-platform/desktop/lifecycle.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/cross-platform/desktop/lifecycle.md)
* Product: **xamarin**
* GitHub Login: @asb3993
* Microsoft Alias: **amburns**

**Comment by conceptdev** [comment]
Thanks @alataffective fixing it now.
