### ISSUE TITLE
could msbuild remember the ssh connection for reuse?

### ISSUE THREAD

**Issue by fatfatson** [MicrosoftDocs/xamarin-docs#1504]
everytime it will reconnect and there's chance connect fails, why don't let it keep the connection alive?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 98c96bcc-1743-8d9f-f1b2-3c30d5b2a6e2
* Version Independent ID: f57a6157-332a-3f31-c785-7efa99e62711
* Content: [Pair to Mac for Xamarin.iOS Development - Xamarin](https://docs.microsoft.com/en-us/xamarin/ios/get-started/installation/windows/connecting-to-mac/index#feedback)
* Content Source: [docs/ios/get-started/installation/windows/connecting-to-mac/index.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/ios/get-started/installation/windows/connecting-to-mac/index.md)
* Product: **xamarin**
* GitHub Login: @lobrien
* Microsoft Alias: **laobri**

**Comment by fatfatson** [comment]
sometime it could not connect, but i'm sure i could always ssh into my mac everytime!
> C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.After.targets(254,3): warning : 由于没有到 Mac 的可用连接，因此将不会执行任务 ResolveUniversalTypeIdentifiers [D:\code\mb\mb
> .iOS\mb.iOS.csproj]
> C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(1153,3): warning : 由于没有到 Mac 的可用连接，因此将不会执行任务 Xamarin.MacDev.Tasks.CollectBundleResources [D:\cod
> e\mb\mb.iOS\mb.iOS.csproj]

**Comment by conceptdev** [comment]
Hi @fatfatson thanks for your feedback. If you continue to have connection issues with your Mac, please [report the problem using Visual Studio](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2017) since this will include detailed information that can help diagnose any problems.
