### ISSUE TITLE
No JDK folder

### ISSUE THREAD

**Issue by petemillermultimedia** [MicrosoftDocs/xamarin-docs#1505]
I have Xamarin installed via Visual Studio Community. I have no C:\Program Files (x86)\Java folder, nor do I have keytool anywhere in my system.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 80d55339-006a-0aec-13cb-6d2b8d4592a7
* Version Independent ID: 43d2c9a2-d208-1e80-606c-d2c9e8351110
* Content: [Finding your Keystore's Signature - Xamarin](https://docs.microsoft.com/en-us/xamarin/android/deploy-test/signing/keystore-signature?tabs=windows)
* Content Source: [docs/android/deploy-test/signing/keystore-signature.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/android/deploy-test/signing/keystore-signature.md)
* Product: **xamarin**
* GitHub Login: @conceptdev
* Microsoft Alias: **crdun**

**Comment by conceptdev** [comment]
Hi @petemillermultimedia can you report this [via Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2017)? That will include additional product and system information that can help diagnose any problems.
Thanks.
