### ISSUE TITLE
My issue got locked for spam?

### ISSUE THREAD

**Issue by StingyJack** [MicrosoftDocs/xamarin-docs#1507]
https://github.com/MicrosoftDocs/xamarin-docs/issues/735

I didnt say anything spammy.

And why cant the author make further comments?

**Comment by conceptdev** [comment]
Hi @StingyJack it was not you spamming, but another user who was adding multiple unrelated comments to the thread. It was locked in part to prevent your inbox from being filled up with the notifications from those posts.

This is no way related to you or your original issue. It was closed 6 months ago, but if you have further questions on the page, please feel free to open a new issue. We appreciate your feedback and involvement with the docs.

I have changed the lock reason to *Resolved*, to avoid the appearance that the original question was spam.

**Comment by StingyJack** [comment]
It's kind of annoying that that kind of locking blocks the author, but w/e. Thanks for the update.

**Comment by conceptdev** [comment]
Yeah, I agree with that. I did try just deleting the spammy comments - but they kept coming, and I felt like locking it was the best way to clearly communicate that behavior is against our code of conduct. Thanks for your understanding.
