### ISSUE TITLE
Pitiful

### ISSUE THREAD

**Issue by billyard61** [MicrosoftDocs/xamarin-docs#1508]
This is some of the worst documentation I've seen. Partial/nonexistent examples are not very helpful - see "Creating a Custom Renderer Class". Troubleshooting? What is there to troubleshoot based on this documentation? Laziness rules whoever did this garbage.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9c42adf4-cc4f-3269-6c1e-e338eba1de44
* Version Independent ID: 8c949e94-ce7b-9b42-5853-24615b84e21e
* Content: [Introduction to Custom Renderers - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/custom-renderer/introduction#feedback)
* Content Source: [docs/xamarin-forms/app-fundamentals/custom-renderer/introduction.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/app-fundamentals/custom-renderer/introduction.md)
* Product: **xamarin**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by conceptdev** [comment]
There are 21 separate pages of custom renderer documentation, along with [8 complete samples on GitHub](https://github.com/xamarin/xamarin-forms-samples/tree/master/CustomRenderers). Once you have read and tried all these, please post any specific questions or feedback you may have.
