### ISSUE TITLE
Ellipsis in step 13 and designer question

### ISSUE THREAD

**Issue by GovirDrauka** [MicrosoftDocs/xamarin-docs#1509]
In the sample code for step 13, there is an ellipsis (...) which is causing my project not to build. Is this supposed to just be removed, or is there something specifically that it should be replaced with?

Additionally, I'm working on getting my hands on an actual Android phone (because the emulator is very slow on my machine). For now I'm looking at the designers of the pages, but I get an error (System.IO.IOException: Error 123) when opening NotesPage.xaml in designer. Is that expected?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 60587f77-05de-89b9-8a08-c7e7221d27af
* Version Independent ID: 4080b687-b353-f833-4bb7-a7a3f9993338
* Content: [Perform navigation in a multi-page Xamarin.Forms application - Xamarin](https://docs.microsoft.com/en-us/xamarin/get-started/quickstarts/multi-page?pivots=windows#feedback)
* Content Source: [docs/get-started/quickstarts/multi-page.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/get-started/quickstarts/multi-page.md)
* Product: **xamarin**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by GovirDrauka** [comment]
And of course, I didn't think to download the sample project before asking this question. I see now that the ellipsis is for the OnStart(), OnSleep(), and OnResume() functions.

I am do still get the same error when opening the Designer of NotesPage.xaml in the downloaded project as well.

**Comment by davidbritch** [comment]
Hi @GovirDrauka 

I've opened NotesPage.xaml in the previewer without any problems.

**Comment by walter-grace** [comment]
Since we are here, I had a question I was getting an invalid token error line 19 (...) on app.xaml.cs, the question above looked similar. Wonder how to fix that? Also, I didn't know you could connect to your actual mobile device, how would one go about doing that. I am new to app development, thanks in advanced

**Comment by walter-grace** [comment]
Also, how can I learn how to import a downloaded sample directly into VS? I have sample folders downloaded that I would like to import into VS and make life a bit easier.

**Comment by GovirDrauka** [comment]
@walter-grace
1. The ellipsis line can be commented out. In the sample, you will see empty override methods there, but they are not strictly needed.

2. I don't have an android device, and I thought it was just plug and go, but looks like there may be more too it. Here's an article I found, but have not tried: https://docs.microsoft.com/en-us/xamarin/android/deploy-test/debugging/debug-on-device?tabs=windows

3. You do not need to "import" the sample into VisualStudio. It should have contained a solution file (Notes.sln). Opening that file will open the whole sample. If you still have it as a ZIP file, then you need to extract it (the archive does not have a base folder, so be careful where you extract it. I almost overwrote my own project).
