### ISSUE TITLE
import not correct & new database creation not working.

### ISSUE THREAD

**Issue by Karlheinzniebuhr** [MicrosoftDocs/xamarin-docs#151]
the import "using SQLite;" does not work, it has to be "using SQLite.Net;" in order to resolve. Also, the SQLiteConnection(dbPath) is taking more than one arguments which is why I receive the error "sqlite.net.sqliteconnection' does not contain a constructor that takes 1 arguments" when doing the tutorial. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c07438f1-7799-35a5-c6aa-86ce411694b1
* Version Independent ID: 7d3ccdcd-5165-99cf-9184-dcc966dbd25e
* Content: [Using SQLite.NET - Xamarin](https://docs.microsoft.com/en-us/xamarin/android/data-cloud/data-access/using-sqlite-orm#feedback)
* Content Source: [docs/android/data-cloud/data-access/using-sqlite-orm.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/android/data-cloud/data-access/using-sqlite-orm.md)
* Service: **unspecified**
* GitHub Login: @mgmclemore
* Microsoft Alias: **mamcle**

**Comment by Karlheinzniebuhr** [comment]
Solved this issue by installing the sqlite-net-pcl package which has 700K+ downloads. There are several other packages which have 280K+ downloads. They are not working with this tutorial but they appear on top of the "sqlite-net-pcl" search. This should be specified in the guide.

**Comment by conceptdev** [comment]
@Karlheinzniebuhr glad you were able to resolve the issue.

You're right - we could be clearer about the specific package name that's required. We'll update the guide to help readers find to the correct package. Thanks for your help!

**Comment by conceptdev** [comment]
Both this doc and the companion [iOS doc](https://docs.microsoft.com/xamarin/ios/data-cloud/data/using-sqlite-orm) have been updated to be more specific about the NuGet package required. Thanks again for the feedback.
