### ISSUE TITLE
Classes which implement an Idisposeable interface 

### ISSUE THREAD

**Issue by BrayanKhosravian** [MicrosoftDocs/xamarin-docs#1510]
What's about classes which implement an Idisposeable interface?

Will the dispose method be automatically called or has the user explicitly call the method? 
And when not calling the dispose method will the unmanaged resourced get freed? 
Sincerely brayan

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6e9eecf7-0edb-5b24-964c-a1ae2e7556ba
* Version Independent ID: 8f9243b4-0f7c-6aac-39e2-913173ea472a
* Content: [Introduction to DependencyService - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/dependency-service/introduction)
* Content Source: [docs/xamarin-forms/app-fundamentals/dependency-service/introduction.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/app-fundamentals/dependency-service/introduction.md)
* Product: **xamarin**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @BrayanKhosravian 

Great questions.

By default, retrieved services are singletons and will live for the lifetime of the app. However, when calling the `Get` method you can specify `DependencyFetchTarget.NewInstance` as an argument. This will create a new instance of the service each time `Get` is called, with the app then being responsible for freeing up any resources e.g.

```
var myService = DependencyService.Get<IMyService>(DependencyFetchTarget.NewInstance);
using (myService as IDisposable)
{
    myService.DoStuff();
}
```

I've created an issue in our backlog to refresh the DependencyService docs, to mention such issues.
