### ISSUE TITLE
What is the difference between DependencyService and CustomRenderer

### ISSUE THREAD

**Issue by arvindrajachourasiya** [MicrosoftDocs/xamarin-docs#1512]
I have struggling to find difference between DependencyService and CustomRenderer. In which cases DepService won't work so we go for custom renderer. What is difference between these two.

What is the lists of scenario when we should go with DepService?

Thank you

**Comment by conceptdev** [comment]
CustomRenderer is for _rendering_ controls, as you can see from the [examples](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/custom-renderer/index): entry, map, listview, etc. Create a custom renderer if you want to change the way a control looks, or write your own.

DependencyService is for accessing platform-specific implementations, typically methods or properties (often they don't have a UI component). See the [examples](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/dependency-service/) like text-to-speech, orientation, or battery. Note they are just examples of _how_ to build one - those features are now available via [Xamarin.Essentials](https://docs.microsoft.com/en-us/xamarin/essentials/?context=xamarin/xamarin-forms).
