### ISSUE TITLE
Linking an applicaiton to the Azure-Cloud-App

### ISSUE THREAD

**Issue by karimzey9** [MicrosoftDocs/xamarin-docs#1515]
![image](https://user-images.githubusercontent.com/42332259/54807277-bdf8c980-4c4a-11e9-8ce2-4fdbd223cb27.png)

I was watching a tutorial vidoe of how to make an app.
 During the process of making, we created an app using C#, Cross-platforms. 
Then I tried to add to the Cloud services. by following this is procedure. File-Add-New project- Cloud - ASP.NET we..... - then Azzure mobile app. As soon as i click ok, it thows an error message.
 is there anyone who know how to fix this ? or provide any suppor ?

**Comment by dannyjr894** [comment]
What is this I'm afraid to press n e thing now

**Comment by conceptdev** [comment]
Hi @karimzey9 you can report the problem [in Visual Studio](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) which will raise an issue you can discuss on the [Developer Community site](https://developercommunity.visualstudio.com/spaces/8/index.html).

**Comment by karimzey9** [comment]
Thanks
