### ISSUE TITLE
Read SMS

### ISSUE THREAD

**Issue by developerult** [MicrosoftDocs/xamarin-docs#1517]
Does xamarin essentials has sms read method to read the mobile sms.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e9f58f89-6349-2778-fc01-c565f7834f62
* Version Independent ID: e81b037b-2beb-d0ff-d47f-27130f6e2d5c
* Content: [Sms Class (Xamarin.Essentials)](https://docs.microsoft.com/en-us/dotnet/api/xamarin.essentials.sms?view=xamarin-essentials#feedback)
* Content Source: [docs/en/Xamarin.Essentials/Sms.xml](https://github.com/xamarin/Essentials/blob/live/docs/en/Xamarin.Essentials/Sms.xml)
* Product: **xamarin**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by conceptdev** [comment]
No, this is not a feature available across all the supported platforms.
