### ISSUE TITLE
problem to show a video on iOS

### ISSUE THREAD

**Issue by MarianXXL** [MicrosoftDocs/xamarin-docs#1519]
If I try to show the video modal on iOS it works only once, the second time it doesn't Show any view. 

To test it, change the example code  like this:

        public HomePage()
        {
            InitializeComponent();

            NavigateCommand = new Command&lt;Type&gt;(async (Type pageType) =&gt;
            {
                Page page = (Page)Activator.CreateInstance(pageType);
                await Navigation.PushModalAsync(page);
            });

            BindingContext = this;
        }

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0081290c-715f-d4fa-38ca-6cfdfd65b5c0
* Version Independent ID: 8fd98837-f8b5-d341-c18c-6ca2c760973d
* Content: [Implementing a video player - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/custom-renderer/video-player/#feedback)
* Content Source: [docs/xamarin-forms/app-fundamentals/custom-renderer/video-player/index.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/app-fundamentals/custom-renderer/video-player/index.md)
* Product: **xamarin**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @MarianXXL 

This is because the sample is not designed to work with modal navigation. The `VideoPlayerRenderer` on iOS would require rework for this scenario.
