### ISSUE TITLE
Android designer not rendering properly

### ISSUE THREAD

**Issue by sidsrf** [MicrosoftDocs/xamarin-docs#152]
Please see the screenshot. It says it all. 

![sketch 1](https://user-images.githubusercontent.com/26246421/38769098-0c88dec4-401b-11e8-94a6-498230aad028.png)

Because of this problem, I am having problems designing the UI

**Comment by topgenorth** [comment]
Sorry that the Xamarin.Android designer is having problems rendering. On thing you can try is to try a Rebuild All, and the look at the build log. Hopefully there will be an error message that explains exactly what is causing the designer errors.

**Comment by topgenorth** [comment]
Please visit the [Visual Studio Developer Community](https://developercommunity.visualstudio.com/) and for support with the Xamarin.Android designer.
