### ISSUE TITLE
It's will be nice when can be read and return as Stream!

### ISSUE THREAD

**Issue by nguyenthanhliemfc** [MicrosoftDocs/xamarin-docs#1521]
Thank for you Plugin!
It's will be nice when can be read and return as Stream!
Thank!

---
#### Chi tiết tài liệu

⚠ *Không chỉnh sửa phần này. Điều này là bắt buộc cho docs.microsoft.com ➟ Vấn đề khi liên kết GitHub.*

* ID: 91d50947-38a1-44b7-2684-63b17d5bac66
* Version Independent ID: b449b3f5-7a68-fdea-041b-71cc39a46a48
* Content: [Xamarin.Essentials: File System Helpers - Xamarin](https://docs.microsoft.com/vi-vn/xamarin/essentials/file-system-helpers?context=xamarin%2Fandroid&tabs=android)
* Content Source: [docs/essentials/file-system-helpers.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/essentials/file-system-helpers.md)
* Product: **xamarin**
* GitHub Login: @jamesmontemagno
* Microsoft Alias: **jamont**

**Comment by jamesmontemagno** [comment]
Please submit feature requests at http://github.com/xamarin/essentials
