### ISSUE TITLE
EntryCell misleading info

### ISSUE THREAD

**Issue by eveldee0680** [MicrosoftDocs/xamarin-docs#1523]
For the EntryCell, it is said:

> Label – The label text to display to the **right** of the text entry field.

It should be instead:

> Label – The label text to display to the **left** of the text entry field.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7ad16e14-5abd-7115-a64a-69db1178d58a
* Version Independent ID: 1602a6ea-3968-006b-9d63-63c25051b5b4
* Content: [Xamarin.Forms TableView - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/tableview#switchcell)
* Content Source: [docs/xamarin-forms/user-interface/tableview.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/tableview.md)
* Product: **xamarin**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @eveldee0680 

Thanks for pointing this out. I've updated the doc, which will go out in a PR later.
