### ISSUE TITLE
Provide background information or links regarding -shm and -wal files

### ISSUE THREAD

**Issue by robinne** [MicrosoftDocs/xamarin-docs#1524]
I have found that 3 files are created, my "mydatabase.db", along with "mydatabase.db-wal" and "mydatabase.db-shm". I have only run across this in an attempt to backup the database. I am unable to simply copy "mydatabase.db" to the file system, as all changes are sitting in wait, in the -wal file. Even using db.close does not resolve this. Please provide best practices for opening and closing the database or how to get rid of wal file by using exclusive access. I am using all async calls. the -wal and -shm files are created immediately upon creating the database per these instructions. This is all being done on iOS simulator. The instructions here are helpful, but don't provide Xamarin/C# instructions. https://www.sqlite.org/walformat.html. Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3ab6098a-39c7-151f-124b-f88aa62c4659
* Version Independent ID: dc27c1e4-ff12-c1af-646a-c2617def0bcd
* Content: [Xamarin.Forms Local Databases - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/databases)
* Content Source: [docs/xamarin-forms/app-fundamentals/databases.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/app-fundamentals/databases.md)
* Product: **xamarin**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by conceptdev** [comment]
Hi @robinne, my first suggestion would be to always test on an actual device rather than the simulator. You will get different behavior in the simulator.

Low-level details of SQLite are beyond the scope of our documentation.

The question about closing connections so the database file can be copied is a good one, we'll consider adding that in a future update of this content.

**Comment by robinne** [comment]
Actual device also uses wal file because when I export the .db file to iOS "Files", same issue, no data or very old data. Close() worked once, but never again (to flush the WAL file). This code did work:
var x = DependencyService.Get<IDatabaseConnection>().DBConnect();
            x.ExecuteScalarAsync<int>("PRAGMA wal_checkpoint(RESTART);", new string[] { });

**Comment by conceptdev** [comment]
Great, thanks for the additional info - appreciate it. I've added it to our backlog.
