### ISSUE TITLE
source code

### ISSUE THREAD

**Issue by khairnar** [MicrosoftDocs/xamarin-docs#1526]
Please let me know source code link. 
Link provided on top of this page, does not contain this sample

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6f1dc742-1e5f-dbb1-df52-b7da9a5b41ce
* Version Independent ID: 54dcd81d-86a7-10ca-5f82-a003284e237b
* Content: [Touch Manipulations - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/graphics/skiasharp/transforms/touch#feedback)
* Content Source: [docs/xamarin-forms/user-interface/graphics/skiasharp/transforms/touch.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/graphics/skiasharp/transforms/touch.md)
* Product: **xamarin**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by conceptdev** [comment]
The link at the top of the page ultimately goes to sample on GitHub:
https://github.com/xamarin/xamarin-forms-samples/tree/master/SkiaSharpForms/Demos/Demos/SkiaSharpFormsDemos

You will see most of the code from this page in this folder, eg `TouchManipulationPage`, `BitmapScatterViewPage`, etc.

There is also a note at the start of the page, to also review this sample https://github.com/xamarin/xamarin-forms-samples/tree/master/Effects/TouchTrackingEffect

It does appear that some classes are not included - eg. BitmapDraggingPage - these will have to be implemented from the code snippets. We will investigate adding them to the sample in future.
