### ISSUE TITLE
Is this support UWP.

### ISSUE THREAD

**Issue by nguyenthanhliemfc** [MicrosoftDocs/xamarin-docs#1527]
Thank you for your docs!
Is this support UWP!
Thank!

---
#### Chi tiết tài liệu

⚠ *Không chỉnh sửa phần này. Điều này là bắt buộc cho docs.microsoft.com ➟ Vấn đề khi liên kết GitHub.*

* ID: aa8bb9e0-5898-0d11-0213-fd4d8c8d0297
* Version Independent ID: 2f46e1f7-164f-2f32-70c0-f28919d16c5c
* Content: [Authenticating Users with an Identity Provider - Xamarin](https://docs.microsoft.com/vi-vn/xamarin/xamarin-forms/data-cloud/authentication/oauth#feedback)
* Content Source: [docs/xamarin-forms/data-cloud/authentication/oauth.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/data-cloud/authentication/oauth.md)
* Product: **xamarin**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by conceptdev** [comment]
According to the [Xamarin.Auth GitHub page](https://github.com/xamarin/Xamarin.Auth), UWP is supported by the library.

The [sample](https://developer.xamarin.com/samples/xamarin-forms/WebServices/OAuthNativeFlow/) for this doc only includes iOS and Android, but it should be possible to add to UWP.

**Comment by nguyenthanhliemfc** [comment]
Great!
I hope the docs will update for UWP!
Thank!

**Comment by LooWooL** [comment]
Please provide a UWP example. You are Microsoft at the end, you can't just drop UWP support like this. Yes iOS and Android are important, but we went with Xamarin because it supports ALL including UWP.
