### ISSUE TITLE
WebVideo is not loading on Android pie in xamarin forms

### ISSUE THREAD

**Issue by rajamedialabs** [MicrosoftDocs/xamarin-docs#1529]
WebVideo is not loading on Android pie in xamarin forms. Kindly provide some solutions

**Comment by Mikilll94** [comment]
WebVideos or WebView?

**Comment by conceptdev** [comment]
Please use the **Report a problem** feature in Visual Studio ([Windows](https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2017) or [Mac](https://docs.microsoft.com/en-us/visualstudio/mac/report-a-problem)), or raise an issue on the [Xamarin.Forms open-source GitHub](https://github.com/xamarin/Xamarin.Forms/issues) and include enough information to reproduce the problem - a sample application if possible.
