### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by williansjmo** [MicrosoftDocs/xamarin-docs#153]
Excelente

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ef31dc71-3610-6c18-2bda-d0bb70804c92
* Version Independent ID: 02f7dc7b-541b-4b82-b33c-4e974fb94d8c
* Content: [WebView - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/webview?tabs=vswin)
* Content Source: [docs/xamarin-forms/user-interface/webview.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/webview.md)
* Service: **unspecified**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by conceptdev** [comment]
Thanks for the feedback!
