### ISSUE TITLE
WebView - no information about WebNavigationEvent and WebNavigationResult

### ISSUE THREAD

**Issue by Mikilll94** [MicrosoftDocs/xamarin-docs#1530]
In the article about WebView there is no information about WebNavigationEvent and WebNavigationResult. Especially WebNavigationResult should be described in details because it is not obvious how these navigation results are triggered, i.e. what exactly causes "Failure" navigation result.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ef31dc71-3610-6c18-2bda-d0bb70804c92
* Version Independent ID: 02f7dc7b-541b-4b82-b33c-4e974fb94d8c
* Content: [Xamarin.Forms WebView - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/webview?tabs=windows)
* Content Source: [docs/xamarin-forms/user-interface/webview.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/webview.md)
* Product: **xamarin**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @Mikilll94 

I've updated the doc with some information about the events, which is in a PR that will go out later.

With regards to what triggers navigation results, this is internal implementation detail of the native controls (e.g. `WkWebView` on iOS). For example, if a `WkWebView` fails to load a Url, the Xamarin.Forms `WebViewRenderer` on iOS sets a `Failure` result. The reason for the failure is internal implementation details of the `WkWebView`.
