### ISSUE TITLE
VS 2019

### ISSUE THREAD

**Issue by domagojmedo** [MicrosoftDocs/xamarin-docs#1531]
Is Live player going to be supported in VS 2019?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 07cbe485-3d3b-c8e0-410e-3d04e1beb269
* Version Independent ID: ec2a19ac-ce29-8644-70c1-4a3becb5cda4
* Content: [Xamarin Live Player for Xamarin.Forms - Xamarin](https://docs.microsoft.com/en-us/xamarin/tools/live-player/)
* Content Source: [docs/tools/live-player/index.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/tools/live-player/index.md)
* Product: **xamarin**
* GitHub Login: @lobrien
* Microsoft Alias: **laobri**

**Comment by conceptdev** [comment]
Live Player is a technology preview, and Visual Studio 2019 is not yet officially launched, so can't say for sure... but I don't think Live Player is available in any of the Visual Studio 2019 previews.

**Comment by joehanna** [comment]
VS Mac 2019 is out now - is the Live Player coming back?

**Comment by conceptdev** [comment]
No, the Live Player preview is only available in Visual Studio 2017.

**Comment by domagojmedo** [comment]
@conceptdev is XAML previewer supposed to be replacement for Live Player or?
