### ISSUE TITLE
MessagingService typo?

### ISSUE THREAD

**Issue by alataffective** [MicrosoftDocs/xamarin-docs#1532]
"The MessagingService is a static class with Subscribe and Send methods that are used throughout the solution."

Should it say MessagingCenter?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4d80a771-2198-328b-b9fa-fe25f16261cd
* Version Independent ID: be0408fe-d00b-baf6-8a9c-e24659029c4b
* Content: [Xamarin.Forms MessagingCenter - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/messaging-center)
* Content Source: [docs/xamarin-forms/app-fundamentals/messaging-center.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/app-fundamentals/messaging-center.md)
* Product: **xamarin**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by conceptdev** [comment]
Oh, probably 😬 thanks for the heads-up, fixing now.
