### ISSUE TITLE
'App' doesn't contain a definition for a 'FolderPath'

### ISSUE THREAD

**Issue by Knastordin** [MicrosoftDocs/xamarin-docs#1534]
Hi, i follow you tutorial and in 'OnSaveButtonClicked' method i've gotthe next error 'App' doesn't contain definition for a 'FolderPath', i've copied my to pastebin check it if you want https://pastebin.com/0P1VDQ2b. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 60587f77-05de-89b9-8a08-c7e7221d27af
* Version Independent ID: 4080b687-b353-f833-4bb7-a7a3f9993338
* Content: [Perform navigation in a multi-page Xamarin.Forms application - Xamarin](https://docs.microsoft.com/en-us/xamarin/get-started/quickstarts/multi-page?pivots=windows#feedback)
* Content Source: [docs/get-started/quickstarts/multi-page.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/get-started/quickstarts/multi-page.md)
* Product: **xamarin**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @Knastordin 

Step 13 adds the `App.FolderPath` property.

**Comment by Knastordin** [comment]
Hi @davidbrinch, oh, i got it, thank you!

**Comment by ChrisMyrick** [comment]
I was tripped up on this too until reading the comments section to see if anyone had resolved it.
