### ISSUE TITLE
Screenshots for some sections seem to be outdated

### ISSUE THREAD

**Issue by Gimly** [MicrosoftDocs/xamarin-docs#1536]
The screenshot for the section "Migrating from Info.plist to Asset Catalogs" for Visual Studio seem to be an older version and is outdated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dcbf82ce-c197-0e4d-4d6a-4cdc6db69088
* Version Independent ID: 68126a0d-7f14-35ec-2df4-42569c6fa283
* Content: [Application Icons in Xamarin.iOS - Xamarin](https://docs.microsoft.com/en-us/xamarin/ios/app-fundamentals/images-icons/app-icons?tabs=windows)
* Content Source: [docs/ios/app-fundamentals/images-icons/app-icons.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/ios/app-fundamentals/images-icons/app-icons.md)
* Product: **xamarin**
* GitHub Login: @lobrien
* Microsoft Alias: **laobri**

**Comment by amrutha786** [comment]
Same here, I dont see the option "Migrate to Asset Catalogs" in the info.plist iPhone Icons section

**Comment by conceptdev** [comment]
"Migrate" instructions are being updated today, thanks for the feedback.
