### ISSUE TITLE
Device info should include device specific data

### ISSUE THREAD

**Issue by eric99r** [MicrosoftDocs/xamarin-docs#1537]
This would replace my current device info package if it included info such as device specific id or imei

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a17064bc-6b39-3a27-fd12-8c37984905fb
* Version Independent ID: 9593bbe1-e42f-ff6e-cda4-f5d7b952bbf7
* Content: [DeviceInfo Class (Xamarin.Essentials)](https://docs.microsoft.com/en-us/dotnet/api/xamarin.essentials.deviceinfo?view=xamarin-essentials#feedback)
* Content Source: [docs/en/Xamarin.Essentials/DeviceInfo.xml](https://github.com/xamarin/Essentials/blob/live/docs/en/Xamarin.Essentials/DeviceInfo.xml)
* Product: **xamarin**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by eric99r** [comment]
disregard, just noticed the app info

**Comment by conceptdev** [comment]
If you have a feature request for Xamarin.Essentials, you can raise it directly with the team on their [GitHub repo](https://github.com/xamarin/essentials/issues). Thanks!
