### ISSUE TITLE
ProductTable is null in AwakeFromNib

### ISSUE THREAD

**Issue by mawarnes** [MicrosoftDocs/xamarin-docs#1539]
I had to move the datasource initialisation from AwakeFromNib to ViewDidLoad

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9f9e3e21-40e8-d379-d380-507b8f4febf0
* Version Independent ID: bc36f8c3-3dc1-9f8f-073e-dd5aa77ba3f7
* Content: [Table Views in Xamarin.Mac - Xamarin](https://docs.microsoft.com/en-us/xamarin/mac/user-interface/table-view#feedback)
* Content Source: [docs/mac/user-interface/table-view.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/mac/user-interface/table-view.md)
* Product: **xamarin**
* Technology: **xamarin-mac**
* GitHub Login: @lobrien
* Microsoft Alias: **laobri**

**Comment by lobrien** [comment]
What code were you using? I downloaded [MacTables](https://developer.xamarin.com/samples/mac/MacTables/) and it compiled and ran without modification.

**Comment by conceptdev** [comment]
If you continue to have problems with the sample code please open a new issue with the details.
