### ISSUE TITLE
UWP Geolocation - user not prompted for allowing location

### ISSUE THREAD

**Issue by StanleyBroo** [MicrosoftDocs/xamarin-docs#1541]
PermissionException LocationWhenInUse always comes up and no prompt for the user to allow location is shown when app starts?

Xamarin.Forms 3.6.0.264807
Essentials 1.1.0
UWP  OS 1809, x64 ..same on x86

try{ 
var request = new GeolocationRequest(GeolocationAccuracy.High, TimeSpan.FromSeconds(10));
var location = await Geolocation.GetLocationAsync(request);
}
catch (PermissionException pEx){
...pEx = LocationWhenInUse always comes up..no prompt to user for allowing location
when looking at the app settings in Windows 10 for the App ..position is greyed out.
}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f0acf3fa-b705-f0cc-b676-eeca60176dfa
* Version Independent ID: 1788a5d5-a3cb-15c8-927c-b6a24810245a
* Content: [Xamarin.Essentials: Geolocation - Xamarin](https://docs.microsoft.com/en-us/xamarin/essentials/geolocation?tabs=uwp#feedback)
* Content Source: [docs/essentials/geolocation.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/essentials/geolocation.md)
* Product: **xamarin**
* Technology: **xamarin-essentials**
* GitHub Login: @jamesmontemagno
* Microsoft Alias: **jamont**

**Comment by jamesmontemagno** [comment]
Please open an issue on http://github.com/xamarin/essentials

**Comment by captainchadl** [comment]
I am also experiencing this same issue. I have found that the prompt only displays when I use 'Geolocation.GetLastKnownLocationAsync()' before 'GeolocationRequest()'.
