### ISSUE TITLE
Great content

### ISSUE THREAD

**Issue by carlosrodriguezlumira** [MicrosoftDocs/xamarin-docs#1542]
Quick and very useful to an experienced iOS dev.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1b2ff35d-6d61-172e-92be-c50650642a8f
* Version Independent ID: d95a1e88-b823-2445-bed0-cd7bf3ee5bfa
* Content: [Hello, iOS – Quickstart - Xamarin](https://docs.microsoft.com/en-us/xamarin/ios/get-started/hello-ios/hello-ios-quickstart?pivots=macos#feedback)
* Content Source: [docs/ios/get-started/hello-ios/hello-ios-quickstart.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/ios/get-started/hello-ios/hello-ios-quickstart.md)
* Product: **xamarin**
* Technology: **xamarin-ios**
* GitHub Login: @lobrien
* Microsoft Alias: **laobri**

**Comment by conceptdev** [comment]
Thanks @carlosrodriguezlumira we appreciate your feedback!
