### ISSUE TITLE
Missing closing parenthesis in sample code

### ISSUE THREAD

**Issue by chrisgull** [MicrosoftDocs/xamarin-docs#1545]
This line
[assembly: ExportEffect(typeof(FocusEffect), nameof(FocusEffect)]
is missing a closing parenthesis before the closing bracket.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 98582b03-f63d-896e-5cfb-bac55bde97fb
* Version Independent ID: 81f9604e-deb9-434c-f580-47aa76087017
* Content: [Creating an Effect - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/effects/creating#feedback)
* Content Source: [docs/xamarin-forms/app-fundamentals/effects/creating.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/app-fundamentals/effects/creating.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @chrisgull 

Thanks for pointing this out. I've fixed the doc, in a PR that will go out later.
