### ISSUE TITLE
Android Device Manager : System Image Download Error

### ISSUE THREAD

**Issue by sowsan** [MicrosoftDocs/xamarin-docs#1547]
Hello Trying to add the android wearable square image on x86 and its always erroring out says stem image download error with all API types. It worked with armeabi. I have enabled Hyperv Acceleration and my default Android_Accelerated_X86_Orea running without issues.

![image](https://user-images.githubusercontent.com/11544153/55280886-14789e80-5302-11e9-92e6-d4e3806b2ab0.png)

![image](https://user-images.githubusercontent.com/11544153/55280895-370ab780-5302-11e9-9adb-5feaf4a12960.png)

![image](https://user-images.githubusercontent.com/11544153/55280899-4558d380-5302-11e9-8498-816affa60426.png)

**Comment by conceptdev** [comment]
Hi @sowsan this repo is for documentation problems rather than product issues. You can [report right in  Visual Studio](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) which will include system information that can help track down problems.
