### ISSUE TITLE
Cannot get conditional compile to work

### ISSUE THREAD

**Issue by JohnGaby** [MicrosoftDocs/xamarin-docs#1549]
I have code that is surrounded by a

#if WINDOWS_UWP
#endif

and when I run this under windows, the code within that block is not compiled or present. What am I doing wrong?

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d54ff3f6-796e-2f2b-4719-ac8c9a623455
* Version Independent ID: 9368f048-524d-fc8a-493f-47f60b34e20e
* Content: [Part 4 - Dealing with Multiple Platforms - Xamarin](https://docs.microsoft.com/en-us/xamarin/cross-platform/app-fundamentals/building-cross-platform-applications/platform-divergence-abstraction-divergent-implementation#feedback)
* Content Source: [docs/cross-platform/app-fundamentals/building-cross-platform-applications/platform-divergence-abstraction-divergent-implementation.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/cross-platform/app-fundamentals/building-cross-platform-applications/platform-divergence-abstraction-divergent-implementation.md)
* Product: **xamarin**
* Technology: **xamarin-crossplatform**
* GitHub Login: @asb3993
* Microsoft Alias: **amburns**

**Comment by conceptdev** [comment]
The conditional compile symbols only work where the same C# file is included and compiled in different projects - which happens with Linked Files and Shared Asset Projects. _It won't work in a PCL or .NET Standard library._

If you are definitely using a Shared Asset Project, ensure that it is referenced by your UWP project. Then check in your UWP project's settings **Properties > Build > General > Conditional compilation symbols** to ensure `WINDOWS_UWP` appears (see screenshot below):

<img width="1280" alt="publicissue-1549" src="https://user-images.githubusercontent.com/199373/55359329-719d5d00-5486-11e9-8f4f-54da2751a596.png">
