### ISSUE TITLE
How to delete or change to another account

### ISSUE THREAD

**Issue by anhvv** [MicrosoftDocs/xamarin-docs#155]
How to delete or change to another account? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5ccadd93-fcc8-6a15-9670-d5af7ee7f6f8
* Version Independent ID: 188007d3-cf20-97ba-137f-64ff25a88e7c
* Content: [Automatic Provisioning - Xamarin](https://docs.microsoft.com/en-us/xamarin/ios/get-started/installation/device-provisioning/automatic-provisioning)
* Content Source: [docs/ios/get-started/installation/device-provisioning/automatic-provisioning.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/ios/get-started/installation/device-provisioning/automatic-provisioning.md)
* Service: **unspecified**
* GitHub Login: @asb3993
* Microsoft Alias: **amburns**

**Comment by bradumbaugh** [comment]
Hi @anhvv, check out the [Apple Account Management](https://docs.microsoft.com/xamarin/cross-platform/macios/apple-account-management) guide listed at the top of this document - it describes how to work with Apple IDs. Hope this is helpful!
