### ISSUE TITLE
No link for: How do I enable Intellisense in Android .axml files

### ISSUE THREAD

**Issue by PapierenTijger** [MicrosoftDocs/xamarin-docs#1552]
There is no link to the mentioned guide in the answer.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d166afd8-560c-978f-7cdc-24f88c4dd6dd
* Version Independent ID: 6be87a41-a472-d381-21be-10b3e5dc881c
* Content: [Xamarin.Android Frequently Asked Questions - Xamarin](https://docs.microsoft.com/en-us/xamarin/android/troubleshooting/questions/#feedback)
* Content Source: [docs/android/troubleshooting/questions/index.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/android/troubleshooting/questions/index.md)
* Product: **xamarin**
* Technology: **xamarin-android**
* GitHub Login: @conceptdev
* Microsoft Alias: **crdun**

**Comment by conceptdev** [comment]
Hi @PapierenTijger sorry about that. The content has been removed: in the past it was possible to 'enable' IntelliSense for Android XML files.

In the latest versions of Visual Studio and Visual Studio for Mac, there should always be IntelliSense displayed. There is no option to 'enable' it.

If you are having trouble with the Android XML editor, please [report an issue in Visual Studio](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio).

To prevent confusion in future, this page is being updated to remove the bad link.
