### ISSUE TITLE
VisualStateManager do not work properly in UWP

### ISSUE THREAD

**Issue by JohnGaby** [MicrosoftDocs/xamarin-docs#1554]
I have tried to use VisualStateManger described above to change the appearance of the button when pressed and not pressed. While this does seem to work properly for Android, when running under UWP, when I click on the button it changes to the 'Pressed' state, but when I release it, it does NOT change back to the 'Normal' state until I click somewhere else on the page. Am I doing something wrong here or is this a bug?

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f70c4017-a981-2cd6-24b2-7da7674efa5a
* Version Independent ID: 2b4a8128-38d8-352f-c310-d033b56a3081
* Content: [Xamarin.Forms ImageButton - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/imagebutton#imagebutton-visual-states)
* Content Source: [docs/xamarin-forms/user-interface/imagebutton.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/imagebutton.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by conceptdev** [comment]
Hi @JohnGaby if it works on Android and iOS, but not UWP, then it could be a bug.

You can raise bugs directly on the [Xamarin.Forms open source repo](https://github.com/xamarin/Xamarin.Forms/issues).
