### ISSUE TITLE
AndroidManifest is not getting <activity> section

### ISSUE THREAD

**Issue by dinobu** [MicrosoftDocs/xamarin-docs#1556]
Based on this page [(https://docs.microsoft.com/en-us/xamarin/android/platform/android-manifest),](https://docs.microsoft.com/en-us/xamarin/android/platform/android-manifest) it states that if activity has attribute [Name="..."], then AndroidManifest will be updated and will contain <activity></activity> section.

I dont see this happening.  I am using Xamarin.Forms, .NETStandard 2.0, on Visual Studio for Mac.
My AndroidManifest does not have <activity> section but my MainActivity is adorned with attributes for Name, Label, Icon, Theme, ConfigurationChanges like:

```
    [Activity(Name = "packagename.mainactivity",
        Label = "MyApp",
        Icon = "@drawable/icon",
        Theme = "@style/MainTheme",
        ConfigurationChanges = ConfigChanges.ScreenSize | ConfigChanges.SmallestScreenSize | ConfigChanges.ScreenLayout | ConfigChanges.Orientation)]
    public class MainActivity : Xamarin.Forms.Platform.Android.FormsAppCompatActivity
    {
```

I tried adding manually the entry in AndroidManifest like:

`<activity android:name="packagename.mainactivity"/>`

or, 
`
<activity android:name=".mainactivity"/>`

but I dont think that is working.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 50a4c45c-34a0-9fa7-5916-f9c3a85c5558
* Version Independent ID: c03c4a7a-fdec-ffd0-cacc-17cf329454f8
* Content: [Working with the Android Manifest - Xamarin](https://docs.microsoft.com/en-us/xamarin/android/platform/android-manifest#The_Basics)
* Content Source: [docs/android/platform/android-manifest.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/android/platform/android-manifest.md)
* Product: **xamarin**
* Technology: **xamarin-android**
* GitHub Login: @conceptdev
* Microsoft Alias: **crdun**

**Comment by conceptdev** [comment]
@dinobu the AndroidManifest.xml file in your project will not get updated. The attributes you apply in C# code will be added to the AndroidManifest.xml that is shipped with your app. This is explained in the second paragraph:

>AndroidManifest.xml is generated as part of the build process, and the XML found within Properties/AndroidManifest.xml is **merged with XML that is generated from custom attributes. The resulting merged AndroidManifest.xml resides in the obj subdirectory**; for example, it resides at obj/Debug/android/AndroidManifest.xml for Debug builds. The merging process is trivial: it uses custom attributes within the code to generate XML elements, and inserts those elements into AndroidManifest.xml.

**Comment by dinobu** [comment]
Thank you.  How do I then add <activity> section manually to AndroidManifest?  I tried it by adding "packagename.mainactivity" or ".mainactivity" or ".MainActivity" but none seam to work.

**Comment by conceptdev** [comment]
As the document says, the file in your project is _merged_ with the attributes defined in C# attributes. For general use, especially a Xamarin.Forms app, you shouldn't need to add sections manually to the XML file. Look at the output file in the **/obj/** folder to debug.

**Comment by dinobu** [comment]
figured it out, thanks for your help
