### ISSUE TITLE
Not complete documentation as usuall

### ISSUE THREAD

**Issue by graftedin** [MicrosoftDocs/xamarin-docs#156]
There is a axml designer in visual studio......these changes don't effect the layout in there.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 87b678e7-5336-db4f-02ac-db6d2115ebec
* Version Independent ID: 5434c705-8fa7-f2ed-e358-6c05d915cde0
* Content: [Material Theme - Xamarin](https://docs.microsoft.com/en-us/xamarin/android/user-interface/material-theme)
* Content Source: [docs/android/user-interface/material-theme.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/android/user-interface/material-theme.md)
* Service: **unspecified**
* GitHub Login: @mgmclemore
* Microsoft Alias: **mamcle**

**Comment by topgenorth** [comment]
@graftedin - could you please provide a bit more detail about what the issue is. Are you having a problem using the Xamarin.Android Designer, or are you having a problem adding a theme to an Android application?

**Comment by graftedin** [comment]
Well.  This support ticket doesn't show me the page I was commenting on so I can't be specific.

What I find all the time in documentation is it'll say do x in y and assume that I know what y is (or where to find it, or how to create it, or ....).  Maybe if I have many years of app building experience I'll know what you are saying but.....this is my first app and I'm trying to figure this stuff out on the fly.  I have no clue what y is.

**Comment by graftedin** [comment]
Possibly I was commenting on...
https://docs.microsoft.com/en-us/xamarin/android/user-interface/material-theme

It seems that if you use these steps to customize a theme it will change it when you build and test the app but not when viewing it in the "Designer".

![designer_screen_shot](https://user-images.githubusercontent.com/696233/39010879-6a2170fe-43ff-11e8-858a-112c40dc59bc.png)

**Comment by topgenorth** [comment]
This sounds like an issue with the Xamarin.Android Designer itself. We're unable to provide support for the Designer here, as this is for reporting documentation related issues. For support with the Xamarin.Android Designer, please visit the [Visual Studio Developer Community](https://developercommunity.visualstudio.com/spaces/8/index.html).
