### ISSUE TITLE
Direct download link for OpenJDK

### ISSUE THREAD

**Issue by CeciAc** [MicrosoftDocs/xamarin-docs#1568]
@balivo commented on [Thu Apr 04 2019](https://github.com/MicrosoftDocs/xamarin-docs.pt-br/issues/22)

Direct download link from Microsoft OpenJDK been removed?

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: 97e1cd96-e7a2-ec22-8d79-ac949e890ccb
* Version Independent ID: 922a3fdf-7bab-7d9d-5518-904db9e75ee3
* Content: [Distribuição do Mobile OpenJDK da Microsoft - Xamarin](https://docs.microsoft.com/pt-br/xamarin/android/get-started/installation/openjdk#feedback)
* Content Source: [docs/android/get-started/installation/openjdk.md](https://github.com/MicrosoftDocs/xamarin-docs.pt-BR/blob/live/docs/android/get-started/installation/openjdk.md)
* Product: **xamarin**
* Technology: **xamarin-android**
* GitHub Login: @vyedin
* Microsoft Alias: **vyedin**

**Comment by CeciAc** [comment]
Hi team, 
I'm moving this because the user is making a suggestion on the original documentatino
best

**Comment by balivo** [comment]
Great!

Tks

**Comment by conceptdev** [comment]
The Visual Studio installer/updater should [automatically download](https://docs.microsoft.com/xamarin/android/get-started/installation/openjdk#download) for you.

I'll check with the team whether we need to provide a link here for other purposes.

**Comment by balivo** [comment]
Yes, I know @conceptdev but at installer we can't change OpenJDK (specific) folder...

Sometimes "Long Path" is an issue in Android tools, for exemple, and we need put "Java Tools" on paths like "c:\java" to make it happens...

A cool thing to think is make OpenJDK installation folder available to customize at next VS Installer...

Tks!

**Comment by conceptdev** [comment]
Ok, I understand! Thanks for the feedback, will pass it on to the team.
