### ISSUE TITLE
About LocalBroadcastManager

### ISSUE THREAD

**Issue by kwacks** [MicrosoftDocs/xamarin-docs#157]
It should also be noted that if you're sending just local broadcasts using LocalBroadcastManager, then you should also register for those notifications using LocalBroadcastManager instance vs the system wide RegisterBrodcast (and unregisterBroadcast)
i.e. 
Android.Support.V4.Content.LocalBroadcastManager.GetInstance(this). RegisterReceiver(receiver, new IntentFilter("com.xamarin.example.TEST"));
 for example.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bf408f58-3116-0a60-d5f7-dbf4d0c02c9d
* Version Independent ID: aa2b5ea1-6a0c-77a4-6665-49c0505a18e4
* Content: [Broadcast Receivers in Xamarin.Android - Xamarin](https://docs.microsoft.com/en-us/xamarin/android/app-fundamentals/broadcast-receivers)
* Content Source: [docs/android/app-fundamentals/broadcast-receivers.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/android/app-fundamentals/broadcast-receivers.md)
* Service: **unspecified**
* GitHub Login: @topgenorth
* Microsoft Alias: **toopge**

**Comment by topgenorth** [comment]
Thanks for bringing this to our attention. We'll revisit this guide and update to be clear about this.
