### ISSUE TITLE
Complex Objects With DateTimeOffset

### ISSUE THREAD

**Issue by jmichas** [MicrosoftDocs/xamarin-docs#1570]
I have a complex object I am trying to use for design time data that include field for DateTimeOffset. Simply setting the property like TransactionDateUtc="1/20/2019" yields an empty date in the binding. I've been trying to set it using more verbose xaml like:

&lt;models:AccountTransaction.TransactionDateUtc&gt;
	&lt;x:DateTimeOffset&gt;01/12/2019 00:00:00&lt;/x:DateTimeOffset&gt;
&lt;/models:AccountTransaction.TransactionDateUtc&gt;

But that doesn't work either. 
Is there a way to do this in XAML?

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b137e71e-e8c5-67c4-944f-a427edd8a5be
* Version Independent ID: d1350601-a386-8107-182e-cc2485e31ae6
* Content: [Use Design Time Data with the XAML Previewer - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/xaml/xaml-previewer/design-time-data#feedback)
* Content Source: [docs/xamarin-forms/xaml/xaml-previewer/design-time-data.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/xaml/xaml-previewer/design-time-data.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @maddyleger1
* Microsoft Alias: **maleger**

**Comment by maddyleger1** [comment]
Hi there!
Check the following:
Are you on Visual Studio 2019 (Windows and Mac) and using Xamarin.Forms 3.6 or higher?
Did you pull in the 3 namespaces in the header, and are you prefixing the Property with d: (like d:TransactionDateUtc)?
If this is a custom control (that you've created yourself, or that you've pulled in from Nuget) it might not be enabled for design time rendering - check out this page for more info on that: https://docs.microsoft.com/en-us/xamarin/xamarin-forms/xaml/xaml-previewer/render-custom-controls#enable-design-time-rendering-for-custom-controls

If none of that works, this may be an issue with the XAML Previewer itself, so you can file an issue through Help > Report a Problem in Visual Studio 2019. Thanks!

**Comment by jmichas** [comment]
Hi,
Yes, I am using VS 2019 on Windows and the latest 3.6+ XF and included all the d: namespaces.

I finally found the answer to my problem after a lot of searching.
I wish I had the link still, but basically I found some language that stated that the DateTimeOffset type is not supported to be set from XAML. I tested adding a DateTime field to my object and was able to set it with a simple string property. It's not the end of the world, you can still see 01/01/0001 00:00:00 in the previewer for the DateTimeOffset fields but it would be nice to have actual values in there especially if there is conditional display logic in the XAML view.

Hopefully this helps some other people out there.
