### ISSUE TITLE
Archive Android on VS2019

### ISSUE THREAD

**Issue by michaelmairegger** [MicrosoftDocs/xamarin-docs#1572]
The menu item to "Archive" a android project is not visible anymore on VS2019. Within VS2017 there was no issue.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f43472af-a9d3-8bef-0f24-b81f8f6cd2dd
* Version Independent ID: 42cfbea5-0b4c-a0a3-4cce-1edf5523f605
* Content: [Preparing an Application for Release - Xamarin](https://docs.microsoft.com/en-us/xamarin/android/deploy-test/release-prep/index?tabs=windows#feedback)
* Content Source: [docs/android/deploy-test/release-prep/index.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/android/deploy-test/release-prep/index.md)
* Product: **xamarin**
* Technology: **xamarin-android**
* GitHub Login: @conceptdev
* Microsoft Alias: **crdun**

**Comment by conceptdev** [comment]
I have just confirmed the **Archive** menu item appears in Visual Studio 2019, see screenshots below:

<img width="420" alt="android-archive" src="https://user-images.githubusercontent.com/199373/55645186-be39ae80-578c-11e9-88bc-78d4613c4817.png">

<img width="654" alt="android-archive-2" src="https://user-images.githubusercontent.com/199373/55645190-c09c0880-578c-11e9-857a-fec2239662ea.png">

Check your install includes the Xamarin Tools (Mobile Development with .NET), and if you continue to have issues use the [report a problem feature](https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2019) in Visual Studio 2019.

**Comment by michaelmairegger** [comment]
@conceptdev Thanks for confirming that.
I have created a blank Xamarin Forms solution. Then I have compared both Android .csproj files and then I found that my file had a  `<ProductVersion>8.0.30703</ProductVersion>`  line inside. After removing this line the `Archive` button appears.

**Comment by conceptdev** [comment]
Glad you got it working - can I ask: was the "problem" project one created with Visual Studio on Windows or Mac, or was it one of our downloaded samples?

**Comment by michaelmairegger** [comment]
No, the project was created with VS2017 by using the Prism Template Pack.
I have tried to reproduce the issue with a new project created by the template pack but even though the ProductVersion line is present the archive button works.
But now everyting works.

**Comment by conceptdev** [comment]
Thanks for confirming.
