### ISSUE TITLE
sqlite-net-pcl and Embedded Resource

### ISSUE THREAD

**Issue by jhessin** [MicrosoftDocs/xamarin-docs#1574]
This isn't an issue so much as a question. I have an existing Database that I would like to embed in my application as a resource. How do I use sqlite-net-pcl to access this file?

I was going to try the above example, but I run into problems when looking for typeof(LoadResourceText) as "LoadResourceText" is not recognized. Even if it worked this gets me a stream where the SQLite Connection requires a path string to the database.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8fb68890-cda3-6b2a-deba-55a171963da5
* Version Independent ID: 675d1663-d7ea-3e47-dbdd-772944acce5a
* Content: [File Handling in Xamarin.Forms - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/files?tabs=macos#feedback)
* Content Source: [docs/xamarin-forms/app-fundamentals/files.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/app-fundamentals/files.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @jhessin 

Take a look at this blog post: https://robgibbens.com/deploying-a-database-file-with-a-xamarin-forms-app/

**Comment by jhessin** [comment]
Awesome thanks!
