### ISSUE TITLE
Is it possible to restrict Entry text Length using Bindable Property only

### ISSUE THREAD

**Issue by arvindrajachourasiya** [MicrosoftDocs/xamarin-docs#1575]
I have a doubt, Is it possible to restrict `Entry` text length  to 10 characters using Bindable properties only, not custom renderer along with `BindableProperties`.

Please add one example in your docs so that I can understand it. 
Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b054a909-6f7f-0b32-5059-eb5c8a9b366b
* Version Independent ID: 723af07b-8f4e-ebe3-a520-99cdcf5efc5a
* Content: [Bindable Properties - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/xaml/bindable-properties#feedback)
* Content Source: [docs/xamarin-forms/xaml/bindable-properties.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/xaml/bindable-properties.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @arvindrajachourasiya 

There's an easier way: set the `Entry.MaxLength` property to 10 - https://docs.microsoft.com/xamarin/xamarin-forms/user-interface/text/entry#limiting-input-length
