### ISSUE TITLE
Confusing

### ISSUE THREAD

**Issue by nick5454** [MicrosoftDocs/xamarin-docs#1577]
Why are you using (execute:) format? No one uses this format unless you're reading a book. You should be using the widely used format "public ICommand MyCommand { get { return new Command&lt;Type&gt;(async (type) =&gt; {}"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 13b6227e-5c43-097e-20f7-efe87b04b852
* Version Independent ID: a8e09565-d055-07ad-ba11-1e78f1564d64
* Content: [The Xamarin.Forms Command Interface - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/data-binding/commanding)
* Content Source: [docs/xamarin-forms/app-fundamentals/data-binding/commanding.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/app-fundamentals/data-binding/commanding.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by conceptdev** [comment]
Thanks for your feedback. Named parameters are used to increase the clarity of the code:

```
        SubmitCommand = new Command(
            execute: () =>
            {
                Persons.Add(PersonEdit);
                PersonEdit.PropertyChanged -= OnPersonEditPropertyChanged;
                PersonEdit = null;
                IsEditing = false;
                RefreshCanExecutes();
            },
            canExecute: () =>
            {
                return PersonEdit != null &&
                       PersonEdit.Name != null &&
                       PersonEdit.Name.Length > 1 &&
                       PersonEdit.Age > 0;
            });
```

is more readable than without, when using the `Command` constructor that has two parameters:

```
        SubmitCommand = new Command(
            () =>
            {
                Persons.Add(PersonEdit);
                PersonEdit.PropertyChanged -= OnPersonEditPropertyChanged;
                PersonEdit = null;
                IsEditing = false;
                RefreshCanExecutes();
            },
            () =>
            {
                return PersonEdit != null &&
                       PersonEdit.Name != null &&
                       PersonEdit.Name.Length > 1 &&
                       PersonEdit.Age > 0;
            });
```

**Comment by WillAutioItrax** [comment]
Lots of examples and explanations of what is happening and why. Just what I needed.

**Comment by FrankSzendzielarz** [comment]
Yeah I can't read this article. It's just unreadable.
