### ISSUE TITLE
Define static resource for ColumnDefinition Width attribute

### ISSUE THREAD

**Issue by nakulashok** [MicrosoftDocs/xamarin-docs#1578]
How can i define static resource for the below code?
`
<Grid.ColumnDefinitions>
                         <ColumnDefinition Width="0.4*"></ColumnDefinition>                       
                         <ColumnDefinition Width="0.6*"></ColumnDefinition>
</Grid.ColumnDefinitions>
`
Is there any way to define static resource for the **Width** attribute of **ColumnDefinition** element.

**Comment by davidbritch** [comment]
Hi @nakulashok 

Use the `x:Static` XAML markup extension - https://docs.microsoft.com/xamarin/xamarin-forms/xaml/markup-extensions/consuming#xstatic-markup-extension
