### ISSUE TITLE
Xamarin.Forms.Themes.Light

### ISSUE THREAD

**Issue by Unlonlyness** [MicrosoftDocs/xamarin-docs#1579]
The third nuget package should be   "Xamarin.Forms.Theme.Light" 
not "Xamarin.Forms.Themes.Light"

There is a redundant "s" in the package name. 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 28053f34-1703-6038-00be-75eb4af8c883
* Version Independent ID: 42bd80fe-81f0-ee2c-01bd-5ba82fef705e
* Content: [Getting Started with DataPages - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/datapages/get-started#feedback)
* Content Source: [docs/xamarin-forms/user-interface/datapages/get-started.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/datapages/get-started.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @Unlonlyness 

Thanks for pointing this out. I've fixed it in a PR that will go out later this week.
