### ISSUE TITLE
When you are planing for release of  Xamarin.WPFin production?

### ISSUE THREAD

**Issue by tejasklodha** [MicrosoftDocs/xamarin-docs#1580]
Dear Sir,

I am be curios about Xamarin.WPF development and already plans many projects on it.
Can you give the tentative month of release of Xamarin.WPF ?
It's really great for us.

Thanks and Regards,
Tejas Lodha

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c9da89cd-1206-0d63-4231-b86a427cda0b
* Version Independent ID: 22b11d5f-71fc-82ff-7b75-2f84cc2bf3aa
* Content: [WPF Platform Setup - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/platform/other/wpf)
* Content Source: [docs/xamarin-forms/platform/other/wpf.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/platform/other/wpf.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @tejasklodha 

WPF support in Xamarin.Forms is a community project, rather than a Microsoft project. For more information on status, see https://github.com/mohachouch/forms-wpf-progress/blob/master/Status.md

**Comment by amirvenus** [comment]
I’m losing my hopes day by day as I am sensing that XF is really focused on iOS and Android rather than WPF and macOS.

Evidently, they have even removed UWP in new Visuals Studio XF template.

I wish Microsoft, one of the richest companies alive, could spend some budget and resources to get things done.. sigh... 😔
