### ISSUE TITLE
What is developed?

### ISSUE THREAD

**Issue by ysanjay** [MicrosoftDocs/xamarin-docs#1581]
What is devleoped?

Section
Cross platform development.

"including case studies of reference applications we have devleoped, along with best"

I think it should be
Developed.

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ccf3321d-3945-a973-66e7-fb38ea30e4fd
* Version Independent ID: dfc849ff-6de9-101e-5af5-64a5d00196c6
* Content: [Xamarin for Objective-C Developers - Xamarin](https://docs.microsoft.com/en-us/xamarin/ios/get-started/objective-c-developers/#feedback)
* Content Source: [docs/ios/get-started/objective-c-developers/index.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/ios/get-started/objective-c-developers/index.md)
* Product: **xamarin**
* Technology: **xamarin-ios**
* GitHub Login: @lobrien
* Microsoft Alias: **laobri**

**Comment by conceptdev** [comment]
Fixed in linked PR.
