### ISSUE TITLE
Missing Constant Parameter Value

### ISSUE THREAD

**Issue by LuckyDuck97** [MicrosoftDocs/xamarin-docs#1582]
In the 2nd Boxview, contained within the RelativeLayout which is contained within the 1st RelativeLayout the Constant parameter (for the XConstraint) is missing a value.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 35a0e591-622a-aa3f-a289-7896af574a81
* Version Independent ID: 8e796318-0fa6-d67f-1de3-f3b0a5feb49c
* Content: [Xamarin.Forms RelativeLayout - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/layouts/relative-layout#feedback)
* Content Source: [docs/xamarin-forms/user-interface/layouts/relative-layout.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/layouts/relative-layout.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @LuckyDuck97 

Thanks for pointing this out. I've fixed it in a PR that will go out later.
