### ISSUE TITLE
FSEvent Watcher for Mac sample is for C#, not F#.

### ISSUE THREAD

**Issue by danien** [MicrosoftDocs/xamarin-docs#1584]
Clicking on the FSEvent Watcher leads to this URL (https://developer.xamarin.com/samples/mac/FSEvents/), which has a button to Browse the source code, which leads to the github page for the C# version of the project (https://github.com/xamarin/mac-samples/tree/master/FSEvents), not the F# version.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4e8c1ab1-a9b2-02e2-744e-4edd9abd623e
* Version Independent ID: 5f586177-1f2a-eade-6878-c135aaff6583
* Content: [F# Samples for Xamarin - Xamarin](https://docs.microsoft.com/en-us/xamarin/cross-platform/platform/fsharp/samples#feedback)
* Content Source: [docs/cross-platform/platform/fsharp/samples.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/cross-platform/platform/fsharp/samples.md)
* Product: **xamarin**
* Technology: **xamarin-crossplatform**
* GitHub Login: @asb3993
* Microsoft Alias: **amburns**

**Comment by conceptdev** [comment]
You're right! Just fixing the page now, will be published soon. Thanks.
