### ISSUE TITLE
spelling

### ISSUE THREAD

**Issue by smchughinfo** [MicrosoftDocs/xamarin-docs#1586]
Open the plist editor and add the Privacy - Location When In Use Usage Description property and fill in a value to display the user.

should be

Open the plist editor and add the Privacy - Location When In Use Usage Description property and fill in a value to display to the user.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f0acf3fa-b705-f0cc-b676-eeca60176dfa
* Version Independent ID: 1788a5d5-a3cb-15c8-927c-b6a24810245a
* Content: [Xamarin.Essentials: Geolocation - Xamarin](https://docs.microsoft.com/en-us/xamarin/essentials/geolocation?tabs=ios)
* Content Source: [docs/essentials/geolocation.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/essentials/geolocation.md)
* Product: **xamarin**
* Technology: **xamarin-essentials**
* GitHub Login: @jamesmontemagno
* Microsoft Alias: **jamont**

**Comment by jamesmontemagno** [comment]
https://github.com/MicrosoftDocs/xamarin-docs/pull/1623
