### ISSUE TITLE
更新vs for mac出现很严重的bug

### ISSUE THREAD

**Issue by adomit** [MicrosoftDocs/xamarin-docs#1587]
通过unity安装vs 2019 for mac,首次启动vs 2019,并从菜单中选择检测更新,提示需要更新,然后就会报错,然后vs 2019 就再也无法启动了.在mac和win下都测试了,都存在同样的问题.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 97e1cd96-e7a2-ec22-8d79-ac949e890ccb
* Version Independent ID: 922a3fdf-7bab-7d9d-5518-904db9e75ee3
* Content: [Microsoft's Mobile OpenJDK Distribution - Xamarin](https://docs.microsoft.com/en-us/xamarin/android/get-started/installation/openjdk#feedback)
* Content Source: [docs/android/get-started/installation/openjdk.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/android/get-started/installation/openjdk.md)
* Product: **xamarin**
* Technology: **xamarin-android**
* GitHub Login: @vyedin
* Microsoft Alias: **vyedin**

**Comment by conceptdev** [comment]
[如何在 Visual Studio for Mac 中回報問題](https://docs.microsoft.com/visualstudio/mac/report-a-problem).
