### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by mlamothe** [MicrosoftDocs/xamarin-docs#1588]
This sentence has a typo that makes it confusing: "Because both languages use garbage collection, there is way to explicitly release unused objects" ("there is way"? should it be "there is NO way"?)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cbb2ed12-d9b5-ea5c-9575-bf57bf19fc4e
* Version Independent ID: 0fdfc765-e358-a9bb-3289-680170e9570b
* Content: [Xamarin for Java Developers - Xamarin](https://docs.microsoft.com/en-us/xamarin/android/get-started/java-developers#feedback)
* Content Source: [docs/android/get-started/java-developers.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/android/get-started/java-developers.md)
* Product: **xamarin**
* Technology: **xamarin-android**
* GitHub Login: @conceptdev
* Microsoft Alias: **crdun**

**Comment by conceptdev** [comment]
Thanks for the feedback @mlamothe - you are probably right; I'll check in with the engineering team and then update as appropriate.
