### ISSUE TITLE
Hide Menu Button

### ISSUE THREAD

**Issue by WilliamDumontRT** [MicrosoftDocs/xamarin-docs#1589]
Is there any way to hide the hamburger button in the navigation bar of a master detail page?

**Comment by davidbritch** [comment]
Hi @WilliamDumontRT 

It can only be done by resorting to custom renderers. A quick search reveals some solutions out there for it.

However, you should consider whether its advisable to do so. A swipe will most likely still reveal the menu that the hamburger icon would reveal.
