### ISSUE TITLE
Thanks

### ISSUE THREAD

**Issue by khenzar** [MicrosoftDocs/xamarin-docs#159]
This has been helpful, thanks. I was struggling with restoring NuGet packages after moving a solution to another VSTS Git repo. Removing the error references for .NETStandard2.0 (which was added previously by mistake) from the .csproj file was to only way to restore the references for other NuGet packages.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d2985157-745d-483d-7255-bcebcfa53ca9
* Version Independent ID: ebf3d8e1-502b-9579-1552-895788386483
* Content: [Missing packages error after updating Nuget packages - Xamarin](https://docs.microsoft.com/en-us/xamarin/cross-platform/troubleshooting/questions/nuget-packages-missing)
* Content Source: [docs/cross-platform/troubleshooting/questions/nuget-packages-missing.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/cross-platform/troubleshooting/questions/nuget-packages-missing.md)
* Service: **unspecified**
* GitHub Login: @asb3993
* Microsoft Alias: **amburns**

**Comment by bradumbaugh** [comment]
Glad this was helpful, @khenzar - thanks for letting us know!
