### ISSUE TITLE
Set WidthRequest and HeightRequest in HTML Strings sample code

### ISSUE THREAD

**Issue by fritzlim** [MicrosoftDocs/xamarin-docs#1590]
Both 'WidthRequest' and 'HeightRequest' need to be set in the sample code at https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/webview?tabs=windows#html-strings, otherwise the HTML doesn't appear.

I.e. these lines are needed:
`browser.WidthRequest = 1000;`
`browser.HeightRequest = 1000;` 

The values could be something other than 1000.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ef31dc71-3610-6c18-2bda-d0bb70804c92
* Version Independent ID: 02f7dc7b-541b-4b82-b33c-4e974fb94d8c
* Content: [Xamarin.Forms WebView - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/webview?tabs=windows)
* Content Source: [docs/xamarin-forms/user-interface/webview.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/webview.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @fritzlim 

In the sample application the doc links to, `WidthRequest` and `HeightRequest` aren't set and the HTML still appears:

```
    public class LocalHtml : ContentPage
    {
        public LocalHtml()
        {
            var browser = new WebView();
            var htmlSource = new HtmlWebViewSource();
            htmlSource.Html = @"<html><body>
                                <h1>Xamarin.Forms</h1>
                                <p>Welcome to WebView.</p>
                                </body>
                                </html>";
            browser.Source = htmlSource;
            Content = browser;
        }
    }
```

However, it could be required to set `WidthRequest` and `HeightRequest` depending upon the layout the `WebView` is a child of. I've added a note to the doc to that effect, in a PR that will go live later.
