### ISSUE TITLE
Errors in the "referencing resources programmatically" section?

### ISSUE THREAD

**Issue by mlamothe** [MicrosoftDocs/xamarin-docs#1591]
After this text: "When referencing resources programmatically (in code), they can be accessed via the Resources class hierarchy which uses the following syntax:", there's a code block with type "XML" - should it be marked C# instead? 

The contents of that block are:

  "@[&lt;PackageName&gt;.]Resource.&lt;ResourceType&gt;.&lt;ResourceName&gt;"

I don't believe the @ belongs here. Perhaps it was copied from the XML block below it?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4db71a47-f7c4-e619-af5d-f173d97df1bd
* Version Independent ID: 1f6af9fe-e53f-de92-041a-4340b1ae45a4
* Content: [Android Resource Basics - Xamarin](https://docs.microsoft.com/en-us/xamarin/android/app-fundamentals/resources-in-android/android-resource-basics?tabs=windows)
* Content Source: [docs/android/app-fundamentals/resources-in-android/android-resource-basics.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/android/app-fundamentals/resources-in-android/android-resource-basics.md)
* Product: **xamarin**
* Technology: **xamarin-android**
* GitHub Login: @conceptdev
* Microsoft Alias: **crdun**

**Comment by conceptdev** [comment]
Thanks @mlamothe I think you're right! Updating the page now 😊
