### ISSUE TITLE
Code example for PreferenceFragment

### ISSUE THREAD

**Issue by PingPongSet** [MicrosoftDocs/xamarin-docs#1595]
I cannot find the code example for PreferenceFragment.
I searched the code base, but cannot find it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: efc8dc11-2c71-4103-a860-a7864b8244b5
* Version Independent ID: 5f1d659a-b57a-d7fe-c640-33f958f28cb3
* Content: [Specialized Fragment Classes - Xamarin](https://docs.microsoft.com/en-us/xamarin/android/platform/fragments/specialized-fragment-classes#preferencefragment)
* Content Source: [docs/android/platform/fragments/specialized-fragment-classes.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/android/platform/fragments/specialized-fragment-classes.md)
* Product: **xamarin**
* Technology: **xamarin-android**
* GitHub Login: @conceptdev
* Microsoft Alias: **crdun**

**Comment by conceptdev** [comment]
This [sample code](https://github.com/xamarin/monodroid-samples/blob/master/ApiDemo/Preferences/PreferenceWithHeaders.cs) includes a reference to PreferenceFragment.
