### ISSUE TITLE
Can't install or update SDK

### ISSUE THREAD

**Issue by Wenfengcheng** [MicrosoftDocs/xamarin-docs#1597]
I'm using VS For Mac Enterprise 8.0.2, I try to use SDK Manager to install android sdks and update android emulator, but always shows offline mode. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dac28e18-875a-cb51-a031-717692255d0a
* Version Independent ID: f2e625c7-18a7-c090-fa92-9d635ac39164
* Content: [Setting up the Android SDK for Xamarin.Android - Xamarin](https://docs.microsoft.com/en-us/xamarin/android/get-started/installation/android-sdk?tabs=macos#feedback)
* Content Source: [docs/android/get-started/installation/android-sdk.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/android/get-started/installation/android-sdk.md)
* Product: **xamarin**
* Technology: **xamarin-android**
* GitHub Login: @conceptdev
* Microsoft Alias: **crdun**

**Comment by conceptdev** [comment]
Please report issues like this [inside Visual Studio for Mac](https://docs.microsoft.com/visualstudio/mac/report-a-problem?view=vsmac-2019), so that the team gets diagnostic information that can help solve the issue. Thanks.
