### ISSUE TITLE
Xamarin.Forms resource lookup precedence

### ISSUE THREAD

**Issue by RajasekarBabu** [MicrosoftDocs/xamarin-docs#160]
In the following point, should the 'in the order' be 'in the reverse order'? As I saw, in the code, merged dictionaries are reversed before look up process.

'3. The resources contained in the resource dictionaries that were merged via the MergedDictionaries collection, in the order they are listed in the MergedDictionaries property.'

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1d23ce09-1c59-1482-036a-f7348090fd00
* Version Independent ID: 9b4213b5-8278-5bea-c73d-0e172d7c0a89
* Content: [Resource Dictionaries - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/xaml/resource-dictionaries#feedback)
* Content Source: [docs/xamarin-forms/xaml/resource-dictionaries.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/xaml/resource-dictionaries.md)
* Service: **unspecified**
* GitHub Login: @charlespetzold
* Microsoft Alias: **chape**

**Comment by RajasekarBabu** [comment]
Any update on the above query?

**Comment by davidbritch** [comment]
Hi @RajasekarBabu 

Apologies for the delayed response to your issue. You're right. I've updated the doc, which will go live once the PR is merged.

Thanks for pointing this out.
