### ISSUE TITLE
Box sizing behavior

### ISSUE THREAD

**Issue by Ghasan** [MicrosoftDocs/xamarin-docs#1602]
Box sizing behavior needs to be added, as it is quite confusing for those coming from web development to Xamarin, as it has two different behaviors depending on the size offered by parent element. Refer to discussions:
https://forums.xamarin.com/discussion/150004/xamarin-forms-box-sizing
https://developer.mozilla.org/en-US/docs/Web/CSS/box-sizing

Basically, padding will be added to the width / height requested if there is extra room for the element, otherwise, it will deduct padding size from the width / height requested.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8e602f0b-0118-2c49-6564-3ba7fd2c0b43
* Version Independent ID: da2560d0-e178-161c-e9c8-93be02fe660f
* Content: [Margin and Padding - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/layouts/margin-and-padding#feedback)
* Content Source: [docs/xamarin-forms/user-interface/layouts/margin-and-padding.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/layouts/margin-and-padding.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by Ghasan** [comment]
Well, there is a caveat. Button respects its Height/Width Request, and deducts padding from the requested size, even if there is extra space in the parent element.

**Comment by davidbritch** [comment]
Hi @Ghasan 

Apologies for the delayed response. Really this is about how Xamarin.Forms layout works. There's a doc that touches on it (https://docs.microsoft.com/xamarin/xamarin-forms/user-interface/layouts/custom), but it doesn't go into all the details.

I'll add this to our (private) backlog.
