### ISSUE TITLE
Error in snippets

### ISSUE THREAD

**Issue by shakmurb** [MicrosoftDocs/xamarin-docs#1606]
Line:
listView.ItemsSource.Add("monochrome")
Will not work as there is no Add method in array. You should use List for that functionality. 

In this snippet:
&lt;?xml version="1.0" encoding="utf-8" ?&gt;
&lt;ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
xmlns:constants="clr-namespace:XamarinFormsSample;assembly=XamarinFormsXamlSample"
x:Class="XamarinFormsXamlSample.Views.EmployeeListPage"
Title="Employee List"&gt;
  &lt;ListView x:Name="EmployeeView"&gt;
    &lt;ListView.ItemTemplate&gt;
      &lt;DataTemplate&gt;
        &lt;TextCell Text="{Binding DisplayName}" /&gt;
      &lt;/DataTemplate&gt;
    &lt;/ListView.ItemTemplate&gt;
  &lt;/ListView&gt;
&lt;/ContentPage&gt;

ListView will show just blank lines as it's not specified what Class will be used. ListView missing attribute ItemsSource="Employee"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f9bb8625-60a7-2d18-86aa-501c64a71073
* Version Independent ID: 4891a28f-63b1-dca9-0467-fc81f32363cf
* Content: [ListView Data Sources - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/listview/data-and-databinding#feedback)
* Content Source: [docs/xamarin-forms/user-interface/listview/data-and-databinding.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/listview/data-and-databinding.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @shakmurb 

Thanks for pointing these issues out. I've fixed them in a PR which will go live later.
