### ISSUE TITLE
To start the Android Emulator a whole lot more needs to be installed

### ISSUE THREAD

**Issue by Darlanio** [MicrosoftDocs/xamarin-docs#1609]
Sorry, but this leave a lot to be wished for.

Intel® Hardware Accelerated Execution Manager does not get properly installed without doing it manually.
Android Emulator does not start, get project deployed and start debugging the project without a lot of manual work.
Make sure the installation installs a simple Android Emulator that works on CPU alone (always work, even if slow).
Get the templates to compile, deploy and debug on that emulator, even if it is KitKat-4.4 or earlier.
After installation the product should just work. Later it can be optimzed, speed up and upgraded.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b4445585-af8f-09d3-5d35-762c3aac187b
* Version Independent ID: fa9263db-60d6-eb98-eb74-842351ba5387
* Content: [Build your first Xamarin.Forms app - Xamarin](https://docs.microsoft.com/en-us/xamarin/get-started/first-app/?pivots=windows)
* Content Source: [docs/get-started/first-app/index.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/get-started/first-app/index.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @conceptdev
* Microsoft Alias: **crdun**

**Comment by hnmange** [comment]
@Darlanio Same here. I should be like install and develop.

**Comment by conceptdev** [comment]
See also the related feedback in this issue https://github.com/MicrosoftDocs/xamarin-docs/issues/1608

**Comment by dbartoncooke** [comment]
I get the emulator running - until it hangs and says "System UI isn't responding". No errors. The only warnings are about iOS, which is not what I am running. I am running an Oreo emulator.

**Comment by davidbritch** [comment]
The videos on this page have now been updated.
