### ISSUE TITLE
Unable to generate a bug report on https://developercommunity.visualstudio.com/spaces/8/index.html

### ISSUE THREAD

**Issue by sushihangover** [MicrosoftDocs/xamarin-docs#161]
On Mac : Generate bug report within the  Android Device Manager app, creates a bug report zip file (XDM_BugTool_XXXX.zip) and provides a link to https://developercommunity.visualstudio.com/spaces/8/index.html.

BUT, you can not "Report a problem" on that developercommunity.visualstudio.com page as it requires you to do it via Visual Studio or an installer. 

The docs state:

>If you find a problem with the Xamarin Android Device Manager that cannot be resolved using the above troubleshooting tips, please file a bug report by clicking Help > Generate Bug Report:

Which is not possible...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77921f62-3d69-ff6e-57a8-ebe4bffde990
* Version Independent ID: d12d0c6d-5e03-533e-a6cc-fe940ff18206
* Content: [Xamarin Android Device Manager - Xamarin](https://docs.microsoft.com/en-us/xamarin/android/get-started/installation/android-emulator/xamarin-device-manager?tabs=vsmac)
* Content Source: [docs/android/get-started/installation/android-emulator/xamarin-device-manager.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/android/get-started/installation/android-emulator/xamarin-device-manager.md)
* Service: **unspecified**
* GitHub Login: @mgmclemore
* Microsoft Alias: **mamcle**

**Comment by conceptdev** [comment]
@sushihangover if you are on a Mac, go to the [Visual Studio for Mac](https://developercommunity.visualstudio.com/spaces/41/index.html) tab on Developer Community and do **Report a problem** from there.

I'll pass on the feedback too, thanks.
