### ISSUE TITLE
Provide documention on using BindableLayout with Grid

### ISSUE THREAD

**Issue by dansiegel** [MicrosoftDocs/xamarin-docs#1610]
The documentation currently gives the impression that BindableLayout works with Grid, AbsoluteLayout and RelativeLayout, yet none of these have an actual example as far as I can tell.

The issue with each of the layouts I mentioned is that you quickly run into the issue where you may need to specify attributes for views that need to be created for each item in your ItemsSource.

```cs
public class Person
{
    public string FirstName { get; set; }
    public string LastName { get; set; }
    public DateTimeOffset DOB { get; set; }
    public Uri AvatarUri { get; set; }
}
```

Let's say for instance that you have a Person object and you want to layout people in a Grid. I might have a column for the Avatar, another for the First Name, another for the Last Name, and another for the Date of Birth.

The first issue is that BindableLayout only provides for a DataTemplate which requires a single object so if I have something like:

```xml
<DataTemplate>
  <Grid>
    <Image Source="{Binding AvatarUri}" Grid.Column="0" />
    <Label Text="{Binding FirstName}" Grid.Column="1" />
    <Label Text="{Binding LastName}" Grid.Column="2" />
    <Label Text="{Binding DOB}" Grid.Column="3" />
  <Grid>
</DataTemplate>
```

This in essence is creating a flat grid with a bunch of Grid's as Children... which begs the question why didn't I just do a StackLayout… 

#### Ask for the docs

1. Is there really support for Grid
1. If there is, let's see an example
1. If there isn't, let's update the docs to reflect that it's not really suited to this sort of use.
1. If there is, let's take it a step further... does it support only flat rows for an element in our ItemsSource or does it support scenarios where I might have a RowSpan or ColumnSpan?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 59df8b1e-8b94-a79e-25eb-f47ddf38777a
* Version Independent ID: cd195715-e7e3-428f-1061-c550ff960dda
* Content: [Bindable Layouts in Xamarin.Forms - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/layouts/bindable-layouts#feedback)
* Content Source: [docs/xamarin-forms/user-interface/layouts/bindable-layouts.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/layouts/bindable-layouts.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @dansiegel 

I'm afraid that bindable layouts don't support the scenario you've outlined. I've added a clarification to the doc, in a PR which will go live later.

**Comment by dansiegel** [comment]
@davidbritch I would tend to agree with your conclusion that it doesn't support it… I'm not sure if you've merged your changes, but just looking at master as of right now the docs still say:

> These properties can be attached to the AbsoluteLayout, FlexLayout, Grid, RelativeLayout, and StackLayout classes, which all derive from the Layout<T> class.
