### ISSUE TITLE
Xamarin.Auth is made for PCL not .NET and throws errors

### ISSUE THREAD

**Issue by rdurrance** [MicrosoftDocs/xamarin-docs#1613]
Is there going to be an update to Xamarin.Auth and Xamarin.Auth.XamarinForms that includes more support for .NET standard 2.0? The dependencies that are included in these do not use package references and the standard Xamarin.Forms project does not create a packages.config. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aa8bb9e0-5898-0d11-0213-fd4d8c8d0297
* Version Independent ID: 2f46e1f7-164f-2f32-70c0-f28919d16c5c
* Content: [Authenticating Users with an Identity Provider - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/data-cloud/authentication/oauth#feedback)
* Content Source: [docs/xamarin-forms/data-cloud/authentication/oauth.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/data-cloud/authentication/oauth.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by profexorgeek** [comment]
I'm in the process of updating our Azure Active Directory B2C authentication sample and docs. This is not exactly what you're looking for but may be helpful, or even an effective alternative as it allows using third-party identity providers. It uses a shared .NET Standard library and the Microsoft Authentication Library (MSAL) Nuget package.

When I finish the doc updates it should offer a better end-to-end explanation. For now, the updated sample project is on a branch here:
https://github.com/xamarin/xamarin-forms-samples/tree/jusjohns-auth-b2c-overhaul/WebServices/AzureADB2CAuth

**Comment by conceptdev** [comment]
Thanks for the question @rdurrance.

The AD B2C changes mentioned above are now published (along with updated sample). 

For questions specific to the Xamarin.Auth implementation, visit the [open source GitHub page](https://github.com/xamarin/Xamarin.Auth) where you can see the current work in progress.
