### ISSUE TITLE
section on wifi confuses itself

### ISSUE THREAD

**Issue by edray581** [MicrosoftDocs/xamarin-docs#1614]
Section on wifi states: "This technique requires a bit more effort but could be useful when there is NO USB cable or the device is TOO FAR away for a USB cable.

So if there is NO USB cable or the device is TOO FAR to be able to use a USB cable the wifi section should be explaining how to connect to wifi WITHOUT the use of any cable.

Instead the first thing the wifi section says is to connect a USB cable... HUH? What part of there is NO USB cable or its too far to connect to a USB cable do the authors of this section do not understand?

The section is being written as if you ALWAYS have to connect a USB cable first before you can switch over to a wifi connection but this is N-O-T true.

If you have a rooted android device, the switching over to the tcpip can be done on the android device side without NO initial USB connection to the development computer by means of activating a wifi adb app on the android device (there are many such apps  available for android devices).

Once this "wifi adb" app is initiated, the development computer will listen to devices connected via tcpip. The app will then tell you to connect via the "ADB connect &lt;Device IP address&gt;:DefaultPortNumber” command such as "ADB connect 192.168.0.3:5555". So, if you do this command on the development computer side as requested, you would NEVER need to connect to a USB cable.

This is what should have been stated in that WIFI section. 

For completeness, one can then specify in that same section, that in absence of such a "wifi adb" app or equivalent terminal script on the android device or in the case the android device is NOT rooted, then and only then will you need to connect to a USB cable first before one can switch over to tcpip. 

For the users that had required that first USB connection, Once the switch to the tcpip connection is made, you will not need the USB cable until the android device is reset (device is powered off and restarted). 

 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0fe8d6a6-7a42-810a-d5d4-e3bd162ae09a
* Version Independent ID: c7851826-27c9-9126-cb46-9300c57c440b
* Content: [Set Up Device for Development - Xamarin](https://docs.microsoft.com/en-us/xamarin/android/get-started/installation/set-up-device-for-development#feedback)
* Content Source: [docs/android/get-started/installation/set-up-device-for-development.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/android/get-started/installation/set-up-device-for-development.md)
* Product: **xamarin**
* Technology: **xamarin-android**
* GitHub Login: @conceptdev
* Microsoft Alias: **crdun**

**Comment by conceptdev** [comment]
Thanks for your feedback. We do not support or encourage customers to root their devices.
