### ISSUE TITLE
Please update the document for VS2019

### ISSUE THREAD

**Issue by kkarakk** [MicrosoftDocs/xamarin-docs#1615]
It's been released already and i don't see a way to use Pie on it(dropdown doesn't have it even after installing Pie sdk)
This is on an existing project that was targeting Pie in 2017 already.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2b11df82-abfb-85bb-36d0-e48c5f82c02e
* Version Independent ID: 109c5eac-2fb0-218d-b737-d244b45556a4
* Content: [Android 9 Pie - Xamarin](https://docs.microsoft.com/en-us/xamarin/android/platform/pie)
* Content Source: [docs/android/platform/pie.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/android/platform/pie.md)
* Product: **xamarin**
* Technology: **xamarin-android**
* GitHub Login: @conceptdev
* Microsoft Alias: **crdun**

**Comment by JonDouglas** [comment]
The docs state `Xamarin.Android 9.0.0.17 or later must be installed with Visual Studio `. Pie will show up as long as you are on that version and above.
