### ISSUE TITLE
DependencyResolver problem for UWP !

### ISSUE THREAD

**Issue by HADDADENICAR** [MicrosoftDocs/xamarin-docs#1616]
I have followed your [doc](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/platform/windows/installation/index) in objective if extending my existing xamarin app with uwp .

iI have added all the nuget packages available in the **\*.shared** project, then debugging i get an unhandled exception:
         
           "Object reference not set to an instance of an object." 

It's  triggered by the  *dependencyResolver* method: 

      await DependencyResolver.Resolve<INavigationService>().InitializeAsync();

that exists in OnStart() method of the App.xmal.cs of the  *\*.Mobile.Shared project*:

        protected override async void OnStart()
        {
           base.OnStart();

          if (Device.RuntimePlatform == Device.iOS)
          {
            SetInitialScreenForIos();
            await UserConfigurationManager.GetIfNeedsAsync();
          }

           await DependencyResolver.Resolve<INavigationService>().InitializeAsync();

          OnResume();
       }

what is wrong please ?

more description of my project in [SO](https://stackoverflow.com/questions/55722447/xamarin-uwp-unhandled-exception-during-launch)

**Comment by conceptdev** [comment]
Hi @HADDADENICAR, this is not a support channel, but for feedback on our documentation. However I took at quick look and it seems like you are using [ACRSupport](https://www.nuget.org/packages/Acr.Support/) but as you can see on [GitHub](https://github.com/aritchie/support) there is no UWP implementation.

**Comment by HADDADENICAR** [comment]
Does that means that  , in order to work all the nuget packages have to be the same for ***\*.ios*** ,***\*.droid*** and ***\*.shared*** ?

**Comment by conceptdev** [comment]
Any NuGet packages you use must have _support_ for UWP, if you plan to deploy on UWP. You can see from the GitHub source that package has no UWP code or support.
