### ISSUE TITLE
Missing Information

### ISSUE THREAD

**Issue by pdblasi** [MicrosoftDocs/xamarin-docs#1618]
This article is missing a lot of steps of how to set up the linker configuration file.

Specifically it's missing:
* Any required naming of the file
* Required/default location of the file (or how to set a custom location)
* Valid values to use within the file
* Links to any existing documentation that may explain these missing pieces

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f76b85eb-e640-6751-7eb2-fc58676d6018
* Version Independent ID: 422c639a-104a-4e31-cc78-03c023dd05ab
* Content: [Custom Linker Configuration - Xamarin](https://docs.microsoft.com/en-us/xamarin/cross-platform/deploy-test/linker#feedback)
* Content Source: [docs/cross-platform/deploy-test/linker.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/cross-platform/deploy-test/linker.md)
* Product: **xamarin**
* Technology: **xamarin-crossplatform**
* GitHub Login: @asb3993
* Microsoft Alias: **amburns**

**Comment by iBobb** [comment]
I share the frustration, there's missing info on linking and also this specific section for the Custom Linker Configuration. Linking is a complex thing and there should be a tutorial for the basic scenarios - take a third party SDK, put it in your Xamarin app - how to link it properly? For instance, a native XXX.framework for iOS

**Comment by JonDouglas** [comment]
Thanks for filing an issue on this!

Much of this documentation comes directly from the Mono IL Linker where you can also read up on here:

https://github.com/mono/linker/blob/master/src/linker/README.md

and additionally the Linker Analyzer tool:

https://github.com/mono/linker/blob/master/src/analyzer/README.md

There are additional examples and explanations here:

https://github.com/mono/linker#link-xml-file-examples

Regarding these questions:

**Any required naming of the file**
Unless stated, there should not be any required naming. The `Build Action` set is the indicator that this file should be used within the linker at MSBuild time.
**Required/default location of the file (or how to set a custom location)**
We recommend the default location within the head project (iOS/Android) root as per the docs. 
**Valid values to use within the file**
We can probably add the XML file example above into this doc if it's more helpful!
**Links to any existing documentation that may explain these missing pieces**
We can also add links to these mono repository readmes and CLI reference (i.e. https://linux.die.net/man/1/monolinker)

Finally, Blazor also uses the same linker and links to similar documentation. Is there anything else on this page we can help make our custom linking page more clear with?

https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/blazor/configure-linker?view=aspnetcore-3.1#control-linking-with-a-configuration-file

Custom linking is quite an advanced scenario & I'd love to better understand how we can improve this documentation!

**Comment by CDrosos** [comment]
also another alternative solution for those who want linking and have issues with the default linking configurations is this: https://docs.microsoft.com/en-us/xamarin/android/deploy-test/linker#falseflag
