### ISSUE TITLE
More clarification needed for binding a member definition that returns a type which conforms to another

### ISSUE THREAD

**Issue by S1r-Lanzelot** [MicrosoftDocs/xamarin-docs#162]
It may be helpful to add guidance on binding types that conform to other types (protocols). 

For example with member:
```
- (UIViewController<AKFViewController> *)viewControllerForPhoneLoginWithPhoneNumber:(nullable AKFPhoneNumber *)phoneNumber
                                                                              state:(nullable NSString *)state;
```

we have a `UIViewController` which conforms to the `AKFViewController` type. It is confusing as to how one would go about binding this (`UIViewController<AKFViewController>`), is it:

```
 // -(UIViewController<AKFViewController> * _Nonnull)viewControllerForPhoneLoginWithPhoneNumber:(AKFPhoneNumber * _Nullable)phoneNumber state:(NSString * _Nullable)state;
[Export("viewControllerForPhoneLoginWithPhoneNumber:state:")]
AKFViewController ViewControllerForPhoneLoginWithPhoneNumber([NullAllowed] PhoneNumber phoneNumber, [NullAllowed] string state);
```

or

```
// -(UIViewController<AKFViewController> * _Nullable)viewControllerForPhoneLoginWithPhoneNumber;
[NullAllowed, Export("viewControllerForPhoneLoginWithPhoneNumber:state:")]
UIViewController ViewControllerForPhoneLoginWithPhoneNumber ( );
```

or 

I thought of using ForcedTypes but that is the wrong use case... So perhaps must we set the basetype of the `AKFViewController` interface as a `UIViewController `even though the protocol does not specify this:
```
@protocol AKFViewController <AKFUIManaging, AKFConfiguring>
```

or (if it isn't changing `AKFViewController` base type) the solution could be creating a skeleton interface for the scenario as follows:
```
    [BaseType(typeof(UIViewController))]
    [Protocol]
    interface IUIViewController : AKFViewController { }
```

(please forgive any conceptual errors I make in the statements above... reading the docs for a reason 😅 )

Bottom-Line: I find information for this situation lacking and I have seen similar questions out there to this example without concrete answers, I thought this could be another candidate for the docs. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6f9b50f1-2047-b6fc-ad8a-b4ceecca5f9d
* Version Independent ID: 7b24c3d1-4861-1e1b-d8a0-7dbf5bd251b6
* Content: [Binding types reference guide - Xamarin](https://docs.microsoft.com/en-us/xamarin/cross-platform/macios/binding/binding-types-reference#member-definitions)
* Content Source: [docs/cross-platform/macios/binding/binding-types-reference.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/cross-platform/macios/binding/binding-types-reference.md)
* Service: **unspecified**
* GitHub Login: @bradumbaugh
* Microsoft Alias: **brumbaug**

**Comment by bradumbaugh** [comment]
Hi @S1r-Lanzelot - thanks for the question. I agree that it would be good to provide some text about this. I'll make this update alongside the update for [this issue](https://github.com/MicrosoftDocs/xamarin-docs/issues/104).

In the meantime, I'm looking at the best way to do this and will keep you posted.

**Comment by bradumbaugh** [comment]
Hi @S1r-Lanzelot,

Some thoughts for you, here (just a starting point, I haven't tested these):

```
namespace MyNamespace
{
    using UIKit;
 
    [Protocol]
    interface AKFViewController { // ... };
  
    [BaseType(typeof(UIViewController))]
    interface MyCustomViewController : AKFViewController;
 
    [BaseType(typeof(NSObject))]
    interface MyClass {
 
        [Export("viewControllerForPhoneLoginWithPhoneNumber:state:")]
        MyCustomViewController ViewControllerForPhoneLogin( [Nullable] AKFPhoneNumber phoneNumber, [Nullable] string state );
 
    }
}
```

This is somewhat similar to the last option you mentioned above, but `MyCustomViewController` isn't a protocol in this version (as `IUIViewController` is in your version).

Another option, if you are really only concerned about the `AKFViewController` methods in the returned object:

```
namespace MyNamespace
{
    using UIKit;
 
    [Protocol]
    interface AKFViewController { // ... };

    interface IAKFViewController;

    [BaseType(typeof(NSObject))]
    interface MyClass {
 
        [Export("viewControllerForPhoneLoginWithPhoneNumber:state:")]
        IAKFViewController ViewControllerForPhoneLogin( [Nullable] AKFPhoneNumber phoneNumber, [Nullable] string state );
 
    }
}
```

This approach doesn't explicitly bind the return value to a `UIViewController` on the C# side, meaning that those methods wouldn't be available in C#. That may be fine, depending on how you need to use the class/what you need to do with it. 

One final option (again, similar to your third option):

```
namespace MyNamespace
{
    using UIKit;
 
    [Protocol]
    [Model][BaseType(typeof(UIViewController))]
    interface AKFViewController { // ... };
    
    [BaseType(typeof(NSObject))]
    interface MyClass {
 
        [Export("viewControllerForPhoneLoginWithPhoneNumber:state:")]
        AKFViewController ViewControllerForPhoneLogin( [Nullable] AKFViewController phoneNumber, [Nullable] string state );
 
    }
}
```

In this case, the returned value is an instance of the abstract class  that was generated by the `[Model]` and `[Protocol]` attributes on `AKFViewController`.

In general, I don't think there is a "right" way to do this - it depends on the API and how you'd like to use it.

This is as far as I can take this for now, but again I've captured your feedback and we'll update the bindings document.

Thanks again.

**Comment by S1r-Lanzelot** [comment]
Great thanks Brad, I appreciate you spending the time to walk through some scenarios. I will play around with some of the suggestions and pick whatever feels most appropriate when consuming the api.
