### ISSUE TITLE
Add to the instructions  using Notes;

### ISSUE THREAD

**Issue by jdcaruso** [MicrosoftDocs/xamarin-docs#1622]
in App.xaml.cs

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5a064123-54f2-0eb2-c76a-65b36c5ec1a7
* Version Independent ID: dbf4119a-2c24-e0f1-8041-bb3755c29c24
* Content: [Create a single page Xamarin.Forms application - Xamarin](https://docs.microsoft.com/en-us/xamarin/get-started/quickstarts/single-page?pivots=macos#feedback)
* Content Source: [docs/get-started/quickstarts/single-page.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/get-started/quickstarts/single-page.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by conceptdev** [comment]
Hi @jdcaruso, could you share more about what you'd like to see added?

**Comment by davidbritch** [comment]
@jdcaruso 

`using Notes;` isn't required in App.xaml.cs - https://github.com/xamarin/xamarin-forms-samples/blob/master/GetStarted/Notes/SinglePage/Notes/App.xaml.cs
