### ISSUE TITLE
Compatibility for 22+

### ISSUE THREAD

**Issue by PingPongSet** [MicrosoftDocs/xamarin-docs#1626]
The setup on section Compatibility, which theme will be used for android 22+?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 87b678e7-5336-db4f-02ac-db6d2115ebec
* Version Independent ID: 5434c705-8fa7-f2ed-e358-6c05d915cde0
* Content: [Material Theme - Xamarin](https://docs.microsoft.com/en-us/xamarin/android/user-interface/material-theme#related-links)
* Content Source: [docs/android/user-interface/material-theme.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/android/user-interface/material-theme.md)
* Product: **xamarin**
* Technology: **xamarin-android**
* GitHub Login: @conceptdev
* Microsoft Alias: **crdun**

**Comment by JonDouglas** [comment]
Material Design is the defacto theme used in Android API 21+. They do however have Material Components for Android in which includes App Compat versions of Material Design items.

https://material.io/develop/android/docs/getting-started/

This is the successor to Design Support Library that you can use today.

https://developer.android.com/topic/libraries/support-library/packages#design
