### ISSUE TITLE
Is there any way to Save favourite articles

### ISSUE THREAD

**Issue by arvindrajachourasiya** [MicrosoftDocs/xamarin-docs#1627]
Hi, I want to know that is there any way to Save or Add important articles of MS Xamarin docs?

Thank you.

**Comment by conceptdev** [comment]
No, this is not a feature of the docs.microsoft.com website. I guess the browser bookmarks menu is the best solution.

We also allow PDF downloads of each 'section' (see the link on the bottom left of each page, under the table of contents). To get a PDF of individual pages, you need to use your browser's print feature.
