### ISSUE TITLE
Portable Class Library

### ISSUE THREAD

**Issue by Alnahrawy** [MicrosoftDocs/xamarin-docs#1629]
Depending on information in this article [Portable Class Libraries (PCL)](https://docs.microsoft.com/ar-sa/xamarin/cross-platform/app-fundamentals/pcl?tabs=windows):

"

> Portable Class Libraries (PCLs) are considered deprecated in the latest versions of Visual Studio. While you can still open, edit, and compile PCLs, for new projects it is recommended to use .NET Standard libraries to access a larger API surface area.

"
I think you need to update this page [Xamarin.Forms using Visual Basic.NET
](https://docs.microsoft.com/en-us/xamarin/cross-platform/platform/visual-basic/xamarin-forms)
Thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 43b06b95-4697-7eb3-c11e-9ec95adcdbca
* Version Independent ID: 5dd15d0c-4bda-0ebc-534b-6252bd436ea6
* Content: [Xamarin.Forms using Visual Basic.NET - Xamarin](https://docs.microsoft.com/en-us/xamarin/cross-platform/platform/visual-basic/xamarin-forms#feedback)
* Content Source: [docs/cross-platform/platform/visual-basic/xamarin-forms.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/cross-platform/platform/visual-basic/xamarin-forms.md)
* Product: **xamarin**
* Technology: **xamarin-crossplatform**
* GitHub Login: @asb3993
* Microsoft Alias: **amburns**

**Comment by conceptdev** [comment]
Thanks for the suggestion @Alnahrawy. Since you bought this to our attention we have started working on the updates. It should be published in a few days.

**Comment by conceptdev** [comment]
Samples have been updated.

**Comment by conceptdev** [comment]
Docs have been updated. Thanks again.

**Comment by Alnahrawy** [comment]
I'm glad I was able to help, Thank you.
