### ISSUE TITLE
Include example for xamarin UWP?

### ISSUE THREAD

**Issue by LuqJensen** [MicrosoftDocs/xamarin-docs#1632]
How come there is no example for UWP in the cpp_with_xamarin sample?
It would be extremely helpful to have a complete beginners solution to this problem.
Is the netstandard project dll supposed to be used for UWP, or is the wrapper missing a compile target for UWP?
I have tried to compile the cpp source for UWP using a new VS project and then added a UWP project in the wrapper solution. But what compile options should be set in order to include the libMathFuncs.dll into the MathFuncs.dll, and what about the UWP specific parameters to include the new dll in the nuget package?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e40fbe03-a099-3b24-4654-162103003d6a
* Version Independent ID: 01e8c667-ed94-7054-758d-2399e879714a
* Content: [Use C/C++ libraries with Xamarin - Xamarin](https://docs.microsoft.com/en-us/xamarin/cross-platform/cpp/)
* Content Source: [docs/cross-platform/cpp/index.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/cross-platform/cpp/index.md)
* Product: **xamarin**
* Technology: **xamarin-crossplatform**
* GitHub Login: @mikeparker104
* Microsoft Alias: **miparker**

**Comment by conceptdev** [comment]
UWP is beyond the scope of this article - the intent is to show how to incorporate the Android and iOS toolchains to get the correct output to host in a NuGet to use in Xamarin apps.

This page on [How to: Use Existing C++ Code in a Universal Windows Platform App](https://docs.microsoft.com/en-us/cpp/porting/how-to-use-existing-cpp-code-in-a-universal-windows-platform-app?view=vs-2019) might be useful.

**Comment by LuqJensen** [comment]
Im sorry but that article just isnt helpful. It doesnt cover the steps for the nuget package for UWP. Why not include your own platform when making an article on the benefits of cross platform? Seems to me like shooting yourself in the foot.
Im very interested in details about this, alas it doesnt seem that there is sources on using C++ with xamarin for UWP specifically.
Conditional compiling, nuget, precompiled artefacts etc are all missing and seemingly very difficult to find for xamarin UWP.

**Comment by LuqJensen** [comment]
For anyone else stumbling across this I want to share my [repository](https://github.com/LuqJensen/CrossPlatformPrototypes/tree/master) wherein i have built a WinRT native component from the C++ source code provided by [xamarin/mobcat](https://github.com/xamarin/mobcat/tree/master2/samples/cpp_with_xamarin). I modified the .nuspec file to include targetting for UWP and added an UWP project to the xamarin forms app.
I have put some details in the commit messages and plan to write a more detailed readme. Hope this helps anyone with the same problem save some time!
And maybe the contributors will up date the docs, now that the ground work is laid.

**Comment by dinobu** [comment]
@LuqJensen MS seam to be getting lost on tracks (universal, crossplatform, crossplatform-win-excluded), but you seam to be getting it to the right track.  Thanks for your solution, I hope it works on UWP.  Wonder will it work with a C library as well?

**Comment by LuqJensen** [comment]
@dinobu yes the functions are explicitly expressed with extern C to make it easier to call from external languages. So its basically already an example on both C and C++.

**Comment by dinobu** [comment]
> @dinobu yes the functions are explicitly expressed with extern C to make it easier to call from external languages. So its basically already an example on both C and C++.

But I dont see anywhere in your MathFuncsLib/Build/MathFuncsLib.sh any UWP related build settings.  Sorry, I am not familiar with C or C++, just trying to figure out how to use a C library I got in my Xamarin.UWP project and I am following the example.  I am now at the "Orchestrating the toolchains" which talks only about setting build for IOS and Android but not UWP.  

I thought your example will show that, am I missing something?

**Comment by LuqJensen** [comment]
@dinobu perhaps that was non-obvious. Yes i didnt edit the built script provided by mobcat.
I added a WinRT project here. You will compile the native DLL from this [project](https://github.com/LuqJensen/CrossPlatformPrototypes/tree/master/MathFuncs/MathFuncs.UWP). Recommend using batch build to target all architectures at once.

**Comment by dinobu** [comment]
> @dinobu perhaps that was non-obvious. Yes i didnt edit the built script provided by mobcat.
> I added a WinRT project here. You will compile the native DLL from this [project](https://github.com/LuqJensen/CrossPlatformPrototypes/tree/master/MathFuncs/MathFuncs.UWP). Recommend using batch build to target all architectures at once.

No, I did not mean to "edit mobcat script".  I said in first sentence above, "I dont see anywhere in **your** MathFuncsLib/Build/MathFuncsLib.sh any UWP related build settings".  I am just following instructions provided by mobcat and attempting to use your repo together with these instructions and figure out how to use it for UWP and I got stuck at the "Orchestrating the toolchains" and tried how do you use it for UWP or even better for all 3 platforms.

Will WinRT work with UWP?
Any good guidance on doing batch builds to target Android, IOS and UWP?  
Thanks

**Comment by LuqJensen** [comment]
Point being that the steps from that article will not work with Windows because they do not produce a WinRT component. I included a project for that in my repo. Simply build it for your CPU architectures, use the updated .nuspec to pack it and install it in the demo xamarin app.
WinRT is [here](https://github.com/LuqJensen/CrossPlatformPrototypes/tree/master/MathFuncs/MathFuncs.UWP)
Updated .nuspec is [here](https://github.com/LuqJensen/CrossPlatformPrototypes/blob/master/MathFuncs/MathFuncs.nuspec)
Demo Xamarin app is [here](https://github.com/LuqJensen/CrossPlatformPrototypes/tree/master/XamarinForms)
