### ISSUE TITLE
What template we need to use?

### ISSUE THREAD

**Issue by mateohideg2** [MicrosoftDocs/xamarin-docs#1633]
Hello, in Xamarine.Android there are 4 templates, what template we need to use?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 185946f8-0709-ba00-7f52-25368e3d4f43
* Version Independent ID: 709db7ec-b02f-dcb5-81b8-e2e4d9a35252
* Content: [Web View - Xamarin](https://docs.microsoft.com/en-us/xamarin/android/user-interface/controls/web-view#feedback)
* Content Source: [docs/android/user-interface/controls/web-view.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/android/user-interface/controls/web-view.md)
* Product: **xamarin**
* Technology: **xamarin-android**
* GitHub Login: @conceptdev
* Microsoft Alias: **crdun**

**Comment by conceptdev** [comment]
Choose the template that suits the app you are building. You can follow the [quickstart](https://docs.microsoft.com/xamarin/android/get-started/hello-android/hello-android-quickstart) to see how to build a simple app. The WebView can be added to any of the templates.
