### ISSUE TITLE
Colour does not support direct content

### ISSUE THREAD

**Issue by christoroth** [MicrosoftDocs/xamarin-docs#1639]
These examples no longer work as the Color element does not support direct content.  This page is the first result when you search for "xamarin ResourceDictionary color".  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1d23ce09-1c59-1482-036a-f7348090fd00
* Version Independent ID: 9b4213b5-8278-5bea-c73d-0e172d7c0a89
* Content: [Resource Dictionaries - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/xaml/resource-dictionaries#feedback)
* Content Source: [docs/xamarin-forms/xaml/resource-dictionaries.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/xaml/resource-dictionaries.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @christoroth 

If by direct content, you mean `<Color x:Key="PageBackgroundColor">Yellow</Color>`, that is still supported.

I've just ran the sample the doc links to, and it still works as per the doc.

**Comment by RealBerd** [comment]
I've got same error today. The project in development for about ~4 month and it always has markup in ResourceDictionary like this one:
<Color  x:Key="Primary">#13bf94</x:Color>

Today it suddenly crashed with error
"XLS0502	The type 'Color' does not support direct content"

I replaced all colors with x:String and it works well, as Color has build-in string-to-Color TypeConverter
<x:String  x:Key="Primary">#13bf94</x:String>

That replacement works for me without changing how I operate with Resources
