### ISSUE TITLE
Typo in Code Sample

### ISSUE THREAD

**Issue by johnny-webdev** [MicrosoftDocs/xamarin-docs#1640]
Under the heading, Spacing, the following block of code references &lt;ColumnDefinitions Width="*"&gt; this is incorrect.  
The correct name is &lt;ColumnDefinition Width="*"&gt;

Wrong:
&lt;Grid ColumnSpacing="5"&gt;
  &lt;Grid.ColumnDefinitions&gt;
    &lt;ColumnDefinitions Width="*" /&gt;
    &lt;ColumnDefinitions Width="*" /&gt;
  &lt;/Grid.ColumnDefinitions&gt;
&lt;/Grid&gt;

Good: 
&lt;Grid ColumnSpacing="5"&gt;
  &lt;Grid.ColumnDefinitions&gt;
    &lt;ColumnDefinition Width="*" /&gt;
    &lt;ColumnDefinition Width="*" /&gt;
  &lt;/Grid.ColumnDefinitions&gt;
&lt;/Grid&gt;

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c0902f8-eb40-4c56-958a-f13f064c8293
* Version Independent ID: 1e930440-f312-6301-d786-262b98f9ce2f
* Content: [Xamarin.Forms Grid - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/layouts/grid#feedback)
* Content Source: [docs/xamarin-forms/user-interface/layouts/grid.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/layouts/grid.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @johnny-webdev 

Thanks for pointing this out. I've just fixed this in a PR that will go live later.
