### ISSUE TITLE
Sound

### ISSUE THREAD

**Issue by corykroll** [MicrosoftDocs/xamarin-docs#1641]
Does the remoted iOS simulator play sound?  In my testing with Visual Studio 2019, this is not the case, and the sound came from macOS.  If sound doesn't come through to Windows, this should be noted.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 18072f31-4d0e-f9b4-c085-fcaa66f278fc
* Version Independent ID: a9ba3155-0f55-f303-e27a-93360433cf0f
* Content: [Remoted iOS Simulator for Windows - Xamarin](https://docs.microsoft.com/en-us/xamarin/tools/ios-simulator/#feedback)
* Content Source: [docs/tools/ios-simulator/index.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/tools/ios-simulator/index.md)
* Product: **xamarin**
* Technology: **xamarin-crossplatform**
* GitHub Login: @lobrien
* Microsoft Alias: **laobri**

**Comment by conceptdev** [comment]
You're correct @corykroll, the engineering team has confirmed the sound doesn't get piped through to Windows, but just plays on the Mac. Will add a note to the page - thanks for the feedback.
