### ISSUE TITLE
Image shows slightly incorrect value

### ISSUE THREAD

**Issue by SteveGoodman** [MicrosoftDocs/xamarin-docs#1642]
The following code snippet:
&lt;Label Text={Binding Name} d:Text="Name" /&gt;

Would not quite produce the image shown below it (https://docs.microsoft.com/en-us/xamarin/xamarin-forms/xaml/xaml-previewer/xaml-previewer-images/designtimedata-label-sm.png)

As this image shows **Name!** and it should be **Name**

Either the image needs to be updated or the references to Name need updating to Name!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b137e71e-e8c5-67c4-944f-a427edd8a5be
* Version Independent ID: d1350601-a386-8107-182e-cc2485e31ae6
* Content: [Use Design Time Data with the XAML Previewer - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/xaml/xaml-previewer/design-time-data)
* Content Source: [docs/xamarin-forms/xaml/xaml-previewer/design-time-data.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/xaml/xaml-previewer/design-time-data.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @maddyleger1
* Microsoft Alias: **maleger**

**Comment by davidbritch** [comment]
Hi @SteveGoodman 

Thanks for pointing this out. I've just fixed this in a PR that will go live later.
