### ISSUE TITLE
Misspelling of ColumnDefinitions in Spacing section

### ISSUE THREAD

**Issue by bjfield** [MicrosoftDocs/xamarin-docs#1645]
In the Spacing section, the grid column definition elements are each written with an extra "s" on the end: &lt;ColumnDefinitions Width="*" /&gt;

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c0902f8-eb40-4c56-958a-f13f064c8293
* Version Independent ID: 1e930440-f312-6301-d786-262b98f9ce2f
* Content: [Xamarin.Forms Grid - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/layouts/grid#feedback)
* Content Source: [docs/xamarin-forms/user-interface/layouts/grid.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/layouts/grid.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @bjfield 

This is now fixed.
