### ISSUE TITLE
GetDeclaredMethod("OnEvent") returning null on iOs

### ISSUE THREAD

**Issue by Rhozero** [MicrosoftDocs/xamarin-docs#1646]
typeof(EventToCommandBehavior).GetTypeInfo().GetDeclaredMethod("OnEvent"); is returning null methodInfo on iOS.

Xamarin forms version 3.6.0.344457

**Comment by conceptdev** [comment]
Check your [linker](https://docs.microsoft.com/xamarin/ios/deploy-test/linker) settings. It is possible that the method is removed if the linker is set to "all assemblies".

If you still have a problem, use the [Xamarin.Forms repo](https://github.com/xamarin/Xamarin.Forms) to report an issue.
