### ISSUE TITLE
Error in code snippet

### ISSUE THREAD

**Issue by ChiduVenkat** [MicrosoftDocs/xamarin-docs#1650]
On instantiating the MapFragment as in the below code, the parameter "**Resource.Id.map_container**" throws error "**Resource Id doesn't exist**".

 var mapFrag = MapFragment.NewInstance();
    activity.FragmentManager.BeginTransaction()
                            .Add(**Resource.Id.map_container,** mapFrag, "map_fragment")
                            .Commit();

**Comment by conceptdev** [comment]
Please try out the [linked sample](https://docs.microsoft.com/samples/xamarin/monodroid-samples/mapsandlocationdemo-v3/). It uses [`AddMapFragmentToLayout(Resource.Id.map_container)`](https://github.com/xamarin/monodroid-samples/blob/master/MapsAndLocationDemo_v3/SimpleMapDemo/MyLocationActivity.cs#L44) which is referenced [here](https://github.com/xamarin/monodroid-samples/blob/master/MapsAndLocationDemo_v3/SimpleMapDemo/GoogleMapHelpers.cs#L56-L58) and is basically the same syntax as above (from [this doc](https://docs.microsoft.com/xamarin/android/platform/maps-and-location/maps/maps-api)).
