### ISSUE TITLE
GoBack

### ISSUE THREAD

**Issue by viktorszekeress** [MicrosoftDocs/xamarin-docs#1652]
Is there a way to call GoBack?
I'm also interested in CanGoBack property, is there something like that? Simply, based on the fact if there is any page in previous stack.

**Comment by conceptdev** [comment]
Which Xamarin platform are you asking about: Android, iOS, Mac, or Xamarin.Forms?

**Comment by viktorszekeress** [comment]
Hi, I'm using Xamarin.Forms.

**Comment by viktorszekeress** [comment]
Hi, is some more info still needed?
I would like to navigate back through Shell, as from my understanding, one of main reasons of Shell is to remove "low-level" stuff and use Shell instead. There is a GoTo method, which navigates forward. I would like to have similar method, eg GoBack.

**Comment by davidbritch** [comment]
Hi @viktorszekeress 

There's still some work being undertaken on Shell navigation, but here's the current situation.

When a route from the Shell visual hierarchy (described in your Shell file) is navigated to, a navigation stack isn't created. Therefore, you can use the `GoToAsync` method to navigate forwards and backwards through these routes, as doing so doesn't create a navigation stack. 

However, when a page that's not in the Shell visual hierarchy is navigated to, a navigation stack is created. That stack can currently be manipulated using the usual Xamarin.Forms navigation methods.
