### ISSUE TITLE
The code on this page does not execute

### ISSUE THREAD

**Issue by stevelhunt** [MicrosoftDocs/xamarin-docs#1653]
The "styling" tutorial makes no changes to the project from the previous "Database" tutorial. No changes to the style are implemented. The sample download makes no changes either.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 46228c67-1dc9-99e0-d279-ff6e722bfd5e
* Version Independent ID: 41994570-80f8-55ae-9a31-9696610b2353
* Content: [Style a cross-platform Xamarin.Forms application - Xamarin](https://docs.microsoft.com/en-us/xamarin/get-started/quickstarts/styling?pivots=macos#feedback)
* Content Source: [docs/get-started/quickstarts/styling.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/get-started/quickstarts/styling.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @stevelhunt 

Styling changes are made. They are just subtle. Perhaps they shouldn't be so subtle.

You can see the changes by comparing the screenshots at the top of the following two pages:

https://docs.microsoft.com/xamarin/get-started/quickstarts/database?pivots=macos
https://docs.microsoft.com/xamarin/get-started/quickstarts/styling?pivots=macos

Hope this helps.

**Comment by julioas09** [comment]
I see no difference at all either.

**Comment by pepeluiz8** [comment]
no difference at all

**Comment by davidbritch** [comment]
I've just refreshed the sample and doc to make the styling changes more obvious. Hope this helps.
