### ISSUE TITLE
There is no Xamarin.Forms 3.6 version available in Nuget

### ISSUE THREAD

**Issue by epomeranz** [MicrosoftDocs/xamarin-docs#1655]
According to this doc I should update to the latest version of xamarin.forms through NuGet. The minimum version required is 3.6. However NuGet shows 3.0.0... has the highest possible version. What am I doing wrong?

Thanks,
Eric

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7008caa8-8acd-9d45-9689-f92b48e78bbf
* Version Independent ID: a94b2057-d8c4-eabd-ca9b-b0de07b468b8
* Content: [XAML Previewer for Xamarin.Forms - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/xaml/xaml-previewer/?pivots=windows#feedback)
* Content Source: [docs/xamarin-forms/xaml/xaml-previewer/index.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/xaml/xaml-previewer/index.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @maddyleger1
* Microsoft Alias: **maleger**

**Comment by conceptdev** [comment]
Here is the NuGet website link for Xamarin.Forms:

https://www.nuget.org/packages/Xamarin.Forms

You should be able to see & install the latest version (and all these versions) from the NuGet window in Visual Studio 2019 or Visual Studio 2017. Access to the preview versions is enabled by a checkbox in the NuGet window.
