### ISSUE TITLE
Crashes when running UWP

### ISSUE THREAD

**Issue by JohnGaby** [MicrosoftDocs/xamarin-docs#1657]
This project immediately crashes when running UWP with the error:

{Windows.UI.Xaml.UnhandledExceptionEventArgs}

It is in the file App.g.i.cs, line 53. There is no stack trace. I am using Visual Studio 2017.

Any ideas?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ec31ee56-e3b9-a70a-a4ef-80fdf58e7249
* Version Independent ID: 766b5774-50bf-f43f-800d-48b5c6c66509
* Content: [Xamarin.Forms Master-Detail Page - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/navigation/master-detail-page)
* Content Source: [docs/xamarin-forms/app-fundamentals/navigation/master-detail-page.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/app-fundamentals/navigation/master-detail-page.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Confirmed that this is crashing.

**Comment by davidbritch** [comment]
The quick fix is to add the [Win2d.uwp](https://www.nuget.org/packages/Win2D.uwp/) NuGet package to the UWP project. Then the sample will run.

Early next week I'll fix this issue across all projects that require it.

**Comment by JohnGaby** [comment]
Thanks

**Comment by davidbritch** [comment]
I've bumped all of our samples to use the latest build of Forms 3.6. On UWP, this will cause a transitive restore of Win2d.uwp, due to being a dependency of Forms.
