### ISSUE TITLE
Preview button on VS for mac 2019

### ISSUE THREAD

**Issue by waletoye** [MicrosoftDocs/xamarin-docs#1658]
I cannot find xaml preview button on VS for mac 2019

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7008caa8-8acd-9d45-9689-f92b48e78bbf
* Version Independent ID: a94b2057-d8c4-eabd-ca9b-b0de07b468b8
* Content: [XAML Previewer for Xamarin.Forms - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/xaml/xaml-previewer/?pivots=macos#feedback)
* Content Source: [docs/xamarin-forms/xaml/xaml-previewer/index.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/xaml/xaml-previewer/index.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @maddyleger1
* Microsoft Alias: **maleger**

**Comment by conceptdev** [comment]
It should appear in the top-right of the XAML tab, just like the screenshot shows. Note that the previewer is only for Xamarin.Forms XAML files, not other file types.

If you continue to have issues, use the [report a problem](https://docs.microsoft.com/visualstudio/mac/report-a-problem?view=vsmac-2019) feature in Visual Studio for Mac.

**Comment by dinobu** [comment]
I also cannot see it anymore.  Reported here: https://github.com/MicrosoftDocs/xamarin-docs/issues/1888
