### ISSUE TITLE
Link Detail

### ISSUE THREAD

**Issue by CeciAc** [MicrosoftDocs/xamarin-docs#1660]
@amadorneto commented on [Tue Apr 30 2019](https://github.com/MicrosoftDocs/xamarin-docs.pt-br/issues/24)

No trecho "Uma versão estendida neste passo a passo pode ser encontrada na repositório GitHub do Mobile CAT que aborda essa parte do exemplo em maior profundidade. " é indicado o link que não existe:
https://github.com/xamarin/mobcat/blob/dev/samples/cppwithxamarin/README.md
O link que funciona é: (com underline em cpp_with_xamarin)
https://github.com/xamarin/mobcat/blob/dev/samples/cpp_with_xamarin/README.md

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: e40fbe03-a099-3b24-4654-162103003d6a
* Version Independent ID: 01e8c667-ed94-7054-758d-2399e879714a
* Content: [Usar bibliotecas de C/C++ com o Xamarin - Xamarin](https://docs.microsoft.com/pt-br/xamarin/cross-platform/cpp/#feedback)
* Content Source: [docs/cross-platform/cpp/index.md](https://github.com/MicrosoftDocs/xamarin-docs.pt-BR/blob/live/docs/cross-platform/cpp/index.md)
* Product: **xamarin**
* Technology: **xamarin-crossplatform**
* GitHub Login: @mikeparker104
* Microsoft Alias: **miparker**

**Comment by CeciAc** [comment]
Hi team, 
there's a broken link in the en-us page which replicates in the localized versions:

Rough translation:

> In the "An extended version of this walk-through can be found in the Mobile CAT GitHub repository that discusses this part of the sample in greater depth." Is indicated the link that does not exist:
> https://github.com/xamarin/mobcat/blob/dev/samples/cppwithxamarin/README.md
> The link that works is: (with underline in cpp_with_xamarin)
> https://github.com/xamarin/mobcat/blob/dev/samples/cpp_with_xamarin/README.md

**Comment by conceptdev** [comment]
Thanks for the report - fixing it now!
