### ISSUE TITLE
Where does "savedInstanceState" come from in the Android init line

### ISSUE THREAD

**Issue by tlhintoq** [MicrosoftDocs/xamarin-docs#1662]
The standard android project init line is:
            global::Xamarin.Forms.Forms.Init(this, bundle);
with `bundle` as the second param.  

Your example reads:
global::Xamarin.Forms.Forms.Init(this, savedInstanceState);
FormsMaterial.Init(this, savedInstanceState);
with `savedInstanceState` as the second param.  Where is this coming from? Do we need to add a `using` statement to the MainActivity.cs so this becomes available?  Or has the template for android projects changed for VS2019 making projects created in VS2017 incompatible or at least in need of migration instructions?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fbfbc90e-2eb6-a305-f7da-bded6e31a2b4
* Version Independent ID: 66cad08c-2158-c081-a668-e4dad525e664
* Content: [Xamarin.Forms Material Visual - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/visual/material-visual#initialize-material-renderers)
* Content Source: [docs/xamarin-forms/user-interface/visual/material-visual.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/visual/material-visual.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by conceptdev** [comment]
The templates may have changed the name of the parameter for the `OnCreate` method, but the name of this item is whatever appears in the method signature. See the code sample:

https://github.com/xamarin/xamarin-forms-samples/blob/master/UserInterface/VisualDemos/VisualDemos.Android/MainActivity.cs#L11

In your case, use `bundle` if that is what's already set up as the parameter name.
