### ISSUE TITLE
The sadness of UWP

### ISSUE THREAD

**Issue by dinobu** [MicrosoftDocs/xamarin-docs#1665]
Is UWP dead?  If you exclude your own technology from your own documentation and your own product, I think it means it is dead

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e40fbe03-a099-3b24-4654-162103003d6a
* Version Independent ID: 01e8c667-ed94-7054-758d-2399e879714a
* Content: [Use C/C++ libraries with Xamarin - Xamarin](https://docs.microsoft.com/en-us/xamarin/cross-platform/cpp/#feedback)
* Content Source: [docs/cross-platform/cpp/index.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/cross-platform/cpp/index.md)
* Product: **xamarin**
* Technology: **xamarin-crossplatform**
* GitHub Login: @mikeparker104
* Microsoft Alias: **miparker**

**Comment by conceptdev** [comment]
UWP is a product separate from Xamarin, though we offer an SDK that allows Xamarin user interfaces to render on UWP. Getting C or C++ to run on UWP is a separate issue to Xamarin's integration. 

In our C/C++ documentation we have focused on the area of most concern to our customers - getting their libraries on Android and iOS with Xamarin. The community has contributed some help to use UWP on [this issue thread](https://github.com/MicrosoftDocs/xamarin-docs/issues/1632). I hope that's useful for you also.
