### ISSUE TITLE
UI Controls learning document and code example with Xamarin Android

### ISSUE THREAD

**Issue by PingPongSet** [MicrosoftDocs/xamarin-docs#1667]
The link below provides good learning resource.  

https://docs.microsoft.com/en-us/xamarin/android/user-interface/

However, there are many controls that I cannot find learning resource and code example.

For example some controls (e.g.ExpandableListView etc) on Visual Studio Toolbox are below. 

**Is there a one stop learning resource and code example for these controls?**

[![enter image description here][1]][1]

[![enter image description here][2]][2]
[![enter image description here][3]][3]

  [1]: https://i.stack.imgur.com/AOUlD.png
  [2]: https://i.stack.imgur.com/QB1pA.png
  [3]: https://i.stack.imgur.com/pDewN.png

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e1e88190-5c02-5765-2353-d0df4b82dbbe
* Version Independent ID: 35e92af7-c1e9-afc0-cdbf-55ceeb89eeb1
* Content: [Creating User Interface with Xamarin.Android - Xamarin](https://docs.microsoft.com/en-us/xamarin/android/user-interface/)
* Content Source: [docs/android/user-interface/index.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/android/user-interface/index.md)
* Product: **xamarin**
* Technology: **xamarin-android**
* GitHub Login: @conceptdev
* Microsoft Alias: **crdun**

**Comment by conceptdev** [comment]
Thanks for your question @PingPongSet, the only Android controls we have Xamarin/C#-specific documentation for are listed on [this controls page](https://docs.microsoft.com/xamarin/android/user-interface/controls/), as well as the [layouts here](https://docs.microsoft.com/xamarin/android/user-interface/layouts/).

For the others, the next best place to start is Google's [Android user interface](https://developer.android.com/guide/topics/ui) and [android.widget](https://developer.android.com/reference/android/widget/package-summary) docs.
