### ISSUE TITLE
Inaccurate link to Hanselman sample

### ISSUE THREAD

**Issue by VeryKross** [MicrosoftDocs/xamarin-docs#1668]
The current link highlights the wrong source lines in the Hanselman sample. Link should be:
https://github.com/jamesmontemagno/Hanselman.Forms/blob/vnext/src/Hanselman/Views/Podcasts/PodcastDetailsPage.xaml#L26-L47

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b137e71e-e8c5-67c4-944f-a427edd8a5be
* Version Independent ID: d1350601-a386-8107-182e-cc2485e31ae6
* Content: [Use Design Time Data with the XAML Previewer - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/xaml/xaml-previewer/design-time-data#feedback)
* Content Source: [docs/xamarin-forms/xaml/xaml-previewer/design-time-data.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/xaml/xaml-previewer/design-time-data.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @maddyleger1
* Microsoft Alias: **maleger**

**Comment by davidbritch** [comment]
Hi @VeryKross 

Thanks for pointing this out. I've fixed it in a PR that will go live later.
