### ISSUE TITLE
Shell Navigation with custom routing does not work

### ISSUE THREAD

**Issue by markti** [MicrosoftDocs/xamarin-docs#1669]
I'm trying to get navigation to work using Shell and when I navigate using Shell.GoToAsync(string) it does nothing...how do I report this issue or get help with this?

**Comment by conceptdev** [comment]
You can click the **Feedback > This product** button at the bottom of the [Shell doc](https://docs.microsoft.com/xamarin/xamarin-forms/app-fundamentals/shell) or go directly to the [Xamarin.Forms open source repo](https://github.com/xamarin/xamarin.forms/issues) to raise an issue. Note that Shell is still in preview, so it may be a bug or known issue.
