### ISSUE TITLE
Firebase Remote Notifications Not Showing

### ISSUE THREAD

**Issue by TonyLugg** [MicrosoftDocs/xamarin-docs#167]
Following this walkthrough: [FCM Notifications Walkthrough](https://docs.microsoft.com/en-ca/xamarin/android/data-cloud/google-messaging/remote-notifications-with-fcm?tabs=vswin).  According to the documentation, when the app is backgrounded a notification pushed from the Firebase console should show up in the notification area and status bar.  On my Google Pixel (Oreo 8) device this did not happen until I handled onMessageReceived and manually created a notification.  It also seems it has to be handled differently in Oreo from earlier versions, needing to create a notification channel for Oreo.   The walkthrough is good but it is missing some essential pieces.  I still haven't been able to get the push notification to show up when the app is not running, which it should, it always did with GCM.

Is there more current documentation?

Also, is it possible to get the Android project to update to Firebase 60 in a Xamarin Forms solution?  I get dependency hell when trying to update it.

**Comment by topgenorth** [comment]
Thanks for bringing this to our attention, we'll take at look at the walkthrough and update it. 

As for updating to Firebase 60 in a Xamarin Forms solution: I'll see if I can track someone down who can provide some help with that issue.

**Comment by topgenorth** [comment]
@TonyLugg  I asked around about Firebase 60 & Xamarin.Forms. Please see the [Android Dependency Update note in this release note](https://developer.xamarin.com/releases/xamarin-forms/xamarin-forms-2.5/2.5.0-pre1/). It is possible for Xamarin.Forms to use Firebase 60, but (as you've observed) the resulting dependencies need to be manually update. It's not possible for X.F to automatically update those dependencies for you.

**Comment by TonyLugg** [comment]
Thanks Tom.  Updating the Android support libraries manually can be an exercise in dependency frustration on its own.  Do you know if it is safe to update the Android support libraries to the latest version in a XF solution, i.e. XF will work with the latest Android libs, or are we on our own to learn the hard way?

Tony Lugg
C-TAP Corp.
Tel: 780-481-9017
Cel: 780-991-3526
www.vdis.com<http://www.vdis.com/>

Microsoft Certified Partner

**Comment by davidortinau** [comment]
Hi Tony, I'm the Program Manager for Xamarin.Forms and thought I'd chime in on this.

The latest version of Xamarin.Android support libraries is 27.0.2, and Xamarin.Forms has been confirmed to work with that. Firebase 60 depends on GooglePlayServices 60 which depends on Xamarin.Android.Support >= 26.0.2. It would stand to reason this should work. But yes, you'll need to manage the dependences of your solution. 

I would recommend branching or some other mechanism to make sure if things go poorly that you can nuke the progress and come right back to a working state for your project.

**Comment by TonyLugg** [comment]
Thank you for chiming in David.  I’ll give it a try.  I’m using a separate solution to test the Firebase components so no fear of messing up the actual solution.

Tony Lugg
C-TAP Corp.
Tel: 780-481-9017
Cel: 780-991-3526
www.vdis.com<http://www.vdis.com/>

Microsoft Certified Partner
