### ISSUE TITLE
Any way to do this in xamarin.forms 

### ISSUE THREAD

**Issue by logeshpalani98** [MicrosoftDocs/xamarin-docs#1672]
When am trying do this in ContentPage inside Tabbed page, it not working, because of tabbed page is not visual element. Any way to like below this image using nuget or custom renderers suggest me

![Screenshot 2019-05-06 at 11 20 27 AM](https://user-images.githubusercontent.com/24875197/57272481-c4030800-7048-11e9-9993-f7dd143a3bca.png)

**Comment by davidbritch** [comment]
ContentPages can be placed in TabbedPages without any problems. I suggest you take a look at https://docs.microsoft.com/xamarin/xamarin-forms/app-fundamentals/navigation/tabbed-page

Alternatively, consider using Shell to achieve the same behaviour: https://docs.microsoft.com/xamarin/xamarin-forms/app-fundamentals/shell/

**Comment by logeshpalani98** [comment]
yah, I archived this by writing a custom renderer
