### ISSUE TITLE
What about a possible implementation in VS?

### ISSUE THREAD

**Issue by FANMixco** [MicrosoftDocs/xamarin-docs#1674]
I'm not sure in which section it should be added, but this could be a great feature to add to VS by itself.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fd7ce9c9-cdec-1b1d-bd4b-b07e12e2388b
* Version Independent ID: a7c7ee7b-414a-de14-0894-e4200db6c886
* Content: [Building ABI-Specific APKs - Xamarin](https://docs.microsoft.com/en-us/xamarin/android/deploy-test/building-apps/abi-specific-apks)
* Content Source: [docs/android/deploy-test/building-apps/abi-specific-apks.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/android/deploy-test/building-apps/abi-specific-apks.md)
* Product: **xamarin**
* Technology: **xamarin-android**
* GitHub Login: @conceptdev
* Microsoft Alias: **crdun**

**Comment by conceptdev** [comment]
Hi @FANMixco, feature suggestions should be submitted on [developer community](https://developercommunity.visualstudio.com/spaces/8/index.html), thanks.
