### ISSUE TITLE
CPU architecture usage on devices

### ISSUE THREAD

**Issue by shalinasanga** [MicrosoftDocs/xamarin-docs#1675]
hi,
Can you specifically say which kind of devices use what cpu architecture ? 
Like, Emulators use this CPU and most of the handheld phones use this CPU architecture.
More clarification on selecting multiple cpu architectures much appriciated

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 78d11702-9a6f-ce25-3807-299f4905a00e
* Version Independent ID: f14945d8-62b4-7417-2f6d-02050ec2a927
* Content: [CPU Architectures - Xamarin](https://docs.microsoft.com/en-us/xamarin/android/app-fundamentals/cpu-architectures?tabs=windows)
* Content Source: [docs/android/app-fundamentals/cpu-architectures.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/android/app-fundamentals/cpu-architectures.md)
* Product: **xamarin**
* Technology: **xamarin-android**
* GitHub Login: @conceptdev
* Microsoft Alias: **crdun**

**Comment by conceptdev** [comment]
Hi @shalinasanga, this would be a large and ever-changing list, that we wouldn't be able to maintain.

Emulators use the CPU in the host computer - `x86` or `x86_64`. To work out what Arm CPU architecture a particular device uses, consult the documentation or manufacturer website.
