### ISSUE TITLE
Wrong property name

### ISSUE THREAD

**Issue by jsuvanto** [MicrosoftDocs/xamarin-docs#1681]
Under the heading Formatted text (https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/text/label#formatted-text) the property "Text" is described twice. The first instance should be "Style" instead.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f8a6273c-62b1-ac18-aab3-62f78bdbade8
* Version Independent ID: 746bd180-ae67-313d-b949-538a508807b2
* Content: [Xamarin.Forms Label - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/text/label#formatted-text)
* Content Source: [docs/xamarin-forms/user-interface/text/label.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/text/label.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @jsuvanto 

Thanks for pointing this out. I've just fixed it in a PR that'll go live later.
