### ISSUE TITLE
Source Code on Git Hub

### ISSUE THREAD

**Issue by rawueest** [MicrosoftDocs/xamarin-docs#1682]
Really helpful documentation! Providing the Source Code of the entire project on Git Hub would be even more helpful, thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8d9bfb2a-2e5d-d505-337f-919251a85de3
* Version Independent ID: 695bff64-ae87-8c0f-5616-20b67893fdf0
* Content: [Remote Notifications with Firebase Cloud Messaging - Xamarin](https://docs.microsoft.com/en-us/xamarin/android/data-cloud/google-messaging/remote-notifications-with-fcm?tabs=windows#feedback)
* Content Source: [docs/android/data-cloud/google-messaging/remote-notifications-with-fcm.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/android/data-cloud/google-messaging/remote-notifications-with-fcm.md)
* Product: **xamarin**
* Technology: **xamarin-android**
* GitHub Login: @conceptdev
* Microsoft Alias: **crdun**

**Comment by davidbritch** [comment]
Hi @rawueest 

The source code for the entire project can be accessed from the Related links section at the end of each doc.

**Comment by rawueest** [comment]
Ok, thanks David and sorry for not seeing it.
