### ISSUE TITLE
No advanced option to support 64 bit

### ISSUE THREAD

**Issue by JohnGaby** [MicrosoftDocs/xamarin-docs#1683]
The 'Advanced' dialog that I see does not contain any option to select support for 64 bit. With my current settings, when I generate an upload the apk file to Google it warns me that support for 64 bit will be required soon. Why do I not see these options?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 78d11702-9a6f-ce25-3807-299f4905a00e
* Version Independent ID: f14945d8-62b4-7417-2f6d-02050ec2a927
* Content: [CPU Architectures - Xamarin](https://docs.microsoft.com/en-us/xamarin/android/app-fundamentals/cpu-architectures?tabs=windows)
* Content Source: [docs/android/app-fundamentals/cpu-architectures.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/android/app-fundamentals/cpu-architectures.md)
* Product: **xamarin**
* Technology: **xamarin-android**
* GitHub Login: @conceptdev
* Microsoft Alias: **crdun**

**Comment by JonDouglas** [comment]
These dialogs include `arm64-v8a` and `x86_64` which are both 64-bit. If this is not the case today, please report an issue using the Help menu inside Visual Studio.

Please also note that x64 support is on by default in Xamarin.Android as of recent releases.

https://docs.microsoft.com/en-us/xamarin/android/release-notes/9/9.3#arm64-v8a-architecture-enabled-by-default

**Comment by ananthasivanvk** [comment]
How to add support for iOS ARM64-e A12 CPU architecture? I don't see the option under iOS Build.

**Comment by davidortinau** [comment]
Closing per Jon's note. 

@ananthasivanvk iOS architecture information is in the iOS section, such as https://docs.microsoft.com/en-us/xamarin/ios/deploy-test/compiling-for-different-devices?tabs=windows#arm64-xamarinios-started-supporting-arm64-in-v86
