### ISSUE TITLE
It's time to update this page

### ISSUE THREAD

**Issue by ncarandini** [MicrosoftDocs/xamarin-docs#1685]
I hope this page will eventually be updated, now that MSAL is no more in preview. Moreover, as stated in [this answer on stackoverflow](https://stackoverflow.com/questions/49258317/azure-mobile-app-obsolete) "Azure Mobile Apps" are something still supported, but the new kid in town is "App Center", so maybe this page should be demoted in favour of the App Center way of doing it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 16864cab-cbfa-98f3-c1da-7ed88cfe2579
* Version Independent ID: c1731783-e6da-af46-3fce-5e4bcc50dd61
* Content: [Integrating Azure Active Directory B2C with Azure Mobile Apps - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/data-cloud/authentication/azure-ad-b2c-mobile-app)
* Content Source: [docs/xamarin-forms/data-cloud/authentication/azure-ad-b2c-mobile-app.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/data-cloud/authentication/azure-ad-b2c-mobile-app.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @ncarandini 

This page/sample has been updated internally, and is undergoing review/feedback incorporation, prior to publication. Therefore I'll close this issue.
