### ISSUE TITLE
NFC Read/Write Tags

### ISSUE THREAD

**Issue by pw3107** [MicrosoftDocs/xamarin-docs#1686]
Any chance of NFC tag read/write support?

**Comment by conceptdev** [comment]
Hi @pw3107, Xamarin.Android and Xamarin.iOS provide access to all the native platform APIs, including NFC functionality where available.

**Comment by pw3107** [comment]
conceptdev,
                  Are any examples available for UWP NFC? I have tried the UWP samples, none of which I can get to work. NFCForms for XF works great on Android but can't get tags to write in UWP. Project seems abandoned. I just need to read/write text to a tag but XF seems to leave UWP behind. Is dependency injection the only option?
Thanks
Paul.

**Comment by conceptdev** [comment]
I had not seen the [NFCForms](https://github.com/poz1/NFCForms) project before, but you're right it has been a long time since any commits were made. The best option might be to try and re-use the code from that repo, and debug/update it if you can. Dependency injection is probably the way to go.

**Comment by pw3107** [comment]
Ok thanks will give it a try. Paul.
