### ISSUE TITLE
Make clear Native Views don't work with compiled XAML

### ISSUE THREAD

**Issue by NickSpag** [MicrosoftDocs/xamarin-docs#1690]
The first note simply says XAMLC, which isn't exactly clear, especially to newcomers. There's no other mention of the compiled XAML restriction other than that (the word compile isn't in the doc at all actually). I believe we also changed the standard Forms templates in the past few months to do XAML compilation assembly/app-wide, so no longer do you simply remove the attribute in code behind, you have to actively tell it to skip compilation. 

A suggestion for copy to change the note:
"Compiled XAML must be turned off for any XAML pages that use native views. Decorate the code-behind class of your XAML with the `[XamlCompilation(XamlCompilationOptions.Skip)]` attribute to turn off compilation."

Hope it helps.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a781e5d5-c0c4-4bc0-2049-97442139bee3
* Version Independent ID: 94e2df3f-c624-98d8-2edb-ef98134835b9
* Content: [Native Views in XAML - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/platform/native-views/xaml)
* Content Source: [docs/xamarin-forms/platform/native-views/xaml.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/platform/native-views/xaml.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @NickSpag 

Thanks for the suggestion. I've updated the doc in a PR that will go live later.
