### ISSUE TITLE
The sample links at the bottom are dead redirects

### ISSUE THREAD

**Issue by sticker592** [MicrosoftDocs/xamarin-docs#1692]
https://developer.xamarin.com/samples/xamarin-forms/behaviors/numericvalidationbehavior/
https://developer.xamarin.com/samples/xamarin-forms/behaviors/numericvalidationbehaviorstyle/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: de196cde-8c57-8c92-4495-fcfa066682f9
* Version Independent ID: 50986b5c-9e22-fd23-aed7-2d3b15ae0dbf
* Content: [Create Xamarin.Forms behaviors - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/behaviors/creating#feedback)
* Content Source: [docs/xamarin-forms/app-fundamentals/behaviors/creating.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/app-fundamentals/behaviors/creating.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by user135711** [comment]
and at the top

**Comment by davidbritch** [comment]
I've fixed this in a PR that will go live later.
