### ISSUE TITLE
placemark allway null on UWP?

### ISSUE THREAD

**Issue by nguyenthanhliemfc** [MicrosoftDocs/xamarin-docs#1695]
Thank for your docs!
It's working good on Android, but "placemark" allway null on UWP? 
I have add BingAPI in MainPage.xaml.cs of UWP Project.

---
#### Chi tiết tài liệu

⚠ *Không chỉnh sửa phần này. Điều này là bắt buộc cho docs.microsoft.com ➟ Vấn đề khi liên kết GitHub.*

* ID: 2ebb7d82-4f75-9c6d-8305-7d40afc3a4aa
* Version Independent ID: cd18ee2b-c941-cc79-c6de-8004294a5e08
* Content: [Xamarin.Essentials: Geocoding - Xamarin](https://docs.microsoft.com/vi-vn/xamarin/essentials/geocoding?context=xamarin%2Fxamarin-forms&tabs=uwp)
* Content Source: [docs/essentials/geocoding.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/essentials/geocoding.md)
* Product: **xamarin**
* Technology: **xamarin-essentials**
* GitHub Login: @jamesmontemagno
* Microsoft Alias: **jamont**

**Comment by jamesmontemagno** [comment]
Can you please open an issue on: https://github.com/xamarin/Essentials this is how we triage bugs. We will need a source code example of what you are trying to do.

**Comment by nguyenthanhliemfc** [comment]
Thank James! I'll open issue.

**Comment by jamesmontemagno** [comment]
@davidbritch  this can be closed
