### ISSUE TITLE
Xamarin Live Player Android app not available in Play store 

### ISSUE THREAD

**Issue by mabubakarriaz** [MicrosoftDocs/xamarin-docs#1697]
Please check Xamarin Live Player android app is not available in Play store, how to get the app that reads this QR code, general QR code reader app doesn't work for this. the step 0 instructions are missing on this page  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0c2e54f0-7761-c7fb-7de7-6680782dc771
* Version Independent ID: 323dd999-d78a-819a-cc93-8cf6a6b36fac
* Content: [Xamarin Live Player App - Xamarin](https://docs.microsoft.com/en-us/xamarin/tools/live-player/player?tabs=windows#feedback)
* Content Source: [docs/tools/live-player/player.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/tools/live-player/player.md)
* Product: **xamarin**
* Technology: **xamarin-crossplatform**
* GitHub Login: @lobrien
* Microsoft Alias: **laobri**

**Comment by conceptdev** [comment]
That is correct, the Live Player preview is only available from the HockeyApp link in the [setup instructions](https://docs.microsoft.com/en-us/xamarin/tools/live-player/install?tabs=windows). Note that the preview has ended and the Live Player is not available for Visual Studio 2019.
