### ISSUE TITLE
Please add DisplayAlert and DisplayActionSheet to this list

### ISSUE THREAD

**Issue by amp64** [MicrosoftDocs/xamarin-docs#1699]
Wasted hours of searching trying to figure out how to display a simple dialog box. Please add these items to this list.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8fdac83c-6d89-7423-b09c-d9a8c7e77d92
* Version Independent ID: 1888bc98-338a-dba3-58bd-96023925b5a7
* Content: [Xamarin.Forms User Interface Views - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/)
* Content Source: [docs/xamarin-forms/user-interface/index.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/index.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @amp64 

This is fixed in a PR that will go live later.
