### ISSUE TITLE
Update from links pointing to developer.xamarin.com to docs.microsoft.com

### ISSUE THREAD

**Issue by alfredmyers** [MicrosoftDocs/xamarin-docs#17]
Several links on [The Command Interface](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/data-binding/commanding) still point to pages under https://developer.xamarin.com.

Lots of them should be updated to point to https://docs.microsoft.com/

**Comment by conceptdev** [comment]
@alfredmyers our API documentation (any link that begins https://developer.xamarin.com/api/ ) has not yet been migrated to docs.microsoft.com (although we are working on it!)

For now, it's expected that those links take you to our old site; over the coming weeks you'll see those update to docs.microsoft.com/dotnet/api

Thanks for your feedback.

**Comment by alfredmyers** [comment]
OK.
Are you guys aware that links pointing to the namespace System.Windows.Input and the types in it (ICommand) are broken?

For instance:
- https://developer.xamarin.com/api/type/System.Windows.Input.ICommand/
- https://developer.xamarin.com/api/namespace/System.Windows.Input/

**Comment by conceptdev** [comment]
No - was not aware of that! Thanks for the tip, will investigate.
