### ISSUE TITLE
Triple "a" apps?

### ISSUE THREAD

**Issue by brokenjavagit** [MicrosoftDocs/xamarin-docs#170]
cross-platforma apps.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4cc8f83c-a8f5-ab4e-76f5-b617b65fe1ed
* Version Independent ID: 43dfad72-eea2-7607-9bee-b43f1cbab255
* Content: [Sharing Code Options - Xamarin](https://docs.microsoft.com/en-us/xamarin/cross-platform/app-fundamentals/code-sharing#Net_Standard)
* Content Source: [docs/cross-platform/app-fundamentals/code-sharing.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/cross-platform/app-fundamentals/code-sharing.md)
* Service: **unspecified**
* GitHub Login: @asb3993
* Microsoft Alias: **amburns**

**Comment by bradumbaugh** [comment]
Thanks, @brokenjavagit! I went ahead and fixed this typo. Fix should be published soon.

Appreciate the help!
