### ISSUE TITLE
Binding to Text in Span is OneTime not OneWay

### ISSUE THREAD

**Issue by SelectMany** [MicrosoftDocs/xamarin-docs#1700]
https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/text/label#formatted-text claims binding is OneWay but appears to behave as OneTime i.e. in order to get it to behave as OneWay have to explicitly set.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f8a6273c-62b1-ac18-aab3-62f78bdbade8
* Version Independent ID: 746bd180-ae67-313d-b949-538a508807b2
* Content: [Xamarin.Forms Label - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/text/label#feedback)
* Content Source: [docs/xamarin-forms/user-interface/text/label.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/text/label.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @SelectMany 

The binding mode is OneWay:

```
		public static readonly BindableProperty TextProperty
			= BindableProperty.Create(nameof(Text), typeof(string), typeof(Span), "", defaultBindingMode: BindingMode.OneWay);
```
