### ISSUE TITLE
UWP?

### ISSUE THREAD

**Issue by weitzhandler** [MicrosoftDocs/xamarin-docs#1705]
Is Shell supported in UWP devices? Can you please clarify this fact in the docs?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 09e0923c-3c3a-4e9b-bb30-b2d3fff2c34e
* Version Independent ID: 1a13d34a-8416-8e29-c65d-2c6d41c72b40
* Content: [Xamarin.Forms Shell Introduction - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/shell/introduction)
* Content Source: [docs/xamarin-forms/app-fundamentals/shell/introduction.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/app-fundamentals/shell/introduction.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by conceptdev** [comment]
Thanks for your suggestion. Shell is not supported on UWP - it is currently only available for iOS and Android. We'll update the docs to make this clearer.

**Comment by weitzhandler** [comment]
That means that XF 4 has brought no new to me 😢
Anyway, thanks for your update.
Feel free to close the issue.

**Comment by davidbritch** [comment]
Hi @weitzhandler 

I've updated the doc to make it clear that Shell isn't available on UWP. The update is in a PR that will go live later.

**Comment by nguyenthanhliemfc** [comment]
Could you please tell me know why Shell not available on UWP, Thank a lot!

**Comment by weitzhandler** [comment]
Because UWP is priority Z for Microsoft.

**Comment by nguyenthanhliemfc** [comment]
@weitzhandler It not support UWP. Will it break the Cross-platform concept?

**Comment by weitzhandler** [comment]
@nguyenthanhliemfc 
You can't use Shell if you want to target UWP.

**Comment by amirvenus** [comment]
Am I the only one that feels UWP is the next Silverlight?
