### ISSUE TITLE
Profiler Download Links Point to Old Versions

### ISSUE THREAD

**Issue by brianrob** [MicrosoftDocs/xamarin-docs#1706]
The profiler download links at https://github.com/MicrosoftDocs/xamarin-docs/blame/live/docs/tools/profiler/index.md#L33 point to version 1.6.1.483.  The latest version is currently 1.6.9-468.  Should these links be automatically updated?  I notice that they don't have a version number associated with them.

If desired, I can create a PR to update these links or to point at the [Release Notes](https://docs.microsoft.com/en-us/xamarin/tools/profiler/release-notes/) link which points at the latest version.

**Comment by conceptdev** [comment]
Thanks @brianrob, I guess the team didn't see this originally; but it was eventually updated (most recently in https://github.com/MicrosoftDocs/xamarin-docs/pull/1358). They "used to be" evergreen links that auto-served the latest version, but that no longer works 🙁
