### ISSUE TITLE
Code mistake in ScheduleLocalNotification example block

### ISSUE THREAD

**Issue by chamons** [MicrosoftDocs/xamarin-docs#1707]
```
UILocalNotification notification = new UILocalNotification();
NSDate.FromTimeIntervalSinceNow(15);
```
should be
```
UILocalNotification notification = new UILocalNotification();
notification.FireDate = NSDate.FromTimeIntervalSinceNow (15);
```
Else the notification does nothing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd0eb534-f7f4-e6c4-048f-d0712ebebe03
* Version Independent ID: 8aa5d675-3d41-492f-23fe-c11fb4e7efcf
* Content: [Notifications in Xamarin.iOS - Xamarin](https://docs.microsoft.com/en-us/xamarin/ios/platform/user-notifications/deprecated/local-notifications-in-ios)
* Content Source: [docs/ios/platform/user-notifications/deprecated/local-notifications-in-ios.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/ios/platform/user-notifications/deprecated/local-notifications-in-ios.md)
* Product: **xamarin**
* Technology: **xamarin-ios**
* GitHub Login: @lobrien
* Microsoft Alias: **laobri**

**Comment by conceptdev** [comment]
Fixed in linked PR
