### ISSUE TITLE
Style example property error

### ISSUE THREAD

**Issue by zy55769068** [MicrosoftDocs/xamarin-docs#1709]
Property="Shell.ShellTabBarBackgroundColor"
Property="Shell.ShellTabBarTitleColor"
Property="Shell.ShellTabBarUnselectedColor"
These properties are wrong,
the correct usage should be 
Shell.TabBarBackgroundColor
Shell.TabBarTitleColor
Shell.TabBarUnselectedColor

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ef7242a0-d46e-19ea-e22d-f327dcc9b3e9
* Version Independent ID: f050be8e-9413-19e7-5799-90a55c4e5bfb
* Content: [Xamarin.Forms Shell Layout - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/shell/tabs#feedback)
* Content Source: [docs/xamarin-forms/app-fundamentals/shell/tabs.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/app-fundamentals/shell/tabs.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @zy55769068 

While you're correct that the properties you've identified have been renamed, the correct naming is `Shell.BackgroundColor`, `Shell.TitleColor` etc. 

The docs have just been updated, and will continue to receive more updates this week.
