### ISSUE TITLE
Xaminals (sample) link 404!

### ISSUE THREAD

**Issue by nguyenthanhliemfc** [MicrosoftDocs/xamarin-docs#1710]
Xaminals (sample) link 404!

---
#### Chi tiết tài liệu

⚠ *Không chỉnh sửa phần này. Điều này là bắt buộc cho docs.microsoft.com ➟ Vấn đề khi liên kết GitHub.*

* ID: a303fbe7-5786-651e-e730-90efb1796e72
* Version Independent ID: 6a6a96eb-7563-8b4f-1272-1eb7bd221fb7
* Content: [Xamarin.Forms Shell Flyout - Xamarin](https://docs.microsoft.com/vi-vn/xamarin/xamarin-forms/app-fundamentals/shell/flyout#related-links)
* Content Source: [docs/xamarin-forms/app-fundamentals/shell/flyout.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/app-fundamentals/shell/flyout.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @nguyenthanhliemfc 

I've just updated that sample link and am awaiting the new docs building and publishing. Basically the sample is at the same location but in a different branch (master, instead of the forms40 branch).

**Comment by nguyenthanhliemfc** [comment]
Thank @davidbritch
