### ISSUE TITLE
MenuItems do not work anymore

### ISSUE THREAD

**Issue by francis2** [MicrosoftDocs/xamarin-docs#1711]
Forms 4.0.0.425677: MenuItems do not work anymore. Your samples are also broken. 

A value of type 'MenuItem' cannot be added to a collection or dictionary of type 'IList'.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a303fbe7-5786-651e-e730-90efb1796e72
* Version Independent ID: 6a6a96eb-7563-8b4f-1272-1eb7bd221fb7
* Content: [Xamarin.Forms Shell Flyout - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/shell/flyout#feedback)
* Content Source: [docs/xamarin-forms/app-fundamentals/shell/flyout.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/app-fundamentals/shell/flyout.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @francis2 

This is just an intellisense error that's being worked on. It builds and runs without any issues.

https://github.com/xamarin/Xamarin.Forms/issues/3864

**Comment by xeg12** [comment]
This is NOT just intellisense.
My MenuItems are defined in the XAML for the shell.
When I uncomment them and recompile I get an error:
Error XLS0415 The attachable property 'MenuItems' was not found in type 'Shell'. GenList MainShell.xaml
Therefore I am unable to continue without commenting out the MenuItems

**Comment by mohamadayash** [comment]
The same issue when I tried to run the app on iphone 
Error XLS0503	A value of type 'MenuItem' cannot be added to a collection or dictionary of type 'IList'.
