### ISSUE TITLE
Unsure what documentation is actually trying to communicate

### ISSUE THREAD

**Issue by joeruder** [MicrosoftDocs/xamarin-docs#1713]
Hello;

"Cache data can be used for any data that needs to persist longer than temporary data, but should not be data that is required to properly operate"

I am sorry...but what does this actually 'mean'?  
"Should not be data that is required to properly operate" -- on the surface sounds pretty vague.  Pretty much any data that we are storing in any type of persistent storage would be needed to properly operate.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 91d50947-38a1-44b7-2684-63b17d5bac66
* Version Independent ID: b449b3f5-7a68-fdea-041b-71cc39a46a48
* Content: [Xamarin.Essentials: File System Helpers - Xamarin](https://docs.microsoft.com/en-us/xamarin/essentials/file-system-helpers?tabs=android)
* Content Source: [docs/essentials/file-system-helpers.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/essentials/file-system-helpers.md)
* Product: **xamarin**
* Technology: **xamarin-essentials**
* GitHub Login: @jamesmontemagno
* Microsoft Alias: **jamont**

**Comment by jamesmontemagno** [comment]
Cache data can live for a longer amount of time or indefinitely as the OS dictates when it is cleared (or you can clear it yourself). So you shouldn't rely that it is always there and should check before reading files.

**Comment by BuddyLReno** [comment]
I think if the phrase is modified to add _... required to properly operate, as the OS dictates when this storage is cleared._ it would communicate the concept better.
