### ISSUE TITLE
French translation 

### ISSUE THREAD

**Issue by Lushkin** [MicrosoftDocs/xamarin-docs#1715]
Hello !
This sentenses : 
"Create a Thickness structure defined by a single uniform value. The single value is applied to the left, top, right, and bottom sides of the element.
Create a Thickness structure defined by horizontal and vertical values. The horizontal value is symmetrically applied to the left and right sides of the element, with the vertical value being symmetrically applied to the top and bottom sides of the element.
Create a Thickness structure defined by four distinct values that are applied to the left, top, right, and bottom sides of the element.." 
are confusing in french (
Créer un Thickness structure définie par une seule valeur uniforme. La valeur unique est appliquée à la gauche, haut, droite et quatre côtés de l’élément.
Créer un Thickness structure définie par les valeurs horizontales et verticales. La valeur horizontale est appliquée symétriquement pour les côtés gauche et droit de l’élément, avec la valeur verticale qui est appliquée symétriquement sur les côtés supérieur et inférieur de l’élément.
Créer un Thickness structure définie par quatre valeurs distinctes qui sont appliqués à la gauche, haut, droite et quatre côtés de l’élément.
) . You should write them this way =&gt; 
"Créer une structure Thickness définie par une seule valeur uniforme. La valeur unique est appliquée aux côtés gauche, haut, droite et bas de l’élément.
Créer une structure Thickness définie par les valeurs horizontales et verticales. La valeur horizontale est appliquée symétriquement pour les côtés gauche et droit de l’élément, avec la valeur verticale qui est appliquée symétriquement sur les côtés supérieur et inférieur de l’élément.
Créer une structure Thickness définie par quatre valeurs distinctes qui sont appliqués aux côtés gauche, haut, droite et bas de l’élément.".

Regards,

Roman.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8e602f0b-0118-2c49-6564-3ba7fd2c0b43
* Version Independent ID: da2560d0-e178-161c-e9c8-93be02fe660f
* Content: [Margin and Padding - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/layouts/margin-and-padding#feedback)
* Content Source: [docs/xamarin-forms/user-interface/layouts/margin-and-padding.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/layouts/margin-and-padding.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @Lushkin 

It looks like this has been dealt with by the localisation team, so I'll close the issue now.
