### ISSUE TITLE
Incorrect information relating to support

### ISSUE THREAD

**Issue by RowlandShaw** [MicrosoftDocs/xamarin-docs#1717]
Page states "Android 5.0 (API 21) or higher" however, compiler says:
The $(TargetFrameworkVersion) for MyProject.Android (v7.0) is less than the minimum required $(TargetFrameworkVersion) for Xamarin.Forms (8.1). You need to increase the $(TargetFrameworkVersion) for MyProject.Android.	

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 443cf095-5281-a757-0005-60dd1c82899c
* Version Independent ID: fd91ca24-84ae-04e4-14b5-d6738f8c6527
* Content: [Xamarin.Forms Requirements - Xamarin](https://docs.microsoft.com/en-us/xamarin/get-started/requirements?tabs=windows#feedback)
* Content Source: [docs/get-started/requirements.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/get-started/requirements.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by luanrox** [comment]
I'm with the same problem here.
![image](https://user-images.githubusercontent.com/172747/58586524-a41ec880-8231-11e9-8ff4-7dfd944c1d53.png)

**Comment by JonDouglas** [comment]
Xamarin.Forms uses the latest features available to both iOS and Android, which in turn requires it to target the latest stable API level. We have a note in the requirements page that describes this:

> Additionally, the target/compile version for Android projects must be set to Use latest installed platform. However the minimum version can be set to API 19 so you can continue to support devices that use Android 4.4 and newer. These values are set in the Project Options:

How might we improve this error message to make it clear when you run into it? Perhaps we can also add a link to our existing [Understanding Android API levels](https://docs.microsoft.com/en-us/xamarin/android/app-fundamentals/android-api-levels?tabs=windows) documentation to clarify what values need to be changed?

**Comment by davidbritch** [comment]
Hi @RowlandShaw 

What this means is you have to use the 8.1 (at a minimum) tools to compile your app. However, those tools can build API21 compatible apps.
