### ISSUE TITLE
Small Pointer

### ISSUE THREAD

**Issue by CoolinJack** [MicrosoftDocs/xamarin-docs#1720]
One thing that tripped me up was the naming conventions, NotesPage.xaml.cs is NOT the same as Notespage.xaml.cs !, Either way awesome tutorials !

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 60587f77-05de-89b9-8a08-c7e7221d27af
* Version Independent ID: 4080b687-b353-f833-4bb7-a7a3f9993338
* Content: [Perform navigation in a multi-page Xamarin.Forms application - Xamarin](https://docs.microsoft.com/en-us/xamarin/get-started/quickstarts/multi-page?pivots=windows#feedback)
* Content Source: [docs/get-started/quickstarts/multi-page.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/get-started/quickstarts/multi-page.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Thanks for the feedback @CoolinJack
