### ISSUE TITLE
VS2019

### ISSUE THREAD

**Issue by rob313663** [MicrosoftDocs/xamarin-docs#1729]
Why am I directed here when VS2019 fails to render the layout of an activity?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b6deff31-ea26-96a9-b201-b199a5fc4144
* Version Independent ID: ea7509c3-2f29-8775-b100-b94594d9f2f8
* Content: [Android Controls (Widgets) - Xamarin](https://docs.microsoft.com/en-us/xamarin/android/user-interface/controls/#feedback)
* Content Source: [docs/android/user-interface/controls/index.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/android/user-interface/controls/index.md)
* Product: **xamarin**
* Technology: **xamarin-android**
* GitHub Login: @conceptdev
* Microsoft Alias: **crdun**

**Comment by JonDouglas** [comment]
@rob313663 I'm not exactly sure here and apologies for a late response. Is this an info bar or error message that is redirecting you here?

**Comment by rob313663** [comment]
Can't remember the exact details, but I think it was a small bar being displayed at the top of the .xaml preview when the view failed to render, maybe caused by me. I think it the message was "Learn how to something something".

I must have been frustrated by the lack of information for troubleshooting why the layout couldn't be rendered.

My apologies.

**Comment by zunjae** [comment]
I got redirected here as well after a compilation error in the Editor. 'The yellow toolbar says: "Learn how to build native Android UIs" Learn More | Hide'

**Comment by conceptdev** [comment]
@JonDouglas there may be some indication that the yellow toolbar is appearing at a confusing time, and is conflated with compile issues? This page makes sense as the target of the "Learn Android UIs" prompt, but error conditions less so 😉
