### ISSUE TITLE
FlyoutItem typo

### ISSUE THREAD

**Issue by neville-nazerane** [MicrosoftDocs/xamarin-docs#1731]
Under the section "Describe the visual hierarchy of the application" the first bullet point reads "FlyoutItem or TabBar. A **FlyoutIcon** represents one or more items..." while it needs to be "FlyoutItem or TabBar. A **FlyoutItem** represents one or more items....".

It says "FlyoutIcon" instead of "FlyoutItem"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f4b70380-164f-2b1d-7480-bd9a92381c7d
* Version Independent ID: 504defb4-61ea-add0-1ad4-04f86fac2d2e
* Content: [Create a Xamarin.Forms Shell Application - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/shell/create#describe-the-visual-hierarchy-of-the-application)
* Content Source: [docs/xamarin-forms/app-fundamentals/shell/create.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/app-fundamentals/shell/create.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @neville-nazerane 

Thanks for pointing this out, and the PR that fixed it. However, I've just merged another PR that fixed it. Thanks anyway!
