### ISSUE TITLE
How to use multiple classes

### ISSUE THREAD

**Issue by haoyuant** [MicrosoftDocs/xamarin-docs#1733]
I want to add multiple classes into an element, like what we do in html css, is it possible?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7a410a97-17d3-aff7-c875-ee9291658957
* Version Independent ID: f415dc53-c941-b0e5-5823-9bafa53f0d9a
* Content: [Styling Xamarin.Forms Apps using Cascading Style Sheets (CSS) - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/styles/css/#feedback)
* Content Source: [docs/xamarin-forms/user-interface/styles/css/index.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/styles/css/index.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by sephirothse** [comment]
If your using xaml its comma separated

StyleClass="Class1,Class2"

**Comment by haoyuant** [comment]
Thanks @sephirothse !
