### ISSUE TITLE
Error: disallowed_useragent

### ISSUE THREAD

**Issue by nguyenthanhliemfc** [MicrosoftDocs/xamarin-docs#1738]
I have follow [Authenticating User Docs](https://docs.microsoft.com/vi-vn/xamarin/xamarin-forms/data-cloud/authentication/oauth) it show error:
![Untitled](https://user-images.githubusercontent.com/17796649/58553855-3cbc4500-8240-11e9-88f3-742961f9b8fe.png)

**Comment by davidbritch** [comment]
Hi @nguyenthanhliemfc 

This will most likely be a misconfiguration of the custom URL scheme in your Android app.
