### ISSUE TITLE
The github link needs to be updated

### ISSUE THREAD

**Issue by PureWeen** [MicrosoftDocs/xamarin-docs#174]
The Browse Code link here just goes to a 404 

https://developer.xamarin.com/samples/xamarin-forms/Effects/TouchTrackingEffectDemos/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 908530d1-f21d-5532-c530-1727e3356b64
* Version Independent ID: e01f2543-3b7d-0b60-8d79-c012feab83de
* Content: [Invoking Events from Effects - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/effects/touch-tracking#feedback)
* Content Source: [docs/xamarin-forms/app-fundamentals/effects/touch-tracking.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/app-fundamentals/effects/touch-tracking.md)
* Service: **unspecified**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
The link is now working (without any intervention). It's most likely that the server burped.

**Comment by PureWeen** [comment]
For me it still goes to a 404

It currently links to
https://github.com/xamarin/xamarin-forms-samples/tree/master/Effects/TouchTrackingEffectDemos
but should link to
https://github.com/xamarin/xamarin-forms-samples/tree/master/Effects/TouchTrackingEffect

![image](https://user-images.githubusercontent.com/5375137/39063324-f73fe4c4-4487-11e8-8c03-30570139e8f8.png)

**Comment by davidbritch** [comment]
Just confirmed that the browse code link in the above screenshot goes to the correct location. Let me know if you have any problems.
