### ISSUE TITLE
Add Bottom, Right properties

### ISSUE THREAD

**Issue by viktorszekeress** [MicrosoftDocs/xamarin-docs#1741]
You are using constants for YConstraints. Imagine, I want to change size of imageCircleBack from 70 to 50. Then I have to recalculate all the YConstraints for children below imageCircleBack, which is insane.

This could be solved by adding View.Right/View.Bottom properties to Xamarin.Forms.

**Comment by conceptdev** [comment]
@viktorszekeress can you add a link to the doc or sample you're referring to? Thanks!

**Comment by viktorszekeress** [comment]
Hi, sure,
I was referring to RelativeLayout doc https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/layouts/relative-layout

**Comment by davidbritch** [comment]
Hi @viktorszekeress 

Enhancing a Xamarin.Forms layout is an issue for the [engineering repo](https://github.com/xamarin/Xamarin.Forms/).
