### ISSUE TITLE
A link to Shell would be awesome

### ISSUE THREAD

**Issue by rlingineni** [MicrosoftDocs/xamarin-docs#1748]
Since Shell is the new recommended approach for Navigation - it would be nice to link it form this page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 31212614-035f-01b6-d709-250173086778
* Version Independent ID: 354945b1-351b-bb2d-a8c4-878650f521d0
* Content: [Xamarin.Forms Navigation - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/navigation/#feedback)
* Content Source: [docs/xamarin-forms/app-fundamentals/navigation/index.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/app-fundamentals/navigation/index.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @rlingineni 

I've added a link to the Shell nav doc, in a PR that will go live next week.
