### ISSUE TITLE
ClassInOtherAssembly

### ISSUE THREAD

**Issue by josh658** [MicrosoftDocs/xamarin-docs#1752]
I still quite new to this and I'm having trouble figuring out what to replace "ClassInOtherAssembly" with. I've tried a plethora of options but nothing seems to fit

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2ec3998b-c321-10e6-8e06-b10900c3a549
* Version Independent ID: de666c26-6261-7762-2c18-1576499b5fac
* Content: [Setup Windows Projects - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/platform/windows/installation/#feedback)
* Content Source: [docs/xamarin-forms/platform/windows/installation/index.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/platform/windows/installation/index.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
It's quite simply the name of a class in an assembly other than the current assembly. So given two assemblies, `Foo`, and `Bar`, with `Bar` containing a class called `Example`, in code in the `Foo` assembly you'd write:

```
using Bar;
...
DependencyService.Register<Example>();
```
