### ISSUE TITLE
Face ID support?

### ISSUE THREAD

**Issue by BradleyDHobbs** [MicrosoftDocs/xamarin-docs#1753]
Is there a way to simulate a successful Face ID match on the windows ios simulator?

**Comment by conceptdev** [comment]
When using a simulator that supports Touch ID, the Remote iOS Simulator on Windows will have a **Touch ID** button (fingerprint icon) that can be used for biometric authentication testing (with simulator 'models' that have a Touch ID sensor, like iPhone 6, 7, 8).

It does not yet support **Face ID**.
