### ISSUE TITLE
Problems to open the example

### ISSUE THREAD

**Issue by Fwallberg** [MicrosoftDocs/xamarin-docs#1754]
Is there any way to open the whole example correctly? I get several errors, such as errors in views and external projects.
https://prntscr.com/nwpf46

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 22a9c7fc-1586-bcae-7e6b-d0506887683f
* Version Independent ID: f5562480-74fd-dd21-e440-cf606a0d5e2d
* Content: [Consume a Windows Communication Foundation (WCF) Web Service - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/data-cloud/consuming/wcf#feedback)
* Content Source: [docs/xamarin-forms/data-cloud/consuming/wcf.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/data-cloud/consuming/wcf.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @Fwallberg 

It looks like you're using VS2015?

I'd try again in VS2017, or better still, VS2019.
