### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by HankiDesign** [MicrosoftDocs/xamarin-docs#1758]
Two external links (Introducing Ice Cream Sandwich and Android 4.0 Platform) in the Related Links section are broken. It's worth to notice that the Hello Tabs ICS link is also broken but I've fixed it and sent a pull request (#1757).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bcfd658c-6687-db1f-6b72-1dfbd0b8d8b8
* Version Independent ID: e2f8272d-9a5c-bfce-5d0e-a72f8ddf1160
* Content: [ActionBar - Xamarin](https://docs.microsoft.com/en-us/xamarin/android/user-interface/controls/action-bar)
* Content Source: [docs/android/user-interface/controls/action-bar.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/android/user-interface/controls/action-bar.md)
* Product: **xamarin**
* Technology: **xamarin-android**
* GitHub Login: @conceptdev
* Microsoft Alias: **crdun**

**Comment by conceptdev** [comment]
Thanks for the heads-up, sorry it took a while to action.
