### ISSUE TITLE
BrowserLaunchOptions / BrowserTitleMode not inside Xamarin.Essentials

### ISSUE THREAD

**Issue by jordan-hewitt** [MicrosoftDocs/xamarin-docs#1759]
Under the customization part of this page, there are BrowserLaunchOptions supplied as the second parameter to open the browser.  I copied and pasted this code into a new Xamarin.Forms project and am using Xamarin.Essentials inside the page I want to open a browser.  The Browser is found inside of Xamarin.Essentials, but both the BrowserLaunchOptions and BrowserTitleMode are not found within the namespace.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0e1cc45d-67d0-81bf-918f-85da4c143c93
* Version Independent ID: 9143201f-a3a5-d283-ba8a-e84c471e9a0b
* Content: [Xamarin.Essentials Open Browser - Xamarin](https://docs.microsoft.com/en-us/xamarin/essentials/open-browser?tabs=ios)
* Content Source: [docs/essentials/open-browser.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/essentials/open-browser.md)
* Product: **xamarin**
* Technology: **xamarin-essentials**
* GitHub Login: @jamesmontemagno
* Microsoft Alias: **jamont**

**Comment by jamesmontemagno** [comment]
What version of the library are you using? This was added in 1.1.0

**Comment by jordan-hewitt** [comment]
I was using 1.0.1.  My bad, all is well with 1.1.0 :).  Thanks, James.

**Comment by chinni-nag** [comment]
@jamesmontemagno  Can i send any text while opening the browser?
Please let me know. Thanks.
