### ISSUE TITLE
Do not advise users to handle password expiration

### ISSUE THREAD

**Issue by bgavrilMS** [MicrosoftDocs/xamarin-docs#1762]
I understand this is for demo purposes, but maybe you want to say that Microsoft does not advise users to handle authentication on their own, because it is unsecure. Instead, they should use modern auth (OAuth2), for example Azure Active Directory. This takes care of the forgot password scenario.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0e1cc45d-67d0-81bf-918f-85da4c143c93
* Version Independent ID: 9143201f-a3a5-d283-ba8a-e84c471e9a0b
* Content: [Xamarin.Essentials Open Browser - Xamarin](https://docs.microsoft.com/en-us/xamarin/essentials/open-browser?tabs=ios#feedback)
* Content Source: [docs/essentials/open-browser.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/essentials/open-browser.md)
* Product: **xamarin**
* Technology: **xamarin-essentials**
* GitHub Login: @jamesmontemagno
* Microsoft Alias: **jamont**

**Comment by jamesmontemagno** [comment]
Was this for: https://docs.microsoft.com/en-us/xamarin/essentials/open-browser ?

**Comment by bgavrilMS** [comment]
Yes

**Comment by jamesmontemagno** [comment]
I guess I don't understand the suggestion too much as we don't really talk about anything here on that, it is just about how to launch a browser externally.... can you expand more.

**Comment by bgavrilMS** [comment]
The Identity division is trying to convince developers to not touch passwords, because handling passwords is generally insecure. If you use an OAuth2 service (e.g. AAD, Google etc.), then logging in and password expiration is handled securely, including password expired scenarios.
