### ISSUE TITLE
"Important" is out of date

### ISSUE THREAD

**Issue by CennoxX** [MicrosoftDocs/xamarin-docs#1763]
The [!IMPORTANT] part is out of date. The currently up-to-date information can be found here under important: https://docs.microsoft.com/en-us/xamarin/ios/deploy-test/app-distribution/app-store-distribution/index

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 383fce08-fe66-8a22-980f-18751b1d028f
* Version Independent ID: 7a96f3a8-272a-4f0d-352f-efbb62de375b
* Content: [Xamarin.iOS App Distribution Overview - Xamarin](https://docs.microsoft.com/en-us/xamarin/ios/deploy-test/app-distribution/index#feedback)
* Content Source: [docs/ios/deploy-test/app-distribution/index.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/ios/deploy-test/app-distribution/index.md)
* Product: **xamarin**
* Technology: **xamarin-ios**
* GitHub Login: @lobrien
* Microsoft Alias: **laobri**

**Comment by conceptdev** [comment]
Thanks for letting us know, and suggesting the fix! Updating the doc now.
