### ISSUE TITLE
Documentation of DependencyService does not describe use of DependencyService<T>.Resolve 

### ISSUE THREAD

**Issue by johnshardman** [MicrosoftDocs/xamarin-docs#1765]
Documentation of DependencyService does not describe use of DependencyService<T>.Resolve  in such a way that the reader can distinguish between the Get and Resolve methods.

See https://docs.microsoft.com/en-us/dotnet/api/xamarin.forms.dependencyservice?view=xamarin-forms where the description of Resolve is inadequate. It needs to be made clearer to distinguish between Get and Resolve.

Also see:
https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/dependency-service/introduction
https://docs.microsoft.com/en-us/dotnet/api/xamarin.forms.dependencyservice.resolve?view=xamarin-forms

From a very quick look at the XF source code, I believe that using Resolve instead of Get allows the user to implement his/her own method for performing the resolve and have that called by the Resolve method. Nowhere in the documentation have I found anything that offers that explanation, or anything close to it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6e9eecf7-0edb-5b24-964c-a1ae2e7556ba
* Version Independent ID: 8f9243b4-0f7c-6aac-39e2-913173ea472a
* Content: [Introduction to DependencyService - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/dependency-service/introduction#feedback)
* Content Source: [docs/xamarin-forms/app-fundamentals/dependency-service/introduction.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/app-fundamentals/dependency-service/introduction.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @johnshardman 

You're right - `Get` resolves the type and creates it using `Activator.CreateInstance`. `Resolve` will use a dependency resolution method specified by you, or will fallback to using `Get` if one isn't specified. You can find out how to inject your own dependency resolution method at https://docs.microsoft.com/xamarin/xamarin-forms/internals/dependency-resolution

I'm starting a refresh of the dependency service docs today, so I'll make sure that this is mentioned. I'm expecting the refreshed docs to go live next week.
