### ISSUE TITLE
hyperlink not working

### ISSUE THREAD

**Issue by caseybeauchamp** [MicrosoftDocs/xamarin-docs#1766]
When clicking the MapsSample hyperlink I get redirected to the Xamarin Microsoft Docs page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 732de335-2b07-a3f1-dad1-88bf6c77b80a
* Version Independent ID: a0979276-6fb0-fede-805b-ad7cc80a6d4d
* Content: [Xamarin.Forms Map - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/map#feedback)
* Content Source: [docs/xamarin-forms/user-interface/map.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/map.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @caseybeauchamp 

This has now been fixed.
