### ISSUE TITLE
 iOS Simulator on Windows doc link 403s

### ISSUE THREAD

**Issue by breyed** [MicrosoftDocs/xamarin-docs#1767]
On the [Remoted iOS Simulator for Windows release notes](https://docs.microsoft.com/en-us/xamarin/tools/ios-simulator/release-notes/?context=xamarin/tools), the link at the bottom of the page, [Get started with the remoted iOS Simulator on Windows](https://review.docs.microsoft.com/xamarin/tools/ios-simulator/), leads to a 403 Forbidden error when I follow it.

**Comment by davidbritch** [comment]
Hi @breyed 

I've fixed this in a PR in the appropriate repo, that will go live next week. The quick fix, for yourself, is to remove "review." from the URL.
