### ISSUE TITLE
NoteDatabase.cs methods

### ISSUE THREAD

**Issue by josh658** [MicrosoftDocs/xamarin-docs#1768]
I was having trouble with the methods in NoteDatabase.cs (getNotesasync, save, delete...) this was the error I was getting "Inconsistent accessibility: return type 'Task&lt;Note&gt;' is less accessible than method 'NoteDatabase.GetNoteAsync(int)'" so in my research I found that I should change the method types from 'public' to 'internal' and it solved the problem. All this to ask if I might have messed something up in another section or this is a new standard? thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5ce30880-c4f0-78f7-1ee0-6507e378201e
* Version Independent ID: a6ad2818-c0d2-e3ef-1262-e143d49cc348
* Content: [Store data in a local SQLite.NET database - Xamarin](https://docs.microsoft.com/en-us/xamarin/get-started/quickstarts/database?pivots=windows)
* Content Source: [docs/get-started/quickstarts/database.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/get-started/quickstarts/database.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @josh658 

You shouldn't need to change the accessibility of the methods. I recommend downloading the sample application, and seeing if there's a difference to your code.

**Comment by mcalexster** [comment]
Hi @josh658, check that your Note class is declared public:
`public class Note { ... }`
