### ISSUE TITLE
The plist instructions don't work in iPhone XR

### ISSUE THREAD

**Issue by johnwmcintosh** [MicrosoftDocs/xamarin-docs#1769]
The instructions work fine for iPhone 8 and iPad, but not XR. Can you update this for XR?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2aa5518d-4a85-6039-6828-f1011b7f657d
* Version Independent ID: 2c62928f-5089-de93-ab11-5032015c430e
* Content: [Adding iOS-specific Formatting - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/platform/ios/formatting)
* Content Source: [docs/xamarin-forms/platform/ios/formatting.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/platform/ios/formatting.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @johnwmcintosh 

I just tried the sample, which is linked to from the doc, and the Info.plist entries described in the doc set the status bar to white in both the iPhone X and iPhone XR simulators:

![Screenshot 2019-06-07 at 12 46 57 (2)](https://user-images.githubusercontent.com/8092460/59102030-c516a600-8922-11e9-898d-6984750014cf.png)
