### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by mac10688** [MicrosoftDocs/xamarin-docs#177]
"a Progress Bar should be used any time your app is executing a long running task of a know duration."

Should probably be "task of an unknown duration"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 71d3e190-977e-2f33-49d8-6cba5afce9c4
* Version Independent ID: 0e0a45e7-f3a1-fb52-d17d-c9386d14ce14
* Content: [Working with Progress Indicators - Xamarin](https://docs.microsoft.com/en-us/xamarin/ios/tvos/user-interface/progress-indicators?tabs=vsmac)
* Content Source: [docs/ios/tvos/user-interface/progress-indicators.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/ios/tvos/user-interface/progress-indicators.md)
* Service: **unspecified**
* GitHub Login: @bradumbaugh
* Microsoft Alias: **brumbaug**

**Comment by bradumbaugh** [comment]
Hi @mac10688, I think this doc is correct - progress bars are actually best-suited for tasks where the duration is known or can be calculated. For tasks with unknown duration, an activity indicator is best.

**Comment by mac10688** [comment]
@bradumbaugh you are right, my bad. But there is a very small typo on that. "Again, a Progress Bar should be used any time your app is executing a long running task of a know duration."

know should be known. 

I appreciate the quick feedback. You guys are on it! I'm very impressed.

**Comment by bradumbaugh** [comment]
@mac10688 Ah, you're right - thanks! I'll fix that. Thanks for the kind words, too. We're grateful for contributions from the community!

**Comment by bradumbaugh** [comment]
@mac10688 I submitted a fix for this (and some other things in the same doc). Should be published soon. Thanks again for the feedback!
