### ISSUE TITLE
FindViewById Issue

### ISSUE THREAD

**Issue by CelloH3r0** [MicrosoftDocs/xamarin-docs#1770]
I am having issues with this code: 
    view.FindViewById&lt;TextView&gt;(Resource.Id.textView1).Text = item.ColorName;
&
    SetContentView(Resource.Layout.activity_main);
    listView = FindViewById&lt;ListView&gt;(Resource.Id.myListView);

This is the error that I get:
     CS0117	'Resource.Id' does not contain a definition for 'myListView'	DesignerWalkthrough	 
    C:\Users\lucas.DYNBUS\Desktop\Practice2\DesignerWalkthrough\DesignerWalkthrough\MainActivity.cs	25	Active
Is there any way to get around this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 927aa51c-a373-2e12-6208-4f6a9dd370d2
* Version Independent ID: 3a1c72c3-f0a8-e330-0c71-dd4e2a3258bb
* Content: [Using the Xamarin.Android Designer - Xamarin](https://docs.microsoft.com/en-us/xamarin/android/user-interface/android-designer/designer-walkthrough?tabs=windows#feedback)
* Content Source: [docs/android/user-interface/android-designer/designer-walkthrough.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/android/user-interface/android-designer/designer-walkthrough.md)
* Product: **xamarin**
* Technology: **xamarin-android**
* GitHub Login: @conceptdev
* Microsoft Alias: **crdun**

**Comment by JonDouglas** [comment]
When you create a new `View` within XML, you need to provide an identifier. To do this, you need to use a special syntax of `@+id/myListView`. The @ sign means to reference an ID, the + sign means to create a new resource if it doesn't exist.
