### ISSUE TITLE
Passing some values to an IntentService

### ISSUE THREAD

**Issue by frankodoom** [MicrosoftDocs/xamarin-docs#1771]
// This is just one example of passing some values to an IntentService via the Intent:
downloadIntent.PutExtra("file_to_download", "http://www.somewhere.com/file/to/download.zip");

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d28665cc-a195-5da8-4d78-1b77611307c2
* Version Independent ID: 4718bda8-aae3-dcef-d3bc-930ac987b2f0
* Content: [Intent Services in Xamarin.Android - Xamarin](https://docs.microsoft.com/en-us/xamarin/android/app-fundamentals/services/creating-a-service/intent-services#feedback)
* Content Source: [docs/android/app-fundamentals/services/creating-a-service/intent-services.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/android/app-fundamentals/services/creating-a-service/intent-services.md)
* Product: **xamarin**
* Technology: **xamarin-android**
* GitHub Login: @conceptdev
* Microsoft Alias: **crdun**

**Comment by conceptdev** [comment]
Thanks for the correction @frankodoom

**Comment by frankodoom** [comment]
Now it reads downloadIntent.PutPutExtra... instead of downloadIntent.PutExtra

**Comment by conceptdev** [comment]
Sorry about that - I clearly rushed the previous 'fix'. I just pushed another change, fixing it properly this itme.
