### ISSUE TITLE
Not working on Xamarin.Forms version 4.0.0.482894

### ISSUE THREAD

**Issue by haydenhancock** [MicrosoftDocs/xamarin-docs#1775]
This doesn't seem to be working on Xamarin.Forms version 4.0.0.482894 targeting the iOS 12.2 SDK.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 094f80f2-7fc1-d4cb-c20f-f6044c108b32
* Version Independent ID: 889aa099-7eb5-d60d-be27-ced081fa8fe8
* Content: [NavigationPage Bar Separator on iOS - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/platform/ios/navigation-bar-separator#feedback)
* Content Source: [docs/xamarin-forms/platform/ios/navigation-bar-separator.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/platform/ios/navigation-bar-separator.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @haydenhancock 

I just tried this with Xamarin.Forms v4.0.0.425677 and v4.0.0.482894, with the iOS 12.2 SDK, and it worked fine in both cases (no navigation bar separator above the `SearchBar`).
