### ISSUE TITLE
Mixing win/mac terms

### ISSUE THREAD

**Issue by mcalexster** [MicrosoftDocs/xamarin-docs#1776]
A couple cosmetic issues:
In "Visual Studio for Mac"
Step 3 and Step 4 refer to the 'Solution Explorer' instead of the 'Solution Pad'

In "Visual Studio 2019"
Step 4 refers to the 'Solution Pad' instead of the 'Solution Explorer'

**Comment by davidbritch** [comment]
Hi @mcalexster 

Which doc are you referring to?

**Comment by mcalexster** [comment]
Hi @davidbritch 
My apologies, I thought the metainfo was sent along with the 'send feedback' link.

Page in question is:  [https://docs.microsoft.com/en-us/xamarin/get-started/quickstarts/styling](https://docs.microsoft.com/en-us/xamarin/get-started/quickstarts/styling)
the mac version uses:  ?pivots=macos
the vs2019 version uses:  ?pivots=windows

**Comment by davidbritch** [comment]
HI @mcalexster 

Thanks for pointing these out. I've just updated them in a PR, which will go live later.
