### ISSUE TITLE
The statusbar color instruction depend on NavigationPage

### ISSUE THREAD

**Issue by johnwmcintosh** [MicrosoftDocs/xamarin-docs#1778]
In addition to the plist changes, the statusbar text color is successfully changed using NavigationPage. There is no solution shown for apps that do not use NavigationPage.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2aa5518d-4a85-6039-6828-f1011b7f657d
* Version Independent ID: 2c62928f-5089-de93-ab11-5032015c430e
* Content: [Adding iOS-specific Formatting - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/platform/ios/formatting)
* Content Source: [docs/xamarin-forms/platform/ios/formatting.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/platform/ios/formatting.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @johnwmcintosh 

What are you using instead of a NavigationPage? TabbedPage? MasterDetailPage?

**Comment by davidbritch** [comment]
Closed due to lack of response.
