### ISSUE TITLE
Profiling iOS doesn't work

### ISSUE THREAD

**Issue by arivoir** [MicrosoftDocs/xamarin-docs#1779]
I'm trying to profile an iOS application in my iPad but it doesn't work. 
From inside VS4Mac I choose "Run"-&gt;"Start Profiling", the profiler opens, then I choose "Time profiler", "Next", "Starts profiling". The app opens correctly, but the profiler keeps saying "Opening var/folders/...../asdf.mlpd", and anything works, the ui keeps responsive, but stoping the session shows nothing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e9e9c055-6a8e-5e81-00c7-e57c8c912a8b
* Version Independent ID: 28ac7239-a6c2-e31e-d423-b5268fd95c65
* Content: [Xamarin Profiler - Xamarin](https://docs.microsoft.com/en-us/xamarin/tools/profiler/?tabs=macos)
* Content Source: [docs/tools/profiler/index.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/tools/profiler/index.md)
* Product: **xamarin**
* Technology: **xamarin-crossplatform**
* GitHub Login: @lobrien
* Microsoft Alias: **laobri**

**Comment by rossvernal** [comment]
I have it working with a device on the simulator but not on a physical device.

**Comment by rossvernal** [comment]
I was able to get this working by setting my architecture to ARM64, and removing "--interpreter" from the mtouch arguments

**Comment by nlykk12** [comment]
im having issues with this problem as well. Is there a solution on the way. The above suggestions doesn't seem to be working for me

**Comment by PureWeen** [comment]
Closing this out from the docs repository

If anyone is still having issues with the profiler please log your issue here
https://developercommunity.visualstudio.com/
