### ISSUE TITLE
The updated video looks good

### ISSUE THREAD

**Issue by Darlanio** [MicrosoftDocs/xamarin-docs#1780]
I have to get back when I have a fresh windows installed on a machine to try out Visual Studio 2019 on its own, without Android Studio and the Android Emulators that comes with it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b4445585-af8f-09d3-5d35-762c3aac187b
* Version Independent ID: fa9263db-60d6-eb98-eb74-842351ba5387
* Content: [Build your first Xamarin.Forms app - Xamarin](https://docs.microsoft.com/en-us/xamarin/get-started/first-app/?pivots=windows)
* Content Source: [docs/get-started/first-app/index.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/get-started/first-app/index.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @conceptdev
* Microsoft Alias: **crdun**

**Comment by conceptdev** [comment]
Thanks @Darlanio, hope it goes well!
