### ISSUE TITLE
CocoSharp not compatible with Visual Studio 2019

### ISSUE THREAD

**Issue by sanjmishra** [MicrosoftDocs/xamarin-docs#1782]
There is  no update to CocoSharp in about 4 years as shown at its GitHub Page (https://github.com/mono/CocosSharp). Is this tool dead ? if so please do either of the two below :
1. Remove this page and even GitHub page
2. Add a comment at the top of this page and the GitHub page that it is not compatible with versions of Visual Studio 2017 onwards.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8f2c5446-f22b-8a7c-b200-7ebe6545562d
* Version Independent ID: e28405f0-a191-c724-4e0b-13c6dcb4023a
* Content: [CocosSharp 2D Game Engine - Xamarin](https://docs.microsoft.com/en-us/xamarin/graphics-games/cocossharp/index#feedback)
* Content Source: [docs/graphics-games/cocossharp/index.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/graphics-games/cocossharp/index.md)
* Product: **xamarin**
* Technology: **xamarin-crossplatform**
* GitHub Login: @conceptdev
* Microsoft Alias: **crdun**

**Comment by conceptdev** [comment]
Thanks for your feedback @sanjmishra. 

1. Regarding the GitHub repo - it is an open-source project, so anyone could decide to start contributing to the code at any time.

2. This is a fair comment - I will discuss with the team how we can best communicate the status of the project and compatibility with Visual Studio in the docs.

Thanks again.

**Comment by sanjmishra** [comment]
Thanks @conceptdev . How I can help on CocoSharp ?
