### ISSUE TITLE
Consider Adding Wave Engine to the Technology Section

### ISSUE THREAD

**Issue by mzhukovs** [MicrosoftDocs/xamarin-docs#1785]
Wave Engine (https://waveengine.net/) is cross-platform, 100% free, and has a visual designer as well to generate a lot of the C# code for you. I believe they even have a Xamarin.Forms template. So might be worth giving that a shout out.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2571d13e-fcea-f675-a4f0-e2060da7620e
* Version Independent ID: 44df9698-4a68-f5e2-2998-e271d6a89e52
* Content: [Introduction to Game Development with Xamarin - Xamarin](https://docs.microsoft.com/en-us/xamarin/graphics-games/game-development/#feedback)
* Content Source: [docs/graphics-games/game-development/index.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/graphics-games/game-development/index.md)
* Product: **xamarin**
* Technology: **xamarin-crossplatform**
* GitHub Login: @conceptdev
* Microsoft Alias: **crdun**

**Comment by conceptdev** [comment]
Thanks for your feedback. I'm not familiar with Wave Engine but will follow this up internally. Generally this page is meant as an index for docs that we are hosting, so I'm not sure if this will be added or not (however, interested customers will always be able to find your comment on the site!).
