### ISSUE TITLE
Why is this synchronous?

### ISSUE THREAD

**Issue by SittenSpynne** [MicrosoftDocs/xamarin-docs#1787]
Why are the Set methods async and these are synchronous?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 99a18f7a-65fa-aac1-ceb2-50786b3f4939
* Version Independent ID: ef45fedb-3dc6-5105-d1eb-fa42cac1ab26
* Content: [SecureStorage.Remove(String) Method (Xamarin.Essentials)](https://docs.microsoft.com/en-us/dotnet/api/xamarin.essentials.securestorage.remove?view=xamarin-essentials#Xamarin_Essentials_SecureStorage_Remove_System_String_)
* Content Source: [docs/en/Xamarin.Essentials/SecureStorage.xml](https://github.com/xamarin/Essentials/blob/live/docs/en/Xamarin.Essentials/SecureStorage.xml)
* Product: **xamarin**
* Technology: **xamarin-essentials**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by jamesmontemagno** [comment]
Remove doesn't require any Tasks or Async work at at all and are completed intermediately.
