### ISSUE TITLE
Suggested improvement

### ISSUE THREAD

**Issue by noutram** [MicrosoftDocs/xamarin-docs#1792]
Re: Section 
## Platform Differences with OnPlatform

I really gained a lot from reading this page, and it prompted me to experiment and try to understand what is going on under the hood.

You start with some example code in C# at the start.  This has a conditional statement which (presumably) does not map directly into XAML, hence the OnPlatform generic class.

Then you begin to build XAML to perform the same logical operation. However, this does not align with the C code leaving the reader to wonder how they relate. 

So here is my suggestion: When you get to the most expanded example (copied in below), it would be good to show the equivalent C# code that maps directly to this. Key to this seems to be implicit type conversion of the generic class OnPlatform<Thickness> to type Thickness? 

The code I wrote to try and mirror what is specified in XAML is shown below. I also use a padding of 40 (20 still seems to obscure the content on the iOS Simulator)

````
            On iOSPlatform = new On
            {
                Value = "0, 40, 0, 0",
                Platform = new List<string>
                {
                    "iOS"
                }
            };

            On otherPlatforms = new On
            {
                Value = "0, 0, 0, 0",
                Platform = new List<string>
                {
                    "Android","UWP"
                }
            };

            OnPlatform<Thickness> pd = new OnPlatform<Thickness>();
            pd.Platforms.Add(iOSPlatform);
            pd.Platforms.Add(otherPlatforms);

            //Set the Padding property of this ContentPage to the Thickness for the running platform
            //The conditional run-time test is encapsulated inside the OnPlatform class
            //Note the C# implicit type conversion from OnPlatform<Thickness> to Thickness
            this.Padding = pd; 
````
The (closest) corresponding XAML is here:
````
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="...">

    <ContentPage.Padding>
        <OnPlatform x:TypeArguments="Thickness">
            <OnPlatform.Platforms>
                <On Platform="iOS" Value="0, 20, 0, 0" />
                <On Platform="Android" Value="0, 0, 0, 0" />
                <On Platform="UWP" Value="0, 0, 0, 0" />
            </OnPlatform.Platforms>
        </OnPlatform>
    </ContentPage.Padding>
  ...
</ContentPage>
````

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e80791df-0605-587f-74cd-ebc4c9fd0f74
* Version Independent ID: 76736d2a-f450-4607-55b9-e7f547c0c775
* Content: [Part 2. Essential XAML Syntax - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/xaml/xaml-basics/essential-xaml-syntax)
* Content Source: [docs/xamarin-forms/xaml/xaml-basics/essential-xaml-syntax.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/xaml/xaml-basics/essential-xaml-syntax.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @noutram 

Thanks for the feedback. While you can use the `OnPlatform` and `On` classes from C#, it's not recommended from a code readability perspective. Our recommendation is that the `OnPlatform` and `On` classes should be used for the XAML equivalent of code such as:

```
double top;
switch (Device.RuntimePlatform)
{
  case Device.iOS:
    top = 20;
    break;
  case Device.Android:
  case Device.UWP:
  default:
    top = 0;
    break;
}
layout.Margin = new Thickness(5, top, 5, 0);
```

With that said, I'll add a note to the doc along those lines.

Also, in XAML I'd recommend using the `OnPlatform` markup extension, instead of the `OnPlatform` class. It results in less verbose XAML. More info at https://docs.microsoft.com/xamarin/xamarin-forms/xaml/markup-extensions/consuming#onplatform-markup-extension

Paddings of 20 used to be fine, until the iPhone X came along.

**Comment by noutram** [comment]
Hi


I think this is just me trying to look at the XAML and “map it to code” (more my comfort zone) – which I seemed to manage, but you’ve kindly clarified.

As a general point coming at this from another platform, sometimes it’s hard to see consistent patterns in XAML, probably as I’m wondering “what does that do under the hood?”. What objects are being instantiated and when etc… Some people might just read and accept, so it’s possibly just me being new to this.

Good to know about the padding – that had me wondering.

Nick

**Comment by davidbritch** [comment]
Fixed in a PR that will go live later.
