### ISSUE TITLE
Can Xamarin or .NET be run in CLI?

### ISSUE THREAD

**Issue by mkstarr** [MicrosoftDocs/xamarin-docs#1793]
This was a little biased towards GUI-users. Some people still use .NET on the CLI thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 483b01c5-75b5-a35b-c90c-c564535416f1
* Version Independent ID: dc8b1e89-e8f9-0e50-5d4d-248ccdab9c91
* Content: [Use .NET Standard Libraries to Share Code - Xamarin](https://docs.microsoft.com/en-us/xamarin/cross-platform/app-fundamentals/net-standard?tabs=windows)
* Content Source: [docs/cross-platform/app-fundamentals/net-standard.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/cross-platform/app-fundamentals/net-standard.md)
* Product: **xamarin**
* Technology: **xamarin-crossplatform**
* GitHub Login: @conceptdev
* Microsoft Alias: **crdun**

**Comment by conceptdev** [comment]
.NET can certainly be fun from a CLI - see this page on [Get started with .NET Core on Windows/Linux/macOS using the command line](https://docs.microsoft.com/en-us/dotnet/core/tutorials/using-with-xplat-cli).

Xamarin development works best in Visual Studio - the Mobile Development with .NET workload brings a lot of functionality to configure native compilation support (required for iOS & Android) as well as deployment and debugging for devices and simulators.
