### ISSUE TITLE
Outdated sample

### ISSUE THREAD

**Issue by robinmanuelthiel** [MicrosoftDocs/xamarin-docs#1794]
The sample and the Tutorial are using the `Microsoft.Identity.Client` library of version `2.7.1`.  As I am writing this, the current version is `4.0.0`. Many functions and methods changed. Can we please have an updated sample using the latest version of the library?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 11f5b457-d99a-06d4-d203-f9eeaa27e0d9
* Version Independent ID: b23b3a5d-b63b-dfe1-bb46-94f57c907be5
* Content: [Authenticate Users with Azure Active Directory B2C - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/data-cloud/authentication/azure-ad-b2c)
* Content Source: [docs/xamarin-forms/data-cloud/authentication/azure-ad-b2c.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/data-cloud/authentication/azure-ad-b2c.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @robinmanuelthiel 

This doc/sample was updated in April, when the latest version of Microsoft.Identity.Client was 2.7.1. Since then v2.7.1 has been superseded by v3 and v4.

In answer to your question: yes, it's going to get updated.

**Comment by robinmanuelthiel** [comment]
Nice, thanks!

**Comment by profexorgeek** [comment]
Hi @robinmanuelthiel and @davidbritch
The updates to the sample and doc are live! You can get started here:
https://docs.microsoft.com/en-us/xamarin/xamarin-forms/data-cloud/authentication/azure-ad-b2c

MSAL versions 3 and 4 made some critical changes that clean up the API. The main changes you'll see in the sample are updating how MSAL's `IPublicClientApplication` is constructed and how auth tokens are requested. Prior to v3, MSAL used overloaded methods with lots of arguments, which could be confusing and hard to read. The new version utilizes `With` clauses that allow you to inject the specific arguments you need.

**Comment by profexorgeek** [comment]
Hi @FreakyAli,
Do you mind opening a new issue to track this? Tag me and I'll assign the new issue to myself and do some research. If you can be specific about what classes you're having trouble with that will be helpful!
