### ISSUE TITLE
Something not explicitly clear

### ISSUE THREAD

**Issue by noutram** [MicrosoftDocs/xamarin-docs#1795]
Up to the section Bindings and Collections, a BindingContext has always been set. For this section, there is suddenly no explicit reference to the BindingContext. Presumably that's encapsulated in the ItemsSource property of ListView? A minor point, and maybe I've misunderstood, so might be worth clarification.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 969d1fbd-aeab-0c4f-8e1b-f7f3c139fd78
* Version Independent ID: 6ea369b2-0654-27ac-5911-aaf77e1c1495
* Content: [Part 4. Data Binding Basics - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/xaml/xaml-basics/data-binding-basics#bindings-and-collections)
* Content Source: [docs/xamarin-forms/xaml/xaml-basics/data-binding-basics.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/xaml/xaml-basics/data-binding-basics.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @noutram 

You are correct. Thanks for the suggestion. I'll make an update.

As an FYI, the guide your are reading is only a basic guide to data binding in XAML. A more detailed guide can be found at: https://docs.microsoft.com/xamarin/xamarin-forms/app-fundamentals/data-binding/

**Comment by noutram** [comment]
Thanks for the response and the suggestion. I'll certainly take a deeper dive on this topic. 
Just to explain my perspective, I'm in the process of writing a course on Xamarin for our second year undergrads, so I'm trying to work through your docs, looking at them from their perspective (as much as I can). Very impressed so far.

**Comment by davidbritch** [comment]
Fixed in a PR that will go live later.
