### ISSUE TITLE
When does a view gets rendered?

### ISSUE THREAD

**Issue by dinobu** [MicrosoftDocs/xamarin-docs#1796]
This article explains renderers and their relationship with platform specific controls but when is actual rendering process occuring?  How can it be captured, in what event?  Does a view has to be visible in order to say it has been rendered? etc

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e3b172d5-2dc1-88e7-ca23-96e87ae24a42
* Version Independent ID: 1ca93300-738f-4af7-b47c-0e170b7205a4
* Content: [Implementing a View - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/custom-renderer/view)
* Content Source: [docs/xamarin-forms/app-fundamentals/custom-renderer/view.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/app-fundamentals/custom-renderer/view.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @dinobu 

If I'm understanding you correctly, it sounds like you're essentially asking for a doc that explains the Xamarin.Forms layout cycle. I've created an issue in our backlog for this.

Meanwhile, you can find an explanation of it in Chapter 26 of "Creating Mobile Apps with Xamarin.Forms". The following link has an overview of chapter 26, and a download link for the full chapter: https://docs.microsoft.com/xamarin/xamarin-forms/creating-mobile-apps-xamarin-forms/summaries/chapter26

**Comment by dinobu** [comment]
> Hi @dinobu
> 
> If I'm understanding you correctly, it sounds like you're essentially asking for a doc that explains the Xamarin.Forms layout cycle. I've created an issue in our backlog for this.
> 
> Meanwhile, you can find an explanation of it in Chapter 26 of "Creating Mobile Apps with Xamarin.Forms". The following link has an overview of chapter 26, and a download link for the full chapter: https://docs.microsoft.com/xamarin/xamarin-forms/creating-mobile-apps-xamarin-forms/summaries/chapter26

I am trying to find out when my for example Entry view gets rendered, how can I access that event, how to capture it.  Basically, like in Android, where I can find out exactly when a view is rendered, visible, etc but in Xamarin.Forms

**Comment by davidbritch** [comment]
@dinobu Understood.

There's a feature, currently scheduled for Forms 4.2, that's going to add `BeforeAppearing`, `Loaded` (raised when a view has appeared on a page), and `Unloaded` events to the `VisualElement` class. The names of these events may change, but you'll be able to use them to track views as they appear on a page from Xamarin.Forms.

Until then, it's a case of having to use platform events to get the notifications you need.
