### ISSUE TITLE
Incomplete documentation for Android SDK Location

### ISSUE THREAD

**Issue by coolsambit** [MicrosoftDocs/xamarin-docs#180]
I installed the Android SDK to C:\Program Files\Android\Android Studio\
Restarted VS 2017(Community Edition), Windows, in-installed, reinstalled Android Studio.
No matter what I do the red asterisk mark would not go.
Problem is with SDK installation, with Visual studio, Windows Home edition or my bad times not sure.
I have spent know 4 hours trying to fix the issue.
Finally came across another documentation that might be addressing my problem:
https://docs.elementscompiler.com/VisualStudio/Setup/AndroidSDK/
Not sure if this would solve the problem but its worth trying.

 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5f0a639d-0482-2f3b-839e-a849cb91ee53
* Version Independent ID: cbb04044-0a5f-0403-282b-32a6032435c4
* Content: [Where can I set my Android SDK locations? - Xamarin](https://docs.microsoft.com/en-us/xamarin/android/troubleshooting/questions/android-sdk-location?tabs=vswin)
* Content Source: [docs/android/troubleshooting/questions/android-sdk-location.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/android/troubleshooting/questions/android-sdk-location.md)
* Service: **unspecified**
* GitHub Login: @mgmclemore
* Microsoft Alias: **mamcle**

**Comment by topgenorth** [comment]
Thanks for letting us know. This does seem very related to an issue I filed with DeveloperCommunity: [SDK manager doesn't detect Android SDK](https://developercommunity.visualstudio.com/content/problem/143975/sdk-manager-doesnt-detect-android-sdk.html)

I see that this issue has been resolved. Hopefully this latest release of the SDK Manager fixes the problem.
