### ISSUE TITLE
Higher requirements for NSLocationWhenInUseUsageDescription 

### ISSUE THREAD

**Issue by Inrego** [MicrosoftDocs/xamarin-docs#1800]
When uploading app to App Store, Apple did not accept the simple Usage Description provided here. Maybe it would be a good idea to add a note, that people should write something about why they are actually requesting position.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f0acf3fa-b705-f0cc-b676-eeca60176dfa
* Version Independent ID: 1788a5d5-a3cb-15c8-927c-b6a24810245a
* Content: [Xamarin.Essentials: Geolocation - Xamarin](https://docs.microsoft.com/en-us/xamarin/essentials/geolocation?tabs=ios#feedback)
* Content Source: [docs/essentials/geolocation.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/essentials/geolocation.md)
* Product: **xamarin**
* Technology: **xamarin-essentials**
* GitHub Login: @jamesmontemagno
* Microsoft Alias: **jamont**

**Comment by jamesmontemagno** [comment]
See: https://github.com/MicrosoftDocs/xamarin-docs/pull/1802
