### ISSUE TITLE
Which image formats are supported?

### ISSUE THREAD

**Issue by dcarapic** [MicrosoftDocs/xamarin-docs#1801]
There is no mention in the document which image formats are actually supported by XamarinForms.
It would be nice to have that information here.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7eeb0e65-143b-0f5e-a8fb-c75309689338
* Version Independent ID: 6b984264-a950-4310-483f-99f908b0a8b0
* Content: [Images in Xamarin.Forms - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/images?tabs=windows#feedback)
* Content Source: [docs/xamarin-forms/user-interface/images.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/images.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @dcarapic 

Thanks for the suggestion. I've created an issue in our backlog to add the image formats to the doc, when we refresh it.
