### ISSUE TITLE
Available tab properties are not well documented

### ISSUE THREAD

**Issue by rscholey** [MicrosoftDocs/xamarin-docs#1803]
It's very confusing right now which properties are available to be set and how to set them.  For example: SelectedTabColorProperty, UnselectedTabColorProperty and a selection of others

Could the available properties be documented so as to be clear to everyone. Even now I'm not sure what's available as there seem to be numerous bugs and commits trying to fix problems with these properties.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ef7242a0-d46e-19ea-e22d-f327dcc9b3e9
* Version Independent ID: f050be8e-9413-19e7-5799-90a55c4e5bfb
* Content: [Xamarin.Forms Shell Layout - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/shell/tabs)
* Content Source: [docs/xamarin-forms/app-fundamentals/shell/tabs.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/app-fundamentals/shell/tabs.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @rscholey 

The `Tab` class properties are listed at https://docs.microsoft.com/xamarin/xamarin-forms/app-fundamentals/shell/tabs#tab-class and in the [API doc](https://docs.microsoft.com/dotnet/api/xamarin.forms.shellsection?view=xamarin-forms#properties).

However, the `Shell` class also defines attached properties that affect tabs. These are documented at https://docs.microsoft.com/xamarin/xamarin-forms/app-fundamentals/shell/tabs#tab-appearance
