### ISSUE TITLE
Xamarin.LiveReload

### ISSUE THREAD

**Issue by Pinox** [MicrosoftDocs/xamarin-docs#1804]
Any chance you guys can update the existing installer for use in VS2019. I use the functionality of LiveReload extensively but some Reactive libs needs VS2019.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e40394ca-9a55-d9b5-d427-7c2a2c00cfc8
* Version Independent ID: 5a5c17e2-a683-88f6-07a9-2002e814d54c
* Content: [Xamarin Live Reload (Preview) - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/xaml/live-reload#feedback)
* Content Source: [docs/xamarin-forms/xaml/live-reload.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/xaml/live-reload.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @pierceboggan
* Microsoft Alias: **piboggan**

**Comment by conceptdev** [comment]
The Live Reload preview has ended. 

Try the new [Hot Reload](https://docs.microsoft.com/xamarin/xamarin-forms/xaml/hot-reload) feature for Xamarin.Forms.
