### ISSUE TITLE
Link points to retired document

### ISSUE THREAD

**Issue by GerryOnGithub** [MicrosoftDocs/xamarin-docs#1805]
The link "Local and Remote Notification Programming Guide" points to a retired document

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a2802ab3-bbf8-af5c-b5c6-be6678563dd1
* Version Independent ID: c7a46e51-3305-6750-c3e2-bcfd9aead6d7
* Content: [User Notifications Framework in Xamarin.iOS - Xamarin](https://docs.microsoft.com/en-us/xamarin/ios/platform/user-notifications/index#feedback)
* Content Source: [docs/ios/platform/user-notifications/index.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/ios/platform/user-notifications/index.md)
* Product: **xamarin**
* Technology: **xamarin-ios**
* GitHub Login: @lobrien
* Microsoft Alias: **laobri**

**Comment by conceptdev** [comment]
Thanks for letting us know, updating to the suggested link https://developer.apple.com/documentation/usernotifications
