### ISSUE TITLE
very usefull

### ISSUE THREAD

**Issue by aghajani59** [MicrosoftDocs/xamarin-docs#1807]
Very nice document.
Very useful for me.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ae9b6d88-c6c9-0411-fb06-1c20d3dc0bd7
* Version Independent ID: 26314e11-e241-8f0c-2d84-23520ca9be7c
* Content: [WebView Mixed Content on Android - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/platform/android/webview-mixed-content#feedback)
* Content Source: [docs/xamarin-forms/platform/android/webview-mixed-content.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/platform/android/webview-mixed-content.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Thanks @aghajani59
