### ISSUE TITLE
CaSe MaTtErs

### ISSUE THREAD

**Issue by brokenjavagit** [MicrosoftDocs/xamarin-docs#181]
So when copying and pasting code try to remember that phoneword != Phoneword.  There are tools to help you with this simple mistake, I can't remember what they are but in step 3 hit that shift key will ya.  Or maybe throw an exception like a custom exception that make sense to silly xaml illiterate people like me XD.
Code CS0103: The name CS0103'InitializeComponent' does not exist in the current context

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2de3e72c-8948-4dd5-e37f-9cf81e62c127
* Version Independent ID: 7b7c5c7f-4102-8e91-fbe6-7d21fcc8f5be
* Content: [Xamarin.Forms Quickstart - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/get-started/hello-xamarin-forms/quickstart?tabs=vswin)
* Content Source: [docs/xamarin-forms/get-started/hello-xamarin-forms/quickstart.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/get-started/hello-xamarin-forms/quickstart.md)
* Service: **unspecified**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by conceptdev** [comment]
Hi @brokenjavagit, can you help me out with exactly what in the doc lead you astray? I don't see any lowercase `phoneword` in there. Thanks!

**Comment by brokenjavagit** [comment]
Nothing in this document led me astray.  I'm just an idiot and named the project incorrectly.  But the generic error: "Code CS0103: The name CS0103'InitializeComponent' does not exist in the current context" was confusing and not particularly helpful.  Searching on the internet for a solution to this error was also not helpful, everything i looked at pointed to, or accused the Xamarin dev team or Xamarin itself of being unreliable/broken/bug riden.  Perhaps this will be helpful to someone else with this specific issue.

**Comment by conceptdev** [comment]
Understood, thanks for the additional information.

You can provide product feedback at the [Developer Community site](https://developercommunity.visualstudio.com) - including requesting and voting on new features.
