### ISSUE TITLE
Settings Page not shown due to lack of reasonable way of implementing on Xamarin.Forms?

### ISSUE THREAD

**Issue by dansoutar-ptx** [MicrosoftDocs/xamarin-docs#1810]
This docs page is fine, but I noticed there's no mention of what the code for a settings page would look like when embedded inside a TabbedPage. A natural way of implementing one would be a MasterDetail, yet that cannot be used since that needs to be the root page (why, I don't know).

It would be nice if Microsoft's docs could at least show how a *hierarchal* settings page (the majority of non-trivial ones are) could be embedded in a TabbedPage. It's a common pattern and in any case a very useful one. It's unfortunate that this page doesn't address this - I suspect because there is no nice way of doing it (currently) in Xamarin.Forms. If there isn't, a mention of this would be helpful rather than having people go off and try to find an answer that isn't there.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0c81c589-e81e-d98c-9656-695a3520a12d
* Version Independent ID: c235f6f9-47ce-15f3-b4da-cb12e219df92
* Content: [Xamarin.Forms Tabbed Page - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/navigation/tabbed-page#feedback)
* Content Source: [docs/xamarin-forms/app-fundamentals/navigation/tabbed-page.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/app-fundamentals/navigation/tabbed-page.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @dansoutar-ptx 

I'm struggling to understand your issue. You can embed ContentPages in a TabbedPage, and so you'd create your settings page as a ContentPage instance.

What am I missing here?

**Comment by davidbritch** [comment]
Closing due to lack of response.
