### ISSUE TITLE
Msal 4 version

### ISSUE THREAD

**Issue by copperbeardy** [MicrosoftDocs/xamarin-docs#1811]
is it possible to get a similar walkthrough using MSAL 4 trying to follow this, most of it causes error relating to an obselete or deprecated approach such as the UI parent and 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 11f5b457-d99a-06d4-d203-f9eeaa27e0d9
* Version Independent ID: b23b3a5d-b63b-dfe1-bb46-94f57c907be5
* Content: [Authenticate Users with Azure Active Directory B2C - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/data-cloud/authentication/azure-ad-b2c#feedback)
* Content Source: [docs/xamarin-forms/data-cloud/authentication/azure-ad-b2c.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/data-cloud/authentication/azure-ad-b2c.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @copperbeardy 

Yes, it will be updated.

I'm going to close this issue as it's already being tracked at #1794
