### ISSUE TITLE
C# example in "rows and columns"

### ISSUE THREAD

**Issue by donaldnp** [MicrosoftDocs/xamarin-docs#1813]
The C# example in the "rows and columns" section does NOT match the XAML example. It looks like someone just copy/pasted the last row definition and changed every instance of "row" to "column" in that line, and didn't add the 2nd column definition at all, leaving this whole page without a single example of using the "auto" property in C#.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c0902f8-eb40-4c56-958a-f13f064c8293
* Version Independent ID: 1e930440-f312-6301-d786-262b98f9ce2f
* Content: [Xamarin.Forms Grid - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/layouts/grid)
* Content Source: [docs/xamarin-forms/user-interface/layouts/grid.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/layouts/grid.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @donaldnp 

I've created a PR that fixes the C# code example, which will go live next week. However, here's an example of using GridUnitType.Auto in C#:

```
grid.ColumnDefinitions.Add(new ColumnDefinition { Width = new GridLength(1, GridUnitType.Auto) });
```

When GridUnitType.Auto is specified, the first argument to the GridLength constructor is ignored.
