### ISSUE TITLE
Android 4.1 or 5.0 required for AndroidClientHandler?

### ISSUE THREAD

**Issue by K232** [MicrosoftDocs/xamarin-docs#1817]
[Documentation](https://docs.microsoft.com/en-us/xamarin/android/app-fundamentals/http-stack?tabs=macos#alternative-configuration-options) says that AndroidClientHandler requires Android 4.1 or later, but help popup in Visual Studio for Mac Community 2019 (Version 8.1.1) says that Android 5.0 or later is required.

Which one is correct?

![AndroidClientHandler](https://user-images.githubusercontent.com/685016/60006820-73d01b80-9671-11e9-807e-75b761e6ea4e.jpg)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 969ae3fb-fa08-217b-a62f-105317ea811a
* Version Independent ID: 49deb3eb-6726-62d1-1684-6816d4b4b1cb
* Content: [HttpClient Stack and SSL/TLS Implementation Selector for Android - Xamarin](https://docs.microsoft.com/en-us/xamarin/android/app-fundamentals/http-stack?tabs=windows#choosing-a-handler)
* Content Source: [docs/android/app-fundamentals/http-stack.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/android/app-fundamentals/http-stack.md)
* Product: **xamarin**
* Technology: **xamarin-android**
* GitHub Login: @conceptdev
* Microsoft Alias: **crdun**

**Comment by JonDouglas** [comment]
This is partially correct. **Some** devices running 4.1+ support TLS 1.2, but that's because manufacturers did not follow the Android spec. The official support is for devices running 5.0+.

**Comment by JonDouglas** [comment]
Hopefully this note helps clarify some items!

https://github.com/MicrosoftDocs/xamarin-docs/pull/1846
