### ISSUE TITLE
UWP/other platforms

### ISSUE THREAD

**Issue by chrisgull** [MicrosoftDocs/xamarin-docs#1819]
Obviously when you end up on this page you care about portable code.
It would be helpful and appreciated to have this walkthrough extended to include a UWP scenario, and other platforms as well.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e40fbe03-a099-3b24-4654-162103003d6a
* Version Independent ID: 01e8c667-ed94-7054-758d-2399e879714a
* Content: [Use C/C++ libraries with Xamarin - Xamarin](https://docs.microsoft.com/en-us/xamarin/cross-platform/cpp/)
* Content Source: [docs/cross-platform/cpp/index.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/cross-platform/cpp/index.md)
* Product: **xamarin**
* Technology: **xamarin-crossplatform**
* GitHub Login: @mikeparker104
* Microsoft Alias: **miparker**

**Comment by chrisgull** [comment]
I have not tried this recipe yet (but I will over the next few days). Does anything change for VS2019?

**Comment by conceptdev** [comment]
Thanks for the feedback. Other platforms are beyond the scope of this sample.
