### ISSUE TITLE
Where is rowHeight used?

### ISSUE THREAD

**Issue by rhodesj971** [MicrosoftDocs/xamarin-docs#182]
Where is the rowHeight resource used? There's no StaticResource used for rowHeight, only BoxSize. Changing the rowHeight number for any platform doesn't do anything? Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 969d1fbd-aeab-0c4f-8e1b-f7f3c139fd78
* Version Independent ID: 6ea369b2-0654-27ac-5911-aaf77e1c1495
* Content: [Part 4. Data Binding Basics - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/xaml/xaml-basics/data-binding-basics)
* Content Source: [docs/xamarin-forms/xaml/xaml-basics/data-binding-basics.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/xaml/xaml-basics/data-binding-basics.md)
* Service: **unspecified**
* GitHub Login: @charlespetzold
* Microsoft Alias: **chape**

**Comment by conceptdev** [comment]
See the linked sample code, where the [`RowHeight="{StaticResource rowHeight}"`](https://github.com/xamarin/xamarin-forms-samples/blob/master/XamlSamples/XamlSamples/XamlSamples/ListViewDemoPage.xaml#L26) is set on the `ListView` element.

We'll update the doc to match - thanks for your feedback.
