### ISSUE TITLE
FullScreen Mode

### ISSUE THREAD

**Issue by balivo** [MicrosoftDocs/xamarin-docs#1823]
Fullscreen button not appearing at Android and iOS.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0081290c-715f-d4fa-38ca-6cfdfd65b5c0
* Version Independent ID: 8fd98837-f8b5-d341-c18c-6ca2c760973d
* Content: [Implementing a video player - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/custom-renderer/video-player/#feedback)
* Content Source: [docs/xamarin-forms/app-fundamentals/custom-renderer/video-player/index.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/app-fundamentals/custom-renderer/video-player/index.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi balivo,

I checked the sample and a full screen button appears in the top left corner on iOS. However, I agree that there's no full screen button appearing on Android. I'll add an issue to our backlog to address this.

**Comment by balivo** [comment]
@davidbritch can u attach bug link here?

**Comment by davidbritch** [comment]
@balivo It's referenced above my previous comment, but it's to our private repo.

**Comment by balivo** [comment]
Tks!

**Comment by chauhan8690** [comment]
Is it possible to display fullscreen button with custom position bar?
