### ISSUE TITLE
Windows 8 Dev Environment - Emulator no longer works

### ISSUE THREAD

**Issue by bfcrmimick** [MicrosoftDocs/xamarin-docs#1824]
Getting redirected to this page regarding the Windows Spring Creators Edition.  I have Windows 8 and cannot run 1803 at the moment.  Am I out of luck?  How to I ignore the "Performance Warning" that stop the running of the emulator?

**Comment by conceptdev** [comment]
Unfortunately this is not the place for product support - try the **Help > Report a problem** feature in Visual Studio or visit https://developercommunity.visualstudio.com/
