### ISSUE TITLE
"US" is not "2 digits"

### ISSUE THREAD

**Issue by gjuwindev** [MicrosoftDocs/xamarin-docs#1825]
the instuctions at **https://docs.microsoft.com/en-us/xamarin/android/deploy-test/signing/** ask to provide "2 digits" as "Country Code", but the sample offers us "US", which definitely is not two digits, but two letters

![image](https://user-images.githubusercontent.com/20825928/60226780-000a5a80-988d-11e9-87cc-2295cf874f78.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d22ceddd-69d4-3a5d-2947-a5abddbbd3aa
* Version Independent ID: e238051f-b809-5541-4049-f1205dd0a3a5
* Content: [Signing the Android Application Package - Xamarin](https://docs.microsoft.com/en-us/xamarin/android/deploy-test/signing/?tabs=windows)
* Content Source: [docs/android/deploy-test/signing/index.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/android/deploy-test/signing/index.md)
* Product: **xamarin**
* Technology: **xamarin-android**
* GitHub Login: @conceptdev
* Microsoft Alias: **crdun**

**Comment by conceptdev** [comment]
Thanks for your feedback @gjuwindev - the dialog is part of the Visual Studio Tools for Xamarin, so this bug (the wrong string) could be reported via Visual Studio's **Help > Report a problem** feature.

For comparison, in Visual Studio for Mac, the label contains "(2 character country code)" (shown below), which is probably what should be used on Windows too. If you are creating a key store, the input does require two characters, not digits.

![Screen Shot 2019-06-26 at 7 11 45 PM](https://user-images.githubusercontent.com/199373/60228064-44263c80-9846-11e9-84b5-da4db5b8f547.png)

**Comment by gjuwindev** [comment]
thanks :-)
