### ISSUE TITLE
Please add Xamarin.Mac explanation for adding and using custom fonts

### ISSUE THREAD

**Issue by voxoid0** [MicrosoftDocs/xamarin-docs#1827]
1238fdd7-c378-6d0d-654e-55656a70d386
https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/text/fonts

**Comment by davidbritch** [comment]
Hi @voxoid0 

Thanks for the suggestion. In the meantime, see https://forums.xamarin.com/discussion/137290/using-custom-fonts-in-xamarin-forms-inside-xamarin-mac
