### ISSUE TITLE
Proposed method PlacePhoneCall does not need to be async

### ISSUE THREAD

**Issue by thomasgalliker** [MicrosoftDocs/xamarin-docs#1828]
There is no async task awaited in PlacePhoneCall.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9f4d0869-b5c2-c17b-63d4-f325856d1a79
* Version Independent ID: a5f487c3-4e56-838f-89a9-b8fa0dc13261
* Content: [Xamarin.Essentials: Phone Dialer - Xamarin](https://docs.microsoft.com/en-us/xamarin/essentials/phone-dialer)
* Content Source: [docs/essentials/phone-dialer.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/essentials/phone-dialer.md)
* Product: **xamarin**
* Technology: **xamarin-essentials**
* GitHub Login: @jamesmontemagno
* Microsoft Alias: **jamont**

**Comment by jamesmontemagno** [comment]
Fixed here: https://github.com/MicrosoftDocs/xamarin-docs/pull/1847

Thanks for the feedback!
