### ISSUE TITLE
No UWP support of Shell

### ISSUE THREAD

**Issue by weitzhandler** [MicrosoftDocs/xamarin-docs#1829]
This fact should be jumbotroned in the docs.
To me Shell doesn't exist so long it doesn't support UWP. It's disappointing to see how Xamarin.Forms, a Microsoft product, contributes to the fading of UWP.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f64762a5-78e3-5c1e-b8b3-9572d66110f5
* Version Independent ID: bb324623-2127-a5a3-d620-ebf314dfbf1a
* Content: [Xamarin.Forms Shell - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/shell/)
* Content Source: [docs/xamarin-forms/app-fundamentals/shell/index.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/app-fundamentals/shell/index.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @weitzhandler 

It's already mentioned in the Introduction doc, nearly the top of the page.

If you want to make your views known, you should contact the [engineering team](https://github.com/xamarin/Xamarin.Forms) or @davidortinau

**Comment by scottkuhl** [comment]
FYI There is an issue open for UWP support.

https://github.com/xamarin/Xamarin.Forms/issues/5593
