### ISSUE TITLE
Updating Nuget packages

### ISSUE THREAD

**Issue by brokenjavagit** [MicrosoftDocs/xamarin-docs#183]
This may sound simple, but every time I open the project in VS 2017 something is broken AGAIN usually the message  (are you missing a using directive or an assembly reference?).  Could someone add a friendly reminder to update not just the solution packages but the EACH INDIVIDUAL PROJECT NuGet packages as well.  While I can see how great it is to have the redundant versioning and dependencies, it may not be obvious to the beginner.  Keep up the good work guys!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d1ce2b1a-b764-8102-3996-747975980b44
* Version Independent ID: 4ab40b26-8aa8-8f09-5a52-4203920e6173
* Content: [Xamarin.Forms Multiscreen Quickstart - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/get-started/hello-xamarin-forms-multiscreen/quickstart?tabs=vswin)
* Content Source: [docs/xamarin-forms/get-started/hello-xamarin-forms-multiscreen/quickstart.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/get-started/hello-xamarin-forms-multiscreen/quickstart.md)
* Service: **unspecified**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Apologies for the delayed response to this issue. Are you suggesting that the sample was broken at the time of logging your issue? If so, following an update, there's no problems now.

**Comment by brokenjavagit** [comment]
I believe it was my incompetence that perpetuated this error.  It was my inability to properly update the appropriate Nuget packages.  This was based on my presupposition that no further action was required after downloading sample code and following the tutorial.  I believe the issue whatever it was, has been since resolved.  My failure to clearly communicate what I did incorrectly, or what the problem actually was is the fault here.  Please close the issue and disregard initial grievance.

**Comment by bakemycode** [comment]
I am working on this on my Mac. After the build, it works in Android Emulator, but it doesn't in iOS simulator. When I click the button, Translate, it does and pops up a window to ask me if I want to make a call to the number. After clicking 'Yes', it leads me to

in Main.cs of Phoneword.iOS
UIApplication.Main(args, null, "AppDelegate");

and Visual Studio said there's an exception.

**Comment by bakemycode** [comment]
I apologize that I commented wrong place
