### ISSUE TITLE
Update Please

### ISSUE THREAD

**Issue by dinobu** [MicrosoftDocs/xamarin-docs#1834]
Ridiculously complex to follow million links half of them not uptodate and with conflicting information

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3aafb37d-8ba1-2f95-2e87-0460d626d94b
* Version Independent ID: 22ea536b-5c49-33fd-6a1c-8012e33462e9
* Content: [Authenticating Users with Azure Mobile Apps - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/data-cloud/authentication/azure)
* Content Source: [docs/xamarin-forms/data-cloud/authentication/azure.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/data-cloud/authentication/azure.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @dinobu 

Afraid this doc won't be updated, in fact, I've got a PR open to remove it. The AMA (Azure Mobile Apps) docs do a good job of how to use Xamarin.Forms with AMA. For their auth doc, see https://docs.microsoft.com/azure/app-service-mobile/app-service-mobile-xamarin-forms-get-started-users

**Comment by dinobu** [comment]
> Hi @dinobu
> 
> Afraid this doc won't be updated, in fact, I've got a PR open to remove it. The AMA (Azure Mobile Apps) docs do a good job of how to use Xamarin.Forms with AMA. For their auth doc, see https://docs.microsoft.com/azure/app-service-mobile/app-service-mobile-xamarin-forms-get-started-users

@Davidbritch Thanks for sharing; however, I believe I somehow ended up from that document to this one.  I'll check again but I think it is how I landed to this area at the first place.
