### ISSUE TITLE
Should be documented as "experimental"

### ISSUE THREAD

**Issue by ArgusMagnus** [MicrosoftDocs/xamarin-docs#1838]
`Shell` and its related additions (`SearchHandler`s, etc.) should be clearly documented as `experimental` as they are (as of XF 4.0.0.540366) nowhere near release/production quality.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f64762a5-78e3-5c1e-b8b3-9572d66110f5
* Version Independent ID: bb324623-2127-a5a3-d620-ebf314dfbf1a
* Content: [Xamarin.Forms Shell - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/shell/#feedback)
* Content Source: [docs/xamarin-forms/app-fundamentals/shell/index.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/app-fundamentals/shell/index.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @ArgusMagnus 

Shell functionality ceased to be experimental as of Xamarin.Forms 4.0. You should feedback your views to the [engineering team](https://github.com/xamarin/Xamarin.Forms/issues). Thanks!

**Comment by ArgusMagnus** [comment]
I am providing feedback by filling out issues at the XF repo. But I wanted to state here that I ran into serious bugs (on a basic/fundamental level) with every new feature I've tried so far. As cool as these new features are (I'm really looking forward to a stable release), in its current state, this API should not be declared "stable".

**Comment by davidbritch** [comment]
Hi @ArgusMagnus 

Thanks for filing the issues in the engineering repo. I hear you re: the Shell API, but all I can say is that decisions about the state of a feature are purely down to the engineers, and that you can make your concerns known to @davidortinau (https://twitter.com/davidortinau).
