### ISSUE TITLE
DeviceInfo.Name is getting wrong name from the device in android.

### ISSUE THREAD

**Issue by RajeethKalluru** [MicrosoftDocs/xamarin-docs#1839]
Hi Team,

DeviceInfo.Name is getting wrong name from the device in android when we Use Xamarin.Essentials.

**Issue:**
Showing  Model instead of Name of the device.
 Can you please check it.

Thanks,
Rajeethulla.

**Comment by conceptdev** [comment]
Issues with Xamarin.Essentials should be reported on its [GitHub repo](https://github.com/xamarin/essentials/issues), thanks.
