### ISSUE TITLE
Does it work with fontawesome pro?

### ISSUE THREAD

**Issue by Wallysantos** [MicrosoftDocs/xamarin-docs#1840]
I have a subscription of FontAwesomePro and I'm trying use it with FontImageSource but only displays "?". Do you know if it works with it?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe0572c4-91be-fc86-d130-242db2bf470b
* Version Independent ID: 1238fdd7-c378-6d0d-654e-55656a70d386
* Content: [Fonts in Xamarin.Forms - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/text/fonts)
* Content Source: [docs/xamarin-forms/user-interface/text/fonts.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/text/fonts.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Yes, it works with FontAwesomePro. It can be difficult figuring out the unicode representation for the glyph. Take a look at this blog post: https://medium.com/@tsjdevapps/use-fontawesome-in-a-xamarin-forms-app-2edf25311db4

**Comment by Wallysantos** [comment]
Hi @davidbritch
Definitely there is something very, very wrong here in my code because I only see "?" instead FontAwesome, although it is relatively easy to get the unicode representation for the icons (from https://andreinitescu.github.io/IconFont2Code/).
I'm open to more suggestions. Thanks!

**Comment by Wallysantos** [comment]
Well, in fact I did all samples of this page and worked fine. But FontAwesome Pro, is doesn't. Giving up...

**Comment by davidbritch** [comment]
Try dropping FontAwesomePro into this sample and giving it a go: https://github.com/Luca7993/FontImageIosProblem

**Comment by docs-product** [comment]
Thanks @davidbritch!
