### ISSUE TITLE
Is the method name correct?

### ISSUE THREAD

**Issue by CeciAc** [MicrosoftDocs/xamarin-docs#1841]
Hi team, 
I'm moving this from here https://github.com/MicrosoftDocs/xamarin-docs.ru-ru/issues/9
User is making a suggestion on a code box.

@lexboss93 commented 7 hours ago 
&gt; StartForegroundServiceComapt
Shouldn't it be StartForegroundServiceCompat ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 14dfecf6-b596-61af-ef6c-c0b65838bd45
* Version Independent ID: 7e1e4994-270d-5383-7d2d-f6d1cd1e1992
* Content: [Foreground Services - Xamarin](https://docs.microsoft.com/en-us/xamarin/android/app-fundamentals/services/foreground-services#feedback)
* Content Source: [docs/android/app-fundamentals/services/foreground-services.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/android/app-fundamentals/services/foreground-services.md)
* Product: **xamarin**
* Technology: **xamarin-android**
* GitHub Login: @conceptdev
* Microsoft Alias: **crdun**

**Comment by JonDouglas** [comment]
This is a typo, here's a PR to resolve:

https://github.com/MicrosoftDocs/xamarin-docs/pull/1845
