### ISSUE TITLE
what is "sDownloadHomepage" ? 

### ISSUE THREAD

**Issue by CeciAc** [MicrosoftDocs/xamarin-docs#1843]
Hi team, 
I'm moving this from here: https://github.com/MicrosoftDocs/xamarin-docs.zh-tw/issues/22 

It looks like there's a typo in this paragraph, could it be that "s" should be "is"?

> The code `await` s on the DownloadHomepage method directly on an assignment

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3e6b1679-7d43-32c2-0ea9-72c2bda2da06
* Version Independent ID: 63828f35-0a1e-1613-bc7f-4f8d95ac3fe7
* Content: [Async Support Overview - Xamarin](https://docs.microsoft.com/en-us/xamarin/cross-platform/platform/async#feedback)
* Content Source: [docs/cross-platform/platform/async.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/cross-platform/platform/async.md)
* Product: **xamarin**
* Technology: **xamarin-crossplatform**
* GitHub Login: @asb3993
* Microsoft Alias: **amburns**

**Comment by conceptdev** [comment]
The 's' belongs to the `await` - as in "The code awaits on the DownloadHomepage method", but `await` is code formatted, leaving the 's' to be translated separately and causing the incorrect appearance in Chinese. We should adjust the text to prevent this kind of translation error - thanks for the feedback.
