### ISSUE TITLE
A small doubt clarification

### ISSUE THREAD

**Issue by nimsrulz** [MicrosoftDocs/xamarin-docs#185]
Hey there,
not tryna be a noob here but just outta curiosity, can we not combine the classes App, MainApp and PhonewordTranslator into one .cs file? I was just tryna understand i from a learning pointa view.. your response would be much appreciated.. thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 540c35eb-3db5-7e73-e6eb-07c4b70df1b0
* Version Independent ID: d8bd33e1-164d-2b2a-75de-42a95c75e6ad
* Content: [Xamarin.Forms Deep Dive - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/get-started/hello-xamarin-forms/deepdive?tabs=vswin)
* Content Source: [docs/xamarin-forms/get-started/hello-xamarin-forms/deepdive.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/get-started/hello-xamarin-forms/deepdive.md)
* Service: **unspecified**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by conceptdev** [comment]
It's common practice to write one-class-per-file, to keep code organized and easy to navigate when apps get bigger and more complicated. In addition, the `App` and `MainPage` are created as part of the **File > New** template.

_Technically_, yes, you could combine them – the compiled output would be the same.

**Comment by nimsrulz** [comment]
thanks Craig.. much appreciated!
