### ISSUE TITLE
UWP Completed event

### ISSUE THREAD

**Issue by donaldnp** [MicrosoftDocs/xamarin-docs#1860]
You need to include information here (and any other relevant places) about triggering the Completed event when on UWP with a real keyboard. I couldn't find anything about this (except for a vague reference to "unfocus", which I tried without success a few ways), but eventually succeeded by using the tab key (after reasoning "well, you can tab between entry boxes, so let's try that...").

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8881d8f1-1d94-e090-e709-aca80b644a78
* Version Independent ID: 298aeed6-5e3e-f053-10f0-66d1061b4b2e
* Content: [Xamarin.Forms Editor - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/text/editor#feedback)
* Content Source: [docs/xamarin-forms/user-interface/text/editor.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/text/editor.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @donaldnp 

Fixed in a PR that will go live later.
