### ISSUE TITLE
UrhoSharp Api Documentation link broken

### ISSUE THREAD

**Issue by HankiDesign** [MicrosoftDocs/xamarin-docs#1864]
Looks like the UrhoSharp API documentation hasn't been migrated to the .NET API Browser, breaking the API documentation link on this page.

Also, the articles that follow this one have a couple of links to the developer.xamarin.com based API documentation that doesn't exist anymore, so the links try to redirect to docs.microsoft.com and result in a 404 page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d087172d-634f-1931-2780-e0739ea16465
* Version Independent ID: 14e34493-0b8d-de08-a3b8-775f9be451d4
* Content: [UrhoSharp - 3D/2D Engine - Xamarin](https://docs.microsoft.com/en-us/xamarin/graphics-games/urhosharp/#feedback)
* Content Source: [docs/graphics-games/urhosharp/index.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/graphics-games/urhosharp/index.md)
* Product: **xamarin**
* Technology: **xamarin-crossplatform**
* GitHub Login: @conceptdev
* Microsoft Alias: **crdun**

**Comment by HankiDesign** [comment]
For example, the majority of links in [_An Introduction to UrhoSharp_](https://docs.microsoft.com/en-us/xamarin/graphics-games/urhosharp/introduction) article are broken.

**Comment by conceptdev** [comment]
Thanks for your feedback - the UrhoSharp API docs are not currently available (as you noticed!). We are figuring out the next steps. For now, you can find the source for the API docs content at https://github.com/xamarin/urho/tree/master/Docs

**Comment by HankiDesign** [comment]
@conceptdev Oh right, thanks for the link!

**Comment by conceptdev** [comment]
We are not planning to host the UrhoSharp API docs at this time, so for now I've removed the links from these docs to avoid confusion. As I mentioned above, we are still figuring out the plan for the long term for these docs.
