### ISSUE TITLE
Add section for GitLab CI .gitlab-ci.yml configuration

### ISSUE THREAD

**Issue by JeroMiya** [MicrosoftDocs/xamarin-docs#1867]
GitLab has a built-in CI system using a `.gitlab-ci.yml` file, which is roughly similar to the Travis configuration format. Would love to see a section in the docs for how to setup GitLab CI to work with Xamarin.Forms and other Xamarin/.Net projects (e.g. asp.net core apps, etc...).

Bonus points for a documenting a multi-project solution with the Xamarin app and the Asp.Net Core backend in one repo (plus iOS, Android, and UWP app building jobs).

**Comment by conceptdev** [comment]
This feels like it might be documentation that belongs on the GitLab site? We have no plans to expand our CI documentation at this time, but appreciate your suggestion.
