### ISSUE TITLE
Great article!

### ISSUE THREAD

**Issue by brokenjavagit** [MicrosoftDocs/xamarin-docs#187]
This should be the first introduction to Xamarin.Forms, xaml and getting started imho.  Unless the previous articles were to raise suspicion and gather a list of further questions.  Now i see the connection between the markup and code behind.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 02a2221e-ff55-cfe0-9f24-382101584c80
* Version Independent ID: 260000a6-cee8-487a-2fbd-2dfdd0864735
* Content: [Part 1. Getting Started with XAML - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/xaml/xaml-basics/get-started-with-xaml?tabs=vswin)
* Content Source: [docs/xamarin-forms/xaml/xaml-basics/get-started-with-xaml.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/xaml/xaml-basics/get-started-with-xaml.md)
* Service: **unspecified**
* GitHub Login: @charlespetzold
* Microsoft Alias: **chape**

**Comment by conceptdev** [comment]
Thanks for the feedback @brokenjavagit.
