### ISSUE TITLE
FeatureNotEnabledException 

### ISSUE THREAD

**Issue by thomasgalliker** [MicrosoftDocs/xamarin-docs#1884]
FeatureNotEnabledException with the comment "Handle not enabled on device exception" is either misleading or I didn't understand it. "Not enabled" in the context of the location service means (to me) the service is globally disabled in the device settings. On github I can read that FeatureNotEnabledException is throw if "there is no location provider available on the device" (similarly stated). I would expect the first case, but when I disable the location service on a device, I always receive PermissionException instead of FeatureNotEnabledException. No matter if the permitted/denied the permission, if the location service is off, I would always expect FeatureNotEnabledException to be throw. Correct?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f0acf3fa-b705-f0cc-b676-eeca60176dfa
* Version Independent ID: 1788a5d5-a3cb-15c8-927c-b6a24810245a
* Content: [Xamarin.Essentials: Geolocation - Xamarin](https://docs.microsoft.com/en-us/xamarin/essentials/geolocation?tabs=android)
* Content Source: [docs/essentials/geolocation.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/essentials/geolocation.md)
* Product: **xamarin**
* Technology: **xamarin-essentials**
* GitHub Login: @jamesmontemagno
* Microsoft Alias: **jamont**

**Comment by jamesmontemagno** [comment]
Please open an issue on: https://github.com/xamarin/essentials this is where bugs are triaged.
