### ISSUE TITLE
[Xamarin Shell] Using images that are larger than icon space scale tab bar significantly on iOS, Droid it works fine. [Xamarin Shell]

### ISSUE THREAD

**Issue by XXcharlosXX** [MicrosoftDocs/xamarin-docs#1885]
**[Xamarin Shell]**
The typical size of an icon is around **30 x 30 px**.
Lets say for some reason I wanted to use a **512 x 512 px** .png for an icon.
On iOS this scales the **tab bar** to the size of the image, **NOT** the other way around.
On Droid, works as desired. **512px** image is scaled to fit the area provided for the tab icon.

<img width="496" alt="Screen Shot 2019-07-09 at 1 47 17 PM" src="https://user-images.githubusercontent.com/40214085/60921734-15e62b00-a250-11e9-8932-370157746869.png">

In this image you can clearly see the icons are larger than the tab bar. The size of the icon is **60 x 60px**.

Below is an example of using a **512x 512px .png**

<img width="543" alt="Screen Shot 2019-07-09 at 1 50 35 PM" src="https://user-images.githubusercontent.com/40214085/60921992-9efd6200-a250-11e9-94c5-e3f9c2fc263a.png">
**[Xamarin Shell]**

**Comment by davidbritch** [comment]
Hi @XXcharlosXX 

Thanks for logging this issue, but it really belongs in the [engineering repo](https://github.com/xamarin/Xamarin.Forms).
