### ISSUE TITLE
A note to all - please ignore the article, go to the code

### ISSUE THREAD

**Issue by HUBBER12** [MicrosoftDocs/xamarin-docs#189]
Do not follow this article if you are trying to use it as a how to guide.. It's not clear which file you should be in when to start adding the code, there are some important lines not here in the article.  Read it just to kind of familiarize yourself with what's going on but if you are trying to get this up and running for the first time, you might want to just skim through and then open up the sample project and fuiger out what's imssing from there.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3ab6098a-39c7-151f-124b-f88aa62c4659
* Version Independent ID: dc27c1e4-ff12-c1af-646a-c2617def0bcd
* Content: [Local Databases - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/databases)
* Content Source: [docs/xamarin-forms/app-fundamentals/databases.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/app-fundamentals/databases.md)
* Service: **unspecified**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by conceptdev** [comment]
Thanks for your feedback @HUBBER12 - this article is scheduled for an update to address the issues you've raised.
