### ISSUE TITLE
The "..." in step 8 (App.xaml.cs) causes syntax error

### ISSUE THREAD

**Issue by KentVu** [MicrosoftDocs/xamarin-docs#1891]
```c#
        public App()
        {
            InitializeComponent();
            MainPage = new NavigationPage(new NotesPage());
        }
        ...
    }
```
Please remove or comment it out.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5ce30880-c4f0-78f7-1ee0-6507e378201e
* Version Independent ID: a6ad2818-c0d2-e3ef-1262-e143d49cc348
* Content: [Store data in a local SQLite.NET database - Xamarin](https://docs.microsoft.com/en-us/xamarin/get-started/quickstarts/database?pivots=macos#feedback)
* Content Source: [docs/get-started/quickstarts/database.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/get-started/quickstarts/database.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @KentVu 

Thanks for your feedback. I've updated the doc, to include the full app class for that step, in a PR that will go live later.
