### ISSUE TITLE
there’s NO XAML attribute specifically to define generic arguments called x:TypeArguments

### ISSUE THREAD

**Issue by idealmusliu** [MicrosoftDocs/xamarin-docs#1892]
Please fix there's no XAML attribute specifically to define generic arguments called x:TypeArguments but in new version of xamarin.forms there's replaced x:TypeArguments with x:DataType so please change it too in docs.microsoft ! 

Thanks 
Sincerely, Ideal 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e80791df-0605-587f-74cd-ebc4c9fd0f74
* Version Independent ID: 76736d2a-f450-4607-55b9-e7f547c0c775
* Content: [Part 2. Essential XAML Syntax - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/xaml/xaml-basics/essential-xaml-syntax#feedback)
* Content Source: [docs/xamarin-forms/xaml/xaml-basics/essential-xaml-syntax.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/xaml/xaml-basics/essential-xaml-syntax.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @idealmusliu 

`x:TypeArguments` *is* used to specify the generic type arguments to the constructor of a generic type. `x:DataType` is used purely in compiled bindings, to specify the type of the object that will be used in the binding.

See: https://docs.microsoft.com/xamarin/xamarin-forms/xaml/namespaces for more info.

**Comment by idealmusliu** [comment]
Hi @davidbritch you cant use x:TypeArguments anymore even for generic type arguments as "Thickness" for example open a new project and try it IntelliSense will not show it ("x:TypeArguments")!

Thanks in advance!

**Comment by davidbritch** [comment]
Hi @idealmusliu 

Regardless of the intellisense issue, if you open the sample associated with the page, you'll see that you can use `x:TypeArguments`.
