### ISSUE TITLE
Unfortunately, it doesn't work with fontawesome!

### ISSUE THREAD

**Issue by Wallysantos** [MicrosoftDocs/xamarin-docs#1895]
Hi @davidbritch
Definitely there is something very, very wrong here in my code because I only see "?" instead FontAwesome, although it is relatively easy to get the unicode representation for the icons (from https://andreinitescu.github.io/IconFont2Code/).

I did some tests with the Lobster font, as demonstrated above and it worked fine. So, unfortunately there is some trick with FontAwesome.

If someone did, please share how do it in clear steps.

_Originally posted by @Wallysantos in https://github.com/MicrosoftDocs/xamarin-docs/issues/1840#issuecomment-510460138_

**Comment by Wallysantos** [comment]
Hi @davidbritch 

Yes. Actually I already use Iconize and I would like to replace by this feature. 
Unfortunately, as I told before, with FontAwesome it doesn't work. It doesn't work in any platform with my apps (or even in sample project to test/evaluation). Some weird I believe, but it is what we have... :(

**Comment by davidbritch** [comment]
Hi @Wallysantos 

The only way to move forward with this issue is to log an issue in the [engineering repo](https://github.com/xamarin/Xamarin.Forms) that describes the problem, and with a repo project so that the engineers can work on a fix if required.

Therefore, I'll close this issue here.

**Comment by Wallysantos** [comment]
No problem @davidbritch 

Thanks! I'm looking forward to use this feature. 

All the best
