### ISSUE TITLE
Xamarin sample Text to Speech program

### ISSUE THREAD

**Issue by jclark993** [MicrosoftDocs/xamarin-docs#190]
[Enter feedback here]
I downloaded Xamarin Text to Speech sample project (Android) and build/run using Xamarin Live Viewer on my Android device.

I got runtime error (appeared in Xamarin Live Viewer logs):

[LogEntry: Time=4/23/2018 8:09:28 PM -05:00, Level=Error, Title=Build Error, Message=
❌'Resource.Layout' does not contain a definition for 'Main'
❌ 'Resource.Id' does not contain a definition for 'btnSpeak'
❌ 'Resource.Id' does not contain a definition for 'editSpeech'
❌ 'Resource.Id' does not contain a definition for 'spinLanguage'
❌ 'Resource.Id' does not contain a definition for 'textSpeed'
❌ 'Resource.Id' does not contain a definition for 'textPitch'
❌ 'Resource.Id' does not contain a definition for 'seekSpeed'
❌ 'Resource.Id' does not contain a definition for 'seekPitch']

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a97fc41a-db2e-51eb-8303-5f4ff89f7706
* Version Independent ID: 3c75dea4-9fc7-5880-de38-1b5f87abdd93
* Content: [Android Speech - Xamarin](https://docs.microsoft.com/en-us/xamarin/android/platform/speech)
* Content Source: [docs/android/platform/speech.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/android/platform/speech.md)
* Service: **unspecified**
* GitHub Login: @mgmclemore
* Microsoft Alias: **mamcle**

**Comment by conceptdev** [comment]
@jclark993 the Xamarin Live Player is only intended for Xamarin.Forms applications. See the [Limitations page](https://docs.microsoft.com/en-us/xamarin/tools/live-player/limitations#limitations-1) for more information.
