### ISSUE TITLE
Please provide Xamarin.Forms Universal Link instructions

### ISSUE THREAD

**Issue by faceoffers28** [MicrosoftDocs/xamarin-docs#191]
From what I can tell, the OpenUrl method only gets called in a native Xamarin.iOS app. It's my understanding that the OnAppLinkRequestReceived method is supposed to be called in a Xamarin.Forms iOS app. If this is true, please provide documentation on how to configure this. Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9195992d-8c5b-0f0c-ae75-700d8ee2f6e4
* Version Independent ID: 0b9cce03-4a62-29c8-57fd-7e3cd3bdd9d0
* Content: [Search with Web Markup - Xamarin](https://docs.microsoft.com/en-us/xamarin/ios/platform/search/web-markup)
* Content Source: [docs/ios/platform/search/web-markup.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/ios/platform/search/web-markup.md)
* Service: **unspecified**
* GitHub Login: @bradumbaugh
* Microsoft Alias: **brumbaug**

**Comment by conceptdev** [comment]
@faceoffers28 this is covered in the [Deep Linking](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/platform/deep-linking) docs referenced in your earlier issue https://github.com/MicrosoftDocs/xamarin-docs/issues/136. The planned update for that page is yet to be published, but will certainly take your feedback into consideration.

For product support and suggestions, visit the [Visual Studio Developer Community site](https://developercommunity.visualstudio.com/).

**Comment by faceoffers28** [comment]
@conceptdev Thanks for the response. This is all it says. "On the iOS platform, there's no additional setup required to use this functionality". This is referring to Deep Linking on an iOS device. However, since lots of people seem to be having problems with Universal Links, it would be nice for Microsoft/Xamarin to provide detailed instructions on how to configure this. Also, it seems as if you are saying that Universal Links and Deep Links are the same based on your comment above. From what I understand, a Deep Link indexes your content and exposes it to being Searched on the device. A Universal Link on the other hand is what happens when someone clicks on a URL on an iOS device and selects whether to open the content in a web browser or using the App. App-Linking is what happens when someone clicks on a URL on an Android device and selects whether to open the content in a web browser or using the App.
