### ISSUE TITLE
Define the class type better

### ISSUE THREAD

**Issue by LanceMcCarthy** [MicrosoftDocs/xamarin-docs#1913]
The `FocusEffect` class name exists in both projects. In the platform specific examples, there is no namespace. So you can't tell if it's supposed to be the class in the class library project or in the platform project.

To fix this, there should be a qualifying namespace. For example:

```csharp
using Xamarin.Forms;
using Xamarin.Forms.Platform.iOS;

[assembly:ResolutionGroupName ("MyCompany")]
[assembly:ExportEffect (typeof(EffectsDemo.iOS.FocusEffect), nameof(EffectsDemo.iOS.FocusEffect))]
namespace EffectsDemo.iOS
{
  ...
}
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 98582b03-f63d-896e-5cfb-bac55bde97fb
* Version Independent ID: 81f9604e-deb9-434c-f580-47aa76087017
* Content: [Creating an Effect - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/effects/creating#feedback)
* Content Source: [docs/xamarin-forms/app-fundamentals/effects/creating.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/app-fundamentals/effects/creating.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @LanceMcCarthy 

Thanks for the suggestion, and sorry for the confusion. I've updated the doc as per your suggestion, in a PR that will go live later.
