### ISSUE TITLE
StackLayout Tutorial Step 1 Feedback

### ISSUE THREAD

**Issue by Rashid-BB** [MicrosoftDocs/xamarin-docs#1918]
### Description

When I created the page MainPage.xaml, the underlying code behind the page "MainPage.xaml.cs" threw an error when trying to build. The error is 

"The name 'InitializeComponent' does not exist in the current context"

### Information

- IDE and IDE version: Visual Studio 2019 16.1 
- Platform with the issue: 
  - iOS:  
  - Android:

**Comment by davidbritch** [comment]
Hi @Rashid-BB 

Have you managed to successfully complete the "First App" tutorial? https://docs.microsoft.com/xamarin/get-started/first-app/?pivots=windows

**Comment by Rashid-BB** [comment]
I have, and the issue is fixed, it was an error with my code.
