### ISSUE TITLE
Code Sharing Strategy

### ISSUE THREAD

**Issue by peejaydeleon** [MicrosoftDocs/xamarin-docs#1919]
Why is this removed in VS2019? Does this mean we have to unlearn Shared Project and only stick to .NET Standard?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b4445585-af8f-09d3-5d35-762c3aac187b
* Version Independent ID: fa9263db-60d6-eb98-eb74-842351ba5387
* Content: [Build your first Xamarin.Forms app - Xamarin](https://docs.microsoft.com/en-us/xamarin/get-started/first-app/?pivots=win-vs2017#feedback)
* Content Source: [docs/get-started/first-app/index.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/get-started/first-app/index.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @conceptdev
* Microsoft Alias: **crdun**

**Comment by maharsh007** [comment]
Yes you have to.

**Comment by conceptdev** [comment]
.NET Standard is preferred for new library projects in Visual Studio 2019 - however you can still _open_ Shared Projects created with earlier versions.

Visual Studio 2019 also has the concept of "multi-targeting", which is an alternative way to produce libraries for different platforms (see the https://github.com/xamarin/essentials source for an example). This feature works in Visual Studio 2019 on Windows and is planned for a future version of Visual Studio for Mac.
