### ISSUE TITLE
InitializeComponent() bug

### ISSUE THREAD

**Issue by sjointer** [MicrosoftDocs/xamarin-docs#192]
In Step 10 of these directions, we are told to copy and overwrite the file App.xaml.cs with the given code.

When doing so, the line InitializeComponent() in the constructor is a compile time error that doesn't disappear regardless of how many times I copy and paste the code.  I've also tried creating a different project, which didn't succeed either.

Based on reading the comments in some of the source files, I have the thought that the line actually doesn't belong in the constructor, because the class, which is derived from Application, is not a content page.  The call to initialize component on the class that is derived from ContentPage doesn't have an error on it.

Please advise.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2de3e72c-8948-4dd5-e37f-9cf81e62c127
* Version Independent ID: 7b7c5c7f-4102-8e91-fbe6-7d21fcc8f5be
* Content: [Xamarin.Forms Quickstart - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/get-started/hello-xamarin-forms/quickstart?tabs=vswin)
* Content Source: [docs/xamarin-forms/get-started/hello-xamarin-forms/quickstart.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/get-started/hello-xamarin-forms/quickstart.md)
* Service: **unspecified**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by conceptdev** [comment]
The `InitializeComponent();` call is correct - it is generated at build-time from the **App.xaml** partial class. If you are not using the latest Visual Studio 2017, the template may not be creating **App.xaml** and **App.xaml.cs** files. You can verify by checking if your file is called **App.cs** instead, in which case simply remove the InitializeComponent call.

**Comment by bharam** [comment]
Not sure if this helps anyone but I created the initial solution using a different name than Phoneword which resulted in this issue.
