### ISSUE TITLE
Documentation/Steps/Guidance for the "MVVM SignalR chat sample" link above

### ISSUE THREAD

**Issue by dinobu** [MicrosoftDocs/xamarin-docs#1922]
Any documentation explaining how to start and steps to follow with this?  Having repo is great but we need steps/guidance to follow when learning something.  Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 99698458-a6cb-0874-bdda-5a3fcb0988b3
* Version Independent ID: 970e5418-c85e-7b4e-adf1-a5ebc411bebc
* Content: [Azure SignalR Service with Xamarin.Forms - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/data-cloud/azure-services/azure-signalr)
* Content Source: [docs/xamarin-forms/data-cloud/azure-services/azure-signalr.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/data-cloud/azure-services/azure-signalr.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @profexorgeek
* Microsoft Alias: **jusjohns**

**Comment by profexorgeek** [comment]
Hi @dinobu - This article is a companion to the sample application. It walks through each of the parts of the application, starting with how to set up the Azure services and explains the key parts. Can you try out the steps in the article and let me know if there are specific parts that are unclear?

**Comment by dinobu** [comment]
> Hi @dinobu - This article is a companion to the sample application. It walks through each of the parts of the application, starting with how to set up the Azure services and explains the key parts. Can you try out the steps in the article and let me know if there are specific parts that are unclear?

I assume you are talking about this article
[https://docs.microsoft.com/en-us/xamarin/xamarin-forms/data-cloud/azure-services/azure-signalr](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/data-cloud/azure-services/azure-signalr)

**Comment by profexorgeek** [comment]
Yep, this issue is filed against the article you linked.

If you look at the metadata below your first comment, it links to both the published article and its markdown source code. Our documentation is open-source markdown code, so filing issues against our docs works exactly like filing issues against a code repository!

**Comment by dinobu** [comment]
Much appreciated, I'll give it a try

**Comment by Tarunshrma** [comment]
I am facing the same issue ass mentioned by IvanCalderon005590243 . I am implementing it in my application using above guide. This let me connected  but when I send the message I never receive the On event fired. So I am never getting back the message that I am sending,
