### ISSUE TITLE
OnMainDisplayInfoChanged fires on pages which have been opened but no longer in stack

### ISSUE THREAD

**Issue by PorkiePie** [MicrosoftDocs/xamarin-docs#1923]
I am sure I am missing something here. 

I am using modal navigation, a page is opened with await Navigation.PushModalAsync(new SamplePage)), then dropped from the stack using await PopModalAsync(). 

After dropping SamplePage, when the device is rotated OnMainDisplayInfoChanged() fires on SamplePage, and other pages in the stack, but not on pages which haven't been in the stack and have OnMainDisplayInfoChanged() in the code behind.

My app is a business to business app which collects data using a selection of several pages. Lets say each has 8 label/input pairs which work fine in portrait mode but need scrolling in landscape. So I split the 8 into 2 blocks of 4 and display the blocks side by side or vertically depending upon DeviceDisplay.MainDisplayInfo.Orientation.

I have placed OnMainDisplayInfoChanged() on each of these pages to detect if the user rotates the device while on that page, and I assumed that it would only fire on the top of stack page, or at least only on pages in the stack, but as I say it fires on pages which "have" been in the stack, but not on pages which "haven't" been in the stack.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: baaf5be9-c6c2-5c43-c131-6cb01cda6502
* Version Independent ID: 7020d1c9-9b6b-18af-72b9-3e75c0c26340
* Content: [Xamarin.Essentials: Device Display Information - Xamarin](https://docs.microsoft.com/en-us/xamarin/essentials/device-display?tabs=ios#feedback)
* Content Source: [docs/essentials/device-display.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/essentials/device-display.md)
* Product: **xamarin**
* Technology: **xamarin-essentials**
* GitHub Login: @jamesmontemagno
* Microsoft Alias: **jamont**

**Comment by PorkiePie** [comment]
Bit more information about OnMainDisplayInfoChanged.

When device is rotated on SamplePage, OnMainDisplayInfoChanged() fires on that page, then all the OnMainDisplayInfoChanged() pages in the stack fire, including SamplePage again firing, so the processing when SamplePage rotates gets done twice.

**Comment by jamesmontemagno** [comment]
Please open an issue on: https://github.com/xamarin/essentials this is where bugs are triaged.
