### ISSUE TITLE
NuGet addresses seem to be out of date

### ISSUE THREAD

**Issue by joelverhagen** [MicrosoftDocs/xamarin-docs#1924]
I am on the nuget.org team and we noticed that your document is mentioning "az320820.vo.msecnd.net". We no longer use this host name. It has been replaced by "globalcdn.nuget.org". I don't know if this document is meant to be an exhaustive list but this aforementioned one is certainly out of date. Other ones that come to mind are "api.nuget.org" and package search endpoints enumerated in this service discovery endpoint:
https://api.nuget.org/v3/index.json

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 946e7563-c5a9-14e8-323e-c557ebc9cfe0
* Version Independent ID: 40cb0a2d-bfa1-8b7d-64f5-076c6067750c
* Content: [Xamarin Firewall Configuration Instructions - Xamarin](https://docs.microsoft.com/en-us/xamarin/get-started/installation/firewall)
* Content Source: [docs/get-started/installation/firewall.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/get-started/installation/firewall.md)
* Product: **xamarin**
* Technology: **xamarin-crossplatform**
* GitHub Login: @asb3993
* Microsoft Alias: **amburns**

**Comment by davidbritch** [comment]
Thanks for pointing this out @joelverhagen . I've made an update to the doc.
