### ISSUE TITLE
Windows Maximum Path Length

### ISSUE THREAD

**Issue by dastewa** [MicrosoftDocs/xamarin-docs#1926]
"On Windows (where the maximum length for a path is 260 characters)" seems to contradict documentation that mentions that this limit has been lifted [Naming Files, Paths, and Namespaces](https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file#maximum-path-length-limitation).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 500cca09-76fd-5df5-6bd9-90cc51fae84d
* Version Independent ID: 3a9bfdcc-ac3a-6cdf-ab20-9fc425c56b71
* Content: [How do I resolve a PathTooLongException error? - Xamarin](https://docs.microsoft.com/en-us/xamarin/android/troubleshooting/questions/path-too-long-exception)
* Content Source: [docs/android/troubleshooting/questions/path-too-long-exception.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/android/troubleshooting/questions/path-too-long-exception.md)
* Product: **xamarin**
* Technology: **xamarin-android**
* GitHub Login: @conceptdev
* Microsoft Alias: **crdun**

**Comment by conceptdev** [comment]
This is a troubleshooting tip, designed to help people who have specifically hit this exception. While there are limited cases where you can opt-in to "remove" this restriction, not all customers will have the right version of Windows, or permission to edit the registry. For this reason, the best solution for our customers continues to be the advice on this page, to minimize the path length as much as possible.

**Comment by dastewa** [comment]
@conceptdev I completely agree, this advice is the best path forward for most of us that have come across this issue for sure.  This issue was moreso about exactly what you just said - folks on certain versions of Windows can opt-in to remove the 260 character restriction. In that case, the statement "On Windows (where the maximum length for a path is 260 characters)" is much too general/inaccurate.
