### ISSUE TITLE
Java Activation - Order of events:

### ISSUE THREAD

**Issue by jzeferino** [MicrosoftDocs/xamarin-docs#193]
In the [Java Activation order or events](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/android/internals/architecture.md#java-activation), the step 12 has "...." and then in the line below we have

> If the (IntPtr, JniHandleOwnership) constructor cannot be found, then a System.MissingMethodException will be thrown.

Should I move that line to step 12?

**Comment by topgenorth** [comment]
Thanks for the catch. We always appreciate feedback that improves the accuracy and quality of our docs.
