### ISSUE TITLE
Email Send Fail: Enable "Email Attachcments Experimental"

### ISSUE THREAD

**Issue by stewa11** [MicrosoftDocs/xamarin-docs#1930]
JUST ADD  ExperimentalFeatures.Enable("EmailAttachments_Experimental"); in your code -> STEW
Maybe worth updating the code for attachments?

Hi, thanks for the code.
I am using VS2019 with Android Emulator.
I created a Xamarin Forms project and added the email with attachments code. This failed on the error below.
I then created an 'Droid Interface' and ran the code. This also failed on the error below.
"
The class, property, or method you are attempting to use ('.ctor'), which is an experimental feature; to use it, you must opt-in by calling ExperimentalFeatures.Enable("EmailAttachments_Experimental") before using this feature.
"
Can you please advise:
1) what is 'ctor'
2)  where in code I should make the call to ExperimentalFeatures.Enable("EmailAttachments_Experimental

Thanks
Stew

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 51ff7357-2cd8-7988-ed3c-de156cc18211
* Version Independent ID: ff242941-6d92-9523-bd73-ec03dbcb095d
* Content: [Xamarin.Essentials: Email - Xamarin](https://docs.microsoft.com/en-us/xamarin/essentials/email?tabs=android#feedback)
* Content Source: [docs/essentials/email.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/essentials/email.md)
* Product: **xamarin**
* Technology: **xamarin-essentials**
* GitHub Login: @jamesmontemagno
* Microsoft Alias: **jamont**

**Comment by jamesmontemagno** [comment]
Please open an issue on: https://github.com/xamarin/essentials this is where bugs are triaged.

**Comment by stewa11** [comment]
cheers James.

The solution was simple: I just entered 'ExperimentalFeatures.Enable("EmailAttachments_Experimental")' into the code before the email was created.

**Comment by jamesmontemagno** [comment]
Glad you got it working, we documented this here: https://docs.microsoft.com/en-us/xamarin/essentials/email?context=xamarin%2Fxamarin-forms&tabs=ios#file-attachments

**Comment by stewa11** [comment]
Documentation looks perfect. Thank you.

& Thank you and all the team for Xamarin... although publishing to Google Play is doing by head in.
I'll raise a different question.
