### ISSUE TITLE
Typo in reSpository selection

### ISSUE THREAD

**Issue by AntiPasha** [MicrosoftDocs/xamarin-docs#1931]
fix respository to repository

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dac28e18-875a-cb51-a031-717692255d0a
* Version Independent ID: f2e625c7-18a7-c090-fa92-9d635ac39164
* Content: [Setting up the Android SDK for Xamarin.Android - Xamarin](https://docs.microsoft.com/en-us/xamarin/android/get-started/installation/android-sdk?tabs=windows#feedback)
* Content Source: [docs/android/get-started/installation/android-sdk.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/android/get-started/installation/android-sdk.md)
* Product: **xamarin**
* Technology: **xamarin-android**
* GitHub Login: @conceptdev
* Microsoft Alias: **crdun**

**Comment by dplotnikov** [comment]
@conceptdev please merge my PR
