### ISSUE TITLE
[Table(name)] parameter "name" optional in documentation, not optional in code

### ISSUE THREAD

**Issue by avihayb** [MicrosoftDocs/xamarin-docs#1932]
https://docs.microsoft.com/en-us/xamarin/android/data-cloud/data-access/using-sqlite-orm
From docs:
[Table(name)] – Marks the class as being able to be stored in an underlying SQLite table. Specifying the optional name parameter will override the default value of the underlying database table's name (which is the same as the class name).

From the IDE:
There is no argument given that corresponds to the required formal parameter 'name' of 'TableAttribute.TableAttribute(string)'

**Comment by conceptdev** [comment]
Thanks for this feedback, I've tested as well and you are right, the `name` isn't optional. Page is being updated now.
