### ISSUE TITLE
Please Add note that Xamarin.Essentials Nuget is "Essentials" for the old projects migration to Shell

### ISSUE THREAD

**Issue by husseinmohkhalil** [MicrosoftDocs/xamarin-docs#1933]
I spent like 2 hours trying to figure out why my project is not working with Shell, the application was crashing with no message or compilation error. then I figured out that I am missing the Xamarin.Essentials NuGet. after installing the NuGet package, everything worked smoothly as expected. 
please just add a note in the documentation in this [Page ](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/shell/create)that Xamarin.Essentials NuGet is important for migration. 
Thanks

**Comment by davidbritch** [comment]
Shell doesn't have any dependencies on Xamarin.Essentials. Is it just your app that has the dependency?

**Comment by husseinmohkhalil** [comment]
I think you are right, although the application was working perfectly without Xamarin.Essentials. but I have created a blank Xamarin solution and added the AppShell file. and everything was smooth. sorry for bothering :)
