### ISSUE TITLE
Explain how to use DataType properties with generic type?

### ISSUE THREAD

**Issue by DeveloperLookBook** [MicrosoftDocs/xamarin-docs#1934]
Will DataType work with generic types? 
How to set generic type for the DataType property value?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f6dded20-b246-945c-63ce-0e349afac9a2
* Version Independent ID: 1e24cfb3-a124-e001-5eb5-9410834bf3a1
* Content: [Xamarin.Forms Compiled Bindings - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/data-binding/compiled-bindings#feedback)
* Content Source: [docs/xamarin-forms/app-fundamentals/data-binding/compiled-bindings.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/app-fundamentals/data-binding/compiled-bindings.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @DeveloperLookBook 

That scenario is currently unsupported. See https://github.com/xamarin/Xamarin.Forms/pull/6843#issuecomment-511366417 for more info.

However, the engineers will add support for this scenario if an enhancement request is opened for it on [their repo](https://github.com/xamarin/Xamarin.Forms).
