### ISSUE TITLE
Connectivity issue in iOS

### ISSUE THREAD

**Issue by jpmock** [MicrosoftDocs/xamarin-docs#1938]
Hey @jamesmontemagno , I am trying to use the Xamarin Essentials Connectivity events for iOS in a Xamarin Forms solution and when I register the event (Connectivity.ConnectivityChanged += Connectivity_ConnectivityChanged) it fires as expected when I disable the internet connection.  It hits the handler and all is good.  

However, the issue is when I re-enable the internet connection, nothing happens.  No event is fired.  

Also worth mentioning is that the only time the event is fired is when I first launch the app in a connected state and transition to a disconnected state. 
If I launch the app in a disconnected state and transition to a connected state, no event is fired.

**Comment by jamesmontemagno** [comment]
Please open an issue on: https://github.com/xamarin/essentials this is where bugs are triaged.
