### ISSUE TITLE
should add a disclaimer here

### ISSUE THREAD

**Issue by maxisam** [MicrosoftDocs/xamarin-docs#1939]
according to the response of this issue https://github.com/xamarin/Xamarin.Forms/issues/6819

The HybridWebView is a sample on how to create a custom renderer, not a fully fledged control we support or distribute.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9c1bd30c-6e7a-df38-8c20-dff7361e901f
* Version Independent ID: 013c6027-db9a-6039-3404-2e4f717133a9
* Content: [Implementing a HybridWebView - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/custom-renderer/hybridwebview#feedback)
* Content Source: [docs/xamarin-forms/app-fundamentals/custom-renderer/hybridwebview.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/app-fundamentals/custom-renderer/hybridwebview.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @maxisam 

If it was a fully fledged control it would be shipping as part of Xamarin.Forms, or via another NuGet package. 

If we add a disclaimer to the page, we'd have to add one to every single page we own, which would hinder readability.
