### ISSUE TITLE
SelectedItem being readonly causing issues with CRUD

### ISSUE THREAD

**Issue by iooovolts** [MicrosoftDocs/xamarin-docs#1942]
As this property is readonly it causes some interesting problems. In the Xaminals example your selection opens a new page so everytime you search the SelectedItem property is reset. In my app for example, I have the SearchHandler component as a means to search for an item and add it to an ObservableCollection&lt;&gt; within the same view. The problem that arises is that I cannot add the same item twice consecutively. I must first select another item so ItemSelected is reset before going back to add the item I wanted to add for the second time in a row!
For a bit more detail I have a post on the Xamarin Forums https://forums.xamarin.com/discussion/162196/how-to-set-itemselected-to-null-after-selection-xamarin-shell-search-handler#latest

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ea22bfa0-1713-6aff-9c8c-dedf47bb3381
* Version Independent ID: f9b7e5be-4b5a-c292-c425-89125369b97b
* Content: [Xamarin.Forms Shell Search - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/shell/search#feedback)
* Content Source: [docs/xamarin-forms/app-fundamentals/shell/search.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/app-fundamentals/shell/search.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @iooovolts 

I'm moving this issue to the engineering repo, for the engineers to consider.

**Comment by davidbritch** [comment]
Hi @iooovolts 

Unfortunately, I can't move this issue to the [engineering repo](https://github.com/xamarin/Xamarin.Forms) as it's in a different GitHub org. However, this is an issue for the engineers so I suggest you log an issue there.
