### ISSUE TITLE
Compiler warning

### ISSUE THREAD

**Issue by noutram** [MicrosoftDocs/xamarin-docs#1952]
In the section invoking asynchronous methods, "https://docs.microsoft.com/en-us/xamarin/xamarin-forms/xaml/xaml-basics/data-bindings-to-mvvm#invoking-asynchronous-methods"
this code seems to generate a yellow underline for the async keyword in the editor relating to warning (RECS1065) . Is this a known issue?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ed970855-6db1-6838-12cf-5a6f58b8ebf4
* Version Independent ID: edfe1b4d-58d2-477d-89b2-2641789cf2db
* Content: [Part 5. From Data Bindings to MVVM - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/xaml/xaml-basics/data-bindings-to-mvvm#invoking-asynchronous-methods)
* Content Source: [docs/xamarin-forms/xaml/xaml-basics/data-bindings-to-mvvm.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/xaml/xaml-basics/data-bindings-to-mvvm.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @noutram 

Yes, this is a known code analyser issue. It's misidentifying a problem with async anonymous methods, when there isn't one (aside from anything else, the code example doesn't use an anonymous method).
