### ISSUE TITLE
'SearchHandler' doesn't contain a definititon for a 'Keyboard'

### ISSUE THREAD

**Issue by heartsender** [MicrosoftDocs/xamarin-docs#1955]
[Enter feedback here]
[Error] CS1061	'SearchHandler' does not contain a definition for 'Keyboard' and no accessible extension method 'Keyboard' accepting a first argument of type 'SearchHandler' could be found (are you missing a using directive or an assembly reference?)

`SearchHandler searchHandler = new SearchHandler { Placeholder = "Enter search terms" };
searchHandler.Keyboard = Keyboard.Create(KeyboardFlags.Suggestions | KeyboardFlags.CapitalizeCharacter);`
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ea22bfa0-1713-6aff-9c8c-dedf47bb3381
* Version Independent ID: f9b7e5be-4b5a-c292-c425-89125369b97b
* Content: [Xamarin.Forms Shell Search - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/shell/search)
* Content Source: [docs/xamarin-forms/app-fundamentals/shell/search.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/app-fundamentals/shell/search.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @heartsender 

I just tried this with Xamarin.Forms 4.1.0.555618 and it worked just fine. No errors.

If you run into such problems, I suggest closing your solution, deleting obj/bin folders in the appropriate project, and reloading.
