### ISSUE TITLE
Master page IconImageSource needs to be set

### ISSUE THREAD

**Issue by pspeybro** [MicrosoftDocs/xamarin-docs#1956]
On this page there is the following note: The MasterDetailPage.Master page must have its Title property set, or an exception will occur.
Please add the property IconImageSource to the list of properties to be set. 
I was running into a nullreference exception. The stacktrace from the device log finally pointed me to this line of code:
https://github.com/xamarin/Xamarin.Forms/blob/4.1.0/Xamarin.Forms.Platform.Android/Platform.cs#L585

CurrentMasterDetailPage.Master.IconImageSource.IsEmpty seems to throw a nullreference because CurrentMasterDetailPage.Master.IconImageSource is null.

I ran into this issue after upgrading from Xamarin Forms 3.4 to 4.1.
Comparing the code that threw the exception, this line of code indeed changed between these versions:
https://github.com/xamarin/Xamarin.Forms/blob/3.4.0/Xamarin.Forms.Platform.Android/Platform.cs#L558
It used to be a check like: string.IsNullOrEmpty(CurrentMasterDetailPage.Master.Icon)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ec31ee56-e3b9-a70a-a4ef-80fdf58e7249
* Version Independent ID: 766b5774-50bf-f43f-800d-48b5c6c66509
* Content: [Xamarin.Forms Master-Detail Page - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/navigation/master-detail-page#feedback)
* Content Source: [docs/xamarin-forms/app-fundamentals/navigation/master-detail-page.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/app-fundamentals/navigation/master-detail-page.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @pspeybro 

I investigated this using the latest Xamarin.Forms release (4.1.0.618606) and was unable to repro the issue.

I agree that the `MasterDetailPage.Master` page must have its Title property set, or an InvalidOperationException is thrown. However, I'm able leave the `MasterDetailPage.IconImageSource` property unset, and the app runs on both iOS and Android. Similarly, I'm able to set the `MasterDetailPage.IconImageSource` property and the app runs on both iOS and Android. The source of your problem must be elsewhere. 

Therefore, I'm going to close this issue as I've noticed you've also opened it in the engineering repo, which is the best place for it.
