### ISSUE TITLE
The last two "Related Links" don't go to a sample page

### ISSUE THREAD

**Issue by Eilon** [MicrosoftDocs/xamarin-docs#1957]
These two links don't work:

* Custom Renderer View (sample)
* ListView Interactivity (sample)

They just go to a generic Xamarin page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3218187d-58a5-a214-4a23-bd2093e771b7
* Version Independent ID: 7a506e7e-e8c9-2bc4-148b-34529ce3afad
* Content: [Xamarin.Forms ListView - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/listview/)
* Content Source: [docs/xamarin-forms/user-interface/listview/index.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/listview/index.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @Eilon 

Leaving this open for now, in the hope that the new sample gallery (and associated redirects) going live fixes this.

**Comment by davidbritch** [comment]
This is now working, with the new samples gallery/redirects being in place.
