### ISSUE TITLE
Wrong Path to MSBuild in Note

### ISSUE THREAD

**Issue by CSharpDevChris** [MicrosoftDocs/xamarin-docs#1958]
The Visual Studio 2019 Path in the Note of "Build iOS apps from the Windows command-line" is wrong. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 98c96bcc-1743-8d9f-f1b2-3c30d5b2a6e2
* Version Independent ID: f57a6157-332a-3f31-c785-7efa99e62711
* Content: [Pair to Mac for Xamarin.iOS Development - Xamarin](https://docs.microsoft.com/en-us/xamarin/ios/get-started/installation/windows/connecting-to-mac/#feedback)
* Content Source: [docs/ios/get-started/installation/windows/connecting-to-mac/index.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/ios/get-started/installation/windows/connecting-to-mac/index.md)
* Product: **xamarin**
* Technology: **xamarin-ios**
* GitHub Login: @lobrien
* Microsoft Alias: **laobri**

**Comment by profexorgeek** [comment]
Thank you. Fixing this now.
