### ISSUE TITLE
What is the limit, if any, to the amount of text it can process?

### ISSUE THREAD

**Issue by mkamoski** [MicrosoftDocs/xamarin-docs#1962]
What is the limit, if any, to the amount of text it can process?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c941b98c-cfe4-a6c9-2117-f5f0d2f5a7f8
* Version Independent ID: 7fe2d995-09dd-2dce-2dbf-7f49e6d7c3f1
* Content: [Xamarin.Essentials: Text-to-Speech - Xamarin](https://docs.microsoft.com/en-us/xamarin/essentials/text-to-speech#feedback)
* Content Source: [docs/essentials/text-to-speech.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/essentials/text-to-speech.md)
* Product: **xamarin**
* Technology: **xamarin-essentials**
* GitHub Login: @jamesmontemagno
* Microsoft Alias: **jamont**

**Comment by jamesmontemagno** [comment]
The API should handle any amount of string length and automatically breaks up strings if they are too long.
