### ISSUE TITLE
I'm stuck on step 5

### ISSUE THREAD

**Issue by ekolis** [MicrosoftDocs/xamarin-docs#1967]
I get an error saying "Unable to add a reference to project 'MyProjectName'". I am supposed to add a reference for the main Xamarin app project into my new UWP app project, right?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2ec3998b-c321-10e6-8e06-b10900c3a549
* Version Independent ID: de666c26-6261-7762-2c18-1576499b5fac
* Content: [Setup Windows Projects - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/platform/windows/installation/#feedback)
* Content Source: [docs/xamarin-forms/platform/windows/installation/index.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/platform/windows/installation/index.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @ekolis 

Correct - you add a reference for the Xamarin .NET Standard project to your UWP app project.

**Comment by ekolis** [comment]
Oh, I'm an idiot - I tried to add a reference to a web service project instead of the Xamarin project!

**Comment by davidbritch** [comment]
Glad you managed to unblock yourself :)
