### ISSUE TITLE
Xamarin.Forms Android minimum version is confusing

### ISSUE THREAD

**Issue by akamud** [MicrosoftDocs/xamarin-docs#1969]
[This](https://docs.microsoft.com/en-us/xamarin/get-started/requirements?tabs=windows#android) page says that the Android "Target" Platform is Android 5.0+, but below it says the minimum version your app can run for Android is 4.4.

From my understanding, we can compile the app with a target o 5.0, but we can run on 4.4. Is this correct? Is there a way to improve this so it becomes less confusing, specially for new Android developers?

**Comment by conceptdev** [comment]
This info on [Understanding Android API Levels](https://docs.microsoft.com/en-us/xamarin/android/app-fundamentals/android-api-levels) might be helpful?

You have a fair bit of control over what you build with and target when using Xamarin for Android, but we have tried to keep the guidance for Xamarin.Forms simple.

**Comment by akamud** [comment]
It is helpful. But thinking from the standpoint of a newcomer, what they might understand from the first page is: if I use XF I can't run on Android 4.4+ devices. This might even be the reason why someone doesn't use XF on a project (in fact this happened at my company with a person that understands Mobile but doesn't use Xamarin).

If I remember correctly, the first page was simpler before, and it just said that Xamarin.Forms supports Android 4.4+.

I think what I'm trying to suggest is this (omitting unrelated parts):

-----

## Target platforms

Xamarin.Forms applications can be written for the following operating systems:

- iOS 8 or higher
- Android 4.4 (API 19) or higher ([more details](#android))
- Windows 10 Universal Windows Platform ([more details](#windows10))

It is assumed that developers have familiarity with [.NET Standard](~/cross-platform/app-fundamentals/net-standard.md).

### Android

You should have the latest Android SDK Tools and Android API platform installed. You can update to the latest versions using the [Android SDK Manager](~/android/get-started/installation/android-sdk.md).

Additionally, the target/compile version for Android projects **must** be set to *Use latest installed platform* (considering a minimum **Target** of Android 5.5 - API 21). However the minimum version can be set to API 19 so you can continue to support devices that use Android 4.4 and newer. These values are set in the **Project Options**:

-----

The whole point is to make sure people understand XF runs on Android 4.4 on a first glance, provided they follow the instructions in the "more details" part. Maybe adding a link to "Understanding API Levels" at this detailed part. 

What do you think?

**Comment by davidbritch** [comment]
I'm chasing this up internally, to get clarity on the minimum requirement (19 or 21).

**Comment by davidbritch** [comment]
Having chased this up, the minimum API is 19, but with a caveat that we recommend API 21 as the minimum. API 21 ensures compatibility with all the Android support libraries, while targeting the majority of the devices out there.

I'll get the doc updated.

**Comment by davidbritch** [comment]
This is fixed in a PR that will go live later today.
