### ISSUE TITLE
Impossible to edit articles under section Interface Views on localize version

### ISSUE THREAD

**Issue by FoggyFinder** [MicrosoftDocs/xamarin-docs#1970]
I can't see "Edit" link, so opportunity to edit a translation is missing.

For example here : https://docs.microsoft.com/ru-ru/xamarin/xamarin-forms/user-interface/

The same as, probably, for the whole section.

**Comment by davidbritch** [comment]
@JasonCard Is this something you can help with?

**Comment by JasonCard** [comment]
Hi @FoggyFinder,	 

Thank you for your feedback and suggestion. 
The article [https://docs.microsoft.com/ru-ru/xamarin/xamarin-forms/user-interface/](https://docs.microsoft.com/ru-ru/xamarin/xamarin-forms/user-interface/) is machine translated.
Currently, we are discouraging users from sending PRs on all machine translated content and have thus turned off the "Edit" button for this content. 
We use our human translated content to train the machine translation engines, so over time, this will improve the quality of all translations.
We cannot ensure that in the future we will process machine-translated content PRs, so it would be best to focus your efforts on the human translated topics, which will have much greater impact. We are closing this PR now.

Many thanks for your support.
Kind regards, 	
Microsoft DOCS Global Experience Team

@davidbritch Could you please go ahead to close this issue as I don't have access to close it.
