### ISSUE TITLE
Add release notes maybe?

### ISSUE THREAD

**Issue by domagojmedo** [MicrosoftDocs/xamarin-docs#1974]
Having release notes would be really useful to see what new APIs were added and changed

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c420b152-7303-918a-dbc8-8d1e539c64ec
* Version Independent ID: fe85e24f-c3fc-3763-b1db-6b360fb08067
* Content: [Xamarin.Essentials - Xamarin](https://docs.microsoft.com/en-us/xamarin/essentials/)
* Content Source: [docs/essentials/index.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/essentials/index.md)
* Product: **xamarin**
* Technology: **xamarin-essentials**
* GitHub Login: @jamesmontemagno
* Microsoft Alias: **jamont**

**Comment by conceptdev** [comment]
They are currently only on the GitHub repo
https://github.com/xamarin/essentials/wiki/Release-Notes
but if you'd like to see them hosted here, along with the rest of our platform, let @jamesmontemagno know 😉
