### ISSUE TITLE
Return type missing from OnApplyTemplate example

### ISSUE THREAD

**Issue by COsborn2** [MicrosoftDocs/xamarin-docs#1975]
Current code is:
```
class MyCustomControl : ContentView
{
    Label myLabel;

    protected override OnApplyTemplate()
    {  
        myLabel = GetTemplateChild("myLabel");
    }
    //...
}
```
Should be:
```
class MyCustomControl : ContentView
{
    Label myLabel;

    protected override void OnApplyTemplate()
    {  
        myLabel = GetTemplateChild("myLabel");
    }
    //...
}
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4960f785-1557-c628-397c-62bdec8b5ac4
* Version Independent ID: 77101e96-d57c-0aaf-af55-9d7e3b86c048
* Content: [Create a ControlTemplate - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/templates/control-templates/creating#feedback)
* Content Source: [docs/xamarin-forms/app-fundamentals/templates/control-templates/creating.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/app-fundamentals/templates/control-templates/creating.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @COsborn2 

Thanks for pointing this out. I've fixed this in a PR that will go live later.
