### ISSUE TITLE
window is in lower case.

### ISSUE THREAD

**Issue by CeciAc** [MicrosoftDocs/xamarin-docs#1977]
@daesang commented on [Tue Jul 30 2019](https://github.com/MicrosoftDocs/xamarin-docs.ko-kr/issues/52)

[여기에 피드백 입력]
public class AppDelegate : UIApplicationDelegate
{
    public override UIWindow Window
            {
                get;
                set;
            }

    public override bool FinishedLaunching(UIApplication app, NSDictionary options)
    {
        // create a new window instance based on the screen size
        window = new UIWindow(UIScreen.MainScreen.Bounds);

        // make the window visible
        window.MakeKeyAndVisible();

        return true;
    }
}

window is in lower case.
---
#### 문서 세부 정보

⚠ *이 섹션을 편집하지 마세요. docs.microsoft.com ➟ GitHub 문제 연결에 필요합니다.*

* ID: 08c274f5-e72f-067b-6cdc-81c50acc7616
* Version Independent ID: 5b0d048a-83d0-98a4-d4d0-027befc40365
* Content: [Xamarin.iOS에서 코드로 iOS 사용자 인터페이스 만들기 - Xamarin](https://docs.microsoft.com/ko-kr/xamarin/ios/app-fundamentals/ios-code-only?tabs=windows#feedback)
* Content Source: [docs/ios/app-fundamentals/ios-code-only.md](https://github.com/MicrosoftDocs/xamarin-docs.ko-KR/blob/live/docs/ios/app-fundamentals/ios-code-only.md)
* Product: **xamarin**
* Technology: **xamarin-ios**
* GitHub Login: @lobrien
* Microsoft Alias: **laobri**

---

@srvbpigh commented on [Tue Jul 30 2019](https://github.com/MicrosoftDocs/xamarin-docs.ko-kr/issues/52#issuecomment-516253691)

Hello, @daesang
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hi team, 
I'm moving this here because the user is making a suggestion on the code box

best regards

**Comment by conceptdev** [comment]
Thank you for this feedback. Another customer recently noticed this and has submitted a fix:

https://github.com/MicrosoftDocs/xamarin-docs/pull/1949

We will be accepting this fix soon, which will appear in the localized content not long after.
