### ISSUE TITLE
Error adding NuGet package

### ISSUE THREAD

**Issue by CMoebius** [MicrosoftDocs/xamarin-docs#1980]
Getting restore information for project /Users/cpm/Projects/Notes/Notes/Notes.csproj
Getting restore information for project /Users/cpm/Projects/Notes/Notes.UITests/Notes.UITests.csproj
Running non-parallel restore.
Reading project file /Users/cpm/Projects/Notes/Notes/Notes.csproj.
Persisting no-op dg to /Users/cpm/Projects/Notes/Notes/obj/Notes.csproj.nuget.dgspec.json
Restoring packages for /Users/cpm/Projects/Notes/Notes/Notes.csproj...
Restoring packages for .NETStandard,Version=v2.0...
Unable to get repository signature information for source https://api.nuget.org/v3-index/repository-signatures/5.0.0/index.json.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5ce30880-c4f0-78f7-1ee0-6507e378201e
* Version Independent ID: a6ad2818-c0d2-e3ef-1262-e143d49cc348
* Content: [Store data in a local SQLite.NET database - Xamarin](https://docs.microsoft.com/en-us/xamarin/get-started/quickstarts/database?pivots=macos#feedback)
* Content Source: [docs/get-started/quickstarts/database.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/get-started/quickstarts/database.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @CMoebius 

Your log suggests an error with NuGet (there may have been a transitive error at the exact moment you loaded this solution and it tried to restore its NuGet packages). Have you since been able to load this solution?

**Comment by davidbritch** [comment]
Closing due to lack of response.
