### ISSUE TITLE
Related links (Simple Background Transfer (sample))

### ISSUE THREAD

**Issue by viveknegi51288** [MicrosoftDocs/xamarin-docs#1982]
Related links (Simple Background Transfer (sample)) is not navigation to proper page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a20bd70b-c9fd-a19d-5740-4639cbe254bb
* Version Independent ID: 06ad12d0-9445-a921-9bb4-39381ceccb7c
* Content: [Background Transfer and NSURLSession in Xamarin.iOS - Xamarin](https://docs.microsoft.com/en-us/xamarin/ios/app-fundamentals/backgrounding/ios-backgrounding-walkthroughs/background-transfer-walkthrough#feedback)
* Content Source: [docs/ios/app-fundamentals/backgrounding/ios-backgrounding-walkthroughs/background-transfer-walkthrough.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/ios/app-fundamentals/backgrounding/ios-backgrounding-walkthroughs/background-transfer-walkthrough.md)
* Product: **xamarin**
* Technology: **xamarin-ios**
* GitHub Login: @lobrien
* Microsoft Alias: **laobri**

**Comment by conceptdev** [comment]
This may have temporarily failed as we migrated to the new [Microsoft Code Samples](https://docs.microsoft.com/samples/) site.

The link works now, the correct target is https://docs.microsoft.com/samples/xamarin/ios-samples/simplebackgroundtransfer/
