### ISSUE TITLE
Download Sample Link Returns 404 Error

### ISSUE THREAD

**Issue by brent-p** [MicrosoftDocs/xamarin-docs#1983]
Download Sample Link https://docs.microsoft.com/samples/xamarin/xamarin-forms-samples/templates-controltemplates-simpletheme no longer exists.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4960f785-1557-c628-397c-62bdec8b5ac4
* Version Independent ID: 77101e96-d57c-0aaf-af55-9d7e3b86c048
* Content: [Create a ControlTemplate - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/templates/control-templates/creating#feedback)
* Content Source: [docs/xamarin-forms/app-fundamentals/templates/control-templates/creating.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/app-fundamentals/templates/control-templates/creating.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @brent-p 

Apologies. This is now fixed.

**Comment by brent-p** [comment]
Thanks so much :)
