### ISSUE TITLE
"Valid values" for this prop are not up to date

### ISSUE THREAD

**Issue by BrayanKhosravian** [MicrosoftDocs/xamarin-docs#1984]
Hi i just figured out that there are more values settable for the property "x:FieldModifier"
valid values are: private, protected, internal and public.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6f0cf734-e614-b430-80dc-299c220eeec7
* Version Independent ID: fc77cd7f-a538-ab81-0734-51148443487c
* Content: [XAML Field Modifiers in Xamarin.Forms - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/xaml/field-modifiers#feedback)
* Content Source: [docs/xamarin-forms/xaml/field-modifiers.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/xaml/field-modifiers.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @BrayanKhosravian 

Good catch, thanks for the feedback.

Having looked at the source, I agree that the full set of valid values is: private, public, protected, internal, and notpublic (with internal and notpublic having the same meaning).

I'll get the doc updated tomorrow.

**Comment by davidbritch** [comment]
This is fixed via a PR that will go live later.
