### ISSUE TITLE
Named Font Size (Header) is this correct?

### ISSUE THREAD

**Issue by XXcharlosXX** [MicrosoftDocs/xamarin-docs#1986]
**Member | iOS | Android | UWP**
**Default** | 16 | 14 | 14
**Micro** | 11 | 10 | 15.667
**Small** | 13 | 14 | 18.667
**Medium** | 16 | 17 | 22.667
**Large** | 20 | 22 | 32
**Body** | 17 | 16 | 14
**Header** | 17 | 96 | 46
**Title** | 28 | 24 | 24
**Subtitle** | 22 | 16 | 20
**Caption** | 12 | 12 | 12

on iOS a **Header** is the same size as the body... (17)
on Android **Header** is 96, which is huge.
Just curious was this **overlooked** **or** are these values **intentional**.
They do not look similar **AT ALL** on their respective devices.

**Comment by conceptdev** [comment]
Hi @XXcharlosXX that is probably best raised as an [issue on the Xamarin.Forms repo](https://github.com/xamarin/Xamarin.Forms/issues).

It looks like you've already checked out the [code](https://github.com/xamarin/Xamarin.Forms/pull/5985/files) in this [PR](https://github.com/xamarin/Xamarin.Forms/pull/5985) that changed/updated those values. Not sure if a solution presents itself based on the implementation - it looks like on iOS that `Header` value is calculated via `_fontScalingFactor`... not sure if that's having an unexpected impact.
