### ISSUE TITLE
CollapseStyle does not exist on MasterDetailPage

### ISSUE THREAD

**Issue by Schinwinkwinsky** [MicrosoftDocs/xamarin-docs#1987]
Hi! I tried the solution shown above but it seems not work. There's only the CollapsedPaneWidth property and it didn't work too.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 252cfd43-6410-4474-4812-79705d7c94e0
* Version Independent ID: d3cf7ca3-0417-cbc5-2027-8ec51e4d3f50
* Content: [MasterDetailPage Navigation Bar on Windows - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/platform/windows/masterdetailpage-navigation-bar#feedback)
* Content Source: [docs/xamarin-forms/platform/windows/masterdetailpage-navigation-bar.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/platform/windows/masterdetailpage-navigation-bar.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @Schinwinkwinsky 

I tried the sample that the page links to, and both `CollapseStyle` and `CollapsedPaneWidth` worked perfectly:

![01uwp](https://user-images.githubusercontent.com/8092460/62364923-b01d5400-b51a-11e9-8c2a-b93fb8fd53c9.PNG)

![02uwp](https://user-images.githubusercontent.com/8092460/62364927-b1e71780-b51a-11e9-9a13-4e699e66d17c.PNG)

![03uwp](https://user-images.githubusercontent.com/8092460/62364940-b4497180-b51a-11e9-88b8-afa073b3f478.PNG)

Therefore I'm closing this issue.

**Comment by Schinwinkwinsky** [comment]
Worked, but there's an alert!

![image](https://user-images.githubusercontent.com/13337108/62372543-210a3f00-b50e-11e9-9164-5ccdbc7cf6f8.png)

**Comment by davidbritch** [comment]
That's an intellisense error, rather than a build error. The APIs are both documented (https://docs.microsoft.com/dotnet/api/xamarin.forms.platformconfiguration.windowsspecific.masterdetailpage?view=xamarin-forms) so they should be appearing in the intellisense.

There can be a plethora of reasons why intellisense is incorrect.
