### ISSUE TITLE
Android Sample Out of Date

### ISSUE THREAD

**Issue by thekeviv** [MicrosoftDocs/xamarin-docs#1988]
The android sample in this tutorial uses the deprecated Android 1 API and should be upgraded to use the new Android 2 Camera API

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e3b172d5-2dc1-88e7-ca23-96e87ae24a42
* Version Independent ID: 1ca93300-738f-4af7-b47c-0e170b7205a4
* Content: [Implementing a View - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/custom-renderer/view)
* Content Source: [docs/xamarin-forms/app-fundamentals/custom-renderer/view.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/app-fundamentals/custom-renderer/view.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by rodrigoalmeidafrancisco** [comment]
It is expected to be updated to version 2 camera ?

**Comment by davidbritch** [comment]
I've just updated the sample/doc to use the Camera2 API. It'll all take a while to run through the CI, but in the meantime you can get the updated sample from https://github.com/xamarin/xamarin-forms-samples/tree/master/CustomRenderers/View
