### ISSUE TITLE
ListView.ChoiceMode

### ISSUE THREAD

**Issue by csutorasbalazs** [MicrosoftDocs/xamarin-docs#199]
"...To avoid confusion, use Single selection mode with Checked and SingleChoice accessories and the Multiple mode with the MultipleChoice style..."
This is not true. Single only works with SingleChoice. Checked requires Multiple mode.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be10b84e-1773-7f4c-bd91-2fee1671b284
* Version Independent ID: 26d2aea5-4bcd-c20a-eeab-2537cf7ca78c
* Content: [Customizing a ListView's Appearance - Xamarin](https://docs.microsoft.com/en-gb/xamarin/android/user-interface/layouts/list-view/customizing-appearance)
* Content Source: [docs/android/user-interface/layouts/list-view/customizing-appearance.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/android/user-interface/layouts/list-view/customizing-appearance.md)
* Service: **unspecified**
* GitHub Login: @mgmclemore
* Microsoft Alias: **mamcle**

**Comment by topgenorth** [comment]
Thanks for the catch. We always appreciate feedback that improves the accuracy and quality of our docs. The guide has been updated, and the changes are making their way through the publishing process.
