### ISSUE TITLE
where / how to switch garbage collector

### ISSUE THREAD

**Issue by hot33331** [MicrosoftDocs/xamarin-docs#1993]
It would be good to know WHERE to change the garbage collector. I figured it out, but maybe it would be more helpful to just put it there or at least in a link.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2553ca72-7627-eb9b-e5f6-51c84fd7c4b9
* Version Independent ID: 50cd62a7-83f5-73f0-409a-57135a5e5704
* Content: [Cross-Platform Performance - Xamarin](https://docs.microsoft.com/en-gb/xamarin/cross-platform/deploy-test/memory-perf-best-practices#feedback)
* Content Source: [docs/cross-platform/deploy-test/memory-perf-best-practices.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/cross-platform/deploy-test/memory-perf-best-practices.md)
* Product: **xamarin**
* Technology: **xamarin-crossplatform**
* GitHub Login: @asb3993
* Microsoft Alias: **amburns**

**Comment by Bejasc** [comment]
@hot33331 perhaps you could mention where you figured it out, to help those looking for the same information?

**Comment by hot33331** [comment]
Just put in a pr with clarification. Thanks for putting me to it! ;-)

**Comment by hot33331** [comment]
I guess this can be closed now.
