### ISSUE TITLE
Static methods are deprecated?

### ISSUE THREAD

**Issue by jayseaCODE** [MicrosoftDocs/xamarin-docs#1995]
All static methods such as InvokeOnMainThreadAsync, other than BeginInvokeOnMainThread are no longer available in the Device class (https://docs.microsoft.com/en-us/dotnet/api/xamarin.forms.device?view=xamarin-forms). Should this page be updated?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e81aa61e-e932-f169-b7ed-83cecfd6702d
* Version Independent ID: 08d4698a-1d94-e4c3-bf87-9f1a73892a67
* Content: [Xamarin.Forms Device Class - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/platform/device#feedback)
* Content Source: [docs/xamarin-forms/platform/device.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/platform/device.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @jayseaCODE 

The `InvokeOnMainThreadAsync` methods were only introduced in Xamarin.Forms 4.1 and are still available. Prior to Xamarin.Forms 4.1, only the `BeginInvokeOnMainThread` method was available.

As for the API page, it needs updating to include the new methods. That's in the hands of the [engineers](https://github.com/xamarin/Xamarin.Forms/).

**Comment by jayseaCODE** [comment]
Hi @davidbritch 
Ah I see. Thanks for pointing that out.
