### ISSUE TITLE
Where are the emulator logs?

### ISSUE THREAD

**Issue by francis2** [MicrosoftDocs/xamarin-docs#1996]
Emulator works fine, but breakpoints are not hit in VS2019 on Windows, and I can't find the logs so it's a liiitle painful to debug.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 18072f31-4d0e-f9b4-c085-fcaa66f278fc
* Version Independent ID: a9ba3155-0f55-f303-e27a-93360433cf0f
* Content: [Remoted iOS Simulator for Windows - Xamarin](https://docs.microsoft.com/en-us/xamarin/tools/ios-simulator/)
* Content Source: [docs/tools/ios-simulator/index.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/tools/ios-simulator/index.md)
* Product: **xamarin**
* Technology: **xamarin-crossplatform**
* GitHub Login: @lobrien
* Microsoft Alias: **laobri**

**Comment by conceptdev** [comment]
Hey @francis2, can you report this [via Visual Studio](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2019), thanks.
