### ISSUE TITLE
Tob top background color title

### ISSUE THREAD

**Issue by anilsnl** [MicrosoftDocs/xamarin-docs#1998]
Hi, when i crate a tab tha contains more then one shelcontent in flayout. The background and title color of bar could not be set. Could you add theese things.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c9d653fd-51ed-ed03-db65-a9efb684dc12
* Version Independent ID: 06470094-10f9-b28e-4ece-4da457a4a609
* Content: [Xamarin.Forms Shell Page Configuration - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/shell/configuration)
* Content Source: [docs/xamarin-forms/app-fundamentals/shell/configuration.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/app-fundamentals/shell/configuration.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @anilsnl 

If I understand you correctly, you're suggesting there's a bug. If that's the case, you need to submit a repro project to the [engineering repo](https://github.com/xamarin/Xamarin.Forms).
