### ISSUE TITLE
Outdated docs about MonoGame

### ISSUE THREAD

**Issue by Mikilll94** [MicrosoftDocs/xamarin-docs#1999]
Docs about MonoGame are completely outdated. They are written for Xamarin Studio. Please update docs for Visual Studio 2019.

#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 68f143ce-fcb0-172a-625d-3b26523c9fae
* Version Independent ID: 9694d752-dc85-9871-e40c-d4e1451dd777
* Content: [Part 2 – Implementing the WalkingGame - Xamarin](https://docs.microsoft.com/en-us/xamarin/graphics-games/monogame/introduction/part2)
* Content Source: [docs/graphics-games/monogame/introduction/part2.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/graphics-games/monogame/introduction/part2.md)
* Product: **xamarin**
* Technology: **xamarin-crossplatform**
* GitHub Login: @conceptdev
* Microsoft Alias: **crdun**

**Comment by conceptdev** [comment]
Thanks for your feedback @Mikilll94. Until we are able to address this issue, please visit the [MonoGame site](http://www.monogame.org) and/or ask a question in the [MonoGame community forum](http://community.monogame.org/).
