### ISSUE TITLE
Mcclist.com is now a parked domain serving ads only

### ISSUE THREAD

**Issue by HankiDesign** [MicrosoftDocs/xamarin-docs#2]
Looks like the domain mcclist.com expired earlier this year and now serves a bunch of ads as a parked domain. This domain is linked to on the very beginning of the document where the mobile country codes (MCC and MNC) are listed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3981f989-83a6-e4eb-664b-cd2f88481312
* Version Independent ID: 09b960a9-2dcf-a0ae-2981-2579d4cfdbdf
* Content: [Alternate Resources - Xamarin | Microsoft Docs](https://docs.microsoft.com/en-us/xamarin/android/app-fundamentals/resources-in-android/alternate-resources?tabs=vswin)
* Content Source: [docs/android/app-fundamentals/resources-in-android/alternate-resources.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/android/app-fundamentals/resources-in-android/alternate-resources.md)
* Service: **unspecified**
* GitHub Login: @mgmclemore
* Microsoft Alias: **mamcle**

**Comment by mgmclemore** [comment]
Fixed, the update should be published soon. Thank you for pointing this out!
