### ISSUE TITLE
Code example fix

### ISSUE THREAD

**Issue by csutorasbalazs** [MicrosoftDocs/xamarin-docs#200]
Semicolons are missing in the OnCreate code example from the end of the event delegates/lambdas.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 10083fd5-785a-2b8d-e4a3-58b41e9e6412
* Version Independent ID: de8f654d-ef57-318c-d6a5-d9497f251d9b
* Content: [Tabbed Layouts with the ActionBar - Xamarin](https://docs.microsoft.com/en-gb/xamarin/android/user-interface/layouts/tab-layout/with-action-bar)
* Content Source: [docs/android/user-interface/layouts/tab-layout/with-action-bar.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/android/user-interface/layouts/tab-layout/with-action-bar.md)
* Service: **unspecified**
* GitHub Login: @mgmclemore
* Microsoft Alias: **mamcle**

**Comment by conceptdev** [comment]
Fixed! Thanks for the feedback and helping us to improve the docs.
