### ISSUE TITLE
Android manifest configuration should be clearer

### ISSUE THREAD

**Issue by hashtobewild** [MicrosoftDocs/xamarin-docs#2002]
In the Android *Manifest.xml* example, you specify:

```xml
<data android:scheme="INSERT_URI_SCHEME_HERE" android:host="auth" />"
```

* The first problem is the trailing quotation.
* The second (more interesting) problem  is that your placeholder text implies using the URI scheme, which (when reading the rest of the document) implies a URI in the format:

```
msal1234abcd://auth
```

which does not seem to work. Using the above example, it should just be:

```
msal1234abcd
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 11f5b457-d99a-06d4-d203-f9eeaa27e0d9
* Version Independent ID: b23b3a5d-b63b-dfe1-bb46-94f57c907be5
* Content: [Authenticate Users with Azure Active Directory B2C - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/data-cloud/authentication/azure-ad-b2c)
* Content Source: [docs/xamarin-forms/data-cloud/authentication/azure-ad-b2c.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/data-cloud/authentication/azure-ad-b2c.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by profexorgeek** [comment]
Hi @hashtobewild,
Thanks for your comment, I agree! Another user filed a similar issue and I responded with some technical details on how the URI Scheme and host work that may help you understand why it works the way it does:

https://github.com/MicrosoftDocs/xamarin-docs/issues/2033

There's a PR that will add a more clear example to the doc as soon as it is merged.
