### ISSUE TITLE
Flyout behavior

### ISSUE THREAD

**Issue by GideonNkrumah** [MicrosoftDocs/xamarin-docs#2004]
It seems like Flyout Behavior no longer works. When setting the behavior to disabled it still follows the default behavior.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a303fbe7-5786-651e-e730-90efb1796e72
* Version Independent ID: 6a6a96eb-7563-8b4f-1272-1eb7bd221fb7
* Content: [Xamarin.Forms Shell Flyout - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/shell/flyout)
* Content Source: [docs/xamarin-forms/app-fundamentals/shell/flyout.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/app-fundamentals/shell/flyout.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @GideonNkrumah 

This needs reporting in the [engineering repo](https://github.com/xamarin/Xamarin.Forms/) so that the engineers can investigate/fix.
