### ISSUE TITLE
Now from another assembly!

### ISSUE THREAD

**Issue by a-einstein** [MicrosoftDocs/xamarin-docs#2005]
This has already cost me a lot of time. First to get it working the old way using MergedWith. Then that turned out to be obsolete, referring to Source. That turned out to only work from xaml. Then I got to this example which only does a local reference. 

I have seen discussions hacking to comply to this, but is that really necessary?

Meanwhile I got ResourceDictionary.MergedDictionaries working, but that still needs InitializeComponent in ResourceDictionary.

So the question remains: can I merge a ResourceDictionary from another assembly using Source?! And how?!

I am not even sure that would really be advantageous.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1d23ce09-1c59-1482-036a-f7348090fd00
* Version Independent ID: 9b4213b5-8278-5bea-c73d-0e172d7c0a89
* Content: [Resource Dictionaries - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/xaml/resource-dictionaries#feedback)
* Content Source: [docs/xamarin-forms/xaml/resource-dictionaries.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/xaml/resource-dictionaries.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @a-einstein 

Currently, only local dictionaries can be loaded via the `Source` property of `ResourceDictionary`. As you've discovered, using the `MergedDictionaries` collection is the only way to merge a dictionary from another assembly.

The docs don't reflect this situation, so I'll get them updated.

**Comment by davidbritch** [comment]
I've updated the doc, in a PR which will go live later.

**Comment by lHubertl** [comment]
Hi, @davidbritch 
I faced this issue as well. I think this feature to merge resource dictionary from another assembly by Source it is extremely important as we can save some code by removing *.xaml.cs
Will someone enhance this?

**Comment by davidbritch** [comment]
@lHubertl That's one to raise in the [engineering repo](https://github.com/xamarin/Xamarin.Forms/).
