### ISSUE TITLE
Incorrect Data Shown

### ISSUE THREAD

**Issue by joshwl2003** [MicrosoftDocs/xamarin-docs#2006]
If I use design time data it is what always shows up in the collection view when running it. I am using 4.1.0.673156 forms. I am seeing this issue when I build and run for iOS. If I remove design time data I do see the correct information when running my application.
`<ContentPage
    xmlns="http://xamarin.com/schemas/2014/forms"
    xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
    xmlns:d="http://xamarin.com/schemas/2014/forms/design"
    xmlns:models="clr-namespace:Model;assembly=Services"
    x:Class="ActionIndicatorNotificationsPage">
    <ContentPage.Content>
        <StackLayout>
            
            <CollectionView x:Name="cvNotificationsView"
                            ItemsSource="{Binding ActionIndicatorNotifications}"
                        EmptyView="No Notification Data to show">
            <d:CollectionView.ItemsSource>
                <x:Array Type="{x:Type models:ActionIndicatorNotification}">
                    <models:ActionIndicatorNotification
                        Title="Title"
                        DateSent="10/11/2013 05:32:00"
                        FullText="This is some text">
                    </models:ActionIndicatorNotification>
                </x:Array>
            </d:CollectionView.ItemsSource>
            <CollectionView.ItemTemplate>
                <DataTemplate>
                    <Grid Padding="10">
                        <Grid.ColumnDefinitions>
                            <ColumnDefinition></ColumnDefinition>
                            <ColumnDefinition></ColumnDefinition>
                        </Grid.ColumnDefinitions>
                        <Grid.RowDefinitions>
                            <RowDefinition></RowDefinition>
                            <RowDefinition></RowDefinition>
                        </Grid.RowDefinitions>
                        <Label Text="{Binding Title}" FontAttributes="Bold" />
                        <Label Text="{Binding DateSent}" Grid.Column="1"/>
                        <Label Text="{Binding FullText}" Grid.Row="1" Grid.ColumnSpan="2" />
                    </Grid>
                </DataTemplate>
            </CollectionView.ItemTemplate>
        </CollectionView>
            </StackLayout>
    </ContentPage.Content>
</ContentPage>
`

**Comment by davidbritch** [comment]
Hi @joshwl2003 

This needs reporting in the [engineering repo](https://github.com/xamarin/Xamarin.Forms/) so that the engineers can investigate/fix.
