### ISSUE TITLE
What are Key Alias and Key Password?

### ISSUE THREAD

**Issue by blanthor** [MicrosoftDocs/xamarin-docs#2010]
I don't see this documented anywhere. Keystore Password is obvious, but that is three different fields I need, and I only know one of them.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d22ceddd-69d4-3a5d-2947-a5abddbbd3aa
* Version Independent ID: e238051f-b809-5541-4049-f1205dd0a3a5
* Content: [Signing the Android Application Package - Xamarin](https://docs.microsoft.com/en-us/xamarin/android/deploy-test/signing/?tabs=windows)
* Content Source: [docs/android/deploy-test/signing/index.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/android/deploy-test/signing/index.md)
* Product: **xamarin**
* Technology: **xamarin-android**
* GitHub Login: @conceptdev
* Microsoft Alias: **crdun**

**Comment by KevinWCIS** [comment]
I have same issue, I went to Pie (9.0) and converted to 64bit because of Google Requirements
. Now ask for signing information that I cannot get through. I bring in my Keystore details and need to get by the ALIAS and password.

**Comment by Ralpharoo** [comment]
After some further searching I found the answer here;
[https://blog.beecomedigital.com/2016/03/06/signing-your-xamarin-android-application-package-during-the-development-phase/](url)

> If you have used the GUI to create the keystore, you probably noticed that there’s only one password value while there are 2 values (keystore password and alias password) in this screen. The GUI use the same value for both fields, but it’s possible to use different values if you use command-line tools.

It worked for me using the Alias and the same password.
