### ISSUE TITLE
Do we need to use Xamarin.Forms.Internals to do pinching?

### ISSUE THREAD

**Issue by mshwf** [MicrosoftDocs/xamarin-docs#2012]
The method `Clamp` exists in `Xamarin.Forms.Internals`, but in the [GitHub sample](https://github.com/xamarin/xamarin-forms-samples/blob/master/WorkingWithGestures/PinchGesture/PinchGesture/PinchToZoomContainer.cs) no reference to this namespace

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ddfae6f3-bfc3-da98-251f-4fe08b7f8e21
* Version Independent ID: a7a9ebc5-b663-7a19-dc0d-b8fd5050f7b7
* Content: [Adding a pinch gesture recognizer - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/gestures/pinch)
* Content Source: [docs/xamarin-forms/app-fundamentals/gestures/pinch.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/app-fundamentals/gestures/pinch.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by conceptdev** [comment]
`Xamarin.Forms.Internals` are not meant for customer use, and the [`Clamp` method](https://github.com/xamarin/Xamarin.Forms/blob/master/Xamarin.Forms.Core/NumericExtensions.cs) is a specialized math function - it is not related to UI gestures.

**Comment by mshwf** [comment]
I know it's not meant for customer use, that's why I asked. Can I use it in my production code (for example; to perform pinching)?

**Comment by conceptdev** [comment]
Please avoid using `Internal` members. I linked to the code above - if you think that will be useful in your app, you can copy it.

**Comment by davidbritch** [comment]
In the sample, the Clamp method is an extension method - https://github.com/xamarin/xamarin-forms-samples/blob/master/WorkingWithGestures/PinchGesture/PinchGesture/Extensions/DoubleExtensions.cs

**Comment by mshwf** [comment]
@davidbritch I figured it out after @conceptdev 's comment. I didn't download the sample or look out into the code files, so I guessed a reference to the `Xamarin.Forms.Internals` is required. Thanks for your help.
