### ISSUE TITLE
UWP 'information' spelling

### ISSUE THREAD

**Issue by jeff-fichtner** [MicrosoftDocs/xamarin-docs#2013]
"Not all email clients support sending attachments. See documentation for more inforamtion." information is spelled wrong

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 51ff7357-2cd8-7988-ed3c-de156cc18211
* Version Independent ID: ff242941-6d92-9523-bd73-ec03dbcb095d
* Content: [Xamarin.Essentials: Email - Xamarin](https://docs.microsoft.com/en-us/xamarin/essentials/email?tabs=uwp#feedback)
* Content Source: [docs/essentials/email.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/essentials/email.md)
* Product: **xamarin**
* Technology: **xamarin-essentials**
* GitHub Login: @jamesmontemagno
* Microsoft Alias: **jamont**

**Comment by conceptdev** [comment]
This has been fixed, thanks for the info.
