### ISSUE TITLE
SetAppearance is never called

### ISSUE THREAD

**Issue by Softtinn** [MicrosoftDocs/xamarin-docs#2016]
Hey,
I've followed your example and created a custom renderer for my toolbar. Howeverl, the SetAppearance method is never fired/called. Why?

Sincerely,
Marcus

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b6242cd2-d96b-273b-d3c6-089cb170ba8d
* Version Independent ID: 5c1a70be-0d94-bed3-ff9a-d46def91cfb3
* Content: [Xamarin.Forms Shell Custom Renderers - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/shell/customrenderers#feedback)
* Content Source: [docs/xamarin-forms/app-fundamentals/shell/customrenderers.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/app-fundamentals/shell/customrenderers.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @Softtinn 

I just checked my sample code and the `SetRenderer` method is getting called in Xamarin.Forms 4.1. There's nothing more to it than is explained in the doc: (1) create a shell renderer class that inherits from `ShellRenderer` that overrides `CreateToolbarAppearanceTracker`, and (2) create a toolbar tracker class that inherits from `ShellToolbarAppearanceTracker` and override `SetAppearance`.
