### ISSUE TITLE
How to use this library on Mac OS and Windows?

### ISSUE THREAD

**Issue by xclw2000** [MicrosoftDocs/xamarin-docs#2022]
In this sample, there are only aim at android and ios platforms, how about used for Android, IOS, Mac OS and Windows at the same time?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e40fbe03-a099-3b24-4654-162103003d6a
* Version Independent ID: 01e8c667-ed94-7054-758d-2399e879714a
* Content: [Use C/C++ libraries with Xamarin - Xamarin](https://docs.microsoft.com/en-us/xamarin/cross-platform/cpp/#feedback)
* Content Source: [docs/cross-platform/cpp/index.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/cross-platform/cpp/index.md)
* Product: **xamarin**
* Technology: **xamarin-crossplatform**
* GitHub Login: @mikeparker104
* Microsoft Alias: **miparker**

**Comment by conceptdev** [comment]
Other platforms are beyond the scope of this sample. In **Step 1** you would need to use the C++ compilation toolchain for your target platforms (eg. Visual Studio 2019 can be used for Windows), to produce platform-specific native libraries. Wrapping and packaging would follow similar steps to those outlined.

**Comment by xclw2000** [comment]
I still have 2 questions:
1.In Step 2, what project type should I create for Mac OS wrapper and how to add reference to my .dylib file?(Is the .a file for IOS work for Mac OS, too?)
2.In Step 3, how to config the <file> elements for Mac OS,  especially the "target" property?

**Comment by xclw2000** [comment]
> Other platforms are beyond the scope of this sample. In **Step 1** you would need to use the C++ compilation toolchain for your target platforms (eg. Visual Studio 2019 can be used for Windows), to produce platform-specific native libraries. Wrapping and packaging would follow similar steps to those outlined.

I still have 2 questions:
1.In Step 2, what project type should I create for Mac OS wrapper and how to add reference to my .dylib file?(Is the .a file for IOS work for Mac OS, too?)
2.In Step 3, how to config the < file > elements in nuspec file for Mac OS, especially the "target" property?

**Comment by conceptdev** [comment]
I doubt iOS and macOS are interchangable - iOS runs on ARM chips and macOS currently runs on Intel.

See the [Nuget docs on target framework](https://docs.microsoft.com/nuget/reference/target-frameworks).
