### ISSUE TITLE
CreateTable data convertion from DateTime on C# to BigInt datatype on SQLite

### ISSUE THREAD

**Issue by cholinflaz** [MicrosoftDocs/xamarin-docs#2023]
Hi

I'm currently working with SQLite databases using the SQLite-net-pcl version 1.3.2. When I use create the SQLite tables from my models on C#. The DateTime datatype in C# is converted to BigInt datatype in the SQLite table
```c#
using SQLite;

public class Student
{
    [PrimaryKey]
    public int Id {set; get;}
    public string Name {set; get;}
    public DateTime Birthday {set; get;}
}
```
The sentence in C# I use to convert the table is:
```c#
using (conn = new SQLiteConnection(DependencyService.Get<IFileHelper>().GetLocalFilePath("mydb.db3")))
{
       try
       {
                conn.CreateTable<Student>();
       }
       catch(Exception)
       {
       }
}
```

The result of the table converted in SQLite is:
```
ID - INT - PRIMARY - NOT NULL
NAME - VARCHAR
BIRTHDAY - BIGINT
```

Is there a way to set ```BIRTHDAY``` as ```DATETIME``` without using ```conn.Query<object>```? Like other attribute?

**Comment by conceptdev** [comment]
From the [SQLite docs](https://www.sqlite.org/datatype3.html#date_and_time_datatype): 

> _SQLite does not have a storage class set aside for storing dates and/or times. Instead, the built-in Date And Time Functions of SQLite are capable of storing dates and times as TEXT, REAL, or INTEGER values_

You should be able to set and read `DateTime` values using SQLite-net-pcl.
