### ISSUE TITLE
Install the package into ALL projects including Android, iOS, and .NET Standard libraries.

### ISSUE THREAD

**Issue by cosminstirbu** [MicrosoftDocs/xamarin-docs#2025]
Hello,

The docs say to install the package into ALL projects including Android, iOS, and .NET Standard libraries, however, if my Android, iOS, and .NET Standard are ALL using PackageReference, based on my testing it is enough to add the reference only in the .NET Standard project.

Am I seeing an expected behaviour? Or should I go ahead and add the nuget reference to the platform specific projects as well?

Thanks,
Cosmin

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 78e6dee8-1182-bf1e-fd3a-e8d1aecc094a
* Version Independent ID: 81202c69-317a-f0fa-7324-5316f7c1ceb7
* Content: [Get Started with Xamarin.Essentials - Xamarin](https://docs.microsoft.com/en-us/xamarin/essentials/get-started?context=xamarin%2Fandroid&tabs=macos%2Candroid)
* Content Source: [docs/essentials/get-started.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/essentials/get-started.md)
* Product: **xamarin**
* Technology: **xamarin-essentials**
* GitHub Login: @jamesmontemagno
* Microsoft Alias: **jamont**

**Comment by cosminstirbu** [comment]
Also if I use ILSpy with the Xamarin.Essentials.dll from the UWP bin folder, I can see that the several Windows namespaces and APIs are being used so this means that the UWP target is resolved automatically.

Is it safe to reference the nuget only in the .NET Standard project if all projects are using PackageReference?

**Comment by jamesmontemagno** [comment]
Yes, I believe that this is newer that they trickle down. I still recommend installing in all for dependencies, but @terrajobst may have some insight here.
