### ISSUE TITLE
Using Compiled Bindings with Coded UI

### ISSUE THREAD

**Issue by brminnick** [MicrosoftDocs/xamarin-docs#2030]
Would it possible to add C# examples, alongside the XAML examples, demonstrating how to use Compiled Bindings?

https://docs.microsoft.com/xamarin/xamarin-forms/app-fundamentals/data-binding/compiled-bindings

**Comment by davidbritch** [comment]
Hi @brminnick 

Compiled bindings use the **TypedBinding** type, which while public is only public so it can be consumed by the IL generated by XAMLC. Really, it should be thought of as an internal type, not to be consumed by developers (and in fact, it deliberately doesn't appear in intellisense). See https://www.davidbritch.com/2018/10/xamarinforms-compiled-bindings-faq.html for more info.

So for that reason, our compiled bindings sample will remain XAML only.

**Comment by brminnick** [comment]
Thanks @davidbritch!

Does Compiled Bindings only benefit UI built in XAML? In other words, is this not a performance improvement that C# UIs need to worry about?

For example, if I create a binding like this, does it get the same benefit as a compiled binding in XAML?

```csharp
myListView.SetBinding(ListView.ItemsSourceProperty, nameof(MyViewModel.MyItemSource));
```

**Comment by davidbritch** [comment]
Compiled bindings are for XAML only. So in your C# example, that binding expression is resolved at runtime and would benefit from using compiled bindings. But compiled bindings aren't available for C# code.
