### ISSUE TITLE
404 on Register your mobile application with Azure Active Directory B2C 

### ISSUE THREAD

**Issue by spottedmahn** [MicrosoftDocs/xamarin-docs#2032]
On https://docs.microsoft.com/en-us/xamarin/xamarin-forms/data-cloud/authentication/azure-ad-b2c#android

### Screenshot of the section w/ the link:

![image](https://user-images.githubusercontent.com/14079228/63205365-4e5bfe80-c071-11e9-941d-43f5b2fba531.png)

The links tries to go to: https://docs.microsoft.com/en-us/docs/xamarin-forms/data-cloud/authentication/azure-ad-b2c.md#register-your-mobile-application-with-azure-active-directory-b2c

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 11f5b457-d99a-06d4-d203-f9eeaa27e0d9
* Version Independent ID: b23b3a5d-b63b-dfe1-bb46-94f57c907be5
* Content: [Authenticate Users with Azure Active Directory B2C - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/data-cloud/authentication/azure-ad-b2c)
* Content Source: [docs/xamarin-forms/data-cloud/authentication/azure-ad-b2c.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/data-cloud/authentication/azure-ad-b2c.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by spottedmahn** [comment]
Is it supposed to be an anchor to the same doc page just higher up in the doc?

Here: https://docs.microsoft.com/en-us/xamarin/xamarin-forms/data-cloud/authentication/azure-ad-b2c#register-your-mobile-application-with-azure-active-directory-b2c?

If so, I can fix that 😊

**Comment by profexorgeek** [comment]
Hi @spottedmahn,
I actually got the same 404 while reviewing one of your other issues and fixed it before I saw this issue and PR! So I'm going to close the linked PR and this issue but thank you very much for your catch and fix.

**Comment by spottedmahn** [comment]
Nice, thanks @profexorgeek 👍
