### ISSUE TITLE
Incorrect method names in examples

### ISSUE THREAD

**Issue by frenetisch-applaudierend** [MicrosoftDocs/xamarin-docs#2036]
The examples for Point and Rect use the wrong method names to convert. According to the documentation those should be `toPlatformPoint()` / `toSystemPoint()` and `toPlatformRectangle()` / `toSystemRectangle()` respectively.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5ae960dd-9557-8c1b-f628-47b0e6729c45
* Version Independent ID: c8fed11b-6507-5113-0159-0ccf1f9611f4
* Content: [Xamarin.Essentials Platform Extensions - Xamarin](https://docs.microsoft.com/en-us/xamarin/essentials/platform-extensions?context=xamarin%2Fxamarin-forms#feedback)
* Content Source: [docs/essentials/platform-extensions.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/essentials/platform-extensions.md)
* Product: **xamarin**
* Technology: **xamarin-essentials**
* GitHub Login: @jamesmontemagno
* Microsoft Alias: **jamont**

**Comment by conceptdev** [comment]
Fixed in the PR referenced above (thanks!)
