### ISSUE TITLE
C# examples result in error:  switch is a Type which is not valid in the current context

### ISSUE THREAD

**Issue by spidermonkey1187** [MicrosoftDocs/xamarin-docs#2038]
The examples are good, however my VS2019 complained of the above error due to the 'switch' keyword being overloaded in this case.  In the above examples I changed 'switch' to 'mySwitch' and it was fine. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5859b652-cae6-50a5-8150-8b253ccac1e1
* Version Independent ID: 9e7d4805-ead6-65d1-17f7-baf545dd68eb
* Content: [Xamarin.Forms Switch - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/switch#feedback)
* Content Source: [docs/xamarin-forms/user-interface/switch.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/switch.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @profexorgeek
* Microsoft Alias: **jusjohns**

**Comment by profexorgeek** [comment]
Hi @spidermonkey1187,
Thanks for catching this! I have a branch in progress to fix a few minor issues with our control docs. I have added this fix and it will go out when I finish the related work.

Thanks again for the catch!
