### ISSUE TITLE
Question about crashes

### ISSUE THREAD

**Issue by Synthezator** [MicrosoftDocs/xamarin-docs#204]
Hello,
I have a question about the last code example with crash. I've read carefully how delegates work (http://csharpindepth.com/Articles/Chapter2/Events.aspx) but I still cannot understand why and where it would crash. If the user taps a label on a cell that should mean this cell is visible and could not been garbage collected. 
Could you please give more details on it? What line would it crash at and how was it possible?
Thank you in advance

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8b6d7825-14ee-ac0c-41ea-48bf372a381d
* Version Independent ID: a347f0a0-b21c-1d6e-df4d-61dbb344666f
* Content: [New Reference Counting System - Xamarin](https://docs.microsoft.com/en-us/xamarin/ios/internals/newrefcount)
* Content Source: [docs/ios/internals/newrefcount.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/ios/internals/newrefcount.md)
* Service: **unspecified**
* GitHub Login: @bradumbaugh
* Microsoft Alias: **brumbaug**

**Comment by bradumbaugh** [comment]
Hi @Synthezator, thanks for the comment. 

In this sample, the `GetCell` method creates a `UITableViewCell`, adds a text view to it, and sets up a C# delegate to handle the text view's `TouchDown` event. 

While the C# `UITableViewCell` wraps an analogous native (Objective-C) `UITableViewCell` object, the delegate for the `TouchDown` event exists only in C# - there's no analog on the native side. 

This means that the native (Objective-C) `UITableViewCell` (and its text view) have a dependency on C# code (specifically, on the `TouchDown` delegate). If that dependency isn't available when the `TouchDown` event actually occurs, it will lead to a crash. This can happen if the C# `UITableViewCell` has been garbage collected before that event occurs.

The new reference counting system helps prevent these types of confusing situations by making sure that "derived" objects – C# objects that wrap native objects but also augment them with extra state/functionality in C# – are still available when necessary.

**Comment by Synthezator** [comment]
Hi @bradumbaugh , thank you for the response. It's almost clear now.
So the C# UITableViewCell could be garbage collected while it's visible just because there is no references from other C# objects, and Mono GC doesn't know about references from Objective-C objects, right?

**Comment by bradumbaugh** [comment]
Hi @Synthezator, you're right – when the managed **UITableViewCell** isn't referenced by other C# objects, it becomes eligible for garbage collection. However, since in this case it contains state that shouldn't be lost – the `TouchDown` delegate – Xamarin.iOS (with "new reference counting") will automatically keep the object alive despite a lack of managed references to it.
