### ISSUE TITLE
CSS doesn't work on ListView.Header

### ISSUE THREAD

**Issue by MrMiso** [MicrosoftDocs/xamarin-docs#2043]
As title say CSS doesn't work on elements placed within 

`<ListView.Header> <Label Text="test" StyleClass="blueLabels"> </ListView.Header>`

Tested with StyleClass in ListView.ItemTemplate and ListView.Header. In ItemTemplate it works fine while in Header it totally ignores it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7a410a97-17d3-aff7-c875-ee9291658957
* Version Independent ID: f415dc53-c941-b0e5-5823-9bafa53f0d9a
* Content: [Styling Xamarin.Forms Apps using Cascading Style Sheets (CSS) - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/styles/css/#feedback)
* Content Source: [docs/xamarin-forms/user-interface/styles/css/index.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/styles/css/index.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @MrMiso 

You need to let the [engineers](https://github.com/xamarin/Xamarin.Forms) know about this, and provide a repro project for it.
