### ISSUE TITLE
Incorrect link in Related Links section

### ISSUE THREAD

**Issue by mshwf** [MicrosoftDocs/xamarin-docs#2044]
The link to "How to Create a Sign In Screen Flow in Xamarin.Forms video" is not directing to the correct page

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 35a3ba3a-3a14-45a7-9fdd-9ef948962d0b
* Version Independent ID: b1c9a8f2-1b6a-cbc0-ef57-b9b540de7320
* Content: [Hierarchical Navigation - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/navigation/hierarchical)
* Content Source: [docs/xamarin-forms/app-fundamentals/navigation/hierarchical.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/app-fundamentals/navigation/hierarchical.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @mshwf 

Thanks for letting me know. I've updated the link in a PR that will go live later. In the meantime, here's the correct link: https://www.youtube.com/watch?v=qKQ7pyyG1fo
