### ISSUE TITLE
Why not Entity Framework?

### ISSUE THREAD

**Issue by LanderVe** [MicrosoftDocs/xamarin-docs#2048]
Now that EF Core works for Xamarin, why are you still recommending sqlite-net? Am I missing something? This page hasn't been updated in years and newcomers might not understand that they can use Entity Framework.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bdcea465-138a-d586-5297-dc93370826b3
* Version Independent ID: a41a6f67-0675-036f-0781-13b9165d3848
* Content: [Xamarin.Forms Local Databases - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/data-cloud/data/databases)
* Content Source: [docs/xamarin-forms/data-cloud/data/databases.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/data-cloud/data/databases.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @LanderVe 

There are trade offs with using ORMs, and performance is one of them, regardless of the platform. In particular, on Xamarin.Android Entity Framework is particularly non-performant (see https://github.com/aspnet/EntityFrameworkCore/issues/12087 details). Therefore, it's not a path we want to send users down.

If Entity Framework becomes more performant on the Xamarin platform, we'll be sure to document it and recommend it. Until that point, our recommendation is to use sqlite-net.

**Comment by LanderVe** [comment]
@davidbritch thanks for the insight. much appreciated

**Comment by vitaha123** [comment]
So Xamarin is unusable for all cases? You say "If Entity Framework becomes more performant on the Xamarin platform". And when this significant day will happen?

**Comment by davidbritch** [comment]
Hi @vitaha123 

The problem platform for Entity Framework is Android. It's performance on iOS and UWP is ok.

When will Entity Framework be performant on the Xamarin platform is a question for the Entity Framework team.

**Comment by vitaha123** [comment]
Sorry, That is so sadness!! EF so popular, and I wont to believe in
Xamarin! Good luck for You!


чт, 24 окт. 2019 г. в 19:37, David Britch <notifications@github.com>:

**Comment by alex4998** [comment]
Not performant. I understand that. I accept that. Could anybody, please, give a complete end to end example how to setup everything and use Entity Framework in Xamarin Android? I'm completely stuck with one exception going after another and still unable to make it work.
