### ISSUE TITLE
How to send header with every HTTP Request?

### ISSUE THREAD

**Issue by Mimisss** [MicrosoftDocs/xamarin-docs#2054]
Can we please have an official example of how to send header(s) with every HTTP request? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ef31dc71-3610-6c18-2bda-d0bb70804c92
* Version Independent ID: 02f7dc7b-541b-4b82-b33c-4e974fb94d8c
* Content: [Xamarin.Forms WebView - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/webview?tabs=windows#feedback)
* Content Source: [docs/xamarin-forms/user-interface/webview.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/webview.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @Mimisss 

We've got samples that set the headers made with HTTP requests - for example https://docs.microsoft.com/xamarin/xamarin-forms/data-cloud/azure-cognitive-services/speech-recognition#authentication

However, it's not something we focus on too much as it's not Xamarin specific. Instead, it's part of the .NET Core documentation. https://docs.microsoft.com/en-us/dotnet/csharp/tutorials/console-webapiclient looks like it'll help you.

**Comment by Mimisss** [comment]
Thanks but I am not sure what your answer has to do with the question asked. This is probably not your fault either since the question is out of context, it seems. I was on the [Xamarin.Forms WebView page](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/webview?tabs=windows) when I originally posted using the "_Send feedback about this page_" button. So, the question was about sending http headers with the Xamarin.Forms WebView view and had nothing to do with .NET Core, HttpClient, JSON or REST whatsoever.

**Comment by davidbritch** [comment]
Apologies @Mimisss 

The short answer is there's nothing included in the Xamarin.Forms `WebView` control that allows you to set headers. However, it can be achieved by creating your own custom renderer for the control. For more info, see https://github.com/albertoms/xamarin-webview-with-custom-headers

**Comment by Mimisss** [comment]
@davidbritch Excellent, thank you.
