### ISSUE TITLE
Xamarin Essentials documentation - show O/S-specific permissions required for each function

### ISSUE THREAD

**Issue by joehanna** [MicrosoftDocs/xamarin-docs#2055]
Would be great if the Xamarin Essentials documentation had a section that specified which app permissions are required to execute the feature for each operating system.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9f4d0869-b5c2-c17b-63d4-f325856d1a79
* Version Independent ID: a5f487c3-4e56-838f-89a9-b8fa0dc13261
* Content: [Xamarin.Essentials: Phone Dialer - Xamarin](https://docs.microsoft.com/en-us/xamarin/essentials/phone-dialer?context=xamarin/android)
* Content Source: [docs/essentials/phone-dialer.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/essentials/phone-dialer.md)
* Product: **xamarin**
* Technology: **xamarin-essentials**
* GitHub Login: @jamesmontemagno
* Microsoft Alias: **jamont**

**Comment by jamesmontemagno** [comment]
On each page of documentation it highlights what permissions are needed. Are you looking for just a single page with all of them? Would be a bit of a duplicate and I think would be better to keep them together.

**Comment by joehanna** [comment]
Thanks @jamesmontemagno for replying.

A lot of the Essentials pages show Permissions required - which is great -  but I was talking about features like the Phone Dialler and Geocoding.  Geocoding for instance, doesn't have a **Permissions** section in the Docs (by omission or just doesn't need any?). I can get it to work fine on iOS (Simulator and device) but I just can't get it to work in the Android emulator (simply returns null for `GetLocationsAsync`) nor on a physical device (OPPO) which returns an exception: `Java.IO.IOException - Service not available`.  I can only guess it Is a permission problem on Android since iOS is working.

**Comment by jamesmontemagno** [comment]
Gotcha, every API that requires a permission has it documented.

In this instances the IOException you are getting is due to the device not having a Geocoder capable hardware/software support.  So the only thing that we could possibly do and think about is troubleshooting to every page to help developers understand exceptions that may occur.

**Comment by joehanna** [comment]
Thanks for that.  I just figured a fixed section in the docs for "Permissions" would be better and more consistent (especially for noobies). For the functions that don't need them, it could just say "None".  Some of the functions can be a little confusing: Geolocation needs permissions, but Geocoding doesn't, but when it doesn't work, there is doubt whether special permissions are required.

**Comment by conceptdev** [comment]
Going to close this issue now. @joehanna thanks for the feedback - for now I think we'll only specify things like "Permissions" and "Platform differences" when they're required.
