### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by samirgunic** [MicrosoftDocs/xamarin-docs#206]
```404: https://www.visualstudio.com/explore/msft-android-emulator-vs```

```200: https://www.visualstudio.com/vs/msft-android-emulator/```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0546ef4d-4237-66c4-d7b0-f86b57dc91b3
* Version Independent ID: 85fa9e0e-cf82-e63b-2557-c3869a3888b4
* Content: [Visual Studio Android Emulator - Xamarin](https://docs.microsoft.com/en-us/xamarin/android/deploy-test/debugging/visual-studio-android-emulator)
* Content Source: [docs/android/deploy-test/debugging/visual-studio-android-emulator.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/android/deploy-test/debugging/visual-studio-android-emulator.md)
* Service: **unspecified**
* GitHub Login: @mgmclemore
* Microsoft Alias: **mamcle**

**Comment by topgenorth** [comment]
That's for reporting this. A fix for this will be published shortly.
