### ISSUE TITLE
Location of "Notes.db3"

### ISSUE THREAD

**Issue by tpham210** [MicrosoftDocs/xamarin-docs#2062]
Thanks for another great tutorial, sir!

I tried to find the location of "Notes.db3" so that I can try to modify the other way around to see the effect. (Modify from DB using "DB Browser (SQLite)", reflect the change in UI)

I tried to add
`
Console.WriteLine("Notes.db3 location: {0}", Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData));
`

Got this location: 
`/data/user/0/com.companyname.Notes/files/.local/share`

But when I looked into the phone's file structure, still can't find it ...

Am I missing some knowledge here, sir?

**Comment by davidbritch** [comment]
Hi @tpham210 

Apologies for the delayed response.

The location is a private directory for your application, and so you won't be able to see the file using a file browser (unless it has root privileges). However, you can use `add` to inspect the file, or write code to copy it to a known public location on the device.

I suggest you take a look at:

https://forums.xamarin.com/discussion/87597/xamarin-extract-android-sqlite-to-a-local-folder-on-the-device

AND

https://forums.xamarin.com/discussion/129543/how-can-i-see-my-database

Hope this helps!
