### ISSUE TITLE
nuget package bust be add to app project, too.

### ISSUE THREAD

**Issue by CeciAc** [MicrosoftDocs/xamarin-docs#2064]
@a44281071 commented on [Sat Aug 24 2019](https://github.com/MicrosoftDocs/xamarin-docs.zh-cn/issues/53)

if not, will cause System.DllNotFoundException: 'e_sqlite3' exception.

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 5ce30880-c4f0-78f7-1ee0-6507e378201e
* Version Independent ID: a6ad2818-c0d2-e3ef-1262-e143d49cc348
* Content: [将数据存储在本地 SQLite.NET 数据库中 - Xamarin](https://docs.microsoft.com/zh-cn/xamarin/get-started/quickstarts/database?pivots=windows#feedback)
* Content Source: [docs/get-started/quickstarts/database.md](https://github.com/MicrosoftDocs/xamarin-docs.zh-CN/blob/live/docs/get-started/quickstarts/database.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

---

@srvbpigh commented on [Sat Aug 24 2019](https://github.com/MicrosoftDocs/xamarin-docs.zh-cn/issues/53#issuecomment-524516153)

Hello, @a44281071
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by davidbritch** [comment]
Hi @CeciAc 

Can you find out on which platform, and which platform version this is an issue? I've been unable to repro it on both iOS and Android. My guess is only affects a specific Android API level.

**Comment by davidbritch** [comment]
Closing due to lack of response.
