### ISSUE TITLE
Link under "See also"

### ISSUE THREAD

**Issue by CeciAc** [MicrosoftDocs/xamarin-docs#2065]
@wegascee commented on [Mon Aug 26 2019](https://github.com/MicrosoftDocs/xamarin-docs.de-de/issues/29)

The link for "Symbolicating iOS Crash Files (Xamarin.iOS)" seems not to be correct (linking only to blog main site). The link should be

https://www.jmillerdev.net/symbolicating-ios-crash-files-xamarin-ios/

instead of

http://jmillerdev.net/symbolicating-ios-crash-files-xamarin-ios/

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 787467fb-f4f4-74f4-6111-d9bbb38f96f0
* Version Independent ID: 946c9585-0e67-7d46-3a21-ad5aa9bcc4c1
* Content: [Wo finde ich die DSYM-Datei zum Ersetzen der iOS-Absturzprotokolle durch Symbole? - Xamarin](https://docs.microsoft.com/de-de/xamarin/ios/troubleshooting/questions/symbolicate-ios-crash)
* Content Source: [docs/ios/troubleshooting/questions/symbolicate-ios-crash.md](https://github.com/MicrosoftDocs/xamarin-docs.de-DE/blob/live/docs/ios/troubleshooting/questions/symbolicate-ios-crash.md)
* Product: **xamarin**
* Technology: **xamarin-ios**
* GitHub Login: @lobrien
* Microsoft Alias: **laobri**

---

@srvbpigh commented on [Mon Aug 26 2019](https://github.com/MicrosoftDocs/xamarin-docs.de-de/issues/29#issuecomment-524905794)

Hello, @wegascee
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by conceptdev** [comment]
Thanks, updating now!
