### ISSUE TITLE
MinimumWidthRequest and MinimumHeightRequest descriptions do not suggest actual functionality

### ISSUE THREAD

**Issue by vchelaru** [MicrosoftDocs/xamarin-docs#2069]
There is a lot of discussion about MinimumWidthRequest and MinimumHeightRequest on various github issues, and in my own experience this property does not do what the name suggests.

According to https://github.com/xamarin/Xamarin.Forms/issues/2887, the properties will remain as-is. If they do, I think it's worth having docs that clarify how they actually work since they seem to not work how most expect.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1e23d082-44c6-6139-f2a3-8a1286e6b48a
* Version Independent ID: 5c402cd7-0cb4-2d7b-66b8-fa0df4221e9c
* Content: [Xamarin.Forms common control properties, methods, and events - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/controls/common-properties#feedback)
* Content Source: [docs/xamarin-forms/user-interface/controls/common-properties.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/controls/common-properties.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @profexorgeek
* Microsoft Alias: **jusjohns**

**Comment by profexorgeek** [comment]
This doc has been updated to more clearly explain how minimum request properties work in commit:
https://github.com/MicrosoftDocs/xamarin-docs-pr/commit/74f760c88321cf13a70a783a60badeaf05c6ef9e

Details:
https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/controls/common-properties#minimum-request-properties
