### ISSUE TITLE
ThumbColor doesn't exist

### ISSUE THREAD

**Issue by HeadBanging** [MicrosoftDocs/xamarin-docs#2090]
ThumbColor looks like an excellent addition for a nicely themed app - but, when I try to use it (with the latest version of Visual Studio on the Mac) I get an error in the XAML:

The property 'ThumbColor' was not found in type 'Switch'

also: 

SettingsPage.xaml(21,21): Error: Position 29:21. No property, bindable property, or event found for 'ThumbColor', or mismatching type between value and property. 

Like software itself, documentation is only any good if it's been properly tested and actually works.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5859b652-cae6-50a5-8150-8b253ccac1e1
* Version Independent ID: 9e7d4805-ead6-65d1-17f7-baf545dd68eb
* Content: [Xamarin.Forms Switch - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/switch#feedback)
* Content Source: [docs/xamarin-forms/user-interface/switch.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/switch.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @profexorgeek
* Microsoft Alias: **jusjohns**

**Comment by profexorgeek** [comment]
Hi @HeadBanging, please update the nuget packages in your project to the latest stable version of Xamarin.Forms 4.2 to use the `ThumbColor` property. It was just released in 4.2 but the project template is still targeting Xamarin.Forms 4.1.X!
