### ISSUE TITLE
Where is the example on how to customize Material Entry Renderer on iOS

### ISSUE THREAD

**Issue by CeciAc** [MicrosoftDocs/xamarin-docs#2091]
@MathewLC commented on [Mon Sep 02 2019](https://github.com/MicrosoftDocs/xamarin-docs.pt-br/issues/29)

I am't seeing the example on how to customize iOS material Render and i actually need this. I need to customize the keyboard of my iOS entry but i also need to apply material visual. And when i apply the visual marker to the component, i can't do the changes. 

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: fbfbc90e-2eb6-a305-f7da-bded6e31a2b4
* Version Independent ID: 66cad08c-2158-c081-a668-e4dad525e664
* Content: [Visual de material do Xamarin. Forms - Xamarin](https://docs.microsoft.com/pt-br/xamarin/xamarin-forms/user-interface/visual/material-visual#feedback)
* Content Source: [docs/xamarin-forms/user-interface/visual/material-visual.md](https://github.com/MicrosoftDocs/xamarin-docs.pt-BR/blob/live/docs/xamarin-forms/user-interface/visual/material-visual.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

---

@srvbpigh commented on [Mon Sep 02 2019](https://github.com/MicrosoftDocs/xamarin-docs.pt-br/issues/29#issuecomment-527136970)

Hello, @MathewLC
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hi team, 
I'm moving this here because the user is requesting aditional examples
best regards

**Comment by davidbritch** [comment]
Hi @CeciAc and @MathewLC 

This is a fair comment - the example of customising a material renderer is a bit thin. Therefore, I've created an item in our backlog to flesh this out some more.

**Comment by CarLoOSX** [comment]
any updates I'm unable to customize these controls.
