### ISSUE TITLE
Wrong function name

### ISSUE THREAD

**Issue by criistii** [MicrosoftDocs/xamarin-docs#2097]
In the PersonDataTemplateSelector class, the function should be SelectTemplate (not OnSelectTemplate)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 49c3ed9a-994e-1d23-cf5f-14e7295c514c
* Version Independent ID: 1382be5e-00c7-ebaa-1bfb-f16e43afa3b9
* Content: [Creating a Xamarin.Forms DataTemplateSelector - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/templates/data-templates/selector#feedback)
* Content Source: [docs/xamarin-forms/app-fundamentals/templates/data-templates/selector.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/app-fundamentals/templates/data-templates/selector.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @criistii 

The doc is correct. The method you override is `OnSelectTemplate`. If you examine the Xamarin.Forms source code (https://github.com/xamarin/Xamarin.Forms/blob/master/Xamarin.Forms.Core/DataTemplateSelector.cs) `OnSelectTemplate` is the overridable method, and which is called by the `SelectTemplate` method (which isn't overridable).
