### ISSUE TITLE
ConnectivityChanged event fired only once

### ISSUE THREAD

**Issue by alphagamer7** [MicrosoftDocs/xamarin-docs#2098]
https://docs.microsoft.com/en-us/xamarin/essentials/connectivity?tabs=ios For internet connectivity check,
I have used ` Connectivity.ConnectivityChanged += Connectivity_ConnectivityChanged;` as in the example with relevant `Connectivity_ConnectivityChanged` function. ConnectivityChanged event only gets fired once, from when I Connect -> Disconnect. When I reconnect back, the event doesn't get fired. Any idea why?

Simulator iOS 12.4

**Comment by conceptdev** [comment]
@alphagamer7 product issues can be raised directly on the [Xamarin.Essentials GitHub repo](https://github.com/xamarin/essentials/issues), which will get more attention from the engineering team.

**Comment by conceptdev** [comment]
Thanks, I see https://github.com/xamarin/Essentials/issues/901 with additional info. Closing this issue, please track on the Essentials repo.
