### ISSUE TITLE
Needs information on how to open a specific page

### ISSUE THREAD

**Issue by jsuvanto** [MicrosoftDocs/xamarin-docs#2099]
What is the recommended way to open a specific ContentPage (using PushAsync or PushModalAsync) after tapping the notification and launching the activity?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 78e442e3-b387-f538-5430-e4538cf60cb9
* Version Independent ID: 44dc930e-09e2-56e8-e693-18a69af0a747
* Content: [Local Notifications on Android - Xamarin](https://docs.microsoft.com/en-us/xamarin/android/app-fundamentals/notifications/local-notifications)
* Content Source: [docs/android/app-fundamentals/notifications/local-notifications.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/android/app-fundamentals/notifications/local-notifications.md)
* Product: **xamarin**
* Technology: **xamarin-android**
* GitHub Login: @conceptdev
* Microsoft Alias: **crdun**

**Comment by conceptdev** [comment]
To clarify, are you asking about a Xamarin.Forms app (receiving a notification on the Android platform)?

**Comment by jsuvanto** [comment]
Yes.

**Comment by davidbritch** [comment]
Hi @jsuvanto 

Apologies for the delayed response to your issue. We now have a doc on local notifications in Xamarin.Forms apps, which should direct you to the information you need: https://docs.microsoft.com/xamarin/xamarin-forms/app-fundamentals/local-notifications
