### ISSUE TITLE
Outdated information and misleading title

### ISSUE THREAD

**Issue by bruzkovsky** [MicrosoftDocs/xamarin-docs#21]
This starting page looks like it has not been updated in two years, this leaves a bad first impression.
1) The latest C# version is 7, there is no mentioning of Xamarin supporting this (which it does). You could link to this: https://blogs.msdn.microsoft.com/dotnet/2016/08/24/whats-new-in-csharp-7-0/
2)  Portable Visual Basic but no .NetStandard?
3) The title of this document is misleading. From reading this, I don't have any clue about the platform features, nor which platforms there actually are supported. This just seems like random information being mashed together with a random title

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 58fbbe80-f4f1-88da-e902-9263d61b07ed
* Version Independent ID: 162ea562-906f-4960-29a8-aaacf8e89254
* Content: [Platform Features - Xamarin | Microsoft Docs](https://docs.microsoft.com/en-us/xamarin/cross-platform/platform/index#feedback)
* Content Source: [docs/cross-platform/platform/index.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/cross-platform/platform/index.md)
* Service: **unspecified**
* GitHub Login: @asb3993
* Microsoft Alias: **amburns**

**Comment by conceptdev** [comment]
Thanks for your feedback. .NET Standard is covered in the [App Fundamentals](https://docs.microsoft.com/en-us/xamarin/cross-platform/app-fundamentals/net-standard) section.

We'll look to address your other comments in a future update of this content. Perhaps the information on [visualstudio.com/xamarin](https://www.visualstudio.com/xamarin/) is closer to what you expected on this page?

**Comment by bruzkovsky** [comment]
Ok, I found what I was expecting here: [https://docs.microsoft.com/en-us/xamarin/xamarin-forms/platform/index](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/platform/index), so I just visited the wrong section. Still I think I wouldn't get this Cross-Platform section if I didn't know how Xamarin works already. Maybe you could fit the whole section into a single page :smile:

I just noticed that the layout of visualstudio.com/xamarin is broken when you choose german language, see screenshot:

![capture](https://user-images.githubusercontent.com/10390959/37509937-ba553ec8-28f9-11e8-8646-57b87d56edf6.PNG)

**Comment by conceptdev** [comment]
Thanks for the additional context, it helps to understand what readers expect. 

I'll pass the visualstudio.com issue onto the team.

Appreciate your time!
