### ISSUE TITLE
Slider resolution on UWP

### ISSUE THREAD

**Issue by brokenjavagit** [MicrosoftDocs/xamarin-docs#210]
Commanding with ViewModels
When i deploy to Android i can move the slider with 2 digits of accuracy eg. hue =  0.62, sat  = 0.92, ect.  But on UWP deploy I can only move the slider in 0.1 increments, hue = 0.00, 0.10, 0.20 ect. I cannot use the slider to hit 0.23 for example on UWP but i can on other platforms?  Am I missing something? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ed970855-6db1-6838-12cf-5a6f58b8ebf4
* Version Independent ID: edfe1b4d-58d2-477d-89b2-2641789cf2db
* Content: [Part 5. From Data Bindings to MVVM - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/xaml/xaml-basics/data-bindings-to-mvvm)
* Content Source: [docs/xamarin-forms/xaml/xaml-basics/data-bindings-to-mvvm.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/xaml/xaml-basics/data-bindings-to-mvvm.md)
* Service: **unspecified**
* GitHub Login: @charlespetzold
* Microsoft Alias: **chape**

**Comment by charlespetzold** [comment]
What you have observed about the UWP implementation of `Slider` is correct. That limitation is described in the section of the article [Using Slider: Platform implementation differences](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/slider#platform-implementation-differences).

That section of the article also mentions an alternative `StepSlider` that is described in [Chapter 27. Custom renderers](https://xamarin.azureedge.net/developer/xamarin-forms-book/XamarinFormsBook-Ch27-Apr2016.pdf) of the book _Creating Mobile Apps with Xamarin.Forms_ beginning on the page 1149. The `StepSlider` can be set to any desired resolution.

**Comment by brokenjavagit** [comment]
Thank you Charles, if only I had the patience to continue reading.  If the dog wouldn't have stopped to ... he would have caught the hare.
