### ISSUE TITLE
Dynamic sizing - relative

### ISSUE THREAD

**Issue by BioTurboNick** [MicrosoftDocs/xamarin-docs#2102]
I'm trying to dynamically size my DataTemplate items based on the size of the control. E.g. if there's only 1, it should take up the whole space. If 2, it should split 50:50, etc. But I can't seem to get it to respond with different binding strategies. It'd be helpful if you could demonstrate this here.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: db5e00a1-93a6-5965-70cc-cef81656dce0
* Version Independent ID: 11361877-6f4b-b0f7-0ece-5dc6a44f9ce0
* Content: [Xamarin.Forms CollectionView Layout - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/collectionview/layout#feedback)
* Content Source: [docs/xamarin-forms/user-interface/collectionview/layout.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/collectionview/layout.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @BioTurboNick 

Can you elaborate so I can get a better understanding of what you've trying to achieve?

**Comment by davidbritch** [comment]
I suspect this is an area where the new relative binding markup extension will help: https://docs.microsoft.com/xamarin/xamarin-forms/app-fundamentals/data-binding/relative-bindings

**Comment by BioTurboNick** [comment]
@davidbritch I'll check that out, thanks. I also raised a feature request for the CollectionView control in Xamarin.Forms repository.

Right now, I believe the items in the CollectionView have to determine their own size, which are then positioned by the CollectionView control. So I need the items to resize themselves based on the screen size and the number of elements being displayed.

**Comment by davidbritch** [comment]
I'll close this issue here, as the conversation can continue on your enhancement request in the engineering repo.
