### ISSUE TITLE
When I tabbed on Swift Developers, I had beed directed to this page

### ISSUE THREAD

**Issue by JawadJaber** [MicrosoftDocs/xamarin-docs#2104]
I tried to access Objective C, and Swift pages from the navigation bar at left (https://docs.microsoft.com/en-us/xamarin/get-started/). Objective C worked fine and directed me to this page. however, Swift page also directed me to this page. I believe the page must mention something about Swift lang.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ccf3321d-3945-a973-66e7-fb38ea30e4fd
* Version Independent ID: dfc849ff-6de9-101e-5af5-64a5d00196c6
* Content: [Xamarin for Objective-C Developers - Xamarin](https://docs.microsoft.com/en-us/xamarin/ios/get-started/objective-c-developers/)
* Content Source: [docs/ios/get-started/objective-c-developers/index.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/ios/get-started/objective-c-developers/index.md)
* Product: **xamarin**
* Technology: **xamarin-ios**
* GitHub Login: @conceptdev
* Microsoft Alias: **crdun**

**Comment by conceptdev** [comment]
Can you please share which link you clicked on that mentioned Swift? We do not currently have any Swift guidance, so that link is in error. Thanks.

**Comment by JawadJaber** [comment]
![Screen Shot 2019-09-15 at 4 39 43 PM](https://user-images.githubusercontent.com/7624547/64922402-8755d300-d7d7-11e9-8d75-8e1c79560f77.png)
Image attached, it is right at left-down.

**Comment by conceptdev** [comment]
Thanks for the clarification - I have removed that entry until we have Swift-specific content.
