### ISSUE TITLE
Alternate download locations

### ISSUE THREAD

**Issue by regolas** [MicrosoftDocs/xamarin-docs#2105]
My company will not allow downloads from google (dl.google.com). However, they did provide me the 4 files needed to do the download. Is there a method that could be shown here to allow these files to be installed from an alternate location?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 946e7563-c5a9-14e8-323e-c557ebc9cfe0
* Version Independent ID: 40cb0a2d-bfa1-8b7d-64f5-076c6067750c
* Content: [Xamarin Firewall Configuration Instructions - Xamarin](https://docs.microsoft.com/en-us/xamarin/get-started/installation/firewall#feedback)
* Content Source: [docs/get-started/installation/firewall.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/get-started/installation/firewall.md)
* Product: **xamarin**
* Technology: **xamarin-crossplatform**
* GitHub Login: @conceptdev
* Microsoft Alias: **crdun**

**Comment by conceptdev** [comment]
We do not currently have an offline installer, however we do have other customers with similar needs. You can [provide a feature suggestion](https://docs.microsoft.com/en-us/visualstudio/ide/suggest-a-feature?view=vs-2019) online, and describe your specific use-case, to be considered for future releases.
Thanks for your feedback.
