### ISSUE TITLE
Missing link

### ISSUE THREAD

**Issue by granth7** [MicrosoftDocs/xamarin-docs#2114]
The link to custom font iOS instructions (https://blog.xamarin.com/custom-fonts-in-ios/) redirects to the Xamarin blog.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe0572c4-91be-fc86-d130-242db2bf470b
* Version Independent ID: 1238fdd7-c378-6d0d-654e-55656a70d386
* Content: [Fonts in Xamarin.Forms - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/text/fonts#feedback)
* Content Source: [docs/xamarin-forms/user-interface/text/fonts.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/text/fonts.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @granth7 

I've fixed the link in a PR that will go live later. In the meantime, the correct link is https://devblogs.microsoft.com/xamarin/custom-fonts-in-ios/
