### ISSUE TITLE
How can we prepopulate AppDataDIrecotry on build?

### ISSUE THREAD

**Issue by matjazmav** [MicrosoftDocs/xamarin-docs#2118]
I have "config.json" file in shared code project. How can I move it to the "AppDataDirecotry" on build?

Can I set "Build Action" to "Content"? Can you provide example?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: db0515b3-ad35-c915-dc5a-d8b7c22b4dbb
* Version Independent ID: b0acdf74-2410-73bf-2744-3e55c4984ca9
* Content: [FileSystem.AppDataDirectory Property (Xamarin.Essentials)](https://docs.microsoft.com/en-us/dotnet/api/xamarin.essentials.filesystem.appdatadirectory?view=xamarin-essentials#feedback)
* Content Source: [docs/en/Xamarin.Essentials/FileSystem.xml](https://github.com/xamarin/Essentials/blob/live/docs/en/Xamarin.Essentials/FileSystem.xml)
* Product: **xamarin**
* Technology: **xamarin-essentials**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by jamesmontemagno** [comment]
The App Data Directory is a folder on disk that is created for your app by the OS. So no way to pre-populate it unless you unpack it and save the files there.

You can though use the App Package File API -> https://docs.microsoft.com/en-us/xamarin/essentials/file-system-helpers?context=xamarin%2Fandroid&tabs=android

This is in the Android Assets folder, iOS Resources (BundleResource), and UWP any Content.
