### ISSUE TITLE
Missing using statement?

### ISSUE THREAD

**Issue by nickidw** [MicrosoftDocs/xamarin-docs#212]
Unless I missed a piece of code there is a using statement missing for Android.Content in order to use the Intent class.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 672a11c0-fb8f-4b75-f42c-23429f52c35a
* Version Independent ID: 51f9c1e4-fa5d-b6ac-6081-c4c3189191f7
* Content: [Hello, Android Multiscreen: Quickstart - Xamarin](https://docs.microsoft.com/en-gb/xamarin/android/get-started/hello-android-multiscreen/hello-android-multiscreen-quickstart?tabs=vsmac#feedback)
* Content Source: [docs/android/get-started/hello-android-multiscreen/hello-android-multiscreen-quickstart.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/android/get-started/hello-android-multiscreen/hello-android-multiscreen-quickstart.md)
* Service: **unspecified**
* GitHub Login: @mgmclemore
* Microsoft Alias: **mamcle**

**Comment by mgmclemore** [comment]
Hi @nickidw, you are correct, good catch!  This missing step for adding the `using` statement will be added to the doc and published soon. Thank you for pointing this out!

**Comment by ShazwieHar** [comment]
will this series ever be updated?
