### ISSUE TITLE
Instructions for linux GUI (GTK) uses windows only Visual Studio

### ISSUE THREAD

**Issue by trampster** [MicrosoftDocs/xamarin-docs#2121]
I'm not going to develop my GTK# user interface on windows, this makes zero sense. I need to develop it on target, that is on linux, so these instructions need to use either MonoDevelop or vscode. Or Microsoft needs to port Visual Studio to linux.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 66853f3d-854e-08ad-84d2-b2a98f88c48b
* Version Independent ID: 77ea362d-ef46-f426-3d4a-5f99e39ce160
* Content: [GTK# Platform Setup - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/platform/other/gtk?tabs=windows#feedback)
* Content Source: [docs/xamarin-forms/platform/other/gtk.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/platform/other/gtk.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by conceptdev** [comment]
Thanks for your feedback. The GTK# platform is community-supported, and is still in Preview.  Documentation may be updated once the product is considered stable.
