### ISSUE TITLE
Availability in VS2019 Community Edition

### ISSUE THREAD

**Issue by boggEight** [MicrosoftDocs/xamarin-docs#2125]
Is this available in VS2019 community edition?

I'm using vs2019 16.2.5 community edition, I was able to install Xamarin.Forms HotReload 1.4 from Extension Manager.  I was able to install and enabled it and messagebox confirmed that its listening to port 15001, also I've seen the thunder icon now in my toolbar.  however when debugging my xamarin.forms 4.2 on android (8.1) emulator I was not able to see any Hot Reload stuffs in my screen. Is there anything I miss? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b74184fd-ca8a-11fa-ed37-91235fc59401
* Version Independent ID: 87f197b8-20c6-4825-18e4-86562bb2523c
* Content: [XAML Hot Reload for Xamarin.Forms - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/xaml/hot-reload?WT.mc_id=hrpreview-xamarinblog-maleger#feedback)
* Content Source: [docs/xamarin-forms/xaml/hot-reload.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/xaml/hot-reload.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @maddyleger1
* Microsoft Alias: **maleger**

**Comment by jamesmontemagno** [comment]
Yes, absolutely! It is available today in preview in VS 2019 16.3 and VS for Mac 8.3

**Comment by jamesmontemagno** [comment]
The extension you installed is not from us. There is nothing to install as it is included inside of VS :)

**Comment by boggEight** [comment]
Thanks, I upgraded it now to version 16.3.5 and it got loaded now.
