### ISSUE TITLE
The code snippet of the event trigger doesn't explain the use of the TriggerAction properties

### ISSUE THREAD

**Issue by mshwf** [MicrosoftDocs/xamarin-docs#2129]
The article mentions:

> Optionally expose properties that can be set in the XAML when the trigger is declared (such as Anchor, Scale, and Length in this example).

But the accompanying snippet code doesn't illustrate this, and also the following statement:

> The properties exposed by the trigger action can be set in the XAML declaration as follows:

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a3ff3ffd-9177-76ff-ac6e-7cb439750203
* Version Independent ID: 8e881672-c9ff-354c-fb22-97a8d1af2d72
* Content: [Xamarin.Forms Triggers - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/triggers)
* Content Source: [docs/xamarin-forms/app-fundamentals/triggers.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/app-fundamentals/triggers.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @mshwf 

Thanks for pointing this out. My guess is that at some point in the past this doc referenced the `VisualElementPopTriggerAction` class from the sample application, which does consume the `Anchor`, `Scale`, and `Length` properties. I originally set out to restore this example to the doc, but it's pretty abstract. Instead, I've updated the doc to remove references to the properties concerned.

This change will go live later.
