### ISSUE TITLE
Does it support Xamarin.Forms?

### ISSUE THREAD

**Issue by yanxiaodi** [MicrosoftDocs/xamarin-docs#2137]
I downloaded and installed the Profiler but I didn't find it for my UWP app based on Xamarin.Forms. Does it support Xamarin.Forms?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e9e9c055-6a8e-5e81-00c7-e57c8c912a8b
* Version Independent ID: 28ac7239-a6c2-e31e-d423-b5268fd95c65
* Content: [Xamarin Profiler - Xamarin](https://docs.microsoft.com/en-us/xamarin/tools/profiler/?tabs=windows)
* Content Source: [docs/tools/profiler/index.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/tools/profiler/index.md)
* Product: **xamarin**
* Technology: **xamarin-crossplatform**
* GitHub Login: @conceptdev
* Microsoft Alias: **crdun**

**Comment by conceptdev** [comment]
You can try [Visual Studio profiling tools](https://docs.microsoft.com/visualstudio/profiling/profiling-feature-tour?view=vs-2019) to look at Windows apps such as UWP.

From the Xamarin Profiler page:

> The Xamarin Profiler a graphical interface for the Mono log profiler, and supports profiling Android, iOS, tvOS, and Mac applications on Mac, and Android, iOS, and tvOS applications on Windows.

Xamarin.Forms is an SDK that runs on various platforms. Use the correct profiling tool for the target platform.
