### ISSUE TITLE
Build error APT0000: No resource found that matches the given name (at 'icon' with value '@mipmap/Icon').

### ISSUE THREAD

**Issue by yeiacatl** [MicrosoftDocs/xamarin-docs#214]
Workaround/fix: add this line to AssemblyInfo.cs:

`[assembly: Application(Icon = "@mipmap/icon")]`

Source: https://stackoverflow.com/questions/47085360/error-no-resource-found-that-matches-the-given-name-at-icon-with-value-mip

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 660b0f7c-9941-2db3-63bf-fc8a97765b1e
* Version Independent ID: 5aa1e6f6-534a-05b9-c44a-1f62b24c201a
* Content: [Hello, Android: Quickstart - Xamarin](https://docs.microsoft.com/en-us/xamarin/android/get-started/hello-android/hello-android-quickstart?tabs=vswin)
* Content Source: [docs/android/get-started/hello-android/hello-android-quickstart.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/android/get-started/hello-android/hello-android-quickstart.md)
* Service: **unspecified**
* GitHub Login: @mgmclemore
* Microsoft Alias: **mamcle**

**Comment by mgmclemore** [comment]
Hi @yeiacatl, thanks for you feedback! The latest Visual Studio templates are no longer providing a default icon.png (which would explain the error) -- we'll update this topic so that it is in sync.

**Comment by yeiacatl** [comment]
I should've been more clear: I downloaded and added the icons manually, as the instructions state, then in the Project properties I selected the icon from the dropdown, compiled, but the build failed with that error in the title. I was able to workaround this by adding the AssemblyInfo line, and now it builds.

**Comment by mgmclemore** [comment]
Hi @yeiacatl, understood!  The topic states that Visual Studio provides a default icon, but this is no longer true -- it could be that this change to the template is responsible for the workaround that you had to apply. We'll include your suggestion in the updated topic. Thanks again!
