### ISSUE TITLE
How to add multiple custom pins to customMap.Pins ?

### ISSUE THREAD

**Issue by LSparkzwz** [MicrosoftDocs/xamarin-docs#2140]
Here you create a "customMap.CustomPins" list with a single "pin", then you manually add the single pin to "customMap.Pins" with "Add". What if I have a long list "customPins" of CustomPin though? How can I add all them to  "customMap.Pin"?
Doing "customMap.Pins = customPins;" doesn't work because it's readable only.
I can't use AddRange either because Pins is an IList.
Is the only way to cycle through the list with a foreach and run "Add" every time?

`
public MapPage ()
{
  ...
  var pin = new CustomPin { . . . };

  customMap.CustomPins = new List&lt;CustomPin&gt; { pin };
  customMap.Pins.Add (pin);
  customMap.MoveToRegion (MapSpan.FromCenterAndRadius (
    new Position (37.79752, -122.40183), Distance.FromMiles (1.0)));
}
`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 591d1079-dec9-5797-eb4f-4d11b56fcbd9
* Version Independent ID: 0169a2c9-a004-d5fd-7a24-855664f2d8b5
* Content: [Customizing a Map Pin - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/custom-renderer/map/customized-pin#feedback)
* Content Source: [docs/xamarin-forms/app-fundamentals/custom-renderer/map/customized-pin.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/app-fundamentals/custom-renderer/map/customized-pin.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @LSparkzwz 

Yes, but you can condense it into a single line of code.

Given a `List<CustomPin>` you can add them to `customMap.Pins` using the `ForEach` method on the `List<CustomPin>` e.g.

```
        List<CustomPin> customPins = new List<CustomPin>
        {
            new CustomPin
            {
               ...
            },
            new CustomPin
            {
                ...
            },
            new CustomPin
            {
                ...
            }
        };

customMap.CustomPins = customPins;
customPins.ForEach(p => customMap.Pins.Add(p));
```

Hope this helps!
