### ISSUE TITLE
Local Image Display

### ISSUE THREAD

**Issue by BobMolloy** [MicrosoftDocs/xamarin-docs#2141]
The sample code just didn't work. The simulators kept displaying the ape picture instead of the Xamarin logo. I finally scrapped the app and rebuilt, skipping the remote image part. I also renamed XamarinLogo.png to xamarinlogo.png and specified the fully qualified name in the XAML Image element.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 679634c0-a0c6-cc03-c50f-6d22ce71c099
* Version Independent ID: 874062b9-a51b-a10d-4d27-d3811fa9b56b
* Content: [Xamarin.Forms Image Tutorial - Xamarin](https://docs.microsoft.com/en-us/xamarin/get-started/tutorials/image/index?tutorial-step=4&tabs=vswin)
* Content Source: [docs/get-started/tutorials/image/index.yml](https://github.com/MicrosoftDocs/xamarin-docs-pr/blob/live/docs/get-started/tutorials/image/index.yml)
* Product: **xamarin**
* Technology: **xamarin-crossplatform**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @BobMolloy 

Which platform is your problem with? iOS/Android or both?

If you run the sample application (https://docs.microsoft.com/samples/xamarin/xamarin-forms-samples/getstarted-tutorials-imagetutorial/) that accompanies this tutorial, it works fine on both platforms.
