### ISSUE TITLE
Android app fails

### ISSUE THREAD

**Issue by BobMolloy** [MicrosoftDocs/xamarin-docs#2145]
With this message after selecting a second option:

Attempted to finish an input event but the input event receiver has already been disposed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a4cfe01b-2f14-16fa-2e67-653c806ee263
* Version Independent ID: a1bdb0d6-b428-bb73-b719-da0ff098ac9a
* Content: [Xamarin.Forms Pop-ups Tutorial - Xamarin](https://docs.microsoft.com/en-us/xamarin/get-started/tutorials/pop-ups/index?tutorial-step=3&tabs=vswin)
* Content Source: [docs/get-started/tutorials/pop-ups/index.yml](https://github.com/MicrosoftDocs/xamarin-docs-pr/blob/live/docs/get-started/tutorials/pop-ups/index.yml)
* Product: **xamarin**
* Technology: **xamarin-crossplatform**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @BobMolloy 

Try running the accompanying sample for this tutorial (https://docs.microsoft.com/samples/xamarin/xamarin-forms-samples/getstarted-tutorials-popupstutorial/) and see if it works for you. It works fine for me.
