### ISSUE TITLE
VisualElement Elevation on Android broken

### ISSUE THREAD

**Issue by SOliasS** [MicrosoftDocs/xamarin-docs#2146]
Does not work anymore
if this is used:
`this.ElevationButton.On<Android>().SetElevation(20);`
Xamarin does not build.
![image](https://user-images.githubusercontent.com/14180046/65404985-2b90d880-dddb-11e9-9fa1-346187764198.png)

In Xaml:
![image](https://user-images.githubusercontent.com/14180046/65405021-3cd9e500-dddb-11e9-95ae-79352f42f27c.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0e2ccd04-96eb-bee8-3a68-95a590291cb2
* Version Independent ID: 366097b0-7c57-279e-f346-c7e06cb53ed4
* Content: [VisualElement Elevation on Android - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/platform/android/visualelement-elevation#feedback)
* Content Source: [docs/xamarin-forms/platform/android/visualelement-elevation.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/platform/android/visualelement-elevation.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @SOliasS 

It looks like you're not including all the relevant `using` statements. You need:

```
using Xamarin.Forms;
using Xamarin.Forms.PlatformConfiguration;
using Xamarin.Forms.PlatformConfiguration.AndroidSpecific;
```

Try the sample yourself (https://docs.microsoft.com/samples/xamarin/xamarin-forms-samples/userinterface-platformspecifics/), which works, and let me know.

**Comment by SOliasS** [comment]
Strange something in my project seems to overrite the android namespace? don´t know what or how but if i declare `using TestAndroid= Xamarin.Forms.PlatformConfiguration;`
` aboveButton.On<TestAndroid.Android>().SetElevation(10);`
it works.

**Comment by davidbritch** [comment]
@SOliasS Glad you got it working :)
