### ISSUE TITLE
Confusion about when to stop

### ISSUE THREAD

**Issue by LindaLawton** [MicrosoftDocs/xamarin-docs#2147]
I was following along with this page and everything was fine.  Then I hit the second about Accelerating with HAXM where by I just kept going.   There was nothing at the end of the Hyper-v section to say that 

Well you are done now you have hyper v set up you can continue with the next page you dont need to go check out Haxm.

I was a little confused because when i tried to install HAXM virtualization engine it said i needed to turn off Hyper-v which didnt make any sense at all as I had just been instructed to install it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4e37d642-2051-8d70-9968-dfb484122a6a
* Version Independent ID: 178ea80c-2b99-0c44-eeb6-9db319439b33
* Content: [Hardware Acceleration for Emulator Performance (Hyper-V & HAXM) - Xamarin](https://docs.microsoft.com/en-us/xamarin/android/get-started/installation/android-emulator/hardware-acceleration?pivots=windows)
* Content Source: [docs/android/get-started/installation/android-emulator/hardware-acceleration.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/android/get-started/installation/android-emulator/hardware-acceleration.md)
* Product: **xamarin**
* Technology: **xamarin-android**
* GitHub Login: @conceptdev
* Microsoft Alias: **crdun**

**Comment by JonDouglas** [comment]
Thanks for the feedback @LindaLawton! We're actively looking for ways to make this more clear to our users with regards to which hypervisor option to choose for their Android emulator. 

Do you by chance have any ideas with regards to what you'd like to see in the documentation to prevent you from continuing to the second hypervisor section after reading the introduction?

**Comment by LindaLawton** [comment]
Ideally i would split it into two separate documents.  One for Hyper-v and one for HAXM. When i write tutorials I normally like to keep them to single topic.  

Alternately you could just put something like the following at the bottom of the hyper v section.   

>You can now run your emulator and dont need to continue with the HAXM section.

**Comment by shsohel** [comment]
Thanks for tips. But My Desktop PC So Slower Version.  
Processor: Intel(R) Pentium(R) CPU G3240@3.10 GHz
RAM: 4.00 GM
SystemType: 64 BIT
Windows 10 Enterprise .
Please, give me suggestion how could to get rid the problems . How can I faster performance of my PC?
