### ISSUE TITLE
Update for VS 2019 please?

### ISSUE THREAD

**Issue by TravelingGeek** [MicrosoftDocs/xamarin-docs#2148]
Great article as far as I could get.  I would love to see this updated for Visual Studio 2019.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 02a2221e-ff55-cfe0-9f24-382101584c80
* Version Independent ID: 260000a6-cee8-487a-2fbd-2dfdd0864735
* Content: [Part 1. Getting Started with XAML - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/xaml/xaml-basics/get-started-with-xaml?tabs=windows#feedback)
* Content Source: [docs/xamarin-forms/xaml/xaml-basics/get-started-with-xaml.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/xaml/xaml-basics/get-started-with-xaml.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @TravelingGeek 

I've just updated it to VS2019 screenshots/explanation. These changes will go live later today.
