### ISSUE TITLE
Great tutorials

### ISSUE THREAD

**Issue by BobMolloy** [MicrosoftDocs/xamarin-docs#2151]
I somehow got started with the MSLearn tutorials for Xamarin. They went too deep, too quickly. This set of tutorials is where I should have started. They are well crafted and carefully designed, so I feel that I learned a lot. Aside from a couple of ID-10T errors, the whole process was smooth and rewarding.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2db7abd5-24b6-7a5e-9a39-0981723923cf
* Version Independent ID: eae9135a-ed88-333c-9f94-2fb600bf8f80
* Content: [Xamarin.Forms Web Service Tutorial - Xamarin](https://docs.microsoft.com/en-us/xamarin/get-started/tutorials/web-service/index?tutorial-step=4&tabs=vswin)
* Content Source: [docs/get-started/tutorials/web-service/index.yml](https://github.com/MicrosoftDocs/xamarin-docs-pr/blob/live/docs/get-started/tutorials/web-service/index.yml)
* Product: **xamarin**
* Technology: **xamarin-crossplatform**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Thanks for your kind words @BobMolloy
