### ISSUE TITLE
Please clarify ImageButton vs. Button + ImageSource

### ISSUE THREAD

**Issue by mfeingol** [MicrosoftDocs/xamarin-docs#2158]
It's entirely unclear from the documentation when one would use `ImageButton` and when one would use `Button` with the `ImageSource` property. Further, when would one use `ImageButton` with a `FontImageSource` vs a `Button` with `Text` and `FontFamily`?  Thanks.

**Comment by davidbritch** [comment]
Hi @mfeingol 

A `Button` is intended to display (small) icons as images. An `ImageButton` is intended to display images of arbitrary size (e.g. small to large).

Both `Button` and `ImageButton` can display font icons via `FontImageSource` objects. Font icons tend to be small and so can equally be displayed by both `Button` and `ImageButton` objects.
