### ISSUE TITLE
Instructions need to be updated for XCode 11 without Application Loader

### ISSUE THREAD

**Issue by wadebaird** [MicrosoftDocs/xamarin-docs#2163]
Xcode 11 removed Application Loader so these instructions no longer apply. We need instructions on how to upload a Xamarin app from a windows machine with the absence of Application Loader.

This is a blocking issue for our team.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bb327a64-010d-dba8-5ebc-546892d739af
* Version Independent ID: 48a24297-7b8f-b1b2-7b25-44f40fe33eac
* Content: [Publishing Xamarin.iOS apps to the App Store - Xamarin](https://docs.microsoft.com/en-us/xamarin/ios/deploy-test/app-distribution/app-store-distribution/publishing-to-the-app-store?tabs=windows)
* Content Source: [docs/ios/deploy-test/app-distribution/app-store-distribution/publishing-to-the-app-store.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/ios/deploy-test/app-distribution/app-store-distribution/publishing-to-the-app-store.md)
* Product: **xamarin**
* Technology: **xamarin-ios**
* GitHub Login: @conceptdev
* Microsoft Alias: **crdun**

**Comment by conceptdev** [comment]
Thanks for the feedback @wadebaird.

As you mentioned, Application Loader is no longer included in Xcode 11 (mentioned in the [release notes](https://developer.apple.com/documentation/xcode_release_notes/xcode_11_release_notes)). One option that page offers is using `xcodebuild` or `xcrun altool` from the Terminal on macOS.

There are some [forum mentions](https://forums.developer.apple.com/thread/118304), and the usage is available from the command line. I have not yet used this myself, I just want to offer some alternatives while we get the documentation updated.

```
$ xcrun altool
Copyright (c) 2009-2019, Apple Inc. Version 4.00.1181

Usage: altool --validate-app -f <file> -t <platform> -u <username> {[-p <password>] | --apiKey <api_key> --apiIssuer <issuer_id>}
       altool --upload-app -f <file> -t <platform> -u <username> {[-p <password>] | --apiKey <api_key> --apiIssuer <issuer_id>}
       altool --notarize-app -f <file> --primary-bundle-id <bundle_id> -u <username> {[-p <password>] | --apiKey <api_key> --apiIssuer <issuer_id>} [--asc-provider <provider_shortname>]
       altool --notarization-info <uuid> -u <username> {[-p <password>] | --apiKey <api_key> --apiIssuer <issuer_id>}
       altool --notarization-history <page> -u <username> {[-p <password>] | --apiKey <api_key> --apiIssuer <issuer_id>} [--asc-provider <provider_shortname>]
       altool --list-apps -u <username> {[-p <password>] | --apiKey <api_key> --apiIssuer <issuer_id>}
       altool --store-password-in-keychain-item <name_for_keychain_item> -u <username> -p <password>
```

**Comment by conceptdev** [comment]
@wadebaird the documentation has now been updated:

https://docs.microsoft.com/xamarin/ios/deploy-test/app-distribution/app-store-distribution/publishing-to-the-app-store?tabs=macos#build-and-submit-your-app

It describes a new feature in the latest version of **Visual Studio for Mac** that replaces Application Loader. The Windows information has not yet been updated, but you should be able to complete your submission in macOS.

**Comment by RhomGit** [comment]
Its probably premature to close this as it really isn't fixed nor addressed in any realistic manner.

**Comment by jimmgarrido** [comment]
We added a publishing workflow to Visual Studio 2019 that replaces the need for Application Loader. 

The docs have been updated to describe the new workflow: https://docs.microsoft.com/xamarin/ios/deploy-test/app-distribution/app-store-distribution/publishing-to-the-app-store#build-and-submit-your-app

**Comment by chadgruka** [comment]
I appreciate the updates, however after a successful Archive of an iOS app, the Distribute button is not present. Any ideas?
