### ISSUE TITLE
Nugetizer 300 no longer generates multi-platform projects

### ISSUE THREAD

**Issue by MouthOfMadness** [MicrosoftDocs/xamarin-docs#2164]
I downloaded the vsix, I installed it to 2017, I clicked the template to generate a multi-platform library, I get the following errors:

Blah, blah, blah, failed to install packages: 15.0_6E3324E5\EXTENSIONS\YARD5RV4.JRX\Packages:
Nuget.Build.Packaging.0.2.5.-pr172.11 : Package restore failed. Rolling back package changes for 'Library2.Nuget'

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 44cfe14b-198c-56d5-0b63-de00dd08bafe
* Version Independent ID: 39eea43d-d7b5-1659-1583-dc23d099c9f8
* Content: [NuGet Multiplatform Library Projects (aka Nugetizer 3000) - Xamarin](https://docs.microsoft.com/en-us/xamarin/cross-platform/app-fundamentals/nuget-multiplatform-libraries/?tabs=windows)
* Content Source: [docs/cross-platform/app-fundamentals/nuget-multiplatform-libraries/index.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/cross-platform/app-fundamentals/nuget-multiplatform-libraries/index.md)
* Product: **xamarin**
* Technology: **xamarin-crossplatform**
* GitHub Login: @conceptdev
* Microsoft Alias: **crdun**

**Comment by conceptdev** [comment]
Hi @MouthOfMadness for product bugs, please report from [within Visual Studio](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2019) so that we get useful product and environment information that can help diagnose the issue. Thanks.
