### ISSUE TITLE
iOS offset encoding

### ISSUE THREAD

**Issue by mrengineer7777** [MicrosoftDocs/xamarin-docs#2165]
This was exactly my issue.  Thank you for the help page!  I set my debug project to ARM64 and now it compiles.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0fb56313-2c64-de22-673c-d0534aea4943
* Version Independent ID: c9fa9166-6090-a71d-b229-87f0eca959aa
* Content: [Compile error: Can not encode offset X in resulting scattered relocation - Xamarin](https://docs.microsoft.com/en-us/xamarin/ios/troubleshooting/questions/error-encode-offset-scattered-relocation#feedback)
* Content Source: [docs/ios/troubleshooting/questions/error-encode-offset-scattered-relocation.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/ios/troubleshooting/questions/error-encode-offset-scattered-relocation.md)
* Product: **xamarin**
* Technology: **xamarin-ios**
* GitHub Login: @chamons
* Microsoft Alias: **chhamo**

**Comment by conceptdev** [comment]
Glad it was useful! Thanks for the kind words.
