### ISSUE TITLE
Outdated Samples

### ISSUE THREAD

**Issue by FreakyAli** [MicrosoftDocs/xamarin-docs#2166]
The sample and the Tutorial are using the Microsoft.Identity.Client library of version 4.0. As I am writing this, the current version is 4.4.0. Many methods have changed. Can we please have an updated sample using the latest version of the library?

Methods unavailable are native eg the below piece of code is not available on native Android:

`AuthenticationContinuationHelper.SetAuthenticationContinuationEventArgs(requestCode, resultCode, data` is not available in the `Microsoft.Identity.Client` namespace

@profexorgeek Can you please take a look into it.

> Document Details
> ⚠ Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.
> 
> ID: 11f5b457-d99a-06d4-d203-f9eeaa27e0d9
> Version Independent ID: b23b3a5d-b63b-dfe1-bb46-94f57c907be5
> Content: Authenticate Users with Azure Active Directory B2C - Xamarin
> Content Source: docs/xamarin-forms/data-cloud/authentication/azure-ad-b2c.md
> Product: xamarin
> Technology: xamarin-forms
> GitHub Login: @davidbritch
> Microsoft Alias: dabritch

**Comment by profexorgeek** [comment]
Hi @FreakyAli,
I have been unable to reproduce this problem. MSAL 4.4 is a minor revision that should not be breaking. I also checked the roadmap/release notes for MSAL (here: https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki) and nothing mentioned should be affecting the methods you referenced.

But to be sure I tested our sample. Here are the steps I took using Visual Studio 2019 for Windows:

- Configured Constants.cs and Android manifest with my Azure test instance info
- Verified that 4.0 worked fine (it did)
- Updated NuGet packages for each project to latest (4.4.0)
- Cleaned solution and wiped bin/obj directories, rebuilt with 4.4.0
- Verified that 4.4.0 worked with no build or runtime errors (it did)

I was able to log in without issues on UWP and Android. I did not test iOS.

If you are having build errors stating that the AuthenticationContinuationHelper is not a recognized class make sure:

- You have the `using Microsoft.Identity.Client;` statement at the top of the Android MainActivity file
- NuGet package for both Android and Shared projects are updated

If that doesn't work, clean your solution, delete your bin/obj directories, and rebuild. It might also be worth deleting your nuget packages directory to force a reresh just in case something bad is cached.

Try that and let me know if you're still having problems.

**Comment by FreakyAli** [comment]
@profexorgeek After looking for more than 2 days I ended up finding the solution in a comment on Stackoverflow or somewhere. Well, the issue was that I was not targeting Android 9.0 in my application and hence these methods were not available. This seems to be the case even when using the MSAL library used by the documentation sample i.e. v4.0. I feel this is an important point too that should be mentioned by the documentation, rest is your call. Thank you very much for your support

**Comment by profexorgeek** [comment]
No problem, glad you found a solution! I'll have to do a little research on that as well and will update the docs, and this issue, once I understand the specifics of why an older Android target is causing problems. Thanks!
