### ISSUE TITLE
Document Out of Date

### ISSUE THREAD

**Issue by PatrickRyder** [MicrosoftDocs/xamarin-docs#2167]
I am trying to change the Deployment Target but can't find this setting on the iOS Build page in the iOS project properties.  In fact, I can't see it in any of the screenshots above either. How do you change the minimum target iOS version?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 636ef44f-3375-0f01-0472-53f424d091e1
* Version Independent ID: 7cb8bf83-305c-a2d2-f73d-308814d688d0
* Content: [Compiling for Different Devices in Xamarin.iOS - Xamarin](https://docs.microsoft.com/en-us/xamarin/ios/deploy-test/compiling-for-different-devices?tabs=windows)
* Content Source: [docs/ios/deploy-test/compiling-for-different-devices.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/ios/deploy-test/compiling-for-different-devices.md)
* Product: **xamarin**
* Technology: **xamarin-ios**
* GitHub Login: @conceptdev
* Microsoft Alias: **crdun**

**Comment by conceptdev** [comment]
Thanks for your feedback @PatrickRyder, the **Deployment Target** is in the **Info.plist** file under **Deployment Info**:

![Screen Shot 2019-09-26 at 9 25 24 AM](https://user-images.githubusercontent.com/199373/65706571-98a4a800-e03f-11e9-803d-70a78f902a86.png)

We will need to update the page to clarify this.

Note that this does not set the _minimum version_ of iOS, this is the compilation target that lets you use APIs up to that OS level. In general you would always set this to the highest available version. If your app uses APIs that may not exist on older versions of iOS that you wish to support, see the [conditional framework usage](https://docs.microsoft.com/en-us/xamarin/ios/deploy-test/compiling-for-different-devices?tabs=macos#conditional-framework-usage) section further down the page.

**Comment by conceptdev** [comment]
Just updated the page with more details, thanks for asking.
