### ISSUE TITLE
The "How Xamarin.Forms works" diagram does not have Windows/UWP

### ISSUE THREAD

**Issue by ghuntley** [MicrosoftDocs/xamarin-docs#2168]
![](https://docs.microsoft.com/en-us/xamarin/get-started/what-is-xamarin-forms-images/xamarin-forms-architecture.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4552b599-04cd-aaca-635c-3ec23e3ecdff
* Version Independent ID: 8c504569-d341-c8d7-a847-bea0a182fd24
* Content: [What is Xamarin.Forms? - Xamarin](https://docs.microsoft.com/en-us/xamarin/get-started/what-is-xamarin-forms?WT.mc_id=twitter#feedback)
* Content Source: [docs/get-started/what-is-xamarin-forms.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/get-started/what-is-xamarin-forms.md)
* Product: **xamarin**
* Technology: **xamarin-crossplatform**
* GitHub Login: @profexorgeek
* Microsoft Alias: **jusjohns**

**Comment by conceptdev** [comment]
The Windows/UWP stack is comparatively boring - it's C# on .NET on Windows. To save space we have focused on the platforms that we felt needed more explaining. You'll be pleased to know we have a version that covers Windows:

![forms-architecture-full](https://user-images.githubusercontent.com/199373/65705939-38613680-e03e-11e9-804d-5126f42c719a.png)

**Comment by aarontoko** [comment]
Microsoft has ceased support for UWP.
