### ISSUE TITLE
Image not showing.

### ISSUE THREAD

**Issue by L0rdMortimer** [MicrosoftDocs/xamarin-docs#2181]
Step 1 and 2 fail to show a picture. If I type a &lt;Label Text="Monkey"/&gt; underneath it shows the text but the picture area is just blank white occupying the 300px HeightRequest.
Step 3 works just fine.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 679634c0-a0c6-cc03-c50f-6d22ce71c099
* Version Independent ID: 874062b9-a51b-a10d-4d27-d3811fa9b56b
* Content: [Xamarin.Forms Image Tutorial - Xamarin](https://docs.microsoft.com/en-us/xamarin/get-started/tutorials/image/?tutorial-step=4&tabs=vswin#feedback)
* Content Source: [docs/get-started/tutorials/image/index.yml](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/get-started/tutorials/image/index.yml)
* Product: **xamarin**
* Technology: **xamarin-crossplatform**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @L0rdMortimer 

I agree that you've uncovered an issue here, on Android. However, it's an issue with the Xamarin.Forms rather than with the tutorial, so I'll follow this up with the engineers.

**Comment by L0rdMortimer** [comment]
Thank You for looking into this!

**Comment by flagamba** [comment]
Hi @L0rdMortimer , I have the same problem !

**Comment by davidbritch** [comment]
Hi @L0rdMortimer and @flagamba 

After talking to the engineers, this is a bug to do with image caching from URLs in Xamarin.Forms 4.2. For more info see:

https://github.com/xamarin/Xamarin.Forms/issues/7751#issuecomment-536694500
https://github.com/xamarin/Xamarin.Forms/issues/7751#issuecomment-536864832

**Comment by davidbritch** [comment]
I'm going to close the issue here, purely because it's an engineering issue rather than a docs issue.
