### ISSUE TITLE
404 – Page not found

### ISSUE THREAD

**Issue by ghost** [MicrosoftDocs/xamarin-docs#2182]
@luizpires commented on [Sun Sep 29 2019](https://github.com/MicrosoftDocs/xamarin-docs.pt-br/issues/32)

By clicking on the GridLayoutDemo link (example) you get 404 - Page not found.

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: 6c7acf3a-9bf8-b5a9-1f9d-4bd91296355d
* Version Independent ID: 13c644dd-acda-2457-74d3-a17e82ad90d1
* Content: [GridLayout - Xamarin](https://docs.microsoft.com/pt-br/xamarin/android/user-interface/layouts/grid-layout#feedback)
* Content Source: [docs/android/user-interface/layouts/grid-layout.md](https://github.com/MicrosoftDocs/xamarin-docs.pt-br/blob/live/docs/android/user-interface/layouts/grid-layout.md)
* Product: **xamarin**
* Technology: **xamarin-android**
* GitHub Login: @conceptdev
* Microsoft Alias: **crdun**

---

@srvbpigh commented on [Sun Sep 29 2019](https://github.com/MicrosoftDocs/xamarin-docs.pt-br/issues/32#issuecomment-536303872)

Hello, @luizpires
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by lichasu** [comment]
I moved this issue here because a link is getting 404.

Thanks!

**Comment by james-alt** [comment]
@davidbritch @conceptdev I think I've found what the correct link should be, but this seems to be a problem in both the Brazilian language as well as the English version of this document. Before I open 40 pull requests, is there a better process for this or does it need to be fixed for every language version of this document? Happy to do it but I didn't want to cause excess work for the team and myself.

**Comment by conceptdev** [comment]
all the localized pages are based on the English version, so you just have to fix in one place 🙂 the time for the fix to propagate across the other languages will vary, but it will happen!

**Comment by profexorgeek** [comment]
This appears to be fixed but not closed. I tested the page in question and the sample link is working as expected. Closing this now.
