### ISSUE TITLE
Note about experimental feature.

### ISSUE THREAD

**Issue by idrish-rishabhsoft** [MicrosoftDocs/xamarin-docs#2184]
Email attachment feature is experiment so, this page should contain some kind of note about it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 51ff7357-2cd8-7988-ed3c-de156cc18211
* Version Independent ID: ff242941-6d92-9523-bd73-ec03dbcb095d
* Content: [Xamarin.Essentials: Email - Xamarin](https://docs.microsoft.com/en-us/xamarin/essentials/email?context=xamarin%2Fandroid&tabs=ios#feedback)
* Content Source: [docs/essentials/email.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/essentials/email.md)
* Product: **xamarin**
* Technology: **xamarin-essentials**
* GitHub Login: @jamesmontemagno
* Microsoft Alias: **jamont**

**Comment by jamesmontemagno** [comment]
It is no longer experimental, we dropped the flag in 1.3 :)
