### ISSUE TITLE
Plist keys

### ISSUE THREAD

**Issue by viktorszekeress** [MicrosoftDocs/xamarin-docs#2189]
At Application Setup -> 5. section you mention to add either of 2 keys:
`NSLocationAlwaysUsageDescription`
`NSLocationWhenInUseUsageDescription`
According to [stackoverflow thread](https://stackoverflow.com/questions/44424092/location-services-not-working-in-ios-11), we need to add both or even new key `NSLocationAlwaysAndWhenInUseUsageDescription`.

Could you bring some light into this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3869aaed-63b6-64b5-b817-0331748f554d
* Version Independent ID: 0345d352-6ebb-b239-cdfe-1a562bd955ca
* Content: [Walkthrough - Background Location in Xamarin.iOS - Xamarin](https://docs.microsoft.com/en-us/xamarin/ios/app-fundamentals/backgrounding/ios-backgrounding-walkthroughs/location-walkthrough)
* Content Source: [docs/ios/app-fundamentals/backgrounding/ios-backgrounding-walkthroughs/location-walkthrough.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/ios/app-fundamentals/backgrounding/ios-backgrounding-walkthroughs/location-walkthrough.md)
* Product: **xamarin**
* Technology: **xamarin-ios**
* GitHub Login: @conceptdev
* Microsoft Alias: **crdun**

**Comment by conceptdev** [comment]
You're right @viktorszekeress - that additional key has been added to iOS since this doc was originally written. Thanks for letting us know!
