### ISSUE TITLE
PLEASE MAKE IT CLEARER THAT THIS IS NOT SUPPORTED FOR XAMARIN UWP

### ISSUE THREAD

**Issue by terriblememory** [MicrosoftDocs/xamarin-docs#2192]
I have just wasted hours trying to figure out why it wasn't working. This should be in bold at the top of the page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b74184fd-ca8a-11fa-ed37-91235fc59401
* Version Independent ID: 87f197b8-20c6-4825-18e4-86562bb2523c
* Content: [XAML Hot Reload for Xamarin.Forms - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/xaml/hot-reload#feedback)
* Content Source: [docs/xamarin-forms/xaml/hot-reload.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/xaml/hot-reload.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @maddyleger1
* Microsoft Alias: **maleger**

**Comment by yshteinm** [comment]
Thank you for posting this.

**Comment by chrisevans9629** [comment]
Yes this needs to be made clear.  I ran into this issue as well.  Waste of time.

**Comment by Hyoe** [comment]
THIS!
Is there a timeline for UWP hot reloading support?

**Comment by chkn** [comment]
This is a great point. We will look at clarifying the messaging in the documentation. In the meantime, if XAML Hot Reload for Xamarin.Forms UWP projects is important to you, please upvote here if you haven't already: https://developercommunity.visualstudio.com/content/idea/661682/xaml-hot-reload-for-xamarinforms-on-uwp.html

This will help us prioritize future work. Thanks!

**Comment by TommyBeaton** [comment]
YES! Especially when it says that Hot Reload is available... 

Thanks for posting this!

**Comment by conceptdev** [comment]
Added a note at the top, and a bullet in the limitations. Keep an eye on the page for future updates.
