### ISSUE TITLE
Wrong reference link for ScaleTo

### ISSUE THREAD

**Issue by BioTurboNick** [MicrosoftDocs/xamarin-docs#2198]
"ScaleTo animates the Scale property of a VisualElement." &lt;-- The link should be to docs for ScaleTo, but instead links to Scale.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5fb76e26-b365-76c2-6a8c-c35c03e7fb2b
* Version Independent ID: 9cefc858-4798-c05f-f7ae-7dedf7e5522a
* Content: [Simple Animations in Xamarin.Forms - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/animation/simple)
* Content Source: [docs/xamarin-forms/user-interface/animation/simple.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/animation/simple.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @BioTurboNick 

Thanks for pointing this out. I've fixed it in a PR that will go live later today.
