### ISSUE TITLE
ContentView Sample Link

### ISSUE THREAD

**Issue by erezbm** [MicrosoftDocs/xamarin-docs#2199]
The sample link markdown on the ContentView description is missing a closing parentheses.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 07b7fe9d-eda5-ea03-1f95-b2ddcea26ec5
* Version Independent ID: 3c89f3d3-65f3-08d7-f0a4-bce5442221a8
* Content: [Xamarin.Forms Layouts - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/controls/layouts#feedback)
* Content Source: [docs/xamarin-forms/user-interface/controls/layouts.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/controls/layouts.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @erezbm 

Thanks for pointing this out. I've just fixed it in a PR that will go live later today.
