### ISSUE TITLE
Colors.xml breaks, but color.xml doesn't

### ISSUE THREAD

**Issue by Aphire** [MicrosoftDocs/xamarin-docs#220]
I found following this documentation to the letter ended with me having a strange NullReferenceException when I tried to launch this.
I believe this is due to the filename for color definition being entitled "colors.xml" however in the style.xml file, it points at: @color/ (note the missing S on the end)

Once I updated my colors.xml file to color.xml everything worked as expected.
This was using Xamarin.Forms NuGet version 2.5.1.444934

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1da34509-8080-6e59-cebb-ac8aceb27952
* Version Independent ID: 082801dc-e5d2-0f68-141d-19b5cf430e90
* Content: [Adding AppCompat and Material Design - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/platform/android/appcompat#feedback)
* Content Source: [docs/xamarin-forms/platform/android/appcompat.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/platform/android/appcompat.md)
* Service: **unspecified**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by topgenorth** [comment]
One possibility to this problem - the filenames of Android resource files has to be lower case (this is an Android requirement, not a Xamarin.Android one). Is it possible that the resource file was named `Colors.xml` (as opposed to `colors.xml`)?  If you renamed the file from `Colors.xml` to `color.xml` the subtle change of case might be what fixed the issue.

**Comment by Aphire** [comment]
It's certainly a possibility, however I've just tried with both `Colors.xml`, `color.xml` and `colors.xml` with success each time... I shall try some build/rebuilds and the old delete obj/bin trick and see if I can get any other outcome and update.

Thanks!

**Comment by Aphire** [comment]
Unable to reliably replicate, sometimes changing, cleaning/deleting bin and obj folders seems to cause the issues, othertimes it fix's it. 

Assume one of Xamarins many weird moodswings. Will close issue now, apologies for wasting time opening it.

**Comment by topgenorth** [comment]
No need to apologize, and I'm sorry to hear that this behaviour is so sporadic. If something happens like this again, I would encourage you to report the issue at [Visual Studio Developer Community](https://developercommunity.visualstudio.com). This will bring it to the attention of the Xamarin developers.
