### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by valentinba** [MicrosoftDocs/xamarin-docs#2200]
Shouldn't IsTapStop be IsTabStop?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c1361326-9c23-642d-57f2-988ad4e29f6a
* Version Independent ID: fd9ea4b8-eb96-31dc-602a-24e5f6746fc0
* Content: [Keyboard Accessibility - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/accessibility/keyboard#feedback)
* Content Source: [docs/xamarin-forms/app-fundamentals/accessibility/keyboard.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/app-fundamentals/accessibility/keyboard.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by valentinba** [comment]
Thanks for fixing, but I think there's another occurrence of IsTapStop in the file...

**Comment by davidbritch** [comment]
Hi @valentinba 

Thanks for pointing this out. I've just fixed it in a PR that will go live later today.
