### ISSUE TITLE
Typo: "SimpleCirle"

### ISSUE THREAD

**Issue by cmeil** [MicrosoftDocs/xamarin-docs#2206]
From the page's HTML source: 
&lt;p&gt;The &lt;a href="https://github.com/xamarin/xamarin-forms-samples/blob/master/SkiaSharpForms/Demos/Demos/SkiaSharpFormsDemos/Basics/SimpleCirclePage.cs" data-linktype="external"&gt;&lt;code&gt;SimpleCirle&lt;/code&gt;&lt;/a&gt; page class derives from &lt;code&gt;ContentPage&lt;/code&gt; and contains two &lt;code&gt;using&lt;/code&gt; directives for the SkiaSharp namespaces:&lt;/p&gt;

should be

&lt;p&gt;The &lt;a href="https://github.com/xamarin/xamarin-forms-samples/blob/master/SkiaSharpForms/Demos/Demos/SkiaSharpFormsDemos/Basics/SimpleCirclePage.cs" data-linktype="external"&gt;&lt;code&gt;SimpleCircle&lt;/code&gt;&lt;/a&gt; page class derives from &lt;code&gt;ContentPage&lt;/code&gt; and contains two &lt;code&gt;using&lt;/code&gt; directives for the SkiaSharp namespaces:&lt;/p&gt;

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 261342ea-fd87-d603-fa4e-fcf903e8798b
* Version Independent ID: 477efad7-92bc-5498-c82e-e3305cb33e66
* Content: [Drawing a Simple Circle in SkiaSharp - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/graphics/skiasharp/basics/circle)
* Content Source: [docs/xamarin-forms/user-interface/graphics/skiasharp/basics/circle.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/graphics/skiasharp/basics/circle.md)
* Product: **xamarin**
* Technology: **xamarin-skiasharp**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @cmeil 

Thanks for pointing this out. I've fixed it in a PR that will go live later today.
