### ISSUE TITLE
Minor, but...  "Don't Link" vs "Link None"

### ISSUE THREAD

**Issue by bobwhitten** [MicrosoftDocs/xamarin-docs#2208]
It says:  "Set the linker to Link None for the best experience" under "Known Limitations".
Shouldn't it be "Don't Link"?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b74184fd-ca8a-11fa-ed37-91235fc59401
* Version Independent ID: 87f197b8-20c6-4825-18e4-86562bb2523c
* Content: [XAML Hot Reload for Xamarin.Forms - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/xaml/hot-reload?WT.mc_id=xamarin-c9-jamont#feedback)
* Content Source: [docs/xamarin-forms/xaml/hot-reload.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/xaml/hot-reload.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @maddyleger1
* Microsoft Alias: **maleger**

**Comment by conceptdev** [comment]
Issue was addressed in referenced PR
