### ISSUE TITLE
Where can I find the devices list on Windows Visual Studio 2017?

### ISSUE THREAD

**Issue by cveld** [MicrosoftDocs/xamarin-docs#221]
I can't seem to play to my connected Xamarin Live Player device.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 07cbe485-3d3b-c8e0-410e-3d04e1beb269
* Version Independent ID: ec2a19ac-ce29-8644-70c1-4a3becb5cda4
* Content: [Live Player for Xamarin.Forms - Xamarin](https://docs.microsoft.com/en-us/xamarin/tools/live-player/)
* Content Source: [docs/tools/live-player/index.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/tools/live-player/index.md)
* Service: **unspecified**
* GitHub Login: @topgenorth
* Microsoft Alias: **toopge**

**Comment by bradumbaugh** [comment]
Hi @cveld, apologies for the slow response to this issue. Selecting a device is described [on this page](https://docs.microsoft.com/xamarin/tools/live-player/install).

For support, please post over on [Developer Community](https://developercommunity.visualstudio.com/spaces/8/index.html).
