### ISSUE TITLE
Presentation style applies to iPad and iPhone

### ISSUE THREAD

**Issue by breyed** [MicrosoftDocs/xamarin-docs#2210]
Despite the title of this doc page, the iPhone (not just the iPad) also accounts for presentation style in how it displays a modal page. The docs should be updated to reflect this.

See also a bug in handling presentation style on iOS 13: xamarin/Xamarin.Forms#7878

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9db97200-aed6-65a2-9f19-cd535991c588
* Version Independent ID: 8f428a69-0e41-9054-2d24-c9c7c1230b99
* Content: [iPad Modal Page Presentation Style - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/platform/ios/ipad-page-presentation-style)
* Content Source: [docs/xamarin-forms/platform/ios/ipad-page-presentation-style.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/platform/ios/ipad-page-presentation-style.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @breyed 

Thanks for pointing this out. I've updated the page, and the updates will go live later today.
