### ISSUE TITLE
Does not compile

### ISSUE THREAD

**Issue by genifycom** [MicrosoftDocs/xamarin-docs#2214]
The first code sample is incorrect. This line

protected override void OnListItemClick(ListView l, View v, int position, long id)

does not compile because it has no body.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0a7120d0-7a67-58f6-6932-df0d3f97ba83
* Version Independent ID: 2c8aa4f7-d3ec-56f3-5a96-2400d7a1a338
* Content: [Populating a Xamarin.Android ListView With Data - Xamarin](https://docs.microsoft.com/en-us/xamarin/android/user-interface/layouts/list-view/populating#feedback)
* Content Source: [docs/android/user-interface/layouts/list-view/populating.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/android/user-interface/layouts/list-view/populating.md)
* Product: **xamarin**
* Technology: **xamarin-android**
* GitHub Login: @conceptdev
* Microsoft Alias: **crdun**

**Comment by conceptdev** [comment]
Thanks for the tip @genifycom, looks like that line shouldn't be in the first code block (it is covered further down the page). Removed!
