### ISSUE TITLE
StackLayout Tutorial Step 1 Feedback

### ISSUE THREAD

**Issue by WahidinAji** [MicrosoftDocs/xamarin-docs#2219]
### Information

- IDE and IDE version: 
- Platform with the issue: 
  - iOS:  
  - Android: 

how can i run my iOS project :v but idon;t have Mac

**Comment by davidbritch** [comment]
Hi @WahidinAji 

Afraid you need a Mac to do iOS development. This is a requirement from Apple. A Mac is required for building as well as running the iOS simulator. You can either use it as a build server, and do your development in Visual Studio, or you can develop directly on the Mac using Visual Studio for Mac.

An alternative to buying a Mac is renting one using a service such as macincloud.
