### ISSUE TITLE
Incorrect 'to'

### ISSUE THREAD

**Issue by hartez** [MicrosoftDocs/xamarin-docs#222]
In the [Purpose section](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/layouts/relative-layout#purpose)

`RelativeLayout` can be used to position views on screen relative to the overall layout or two other views.

should be

`RelativeLayout` can be used to position views on screen relative to the overall layout or to other views.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 35a0e591-622a-aa3f-a289-7896af574a81
* Version Independent ID: 8e796318-0fa6-d67f-1de3-f3b0a5feb49c
* Content: [RelativeLayout - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/layouts/relative-layout#purpose)
* Content Source: [docs/xamarin-forms/user-interface/layouts/relative-layout.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/layouts/relative-layout.md)
* Service: **unspecified**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by conceptdev** [comment]
Fixed!
