### ISSUE TITLE
Link not longer valid

### ISSUE THREAD

**Issue by Depechie** [MicrosoftDocs/xamarin-docs#2223]
The URL for the Related Links : https://docs.microsoft.com/en-us/appcenter/test-cloud/preparing-for-upload/uitest/ is no longer valid.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ffb2875d-657b-defe-7b69-658b2646c5ea
* Version Independent ID: 33461a92-2dd6-adeb-0131-09cbbe1fcc06
* Content: [Using Team City with Xamarin - Xamarin](https://docs.microsoft.com/en-us/xamarin/tools/ci/teamcity#feedback)
* Content Source: [docs/tools/ci/teamcity.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/tools/ci/teamcity.md)
* Product: **xamarin**
* Technology: **xamarin-crossplatform**
* GitHub Login: @conceptdev
* Microsoft Alias: **crdun**

**Comment by davidbritch** [comment]
Hi @Depechie 

I've fixed this in a PR that will go live later today. Thanks for pointing it out.
