### ISSUE TITLE
no mention of macos

### ISSUE THREAD

**Issue by noman9607** [MicrosoftDocs/xamarin-docs#2225]
I know I am in a minority, but my interest is in using c# and visual studio for mac. I don't care about ios.
So, I would like to know how xamarin engages with cocoa and swift for apps on the desktop. It would be nice if you listed a third architecture, similar to the two above that pertains to macos. Xamarin is necessary for me because wpf is only for windows. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 95f1bfc6-27ee-d6b0-6823-bf44d37ae207
* Version Independent ID: 278e483a-9b38-451c-8b79-5c36da9190fe
* Content: [What is Xamarin? - Xamarin](https://docs.microsoft.com/en-us/xamarin/get-started/what-is-xamarin#feedback)
* Content Source: [docs/get-started/what-is-xamarin.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/get-started/what-is-xamarin.md)
* Product: **xamarin**
* Technology: **xamarin-crossplatform**
* GitHub Login: @profexorgeek
* Microsoft Alias: **jusjohns**

**Comment by profexorgeek** [comment]
Hi @noman9607,
The "What Is Xamarin?" page serves as an introduction to Xamarin and only covers the most common use cases. However, you can find details about the MacOS architecture here:
https://docs.microsoft.com/en-us/xamarin/mac/internals/architecture
