### ISSUE TITLE
Need a modification to the HTTP imageuri heade per website being used

### ISSUE THREAD

**Issue by davefxy** [MicrosoftDocs/xamarin-docs#223]
This is really not a documentation comment. But I don't know where else to mention this. For me to use avail myself of the downloaded image caching from the site I frequently download images, I would need to add 2 HTTP header fields : User Agent and Accept. The header fields both have static information either identifying the app/Version and the acceptable returned data format. It would be very useful to allow the program to request these changes prior to the page appearing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7eeb0e65-143b-0f5e-a8fb-c75309689338
* Version Independent ID: 6b984264-a950-4310-483f-99f908b0a8b0
* Content: [Images - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/images?tabs=vswin#downloading-images)
* Content Source: [docs/xamarin-forms/user-interface/images.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/images.md)
* Service: **unspecified**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by conceptdev** [comment]
This system is just for documentation feedback. Please visit [Developer Community](https://developercommunity.visualstudio.com/spaces/8/index.html) to ask questions and post product feedback.
