### ISSUE TITLE
add this for clarity

### ISSUE THREAD

**Issue by aarontoko** [MicrosoftDocs/xamarin-docs#2232]
Just think the tip to
'ensure that your app class has a parameterless constructor'
should also provide a link to the documentation of what a parameterless constructor is.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7008caa8-8acd-9d45-9689-f92b48e78bbf
* Version Independent ID: a94b2057-d8c4-eabd-ca9b-b0de07b468b8
* Content: [XAML Previewer for Xamarin.Forms - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/xaml/xaml-previewer/?pivots=windows#feedback)
* Content Source: [docs/xamarin-forms/xaml/xaml-previewer/index.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/xaml/xaml-previewer/index.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @maddyleger1
* Microsoft Alias: **maleger**

**Comment by conceptdev** [comment]
Thanks for the suggestion @aarontoko. Knowledge of C# is assumed across the Xamarin documentation, so there are no explanations for concepts like parameterless constructors, or how to implement and interface, etc. Information about C# is a quick search away, either using the docs.microsoft.com search function or your preferred search engine.
