### ISSUE TITLE
Not very informative

### ISSUE THREAD

**Issue by texasgeek** [MicrosoftDocs/xamarin-docs#2235]
The page could use more instructions on how to put together a Xamarin Forms app with Localization. It should at minimum create a working demo showing how to enter values for two languages.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: afe74e14-16a6-08f7-bf4d-e8e3b0d0f0c4
* Version Independent ID: f466d02e-f83f-fb32-76fa-bd010366bf41
* Content: [Xamarin.Forms Localization - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/localization/#feedback)
* Content Source: [docs/xamarin-forms/app-fundamentals/localization/index.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/app-fundamentals/localization/index.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @texasgeek 

The page you've mentioned is just a landing page for the two topics (string localisation, and RTL localisation). If you go into each page, they include downloadable samples.
