### ISSUE TITLE
No pure code examples.

### ISSUE THREAD

**Issue by LJ9999** [MicrosoftDocs/xamarin-docs#2236]
Just a lot of Microsoft technobabble for people who already know all about this rocket science.

Well, there are some of us who don't know it all.

But that's okay. Microsoft has always been the worst teacher of its tech.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a6fd1063-e094-1bda-e2ec-f63a0136523d
* Version Independent ID: 6e25673a-374a-2f05-f610-984d22e52053
* Content: [Xamarin.Forms Basic Bindings - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/data-binding/basic-bindings)
* Content Source: [docs/xamarin-forms/app-fundamentals/data-binding/basic-bindings.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/app-fundamentals/data-binding/basic-bindings.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @LJ9999 

In that case I recommend the following learning path for you:

1. Take a look at [Creating Mobile Apps with Xamarin.Forms](https://docs.microsoft.com/xamarin/xamarin-forms/creating-mobile-apps-xamarin-forms/) by Charles Petzold.
1. Start learning the [basics](https://docs.microsoft.com/xamarin/get-started/tutorials/).
1. Build a [working app](https://docs.microsoft.com/xamarin/get-started/quickstarts/).
1. Complete the [MSLearn modules](https://docs.microsoft.com/learn/browse/?roles=developer&products=xamarin) to gain a deeper understanding.
