### ISSUE TITLE
All I want to do is update a label with different text

### ISSUE THREAD

**Issue by LJ9999** [MicrosoftDocs/xamarin-docs#2239]
Why is that so hard? It's not even in here. Nevermind. Typical Microsoft. I'll waste another evening figuring it out. MS docs are horrible. 'Have been for the last 30 years.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f8a6273c-62b1-ac18-aab3-62f78bdbade8
* Version Independent ID: 746bd180-ae67-313d-b949-538a508807b2
* Content: [Xamarin.Forms Label - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/text/label)
* Content Source: [docs/xamarin-forms/user-interface/text/label.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/text/label.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by LJ9999** [comment]
Yes, the problem isn't Xamarin. I'm think I'm sure of that. The problem is that there is nobody able to competently teach it. And I do mean Nobody.

**Comment by davidbritch** [comment]
Hi @LJ9999 

In that case I recommend the following learning path for you:

1. Take a look at [Creating Mobile Apps with Xamarin.Forms](https://docs.microsoft.com/xamarin/xamarin-forms/creating-mobile-apps-xamarin-forms/) by Charles Petzold.
1. Start learning the [basics](https://docs.microsoft.com/xamarin/get-started/tutorials/).
1. Build a [working app](https://docs.microsoft.com/xamarin/get-started/quickstarts/).
1. Complete the [MSLearn modules](https://docs.microsoft.com/learn/browse/?roles=developer&products=xamarin) to gain a deeper understanding.
