### ISSUE TITLE
Connectivity is *not* supported on WatchOS

### ISSUE THREAD

**Issue by DamianMehers** [MicrosoftDocs/xamarin-docs#2241]
Connectivity is *not* supported on WatchOS

https://github.com/xamarin/Essentials/blob/master/Xamarin.Essentials/Connectivity/Connectivity.netstandard.watchos.cs

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d37c2f4a-4b14-4936-deb4-3b1fcdb55c9d
* Version Independent ID: 64d981c3-07ad-da2b-4a6c-f7c4c1a70644
* Content: [Xamarin.Essentials Platform & Feature Support - Xamarin](https://docs.microsoft.com/en-us/xamarin/essentials/platform-feature-support?context=xamarin%2Fandroid#feedback)
* Content Source: [docs/essentials/platform-feature-support.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/essentials/platform-feature-support.md)
* Product: **xamarin**
* Technology: **xamarin-essentials**
* GitHub Login: @jamesmontemagno
* Microsoft Alias: **jamont**

**Comment by jamesmontemagno** [comment]
Good catch, i put in a pr for the team to validate.

**Comment by DamianMehers** [comment]
Thanks.  The underlying issue is that [SystemConfiguration](https://developer.apple.com/documentation/systemconfiguration) is not currently available on WatchOS :-(
