### ISSUE TITLE
404

### ISSUE THREAD

**Issue by Siaukovich** [MicrosoftDocs/xamarin-docs#2244]
"Remote Notifications (sample)" link in "Related Links" section opens 404 error page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 79599e74-f3b5-261c-3d30-e6b8313c1955
* Version Independent ID: bfd910eb-f776-1799-6e2b-4019f56f0027
* Content: [Notifications in Xamarin.Android - Xamarin](https://docs.microsoft.com/en-us/xamarin/android/app-fundamentals/notifications/#feedback)
* Content Source: [docs/android/app-fundamentals/notifications/index.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/android/app-fundamentals/notifications/index.md)
* Product: **xamarin**
* Technology: **xamarin-android**
* GitHub Login: @conceptdev
* Microsoft Alias: **crdun**

**Comment by conceptdev** [comment]
Thanks for letting us know - the sample has been [deprecated](https://github.com/xamarin/monodroid-samples/tree/master/RemoteNotifications). Removing the broken link now.
