### ISSUE TITLE
Outdated.

### ISSUE THREAD

**Issue by JanettHolst290490** [MicrosoftDocs/xamarin-docs#2245]
https://docs.microsoft.com/en-us/xamarin/ios/get-started/installation/device-provisioning/manual-provisioning?tabs=macos#provisioning-profile, point 9: Xcode &gt; Preferences &gt; Accounts. Select your Apple ID and click View Details....
This doesn't seem to be possible any more. Is there any other way to see provisioning profiles installed on the Mac ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2f798d8c-b191-34a4-55dd-02005b0b6332
* Version Independent ID: 2f6ec8bd-359d-a5a6-891a-6c60ff52adb7
* Content: [Manual provisioning for Xamarin.iOS - Xamarin](https://docs.microsoft.com/en-us/xamarin/ios/get-started/installation/device-provisioning/manual-provisioning?tabs=macos#feedback)
* Content Source: [docs/ios/get-started/installation/device-provisioning/manual-provisioning.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/ios/get-started/installation/device-provisioning/manual-provisioning.md)
* Product: **xamarin**
* Technology: **xamarin-ios**
* GitHub Login: @conceptdev
* Microsoft Alias: **crdun**

**Comment by CennoxX** [comment]
Point 9 should be replaced with:
This can be verified by browsing to Xcode > Window > Devces. Right-click on your device and select Show Provisioning Profiles ...

**Comment by conceptdev** [comment]
Updated text per @CennoxX (thanks!) and redid screenshot.
