### ISSUE TITLE
ShareFile contentType parameter 

### ISSUE THREAD

**Issue by sehuff** [MicrosoftDocs/xamarin-docs#2246]
This documentation does not explain what the contentType parameter is very well.  It says: "Explicit content type of the file."  Is that the MimeType?  I'm not sure me or others know what contentType is.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5e5ab81d-1b4c-6be3-16a3-23b259d29a9a
* Version Independent ID: b05ac121-f4df-0313-21a6-dbb2668417b8
* Content: [ShareFile Constructor (Xamarin.Essentials)](https://docs.microsoft.com/en-us/dotnet/api/xamarin.essentials.sharefile.-ctor?view=xamarin-essentials#feedback)
* Content Source: [docs/en/Xamarin.Essentials/ShareFile.xml](https://github.com/xamarin/Essentials/blob/live/docs/en/Xamarin.Essentials/ShareFile.xml)
* Product: **xamarin**
* Technology: **xamarin-essentials**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by conceptdev** [comment]
Thanks for your feedback @sehuff 

@jamesmontemagno FYI this is referencing the API docs, not the conceptual docs.

**Comment by jamesmontemagno** [comment]
Good feedback @redth perhaps you can fill in the details here. I think it is just the mime type.

**Comment by Redth** [comment]
I think we can close this issue now that there is a PR in the repo to clarify.

Thanks!
