### ISSUE TITLE
Hyper-V not on windows features

### ISSUE THREAD

**Issue by w1wwwwww** [MicrosoftDocs/xamarin-docs#2248]
Hyper-V is not on windows features, is there any way i can download it or get it?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4e37d642-2051-8d70-9968-dfb484122a6a
* Version Independent ID: 178ea80c-2b99-0c44-eeb6-9db319439b33
* Content: [Hardware Acceleration for Emulator Performance (Hyper-V & HAXM) - Xamarin](https://docs.microsoft.com/en-us/xamarin/android/get-started/installation/android-emulator/hardware-acceleration?pivots=windows#feedback)
* Content Source: [docs/android/get-started/installation/android-emulator/hardware-acceleration.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/android/get-started/installation/android-emulator/hardware-acceleration.md)
* Product: **xamarin**
* Technology: **xamarin-android**
* GitHub Login: @conceptdev
* Microsoft Alias: **crdun**

**Comment by irongut** [comment]
If Hyper-V is not shown in the Windows Features dialog then I assume you're using Windows 10 Home Edition. You need to upgrade to one of the more business orientated versions of Windows, Hyper-V is not available separately.
https://docs.microsoft.com/en-us/virtualization/hyper-v-on-windows/about/

**Comment by jsykes2203** [comment]
Wouldn't it be useful to add this info somewhere on this page instead of leaving users confused and having to search elsewhere to find it out? The section mentioning Windows must be up to specific build version would a suitable place.
