### ISSUE TITLE
Please provide full examples

### ISSUE THREAD

**Issue by ndastur** [MicrosoftDocs/xamarin-docs#2249]
This page is an example, but it is a problem throughout the documentation that the examples are never complete. The required using statements do not appear and for XAML examples the location of the XAML and any enveloping structures are not given. So this page would be improved by:

&lt;ContentPage.ToolbarItems&gt;
&lt;ToolbarItem ...
             Clicked="OnItemClicked" /&gt;
&lt;/ContentPage.ToolbarItems&gt;

as the example

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 84079a4a-8798-d710-58b4-df1bc3be6058
* Version Independent ID: b12ca022-d891-6e99-2276-058424af27c5
* Content: [Xamarin.Forms ToolbarItem - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/toolbaritem#feedback)
* Content Source: [docs/xamarin-forms/user-interface/toolbaritem.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/toolbaritem.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @profexorgeek
* Microsoft Alias: **jusjohns**

**Comment by profexorgeek** [comment]
Hi @ndastur,
Keeping our code and XAML samples concise in docs helps keep them readable. We try to provide a sample project that shows the full context and code. However, the XAML and C# examples in this case did not match so I have made the changes you requested.

It's worth mentioning that `ToolbarItem` can also be used in Shell menus or custom controls. So there are use cases beyond just the `ToolbarItems` collection.

**Comment by ndastur** [comment]
Thanks, @profexorgeek for the reply and I understand the rationale. However, if the little snippets don't actually "work" then would it not be better to link to the full example code. I say this as the current process, from a users perspective is
- read MS docs
- use the snippet
- find it doesn't work with some abstract error message in VS
- *scream* at computer
- Open the GitHub example
- Search for the relevant file (as there is no direct link)
- Then find a solution that does work
- Rinse and repeat

**Comment by profexorgeek** [comment]
I definitely understand your frustrations. We absolutely want the snippits to work (which is why I went ahead with your change) but sometimes things require significant config or boilerplate that clutters the doc. Finding where to draw that line is always a grey area! Thanks again for your feedback.
