### ISSUE TITLE
It is not working

### ISSUE THREAD

**Issue by RazvanEmilR** [MicrosoftDocs/xamarin-docs#2250]
I have the latest Visual Studio Community 2019 16.3.5

with Xamarin.Forms 4.2.0.848062

Hot Reload is enabled. On the bottom bar when I save the changes (Like changes to the Placeholder on the login page) in XAML the message says "Hot Reload Succesful" but nothing changes in the iOS simulator for iPHONE 11 

Build link option is set to "Don't Link"

Same behaviour for Android.

**Comment by maddyleger1** [comment]
Hi there! Can you file a bug using Help > Send Feedback > Report a Problem with logs attached so we can have our engineering team diagnose this? Thanks!

**Comment by conceptdev** [comment]
You can refer to these [detailed instructions on submitting an issue in Visual Studio](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio), thanks.
