### ISSUE TITLE
Loading from stream seems faster then from loading from resource

### ISSUE THREAD

**Issue by BrayanKhosravian** [MicrosoftDocs/xamarin-docs#2254]
hi i was loading the images using `FromResource` till i had to set up a sqlite db where i had to convert the image to a bytearray in order to store the image in the db.

After i noticed that its not that easy to convert an imageSource to a byte array, i decided to use `FromStream` and now im converting the image into bytes via reflection.
And even when reflection is slow, `FromStream` seems to be much faster.

Theres a code example below.

```cs
public BaseLiquidBuilder&lt;TLiquidBase&gt; SetImageSource(string partialResource, Type resolvingType)
		{
			if (resolvingType == null) throw ExceptionFactory.Get&lt;ArgumentNullException&gt;("'resolvingType' is null");
			if (string.IsNullOrWhiteSpace(partialResource))
				throw ExceptionFactory.Get&lt;ArgumentException&gt;("'partialResource' is null or has whitespaces");

			var resource = string.Join(".", "SmartButler.Resources", partialResource);
			var sourceAssembly = resolvingType.GetTypeInfo().Assembly;

			byte[] byteImage;
			using (var stream = sourceAssembly.GetManifestResourceStream(resource))
			{
				if (stream == null)
				{
					ActualImage = null;
					ByteImage = null;
					return this;
				}
				var length = stream.Length;
				byteImage = new byte[length];
				stream.Read(byteImage, 0, (int)length);
				ActualImage = ImageSource.FromStream(() =&gt; new MemoryStream(byteImage));
			}

			ByteImage = byteImage;

			return this;
		}
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7eeb0e65-143b-0f5e-a8fb-c75309689338
* Version Independent ID: 6b984264-a950-4310-483f-99f908b0a8b0
* Content: [Images in Xamarin.Forms - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/images?tabs=windows)
* Content Source: [docs/xamarin-forms/user-interface/images.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/images.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @BrayanKhosravian 

Was this iOS, Android, or both?

**Comment by BrayanKhosravian** [comment]
Thank you for your response.
I tested this only with android.

Heres my repository, if u want to clone it. 
https://github.com/BrayanKhosravian/SmartButler

The behaviour is not isolated in my repo but its possie to execute the app.

**Comment by davidbritch** [comment]
Hi @BrayanKhosravian 

Apologies for the delayed response. I've just been investigating if there's anything solid that can be put into the docs on this issue, and it's not looking like there is. Performance is dependent upon so many different issues, including the version of .NET Standard, the Android API level, and the version of Xamarin.Forms.

The most interesting thing I found out is that if you call `FromResource` to load an image, it ultimately calls `FromStream` to do that load. The last line of code in the `FromResource` method is:

```
return FromStream(() => sourceAssembly.GetManifestResourceStream(resource));
```

Anyway, thanks for starting this discussion, and good luck with your app!
