### ISSUE TITLE
I wonder how many evenings it will take me to find information about PropertyChanged.

### ISSUE THREAD

**Issue by LJ9999** [MicrosoftDocs/xamarin-docs#2256]
Microsoft documentation is next-to-worthless. 'Can't find anything.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9de402a5-a78c-3cfe-f9b1-443a3401574b
* Version Independent ID: 4488127d-8fe9-eef6-c665-106b493f93fd
* Content: [Xamarin.Forms CollectionView - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/collectionview/)
* Content Source: [docs/xamarin-forms/user-interface/collectionview/index.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/collectionview/index.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @LJ9999 

I recommend you read and understand the following: https://docs.microsoft.com/xamarin/xamarin-forms/xaml/xaml-basics/data-bindings-to-mvvm
