### ISSUE TITLE
Page redundant

### ISSUE THREAD

**Issue by ChrisMaddock** [MicrosoftDocs/xamarin-docs#2258]
Xamarin.UITest now supports NUnit 3, which I presume makes this page redundant?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 51a5d74f-ccf7-8e9b-e242-842bc7a3ee75
* Version Independent ID: 31c4ef93-2ff3-280d-70f5-128511277ad7
* Content: [Installing NUnit 2.6.4 using NuGet - Xamarin](https://docs.microsoft.com/en-us/xamarin/cross-platform/deploy-test/installing-nunit-using-nuget?tabs=windows)
* Content Source: [docs/cross-platform/deploy-test/installing-nunit-using-nuget.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/cross-platform/deploy-test/installing-nunit-using-nuget.md)
* Product: **xamarin**
* Technology: **xamarin-crossplatform**
* GitHub Login: @conceptdev
* Microsoft Alias: **crdun**

**Comment by conceptdev** [comment]
Thanks for the reminder, this page is indeed outdated with the NUnit 3 support. Will probably remove it 😉

**Comment by conceptdev** [comment]
Page has been removed - thanks again.
