### ISSUE TITLE
Wrong href in the first Hello, Android Multiscreen Deep Dive. link

### ISSUE THREAD

**Issue by carlbinalla** [MicrosoftDocs/xamarin-docs#2259]
The first **Hello, Android Multiscreen Deep Dive.** link's href is wrong. It is redirecting to the [first deepdive](https://docs.microsoft.com/en-us/xamarin/android/get-started/hello-android/hello-android-deepdive?pivots=windows) rather than its own [deepdive](https://docs.microsoft.com/en-us/xamarin/android/get-started/hello-android-multiscreen/hello-android-multiscreen-deepdive)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 672a11c0-fb8f-4b75-f42c-23429f52c35a
* Version Independent ID: 51f9c1e4-fa5d-b6ac-6081-c4c3189191f7
* Content: [Hello, Android Multiscreen: Quickstart - Xamarin](https://docs.microsoft.com/en-us/xamarin/android/get-started/hello-android-multiscreen/hello-android-multiscreen-quickstart?pivots=windows#feedback)
* Content Source: [docs/android/get-started/hello-android-multiscreen/hello-android-multiscreen-quickstart.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/android/get-started/hello-android-multiscreen/hello-android-multiscreen-quickstart.md)
* Product: **xamarin**
* Technology: **xamarin-android**
* GitHub Login: @conceptdev
* Microsoft Alias: **crdun**

**Comment by conceptdev** [comment]
Thanks for letting us know - fixing now.
