### ISSUE TITLE
iOS image set naming convention should be added

### ISSUE THREAD

**Issue by tnoah23** [MicrosoftDocs/xamarin-docs#2262]
Struggled for a long time before I discovered that image sets wont be pulled from xaml code if using underscores. For example...  `<Image Source="foo_bar.png">` Will only display on Android and not iOS. Android naming rules are mentioned but not iOS

**Comment by davidbritch** [comment]
Hi @tnoah23 

Thanks for pointing this out. I've added it to our backlog, and hence will close the item here.
