### ISSUE TITLE
Hot Reload Doesn't Work

### ISSUE THREAD

**Issue by CeciAc** [MicrosoftDocs/xamarin-docs#2264]
The comment below was Machine translated

@Nathaniel-Santos commented on [Wed Oct 23 2019](https://github.com/MicrosoftDocs/xamarin-docs.pt-br/issues/33)

Even following all the steps informed, it still does not work. Interestingly on the way tools> options> Xamarin ... There is no Hot reupload option for me. Already reinstalled the software but simply does not appear the option Hot reupload, or HotReload in this way. I've been months without solution to this problem.

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: b74184fd-ca8a-11fa-ed37-91235fc59401
* Version Independent ID: 87f197b8-20c6-4825-18e4-86562bb2523c
* Content: [Hot recarregamento de XAML para Xamarin. Forms - Xamarin](https://docs.microsoft.com/pt-br/xamarin/xamarin-forms/xaml/hot-reload#feedback)
* Content Source: [docs/xamarin-forms/xaml/hot-reload.md](https://github.com/MicrosoftDocs/xamarin-docs.pt-br/blob/live/docs/xamarin-forms/xaml/hot-reload.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @maddyleger1
* Microsoft Alias: **maleger**

---

@srvbpigh commented on [Wed Oct 23 2019](https://github.com/MicrosoftDocs/xamarin-docs.pt-br/issues/33#issuecomment-545258294)

Hello, @Nathaniel-Santos
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by maddyleger1** [comment]
Hi, please file an issue through Visual Studio [using these instructions](https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2019). Thanks!
