### ISSUE TITLE
StackLayout Tutorial Step 3 Feedback

### ISSUE THREAD

**Issue by andrelevacic** [MicrosoftDocs/xamarin-docs#2266]
### Description

It looks different.

### Information

- IDE and IDE version: Visual Studio 2019 4.7.03062
- Platform with the issue: 
  - iOS:  13.1
![Fehler_iOS](https://user-images.githubusercontent.com/45570256/67476454-5c716100-f658-11e9-8c00-8014210c6553.JPG)

My Code:

<?xml version="1.0" encoding="utf-8"?>
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="MSTut.MainPage">
    <StackLayout Margin="30,35,20,25">
        <StackLayout Margin="30,35,20,25" >
            <Label Text="Start"
                   HorizontalOptions="Start"
                   BackgroundColor="Red" />
            <Label Text="Center"
                   HorizontalOptions="Center"
                   BackgroundColor="Gray" />
            <Label Text="End"
                   HorizontalOptions="End"
                   BackgroundColor="Gray" />
            <Label Text="Fill"
                   HorizontalOptions="Fill"
                   BackgroundColor="Gray" />
            <Label Text="StartAndExpand"
                   HorizontalOptions="StartAndExpand"
                   BackgroundColor="Gray" />
            <Label Text="CenterAndExpand"
                   HorizontalOptions="CenterAndExpand"
                   BackgroundColor="Gray" />
            <Label Text="EndAndExpand"
                   HorizontalOptions="EndAndExpand"
                   BackgroundColor="Gray" />
            <Label Text="FillAndExpand"
                   HorizontalOptions="FillAndExpand"
                   BackgroundColor="Gray" />
        </StackLayout>
        <StackLayout Margin="0,0,0,0" >
            <Label Text="The StackLayout has its Margin property set, to control the rendering position of the StackLayout." />
            <Label Text="The Padding property can be set to specify the distance between the StackLayout and its children." />
            <Label Text="The Spacing property can be set to specify the distance between views in the StackLayout." />
        </StackLayout>
        <StackLayout Padding="30,35,20,25" Orientation="Horizontal">
            <Label Text="The 1st in it." Margin="10" />
            <Label Text="The 2nd in it." Margin="10,25"/>
            <Label Text="The 3rd in it." Margin="10,20,10,20"/>
        </StackLayout>
    </StackLayout>
</ContentPage>

**Comment by davidbritch** [comment]
Hi @andrelevacic 

I just tried the sample (https://docs.microsoft.com/samples/xamarin/xamarin-forms-samples/getstarted-tutorials-stacklayouttutorial/) for this tutorial, on iOS 13, and I get the layout as shown in the doc:

![Simulator Screen Shot - iPhone X - 2019-10-25 at 09 41 35](https://user-images.githubusercontent.com/8092460/67556854-d3b3fd00-f70b-11e9-8d1e-5e7210d3310a.png)

I recommend trying the sample yourself, and compare your code against it.
