### ISSUE TITLE
Support for other refresh directions.

### ISSUE THREAD

**Issue by emmauss** [MicrosoftDocs/xamarin-docs#2267]
[Enter feedback here]
Are there any plans for implementing directions to trigger refreshes? like pulling from the bottom or sides?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a9d4ba1f-8a3a-b72a-75b4-4ad6138ecec9
* Version Independent ID: 4fd13d66-c654-7ab3-58ce-1806c8383d67
* Content: [Xamarin.Forms RefreshView - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/refreshview)
* Content Source: [docs/xamarin-forms/user-interface/refreshview.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/refreshview.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @emmauss 

UWP is the only platform that natively provides an API for changing the refresh direction (see https://docs.microsoft.com/xamarin/xamarin-forms/platform/windows/refreshview-pulldirection). That doesn't make it impossible on iOS and Android, but it does make it a more significant piece of work. Whether it happens depends on how strongly the feature is requested. Opening an enhancement request on the [engineering repo](https://github.com/xamarin/Xamarin.Forms/) would start the ball rolling.
