### ISSUE TITLE
Clockwise or anticlockwise?

### ISSUE THREAD

**Issue by oliver-ep** [MicrosoftDocs/xamarin-docs#2268]
I know I can experiment to get this answer, but I think it would help to clarify if the angle is considered clockwise or anti-clockwise.

For example, if the device returns 90 degrees, is it pointing east or west? I would assume east here, but it'll save me, and like minded individuals, if it were clarified.

Also the name 'Course' suggests there is a destination in mind. Considering the subtle differences in english for Bearing, Heading, and Course it would sit better with me if this was named Heading but I can live without.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ebea8865-1c13-7f13-c40f-d4f24bd01988
* Version Independent ID: 85959ace-7cc5-fab6-791f-7820bce15039
* Content: [Location.Course Property (Xamarin.Essentials)](https://docs.microsoft.com/en-us/dotnet/api/xamarin.essentials.location.course?view=xamarin-essentials#Xamarin_Essentials_Location_Course)
* Content Source: [docs/en/Xamarin.Essentials/Location.xml](https://github.com/xamarin/Essentials/blob/live/docs/en/Xamarin.Essentials/Location.xml)
* Product: **xamarin**
* Technology: **xamarin-essentials**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by jamesmontemagno** [comment]
It is clockwise:

Here is the docs from Apple:

Course values are measured in degrees starting at due north and continue clockwise around the compass. Thus, north is 0 degrees, east is 90 degrees, south is 180 degrees, and so on. Course values may not be available on all devices. A negative value indicates that the course information is invalid. https://developer.apple.com/documentation/corelocation/cllocation/1423832-course

Will work on updating.
