### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by mairaw** [MicrosoftDocs/xamarin-docs#2269]
Issue reported by @DualBrain

There's a broken link in the [Related links](https://docs.microsoft.com/en-us/xamarin/cross-platform/platform/visual-basic/#related-links) section.

Should the link be https://github.com/xamarin/mobile-samples/tree/master/VisualBasic/TaskyVB instead?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5d96c4ac-4420-b204-84e7-42c5db5c9060
* Version Independent ID: eb0ecf91-bd3c-c1e8-46e9-ca8bc71b2509
* Content: [Visual Basic and .NET Standard - Xamarin](https://docs.microsoft.com/en-us/xamarin/cross-platform/platform/visual-basic/)
* Content Source: [docs/cross-platform/platform/visual-basic/index.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/cross-platform/platform/visual-basic/index.md)
* Product: **xamarin**
* Technology: **xamarin-crossplatform**
* GitHub Login: @conceptdev
* Microsoft Alias: **crdun**

**Comment by conceptdev** [comment]
Thanks @mairaw, updating now. Going to use the samples portal link

https://docs.microsoft.com/samples/xamarin/mobile-samples/visualbasic-taskyvb/

😉
