### ISSUE TITLE
Suggestion for correction

### ISSUE THREAD

**Issue by rayaqin** [MicrosoftDocs/xamarin-docs#227]
Hi, it's me again

"This object contains callback methods that notify the client when it has connected to (or lost the connection) from the service. " 

This doesn't seem right. I would probably change the phrasing too, but at least the "from" should be inside the parenthesis.

Best regards,
rayaqin

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ed0a6ecd-980c-c2dd-433b-ab3c5f7f467c
* Version Independent ID: 458fb06e-8a5e-adc1-a75d-03b04180fe9f
* Content: [Bound Services in Xamarin.Android - Xamarin](https://docs.microsoft.com/en-us/xamarin/android/app-fundamentals/services/creating-a-service/bound-services)
* Content Source: [docs/android/app-fundamentals/services/creating-a-service/bound-services.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/android/app-fundamentals/services/creating-a-service/bound-services.md)
* Service: **unspecified**
* GitHub Login: @topgenorth
* Microsoft Alias: **toopge**

**Comment by rayaqin** [comment]
also:
"An IBinder Instead applications should extend the Binder which provides..."

Is a bit off as well

**Comment by topgenorth** [comment]
Thanks again for your keen eye and reporting the issues.  The updates are working their way through our publishing workflow.
