### ISSUE TITLE
Outdated material

### ISSUE THREAD

**Issue by micheleissa** [MicrosoftDocs/xamarin-docs#2270]
The part about Autofac needs to be changed to TinyIoC as it is what's being used in the code.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 10e6c4c3-75a5-04bc-3ed7-db347d434b03
* Version Independent ID: 99cb62ae-36e5-aa03-c261-131390ca1c0f
* Content: [Enterprise App Navigation - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/enterprise-application-patterns/navigation#feedback)
* Content Source: [docs/xamarin-forms/enterprise-application-patterns/navigation.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/enterprise-application-patterns/navigation.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @micheleissa 

I've just updated the doc, so that it uses TinyIoC and reflects the source code. The PR this update is in will go live later today.
