### ISSUE TITLE
Thisckness is faulty

### ISSUE THREAD

**Issue by Otto404** [MicrosoftDocs/xamarin-docs#2272]
the line
    "&lt;Thickness x:Key="PageMargin"&gt;20&lt;/Thickness&gt;"

should be replaced by

        <OnPlatform x:Key="PageMargin" x:TypeArguments="Thickness">
            <On Platform="Android">16</On>
            <On Platform="iOS">20</On>
            <On Platform="WinPhone">24</On>
        </OnPlatform>

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 46228c67-1dc9-99e0-d279-ff6e722bfd5e
* Version Independent ID: 41994570-80f8-55ae-9a31-9696610b2353
* Content: [Style a cross-platform Xamarin.Forms application - Xamarin](https://docs.microsoft.com/en-us/xamarin/get-started/quickstarts/styling?pivots=windows#feedback)
* Content Source: [docs/get-started/quickstarts/styling.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/get-started/quickstarts/styling.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @Otto404 

The original line of code (`<Thickness x:Key="PageMargin">20</Thickness>`) is fine. I just tried it in the [sample](https://docs.microsoft.com/samples/xamarin/xamarin-forms-samples/getstarted-notes-styled/) for that page, and it worked as expected.

**Comment by LNOXS07** [comment]
Hi @davidbritch, 
<Thickness x:Key="PageMargin">20</Thickness> gives this error in VS19.
Error	XLS0502	The type 'Thickness' does not support direct content.	Notes	App.xaml	8	

I replaced it with the following to resolve:

<Thickness x:Key="PageMargin" Left="20" Top="20" Right="20" Bottom="20"/>

**Comment by davidbritch** [comment]
Hi @LNOXS07 

I just tried this, again, in VS2019 and there was no problem. Note the build succeeded message in my IDE:

![Capture](https://user-images.githubusercontent.com/8092460/77902041-7a329a00-7278-11ea-9eaa-1380645b3960.PNG)

I'd recommended (1) ensuring you are using the latest version of Xamarin.Forms in your project, and that all projects are using the same version, and (2) deleting your bin/obj folders and rebuilding.
