### ISSUE TITLE
Relative Bindings Require Xamarin Forms 4.3 minimum version.

### ISSUE THREAD

**Issue by rogerwcpt** [MicrosoftDocs/xamarin-docs#2273]
Relative Bindings Require Xamarin Forms 4.3 minimum version.  Lower versions will result in your XAML not compiling.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3f73553f-8c35-877b-0a34-db9b51df93be
* Version Independent ID: d51b2ace-0519-6309-7417-d29a582a4de2
* Content: [Xamarin.Forms Relative Bindings - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/data-binding/relative-bindings?WT.mc_id=social-twitter-bramin)
* Content Source: [docs/xamarin-forms/app-fundamentals/data-binding/relative-bindings.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/app-fundamentals/data-binding/relative-bindings.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @rogerwcpt 

Correct. Our docs always reflect what's available in the latest version of Xamarin.Forms.
