### ISSUE TITLE
Example does not compile.

### ISSUE THREAD

**Issue by cplager** [MicrosoftDocs/xamarin-docs#2275]
It's a little hard to tell since you don't show where the code is supposed to be posted in the files,  But I belive I'm doing it where I am supposed to and am getting the following errors:

Severity	Code	Description	Project	File	Line	Suppression State	Suppression State
Error	CS1061	'Button' does not contain a definition for 'Text' and no accessible extension method 'Text' accepting a first argument of type 'Button' could be found (are you missing a using directive or an assembly reference?)	AwesomeApp.UWP	C:\Users\Charles Plager\source\repos\AwesomeApp\AwesomeApp\AwesomeApp.UWP\MainPage.xaml.cs	31		Active
Error		Position 14:33. EventHandler "Handle_Clicked" with correct signature not found in type "AwesomeApp.MainPage"	AwesomeApp	C:\Users\Charles Plager\source\repos\AwesomeApp\AwesomeApp\AwesomeApp\MainPage.xaml	14		

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b4445585-af8f-09d3-5d35-762c3aac187b
* Version Independent ID: fa9263db-60d6-eb98-eb74-842351ba5387
* Content: [Build your first Xamarin.Forms app - Xamarin](https://docs.microsoft.com/en-us/xamarin/get-started/first-app/?pivots=windows#feedback)
* Content Source: [docs/get-started/first-app/index.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/get-started/first-app/index.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @conceptdev
* Microsoft Alias: **crdun**

**Comment by cplager** [comment]
This rpoblem was caused by me editing the wrong MainPage.xaml.cs file.  I should have edited the one found when expanding MainPaig.xaml.

**Comment by davidbritch** [comment]
Hi @cplager 

Glad you've dealt with the issue!
