### ISSUE TITLE
Release notes list 4.3.0.908675 as rc1

### ISSUE THREAD

**Issue by breyed** [MicrosoftDocs/xamarin-docs#2279]
This is the [4.3.0 release notes](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/release-notes/4.3/4.3.0) title:
> The Xamarin.Forms 4.3.0.908675 (4.3.0 rc1) Release Notes

Likewise for the [dated subtitle](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/release-notes/4.3/4.3.0#monday-october-21-2019---xamarinforms-430908675-430-rc1):
> Monday, October 21, 2019 - Xamarin.Forms 4.3.0.908675 (4.3.0 rc1)

However, the table of contents and NuGet indicate that 4.3.0.908675 is a stable release, not a release candidate. It looks like the titles each have an obsolete "rc1".

**Comment by davidbritch** [comment]
Hi @breyed 

Thanks for pointing this out. It looks like it's since been fixed, so I'll close the issue now.
