### ISSUE TITLE
macOS "Could not find assembly '--output=managed_c'"

### ISSUE THREAD

**Issue by robotogre** [MicrosoftDocs/xamarin-docs#228]
I have installed Embeddinator 4000 via NuGet, using the above directions, in Visual Studio Community for macOS. The file, 'CppSharp.Generator.dll' is in my /tools/ directory, right next to Embeddinator-4000.exe. When I run the mono command listed above, I get the following error: "Could not find assembly '--output=managed_c'".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9256b5bb-c992-0f75-aa3e-e1cac2c600ca
* Version Independent ID: c6a0defa-2a17-a88e-e989-b23de2b70a0b
* Content: [Getting started with C - Xamarin](https://docs.microsoft.com/en-us/xamarin/tools/dotnet-embedding/get-started/c)
* Content Source: [docs/tools/dotnet-embedding/get-started/c.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/tools/dotnet-embedding/get-started/c.md)
* Service: **unspecified**
* GitHub Login: @topgenorth
* Microsoft Alias: **toopge**

**Comment by bradumbaugh** [comment]
Hi @robotogre - you're right, I took a look at this, and the actual parameter is `--outdir` (or `--out` or `--o`), not `--output`. 

I've made the change in the docs and it should be published soon. Appreciate the help!
