### ISSUE TITLE
In ios toolbar item icon image not binding dynamically

### ISSUE THREAD

**Issue by PRAVEENPOTLA** [MicrosoftDocs/xamarin-docs#2280]
See below image in andriod is working fine but problem with ios

**Comment by conceptdev** [comment]
Hi @PRAVEENPOTLA , if you are experiencing problems with Xamarin.Forms, the best place to report is the [open-source issues list](https://github.com/xamarin/xamarin.forms/issues). Someone may have already reported a similar problem. It is always help to include an example of the exact code causing the problem (and don't forget to update any images too). The team appreciates as much information as possible to diagnose the problem.
