### ISSUE TITLE
What should be Copy to output direcory?

### ISSUE THREAD

**Issue by pmahend1** [MicrosoftDocs/xamarin-docs#2281]
What should be `Copy to output direcory` in *Properties*? Should it be copy always?

Android doesnt like file names with hyphens `Lobster-Medium` , is that the case here as well? 
![abc](https://user-images.githubusercontent.com/21352870/67712392-46d2a300-f99a-11e9-8a0b-ff843a226877.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe0572c4-91be-fc86-d130-242db2bf470b
* Version Independent ID: 1238fdd7-c378-6d0d-654e-55656a70d386
* Content: [Fonts in Xamarin.Forms - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/text/fonts#feedback)
* Content Source: [docs/xamarin-forms/user-interface/text/fonts.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/text/fonts.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @pmahend1 

Is your question specifically about a custom font?

**Comment by pmahend1** [comment]
Yes

Regards,
Prateek Mahendrakar

**Comment by davidbritch** [comment]
Apologies for the much delayed response. On Android, you can leave `Copy to output directory` as `Do not copy`. However, changing it to `Always copy` won't create any problems.

As you'll see in the [sample](https://docs.microsoft.com/samples/xamarin/xamarin-forms-samples/workingwithfonts/), a font file containing a hyphen isn't problematic.
