### ISSUE TITLE
Property TextType does not exist on label

### ISSUE THREAD

**Issue by Cload** [MicrosoftDocs/xamarin-docs#2284]
The Label class https://docs.microsoft.com/en-us/dotnet/api/xamarin.forms.label?view=xamarin-forms does not contain a property named TextType (at least not anymore), but it is referenced in the page https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/text/label#.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f8a6273c-62b1-ac18-aab3-62f78bdbade8
* Version Independent ID: 746bd180-ae67-313d-b949-538a508807b2
* Content: [Xamarin.Forms Label - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/text/label#display-html)
* Content Source: [docs/xamarin-forms/user-interface/text/label.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/text/label.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @Cload 

The `Label.TextType` property was introduced in Xamarin.Forms 4.3, so you must be using the latest NuGet package to access this property.

The Label API doc (https://docs.microsoft.com/en-us/dotnet/api/xamarin.forms.label?view=xamarin-forms) hasn't been updated yet.
