### ISSUE TITLE
Xamarin forms Lable textdecorators do not work on IOS when built using Vs 2019

### ISSUE THREAD

**Issue by sogetidev1** [MicrosoftDocs/xamarin-docs#2286]
Xamarin forms Lable textdecorators do not work on IOS after we got VS 2019. It works fine with Vs 2017. 
None of the below code workes on vs2019 and text does not get underlined:

 <Label Text="REMARKS"  HorizontalTextAlignment="Center" >
                                                    <Label.TextDecorations>
                                                        <OnPlatform iOS="Underline"/>
                                                    </Label.TextDecorations>
                                                </Label>

 <Label Text="REMARKS" TextDecorations="Underline" HorizontalTextAlignment="Center" >
                                                    
                                                </Label>

The text does not show with underline if I build it with vs2019 but underline shows if I build with vs2017
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a41aec46-a538-a8ad-5ed9-44a9138ae4cc
* Version Independent ID: 011fa795-cee3-059f-81a3-31aeca6fdd43
* Content: [Text in Xamarin.Forms - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/text/)
* Content Source: [docs/xamarin-forms/user-interface/text/index.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/text/index.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @sogetidev1 

Agreed. It's not a VS2019 problem as such. It's a Xamarin.Forms problem. An [issue](https://github.com/xamarin/Xamarin.Forms/issues/8272) has been logged in the engineering repo, and a fix produced. I recommend watching the issue to be notified when the fix goes live.

I'll close the issue here, as it's being dealt with by the engineers.
