### ISSUE TITLE
How to set BarbackgroundColor for iOS?

### ISSUE THREAD

**Issue by nguyenthanhliemfc** [MicrosoftDocs/xamarin-docs#2289]
How to set BarbackgroundColor for iOS in code only, Thank!
I only want to create code file NO XAML. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4cc2a90e-4630-65dc-55b6-9596bb0c9b40
* Version Independent ID: d7bc3049-8f79-9d9d-311e-e62d1a5a6194
* Content: [NavigationPage Bar Text Color Mode on iOS - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/platform/ios/status-bar-text-color#feedback)
* Content Source: [docs/xamarin-forms/platform/ios/status-bar-text-color.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/platform/ios/status-bar-text-color.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by nguyenthanhliemfc** [comment]
I need set in Code behide!

**Comment by davidbritch** [comment]
Hi @nguyenthanhliemfc 

The [doc](https://docs.microsoft.com/xamarin/xamarin-forms/platform/ios/status-bar-text-color#feedback) also has a C# example. In addition, the sample (linked to from the doc) has the same C# code.

**Comment by nguyenthanhliemfc** [comment]
@davidbritch Thank you!
