### ISSUE TITLE
This Notes sample project will not build

### ISSUE THREAD

**Issue by robertboxer** [MicrosoftDocs/xamarin-docs#2292]
The sample Notes project will not build while using a fresh install of Visual Studio 2019, version 16.3.7. Carefully following the steps given creates a project that results in build errors. 

For one, the build process cannot find this file:

Error Unable to access jarfile C:\Program Files (x86)\Android\android-sdk\build-tools\28.0.3\\lib\dx.jar	

Since this is a sample project that is supposed to give a new Xamarin developer an initial look at building Xamarin apps within Visual Studio, it is pretty pathetic that it doesn't build. An initial look is not supposed to turn into a debugging session.

Also, the sample zip file that contains the entire Notes project doesn't build either. 	

I suspect nobody has checked this out for compatibility with Visual Studio 2019. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5a064123-54f2-0eb2-c76a-65b36c5ec1a7
* Version Independent ID: dbf4119a-2c24-e0f1-8041-bb3755c29c24
* Content: [Create a single page Xamarin.Forms application - Xamarin](https://docs.microsoft.com/en-us/xamarin/get-started/quickstarts/single-page?pivots=windows#feedback)
* Content Source: [docs/get-started/quickstarts/single-page.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/get-started/quickstarts/single-page.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @robertboxer 

There's nothing wrong with the sample. I just loaded [it](https://docs.microsoft.com/samples/xamarin/xamarin-forms-samples/getstarted-notes-singlepage/) into VS2019, and it built and deployed perfectly to both iOS and Android.

From your error message it sounds like you have an issue with your Android tooling (either it not being installed, or not being installed correctly). I suggest you try creating the [first app](https://docs.microsoft.com/xamarin/get-started/first-app/?pivots=windows) to verify this.

**Comment by CosmicStresshead** [comment]
Hi David, 

Unfortunate the issue is that the code on page differs from that in the downloadable sample.  The downloadable sample works perfectly but if you follow along with the code on the web page it results in errors, namely that the editor object in the code behind isn't declared in the current context.  The differences seem to be minor but enough to cause errors if you're copying and pasting as per the instructions.  The code on the page might just need updating.

Thanks for the brilliant intro tutorials, I'm really loving C#.
