### ISSUE TITLE
Testing viewmodels which consume the singleton

### ISSUE THREAD

**Issue by BrayanKhosravian** [MicrosoftDocs/xamarin-docs#2293]
Hi, whats about testing all the viewmodels which reference the singleton?

1.) when my VMs consume the sqlite connection from the app class, i would always have to make sure if its not null, in order to test my VMs. But that way mocking becomes a pain and resolves to an integration test instead of a unittest.

2.) second way would be to write something like a wrapper class which just references the singleton from the App class. Then i could write an interface and inject the wrapper class as service. But is this really good way?

I hope that some could clarify this a bit better.
Thanks in advance.

Sincerely, Brayan

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bdcea465-138a-d586-5297-dc93370826b3
* Version Independent ID: a41a6f67-0675-036f-0781-13b9165d3848
* Content: [Xamarin.Forms Local Databases - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/data-cloud/data/databases?source=docs)
* Content Source: [docs/xamarin-forms/data-cloud/data/databases.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/data-cloud/data/databases.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by BrayanKhosravian** [comment]
Ok hi david, I think I found a good way to test my repositories actually. (Dont know if theres a better way actually)
Just want to show you my solution, just for the case if someone has to edit the docs. That could maybe help.

I attached some screenshots below.
A fiew things which could be important to mention:
- Im using Autofac as IoC container and instead of using a singleton in the Application root, i just register the repository as `.SingleInstance()` like this: `builder.RegisterType<IngredientRepository>().As<IIngredientRepository>().SingleInstance();`
- this means that i dont use any static fields inside my repository. 
- boolean property called `IsTest` located in my `BaseRepository` indicates if the test is being executed for a test. If its set to true, then i use a inMemory path like this `":memory:"`.

Im not sure if this solution is actually good to go, neither i dont know it that info helps.

Sincerely Brayan

This is my base repository:
![image](https://user-images.githubusercontent.com/35541212/68163381-b0365100-ff5a-11e9-9d1f-ddf695dce1e7.png)

This is my concrete class IngredientRepository which inherits from BaseRepository
![image](https://user-images.githubusercontent.com/35541212/68163456-d78d1e00-ff5a-11e9-8ac7-4087a978e689.png)

this is how i register my repository
![image](https://user-images.githubusercontent.com/35541212/68163859-ba0c8400-ff5b-11e9-9ebf-640318ae8488.png)

this is how i register and configure my app at the composition root
![image](https://user-images.githubusercontent.com/35541212/68163733-7ca7f680-ff5b-11e9-8207-51b896f63074.png)

this is how my test looks like
![image](https://user-images.githubusercontent.com/35541212/68163795-99442e80-ff5b-11e9-81b4-a1f36c80629d.png)

**Comment by BrayanKhosravian** [comment]
I made some changes actually and wrote a test.
The issue with my last approches i showed u was, that when i add another RepositoryClass and register it as singleinstance, the state of the baseclass was not shared.
Im not sure why, but i fixed that. Ill change the implementation a bit in the feature because im not that happy. But for now its fine.

**Comment by davidbritch** [comment]
Hi @BrayanKhosravian 

Thanks for the info. In a real app I'd be taking a similar approach - registering the repository as a singleton with an IoC container. But obviously in our docs we have to have minimal complexity, and just focus on the task at hand.

Unit testing repositories can be difficult, but it sounds like you've found a sensible approach.

Note that we've recently updated our local DB doc to use lazy initialisation of the db connection, for performance reasons.
