### ISSUE TITLE
Numerous build errors

### ISSUE THREAD

**Issue by bobcotte** [MicrosoftDocs/xamarin-docs#2294]
I made a fresh install of VS2019 on a system with no previous VS products. I tried the new project templates, the above mods, and other "sample downloads". Nothing builds because of numerous version issues.  For example, NETStandard.library V2.0 didn't work, System.numerics.vectors wasn't found and Xamarin.Forms was looking for 4.1.xxx and only 4.2.xxx was available.  

A link to the appropriate help forum would be a big help as well.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5a064123-54f2-0eb2-c76a-65b36c5ec1a7
* Version Independent ID: dbf4119a-2c24-e0f1-8041-bb3755c29c24
* Content: [Create a single page Xamarin.Forms application - Xamarin](https://docs.microsoft.com/en-us/xamarin/get-started/quickstarts/single-page?pivots=windows#feedback)
* Content Source: [docs/get-started/quickstarts/single-page.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/get-started/quickstarts/single-page.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @bobcotte 

I guarantee that the [sample](https://docs.microsoft.com/samples/xamarin/xamarin-forms-samples/getstarted-notes-singlepage/) works in VS2019.

It sounds like you have installation problems. I recommend you read our [installation guide](https://docs.microsoft.com/xamarin/get-started/installation/?pivots=windows), and then try building your [first app](https://docs.microsoft.com/xamarin/get-started/first-app/?pivots=windows). If the first app builds without any problems, you know all is well and can continue on your previous path.

As for where to go for help, I recommend [Developer Community](https://developercommunity.visualstudio.com/spaces/8/index.html) and the [Xamarin Community Forums](https://forums.xamarin.com).
