### ISSUE TITLE
This contradicts the documentation

### ISSUE THREAD

**Issue by johndaintree** [MicrosoftDocs/xamarin-docs#2297]
The page:

https://docs.microsoft.com/en-us/dotnet/api/system.reflection.emit.assemblybuilder?view=xamarinios-10.8

suggests that Reflection.Emit IS available on Xamarin.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 500b8f87-12fb-9f14-9655-06cd3f1d91d2
* Version Independent ID: b199d974-6356-af0e-9d96-81e54953b65d
* Content: [Limitations of Xamarin.iOS - Xamarin](https://docs.microsoft.com/en-us/xamarin/ios/internals/limitations)
* Content Source: [docs/ios/internals/limitations.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/ios/internals/limitations.md)
* Product: **xamarin**
* Technology: **xamarin-ios**
* GitHub Login: @davidortinau
* Microsoft Alias: **daortin**

**Comment by conceptdev** [comment]
In this case, the documentation is correct:

>Due to the limitations on iOS (no JIT compilation) this is not supported.

Regardless of whether the method is surfaced in the Xamarin.iOS version of mono. `Reflection.Emit` is not supported on Xamarin.iOS.
