### ISSUE TITLE
Disclosure indicators

### ISSUE THREAD

**Issue by pfedotovsky** [MicrosoftDocs/xamarin-docs#2298]
With ListView, it’s very easy to add disclosure indicators for iOS as required by guidelines. With CollectionView the only way I see is to manually add them to every template. This difference should be mentioned in documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e1a71b09-4e7a-a84b-5495-154552b2cc93
* Version Independent ID: c7dfd258-be01-f156-0a7f-3ee91e0af5b2
* Content: [Xamarin.Forms CollectionView Introduction - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/collectionview/introduction#feedback)
* Content Source: [docs/xamarin-forms/user-interface/collectionview/introduction.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/collectionview/introduction.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @pfedotovsky 

Apologies for the delayed response. Yes, the best approach would be modifying your `DataTemplate`, and only show the Image (for the disclosure indicator) on iOS.

Out of interest, what's your scenario for requiring disclosure indicators? For example, are you wanting to use `CollectionView` for a navigation menu? Or are you trying to reproduce the look and feel of a `UITableView`?

**Comment by davidbritch** [comment]
I've added some text about disclosure indicators, in a PR that will go live later today.
