### ISSUE TITLE
Sample download link - 404 not found

### ISSUE THREAD

**Issue by timmi4sa** [MicrosoftDocs/xamarin-docs#2299]
'nuf said.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a9d4ba1f-8a3a-b72a-75b4-4ad6138ecec9
* Version Independent ID: 4fd13d66-c654-7ab3-58ce-1806c8383d67
* Content: [Xamarin.Forms RefreshView - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/refreshview)
* Content Source: [docs/xamarin-forms/user-interface/refreshview.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/refreshview.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @timmi4sa 

Sorry about this. For some reason the build system didn't detect the sample in the repo. I've given it a prod and will close this issue once it's fixed.

**Comment by davidbritch** [comment]
This is now fixed.
