### ISSUE TITLE
Workbooks header image not visible for non-english versions

### ISSUE THREAD

**Issue by CayasSoftware** [MicrosoftDocs/xamarin-docs#23]
Visiting the documentation in German (de-de) does not show the Workbooks header image. I also tested it for Spanish (es-es) with the same result.

The reason is an URL pointing to:
https://review.docs.microsoft.com/en-us//media/illustrations/dynamics-resource-library.svg

instead of:

https://docs.microsoft.com/en-us/media/illustrations/dynamics-resource-library.svg

**Comment by bradumbaugh** [comment]
@CayasSoftware Thanks for calling this out, appreciate it. We've committed a fix for this, so you should see an update soon.
