### ISSUE TITLE
Suggests a deprecated api

### ISSUE THREAD

**Issue by verybadcat** [MicrosoftDocs/xamarin-docs#230]
This document is highly confusing as ActionBar tabs are now deprecated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dde0de0f-6bc7-cc20-6cde-b5de791445ef
* Version Independent ID: a309f7bb-7de9-6ccd-589b-2f60e1d9056d
* Content: [Walkthrough - Creating a tabbed UI with TabHost - Xamarin](https://docs.microsoft.com/en-us/xamarin/android/user-interface/layouts/tab-layout/creating-a-tabbed-ui)
* Content Source: [docs/android/user-interface/layouts/tab-layout/creating-a-tabbed-ui.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/android/user-interface/layouts/tab-layout/creating-a-tabbed-ui.md)
* Service: **unspecified**
* GitHub Login: @mgmclemore
* Microsoft Alias: **mamcle**

**Comment by topgenorth** [comment]
Thanks for pointing this out. The TabHost is very out of date; we'll remove this guide from our docs.
