### ISSUE TITLE
Shell.NavBarIsVisible="False"  is not work

### ISSUE THREAD

**Issue by CeciAc** [MicrosoftDocs/xamarin-docs#2304]
@wa926talent commented on [Thu Nov 07 2019](https://github.com/MicrosoftDocs/xamarin-docs.zh-cn/issues/58)

[Enter feedback here]
Shell.NavBarIsVisible="False"  is not work 
Xamarin.Forms  4.3.0.947036
Android 9.0
---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: c9d653fd-51ed-ed03-db65-a9efb684dc12
* Version Independent ID: 06470094-10f9-b28e-4ece-4da457a4a609
* Content: [Xamarin.Forms Shell 页面配置 - Xamarin](https://docs.microsoft.com/zh-cn/xamarin/xamarin-forms/app-fundamentals/shell/configuration)
* Content Source: [docs/xamarin-forms/app-fundamentals/shell/configuration.md](https://github.com/MicrosoftDocs/xamarin-docs.zh-cn/blob/live/docs/xamarin-forms/app-fundamentals/shell/configuration.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

---

@srvbpigh commented on [Thu Nov 07 2019](https://github.com/MicrosoftDocs/xamarin-docs.zh-cn/issues/58#issuecomment-551164413)

Hello, @wa926talent
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hi team, 

I moved this here because it looks like it's about the example

**Comment by davidbritch** [comment]
Hi @CeciAc 

This isn't about the sample as such. It's more a comment that a piece of functionality in Xamarin.Forms isn't working. Therefore, it's an issue for the [engineers](https://github.com/xamarin/Xamarin.Forms) rather than docs.
