### ISSUE TITLE
Platform specific model 

### ISSUE THREAD

**Issue by pmahend1** [MicrosoftDocs/xamarin-docs#2306]
*Platform Implementation Specifics* is subheading under `DeviceInfo.Model` Its mentioned as Platform Implementation Specifics which is not so explicit and seems confusing since we have `DeviceInfo.Platform`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c918dea8-217e-8886-73ad-c1dcb9cc1e1e
* Version Independent ID: 238f8427-325c-dc77-caaf-1f3a8e44df88
* Content: [Xamarin.Essentials: Device Information - Xamarin](https://docs.microsoft.com/en-us/xamarin/essentials/device-information?context=xamarin%2Fxamarin-forms&tabs=ios)
* Content Source: [docs/essentials/device-information.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/essentials/device-information.md)
* Product: **xamarin**
* Technology: **xamarin-essentials**
* GitHub Login: @jamesmontemagno
* Microsoft Alias: **jamont**

**Comment by jamesmontemagno** [comment]
We standardized on this verbiage to be standard across all of the Essentials docs at the bottom of section summarizing all the APIs. @conceptdev thoughts?

**Comment by conceptdev** [comment]
Thanks for the feedback. It's unfortunate that it has caused confusion in this instance; but I think the consistency across all the Xamarin.Essentials is important, so not something we want to change for now.
