### ISSUE TITLE
Missing note for developers migrating from Xam.Plugins.Settings

### ISSUE THREAD

**Issue by albertoms** [MicrosoftDocs/xamarin-docs#2307]
The first thought that I had when I started the migration from `Xam.Plugins.Settings` to `Essentials.Preferences` was that I should create—and I did—a copy of every current stored value in Settings into the Preferences implementation. But when I was on the final steps of the migration I found out that, in fact, _both plugins access to the same file on device to fetch the associated values for the preferences defined in code_.

I wasted a few hours on the unnecessary task of copying values between implementations and I take full responsibility for that. My suggestion is to add a note (like the above in italics) on the Preferences documentation for developers in my situation in order to help them save tame on the migration, which is reduced to change:

Settings way:
```
public string SettingSample {
  get => CrossSettings.Current.GetValueOrDefault(nameof(SettingSample), string.Empty);
  set => CrossSettings.Current.AddOrUpdateValue(nameof(SettingSample), value);
}
```

to the Preferences way:
```
public string SettingSample {
  get => Preferences.Get(nameof(SettingSample), string.Empty);
  set => Preferences.Set(nameof(SettingSample), value);
}
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a7a399b1-a8a2-9cbd-c479-1bd98af46988
* Version Independent ID: 91a6ae06-508b-b668-52aa-cbdeabb2b46a
* Content: [Xamarin.Essentials: Preferences - Xamarin](https://docs.microsoft.com/en-us/xamarin/essentials/preferences?tabs=android#feedback)
* Content Source: [docs/essentials/preferences.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/essentials/preferences.md)
* Product: **xamarin**
* Technology: **xamarin-essentials**
* GitHub Login: @jamesmontemagno
* Microsoft Alias: **jamont**

**Comment by jamesmontemagno** [comment]
I don't think this is something we would put on official docs. I outlined it all in a blog post: https://montemagno.com/upgrading-from-plugins-to-xamarin-essentials/

**Comment by albertoms** [comment]
That's understandable. What about doing it the other way around, pointing out to this nice and detailed blog post on the SettingsPlugin repo? I opened a tab for each API reference but it didn't hit me until I dug a bit deeper.

**Comment by conceptdev** [comment]
Thanks for the feedback and suggestion @albertoms.
