### ISSUE TITLE
priceObserver = succeededObserver

### ISSUE THREAD

**Issue by c-lamont** [MicrosoftDocs/xamarin-docs#2308]
The field `priceObserver` should be `succeededObserver` as described in line `NSObject succeededObserver, failedObserver;`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3362d3a6-b1e9-0f6b-f18e-e4f09b8c166f
* Version Independent ID: 396e6078-9c25-4f01-f3ea-d6d37e9c7315
* Content: [Purchasing Consumable Products in Xamarin.iOS - Xamarin](https://docs.microsoft.com/en-us/xamarin/ios/platform/in-app-purchasing/purchasing-consumable-products)
* Content Source: [docs/ios/platform/in-app-purchasing/purchasing-consumable-products.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/ios/platform/in-app-purchasing/purchasing-consumable-products.md)
* Product: **xamarin**
* Technology: **xamarin-ios**
* GitHub Login: @davidortinau
* Microsoft Alias: **daortin**

**Comment by conceptdev** [comment]
Thanks for the fix! Implementing now.
