### ISSUE TITLE
Not accurate for me

### ISSUE THREAD

**Issue by KeithBoynton** [MicrosoftDocs/xamarin-docs#231]
Using Visual Studio 7.4.3 for the Mac the suggested location above doesn't exist. In fact _/Users/&lt;username&gt;/Library/Caches/Xamarin_ doesn't exist on my system.

The dSYM package can be found in the target build location so long as Debug information is switched on in the compiler options for that target. For me I chose (Symbols only). In my case the package was created here: _&lt;projectfolder&gt;/bin/iPhone/AppStore/MyApp.dSYM_

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 787467fb-f4f4-74f4-6111-d9bbb38f96f0
* Version Independent ID: 946c9585-0e67-7d46-3a21-ad5aa9bcc4c1
* Content: [Where can I find the .dSYM file to symbolicate iOS crash logs? - Xamarin](https://docs.microsoft.com/en-us/xamarin/ios/troubleshooting/questions/symbolicate-ios-crash)
* Content Source: [docs/ios/troubleshooting/questions/symbolicate-ios-crash.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/ios/troubleshooting/questions/symbolicate-ios-crash.md)
* Service: **unspecified**
* GitHub Login: @bradumbaugh
* Microsoft Alias: **brumbaug**

**Comment by bradumbaugh** [comment]
Hi @KeithBoynton, thanks for calling this out. I've put together an update for this doc – should be published soon. Thanks again!
