### ISSUE TITLE
Version issues with nuGet package SQLite-net-pcl

### ISSUE THREAD

**Issue by DaFreeLum** [MicrosoftDocs/xamarin-docs#2310]
As a seasoned developer ( I started in IT in 1991) I was impressed with how straight forward this quic start was that was until I tried the last section - adding an SQLite database. Unfortunately I used NuGet to get the latest version which compiled but caused an error - I downloaded the sample which worked OK so after comparing the sample project with my own I realised the only difference was the version of the sqlite-net-pcl package - after downgrading to the same as the sample project all was tickety boo 

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5a064123-54f2-0eb2-c76a-65b36c5ec1a7
* Version Independent ID: dbf4119a-2c24-e0f1-8041-bb3755c29c24
* Content: [Create a single page Xamarin.Forms application - Xamarin](https://docs.microsoft.com/en-gb/xamarin/get-started/quickstarts/single-page?pivots=windows#building-the-quickstart)
* Content Source: [docs/get-started/quickstarts/single-page.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/get-started/quickstarts/single-page.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @DaFreeLum 

Thanks for mentioning this. I'll close this issue but will link to it from your other open issue.
