### ISSUE TITLE
What about "Pressed" state for buttons?

### ISSUE THREAD

**Issue by Mikilll94** [MicrosoftDocs/xamarin-docs#2312]
```
The Xamarin.Forms Visual State Manager defines one visual state group named "CommonStates" with three visual states: "Normal", "Disabled", "Focused"
```

What about "Pressed" state for buttons? There is no info about that in this article.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b744a13f-16ad-4f35-cdf2-bdfd6fa90df1
* Version Independent ID: 7a08549b-07a5-085b-0c93-255d9e84d7a3
* Content: [The Xamarin.Forms Visual State Manager - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/visual-state-manager)
* Content Source: [docs/xamarin-forms/user-interface/visual-state-manager.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/visual-state-manager.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @Mikilll94 

The VisualStateManager doc only discusses the states that are common to all controls. Any additional states are mentioned in the doc for the specific control (e.g. https://docs.microsoft.com/xamarin/xamarin-forms/user-interface/button#button-visual-states).

I'll add something to the VSM doc to that affect.

**Comment by Mikilll94** [comment]
@davidbritch 
It would be nice to see somewhere all states listed for all controls.

**Comment by davidbritch** [comment]
@Mikilll94 

Makes sense. I'll add a table to the VSM doc, hopefully later this week.

**Comment by Mikilll94** [comment]
@davidbritch 
Thanks you very much

**Comment by Mikilll94** [comment]
@davidbritch 
Ping. I don't see any table.

**Comment by davidbritch** [comment]
@Mikilll94 I've not forgotten about this (that's why the issue is still open). I'm just heads down on some high priority work. Once that's complete, I'll get back to dealing with open issues.

**Comment by davidbritch** [comment]
Hi @Mikilll94 

This is now done in a PR that will go live later this week. For the record, there are only states implemented in four classes at the moment - Button, CollectionView, ImageButton, and VisualElement.
