### ISSUE TITLE
Richer example

### ISSUE THREAD

**Issue by DamianMehers** [MicrosoftDocs/xamarin-docs#2313]
There is a richer, but more complicated example in the mono linker github https://github.com/mono/linker

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f76b85eb-e640-6751-7eb2-fc58676d6018
* Version Independent ID: 422c639a-104a-4e31-cc78-03c023dd05ab
* Content: [Custom Linker Configuration - Xamarin](https://docs.microsoft.com/en-us/xamarin/cross-platform/deploy-test/linker)
* Content Source: [docs/cross-platform/deploy-test/linker.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/cross-platform/deploy-test/linker.md)
* Product: **xamarin**
* Technology: **xamarin-crossplatform**
* GitHub Login: @davidortinau
* Microsoft Alias: **daortin**

**Comment by conceptdev** [comment]
Thanks for the recommendation, adding to the page.
