### ISSUE TITLE
Hot Reload Cause VS2019 to hang when using IOS Simulator

### ISSUE THREAD

**Issue by buzzbonner** [MicrosoftDocs/xamarin-docs#2315]
The feature generally works well when debugging with VS2019. However, on ending the debug session by closing the Simulator, VS2019 hangs with the message VS2019 is busy. This never seems to finish.

No errors are reported and nothing written to the output window.

**Comment by conceptdev** [comment]
@buzzbonner please use the [Report a problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2019) feature in Visual Studio, which can include system information and logs to help diagnose.
