### ISSUE TITLE
Update this page information and the GitHub project is desirable

### ISSUE THREAD

**Issue by OvidiuCaba** [MicrosoftDocs/xamarin-docs#2316]
MySample is not compilable because it misses a parameterless constructor. It would be nice if you update this page and the Droid project on GitHub (it doesn't work either).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9513f471-5dbf-c597-74da-0538f625cf39
* Version Independent ID: 6bc6322f-f6bb-2121-b5d0-9d383bedbee7
* Content: [Introduction to UrhoSharp - Xamarin](https://docs.microsoft.com/en-us/xamarin/graphics-games/urhosharp/introduction#feedback)
* Content Source: [docs/graphics-games/urhosharp/introduction.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/graphics-games/urhosharp/introduction.md)
* Product: **xamarin**
* Technology: **xamarin-crossplatform**
* GitHub Login: @conceptdev
* Microsoft Alias: **crdun**

**Comment by davidbritch** [comment]
UrhoSharp is now obsolete, so I'm closing this issue.
