### ISSUE TITLE
Accept pull requests on GitHub

### ISSUE THREAD

**Issue by OvidiuCaba** [MicrosoftDocs/xamarin-docs#2317]
Accept pull requests on GitHub or reject them or add comments so that the reqesters understand what's happening. Initially I intended to try to fix the Android project for SamplyGame, but I was discouraged by the fact that no one responds to the PRs. I don't want to waste time for something invaluable. So if you want the community to get involved, behave in such a way that the people are encouraged to do so.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9513f471-5dbf-c597-74da-0538f625cf39
* Version Independent ID: 6bc6322f-f6bb-2121-b5d0-9d383bedbee7
* Content: [Introduction to UrhoSharp - Xamarin](https://docs.microsoft.com/en-us/xamarin/graphics-games/urhosharp/introduction#feedback)
* Content Source: [docs/graphics-games/urhosharp/introduction.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/graphics-games/urhosharp/introduction.md)
* Product: **xamarin**
* Technology: **xamarin-crossplatform**
* GitHub Login: @conceptdev
* Microsoft Alias: **crdun**

**Comment by conceptdev** [comment]
@OvidiuCaba here in docs we endeavor to process PRs promptly, and although there are currently 7 open, we've accepted over 700. Reasons for delay can include a large verification burden (PRs submitted that touch scores or hundreds of files), people being on unavailable (holidays or busy times), or sometimes difficultly finding the subject-matter-expert to approve. 

Other repos are the responsibility of various teams, so responses can vary based on that team, but I would certainly welcome any Xamarin documentation PRs you'd care to submit.

Thanks for your feedback, I understand your perspective and agree that stale PRs can discourage other contributors.
