### ISSUE TITLE
Code Sample Does Not Compile

### ISSUE THREAD

**Issue by marcusts** [MicrosoftDocs/xamarin-docs#2318]
The code sample is out of date.

"UnregisterAllAsync has 1 parameter(s) but is invoked with 2 arguments".

Please update when possible, thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 92f390d9-cbd0-ab8c-6c8c-49df76d1b8e0
* Version Independent ID: 15739c2f-afbb-c21d-b96f-fabe7060e410
* Content: [Send and receive push notifications with Azure Notification Hubs and Xamarin.Forms - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/data-cloud/azure-services/azure-notification-hub)
* Content Source: [docs/xamarin-forms/data-cloud/azure-services/azure-notification-hub.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/data-cloud/azure-services/azure-notification-hub.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @profexorgeek
* Microsoft Alias: **jusjohns**

**Comment by profexorgeek** [comment]
Hi @marcusts,
I just tested the sample on iOS with Visual Studio 2019 and didn't have any compilation problems. If you updated nuget packages to a different version it could be that method signatures have changed. However the sample compiled for me without any issues.

Can you provide any more details about your problem?

**Comment by marcusts** [comment]
Hi Justin,

Yes, like most programmers, I keep NuGet up-to-date. The sample is not
up-to-date.

I have revised the code to work without the error handling.  The problem
now is that it is no longer compatible with our code from the past several
years:

public static string MobileServiceUrl = "
https://acsaccountviewnotificationsbackend20180625044448.azurewebsites.net";

We used to both register and issue notifications using this URL.

Now we register using:

public static string NotificationHubName { get; set; } =
"AccountViewNHXamarin";
public static string ListenConnectionString { get; set; } = "Endpoint=sb://
accountviewnhxamarin.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=gSOKkRO1fwdbK0g4ITUK63Lp5py3IETXpi8RBpq8L+Q=
";

... so we can't send pushes using the older system.

Is there a URL where can go to see how to migrate to this new
SBNotificationHub on the back end?

Thanks!

Stephen

**Comment by profexorgeek** [comment]
Hi @marcusts,
I wanted to let you know that I am looking into this. It's interesting because the iOS NuGet package had a major revision update but the Android package only had minor revisions. I'm working to understand the broader context and impact of the iOS update so I can update our docs and sample.

Some of this appears to be related to the updates for iOS 13, which are fairly recent. I'm not sure if this has any impact on you but it might be helpful to know: https://docs.microsoft.com/en-us/azure/notification-hubs/push-notification-updates-ios-13

**Comment by marcusts** [comment]
Hey Justin,

Yes, you are correct.  That is also my observation. IOS tends to be a
rigorous enforce of rules... Android lags a bit and does to act
dogmatically.

The code samples mostly affect the front end.  The back end changes are a
bit of surprise, so I am trying to help out my IT guys and make sure they
don’t fall out of step.

Stephen
