### ISSUE TITLE
"target/compile version for Android projects must be set to Use latest installed platform" and CI/CM

### ISSUE THREAD

**Issue by gjkhw** [MicrosoftDocs/xamarin-docs#232]
The requirement that "target/compile version for Android projects must be set to Use latest installed platform." creates a problem for my non-play store application. I have a CI/CM machine that has many versions of the Android SDK installed, and will continue to get newer versions installed over time. 

If I want to make a hot fix for a customer build based on an older version of the Android SDK, I risk introducing a behavior change because a newer Android SDK may have been installed on the CI/CM machine at some point in time after the customer builds was made.

It would be helpful to explain this "latest SDK" requirement in more detail. It would be even more helpful to provide a way to not require it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d8ef5687-ac87-e450-5d84-f17bc91788fe
* Version Independent ID: 1fd9e99d-1119-f1ff-a5d9-d8c58b5c47be
* Content: [Xamarin.Forms Requirements - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/get-started/installation?tabs=vswin)
* Content Source: [docs/xamarin-forms/get-started/installation.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/get-started/installation.md)
* Service: **unspecified**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by conceptdev** [comment]
Hi @gjkhw, thanks for your feedback. This information is best shared with the team via the [Visual Studio Developer Community](https://developercommunity.visualstudio.com/); these issues are intended for highlighting and fixing issues with the docs themselves.
