### ISSUE TITLE
AbsoluteLayout is obsolete

### ISSUE THREAD

**Issue by OvidiuCaba** [MicrosoftDocs/xamarin-docs#2320]
AbsoluteLayout is obsolete. Perhaps FrameLayout should be used instead [this is what I use and seems to work properly].

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 93bcf8b5-741a-9b50-5192-06baa2a03cbb
* Version Independent ID: 27814cb7-9a0e-4292-d367-86073068034b
* Content: [UrhoSharp Android support - Xamarin](https://docs.microsoft.com/en-us/xamarin/graphics-games/urhosharp/platform/android)
* Content Source: [docs/graphics-games/urhosharp/platform/android.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/graphics-games/urhosharp/platform/android.md)
* Product: **xamarin**
* Technology: **xamarin-crossplatform**
* GitHub Login: @conceptdev
* Microsoft Alias: **crdun**

**Comment by davidbritch** [comment]
UrhoSharp is now obsolete, so I'm closing this issue.
