### ISSUE TITLE
There is no longer an AssemblyInfo.cs file in the cross-platform project

### ISSUE THREAD

**Issue by jbachelor** [MicrosoftDocs/xamarin-docs#2321]
Hello,
I'm working on implementing multiple languages for a Xamarin.Forms app (.NET Standard), where there is no AssemblyInfo.cs file in the cross-platform project. It would be awesome if the documentation regarding setting the default app language (NeutralResourcesLanguage) could provide some guidance as to where we can specify the NeutralResourcesLanguage. I'm not sure where/how to set this currently. Perhaps in App.xaml.cs?

Link to the documentation section:  https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/localization/text?pivots=windows#specify-the-default-culture 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: af66394d-81c5-0c2e-1682-a2bb7eeb3c3e
* Version Independent ID: 27542a45-2f25-4042-cf48-b9517025635c
* Content: [String and Image Localization in Xamarin.Forms - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/localization/text?pivots=windows)
* Content Source: [docs/xamarin-forms/app-fundamentals/localization/text.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/app-fundamentals/localization/text.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @profexorgeek
* Microsoft Alias: **jusjohns**

**Comment by profexorgeek** [comment]
Technically this line:
`[assembly: NeutralResourcesLanguage("en-US")]`
can be put into any file that is included and compiled in your project. However, the best practice is typically to put it into the AssemblyInfo.cs file with similar attributes so they are grouped in one place. If your project doesn't have an AssemblyInfo.cs file you can simply create it and make sure it is included in .csproj. The entire file can just be this if you have no other attributes to specify:
```csharp
using System.Resources;

[assembly: NeutralResourcesLanguage("en-US")]
```

For more information about assemblies, see [Set Assembly Attributes](https://docs.microsoft.com/en-us/dotnet/standard/assembly/set-attributes)

**Comment by jbachelor** [comment]
Thanks very much... I greatly appreciate your help!  =)
