### ISSUE TITLE
Xamarin Forms + Prism: Frame with Material visual not fire EventToCommandBehavior on iOS.

### ISSUE THREAD

**Issue by Schinwinkwinsky** [MicrosoftDocs/xamarin-docs#2324]
At my code there´s a ListView that uses a custom view as its ItemTemplate. It was set a behavior using the Prism EventToCommandBehavior:

![image](https://user-images.githubusercontent.com/13337108/69154690-3b692800-0abf-11ea-8ed3-d7e60f202bc5.png)

That´s the PromotionView:

![image](https://user-images.githubusercontent.com/13337108/69154806-723f3e00-0abf-11ea-8427-2127e08735b9.png)

At PromotionView I set the Frame Visual property as Material. After that, when the user clickes at the list element, the app don´t respond as expected. Nothing happens. I´m facing this problem only on iOS (Android runs properly) and when the Frame visual is set as Material.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fbfbc90e-2eb6-a305-f7da-bded6e31a2b4
* Version Independent ID: 66cad08c-2158-c081-a668-e4dad525e664
* Content: [Xamarin.Forms Material Visual - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/visual/material-visual)
* Content Source: [docs/xamarin-forms/user-interface/visual/material-visual.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/visual/material-visual.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @Schinwinkwinsky 

This sounds like an issue for the engineers to look into. Therefore you should open an issue in the [engineering repo](https://github.com/xamarin/Xamarin.Forms). The engineers will require a ZIP of a reproduction in order to investigate.
