### ISSUE TITLE
How to set GC options?

### ISSUE THREAD

**Issue by pmahend1** [MicrosoftDocs/xamarin-docs#2327]
How do I set GC options in Android project settings?

Suppose I want to set it to new instead of tarjan where and what will I change in project settings?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 626dace3-cf0d-1c6e-6320-ca8007a0b97e
* Version Independent ID: b71ec0ef-9178-bfee-b693-dbcaac002879
* Content: [Garbage Collection - Xamarin](https://docs.microsoft.com/en-us/xamarin/android/internals/garbage-collection#feedback)
* Content Source: [docs/android/internals/garbage-collection.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/android/internals/garbage-collection.md)
* Product: **xamarin**
* Technology: **xamarin-android**
* GitHub Login: @davidortinau
* Microsoft Alias: **daortin**

**Comment by bruzkovsky** [comment]
Hi @pmahend1,

you just add a file to your android project, name it e.g. AndroidEnvironment.txt (or anything you want) and set the build action to `AndroidEnvironment`. Then you add the following to the file:
```
MONO_GC_PARAMS=bridge-implementation=new
```

**Comment by pmahend1** [comment]
@bruzkovsky Yes. I figured that out. I opened the issue so that it's added clearly in documentation as well.

**Comment by profexorgeek** [comment]
Hi @pmahend1,
The existing documentation seems to offer similar information to what @bruzkovsky contributed:

> `bridge-implementation` = bridge implementation : This will set the GC Bridge option to help address GC performance issues. There are three possible values: old , new , tarjan.

Was there something specific, not already mentioned here, that would help make this clearer?

**Comment by pmahend1** [comment]
The documentation doesn't explain is it accomplished by adding text file and setting it to Android environment explicity.

**Comment by profexorgeek** [comment]
Ah I see what you mean. The doc actually does mention this but it is later in the Configuration section. The GC Bridge section doesn't cover adding the file. I'm rewording that a bit for clarity and will push an update shortly!
