### ISSUE TITLE
C# , Mobile App, for Android and iOS, Share Code with .Net standard

### ISSUE THREAD

**Issue by souris999** [MicrosoftDocs/xamarin-docs#2328]
Starting with the template of a C# .net standard , Mobile App, for Android and iOS, what is the way to share platform specific code?
For example to get the description/version of the OS, access to a USB device...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b4445585-af8f-09d3-5d35-762c3aac187b
* Version Independent ID: fa9263db-60d6-eb98-eb74-842351ba5387
* Content: [Build your first Xamarin.Forms app - Xamarin](https://docs.microsoft.com/en-us/xamarin/get-started/first-app/?pivots=windows#feedback)
* Content Source: [docs/get-started/first-app/index.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/get-started/first-app/index.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @conceptdev
* Microsoft Alias: **crdun**

**Comment by davidbritch** [comment]
Hi @souris999 

For the options for sharing code across platforms, see [Sharing code on multiple platforms](https://docs.microsoft.com/en-gb/xamarin/cross-platform/app-fundamentals/).

In addition, [Xamarin.Essentials](https://docs.microsoft.com/xamarin/essentials/) provides cross-platform APIs for commonly used mobile functionality (device info, sensors etc).
