### ISSUE TITLE
There's no real use of DataTemplateSelector in a map!

### ISSUE THREAD

**Issue by mshwf** [MicrosoftDocs/xamarin-docs#2329]
This is a [useless thing](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/map/pins#choose-item-appearance-at-runtime) to have in a map, there's no way to customize a pin (not even its color) thus the `DataTemplateSelector` has no real-scenario use! 
Remove it or show a real example of using it!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d967c4fc-27ef-2712-f902-db53cef7f5dc
* Version Independent ID: ee85bf33-2ce2-fc75-3806-50167b47a1f5
* Content: [Xamarin.Forms Map Pins - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/map/pins#feedback)
* Content Source: [docs/xamarin-forms/user-interface/map/pins.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/map/pins.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @mshwf 

The [PR](https://github.com/xamarin/Xamarin.Forms/pull/5226) that added a DataTemplateSelector to Map was made by a community member, in response to another community member making the [suggestion](https://github.com/xamarin/Xamarin.Forms/pull/4269#issuecomment-452822221).

With that said, the doc could be made more clear by outlining the usage scenario, so I'll give it an update.

**Comment by davidbritch** [comment]
Doc update has been made, in a PR that will go live later.

**Comment by mshwf** [comment]
> Hi @mshwf
> 
> The [PR](https://github.com/xamarin/Xamarin.Forms/pull/5226) that added a DataTemplateSelector to Map was made by a community member, in response to another community member making the [suggestion](https://github.com/xamarin/Xamarin.Forms/pull/4269#issuecomment-452822221).
> 
> With that said, the doc could be made more clear by outlining the usage scenario, so I'll give it an update.

Thanks for clarifying.

**Comment by islamghost1** [comment]
how can i bind this two properties to my code behind :
