### ISSUE TITLE
Only describes NON-INTERACTIVE native views via C#; what about button clicks and other interaction?

### ISSUE THREAD

**Issue by MappingSteve** [MicrosoftDocs/xamarin-docs#233]
I doubt anyone would bother to wrap a native view, just to show STATIC information that can't be INTERACTED with.  But that is all that is shown on this page.

In "Native Views in XAML", there is a great discussion of "Native Bindings". Is there an equivalent in C#?  

Equally important, one of the major reasons to wrap native UI is to take existing native code + UI, and use it within an X Forms app. How pass information between the old native "code behind", and the wrapping ContentPage or ContentView?  Or what "rework" could/should be done to the native "code behind", to fit better into X Forms?

When does it make sense to use the technique shown on this page, vs doing "Customizing a ContentPage"? https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/custom-renderer/contentpage

This also appears to be a related technique;  "Custom Renderers / Implementing a View" https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/custom-renderer/viewcell

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 74c821e6-ae09-bbe7-7bc5-0062c2bb29fb
* Version Independent ID: 0daa9061-aebb-529f-2bf1-f2c7b883bcc3
* Content: [Native Views in C# - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/platform/native-views/code)
* Content Source: [docs/xamarin-forms/platform/native-views/code.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/platform/native-views/code.md)
* Service: **unspecified**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @MappingSteve 

Thanks for the feedback. The "Native Views in C#" feature was a first attempt by the engineering team to permit embedding of native views into Forms apps. The functionality it offers is not as extensive as the "Native Views in XAML" feature that superseded it.

`MessagingCenter` is one approach for communicating between the native code and the wrapping Forms control. Another is to make the native code XAML friendly - see https://docs.microsoft.com/en-us/xamarin/xamarin-forms/platform/native-views/xaml#subclassing-native-views

As for whether to use native views over custom renderers, it all depends on the native code you're wrapping. Custom renderers used to be the only option for doing this but many people prefer to avoid creating a custom renderer for small customisations, preferring to use native views instead.
