### ISSUE TITLE
Application Uploader was removed from Xcode

### ISSUE THREAD

**Issue by AndresRR-IG** [MicrosoftDocs/xamarin-docs#2336]
[Enter feedback here]
This docs are outdated.
Application Uploader was removed from Xcode, should use Transport App instead.

Regards.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fd717da0-195f-0f8e-28ac-b2f9d279477d
* Version Independent ID: cdd99f6b-7ace-0740-ff84-61f90af13acd
* Content: [Upload to Mac App Store - Xamarin](https://docs.microsoft.com/en-us/xamarin/mac/deploy-test/publishing-to-the-app-store/uploading)
* Content Source: [docs/mac/deploy-test/publishing-to-the-app-store/uploading.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/mac/deploy-test/publishing-to-the-app-store/uploading.md)
* Product: **xamarin**
* Technology: **xamarin-mac**
* GitHub Login: @davidortinau
* Microsoft Alias: **daortin**

**Comment by conceptdev** [comment]
Thanks for the feedback @AndresRR-IG, I've just updated the page with a link to download **Transporter**. Should be published soon.
