### ISSUE TITLE
Documentation doesn't properly handle passing parameters and loading data async nor handle naming of properties versus parameters.

### ISSUE THREAD

**Issue by JohnGalt1717** [MicrosoftDocs/xamarin-docs#2337]
Nameing of properties:

eg:  Property on page called PlaylistId which is a nullable int.

await Shell.Current.GoToAsync($"//playlists/playlist?playlistId={playlist.Id}"); -- Doesn't work. (navigates to page but set never called)
await Shell.Current.GoToAsync($"//playlists/playlist?playlistid={playlist.Id}"); -- Same
await Shell.Current.GoToAsync($"//playlists/playlist?PlaylistId={playlist.Id}"); --Same

Not clear if this is supposed to set these properties before OnAppearing (I would hope so). This means that the example above is contrived. The most common use case would be to pass an Id value and then do an http client call async to lookup the resulting object or list and then set that into the binding context. None of that is possible by setting the BindingContext in the syncronous setter.

This needs to be massively expanded to show how to do this properly in the context of loading data asynchronously when the page is navigated to with parameters and setting the bindingmodel on appearing or similar.  And in this case it should handle multiple properties, all from async calls wound up in Task.WhenAll to be set into the bindingmodel for efficiency.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b6efe82d-a8b9-82a8-7d38-98f2f8d5e682
* Version Independent ID: 28d7341e-ae6e-6321-6550-d27ae6b256d2
* Content: [Xamarin.Forms Shell Navigation - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/shell/navigation#feedback)
* Content Source: [docs/xamarin-forms/app-fundamentals/shell/navigation.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/app-fundamentals/shell/navigation.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @JohnGalt1717 

Shell navigation is currently a bit limited, and will be enhanced in a future release. When that happens, the docs will be expanded. In the meantime, the enhancement request can be found [here](https://github.com/xamarin/Xamarin.Forms/issues/5166).
