### ISSUE TITLE
Documentation doesn't sufficiently discribe how to use Searchbox Visibility and these instructions result in no search showing on android or iOS

### ISSUE THREAD

**Issue by JohnGalt1717** [MicrosoftDocs/xamarin-docs#2338]
#1 SearchboxVisbility isn't properly nor fully described.
#2 With the latest public version of Xamarin Forms it doesn't actually work. The search never shows even if you force it to always be expanded.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ea22bfa0-1713-6aff-9c8c-dedf47bb3381
* Version Independent ID: f9b7e5be-4b5a-c292-c425-89125369b97b
* Content: [Xamarin.Forms Shell Search - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/shell/search)
* Content Source: [docs/xamarin-forms/app-fundamentals/shell/search.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/app-fundamentals/shell/search.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @JohnGalt1717 

You're going to have to expand on #1. The docs discuss the purpose of each item in the `SearchBoxVisibility` enumeration (https://docs.microsoft.com/xamarin/xamarin-forms/app-fundamentals/shell/search#search-box-visibility). What do you think is missing?

Re: #2 - that's an issue for the [engineering repo](https://github.com/xamarin/Xamarin.Forms).

**Comment by JohnGalt1717** [comment]
None of #1 actually works and it's not clear how it's supposed to actually work at all in the documentation. There should be examples of each in practice.

#2: Engineering repo has countless cases reports of it not working and they're doing nothing, but your documentation claims it works and explains it working (partially).  The documentation should be updated to state that it doesn't work right now.

**Comment by davidbritch** [comment]
I've just tried the `SearchBoxVisibility` enumeration members on iOS and Android, with Xamarin.Forms 4.4, and they all worked as expected.

However, the docs did require some clarifications adding, which I've done. They are in a PR which will go live later in the week.
