### ISSUE TITLE
Thanks so much

### ISSUE THREAD

**Issue by cillroy** [MicrosoftDocs/xamarin-docs#2339]
I really appreciate you keeping these pages up to date

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9a9a5ad3-9618-8b83-2357-22c2ae0432fe
* Version Independent ID: 7fa1c6a0-3968-b662-2f7f-748cb4c1bacf
* Content: [Xamarin Docs What's New (March 2019) - Xamarin](https://docs.microsoft.com/en-us/xamarin/whats-new/2019-03)
* Content Source: [docs/whats-new/2019-03.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/whats-new/2019-03.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @cillroy 

Thanks for your feedback. We aim to publish a what's new page to coincide with each new release of Xamarin.Forms, so you can expect another one in December.
