### ISSUE TITLE
Update to reflect fact that Essentials is now included by default in our Templates

### ISSUE THREAD

**Issue by BretJohnson** [MicrosoftDocs/xamarin-docs#2342]
I did a call with a customer using Xamarin for the first time, going through his pain points.
And he pointed out that our Essentials getting started instructions point out code changes that are already there, in apps created with the latest templates, which include Essentials.

Also, the code in the templates for OnRequestPermissionsResult is slightly different than what's in the docs here - it's a benign difference, but made the experience more confusing.

Anyway, we should update the doc to make clear that normally these steps aren't needed in most cases, for new projects created with the most recent Forms templates.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 78e6dee8-1182-bf1e-fd3a-e8d1aecc094a
* Version Independent ID: 81202c69-317a-f0fa-7324-5316f7c1ceb7
* Content: [Get Started with Xamarin.Essentials - Xamarin](https://docs.microsoft.com/en-us/xamarin/essentials/get-started?tabs=macos%2Candroid)
* Content Source: [docs/essentials/get-started.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/essentials/get-started.md)
* Product: **xamarin**
* Technology: **xamarin-essentials**
* GitHub Login: @jamesmontemagno
* Microsoft Alias: **jamont**

**Comment by conceptdev** [comment]
Looks like this has been updated in the docs.
