### ISSUE TITLE
My App don´t start

### ISSUE THREAD

**Issue by GaldamezEdgar** [MicrosoftDocs/xamarin-docs#2343]
I did all the thing listed in is page, but now my app doesn´t start

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5823a3fa-87be-0b27-155b-b44130c67e84
* Version Independent ID: c90633f5-22b9-f7dd-fd08-c9affc251dd4
* Content: [Splash Screen - Xamarin](https://docs.microsoft.com/en-us/xamarin/android/user-interface/splash-screen?source=docs#feedback)
* Content Source: [docs/android/user-interface/splash-screen.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/android/user-interface/splash-screen.md)
* Product: **xamarin**
* Technology: **xamarin-android**
* GitHub Login: @davidortinau
* Microsoft Alias: **daortin**

**Comment by conceptdev** [comment]
Please provide additional information about the error you are experiencing, and confirm that you were able to run the [linked sample](https://docs.microsoft.com/en-us/samples/xamarin/monodroid-samples/splashscreen/) successfully.
