### ISSUE TITLE
Related Links are broken

### ISSUE THREAD

**Issue by tripleacoder** [MicrosoftDocs/xamarin-docs#2344]
Activities and Intents  etc. are broken.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e994a1e6-78e2-1bed-f815-e4136b9b4206
* Version Independent ID: ee8093c5-80f1-63bb-cfbf-0cc70c27e49c
* Content: [App-Linking in Android - Xamarin](https://docs.microsoft.com/en-us/xamarin/android/platform/app-linking#testing-app-links)
* Content Source: [docs/android/platform/app-linking.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/android/platform/app-linking.md)
* Product: **xamarin**
* Technology: **xamarin-android**
* GitHub Login: @davidortinau
* Microsoft Alias: **daortin**

**Comment by conceptdev** [comment]
Thanks for letting us know - unfortunately Xamarin University is no longer available, so the link . has been removed.
