### ISSUE TITLE
Delegate invocation thread

### ISSUE THREAD

**Issue by breyed** [MicrosoftDocs/xamarin-docs#2346]
What thread is the delegate passed to Subscribe called on, the thread of the caller to Subscribe or the thread of the caller to Send?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4d80a771-2198-328b-b9fa-fe25f16261cd
* Version Independent ID: be0408fe-d00b-baf6-8a9c-e24659029c4b
* Content: [Xamarin.Forms MessagingCenter - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/messaging-center)
* Content Source: [docs/xamarin-forms/app-fundamentals/messaging-center.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/app-fundamentals/messaging-center.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @breyed 

It should be the thread of the caller to Send.

**Comment by breyed** [comment]
Do you think that this behavior should be documented on the general [MessagingCenter](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/app-fundamentals/messaging-center.md) page and on the MessagingCenter.Subscribe page?

**Comment by davidbritch** [comment]
I've done so, in a PR that will go live later this week.
