### ISSUE TITLE
Would be great to see example for UWP

### ISSUE THREAD

**Issue by solomonfried** [MicrosoftDocs/xamarin-docs#2348]
For those of us including UWP Apps in our Xamarin projects, authentication examples for other environemtns would be extremely helpful. (also  WPF, Mac, Tizen?)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aa8bb9e0-5898-0d11-0213-fd4d8c8d0297
* Version Independent ID: 2f46e1f7-164f-2f32-70c0-f28919d16c5c
* Content: [AuthenticateUsers with an Identity Provider - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/data-cloud/authentication/oauth)
* Content Source: [docs/xamarin-forms/data-cloud/authentication/oauth.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/data-cloud/authentication/oauth.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @solomonfried 

While not an official sample/doc, I wrote a blog post on doing OAuth for iOS/Android/UWP. Hopefully it'll help: https://www.davidbritch.com/2019/07/oauth-20-for-native-apps-using.html

**Comment by solomonfried** [comment]
Thanks for the info.

Trying to build NativeBrowsersWithOIDCClient and am getting this error (1 for Android and 1 for UWP)
Tried updating all NuGet packages, but to no avail.

Severity
Code
Description
Project
File
Line
Suppression State
Error

Failed to create JavaTypeInfo for class: Android.Support.V4.View.Accessibility.AccessibilityManagerCompat/IAccessibilityStateChangeListenerImplementor due to System.IO.DirectoryNotFoundException: Could not find a part of the path 'D:\projects.vs\TestProjects\DavidBritch\xamarin-forms-master\NativeBrowsersWithOIDCClient\NativeBrowsersWithOIDCClient.Android\obj\Debug\81\android\src\mono\android\support\v4\view\accessibility\AccessibilityManagerCompat_AccessibilityStateChangeListenerImplementor.java'.   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)   at System.IO.File.InternalDelete(String path, Boolean checkHost)   at System.IO.File.Delete(String path)   at Xamarin.Android.Tools.Files.CopyIfStreamChanged(Stream stream, String destination)   at Xamarin.Android.Tasks.Generator.CreateJavaSources(TaskLoggingHelper log, IEnumerable`1 javaTypes, String outputPath, String applicationJavaClass, String androidSdkPlatform, Boolean useSharedRuntime, Boolean generateOnCreateOverrides, Boolean hasExportReference)
NativeBrowsersWithOIDCClient.Android



Error

Framework resource extraction failed. Could not find a part of the path 'D:\projects.vs\TestProjects\DavidBritch\xamarin-forms-master\NativeBrowsersWithOIDCClient\NativeBrowsersWithOIDCClient.UWP\obj\x86\Debug\Microsoft.Extensions.DependencyInjection.Abstractions\en-US\Microsoft.Extensions.DependencyInjection.Abstractions.Resources.resw'.
NativeBrowsersWithOIDCClient.UWP





When using the NativeBrowsers example, I am getting a bit further but would you have a mapping for Google and Facebook to the fields in the Constants.cs file?

For Facebook using Xamarin OAuth I have the following…

ClientID => "4XXXXXXXXXXXX";
Scope => "email";
AuthorizeUrl => "https://www.facebook.com/dialog/oauth/";
ClientSecret => null;
RedirectUrl => "https://www.facebook.com/connect/login_success.html";

When I map these to the constants I and try to Login (I have tried several permutations), I do get a Login screen but there is an error message.
Can't Load URL
The domain of this URL isn't included in the app's domains. To be able to load this URL, add all domains and subdomains of your app to the App Domains field in your app settings.

For Google I have

Scope => "https://www.googleapis.com/auth/userinfo.email";
AuthorizeUrl => "https://accounts.google.com/o/oauth2/auth";
AccessTokenUrl => "https://www.googleapis.com/oauth2/v4/token";
UserInfoUrl => "https://www.googleapis.com/oauth2/v2/userinfo";
ClientSecret => null;
RedirectUrl => "com.pnqsys.classtars:/oauth2redirect";
ClientID => "9999999999-askdjalkdjopeijdqwdjakjdaskdjlaskdjasd.apps.googleusercontent.com";



But again, everything I have tried results in the popup with an error
“We can’t Connect to the service you need right now. Check your Network connections or try this again later”

Any suggestions would be appreciated.

**Comment by davidbritch** [comment]
Hi @solomonfried 

For your problems building NativeBrowsersWithOIDCClient it looks like your paths on Android and UWP are breaching the Windows 260 char limit.

Afraid I don't have any Constants to hand for Google and Facebook.

**Comment by solomonfried** [comment]
Thank you for looking into this. 
I will see if I have any options for shortening the URL.
I appreciate the work you have put into this. 
IMHO, I can't figure out why a function so common in apps these days is such a headache to implement cleanly on each platform. So on behalf of myself and the rest of us looking for a solution, we thank you.
