### ISSUE TITLE
How to do these all Triggers in Code Behind ?

### ISSUE THREAD

**Issue by nmano2188** [MicrosoftDocs/xamarin-docs#2349]

**Comment by davidbritch** [comment]
Hi @nmano2188 

The reason for why there's no C# Trigger examples is that Triggers are specifically designed for XAML usage. While you could use the Trigger class from C# there's no advantage to doing so. In fact, it would over complicate what can already be achieved in C# using conventional techniques. For example, there's no need to use an event trigger in C# as you can just create event handlers and register them against an event. Similarly, there's no need to use a property trigger in C# as you can just listen for a property changed event and handle that.

**Comment by nmano2188** [comment]
I got it
