### ISSUE TITLE
Landscape Android Examples

### ISSUE THREAD

**Issue by sivaramganesan** [MicrosoftDocs/xamarin-docs#235]
Any examples for Splashscreen in landscape mode for both Android and iOS platform.? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5823a3fa-87be-0b27-155b-b44130c67e84
* Version Independent ID: c90633f5-22b9-f7dd-fd08-c9affc251dd4
* Content: [Splash Screen - Xamarin](https://docs.microsoft.com/en-us/xamarin/android/user-interface/splash-screen)
* Content Source: [docs/android/user-interface/splash-screen.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/android/user-interface/splash-screen.md)
* Service: **xamarin**
* GitHub Login: @mgmclemore
* Microsoft Alias: **mamcle**

**Comment by mgmclemore** [comment]
Hi @sivaramganesan, thanks for your feedback!  Currently this topic does not show how to implement Splashscreen in landscape mode -- I've added a task to our backlog to update it accordingly.

Meanwhile, the following Xamarin forums discussions may be of some help:
https://forums.xamarin.com/discussion/74517/landscape-splash-screen-in-android
https://forums.xamarin.com/discussion/55849/launch-screen

**Comment by bradumbaugh** [comment]
Hi @sivaramganesan, for iOS launch screens, check out [this document](https://docs.microsoft.com/xamarin/ios/app-fundamentals/images-icons/launch-screens?tabs=vsmac), which describes how to use storyboards to create launch screens that work for different devices / orientations.

**Comment by sivaramganesan** [comment]
HI @bradumbaugh, 

Already i have implemented in iOS using dynamic launch screen storyboard. AW Thank you for the link. 

@mgmclemore, Hope it will be added soon. As i can see a lot of discussion on the forum regarding this landscape splash screen most are not reliable or failing in some cases.
