### ISSUE TITLE
Mac Bindings Library project now available

### ISSUE THREAD

**Issue by alataffective** [MicrosoftDocs/xamarin-docs#2354]
Looking at Visual Studio for Mac 8.3.10 (build 2) I see there is now support for creating a Binding Library project.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 380503db-d607-d0a8-345c-6f7b5ea3d67a
* Version Independent ID: 88ef63f1-6c00-2703-a670-bf11f7a4e06d
* Content: [Binding Objective-C - Xamarin](https://docs.microsoft.com/en-us/xamarin/cross-platform/macios/binding/?context=xamarin/ios)
* Content Source: [docs/cross-platform/macios/binding/index.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/cross-platform/macios/binding/index.md)
* Product: **xamarin**
* Technology: **xamarin-crossplatform**
* GitHub Login: @davidortinau
* Microsoft Alias: **daortin**

**Comment by conceptdev** [comment]
Thanks for pointing this out - updating the page now.
