### ISSUE TITLE
"This API has been deprecated and is no longer available. [410]"

### ISSUE THREAD

**Issue by boskobezik** [MicrosoftDocs/xamarin-docs#2356]
I can't deploy my app to Google Play Store anymore using this approach. I keep getting the message you see in the title.
Screenshot: "https://prnt.sc/q5k9ax"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a56847d5-1bac-1ad0-e7b8-112ba38f7848
* Version Independent ID: 830bff27-5dfb-92ac-9402-62992122100b
* Content: [Publishing to Google Play - Xamarin](https://docs.microsoft.com/en-us/xamarin/android/deploy-test/publishing/publishing-to-google-play/?tabs=windows#feedback)
* Content Source: [docs/android/deploy-test/publishing/publishing-to-google-play/index.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/android/deploy-test/publishing/publishing-to-google-play/index.md)
* Product: **xamarin**
* Technology: **xamarin-android**
* GitHub Login: @davidortinau
* Microsoft Alias: **daortin**

**Comment by ImGonaRot** [comment]
I am also getting the same "410" error.
I have tried the following but none of it worked.

1. UNLINK / RE-LINK the account
2. Deleted the local OAuth credentials inside Visual Studio 2019
3. Created a new OAuth credential on the Google Play console API Access page

**Comment by ricardocosta21** [comment]
Same here. Just can't publish the app and the error message isn't that helpful.

**Comment by federosa77** [comment]
i got the same issue, any solution?

**Comment by ricardocosta21** [comment]
On VS, when pressing 'Distribute', choose 'Ad Hoc' and then just grab the local apk signed file and drag it to the Google Console 'Drag and Drop' area.

**Comment by ImGonaRot** [comment]
Looks like Google removed support for version 2 of the Google Play Developer API on December 1, 2019 and that Microsoft has not updated Visual Studio deployment to use version 3 of the API.
https://android-developers.googleblog.com/2019/03/changes-to-google-play-developer-api.html

**Comment by federosa77** [comment]
Update Visual Studio to V 16.4.2 Works for me.

**Comment by davidortinau** [comment]
@boskobezik looks like this was a product issue that has since been resolved. Closing this report.
