### ISSUE TITLE
404 link

### ISSUE THREAD

**Issue by dani924** [MicrosoftDocs/xamarin-docs#2357]
Link to Layouts on this page https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/ leads to https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/layouts/index.md which returns 404. I suppose correct link would be this one https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/layouts/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f5bd8beb-52ef-9e33-4453-4fea779b6342
* Version Independent ID: d4a85f7a-fe87-1850-854d-db2114a01555
* Content: [Choose a Xamarin.Forms Layout - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/layouts/choose-layout#feedback)
* Content Source: [docs/xamarin-forms/user-interface/layouts/choose-layout.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/layouts/choose-layout.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @dani924 

Thanks for reporting this. I've fixed it in a PR that will go live later this week.
