### ISSUE TITLE
Live stream

### ISSUE THREAD

**Issue by ahmad913** [MicrosoftDocs/xamarin-docs#2358]
Hi
may i ask when you say 
"No stream option is available for the VideoPlayer however, because iOS and Android do not support playing a video from a stream."
do you mean we cannot implement a live stream from youtube ?
or basically any other viable url..

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 08231611-5a52-267d-cfc6-0042e5d5c2a3
* Version Independent ID: 6c39962d-a013-a391-9f1f-4a69f3a99de0
* Content: [Playing a Web video - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/custom-renderer/video-player/web-videos#feedback)
* Content Source: [docs/xamarin-forms/app-fundamentals/custom-renderer/video-player/web-videos.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/app-fundamentals/custom-renderer/video-player/web-videos.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @ahmad913 

Looks like you've already figured the answer out - https://stackoverflow.com/questions/55907284/how-to-live-stream-a-m3u8-video-file-in-xamarin-forms

**Comment by ahmad913** [comment]
thanks a lot for the reply although its a bit disappointing 😅
