### ISSUE TITLE
Doesn't define the stack layout inside of the scroll view

### ISSUE THREAD

**Issue by Escapehub** [MicrosoftDocs/xamarin-docs#2359]
var stack = new StackLayout();
var scroll = new ScrollView { Content = stack };
Content = scroll;
stack.Children.Add(new BoxView { BackgroundColor = Color.Red,    HeightRequest = 600, WidthRequest = 600 });
stack.Children.Add(new Entry());

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6f75ab81-45e6-51c3-3591-79b2e3f8e4ba
* Version Independent ID: 74048293-a950-c375-aac9-7f0f1cb9b49d
* Content: [Xamarin.Forms ScrollView - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/layouts/scroll-view#feedback)
* Content Source: [docs/xamarin-forms/user-interface/layouts/scroll-view.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/layouts/scroll-view.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by eshoo** [comment]
Just a guess but maybe try creating new ScrollView { Content = stack } after you have added its children.
So something along these lines instead:
var stack = new StackLayout();

stack.Children.Add(new BoxView { BackgroundColor = Color.Red, HeightRequest = 600, WidthRequest = 600 });
stack.Children.Add(new Entry());
/*THE CHANGE */
var scroll = new ScrollView { Content = stack };
Content = scroll;

**Comment by davidbritch** [comment]
Hi @Escapehub 

I've just fixed the code in the doc, in a PR that will go live later this week.

In the meantime, the code you want is:

```
        StackLayout stackLayout = new StackLayout();
        stackLayout.Children.Add(new BoxView { BackgroundColor = Color.Red, HeightRequest = 600, WidthRequest = 150 });
        stackLayout.Children.Add(new Entry());
        ScrollView scrollView = new ScrollView();
        scrollView.Content = stackLayout;
        Content = scrollView;
```
