### ISSUE TITLE
Multiple setters for individual trigger

### ISSUE THREAD

**Issue by pmahend1** [MicrosoftDocs/xamarin-docs#2360]
`MultipleTrigger` says `<!-- multiple Setter elements are allowed -->`  does that mean `PropertyTrigger` `DataTrigger` only support one setter for each event defined?
Please clarify in the documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a3ff3ffd-9177-76ff-ac6e-7cb439750203
* Version Independent ID: 8e881672-c9ff-354c-fb22-97a8d1af2d72
* Content: [Xamarin.Forms Triggers - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/triggers)
* Content Source: [docs/xamarin-forms/app-fundamentals/triggers.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/app-fundamentals/triggers.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @pmahend1 

Multiple setters are allowed in both property and data triggers. I've updated the doc to say so, in a PR that will go live later this week.
