### ISSUE TITLE
Stuck at the referencing part

### ISSUE THREAD

**Issue by emanuel1996** [MicrosoftDocs/xamarin-docs#2361]
"Get a reference to the controls that were created in the layout file via the Android Designer. Add the following code inside the OnCreate method, after the call to SetContentView" 
I'm stuck at this part of the guide as i keep getting this error :

string translatedNumber = Core.PhonewordTranslator.ToNumber(phoneNumberText.Text);

The name "Core" does not exist in the current context.

I've seen people mention that the guide is not exactly up to date. In any case, i'd really appreciate some help. I've google for a decent 3 hours for solutions yet i am more confused. Please be kind with me as i'm a total begginer in this. I apologize if my problem has a easy fix that i didn't see or think of.

Thank you!
![e1](https://user-images.githubusercontent.com/26093362/70155503-0bbf4000-16bb-11ea-86b6-053b14344365.png)

**Comment by conceptdev** [comment]
In the [**Write some code** step](https://docs.microsoft.com/xamarin/android/get-started/hello-android/hello-android-quickstart#write-some-code-1) you need to add a new C# file to your solution, and paste in the `Core. PhonewordTranslator` class as shown in the docs. 

Can you share a screenshot that includes your solution explorer? This might help to identify the issue. Thanks.
