### ISSUE TITLE
"Enable Proguard" option no longer available in VS 2019.

### ISSUE THREAD

**Issue by toluasalu** [MicrosoftDocs/xamarin-docs#2363]
I'm trying to sign my application in release mode so i can send it to my client for testing on his device. I've gotten to the part where i'm supposed to use proguard to link and obfuscate java bytecode. But the "enable Proguard" Option is not available in Visual Studio 2019.

**Comment by conceptdev** [comment]
This might be related to the redesign of the Android Options window (see this [other issue](https://github.com/MicrosoftDocs/xamarin-docs/issues/2350#issuecomment-565108082)). 

The [Proguard page](https://docs.microsoft.com/xamarin/android/deploy-test/release-prep/proguard?tabs=windows&source=docs#enabling-proguard) has been updated to reflect the Proguard setting is now in the **Code shrinker** drop-down list.
