### ISSUE TITLE
Launcher.OpenAsync vs Share.RequestAsync

### ISSUE THREAD

**Issue by sehuff** [MicrosoftDocs/xamarin-docs#2364]
Based on the documentation for Launcher.OpenAsync which says:

"This features enables an app to request other apps to open and view a file."

I would expect that when providing a word document with a docx file extension it see I have the Word app installed and launch word and open the document.  However, this seems to be no different then Share.RequestAsync which just prompts the user for what app they want to use (neither put Word front and center forcing the user to click ... to find Open Word.

**Comment by jamesmontemagno** [comment]
Each app can handle it different. Some use it as an attachment and some just open it directly without saving it. 

Usually a "Share" is a copy/attachment and "Launcher" is just open this file to display. It is all up to the apps installed though.
