### ISSUE TITLE
How to change hamburger image in master page xamarin forms

### ISSUE THREAD

**Issue by PRAVEENPOTLA** [MicrosoftDocs/xamarin-docs#2365]

**Comment by profexorgeek** [comment]
Hi @PRAVEENPOTLA,
Xamarin.Forms translates Forms elements into native platform elements on Android and iOS. Components are sometimes limited by what the underlying platform allows.

In the case of Master Detail pages, this menu is provided by the underlying platform. This means that the icon is controlled by the underlying platform and cannot be changed within the context of Xamarin.Forms. You would likely have to create a custom navigation component to accomplish this.

However, if you want more control over the navigation experience you could explore using Xamarin.Forms Shell:
https://docs.microsoft.com/xamarin/xamarin-forms/app-fundamentals/shell/

CC: @PureWeen
