### ISSUE TITLE
versions

### ISSUE THREAD

**Issue by russellg59** [MicrosoftDocs/xamarin-docs#2369]
When I check with visual studio the versions shown have absolutely no resemblance to the version numbers you give here. It would be really helpful if VS reported the same numbering scheme as you use in the docs.

Here's what vs says...

Xamarin Designer   16.4.0.464 (remotes/origin/d16-4@4abf337c3)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   16.4.25 (579ee62)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   10.1.0.30 (d16-4/5e2fd06)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: e1ef774
    Java.Interop: xamarin/java.interop/d16-4@c4e569f
    ProGuard: xamarin/proguard/master@905836d
    SQLite: xamarin/sqlite/3.28.0@46204c4
    Xamarin.Android Tools: xamarin/xamarin-android-tools/master@9f4ed4b
Xamarin.iOS and Xamarin.Mac SDK   13.8.2.2 (44c08f2)

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ee866334-76c9-4814-5a0e-026e7f7510f5
* Version Independent ID: 2bafddb4-ce0b-33d1-154f-41cba85ca4bf
* Content: [Xamarin Docs What's New (October 2019) - Xamarin](https://docs.microsoft.com/en-gb/xamarin/whats-new/2019-10?source=docs#feedback)
* Content Source: [docs/whats-new/2019-10.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/whats-new/2019-10.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @russellg59 

The version numbers in the What's new page refer to Xamarin.Forms, which is a [NuGet package](https://www.nuget.org/packages/Xamarin.Forms/).

**Comment by russellg59** [comment]
Hi David,

Thanks for the reply.

It fees like it would be helpful, not to say less confusing,  if these package numbers were shown in the help/about page.

Kind Regards

Russell


Russell Gilbert
russell@sandyatom.uk<mailto:russell@sandyatom.uk>
Sandy Atom Technology

Tel: +44 118 328 2445
Mob +44 7960 674911

Web: http://www.sandyatom.co.uk<http://www.sandyatom.co.uk/>
Blog: http://blog.russellgilbert.co.uk<http://blog.russellgilbert.co.uk/>
LinkedIn: http://uk.linkedin.com/in/csharprussellgilbert
