### ISSUE TITLE
Why not just  apply the new style to MainActivity?

### ISSUE THREAD

**Issue by jokogarcia** [MicrosoftDocs/xamarin-docs#2370]
That's what I did, anyways. Seems to work well and there is no need to "simulate" loading work with a timer.
Note: my project is a Xamarin.Forms Crossplatform solution.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5823a3fa-87be-0b27-155b-b44130c67e84
* Version Independent ID: c90633f5-22b9-f7dd-fd08-c9affc251dd4
* Content: [Splash Screen - Xamarin](https://docs.microsoft.com/en-us/xamarin/android/user-interface/splash-screen#feedback)
* Content Source: [docs/android/user-interface/splash-screen.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/android/user-interface/splash-screen.md)
* Product: **xamarin**
* Technology: **xamarin-android**
* GitHub Login: @davidortinau
* Microsoft Alias: **daortin**

**Comment by profexorgeek** [comment]
It's possible to combine these roles but some apps may want to keep these activities separate so the doc shows this use case. Here are a couple reasons:

- You may want to separate the logic to load and cache content (splash) from the logic to bind data to the UI (main activity)
- You may want a different theme for your splash. For instance it might have a dark background or hide the title bar.
