### ISSUE TITLE
TextType HTML for IOS App font issue

### ISSUE THREAD

**Issue by proinfocus** [MicrosoftDocs/xamarin-docs#2372]
When the TextType is set to Html for Xamarin.Forms Label control, it renders correctly in Android for custom fonts, but in IOS the font reverts back to Times New Roman even if the FontFamily is set to a custom font.  I have set the default font for Label to **Montserrat** which works fine in Android, but in IOS it displays in Times New Roman font. If we remove the TextType property is shows correctly.

```
<Label Text="{Binding Address}" TextType="Html" />
```

**Comment by profexorgeek** [comment]
This appears to affect Xamarin.Forms itself, not a specific doc or sample. Opening an issue in the Xamarin.Forms repository will help our team properly track and address your problem:
https://github.com/xamarin/Xamarin.Forms/issues

**Comment by rosalesruben** [comment]
I have a new issue related to this with iOS devices. When I set at least one font attributes (for example TextColor, FontSize) and textType="html" is present then the tag attribute is lost.
For example:
At the modelView a property myHtmlText with value  "My text with<b>BOLD</b>"

And at the Xaml page
<Label  FontSize="12" TextType="Html" Text="{Binding myHtmlText}"/>

In iOS devices the "bold" is not seen when FontSize is set. When remove FontSize, the bold is seen correctly.

I update today Xamarin Forms to lattest version (4.8.0.1534+384-sha.712849b9d-azdo.4114742)

**Comment by MoleDJ** [comment]
Same issue for me, using Xamarin Forms 5.0.0.1874, when any property related to font is set (fontsize, font-family), <b> bold tags not seen.
