### ISSUE TITLE
Behavior OnPropertyChanged

### ISSUE THREAD

**Issue by BrayanKhosravian** [MicrosoftDocs/xamarin-docs#2373]
Hi, are all the methods which are responsible for measuring, layouting and invalidation being invoked when a OnPropertyChanged gets triggered?

Lets think of mvvm. When a user clicks on an image and loads a new one from the galery, then the image changes at runtime. Would this be remeasured when changing an image at runtime? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3ae9b20a-a4bc-23bc-e2ec-c70660cc53cf
* Version Independent ID: 17f6b082-d994-531e-1e89-3ffaed871273
* Content: [Create a Custom Layout in Xamarin.Forms - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/layouts/custom)
* Content Source: [docs/xamarin-forms/user-interface/layouts/custom.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/layouts/custom.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by profexorgeek** [comment]
Hi @BrayanKhosravian,
Yes, changing properties that affect layout should result in the layout being recalculated and redrawn. For example, clicking a button that sets the source of an image moves the purple box layout down when the image is loaded:

![imageSourceDemo](https://user-images.githubusercontent.com/711100/70638534-4e6ea400-1bf6-11ea-9ad9-fd604910a79d.gif)
