### ISSUE TITLE
Thanks!

### ISSUE THREAD

**Issue by mc738** [MicrosoftDocs/xamarin-docs#2375]
Thank you for a great example, it saved a lot of time. Two little things I had to do to get it to work:

In the xaml I had to use:
xmlns:tt="clr-namespace:TouchTracking.Forms;assembly=TouchTracking.Forms"
instead of
xmlns:tt="clr-namespace:TouchTracking"

Both times ConvertToPixels is called I had to call ConvertToPixel(new Point(args.Location.X, args.Location.Y)) (however changing the signature ConvertToPixel to accept a TouchTrackingPoint will also work).

Thanks again, very useful!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3dd86692-80ad-ec6a-fd7e-645331262b30
* Version Independent ID: 1070b49c-c04c-c475-f9eb-78ee5bb61986
* Content: [Finger Painting in SkiaSharp - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/graphics/skiasharp/paths/finger-paint#feedback)
* Content Source: [docs/xamarin-forms/user-interface/graphics/skiasharp/paths/finger-paint.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/graphics/skiasharp/paths/finger-paint.md)
* Product: **xamarin**
* Technology: **xamarin-skiasharp**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by conceptdev** [comment]
Hey @mc738, thanks for the kind words.

I've just run the sample up here without problems, could you share which version of Xamarin.Forms you're using and perhaps which platform/IDE? `ConvertToPixel(args.Location)` seems like it should work, as the `args` object is of type `TouchActionEventArgs` but the `Location` property is a `Point` (I'm using Xamarin.Forms 4.3, and tested SkiaSharp 1.60 and 1.68). 

Interested in your experience, thanks.
