### ISSUE TITLE
VS2017 Error A server with the specified hostname could not be found while adding an Apple Account

### ISSUE THREAD

**Issue by fperez2511** [MicrosoftDocs/xamarin-docs#2377]
Trying to add an Apple Developer account [Tools &gt; Options &gt; Xamarin &gt; Apple Accounts] to Visual Studio Professional 2017 Version 15.9.16
will result in a dialog saying:

Error adding account
There was an error while trying to log in: A server with the specified hostname could not be found.

At the paired mac's Keychain Access app, we can see in the Passwords section every attempt to try to add the account with a corresponding entry like:
`deliver.MYAPPLEID@MYHOST.COM`

Please advise

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6d17e2db-437f-d45f-f78f-f4b32a40c3f3
* Version Independent ID: 44ff0294-e19c-a926-1aa2-338c3b61371a
* Content: [Apple Account Management - Xamarin](https://docs.microsoft.com/en-us/xamarin/cross-platform/macios/apple-account-management?tabs=windows#adding-an-apple-developer-account)
* Content Source: [docs/cross-platform/macios/apple-account-management.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/cross-platform/macios/apple-account-management.md)
* Product: **xamarin**
* Technology: **xamarin-crossplatform**
* GitHub Login: @davidortinau
* Microsoft Alias: **daortin**

**Comment by conceptdev** [comment]
Hi @fperez2511 this sounds like something where more system information and logs would be helpful in diagnosing.

Please use the [Report a problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2019) feature in Visual Studio, to include the additional information that might help us identify the problem. Thanks!

**Comment by jolugbo** [comment]
Also experiencing this issue

**Comment by startwoinformatica** [comment]
Also experiencing this issue.

**Comment by Bobisback** [comment]
I also have this same issue, anyone have any solutions?

**Comment by jolugbo** [comment]
upgrading to vs 2019 worked for me.

**Comment by pointh** [comment]
The same problem. No option to upgrade to VS2019.

**Comment by obartelt** [comment]
Same problem. And no intention to upgrade to VS2019.
