### ISSUE TITLE
.Net Core 3.1 on Windows throws NotImplementedInReferenceAssemblyException

### ISSUE THREAD

**Issue by jmosbech** [MicrosoftDocs/xamarin-docs#2378]
We're getting a `Xamarin.Essentials.NotImplementedInReferenceAssemblyException` when trying to use the `Xamarin.Essentials.FileSystem.CacheDirectory` from a .Net Core 3.1 console app on Windows:

    Xamarin.Essentials.NotImplementedInReferenceAssemblyException : This functionality is not implemented in the portable version of this assembly. You should reference the NuGet package from your main application project in order to reference the platform-specific implementation.

We are referencing `Xamarin.Essentials` from the project, so we're a bit puzzled on how to move forward. Can you provide some guidance?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 69057ea4-203a-b40b-03d4-4dd7a6df8dc2
* Version Independent ID: 293454ff-7958-ef68-7477-dbfb084d3da0
* Content: [FileSystem Class (Xamarin.Essentials)](https://docs.microsoft.com/en-us/dotnet/api/xamarin.essentials.filesystem?view=xamarin-essentials#feedback)
* Content Source: [docs/en/Xamarin.Essentials/FileSystem.xml](https://github.com/xamarin/Essentials/blob/live/docs/en/Xamarin.Essentials/FileSystem.xml)
* Product: **xamarin**
* Technology: **xamarin-essentials**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by conceptdev** [comment]
Hi @jmosbech, issues with the product should be directed to the team on the [open-source GitHub repo](https://github.com/xamarin/essentials/issues). 

I'm not sure .NET Core 3.1 Console apps are a supported platform, so that would be something to check with the engineering team.
