### ISSUE TITLE
Transparent PNG not visible with hight contrast theme

### ISSUE THREAD

**Issue by HankiDesign** [MicrosoftDocs/xamarin-docs#2379]
I'm using the dark theme when browsing the docs and noticed that the Android 10 logo is barely visible. If I change to the high contrast theme, it's completely invisible because the background is also black.

Perhaps this sort of images should have an opaque background in case of users not using the Light theme? I assume that the docs engine doesn't support per-theme images.

**Dark**

![Screenshot 2019-12-10 at 14 18 36](https://user-images.githubusercontent.com/1816448/70532838-19ac0f80-1b58-11ea-98f8-59f9464a7f6f.png)

**High contrast**

![Screenshot 2019-12-10 at 14 17 27](https://user-images.githubusercontent.com/1816448/70532834-16b11f00-1b58-11ea-896a-6c4d2f952cf1.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e0301dd5-7ff9-6f2b-ab83-271b539d46fd
* Version Independent ID: fee54cf8-4cc4-de5d-b00d-302d307545fa
* Content: [Android 10 features - Xamarin](https://docs.microsoft.com/en-us/xamarin/android/platform/android-10#feedback)
* Content Source: [docs/android/platform/android-10.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/android/platform/android-10.md)
* Product: **xamarin**
* Technology: **xamarin-android**
* GitHub Login: @JonDouglas
* Microsoft Alias: **jodou**

**Comment by conceptdev** [comment]
Thanks for mentioning this. You're right, we can't have per-theme images, so generally a solid white background is our fallback (which fixes readability, but will create a "bright-spot" on the dark theme). Will be updated soon.
