### ISSUE TITLE
Can also return -1

### ISSUE THREAD

**Issue by hmumm** [MicrosoftDocs/xamarin-docs#2380]
There is one edge case where this will not return 0 - 1. If you are using the iOS simulator and you have a desktop (or a VM) it will return -1. This happens because the iOS simulator sets the battery based on the computer but a desktop or VM has no battery. If you could update the documentation to say that, that would be great.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 85864d78-2fe1-c7a6-7588-1b1a67c15612
* Version Independent ID: 1155b7e1-7fbc-791b-16d0-f3e51fd5c0f6
* Content: [Battery.ChargeLevel Property (Xamarin.Essentials)](https://docs.microsoft.com/en-us/dotnet/api/xamarin.essentials.battery.chargelevel?view=xamarin-essentials#feedback)
* Content Source: [docs/en/Xamarin.Essentials/Battery.xml](https://github.com/xamarin/Essentials/blob/live/docs/en/Xamarin.Essentials/Battery.xml)
* Product: **xamarin**
* Technology: **xamarin-essentials**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by jamesmontemagno** [comment]
Fixed via https://github.com/xamarin/Essentials/pull/1049
