### ISSUE TITLE
Example code visual.Animate(""... causes exception.  You must provide an animation name

### ISSUE THREAD

**Issue by ryanlpoconnell** [MicrosoftDocs/xamarin-docs#2381]
Example code in FadeTriggerAction visual.Animate(""... causes exception.  You must provide an animation name

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a3ff3ffd-9177-76ff-ac6e-7cb439750203
* Version Independent ID: 8e881672-c9ff-354c-fb22-97a8d1af2d72
* Content: [Xamarin.Forms Triggers - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/triggers#enterexit)
* Content Source: [docs/xamarin-forms/app-fundamentals/triggers.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/app-fundamentals/triggers.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @ryanlpoconnell 

Thanks for pointing out this problem. I've updated the doc (and the sample) in a PR that will go live later.

The solution is to provide a string as the first parameter to the `Animate` method. It can literally be anything, but it's best to give the animation a unique name that identifies the animation - in this case "FadeTriggerAction".
