### ISSUE TITLE
Incorrect screenshot for Drawable Example

### ISSUE THREAD

**Issue by njsokalski** [MicrosoftDocs/xamarin-docs#2382]
The screenshot for the Drawable Example at:
https://docs.microsoft.com/en-us/xamarin/android/app-fundamentals/graphics-and-animation#drawable-example
Is the incorrect screenshot.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 264c90d2-0c8a-9ad0-05d5-56a7932e1476
* Version Independent ID: 9bcbc45f-12cc-a108-735b-e9691bbbb895
* Content: [Graphics and Animation - Xamarin](https://docs.microsoft.com/en-us/xamarin/android/app-fundamentals/graphics-and-animation#drawable-example)
* Content Source: [docs/android/app-fundamentals/graphics-and-animation.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/android/app-fundamentals/graphics-and-animation.md)
* Product: **xamarin**
* Technology: **xamarin-android**
* GitHub Login: @davidortinau
* Microsoft Alias: **daortin**

**Comment by conceptdev** [comment]
You're right - updated the link now.
