### ISSUE TITLE
Error throw when use [assembly: XamlCompilation(XamlCompilationOptions.Compile)]

### ISSUE THREAD

**Issue by SuperXCode** [MicrosoftDocs/xamarin-docs#2383]
**Error throw when use 

> [assembly: XamlCompilation(XamlCompilationOptions.Compile)]

**

$exception {System.InvalidCastException: Specified cast is not valid.
  
at MyApp.Views.Login.LoginPage.InitializeComponent () [0x00100] 
in D:\App\MyApp-master16\MyApp\obj\Debug\netstandard2.0\Views\Login\LoginPage.xaml.g.cs:78 

  at MyApp.Views.Login.LoginPage..ctor () [0x00022] 
in D:\App\MyApp-master16\MyApp\Views\Login\LoginPage.xaml.cs:55 

  at MyApp.Helpers.Language.LanguageHelper.SetLanguage (System.String language) [0x000c7] 
in D:\App\MyApp-master16\MyApp\Helpers\Language\LanguageHelper.cs:53 

  at MyApp.App.Initialize () [0x00045] 
in D:\App\MyApp-master16\MyApp\App.xaml.cs:109 

  at MyApp.App..ctor () [0x0000f] 
in D:\App\MyApp-master16\MyApp\App.xaml.cs:68 

  at MyApp.Droid.MainActivity.OnCreate (Android.OS.Bundle savedInstanceState) [0x000a9] 
in D:\App\MyApp-master16\MyApp.Android\MainActivity.cs:61 

  at Android.App.Activity.n_OnCreate_Landroid_os_Bundle_ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_savedInstanceState) [0x00011] in <06692e0cad5848598a0f46942a89e99f>:0 
  
at (wrapper dynamic-method) Android.Runtime.DynamicMethodNameCounter.3(intptr,intptr,intptr)
System.InvalidCastException

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 18750a4a-7a18-60c6-206e-b5740a7902e3
* Version Independent ID: a1cd5eac-0f69-4304-88b1-ed17d128ff84
* Content: [XAML Compilation in Xamarin.Forms - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/xaml/xamlc#feedback)
* Content Source: [docs/xamarin-forms/xaml/xamlc.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/xaml/xamlc.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @SuperXCode 

The error suggests that you have some invalid XAML in `LoginPage`.

**Comment by SuperXCode** [comment]
why when remove xamlc it's work fine?
How I know what invalid XAML in my pages?!

what about this?
GdSrchPG.InitializeComponent ()
Khawarizm.Views.GeyodNS.GdSrchPG..ctor () <0x1065df7d0 + 0x00193> in <1ca04ac67cfa4e54bb6f39702d3e64c4#0b94f4fd871a01a3eb09ab40db6ea41a>:0
MasterMainPage.NavigateFromMenu (Khawarizm.Models.Enums.MenuEnum menuEnum, System.Boolean isHistory)
MasterMainPage.GdSrchPG_Clicked (System.Object sender, System.EventArgs e)
AsyncMethodBuilderCore+<>c.<ThrowAsync>b__7_0 (System.Object )
NSAsyncSynchronizationContextDispatcher.Apply ()
(wrapper managed-to-native) UIKit.UIApplication.UIApplicationMain(int,string[],intptr,intptr)
UIApplication.Main (System.String[] , System.IntPtr , System.IntPtr )
UIApplication.Main (System.String[] , System.String , System.String )
Application.Main (System.String[] args)
