### ISSUE TITLE
AccountStore example is deprecated

### ISSUE THREAD

**Issue by UnicornOfMagic** [MicrosoftDocs/xamarin-docs#2385]
The AccountStore example provided for storing account information is deprecated in favor of `Xamarin.Essentials` Secure Storage solution. Perhaps it'd be best to link to the migration docs: https://github.com/xamarin/Xamarin.Auth/wiki/Migrating-from-AccountStore-to-Xamarin.Essentials-SecureStorage

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aa8bb9e0-5898-0d11-0213-fd4d8c8d0297
* Version Independent ID: 2f46e1f7-164f-2f32-70c0-f28919d16c5c
* Content: [AuthenticateUsers with an Identity Provider - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/data-cloud/authentication/oauth#feedback)
* Content Source: [docs/xamarin-forms/data-cloud/authentication/oauth.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/data-cloud/authentication/oauth.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @UnicornOfMagic 

I've added a link to the migration doc in a PR that will go live later this week.
