### ISSUE TITLE
Code Not Render Correctly.

### ISSUE THREAD

**Issue by RonakSankhala4u** [MicrosoftDocs/xamarin-docs#2386]
&lt;?xml version="1.0" encoding="utf-8" ?&gt;
&lt;ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:d="http://xamarin.com/schemas/2014/forms/design"
             xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
             mc:Ignorable="d"
             x:Class="Label01.MainPage"&gt;

    &lt;StackLayout Margin="20,35,20,20"&gt;
        &lt;!-- Place new controls here --&gt;
        
        &lt;Label TextColor="Black" 
               FontSize="Medium"&gt;
            &lt;Label.FormattedText&gt;
            &lt;FormattedString&gt;
                    &lt;Span Text="This Sentence Contains "/&gt;
                    &lt;Span Text="Words that are Emphasized, "
                          FontAttributes="Italic"/&gt;

                &lt;Span Text="and UnderLined."
                      TextDecorations="Underline"/&gt;
            &lt;/FormattedString&gt;

            &lt;/Label.FormattedText&gt;
        &lt;/Label&gt;
    &lt;/StackLayout&gt;

&lt;/ContentPage&gt;

I Write that Code in Output like This
This Sentence
Contains Words that are Emphasized, and UnderLined

My Question :-Why String Goes to the New Line Even I didn't Write Code for that.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b0b433b5-8544-660f-493f-3219c489953e
* Version Independent ID: 6bb8278a-e685-683d-6a35-067eb85b951b
* Content: [Xamarin.Forms Label Tutorial - Xamarin](https://docs.microsoft.com/en-us/xamarin/get-started/tutorials/label/?tutorial-step=4&tabs=vswin#feedback)
* Content Source: [docs/get-started/tutorials/label/index.yml](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/get-started/tutorials/label/index.yml)
* Product: **xamarin**
* Technology: **xamarin-crossplatform**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by RonakSankhala4u** [comment]
![image](https://user-images.githubusercontent.com/24754964/70849142-944e9500-1ea0-11ea-8e6c-427910549a21.png)

![Code Not Render Properly 01](https://user-images.githubusercontent.com/24754964/70849155-b9430800-1ea0-11ea-9e99-e6d9fa444eb5.png)

**Comment by davidbritch** [comment]
Hi @RonakSankhala4u 

I just tried your code in Xamarin.Forms 4.4 and it worked fine (it was rendered as a single sentence).

iOS:

![Simulator Screen Shot - iPhone X - 2019-12-17 at 15 18 24](https://user-images.githubusercontent.com/8092460/71008754-0a413f00-20e1-11ea-8239-7a4cb2777526.png)

Android:

![Screenshot_1576595964](https://user-images.githubusercontent.com/8092460/71008763-0e6d5c80-20e1-11ea-96eb-26030c9e7187.png)

**Comment by RonakSankhala4u** [comment]
Why Sentence Automatically Goes to New Line ?
