### ISSUE TITLE
Button's BorderRadius property doesn't exist. I think it should be CornerRadius

### ISSUE THREAD

**Issue by dj-diaz** [MicrosoftDocs/xamarin-docs#2388]
In step 4 for [this page](https://docs.microsoft.com/en-us/xamarin/get-started/quickstarts/styling?pivots=windows), There's a styling set for Button's `BorderRadius` property which I think doesn't exist anymore. 

```
  <Style TargetType="Button"
               ApplyToDerivedTypes="True"
               CanCascade="True">
            <Setter Property="FontSize" Value="Medium" />
            <Setter Property="BackgroundColor" Value="LightGray" />
            <Setter Property="TextColor" Value="Black" />
            <Setter Property="BorderRadius" Value="5" />
  </Style>
```

Intellisense suggests `CornerRadius` property instead.

```
<Style TargetType="Button"
               ApplyToDerivedTypes="True"
               CanCascade="True">
            <Setter Property="FontSize" Value="Medium"/>
            <Setter Property="BackgroundColor" Value="LightGray"/>
            <Setter Property="TextColor" Value="Black"/>
            <Setter Property="CornerRadius" Value="5"/>
</Style>
```

Edit: Sorry didn't know how the docs linking feature works, ended up creating a new github issue instead.

**Comment by davidbritch** [comment]
@dj-diaz 

You're correct - `CornerRadius` has replaced `BorderRadius`. I'll leave this issue open until I've updated the doc/sample.

**Comment by davidbritch** [comment]
I've fixed this in a PR that will go live later this week.
