### ISSUE TITLE
No Longer supported?

### ISSUE THREAD

**Issue by stephenstarkie** [MicrosoftDocs/xamarin-docs#2390]
Looking at github and the lack of commits for the last 3 years(?), it looks like this isn't support by Microsoft, particularly on UWP.  What should we use instead?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d216f918-e887-0a9a-f5a5-b6dab23a0c5b
* Version Independent ID: c946ef4f-1260-ba20-a1d4-cff12a25b994
* Content: [Using CocosSharp in Xamarin.Forms - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/graphics/cocossharp#feedback)
* Content Source: [docs/xamarin-forms/user-interface/graphics/cocossharp.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/graphics/cocossharp.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by conceptdev** [comment]
Correct - you can find the remainder of our CocosSharp content on our [docs-archive](https://github.com/xamarin/docs-archive/tree/master/Docs/CocosSharp).

You could try [MonoGame](https://docs.microsoft.com/xamarin/graphics-games/monogame/), although to be clear that also isn't supported by Microsoft, but through an [open-source community](http://www.monogame.net).

Alternatively, [Unity](https://unity.com/solutions/game) is a game platform that uses C# and Visual Studio for editing.
