### ISSUE TITLE
Error in the menu in the UWP app

### ISSUE THREAD

**Issue by CeciAc** [MicrosoftDocs/xamarin-docs#2391]
Hi team, 
I moved this from here: https://github.com/MicrosoftDocs/xamarin-docs.es-es/issues/82 

The comment below was machine-translated

@wjvelasquez commented 2 days ago — with docs.microsoft.com
The app works as expected, although it has some errors.
The problem is that in the UWP app, which I do not understand the reason to ignore by you, the menu does not look good. The menu does not display the text unless it is expanded in all 3 points.

In my opinion. I think they should put more effort into UWP and not leave it out in their examples.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 60587f77-05de-89b9-8a08-c7e7221d27af
* Version Independent ID: 4080b687-b353-f833-4bb7-a7a3f9993338
* Content: [Perform navigation in a multi-page Xamarin.Forms application - Xamarin](https://docs.microsoft.com/en-us/xamarin/get-started/quickstarts/multi-page?pivots=windows#feedback)
* Content Source: [docs/get-started/quickstarts/multi-page.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/get-started/quickstarts/multi-page.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by conceptdev** [comment]
Thanks for this feedback.

For product issues like UWP display problems, please raise an issue on the [Xamarin.Forms open-source repo](https://github.com/xamarin/Xamarin.Forms/issues).
