### ISSUE TITLE
"External - iOS Support Matrix" related link broken

### ISSUE THREAD

**Issue by kimbirkelund** [MicrosoftDocs/xamarin-docs#2394]
As title says.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 636ef44f-3375-0f01-0472-53f424d091e1
* Version Independent ID: 7cb8bf83-305c-a2d2-f73d-308814d688d0
* Content: [Compiling for Different Devices in Xamarin.iOS - Xamarin](https://docs.microsoft.com/en-us/xamarin/ios/deploy-test/compiling-for-different-devices?tabs=windows#feedback)
* Content Source: [docs/ios/deploy-test/compiling-for-different-devices.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/ios/deploy-test/compiling-for-different-devices.md)
* Product: **xamarin**
* Technology: **xamarin-ios**
* GitHub Login: @davidortinau
* Microsoft Alias: **daortin**

**Comment by conceptdev** [comment]
Sadly, the link is still down after a few weeks 🙁 which is a shame because it is a great resource for iOS developers. I've removed the http://iossupportmatrix.com links to prevent any confusion (but I hope the site is restored!).
