### ISSUE TITLE
how do i query and add 2 values?

### ISSUE THREAD

**Issue by chemobrain** [MicrosoftDocs/xamarin-docs#2396]
For example in the sample Matt and Ann i want to add their age, how do i do that?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d277d164-ac67-d097-dba9-3be6f3c2534f
* Version Independent ID: 30c44243-738f-b964-81be-deb28928843f
* Content: [Xamarin.Forms Local Database Tutorial - Xamarin](https://docs.microsoft.com/en-us/xamarin/get-started/tutorials/local-database/?tutorial-step=4&tabs=vswin#feedback)
* Content Source: [docs/get-started/tutorials/local-database/index.yml](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/get-started/tutorials/local-database/index.yml)
* Product: **xamarin**
* Technology: **xamarin-crossplatform**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
The tutorial already covers storing name/age into the local db. What am I missing?
