### ISSUE TITLE
Enable/Disable Notification Sound

### ISSUE THREAD

**Issue by Muthutc** [MicrosoftDocs/xamarin-docs#2397]
Hi,
                               How to **Enable/Disable** a Notification Sound and Vibration for **Xamarin forms iOS.** Please Let me know if you Know the Solution.

**Comment by davidbritch** [comment]
Hi @Muthutc 

If it's for a local notification, read this doc - https://docs.microsoft.com/xamarin/ios/platform/user-notifications/deprecated/local-notifications-in-ios

Alternatively, you can use Xamarin.Essentials to cause a vibration - https://docs.microsoft.com/xamarin/essentials/vibrate?context=xamarin%2Fxamarin-forms&tabs=android

**Comment by Muthutc** [comment]
@davidbritch No, I Need for Remote Notification.
