### ISSUE TITLE
Phone dialer code?

### ISSUE THREAD

**Issue by Bosch-Eli-Black** [MicrosoftDocs/xamarin-docs#2399]
The documentation mentions "The common code for the application is now complete. Platform-specific phone dialer code will now be implemented as a DependencyService.", which seems like a non-sequitur. Was this documentation originally part of a chain of tutorials?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe0572c4-91be-fc86-d130-242db2bf470b
* Version Independent ID: 1238fdd7-c378-6d0d-654e-55656a70d386
* Content: [Fonts in Xamarin.Forms - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/text/fonts#use-a-custom-font)
* Content Source: [docs/xamarin-forms/user-interface/text/fonts.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/text/fonts.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @Bosch-Eli-Black 

Thanks for pointing out this issue. I've no idea why it says that there. It shouldn't. So I'll remove it today.

**Comment by davidbritch** [comment]
I've fixed this in a PR that will go live later today.

**Comment by Bosch-Eli-Black** [comment]
Thanks :)
