### ISSUE TITLE
Enable/Disable Notification Sound for Remote Notification

### ISSUE THREAD

**Issue by Muthutc** [MicrosoftDocs/xamarin-docs#2400]
Hi,
How to Enable/Disable a Remote Notification Sound and Vibration for Xamarin forms iOS. Please Let me know if you Know the Solution.

**Comment by davidbritch** [comment]
Hi @Muthutc 

Take a look at https://docs.microsoft.com/xamarin/xamarin-forms/data-cloud/azure-services/azure-notification-hub#configure-ios-for-notifications

It's a case of specifying the values of the `UIUserNotificationType` you require in your iOS platform code.
