### ISSUE TITLE
UWP embedded Forms page won't adjust layout when UWP window is resized.

### ISSUE THREAD

**Issue by jgold6** [MicrosoftDocs/xamarin-docs#2401]
With the code sample as-is for embedding a Xam.Forms page in UWP's MainPage, the Xamarin.Forms page won't get update its layout when the window size is changed. To do that one has to handle the MainPage.SizeChanged event and call the Layout method on the Xam.Forms page with the new width and height, e.g. replace:

```
    this.Content = new Notes.UWP.Views.NotesPage().CreateFrameworkElement();
```

with

```   
     var formsPage = new Notes.UWP.Views.NotesPage();
     this.Content = formsPage.CreateFrameworkElement();
        
     SizeChanged += (sender, args) =&gt;
     {
          formsPage.Layout(new Rectangle(0, 0, args.NewSize.Width, args.NewSize.Height));
      };
```
(internal pull request 1409 created for this doc)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2e9d651b-6624-f671-16e2-61c28415374b
* Version Independent ID: 61600bb9-66b3-904d-6be3-32029e78bc5a
* Content: [Xamarin.Forms in Xamarin Native Projects - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/platform/native-forms#uwp)
* Content Source: [docs/xamarin-forms/platform/native-forms.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/platform/native-forms.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Thanks for the issue/PR @jgold6 

Closing this issue, and transferring my attention to the PR.
