### ISSUE TITLE
Disambiguous terminology

### ISSUE THREAD

**Issue by Nixon-Joseph** [MicrosoftDocs/xamarin-docs#2402]
In Android, Deep Links and App Links, while related, are separate concepts. This document appears to use them interchangeably.
Some major differences that should be noted are:
 - Deep Links are supported since Android 1
 - App Links require Android 6+
 - Deep Links prompt disambiguation dialog
 - App Links always open the app, due to the ability to register the site to the application (see [this section](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/deep-linking#registering-content-for-indexing))

While I get the point of this article is to provide a single point of contact for both iOS and Android and iOS only has one version of this, I believe it's important to distinguish the differences.
For instance, for my implementation, all I care about is Deep Links in Android, I don't need App Links, but this article makes it seem like the whole App Link implementation is required for any of it to work.

Otherwise, it's spot on, and super helpful.

See [Deep Link documentation](https://developer.android.com/training/app-links/deep-linking)
See [App Link documentation](https://developer.android.com/training/app-links)
Also [The difference between App Links and Deep Links](https://developer.android.com/training/app-links/verify-site-associations#the-difference)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 42da09a1-6b69-6787-487e-e7e9915caec5
* Version Independent ID: d335d34e-4e88-a4c7-cd97-0a7cfbd45269
* Content: [Application Indexing and Deep Linking - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/deep-linking#feedback)
* Content Source: [docs/xamarin-forms/app-fundamentals/deep-linking.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/app-fundamentals/deep-linking.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @Nixon-Joseph 

Thanks for the feedback. I've added a clarification to the doc, in a PR that will go live later.
