### ISSUE TITLE
TabbedPage Change FontFamilly

### ISSUE THREAD

**Issue by ahmad913** [MicrosoftDocs/xamarin-docs#2403]
is there no way of changing the tabs font family ?
or is it that we just don't have any choice but to use custom render ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0c81c589-e81e-d98c-9656-695a3520a12d
* Version Independent ID: c235f6f9-47ce-15f3-b4da-cb12e219df92
* Content: [Xamarin.Forms TabbedPage - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/navigation/tabbed-page)
* Content Source: [docs/xamarin-forms/app-fundamentals/navigation/tabbed-page.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/app-fundamentals/navigation/tabbed-page.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @ahmad913 

There's no way of doing this in shared code. You can use custom renderers. Alternatively, on Android only you can modify style.xml and Tabbar.axml to do this.

**Comment by ahmad913** [comment]
can you send me a reference for the android i found some but they does not
seem to be working
