### ISSUE TITLE
How to get Periodically location updates 

### ISSUE THREAD

**Issue by jangra1981** [MicrosoftDocs/xamarin-docs#2405]
Dear Team,

How can we get location updates in regular interval in Xamarin Form.  How can  we achieve this using Xamarin essential Geolocation feaure ?

**Comment by jamesmontemagno** [comment]
This is not a supported feature at this time. Currently you can setup Jobs to query the location when you need it, however the  feature is on our backlog for implementation that you can see https://github.com/xamarin/essentials
