### ISSUE TITLE
Incomplete tutorial

### ISSUE THREAD

**Issue by ekalyvio** [MicrosoftDocs/xamarin-docs#2406]
This tutorial is incomplete.
1) When authenticating via the UWP app the Redirect URL should be something like https://{tenantID}.b2clogin.com/{tenantID}.onmicrosoft.com/oauth2/authresp
This is not mentioned anywhere.
2) If I am not mistaken, the options in the Advanced Settings -&gt; Live SDK support in the app registration should be Yes.
3) Enabling Multifactor authentication on the signup/signin flow & trying to log-in via OpenID Connect provider, after the system sends the verification code & the user enters it to the web page there is no submit button & the mobile device does not automatically proceed to check it like desktop browsers do.
![image](https://user-images.githubusercontent.com/3956939/71365024-7ec72280-25a6-11ea-8d9e-90c1f5955bc1.png)

4) It doesn't seem to work at all on Android devices (even without multi-factor Authentication). After logging in and accepting approval by the MS Authenticator app, the browser redirects at login.microsoftonline.com and stops there without redirecting to any of the predefined callback URLs.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 11f5b457-d99a-06d4-d203-f9eeaa27e0d9
* Version Independent ID: b23b3a5d-b63b-dfe1-bb46-94f57c907be5
* Content: [Authenticate Users with Azure Active Directory B2C - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/data-cloud/authentication/azure-ad-b2c#feedback)
* Content Source: [docs/xamarin-forms/data-cloud/authentication/azure-ad-b2c.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/data-cloud/authentication/azure-ad-b2c.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by profexorgeek** [comment]
Hi @ekalyvio,
I have been researching your issues. I'll answer your questions as a series of comments for readability.

> When authenticating via the UWP app the Redirect URL should be something like https://{tenantID}.b2clogin.com/{tenantID}.onmicrosoft.com/oauth2/authresp
This is not mentioned anywhere.

I am not sure where you got that URL. The sample project includes a **Constants.cs** file with some helper properties that build the Authority URI strings. However, these are different than the URL you mention and are dependent on the policy names created in your ADB2C instance. The redirect URL defined in ADB2C and the client is formatted like this:

`var redirectUrl = $"msal{YourUniqueClientGuid}://auth";`

This value appears in the sample **App.xaml.cs** file and is provided to the `WithRedirectUri` method to notify Azure where to redirect a successful authentication.

**Comment by profexorgeek** [comment]
> If I am not mistaken, the options in the Advanced Settings -> Live SDK support in the app registration should be Yes.

I'm not sure where you are seeing/setting this value. I can't find a reference to "Live SDK support" in my Azure ADB2C settings. I tested the sample with an ADB2C configuration that looks like this:
![image](https://user-images.githubusercontent.com/711100/71920145-60832a00-3143-11ea-8916-389d95f130ef.png)

**Comment by profexorgeek** [comment]
> Enabling Multifactor authentication on the signup/signin flow & trying to log-in via OpenID Connect provider, after the system sends the verification code & the user enters it to the web page there is no submit button & the mobile device does not automatically proceed to check it like desktop browsers do.

This is not within the Xamarin.Forms app ability to change. The browser experience is part of ADB2C itself and not controlled by the Xamarin.Forms application. This is probably the best place to open an issue regarding the missing button:
https://github.com/Azure/azure-sdk-for-net/issues

I'm not sure if this will help but it is possible to customize the page layouts for your individual user flows. If you click on one of your User Flows (policies) you can customize the page layouts.

**Comment by profexorgeek** [comment]
> It doesn't seem to work at all on Android devices (even without multi-factor Authentication). After logging in and accepting approval by the MS Authenticator app, the browser redirects at login.microsoftonline.com and stops there without redirecting to any of the predefined callback URLs.

I have successfully tested our sample on both physical and emulated devices. If it's not working for you, it could be one of these things:

1. You have not correctly set the redirect scheme in your Android manifest. It should look something like this with your unique client ID provided in the `android:scheme`:

```xml
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android" android:versionCode="1" android:versionName="1.0" package="com.xamarin.adb2cauthorization">
  <uses-sdk android:minSdkVersion="19" />
  <application android:label="ADB2CAuthorization">
    <activity android:name="microsoft.identity.client.BrowserTabActivity">
      <intent-filter>
        <action android:name="android.intent.action.VIEW" />
        <category android:name="android.intent.category.DEFAULT" />
        <category android:name="android.intent.category.BROWSABLE" />
        <data android:scheme="msalAAAAAAAA-BBBB-CCCC-DDDD-EEEEEEEEEEEE" android:host="auth" />
      </intent-filter>
    </activity>
  </application>
</manifest>
```

2. You have not provided a redirect URL using the `WithRedirectUri` method when building the configuration client in **App.xaml.cs**:

```csharp
AuthenticationClient = PublicClientApplicationBuilder.Create(Constants.ClientId)
                .WithIosKeychainSecurityGroup(Constants.IosKeychainSecurityGroups)
                .WithB2CAuthority(Constants.AuthoritySignin)
                .WithRedirectUri($"msal{Constants.ClientId}://auth")
                .Build();
```

3. The redirect URI you have defined in your Azure ADB2C configuration doesn't match your client configuration.
