### ISSUE TITLE
Is FontSize specified in pixels, points, or something else?

### ISSUE THREAD

**Issue by Bosch-Eli-Black** [MicrosoftDocs/xamarin-docs#2411]
Hello,

Does the FontSize property correspond to pixels (px) or points (pt)? It would be nice if the documentation noted this.

Thanks :)
-Eli

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe0572c4-91be-fc86-d130-242db2bf470b
* Version Independent ID: 1238fdd7-c378-6d0d-654e-55656a70d386
* Content: [Fonts in Xamarin.Forms - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/text/fonts#named-font-sizes)
* Content Source: [docs/xamarin-forms/user-interface/text/fonts.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/text/fonts.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @Bosch-Eli-Black 

It's device independent units. I've added a clarification to the doc.

**Comment by Bosch-Eli-Black** [comment]
Ah, interesting. That wasn't even on my list of guesses, haha.

Thanks for the fix :)
