### ISSUE TITLE
The terminal commands to run the uninstall script on mac are outdated

### ISSUE THREAD

**Issue by Chewieez** [MicrosoftDocs/xamarin-docs#2412]
The terminal commands shown to make the script to uninstall vs on Mac use an older, out-of-date script file name. The script that is linked at the top of this page has a different file name than the one references in the documentation on how to use the script. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a77068e2-5802-f169-f068-6a2bf41491c2
* Version Independent ID: 073d6c2f-b652-e427-f0e6-fb1ce0012485
* Content: [Uninstalling Xamarin - Xamarin](https://docs.microsoft.com/en-us/xamarin/get-started/installation/uninstalling-xamarin#feedback)
* Content Source: [docs/get-started/installation/uninstalling-xamarin.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/get-started/installation/uninstalling-xamarin.md)
* Product: **xamarin**
* Technology: **xamarin-crossplatform**
* GitHub Login: @conceptdev
* Microsoft Alias: **crdun**

**Comment by conceptdev** [comment]
Updated to `uninstall-vsmac.sh`
