### ISSUE TITLE
Need to add NSPhotoLibraryUsageDescription to Info.plist or app will crash.

### ISSUE THREAD

**Issue by jgold6** [MicrosoftDocs/xamarin-docs#2413]
Need to add NSPhotoLibraryUsageDescription to Info.plist or app will crash when PHAsset.FetchAssets (PHAssetMediaType.Image, null); is called. 

Also a fully working sample might be in order here as it is not immediately clear what `imageMgr` is in the examples. (It is PHImageManager.DefaultManager I believe). Maybe a link to the UICollectionView sample would be helpful: https://docs.microsoft.com/en-us/samples/xamarin/ios-samples/simplecollectionview/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7056cfb1-5e91-aa40-fe72-0ebcbfcee352
* Version Independent ID: 573414e8-0dcf-9f58-e674-6ac4ac09e0b2
* Content: [PhotoKit in Xamarin.iOS - Xamarin](https://docs.microsoft.com/en-us/xamarin/ios/platform/photokit)
* Content Source: [docs/ios/platform/photokit.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/ios/platform/photokit.md)
* Product: **xamarin**
* Technology: **xamarin-ios**
* GitHub Login: @davidortinau
* Microsoft Alias: **daortin**

**Comment by conceptdev** [comment]
Page has been updated with the **Info.plist** suggestion, and an appropriate sample link
