### ISSUE TITLE
Entry Text Center

### ISSUE THREAD

**Issue by alKhairul** [MicrosoftDocs/xamarin-docs#2417]
How to set text center? After I updated to Xamarin 4.4, HorizontalTextAlignment=Center does not work anymore. Please help. This bug makes me headache, because before this everything is fine. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c5afa3c9-4bcb-4986-2161-1bf2feb856b7
* Version Independent ID: 39fc31bd-4b1d-65f3-aaf8-6eb464e9b38a
* Content: [Xamarin.Forms Entry - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/text/entry#feedback)
* Content Source: [docs/xamarin-forms/user-interface/text/entry.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/text/entry.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @alKhairul 

If you believe there's a bug in Xamarin.Forms you need to open an issue in the [engineering repo](https://github.com/xamarin/Xamarin.Forms/),
