### ISSUE TITLE
Dead link

### ISSUE THREAD

**Issue by Nosegoo** [MicrosoftDocs/xamarin-docs#2418]
The link to the announcement blog in the yellow box warning readers about deprecation of Xamarin Android Player is dead. It ends up leading to Xamarin blog home page instead of the article itself.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2dd9b200-7ae7-5364-db40-eaab79c42435
* Version Independent ID: adca7f09-533b-f8ae-4faf-cb0c924c6aa5
* Content: [Debugging Xamarin.Android on Devices and Emulators - Xamarin](https://docs.microsoft.com/en-us/xamarin/android/deploy-test/debugging/#feedback)
* Content Source: [docs/android/deploy-test/debugging/index.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/android/deploy-test/debugging/index.md)
* Product: **xamarin**
* Technology: **xamarin-android**
* GitHub Login: @davidortinau
* Microsoft Alias: **daortin**

**Comment by conceptdev** [comment]
Thanks for the tip, the outdated section is being removed.
