### ISSUE TITLE
Guide and sample break if Microsoft.AspNetCore.SignalR.Client is updated

### ISSUE THREAD

**Issue by jgold6** [MicrosoftDocs/xamarin-docs#2419]
This guide and sample break if `Microsoft.AspNetCore.SignalR.Client` nuget package is updated to version 3.x in the client app. After updating, clients no longer receive the message. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 99698458-a6cb-0874-bdda-5a3fcb0988b3
* Version Independent ID: 970e5418-c85e-7b4e-adf1-a5ebc411bebc
* Content: [Azure SignalR Service with Xamarin.Forms - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/data-cloud/azure-services/azure-signalr)
* Content Source: [docs/xamarin-forms/data-cloud/azure-services/azure-signalr.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/data-cloud/azure-services/azure-signalr.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @profexorgeek
* Microsoft Alias: **jusjohns**

**Comment by jgold6** [comment]
Apparently this is a known breaking change:

"It is breaking change in SignalR client 3.x. System.Text.Json is now the default Hub Protocol used by SignalR clients v3.x. but the sample send JObject of Newtonsoft.Json.Linq.JObject. Therefore, SignalR client fails to parse the messages.
 
To mitigate the issue, do the following changes in client side:
add package in your csproj: <PackageReference Include="Microsoft.AspNetCore.SignalR.Protocols.NewtonsoftJson" Version="3.1.0" />
create connection and specify json protocol explicitly: var connection = new HubConnectionBuilder().WithUrl(url)***.AddNewtonsoftJsonProtocol()**.Build();"

**Comment by jgold6** [comment]
Oops, typo:

create connection and specify json protocol explicitly: var connection = new HubConnectionBuilder().WithUrl(url)**.AddNewtonsoftJsonProtocol()**.Build();"

**Comment by profexorgeek** [comment]
Thanks for all the info @jgold6! I'll be investigating and fixing this soon.
