### ISSUE TITLE
Looks like this page is using an obsolete API.

### ISSUE THREAD

**Issue by WillAutioItrax** [MicrosoftDocs/xamarin-docs#2420]
I am using something like you have here:
session = NSUrlSession.FromConfiguration
      (configuration, (NSUrlSessionDelegate) new MySessionDelegate(), new NSOperationQueue());
and get the Warning:
"Warning	CS0618	'NSUrlSession.FromConfiguration(NSUrlSessionConfiguration, NSUrlSessionDelegate, NSOperationQueue)' is obsolete: 'Use the overload with a 'INSUrlSessionDelegate' parameter.'"

And according to this url:
https://docs.microsoft.com/en-us/dotnet/api/foundation.nsurlsession.fromconfiguration?view=xamarin-ios-sdk-12#Foundation_NSUrlSession_FromConfiguration_Foundation_NSUrlSessionConfiguration_Foundation_NSUrlSessionDelegate_Foundation_NSOperationQueue_

"This API is now obsolete."
Does this page need updating or am I missing something here?
Thanks!
Will

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a20bd70b-c9fd-a19d-5740-4639cbe254bb
* Version Independent ID: 06ad12d0-9445-a921-9bb4-39381ceccb7c
* Content: [Background Transfer and NSURLSession in Xamarin.iOS - Xamarin](https://docs.microsoft.com/en-us/xamarin/ios/app-fundamentals/backgrounding/ios-backgrounding-walkthroughs/background-transfer-walkthrough)
* Content Source: [docs/ios/app-fundamentals/backgrounding/ios-backgrounding-walkthroughs/background-transfer-walkthrough.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/ios/app-fundamentals/backgrounding/ios-backgrounding-walkthroughs/background-transfer-walkthrough.md)
* Product: **xamarin**
* Technology: **xamarin-ios**
* GitHub Login: @davidortinau
* Microsoft Alias: **daortin**

**Comment by conceptdev** [comment]
The date on the page is 2017 so it's likely that the code shown is out-of-date/needs updating.

In this case, the fix might be as easy as changing the cast to `(INSUrlSessionDelegate)` in the method call.
