### ISSUE TITLE
Spelling mistake

### ISSUE THREAD

**Issue by huckjulius** [MicrosoftDocs/xamarin-docs#2425]
Here is a small spelling mistake:

`By clicking the for Red I-Beams at the top of the editor and clicking Add 4 Constraints, we are telling the text view to stick to the given X,Y coordinates and grow or shrink horizontally and vertically as the window is resized.`

I think it should be `the four Red I-Beams`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 36397c70-dafe-4e57-04e0-1b7ec5b0f83c
* Version Independent ID: b245ec2e-7481-d6fb-73d7-0fa7c3250146
* Content: [Windows in Xamarin.Mac - Xamarin](https://docs.microsoft.com/en-us/xamarin/mac/user-interface/window#feedback)
* Content Source: [docs/mac/user-interface/window.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/mac/user-interface/window.md)
* Product: **xamarin**
* Technology: **xamarin-mac**
* GitHub Login: @davidortinau
* Microsoft Alias: **daortin**

**Comment by conceptdev** [comment]
Updated! Thanks for the tip.
