### ISSUE TITLE
Typo in sample code

### ISSUE THREAD

**Issue by chrisgull** [MicrosoftDocs/xamarin-docs#2429]
Mid-page is a code snippet referring System.IO.ReadAllText.
Correct code should refer System.IO.File.ReadAllText.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 62c77a64-b846-c079-00b2-69e68e1cd556
* Version Independent ID: 26a43118-8b04-86e9-df21-3916e3ec2bac
* Content: [Part 5 - Practical Code Sharing Strategies - Xamarin](https://docs.microsoft.com/en-us/xamarin/cross-platform/app-fundamentals/building-cross-platform-applications/practical-code-sharing-strategies)
* Content Source: [docs/cross-platform/app-fundamentals/building-cross-platform-applications/practical-code-sharing-strategies.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/cross-platform/app-fundamentals/building-cross-platform-applications/practical-code-sharing-strategies.md)
* Product: **xamarin**
* Technology: **xamarin-crossplatform**
* GitHub Login: @davidortinau
* Microsoft Alias: **daortin**

**Comment by conceptdev** [comment]
Thanks for the tip - fixing now.
