### ISSUE TITLE
Xaml Rendering Issue

### ISSUE THREAD

**Issue by tskharva** [MicrosoftDocs/xamarin-docs#243]
I am getting an issue getting the MainPage.xaml to render. I get the following error:
An exception occurred while rendering the control. (Specified cast is not valid). The project builds and runs fine on iOS and Android emulators.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2de3e72c-8948-4dd5-e37f-9cf81e62c127
* Version Independent ID: 7b7c5c7f-4102-8e91-fbe6-7d21fcc8f5be
* Content: [Xamarin.Forms Quickstart - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/get-started/hello-xamarin-forms/quickstart?tabs=vsmac)
* Content Source: [docs/xamarin-forms/get-started/hello-xamarin-forms/quickstart.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/get-started/hello-xamarin-forms/quickstart.md)
* Service: **unspecified**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Thanks for the feedback. I've just tried this sample in the latest VS2017/VS for Mac builds and can't detect any problems.
