### ISSUE TITLE
This documentation is missing The Maps Initialization

### ISSUE THREAD

**Issue by minahenin** [MicrosoftDocs/xamarin-docs#2430]
I followed the instructions but the Maps in iOS didn't work, I almost spent 1 hour till I found that I have to initialize the Maps first in each project
using 
Xamarin.FormsMaps.Init();
in both MainActivity in Android & AppDelegate in iOS, so I appreciate if you mention that step in this documentation to save time for others

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: beb88e8a-8eb4-9dd4-7f2c-b199aab108d3
* Version Independent ID: cdd41cb6-c43a-fb96-5381-9815e50a61ad
* Content: [Xamarin.Forms Map Control - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/map/map#feedback)
* Content Source: [docs/xamarin-forms/user-interface/map/map.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/map/map.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @minahenin 

It's already mentioned in the [first doc](https://docs.microsoft.com/xamarin/xamarin-forms/user-interface/map/setup) in the map series.
