### ISSUE TITLE
HybridWebView didFinishNavigation

### ISSUE THREAD

**Issue by tpitman** [MicrosoftDocs/xamarin-docs#2432]
I followed your example for the HybridWebView on iOS and Android. I have everything working great on Android.

One problem I am having with iOS. I need to get the DidFinishNavigation callback after each page is loaded. I added the following code:

`[Export("webView:didFinishNavigation:")]`
`public void DidFinishNavigation(WKWebView webView, WKNavigation navigation)`
 `{`
`if (hybridWebView != null)`
 `hybridWebView.OnPageLoadComplete(null);`
`}`

I also added the `IWKNavigationDelegate` type to my HybridWebViewRenderer class definition.

I also added this line inside the constructor:

`NavigationDelegate = this;`

None of that seems to matter. I successfully browser to my page, but never hit my break point inside of the DidFinishNavigation.

How do I make this work?

**Comment by davidbritch** [comment]
Hi @tpitman 

The `WebView` control already provides a `Navigated` event you could subscribe to in cross-platform code (or even only in your iOS renderer) to be notified when a page has loaded.

**Comment by tpitman** [comment]
That worked like a charm. Thanks!
