### ISSUE TITLE
The property 'CharacterSpacing' was not found in type 'Entry'

### ISSUE THREAD

**Issue by remziyenuryapici** [MicrosoftDocs/xamarin-docs#2436]
Hello,
I am using xamarin.forms 4.2 and I am getting this error. Is this related to version 4.2?

**Comment by conceptdev** [comment]
Hi @remziyenuryapici these issues are for documentation feedback.

Product issues should go directly to the team on [Xamarin.Forms GitHub](https://github.com/xamarin/xamarin.forms/issues), thanks.
