### ISSUE TITLE
Remote simulator logs

### ISSUE THREAD

**Issue by jgold6** [MicrosoftDocs/xamarin-docs#2437]
The logs for the iOS remote simulator are not in 
~/Library/Logs/Xamarin-[MAJOR.MINOR]
on the Mac, but instead are in 
~/Library/Logs/Xamarin/Simulator.Server

On windows, the remote simulator logs ARE in:
%LOCALAPPDATA%\Xamarin\Logs
but in a subfolder called Xamarin.Simulator, and are not collected when **Help &gt; Xamarin &gt; Zip Logs** is used. 

I checked the remoted simulator docs, https://docs.microsoft.com/en-us/xamarin/tools/ios-simulator/, and there is no troubleshooting section in that doc, so I am making the suggestion to addd the log location for the remote simulator here. But perhaps it would be better to add a troubleshooting section to the remoted simulator doc page showing how to get the remote simulator logs? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 992a68e4-2f19-9cb5-d3b6-4f682ee8a1f4
* Version Independent ID: 61923335-63c3-cc42-f310-eb090e09497b
* Content: [Connection Troubleshooting for a Xamarin.iOS Build Host - Xamarin](https://docs.microsoft.com/en-us/xamarin/ios/get-started/installation/windows/connecting-to-mac/troubleshooting#log-file-location)
* Content Source: [docs/ios/get-started/installation/windows/connecting-to-mac/troubleshooting.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/ios/get-started/installation/windows/connecting-to-mac/troubleshooting.md)
* Product: **xamarin**
* Technology: **xamarin-ios**
* GitHub Login: @davidortinau
* Microsoft Alias: **daortin**

**Comment by conceptdev** [comment]
Adding the log locations to the remoted simulator docs, as suggested.
