### ISSUE TITLE
Documentation is wrong

### ISSUE THREAD

**Issue by PhilPJL** [MicrosoftDocs/xamarin-docs#244]
TBA WCF currently doesn't work with Xamarin.  See https://github.com/dotnet/wcf/issues/2463#issuecomment-387836438. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6b6d6bd0-71b7-f141-2eed-9f99e5d30099
* Version Independent ID: 37b4dd5f-4f41-d850-6be1-be92fcb3b739
* Content: [Walkthrough - Working with WCF - Xamarin](https://docs.microsoft.com/en-us/xamarin/cross-platform/data-cloud/web-services/walkthrough-working-with-wcf)
* Content Source: [docs/cross-platform/data-cloud/web-services/walkthrough-working-with-wcf.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/cross-platform/data-cloud/web-services/walkthrough-working-with-wcf.md)
* Service: **xamarin**
* GitHub Login: @asb3993
* Microsoft Alias: **amburns**

**Comment by bradumbaugh** [comment]
Thanks @PhilPJL. I've added a note to our internal backlog to take a look at this. Appreciate the help.
