### ISSUE TITLE
B2B distribution

### ISSUE THREAD

**Issue by dazinator** [MicrosoftDocs/xamarin-docs#2440]
Apple now also provide "B2B" distribution method. Can these docs be updated to explain / cover this method of distribution please?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 383fce08-fe66-8a22-980f-18751b1d028f
* Version Independent ID: 7a96f3a8-272a-4f0d-352f-efbb62de375b
* Content: [Xamarin.iOS App Distribution Overview - Xamarin](https://docs.microsoft.com/en-us/xamarin/ios/deploy-test/app-distribution/)
* Content Source: [docs/ios/deploy-test/app-distribution/index.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/ios/deploy-test/app-distribution/index.md)
* Product: **xamarin**
* Technology: **xamarin-ios**
* GitHub Login: @davidortinau
* Microsoft Alias: **daortin**

**Comment by conceptdev** [comment]
Much of the business/education distribution process is the same no matter whether the app was built with Xamarin or Swift/Objective-C. Adding links to the page for [Apple's docs on this](https://developer.apple.com/business/custom-apps/).
