### ISSUE TITLE
Part 1. Get Started with XAML is out of date to VS19

### ISSUE THREAD

**Issue by Johnvan** [MicrosoftDocs/xamarin-docs#2441]
The exercises don't match the Create New Project of Visual Studio 19. Example references to Local or ContentPage are not present  in the New Project files produced as it produces a completely difference set of file/directories such as Views and ViewModels, plus the files contain a lot more code than what the course shows.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 02a2221e-ff55-cfe0-9f24-382101584c80
* Version Independent ID: 260000a6-cee8-487a-2fbd-2dfdd0864735
* Content: [Part 1. Getting Started with XAML - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/xaml/xaml-basics/get-started-with-xaml?tabs=windows)
* Content Source: [docs/xamarin-forms/xaml/xaml-basics/get-started-with-xaml.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/xaml/xaml-basics/get-started-with-xaml.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by conceptdev** [comment]
See https://github.com/MicrosoftDocs/xamarin-docs/issues/2442
