### ISSUE TITLE
Part 1. Get Started with XAML

### ISSUE THREAD

**Issue by Johnvan** [MicrosoftDocs/xamarin-docs#2442]
Sorry, my previous feedback is incorrect, the course Part 1 is fine, my mistake when starting a new project. Please disregard my previous comments.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 02a2221e-ff55-cfe0-9f24-382101584c80
* Version Independent ID: 260000a6-cee8-487a-2fbd-2dfdd0864735
* Content: [Part 1. Getting Started with XAML - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/xaml/xaml-basics/get-started-with-xaml?tabs=windows)
* Content Source: [docs/xamarin-forms/xaml/xaml-basics/get-started-with-xaml.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/xaml/xaml-basics/get-started-with-xaml.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by conceptdev** [comment]
Thanks for letting us know.
