### ISSUE TITLE
Error when starting empty project

### ISSUE THREAD

**Issue by JNickVA1** [MicrosoftDocs/xamarin-docs#2443]
I followed the instructions exactly as shown on this page and when I start the emulator by clicking the Debug button, I get the following shown in the emulator:

Encryption Unsuccessful
Encryption was interrupted and can't complete.
As a result, the data on your phone is no longer accessible.

To resume using your phone, you need to perform a factory reset.
blah, blah, blah

Then there is a button stating "Reset Phone"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b4445585-af8f-09d3-5d35-762c3aac187b
* Version Independent ID: fa9263db-60d6-eb98-eb74-842351ba5387
* Content: [Build your first Xamarin.Forms app - Xamarin](https://docs.microsoft.com/en-us/xamarin/get-started/first-app/?pivots=windows&source=docs#feedback)
* Content Source: [docs/get-started/first-app/index.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/get-started/first-app/index.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @conceptdev
* Microsoft Alias: **crdun**

**Comment by conceptdev** [comment]
Please us the [Report a problem feature of Visual Studio](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) for this, it sounds like a problem where having logs and system information might help to resolve. Also, don't forget to mention what platform you are developing on and what emulator (Android or iOS) you are using. Attach a screenshot if possible, thanks.

**Comment by KarimGithub-1** [comment]
.

**Comment by KarimGithub-1** [comment]
test

**Comment by KarimGithub-1** [comment]
404

**Comment by KarimGithub-1** [comment]
error

**Comment by KarimGithub-1** [comment]
This is Text

**Comment by KarimGithub-1** [comment]
cmd
