### ISSUE TITLE
There is no "Instance" property on the MainActivity

### ISSUE THREAD

**Issue by wutever0** [MicrosoftDocs/xamarin-docs#2444]
Something is either missing or wrong in the PhotoPickerService Android implementation code because there is no "Instance" property in the MainActivity class.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 22cd76be-2702-6a58-498c-a84c723d9588
* Version Independent ID: 9f98549e-ff3d-5b8d-67e6-523834c4dd6d
* Content: [Picking a Photo from the Picture Library - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/dependency-service/photo-picker)
* Content Source: [docs/xamarin-forms/app-fundamentals/dependency-service/photo-picker.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/app-fundamentals/dependency-service/photo-picker.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by conceptdev** [comment]
It appears the page does not discuss where `Instance` is defined – please refer to the linked sample, in particular lines [14 and 22 of  MainActivity.cs](https://github.com/xamarin/xamarin-forms-samples/blob/master/DependencyService/DependencyServiceDemos.Android/MainActivity.cs#L14-L22)

```csharp
    internal static MainActivity Instance { get; private set; }

    [Activity(Label = "DependencyServiceDemos", Icon = "@mipmap/icon", Theme = "@style/MainTheme", MainLauncher = true, ConfigurationChanges = ConfigChanges.ScreenSize | ConfigChanges.Orientation)]
    public class MainActivity : global::Xamarin.Forms.Platform.Android.FormsAppCompatActivity
    {
        protected override void OnCreate(Bundle savedInstanceState)
        {
...
            Instance = this;
```

We'll have to update the page to make this clearer, thanks for pointing it out.

**Comment by davidbritch** [comment]
This is now fixed in a PR that will go live later.
