### ISSUE TITLE
Confusing Document Titles

### ISSUE THREAD

**Issue by nobiGT** [MicrosoftDocs/xamarin-docs#2445]
I am implementing Apple Sign-in on Xamarin Forms and find the document titles on the left pane quite confusing :

"Setup for iOS" &lt;-- This is in fact about Xamarin.iOS (and applicable only to iOS 13) despite being under Xamarin.Forms contents
"Setup for other platforms" & "Use Sign In with Apple" &lt;-- This is about Xamarin Forms implementation INCLUDING iOS (iOS 13 and lower)

I already did implement according to "Setup for iOS" and it seems I have to go through again "Setup for other platforms" as this was actually what I needed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: baaa38ab-77e3-83b2-492c-86e1051862c3
* Version Independent ID: 4194e7df-a3fc-fc87-9d7c-c008d1aa6eb2
* Content: [Sign In with Apple in Xamarin.Forms - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/platform/sign-in-with-apple/)
* Content Source: [docs/xamarin-forms/platform/sign-in-with-apple/index.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/platform/sign-in-with-apple/index.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidortinau
* Microsoft Alias: **daortin**

**Comment by davidbritch** [comment]
Hi @nobiGT 

I've just updated the titles in a PR that will go live later.
