### ISSUE TITLE
how to know the implementation ?

### ISSUE THREAD

**Issue by Solyman4** [MicrosoftDocs/xamarin-docs#2447]
Hi , my question is how to know the implementation of an interface ?? for example i have the IOnMapReadyCallback android native interface  , how am i meant to now how to implement it ? 
thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6e9eecf7-0edb-5b24-964c-a1ae2e7556ba
* Version Independent ID: 8f9243b4-0f7c-6aac-39e2-913173ea472a
* Content: [Xamarin.Forms DependencyService Introduction - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/dependency-service/introduction#feedback)
* Content Source: [docs/xamarin-forms/app-fundamentals/dependency-service/introduction.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/app-fundamentals/dependency-service/introduction.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @Solyman4 

Are you sure you need to implement `IOnMapReadyCallback`? The Android `MapRenderer` on Xamarin.Forms already implements this interface - https://github.com/xamarin/Xamarin.Forms/blob/master/Xamarin.Forms.Maps.Android/MapRenderer.cs
