### ISSUE TITLE
Really dude?

### ISSUE THREAD

**Issue by thomas-cruz** [MicrosoftDocs/xamarin-docs#2449]
Mate, I click on "Download Now" in Visual Studio and it directs me to a page where it says "You already downloaded it" when I really haven't. AND THEN the page asks if I found this helpful? Do YOU think that's helpful? Is this a joke?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 97e1cd96-e7a2-ec22-8d79-ac949e890ccb
* Version Independent ID: 922a3fdf-7bab-7d9d-5518-904db9e75ee3
* Content: [Microsoft's Mobile OpenJDK Distribution - Xamarin](https://docs.microsoft.com/en-us/xamarin/android/get-started/installation/openjdk#feedback)
* Content Source: [docs/android/get-started/installation/openjdk.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/android/get-started/installation/openjdk.md)
* Product: **xamarin**
* Technology: **xamarin-android**
* GitHub Login: @vyedin
* Microsoft Alias: **vyedin**

**Comment by GavinThornton** [comment]
Are you using Visual Studio Installer like it says above? Open Visual Studio Installer, click the "Modify" button next to VS2019, click the "Individual Components" tab, in the search bar type "android" and see of the "OpenJDK" item is ticked.

**Comment by moljac** [comment]
I did minimal tests on Windows with Zulu and Adopt Open JDK. You need to use Java 8, because MSBuild tasks will not let you use newer versions.

*   https://www.azul.com/downloads/zulu-community/?package=jdk

*   https://adoptopenjdk.net/

*   https://adoptopenjdk.net/releases.html

I was able to launch AndroidX migrated apps in the emulator, but that is about it.

**Comment by davidortinau** [comment]
For issues such as this please report feedback through Visual Studio using the report feature under Help.
