### ISSUE TITLE
More details on DeviceInfo Version and VersionString

### ISSUE THREAD

**Issue by shalinasanga** [MicrosoftDocs/xamarin-docs#2450]
it's great if this page can provide more detail and descriptive information on Version & VersionString
what are those 
what those does
usage 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c918dea8-217e-8886-73ad-c1dcb9cc1e1e
* Version Independent ID: 238f8427-325c-dc77-caaf-1f3a8e44df88
* Content: [Xamarin.Essentials: Device Information - Xamarin](https://docs.microsoft.com/en-us/xamarin/essentials/device-information?context=xamarin%2Fandroid&tabs=ios#feedback)
* Content Source: [docs/essentials/device-information.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/essentials/device-information.md)
* Product: **xamarin**
* Technology: **xamarin-essentials**
* GitHub Login: @jamesmontemagno
* Microsoft Alias: **jamont**

**Comment by jamesmontemagno** [comment]
Version is the operating system version and VersionString is just the string representation of it.
