### ISSUE TITLE
Not working in XAML

### ISSUE THREAD

**Issue by domagojmedo** [MicrosoftDocs/xamarin-docs#2452]
When trying this in XAML I get "The attachable property 'Elevation' was not found in type 'VisualElement'". 
When I type android: all I get from intellisense is Button, Entry, ListView, TabbedPage and WebView

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0e2ccd04-96eb-bee8-3a68-95a590291cb2
* Version Independent ID: 366097b0-7c57-279e-f346-c7e06cb53ed4
* Content: [VisualElement Elevation on Android - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/platform/android/visualelement-elevation#feedback)
* Content Source: [docs/xamarin-forms/platform/android/visualelement-elevation.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/platform/android/visualelement-elevation.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @domagojmedo 

If you try the sample the page in question links to, you'll see that the code works and will hopefully find your answer there.

**Comment by andy-cox** [comment]
I'm also getting the same. I took a look at the sample but I cannot see what the issue is!

![image](https://user-images.githubusercontent.com/62072/94529545-c794c180-0231-11eb-8977-b5a1f27d7593.png)

**Comment by NathanCrama** [comment]
I've had the same issue. The code-behind part of the sample worked for me but the XAML didn't.

**Comment by davidbritch** [comment]
I've just tried it again. Worked perfectly. The error you see above is an Intellisense error, not a build error.
