### ISSUE TITLE
Link broken

### ISSUE THREAD

**Issue by onurhazar** [MicrosoftDocs/xamarin-docs#2453]
Latest release notes page for Xamarin iOS 13.10 is not reachable. Please fix it.
https://docs.microsoft.com/en-us/xamarin/ios/release-notes/13/13.10

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 387b26bc-ceb7-6e63-02ff-9a9c8b4262cc
* Version Independent ID: 7bc8c403-fd95-4527-7599-c2eedb27a831
* Content: [Introduction to iOS 13 - Xamarin](https://docs.microsoft.com/en-us/xamarin/ios/platform/ios13/)
* Content Source: [docs/ios/platform/ios13/index.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/ios/platform/ios13/index.md)
* Product: **xamarin**
* Technology: **xamarin-ios**
* GitHub Login: @davidortinau
* Microsoft Alias: **daortin**

**Comment by conceptdev** [comment]
Thanks for your feedback. The link on this page is correct. Release notes are published by the engineering team, I'm sure they'll be updated as soon as possible after each release.

**Comment by conceptdev** [comment]
FYI, the team published this just now
https://docs.microsoft.com/xamarin/ios/release-notes/13/13.10
