### ISSUE TITLE
Confusing which hardware accelerator to use

### ISSUE THREAD

**Issue by tonivuc** [MicrosoftDocs/xamarin-docs#2454]
At the top of the article it says
"For the best experience on Windows, it is recommended that you use HAXM to accelerate the Android emulator."
in the HAXM section it says:
"Use HAXM to accelerate the Android emulator if your computer does not support Hyper-V."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4e37d642-2051-8d70-9968-dfb484122a6a
* Version Independent ID: 178ea80c-2b99-0c44-eeb6-9db319439b33
* Content: [Hardware Acceleration for Emulator Performance (Hyper-V & HAXM) - Xamarin](https://docs.microsoft.com/en-us/xamarin/android/get-started/installation/android-emulator/hardware-acceleration?pivots=windows#feedback)
* Content Source: [docs/android/get-started/installation/android-emulator/hardware-acceleration.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/android/get-started/installation/android-emulator/hardware-acceleration.md)
* Product: **xamarin**
* Technology: **xamarin-android**
* GitHub Login: @davidortinau
* Microsoft Alias: **daortin**

**Comment by JonDouglas** [comment]
The most performant experience is using HAXM. The most compatible experience is using WHPX(Hyper-V). We will work to change our docs to reflect this and remove confusion in the future. Thanks for the report!
