### ISSUE TITLE
UIParent is Obselete in Msal3.x

### ISSUE THREAD

**Issue by thekeviv** [MicrosoftDocs/xamarin-docs#2455]
Here's the link to the documentation. I think we just have to use an embedded view now?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 11f5b457-d99a-06d4-d203-f9eeaa27e0d9
* Version Independent ID: b23b3a5d-b63b-dfe1-bb46-94f57c907be5
* Content: [Authenticate Users with Azure Active Directory B2C - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/data-cloud/authentication/azure-ad-b2c)
* Content Source: [docs/xamarin-forms/data-cloud/authentication/azure-ad-b2c.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/data-cloud/authentication/azure-ad-b2c.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by thekeviv** [comment]
https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/MSAL.NET-2.x-to-MSAL.NET-3.x

**Comment by profexorgeek** [comment]
Hi @thekeviv,
As far as I can tell, this is incorrect.

MSAL offers the option of authenticating with the system browser or an embedded web view. Typically a system browser is preferred for these reasons:

- It allows you to share SSO across applications (and it offers the user a familiar experience).
- It offers a familiar experience to the user
- It is better supported (docs linked below contain warnings about system brokers and other gotchas)

On Android if you want to use the system browser, it is _required_ that you call `WithActivityOrParentWindow` and pass an `Activity` instance - either when configuring the client or making the token request. See: https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/Xamarin-Android-specifics

On iOS it is optional but providing an instance of `IUIViewController` seems to offer some advantages to user experience (unsure about the specifics of this as I did not explore passing it versus not passing it personally). See: https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/MSAL.NET-uses-web-browser#developer-options

So, in the sample application we define an `object` called `UIParent` in the shared project on the `App` class. This allows each platform project to specify the UI parent: an `Activity` instance on Android and `null` or an `IUIViewController` instance on iOS. This allows the sample to make token requests in the shared code using platform-specific instances.
