### ISSUE TITLE
Got NullReferenceException in iOS

### ISSUE THREAD

**Issue by HectorMeneses333** [MicrosoftDocs/xamarin-docs#2457]
when running the code for this article, I get a null reference exception when navigating back after saving a note.

Looks like the offending code is in Platform.cs :
Application.Current.NavigationProxy.Inner = this; 

where Application is not defined.
How can this be fixed?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2e9d651b-6624-f671-16e2-61c28415374b
* Version Independent ID: 61600bb9-66b3-904d-6be3-32029e78bc5a
* Content: [Xamarin.Forms in Xamarin Native Projects - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/platform/native-forms#feedback)
* Content Source: [docs/xamarin-forms/platform/native-forms.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/platform/native-forms.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by conceptdev** [comment]
Thanks @HectorMeneses333, I can reproduce this error (only on the iOS project, Android seems to work fine).

Specifically, the `Application` **Xamarin.Forms.Platform.iOS/Platform.cs** [line 231](https://github.com/xamarin/Xamarin.Forms/blob/master/Xamarin.Forms.Platform.iOS/Platform.cs#L238). That line of code is 3 years old, so I wonder if something in iOS 13 has changed how this app interacts with the SDK.

There is no obvious reason for the crash in the sample code, so I will have to refer this to the engineering team.

**Comment by conceptdev** [comment]
I've raised this as an issue on the [Xamarin.Forms repo - issue 9269](https://github.com/xamarin/Xamarin.Forms/issues/9269). Please follow progress there.

**Comment by HectorMeneses333** [comment]
Hi Craig,

Thanks!
We had the same issue when trying to implement the back button navigation for an embedded Xamarin forms page in a native app.

Hector

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
