### ISSUE TITLE
How to put email and password on request to login for xamarin mobile login?

### ISSUE THREAD

**Issue by linh040800** [MicrosoftDocs/xamarin-docs#2459]
I still don't  understand put email and password for request to get authentication code and token? Please explain this my question for me.
Many Thanks

**Comment by conceptdev** [comment]
Please refer to our documentation on [authentication with Azure](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/data-cloud/authentication/azure-ad-b2c).
