### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by c-lamont** [MicrosoftDocs/xamarin-docs#246]
Really poor document. You can't just add `<JavaDocPaths>` in the `.csproj`. Can you explain or add a link to what the Javadoc is and where it can usually be obtained.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8c9721ce-84ff-172f-3316-0d7fed7d36cd
* Version Independent ID: 966f0f4f-1e83-1bf2-e6db-2f56d55dd613
* Content: [Naming Parameters With Javadoc - Xamarin](https://docs.microsoft.com/en-us/xamarin/android/platform/binding-java-library/customizing-bindings/naming-parameters-with-javadoc)
* Content Source: [docs/android/platform/binding-java-library/customizing-bindings/naming-parameters-with-javadoc.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/android/platform/binding-java-library/customizing-bindings/naming-parameters-with-javadoc.md)
* Service: **xamarin**
* GitHub Login: @mgmclemore
* Microsoft Alias: **mamcle**

**Comment by mgmclemore** [comment]
Hi @c-lamont, thanks for you feedback!  Yes, this topic is poorly written and it is too short. I'm adding a task to our backlog to have this topic rewritten.

**Comment by joaosilvareed** [comment]
It's been several months and it still says the same, nothing helpful.

**Comment by alexsorokoletov** [comment]
+1, needs some explanation or example what is considered a good Javadoc.
Also, if something does not really work (and the parameters are still p0, p1) the build log with LOG_LEVEL=diagnostic shows no information whatsoever what went wrong

**Comment by tompi** [comment]
+1, Spent some hours trying to get at least param names different than p0, p1 etc, but giving up, cant figure out what is going wrong(tried javadoc-index build target(including all javadoc in solution) and also the property group with javadocpaths...

**Comment by StefAnglr** [comment]
+1. Glad I found this issue before I spent any time trying to use this feature.
