### ISSUE TITLE
Obfuscation and dotPeek

### ISSUE THREAD

**Issue by Syed-Aoon** [MicrosoftDocs/xamarin-docs#2460]
I have tried dotfuscator and many other tools to obfuscate my code but i realize that all these are useless as resultant code in dlls (obfuscated dlls) can be seen easily by dotPeek tool.

**Comment by conceptdev** [comment]
Obfuscation is not a feature of Visual Studio or Xamarin. There is a [community edition of Dotfuscator](https://devblogs.microsoft.com/xamarin/protect-xamarin-android-apps-dotfuscator/) in some versions of Visual Studio, but you should reach out to PreEmptive Solutions (publishers of Dotfuscator) for specifics on how their product works.
