### ISSUE TITLE
UWP implementation

### ISSUE THREAD

**Issue by illanos** [MicrosoftDocs/xamarin-docs#2461]
Hi!, 
Could you please add an example for UWP? 

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ddbe4aab-ea07-14fa-09ff-f68e43fe289a
* Version Independent ID: 44dbed2f-fa71-dfee-90e1-422f52ba3891
* Content: [Xamarin.Forms Reusable RoundEffect - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/effects/reusable-roundeffect#feedback)
* Content Source: [docs/xamarin-forms/app-fundamentals/effects/reusable-roundeffect.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/app-fundamentals/effects/reusable-roundeffect.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @profexorgeek
* Microsoft Alias: **jusjohns**

**Comment by profexorgeek** [comment]
Hi @illanos,
I have created an internal work item for our team to discuss and prioritize.
Thanks for your suggestion!
