### ISSUE TITLE
Give us more integration examples

### ISSUE THREAD

**Issue by NickeManarin** [MicrosoftDocs/xamarin-docs#2462]
It would be great if login examples from LinkedIn, GitHub, Microsoft, Twitter and Facebook existed too.

They all differ from the Google example, so it would be good to have in here too.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aa8bb9e0-5898-0d11-0213-fd4d8c8d0297
* Version Independent ID: 2f46e1f7-164f-2f32-70c0-f28919d16c5c
* Content: [AuthenticateUsers with an Identity Provider - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/data-cloud/authentication/oauth)
* Content Source: [docs/xamarin-forms/data-cloud/authentication/oauth.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/data-cloud/authentication/oauth.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @NickeManarin 

Thanks for the suggestion. I've added it to our backlog.
