### ISSUE TITLE
UWP section needs to be fleshed out.

### ISSUE THREAD

**Issue by drchilds** [MicrosoftDocs/xamarin-docs#2466]
Either in this page or the "Create a Shell application" page, additional steps need to be detailed as to how to add the experimental UWP project to a solution.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 09e0923c-3c3a-4e9b-bb30-b2d3fff2c34e
* Version Independent ID: 1a13d34a-8416-8e29-c65d-2c6d41c72b40
* Content: [Xamarin.Forms Shell Introduction - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/shell/introduction#feedback)
* Content Source: [docs/xamarin-forms/app-fundamentals/shell/introduction.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/app-fundamentals/shell/introduction.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @drchilds 

I've added a link to [Setup Windows Projects](https://docs.microsoft.com/xamarin/xamarin-forms/platform/windows/installation/) to this doc, in a PR that will go live later.
