### ISSUE TITLE
Is .NET Embedding with C available with Android NDK?

### ISSUE THREAD

**Issue by WesleyKhoiVo** [MicrosoftDocs/xamarin-docs#2469]
I see a commit in Embeddinator-4000 [37a4362](https://github.com/mono/Embeddinator-4000/pull/382/commits/37a436252aa96bb9693e8747eec0b81283496460) in a pull request [382](https://github.com/mono/Embeddinator-4000/pull/382/commits) has support compile with NDK. But in this document doesn't talk about it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9256b5bb-c992-0f75-aa3e-e1cac2c600ca
* Version Independent ID: c6a0defa-2a17-a88e-e989-b23de2b70a0b
* Content: [Getting started with C - Xamarin](https://docs.microsoft.com/en-us/xamarin/tools/dotnet-embedding/get-started/c)
* Content Source: [docs/tools/dotnet-embedding/get-started/c.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/tools/dotnet-embedding/get-started/c.md)
* Product: **xamarin**
* Technology: **xamarin-crossplatform**
* GitHub Login: @davidortinau
* Microsoft Alias: **daortin**

**Comment by WesleyKhoiVo** [comment]
Hi Microsoft, is there anything new?

**Comment by steenmbiz** [comment]
I'm also interesting about this, any tutorial is helpful!

**Comment by davidbritch** [comment]
Hi @WesleyKhoiVo 

Afraid that this tool is no longer supported, and so the docs have been removed.
