### ISSUE TITLE
Download link "installer from Apple" not working

### ISSUE THREAD

**Issue by rdeveen** [MicrosoftDocs/xamarin-docs#2473]
Correct link is https://www.apple.com/itunes/download/win64

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: 8f3eb808-8e6d-4e07-fc75-8d79a7249265
* Version Independent ID: dbb2b9a9-87a6-e473-50e6-f88435d49e88
* Content: [Xamarin Hot Restart - Xamarin](https://docs.microsoft.com/nl-nl/xamarin/xamarin-forms/deploy-test/hot-restart#feedback)
* Content Source: [docs/xamarin-forms/deploy-test/hot-restart.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/deploy-test/hot-restart.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @jimmgarrido
* Microsoft Alias: **jigarrid**

**Comment by jimmgarrido** [comment]
Hey there! The link in the doc redirects to https://www.apple.com/itunes/download/win64 , is the redirect failing for you?

**Comment by rdeveen** [comment]
It was failing, but now its working.
