### ISSUE TITLE
Disable a SwipeView not working

### ISSUE THREAD

**Issue by vladsava87** [MicrosoftDocs/xamarin-docs#2476]
The IsEnabled property of the SwipeView doesn't disable the swipe event for the user as expected. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 02d932c9-7483-c314-b1c6-3850778cd6dc
* Version Independent ID: 8ab4f230-a8ff-5164-d377-b0b12cac5f09
* Content: [Xamarin.Forms SwipeView - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/swipeview)
* Content Source: [docs/xamarin-forms/user-interface/swipeview.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/swipeview.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @vladsava87 

I can see you've logged this as a bug in the engineering repo (https://github.com/xamarin/Xamarin.Forms/issues/9329) so I'll close it here.
