### ISSUE TITLE
No Content page

### ISSUE THREAD

**Issue by Cyderrules** [MicrosoftDocs/xamarin-docs#2478]
Hello
When I am following this "Get started..." I create a project called 'Notes' and click on the Xaml in the Notes MainPage but I do not have a contents page to be able to replace the code (the first step) how do I find the contents page? thank you. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5a064123-54f2-0eb2-c76a-65b36c5ec1a7
* Version Independent ID: dbf4119a-2c24-e0f1-8041-bb3755c29c24
* Content: [Create a single page Xamarin.Forms application - Xamarin](https://docs.microsoft.com/en-us/xamarin/get-started/quickstarts/single-page?pivots=windows#feedback)
* Content Source: [docs/get-started/quickstarts/single-page.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/get-started/quickstarts/single-page.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @Cyderrules 

It's literally as in step 5 in the page. When you open MainPage.xaml you'll see the code displayed in the screenshot. Highlight the code and delete it, and paste in the code from step 6.
