### ISSUE TITLE
StackLayout Tutorial Step 1 Feedback

### ISSUE THREAD

**Issue by Cyderrules** [MicrosoftDocs/xamarin-docs#2479]
If replace all code I get errors. if replace after _using Xamarin.Forms_
still, get errors. where exactly should the code go? it doesn't explain properly.  

<>
namespace StackLayoutTutorial
{
    
    {<? xml version="1.0" encoding="utf-8"?>
<ContentPage xmlns = "http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="StackLayoutTutorial.MainPage">
    <StackLayout Margin = "20,35,20,25" >
        < Label Text="The StackLayout has its Margin property set, to control the rendering position of the StackLayout." />
        <Label Text = "The Padding property can be set to specify the distance between the StackLayout and its children." />
        < Label Text="The Spacing property can be set to specify the distance between views in the StackLayout." />
    </StackLayout>
</ContentPage>
        }

}

### Information

- IDE and IDE version: 
- Platform with the issue: 
  - iOS:  
  - Android:

**Comment by davidbritch** [comment]
Hi @Cyderrules 

As step 2 in the walkthrough explains, open MainPage.xaml (not MainPage.xaml.cs) and remove all the XAML and replace it with the code shown.

From above it looks like you've pasted the XAML into MainPage.xaml.cs.

At the end of each tutorial there's a link to download a working sample for the tutorial, so you can always compare against that.
