### ISSUE TITLE
Could the SwipeView's Command support the AncestorType Relative Binding?

### ISSUE THREAD

**Issue by joewang1967** [MicrosoftDocs/xamarin-docs#2481]
Could the SwipeView's Command support the AncestorType Relative Binding? Sample?

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 02d932c9-7483-c314-b1c6-3850778cd6dc
* Version Independent ID: 8ab4f230-a8ff-5164-d377-b0b12cac5f09
* Content: [Xamarin.Forms SwipeView - Xamarin](https://docs.microsoft.com/en-gb/xamarin/xamarin-forms/user-interface/swipeview)
* Content Source: [docs/xamarin-forms/user-interface/swipeview.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/swipeview.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @joewang1967 

It's difficult to say. The answer should of course be yes. But at the moment the answer appears to be no. However, this could equally well be due to the SwipeView having problems even executing a command, regardless of where the command binds to (see https://github.com/xamarin/Xamarin.Forms/issues/9028).

**Comment by joewang1967** [comment]
> Hi @joewang1967
> 
> It's difficult to say. The answer should of course be yes. But at the moment the answer appears to be no. However, this could equally well be due to the SwipeView having problems even executing a command, regardless of where the command binds to (see [xamarin/Xamarin.Forms#9028](https://github.com/xamarin/Xamarin.Forms/issues/9028)).

Thank you. We have the same expectations and feelings before and after I did a test for a practical application.
