### ISSUE TITLE
Does not play on iOS Simulator

### ISSUE THREAD

**Issue by iam-b-ly** [MicrosoftDocs/xamarin-docs#2486]
Ran the code using an iOS Simulator but the videos do not play. Does this class not support running on a simulator?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0081290c-715f-d4fa-38ca-6cfdfd65b5c0
* Version Independent ID: 8fd98837-f8b5-d341-c18c-6ca2c760973d
* Content: [Implementing a video player - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/custom-renderer/video-player/)
* Content Source: [docs/xamarin-forms/app-fundamentals/custom-renderer/video-player/index.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/app-fundamentals/custom-renderer/video-player/index.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @iam-b-ly 

I just tried the sample in an iOS simulator and videos played just fine:

![Simulator Screen Shot - iPhone X - 2020-01-29 at 11 53 41](https://user-images.githubusercontent.com/8092460/73354704-41813f00-428e-11ea-849d-606b8204ee81.png)

![Simulator Screen Shot - iPhone X - 2020-01-29 at 11 54 35](https://user-images.githubusercontent.com/8092460/73354705-41813f00-428e-11ea-8649-36df02676421.png)

**Comment by iam-b-ly** [comment]
I tried it again several times today and was able to play a few seconds of the videos on a couple of attempts before the loading icon plays indefinitely. I also tried to change the 8mb resource video to a 23mb video and the app simply closes when it attempted to play. I am using a VS locally and connected to a MacinCloud. I am guessing it has something to do with my internet connection?

**Comment by davidbritch** [comment]
My guess is it's an issue with MacinCloud/your connection to MacinCloud.

Two items that will help you here, in the not too distant future are:

1. Xamarin.Forms has gained a `MediaElement` control that can play videos, without you having to resort to custom renderers. It was merged into master this week, so should be appearing a release soon. It'll be an experimental control initially (behind an experimental flag).
1. Visual Studio 2019 16.5 Preview has a new feature called hot restart. It enables you to debug Xamarin.Forms iOS apps on a device, from Windows, without requiring a Mac to build the app. However, you still need a Mac to build the final app for publishing

**Comment by iam-b-ly** [comment]
Cool. Thank you so much for the valuable insight and quick response.
