### ISSUE TITLE
Xamarin.Auth and Salesforce

### ISSUE THREAD

**Issue by JeffWeber** [MicrosoftDocs/xamarin-docs#2493]
I have a need to access Salesforce from a Xamarin.Forms app.

Does the current version of Xamarin.Auth support this? It seems close, but there are few things in the following Salesforce documentation that seem to be missing in Xamaring.Auth.

https://developer.salesforce.com/docs/atlas.en-us.api_rest.meta/api_rest/intro_understanding_web_server_oauth_flow.htm

The documentation mentions the requirement of a 'grant_type' parameter on the call to get the token, but I'm not sure how to add that after Xamarin.Auth gets the Authorization Code.

-Jeff

**Comment by davidbritch** [comment]
Hi @JeffWeber 

Xamarin.Auth doesn't generally support the kind of fine grained control you need over the authentication process. For that, I recommend the OIDCClient2 library. For more details, see a blog post I wrote at https://www.davidbritch.com/2019/07/oauth-20-for-native-apps-using.html
