### ISSUE TITLE
Shell TabBar Issue

### ISSUE THREAD

**Issue by IndexOutOfLimit** [MicrosoftDocs/xamarin-docs#2496]
[Enter feedback here]
I am facing issue while implementing TabBar on Xamarin.Forms Shell. Issue is I am not able to open a popup page which is required for my project to open Modal popup , show custom Alert with overlay. It's crashing. One more issue is I am not able to get any event on my ViewModel during the load of Detail page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f64762a5-78e3-5c1e-b8b3-9572d66110f5
* Version Independent ID: bb324623-2127-a5a3-d620-ebf314dfbf1a
* Content: [Xamarin.Forms Shell - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/shell/)
* Content Source: [docs/xamarin-forms/app-fundamentals/shell/index.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/app-fundamentals/shell/index.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @IndexOutOfLimit 

Xamarin.Forms 4.5 (currently a pre-release) has support for a page presentation mode in Shell apps. This enables you to display a page as a modal page, which sounds like what you're trying to accomplish. It's available from the 4.5-pre2 (and upwards) release.

**Comment by IndexOutOfLimit** [comment]
Thanks David for your valuable input. Actually , I am facing another issue
on using Shell TabBar.Scenario is below:

I have one login screen(without TabBar) and once user logs in I need do
show another content page which is again without TabBar. But that user will
be navigated to 3rd page which will have TabBar.

So, in the above context I was able to hide TabBar for first 2 pages but on
the third page when I am trying to set TabBar visibility to true , TabBar
is not showing up.
Secondly, on clicking on one of the TabItem I need to open pop up modal and
on Tab selection event U need to change TabItem Title text color and icon
which needs to be done using font awesome. Here I am not able to track tab
selection event on Xamarin.Forms project level.

It would be highly appreciated if I can get some help or idea on how to
accomplish that.

Thanks again,
Bikash Ghosh

**Comment by davidbritch** [comment]
Hi @IndexOutOfLimit 

For the first issue (TabBar visibility), I recommend you open an issue in the [engineering repo](https://github.com/xamarin/Xamarin.Forms/) (there may already be an issue for it - see https://github.com/xamarin/Xamarin.Forms/issues/6485).

For the second issue, as tab selection results in a page being displayed, you should be able to handle the PageAppearing event to derive when a tab is selected. You can even handle that in a view model with a behavior.
