### ISSUE TITLE
Path Information and Enumeration example bug

### ISSUE THREAD

**Issue by timskillman** [MicrosoftDocs/xamarin-docs#2498]
Used the code on this page and found the 

`FlattenConic(SKPoint pt0, SKPoint pt1, SKPoint pt2, float weight)` 

... function doesn't set the points

Just add

`points[i] = new SKPoint(x, y);`

To fix :)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3fc79f7a-2df3-6c07-82a3-a94b758877e1
* Version Independent ID: 92c3c2d5-759b-102a-2fd1-3b4ecc3860d7
* Content: [Path Information and Enumeration - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/graphics/skiasharp/curves/information)
* Content Source: [docs/xamarin-forms/user-interface/graphics/skiasharp/curves/information.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/graphics/skiasharp/curves/information.md)
* Product: **xamarin**
* Technology: **xamarin-skiasharp**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @timskillman 

Thanks for this. I've just updated the doc/sample. It'll go live once it makes its way through our CI system.

**Comment by timskillman** [comment]
That's great!  Glad to help.

Tim Skillman
