### ISSUE TITLE
Create an emulator - prerequisites?

### ISSUE THREAD

**Issue by Legends** [MicrosoftDocs/xamarin-docs#2499]
I've created a xamarin.forms app via VS2019 templates, when I press debug it wants me to create an Android Emulator.

The create never ends:

![image](https://user-images.githubusercontent.com/966368/73584558-744b5300-4499-11ea-97b5-3f039d29d301.png)

 and while hovering over all emulators it shows error:

![image](https://user-images.githubusercontent.com/966368/73584625-ea4fba00-4499-11ea-81ba-cd2b669ce4b1.png)

What do I need in order to create/debug a xamarin.forms app in VS2019?
Are there emulators for all available devices (Pocophone F1)?

#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5fc5d4b4-e0c4-7399-8e32-2c2fe935cbbe
* Version Independent ID: 89992fd0-d78a-fc6f-16f9-1ee91cf18485
* Content: [Installing Xamarin - Xamarin](https://docs.microsoft.com/en-us/xamarin/get-started/installation/?pivots=windows)
* Content Source: [docs/get-started/installation/index.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/get-started/installation/index.md)
* Product: **xamarin**
* Technology: **xamarin-crossplatform**
* GitHub Login: @conceptdev
* Microsoft Alias: **crdun**

**Comment by davidbritch** [comment]
@JonDouglas Can you advise?

**Comment by JonDouglas** [comment]
@Legends The Device Manager should handle creation of the emulator for you by downloading all prerequisites needed. If you are having issues downloading through it, double check your connection and ensure you're not behind a proxy or similar.

You can additionally download these items manually through the Android SDK Manager:

https://docs.microsoft.com/en-us/xamarin/android/get-started/installation/android-sdk?tabs=windows

> Are there emulators for all available devices (Pocophone F1)?

Not by default, but you can create your own device that matches whatever device you want.

**Comment by Legends** [comment]
Ok, good, so why is it not creating the emulator?

How many hours do I have to wait?

![image](https://user-images.githubusercontent.com/966368/73959998-75053e80-490a-11ea-98d4-2b658d30f592.png)
