### ISSUE TITLE
Where is mtouch?

### ISSUE THREAD

**Issue by joaosilvareed** [MicrosoftDocs/xamarin-docs#25]
Where can I find the mtouch command on a Mac? if I write mtouch it doesn't find it.

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 548b6d92-e589-8adb-029f-c8ffe58325e5
* Version Independent ID: b2418389-a0bb-4616-4e72-d1909a337a98
* Content: [mtouch - Xamarin | Microsoft Docs](https://docs.microsoft.com/en-us/xamarin/ios/deploy-test/mtouch)
* Content Source: [docs/ios/deploy-test/mtouch.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/ios/deploy-test/mtouch.md)
* Service: **unspecified**
* GitHub Login: @bradumbaugh
* Microsoft Alias: **brumbaug**

**Comment by HankiDesign** [comment]
You need to manually add the location of the mtouch executable to your PATH. Make sure that it exists in the following location (with Finder or terminal): 

`/Library/Frameworks/Xamarin.iOS.framework/Versions/Current/bin/mtouch`

If you see a bunch of executables, including mtouch, run the following command on the terminal to add the directory to your path:

`export PATH=$PATH:/Library/Frameworks/Xamarin.iOS.framework/Versions/Current/bin`

After that, you should be able to run any example from the article you linked to.

**Comment by bradumbaugh** [comment]
Thanks for the question, @joaosilvareed, and thanks @HankiDesign for chiming in - much appreciated. I'll add this information to the docs!
