### ISSUE TITLE
Profiles is the worst possible option

### ISSUE THREAD

**Issue by jormundgand** [MicrosoftDocs/xamarin-docs#250]
I'm currently working on a pure desktop app that will not be ported to any mobile device (the app doesn't make sense on mobile devices). Because PCLs are based on profiles I am forced to either *only* support Windows or support Windows, Mac and a multitude of mobiles devices; I just need the Windows and Mac support.

If PCLs had been based on, say, having a list of platforms supported rather than a profile with hardcoded platforms, I could have avoid this *and* added support for any other platform that hasn't been graced with a profile by Microsoft. As it is now, profiles is the worst possible solution to the problem of specifying which platforms are supported by a PCL.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 271e134d-3069-e673-3874-faf6930a19ee
* Version Independent ID: 0c84a593-80cf-6195-c082-6752736f386b
* Content: [Introduction to Portable Class Libraries - Xamarin](https://docs.microsoft.com/en-us/xamarin/cross-platform/app-fundamentals/pcl?tabs=vsmac)
* Content Source: [docs/cross-platform/app-fundamentals/pcl.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/cross-platform/app-fundamentals/pcl.md)
* Service: **xamarin**
* GitHub Login: @asb3993
* Microsoft Alias: **amburns**

**Comment by bradumbaugh** [comment]
Hi @jormundgand, this repository is intended specifically for issues related to the documentation. For general support, please feel free to post a question in [Developer Community](https://developercommunity.visualstudio.com/spaces/8/index.html).

That said, you might be interested in the .NET Standard documentation found [here](https://docs.microsoft.com/xamarin/cross-platform/app-fundamentals/net-standard) and [here](https://docs.microsoft.com/dotnet/standard/net-standard) or the [Shared Project](https://docs.microsoft.com/xamarin/cross-platform/app-fundamentals/shared-projects) documentation.
