### ISSUE TITLE
ScrollTo with viewModel throws Invalid Target Position

### ISSUE THREAD

**Issue by eli191** [MicrosoftDocs/xamarin-docs#2500]
The `ScrollTo` method with an item from the source list of the `CarouselView` throws an exception `Invalid Target Position`. `ScrollTo` with index works.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c160c440-f809-0887-0547-ba78be2fc3d5
* Version Independent ID: 88e2f5b3-e2f0-9e15-598a-7c362e549a67
* Content: [Xamarin.Forms CarouselView Scrolling - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/carouselview/scrolling#feedback)
* Content Source: [docs/xamarin-forms/user-interface/carouselview/scrolling.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/carouselview/scrolling.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @eli191 

Yes. It's fixed in one of the 4.5 pre-releases.

**Comment by lorne-olo** [comment]
Fixed in a 4.5 pre-release, huh?
I'm seeing this in 4.8.
I can't use either of the ScrollTo overloads without this error occurring!!!

**Comment by lorne-olo** [comment]
Still doesn't work in 4.8.
