### ISSUE TITLE
Device.BeginInvokeOnMainThread behaves differently to MainThread.BeginInvokeOnMainThread

### ISSUE THREAD

**Issue by DamianMehers** [MicrosoftDocs/xamarin-docs#2504]
This doc states that: *Xamarin.Forms has a method called Device.BeginInvokeOnMainThread(Action) that does the same thing as MainThread.BeginInvokeOnMainThread(Action).*

This isn't currently the case:

`Device.BeginInvokeOnMainThread` **always queues the action** for later invocation on the main thread (`s_handler.Post(action)` on Android and `NSRunLoop.Main.BeginInvokeOnMainThread(action.Invoke)` on iOS), whereas  `MainThread.BeginInvokeOnMainThread` invokes the action immediately if you are currently on the main thread in [MainThread.shared.cs](https://github.com/xamarin/Essentials/blob/master/Xamarin.Essentials/MainThread/MainThread.shared.cs)

Bug reported at https://github.com/xamarin/Essentials/issues/1070

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 86178166-6c3e-2168-7764-4a4f8573a9c5
* Version Independent ID: dd3987de-9fc6-f84c-c68c-a50c9f6c57f5
* Content: [Xamarin.Essentials: MainThread - Xamarin](https://docs.microsoft.com/en-us/xamarin/essentials/main-thread?content=xamarin%2Fxamarin-forms#feedback)
* Content Source: [docs/essentials/main-thread.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/essentials/main-thread.md)
* Product: **xamarin**
* Technology: **xamarin-essentials**
* GitHub Login: @jamesmontemagno
* Microsoft Alias: **jamont**

**Comment by jamesmontemagno** [comment]
Ah, yeah, we should just document that they are different here. They are similar, but we do a check for mainthread, which we like :)
