### ISSUE TITLE
Apostrophe usage

### ISSUE THREAD

**Issue by geoffmayo** [MicrosoftDocs/xamarin-docs#2509]
"with it's Text property"
"before it's Text property"
Neither need an apostrophe.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 395aebc1-0ae5-399c-373a-f9ca77645a51
* Version Independent ID: 99bf0c20-3e8a-2578-1e75-514843e435a0
* Content: [Loading XAML at Runtime in Xamarin.Forms - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/xaml/runtime-load#feedback)
* Content Source: [docs/xamarin-forms/xaml/runtime-load.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/xaml/runtime-load.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Thanks for pointing this out @geoffmayo 

I've fixed it in a PR that will go live later today.
