### ISSUE TITLE
C# How to map an object with a list of another object using Auto Mapper

### ISSUE THREAD

**Issue by Flave1** [MicrosoftDocs/xamarin-docs#2510]
Source 

    public class Post
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int PostId { get; set; }
        public string UserId { get; set; }
        [NotMapped]
        [ForeignKey(nameof(UserId))]
        public ApplicationUser User { get; set; }
        public int CategoryId { get; set; } 
        public DateTime DatePosted { get; set; }
        public DateTime DateUpdated { get; set; }
        public int Status { get; set; }
        public string PostBody { get; set; }
        public string PostTitle { get; set; } 
        public virtual List<Comment> Comments { get; set; }
    }

Destination

       
      public class PostResponse
    {
        public int PostId { get; set; }
        public string UserId { get; set; }
        public string PostBody { get; set; }
        public string PostTitle { get; set; }
        public int CategoryId { get; set; }
        public DateTime DatePosted { get; set; }
        public DateTime DateUpdated { get; set; }
        public int Status { get; set; }
        public  IEnumerable<CommentObj> Comments { get; set; }
    }

**Comment by davidbritch** [comment]
Hi @Flave1 

Any issues in this repo should be about Xamarin documentation. Therefore, I recommend you take a look at the [AutoMapper documentation](https://docs.automapper.org/en/stable/Getting-started.html).
