### ISSUE TITLE
saving the text in the editor to the database

### ISSUE THREAD

**Issue by ozerkon** [MicrosoftDocs/xamarin-docs#2511]
Hi.
I am trying to learn xamarin from Microsoft official documents. There is a point I cannot understand in the process of saving to the database in step 10.
https://docs.microsoft.com/en-us/xamarin/get-started/quickstarts/database?pivots=windows

async void OnSaveButtonClicked(object sender, EventArgs e)
        {
            var note = (Note)BindingContext;
            note.Date = DateTime.UtcNow;
            await App.Database.SaveNoteAsync(note);
            await Navigation.PopAsync();
        }
Here I could not understand how the text in the editor was saved in the "Text" field in the database. "ID" value is increasing automatically, there is no problem in it. We can also add data with the command "note.Date = DateTime.UtcNow;" in the "Date" field, but how we determined which data to write in the "Text" field?

**Comment by davidbritch** [comment]
Hi @ozerkon 

When you navigate from the NotesPage (by selecting a note) to the NoteEntryPage, the BindingContext of the NoteEntryPage is set to the Note object that represents the selected note.

On the NoteEntryPage, the Editor data binds to the Text property of the page's BindingContext (which is the Note object). As the text changes in the Editor, the Text property is automatically updated via the magic of data binding. Therefore, when you tap the Save button the Note object is retrieved from the page's BindingContext, it's Date property is updated, and the entire object (Text + Date) is saved to the database.

So what you need to get a good understanding of is data binding. I wouldn't recommend writing an app without using it. I recommend you read the 5 part [XAML Basics guide](https://docs.microsoft.com/xamarin/xamarin-forms/xaml/xaml-basics/) to learn more. Hope this helps!

**Comment by ozerkon** [comment]
Thank you @davidbritch 
The corresponding code was in the **NoteEnrtyPage.xaml** file. 
`<Editor Placeholder="Enter your note" Text="{Binding Text}" HeightRequest="100" TextChanged="Editor_TextChanged" />`
I was looking in the wrong place.
