### ISSUE TITLE
Topics like this should be cross-referenced from class reference

### ISSUE THREAD

**Issue by SittenSpynne** [MicrosoftDocs/xamarin-docs#2517]
I was looking at ListView's conceptual topic and it told me I might consider CollectionView. When I click that link, it takes me to the class reference for CollectionView.

The class reference is good, but for a quick overview I'd rather end up here, what I call the "conceptual reference". But while this page has many links to the class reference, there are no links from that class reference back to articles like this.

MSDN documentation used to have "See Also" links in the class documentation to help cross-reference this way. I wish Microsoft Docs had that kind of linking.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9de402a5-a78c-3cfe-f9b1-443a3401574b
* Version Independent ID: 4488127d-8fe9-eef6-c665-106b493f93fd
* Content: [Xamarin.Forms CollectionView - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/collectionview/#feedback)
* Content Source: [docs/xamarin-forms/user-interface/collectionview/index.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/collectionview/index.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @SittenSpynne 

In the [ListView doc](https://docs.microsoft.com/xamarin/xamarin-forms/user-interface/listview/) there are two links. The link on the type goes to the API docs, whereas the "For more info" link goes to the conceptual docs. That's the norm throughout the conceptual docs.

Agreed about the links back from the API docs to the conceptual docs. Afraid I can't say more than that.
