### ISSUE TITLE
How is it "decoupling"?

### ISSUE THREAD

**Issue by SittenSpynne** [MicrosoftDocs/xamarin-docs#2520]
If I read this API right, then a subscriber *must* know a list of all TSender types that will send the message. I *could* break that coupling by using an interface type for "all things that send this message", but wouldn't it be easier to just omit the TSender parameters and accept that subscribers generally shouldn't want to or need to know who is sending the message?

By the time I add a new interface that my subscriber is aware of, I could've just used DI or some other mechanism to inject the subscriber into the publisher. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4d80a771-2198-328b-b9fa-fe25f16261cd
* Version Independent ID: be0408fe-d00b-baf6-8a9c-e24659029c4b
* Content: [Xamarin.Forms MessagingCenter - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/messaging-center#feedback)
* Content Source: [docs/xamarin-forms/app-fundamentals/messaging-center.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/app-fundamentals/messaging-center.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @SittenSpynne 

Yes, you are correct. Using `MessagingCenter` is a choice. It is by no means perfect, and there are alternative/better solutions out there.
