### ISSUE TITLE
UI testing when app requires OAuth2 login

### ISSUE THREAD

**Issue by jbachelor** [MicrosoftDocs/xamarin-docs#2522]
## Handling OAuth2 Google Login in Xamarin UI Tests?
It would be fantastic if this page included a 'Related Link' to help developers implement UI tests that successfully can login to an app, even when an oauth2 identity provider login (with Google, for instance) is required.

If there is any information on how best to handle this situation, I would greatly  appreciate it. Please let me know if my question needs any sort of clarification.

Thanks so much for your hard work!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aa8bb9e0-5898-0d11-0213-fd4d8c8d0297
* Version Independent ID: 2f46e1f7-164f-2f32-70c0-f28919d16c5c
* Content: [AuthenticateUsers with an Identity Provider - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/data-cloud/authentication/oauth#feedback)
* Content Source: [docs/xamarin-forms/data-cloud/authentication/oauth.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/data-cloud/authentication/oauth.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
It looks like the page on which this issue was opened no longer exists, so I'll close the issue here. In addition, UITest is looked after by the AppCenter team (https://docs.microsoft.com/appcenter/test-cloud/frameworks/uitest/), so the question is best raised there.
