### ISSUE TITLE
UWP Primary items only showing when 3 dots clicked

### ISSUE THREAD

**Issue by SmartmanApps** [MicrosoftDocs/xamarin-docs#2523]
Not sure if my UWP isn't performing correctly (a bug or an incorrect setting perhaps?), or if the doco is incorrect in this case, but my understanding was that Primary ToolbarItems will always be visible on UWP, which is what I wanted (and is indeed what I'm getting on Android), but what I'm experiencing is they only show up on UWP if you click the 3 dots (in other words, on UWP I have to click the 3 dots regardless of whether it's Primary or Secondary). So which is correct - this page (my app is not performing correctly) or the behaviour I'm getting (page is incorrect)?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 84079a4a-8798-d710-58b4-df1bc3be6058
* Version Independent ID: b12ca022-d891-6e99-2276-058424af27c5
* Content: [Xamarin.Forms ToolbarItem - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/toolbaritem)
* Content Source: [docs/xamarin-forms/user-interface/toolbaritem.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/toolbaritem.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @profexorgeek
* Microsoft Alias: **jusjohns**

**Comment by davidbritch** [comment]
Hi @SmartmanApps 

I just tried the sample associated with the doc, and the doc is correct. Primary `ToolBarItem` objects appear in the main nav bar. However, you'll only see them if they have an icon. Seeing their text requires clicking the three dots.
