### ISSUE TITLE
Intel HAXM vs. Hyper-V - Which should 

### ISSUE THREAD

**Issue by sp4rc** [MicrosoftDocs/xamarin-docs#2529]
I am trying to setup hardware acceleration for my xamarin project using Visual Studio 2019. I am having an Intel CPU that would both support the HAXM and Hyper-V path. Now I am puzzled about this line within the documentation: 

> For the best experience on Windows, it is recommended that you use HAXM to accelerate the Android emulator. 

Why does Microsoft vote for HAXM over there own Hyper-V? Which route should I take when having the choice and why? TIA

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4e37d642-2051-8d70-9968-dfb484122a6a
* Version Independent ID: 178ea80c-2b99-0c44-eeb6-9db319439b33
* Content: [Hardware Acceleration for Emulator Performance (Hyper-V & HAXM) - Xamarin](https://docs.microsoft.com/en-us/xamarin/android/get-started/installation/android-emulator/hardware-acceleration?pivots=windows#feedback)
* Content Source: [docs/android/get-started/installation/android-emulator/hardware-acceleration.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/android/get-started/installation/android-emulator/hardware-acceleration.md)
* Product: **xamarin**
* Technology: **xamarin-android**
* GitHub Login: @davidortinau
* Microsoft Alias: **daortin**

**Comment by JonDouglas** [comment]
@sp4rc We changed this guidance last year when there were a number of reliability issues with the Hyper-V powered emulator. Those are since resolved and I'll revert the guidance given it's the most compatible way forward.

Thank you for opening the issue!
