### ISSUE TITLE
Dead link

### ISSUE THREAD

**Issue by Krumelur** [MicrosoftDocs/xamarin-docs#253]
Hi, the link to the source on Github is dead. "Sms source code" is pointing to https://github.com/xamarin/Essentials/tree/master/Essentials/Sms

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1b80826a-6389-7b3b-9c60-0682f735e7d2
* Version Independent ID: 0987fc15-6ca4-faf3-56af-85f0bb22b92c
* Content: [Xamarin.Essentials SMS - Xamarin](https://docs.microsoft.com/en-gb/xamarin/essentials/sms?context=xamarin/xamarin-forms)
* Content Source: [docs/essentials/sms.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/essentials/sms.md)
* Service: **xamarin**
* GitHub Login: @jamesmontemagno
* Microsoft Alias: **jamont**

**Comment by bradumbaugh** [comment]
Thanks @Krumelur - fixed in https://github.com/MicrosoftDocs/xamarin-docs/pull/252.
