### ISSUE TITLE
dimensions of boxes in corners

### ISSUE THREAD

**Issue by ozerkon** [MicrosoftDocs/xamarin-docs#2532]
The dimensions of the red box in the middle and the blue rectangular box positioned relative to it are clearly defined.  
For the large red rectangle, relative width and height values have been defined according to the screen size
RelativeLayout.WidthConstraint=
                     "{ConstraintExpression Type=RelativeToParent,
                                            Property=Width,
                                            Factor=0.33}"
                 RelativeLayout.HeightConstraint=
                     "{ConstraintExpression Type=RelativeToParent,
                                            Property=Height,
                                            Factor=0.33}" 

and for the small blue rectangle that appears to be inside the large red rectangle, relative width and height values have been defined according to the dimensions of the large red box.

RelativeLayout.WidthConstraint=
                     "{ConstraintExpression Type=RelativeToView,
                                            ElementName=oneThird,
                                            Property=Width,
                                            Factor=0.33}"
                 RelativeLayout.HeightConstraint=
                     "{ConstraintExpression Type=RelativeToView,
                                            ElementName=oneThird,
                                            Property=Height,
                                            Factor=0.33}" 

But I couldn't see a description of the dimensions of the boxes in the corners. Does it have a default value or is there a definition that I cannot see?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 673a2420-3d41-aa5d-a8e4-3383cf10da6e
* Version Independent ID: ecdf7b35-97d1-524d-d448-9b7865b5b66a
* Content: [Part 3. XAML Markup Extensions - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/xaml/xaml-basics/xaml-markup-extensions)
* Content Source: [docs/xamarin-forms/xaml/xaml-basics/xaml-markup-extensions.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/xaml/xaml-basics/xaml-markup-extensions.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @ozerkon 

Sorry for the confusion. `BoxView` objects have a default size of 40x40 (see the source code at https://github.com/xamarin/Xamarin.Forms/blob/master/Xamarin.Forms.Core/BoxView.cs#L40). That explains the size of the corner items.

**Comment by ozerkon** [comment]
I have not been able to deal with Xamarin because my computer has been out of order for a while. 

So I'm late to thank. 

Thank you for the answer, there is another question that is stuck in my head right now.
