### ISSUE TITLE
Descriptions of Tall and Wide SpanMode mixed up?

### ISSUE THREAD

**Issue by BurningLights** [MicrosoftDocs/xamarin-docs#2534]
The comments in the sample code indicate that TwoPaneViewMode.Tall indicates landscade and TwoPaneViewMode.Wide indicates portrait. This seems backwards to me, since portrait means something is taller than it is wide and landscape means it is wider than it is tall.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 26999f03-5526-4b26-b0bb-0e2df776cd16
* Version Independent ID: 71a21d8b-c639-caec-7412-64493e528549
* Content: [Xamarin.Forms DualScreenInfo - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/dual-screen/dual-screen-info#feedback)
* Content Source: [docs/xamarin-forms/app-fundamentals/dual-screen/dual-screen-info.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/app-fundamentals/dual-screen/dual-screen-info.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidortinau
* Microsoft Alias: **daortin**

**Comment by davidbritch** [comment]
Hi @BurningLights 

It's natural to think that landscape is wide and portrait is tall. But that idea changes when you have double portrait or double landscape. So the wording in the doc is correct.

With that said, it may be possible to make this clearer. I'll leave this issue open until this is done.

**Comment by BurningLights** [comment]
Oh, okay, I understand now. I was thinking in terms of the two screens together, not the individual screens. I do think it would help to clarify that the comments are referring to each individual screens being in portrait or landscape, and not the device as a whole.

**Comment by davidbritch** [comment]
I've just updated the doc in a PR that will go live later today.
