### ISSUE TITLE
XAML Hot Relead for Xamarin still not working in 16.4.5 when open from VS

### ISSUE THREAD

**Issue by cacafaca** [MicrosoftDocs/xamarin-docs#2536]
Hi all,

Workaround works. That is, if I open solution with double click Hot Reload Works. But, if I open solution within Visual Studio, nothing happens when I save XAML file.

Regards,
Nemanja

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b74184fd-ca8a-11fa-ed37-91235fc59401
* Version Independent ID: 87f197b8-20c6-4825-18e4-86562bb2523c
* Content: [XAML Hot Reload for Xamarin.Forms - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/xaml/hot-reload#feedback)
* Content Source: [docs/xamarin-forms/xaml/hot-reload.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/xaml/hot-reload.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @maddyleger1
* Microsoft Alias: **maleger**

**Comment by Boukri** [comment]
Hello,
I'm currently using visual studio 2019 version 16.6 and i did all necessary configuration, then when i save the XAML file nothing happens.

**Comment by maddyleger1** [comment]
> Hello,
> I'm currently using visual studio 2019 version 16.6 and i did all necessary configuration, then when i save the XAML file nothing happens.

Hi @Boukri - please go to Help > Send Feedback > Report a Problem and file a bug there, that way our engineering team can take a look. Thanks!
