### ISSUE TITLE
Context Menu Actions in a ListView

### ISSUE THREAD

**Issue by tchadwick** [MicrosoftDocs/xamarin-docs#2539]
This document is incorrect as Context Menu Actions don't work in a ListView on Android for the last 2 years: https://github.com/xamarin/Xamarin.Forms/issues/2180

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1b0eed28-8065-951a-1b3f-325c59414a7c
* Version Independent ID: eac566b7-faba-2bea-f9c4-bdadff5169f6
* Content: [ListView Interactivity - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/listview/interactivity#feedback)
* Content Source: [docs/xamarin-forms/user-interface/listview/interactivity.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/listview/interactivity.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @tchadwick 

I just tried the sample associated with the doc, and context menu actions in a ListView on Android worked just fine.

**Comment by tchadwick** [comment]
Hello @davidbritch, Thank you for the swift response, the context menu works, but the select event/selected item binding (both) on the listview stops working, this makes the listview near useless for 95% of use-cases.

**Comment by davidbritch** [comment]
@tchadwick 

I'm struggling to repo this. I tried [this sample](https://docs.microsoft.com/samples/xamarin/xamarin-forms-samples/userinterface-listview-interactivity/) and was able to use context menu items, and the selected event still fired afterwards.
