### ISSUE TITLE
Debugging

### ISSUE THREAD

**Issue by dpaustin** [MicrosoftDocs/xamarin-docs#254]
Please add content to describe how debugging works through the Pair to Mac options works.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 98c96bcc-1743-8d9f-f1b2-3c30d5b2a6e2
* Version Independent ID: f57a6157-332a-3f31-c785-7efa99e62711
* Content: [Pair to Mac - Xamarin](https://docs.microsoft.com/en-us/xamarin/ios/get-started/installation/windows/connecting-to-mac/)
* Content Source: [docs/ios/get-started/installation/windows/connecting-to-mac/index.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/ios/get-started/installation/windows/connecting-to-mac/index.md)
* Service: **xamarin**
* GitHub Login: @bradumbaugh
* Microsoft Alias: **brumbaug**

**Comment by bradumbaugh** [comment]
Hi @dpaustin, there are a couple of other docs already in place that you may find useful:

- https://docs.microsoft.com/xamarin/ios/deploy-test/debugging-in-xamarin-ios
- https://docs.microsoft.com/xamarin/tools/ios-simulator

I've just updated the second doc a bit, and I'll add a link to it in the Pair to Mac guide. Both updates should be published soon.

Thanks for the suggestion!

**Comment by dpaustin** [comment]
Great, thanks for additional guidance Brad.  Cross-linking helps a lot when
you're cross-eyed looking for info.

Sincerely,

David Austin
817-372-5647 mobile

**Comment by dpaustin** [comment]
Also, some additional information about debugging on the device itself
would help.  As i'm new to Xamarin, digesting the debugging scenarios is
challenging.  I'm working on a camera-heavy app, so I can't test that in
the simulator.  I thought I could plug in an iPhone to the PC and debug,
but as far I can tell, I have to plug it into the Mac.  It took an hour of
research to figure this out.  Thanks.

Sincerely,

David Austin
817-372-5647 mobile

**Comment by bradumbaugh** [comment]
Hi @dpaustin - thanks for the feedback, I appreciate it. 

I'll add a note to our backlog to review the debugging-on-device docs in general.

Another good resource that I should have mentioned above: the [Wireless Deployment guide](https://docs.microsoft.com/xamarin/ios/deploy-test/wireless-deployment?tabs=vsmac). I'll add a link to this doc in the Pair to Mac guide.

Thanks again!
