### ISSUE TITLE
Problem with ItemsSourceBy usage in IndicatorView example

### ISSUE THREAD

**Issue by okproject** [MicrosoftDocs/xamarin-docs#2542]
Hi.
The example shared about  IndicatorView  contains that info:
IndicatorView ItemsSourceBy="..."

But visual studio  gives error with this usage; live reload does not work properly with this case.
Instead
IndicatorView  IndicatorView.ItemsSourceBy="..."

works well. It needs the class name as prefix before itemsSourceBy property.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 964bba3d-71b4-c30b-de73-8c2f0864a7df
* Version Independent ID: d735dc5e-8c87-ffef-c07b-51a991e4327a
* Content: [Xamarin.Forms IndicatorView - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/indicatorview)
* Content Source: [docs/xamarin-forms/user-interface/indicatorview.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/indicatorview.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @okproject 

Thanks for pointing this out. I missed that `ItemsSourceBy` is an attached property. I've updated the samples, and have updated the docs in a PR that will go live later today.

**Comment by TouchBoarder** [comment]
Looks like the  IndicatorView.ItemsSourceBy has been removed in Xamarin.Forms 4.5 https://docs.microsoft.com/en-us/xamarin/xamarin-forms/release-notes/4.5/4.5.0#type-changed-xamarinformsindicatorview

You now need to set the IndicatorView property on the CarouselView instead:
https://github.com/xamarin/Xamarin.Forms/pull/9332

Example:
<IndicatorView x:Name="indicatorView"/>
<CarouselView x:Name="carouselView" IndicatorView="indicatorView"/>

**Comment by davidbritch** [comment]
Hi @TouchBoarder 

Thanks for pointing this out. I've updated the samples to use this new syntax, as part of their mass update to 4.5. Doc updates to follow today/tomorrow.

**Comment by miote** [comment]
In Version Xamarin.Forms 4.5.0.356 IndicatorView marks error:
Exception has been thrown by the target of an invocation

**Comment by davidbritch** [comment]
Hi @miote 

The API has changed in v4.5. See the [doc](https://docs.microsoft.com/xamarin/xamarin-forms/user-interface/indicatorview) for the new API.
