### ISSUE TITLE
Interesting...

### ISSUE THREAD

**Issue by BigPaul** [MicrosoftDocs/xamarin-docs#2545]
...but of any practical use to developers? I came here hoping to find advice on creating a Xamarin.Forms splash screen.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a5a4e93b-006f-176e-cf02-108f48bff807
* Version Independent ID: 2d677054-ae70-1eb1-903d-70b4f6cdfc50
* Content: [Xamarin.Forms splash screen - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/splashscreen)
* Content Source: [docs/xamarin-forms/user-interface/splashscreen.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/splashscreen.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @profexorgeek
* Microsoft Alias: **jusjohns**

**Comment by profexorgeek** [comment]
Hi @BigPaul,
Typically the purpose of a splash screen is to offer users some type of branded experience while the platform operating system (such as Android) loads your application. Once Xamarin.Forms is fully initialized and loads your application, this delay _has already elapsed_. This means that splash screens must be implemented at a lower level so they can show before Xamarin.Forms even starts loading!

So "creating a Xamarin.Forms splash screen" really means creating a native screen that shows while Xamarin.Forms loads your application. This article attempts to introduce that concept and provide links to articles for each platform.
