### ISSUE TITLE
TableLayout Example does not compile

### ISSUE THREAD

**Issue by scarabdesign** [MicrosoftDocs/xamarin-docs#2548]
The example on this page when used in code won't allow you to build because of missing attributes on all subviews:
- Missing attribute: layout_width
- Missing attribute: layout_height

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 49589ded-ff45-091e-a6d0-fb3d3ebb7d68
* Version Independent ID: 5e122705-dd38-8bb3-88c1-9d960fdfc3e7
* Content: [Xamarin.Android TableLayout - Xamarin](https://docs.microsoft.com/en-us/xamarin/android/user-interface/layouts/table-layout#feedback)
* Content Source: [docs/android/user-interface/layouts/table-layout.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/android/user-interface/layouts/table-layout.md)
* Product: **xamarin**
* Technology: **xamarin-android**
* GitHub Login: @davidortinau
* Microsoft Alias: **daortin**

**Comment by JayD2019** [comment]
I have the same issue. Also , in VS2019 the Table Layout dragged from the Toolbox brings up the same errors. In the XML pane, the TableRow Element is highlighted as error
Please fix. I need this ASAP.

**Comment by PanuLappalainen** [comment]
Does anyone have solution for this yet?
For me it compiles, but I get the same errors as @scarabdesign
