### ISSUE TITLE
dosen't discuss problem when Xcode not installed in Path : \Application\Xcode.app

### ISSUE THREAD

**Issue by scarrier92** [MicrosoftDocs/xamarin-docs#2554]
dosen't discuss problem when Xcode not installed in Path : \Application\Xcode.app  The path can be changend in settings when this is the case

**Comment by davidortinau** [comment]
@scarrier92 could you please post a link to the doc you're referring to?

**Comment by PureWeen** [comment]
Thank you for the report @scarrier92, but we're going to close this for now since we haven't heard from you yet.

If you can answer @davidortinau's question then we'll re-open
