### ISSUE TITLE
Java.Lang.IllegalArgumentException: View=DecorView@842599d[AppleSignInCallbackActivity] not attached to window manager

### ISSUE THREAD

**Issue by microwales** [MicrosoftDocs/xamarin-docs#2556]
I am getting this error after completing the Callback Flow and back in the main app. Any idea?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: baaa38ab-77e3-83b2-492c-86e1051862c3
* Version Independent ID: 4194e7df-a3fc-fc87-9d7c-c008d1aa6eb2
* Content: [Sign In with Apple in Xamarin.Forms - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/platform/sign-in-with-apple/)
* Content Source: [docs/xamarin-forms/platform/sign-in-with-apple/index.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/platform/sign-in-with-apple/index.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidortinau
* Microsoft Alias: **daortin**

**Comment by davidbritch** [comment]
Hi @microwales 

This is normally caused by trying to dismiss a dialog/activity that has already been dismissed, or trying to do so off the UI thread.
