### ISSUE TITLE
Code in MainPage.xaml.cs incorrect

### ISSUE THREAD

**Issue by rjwhitlock** [MicrosoftDocs/xamarin-docs#2557]
Code should be:

    public partial class MainPage : ContentPage
    {
        string _fileName = Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData), "notes.txt");
        public MainPage()
        {

            InitializeComponent();

            if (!File.Exists(_fileName))
            {
                return;
            }
            editor.Text = File.ReadAllText(_fileName);

        }
        void OnSaveButtonClicked(object sender, EventArgs e)
        {
            File.WriteAllText(_fileName, editor.Text);
        }

        void OnDeleteButtonClicked(object sender, EventArgs e)
        {
            if (File.Exists(_fileName))
            {
                File.Delete(_fileName);
            }
            editor.Text = string.Empty;
        }

    }
}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5a064123-54f2-0eb2-c76a-65b36c5ec1a7
* Version Independent ID: dbf4119a-2c24-e0f1-8041-bb3755c29c24
* Content: [Create a single page Xamarin.Forms application - Xamarin](https://docs.microsoft.com/en-us/xamarin/get-started/quickstarts/single-page?pivots=windows#feedback)
* Content Source: [docs/get-started/quickstarts/single-page.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/get-started/quickstarts/single-page.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @rjwhitlock 

The change you've made adds one line of code to the existing code, without changing the logic.

**Comment by rjwhitlock** [comment]
Yeah I realized that just after I posted and couldn't delete it


Randy Whitlock

**Comment by davidbritch** [comment]
@rjwhitlock 

No worries :)
