### ISSUE TITLE
Search not working for top tabs

### ISSUE THREAD

**Issue by vkroust** [MicrosoftDocs/xamarin-docs#2558]
Search handler does not get updated when navigating from one top tab to another, so it works only for the first top tab.
I tested in both in Xaminals and my own project. 
I noticed that when you navigate from a bottom tab of a fly out item to another, search handler gets updated and works.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ea22bfa0-1713-6aff-9c8c-dedf47bb3381
* Version Independent ID: f9b7e5be-4b5a-c292-c425-89125369b97b
* Content: [Xamarin.Forms Shell Search - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/shell/search#feedback)
* Content Source: [docs/xamarin-forms/app-fundamentals/shell/search.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/app-fundamentals/shell/search.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @vkroust 

Thanks for raising this issue. However, it really needs opening in the [engineering repo](https://github.com/xamarin/Xamarin.Forms). Therefore, I'll close it here.
