### ISSUE TITLE
Bind to an Ancestor with Prism

### ISSUE THREAD

**Issue by HelenMamalaki** [MicrosoftDocs/xamarin-docs#2560]
People using Prism do not define BindingContext in code behind and Prism documentation doesn't cover how to bind to an Ancestor. Can the docs cover this here?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3f73553f-8c35-877b-0a34-db9b51df93be
* Version Independent ID: d51b2ace-0519-6309-7417-d29a582a4de2
* Content: [Xamarin.Forms Relative Bindings - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/data-binding/relative-bindings#feedback)
* Content Source: [docs/xamarin-forms/app-fundamentals/data-binding/relative-bindings.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/app-fundamentals/data-binding/relative-bindings.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @HelenMamalaki 

We aren't going to add any Prism specific docs, as if we do that we'd then have to add them for every other popular MVVM framework.

With that said, is your issue that you want to know how to set the `BindingContext` in XAML?
