### ISSUE TITLE
WPF

### ISSUE THREAD

**Issue by culigan** [MicrosoftDocs/xamarin-docs#2561]
I am trying to implement a webviewrenderer with a wpf project that is within a cross-platform application. Do you have an example or know how this can be accomplished?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9c1bd30c-6e7a-df38-8c20-dff7361e901f
* Version Independent ID: 013c6027-db9a-6039-3404-2e4f717133a9
* Content: [Customizing a WebView - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/custom-renderer/hybridwebview#feedback)
* Content Source: [docs/xamarin-forms/app-fundamentals/custom-renderer/hybridwebview.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/app-fundamentals/custom-renderer/hybridwebview.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @culigan 

Afraid we don't have an example. WPF support in Xamarin.Forms is a community project.

Looking at the [source code](https://github.com/xamarin/Xamarin.Forms/blob/master/Xamarin.Forms.Platform.WPF/Renderers/WebViewRenderer.cs) it should be no different to creating a WebView renderer on the mobile platforms.
