### ISSUE TITLE
Why not still reload on Vs2019 16.4 also if enabled?

### ISSUE THREAD

**Issue by biapar** [MicrosoftDocs/xamarin-docs#2568]
Why not still reload on Vs2019 16.4 also if enabled?

**Comment by davehump** [comment]
@biapar  Could you please confirm that is an issue with Hot Reload not working in VS2019 16.4, even though its enabled?  Is this an issue with the documentation?

**Comment by davehump** [comment]
@biapar this looks like an issue with the Hot reload functionality in Visual studio and not a documentation issue.  

You can search and log issues relating to visual studio and hot reload on the Developer community site,  https://developercommunity.visualstudio.com.
