### ISSUE TITLE
Setting Flyout Icon with a fontimagesource doesnt work on UWP

### ISSUE THREAD

**Issue by abrantie1z** [MicrosoftDocs/xamarin-docs#2569]
i tried setting the flyout icon with a fontimagesource, it works on android, but not on uwp.

**Comment by davidbritch** [comment]
Hi @abrantie1z 

Shell support on UWP is still in a preview, and lacks much of the functionality. When UWP support is finished we'll be sure to publicise that.

**Comment by abrantie1z** [comment]
Alright sir
