### ISSUE TITLE
Using pop-up from ViewModel

### ISSUE THREAD

**Issue by domagojmedo** [MicrosoftDocs/xamarin-docs#2571]
It would be good to show samples of usage from ViewModel 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3c6e0bb1-26e4-091b-8a99-27d772bed7f6
* Version Independent ID: 57d8ad92-0aa2-9ec4-47bc-8853d9a71d91
* Content: [Display Pop-ups - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/pop-ups)
* Content Source: [docs/xamarin-forms/user-interface/pop-ups.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/pop-ups.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @domagojmedo 

We traditionally don't show usage with MVVM, as it's a minefield depending on how purist a view of MVVM you have.

There are a number of approaches that could be used here (depending on your view on MVVM purity).

The simplest approach is to do something like the following, in your view model:

```
Application.Current.MainPage.DisplayAlert("Alert", "Hello", "Cancel", "ok")
```

Another option is to use MessagingCenter to send a message from the view model to a page that then calls DisplayAlert.

MVVM purists would tend to go for some kind of DialogService, such as the following one included in Prism: https://github.com/PrismLibrary/Prism/blob/master/Source/Xamarin/Prism.Forms/Services/PageDialogService/PageDialogService.cs
