### ISSUE TITLE
Browser Closing Issue in Android, and Loading a Page Prior to Auth

### ISSUE THREAD

**Issue by nosmalldreams** [MicrosoftDocs/xamarin-docs#2573]
There is a bug that prevents the browser from closing in Android after authentication is complete. It's documented here - https://github.com/xamarin/Xamarin.Auth/issues/226. That link also includes workaround code to get the browser to close. This is critical to making the above documented solution work.

Also, I found that if I did not load any view prior to running the auth code, I got an ArgumentOutOfRange... Parameter name: index message when I then tried to load a page in the OnAuthCompleted method. Pushing a simple blank page just before invoking the presenter.Login call fixed that for me (e.g. making this call: await this.Navigation.PushModalAsync(new NavigationPage(new BlankPage()));)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aa8bb9e0-5898-0d11-0213-fd4d8c8d0297
* Version Independent ID: 2f46e1f7-164f-2f32-70c0-f28919d16c5c
* Content: [AuthenticateUsers with an Identity Provider - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/data-cloud/authentication/oauth#feedback)
* Content Source: [docs/xamarin-forms/data-cloud/authentication/oauth.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/data-cloud/authentication/oauth.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @nosmalldreams 

Afraid this doc won't be getting updated, as Xamarin.Auth will shortly be replaced with something else. Thanks for the suggestion though!

**Comment by jeyoor** [comment]
@davidbritch ,
Can you provide more detail or guidance on what the replacement for Xamarin.Auth should be?
I'm pushing my team to integrate Xamarin.Auth right now in an urgent project; I am highly interested in what the future of the library will be.
Thank you,
Jeyan
