### ISSUE TITLE
Implicit vs AuthorizationCode Flow

### ISSUE THREAD

**Issue by nosmalldreams** [MicrosoftDocs/xamarin-docs#2574]
I think it bears mentioning that this supports an Implicit flow by which the authentication token is passed to the client directly, and that, in the case of an application that has both mobile and server side components, a more secure option is to use an Authorization Code flow in which the Authorization Code is retrieved by the client and then passed to the server, and the authentication token is retrieved server-side, potentially using a client-secret for additional security. It seems like Xamarin.Auth does not support a flow returning an Authorization Code, but I would love to see that question answered explicitly in this text. Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aa8bb9e0-5898-0d11-0213-fd4d8c8d0297
* Version Independent ID: 2f46e1f7-164f-2f32-70c0-f28919d16c5c
* Content: [AuthenticateUsers with an Identity Provider - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/data-cloud/authentication/oauth)
* Content Source: [docs/xamarin-forms/data-cloud/authentication/oauth.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/data-cloud/authentication/oauth.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @nosmalldreams 

Afraid this doc won't be getting updated, as Xamarin.Auth will shortly be replaced with something else. Thanks for the suggestion though!
