### ISSUE TITLE
AndroidManifest error

### ISSUE THREAD

**Issue by parejajd** [MicrosoftDocs/xamarin-docs#2578]
In the Map Initialization process, this page specified that AndroidManifest configuration must be set in com.google.android.maps.v2.API_KEY , this configuration generate error. 

However Google docs https://developers.google.com/maps/documentation/android-sdk/get-api-key specified the com.google.android.geo.API_KEY must be used

&lt;meta-data
     android:name="com.google.android.geo.API_KEY"
     android:value="YOUR-API-KEY" /&gt;

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2a251251-3037-b49f-de79-f820b469321d
* Version Independent ID: 4af74db2-b248-3a02-bf38-0b76ede42ef6
* Content: [Xamarin.Forms Map Initialization and Configuration - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/map/setup#feedback)
* Content Source: [docs/xamarin-forms/user-interface/map/setup.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/map/setup.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @parejajd 

I tried the com.google.android.maps.v2.API_KEY and it worked fine for me. However, a quick read of Google's docs say that com.google.android.geo.API_KEY is the new recommended key, with com.google.android.maps.v2.API_KEY being for backwards compatibility.

Therefore I'll update the doc/sample to use com.google.android.geo.API_KEY. Thanks for pointing this out.

**Comment by davidbritch** [comment]
I've updated this in a PR that will go live later today.
