### ISSUE TITLE
CommonStates inconsistency

### ISSUE THREAD

**Issue by viktorszekeress** [MicrosoftDocs/xamarin-docs#2579]
In the https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/visual-state-manager#visual-states-in-xamarinforms table, 4 states are listed for VisualElement.
In the https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/visual-state-manager#define-your-own-visual-states, 3 states mentioned.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b744a13f-16ad-4f35-cdf2-bdfd6fa90df1
* Version Independent ID: 7a08549b-07a5-085b-0c93-255d9e84d7a3
* Content: [Xamarin.Forms Visual State Manager - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/visual-state-manager#visual-states-in-xamarinforms)
* Content Source: [docs/xamarin-forms/user-interface/visual-state-manager.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/visual-state-manager.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @viktorszekeress 

Thanks for pointing this out. I'll get it fixed today. Four states is correct, as the CommonStates have gained a Selected state (moved from CollectionView).

**Comment by davidbritch** [comment]
I've fixed this in a PR that will go live later today.
