### ISSUE TITLE
NavBarHasShadow default is wrong

### ISSUE THREAD

**Issue by irongut** [MicrosoftDocs/xamarin-docs#2580]
The "Enable navigation bar shadow" section states that the default value of the NavBarHasShadow property is false. But this is wrong, the default is true.

When I don't set this property my pages have a drop shadow on the nav bar. When I set it to false they don't have that shadow.

Xamarin Forms v4.5.0.356

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c9d653fd-51ed-ed03-db65-a9efb684dc12
* Version Independent ID: 06470094-10f9-b28e-4ece-4da457a4a609
* Content: [Xamarin.Forms Shell Page Configuration - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/shell/configuration)
* Content Source: [docs/xamarin-forms/app-fundamentals/shell/configuration.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/app-fundamentals/shell/configuration.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @irongut 

The `NavBarHasShadow` bindable property has a default value of `false`:

```
		public static readonly BindableProperty NavBarHasShadowProperty =
			BindableProperty.CreateAttached("NavBarHasShadow", typeof(bool), typeof(Shell), default(bool),
```

However, something else might be going on here. I'll speak to one of the engineers.

**Comment by irongut** [comment]
If it helps you can see the app I was working on here:  [irongut/XF40Demo](https://github.com/irongut/XF40Demo)
The page in question is: [StandingsPage.xaml](https://github.com/irongut/XF40Demo/blob/master/XF40Demo/XF40Demo/Views/StandingsPage.xaml)

This page has a nav bar shadow unless I set: `Shell.NavBarHasShadow="False"`

**Comment by davidbritch** [comment]
Hi @irongut 

It turns out that by default the property is `false` on iOS, but `true` on Android. I've updated the doc in a PR that will go live soon.
