### ISSUE TITLE
not available

### ISSUE THREAD

**Issue by sjorsmiltenburg** [MicrosoftDocs/xamarin-docs#2581]
Hi, I upgraded to xamarin.forms 4.5.0.356 and tried to use the code mentioned above but I get the error "XLS0415	The attachable property 'ImageDirectory' was not found in type 'Application'." The sample project referenced also does not contain a reference to 'ImageDirectory' and adding the code in the sample project also does not build for me. I am using Visual Studio Version 16.4.5.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 090e1d14-ea30-053f-709a-790ffe43efaa
* Version Independent ID: 316707a6-75e2-ac59-3efa-9311aeb4269d
* Content: [Default image directory on Windows - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/platform/windows/default-image-directory)
* Content Source: [docs/xamarin-forms/platform/windows/default-image-directory.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/platform/windows/default-image-directory.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by sjorsmiltenburg** [comment]
hmm I don't know what I did, (because I already restarted VS, rebootted my pc, cleaned my solution and delted the bin/obj dirs from my uwp project) but now it compiles.

**Comment by davidbritch** [comment]
Hi @sjorsmiltenburg 

Glad you're sorted. It was most likely deleting the bin/obj dirs that did it.
