### ISSUE TITLE
The convert method requires four parameters to work, but we sent one!

### ISSUE THREAD

**Issue by ozerkon** [MicrosoftDocs/xamarin-docs#2583]
Here is the convert method:
public object Convert(object value, Type targetType, object parameter, CultureInfo culture)
        {
            double multiplier;
            if (!Double.TryParse(parameter as string, out multiplier))
                multiplier = 1;
            return (int)Math.Round(multiplier * (double)value);
        }
 And XAML code here:
&lt;Label Text="{Binding Color.R,
                      Converter={StaticResource intConverter},
                      ConverterParameter=255,
                      StringFormat='R={0:X2}'}" /&gt;

It looks like we just sent "255" to this method.  As I understand it, the Color.R value for "object value" is sent automatically. 

It looks like we haven't posted anything for "type targetType". Since The Label view works with string values, I assume that the "Type targetType" parameter is also sent automatically. 

What about "CultureInfo culture"? 

To be honest, I could not fully understand how we used this method.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 969d1fbd-aeab-0c4f-8e1b-f7f3c139fd78
* Version Independent ID: 6ea369b2-0654-27ac-5911-aaf77e1c1495
* Content: [Part 4. Data Binding Basics - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/xaml/xaml-basics/data-binding-basics#feedback)
* Content Source: [docs/xamarin-forms/xaml/xaml-basics/data-binding-basics.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/xaml/xaml-basics/data-binding-basics.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @ozerkon 

The XAML basics guide only explores the basic of data binding. There's a full data binding guide [here](https://docs.microsoft.com/xamarin/xamarin-forms/app-fundamentals/data-binding/), with a page on value converters.

When using a converter in XAML, Xamarin.Forms automatically ensures that the parameters to the `Convert` method are populated:

- The `value` parameter is the object or value from the data binding source.
- The `targetType` parameter is the type of the data binding target (and is the expected type of the method's return value).
- The `parameter` parameter is the value of the `ConverterParameter` property.
- The `culture` parameter is a `CultureInfo` object. In Xamarin.Forms, this will always be the value of `CultureInfo.CurrentUICulture` (essentially the locale of the device the app is running on). This enables you to perform culture-specific conversions, if required.

Hope this helps!

**Comment by ozerkon** [comment]
Hi @davidbritch 
Thank you for the quick response. 
My estimates for "value", "targetType", and "parameter" (there was no problem with this anyway) were correct. 
 My confusion about the "culture" parameter has now been resolved. 

Thanks to you my determination to learn is increasing.
