### ISSUE TITLE
Grid example error

### ISSUE THREAD

**Issue by MykhayloMike** [MicrosoftDocs/xamarin-docs#2584]
Grid example is erroring. It is because label has a width property that is read-only. My guess is because ColumnDefinition already defines width as Auto. Need to remove "Width="200"" from Grid example

&lt;Grid&gt;
    &lt;Grid.RowDefinitions&gt;
        &lt;RowDefinition Height="50" /&gt;
        &lt;RowDefinition Height="50" /&gt;
    &lt;/Grid.RowDefinitions&gt;
    &lt;Grid.ColumnDefinitions&gt;
        &lt;ColumnDefinition Width="Auto" /&gt;
        &lt;ColumnDefinition /&gt;
    &lt;/Grid.ColumnDefinitions&gt;    
    &lt;Label Text="Column 0, Row 0"
           Width="200" /&gt;
    &lt;Label Grid.Column="1"
           Text="Column 1, Row 0" /&gt;
    &lt;Label Grid.Row="1"
           Text="Column 0, Row 1" /&gt;
    &lt;Label Grid.Column="1"
           Grid.Row="1"
           Text="Column 1, Row 1" /&gt;
&lt;/Grid&gt;

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f5bd8beb-52ef-9e33-4453-4fea779b6342
* Version Independent ID: d4a85f7a-fe87-1850-854d-db2114a01555
* Content: [Choose a Xamarin.Forms Layout - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/layouts/choose-layout#feedback)
* Content Source: [docs/xamarin-forms/user-interface/layouts/choose-layout.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/layouts/choose-layout.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @MykhayloMike 

Thanks for pointing this out. It should have been `WidthRequest` rather than `Width`. I've fixed this in a PR that will go live in the next hour.
