### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by DickBaker** [MicrosoftDocs/xamarin-docs#259]
For "flowing" read "following"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 07cbe485-3d3b-c8e0-410e-3d04e1beb269
* Version Independent ID: ec2a19ac-ce29-8644-70c1-4a3becb5cda4
* Content: [Live Player for Xamarin.Forms - Xamarin](https://docs.microsoft.com/en-us/xamarin/tools/live-player/)
* Content Source: [docs/tools/live-player/index.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/tools/live-player/index.md)
* Service: **xamarin**
* GitHub Login: @topgenorth
* Microsoft Alias: **toopge**

**Comment by bradumbaugh** [comment]
Thanks @DickBaker - fix should be published soon. Appreciate the help!
