### ISSUE TITLE
How to get Authenticate Users with an Identity Provider in Xmarine.Android?

### ISSUE THREAD

**Issue by SoumenHalder88** [MicrosoftDocs/xamarin-docs#2593]
I am working the same in Xmarine.Android, where I am not getting the access token, the example is in Xmarin.Forms. How can I get the authentication token in Xmarine.Android?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aa8bb9e0-5898-0d11-0213-fd4d8c8d0297
* Version Independent ID: 2f46e1f7-164f-2f32-70c0-f28919d16c5c
* Content: [AuthenticateUsers with an Identity Provider - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/data-cloud/authentication/oauth#feedback)
* Content Source: [docs/xamarin-forms/data-cloud/authentication/oauth.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/data-cloud/authentication/oauth.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @SoumenHalder88 

The recommended approach is now to use the `WebAuthenticator` class from Xamarin.Essentials. It works for both Xamarin.Forms and Xamarin.Android: https://docs.microsoft.com/en-us/xamarin/essentials/web-authenticator?tabs=android#feedback
