### ISSUE TITLE
Any way the SwipeView could have custom content rather than a bitmap?

### ISSUE THREAD

**Issue by malware-dev** [MicrosoftDocs/xamarin-docs#2594]
We don't use bitmaps in our app, just vector drawings. It would be great if the swipe view was flexible enough to support custom content, otherwise we won't be able to use it and will have to roll our own.

**Comment by davidbritch** [comment]
Hi @malware-dev 

Yes, you can use custom swipe items. See https://docs.microsoft.com/xamarin/xamarin-forms/user-interface/swipeview#custom-swipe-items

**Comment by malware-dev** [comment]
... so in other words, "read the d**n manual"? 😛 

I'm sorry for wasting your time, I completely missed that. Thank you.
