### ISSUE TITLE
Hot restart option disappeared from Preview Features section in Visual Studio 2019 Version 16.5 Preview 5

### ISSUE THREAD

**Issue by astralmaster** [MicrosoftDocs/xamarin-docs#2595]
Title says it all. Is it no longer in Preview features section but enabled globally? I do not see it listed in Tools -> Options -> Xamarin sub-menu.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8f3eb808-8e6d-4e07-fc75-8d79a7249265
* Version Independent ID: dbb2b9a9-87a6-e473-50e6-f88435d49e88
* Content: [Xamarin Hot Restart - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/deploy-test/hot-restart)
* Content Source: [docs/xamarin-forms/deploy-test/hot-restart.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/deploy-test/hot-restart.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @jimmgarrido
* Microsoft Alias: **jigarrid**

**Comment by aherrick** [comment]
I'm also seeing this... how do you enable Hot Restart in Preview 5??

**Comment by maddyleger1** [comment]
Hi everyone! Sorry for the confusion. We found an issue with Hot Restart that we wanted to fix before we get to our stable release and had to turn off the feature for Preview 5. The issue has been fixed and Hot Restart will be available again as a preview feature in Visual Studio 2019 16.5 GA. You can keep your eye out for the release on the [release notes site](https://docs.microsoft.com/en-us/visualstudio/releases/2019/release-notes)

**Comment by astralmaster** [comment]
> Hi everyone! Sorry for the confusion. We found an issue with Hot Restart that we wanted to fix before we get to our stable release and had to turn off the feature for Preview 5. The issue has been fixed and Hot Restart will be available again as a preview feature in Visual Studio 2019 16.5 GA. You can keep your eye out for the release on the [release notes site](https://docs.microsoft.com/en-us/visualstudio/releases/2019/release-notes)

Is the feature present in the yesterdays release of 16.4.6?

**Comment by maddyleger1** [comment]
> > Hi everyone! Sorry for the confusion. We found an issue with Hot Restart that we wanted to fix before we get to our stable release and had to turn off the feature for Preview 5. The issue has been fixed and Hot Restart will be available again as a preview feature in Visual Studio 2019 16.5 GA. You can keep your eye out for the release on the [release notes site](https://docs.microsoft.com/en-us/visualstudio/releases/2019/release-notes)
> 
> Is the feature present in the yesterday's release of 16.4.6?

No, it was first released in 16.5 Preview, so it won't be retrofitted to 16.4.x!
