### ISSUE TITLE
Requirement or Any benefit to define itemssource in Xaml.

### ISSUE THREAD

**Issue by Vespiyanus** [MicrosoftDocs/xamarin-docs#2596]
I am very new in Xamarin and xaml. So it may be simple but I need some explanation.
When I am trying to explore the usage of binding of itemssource for listview, I noticed that if, itemssource is defined in code behind like:
..
public EmployeeListPage()
{
    EmployeeView.ItemsSource = employees;
..

then it seems it is not necessarily require to set it in xaml as well like:
  &lt;ListView x:Name="EmployeeView"
            ItemsSource="{Binding Employees}"&gt;
...
At least, in my case it worked when I remove from xaml. 
However, I tried the other way, (delete from code behind and set it from xaml only) it didnt work. 

can you put some explanation on that?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f9bb8625-60a7-2d18-86aa-501c64a71073
* Version Independent ID: 4891a28f-63b1-dca9-0467-fc81f32363cf
* Content: [ListView Data Sources - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/listview/data-and-databinding#feedback)
* Content Source: [docs/xamarin-forms/user-interface/listview/data-and-databinding.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/listview/data-and-databinding.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @Vespiyanus 

Correct. If you set `ItemsSource` in code-behind, you don't need to set it in XAML. 

To make it work from XAML, the binding needs to know where the `Employees` collection is. This is accomplished by setting the `BindingContext` property to the object that contains the `Employees` collection. Normally this would be done on the page, as the BindingContext property is inherited from its parent (meaning that each object in the page, including the ListView, will inherit it from the ContentPage).

Understanding data binding is the key to XAML development. I recommend you read [Data Binding Basics](https://docs.microsoft.com/xamarin/xamarin-forms/xaml/xaml-basics/data-binding-basics) for an overview, with the full detail at [Data Binding](https://docs.microsoft.com/xamarin/xamarin-forms/app-fundamentals/data-binding/).
