### ISSUE TITLE
ObservableCollection for Itemsource

### ISSUE THREAD

**Issue by Vespiyanus** [MicrosoftDocs/xamarin-docs#2597]
In order to enable Listview to be updated whenever there is a change, ObservableCollection should be used as source. It is quite clear and well explained. 
However, this works only  when there is internal changes on the Observablecollection which is bound to the Listview.  If it is assigned to a new ObservableCollection instance as illustrated below, there will be no update on listview as there is no collection change event fired from original observable collection. 
...
ObservableCollection&lt;Employee&gt; employees = new ObservableCollection&lt;Employee&gt;();
public ObservableCollection&lt;Employee&gt; Employees { get { return employees; }}
public EmployeeListPage()
{
    EmployeeView.ItemsSource = employees;

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f9bb8625-60a7-2d18-86aa-501c64a71073
* Version Independent ID: 4891a28f-63b1-dca9-0467-fc81f32363cf
* Content: [ListView Data Sources - Xamarin](https://docs.microsoft.com/en-my/xamarin/xamarin-forms/user-interface/listview/data-and-databinding#feedback)
* Content Source: [docs/xamarin-forms/user-interface/listview/data-and-databinding.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/listview/data-and-databinding.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by Vespiyanus** [comment]
Continuation to previous comment:
employees = other_Observable collection
..

**Comment by davidbritch** [comment]
Hi @Vespiyanus 

Thanks for pointing this out. I've added a note to the doc, in a PR that will go live later.

Just as an FYI: we encourage everyone to use `CollectionView` now instead of `ListView`.
