### ISSUE TITLE
How to navigate to a normal ContentPage in fullscreen from NavigationPage with TabbedPage?

### ISSUE THREAD

**Issue by yangshuairocks** [MicrosoftDocs/xamarin-docs#2598]
This [Xamarin official sample][1] demonstrates how to use TabbedPage with NavigationPage together. The result looks like this:

<img src="https://i.imgur.com/G44D3jE.gif" />

As you can see, when it navigates to a sub-page, the sub-page is "nested" in the TabbedPage. I want to know how can I make the sub-page in fullscreen, which means when it's on the sub-page, it takes up the whole screen and the TabbedPage doesn't show. Below is an example:

<img src="https://i.imgur.com/XBMcrRG.gif" />

As Microsoft suggestes

> While a NavigationPage can be placed in a TabbedPage, it's not recommended to place a TabbedPage into a NavigationPage. This is because, on iOS, a UITabBarController always acts as a wrapper for the UINavigationController.

I don't know how to implement this. 

  [1]: https://github.com/xamarin/xamarin-forms-samples/tree/master/Navigation/TabbedPageWithNavigationPage

**Comment by davidbritch** [comment]
Hi @yangshuairocks 

The easiest way is to push your `ContentPage` as a modal page using `Navigation.PushModalAsync` rather than `Navigation.PushAsync`.
