### ISSUE TITLE
TargetPlatform enumeration and native views

### ISSUE THREAD

**Issue by chucker** [MicrosoftDocs/xamarin-docs#2599]
https://docs.microsoft.com/en-us/xamarin/xamarin-forms/platform/native-views/xaml refers to the target platform:

> As well as specifying the clr-namespace and assembly for a native view namespace, a targetPlatform must also be specified. This should be set to one of values of the TargetPlatform enumeration, and will typically be set to iOS, Android, or Windows.

However, [that enum](https://docs.microsoft.com/en-us/dotnet/api/xamarin.forms.targetplatform?view=xamarin-forms) (which is linked from the page) is deprecated. It also seems to be incomplete; my expected value of macOS isn't included.

What's the new approach to a platform-specific control inside a view?

**Comment by davidbritch** [comment]
Hi @chucker 

Thanks for pointing this out. Although the `TargetPlatform` enum is deprecated, the `targetPlatform` value must be identical to one of: `iOS`, `Android`, `UWP`, `Windows` (which is equivalent to `UWP`), `macOS`, `GTK`, `Tizen`, or `WPF`.

I've just updated the doc, in a PR that will go live later.
