### ISSUE TITLE
Documentation structure

### ISSUE THREAD

**Issue by Phlash1989** [MicrosoftDocs/xamarin-docs#260]
Hi there, shouln't the docs for Xamarin.Essentials go to the cross platform section? Looks like at the moment it's located under Xamarin.iOS.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c420b152-7303-918a-dbc8-8d1e539c64ec
* Version Independent ID: fe85e24f-c3fc-3763-b1db-6b360fb08067
* Content: [Xamarin.Essentials - Xamarin](https://docs.microsoft.com/en-us/xamarin/essentials/)
* Content Source: [docs/essentials/index.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/essentials/index.md)
* Service: **xamarin**
* GitHub Login: @jamesmontemagno
* Microsoft Alias: **jamont**

**Comment by jamesmontemagno** [comment]
Xamarin.Essentials is specifically for iOS, Android, and Xamarin.Forms applications. So it is relevant to those platforms.

**Comment by Phlash1989** [comment]
Ah, got it now. So from this point of view, it makes sense to me. 

Thanks @jamesmontemagno!
