### ISSUE TITLE
Poorly worded description.

### ISSUE THREAD

**Issue by Entiat** [MicrosoftDocs/xamarin-docs#2600]
One of the paragraphs starts with "Data binding automates this job, and renders the event handlers unnecessary. (The events are still necessary, however, because the data-binding infrastructure uses them.)"

Well, are they necessary or not? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f255d152-0e9d-92dd-e1ca-0efc335f98dd
* Version Independent ID: 5c7dfe7c-1696-17f2-e07d-266a170a06a0
* Content: [Xamarin.Forms Data Binding - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/data-binding/#feedback)
* Content Source: [docs/xamarin-forms/app-fundamentals/data-binding/index.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/app-fundamentals/data-binding/index.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @Entiat 

The text is accurate, but clearly confusing. Data binding renders the *event handlers* unnecessary, but under the hood *events* are used.

I've updated the text in a PR that will go live later.
