### ISSUE TITLE
Missing clarifying example

### ISSUE THREAD

**Issue by LeonSweden** [MicrosoftDocs/xamarin-docs#2605]
Needs example w/ different properties.
I need ISO codes of locale f.e. US-AU (Australia) or SE-SE (Sweden)...

Also, must be consistent over devices. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aed49631-fea0-cdd4-867f-84bec6a87dc9
* Version Independent ID: 5f986208-a5a4-9154-83c7-fd6d5a4731e5
* Content: [Locale Class (Xamarin.Essentials)](https://docs.microsoft.com/en-us/dotnet/api/xamarin.essentials.locale?view=xamarin-essentials-android#feedback)
* Content Source: [docs/en/Xamarin.Essentials/Locale.xml](https://github.com/xamarin/Essentials/blob/live/docs/en/Xamarin.Essentials/Locale.xml)
* Product: **xamarin**
* Technology: **xamarin-essentials**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by jamesmontemagno** [comment]
Thanks for the feature request, can you please open an issue at http://github.com/xamarin/essentials
