### ISSUE TITLE
Missing mime-checker

### ISSUE THREAD

**Issue by LeonSweden** [MicrosoftDocs/xamarin-docs#2606]
Would be nice to have a mime-checker.
With a mime-id, is there app(s) that supports that type?
What apps?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6a7e802f-ce88-b235-c1f0-45a31e7144e6
* Version Independent ID: b88b1c7f-b42c-02d0-0f41-a778b0b5d80a
* Content: [Launcher Class (Xamarin.Essentials)](https://docs.microsoft.com/en-us/dotnet/api/xamarin.essentials.launcher?view=xamarin-essentials-android)
* Content Source: [docs/en/Xamarin.Essentials/Launcher.xml](https://github.com/xamarin/Essentials/blob/live/docs/en/Xamarin.Essentials/Launcher.xml)
* Product: **xamarin**
* Technology: **xamarin-essentials**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by jamesmontemagno** [comment]
Thanks, can you put in a Feature request on http://github.com/xamarin/essentials
