### ISSUE TITLE
This API Not Working!!!

### ISSUE THREAD

**Issue by salarbrefki** [MicrosoftDocs/xamarin-docs#2610]
This line of code not work!!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9c678b27-7a65-6571-3a66-7e9554c5dbd1
* Version Independent ID: a53381fe-0213-9ba1-082c-691a6b8361d5
* Content: [Xamarin.Essentials: App Theme - Xamarin](https://docs.microsoft.com/en-us/xamarin/essentials/app-theme?context=xamarin%2Fandroid&tabs=android#feedback)
* Content Source: [docs/essentials/app-theme.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/essentials/app-theme.md)
* Product: **xamarin**
* Technology: **xamarin-essentials**
* GitHub Login: @jamesmontemagno
* Microsoft Alias: **jamont**

**Comment by jamesmontemagno** [comment]
Please post an issue on: https://github.com/xamarin/essentials with more information please.
