### ISSUE TITLE
UIWebView Deprecation and App Store Rejection (ITMS-90809)

### ISSUE THREAD

**Issue by jackkranz** [MicrosoftDocs/xamarin-docs#2612]
I am still having this issue!

I have followed all the documented steps (https://docs.microsoft.com/en-au/xamarin/xamarin-forms/user-interface/webview?tabs=macos#uiwebview-deprecation-and-app-store-rejection-itms-90809) 

My versions of Xamarin.Forms + Xamarin.iOS are higher than required.
I've added the additional mtouch args.

Any ideas?

**Comment by jfversluis** [comment]
Hi @jackkranz, thanks for reporting this!

We've had a couple of more cases where it didn't seem to work, while all the bits seemed to be in place. You can see all the suggestions and conversation [here](https://github.com/xamarin/Xamarin.Forms/issues/9823).

The gist of it is; 
- Make sure you've got the right versions, which you say you do
- Make sure you set the linker behavior to either LinkAll or SDK Only
- Make sure that you have the mtouch argument for the right build configuration, see https://github.com/xamarin/Xamarin.Forms/issues/9823#issuecomment-594135484
- Make sure that you did a clean build. Delete the bin and obj folders and rebuild the whole thing

One of the last options is that you might be using a third-party library that still references the UIWebView, this won't be captured by our solution. However, this hasn't been the case for the majority of people. 

Let me know if any of these suggestions make sense. If you still need assistance you would probably be better off opening an issue on the Forms repository. In this case you may also contact me directly at gerald.versluis [mail sign] microsoft.com so we can get to the bottom of this.

**Comment by vunhutien** [comment]
Hi @jfversluis I also have this issue, i don't use Material component.
This is my build configuration - I use AppCenter to build Ipa file.
```
<PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|iPhone' ">
    <DebugType>none</DebugType>
    <Optimize>true</Optimize>
    <OutputPath>bin\iPhone\Release</OutputPath>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
    <MtouchArch>ARM64</MtouchArch>
    <CodesignKey>XXX</CodesignKey>
    <CodesignEntitlements>Entitlements.plist</CodesignEntitlements>
    <CodesignProvision>Automatic:AppStore</CodesignProvision>
    <MtouchExtraArgs>--optimize=experimental-xforms-product-type</MtouchExtraArgs>
    <MtouchLink>Full</MtouchLink>
  </PropertyGroup>
```

List of nuget packages:
```
<ItemGroup>
    <PackageReference Include="Xamarin.Forms" Version="4.5.0.356" />
    <PackageReference Include="Xamarin.Essentials" Version="1.3.1" />
    <PackageReference Include="sqlite-net-pcl">
      <Version>1.6.292</Version>
    </PackageReference>
    <PackageReference Include="Newtonsoft.Json">
      <Version>12.0.3</Version>
    </PackageReference>
    <PackageReference Include="Com.Airbnb.Xamarin.Forms.Lottie">
      <Version>3.0.3</Version>
    </PackageReference>
    <PackageReference Include="SkiaSharp">
      <Version>1.68.0</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.FFImageLoading">
      <Version>2.4.11.982</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.FFImageLoading.Forms">
      <Version>2.4.11.982</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.FFImageLoading.Svg">
      <Version>2.4.11.982</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.FFImageLoading.Svg.Forms">
      <Version>2.4.11.982</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.FFImageLoading.Transformations">
      <Version>2.4.11.982</Version>
    </PackageReference>
    <PackageReference Include="Xam.Plugins.Settings">
      <Version>3.1.1</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.Google.iOS.MobileAds">
      <Version>7.47.0</Version>
    </PackageReference>
    <PackageReference Include="Plugin.InAppBilling">
      <Version>2.0.0</Version>
    </PackageReference>
    <PackageReference Include="Xam.Plugin.HtmlLabel">
      <Version>3.0.2.2</Version>
    </PackageReference>
    <PackageReference Include="Xam.Plugins.Forms.ProgressRing">
      <Version>0.1.2</Version>
    </PackageReference>
    <PackageReference Include="Acr.UserDialogs">
      <Version>7.1.0.440</Version>
    </PackageReference>
    <PackageReference Include="MarcTron.Admob">
      <Version>1.4.5</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.Google.iOS.SignIn">
      <Version>4.4.0</Version>
    </PackageReference>
  </ItemGroup>
```
App Center build configuration:
![image](https://user-images.githubusercontent.com/37206017/76969945-0f26c080-6966-11ea-8954-75fa86e7acdf.png)


Please give advice.

**Comment by jfversluis** [comment]
I’ve answered in the issue on the Forms repository. This issue has to do with Forms, not the docs. If there are still any issues, please find an issue on the Forms repo that is appropriate or open a new one. Thanks!

@davidbritch feel free to close
