### ISSUE TITLE
Xamarin.Auth no longer maintained?

### ISSUE THREAD

**Issue by JakubHolovsky** [MicrosoftDocs/xamarin-docs#2613]
This article is relying on Xamarin.Auth that hasn't been touched for over 8 months now. No issues are being worked on & no pull requests are merged. Any created issues are just either overlooked or assigned to a guy that never replies to anything. I wonder is this still something we should rely on? https://github.com/xamarin/Xamarin.Auth

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aa8bb9e0-5898-0d11-0213-fd4d8c8d0297
* Version Independent ID: 2f46e1f7-164f-2f32-70c0-f28919d16c5c
* Content: [AuthenticateUsers with an Identity Provider - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/data-cloud/authentication/oauth#feedback)
* Content Source: [docs/xamarin-forms/data-cloud/authentication/oauth.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/data-cloud/authentication/oauth.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @JakubHolovsky 

No, you shouldn't rely on Xamarin.Auth any longer. It's being replaced by authentication support in Xamarin.Essentials. If you look in the Essentials repo in GitHub, you can see an example of how to use the authentication support in Essentials.

Please bear with us while the docs get updated.
