### ISSUE TITLE
XF - ListView appearance

### ISSUE THREAD

**Issue by munkii** [MicrosoftDocs/xamarin-docs#2614]
See the page "[ListView appearance](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/listview/customizing-list-appearance)"

In the section "[Customising Grouping](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/listview/customizing-list-appearance#customizing-grouping)". It has an example of setting the `GroupHeaderTemplate` however the example is wrong because it needs to be a `DataTemplate` wrapping a `ViewCell`. 

If that does not happen the app will crash with no useful error

**Comment by davidbritch** [comment]
Hi @munkii 

Within the `DataTemplate` in a `ListView` `GroupHeaderTemplate`, you just need a type that derives from `Cell`. So that could be a `ViewCell` or a `TextCell`, or other types that derive from `Cell`. I just tried the following template and it worked fine:

```
            <ListView.GroupHeaderTemplate>
                <DataTemplate>
                    <TextCell Text="{Binding LongName}"
                              Detail="{Binding ShortName}"
                              TextColor="#f35e20"
                              DetailColor="#503026" />
                </DataTemplate>
            </ListView.GroupHeaderTemplate>
```

**Comment by munkii** [comment]
I wasn't asking for how it should work. I know the that it needs to be a derivative of Cell. The issue is the docs are wrong they are showing an example that does not follow the rules that you and I know and therefore fails

**Comment by davidbritch** [comment]
In [this](section) the `GroupHeaderTemplate` contains a `DataTemplate` wrapping a `TextCell`, which is correct. What am I missing?

**Comment by munkii** [comment]
Weird. Based on the documentation I can now see you are missing nothing and I am incorrect. Did I imagine that the previous sample did not have a DataTemplate wrapping a Cell? Either way the documentation is correct and this should be closed.
