### ISSUE TITLE
Styling menuitem on Android

### ISSUE THREAD

**Issue by LeonSweden** [MicrosoftDocs/xamarin-docs#2617]
On Android the menu items are shown at top of screen. 
It could be useful to be able to bind a Text property from corresponding selected item's properties.
That Text property should then be shown on the right side of the left arrow.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 27e9d3ab-b3ff-9936-4524-aa18bbf4fb08
* Version Independent ID: 609b293d-deed-8d59-b052-12e21d2dc1f9
* Content: [Xamarin.Forms MenuItem - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/menuitem?source=docs)
* Content Source: [docs/xamarin-forms/user-interface/menuitem.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/menuitem.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @profexorgeek
* Microsoft Alias: **jusjohns**

**Comment by davidbritch** [comment]
Hi @LeonSweden 

This is best logged as an enhancement request in the [engineering repo](https://github.com/xamarin/Xamarin.Forms/).
