### ISSUE TITLE
Add C# Markup Documentation Page

### ISSUE THREAD

**Issue by VincentH-Net** [MicrosoftDocs/xamarin-docs#2618]
As @davidortinau [proposed](https://twitter.com/davidortinau/status/1238224907617677313) for documenting the [XamarinForms C# Markup experimental feature](https://github.com/xamarin/Xamarin.Forms/pull/8342):

> add a new docs page dedicated to using this method of writing UI that can be marked as an experimental preview

# Goal
The primary goal for this documentation - and especially for it's proposed surfacing location(s) in the navigation - is indicated in [this comment on the feature PR](https://github.com/xamarin/Xamarin.Forms/pull/8342#issuecomment-580722371):
> to actually attract a lot of new developers to Forms, it is essential that this modernization of the Forms C# UI style becomes visible in all guidance that contains C# UI examples.
> If not, then developers googling Forms will think C# UI in Forms is still old fashioned procedural, and turn away to frameworks (e.g. Flutter / SwiftUI) that they (injustly) perceive as more modern.

We aim to ensure that developers who are new to Xamarin Forms will see at a glance that XAML and fluent, declarative C# Markup are both supported markup options.

A secondary goal is of course to provide guidance on how to use the feature and give best practices for formatting and other valuable conventions.

_Note that XAML and C# Markup can (and are likely to) be used together for different pages in the same app; many developers already state that they wish to use C# Markup for pages that become/are too complex/dynamic to easily maintain in XAML._

## Url
[docs.microsoft.com/en-us/xamarin/xamarin-forms/csharp-markup](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/csharp-markup)

## Location in top navigation
`Docs / Xamarin / Xamarin.Forms / C# Markup / Overview`

## Location in left navigation
  Xamarin.Forms
<details><summary>Get Started</summary>&nbsp;&nbsp;&nbsp;&nbsp;...</details>
<details><summary>XAML</summary>
&nbsp;&nbsp;&nbsp;&nbsp;Overview

&nbsp;&nbsp;&nbsp;&nbsp;...
</details>
<details open><summary>C# Markup</summary>
&nbsp;&nbsp;&nbsp;&nbsp;<b>Overview</b>
</details>
<details><summary>Application Fundamentals</summary>&nbsp;&nbsp;&nbsp;&nbsp;...</details>

## Location in [docs.microsoft.com/en-us/xamarin/xamarin-forms](https://docs.microsoft.com/en-us/xamarin/xamarin-forms)
![image](https://user-images.githubusercontent.com/1872271/76610713-9c5ab700-6519-11ea-909f-7fad745530eb.png)

## Content
The [PR description](https://github.com/xamarin/Xamarin.Forms/pull/8342#issue-335122886) contains a complete and accurate overview of the API, and it is already written in an introduction style. 

I propose to use that content as starting point and clearly state at the top of the page that this is documentation of an experimental feature (or "preview documentation"?)

I offer to provide the page content so the team only needs to spend time on review.

## Next Steps

1. I can provide the page content within a week in a PR. If possible I can also add the proposed navigation additions in that PR or alternatively a team member can do that before it is merged.
2. When the feature is no longer experimental, this single page documentation can be split up and expanded, while keeping the `Overview` page on the same url and in the same locations in navigation.

**Comment by VincentH-Net** [comment]
Background info to support documenting this feature prominently; also explains how it would **reduce** total documentation effort:

From [this PR comment](https://github.com/xamarin/Xamarin.Forms/pull/8342#issuecomment-580722371):
> The whole point of including C# Markup helpers in Forms is to give developers confidence that this will become the mainstream Microsoft supported way of doing C# Forms UI - on equal footing with XAML - so they won't have doubts about adopting it.
> - Support the case to be made to the docs team, to start writing the examples in documentation for **new** Forms UI features in XAML + in this declarative C# style.
> Points for that case are:
>   - The docs team has always done a great job by providing every Forms UI code example in both XAML and C# variations. However to actually attract a lot of new developers to Forms, it is essential that this modernization of the Forms C# UI style becomes visible in all guidance that contains C# UI examples.
> If not, then developers googling Forms will think C# UI in Forms is still old fashioned procedural, and turn away to frameworks that they (injustly) perceive as more modern.
>   - I do realize that we need have a follow-up conversation about this internally and with the docs team after this PR is merged, but if it would become a separate NuGet it will be perceived as optional, and we run the risk that the docs team will object to the extra effort of adding another variation to UI examples (XAML, procedural C# **and** declarative C#). Note that writing the C# variation of new Forms UI examples in this declarative style instead of in procedurel style will require **no extra effort** from the docs team (in fact, it should **reduce** their effort since the declarative style is more productive, and increase the documentation clarity).
> In short, it would increase Forms documentation value while reducing documentation effort.
>   - Also, I received feedback from developers who use CSharpForMarkup that one downside is the scarcity of online examples in this style. They often need to translate XAML examples to CSharpForMarkup (maybe I could write a VS extension for that...). Although translating XAML to CSharpForMarkup is much easier than translating it to procedural C#, having Microsoft provide the right examples would help. And if Microsoft sets the example by using this style, the Forms community is also encouraged to share more examples in this style.
>   - I could provide some pull requests to existing docs to help convince the docs team. I could also spearhead an initiative to recruit community assistance for updating existing docs.
> 
> **Note** that in [this recent Twitter poll](https://twitter.com/davidortinau/status/1221108490070085632) by @davidortinau, of the 2100 devs that responded:
> - **15%** said they would start new projects with C#
> - **5%** with @Clancey 's Comet
> - **38%** with XAML
> 
> That is **one of every five devs** who intends to use C# for markup. XAML has **two out of five**, so they already are in the same league going forward. And that is still within the current Forms community which is heavily XAML biased; the audience where this PR aims to gain the most (devs that do not yet know XAML or Forms) will give a significant higher % for C# UI.
> Also from feedback in the poll thread, I noticed that devs [chose XAML because they had not seen CSharpForMarkup examples](https://twitter.com/hindrikes/status/1221141600396627969) - supporting the docs team case above.

**Comment by VincentH-Net** [comment]
A side-by-side comparison of a full page in declarative style versus the current imperative C# documentation style [from Brandon Minnick's XamConverter](https://github.com/brminnick/XamConverter/blob/5c0dca70afe91a1599f42b8b54845836617b5757/Source/XamConverter/Pages/ConversionPage.cs), which was first written in imperative style and later converted to C# Markup:
![image](https://user-images.githubusercontent.com/1872271/76621481-bd2e0700-652f-11ea-87f4-c2209d560f31.png)

**Comment by davidbritch** [comment]
Hi @VincentH-Net 

Worry not. This is already in hand. I'll be starting this later today. The work will happen in our private repo, so you won't be able to see it until it goes live.

Therefore, I'll close the issue here.

**Comment by VincentH-Net** [comment]
Thanks @davidbritch! That leaves more time for me to focus on tooling for C# markup and a new part 2 PR of the feature.

Key for C# Markup docs is not to use the standard C# formatting for logic, but instead a **markup specific C# formatting convention** as illustrated in above screenshot. An important element of this is the **layout line**, which is described in the PR description.

Feel free to ask me to review a first snippet at any time.

Any idea about when the docs will become visible?
It would be great if that could be when 4.6 hits stable.

**Comment by davidbritch** [comment]
Hi @VincentH-Net 

All the Forms 4.6 docs will go live on the day the package hits a stable release, as part of a single docs PR. I'd expect to have finished the doc by mid-week, and I'm happy to send it to you for a review.

**Comment by davidbritch** [comment]
Hi @VincentH-Net 

Any problems with me reusing your [example](https://github.com/VincentH-Net/CSharpForMarkup/tree/master/Example) as the sample to use for the doc?

**Comment by VincentH-Net** [comment]
That example uses the obsolete [CSharpForMarkup](https://github.com/VincentH-Net/CSharpForMarkup/tree/master/Example) implementation; it is not yet updated to the helper name changes and enhancements in the Forms 4.6 implementation.

It also uses Fody.PropertyChanged to keep viewmodel code small 

How about I add a branch based on 4.6 preview, and clean it up real quick?

**Comment by davidbritch** [comment]
@VincentH-Net That'd be perfect :)

**Comment by VincentH-Net** [comment]
@davidbritch  I have migrated my old example to Xamarin.Forms.Markup - [here](https://github.com/VincentH-Net/CSharpForMarkup/tree/formsexample/Example)
Also did some cleanup to remove irrelevant code and update to some new best practices.

The example does illustrate quite some C# Markup features and a few alternative variations in patterns (styles / nested classes / create methods) however it is visually not very appealing or consistent - you can tell I'm not a designer.

**Comment by davidbritch** [comment]
@VincentH-Net Thanks. You're more of a designer than me!

**Comment by davidbritch** [comment]
@VincentH-Net UWP isn't supported?

**Comment by davidbritch** [comment]
@VincentH-Net Ignore me. UWP is supported. I just forgot to initialise the TaskHelper in the UWP project.

**Comment by VincentH-Net** [comment]
Yes; *all* platforms are supported; there is nothing platform specific in the code

**Comment by VincentH-Net** [comment]
Hi, @davidbritch, anything for me to review yet?
> I'd expect to have finished the doc by mid-week, and I'm happy to send it to you for a review.

I don't mind if it is incomplete; early feedback is cheapest to incorporate anyway

**Comment by davidbritch** [comment]
@VincentH-Net 

Yep, finished it yesterday. Send me your email address (as a twitter message?) and I'll email it to you.

**Comment by VincentH-Net** [comment]
Great! Can't send you a DM on Twitter, but ain't afraid of no spam :-)
My email:
dev at vincenth.net

**Comment by VincentH-Net** [comment]
Thanks for the draft @davidbritch ! I mailed the reviewed doc and did a [PR on the example](https://github.com/xamarin/xamarin-forms-samples/pull/594)
