### ISSUE TITLE
Typo: exception -> permission

### ISSUE THREAD

**Issue by Oskiii** [MicrosoftDocs/xamarin-docs#2619]
"Exception that occures when calling an API that requires a specific exception"
should be
"Exception that occures when calling an API that requires a specific PERMISSION"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2ab42136-ce08-cef7-1ba9-4ece1d4118bd
* Version Independent ID: a909d920-0346-e658-3f43-5659a3eb408d
* Content: [PermissionException Class (Xamarin.Essentials)](https://docs.microsoft.com/en-us/dotnet/api/xamarin.essentials.permissionexception?view=xamarin-essentials#feedback)
* Content Source: [docs/en/Xamarin.Essentials/PermissionException.xml](https://github.com/xamarin/Essentials/blob/live/docs/en/Xamarin.Essentials/PermissionException.xml)
* Product: **xamarin**
* Technology: **xamarin-essentials**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by jamesmontemagno** [comment]
Thanks put in a PR: https://github.com/xamarin/Essentials/pull/1258
