### ISSUE TITLE
Please support VMWare!

### ISSUE THREAD

**Issue by nguyenthanhliemfc** [MicrosoftDocs/xamarin-docs#262]
I develop app by Xamarin.Forms so I need test app on Windows Simulator, Android Emulator and VMWare to run MacOS. Please support VMWare.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4e37d642-2051-8d70-9968-dfb484122a6a
* Version Independent ID: 178ea80c-2b99-0c44-eeb6-9db319439b33
* Content: [Android Emulator Hardware Acceleration - Xamarin](https://docs.microsoft.com/en-us/xamarin/android/get-started/installation/android-emulator/hardware-acceleration?tabs=vswin#hyper-v-overview)
* Content Source: [docs/android/get-started/installation/android-emulator/hardware-acceleration.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/android/get-started/installation/android-emulator/hardware-acceleration.md)
* Service: **xamarin**
* GitHub Login: @mgmclemore
* Microsoft Alias: **mamcle**

**Comment by mgmclemore** [comment]
Hi @nguyenthanhliemfc, this system is just for documentation feedback. Please visit the [Developer Community](https://developercommunity.visualstudio.com/spaces/8/index.html) to post enhancement requests.
