### ISSUE TITLE
Missing guide on Azure AD  Authentication

### ISSUE THREAD

**Issue by LeonSweden** [MicrosoftDocs/xamarin-docs#2621]
I've implemented AD Authentication into my Xamarin Forms App.
It was not hard nor complicated but since it was not covered here, I thought I could use B2C for this, and that was wrong w/ single tenant AD's.

So please, create a Azure AD use case as well.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 883bf5dc-9806-f848-93e6-7a8bb36ae52a
* Version Independent ID: 98a9a075-d451-ed9b-fde6-c13b9379ca13
* Content: [Xamarin.Forms Web Service Authentication - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/data-cloud/authentication/)
* Content Source: [docs/xamarin-forms/data-cloud/authentication/index.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/data-cloud/authentication/index.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @LeonSweden 

I've added an issue to our backlog for this.
