### ISSUE TITLE
Custom Font in folder does not work in code (Android)

### ISSUE THREAD

**Issue by eli191** [MicrosoftDocs/xamarin-docs#2624]
Hi,
Suppose a font in a folder named `Fonts` in the `Assets` folder.
Then doing
```
new Label
{
  Text = "Hello, Forms!",
  FontFamily =  "Fonts/Lobster-Regular.ttf#Lobster-Regular" 
}
```
does not render the `Label`.
It works from XAML.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe0572c4-91be-fc86-d130-242db2bf470b
* Version Independent ID: 1238fdd7-c378-6d0d-654e-55656a70d386
* Content: [Fonts in Xamarin.Forms - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/text/fonts#set-the-font-in-code)
* Content Source: [docs/xamarin-forms/user-interface/text/fonts.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/text/fonts.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @eli191 

Agreed that it's not working from code. That's one to take up with the engineers, in the [engineering repo](https://github.com/xamarin/Xamarin.Forms/).
