### ISSUE TITLE
Incorrect Method Name

### ISSUE THREAD

**Issue by RyanGaudion** [MicrosoftDocs/xamarin-docs#2628]
'Preferences' contains no method 'HasKey', should be changed to ContainsKey:

Incorrect Line:
bool hasKey = Preferences.HasKey("my_key");

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a7a399b1-a8a2-9cbd-c479-1bd98af46988
* Version Independent ID: 91a6ae06-508b-b668-52aa-cbdeabb2b46a
* Content: [Xamarin.Essentials: Preferences - Xamarin](https://docs.microsoft.com/en-us/xamarin/essentials/preferences?context=xamarin%2Fxamarin-forms&tabs=android#feedback)
* Content Source: [docs/essentials/preferences.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/essentials/preferences.md)
* Product: **xamarin**
* Technology: **xamarin-essentials**
* GitHub Login: @jamesmontemagno
* Microsoft Alias: **jamont**

**Comment by jamesmontemagno** [comment]
Good catch! fixing now
