### ISSUE TITLE
CollectionView Bored of this error

### ISSUE THREAD

**Issue by fakhravari** [MicrosoftDocs/xamarin-docs#2629]
hi
Java.Lang.NullPointerException: ‘Attempt to invoke virtual method ‘void android.graphics.Rect.set(android.graphics.Rect)’ on a null object reference’

I’m displaying a simple list, but this error occurs while scrolling

https://forums.xamarin.com/discussion/comment/406198
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6bd3b3b0-0147-f10d-76fe-15eecb8c25cf
* Version Independent ID: 586eee27-63ea-6cbf-b064-6e4a3dde7327
* Content: [Xamarin.Forms CollectionView Scrolling - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/collectionview/scrolling#feedback)
* Content Source: [docs/xamarin-forms/user-interface/collectionview/scrolling.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/collectionview/scrolling.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @fakhravari 

Afraid this is an issue for the [engineering repo](https://github.com/xamarin/Xamarin.Forms/).

**Comment by fakhravari** [comment]
What helps me
