### ISSUE TITLE
Thread safety

### ISSUE THREAD

**Issue by rsaugier** [MicrosoftDocs/xamarin-docs#2631]
It would be nice to indicate if this API is thread-safe or not. I can't find this info here nor in the reference, although I might be missing something.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a7a399b1-a8a2-9cbd-c479-1bd98af46988
* Version Independent ID: 91a6ae06-508b-b668-52aa-cbdeabb2b46a
* Content: [Xamarin.Essentials: Preferences - Xamarin](https://docs.microsoft.com/en-us/xamarin/essentials/preferences?tabs=android#feedback)
* Content Source: [docs/essentials/preferences.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/essentials/preferences.md)
* Product: **xamarin**
* Technology: **xamarin-essentials**
* GitHub Login: @jamesmontemagno
* Microsoft Alias: **jamont**

**Comment by jamesmontemagno** [comment]
Under platform implementation you will find the underlying docs on each platform: https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/essentials/preferences.md#platform-implementation-specifics

Most platforms work with an in-memory cache and then written to disk at certain intervals and are thread safe for read/write.
