### ISSUE TITLE
Issue in Xamarin.Auth in android project in c#

### ISSUE THREAD

**Issue by SoumenHalder88** [MicrosoftDocs/xamarin-docs#2632]
Hello ,
I am working in android project in c# with google authentication, I am using Xmarin.Auth to get the google authentication, I am following https://github.com/TimLariviere/Sample-XamarinAuth-Google link for support. It Is authenticating but dose not returning back to the apps. How to resolve?

**Comment by davidbritch** [comment]
Hi @SoumenHalder88 

I'd recommend you stop using Xamarin.Auth. It's being replaced with authentication support in Xamarin.Essentials. 

I recommend you take a look at the [Essentials sample](https://github.com/xamarin/Essentials/tree/develop/Samples) until the docs get sorted out.

**Comment by SoumenHalder88** [comment]
> Hi @SoumenHalder88
> 
> I'd recommend you stop using Xamarin.Auth. It's being replaced with authentication support in Xamarin.Essentials.
> 
> I recommend you take a look at the [Essentials sample](https://github.com/xamarin/Essentials/tree/develop/Samples) until the docs get sorted out.

Hello @davidbritch I am working in a Xmarine.Android app where I need to fetch google contact details of a gmail account. My app will call google login then authenticate that user then return back to my app with access token. then I can use that access token to the google people api to fetch contact list. How can I achieve this Xamarin.Essentials?
