### ISSUE TITLE
A way to enable compilation error if compile-time binding fails?

### ISSUE THREAD

**Issue by wrkettlitz** [MicrosoftDocs/xamarin-docs#2633]
What if I want everything to be compile-time bound, can I configure the compiler to give an error if it fails? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f6dded20-b246-945c-63ce-0e349afac9a2
* Version Independent ID: 1e24cfb3-a124-e001-5eb5-9410834bf3a1
* Content: [Xamarin.Forms Compiled Bindings - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/data-binding/compiled-bindings)
* Content Source: [docs/xamarin-forms/app-fundamentals/data-binding/compiled-bindings.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/app-fundamentals/data-binding/compiled-bindings.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @wrkettlitz 

If you use compiled bindings, you will get a compile time error if the binding can't be resolved. You should never get a runtime failure, due to the binding being resolved at compile time.

**Comment by wrkettlitz** [comment]
@davidbritch I get that, but what if I want _everything_  to be compiled time bound, how can I make sure nothing will be bound at runtime?

**Comment by davidbritch** [comment]
@wrkettlitz Afraid the best you can do right now is to turn it on at the page-level. If you want more than that, your best bet is to file an enhancement request in the [engineering repo](https://github.com/xamarin/Xamarin.Forms/).
