### ISSUE TITLE
Excellent Job

### ISSUE THREAD

**Issue by DMiradakis** [MicrosoftDocs/xamarin-docs#2634]
I just wanted to say that this page was extremely helpful for me! My main way of teaching myself ANYTHING is by reading, and it doesn't get better than Microsoft Docs. Awesome job to you guys!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a6fd1063-e094-1bda-e2ec-f63a0136523d
* Version Independent ID: 6e25673a-374a-2f05-f610-984d22e52053
* Content: [Xamarin.Forms Basic Bindings - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/data-binding/basic-bindings)
* Content Source: [docs/xamarin-forms/app-fundamentals/data-binding/basic-bindings.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/app-fundamentals/data-binding/basic-bindings.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Thanks @DMiradakis 

Much appreciated!
