### ISSUE TITLE
Editor scrolling horizontally

### ISSUE THREAD

**Issue by WillSinger** [MicrosoftDocs/xamarin-docs#2635]
My editor is scrolling horizontally instead of vertically on iOS when there is more than one line of text. I am using Xamarin forms 4.5.0.396

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8881d8f1-1d94-e090-e709-aca80b644a78
* Version Independent ID: 298aeed6-5e3e-f053-10f0-66d1061b4b2e
* Content: [Xamarin.Forms Editor - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/text/editor#feedback)
* Content Source: [docs/xamarin-forms/user-interface/text/editor.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/text/editor.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @WillSinger 

This issue really needs logging in the [engineering repo](https://github.com/xamarin/Xamarin.Forms/). Thanks!
