### ISSUE TITLE
"Translucent" instead of "Transparent"

### ISSUE THREAD

**Issue by radoeska-v** [MicrosoftDocs/xamarin-docs#2636]
This `TranslucencyMode` enumeration value does not match in the documentation and implementation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a52cd5e-2cc8-0398-dcb3-db2607f11c1b
* Version Independent ID: c2586399-6b8c-78c6-e0da-fa3e35adb00a
* Content: [TabbedPage translucent tab bar on iOS - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/platform/ios/tabbedpage-translucent-tabbar#feedback)
* Content Source: [docs/xamarin-forms/platform/ios/tabbedpage-translucent-tabbar.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/platform/ios/tabbedpage-translucent-tabbar.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @radoeska-v 

Thanks for reporting this. I'll get it updated in the next few days.

**Comment by davidbritch** [comment]
I've fixed this in a PR that will go live either today or tomorrow.

**Comment by radoeska-v** [comment]
Hi David,

Thanks for the update :)
