### ISSUE TITLE
Isn't `TemplateBinding` deprecated as of 4.3?

### ISSUE THREAD

**Issue by pmahend1** [MicrosoftDocs/xamarin-docs#2641]
[TemplateBinding is obsolete](https://github.com/xamarin/Xamarin.Forms/blob/fa853ff823272af4b307521d4b5774165d1c7e2c/Xamarin.Forms.Core/TemplateBinding.cs#L6) is obsolete. 

Prior we used to use `TemplateBinding BindingContext.Property` `TemplateBinding Parent.BindingContext` , I am still using `TemplateBiding BindingContext.Property` instead of just `TemplateBinding Property` Its little confusing. Please clarify.

Also does TemplateBinding support `FallBackValue` , `TargetNullValue` ? Please update.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a4b35f51-7abf-c8cc-2dfb-2cb20a0fc200
* Version Independent ID: f47aa11e-86c3-9387-e1f8-b6ce29fe5eb7
* Content: [Xamarin.Forms control templates - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/templates/control-template#feedback)
* Content Source: [docs/xamarin-forms/app-fundamentals/templates/control-template.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/app-fundamentals/templates/control-template.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @pmahend1 

While the `TemplateBinding` class is obsolete, the `TemplateBinding` markup extension isn't. So if you are using `TemplateBinding` in XAML, it's business as usual.

While the `Binding` markup extension supports `FallbackValue` and `TargetNullValue`, the `TemplateBinding` markup extension does not.

See:

https://github.com/xamarin/Xamarin.Forms/blob/fa853ff823272af4b307521d4b5774165d1c7e2c/Xamarin.Forms.Xaml/MarkupExtensions/BindingExtension.cs

and

https://github.com/xamarin/Xamarin.Forms/blob/fa853ff823272af4b307521d4b5774165d1c7e2c/Xamarin.Forms.Xaml/MarkupExtensions/TemplateBindingExtension.cs
