### ISSUE TITLE
Appreciations

### ISSUE THREAD

**Issue by aliyuago** [MicrosoftDocs/xamarin-docs#2644]
[This project is really good it helped me really thanks a lot I will be keeping up with these kind of stuffs because nowadays my mind is really rotating around learning mobile and desktop applications with visual studio thanks. :) ]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6ab89335-bb35-dd6e-cb41-2d889415a555
* Version Independent ID: 72c891a7-6f2a-45e5-0935-0cdee220305c
* Content: [Xamarin.Forms Quickstart Deep Dive - Xamarin](https://docs.microsoft.com/en-us/xamarin/get-started/quickstarts/deepdive?pivots=windows)
* Content Source: [docs/get-started/quickstarts/deepdive.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/get-started/quickstarts/deepdive.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Thanks for the feedback @aliyuago
