### ISSUE TITLE
Unclear statement about VersionTracking.Track() usage

### ISSUE THREAD

**Issue by pfedotovsky** [MicrosoftDocs/xamarin-docs#2645]
The page says "You must call Track early only in your application each time it is loaded to ensure the current version information is tracked". What does it mean? It is mandatory to call the Track method for the VersionTracking to work? What happens if the Track is not called?

I recently noticed that one of my apps doesn't call Track and it seems to work fine. So I'm confused about why Track is needed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a415c6da-557c-7556-4461-40feeea9b119
* Version Independent ID: 326f5d03-88d0-4fad-946c-c178bb3bf976
* Content: [Xamarin.Essentials: Version Tracking - Xamarin](https://docs.microsoft.com/en-us/xamarin/essentials/version-tracking#feedback)
* Content Source: [docs/essentials/version-tracking.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/essentials/version-tracking.md)
* Product: **xamarin**
* Technology: **xamarin-essentials**
* GitHub Login: @jamesmontemagno
* Microsoft Alias: **jamont**

**Comment by jamesmontemagno** [comment]
Version Tracking works by inserting and updating records of the current version of your app. This happens whenever any method or property is called. The guidance is to call Track() early on in your app so no matter what your user does or goes to the current version is recorded. Technically, you can call other properties or methods and it will act the same as Track(), however if your user doesn't go to that page or you only call it at a certain point in the app then that version may not ever be called. So, this is why Track() is recommended at start of your app.
