### ISSUE TITLE
UpdateCancelButton override not working

### ISSUE THREAD

**Issue by dsurrao** [MicrosoftDocs/xamarin-docs#2647]
I could not override ```UpdateCancelButton``` for iOS as mentioned in the docs. I used  ```OnElementPropertyChanged``` instead.

Here's a sample: https://github.com/dsurrao/xamarin-examples/tree/master/CustomSearchBar

Am I missing something?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e2aa5fc1-2b9b-9610-77b2-06bb9eeb1ed1
* Version Independent ID: 8a3da39b-d2a7-27f5-eee9-20842a18519b
* Content: [Xamarin.Forms SearchBar - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/searchbar)
* Content Source: [docs/xamarin-forms/user-interface/searchbar.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/searchbar.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @profexorgeek
* Microsoft Alias: **jusjohns**

**Comment by davidbritch** [comment]
Hi @dsurrao 

`UpdateCancelButton` was added in Xamarin.Forms 4.4, so you need to update the NuGet packages in your sample.
