### ISSUE TITLE
Getting error while deploying

### ISSUE THREAD

**Issue by DailyLearning-prog** [MicrosoftDocs/xamarin-docs#2648]
I followed the above instructions, i even have apple developer account approved. Phone is connected, iTunes is opened, but I am unable to deploy to iPhone. Using VS 2019 16.5. Cleaned the build and rebuild. I don't have Macbook.  Not sure what's causing the below error. 
An error occurred while trying to deploy the app 'App2.iOS.app'. 

Details: Error running winiosterminal: 'An error occurred while deploying the application 'App2.iOS.app' into 'test's iPhone'.
Details: An Afc error occurred. The error code was ObjectNotFound'. Command: 'deploy -u=00008020-001D4CCC2E50003A -i=com.companyname.App2 -n=App2.iOS.app'

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5ccadd93-fcc8-6a15-9670-d5af7ee7f6f8
* Version Independent ID: 188007d3-cf20-97ba-137f-64ff25a88e7c
* Content: [Automatic Provisioning for Xamarin.iOS - Xamarin](https://docs.microsoft.com/en-us/xamarin/ios/get-started/installation/device-provisioning/automatic-provisioning?tabs=windows#feedback)
* Content Source: [docs/ios/get-started/installation/device-provisioning/automatic-provisioning.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/ios/get-started/installation/device-provisioning/automatic-provisioning.md)
* Product: **xamarin**
* Technology: **xamarin-ios**
* GitHub Login: @davidortinau
* Microsoft Alias: **daortin**

**Comment by davidbuckleyni** [comment]
Please post this via Send Feedback Report a problem Microsoft won't look at the issue from here as this is solely for documentation bugs.

**Comment by DailyLearning-prog** [comment]
Okay. I haven't searched in the VS feedback. I will raise a new issue, if i don't find anything.
Thank you!

**Comment by GaboMendez** [comment]
Hey i have this issue, how did yo resolve it?

Regards, Gabriel!

**Comment by DailyLearning-prog** [comment]
There is an existing open ticket and looks like Microsoft is investigating the Visual studio issue.


https://developercommunity.visualstudio.com/content/problem/963269/hotrestart-unable-to-deploy-application.html?childToView=975818#comment-975818

Since it’s a VS issue and document I have closed the issue here. No known solutions till now.😞

**Comment by zzappazz** [comment]
Visual Studio Feedback System, 20200520:
A fix for this issue has been internally implemented and is being prepared for release. We'll update you once it becomes available for download.

Continue on [https://developercommunity.visualstudio.com/comments/1041598/view.html](https://developercommunity.visualstudio.com/comments/1041598/view.html)
