### ISSUE TITLE
Need support for MemoryStream MediaPlayback

### ISSUE THREAD

**Issue by samdubey** [MicrosoftDocs/xamarin-docs#2655]
Will MediaElement support for video playback using memory stream / byte array anytime soon?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4485a974-e563-1a00-bc75-50c15942b5ed
* Version Independent ID: b59da204-445a-5019-7be5-ad2cb2f59c0d
* Content: [Xamarin.Forms MediaElement - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/mediaelement#feedback)
* Content Source: [docs/xamarin-forms/user-interface/mediaelement.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/mediaelement.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @samdubey 

Soon - doubtful. The engineers need to stabilise the control before it gets more enhancements. There aren't any enhancement requests for adding memory stream support, so opening one would be a good place to start (https://github.com/xamarin/Xamarin.Forms/).
