### ISSUE TITLE
Hot Restart is saying the polly assembly is missing

### ISSUE THREAD

**Issue by davidbuckleyni** [MicrosoftDocs/xamarin-docs#2656]
Using the Hot Restart feature I installed iTunes and went to log into my developer account but I was presented with the screen shot below.

AC Result
![image](https://user-images.githubusercontent.com/5619229/77440109-d2345100-6ddf-11ea-890b-7bbfdfe90212.png)

Expected Result.
Hot Restart should be able to log in with my developer account with any issues the account says it is provisioned so what else could cause this issue.
[IOSIssueItunes.zip](https://github.com/MicrosoftDocs/xamarin-docs/files/4375985/IOSIssueItunes.zip)

Version Information of visual studio 

Microsoft Visual Studio Community 2019 Preview
Version 16.6.0 Preview 1.0
VisualStudio.16.Preview/16.6.0-pre.1.0+29911.98
Microsoft .NET Framework
Version 4.8.04084

Installed Version: Community

Visual C++ 2019   00435-60000-00000-AA238
Microsoft Visual C++ 2019

ASP.NET and Web Tools 2019   16.6.582.38564
ASP.NET and Web Tools 2019

ASP.NET Web Frameworks and Tools 2012   16.6.582.38564
For additional information, visit https://www.asp.net/

ASP.NET Web Frameworks and Tools 2019   16.6.582.38564
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   16.6.582.38564
Azure App Service Tools v3.0.0

Azure Functions and Web Jobs Tools   16.6.582.38564
Azure Functions and Web Jobs Tools

BusinessObjectEditor   1.0
Information about my package

C# Tools   3.6.0-1.20127.6+572b1f0e0da95fd92af710ee58c95e2257cb08e3
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

ConvertToDevExtremeCommand Extension   1.0
ConvertToDevExtremeCommand Visual Studio Extension Detailed Info

Cookiecutter   16.5.20042.1
Provides tools for finding, instantiating and customizing templates in cookiecutter format.

Create Stored Procedures   1.0
Create stored procedures

CreateCrud Extension   1.0
CreateCrud Visual Studio Extension Detailed Info

DevExpress Reporting Extension   1.0
A Visual Studio extension that invokes the Report Designer editor for report definition REPX files.

DevExpress.DeploymentTool   1.0
A useful tool for deploying DevExpress assemblies.

DevExpress.ExpressApp.Design.DynamicPackage   1.0
DevExpress VSIX Package

DevExpress.ExpressApp.DesignPackage   1.0
DevExpress VSIX Package

DevExpress.Win.LayoutAssistant Extension   1.0
DevExpress.Win.LayoutAssistant Visual Studio Extension Detailed Info

Extensibility Message Bus   1.2.0 (d16-2@8b56e20)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

EZ-GIT   1.9.0

IntelliCode Extension   1.0
IntelliCode Visual Studio Extension Detailed Info

JetBrains ReSharper Ultimate 2019.2.3   Build 192.0.20191016.60459
JetBrains ReSharper Ultimate package for Microsoft Visual Studio. For more information about ReSharper Ultimate, visit http://www.jetbrains.com/resharper. Copyright © 2020 JetBrains, Inc.

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 2019 - v2.9.30212.1

Microsoft Continuous Delivery Tools for Visual Studio   0.4
Simplifying the configuration of Azure DevOps pipelines from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft Library Manager   2.1.25+gdacdb9b7a1
Install client-side libraries easily to any web project

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ Wizards   1.0
Microsoft Visual C++ Wizards

Microsoft Visual Studio Tools for Containers   1.1
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

Mono Debugging for Visual Studio   16.6.12 (9f081d2)
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   5.6.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

Progress Telerik UI for ASP.NET Core Extension   2020.1.214.1
Progress® Telerik® UI for ASP.NET Core Extension

Progress Telerik UI for ASP.NET MVC Extension   2020.1.214.1
Progress® Telerik® UI for ASP.NET MVC Extension

Progress Telerik UI for WinForms Extension   2020.1.214.1
Progress® Telerik® UI for WinForms Extension

Progress Telerik UI for WPF Extension   2020.1.214.1
Progress® Telerik® UI for WPF Extension

Progress Telerik UI for Xamarin Extension   2020.1.221.1
Progress® Telerik® UI for Xamarin Extension

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

Python   16.5.20042.1
Provides IntelliSense, projects, templates, debugging, interactive windows, and other support for Python developers.

Python - Conda support   16.5.20042.1
Conda support for Python projects.

Python - Django support   16.5.20042.1
Provides templates and integration for the Django web framework.

Python - IronPython support   16.5.20042.1
Provides templates and integration for IronPython-based projects.

Python - Profiling support   16.5.20042.1
Profiling support for Python projects.

Python - VC Project Support   16.1.19129.1
Provides support for launching C++ projects with Python debugging enabled.

SQL Server Data Tools   16.0.62003.05170
Microsoft SQL Server Data Tools

TypeScript Tools   16.0.20226.2001
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   3.6.0-1.20127.6+572b1f0e0da95fd92af710ee58c95e2257cb08e3
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools 10.9.1.0 for F# 4.7   16.6.0-beta.20121.5+ca100895509c18d8fc5b7625632519c25d2adb3f
Microsoft Visual F# Tools 10.9.1.0 for F# 4.7

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Container Tools Extensions (Preview)   1.0
View, manage, and diagnose containers within Visual Studio.

Visual Studio Tools for Containers   1.0
Visual Studio Tools for Containers

VisualStudio.DeviceLog   1.0
Information about my package

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

VSPackage Extension   1.0
VSPackage Visual Studio Extension Detailed Info

Xamarin   16.6.000.902 (d16-6-hr@75cbfa3)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   16.6.0.150 (remotes/origin/d16-6@06009d433)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   16.6.31 (1d547bc)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   10.2.100.7 (d16-6/69561a7)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: fc145be
    Java.Interop: xamarin/java.interop/d16-6@178e849
    ProGuard: xamarin/proguard/master@905836d
    SQLite: xamarin/sqlite/3.31.1@49232bc
    Xamarin.Android Tools: xamarin/xamarin-android-tools/master@bfb66f3

Xamarin.iOS and Xamarin.Mac SDK   13.18.0.19 (514991e)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

**Comment by davidbuckleyni** [comment]
The zip file is the Xamrain logs by the way I didn't make that clear in the ticket.

**Comment by maddyleger1** [comment]
Hi @davidbuckleyni , this is for issues with the documentation not the product! Could you please file this via Help > Send Feedback > Report a Problem in the IDE? Thanks!

**Comment by davidbuckleyni** [comment]
Yes I will do now

**Comment by davidbuckleyni** [comment]
Hi I uploaded that now into report a problem the reason I had placed it into the documentation was that I was following the docs and this issue occurred sorry for the invcovience.
