### ISSUE TITLE
WebView Renderer for Tizen

### ISSUE THREAD

**Issue by hadihashem** [MicrosoftDocs/xamarin-docs#2658]
Hello
It is described in this article the WebView Renderer for Android, iOS and UWP
It is not described for Tizen
Can you please also provide this part?
Regards

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9c1bd30c-6e7a-df38-8c20-dff7361e901f
* Version Independent ID: 013c6027-db9a-6039-3404-2e4f717133a9
* Content: [Customizing a WebView - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/custom-renderer/hybridwebview#feedback)
* Content Source: [docs/xamarin-forms/app-fundamentals/custom-renderer/hybridwebview.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/app-fundamentals/custom-renderer/hybridwebview.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @hadihashem 

We leave Samsung to handle Tizen support for samples. However, they have a fork of xamarin-forms-samples that includes Tizen projects: https://github.com/Samsung/xamarin-forms-samples

Hopefully you'll find what you need there.
