### ISSUE TITLE
Xamarin Hot Restart issue

### ISSUE THREAD

**Issue by VladislavAntonyuk** [MicrosoftDocs/xamarin-docs#2660]
I have successfully authenticated in the application
I exported certificate from my Mac, and try to import it in this window:
![image](https://user-images.githubusercontent.com/33021114/77545153-ab931a80-6eb2-11ea-92d9-833788e320cc.png)

I receive an error after entering the password:
![image](https://user-images.githubusercontent.com/33021114/77545328-eeed8900-6eb2-11ea-9b12-040f5a5c0826.png)

**Comment by maddyleger1** [comment]
Hi @VladislavAntonyuk - can you please file this in the IDE at Help > Send Feedback > Report a Problem if you're still facing this issue? Thank you!
