### ISSUE TITLE
Cannot get this to resolve

### ISSUE THREAD

**Issue by genifycom** [MicrosoftDocs/xamarin-docs#2662]
NU1603: PCLCrypto 1.0.2.15130 depends on Validation (&gt;= 2.0.6 && &lt; 3.0.0) but Validation 2.0.6 was not found. An approximate best match of Validation 2.0.6.15003 was resolved.
NU1608: Detected package version outside of dependency constraint: Xamarin.Android.Support.v7.AppCompat 28.0.0.1 requires Xamarin.Android.Support.Collections (= 28.0.0.1) but version Xamarin.Android.Support.Collections 28.0.0.3 was resolved.
NU1107: Version conflict detected for Xamarin.Android.Support.CursorAdapter. Install/reference Xamarin.Android.Support.CursorAdapter 28.0.0.3 directly to project PFPOS to resolve this issue. 
 PFPOS -&gt; Xamarin.Essentials 1.5.1 -&gt; Xamarin.Android.Support.CustomTabs 28.0.0.3 -&gt; Xamarin.Android.Support.Core.UI 28.0.0.3 -&gt; Xamarin.Android.Support.CursorAdapter (= 28.0.0.3) 
 PFPOS -&gt; PFData -&gt; Microsoft.Data.SqlClient 1.1.1 -&gt; Microsoft.Identity.Client 3.0.8 -&gt; Xamarin.Android.Support.v7.AppCompat 28.0.0.1 -&gt; Xamarin.Android.Support.CursorAdapter (= 28.0.0.1).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 298f0c2c-4109-c641-7cf8-47edb36452bf
* Version Independent ID: 097b0a43-3081-221b-8e07-e6f692ccdc41
* Content: [Xamarin.Essentials: Troubleshooting - Xamarin](https://docs.microsoft.com/en-us/xamarin/essentials/troubleshooting)
* Content Source: [docs/essentials/troubleshooting.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/essentials/troubleshooting.md)
* Product: **xamarin**
* Technology: **xamarin-essentials**
* GitHub Login: @jamesmontemagno
* Microsoft Alias: **jamont**

**Comment by jamesmontemagno** [comment]
I would first try to upgrade all of your Support library nugets to 28.0.0.3 and then try to update or install Xamarin.Essentials.
