### ISSUE TITLE
The iOS DisplayAlert No/Yes button preferred action is inconsistent with current behaviour

### ISSUE THREAD

**Issue by Reisclef** [MicrosoftDocs/xamarin-docs#2664]
In the iOS DisplayAlert(String, String, String, String) method documentation, including the Accept and Cancel button, it shows No on the left, and Yes on the right, which is displayed in bold.

![image](https://user-images.githubusercontent.com/9120292/77669477-bade9a80-6f7c-11ea-8030-9fb28f96fdf2.png)

However, when calling this method in iOS 12 and 13 (at least), it displays as below with the correct placing, but the preferred option is set to be Cancel.

![image](https://user-images.githubusercontent.com/9120292/77669434-ab5f5180-6f7c-11ea-82d0-f136363e3015.png)

I would have raised a bug, except that apparently since iOS 8 the [cancel button is the preferred option](http://www.openradar.me/radar?id=5490788398006272).

Can the docs be updated to show the correct behaviour? Or if this is something that can be fixed within the Xamarin Forms code so it is consistent with the docs, can it be raised internally?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3c6e0bb1-26e4-091b-8a99-27d772bed7f6
* Version Independent ID: 57d8ad92-0aa2-9ec4-47bc-8853d9a71d91
* Content: [Display Pop-ups - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/pop-ups)
* Content Source: [docs/xamarin-forms/user-interface/pop-ups.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/pop-ups.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @Reisclef 

Agreed that this is an issue, and thanks for raising it. I'll get the docs updated.

**Comment by davidbritch** [comment]
This is fixed in a PR that should go live in the next hour.
