### ISSUE TITLE
Event Navigated, Navigating not fire when custome renderer (HybridWebView)

### ISSUE THREAD

**Issue by khoangt** [MicrosoftDocs/xamarin-docs#2666]
Event Navigated, Navigating not fire when custome renderer.

Document Details
⚠ Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.

ID: 9c1bd30c-6e7a-df38-8c20-dff7361e901f
Version Independent ID: 013c6027-db9a-6039-3404-2e4f717133a9
Content: Customizing a WebView - Xamarin
Content Source: docs/xamarin-forms/app-fundamentals/custom-renderer/hybridwebview.md
Product: xamarin
Technology: xamarin-forms
GitHub Login: @davidbritch
Microsoft Alias: dabritch

**Comment by davidbritch** [comment]
Hi @khoangt 

I just tried this and both the `Navigated` and `Navigating` events fired just fine. See the images below which contain breakpoints being hit:

![Screenshot 2020-03-30 at 11 44 10](https://user-images.githubusercontent.com/8092460/77904141-f1b5f880-727b-11ea-9558-24cef378e2c8.png)

![Screenshot 2020-03-30 at 11 44 15](https://user-images.githubusercontent.com/8092460/77904146-f5497f80-727b-11ea-8767-d23913c7b3e9.png)

**Comment by khoangt** [comment]
Hi @davidbritch 
Do you check on Android?

**Comment by davidbritch** [comment]
Hi @khoangt 

Agreed that `Navigated` and `Navigating` don't fire on Android for `HybridWebView`. Working on a fix now.

**Comment by davidbritch** [comment]
Hi @khoangt 

I've fixed this issue in both the sample and the doc. The doc changes will go live in the next hour.

In the meantime, the code changes can be seen in the [sample commit](https://github.com/xamarin/xamarin-forms-samples/commit/2aad2bf0bd69b419495eef3ffa600aa8bc3f736e).

**Comment by khoangt** [comment]
> Hi @khoangt
> 
> I've fixed this issue in both the sample and the doc. The doc changes will go live in the next hour.
> 
> In the meantime, the code changes can be seen in the [sample commit](https://github.com/xamarin/xamarin-forms-samples/commit/2aad2bf0bd69b419495eef3ffa600aa8bc3f736e).

Thanks @davidbritch 
I found another bug relaltive Webview Navigation
On iOS When turn off Internet => Navigated Failure don't fire
