### ISSUE TITLE
This looks way too easy

### ISSUE THREAD

**Issue by PorkiePie** [MicrosoftDocs/xamarin-docs#267]
Cannot you make it more complicated?
Unfortunately the Google pages don't look the same, 
I have been on this for over an hour and have got about 10% of the way......
Finally got it working. The android maps api is now called Maps SDK for Android, and when it is missing the debug error refers to maps API v2 which isn't anywhere.
Also the google play services references have changed so I just installed anything referring to play services

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4d1bc9be-4365-8015-1c11-a9ab1770ea01
* Version Independent ID: 82abd821-8fe1-4204-be15-bf3d8a92abd7
* Content: [Obtaining a Google Maps API Key - Xamarin](https://docs.microsoft.com/en-us/xamarin/android/platform/maps-and-location/maps/obtaining-a-google-maps-api-key?tabs=vswin)
* Content Source: [docs/android/platform/maps-and-location/maps/obtaining-a-google-maps-api-key.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/android/platform/maps-and-location/maps/obtaining-a-google-maps-api-key.md)
* Service: **xamarin**
* GitHub Login: @mgmclemore
* Microsoft Alias: **mamcle**

**Comment by mgmclemore** [comment]
Hi @PorkiePie, thanks for the feedback!  Yes, the Google console pages have changed quite a bit since this topic was written -- I've added a task to our backlog to update this section of our doc so that it is in sync with Google.

**Comment by PorkiePie** [comment]
Thanks Mark,

I was getting pretty frustrated that I couldn't tie everything up, and it
is not a straightforward process and difficult to work out where I was
going wrong.

*pro**CAM*

*Software products for the Tourism sector*
*proCAM *- Client and Agent Management database. Visit our website
www.procam-db.com
*proHSK *- Housekeeping management software.
