### ISSUE TITLE
Deploment failure VS 2019

### ISSUE THREAD

**Issue by bdaunt99** [MicrosoftDocs/xamarin-docs#2670]
Everything seemed to go well following these steps. But Deploying fails with te following error:

"An error occurred while trying to deploy the app 'App1.iOS.app'. Details: Error running winiosterminal: 'An error occurred while deploying the application 'App1.iOS.app' into 'brendan's iPhone'. Details: An Afc error occurred. The error code was ObjectNotFound'. Command: 'deploy -u=383dff3c9a96a1414278e25cef7f83deec5fa825 -i=com.bzsoftware.app1 -n=app1.iOS.app'"

The "App1" iOS app works well otherwise if I Build and Distribute it via the AppCenter and install it on the same iPhone 8 device.

SysInfo: Visual Studio 2019 16.5.1, Windows 10, iPhone 8, iOS 13.3.1

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8f3eb808-8e6d-4e07-fc75-8d79a7249265
* Version Independent ID: dbb2b9a9-87a6-e473-50e6-f88435d49e88
* Content: [Xamarin Hot Restart - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/deploy-test/hot-restart#feedback)
* Content Source: [docs/xamarin-forms/deploy-test/hot-restart.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/deploy-test/hot-restart.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @maddyleger1
* Microsoft Alias: **maleger**

**Comment by jimmccurdy** [comment]
I am getting the same error.  My device is an iPhone 5S.

**Comment by maddyleger1** [comment]
Hi folks - can you please file this via Help > Send Feedback > Report a Problem in the IDE? Thanks!

**Comment by GaboMendez** [comment]
i have the same issue, i want to know how to resolve it...

**Comment by aherrick** [comment]
Same issue with iPhone 5S.

**Comment by avorobjovs** [comment]
Hi,

I have the same issue.
I have the Xamarin.Forms app and use the Xamarin Hot Restart to run the iOS app on iPhone from Visual Studio on Windows. And I also have the deployment issue. But the message is slightly different:

An error occurred while trying to deploy the app 'KC.Mobility.Sales.iOS.app'. Details: Error running winiosterminal: 'An error occurred while deploying the application 'KC.Mobility.Sales.iOS.app' into 'IPR iPhone7+ Test Device'. Details: An Afc error occurred. The error code was EmptyResponse'. Command: 'deploy -u=96346626f88f9f139d81b4d8b9d64dda905679c7 -i=com.yourcompany.KC.Mobility.Sales -n=KC.Mobility.Sales.iOS.app'


Microsoft Visual Studio Enterprise 2019
Version 16.5.4
VisualStudio.16.Release/16.5.4+30011.22
Xamarin 16.5.000.533 (d16-5@9152e1b)
Xamarin Designer 16.5.0.470 (remotes/origin/d16-5@681de3fd6)
Xamarin Templates 16.5.49 (0904f41)
Xamarin.Android SDK 10.2.0.100 (d16-5/988c811)
Xamarin.iOS and Xamarin.Mac SDK 13.16.0.13 (b75deaf)

Device: iPhone 7 Plus.
iOS version 13.4.1

**Comment by nhadro** [comment]
I have the same issue and it doesn't seem to depend on the device I use.  I've tried two Ipads and I get the same error on when trying to deploy to both.

**Comment by maddyleger1** [comment]
@GaboMendez @aherrick @avorobjovs @nhadro thanks everyone for the feedback - I know this is really frustrating. Unfortunately this is for issues with the documentation itself, not the product!

Instead of reporting here, can you please file this via Help > Send Feedback > Report a Problem in the IDE? Thanks!

We're aware of this problem and there is a fix in the works but you can get the most up-to-date info on Developer Community.

**Comment by torynfarr** [comment]
I *think* what's happening is that if you perform a clean and then build again, you'll find that it's building the app with a _.exe_ extension. Then, when attempting to deploy, it's looking in the debug folder for _[your app name].app_.  Not sure how to fix that just yet though.
