### ISSUE TITLE
Any documentation? Example Code?

### ISSUE THREAD

**Issue by solomonfried** [MicrosoftDocs/xamarin-docs#2671]
Does anyone have clear documentation on how this would be used. I am currently using Xamarin.Auth.Presenter.OAuthLoginPresenter and would love to see how this differs. Especially now that I am required to support and Apple sign-on starting soon (6/30/2020)

Thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 51eee071-a48a-1817-4ee7-5e29c83e3846
* Version Independent ID: f452c38e-db28-9896-e035-05cb6a985dbf
* Content: [WebAuthenticator.AuthenticateAsync(Uri, Uri) Method (Xamarin.Essentials)](https://docs.microsoft.com/en-us/dotnet/api/xamarin.essentials.webauthenticator.authenticateasync?view=xamarin-essentials#feedback)
* Content Source: [docs/en/Xamarin.Essentials/WebAuthenticator.xml](https://github.com/xamarin/Essentials/blob/live/docs/en/Xamarin.Essentials/WebAuthenticator.xml)
* Product: **xamarin**
* Technology: **xamarin-essentials**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by davidbritch** [comment]
Hi @solomonfried 

The WebAuthenticator doc has just been published: https://docs.microsoft.com/xamarin/essentials/web-authenticator?context=xamarin%2Fxamarin-forms&tabs=android
