### ISSUE TITLE
Missing explanation on how resource lookups work in xamarin.forms

### ISSUE THREAD

**Issue by Insire** [MicrosoftDocs/xamarin-docs#2672]
I'm coming from the wpf world and we got https://docs.microsoft.com/en-us/dotnet/desktop-wpf/fundamentals/xaml-resources-define#static-resource-lookup-behavior for static and dynamic resources. Would be nice to have an explanation thats relevant to xamarin aswell.

Maybe this can be expanded to also cover how to do the same lookups via c# code.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1d23ce09-1c59-1482-036a-f7348090fd00
* Version Independent ID: 9b4213b5-8278-5bea-c73d-0e172d7c0a89
* Content: [Resource Dictionaries - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/xaml/resource-dictionaries#feedback)
* Content Source: [docs/xamarin-forms/xaml/resource-dictionaries.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/xaml/resource-dictionaries.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @Insire 

Thanks for the suggestion - it's a great doc you've linked to.

I've created an issue in our backlog (https://github.com/MicrosoftDocs/xamarin-docs-pr/issues/1603) to refresh our content. Hoping to do this during April.
