### ISSUE TITLE
Get the height of TabBar

### ISSUE THREAD

**Issue by hadihashem** [MicrosoftDocs/xamarin-docs#2676]
Hello
Can you please explain how to get the height of the TabBar in PCL or plateform project?
Thank you in advance
Regards

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0c81c589-e81e-d98c-9656-695a3520a12d
* Version Independent ID: c235f6f9-47ce-15f3-b4da-cb12e219df92
* Content: [Xamarin.Forms TabbedPage - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/navigation/tabbed-page)
* Content Source: [docs/xamarin-forms/app-fundamentals/navigation/tabbed-page.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/app-fundamentals/navigation/tabbed-page.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @hadihashem 

You can't get the tab bar height from the shared code project.

**Comment by hadihashem** [comment]
@davidbritch 
Is it possible to get it from platform project?
