### ISSUE TITLE
DateTime shows only in UTC timezone.

### ISSUE THREAD

**Issue by Jonas-No** [MicrosoftDocs/xamarin-docs#2678]
The Date for a note is stored as a UTCdate (fine), but on retieving and displaying it on the NotesPage shold it not be converted to the local timezone for the device?
- How to accomplish that?, (and where?)
BTW: -This is a excellent Quickstart!
Thanks // JoNo. 

---
#### Dokumentinformation

⚠ *Redigera inte det här avsnittet. Det krävs för docs.microsoft.com ➟ länkning till GitHub-problem.*

* ID: 5ce30880-c4f0-78f7-1ee0-6507e378201e
* Version Independent ID: a6ad2818-c0d2-e3ef-1262-e143d49cc348
* Content: [Store data in a local SQLite.NET database - Xamarin](https://docs.microsoft.com/sv-se/xamarin/get-started/quickstarts/database?pivots=windows#feedback)
* Content Source: [docs/get-started/quickstarts/database.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/get-started/quickstarts/database.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @Jonas-No 

The quickstart deliberately doesn't convert to local time, as it's meant to be a fairly basic first app. With that said, it's pretty easy to convert to a local time. Given a `DateTime` object named `utcTime` it's simply `var localDateTime = utcTime.ToLocalTime();`
