### ISSUE TITLE
TextDecorations doesn't work in iOS

### ISSUE THREAD

**Issue by Wallysantos** [MicrosoftDocs/xamarin-docs#2679]
The TextDecoration property is not working properly in iOS. There is no problem in Android.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f8a6273c-62b1-ac18-aab3-62f78bdbade8
* Version Independent ID: 746bd180-ae67-313d-b949-538a508807b2
* Content: [Xamarin.Forms Label - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/text/label#feedback)
* Content Source: [docs/xamarin-forms/user-interface/text/label.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/text/label.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @Wallysantos 

Yes. There's an issue logged for it in the engineering repo, and I believe it should be fixed in the next release.

**Comment by edmlbox** [comment]
Still not fixed
