### ISSUE TITLE
So... how what and why?

### ISSUE THREAD

**Issue by BDTomasz** [MicrosoftDocs/xamarin-docs#268]
I am still unclear after reading this on how do I name my images. Lets say I have an Android asset called "my-app-logo" in my desired drawables, in XAML, Source="my-app-logo", how do I create this in iOS app?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8546adbb-ebc5-6275-82ac-3f52842cb2d4
* Version Independent ID: 1b5c925c-74b5-5450-65b4-a08cc342d06a
* Content: [Displaying an Image - Xamarin](https://docs.microsoft.com/en-us/xamarin/ios/app-fundamentals/images-icons/displaying-an-image?tabs=vswin#asset-catalogs)
* Content Source: [docs/ios/app-fundamentals/images-icons/displaying-an-image.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/ios/app-fundamentals/images-icons/displaying-an-image.md)
* Service: **xamarin**
* GitHub Login: @bradumbaugh
* Microsoft Alias: **brumbaug**

**Comment by mikehachen** [comment]
Same here. How can I use Assets in my iOS project when all my xaml's are in a pcl project? Would be nice if there is a sample project.

**Comment by mikehachen** [comment]
@BDTomasz Thanks to your description I was able to get it working! 

Thanks a lot!
Mike

**Comment by bradumbaugh** [comment]
Hi @BDTomasz and @mikehachen - glad you were able to get this working. This process is described in this document: https://docs.microsoft.com/xamarin/xamarin-forms/user-interface/images. Had you seen this doc? Hope this is helpful!

**Comment by BDTomasz** [comment]
@bradumbaugh yes, if you look at the first post from this thread, my original comment is from the document you're linking, it didn't quite answer my questions to start with, learning process I guess.

**Comment by bradumbaugh** [comment]
@BDTomasz OK, glad you found it. It looks like the link in the original post is to an iOS-specific document, which is why I was curious. I'll add a note to our internal backlog asking our Forms team if they can clarify the doc at all. Thanks for the comments!
