### ISSUE TITLE
Long Press Functionality

### ISSUE THREAD

**Issue by Stuart88** [MicrosoftDocs/xamarin-docs#2680]
Long press is bread and butter functionality for touch screen devices these days.

Is there a reason why it hasn't been included as a standard Xamarin gesture recognizer yet?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b1d849b9-e4a6-1507-4532-26daa94ffaae
* Version Independent ID: 07ae51c4-93fe-377e-ad12-41246a6f2e10
* Content: [Xamarin.Forms gestures - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/gestures/)
* Content Source: [docs/xamarin-forms/app-fundamentals/gestures/index.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/app-fundamentals/gestures/index.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @Stuart88 

It's been planned for Xamarin.Forms for a while now. But changing priorities mean that it's not happened yet.

All I can recommend is that you follow the [enhancement request](https://github.com/xamarin/Xamarin.Forms/issues/3480) in the engineering repo.

**Comment by Stuart88** [comment]
Excellent, cheers, that looks like it will definitely hit the spot for now.
