### ISSUE TITLE
Microsoft Blog references this page but uses the wrong syntax

### ISSUE THREAD

**Issue by RyanGaudion** [MicrosoftDocs/xamarin-docs#2681]
Blog Post - https://devblogs.microsoft.com/xamarin/binding-possibilities-relativesource/

Section 1 - Self has the following code:

2
3
4
&lt;BoxView 
    Color="Red"
    HeightRequest="100"
    Width="{Binding RelativeSource={RelativeSource Self}, Path=HeightRequest}"/&gt;

However this line:

 Width="{Binding RelativeSource={RelativeSource Self}, Path=HeightRequest}"/&gt;

Should be:

 Width="{Binding Source={RelativeSource Self}, Path=HeightRequest}"/&gt;

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3f73553f-8c35-877b-0a34-db9b51df93be
* Version Independent ID: d51b2ace-0519-6309-7417-d29a582a4de2
* Content: [Xamarin.Forms Relative Bindings - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/data-binding/relative-bindings)
* Content Source: [docs/xamarin-forms/app-fundamentals/data-binding/relative-bindings.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/app-fundamentals/data-binding/relative-bindings.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @RyanGaudion 

Thanks for letting me know. I've notified the blog post author and he's going to fix it.

**Comment by RyanGaudion** [comment]
@davidbritch thanks!
