### ISSUE TITLE
Redirect uri with Google

### ISSUE THREAD

**Issue by AndreasEike** [MicrosoftDocs/xamarin-docs#2682]
Hi, I've been following this tutorial but I am having problems with the callback uri and "CALLBACK_SCHEME". I am using Google for authentication and have the redirect uri set to the reversed client id from console.developers.google.com website. 
The uri is like this: "com.googleusercontent.apps.&lt;ID&gt;:/oauth2redirect"

The CALLBACK_SCHEME is the same uri. When running my login task I get directed to the google login page, but get this error: "Error: invalid_request, Required parameter is missing: response_type". I've read on Google's tutorial pages that this is a required parameter, so how do I fix this?

Thanks for this tutorial.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1231a1e1-3734-9021-2cc7-eaf99478afca
* Version Independent ID: 01e5fdbe-0b15-4dbe-f8a0-ed40f8593302
* Content: [Xamarin.Essentials: Web Authenticator - Xamarin](https://docs.microsoft.com/en-us/xamarin/essentials/web-authenticator?tabs=android#using-webauthenticator)
* Content Source: [docs/essentials/web-authenticator.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/essentials/web-authenticator.md)
* Product: **xamarin**
* Technology: **xamarin-essentials**
* GitHub Login: @Redth
* Microsoft Alias: **jodick**

**Comment by jamesmontemagno** [comment]
@Redth  are you able to comment on this?

**Comment by Redth** [comment]
I'm not sure you should be using the `com.googleusercontent.apps.<ID>` based `CALLBACK_SCHEME` here, as it might conflict with other apps registered to handle it?  In the example we use a custom scheme that is registered by your app (ie: `const string CALLBACK_SCHEME = "essentials://";`.

I'm also not sure that this is the particular cause of your issue.  It's hard to say without knowing more about what the actual URL you are invoking in the AuthenticateAsync call is.  Is it a URL on your server that kicks off the google authentication server side?  Or are you trying to skip that step and start the oauth flow directly on the client (this isn't really a supported scenario in Essentials).

**Comment by jamesmontemagno** [comment]
@AndreasEike do you have any more information here?

**Comment by davidbritch** [comment]
[Microsoft support for Xamarin](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin) will end on May 1, 2024 for all Xamarin SDKs including Xamarin.Forms. In preparation for this, all issues and PRs in this repository are being closed.

.NET MAUI is the replacement for Xamarin.Forms, and it's documentation can be found [here](https://learn.microsoft.com/dotnet/maui/?view=net-maui-8.0).
