### ISSUE TITLE
Code snippet in section "Detect and apply theme" applying inversed themes

### ISSUE THREAD

**Issue by dk-mushiyoke** [MicrosoftDocs/xamarin-docs#2685]
AppTheme.Dark should set dark theme and vice versa

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3b9ec7d2-90d5-8daa-18a3-f20ee82cc739
* Version Independent ID: 54329222-4b91-c42a-353e-31b40ac67476
* Content: [Detect dark mode in Xamarin.Forms applications - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/theming/dark-mode#feedback)
* Content Source: [docs/xamarin-forms/user-interface/theming/dark-mode.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/theming/dark-mode.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidortinau
* Microsoft Alias: **daortin**

**Comment by davidbritch** [comment]
Hi @dk-mushiyoke 

Thanks for pointing this out. I've fixed it in a PR that will go live later today.
