### ISSUE TITLE
Verbage for section 'Creating a View Model Declaratively' is ambiguous 

### ISSUE THREAD

**Issue by jbollman7** [MicrosoftDocs/xamarin-docs#2686]
Its not clear with the incomplete section, which syntax generates the view model.
  'When the ContentPage is created, an instance of the LoginViewModel is automatically constructed and set as the view's BindingContext.'
Does this mean when i build the app, the new View page will be read, and then a corresponding LoginViewModel page will be created because its referenced in the View, but it does not exist yet?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b5d7a251-6fd9-d6c9-63c6-ad2ca82a8b46
* Version Independent ID: 853f0d5e-e93f-b2d7-f01b-75c80cff8df3
* Content: [The Model-View-ViewModel Pattern - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/enterprise-application-patterns/mvvm#feedback)
* Content Source: [docs/xamarin-forms/enterprise-application-patterns/mvvm.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/enterprise-application-patterns/mvvm.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @jbollman7 

Given the code below:

```
<ContentPage ... xmlns:local="clr-namespace:eShop">  
    <ContentPage.BindingContext>  
        <local:LoginViewModel />  
    </ContentPage.BindingContext>  
    ...  
</ContentPage>
```

What will happen is when that `ContentPage` is navigated to in the app, an instance of `LoginViewModel` will be created and assigned to the `BindingContext` of the `ContentPage`.
