### ISSUE TITLE
.Net is not an option when creating a project

### ISSUE THREAD

**Issue by justdan0227** [MicrosoftDocs/xamarin-docs#2687]
Just a beginner and trying this out after having created the sample app in the first section.  When I create a multi app form, there is no .Net option that is shown on the second screen of creating an app?  Did I miss something in the install that would have included that (on a mac)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5a064123-54f2-0eb2-c76a-65b36c5ec1a7
* Version Independent ID: dbf4119a-2c24-e0f1-8041-bb3755c29c24
* Content: [Create a single page Xamarin.Forms application - Xamarin](https://docs.microsoft.com/en-us/xamarin/get-started/quickstarts/single-page?pivots=macos#feedback)
* Content Source: [docs/get-started/quickstarts/single-page.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/get-started/quickstarts/single-page.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by justdan0227** [comment]
so I created the project and was able to complete the steps.  Not sure why the .NET option was not shown when I created the app.

**Comment by davidbritch** [comment]
Hi @justdan0227 

Glad you were able to unblock yourself.
