### ISSUE TITLE
What the ... Frank?

### ISSUE THREAD

**Issue by BDTomasz** [MicrosoftDocs/xamarin-docs#269]
I hate reading stuff on the screen, and respect my eyes, tried to print this page from my Firefox browser, gives me 1 page...?!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 87b678e7-5336-db4f-02ac-db6d2115ebec
* Version Independent ID: 5434c705-8fa7-f2ed-e358-6c05d915cde0
* Content: [Material Theme - Xamarin](https://docs.microsoft.com/en-us/xamarin/android/user-interface/material-theme)
* Content Source: [docs/android/user-interface/material-theme.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/android/user-interface/material-theme.md)
* Service: **xamarin**
* GitHub Login: @mgmclemore
* Microsoft Alias: **mamcle**

**Comment by mgmclemore** [comment]
Hi @BDTomasz, this is a [known Firefox limitation](https://support.mozilla.org/en-US/questions/1100801) that is not unique to this site. As a workaround, I've had success using the [Firefox Reader](https://support.mozilla.org/en-US/kb/firefox-reader-view-clutter-free-web-pages) to print multi-page docs. Alternately, you can use a different browser like Chrome or Edge.
