### ISSUE TITLE
return a result on iOS or UWP?

### ISSUE THREAD

**Issue by thomiel** [MicrosoftDocs/xamarin-docs#2693]
How would this look like, if the Action would need to return a result. With Android, this is really straight forward by returning a value in the JSBridge exports. But I'm struggling with iOS...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9c1bd30c-6e7a-df38-8c20-dff7361e901f
* Version Independent ID: 013c6027-db9a-6039-3404-2e4f717133a9
* Content: [Customizing a WebView - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/custom-renderer/hybridwebview#feedback)
* Content Source: [docs/xamarin-forms/app-fundamentals/custom-renderer/hybridwebview.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/app-fundamentals/custom-renderer/hybridwebview.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @thomiel 

This [blog post](https://theconfuzedsourcecode.wordpress.com/2020/02/02/pushing-the-limits-of-hybrid-webview-in-xamarin-forms/) has a good overview of how to do this.
