### ISSUE TITLE
Please add geofence

### ISSUE THREAD

**Issue by wml2017** [MicrosoftDocs/xamarin-docs#2698]
Could you add geofence at background (and foreground)? This is very useful feature

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f0acf3fa-b705-f0cc-b676-eeca60176dfa
* Version Independent ID: 1788a5d5-a3cb-15c8-927c-b6a24810245a
* Content: [Xamarin.Essentials: Geolocation - Xamarin](https://docs.microsoft.com/en-us/xamarin/essentials/geolocation?context=xamarin%2Fxamarin-forms&tabs=ios)
* Content Source: [docs/essentials/geolocation.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/essentials/geolocation.md)
* Product: **xamarin**
* Technology: **xamarin-essentials**
* GitHub Login: @jamesmontemagno
* Microsoft Alias: **jamont**

**Comment by jamesmontemagno** [comment]
Thanks for the feature request. We track them on the github repo and we do have one open here: https://github.com/xamarin/Essentials/issues/270
