### ISSUE TITLE
Speak at the background model

### ISSUE THREAD

**Issue by wml2017** [MicrosoftDocs/xamarin-docs#2699]
Can you allow it speaks when Android/iPhone is locked. I mean allow text-to-speak works at the background

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c941b98c-cfe4-a6c9-2117-f5f0d2f5a7f8
* Version Independent ID: 7fe2d995-09dd-2dce-2dbf-7f49e6d7c3f1
* Content: [Xamarin.Essentials: Text-to-Speech - Xamarin](https://docs.microsoft.com/en-us/xamarin/essentials/text-to-speech?context=xamarin/xamarin-forms)
* Content Source: [docs/essentials/text-to-speech.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/essentials/text-to-speech.md)
* Product: **xamarin**
* Technology: **xamarin-essentials**
* GitHub Login: @jamesmontemagno
* Microsoft Alias: **jamont**

**Comment by jamesmontemagno** [comment]
The text to speech engines top executing when the app is in the background or device is locked. I am pretty sure that this is an API limitation as it is not classified as music. You can open an issue at https://github.com/xamarin/essentials
