### ISSUE TITLE
Xamarin.Forms CollectionView - Image does not Load

### ISSUE THREAD

**Issue by githubkarthik** [MicrosoftDocs/xamarin-docs#2700]
I tried using the CollectionView @ https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/collectionview/

The images are NOT loaded onto the IMAGE control available inside the Grid of the DataTemplate.
However, the images from the URL on the Sample are loading directly on Browsers (validated)

Also, I downloaded each image from the URL and added the files explicitly to the RESOURCES folder under drawable. While the images are loaded in a standa-alone IMAGE control, they are not loading inside the IMAGE control in datatemplate.

Any suggestions?

**Comment by davidbritch** [comment]
Hi @githubkarthik 

They are loading just fine for me, from the URLs:

![Screenshot_1586338564](https://user-images.githubusercontent.com/8092460/78769163-dc7c5080-7984-11ea-86ec-6f5502243a29.png)

I'd recommend ensuring you are using the latest version of Xamarin.Forms. There have been issues with loading images in some recent releases.
