### ISSUE TITLE
missing semicolon

### ISSUE THREAD

**Issue by maklmor** [MicrosoftDocs/xamarin-docs#2701]
Hi, it's pretty much unimportent, but you misspelled " ; " and instead wrote " , " in second code window - first assignment of string _filename.
I just wanted to let you know, sorry if it's inconvenient.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5a064123-54f2-0eb2-c76a-65b36c5ec1a7
* Version Independent ID: dbf4119a-2c24-e0f1-8041-bb3755c29c24
* Content: [Create a single page Xamarin.Forms application - Xamarin](https://docs.microsoft.com/en-us/xamarin/get-started/quickstarts/single-page?pivots=win-vs2017#feedback)
* Content Source: [docs/get-started/quickstarts/single-page.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/get-started/quickstarts/single-page.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @maklmor 

I'm struggling to locate the error. Can you let me know if it's VS2019, VS2017, or VS Mac, and the number of the code block with the error on _filename?
