### ISSUE TITLE
Multiple Pins From an API call results in null.

### ISSUE THREAD

**Issue by krcole** [MicrosoftDocs/xamarin-docs#2703]
When I try to add multiple pins from an API call, the map renders before my custom pins can all be saved to customPins.  So when the getMarkers function is called when clicking on a marker, it returns null.  If I add them without doing the API, everything works perfectly.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 591d1079-dec9-5797-eb4f-4d11b56fcbd9
* Version Independent ID: 0169a2c9-a004-d5fd-7a24-855664f2d8b5
* Content: [Customizing a Map Pin - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/custom-renderer/map/customized-pin#feedback)
* Content Source: [docs/xamarin-forms/app-fundamentals/custom-renderer/map/customized-pin.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/app-fundamentals/custom-renderer/map/customized-pin.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @krcole 

That map renderer was only designed to render pins that are available when the map is first drawn. To extend it for your scenario you've need to override (in each renderer) `OnElementPropertyChanged` and when the custom pins collection changes you'll need to call a method that updates the map with the pin details. See https://github.com/xamarin/Xamarin.Forms/blob/8a458aebef77d6a7b2614cfdb1b3aaadd3396015/Xamarin.Forms.Maps.iOS/MapRenderer.cs#L182 for an example of the pattern.
