### ISSUE TITLE
help me to be familiar with this code

### ISSUE THREAD

**Issue by sqbsid** [MicrosoftDocs/xamarin-docs#2706]
Why did you define 'Filename' property in models folder? what is its use when You don't have have any input from the user as Filename?

"var filename = Path.Combine(App.FolderPath, $"{Path.GetRandomFileName()}.notes.txt");" what is meaning of this line of code?

**Comment by davidbritch** [comment]
`$"{Path.GetRandomFileName()}.notes.txt")` generates a random file name, and appends ".notes.txt" to the end of it.

The filename is then combined to the folder stored in `App.FolderPath`, and assigned to the `filename` field.
