### ISSUE TITLE
How to add new field in the existing code?

### ISSUE THREAD

**Issue by sqbsid** [MicrosoftDocs/xamarin-docs#2707]
I want to add a title of the note and want to display it on the main page.

**Comment by davidbritch** [comment]
Hi @sqbsid 

Modify the model, the UI, and the UI code behind.

**Comment by sqbsid** [comment]
I did the same thing, but I'm stuck in code behind. How to display "Title"?
Like I'm doing to display "Text = File.ReadAllText(filename)",
"Title = File.ReadAllText(filename)", it's not working.
what method do I use to get display?
