### ISSUE TITLE
Wrong tag used in code example under 'Efficient page loading'

### ISSUE THREAD

**Issue by RasmusKoldsoe** [MicrosoftDocs/xamarin-docs#2708]
In code example under section 'Efficient page loading' line 15 the tag ShellContent is used but should be Tab.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ef7242a0-d46e-19ea-e22d-f327dcc9b3e9
* Version Independent ID: f050be8e-9413-19e7-5799-90a55c4e5bfb
* Content: [Xamarin.Forms Shell Layout - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/shell/tabs#feedback)
* Content Source: [docs/xamarin-forms/app-fundamentals/shell/tabs.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/app-fundamentals/shell/tabs.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @RasmusKoldsoe 

`ShellContent` is valid in that scenario, because there's an implicit conversion operator that automatically wraps in in a `Tab`.
