### ISSUE TITLE
I dont like custom renderer pfd

### ISSUE THREAD

**Issue by PinkoAgrawal** [MicrosoftDocs/xamarin-docs#271]
https://docs.microsoft.com/en-us/xamarin/xamarin-forms/creating-mobile-apps-xamarin-forms/summaries/chapter27
The above provided pdf is useless why because mostly useful concepts like Tabbed renderer & NavigationPageRenderer is not available. I wonder what is the use of writing long pdf's or documentation if you not giving frequently used topics. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 950254b9-e60b-d70c-a872-8b5387d1dd83
* Version Independent ID: 9f5ab51a-cd31-372a-562f-a0e2c13adb26
* Content: [Summary of Chapter 27. Custom renderers - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/creating-mobile-apps-xamarin-forms/summaries/chapter27#feedback)
* Content Source: [docs/xamarin-forms/creating-mobile-apps-xamarin-forms/summaries/chapter27.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/creating-mobile-apps-xamarin-forms/summaries/chapter27.md)
* Service: **xamarin**
* GitHub Login: @charlespetzold
* Microsoft Alias: **chape**

**Comment by davidbritch** [comment]
Hi @PinkoAgrawal 

Thanks for the feedback. For examples of `TabbedPage` and `NavigationPage` renderers, see the [eShopOnContainers](https://github.com/dotnet-architecture/eShopOnContainers) repo.
