### ISSUE TITLE
Add warning BarBackgroundColor BarTextColor overrides UnSelectedTabColor and SelectedTabColor

### ISSUE THREAD

**Issue by pmahend1** [MicrosoftDocs/xamarin-docs#2710]
If `BarBackgroundColor` and `BarTextColor` are used along with `UnSelectedTabColor` and `SelectedTabColor` the former overrides the latter. Please add this warning to the documentation. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0c81c589-e81e-d98c-9656-695a3520a12d
* Version Independent ID: c235f6f9-47ce-15f3-b4da-cb12e219df92
* Content: [Xamarin.Forms TabbedPage - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/navigation/tabbed-page#feedback)
* Content Source: [docs/xamarin-forms/app-fundamentals/navigation/tabbed-page.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/app-fundamentals/navigation/tabbed-page.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @pmahend1 

That doesn't quite seem to be the case for a quick test I did. Given a `TabbedPage` with the following colours set:

```
            BarBackgroundColor="Red"
            BarTextColor="Green"
            SelectedTabColor="Blue"
            UnselectedTabColor="Yellow"
```

I received the following result:

![Screenshot_1586339898](https://user-images.githubusercontent.com/8092460/78771412-06834200-7988-11ea-86f3-1b46493328c8.png)

So the only colour missing here is Red.

**Comment by pmahend1** [comment]
May be I had issue with older xamarin forms version and I was expecting `SelectedTabColor` and `UnSelectedTabColor` would override selectedtab's text color and unselected tab's text color. But looks like thats default behavior.

**Comment by pmahend1** [comment]
May be I had issue with older xamarin forms version and I was expecting `SelectedTabColor` and `UnSelectedTabColor` would override selectedtab's text color and unselected tab's text color which is Green in this case. But looks like that's default behavior.
