### ISSUE TITLE
Excellent article

### ISSUE THREAD

**Issue by delaney31** [MicrosoftDocs/xamarin-docs#2713]
This is an excellent article! I was wondering though if you could expand a bit on some of the other IOC containers such as AutoFac and Prism and how they compare to TinyIoc when creating Xamarin Forms applications with MVVM?  Also is there any plan to enhance Xamarin Forms to add some of these Dependency Injection features?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 496aefc1-60e7-3484-12d1-ba383cfc099b
* Version Independent ID: 35133eba-8bc2-a54e-b341-d873f9a3c468
* Content: [Dependency Injection - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/enterprise-application-patterns/dependency-injection#feedback)
* Content Source: [docs/xamarin-forms/enterprise-application-patterns/dependency-injection.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/enterprise-application-patterns/dependency-injection.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @delaney31 

See https://github.com/dotnet-architecture/eShopOnContainers/issues/914 for a discussion of Autofac vs TinyIoC, and a link to IoC container performance on the Xamarin platform. Hope it helps.

There are some plans around Xamarin.Forms and DI but afraid I can't say more than that right now.
