### ISSUE TITLE
What about apps that reference nuget packages having a dependency on support libraries?

### ISSUE THREAD

**Issue by PaulVrugt** [MicrosoftDocs/xamarin-docs#2714]
We are trying to migrate from support libraries to androidX in our Xamarin.Forms apps. However, we have some nuget packages included that have a dependency on a support library. (like xamarin.auth) This dependency causes errors during the build process when trying to use androidx. This article doesn't speak a single word about such a situation. Is there a way to work around this issue? Or is it impossible to migrate to androidX while referencing nuget packages having a dependency on a support library?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2c3fb215-91c9-b6bb-1f47-558dd2d4801c
* Version Independent ID: 6cf63a49-569d-c910-6b22-6734d99e473a
* Content: [AndroidX Migration in Xamarin.Forms - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/platform/android/androidx-migration#feedback)
* Content Source: [docs/xamarin-forms/platform/android/androidx-migration.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/platform/android/androidx-migration.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @profexorgeek
* Microsoft Alias: **jusjohns**

**Comment by davidbritch** [comment]
Hi @PaulVrugt 

AndroidX migration should auto migrate all the support libraries, including those used by other NuGet packages. The only error you should be receiving is a message indicating which AndroidX packages need installing into your project. If you still receive errors after doing that, then something maybe broken with AndroidX migration that needs fixing. If you believe AndroidX migration is broken, you need to open an issue in the [engineering repo](https://github.com/xamarin/Xamarin.Forms/).
