### ISSUE TITLE
NewLine for a Label

### ISSUE THREAD

**Issue by WillAutioItrax** [MicrosoftDocs/xamarin-docs#2715]
Can you add how to force text to a new line for a Label.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f8a6273c-62b1-ac18-aab3-62f78bdbade8
* Version Independent ID: 746bd180-ae67-313d-b949-538a508807b2
* Content: [Xamarin.Forms Label - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/text/label#feedback)
* Content Source: [docs/xamarin-forms/user-interface/text/label.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/text/label.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @WillAutioItrax 

There are two main options from XAML:

```
        <Label Text="First line &#10; Second line" />
        <Label>
            <Label.Text>
                First line
                Second line
            </Label.Text>
        </Label>
```

I'll get the doc updated.

**Comment by davidbritch** [comment]
I've fixed this in a PR, that will go live later.

**Comment by WillAutioItrax** [comment]
Hi @davidbritch That is awesome - thanks!
