### ISSUE TITLE
Universal Links uses a different AppDelegate callback method

### ISSUE THREAD

**Issue by kanderson-wellbeats** [MicrosoftDocs/xamarin-docs#2716]
If you're using this class your app is necessarily already running, and if you also use Universal Links (as is advised) then AppDelegate.OpenUrl is not called, it's actually AppDelegate.ContinueUserActivity that gets called. You have to then call Xamarin.Essentials.Platform.OpenUrl from there otherwise your WebAuthenticator.AuthenticateAsync task will never return.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1231a1e1-3734-9021-2cc7-eaf99478afca
* Version Independent ID: 01e5fdbe-0b15-4dbe-f8a0-ed40f8593302
* Content: [Xamarin.Essentials: Web Authenticator - Xamarin](https://docs.microsoft.com/en-us/xamarin/essentials/web-authenticator?tabs=ios#feedback)
* Content Source: [docs/essentials/web-authenticator.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/essentials/web-authenticator.md)
* Product: **xamarin**
* Technology: **xamarin-essentials**
* GitHub Login: @Redth
* Microsoft Alias: **jodick**

**Comment by jamesmontemagno** [comment]
@redth are you able to comment on this one.
