### ISSUE TITLE
Change in method name of Browser Class 

### ISSUE THREAD

**Issue by Im-PJ** [MicrosoftDocs/xamarin-docs#272]
there is no Browser.RequestAsync method available. It should be Browser.OpenAsync 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0e1cc45d-67d0-81bf-918f-85da4c143c93
* Version Independent ID: 9143201f-a3a5-d283-ba8a-e84c471e9a0b
* Content: [Xamarin.Essentials Open Browser - Xamarin](https://docs.microsoft.com/en-us/xamarin/essentials/open-browser?context=xamarin%2Fandroid&tabs=android)
* Content Source: [docs/essentials/open-browser.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/essentials/open-browser.md)
* Service: **xamarin**
* GitHub Login: @jamesmontemagno
* Microsoft Alias: **jamont**

**Comment by bradumbaugh** [comment]
Thanks @Im-PJ. A fix for this should be published soon.
