### ISSUE TITLE
UWP images in root dir

### ISSUE THREAD

**Issue by sjorsmiltenburg** [MicrosoftDocs/xamarin-docs#2721]
This document does not refer to the option to put images for UWP in another place then the root folder  which, in my opinion, is an inconvenient default location

The option I am referring to is add
windows:Application.ImageDirectory="your_Images_dir"
to the <Application> node in the app.xaml

**Comment by davidbritch** [comment]
Hi @sjorsmiltenburg 

Which doc?

**Comment by sjorsmiltenburg** [comment]
sorry I thought this github repo belonged to that document since i ended up here after pressing somewhere at the bottom of the doc so end in feedback.

I was talking about this doc https://docs.microsoft.com/nl-nl/xamarin/xamarin-forms/user-interface/images?tabs=macos&source=docs#local-images

**Comment by davidbritch** [comment]
Hi @sjorsmiltenburg 

I've fixed the doc, in a PR that will go live around this time tomorrow.
