### ISSUE TITLE
Cells no longer respond to taps

### ISSUE THREAD

**Issue by codebeaulieu** [MicrosoftDocs/xamarin-docs#2724]
Adding a Swipe view seems to kill the cell tapped event. Could we either allow taps to trigger that event somehow, or simply add a command to the SwipeView container that I can bind to?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 02d932c9-7483-c314-b1c6-3850778cd6dc
* Version Independent ID: 8ab4f230-a8ff-5164-d377-b0b12cac5f09
* Content: [Xamarin.Forms SwipeView - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/swipeview)
* Content Source: [docs/xamarin-forms/user-interface/swipeview.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/swipeview.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by tallichet** [comment]
I think It's linked, but the selection in a ListView does not work anymore when you have a SwipeView in the CellItem.

**Comment by davidbritch** [comment]
Hi @codebeaulieu and @tallichet 

Afraid this isn't a question for the docs repo. It's best asked in the [engineering repo](https://github.com/xamarin/Xamarin.Forms/).

But I will point out that the `SwipeItemView` has `Command` and `CommandParameter` properties, and also that `CollectionView` is now recommended over `ListView`.
