### ISSUE TITLE
Update examples to use .ConfigureAwait(false)

### ISSUE THREAD

**Issue by ndastur** [MicrosoftDocs/xamarin-docs#2727]
I think it would be correct to update the samples to use .ConfigureAwait(false) on all the awaited methods

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: da75050f-bfda-4792-40d9-b9a25d649d3e
* Version Independent ID: 5c44f996-765b-f6e4-c807-9446c534d50b
* Content: [Xamarin.Essentials: Secure Storage - Xamarin](https://docs.microsoft.com/en-us/xamarin/essentials/secure-storage?tabs=android)
* Content Source: [docs/essentials/secure-storage.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/essentials/secure-storage.md)
* Product: **xamarin**
* Technology: **xamarin-essentials**
* GitHub Login: @jamesmontemagno
* Microsoft Alias: **jamont**

**Comment by jamesmontemagno** [comment]
I think it is best to leave that to the developer based on their app and their methods. Looking at other documentation on .NET things they do not document with ConfigureAwait(false) as we dont' know if devs need it to come back on the original context or not.
