### ISSUE TITLE
How to use css variables?

### ISSUE THREAD

**Issue by TheBlue-1** [MicrosoftDocs/xamarin-docs#2728]
I tried to use them as normal but I get the very nice Exception : "Exception of type 'System.Exception' was thrown." when I start the app. Is there a way to use variales?

**Comment by davidbritch** [comment]
Hi @TheBlue-1 

For which feature of which product?

**Comment by TheBlue-1** [comment]
@davidbritch 
for styling xamarin forms with css

**Comment by davidbritch** [comment]
Hi @TheBlue-1 

Afraid CSS variables aren't supported. I'll update the doc to say so.

**Comment by davidbritch** [comment]
I've updated the doc in a PR that will go live later today.
