### ISSUE TITLE
Native Animation

### ISSUE THREAD

**Issue by realivanjx** [MicrosoftDocs/xamarin-docs#2729]
Will TapGestureRecognizer add native animation effect to the control we set to? Like a ripple effect on android platform when we tap on it?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1e56a604-3af6-80e9-b9df-382e3102a098
* Version Independent ID: 29cc319e-2736-013c-7934-b4335eb8242d
* Content: [Adding a tap gesture recognizer - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/gestures/tap)
* Content Source: [docs/xamarin-forms/app-fundamentals/gestures/tap.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/app-fundamentals/gestures/tap.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @realivanjx 

Afraid not. You'd have to write your own code to do this.
