### ISSUE TITLE
uhhhhhhhh this is absolutely useless!!

### ISSUE THREAD

**Issue by Rob97** [MicrosoftDocs/xamarin-docs#2730]
I need to know what is the setting for infinite and how to set millisecond timeout!!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ed43b8ff-669f-cd72-bf1d-0af6e775e63e
* Version Independent ID: 664a16f0-9da3-8549-42fc-a113bf84364e
* Content: [GeolocationRequest.Timeout Property (Xamarin.Essentials)](https://docs.microsoft.com/en-us/dotnet/api/xamarin.essentials.geolocationrequest.timeout?view=xamarin-essentials#feedback)
* Content Source: [docs/en/Xamarin.Essentials/GeolocationRequest.xml](https://github.com/xamarin/Essentials/blob/live/docs/en/Xamarin.Essentials/GeolocationRequest.xml)
* Product: **xamarin**
* Technology: **xamarin-essentials**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by Rob97** [comment]
No thanks to this documentation but for anyone else with the same problem:
 TimeSpan(Int32, Int32, Int32, Int32, Int32)	
Initializes a new instance of the TimeSpan structure to a specified number of days, hours, minutes, seconds, and milliseconds.

https://docs.microsoft.com/en-us/dotnet/api/system.timespan.-ctor?view=netframework-4.8

**Comment by jamesmontemagno** [comment]
If you do not set a timespan then the default would be infinite.
