### ISSUE TITLE
Confusing explanation

### ISSUE THREAD

**Issue by edmlbox** [MicrosoftDocs/xamarin-docs#2732]
This topic can be explained much more simpler.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 13b6227e-5c43-097e-20f7-efe87b04b852
* Version Independent ID: a8e09565-d055-07ad-ba11-1e78f1564d64
* Content: [The Xamarin.Forms Command Interface - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/data-binding/commanding#feedback)
* Content Source: [docs/xamarin-forms/app-fundamentals/data-binding/commanding.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/app-fundamentals/data-binding/commanding.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Thanks for your feedback @edmlbox
