### ISSUE TITLE
how to use Custom ViewModel Navigation With MasterDetailPage

### ISSUE THREAD

**Issue by TrueTech-Source** [MicrosoftDocs/xamarin-docs#2735]
0

Im Using Custom ViewModelFirst Navigation .Reference of navigation is here https://docs.microsoft.com/en-us/xamarin/xamarin-forms/enterprise-application-patterns/navigation

I have implemented this navigation with ViewModel working fine.But With the MasterDetailPage. The page is not becoming the child of MasterPage. How i should navigate so that the views become the childView of the MasterPage(Parrent Page).
```
` private async Task InternalNavigateToAsync(Type viewModelType, object parameter)
        {
            try
            {
                Page page = CreatePage(viewModelType, parameter);
                if (page is MasterMainPage)
                {
                    Application.Current.MainPage = new CustomNavigationPage(page);
                }
                else
                {
                    var navigationPage = Application.Current.MainPage as CustomNavigationPage;
                    if (navigationPage != null)
                    {
                        await (App.Current.MainPage as MasterDetailPage).Detail.Navigation.PushAsync(page);
                        //var masterMainPage = Startup.ServiceProvider?.GetService<MasterMainPage>();
                        //masterMainPage.Detail = page;
                        // await navigationPage.PushAsync(page);

                    }
                    else
                    {
                        Application.Current.MainPage = new CustomNavigationPage(page);
                    }
                }
                await (page.BindingContext as ViewModelBase).OnAppearing(parameter);
            }
            catch (Exception ex)
            {

                throw;
            }
        }
```
`
In the Code I'm setting the MasterDetailPage as Root and using navigation. I'm Not understanding how i should add the different views to the child of MasterDetailPage.

**Comment by davidbritch** [comment]
Hi @TrueTech-Source 

Hi @zubair1995 

As the docs say, the `NavigationService` is only designed to work with `ContentPage` objects, using hierarchical navigation. It will require substantial re-working to work with a `MasterDetailPage`.
