### ISSUE TITLE
Custom Navigation With MasterDetailPage

### ISSUE THREAD

**Issue by zubair1995** [MicrosoftDocs/xamarin-docs#2736]
Im Using Custom ViewModelFirst Navigation .Reference of navigation is here 
[https://docs.microsoft.com/en-us/xamarin/xamarin-forms/enterprise-application-patterns/navigation](url)
Navigation is missing with masterDetailpage.when Going to implement this navigation the Child views not becoming the childs of masterDetailpage.

**Comment by zubair1995** [comment]
How to use this navigation with masterDetailPage

**Comment by zubair1995** [comment]
@davidbritch  Any Salution navigation with master detail page

**Comment by davidbritch** [comment]
Hi @zubair1995 

As the docs say, the `NavigationService` is only designed to work with `ContentPage` objects, using hierarchical navigation. It will require substantial re-working to work with a `MasterDetailPage`.
