### ISSUE TITLE
problem with entailment

### ISSUE THREAD

**Issue by 1mohmmad4** [MicrosoftDocs/xamarin-docs#2737]
when i make certificate for apple push notification for my app and create new certificate for publishing and new profile to distribute

when i want to distribute with my new profile push notification not appear in my entailment

<img width="583" alt="Screen Shot 1441-08-22 at 10 11 26 AM" src="https://user-images.githubusercontent.com/48172148/79308646-a4838900-7f01-11ea-8d90-42bba10ef099.png">

**Comment by PureWeen** [comment]
Hello @1mohmmad4 

This repository is for docs related issues.

If you're still having issues please try asking them here
https://forums.xamarin.com/
or on Stackoverflow
