### ISSUE TITLE
How I know what invalid XAML in my pages?!

### ISSUE THREAD

**Issue by SuperXCode** [MicrosoftDocs/xamarin-docs#2738]
why when remove xamlc it's work fine?
How I know what invalid XAML in my pages?!

what about this?
GdSrchPG.InitializeComponent ()
Khawarizm.Views.GeyodNS.GdSrchPG..ctor () <0x1065df7d0 + 0x00193> in <1ca04ac67cfa4e54bb6f39702d3e64c4#0b94f4fd871a01a3eb09ab40db6ea41a>:0
MasterMainPage.NavigateFromMenu (Khawarizm.Models.Enums.MenuEnum menuEnum, System.Boolean isHistory)
MasterMainPage.GdSrchPG_Clicked (System.Object sender, System.EventArgs e)
AsyncMethodBuilderCore+<>c.b__7_0 (System.Object )
NSAsyncSynchronizationContextDispatcher.Apply ()
(wrapper managed-to-native) UIKit.UIApplication.UIApplicationMain(int,string[],intptr,intptr)
UIApplication.Main (System.String[] , System.IntPtr , System.IntPtr )
UIApplication.Main (System.String[] , System.String , System.String )
Application.Main (System.String[] args)

**Comment by davidbritch** [comment]
Hi @SuperXCode 

You can find out what XAML is invalid by enabling XAMLC, and enabling compiled bindings.
