### ISSUE TITLE
Quoting mistake

### ISSUE THREAD

**Issue by CeciAc** [MicrosoftDocs/xamarin-docs#2739]
@DisDes commented on [Wed Apr 15 2020](https://github.com/MicrosoftDocs/xamarin-docs.de-de/issues/41)

Hello, i think there is a mistake in the fist XAML-Quote on this page:

xmlns:controls="clr-namespace:MyCompany.Controls;assembly="MyCompany.Controls"

there are three Quoting-Signs

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 3a849344-bfe7-89eb-3949-10591484a2cf
* Version Independent ID: 8be4b6ea-3cd8-8d74-58db-b07dcdf78ab6
* Content: [Benutzerdefinierte XAML-Namespace Schemas in xamarin. Forms - Xamarin](https://docs.microsoft.com/de-de/xamarin/xamarin-forms/xaml/custom-namespace-schemas#feedback)
* Content Source: [docs/xamarin-forms/xaml/custom-namespace-schemas.md](https://github.com/MicrosoftDocs/xamarin-docs.de-DE/blob/live/docs/xamarin-forms/xaml/custom-namespace-schemas.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

---

@srvbpigh commented on [Wed Apr 15 2020](https://github.com/MicrosoftDocs/xamarin-docs.de-de/issues/41#issuecomment-614055746)

Hello, @DisDes
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by davidbritch** [comment]
I've just fixed this in a PR that will go live later today.
