### ISSUE TITLE
Visual Studio 15.8 Preview 1 link is wrong or at least confusing

### ISSUE THREAD

**Issue by jg11jg** [MicrosoftDocs/xamarin-docs#274]
"Install Visual Studio 15.8 Preview 1 – This version of Visual Studio provides IDE support for starting the Google Android Emulator with Hyper-V support."  However, the link from "Install Visual Studio 15.8 Preview 1" actually goes to https://aka.ms/hyperv-emulator-dll which links to Xamarin.VisualStudio.Alpha.4.10.0.1659672-3b3bfc4.vsix.  I'm fairly new to android development on visual studio/xamarin but it feels like the link and the linked to do not correspond correctly.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4e37d642-2051-8d70-9968-dfb484122a6a
* Version Independent ID: 178ea80c-2b99-0c44-eeb6-9db319439b33
* Content: [Android Emulator Hardware Acceleration - Xamarin](https://docs.microsoft.com/en-us/xamarin/android/get-started/installation/android-emulator/hardware-acceleration?tabs=vswin)
* Content Source: [docs/android/get-started/installation/android-emulator/hardware-acceleration.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/android/get-started/installation/android-emulator/hardware-acceleration.md)
* Service: **xamarin**
* GitHub Login: @mgmclemore
* Microsoft Alias: **mamcle**

**Comment by mgmclemore** [comment]
Hi @jg11jg, thanks for the feedback!  The preview is now available [here](https://www.visualstudio.com/vs/preview/) -- the link has been updated and should be published soon.
