### ISSUE TITLE
How to hide the left navigation pane?

### ISSUE THREAD

**Issue by pstricks-fans** [MicrosoftDocs/xamarin-docs#2740]
The left navigation pane on the docs.microsoft.com is distracting if we cannot hide it when reading on the computer's browser.

Zooming in with Ctrl+mouse scroll can automatically hide the pane but the font becomes too large. It makes another problem: we have to scroll horizontally for viewing the code. It is very unpleasant.

If you don't mind, please make docs.microsoft.com more convenient for reading on screen without having to scroll horizontally.

Thank you in advance.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 331f13da-6195-a9dd-5ccb-17c2ad5bd7a5
* Version Independent ID: 58be4a57-baf9-fa3e-c400-2008cb1aa3ee
* Content: [Creating XAML Markup Extensions - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/xaml/markup-extensions/creating)
* Content Source: [docs/xamarin-forms/xaml/markup-extensions/creating.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/xaml/markup-extensions/creating.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @pstricks-fans 

This is an issue for the MicrosoftDocs/feedback repo, so I'm going to move the issue there.

**Comment by pstricks-fans** [comment]
Done. https://github.com/MicrosoftDocs/feedback/issues/2725
