### ISSUE TITLE
The instructions don't seem to work on Visual Studio Mac 2019 Community

### ISSUE THREAD

**Issue by Jptasznik** [MicrosoftDocs/xamarin-docs#2743]
I followed the steps and it is giving the following:
using Xamarin.Forms.Platform.MacOS; 

It Says the MacOS namespace does not exist in Xamarin.Forms.Platform name space.

Any ideas?  
Is MacOs on forms dead?

**Comment by davidbritch** [comment]
Hi @Jptasznik 

Are you talking about this doc: https://docs.microsoft.com/xamarin/xamarin-forms/platform/other/mac

I just used it to add a macOS project to an existing Xamarin.Forms solution, and it worked just fine.
