### ISSUE TITLE
This does not work with Visual Studio Mac 2019 Community 

### ISSUE THREAD

**Issue by Jptasznik** [MicrosoftDocs/xamarin-docs#2745]
I tried to use this walk through and it does not work and it doesn't seem to matter which version of the Nuget package I use.  It always says that it can not find the name space Xamarin.Forms.Platform.MacOS and so the FormsApplicationDelegate is not found.   Any help please.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 35a28b49-e47c-fca9-69e4-c261f2869e9a
* Version Independent ID: db9d6201-0042-eb0c-7b86-80089b543674
* Content: [Mac Platform Setup - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/platform/other/mac#feedback)
* Content Source: [docs/xamarin-forms/platform/other/mac.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/platform/other/mac.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davehump** [comment]
@Jptasznik i've just followed the instructions on the page specified and had no issues with it finding the Xamarin.Forms.Platform.MacOS namespace or the FormsApplicationDelegate class so i dont think this is a documentaton issue.

Can you check you are on the latest version of Visual Studio for mac and that you are using the latest stable version of the nuget(currently 4.5.0.617).

If you still have any issue you should log it with on the Developer community portal -> https://developercommunity.visualstudio.com/spaces/41/index.html

Regards
