### ISSUE TITLE
UIWebView Deprecation and App Store Rejection

### ISSUE THREAD

**Issue by suleman-jalil-devbox** [MicrosoftDocs/xamarin-docs#2746]
A preview version of the linker is available to fix this issue. To enable the preview, you will need to supply an additional argument
 --optimize=experimental-xforms-product-type to the linker.

The prerequisites for this to work are:
    Xamarin.Forms 4.5 or higher – Pre-release versions of Xamarin.Forms 4.5 can be used.
    Xamarin.iOS 13.10.0.17 or higher – Check your Xamarin.iOS version in Visual Studio. This version of Xamarin.iOS is included with Visual Studio for Mac 8.4.1 and Visual Studio 16.4.3.
    Remove references to UIWebView – Your code should not have any references to UIWebView or any classes that make use of UIWebView.
---------------------------------------------------------------------------------
I am using the latest xamarin forms 4.5. Did not found any reference to UIWebView.
I am using ReactiveUI.XamForms 8.7.2 . My application crashes now.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ef31dc71-3610-6c18-2bda-d0bb70804c92
* Version Independent ID: 02f7dc7b-541b-4b82-b33c-4e974fb94d8c
* Content: [Xamarin.Forms WebView - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/webview?tabs=windows#feedback)
* Content Source: [docs/xamarin-forms/user-interface/webview.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/webview.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by kastus2** [comment]
After adding --optimize=experimental-xforms-product-type to MTouch extra arguments, i still see the same warning from Apple for the Xamarin iOS group. I see there are no references from the App to any UIWebView. I see from the logs that these arguments are taken in the build.

Visual Studio for Mac - 8.5.3
Xamarin.Mac 6.14.1.39
Mono 6.8.0.123
XCode 11.4
Version: 13.16.0.13

Thanks
Shreyas

**Comment by suleman-jalil-devbox** [comment]
@kastus2

You will have to make these changes in the Release mode. Xamarin.Forms must be 4.5 or higher.

**Comment by kastus2** [comment]
Thats correct. Its Xamarin Forms 4.5.0 and Release mode.

**Comment by suleman-jalil-devbox** [comment]
@kastu2
Yes, configuration must be  set to 
"Release Mode" with platform set to "Iphone" .
Also setting up the linker to "SDK Only" or "Link All".
I was able to remove the warning message from Apple. You can see the below blog, if it helps.
https://devblogs.microsoft.com/xamarin/uiwebview-deprecation-xamarin-forms/

**Comment by kastus2** [comment]
@suleman-jalil-devbox 
Let me know if you have any inputs and what options to try out.
1.	In our project file, I am already using MTouch arguments as below.
    <MtouchExtraArgs>--compiler:clang++ --gcc_flags "-framework Security" --gcc_flags -finalize --gcc_flags "-finalized-product ${ProjectDir}/bin/iPhone/ReleaseProtected/EnsureITApp.app/EnsureITApp" --gcc_flags "-prefinalized-library ${ProjectDir}/lib/Releaseiphoneos/libDeviceMemoryInfo.a" --gcc_flags "-Xlinker -map -Xlinker ${ProjectDir}/bin/iPhone/ReleaseProtected/EnsureITApp.map" -gcc_flags -finalizer-disable-strip -gcc_flags "${ProjectDir}/lib/Releaseiphoneos/libDeviceMemoryInfo.a"</MtouchExtraArgs>

2.	I tried adding this as a separate argument. 
<MtouchExtraArgs>--optimize=experimental-xforms-product-type</MtouchExtraArgs>
If another <MtouchExtraArgs></MtouchExtraArgs> is added, the argument mentioned in second MtouchExtraArgs is not considered in the build. 

3.	I tried the below way and this didn't work as well, though I see the arguments in the build logs.
<MtouchExtraArgs>--optimize=experimental-xforms-product-type --compiler:clang++ --gcc_flags "-framework Security" --gcc_flags -finalize --gcc_flags "-finalized-product ${ProjectDir}/bin/iPhone/ReleaseProtected/EnsureITApp.app/EnsureITApp" --gcc_flags "-prefinalized-library ${ProjectDir}/lib/Releaseiphoneos/libDeviceMemoryInfo.a" --gcc_flags "-Xlinker -map -Xlinker ${ProjectDir}/bin/iPhone/ReleaseProtected/EnsureITApp.map" -gcc_flags -finalizer-disable-strip -gcc_flags "${ProjectDir}/lib/Releaseiphoneos/libDeviceMemoryInfo.a"</MtouchExtraArgs>

Thanks
Shreyas

**Comment by davidbritch** [comment]
Hi @suleman-jalil-devbox 

I'm sorry this doesn't work for you. However, you have now opened an issue on the Docs repository which is not entirely the right place for this :)

A lot has been written about this issue already, mainly here: https://github.com/xamarin/Xamarin.Forms/issues/9823

There has also been some documentation, which you obviously already found :) some additional documentation by the Xamarin.iOS team on this is here: https://docs.microsoft.com/en-us/xamarin/ios/user-interface/controls/webview#uiwebview-deprecation

Having all that said, there are a couple of important things to make this work:

* Use all the right versions, Xamarin.Forms 4.5 stable or higher and Xamarin.iOS 13.10 or higher. If you are using Azure DevOps or App Center, make sure the right Xamarin.iOS version is selected, this requires some setup
* Set the mtouch argument for the right build configuration
* Set the linker behavior to all/full or SDK only

If you have done all those things but you still get the warning from Apple then there might be a third-party plugin that still references it. Assuming that you don't have any references to `UIWebView` or `WebViewRenderer` in your own code. One that we have identified is the Xamarin.iOS.MaterialComponents which is a dependency of the Xamarin.Forms.Visual.Material package. If you use that, please install the latest version (92.0 at the time of writing) of the Xamarin.iOS.MaterialComponents package on your iOS project for the time being. We are working on updating the dependency version from our Forms package.

If all this doesn't help you to figure it out, please find the email address on my GitHub profile and reach out then we will figure it out :) 

Thanks!
