### ISSUE TITLE
VisualElement Drop Shadows on iOS and Android non found

### ISSUE THREAD

**Issue by jor1196** [MicrosoftDocs/xamarin-docs#2747]
VisualElement Drop Shadows on iOS and Android non found

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 888b3731-bbf4-a456-31c3-c3ede4d3cea4
* Version Independent ID: 62cd58e7-a393-2447-3520-31b9d47b757e
* Content: [VisualElement Drop Shadows on iOS - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/platform/ios/visualelement-drop-shadow#feedback)
* Content Source: [docs/xamarin-forms/platform/ios/visualelement-drop-shadow.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/platform/ios/visualelement-drop-shadow.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @jor1196 

Try the sample the page links to, and you'll see that it works and how to use it.
