### ISSUE TITLE
Unable to connect to localhost web services after upgrading to macOS Catalina 10.15.4

### ISSUE THREAD

**Issue by david-chambers** [MicrosoftDocs/xamarin-docs#2748]
Is anyone having issues with consuming https local web services after upgrading from Mojave to Catalina in Xamarin Forms from the iOS Simulator? This doc worked great for me in the previous macOS version.  Now i'm seeing the following exception from http requests:

Exception:System.Net.Http.HttpRequestException: An SSL error has occurred and a secure connection to the server cannot be made. ---&gt; Foundation.NSErrorException: Error Domain=NSURLErrorDomain Code=-1200 "An SSL error has occurred and a secure connection to the server cannot be made.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd2a2f8e-fe43-c0b7-2559-bddfe31ad9e4
* Version Independent ID: 452de731-fdec-df89-b976-3480b97c9b2b
* Content: [Connect to Local Web Services from iOS Simulators and Android Emulators - Xamarin](https://docs.microsoft.com/en-us/xamarin/cross-platform/deploy-test/connect-to-local-web-services#feedback)
* Content Source: [docs/cross-platform/deploy-test/connect-to-local-web-services.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/cross-platform/deploy-test/connect-to-local-web-services.md)
* Product: **xamarin**
* Technology: **xamarin-crossplatform**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @david-chambers 

Having recently updated my own machine to Catalina, I've just tried it and received the same error as you. The fix is to use the [Android approach](https://docs.microsoft.com/xamarin/cross-platform/deploy-test/connect-to-local-web-services#android-2) on iOS. See https://www.davidbritch.com/2019/10/xamarin-connecting-to-localhost-over.html for more info.

I'll get the doc updated, but it might be tomorrow.

**Comment by david-chambers** [comment]
Thank you for confirming and sharing the doc @davidbritch! Using the android approach solved the issue for me on iOS.

Do you use compiler directives to avoid use of the insecure http handler in release builds?

```csharp
#if DEBUG
            var insecureHandler = DependencyService.Get<IHttpClientHandlerService>().GetInsecureHandler();
            _httpClient = new HttpClient(insecureHandler);
#else
            _httpClient = new HttpClient();
#endif
```

**Comment by davidbritch** [comment]
Hi @david-chambers 

Spot on!
