### ISSUE TITLE
Monkey Image doesn't load from URL

### ISSUE THREAD

**Issue by aconnolly2** [MicrosoftDocs/xamarin-docs#2749]
It appears that the URL redirects to https now, and the image does not automatically handle that redirect in code. When copying the code from the tutorial (which was http), it loaded a blank space. Modifying to https made it load correctly.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 679634c0-a0c6-cc03-c50f-6d22ce71c099
* Version Independent ID: 874062b9-a51b-a10d-4d27-d3811fa9b56b
* Content: [Xamarin.Forms Image Tutorial - Xamarin](https://docs.microsoft.com/en-us/xamarin/get-started/tutorials/image/?tutorial-step=4&tabs=vswin#feedback)
* Content Source: [docs/get-started/tutorials/image/index.yml](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/get-started/tutorials/image/index.yml)
* Product: **xamarin**
* Technology: **xamarin-crossplatform**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @aconnolly2 

Thanks for pointing this out. Yesterday I updated our docs/samples to ensure that remote images were being retrieved over HTTPS instead of HTTP. So this is now fixed.
