### ISSUE TITLE
Contents links don't correctly link to article sections

### ISSUE THREAD

**Issue by PureWeen** [MicrosoftDocs/xamarin-docs#275]
Clicking the links at the top of the article don't navigate you to those sections of the article

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e9e9c055-6a8e-5e81-00c7-e57c8c912a8b
* Version Independent ID: 28ac7239-a6c2-e31e-d423-b5268fd95c65
* Content: [Xamarin Profiler - Xamarin](https://docs.microsoft.com/en-us/xamarin/tools/profiler/?tabs=vsmac#feedback)
* Content Source: [docs/tools/profiler/index.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/tools/profiler/index.md)
* Service: **xamarin**
* GitHub Login: @topgenorth
* Microsoft Alias: **toopge**

**Comment by bradumbaugh** [comment]
Thanks, @PureWeen. Since the contents is listed on the right-hand margin of the document, I went ahead and removed this contents section. The fix should be published soon. Appreciate the help!
