### ISSUE TITLE
Images not loading in ListView

### ISSUE THREAD

**Issue by aconnolly2** [MicrosoftDocs/xamarin-docs#2750]
Similar to the images tutorial, it seems some of the monkey pictures have been redirected to https. The first half of the images in the tutorial list are still at http, and Xamarin does not handle the redirect automatically so it just doesn't load the pictures. Switching text to https resolves the issue.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c0ef804e-d67f-47b3-43c0-2d08d911570d
* Version Independent ID: 54e65a56-7251-7ee7-0229-32d202db0236
* Content: [Xamarin.Forms ListView Tutorial - Xamarin](https://docs.microsoft.com/en-us/xamarin/get-started/tutorials/listview/?tutorial-step=5&tabs=vswin)
* Content Source: [docs/get-started/tutorials/listview/index.yml](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/get-started/tutorials/listview/index.yml)
* Product: **xamarin**
* Technology: **xamarin-crossplatform**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davehump** [comment]
@aconnolly2 I have updated both the documentation and the sample code on the Xamarin.Forms
