### ISSUE TITLE
Audio volume delay adjustement on Android emulator (VS2019)

### ISSUE THREAD

**Issue by EricOuellet2** [MicrosoftDocs/xamarin-docs#2751]
First I'm not sure if I'm at the right place. Is this the Microsoft repo for MediaElement?
If yes, using MediaElement on Xamarin Form project 4.5:
There is a delay on the Android emulator (using VS2019) while setting the volume before playing an audio file. It takes about 3 seconds before the volume is adjusted as given to the MediaEllement control. The audio start and the voume is adjusted around 3 seconds after althought the volume was set before the audio start.

**Comment by davehump** [comment]
hi @EricOuellet2,  This sounds like it would be an issue with the MediaElement in Xamarin.Forms, rather than a documentation issue.  You can log your issue here -> https://github.com/xamarin/Xamarin.Forms/issues. They have a template so you can provide some more details about system and projects.

**Comment by EricOuellet2** [comment]
Thanks you veru much!!!
