### ISSUE TITLE
Error in code example

### ISSUE THREAD

**Issue by mnidhk** [MicrosoftDocs/xamarin-docs#2752]
On this page there is the code:
 UNUserNotificationCenter.Current.RequestAuthorization(UNAuthorizationOptions.Alert |
            UNAuthorizationOptions.Sound |
            UNAuthorizationOptions.Sound,

This should be (instead of 2 times "Sound"):
 UNUserNotificationCenter.Current.RequestAuthorization(UNAuthorizationOptions.Alert |
            UNAuthorizationOptions.Badge |
            UNAuthorizationOptions.Sound,

This was the reason that my badge counter didn't work on my iOS device

**Comment by davehump** [comment]
@mnidhk could you please provide some more details about which page you are refering to so we can fix it. 

Thanks in advance

**Comment by mnidhk** [comment]
https://docs.microsoft.com/nl-nl/xamarin/xamarin-forms/data-cloud/azure-services/azure-notification-hub

**Comment by davidbritch** [comment]
This has since been fixed.
