### ISSUE TITLE
Info.plist instructions out of date

### ISSUE THREAD

**Issue by varyamereon** [MicrosoftDocs/xamarin-docs#2753]
The instructions at https://docs.microsoft.com/en-gb/xamarin/xamarin-forms/user-interface/layouts/device-orientation?tabs=windows#tabpanel_CeZOj-G++Q_windows seem to refer to an old version of Visual Studio. There is now no separate option for iPhone and iPad orientation settings.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ee3536ba-80b7-2443-39ec-2082cfd6d557
* Version Independent ID: 6339e8b1-c252-0647-b3ee-d317100940ae
* Content: [Device Orientation - Xamarin](https://docs.microsoft.com/en-gb/xamarin/xamarin-forms/user-interface/layouts/device-orientation?tabs=windows)
* Content Source: [docs/xamarin-forms/user-interface/layouts/device-orientation.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/layouts/device-orientation.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @varyamereon 

Thanks for pointing this out. I've just updated the screenshots in a PR that will go live in the next hour.
