### ISSUE TITLE
Not enough info on data virtualization 

### ISSUE THREAD

**Issue by jefffhaynes** [MicrosoftDocs/xamarin-docs#2755]
There is an off-hand comment on a different page about data virtualization but no indication if this control actually supports virtualization (e.g. correctly using the IEnumerable in the ItemsSource to only retrieve data when necessary). If the only form of “virtualization” is the (cumbersome) event-driven version then it should be explicitly stated that this control does not support true data virtualization. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 12370c4e-0935-d43a-7d28-32a10a30074f
* Version Independent ID: bb1eccf7-c1b8-25b1-5325-3b37a9b1bd94
* Content: [Xamarin.Forms CollectionView Data - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/collectionview/populate-data)
* Content Source: [docs/xamarin-forms/user-interface/collectionview/populate-data.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/collectionview/populate-data.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @jefffhaynes 

Thanks for your feedback. I've added a note to the doc to specify that only incremental data virtualisation is supported, in a PR that will go live later today.
