### ISSUE TITLE
Not working.

### ISSUE THREAD

**Issue by arsoftcr** [MicrosoftDocs/xamarin-docs#2756]
it doesn't work. The map is always opened and a few seconds later the google maps map is opened, not the one of xamarin. How can I avoid opening the google maps and only see the map of xamarin ?? I followed all the steps in the documentation.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d967c4fc-27ef-2712-f902-db53cef7f5dc
* Version Independent ID: ee85bf33-2ce2-fc75-3806-50167b47a1f5
* Content: [Xamarin.Forms Map Pins - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/map/pins)
* Content Source: [docs/xamarin-forms/user-interface/map/pins.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/map/pins.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @arsoftcr 

If you look at the sample that the page links to, you'll see that native maps are used on each platform, which means that Google Maps are used on Android.
