### ISSUE TITLE
CameraPageCS is redundant on this page.

### ISSUE THREAD

**Issue by MaximMikhisor** [MicrosoftDocs/xamarin-docs#2757]
Please delete it.
And also from source code example.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c36e7942-65b6-9877-aafd-5f1b1291d37d
* Version Independent ID: 77a599a6-43f2-068f-95ad-0a92ca2b4bca
* Content: [Customizing a ContentPage - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/custom-renderer/contentpage#feedback)
* Content Source: [docs/xamarin-forms/app-fundamentals/custom-renderer/contentpage.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/app-fundamentals/custom-renderer/contentpage.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @MaximMikhisor 

It's not redundant. Some users prefer to write their UI in C#, rather than XAML. So many samples include both C# and XAML implementations of the same page. The CS postfix indicates that it's a C# version of the page.
