### ISSUE TITLE
Caching

### ISSUE THREAD

**Issue by pavelku** [MicrosoftDocs/xamarin-docs#2758]
I noticed that once the content from external url is loaded into the webview, it is cached. When I kill my IOS app and open it again with the phone in the flight mode, the content renders. Great!!

As I only have 3 small webviews in separate forms, is there a way how I can preload their cache for all of them in App.xaml.cs after opening? 

Ideally, can I first check whether the cache is loaded and if not then preload it? I would like to do it during the first opening after the install. 

I tried to have a static WebView variable in App.xaml.cs but it seems it loads only after I assign it into the page content.

Thanks!!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ef31dc71-3610-6c18-2bda-d0bb70804c92
* Version Independent ID: 02f7dc7b-541b-4b82-b33c-4e974fb94d8c
* Content: [Xamarin.Forms WebView - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/webview?tabs=macos#feedback)
* Content Source: [docs/xamarin-forms/user-interface/webview.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/webview.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @pavelku 

Cache manipulation isn't exposed through the Xamarin.Forms `WebView`. You'd have to use custom renderers on each platform, and manipulate the underlying native controls. There are community posts that cover doing this.

A simple cross-platform approach is shown at https://forums.xamarin.com/discussion/91075/is-there-a-way-to-cache-webview-content . However, it has limitations.
