### ISSUE TITLE
Several references to nonexistent article

### ISSUE THREAD

**Issue by vaindil** [MicrosoftDocs/xamarin-docs#276]
This page references an article called "Data Access: Using SQLite.NET", but the link doesn't go to an article with that content. I was unable to find an article with that name anywhere (other than one that's specific to Xamarin.Android).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3ab6098a-39c7-151f-124b-f88aa62c4659
* Version Independent ID: dc27c1e4-ff12-c1af-646a-c2617def0bcd
* Content: [Local Databases - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/databases#feedback)
* Content Source: [docs/xamarin-forms/app-fundamentals/databases.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/app-fundamentals/databases.md)
* Service: **xamarin**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by conceptdev** [comment]
@vaindil yes, I believe the link was originally intended to link to 
https://docs.microsoft.com/en-us/xamarin/android/data-cloud/data-access/using-sqlite-orm or
https://docs.microsoft.com/en-us/xamarin/ios/data-cloud/data/using-sqlite-orm
(before there was a single page, which was split in two). 

Thanks for letting us know - will investigate the best way to update it.
