### ISSUE TITLE
 What this property does Shell.TabBarForegroundColor ?

### ISSUE THREAD

**Issue by edmlbox** [MicrosoftDocs/xamarin-docs#2763]
What this property does Shell.TabBarForegroundColor ? its not working for me.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ef7242a0-d46e-19ea-e22d-f327dcc9b3e9
* Version Independent ID: f050be8e-9413-19e7-5799-90a55c4e5bfb
* Content: [Xamarin.Forms Shell Layout - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/shell/tabs)
* Content Source: [docs/xamarin-forms/app-fundamentals/shell/tabs.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/app-fundamentals/shell/tabs.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by edmlbox** [comment]
It's a hamburgerIcon color.

**Comment by davidbritch** [comment]
Hi @edmlbox 

If you believe that the property isn't working you should log an issue in the [engineering repo](https://github.com/xamarin/Xamarin.Forms/).
