### ISSUE TITLE
Not working in iOS 13

### ISSUE THREAD

**Issue by idchlife** [MicrosoftDocs/xamarin-docs#2764]
It seems the problem of removing this line exists even in Swift ecosystem.

I actually can't yet remove it even in custom renderer, but this option is not working.

Here is some kind of rant about removing it on stack: https://stackoverflow.com/questions/19226965/how-to-hide-uinavigationbar-1px-bottom-line

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 094f80f2-7fc1-d4cb-c20f-f6044c108b32
* Version Independent ID: 889aa099-7eb5-d60d-be27-ced081fa8fe8
* Content: [NavigationPage Bar Separator on iOS - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/platform/ios/navigation-bar-separator)
* Content Source: [docs/xamarin-forms/platform/ios/navigation-bar-separator.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/platform/ios/navigation-bar-separator.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @idchlife 

That's one annoying problem you've found! I've logged an issue for it in the engineering repo: https://github.com/xamarin/Xamarin.Forms/issues/10438

Therefore, I'll close the issue here.
