### ISSUE TITLE
Theming with CSS

### ISSUE THREAD

**Issue by danim-hub** [MicrosoftDocs/xamarin-docs#2767]
This page does not state how could we dynamically load the stylesheet, or how to change it at runtime in order to apply different themes to the application.
I don't know if it is possible at all, but in that case it would be helpful to know at least that it is not currently possible.
I will be cross-posting this comment to the theming page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7a410a97-17d3-aff7-c875-ee9291658957
* Version Independent ID: f415dc53-c941-b0e5-5823-9bafa53f0d9a
* Content: [Styling Xamarin.Forms Apps using Cascading Style Sheets (CSS) - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/styles/css/)
* Content Source: [docs/xamarin-forms/user-interface/styles/css/index.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/styles/css/index.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @danim-hub 

Afraid this isn't currently possible. I've added a note to the doc, in a PR that will go live later today.
