### ISSUE TITLE
Theming and CSS

### ISSUE THREAD

**Issue by danim-hub** [MicrosoftDocs/xamarin-docs#2768]
This page does not state how could we apply themes using CSS.
I don't know if it is possible at all, but in that case it would be helpful to know at least that it is not currently possible.
I posted a similar comment in the Styles/CSS page, I think this information should be in both sections

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 455b1419-37da-f785-2c4e-b0bfa08ddd92
* Version Independent ID: ce2b3dba-4c9a-c756-94e1-395c8ce06f08
* Content: [Theming a Xamarin.Forms Application - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/theming/)
* Content Source: [docs/xamarin-forms/user-interface/theming/index.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/theming/index.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @danim-hub 

Afraid that theming support is limited to XAML styles, and isn't possible using CSS. I've added a note to the theming page to this effect, in a PR that will go live later today.
