### ISSUE TITLE
data from cosmos db and/or api

### ISSUE THREAD

**Issue by arizzi12** [MicrosoftDocs/xamarin-docs#2769]
nice tut...any chance we can get this with pulling data from a cosmos db and/or api?...please and thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b47354c0-5630-f56c-4632-d69bbe124b59
* Version Independent ID: 4dda513e-0364-d692-46fb-372e741526fd
* Content: [Adding Data to a Picker's Items Collection - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/picker/populating-items)
* Content Source: [docs/xamarin-forms/user-interface/picker/populating-items.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/picker/populating-items.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @arizzi12 

We've already got a doc on [consuming CosmosDB from Xamarin.Forms apps](https://docs.microsoft.com/xamarin/xamarin-forms/data-cloud/azure-services/azure-cosmosdb). Combining it with a `Picker` is left for you :)
