### ISSUE TITLE
About Consuming Native Views.

### ISSUE THREAD

**Issue by WAELKASSEM** [MicrosoftDocs/xamarin-docs#2770]
Recommendations Concerning this line : 
xmlns:androidLocal="clr-namespace:SimpleColorPicker.Droid;assembly=SimpleColorPicker.Droid;targetPlatform=Android"

clr-namespace : You'll Find it in MainActivity.cs (Android Project)
assembly : You'll find it in AssemblyInfo.cs ( Android Project) .

Copy them carefully instead of **wasting an hour wondering what went wrong.**

**Your Intellisense will not Help  , because this Xaml is not Compiled.** Don't get suspicious.

Remeber to Add the Instance Property to your MainActivity.cs . Check the github sample.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a781e5d5-c0c4-4bc0-2049-97442139bee3
* Version Independent ID: 94e2df3f-c624-98d8-2edb-ef98134835b9
* Content: [Native Views in XAML - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/platform/native-views/xaml#consuming-native-views)
* Content Source: [docs/xamarin-forms/platform/native-views/xaml.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/platform/native-views/xaml.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @davidbritch 

Good advice!
