### ISSUE TITLE
How to subclass a native view in UWP (or WPF)?

### ISSUE THREAD

**Issue by jagg00** [MicrosoftDocs/xamarin-docs#2771]
For the sake of completeness it would be interesting to include an example that explains how to subclass Native Views in UWP (or WPF) as well. 
In my case, I've been trying to figure out how to include a menubar in a UWP application (https://stackoverflow.com/questions/61288106/native-view-of-a-menubar-uwp-or-menu-wpf-using-xamarin-forms), but apparently this control is not as XAML-friendly as the combobox. Having this kind of information will be greatly appreciated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a781e5d5-c0c4-4bc0-2049-97442139bee3
* Version Independent ID: 94e2df3f-c624-98d8-2edb-ef98134835b9
* Content: [Native Views in XAML - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/platform/native-views/xaml#feedback)
* Content Source: [docs/xamarin-forms/platform/native-views/xaml.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/platform/native-views/xaml.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @jagg00 

Although there's no UWP section in the doc, the [sample](https://docs.microsoft.com/samples/xamarin/xamarin-forms-samples/userinterface-nativeviews-nativeswitch/) the doc links to does have a UWP implementation.

Similarly, the other native views samples also have UWP implementations that might help: 

https://docs.microsoft.com/samples/xamarin/xamarin-forms-samples/forms2native/

https://docs.microsoft.com/samples/xamarin/xamarin-forms-samples/userinterface-nativeviews-nativeviewinsidecontentview/

https://docs.microsoft.com/samples/xamarin/xamarin-forms-samples/userinterface-nativeviews-subclassednativecontrols/
