### ISSUE TITLE
ItemSpacing not clear on what it is spacing

### ISSUE THREAD

**Issue by AceOfSpades29** [MicrosoftDocs/xamarin-docs#2773]
ItemSpacing appears to be for each item listed inside of the carousel view and NOT for each item in the carousel view from the Itemsource. For example when I had a carousel view with a stacklayout with a 2x2 grid view inside of it. When updating the item spacing I expected that each stacklayout inside the carousel view would have an item spacing of 10 but instead the items inside of the grid view were spaced out. In order to get the desired effect I had to add a frame inside the stacklayout and add a margin

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f449be86-fbc4-fce9-e347-35b358a3199c
* Version Independent ID: 1254578d-c4d8-6018-e850-f53ece69903b
* Content: [Xamarin.Forms CarouselView Layout - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/carouselview/layout#feedback)
* Content Source: [docs/xamarin-forms/user-interface/carouselview/layout.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/carouselview/layout.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @AceOfSpades29 

I've updated the language in the doc, in a PR that will go live later today.
