### ISSUE TITLE
Update xamarin.android docs about setting androidmanifestplaceholders

### ISSUE THREAD

**Issue by jingliancui** [MicrosoftDocs/xamarin-docs#2774]
https://github.com/xamarin/xamarin-android/commit/b423ff68a6d11230bb493c3cb0633ff2a9c37b20

This feaure had been implement , but Microsoft docs does not has this .

**Comment by brendanzagaeski** [comment]
Documentation now added in: https://github.com/MicrosoftDocs/xamarin-docs/commit/5c096d3a9f84571ca59de810b6d2406e04e05bca

**Comment by jingliancui** [comment]
Thanks

**Comment by wrkntwrkn** [comment]
Is this available in MAUI?
