### ISSUE TITLE
Promote MVVM

### ISSUE THREAD

**Issue by ndastur** [MicrosoftDocs/xamarin-docs#2775]
In most examples the first pattern shown to devs is the onClicked ... pattern. MVVM I think is the promoted coding style and so should really be the first example.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f70c4017-a981-2cd6-24b2-7da7674efa5a
* Version Independent ID: 2b4a8128-38d8-352f-c310-d033b56a3081
* Content: [Xamarin.Forms ImageButton - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/imagebutton)
* Content Source: [docs/xamarin-forms/user-interface/imagebutton.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/imagebutton.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @ndastur 

We go with using events as it's easier to understand for new users. Using MVVM adds a layer of complication, which tends to be avoided through Microsoft Docs.
