### ISSUE TITLE
Will this framework support background NFC scanning for new iPhone? 

### ISSUE THREAD

**Issue by ahsih** [MicrosoftDocs/xamarin-docs#2776]
Will this framework support background NFC scanning for new iPhone? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a77a91ed-4a70-63af-6183-b11724d94861
* Version Independent ID: cdeca2e9-3b8d-f435-86f3-3541f50cbfbe
* Content: [Core NFC in Xamarin.iOS - Xamarin](https://docs.microsoft.com/en-us/xamarin/ios/platform/introduction-to-ios11/corenfc#feedback)
* Content Source: [docs/ios/platform/introduction-to-ios11/corenfc.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/ios/platform/introduction-to-ios11/corenfc.md)
* Product: **xamarin**
* Technology: **xamarin-ios**
* GitHub Login: @davidortinau
* Microsoft Alias: **daortin**

**Comment by PureWeen** [comment]
Closing this out from the docs repository

If you are having issues with the API for the new iPhone please log an issue here
https://github.com/xamarin/xamarin-macios
