### ISSUE TITLE
Bad code

### ISSUE THREAD

**Issue by SermanVS** [MicrosoftDocs/xamarin-docs#2777]
This line:
LeftItems = new SwipeItems(swipeItems)
will invoke an error that SwipeItems class doesn't have a constructor that takes 1 argument.
One workaround is:
List&lt;SwipeItem&gt; menuItems = new List&lt;SwipeItem&gt;() { menuItem1, menuItem2 };
SwipeItems menuSwipeItems = new SwipeItems();
foreach (SwipeItem i in menuItems)
{
    menuSwipeItems.Add(i);
} 
LeftItems = menuSwipeItems

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 02d932c9-7483-c314-b1c6-3850778cd6dc
* Version Independent ID: 8ab4f230-a8ff-5164-d377-b0b12cac5f09
* Content: [Xamarin.Forms SwipeView - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/swipeview#feedback)
* Content Source: [docs/xamarin-forms/user-interface/swipeview.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/swipeview.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @SermanVS 

Afraid there is a `SwipeItems` constructor that takes a single argument: https://github.com/xamarin/Xamarin.Forms/blob/4.5.0/Xamarin.Forms.Core/SwipeItems.cs#L14

It was introduced into 4.5 by this PR: https://github.com/xamarin/Xamarin.Forms/pull/8757

**Comment by SermanVS** [comment]
Hi!
Thanks, apparently I have a 4.4 and will have to use workaround. Probably
it's worth mentioning in documentation that the sample is valid only for 4.5

вт, 28 апр. 2020 г. в 16:59, David Britch <notifications@github.com>:
