### ISSUE TITLE
SwipeViewDemos Broken - Xamarin.Forms 4.5

### ISSUE THREAD

**Issue by Calumfletcher** [MicrosoftDocs/xamarin-docs#2778]
SwipeViewDemos - examples throwing exception

Hi, it appears the SwipeViewDemos is currently broken on a lot of the main examples.

It appears to be due to Xamarin Forms 4.5 as when I downgraded to 4.4, it seemed to resolve the issues and I was able to tap on all the examples without an exception being thrown.

![exception-swipe](https://user-images.githubusercontent.com/49764991/80550840-4b176180-89b9-11ea-83b8-476dd7bc2146.jpg)

**Comment by davidbritch** [comment]
Hi @Calumfletcher 

Agreed that the sample is broken (on iOS as well as Android). Tomorrow, all the samples will be updated to Xamarin.Forms 4.6, which will take care of the problem.

**Comment by Calumfletcher** [comment]
> Hi @Calumfletcher
> 
> Agreed that the sample is broken (on iOS as well as Android). Tomorrow, all the samples will be updated to Xamarin.Forms 4.6, which will take care of the problem.

Brill, thanks. It wasn't causing me too much of an issue, just wasn't sure whether it was known.
