### ISSUE TITLE
Error on first example

### ISSUE THREAD

**Issue by wrkettlitz** [MicrosoftDocs/xamarin-docs#2779]
Error	XLS0502	The type 'Thickness' does not support direct content.
	

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1d23ce09-1c59-1482-036a-f7348090fd00
* Version Independent ID: 9b4213b5-8278-5bea-c73d-0e172d7c0a89
* Content: [Xamarin.Forms resource dictionaries - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/xaml/resource-dictionaries)
* Content Source: [docs/xamarin-forms/xaml/resource-dictionaries.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/xaml/resource-dictionaries.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @wrkettlitz 

If you try the sample the page links to, you'll see that ` <Thickness x:Key="PageMargin">20</Thickness>` is valid.
