### ISSUE TITLE
Mediaelement does not work within a stacklayout

### ISSUE THREAD

**Issue by ymebrugts** [MicrosoftDocs/xamarin-docs#2780]
#implement-a-custom-volume-control

Gives an example with a stacklayout but MediaElement does not work with Stacklayout. On android you see nothing. On iOS it becomes fullscreen. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4485a974-e563-1a00-bc75-50c15942b5ed
* Version Independent ID: b59da204-445a-5019-7be5-ad2cb2f59c0d
* Content: [Xamarin.Forms MediaElement - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/mediaelement#implement-a-custom-volume-control)
* Content Source: [docs/xamarin-forms/user-interface/mediaelement.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/mediaelement.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @ymebrugts 

`MediaElement` is still experimental, and has a lot of bugs logged against it (including that it doesn't work in a `StackLayout`). In a future release, `MediaElement` will work in a `StackLayout`, so the doc is waiting for the control to catch up.
