### ISSUE TITLE
Broken link : CSharpForMarkupDemos (sample)

### ISSUE THREAD

**Issue by VincentH-Net** [MicrosoftDocs/xamarin-docs#2782]
The example source can be found [here](https://github.com/xamarin/xamarin-forms-samples/tree/dabritch-forms46/UserInterface/CSharpMarkupDemos)

At this moment the sample is not yet merged to master of xamarin-forms-samples.

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: cc5d52fb-d4a2-7231-d2d4-3990b7634963
* Version Independent ID: 32b38657-d211-5bff-ee70-f9334aeb2053
* Content: [Xamarin.Forms C# markup - Xamarin](https://docs.microsoft.com/nl-nl/xamarin/xamarin-forms/user-interface/csharp-markup)
* Content Source: [docs/xamarin-forms/user-interface/csharp-markup.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/csharp-markup.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @VincentH-Net 

The mass update to 4.6 is complete, but I'm waiting for all the samples to finish building on Android and UWP before I can publish to master. But it'll all happen today.
