### ISSUE TITLE
, APKSigningTool compiled with Java version53 and it needs v 53

### ISSUE THREAD

**Issue by stewa11** [MicrosoftDocs/xamarin-docs#2783]
Problems with W10 VS2019 Xamarin Forms Android, Archive, Distribution, APKSigningTool compiled with Java version53 and it needs v 53 -  AND THERE IS NO LINK anywhere to show us how to upgrade. Please help. Thanks. Stew

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 97e1cd96-e7a2-ec22-8d79-ac949e890ccb
* Version Independent ID: 922a3fdf-7bab-7d9d-5518-904db9e75ee3
* Content: [Microsoft's Mobile OpenJDK Distribution - Xamarin](https://docs.microsoft.com/en-us/xamarin/android/get-started/installation/openjdk#feedback)
* Content Source: [docs/android/get-started/installation/openjdk.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/android/get-started/installation/openjdk.md)
* Product: **xamarin**
* Technology: **xamarin-android**
* GitHub Login: @vyedin
* Microsoft Alias: **vyedin**

**Comment by Falco20019** [comment]
@stewa11 Make sure you don't have any `30.x` SDKs in your `%userprofile%\AppData\Local\Android\sdk\build-tools` (Android-SDK folder). I had `30.0.0-rc1` in there which caused it for me... It was not visible in the SDK manager.

**Comment by stewa11** [comment]
> @stewa11 Make sure you don't have any 30.x SDKs in your %userprofile%\AppData\Local\Android\sdk\build-tools (Android-SDK folder). I had 30.0.0-rc1 in there which caused it for me... It was not visible in the SDK manager.

Hi Falco2019, thanks for replying. When publishing to Google Play they wanted me to use version ! (SDK v 30), so isn't that a gotcha or am I missing something?
Thanks again, much appreciate any help.
Stew

**Comment by Falco20019** [comment]
Hm, I uploaded 2 days ago and was not requested to have SDK 30. SDK 29 worked just fine.

**Comment by davidortinau** [comment]
It sounds like you want to update your Android SDK, which is a feature of the Android SDK manager available from the tools menu and not related to this doc about OpenJDK. If you again encounter similar issues please use the Feedback option within Visual Studio to report it to developer community.
