### ISSUE TITLE
Xamaine will not install. I followed the instructions to modify visual studio to run mobil android app but the install will not install xamiane  Help

### ISSUE THREAD

**Issue by pmarcantonio** [MicrosoftDocs/xamarin-docs#2784]
help

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b4445585-af8f-09d3-5d35-762c3aac187b
* Version Independent ID: fa9263db-60d6-eb98-eb74-842351ba5387
* Content: [Build your first Xamarin.Forms app - Xamarin](https://docs.microsoft.com/en-us/xamarin/get-started/first-app/?pivots=windows#feedback)
* Content Source: [docs/get-started/first-app/index.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/get-started/first-app/index.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @conceptdev
* Microsoft Alias: **crdun**

**Comment by davidbritch** [comment]
Hi @pmarcantonio 

Afraid all I can do is direct you to this page: https://docs.microsoft.com/xamarin/get-started/installation/windows
