### ISSUE TITLE
Navigating to another xml page, form, or whatever it's called.

### ISSUE THREAD

**Issue by kcovert** [MicrosoftDocs/xamarin-docs#2786]
I haven't been using Xamarin.Forms and didn't want to add that whole library for a simple page to page navigation. If you are the same this is what I got after hours of trying to find something that totally works...

SetContentView(Resource.Layout.&lt;Your Form's name&gt;);

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 60587f77-05de-89b9-8a08-c7e7221d27af
* Version Independent ID: 4080b687-b353-f833-4bb7-a7a3f9993338
* Content: [Perform navigation in a multi-page Xamarin.Forms application - Xamarin](https://docs.microsoft.com/en-us/xamarin/get-started/quickstarts/multi-page?pivots=windows)
* Content Source: [docs/get-started/quickstarts/multi-page.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/get-started/quickstarts/multi-page.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @kcovert 

`SetContentView` is Xamarin.Android rather than Xamarin.Forms.

**Comment by kcovert** [comment]
Thanks David, did use SetContentView and posted about it the other days for others.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by kcovert** [comment]
Add:

This is for returning to my stat page after finishing on another page. Unfortunately all original context is lost on the return to the main page. Have to figure out something there.

By page I mean the .xml form, easy to get caught up in nouns.

Kirk

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
