### ISSUE TITLE
It is Possible to Bind Grouped Data on Bindable Layout (StackLayout).

### ISSUE THREAD

**Issue by mistrypragnesh40** [MicrosoftDocs/xamarin-docs#2788]
I want to bind Grouped Data on StackLayout.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 59df8b1e-8b94-a79e-25eb-f47ddf38777a
* Version Independent ID: cd195715-e7e3-428f-1061-c550ff960dda
* Content: [Bindable Layouts in Xamarin.Forms - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/layouts/bindable-layouts#feedback)
* Content Source: [docs/xamarin-forms/user-interface/layouts/bindable-layouts.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/layouts/bindable-layouts.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @mistrypragnesh40 

It's not possible out of the box. The recommendation is to use `CollectionView` if you want to display grouped data.
