### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by aldrashan** [MicrosoftDocs/xamarin-docs#279]
Whenever any of the battery's properties >>>chagne<<< an event is triggered:

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: 38198725-c8f2-3b90-d179-24f86284c4cb
* Version Independent ID: 1dd34451-25d2-9c50-a7f6-bb5b9f763ba0
* Content: [Xamarin.Essentials Battery - Xamarin](https://docs.microsoft.com/nl-nl/xamarin/essentials/battery?context=xamarin%2Fxamarin-forms&tabs=ios)
* Content Source: [docs/essentials/battery.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/essentials/battery.md)
* Service: **unspecified**
* Product: **xamarin**
* GitHub Login: @jamesmontemagno
* Microsoft Alias: **jamont**

**Comment by conceptdev** [comment]
Thanks @aldrashan, this has been fixed!
