### ISSUE TITLE
can not build resourcetoken solution

### ISSUE THREAD

**Issue by amgarnier** [MicrosoftDocs/xamarin-docs#2790]
I can not build the resourcetoken solution "the target build does not exist in the project"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4a210c03-fa8d-4293-e170-5b4f765c0bb0
* Version Independent ID: c717c858-4e70-dee0-403d-e70683b60a06
* Content: [Authenticate Users with an Azure Cosmos DB Document Database and Xamarin.Forms - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/data-cloud/authentication/azure-cosmosdb-auth#feedback)
* Content Source: [docs/xamarin-forms/data-cloud/authentication/azure-cosmosdb-auth.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/data-cloud/authentication/azure-cosmosdb-auth.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @amgarnier 

I'm afraid that the resource token broken solution is no longer supported by Visual Studio. So it needs an update to use ASP.NET Core. There's an open issue for this in xamarin-forms-samples, so I'll close this issue here.
