### ISSUE TITLE
Android second display exception

### ISSUE THREAD

**Issue by eli191** [MicrosoftDocs/xamarin-docs#2792]
Hi,
Working with a native `TextView` I get this Exception the second time I navigate to the page it is in.
` java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.`
Can you help please?

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a781e5d5-c0c4-4bc0-2049-97442139bee3
* Version Independent ID: 94e2df3f-c624-98d8-2edb-ef98134835b9
* Content: [Native Views in XAML - Xamarin](https://docs.microsoft.com/en-gb/xamarin/xamarin-forms/platform/native-views/xaml#referring-to-native-views-from-code)
* Content Source: [docs/xamarin-forms/platform/native-views/xaml.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/platform/native-views/xaml.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @eli191 

It sounds like you should remove the `TextView` from its parent when you navigate away from the page.

**Comment by eli191** [comment]
Hi @davidbritch 

Thank you for your reply.

How am I suppose to do that from my custom native `TextView` please?
I mean in a Xamarin Forms app. My `TextView` is a subclassed native `TextView` and I don't see any thing to achieve that in the documentation.

Thanks!
