### ISSUE TITLE
`ScrolledEnded` event ?

### ISSUE THREAD

**Issue by eli191** [MicrosoftDocs/xamarin-docs#2793]
Hi, the `Scrolled` event fires even if the user is still scrolling? Is it intended? If yes, is there a way to know if the user has released the scroll?
Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6bd3b3b0-0147-f10d-76fe-15eecb8c25cf
* Version Independent ID: 586eee27-63ea-6cbf-b064-6e4a3dde7327
* Content: [Xamarin.Forms CollectionView Scrolling - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/collectionview/scrolling#detect-scrolling)
* Content Source: [docs/xamarin-forms/user-interface/collectionview/scrolling.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/collectionview/scrolling.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @eli191 

Yes, `Scrolled` fires multiple times as the user scrolls. Afraid there isn't a `ScrollEnded` event. However, you can detect the scroll ending by examining the `ItemsViewScrolledEventArgs.VerticalDelta` property (assuming a vertical list). This property nears 0 as the scroll ends.
