### ISSUE TITLE
 Using code Shell.Current.CurrentItem = aboutItem; does not work

### ISSUE THREAD

**Issue by HobDev** [MicrosoftDocs/xamarin-docs#2794]
[Enter feedback here]
Shell.Current.CurrentItem = aboutItem; is shown as example for setting currentItem in the Shell. But this code does not work. First the Contentpage needs a x:Name (x:Name aboutItem) Property and then:
Shell shell=new shell();
shell.CurrentItem=aboutItem;

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a303fbe7-5786-651e-e730-90efb1796e72
* Version Independent ID: 6a6a96eb-7563-8b4f-1272-1eb7bd221fb7
* Content: [Xamarin.Forms Shell Flyout - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/shell/flyout)
* Content Source: [docs/xamarin-forms/app-fundamentals/shell/flyout.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/app-fundamentals/shell/flyout.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @HobDev 

I've added a clarification to the doc, in a PR that will go live later.
