### ISSUE TITLE
Different syntax for forms 4.4

### ISSUE THREAD

**Issue by ihorbond** [MicrosoftDocs/xamarin-docs#2798]
I think it's worth mentioning that for forms v4.4 the IndicatorView prop doesnt exist on CarouselView and has to be instead set on IndicatorView as IndicatorView.ItemsSourceBy="carouselName"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 964bba3d-71b4-c30b-de73-8c2f0864a7df
* Version Independent ID: d735dc5e-8c87-ffef-c07b-51a991e4327a
* Content: [Xamarin.Forms IndicatorView - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/indicatorview)
* Content Source: [docs/xamarin-forms/user-interface/indicatorview.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/indicatorview.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @ihorbond 

That's correct, but because the `IndicatorView` and `CarouselView` are experimental features, their APIs might/can change until their final stable release. Our previous experience is that listing the API changes that experimental controls go through makes for unreadable docs.
