### ISSUE TITLE
DisplayPromptAsync not implemented for GTK

### ISSUE THREAD

**Issue by Grayhead1** [MicrosoftDocs/xamarin-docs#2801]
Xamarin.Forms.Platform.GTK (4.5 & 4.6) doesn't implement the DisplayPromptAsync feature

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3c6e0bb1-26e4-091b-8a99-27d772bed7f6
* Version Independent ID: 57d8ad92-0aa2-9ec4-47bc-8853d9a71d91
* Content: [Display Pop-ups - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/pop-ups#feedback)
* Content Source: [docs/xamarin-forms/user-interface/pop-ups.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/pop-ups.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @Grayhead1 

Afraid that's the case. The GTK# support in Xamarin.Forms is still classed as a preview, and is a community ran project. New functionality is only added as and when community members have time.
