### ISSUE TITLE
Label TextType does not run

### ISSUE THREAD

**Issue by sandlergiovanni** [MicrosoftDocs/xamarin-docs#2802]
When using Label with TextType = "Html", registered custom font do not run.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe0572c4-91be-fc86-d130-242db2bf470b
* Version Independent ID: 1238fdd7-c378-6d0d-654e-55656a70d386
* Content: [Fonts in Xamarin.Forms - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/text/fonts#feedback)
* Content Source: [docs/xamarin-forms/user-interface/text/fonts.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/text/fonts.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @sandlergiovanni 

Good catch! Thanks for reporting this. I've logged an issue for it in the engineering repo: https://github.com/xamarin/Xamarin.Forms/issues/10588
