### ISSUE TITLE
UIWebView mtouch arguments

### ISSUE THREAD

**Issue by gjhdigital** [MicrosoftDocs/xamarin-docs#2803]
Is the "--optimize=experimental-xforms-product-type" argument something that will always be required or will there be a release Xamarin where this is no longer required?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ef31dc71-3610-6c18-2bda-d0bb70804c92
* Version Independent ID: 02f7dc7b-541b-4b82-b33c-4e974fb94d8c
* Content: [Xamarin.Forms WebView - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/webview?tabs=macos#feedback)
* Content Source: [docs/xamarin-forms/user-interface/webview.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/webview.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @gjhdigital 

The iOS team is going to enable the required flag by default, in a future release. Afraid I have no idea how quickly that's coming though.
