### ISSUE TITLE
Examples for "Relative routes" -> upwards (//) and downwards (///) search

### ISSUE THREAD

**Issue by MaxFmi** [MicrosoftDocs/xamarin-docs#2806]
Can you add a few examples for the area "Relative routes" (it's currently documented as I've pasted below).

In addition, the following relative route formats are supported:

TABLE 1
Format	Description
//route	The route hierarchy will be searched for the specified route, upwards from the currently displayed route.
///route	The route hierarchy will be searched for the specified route, downwards from the currently displayed route.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b6efe82d-a8b9-82a8-7d38-98f2f8d5e682
* Version Independent ID: 28d7341e-ae6e-6321-6550-d27ae6b256d2
* Content: [Xamarin.Forms Shell Navigation - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/shell/navigation#feedback)
* Content Source: [docs/xamarin-forms/app-fundamentals/shell/navigation.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/app-fundamentals/shell/navigation.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @MaxFmi 

This is done in a PR that will go live later this week.
