### ISSUE TITLE
An example for where and how to override the OnXY methods at section "Tab class"

### ISSUE THREAD

**Issue by MaxFmi** [MicrosoftDocs/xamarin-docs#2807]
Can you add examples on where and how to override the following methods (section "Perform navigation" -&gt; "Tab class")?

GetNavigationStack, returns IReadOnlyList&lt;Page&gt;, the current navigation stack.
OnInsertPageBefore, that's called when INavigation.InsertPageBefore is called.
OnPopAsync, returns Task&lt;Page&gt;, and is called when INavigation.PopAsync is called.
OnPopToRootAsync, returns Task, and is called when INavigation.OnPopToRootAsync is called.
OnPushAsync, returns Task, and is called when INavigation.PushAsync is called.
OnRemovePage, that's called when INavigation.RemovePage is called.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b6efe82d-a8b9-82a8-7d38-98f2f8d5e682
* Version Independent ID: 28d7341e-ae6e-6321-6550-d27ae6b256d2
* Content: [Xamarin.Forms Shell Navigation - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/shell/navigation#feedback)
* Content Source: [docs/xamarin-forms/app-fundamentals/shell/navigation.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/app-fundamentals/shell/navigation.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @MaxFmi 

I've added an example of how to override one of these methods, in a PR that will go live later this week.
