### ISSUE TITLE
The comparison between C# and c# markup is tricky in the basic example

### ISSUE THREAD

**Issue by luismts** [MicrosoftDocs/xamarin-docs#2808]
In the c# basic example, you have 13 lines defining an entry object. And in the c# markup, you are defining the same object with 3 lines.

You can check it out [here](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/csharp-markup#basic-example).

The following example shows creating an Entry object in C#:

```
Entry entry = new Entry
{
    Placeholder = "Enter number",
    Keyboard = Keyboard.Numeric,
    BackgroundColor = Color.AliceBlue,
    TextColor = Color.Black,
    FontSize = 15,
    HeightRequest = 44,
    Margin = fieldMargin
};
entry.SetBinding(Entry.TextProperty, new Binding("RegistrationCode", BindingMode.TwoWay));
grid.Children.Add(entry, 0, 2);
Grid.SetColumnSpan(entry, 2);
```
The following example shows creating an Entry object in C# markup:

```
Entry entry = new Entry 
{ 
    Placeholder = "Enter number", 
    Keyboard = Keyboard.Numeric, 
    BackgroundColor = Color.AliceBlue, 
    TextColor = Color.Black 
} 
.Font(15)
.Row(BodyRow.CodeEntry) 
.ColumnSpan (All&lt;BodyCol&gt;()) 
.Margin(fieldMargin) 
.Height(44)
.Bind(nameof(vm.RegistrationCode), BindingMode.TwoWay);
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cc5d52fb-d4a2-7231-d2d4-3990b7634963
* Version Independent ID: 32b38657-d211-5bff-ee70-f9334aeb2053
* Content: [Xamarin.Forms C# markup - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/csharp-markup#feedback)
* Content Source: [docs/xamarin-forms/user-interface/csharp-markup.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/csharp-markup.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by VincentH-Net** [comment]
@luismts thanks for the contribution! 

However, when I invited you to add a reformatted sample I meant reformat the classic C#, not the C# Markup (I could have been more explicit I guess, but that is Twitter for you).

C# Markup has new, specific [formatting conventions](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/csharp-markup#recommended-convention) so we want to adhere to those. The original example of classic C# follows Xamarin standard formatting conventions - that is what resulted in the different number of lines.

Looking closer, the creation of the Grid should also be included to make them more equal - the classic C# example adds the `Entry` to the `Grid` children, while the C# Markup one does not. Also the default `BindingMode` for `Entry` is `TwoWay` so we can omit that.

For a more egual comparison, we can reformat the classic C# more like C# Markup, let both examples create the `Grid` and assign it to the `Page.Content`. And while we are at it, let's add a Label as well to better illustrate the cumulative difference between C# classic and C# Markup.

See my next comment for a proposed new doc snippet

**Comment by VincentH-Net** [comment]
For a more fair comparison, I propose to update the [Basic Example](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/csharp-markup#basic-example) to:

## Basic example
The following example sets the `Page.Content` to a new `Grid` with a `Label` and an `Entry`, in 'classic' C#:
```C#
var grid = new Grid();

var label = new Label { Text = "Code:" };
grid.Children.Add(label, 0, 1);

var entry = new Entry { Placeholder = "Enter number", Keyboard = Keyboard.Numeric, BackgroundColor = Color.AliceBlue, TextColor = Color.Black, FontSize = 15,
                        HeightRequest = 44, Margin = fieldMargin };
grid.Children.Add(entry, 0, 2);
Grid.SetColumnSpan(entry, 2);
entry.SetBinding(Entry.TextProperty, new Binding("RegistrationCode"));

Content = grid;
```
This example creates a `Grid` object, with child `Label` and `Entry` objects. The `Label` has a text, and the `Entry` data binds to the `RegistrationCode` property of the viewmodel. Each child view is set to appear in a specific row in the `Grid`. The `Entry` spans all the columns in the `Grid`. In addition, the height of the `Entry` is set, along with the font size of its text, and its `Margin`.

C# Markup enables this code to be re-written using its fluent API:
```C#
Content = new Grid { Children =
{
    new Label { Text = "Code:" }
               .Row (BodyRow.CodeHeader) .Column (BodyCol.Header),

    new Entry { Placeholder = "Enter number", Keyboard = Keyboard.Numeric, BackgroundColor = Color.AliceBlue, TextColor = Color.Black } .Font (15)
               .Row (BodyRow.CodeEntry) .ColumnSpan (All<BodyCol>()) .Margin (fieldMargin) .Height (44)
               .Bind (nameof(vm.RegistrationCode))
}};
```

**Comment by luismts** [comment]
@VincentH-Net Maybe it's my fault, don't worry. However, for me it makes more sense as follows:

### Basic example
**'Classic' C#**:

 ```cs
 var grid = new Grid();
 
 var label = new Label { Text = "Code:" };
 grid.Children.Add(label, 0, 1);
 
 var entry = new Entry 
{ 
    Placeholder = "Enter number", 
    Keyboard = Keyboard.Numeric, 
    BackgroundColor = Color.AliceBlue, 
    TextColor = Color.Black, 
    FontSize = 15,
    HeightRequest = 44, 
    Margin = fieldMargin 
};

 entry.SetBinding(Entry.TextProperty, new Binding("RegistrationCode"));

 grid.Children.Add(entry, 0, 2);
 Grid.SetColumnSpan(entry, 2);
 
 Content = grid;
 ```
 
 **C# Markup**:
 
 ```cs
 Content =  new Grid 
{ 
    Children = {
        new Label { Text = "Code:" }
            .Row(BodyRow.CodeHeader).Column(BodyCol.Header),
 
        new Entry { 
            Placeholder = "Enter number", 
            Keyboard = Keyboard.Numeric, 
            BackgroundColor = Color.AliceBlue, 
            TextColor = Color.Black 
        } 
        .Font(15)
        .Row(BodyRow.CodeEntry) 
        .ColumnSpan(All<BodyCol>()) 
        .Margin(fieldMargin) 
        .Height(44)
        .Bind(nameof(vm.RegistrationCode))
    }
};
```

**Comment by VincentH-Net** [comment]
@luismts the C# Markup formatting conventions have proven their value in years, but it is personal whether/when you recognize that. Maybe this will clarify it for you:
https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/csharp-markup#layout-line-convention

**Comment by VincentH-Net** [comment]
@luismts I wrote a better explanation in an introductory post for the Xamarin blog, however it is not yet published.l

**Comment by davidbritch** [comment]
I've updated the initial example in the docs, as per Vincent's recommendation.
