### ISSUE TITLE
Chrome Custom Tabs won't open, Custom Tabs will, which could end up being Firefox

### ISSUE THREAD

**Issue by kanderson-wellbeats** [MicrosoftDocs/xamarin-docs#2809]
The Platform Implementation Specifics section says for Android that Chrome Custom Tabs will be used to open if you choose System Preferred, but it looks like Custom Tabs is actually used (not necessarily Chrome) which uses what the user prefers, which could be Firefox for example.

Not a big deal, but got me turned around because, long story short, Firefox handles App Links very differently than Chrome.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0e1cc45d-67d0-81bf-918f-85da4c143c93
* Version Independent ID: 9143201f-a3a5-d283-ba8a-e84c471e9a0b
* Content: [Xamarin.Essentials Open Browser - Xamarin](https://docs.microsoft.com/en-us/xamarin/essentials/open-browser?tabs=android&source=docs#feedback)
* Content Source: [docs/essentials/open-browser.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/essentials/open-browser.md)
* Product: **xamarin**
* Technology: **xamarin-essentials**
* GitHub Login: @jamesmontemagno
* Microsoft Alias: **jamont**

**Comment by jamesmontemagno** [comment]
Ah, yes it is custom tabs in general, which is any browser that supports it :)

**Comment by jamesmontemagno** [comment]
App links you can use Launcher though too.

**Comment by jamesmontemagno** [comment]
Updated the docs to just say "Custom Tabs"
