### ISSUE TITLE
RtL + MasterDetail

### ISSUE THREAD

**Issue by michalec** [MicrosoftDocs/xamarin-docs#281]
Everything works well for me extep "hamburger" menu icon in masterdetail. It holds the left side even I change localization

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1e2456b6-d7c9-77b6-e588-0ab48106074e
* Version Independent ID: 5e5dde6b-d40d-f60b-e428-822f88e9d029
* Content: [Right-to-Left Localization - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/localization/right-to-left)
* Content Source: [docs/xamarin-forms/app-fundamentals/localization/right-to-left.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/app-fundamentals/localization/right-to-left.md)
* Service: **unspecified**
* Product: **xamarin**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @michalec 

Thanks for logging this issue. This is actually an issue with the RTL support present in Xamarin.Forms. There's an issue open for it on the engineering repo, which you can use to track progress in fixing it: https://github.com/xamarin/Xamarin.Forms/issues/2818
