### ISSUE TITLE
Issue with setting CarouselView position 

### ISSUE THREAD

**Issue by mehul19851** [MicrosoftDocs/xamarin-docs#2810]
Hello Team,

I am currently setting the position of CarouselView in page constructor. The value for position is determined from parameter which is passed in the page constructor.

Whenever the position value is set to 0 for first time in page init, the PositionChanged event does not get triggered. If the position value is set to any value greater than 0 in the page init, PositionChanged event gets triggered.

Note: The PositionChanged event does get triggered when user is swiping/interacting with CarouselView and reaches to first item (i.e. Index 0)

**XAML Code**
```
<CarouselView x:Name="ImagesCarouselView" IndicatorView="indicatorView" 
                                          PositionChanged="ImagesCarouselView_PositionChanged" 
```

**Codebehind**
```
public PageConstructor(ObservableCollection<ClassA> classAList, ClassA classAObject)
{
int itemIndex = ViewModel.ObservableCollnList
                .IndexOf(ViewModel.ObservableCollnList
                .First(x => x.Name.Equals(classAObject.ID.Name)));

            ImagesCarouselView.Position = itemIndex; //When itemIdex is 0, ImagesCarouselView_PositionChanged does not get triggered
}

/* where: ObservableCollnList = ObservableCollection<T> */

 private void ImagesCarouselView_PositionChanged(object sender, PositionChangedEventArgs e)
{
            Debug.WriteLine("Position " + e.CurrentPosition + " selected.");
}

```

Can you please have a look at this and let me know further inputs?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1d26c0a4-c31c-7e19-ee61-ad100c64d270
* Version Independent ID: 6cc6b815-7b99-4ae6-2972-26ed90ae3f2a
* Content: [Xamarin.Forms CarouselView Interaction - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/carouselview/interaction)
* Content Source: [docs/xamarin-forms/user-interface/carouselview/interaction.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/carouselview/interaction.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by logeshpalani98** [comment]
instead of position changing use
`carouselView.CurrentItemChanged += OnCurrentItemChanged;`

or 
position changed event use like 
```
void OnPositionChanged(object sender, PositionChangedEventArgs e)
{
    int previousItemPosition = e.PreviousPosition;
    int currentItemPosition = e.CurrentPosition;
}
```

**Comment by mehul19851** [comment]
@logeshpalani98 i have to set Position for CarouselView on page init, so the above solution is not applicable. This looks like a platform issue.

**Comment by davidbritch** [comment]
Hi @mehul19851 

I wouldn't be surprised if what you've described is a feature, rather than a bug. Regardless, it's something for the [engineering repo](https://github.com/xamarin/Xamarin.Forms/).
