### ISSUE TITLE
missing requirement in Android 

### ISSUE THREAD

**Issue by SOliasS** [MicrosoftDocs/xamarin-docs#2811]
I wasn't getting any return error or otherwise after  calling RequestAsync...
Finally found out that this was missing from my android MainActivity.
A remark that this is required would be nice....

     public override void OnRequestPermissionsResult(int requestCode, string[] permissions, [GeneratedEnum] Android.Content.PM.Permission[] grantResults)
        {
            Xamarin.Essentials.Platform.OnRequestPermissionsResult(requestCode, permissions, grantResults);

            base.OnRequestPermissionsResult(requestCode, permissions, grantResults);
        }

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5b055baf-759f-ed5a-d99d-ae9fed491588
* Version Independent ID: 76f823ff-dd9a-1bb6-8e71-29248ffca0c1
* Content: [Xamarin.Essentials: Permissions - Xamarin](https://docs.microsoft.com/en-us/xamarin/essentials/permissions?tabs=android#feedback)
* Content Source: [docs/essentials/permissions.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/essentials/permissions.md)
* Product: **xamarin**
* Technology: **xamarin-essentials**
* GitHub Login: @jamesmontemagno
* Microsoft Alias: **jamont**

**Comment by jamesmontemagno** [comment]
That is in the getting started: https://docs.microsoft.com/en-us/xamarin/essentials/permissions?context=xamarin%2Fandroid&tabs=android#get-started and in the new templates... could add it in that code directly.... however we would want to add it everywhere, which is why we just put a link... thoughts @davidbritch ?

**Comment by davidbritch** [comment]
@jamesmontemagno I think that adding an extra sentence, or note, to the get started section should take care of this (something along the lines of: This is particularly important on Android, which requires modifications to your `MainActivity` class).
