### ISSUE TITLE
We can use StaticResource

### ISSUE THREAD

**Issue by Paul-N** [MicrosoftDocs/xamarin-docs#2812]
Why not to point user that we can use StaticResource if we don't need to change theme in runtime? Using DynamicResource is consuming more resources than the StaticResource.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 455b1419-37da-f785-2c4e-b0bfa08ddd92
* Version Independent ID: ce2b3dba-4c9a-c756-94e1-395c8ce06f08
* Content: [Theming a Xamarin.Forms Application - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/theming/#feedback)
* Content Source: [docs/xamarin-forms/user-interface/theming/index.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/theming/index.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @Paul-N 

There's a distinction in my head that you are styling an app when using `StaticResource`, but you are theming an app when using `DynamicResource`, with theming including the ability to change theme. With that said, I think the doc can use a note along the lines of what you've said above. I'll get to this later in the week.

**Comment by davidbritch** [comment]
Hi @Paul-N 

I've updated the doc in a PR that will go live later today.
