### ISSUE TITLE
How to Logout from Xamarin Forms using WebAuthenticator 

### ISSUE THREAD

**Issue by SudhersonV** [MicrosoftDocs/xamarin-docs#2814]

**Comment by logeshpalani98** [comment]
```
 FormsAuthentication.SignOut();

            WebAuthenticator wa = new WebAuthenticator();
            
            wa.Logout(ResolveHostUrl("/"));
```

**Comment by SudhersonV** [comment]
> logout by using below code
> 
> ```
>             FormsAuthentication.SignOut();
> 
>             WebAuthenticator wa = new WebAuthenticator();
>             
>             wa.Logout(ResolveHostUrl("/"));
> ```
> 
> readmore about ios - https://developer.apple.com/documentation/authenticationservices/authenticating_a_user_through_a_web_service

Xamarin.Essentials.WebAuthenticator is a static class and it only has AuthenticateAsync method.

**Comment by davidbritch** [comment]
Hi @SudhersonV 

See https://github.com/xamarin/Essentials/issues/1223
