### ISSUE TITLE
 Please file a bug

### ISSUE THREAD

**Issue by eli191** [MicrosoftDocs/xamarin-docs#2816]
Hi,
I got this 
```
[CollectionView] An attempt to prepare a layout while a prepareLayout call was already in progress (i.e. reentrant call) has been ignored. Please file a bug. UICollectionView instance is (&lt;UICollectionView: 0x7fe7cbdb0800; frame = (0 0; 414 774); clipsToBounds = YES; autoresize = W+H; gestureRecognizers = &lt;NSArray: 0x600000d77960&gt;; layer = &lt;CALayer: 0x6000006a6d20&gt;; contentOffset: {0, 0}; contentSize: {414, 0}; adjustedContentInset: {0, 0, 0, 0}; layout: &lt;Xamarin_Forms_Platform_iOS_ListViewLayout: 0x7fe7cac3d560&gt;; dataSource: &lt;Xamarin_Forms_Platform_iOS_GroupableItemsViewController_1: 0x7fe7cac3dbc0&gt;&gt;)
Couldn't read view size for auto sizing
```
In the header template, I have an image and I am assigning the height of this image to a Binding.
`HeightRequest="{Binding HalfScreenWidth}"`
The collection view is displayed but not the image.
For information this value is 207, so not null or 0.

If I assign a fixed height (without binding), then I don't get this error and the headers images are displayed BUT the display is totally hazardous as some elements are behind the others.

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: db5e00a1-93a6-5965-70cc-cef81656dce0
* Version Independent ID: 11361877-6f4b-b0f7-0ece-5dc6a44f9ce0
* Content: [Xamarin.Forms CollectionView Layout - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/collectionview/layout)
* Content Source: [docs/xamarin-forms/user-interface/collectionview/layout.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/collectionview/layout.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @eli191 

This needs logging in the [engineering repo](https://github.com/xamarin/Xamarin.Forms/) so the engineers can debug the problem and produce a fix. Thanks!
