### ISSUE TITLE
Setting Window.DecorView.LayoutDirection does not set FlowDirection

### ISSUE THREAD

**Issue by Ghasan** [MicrosoftDocs/xamarin-docs#2817]
Hi,

If I set `Window.DecorView.LayoutDirection` to RTL, nothing happens in Android. I still need to set FlowDirection.

Is this a bug or something I don't understand?

For a context, see this SO question: https://stackoverflow.com/questions/61724519

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1e2456b6-d7c9-77b6-e588-0ab48106074e
* Version Independent ID: 5e5dde6b-d40d-f60b-e428-822f88e9d029
* Content: [Right-to-Left Localization - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/localization/right-to-left#feedback)
* Content Source: [docs/xamarin-forms/app-fundamentals/localization/right-to-left.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/app-fundamentals/localization/right-to-left.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @Ghasan 

It also requires you to have set `android:supportsRtl="true"` in your manifest, as per https://docs.microsoft.com/xamarin/xamarin-forms/app-fundamentals/localization/right-to-left#android

I'll make this clearer in the doc.

As an example, here's a screen from Xaminals in LTR:

![Screenshot_1604575618](https://user-images.githubusercontent.com/8092460/98235946-75df0580-1f5a-11eb-9b4e-04c24261cae0.png)

Setting `Window.DecorView.LayoutDirection = LayoutDirection.Rtl;` updates most of the page to RTL:

![Screenshot_1604575709](https://user-images.githubusercontent.com/8092460/98235967-7ecfd700-1f5a-11eb-87f0-01a56fed2a4d.png)

Unfortunately the `CollectionView` isn't responding to the layout direction change, and has to have its `FlowDirection` property set to RTL:

![Screenshot_1604575729](https://user-images.githubusercontent.com/8092460/98235988-868f7b80-1f5a-11eb-9e16-1bad126a59b8.png)

I'll also make this clearer in the doc

**Comment by davidbritch** [comment]
This is fixed in a PR that will go live tomorrow.
