### ISSUE TITLE
Specify minimum supported macOS version

### ISSUE THREAD

**Issue by chucker** [MicrosoftDocs/xamarin-docs#2819]
As noted at https://github.com/xamarin/Xamarin.Forms/issues/10647, a Xamarin.Forms app won't launch on macOS 10.9 or older, because `NSWindow.ContentViewController` was introduced in 10.10.

If there is a minimum _intended_ supported macOS version, it should probably be stated in the docs on this page. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 74613301-0081-297e-8bc1-8b34d8c1975b
* Version Independent ID: f803c7a6-45aa-9f78-5d7d-608ece2aa425
* Content: [Xamarin.Forms supported platforms - Xamarin](https://docs.microsoft.com/en-us/xamarin/get-started/supported-platforms?tabs=macos)
* Content Source: [docs/get-started/supported-platforms.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/get-started/supported-platforms.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @chucker 

Apologies for the delayed response to this issue. It's took some digging to find out the answer.

Anyway, macOS 10.13 is the minimum requirement. I've updated the doc, in a PR that will go live later today or tomorrow.

**Comment by chucker** [comment]
Thanks for researching this for me!
