### ISSUE TITLE
Responding

### ISSUE THREAD

**Issue by Domik234** [MicrosoftDocs/xamarin-docs#2820]
Hello,
I've tried your sample project and it doesn't work well.

Sample works only when theme is changed before opening application. When you change theme on launched application, colors won't change and opening next pages makes mix coloured ones (part of light theme and part of dark theme).

Regards,
Dominik Švarc

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 268fb9c0-4285-6fa6-2384-3b62a718cdb2
* Version Independent ID: 2d28787a-5161-2d0b-9250-4bbf1faccbad
* Content: [Respond to system theme changes in Xamarin.Forms applications - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/theming/system-theme-changes#feedback)
* Content Source: [docs/xamarin-forms/user-interface/theming/system-theme-changes.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/theming/system-theme-changes.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @Domik234 

Agreed that those problems exist in the sample. However, the sample code is correct, it's more that the feature in Xamarin.Forms doesn't work very well at the moment (which is why it's labelled experimental). The feature should improve in Xamarin.Forms 4.7-pre1 (due out soon).
