### ISSUE TITLE
Dead link

### ISSUE THREAD

**Issue by DennisBannerman** [MicrosoftDocs/xamarin-docs#2823]
The link to SkBlendMode Reference appears to be dead.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1eecb855-d86c-4848-c4be-45d79c4997ae
* Version Independent ID: fd414715-3499-b534-6163-10a1df86f223
* Content: [SkiaSharp blend modes - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/graphics/skiasharp/effects/blend-modes/#feedback)
* Content Source: [docs/xamarin-forms/user-interface/graphics/skiasharp/effects/blend-modes/index.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/graphics/skiasharp/effects/blend-modes/index.md)
* Product: **xamarin**
* Technology: **xamarin-skiasharp**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @DennisBannerman 

Thanks for pointing this out. I've fixed the link, in a PR that will go live later today.
