### ISSUE TITLE
Error In equiv c# code for creating a Circle radius

### ISSUE THREAD

**Issue by LuckyDucko** [MicrosoftDocs/xamarin-docs#2829]
```csharp 
Circle circle = new Circle
{
    Center = new Position(37.79752, -122.40183);,
    Radius = new Distance(250),
    StrokeColor = Color.FromHex("#88FF0000"),
    StrokeWidth = 8,
    FillColor = Color.FromHex("#88FFC0CB")
};
```

There is an extra ; on the `Center = new Position(37.79752, -122.40183);,`
that makes this snippet fail to compile.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eac67304-2af7-b7e1-0cdd-f66ca5d7b585
* Version Independent ID: edd838d1-0506-222b-beca-1d3c0c52b465
* Content: [Xamarin.Forms Map Polygons, Polylines, and Circles - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/map/polygons)
* Content Source: [docs/xamarin-forms/user-interface/map/polygons.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/map/polygons.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @LuckyDucko 

Thanks for pointing this out. I've fixed it, in a PR that will go live later today.
