### ISSUE TITLE
Mutually exclusive lines in documentation

### ISSUE THREAD

**Issue by Tommigun1980** [MicrosoftDocs/xamarin-docs#2830]
"It's best to check the status of the permission before requesting it. Each operating system returns a different default state if the user has never been prompted. iOS returns Unknown, while others return Denied."

These two sentences are mutually exclusive. If it returns 'Denied' on Android even when it's not been requested yet, there's no point in doing the check as you can't know if the user has been asked yet.

Suggestion: Call 'shouldShowRequestPermissionRationale' on Android when status returns Denied, and convert its response to 'Unknown' or 'Denied'. Then they can be differentiated between also on Android, and "It's best to check the status of the permission before requesting it" will be possible.

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5b055baf-759f-ed5a-d99d-ae9fed491588
* Version Independent ID: 76f823ff-dd9a-1bb6-8e71-29248ffca0c1
* Content: [Xamarin.Essentials: Permissions - Xamarin](https://docs.microsoft.com/en-us/xamarin/essentials/permissions?tabs=android)
* Content Source: [docs/essentials/permissions.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/essentials/permissions.md)
* Product: **xamarin**
* Technology: **xamarin-essentials**
* GitHub Login: @jamesmontemagno
* Microsoft Alias: **jamont**

**Comment by jamesmontemagno** [comment]
In 1.6 we are adding shouldShowRequestPermissionRationale however that is only for Android. It is still best practice to check if it is denied or unknown ahead of requesting it... 

If you are on iOS and it is denied you should prompt the user.

**Comment by Tommigun1980** [comment]
> In 1.6 we are adding shouldShowRequestPermissionRationale however that is only for Android. It is still best practice to check if it is denied or unknown ahead of requesting it...
> 
> If you are on iOS and it is denied you should prompt the user to change their settings. I will leave it to @davidbritch for wording

Thank you, that's great to hear! I had to make an extended version of the permission manager just to get the shouldShowRequestPermissionRationale in, so it's always nice when code can be removed. I really appreciate it.

Thanks.

**Comment by jamesmontemagno** [comment]
1.6-pre is live and i have updated the docs.
