### ISSUE TITLE
PermissionStatus.Disabled?

### ISSUE THREAD

**Issue by Tommigun1980** [MicrosoftDocs/xamarin-docs#2831]
When exactly will PermissionStatus.Disabled be returned when checking for a permission? A quick look at the sources shows that only WatchOS seems to return it. Hence my follow-up question: Shouldn't it be returned in the same case where a FeatureNotEnabledException is thrown when requesting a permission?

Use case:
Check if a permission has been granted.
If it's Unknown, explain why it will ask for permissions and perform ask.
If it's Disabled, explain that the user should enable the hardware feature.
If it's Denied, try to upsell user on turning it on in his Preferences.

To the best of my understanding you can't do that currently, as checking for a permission does not take feature disabling into account (only requesting for a permission seems to do it, even though that status code exists in the permission check result). I want to check for this *before* I actually ask the user, so he knows _why_ the permission prompt will be shown.

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5b055baf-759f-ed5a-d99d-ae9fed491588
* Version Independent ID: 76f823ff-dd9a-1bb6-8e71-29248ffca0c1
* Content: [Xamarin.Essentials: Permissions - Xamarin](https://docs.microsoft.com/en-us/xamarin/essentials/permissions?tabs=android)
* Content Source: [docs/essentials/permissions.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/essentials/permissions.md)
* Product: **xamarin**
* Technology: **xamarin-essentials**
* GitHub Login: @jamesmontemagno
* Microsoft Alias: **jamont**

**Comment by jamesmontemagno** [comment]
iOS would return that status if the feature was disabled. You would need to check apple docs for each API.
