### ISSUE TITLE
Shouldn't this be the other way around then?

### ISSUE THREAD

**Issue by wrkettlitz** [MicrosoftDocs/xamarin-docs#2832]
"Behavior is undefined when the minimum value is greater than the absolute value. For example, if MinimumWidthRequest is set to 100, the WidthRequest property should never exceed 100."

Shouldn't it be:

"Behavior is undefined when the minimum value is greater than the absolute value. For example, if WidthRequest is set to 100, the MinimumWidthRequest property should never exceed 100."

Or am i completely misunderstanding this?  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1e23d082-44c6-6139-f2a3-8a1286e6b48a
* Version Independent ID: 5c402cd7-0cb4-2d7b-66b8-fa0df4221e9c
* Content: [Xamarin.Forms common control properties, methods, and events - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/controls/common-properties#request-properties)
* Content Source: [docs/xamarin-forms/user-interface/controls/common-properties.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/controls/common-properties.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @profexorgeek
* Microsoft Alias: **jusjohns**

**Comment by davidbritch** [comment]
Hi @wrkettlitz 

I agree that you're correct. Thanks for pointing this out. I've fixed it, in a PR that will go live later today.
