### ISSUE TITLE
The wrong term must be changed

### ISSUE THREAD

**Issue by pstricks-fans** [MicrosoftDocs/xamarin-docs#2833]
Quoted from the passage above, 

&gt; Each bindable property has a corresponding public static readonly **PROPERTY** of type BindableProperty that is exposed on the same class and that is the identifier of the bindable property. 

It should be

Each bindable property has a corresponding public static readonly **FIELD** of type BindableProperty that is exposed on the same class and that is the identifier of the bindable property. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b054a909-6f7f-0b32-5059-eb5c8a9b366b
* Version Independent ID: 723af07b-8f4e-ebe3-a520-99cdcf5efc5a
* Content: [Xamarin.Forms Bindable Properties - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/xaml/bindable-properties)
* Content Source: [docs/xamarin-forms/xaml/bindable-properties.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/xaml/bindable-properties.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @pstricks-fans 

Agreed. Thanks for pointing this out. I've fixed it, in a PR that will go live later today.
