### ISSUE TITLE
Wrong class name for UITableViewCell in "Subclassing UITableViewSource" section

### ISSUE THREAD

**Issue by gentilijuanmanuel** [MicrosoftDocs/xamarin-docs#2835]
In the "Subclassing UITableViewSource" section, when the docs describe the `GetCell` method, there is an error related to the `UITableViewCell` class name. It says `UITableCellView`.

Screenshot:
<img width="801" alt="Screen Shot 2020-05-15 at 14 06 02" src="https://user-images.githubusercontent.com/14587789/82077121-417a4300-96b5-11ea-8b37-3169c9a61201.png">

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 94d6f38e-dc15-369d-da78-61515af42712
* Version Independent ID: d1ad32a7-f496-de53-745b-da16fde1ff3d
* Content: [Populating a Table with Data in Xamarin.iOS - Xamarin](https://docs.microsoft.com/en-us/xamarin/ios/user-interface/controls/tables/populating-a-table-with-data)
* Content Source: [docs/ios/user-interface/controls/tables/populating-a-table-with-data.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/ios/user-interface/controls/tables/populating-a-table-with-data.md)
* Product: **xamarin**
* Technology: **xamarin-ios**
* GitHub Login: @davidortinau
* Microsoft Alias: **daortin**

**Comment by davidbritch** [comment]
Closing due to your PR that fixed this. Thanks!
