### ISSUE TITLE
Compatibility pre-iOS 9

### ISSUE THREAD

**Issue by nosmalldreams** [MicrosoftDocs/xamarin-docs#2837]
Thanks for this new library! I see that AppDelegate.OpenUrl method was updated in iOS 9 to use the signature you cite above. If I want my URL redirects to work even prior to iOS9, where my OpenUrl method signature has parameters string sourceApplicationString and NSObject annotation instead of an NSDictionary options, how do I generate the options parameter that Xamarin.Essentials.Platform.OpenUrl requires?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1231a1e1-3734-9021-2cc7-eaf99478afca
* Version Independent ID: 01e5fdbe-0b15-4dbe-f8a0-ed40f8593302
* Content: [Xamarin.Essentials: Web Authenticator - Xamarin](https://docs.microsoft.com/en-us/xamarin/essentials/web-authenticator?tabs=ios)
* Content Source: [docs/essentials/web-authenticator.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/essentials/web-authenticator.md)
* Product: **xamarin**
* Technology: **xamarin-essentials**
* GitHub Login: @Redth
* Microsoft Alias: **jodick**

**Comment by jamesmontemagno** [comment]
Xamarin.Essentials only officially supports iOS 10+.

WebAuthenticator will use SFSafariView on iOS 9+ though.

There is no official support for anything less than <10, however this API should work in 9, but not < 9.
