### ISSUE TITLE
LabelShadowEffect  ShadowRadius on iOS

### ISSUE THREAD

**Issue by jvlppm** [MicrosoftDocs/xamarin-docs#2840]
LabelShadowEffect sample code for iOS is setting CornerRadius instead of ShadowRadius

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9e558c10-1e81-b045-47da-47000fa1ff00
* Version Independent ID: 93bb9c1b-451e-81a4-c2fc-41a9cdddc6a0
* Content: [Passing Effect Parameters as Attached Properties - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/effects/passing-parameters/attached-properties#feedback)
* Content Source: [docs/xamarin-forms/app-fundamentals/effects/passing-parameters/attached-properties.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/app-fundamentals/effects/passing-parameters/attached-properties.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @jvlppm 

Thanks for pointing this out. I've updated the doc (and sample), in a PR that'll go live later today.
