### ISSUE TITLE
images are cropped SearchHandler ios

### ISSUE THREAD

**Issue by cramirezoliveros** [MicrosoftDocs/xamarin-docs#2841]
Shell.SearchHandler 
in the xamanimals iOs example, the images are cropped, did you notice that?
Can I do something to avoid it?

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ea22bfa0-1713-6aff-9c8c-dedf47bb3381
* Version Independent ID: f9b7e5be-4b5a-c292-c425-89125369b97b
* Content: [Xamarin.Forms Shell Search - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/shell/search)
* Content Source: [docs/xamarin-forms/app-fundamentals/shell/search.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/app-fundamentals/shell/search.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @cramirezoliveros 

Yes. That's deliberate. The `DataTemplate` for the search handler sets the `Image.Aspect` property to `AspectFill`. While this crops the image, it ensures that all the images have identical dimensions. Changing `Image.Aspect` to `AspectFit` ensures the images aren't cropped, but then the images all end up having slightly different sizes. It's a trade off.

**Comment by cramirezoliveros** [comment]
Hi davidbritch, thanks for the answer, what I wanted to emphasize is that in iOS, the height of the row does not adapt to the height of the content, but in Android it does, and also, if the datatemplate is with a grid, and if there are two rows, one overlaps. to the other. iOs does not respect the number of rows.

**Comment by davidbritch** [comment]
Hi @cramirezoliveros 

That issue needs logging in the [engineering repo](https://github.com/xamarin/Xamarin.Forms/). Thanks!
