### ISSUE TITLE
Accent Color?

### ISSUE THREAD

**Issue by realivanjx** [MicrosoftDocs/xamarin-docs#2844]
Is there a guide to set accent color instead of just black?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fbfbc90e-2eb6-a305-f7da-bded6e31a2b4
* Version Independent ID: 66cad08c-2158-c081-a668-e4dad525e664
* Content: [Xamarin.Forms Material Visual - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/visual/material-visual)
* Content Source: [docs/xamarin-forms/user-interface/visual/material-visual.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/visual/material-visual.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @profexorgeek
* Microsoft Alias: **jusjohns**

**Comment by davidbritch** [comment]
Hi @realivanjx 

You can use the `Color.SetAccent` method from anywhere that has a Xamarin.Forms reference including your Android project. Note, it won't appear in intellisense.

**Comment by realivanjx** [comment]
Thank you
