### ISSUE TITLE
Incorrect "In this article" items

### ISSUE THREAD

**Issue by MarcusOy** [MicrosoftDocs/xamarin-docs#2845]
Hi there,

There seems to be some ghost sections on this article. See "API Level 23 and Higher" and "API Level 22 and Lower." Also, the indicator seems to be stuck on API Level 22 and Lower when on the upper sections of the article.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: da75050f-bfda-4792-40d9-b9a25d649d3e
* Version Independent ID: 5c44f996-765b-f6e4-c807-9446c534d50b
* Content: [Xamarin.Essentials: Secure Storage - Xamarin](https://docs.microsoft.com/en-us/xamarin/essentials/secure-storage?tabs=uwp#platform-implementation-specifics)
* Content Source: [docs/essentials/secure-storage.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/essentials/secure-storage.md)
* Product: **xamarin**
* Technology: **xamarin-essentials**
* GitHub Login: @jamesmontemagno
* Microsoft Alias: **jamont**

**Comment by jamesmontemagno** [comment]
will fix up, good find.

**Comment by jamesmontemagno** [comment]
Pushed out a change should go live soon.
