### ISSUE TITLE
Worst IDE i have ever used in my entire life

### ISSUE THREAD

**Issue by fazal-sharif-confiz** [MicrosoftDocs/xamarin-docs#2846]
Why you guys release something without proper support of it. We Android developers face nightmares when we are forced to work on xamarin and visual studio

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9d9d0953-d803-edff-6110-36af2d053c05
* Version Independent ID: 8dfb9e22-775f-d29d-2aae-9f6bf8e145ba
* Content: [Android build error – The LinkAssemblies task failed unexpectedly - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/troubleshooting/questions/android-linkassemblies-error#feedback)
* Content Source: [docs/xamarin-forms/troubleshooting/questions/android-linkassemblies-error.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/troubleshooting/questions/android-linkassemblies-error.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @fazal-sharif-confiz 

Thanks for your feedback.
