### ISSUE TITLE
Why there is no UWP case

### ISSUE THREAD

**Issue by CeciAc** [MicrosoftDocs/xamarin-docs#2847]
The comments below were machine-translated

@Wowitt commented on [Sat May 16 2020](https://github.com/MicrosoftDocs/xamarin-docs.zh-cn/issues/66)

Why is there no image use case for UWP programs?
Hope to get a reply! Thanks

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 679634c0-a0c6-cc03-c50f-6d22ce71c099
* Version Independent ID: 874062b9-a51b-a10d-4d27-d3811fa9b56b
* Content: [Xamarin.Forms 图像教程 - Xamarin](https://docs.microsoft.com/zh-cn/xamarin/get-started/tutorials/image/?tutorial-step=4&tabs=vswin#feedback)
* Content Source: [docs/get-started/tutorials/image/index.yml](https://github.com/MicrosoftDocs/xamarin-docs.zh-cn/blob/live/docs/get-started/tutorials/image/index.yml)
* Product: **xamarin**
* Technology: **xamarin-crossplatform**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

---

@srvbpigh commented on [Sat May 16 2020](https://github.com/MicrosoftDocs/xamarin-docs.zh-cn/issues/66#issuecomment-629681881)

Hello, @Wowitt
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by davidbritch** [comment]
Hi @Wowitt

Our tutorials target iOS/Android because those platforms are the focus of the majority of our users. However, our main image doc has information about image handling on UWP in Xamarin.Forms - https://docs.microsoft.com/xamarin/xamarin-forms/user-interface/images
