### ISSUE TITLE
Added UWP Application in Existing Xamrin App gives error

### ISSUE THREAD

**Issue by MobilyteApps** [MicrosoftDocs/xamarin-docs#2849]
I am using Visual studio community version 16.3.6 and when i added reference to main core project then giving error. 

Could not copy the file "obj\x86\Debug\App.xbf" because it was not found.
Could not copy the file "obj\x86\Debug\App.xbf" because it was not found.
Could not copy the file "obj\x86\Debug\MainPage.xbf" because it was not found

**Comment by davidbritch** [comment]
Hi @MobilyteApps 

The following doc shows how to add a UWP project to a Xamarin.Forms solution: https://docs.microsoft.com/xamarin/xamarin-forms/platform/windows/installation/
