### ISSUE TITLE
some screens are out of date

### ISSUE THREAD

**Issue by jphellemons** [MicrosoftDocs/xamarin-docs#285]
start from step 2 there is no (longer) an ios or bundle option

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72df5e83-6b77-9864-2016-febdcec0e94c
* Version Independent ID: 7ef7dad6-462c-347e-fd5a-e1b1f13ca26b
* Content: [Configuring an App in iTunes Connect - Xamarin](https://docs.microsoft.com/en-us/xamarin/ios/deploy-test/app-distribution/app-store-distribution/itunesconnect#feedback)
* Content Source: [docs/ios/deploy-test/app-distribution/app-store-distribution/itunesconnect.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/ios/deploy-test/app-distribution/app-store-distribution/itunesconnect.md)
* Service: **unspecified**
* Product: **xamarin**
* GitHub Login: @bradumbaugh
* Microsoft Alias: **brumbaug**

**Comment by bradumbaugh** [comment]
Hi @jphellemons – thanks for calling this out. It looks like these screens have changed significantly since this doc was last updated. I've captured this item on our internal backlog. Appreciate the heads-up!

**Comment by AmirMahdiNassiri** [comment]
It's 2020 and still the guide is outdated!
