### ISSUE TITLE
Where to declare xmlns:local XAML namespace when consuming attached property with style?

### ISSUE THREAD

**Issue by mohitatray** [MicrosoftDocs/xamarin-docs#2853]
Where to declare xmlns:local XAML namespace when consuming attached property with style - the file in which style is defined OR the file in which label is present?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ce1d57d-d599-89c2-3cd4-9c3048dc75f7
* Version Independent ID: 2bf6d771-008b-6e79-4136-114c3dd77733
* Content: [Attached Properties - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/xaml/attached-properties)
* Content Source: [docs/xamarin-forms/xaml/attached-properties.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/xaml/attached-properties.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @mohitatray 

The sample linked to from the doc will show you where.
