### ISSUE TITLE
Where is the documentation for OnThisPlatform() method?

### ISSUE THREAD

**Issue by mohitatray** [MicrosoftDocs/xamarin-docs#2854]
I cannot find a method named OnThisPlatform() in Xamarin.Forms.Label class documentation. Where did this method come from? Which namespace and class this method belongs to?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 29831d4e-b931-c6fa-9a7b-ac3d2ff8f67c
* Version Independent ID: 9117e985-c3e2-b419-5ae4-da008050130f
* Content: [Platform-Specifics - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/platform/platform-specifics/)
* Content Source: [docs/xamarin-forms/platform/platform-specifics/index.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/platform/platform-specifics/index.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @davidbritch 

Look at the sample this doc links to.
