### ISSUE TITLE
On step 11, the argument to LoadApplication method is the Xamarin.Forms.Application instance (defined inside .NET standard project), instead of Win.Ui.Xaml.Application.

### ISSUE THREAD

**Issue by MrClan** [MicrosoftDocs/xamarin-docs#2855]
Due to matching names of classes and files(App, App.xaml.cs) between Xamarin.Forms and the default UWP application, this seems like a very common source of confusion, especially during first time setup. So, it is better that this information is clearly and explicitly mentioned in the docs.
Same issue discussed here:
https://forums.xamarin.com/discussion/59245/cannot-convert-from-helloxuwp-app-to-xamarin-forms-application-in-win10-uwp

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2ec3998b-c321-10e6-8e06-b10900c3a549
* Version Independent ID: de666c26-6261-7762-2c18-1576499b5fac
* Content: [Setup Windows Projects - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/platform/windows/installation/#feedback)
* Content Source: [docs/xamarin-forms/platform/windows/installation/index.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/platform/windows/installation/index.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @MrClan 

I've added a clarification to the doc, in a PR that will go live in the next hour.
