### ISSUE TITLE
Document More Behavior

### ISSUE THREAD

**Issue by realivanjx** [MicrosoftDocs/xamarin-docs#2856]
I found that if you define route in XAML with `Route=""` and with `Routing.RegisterRoute()` and then call `GoToAsync()` it will push the page into navigation stack. If you just define it in XAML (with `Route=""` property) and call `GoToAsync()`, it wont push the page into navigation stack and when you tap hardware back button on Android platform, it will straight close the app immediately.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b6efe82d-a8b9-82a8-7d38-98f2f8d5e682
* Version Independent ID: 28d7341e-ae6e-6321-6550-d27ae6b256d2
* Content: [Xamarin.Forms Shell Navigation - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/shell/navigation#feedback)
* Content Source: [docs/xamarin-forms/app-fundamentals/shell/navigation.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/app-fundamentals/shell/navigation.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by realivanjx** [comment]
Similar behavior can also be found [here](https://forums.xamarin.com/discussion/164175/how-to-navigate-in-shell-without-pushing-in-the-existing-navigation-stack)

**Comment by davidbritch** [comment]
Hi @realivanjx 

This is already documented: "When a route from the Shell visual hierarchy is navigated to, a navigation stack isn't created. However, when a page that's not in the Shell visual hierarchy is navigated to, a navigation stack is created."

Put more simply: when you define routes in XAML, navigation doesn't result in a navigation stack. However, when a route is registered with RegisterRoute, GotoAsync pushes the route onto the navigation stack.

With all that said, the Shell docs are due a refresh to make them clearer. When that happens I'll make sure this gets explained more clearly.
