### ISSUE TITLE
FrameRenderer

### ISSUE THREAD

**Issue by realivanjx** [MicrosoftDocs/xamarin-docs#2857]
Frame renderer on newer android should use `Xamarin.Forms.Platform.Android.AppCompat.FrameRenderer` instead.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cfee594b-8ecc-0d4d-9384-e4afe792b3dd
* Version Independent ID: 9957d9e1-1ebc-aadb-90bb-5e80b595bade
* Content: [Renderer Base Classes and Native Controls - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/custom-renderer/renderers)
* Content Source: [docs/xamarin-forms/app-fundamentals/custom-renderer/renderers.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/app-fundamentals/custom-renderer/renderers.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @realivanjx 

Technically it should be `Xamarin.Forms.Platform.Android.FastRenderers.FrameRenderer` as the `AppCompat.FrameRenderer` simply subclasses that:

```
namespace Xamarin.Forms.Platform.Android.AppCompat
{
    // This version of FrameRenderer is here for backward compatibility with anyone referencing 
    // FrameRenderer from this namespace
    public class FrameRenderer : FastRenderers.FrameRenderer
    {
	    public FrameRenderer(Context context) : base(context)
	    {
		    
	    }

	    [Obsolete("This constructor is obsolete as of version 2.5. Please use FrameRenderer(Context) instead.")]
		[EditorBrowsable(EditorBrowsableState.Never)]
		public FrameRenderer()
	    {
		   
	    }
    }
}
```

But yes, I get your point and have updated the doc in a PR that will go live later today.

**Comment by TsplayerT** [comment]
I tested a project with a version Xamarin 5.0.0.1539-pre2 and occored error.

`System.ObjectDisposedException: Cannot access a dropped object`

Using this line `Forms.SetFlags ("UseLegacyRenderers")` in the project the exception have the ObjectName: 
`Xamarin.Forms.Platform.Android.AppCompat.FrameRenderer`

Without flag line the ObjectName:
`Xamarin.Forms.Platform.Android.FastRenderers.FrameRenderer`

Here it is stack trace:

| Main thread  |  Details  |
| ------------------- | ------------------- |
|  Java.Interop |  JniPeerMembers.AssertSelf (Java.Interop.IJavaPeerable self) |
|  Java.Interop |  JniPeerMembers+JniInstanceMethods.InvokeVirtualVoidMethod (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters) |
|  Android.Views |  View.set_Enabled (System.Boolean value) |
|  Xamarin.Forms.Platform.Android.FastRenderers |  VisualElementRenderer.UpdateIsEnabled () |
|  Xamarin.Forms.Platform.Android.FastRenderers |  VisualElementRenderer.OnElementPropertyChanged (System.Object sender, System.ComponentModel.PropertyChangedEventArgs e) (wrapper delegate-invoke <Module>.invoke_void_object_PropertyChangedEventArgs(object,System.ComponentModel.PropertyChangedEventArgs) |
|  Xamarin.Forms |  BindableObject.OnPropertyChanged (System.String propertyName) |
|  Xamarin.Forms |  Element.OnPropertyChanged (System.String propertyName) |
|  Xamarin.Forms |  BindableObject.SetValueActual (Xamarin.Forms.BindableProperty property, Xamarin.Forms.BindableObject+BindablePropertyContext context, System.Object value, System.Boolean currentlyApplying, Xamarin.Forms.Internals.SetValueFlags attributes, System.Boolean silent) |
|  Xamarin.Forms |  BindableObject.SetValueCore (Xamarin.Forms.BindableProperty property, System.Object value, Xamarin.Forms.Internals.SetValueFlags attributes, Xamarin.Forms.BindableObject+SetValuePrivateFlags privateAttributes) |
|  Xamarin.Forms |  BindingExpression.ApplyCore (System.Object sourceObject, Xamarin.Forms.BindableObject target, Xamarin.Forms.BindableProperty property, System.Boolean fromTarget) |
|  Xamarin.Forms |  BindingExpression.Apply (System.Boolean fromTarget) |
|  Xamarin.Forms |  BindingExpression+BindingExpressionPart.<PropertyChanged>b__49_0 () |
|  Java.Lang |  Thread+RunnableImplementor.Run () |
|  Java.Lang |  IRunnableInvoker.n_Run (System.IntPtr jnienv, System.IntPtr native__this) (wrapper dynamic-method) Android.Runtime.DynamicMethodNameCounter.24(intptr,intptr) |


The details of the error and other information are attached. [report.txt](https://github.com/xamarin/Xamarin.Forms/files/5385658/report.txt)
