### ISSUE TITLE
ReadAsString

### ISSUE THREAD

**Issue by spelltwister** [MicrosoftDocs/xamarin-docs#2860]
While for the example it definitely is more clear to use ReadAsStringAsync and JsonConvert.Deserialize that json string into objects, there should maybe be a note that this can lead to poor performance and increased memory footprint, especially for large responses, since a string has to be created.  Newtonsoft.Json supports deserializing from the response stream directly without requiring the string to be created which can have other improvements as well like not requiring the response to be fully buffered.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 155a1af2-3ce7-058b-d243-b4d7a9cd6e22
* Version Independent ID: 47f0df9e-ab6a-a38b-5916-991b5110ebf1
* Content: [Consume a RESTful Web Service - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/data-cloud/web-services/rest#feedback)
* Content Source: [docs/xamarin-forms/data-cloud/web-services/rest.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/data-cloud/web-services/rest.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @spelltwister 

Thanks for pointing this out. I've updated the doc in a PR that will go live today or tomorrow.
