### ISSUE TITLE
Visual Studio for Mac instructions are missing a step

### ISSUE THREAD

**Issue by benday** [MicrosoftDocs/xamarin-docs#2861]
For item #3 "In the Signing section, select Automatic Provisioning:", you need to go to the "Application" tab after opening Info.plist.  Item #3 should read something like "At the bottom of the Info.plist window, click the Application tab.  Then in the Signing section, select Automatic Provisioning:"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5ccadd93-fcc8-6a15-9670-d5af7ee7f6f8
* Version Independent ID: 188007d3-cf20-97ba-137f-64ff25a88e7c
* Content: [Automatic Provisioning for Xamarin.iOS - Xamarin](https://docs.microsoft.com/en-us/xamarin/ios/get-started/installation/device-provisioning/automatic-provisioning?tabs=macos#feedback)
* Content Source: [docs/ios/get-started/installation/device-provisioning/automatic-provisioning.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/ios/get-started/installation/device-provisioning/automatic-provisioning.md)
* Product: **xamarin**
* Technology: **xamarin-ios**
* GitHub Login: @davidortinau
* Microsoft Alias: **daortin**

**Comment by PureWeen** [comment]
Thank you for the report!

Looks like this was addressed here
https://github.com/MicrosoftDocs/xamarin-docs/commit/ca1eca5bcf6c82bc4ec05db12ee1be585006d59f
