### ISSUE TITLE
Hot Reload?

### ISSUE THREAD

**Issue by realivanjx** [MicrosoftDocs/xamarin-docs#2867]
Is hot reload available for cs markup?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cc5d52fb-d4a2-7231-d2d4-3990b7634963
* Version Independent ID: 32b38657-d211-5bff-ee70-f9334aeb2053
* Content: [Xamarin.Forms C# markup - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/csharp-markup#data-binding)
* Content Source: [docs/xamarin-forms/user-interface/csharp-markup.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/csharp-markup.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @realivanjx 

Afraid not. Hot reload is for XAML. For C# you should give [Hot restart](https://docs.microsoft.com/xamarin/xamarin-forms/deploy-test/hot-restart) a go.

**Comment by realivanjx** [comment]
Thanks. One more, is there any roadmap for hot restart? It would be good to have one in android too soon.
