### ISSUE TITLE
This article should be updated

### ISSUE THREAD

**Issue by mike-01** [MicrosoftDocs/xamarin-docs#2869]
The article states to use "sqlite-net-pcl" from Frank A. Krueger. The project associated with his name in NuGet (v3.1.1) is deprecated and this article conflicts with the more recent article at [https://docs.microsoft.com/en-us/samples/xamarin/xamarin-forms-samples/todo/](https://docs.microsoft.com/en-us/samples/xamarin/xamarin-forms-samples/todo/) 

I believe the author now is "SQLite-net" and the project is located at [https://github.com/praeclarum/sqlite-net](https://github.com/praeclarum/sqlite-net)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bdcea465-138a-d586-5297-dc93370826b3
* Version Independent ID: a41a6f67-0675-036f-0781-13b9165d3848
* Content: [Xamarin.Forms Local Databases - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/data-cloud/data/databases)
* Content Source: [docs/xamarin-forms/data-cloud/data/databases.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/data-cloud/data/databases.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @profexorgeek
* Microsoft Alias: **jusjohns**

**Comment by davidbritch** [comment]
Hi @mike-01 

It still looks like it's sqlite-net-pcl to me: https://www.nuget.org/packages/sqlite-net-pcl

**Comment by davidbritch** [comment]
But yes, the doc does require a minor update to be more precise (Owner is praeclarum).

**Comment by davidbritch** [comment]
I've updated the doc in a PR that will go live later today/tomorrow.
