### ISSUE TITLE
Deprecated function used in example.

### ISSUE THREAD

**Issue by wrkettlitz** [MicrosoftDocs/xamarin-docs#2870]
Under IOS implementation.

``` C#
viewController.PresentModalViewController(imagePicker, true);
```
Is used even though `PresentModalViewController` is deprecated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 22cd76be-2702-6a58-498c-a84c723d9588
* Version Independent ID: 9f98549e-ff3d-5b8d-67e6-523834c4dd6d
* Content: [Picking a Photo from the Picture Library - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/dependency-service/photo-picker)
* Content Source: [docs/xamarin-forms/app-fundamentals/dependency-service/photo-picker.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/app-fundamentals/dependency-service/photo-picker.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @wrkettlitz 

Thanks for pointing this out. I've updated the samples that use the deprecated method, and I've also updated the docs in a PR that will go live later today.
