### ISSUE TITLE
Link to PDF file is wrong.

### ISSUE THREAD

**Issue by christiannagel** [MicrosoftDocs/xamarin-docs#2873]
The link to the PDF format of the book "Creating Mobile Apps with Xamarin.Forms" does not work: https://aka.ms/xamebook

I also tried https://aka.ms/xamebook/pdf doesn't work as well. What's the correct link?

The downloads for ePub and Kindle are ok.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 552cf4bf-553b-d7f4-adc6-7e696029c18b
* Version Independent ID: 67f96253-4908-3f85-fd2f-07563d1b4f7b
* Content: [Creating Mobile Apps with Xamarin.Forms book - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/creating-mobile-apps-xamarin-forms/)
* Content Source: [docs/xamarin-forms/creating-mobile-apps-xamarin-forms/index.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/creating-mobile-apps-xamarin-forms/index.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @christiannagel 

The aka.ms link has ceased to exist for some reason, so I'll recreate it later this week. But for now you can download the PDF from https://download.microsoft.com/download/7/8/8/788971A6-C4BB-43CA-91DC-557B8BE72928/Microsoft_Press_eBook_CreatingMobileAppswithXamarinForms_PDF.pdf

**Comment by davidbritch** [comment]
Hi @christiannagel 

I've updated the link in a PR that will go live later today.
