### ISSUE TITLE
Mutually Exclusive State for IsExpanded property of Xamarin.Forms.Expander

### ISSUE THREAD

**Issue by microwales** [MicrosoftDocs/xamarin-docs#2875]
T%his is not an issue but a feature requests.

First, thank you and congratulations for the great control. This will save developers (like me) and companies using Xamarin (again like mine) a lot of man hours to creating new controls or buying another control that will work out of the box.

I am really happy Xamarin (>> MAUI lols ) is becoming more mature and stable and popular with great useful controls out of the box. Please keep this up. We are rooting for you!

My feedback is very straightforward, please consider having a property to make the **IsExpanded** mutually exclusive such that when one is expanded, any other expanded section will collapse. Thanks a lot

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0b5591cb-8617-6e0e-c17d-c503fd02ee51
* Version Independent ID: 3295e56b-dbfa-62e2-3f87-dd4b264581a2
* Content: [Xamarin.Forms Expander - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/expander)
* Content Source: [docs/xamarin-forms/user-interface/expander.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/expander.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @microwales 

Thanks for your kind words. However, feature requests should be logged in the [engineering repo](https://github.com/xamarin/Xamarin.Forms/).

With that said, Xamarin.Forms 4.7 (released in June) has a new feature called `MultiBinding`. It enables you to bind a single property to multi-properties on multi-controls. This would enable you to do the scenario you've outlined.
