### ISSUE TITLE
Not clear that Xamarin.Forms builds on Xamarin.iOS/Android

### ISSUE THREAD

**Issue by Eilon** [MicrosoftDocs/xamarin-docs#2878]
Myself, as well as other Internet people, were a bit confused about how Xamarin.Forms apps run on iOS/Android. That is, are Xamarin.Forms apps special in how they run, or do they "follow the rules" of Xamarin.iOS and Xamarin.Android on their respective platforms?

I talked to the Xamarin.Forms team and indeed it "follows the rules" of Xamarin.iOS/Android. Specifically, on iOS the project is compiled to native iOS code and then packaged up for delivery (that is, AOT), and on Android the MSIL is packaged up along with the Mono runtime and packaged up for delivery and then JIT'ted on the device (at least by default).

I suggest adding a sentence or two to the Xamarin.Forms section of this doc to make the connection between Xamarin.Forms and Xamarin.iOS/Android.

cc @PureWeen 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 95f1bfc6-27ee-d6b0-6823-bf44d37ae207
* Version Independent ID: 278e483a-9b38-451c-8b79-5c36da9190fe
* Content: [What is Xamarin? - Xamarin](https://docs.microsoft.com/en-us/xamarin/get-started/what-is-xamarin)
* Content Source: [docs/get-started/what-is-xamarin.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/get-started/what-is-xamarin.md)
* Product: **xamarin**
* Technology: **xamarin-crossplatform**
* GitHub Login: @profexorgeek
* Microsoft Alias: **jusjohns**

**Comment by BretJohnson** [comment]
Separate from this, but in the same doc, I wonder if we should nix the stuff around Mono, just not calling it out by name now.

We're becoming "one .net" for .net 5/6, and emphasizing how we aren't that today, instead are this different but compatible mono thing, but will be in the future, just seems like extra complexity for the user to understand and not really necessary for a conceptual understanding of Xamarin, especially on an intro page. We don't need to convince users to trust mono. Textually it looks like it would work to remove the Mono references, but keep the text that talks about what the execution environment does.

I can submit a PR if desired for that.

**Comment by Eilon** [comment]
Personally I agree about not mentioning Mono (except _maybe_ in some super technical doc). Some people might have some bad taste of Mono from some long-ago experience or some ancient Internet posting that is no longer correct or relevant. Some problems I'm sure do still exist, though (it's not perfect). But it's just .NET as far as a customer is concerned. If there's a problem with .NET on Android, it's a problem for .NET, not specifically Mono.

**Comment by davidbritch** [comment]
I've updated the text (clarified that Xamarin.Forms builds Xamarin.iOS and Xamarin.Android apps, and removed mentions of Mono) in a PR that will go live later today.

**Comment by Eilon** [comment]
Thank you @davidbritch !
