### ISSUE TITLE
C# Equivalent?

### ISSUE THREAD

**Issue by realivanjx** [MicrosoftDocs/xamarin-docs#2879]
Is there any equivalent for the use of `AppThemeColor` and device theme styling with C# markup? Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 268fb9c0-4285-6fa6-2384-3b62a718cdb2
* Version Independent ID: 2d28787a-5161-2d0b-9250-4bbf1faccbad
* Content: [Respond to system theme changes in Xamarin.Forms applications - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/theming/system-theme-changes)
* Content Source: [docs/xamarin-forms/user-interface/theming/system-theme-changes.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/theming/system-theme-changes.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @realivanjx 

`AppThemeColor` is new in Xamarin.Forms 4.6, and so most likely isn't covered by C# markup at this time?

However, I'll let @VincentH-Net chime in for the final authoritative word.

**Comment by VincentH-Net** [comment]
C# Markup does not (yet) have specific support for the experimental [system theme changes](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/theming/system-theme-changes) feature: `AppThemeColor`, `OnAppTheme<T>` and the XAML `OnAppTheme` markup extension.

Since this builds on `DynamicResource`, I will look into this when solving #2880

**Comment by davidbritch** [comment]
I'm going to close this is as issue. I'll get notified when @VincentH-Net adds this functionality to C# markup, and the docs will be updated then.

**Comment by VincentH-Net** [comment]
@realivanjx with the DynamicResource functionality included in the Xamarin Forms [CSharpForMarkup Part 2](https://github.com/xamarin/Xamarin.Forms/pull/11428) PR, would you want additional support in C# Markup?

If so, can you give an example of how you do this in C# today, where you would like to see improvement? 
Suggestions for how are also welcome. Thx!
