### ISSUE TITLE
DynamicResource?

### ISSUE THREAD

**Issue by realivanjx** [MicrosoftDocs/xamarin-docs#2880]
Usually in xaml I can do `BackgroundColor={DynamicResource bg}` and the color will change if I change the `bg` in app resource dictionary. Is there any extension for this in C#?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cc5d52fb-d4a2-7231-d2d4-3990b7634963
* Version Independent ID: 32b38657-d211-5bff-ee70-f9334aeb2053
* Content: [Xamarin.Forms C# markup - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/csharp-markup)
* Content Source: [docs/xamarin-forms/user-interface/csharp-markup.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/csharp-markup.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
@vincenth_net Can you advise?

**Comment by VincentH-Net** [comment]
There will be soon. I received the same request by @brminnick this week.

I intend to submit a PR to the [GitTrends](https://github.com/brminnick/GitTrends) app with an implementation for this as well as other new helpers.

If that is well received I will open a PR in Forms with the new helpers. I will update this issue to

**Comment by realivanjx** [comment]
Probably something like this:

```
public static T DynamicResource<T>(this T view, BindableProperty prop, string styleName) where T : View
        {
            view.SetDynamicResource(prop, styleName);
            return view;
        }
```

**Comment by davidbritch** [comment]
I'm going to close this is as issue. I'll get notified when @VincentH-Net adds this functionality to C# markup, and the docs will be updated then.

**Comment by VincentH-Net** [comment]
FYI @realivanjx @davidbritch DynamicResource functionality is included in the Xamarin Forms [CSharpForMarkup Part 2](https://github.com/xamarin/Xamarin.Forms/pull/11428) PR
