### ISSUE TITLE
Authorize attribute example

### ISSUE THREAD

**Issue by n6ither** [MicrosoftDocs/xamarin-docs#2889]
Could you please provide an AuthorizeAttribute example? Once the authentication is done calling the Web Authenticator in the Xamarin Forms App, what is the proper way to send an http request to the backend server? Should the access token be added as the Authorization Header (Bearer)?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1231a1e1-3734-9021-2cc7-eaf99478afca
* Version Independent ID: 01e5fdbe-0b15-4dbe-f8a0-ed40f8593302
* Content: [Xamarin.Essentials: Web Authenticator - Xamarin](https://docs.microsoft.com/en-us/xamarin/essentials/web-authenticator?tabs=android)
* Content Source: [docs/essentials/web-authenticator.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/essentials/web-authenticator.md)
* Product: **xamarin**
* Technology: **xamarin-essentials**
* GitHub Login: @Redth
* Microsoft Alias: **jodick**

**Comment by jamesmontemagno** [comment]
You should be able to add it as the bearertoken and then setup this on your backend https://stackoverflow.com/questions/25764732/retrieve-bearer-token-in-asp-net-webapi

**Comment by jamesmontemagno** [comment]
@n6ither did this help?

**Comment by n6ither** [comment]
@jamesmontemagno sorry the late response but yes sir, it did the trick. Thank you!
