### ISSUE TITLE
CNLabeledValue is a generic class

### ISSUE THREAD

**Issue by Keboo** [MicrosoftDocs/xamarin-docs#289]
The localized properties example in the [contact formatting and localization](https://docs.microsoft.com/en-us/xamarin/ios/platform/contacts#contact-formatting-and-localization) section does not compile. Specifically:
```C#
CNLabeledValue.LocalizeLabel(CNLabelKey.Home);
```
Fails because CNLabeledValue is a [generic class](https://developer.xamarin.com/api/type/Contacts.CNLabeledValue%3CValueType%3E/)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1cfc1d76-6be2-e0ba-52e2-c975f6fd8c76
* Version Independent ID: 5f942f69-fb51-2043-dd69-67b79a4efdd9
* Content: [Contacts and ContactsUI - Xamarin](https://docs.microsoft.com/en-us/xamarin/ios/platform/contacts#contact-formatting-and-localization)
* Content Source: [docs/ios/platform/contacts.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/ios/platform/contacts.md)
* Service: **unspecified**
* Product: **xamarin**
* GitHub Login: @bradumbaugh
* Microsoft Alias: **brumbaug**

**Comment by bradumbaugh** [comment]
Thank @Keboo - put together a fix for this. Should be published soon. Appreciate the help!
