### ISSUE TITLE
Cannot switch to "Visual Studio" tab

### ISSUE THREAD

**Issue by ondrejsv** [MicrosoftDocs/xamarin-docs#2892]
### Doc issue description

I cannot switch to the "Visual Studio" tab in the "Profiler Basic" section and following sections on the Xamarin Profiler page.
https://docs.microsoft.com/en-us/xamarin/tools/profiler/

![image](https://user-images.githubusercontent.com/747563/83377029-98ca2400-a3d4-11ea-84f9-aaf5b6a2c4d6.png)

There is also one error in the script console which may be related:
```
tabs.ts:130 Uncaught (in promise) TypeError: Cannot set property 'selected' of undefined
    at J_ (tabs.ts:130)
    at tq (tabs.ts:178)
    at index-docs.ts:151
```

**Comment by FrankSzendzielarz** [comment]
Trying to report the same thing. Also the actuall submit feedback button does not work for me.

**Comment by davidbritch** [comment]
I just tried the product switcher and it worked fine for me.
