### ISSUE TITLE
System.GC API reference links are broken

### ISSUE THREAD

**Issue by HankiDesign** [MicrosoftDocs/xamarin-docs#29]
All the links pointing to the Xamarin.com's API reference for System.GC namespace are now broken (404). There are plenty of links throughout the document.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 626dace3-cf0d-1c6e-6320-ca8007a0b97e
* Version Independent ID: b71ec0ef-9178-bfee-b693-dbcaac002879
* Content: [Garbage Collection - Xamarin | Microsoft Docs](https://docs.microsoft.com/en-us/xamarin/android/internals/garbage-collection)
* Content Source: [docs/android/internals/garbage-collection.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/android/internals/garbage-collection.md)
* Service: **unspecified**
* GitHub Login: @mgmclemore
* Microsoft Alias: **mamcle**

**Comment by HankiDesign** [comment]
Would be interesting to know if they can be replaced with ones such as this: [GC.MaxGeneration Property](https://msdn.microsoft.com/en-us/library/system.gc.maxgeneration(v=vs.110).aspx) or if the API reference will be completely migrated to Microsoft Docs in the future.

**Comment by conceptdev** [comment]
> API reference will be completely migrated to Microsoft Docs 

Yes, it will! see docs.microsoft.com/dotnet/api rather than msdn 

Will fix asap.

**Comment by HankiDesign** [comment]
Awesome, I thought that must be the case. Thanks for the link! Now I can fix the links myself in case I stumble on a broken one again.
