### ISSUE TITLE
Still not working with a bare shell app 

### ISSUE THREAD

**Issue by stephenhauck** [MicrosoftDocs/xamarin-docs#2900]
- Visual Studio is the latest on both Mac and Windows 
![image](https://user-images.githubusercontent.com/12648793/83668767-7b48b600-a59e-11ea-877e-7fbc466e73ba.png)

- Xcode is current
- I created a Xamarin Forms Shell app targeting iOS and Android on a Windows machine
- Made the settings changes like you indicated 
- Updated the NuGet packages, none used except the ones that are defaulted with a new Xamarin Forms Shell app
![image](https://user-images.githubusercontent.com/12648793/83668841-9d423880-a59e-11ea-931c-c9b9a3f04478.png)

Here are my iOS build settings
![image](https://user-images.githubusercontent.com/12648793/83668310-b8607880-a59d-11ea-9f79-bc3616438f12.png)

Here is the output
/Library/Frameworks/Xamarin.iOS.framework/Versions/Current/bin/mtouch @/Users/stephenhauck/Library/Caches/Xamarin/mtbs/builds/UIWebKitTest.iOS/1188bde15273392423d3b6bb90f2fefd/obj/iPhone/Release/response-file.rsp --optimize=experimental-xforms-product-type --warn-on-type-ref=UIKit.UIWebView 
3>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(842,3): warning MT1502: One or more reference(s) to type 'UIKit.UIWebView' already exists inside 'Xamarin.Forms.Platform.iOS, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null' before linking
3>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(842,3): warning MT1503: One or more reference(s) to type 'UIKit.UIWebView' still exists inside 'Xamarin.Forms.Platform.iOS, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null' after linking
3>  /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/dsymutil -num-threads 4 -z -o bin/iPhone/Release/UIWebKitTest.iOS.app.dSYM bin/iPhone/Release/UIWebKitTest.iOS.app/UIWebKitTest.iOS 
3>  /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/strip -i -s obj/iPhone/Release/mtouch-symbols.list bin/iPhone/Release/UIWebKitTest.iOS.app/UIWebKitTest.iOS 
3>  /usr/bin/mdimport bin/iPhone/Release/UIWebKitTest.iOS.app/../ 
3>  /usr/bin/codesign --verify -vvvv "-R=anchor apple generic and certificate 1[field.1.2.840.113635.100.6.2.1] exists and (certificate leaf[field.1.2.840.113635.100.6.1.2] exists or certificate leaf[field.1.2.840.113635.100.6.1.4] exists)" bin/iPhone/Release/UIWebKitTest.iOS.app 
========== Rebuild All: 3 succeeded, 0 failed, 0 skipped ==========

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ef31dc71-3610-6c18-2bda-d0bb70804c92
* Version Independent ID: 02f7dc7b-541b-4b82-b33c-4e974fb94d8c
* Content: [Xamarin.Forms WebView - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/webview?tabs=windows#uiwebview-deprecation-and-app-store-rejection-itms-90809)
* Content Source: [docs/xamarin-forms/user-interface/webview.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/webview.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by stephenhauck** [comment]
Anyone ?
Hello .. I can't be the only one with this issue

**Comment by davidbritch** [comment]
Hi @stephenhauck 

Apologies for the delayed response to your issue. Afraid you are the only person who's reported such an issue. All I can do is recommend you take it up with the [engineers](https://github.com/xamarin/Xamarin.Forms/issues).
