### ISSUE TITLE
Wonderful content

### ISSUE THREAD

**Issue by hamqthameem** [MicrosoftDocs/xamarin-docs#2907]
Content was worth reading. Really makes me think twice before implementing any control in xamarin forms inorder to retain the performance which will save that beautiful smile on the user's face.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2553ca72-7627-eb9b-e5f6-51c84fd7c4b9
* Version Independent ID: 50cd62a7-83f5-73f0-409a-57135a5e5704
* Content: [Cross-Platform Performance - Xamarin](https://docs.microsoft.com/en-us/xamarin/cross-platform/deploy-test/memory-perf-best-practices)
* Content Source: [docs/cross-platform/deploy-test/memory-perf-best-practices.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/cross-platform/deploy-test/memory-perf-best-practices.md)
* Product: **xamarin**
* Technology: **xamarin-crossplatform**
* GitHub Login: @davidortinau
* Microsoft Alias: **daortin**

**Comment by davidbritch** [comment]
Hi @hamqthameem 

Thanks for your feedback.
