### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by luis-flores** [MicrosoftDocs/xamarin-docs#291]
XAML
"There is currently no way to dyanmically load XAML" -> "There is currently no way to dynamically load XAML"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2491ac06-9f2a-6129-a64d-2c765dcd5780
* Version Independent ID: 84ee4f5c-85a2-7815-8397-9d8890a37581
* Content: [WPF vs. Xamarin.Forms: Similarities & Differences - Xamarin](https://docs.microsoft.com/en-us/xamarin/cross-platform/desktop/controls/wpf#feedback)
* Content Source: [docs/cross-platform/desktop/controls/wpf.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/cross-platform/desktop/controls/wpf.md)
* Service: **unspecified**
* Product: **xamarin**
* GitHub Login: @asb3993
* Microsoft Alias: **amburns**

**Comment by bradumbaugh** [comment]
Hi @luis-flores, thanks for catching this. Fix should be published soon.
