### ISSUE TITLE
Whole blocks of text show as hyperlink

### ISSUE THREAD

**Issue by jfversluis** [MicrosoftDocs/xamarin-docs#2912]
On this page and https://docs.microsoft.com/en-us/xamarin/ios/deploy-test/linker (maybe more) whole blocks of text are showing hyperlink behavior. I guess some closing tag is forgotten somewhere.

![image](https://user-images.githubusercontent.com/939291/84016402-88d6b500-a97d-11ea-98d0-c486f8fee0ad.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 548b6d92-e589-8adb-029f-c8ffe58325e5
* Version Independent ID: b2418389-a0bb-4616-4e72-d1909a337a98
* Content: [Using mtouch to Bundle Xamarin.iOS Apps - Xamarin](https://docs.microsoft.com/en-us/xamarin/ios/deploy-test/mtouch)
* Content Source: [docs/ios/deploy-test/mtouch.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/ios/deploy-test/mtouch.md)
* Product: **xamarin**
* Technology: **xamarin-ios**
* GitHub Login: @davidortinau
* Microsoft Alias: **daortin**

**Comment by davidbritch** [comment]
Hi @jfversluis 

It's a widespread error throughout the docset, due to an updated version of markdig used by OPS. I'm working on fixing the 284 pages that are affected,

**Comment by jfversluis** [comment]
O no! Sorry to hear that :( good luck! 

You probably have another issue tracking this so close at will

**Comment by samhouts** [comment]
YAAAAAY....just came here to report this. :( :(

**Comment by davidbritch** [comment]
This is now fixed everywhere.
