### ISSUE TITLE
How to update TouchEffect to block TabbedPage gesture when necessary

### ISSUE THREAD

**Issue by alex4998** [MicrosoftDocs/xamarin-docs#2917]
Overall this is a great example of how to use TouchEffect to resize the cropping rectangle. I improved a few things regarding the touch hit point identification. Now, I'm struggling with putting the cropping canvas on a tab of a TabbedPage. The TabbedPage gesture takes priority over the cropping rectangle corner moving. If I move it left to right or right to left the TabbedPage takes control and switched tabs. Can anybody explain to me how to update the TouchEffect to block the TabbedPage gesture but only when the touch happened on a cropping rectangle corner. I though that I might need to set a focus on the cropping view or block the touch event bubbling to the parent or something like that but I have no idea what exactly to do and how to do it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c2103650-966c-ac1f-1422-db102483444e
* Version Independent ID: cf19f39c-5fe6-0fe5-653c-a747579886fa
* Content: [Cropping SkiaSharp bitmaps - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/graphics/skiasharp/bitmaps/cropping)
* Content Source: [docs/xamarin-forms/user-interface/graphics/skiasharp/bitmaps/cropping.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/graphics/skiasharp/bitmaps/cropping.md)
* Product: **xamarin**
* Technology: **xamarin-skiasharp**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @alex4998 

Apologies for the delayed response. Looks like you arrived at a [solution](https://forums.xamarin.com/discussion/182711/how-to-block-tabbedpage-gesture-when-using-android-touch-events) so I'll close this issue.
