### ISSUE TITLE
Issue with the BindableProperty naming

### ISSUE THREAD

**Issue by CommentedSnake3** [MicrosoftDocs/xamarin-docs#2918]
[Enter feedback here]
It should be pointed out that the Bindable Property Object name has to be "name" + Property otherwise the property is not recognised. 

[code]
     // the BindableProperty has to have Property at the end of the object name
    public static readonly BindableProperty TmpProperty = BindableProperty.Create(

      propertyName: "Tmp", // if this is anything else than tmp 
      returnType: typeof(string),
      declaringType: typeof(TmpLayout),
      defaultValue: "0_0_0_0_0");

    public string Tmp
    {
      get { return (string)GetValue(TmpProperty); }
      set { SetValue(TmpProperty, value); }
    }
[/code]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b054a909-6f7f-0b32-5059-eb5c8a9b366b
* Version Independent ID: 723af07b-8f4e-ebe3-a520-99cdcf5efc5a
* Content: [Xamarin.Forms Bindable Properties - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/xaml/bindable-properties)
* Content Source: [docs/xamarin-forms/xaml/bindable-properties.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/xaml/bindable-properties.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @CommentedSnake3 

Apologies for the delayed response to your issue. You've made a good suggestion. Then I discovered that it was already in the doc. So instead of having to add it, I've ensured that it's called out better.
