### ISSUE TITLE
about calenadar

### ISSUE THREAD

**Issue by 9739899885** [MicrosoftDocs/xamarin-docs#292]
hoe to use calendar control in xamarin cross platform

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ee24e2ad-9933-c2db-14db-9ca1197ef30e
* Version Independent ID: df7d653b-418d-5650-a7d8-6254edaec90a
* Content: [XAML Standard (Preview) Controls - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/xaml/standard/controls)
* Content Source: [docs/xamarin-forms/xaml/standard/controls.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/xaml/standard/controls.md)
* Service: **unspecified**
* Product: **xamarin**
* GitHub Login: @charlespetzold
* Microsoft Alias: **chape**

**Comment by charlespetzold** [comment]
The Xamarin.Forms `DatePicker` control is discussed here:

https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/datepicker
