### ISSUE TITLE
sqlite-net-pcl package attributes have changed

### ISSUE THREAD

**Issue by jamgarci-MSFT** [MicrosoftDocs/xamarin-docs#2920]
There is a Note with for the correct sqlite-net-pcl package attributes. This has seemed to change to:

![image](https://user-images.githubusercontent.com/61254901/84406844-b155ed80-abcf-11ea-9112-5d77afa7d7f9.png)

I followed the Project URL on GitHub and then to the Nuget package page. In an older version, it does show the same attributes as described in the Note.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5ce30880-c4f0-78f7-1ee0-6507e378201e
* Version Independent ID: a6ad2818-c0d2-e3ef-1262-e143d49cc348
* Content: [Store data in a local SQLite.NET database - Xamarin](https://docs.microsoft.com/en-us/xamarin/get-started/quickstarts/database)
* Content Source: [docs/get-started/quickstarts/database.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/get-started/quickstarts/database.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @jamgarci-MSFT 

Apologies for the delayed response. I've updated this in a PR that'll go live later today.
