### ISSUE TITLE
Incorrect or missing type in docs (EmbeddedImages)

### ISSUE THREAD

**Issue by Stuart88** [MicrosoftDocs/xamarin-docs#2922]
Example code uses a type called `EmbeddedImages` but that doesn't seem to be a thing in Xamarin Forms.

``` c#
var embeddedImage = new Image {
      Source = ImageSource.FromResource(
        "WorkingWithImages.beach.jpg",
        typeof(EmbeddedImages).GetTypeInfo().Assembly // <--- Here!
      ) };
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7eeb0e65-143b-0f5e-a8fb-c75309689338
* Version Independent ID: 6b984264-a950-4310-483f-99f908b0a8b0
* Content: [Images in Xamarin.Forms - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/images?tabs=windows)
* Content Source: [docs/xamarin-forms/user-interface/images.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/images.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @Stuart88 

Every Xamarin.Forms page has a sample associated with it. If you look at the sample for the images page (download link at the top of the page), you'll see that `EmbeddedImages` is a type in the sample.

**Comment by Stuart88** [comment]
@davidbritch  Ah okay, thanks.

This is the first time I've come across Microsoft online docs that require me to take a close look at the sample download for clarification of something. 

I wonder if it might be worth adding a line or two in the docs to explain what the `EmbeddedImages` class is? It seems to appear out of nowhere when reading through that page. 

Or perhaps use the more general `MyClass` (which I've now seen appears later)?

**Comment by davidbritch** [comment]
Hi @Stuart88 

Apologies for the delayed response. I've updated the doc to use `MyClass`, in a PR that's making its way through the CI system now.
