### ISSUE TITLE
Support for Camera

### ISSUE THREAD

**Issue by BenHayat** [MicrosoftDocs/xamarin-docs#293]
Please add support for camera in this API.
Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 78e6dee8-1182-bf1e-fd3a-e8d1aecc094a
* Version Independent ID: 81202c69-317a-f0fa-7324-5316f7c1ceb7
* Content: [Xamarin.Essentials - Xamarin](https://docs.microsoft.com/en-us/xamarin/essentials/get-started?tabs=windows%2Candroid)
* Content Source: [docs/essentials/get-started.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/essentials/get-started.md)
* Service: **unspecified**
* Product: **xamarin**
* GitHub Login: @jamesmontemagno
* Microsoft Alias: **jamont**

**Comment by bradumbaugh** [comment]
Hi @BenHayat, this repository is only intended for documentation-specific feedback. Please file other requests here: https://github.com/xamarin/Essentials/issues.

Thanks!
