### ISSUE TITLE
Typographic mistakes

### ISSUE THREAD

**Issue by GT85** [MicrosoftDocs/xamarin-docs#2932]
[Enter feedback here]
1) pararmName -> paramName
2) x.CanDragRows -> v.CanDragRows (because v is used in the Obj-C example)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 032e4a0c-972d-f739-b20c-6690fa08ec5a
* Version Independent ID: 33b9834c-6c37-fe81-9136-4b0fc17a6e80
* Content: [macOS APIs for Xamarin.Mac Developers - Xamarin](https://docs.microsoft.com/en-us/xamarin/mac/app-fundamentals/mac-apis)
* Content Source: [docs/mac/app-fundamentals/mac-apis.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/mac/app-fundamentals/mac-apis.md)
* Product: **xamarin**
* Technology: **xamarin-mac**
* GitHub Login: @davidortinau
* Microsoft Alias: **daortin**

**Comment by profexorgeek** [comment]
These changes have been made, thanks for pointing this out!
