### ISSUE TITLE
Html bug into section 'Fonts in Xamarin.Forms'

### ISSUE THREAD

**Issue by gewarren** [MicrosoftDocs/xamarin-docs#2934]
---
**Issue moved from MicrosoftDocs/feedback#2816**
- Please respond to @Nihilem.

---

_From @Nihilem on Wednesday, June 3, 2020 11:47:18 AM_

All of the page is clickable, there are some problems with <a> tags in  headlines text. 

to Reproduce
Steps to reproduce the behaviour:
Go to  [https://docs.microsoft.com/it-it/xamarin/xamarin-forms/user-interface/text/fonts](url)

Desktop (please complete the following information):
OS: Windows 10
Browser Chrome
Version 83.0.4103.61

**Comment by gewarren** [comment]
---
**Issue moved from MicrosoftDocs/feedback#2816**
- Please respond to @welcome[bot].

---

_From @welcome[bot] on Wednesday, June 3, 2020 11:47:20 AM_

Thank you for creating the issue! One of our team members will get back to you shortly with additional information. If this is a product issue, please close this and contact the particular product's support instead (see https://support.microsoft.com/allproducts for the list of support websites).

**Comment by davidbritch** [comment]
Hi @Nihilem 

Thanks for opening the issue. I fixed it early last week, so if you look at https://docs.microsoft.com/it-it/xamarin/xamarin-forms/user-interface/text/fonts you'll see that the page now renders correctly.
