### ISSUE TITLE
the URL for ShapeDemos (sample) is broken

### ISSUE THREAD

**Issue by bondarenkod** [MicrosoftDocs/xamarin-docs#2935]
The URL for '**_ShapeDemos (sample)_**' is broken
the URL is: https://docs.microsoft.com/en-us/samples/xamarin/xamarin-forms-samples/userinterface-shapedemos/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 707a95ac-6e19-9c93-dd6c-7f15e2d8a302
* Version Independent ID: 6f81ca5b-fa3c-820d-20ee-e21a242994e6
* Content: [Xamarin.Forms Shapes - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/shapes/)
* Content Source: [docs/xamarin-forms/user-interface/shapes/index.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/shapes/index.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @bondarenkod 

Yes. Not so much broken, more that I'm still waiting for the sample CI to put the sample there.

**Comment by davidbritch** [comment]
I'd love to tell you that this is fixed. But it's not. There's nothing I can do about it until the relevant team coax the sample ingestion service back into life. In the meantime, you can grab the sample from https://github.com/xamarin/xamarin-forms-samples/tree/master/UserInterface/ShapesDemos

**Comment by davidbritch** [comment]
I've temporarily updated the link to point to GitHub, to stop the 404.

**Comment by davidbritch** [comment]
This is now fixed, with the link pointing to the samples browser.
