### ISSUE TITLE
Not sure I understand this.

### ISSUE THREAD

**Issue by joanneraye** [MicrosoftDocs/xamarin-docs#2941]
In your explanation you said the following:
Return a Task object, instead of returning an awaited Task object, when there's no need to process the result of an asynchronous operation. This is more performant due to less context switching being performed.
I would like an example of this as I am not sure what is meant by this.  Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4a6c9a34-df78-94ca-5e6d-701c743eb658
* Version Independent ID: 4c81800f-dc7f-aa92-55c0-d5a90ed8c3c2
* Content: [Improve Xamarin.Forms App Performance - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/deploy-test/performance)
* Content Source: [docs/xamarin-forms/deploy-test/performance.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/deploy-test/performance.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @joanneraye 

Hopefully these videos will help:

https://channel9.msdn.com/Shows/XamarinShow/Best-Practices-Async--Await--The-Xamarin-Show

https://channel9.msdn.com/Shows/XamarinShow/Best-Practices-Advanced-Async--Await--The-Xamarin-Show
