### ISSUE TITLE
Azure Functions steps are outdated

### ISSUE THREAD

**Issue by sinositato** [MicrosoftDocs/xamarin-docs#2946]
The configuration steps for Azure Functions are outdated as of today (06/24/20). 
e.g. Azure Portal screenshots are no longer accurate, missing steps to add/update "AzureSignalRConnectionString" on the Azure Function appSettings, etc.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 99698458-a6cb-0874-bdda-5a3fcb0988b3
* Version Independent ID: 970e5418-c85e-7b4e-adf1-a5ebc411bebc
* Content: [Azure SignalR Service with Xamarin.Forms - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/data-cloud/azure-services/azure-signalr)
* Content Source: [docs/xamarin-forms/data-cloud/azure-services/azure-signalr.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/data-cloud/azure-services/azure-signalr.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @profexorgeek
* Microsoft Alias: **jusjohns**

**Comment by davidbritch** [comment]
Hi @sinositato 

Apologies for the delayed response to your issue. Keeping docs up to date as different Azure services change is next to impossible, so I've deleted this doc and redirected to content in the SignalR docset. This is in a PR that will go live today or tomorrow.
