### ISSUE TITLE
Ability to control button order in DisplayAlert?

### ISSUE THREAD

**Issue by anders9ustafsson** [MicrosoftDocs/xamarin-docs#2947]
In the `DisplayAlert` example with a **Yes** and **No** button, the buttons are non-intuitively displayed, in order from left to right, **No** and **Yes**. Is there a way to reverse the order of these buttons in this specific case? If there is, it would be valuable if this could be applied in the code example.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3c6e0bb1-26e4-091b-8a99-27d772bed7f6
* Version Independent ID: 57d8ad92-0aa2-9ec4-47bc-8853d9a71d91
* Content: [Display Pop-ups - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/pop-ups)
* Content Source: [docs/xamarin-forms/user-interface/pop-ups.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/pop-ups.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @anders9ustafsson 

Apologies for the delayed response to your issue. Afraid there's no way to change the button order from within Xamarin.Forms. However, it can be done by writing your own Xamarin.iOS code to display an alert. See https://docs.microsoft.com/xamarin/ios/user-interface/controls/alerts for more info.
