### ISSUE TITLE
Is Embeddinator-4000 still in development/supported?

### ISSUE THREAD

**Issue by mikeberlin** [MicrosoftDocs/xamarin-docs#2948]
Is this still supported/maintained?

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d938bf09-a3d3-8dc1-556a-3a368197900a
* Version Independent ID: a0ff8ab3-99ba-6ea1-f684-825c6a0fc522
* Content: [.NET Embedding - Xamarin](https://docs.microsoft.com/en-us/xamarin/tools/dotnet-embedding/)
* Content Source: [docs/tools/dotnet-embedding/index.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/tools/dotnet-embedding/index.md)
* Product: **xamarin**
* Technology: **xamarin-crossplatform**
* GitHub Login: @davidortinau
* Microsoft Alias: **daortin**

**Comment by davidbritch** [comment]
Afraid not. It never made it out from being a preview to a stable release. Because it's no longer under active development, I've removed the docs.
