### ISSUE TITLE
Incorrect claims

### ISSUE THREAD

**Issue by randomroxks** [MicrosoftDocs/xamarin-docs#2949]
The page says that PDF can be displayed natively on iOS and ANdroid. 
I have tried this claim, but I can say that it only works for iOS and not for Android. 
Either, please fix the claim or provide a way to display PDF on ANdroid that does not involve using PDFJS, Google PDF Viewer. 
This is highly misleading....

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ef31dc71-3610-6c18-2bda-d0bb70804c92
* Version Independent ID: 02f7dc7b-541b-4b82-b33c-4e974fb94d8c
* Content: [Xamarin.Forms WebView - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/webview?tabs=windows#related-links)
* Content Source: [docs/xamarin-forms/user-interface/webview.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/webview.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @randomroxks 

Apologies for the delayed response to your issue. I've updated the doc, in a PR that will go live by the end of the week.
