### ISSUE TITLE
Open Folder vs Open Distribution

### ISSUE THREAD

**Issue by csutorasbalazs** [MicrosoftDocs/xamarin-docs#295]
"After the signing process completes, click Open Folder" should not be Open Distribution?
Open Folder opens archive folder-

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d22ceddd-69d4-3a5d-2947-a5abddbbd3aa
* Version Independent ID: e238051f-b809-5541-4049-f1205dd0a3a5
* Content: [Signing the Android Application Package - Xamarin](https://docs.microsoft.com/en-gb/xamarin/android/deploy-test/signing/?tabs=vswin)
* Content Source: [docs/android/deploy-test/signing/index.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/android/deploy-test/signing/index.md)
* Service: **unspecified**
* Product: **xamarin**
* GitHub Login: @mgmclemore
* Microsoft Alias: **mamcle**

**Comment by mgmclemore** [comment]
Hi @csutorasbalazs, yes, you are correct: the instruction should be to click Open Distribution rather than Open Folder. I've added this doc to our internal backlog for correction and review. Thank you for the help!
