### ISSUE TITLE
Unable to use RadioButton Control with ListView in Xamarin Forms

### ISSUE THREAD

**Issue by nketu1994** [MicrosoftDocs/xamarin-docs#2950]
Added Experimental Flag in MainActivity.cs before Forms. Init for RadioButton but still getting runtime exception: System.InvalidOperationException: The class, property, or method you are attempting to use ('RadioButton') is part of RadioButton; to use it, you must opt-in by calling Forms.SetFlags("RadioButton_Experimental") before calling Forms.Init().

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a688fe91-33ad-efea-aa29-d56b3c11b42a
* Version Independent ID: c0e81ed5-0eb5-a8cc-9eb6-7baf7e464878
* Content: [Xamarin.Forms RadioButton - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/radiobutton)
* Content Source: [docs/xamarin-forms/user-interface/radiobutton.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/radiobutton.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @nketu1994 

Are you calling `Forms.SetFlags` more than once (with different flags), or from more than one place (e.g. `MainActivity` and `App.xaml.cs`)?
