### ISSUE TITLE
It seems that for iOS, supported languages must be specified in Info.plist in the "Localizations" section.

### ISSUE THREAD

**Issue by arrayofletters** [MicrosoftDocs/xamarin-docs#2953]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: af66394d-81c5-0c2e-1682-a2bb7eeb3c3e
* Version Independent ID: 27542a45-2f25-4042-cf48-b9517025635c
* Content: [String and Image Localization in Xamarin.Forms - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/localization/text?pivots=windows)
* Content Source: [docs/xamarin-forms/app-fundamentals/localization/text.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/app-fundamentals/localization/text.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @profexorgeek
* Microsoft Alias: **jusjohns**

**Comment by davidbritch** [comment]
Hi @arrayofletters 

Apologies for the delayed response to your issue. It looks like the section on editing Info.plist was removed when the doc last refreshed. I've re-inserted it, in a PR that will go live tomorrow.
