### ISSUE TITLE
No longer experimental

### ISSUE THREAD

**Issue by Qythyx** [MicrosoftDocs/xamarin-docs#2954]
I believe CarouselView is no longer experimental. That portion of this doc should be updated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 54157d0c-4fc2-111b-78fa-01783ad02d6d
* Version Independent ID: f18a970e-b733-a7ac-e558-bd7277dcfd03
* Content: [Xamarin.Forms CarouselView Introduction - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/carouselview/introduction)
* Content Source: [docs/xamarin-forms/user-interface/carouselview/introduction.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/carouselview/introduction.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @Qythyx 

Afraid that `CarouselView` is still experimental in Xamarin.Forms 4.7. It's scheduled to move to GA in 4.8.

It's `IndicatorView` that's no longer experimental in 4.7.
