### ISSUE TITLE
what is type of 'this' in  "this.PresentViewController" in the source code sample

### ISSUE THREAD

**Issue by yyou** [MicrosoftDocs/xamarin-docs#2957]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 704a0841-9815-7e6a-60f9-b2034dc96571
* Version Independent ID: 8c41841a-09d7-c86f-0ca7-6145283cdd5f
* Content: [Displaying Alerts in Xamarin.iOS - Xamarin](https://docs.microsoft.com/en-us/xamarin/ios/user-interface/controls/alerts)
* Content Source: [docs/ios/user-interface/controls/alerts.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/ios/user-interface/controls/alerts.md)
* Product: **xamarin**
* Technology: **xamarin-ios**
* GitHub Login: @davidortinau
* Microsoft Alias: **daortin**

**Comment by PureWeen** [comment]
`UIViewController`
