### ISSUE TITLE
CarouselView in UWP?

### ISSUE THREAD

**Issue by plettb** [MicrosoftDocs/xamarin-docs#2958]
Has anyone managed to get the CarouselView working properly in UWP?  Is the reason there are no UWP samples because it doesn't work?

When I use it in its default configuration, I see only the first item, with a long vertical scrollbar on the right that can't be scrolled.  Is this a known problem?

Any help would be much appreciated!  Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e8ab1874-7545-33e1-e2a4-94b98c98cac0
* Version Independent ID: 560bcbd1-e6f3-0cf5-f357-97e9e9e00130
* Content: [Xamarin.Forms CarouselView - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/carouselview/)
* Content Source: [docs/xamarin-forms/user-interface/carouselview/index.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/carouselview/index.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @plettb 

Afraid that UWP support for `CarouselView` is only slowly progressing. At the moment, support is as you've described above.
