### ISSUE TITLE
OnPlatform examples are outdated 

### ISSUE THREAD

**Issue by anpin** [MicrosoftDocs/xamarin-docs#2960]
[Enter feedback here]

OnPlatform examples are outdated 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e80791df-0605-587f-74cd-ebc4c9fd0f74
* Version Independent ID: 76736d2a-f450-4607-55b9-e7f547c0c775
* Content: [Part 2. Essential XAML Syntax - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/xaml/xaml-basics/essential-xaml-syntax)
* Content Source: [docs/xamarin-forms/xaml/xaml-basics/essential-xaml-syntax.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/xaml/xaml-basics/essential-xaml-syntax.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @anpin 

Outdated how? They look fine to me.

Sure, they aren't using the `OnPlatform` markup extension (which uses a less verbose syntax), but that's because markup extensions are only introduced in the next doc in the XAML basics series.

**Comment by anpin** [comment]
I think it was my misunderstanding of XAML syntax as it just wasn't working and I assumed documentation was wrong. Sorry for bothering!
