### ISSUE TITLE
UWP docmentation is missing

### ISSUE THREAD

**Issue by chrisgull** [MicrosoftDocs/xamarin-docs#2962]
UWP documentation is missing on this page. Please add soon.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b6242cd2-d96b-273b-d3c6-089cb170ba8d
* Version Independent ID: 5c1a70be-0d94-bed3-ff9a-d46def91cfb3
* Content: [Xamarin.Forms Shell Custom Renderers - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/shell/customrenderers)
* Content Source: [docs/xamarin-forms/app-fundamentals/shell/customrenderers.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/app-fundamentals/shell/customrenderers.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @chrisgull 

Thanks for pointing this out. At the moment UWP support is still very much a work in progress. However, I've added some UWP renderer details in a PR that will go live later.
