### ISSUE TITLE
SearchBar style on iOS not found

### ISSUE THREAD

**Issue by prkhandelwal** [MicrosoftDocs/xamarin-docs#2963]
[Enter feedback here]
I'm on Xamarin Forms version 4.7.0.1080. The property `ios:SearchBar.SearchBarStyle="Minimal"` is not found

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 526c8b86-955e-1a06-5667-aee569e573cc
* Version Independent ID: 931074ef-dec8-7fdc-ec38-ff2f6414db72
* Content: [SearchBar Style on iOS - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/platform/ios/searchbar-style)
* Content Source: [docs/xamarin-forms/platform/ios/searchbar-style.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/platform/ios/searchbar-style.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @prkhandelwal 

Try the sample the page links to, and you'll see that the SearchBar style platform-specific does work (I also updated the sample, locally, to 4.7.0.1080 and the platform-specific still worked correctly).

**Comment by prkhandelwal** [comment]
@davidbritch Am I missing something here? I have included:

`xmlns:ios="clr-namespace:Xamarin.Forms.PlatformConfiguration.iOSSpecific;assembly=Xamarin.Forms.Core"`

And I'm on most recent Xamarin.Forms version.

![image](https://user-images.githubusercontent.com/12965931/87223617-1a31b080-c39c-11ea-8dd3-8024519c9e6d.png)
