### ISSUE TITLE
misspelling

### ISSUE THREAD

**Issue by emceelovin** [MicrosoftDocs/xamarin-docs#2964]
[Enter feedback here]

Unix-Like Kernal should be Kernel. Not Kernal.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 95f1bfc6-27ee-d6b0-6823-bf44d37ae207
* Version Independent ID: 278e483a-9b38-451c-8b79-5c36da9190fe
* Content: [What is Xamarin? - Xamarin](https://docs.microsoft.com/en-us/xamarin/get-started/what-is-xamarin)
* Content Source: [docs/get-started/what-is-xamarin.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/get-started/what-is-xamarin.md)
* Product: **xamarin**
* Technology: **xamarin-crossplatform**
* GitHub Login: @profexorgeek
* Microsoft Alias: **jusjohns**

**Comment by davidbritch** [comment]
Hi @emceelovin 

I just searched this doc for "kernal" and there aren't any hits. There aren't any hits for "kernel" either. The diagram in the doc has the correct spelling.
