### ISSUE TITLE
UWP limitations?

### ISSUE THREAD

**Issue by chrisgull** [MicrosoftDocs/xamarin-docs#2968]
It would be really helpful to know at least something about the limitations WRT Shell support for UWP. 
I'm getting core functionality working, but it feels like walking a mine field - there is now way for me to know what will and will not work (but what does work looks great).
Thanks,
Lars

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 09e0923c-3c3a-4e9b-bb30-b2d3fff2c34e
* Version Independent ID: 1a13d34a-8416-8e29-c65d-2c6d41c72b40
* Content: [Xamarin.Forms Shell Introduction - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/shell/introduction)
* Content Source: [docs/xamarin-forms/app-fundamentals/shell/introduction.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/app-fundamentals/shell/introduction.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @chrisgull 

Apologies for the delayed response to your issue. Agreed that there should be a link to a status page for Shell support in UWP. I'm looking into it.

**Comment by davidbritch** [comment]
The best source I've been able to find so far is the Shell project board: https://github.com/xamarin/Xamarin.Forms/projects/54

It has a column that shows UWP blockers. It's not ideal though.

**Comment by davidbritch** [comment]
I've added a link from the doc to the UWP Shell project board. The PR will go live tomorrow.
