### ISSUE TITLE
SetPriority is deprecated

### ISSUE THREAD

**Issue by Architekt909** [MicrosoftDocs/xamarin-docs#297]
The SetPriority method is marked as deprecated. What's the appropriate one to use now? The Google docs say to use SetImportance but I don't see this method when using the notification builder (source: https://developer.android.com/reference/android/app/Notification.Builder#setPriority(int) )

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 78e442e3-b387-f538-5430-e4538cf60cb9
* Version Independent ID: 44dc930e-09e2-56e8-e693-18a69af0a747
* Content: [Local Notifications - Xamarin](https://docs.microsoft.com/en-us/xamarin/android/app-fundamentals/notifications/local-notifications)
* Content Source: [docs/android/app-fundamentals/notifications/local-notifications.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/android/app-fundamentals/notifications/local-notifications.md)
* Service: **unspecified**
* Product: **xamarin**
* GitHub Login: @mgmclemore
* Microsoft Alias: **mamcle**

**Comment by mgmclemore** [comment]
Hi @Architekt909, Google is deprecating the older way of creating notifications in favor of using [Notification Channels](https://docs.microsoft.com/en-us/xamarin/android/app-fundamentals/notifications/local-notifications#notification-channels) (explained later in the topic). This topic needs to be updated to remove the out-of-date content -- I've added it to our internal backlog for updating. Thank you for the feedback!
