### ISSUE TITLE
Missing documentation about lack of asset catalog

### ISSUE THREAD

**Issue by Inrego** [MicrosoftDocs/xamarin-docs#2972]
With Xamarin Hot Reload, iOS Asset Catalog is not supported. It should be listed under the `Limitations` section on the hot restart documentation page. Since this limitation is not documented, there are a lot of tickets created about this as a bug.
Just to list a few:

https://developercommunity.visualstudio.com/content/problem/1028032/xamarin-hot-restart-uiimagefrombundle-not-working.html
https://developercommunity.visualstudio.com/content/problem/1010619/using-xamarin-hot-restart-to-debug-on-ios-phone-do.html
https://developercommunity.visualstudio.com/content/problem/1105211/ios-shows-default-icon-instead-of-my-icon-set.html
https://developercommunity.visualstudio.com/content/problem/1007133/xamarin-ios-application-icon-not-set.html

Maybe also add, that a side effect of this limitation means that the splash screen and app icon will always be the default Xamarin ones, and not any custom app icon/splash screen the developer might have added to their project.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8f3eb808-8e6d-4e07-fc75-8d79a7249265
* Version Independent ID: dbb2b9a9-87a6-e473-50e6-f88435d49e88
* Content: [Xamarin Hot Restart - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/deploy-test/hot-restart)
* Content Source: [docs/xamarin-forms/deploy-test/hot-restart.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/deploy-test/hot-restart.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @maddyleger1
* Microsoft Alias: **maleger**

**Comment by davidbritch** [comment]
This has been dealt with by the linked PR.
