### ISSUE TITLE
How to measure the impact of data binding on overall app performance?

### ISSUE THREAD

**Issue by dk-jlew** [MicrosoftDocs/xamarin-docs#2976]
Good info about the % speedups here, thank you!  I'm wondering if there's any guidance on how to measure the amount of time which is currently being spent in my XF app on data binding.  I assume it would be represented somehow in a profiling session, but would appreciate info on what to look for specifically.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f6dded20-b246-945c-63ce-0e349afac9a2
* Version Independent ID: 1e24cfb3-a124-e001-5eb5-9410834bf3a1
* Content: [Xamarin.Forms Compiled Bindings - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/data-binding/compiled-bindings?WT.mc_id=compiledbindings-xamarinblog-jamont)
* Content Source: [docs/xamarin-forms/app-fundamentals/data-binding/compiled-bindings.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/app-fundamentals/data-binding/compiled-bindings.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @dk-jlew 

Apologies for the delayed response. Afraid it won't be represented in a profiling session. The [Xamarin.Forms profiler](https://github.com/xamarin/Xamarin.Forms/wiki/Xamarin.Forms-Profiling) is code based, and doesn't yet have the ability to measure how long data binding takes. However, you would be able to profile two versions of the same page - one with classic bindings, one with compiled bindings.

Hope this helps!
