### ISSUE TITLE
Outdated documentation: Tip for Android TabbedPage

### ISSUE THREAD

**Issue by aaRopi** [MicrosoftDocs/xamarin-docs#2978]
The tip for Android TabbedPage is out of date. The method `GetIconDrawable` is marked obsolete and not available. And the new method `SetIcon..` does not exist.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0c81c589-e81e-d98c-9656-695a3520a12d
* Version Independent ID: c235f6f9-47ce-15f3-b4da-cb12e219df92
* Content: [Xamarin.Forms TabbedPage - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/navigation/tabbed-page)
* Content Source: [docs/xamarin-forms/app-fundamentals/navigation/tabbed-page.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/app-fundamentals/navigation/tabbed-page.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
HI @aaRopi 

Thanks for pointing this out. I've updated the doc in a PR that will go live later.
