### ISSUE TITLE
Color.Default works on UWP but on Android does nothing

### ISSUE THREAD

**Issue by Realgigabyte** [MicrosoftDocs/xamarin-docs#2979]
Color.Default works on UWP but on Android does nothing

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7371ff34-ba0d-2083-52f5-c09f8e581574
* Version Independent ID: e73786ec-34d4-3bb8-f6d5-7eba5c6ad905
* Content: [Colors in Xamarin.Forms - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/colors)
* Content Source: [docs/xamarin-forms/user-interface/colors.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/colors.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @Realgigabyte 

If you believe this is a bug, you should log it in the [engineering repo](https://github.com/xamarin/Xamarin.Forms/).
