### ISSUE TITLE
Version

### ISSUE THREAD

**Issue by jprsatx** [MicrosoftDocs/xamarin-docs#298]
It would be helpful if the Visual Studio version were included in the video -- if it was, I could not tell. I am using 2017 and some aspects of the video do not correlate. Even better would be to provide a link for Building Your First Android App with Xamarin for Visual Studio 2017

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b6f520a2-9747-abe6-5bfb-d327a86130d6
* Version Independent ID: c8c064cb-4b2d-1270-c909-d6e8ae5cfbec
* Content: [Start Developing Android Apps with Xamarin.Android - Xamarin](https://docs.microsoft.com/en-us/xamarin/android/get-started/index)
* Content Source: [docs/android/get-started/index.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/android/get-started/index.md)
* Service: **unspecified**
* Product: **xamarin**
* GitHub Login: @mgmclemore
* Microsoft Alias: **mamcle**

**Comment by mgmclemore** [comment]
Hi @jprsatx, I've contacted the author of the video and passed on your comments. The video was made with an earlier version of Visual Studio 2017 that used different templates -- she is looking into refreshing the video using the latest templates. Thanks for the feedback!
