### ISSUE TITLE
Please expand on how to use SVG images as icons on a TabbedPage?

### ISSUE THREAD

**Issue by DallinJackson** [MicrosoftDocs/xamarin-docs#2987]
See my StackOverflow post [here](https://stackoverflow.com/questions/62963573/xamarin-forms-use-svg-images-as-icons-on-a-tabbedpage). Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0c81c589-e81e-d98c-9656-695a3520a12d
* Version Independent ID: c235f6f9-47ce-15f3-b4da-cb12e219df92
* Content: [Xamarin.Forms TabbedPage - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/navigation/tabbed-page)
* Content Source: [docs/xamarin-forms/app-fundamentals/navigation/tabbed-page.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/app-fundamentals/navigation/tabbed-page.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @DallinJackson 

I've updated the doc with a link to a sample that demos how to do this. It'll probably be next week before the update goes live, as the samples CI is currently misbehaving. In the meantime, I've written a blog post on how to do this: https://www.davidbritch.com/2020/11/display-svgs-as-tabbedpage-tab-icons-in.html
