### ISSUE TITLE
Can this DeviceInfo detected Emulator?

### ISSUE THREAD

**Issue by nguyenthanhliemfc** [MicrosoftDocs/xamarin-docs#299]
If I run on emulator, DeviceInfo API can detected is running on emulator?
Thank!

---
#### Chi tiết tài liệu

⚠ *Không chỉnh sửa phần này. Điều này là bắt buộc cho docs.microsoft.com ➟ Vấn đề khi liên kết GitHub.*

* ID: c918dea8-217e-8886-73ad-c1dcb9cc1e1e
* Version Independent ID: 238f8427-325c-dc77-caaf-1f3a8e44df88
* Content: [Xamarin.Essentials Device Information - Xamarin](https://docs.microsoft.com/vi-vn/xamarin/essentials/device-information?context=xamarin/xamarin-forms)
* Content Source: [docs/essentials/device-information.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/essentials/device-information.md)
* Service: **unspecified**
* Product: **xamarin**
* GitHub Login: @jamesmontemagno
* Microsoft Alias: **jamont**

**Comment by KamiOfDeath** [comment]
```c#
// Device Type (Physical)
var deviceType = DeviceInfo.DeviceType;
```

**Comment by conceptdev** [comment]
No, only the [list of idioms provided](https://docs.microsoft.com/vi-vn/xamarin/essentials/device-information?context=xamarin/xamarin-forms#idioms).
