### ISSUE TITLE
Really Need To Upskill Xamarin API Descriptor Pages

### ISSUE THREAD

**Issue by BOSnooneTON** [MicrosoftDocs/xamarin-docs#2991]
The described capability does not, in fact, work equally well on UWP and Android target runtimes, notwithstanding the example code pointed to by the documentation page.

It would be most helpful if Xamarin adopted the Microsoft approach to documentation which everywhere and always includes a reference to the minimum version in which an API, method, parameter, whatever is available.  At least then, programmers such as this one would not waste time expecting that Xamarin Forms code might work, only to learn through trial and error that we need to code around UWP's less than equal status.

Oh and "No" a) not a noob, b) running on build 4.7.0.1080, and c) been down this road too many times before to expect that submitting a trouble ticket will be a positive experience in anything approaching 2 elapsed years.

Especially as Visual Studio now (16.6.5) supports Xcode, might be time to tighten things up there in Xamarin Forms-land
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3c6e0bb1-26e4-091b-8a99-27d772bed7f6
* Version Independent ID: 57d8ad92-0aa2-9ec4-47bc-8853d9a71d91
* Content: [Display Pop-ups - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/pop-ups)
* Content Source: [docs/xamarin-forms/user-interface/pop-ups.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/pop-ups.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by BOSnooneTON** [comment]
Okay, I was a bit "unspecific", so here, allow me to beat you up as the front man for incompetence:
In a Page's overridden OnAppearing:
                Application.Current.MainPage.DisplayAlert("Get Added ..", "Sup?", "OK");
works on Android and doesn't work on UWP
                Application.Current.MainPage.DisplayActionSheet(null, "Continue", null, new string[] { "01234567890ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz" });
works on Android by wrapping the line and expanding the text box as required.  While unlike the DisplayAlert, the call does work on UWP, the text line is truncated at the "..ST.." boundary despite the fact that there is a [GitHub xamarin/Xamarin.Forms WFP bug submission from 2018 (Issue 3634)](https://github.com/xamarin/Xamarin.Forms/issues/3634) that speaks to that very shortcoming.

Seriously, this ain't Windows 3.1 anymore ..

**Comment by BOSnooneTON** [comment]
Addm:  Oh and if one were to follow your colleague [Jack Hua's advice](https://stackoverflow.com/questions/62431815/xamarin-forms-page-displayalert-in-page-onappearing), instead of coding
       Application.Current.MainPage.DisplayAlert("Get Added ..", "Sup?", "OK");
one simply coded
       DisplayAlert("Get Added ..", "Sup?", "OK");
that doesn't work on UWP and it does work on Android

**Comment by BOSnooneTON** [comment]
Do all y'all really need such a diatribe to go on, or can y'all figure out that it is long past time to increase investment in a more competent approach to product management and automated regression testing as gating functions on each and every release of software product and documentation?

**Comment by davidbritch** [comment]
Thanks for your feedback.

**Comment by BOSnooneTON** [comment]
@David:  Thanks for the considered attention to the suggestion and, in advance, for carrying it forward if unable to single-handedly implement it today.  

And, [here too ](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/expander)is another instance: Is the experimental implementation of Expander intended to function on UWP?  Documentation does not discern Device.Runtimes in the written word, but the [Sample Code](https://github.com/xamarin/xamarin-forms-samples/tree/master/UserInterface/ExpanderDemos) doesn't have a UWP project ...
