### ISSUE TITLE
How can we use output files of Embeddinator?

### ISSUE THREAD

**Issue by MajidGhosian** [MicrosoftDocs/xamarin-docs#2992]
I'm working on my PhD thesis and I need to convert some .Net libraries to C.
I'm trying to use Embeddinator-4000. I followed below document:
https://docs.microsoft.com/en-us/xamarin/tools/dotnet-embedding/get-started/c

I need a detailed explanation of the contents of the generated files. I do not know which function to call for initialization. I don't even know if I need an initialization or not. 
There are some functions that I guess these are my converted functions but they have extra input arguments and I don't know what are those?
The lack of a complete document to explain the contents of the output files is strongly felt.

**Comment by davidbritch** [comment]
Thanks for submitting an issue and we apologize for the delayed response. Unfortunately this tool has been deprecated (it never made it out of preview), and the docs removed. Therefore, I'm closing this issue.
