### ISSUE TITLE
Permissions.RequestAsync<> deadly hang in case when app runs 1st time and there was OS UI displayed

### ISSUE THREAD

**Issue by dmitrybond173** [MicrosoftDocs/xamarin-docs#2993]
[Enter feedback here]
Permissions.RequestAsync<> deadly hang in case when app runs 1st time and there was OS UI displayed to confirm permissions.
So, user clicked [Allow] but application never receive control back from Permissions.RequestAsync<> method call!
Only the solution is to kill app and start it again, then it works because permissions were already granted and there is no call to OS API.

Note: VS 2019 (16.6.5); Xamarin.Forms 4.7.0.1142; Xamarin.Essentials 1.5.3.2 - so, it seems all the latest.

Just for a ref to code sample = https://stackoverflow.com/questions/63039122/xamarin-why-it-hangs-on-permissions-enabling/63045558

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ebd6725e-e917-c705-a885-40c560005e9d
* Version Independent ID: 939979f6-4d84-26a7-d2b7-69e7593a4433
* Content: [Permissions.RequestAsync&lt;TPermission&gt; Method (Xamarin.Essentials)](https://docs.microsoft.com/en-us/dotnet/api/xamarin.essentials.permissions.requestasync?view=xamarin-essentials)
* Content Source: [docs/en/Xamarin.Essentials/Permissions.xml](https://github.com/xamarin/Essentials/blob/live/docs/en/Xamarin.Essentials/Permissions.xml)
* Product: **xamarin**
* Technology: **xamarin-essentials**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by jamesmontemagno** [comment]
It is not recommended that you do this in your OnStart. Your UI must be present and the Activity on Android must also be started and visible to display the UI. You can move this logic into the MainPage of your application in OnAppearing. 

Call .Result will cause locks of your app and you should implement async/await  https://devblogs.microsoft.com/xamarin/getting-started-with-async-await/
