### ISSUE TITLE
Wrong place of 'initialized = true' line of code

### ISSUE THREAD

**Issue by Denn1Ro** [MicrosoftDocs/xamarin-docs#2996]
I think the line of code 'initialized = true' have to go outside of the scope of the if statement where currently is. 

`async Task InitializeAsync()
        {
            if (!initialized)
            {
                if (!Db.TableMappings.Any(m => m.MappedType.Name == typeof(MobileUserModel).Name))
                {
                    await Db.CreateTablesAsync(CreateFlags.None, typeof(MobileUserModel)).ConfigureAwait(false);
                    //initialized = true;   <--- Currently is here
                }
                initialized = true; // <--- 
            }
        }`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bdcea465-138a-d586-5297-dc93370826b3
* Version Independent ID: a41a6f67-0675-036f-0781-13b9165d3848
* Content: [Xamarin.Forms Local Databases - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/data-cloud/data/databases)
* Content Source: [docs/xamarin-forms/data-cloud/data/databases.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/data-cloud/data/databases.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @profexorgeek
* Microsoft Alias: **jusjohns**

**Comment by davidbritch** [comment]
Hi @Denn1Ro 

Good catch. To a certain extent it doesn't matter, as `initialized` is only used in the `InitializeAsync` method. But I agree that it's a sensible update so  I've updated the doc/sample in a PR that will go live later today.
