### ISSUE TITLE
Font size data is unclear and inflexible

### ISSUE THREAD

**Issue by aormsby** [MicrosoftDocs/xamarin-docs#2999]
> - Line spacing is 120% of the font size (130% on the Windows platforms).
> - Average character width is 50% of the font size.

I am trying to auto-size a label, but I find that these values can't be trusted. It's completely unexplained how we arrived at them, and I can't seem to verify them at all. Also, they only work when using the **default font** with its **Latin characters** and are invalid in other circumstances.

Here's where I get caught up with each one.

**Line Height** - If not explicitly set, `myLabel.LineHeight` returns -1. So how do we know the line height is 1.2?

**Character Width** - I'm more concerned about this one. Yes, 0.5 is loosely the average width : height proportion of characters in the default Latin font. However, changing the font or (more so) the alphabet completely invalidates the documented value. For example, Japanese characters are closer to 1:1 so any font sizing calculations would need to use a different character width than the stated 0.5.

**If there was a way to calculate either of these values in a Xamarin.Forms app, this wouldn't be an issue.** Unfortunately, I haven't found an accurate way to do this in Xamarin. This kind of information would be great to have in the docs instead of some ( sadly unreliable) hard values.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 43ca5aa8-6294-ae0a-78e0-07cb096adddc
* Version Independent ID: 0ff2e1bb-8c4e-c8cf-7087-3c4fa8b391a5
* Content: [Summary of Chapter 5. Dealing with sizes - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/creating-mobile-apps-xamarin-forms/summaries/chapter05)
* Content Source: [docs/xamarin-forms/creating-mobile-apps-xamarin-forms/summaries/chapter05.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/creating-mobile-apps-xamarin-forms/summaries/chapter05.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @aormsby 

The doc you're referring to relates to a book that was published in 2016, and that hasn't been updated since. When the book was written, the `Label` class lacked `LineHeight` and `CharacterSpacing` properties. I've added notes to the book docs to reflect this.

There's an [enhancement request](https://github.com/xamarin/Xamarin.Forms/issues/7176) for Xamarin.Forms that includes details on how this can be achieved.
