### ISSUE TITLE
Wrong namespace for the Context class

### ISSUE THREAD

**Issue by HankiDesign** [MicrosoftDocs/xamarin-docs#3]
Right under the **Reading Assets** header, there's a typo in the text body (access => accessing) and the namespace of the Context class (Android.Contet.Context => Android.Content.Context). 

Here's an attempt to highlight the issues within the text: *"... is available by **access** the Assets property on an Android.**Contet**.Context ...*

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d4929345-b389-d55d-5fad-dbd429211541
* Version Independent ID: 33946e4b-4f22-b2f8-8965-a3399beec41e
* Content: [Using Android Assets - Xamarin | Microsoft Docs](https://docs.microsoft.com/en-us/xamarin/android/app-fundamentals/resources-in-android/android-assets?tabs=vswin)
* Content Source: [docs/android/app-fundamentals/resources-in-android/android-assets.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/android/app-fundamentals/resources-in-android/android-assets.md)
* Service: **unspecified**
* GitHub Login: @mgmclemore
* Microsoft Alias: **mamcle**

**Comment by mgmclemore** [comment]
Fixed, these updates should be published soon. Thank you for pointing this out!
