### ISSUE TITLE
Please support Bluetooth connection!

### ISSUE THREAD

**Issue by nguyenthanhliemfc** [MicrosoftDocs/xamarin-docs#300]
Thank you for everything you have do for Xamarin!
Please support Bluetooth connection!

---
#### Chi tiết tài liệu

⚠ *Không chỉnh sửa phần này. Điều này là bắt buộc cho docs.microsoft.com ➟ Vấn đề khi liên kết GitHub.*

* ID: 78e6dee8-1182-bf1e-fd3a-e8d1aecc094a
* Version Independent ID: 81202c69-317a-f0fa-7324-5316f7c1ceb7
* Content: [Xamarin.Essentials - Xamarin](https://docs.microsoft.com/vi-vn/xamarin/essentials/get-started?context=xamarin%2Fxamarin-forms&tabs=windows%2Candroid)
* Content Source: [docs/essentials/get-started.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/essentials/get-started.md)
* Service: **unspecified**
* Product: **xamarin**
* GitHub Login: @jamesmontemagno
* Microsoft Alias: **jamont**

**Comment by bradumbaugh** [comment]
Hi @nguyenthanhliemfc, this repository is only for documentation-specific issues. If you have an issue or a feature request for Xamarin.Essentials, please file it here: https://github.com/xamarin/Essentials/issues. Thank you!

**Comment by bradumbaugh** [comment]
Quick update on this: it looks like there is [a couple](https://github.com/xamarin/Essentials/issues/242) of [issues/proposals](https://github.com/xamarin/Essentials/issues/77) filed related to Bluetooth. Unfortunately, I don't have any more information about the status, but feel free to keep an eye on them. Thanks for the suggestion @nguyenthanhliemfc – appreciate your help!

**Comment by nguyenthanhliemfc** [comment]
Thank you!
