### ISSUE TITLE
Feedback link(s)

### ISSUE THREAD

**Issue by JRWest2000** [MicrosoftDocs/xamarin-docs#3000]
When you click the feedback --**This product**-- link you are taken to **VS2019** not **XAMARIN**

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: beba880f-738a-de50-5fe1-239de315b110
* Version Independent ID: 2385d6da-c57b-5e92-b43b-965ced0a4305
* Content: [Xamarin.Forms Accessibility - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/accessibility/)
* Content Source: [docs/xamarin-forms/app-fundamentals/accessibility/index.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/app-fundamentals/accessibility/index.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @JRWest2000 

The feedback link for the product is correct. The VS2019 category is where feedback for the Mobile Tools component of Visual Studio should be left.
