### ISSUE TITLE
Typo on Efficient page loading example.

### ISSUE THREAD

**Issue by samir-dahal** [MicrosoftDocs/xamarin-docs#3001]
****
### Typo on **Efficient page loading example.**
In a Shell application, every ContentPage object in a ShellContent ....

### Typo: CatsPage
This XAML creates and displays CatsPage, because it's the first item of content declared in the subclassed Shell object. **CatsPage** and MonkeysPage can be navigated to via bottom tabs, and these pages are only created when the user navigates to them. The advantage of this approach is that the poor startup experience is avoided, as pages are created on demand in response to navigation, rather than at application startup.

### Fixed: DogsPage
This XAML creates and displays CatsPage, because it's the first item of content declared in the subclassed Shell object. **DogsPage** and MonkeysPage can be navigated to via bottom tabs, and these pages are only created when the user navigates to them. The advantage of this approach is that the poor startup experience is avoided, as pages are created on demand in response to navigation, rather than at application startup.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ef7242a0-d46e-19ea-e22d-f327dcc9b3e9
* Version Independent ID: f050be8e-9413-19e7-5799-90a55c4e5bfb
* Content: [Xamarin.Forms Shell Layout - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/shell/tabs#efficient-page-loading)
* Content Source: [docs/xamarin-forms/app-fundamentals/shell/tabs.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/app-fundamentals/shell/tabs.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @samir-dahal 

Thanks for pointing this out. I've fixed the doc in a PR that will go live later today.

**Comment by samir-dahal** [comment]
You're welcome :)
