### ISSUE TITLE
Error in Multi-Page Xamarin.Forms Tutorial. Step 9

### ISSUE THREAD

**Issue by danixbsc** [MicrosoftDocs/xamarin-docs#3002]
In step 9 of this tutorial there is an error in line 23 and 28, in function `OnSaveButtonClicked`, of the example code. The code should be `File.WriteAllText(filename, editor.Text);`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 60587f77-05de-89b9-8a08-c7e7221d27af
* Version Independent ID: 4080b687-b353-f833-4bb7-a7a3f9993338
* Content: [Perform navigation in a multi-page Xamarin.Forms application - Xamarin](https://docs.microsoft.com/en-us/xamarin/get-started/quickstarts/multi-page)
* Content Source: [docs/get-started/quickstarts/multi-page.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/get-started/quickstarts/multi-page.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @danixbsc 

Afraid not. If you look at step 8 in the tutorial, the `Editor` no longer has an `x:Name`, and therefore can't be referenced in the code in step 9.
