### ISSUE TITLE
Is there a good way to parse the string results from a reverse geocode?

### ISSUE THREAD

**Issue by Nerves82** [MicrosoftDocs/xamarin-docs#3004]
This API returns a list of string for possible addresses. On the Google side the results have an incredibly unreliable format. Is there a recommended way to parse these into an object that will reliably let the implementing application use the data? 

Example of returned strings:
Lyndon, VT, USA
313 Juniper Ln, Lyndon, VT 05851, USA
Concord, VT 05824, USA

How are we suppose to parse these reliably? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 66ba2270-1bf5-ef49-7598-5ca1f4a06542
* Version Independent ID: ba6a0c37-5bb7-d320-e438-5ed764fc16e8
* Content: [Xamarin.Forms Map Geocoding - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/map/geocoder)
* Content Source: [docs/xamarin-forms/user-interface/map/geocoder.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/map/geocoder.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @Nerves82 

I feel your pain. This is an area where Xamarin.Forms is a bit weak. Internally, it turns the response from Google into an `IList<Address> object, which would be perfect for you. But then it converts them to strings before returning them to you.

Luckily this is an area where Xamarin.Essentials does a far better job. Check out https://docs.microsoft.com/xamarin/essentials/geocoding?tabs=android#using-reverse-geocoding

Hope this helps!

**Comment by Nerves82** [comment]
Oh Snap! Thanks for this @davidbritch. It is nice to know that this exists. Might it be beneficial to make a note in the docs for the Geocoder class that tis is an alternative?

**Comment by davidbritch** [comment]
@Nerves82 Will do. I'm leaving the issue open until I've done that.

**Comment by Nerves82** [comment]
I added the Note in the Docs for ya. https://github.com/MicrosoftDocs/xamarin-docs/pull/3006

**Comment by davidbritch** [comment]
Closed by #3006
