### ISSUE TITLE
Uncompilable XAML example for EnterActions and ExitActions

### ISSUE THREAD

**Issue by BrunoMoureau** [MicrosoftDocs/xamarin-docs#3007]
### Issue

A code sample given in the EnterActions and ExitActions section is uncompilable due to an extra double-quote inside the `<Trigger.EnterActions>` .

### Actual

```
<Entry Placeholder="enter job title">
    <Entry.Triggers>
        <Trigger TargetType="Entry"
                 Property="Entry.IsFocused" Value="True">
            <Trigger.EnterActions>
                <local:FadeTriggerAction StartsFrom="0"" />      // <----- "0""
            </Trigger.EnterActions>
            <Trigger.ExitActions>
                <local:FadeTriggerAction StartsFrom="1" />
            </Trigger.ExitActions>
            <!-- You can use both Enter/Exit and Setter together if required -->
        </Trigger>
    </Entry.Triggers>
</Entry>
```

### Expected

```
<Entry Placeholder="enter job title">
    <Entry.Triggers>
        <Trigger TargetType="Entry"
                 Property="Entry.IsFocused" Value="True">
            <Trigger.EnterActions>
                <local:FadeTriggerAction StartsFrom="0" />
            </Trigger.EnterActions>
            <Trigger.ExitActions>
                <local:FadeTriggerAction StartsFrom="1" />
            </Trigger.ExitActions>
            <!-- You can use both Enter/Exit and Setter together if required -->
        </Trigger>
    </Entry.Triggers>
</Entry>
```

Thank you for the doc ! 👍 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a3ff3ffd-9177-76ff-ac6e-7cb439750203
* Version Independent ID: 8e881672-c9ff-354c-fb22-97a8d1af2d72
* Content: [Xamarin.Forms Triggers - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/triggers)
* Content Source: [docs/xamarin-forms/app-fundamentals/triggers.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/app-fundamentals/triggers.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @BrunoMoureau 

Thanks for pointing this out. I've fixed it in a PR that will go live in the next hour.
