### ISSUE TITLE
When Can a Flag be Removed?

### ISSUE THREAD

**Issue by PatrickRyder** [MicrosoftDocs/xamarin-docs#3009]
It would be good if the document explained how to determine when the flag can be removed - in other words when the particular feature goes into a Xamarin release?

I guess the best thing would be if the compiler issued a flag-no-longer-needed warning.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5584d254-7331-a768-39d2-54d5a6f1e923
* Version Independent ID: a4ba858e-91f4-f79a-219e-6af8f6146fab
* Content: [Xamarin.Forms experimental flags - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/internals/experimental-flags)
* Content Source: [docs/xamarin-forms/internals/experimental-flags.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/internals/experimental-flags.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @PatrickRyder 

At the moment I've been removing experimental flags from the docs as features stop being experimental. So the list is always correct, with regards to the current stable release.

With that said, I get your point. You want to know in what release an experimental flag was removed. I think the best that can be achieved here is a new section that lists the release in which experimental flags were removed.

Moving forward, the plan is for all experimental flags to be removed by Xamarin.Forms 5.0.

**Comment by PatrickRyder** [comment]
Thank you for the information, David. Sounds good.


  *   Patrick

________________________________

**Comment by davidbritch** [comment]
https://docs.microsoft.com/xamarin/xamarin-forms/internals/experimental-flags#old-experimental-flags
