### ISSUE TITLE
So how do you do it from Visual Studio on Windows?

### ISSUE THREAD

**Issue by PatrickRyder** [MicrosoftDocs/xamarin-docs#301]
The title says it all really.  It's a year since I developed on Xamarin and I can't believe getting the application from Windows to build on my Mac is still such a PITA.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a0e57506-fd04-86b0-bc1e-e04fbd7bff05
* Version Independent ID: 7a7578eb-3bfd-60dc-3a9e-6c43aa6e42b6
* Content: [Device Provisioning - Xamarin](https://docs.microsoft.com/en-us/xamarin/ios/get-started/installation/device-provisioning/)
* Content Source: [docs/ios/get-started/installation/device-provisioning/index.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/ios/get-started/installation/device-provisioning/index.md)
* Service: **unspecified**
* Product: **xamarin**
* GitHub Login: @asb3993
* Microsoft Alias: **amburns**

**Comment by asb3993** [comment]
@PatrickRyder If you are trying to deploy to your iOS device, you can use automatic provisioning in VS 2017, provided you have updated for version 15.7. You can find information on doing that here: https://docs.microsoft.com/en-us/xamarin/ios/get-started/installation/device-provisioning/automatic-provisioning?tabs=vswin

If you need help with pairing your Windows machine to a Mac build host, visit the [Pair to Mac](https://docs.microsoft.com/en-us/xamarin/ios/get-started/installation/windows/connecting-to-mac/) guide.
