### ISSUE TITLE
Documentation is wrong regarding safe area modification

### ISSUE THREAD

**Issue by Tommigun1980** [MicrosoftDocs/xamarin-docs#3012]
The document says "It can then be modified as required and re-assigned to the Padding property in the page constructor or OnAppearing override:".

It only works in OnAppearing and not in the constructor as the document says.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c250f813-4a81-7c22-e42c-eeb328aeaba6
* Version Independent ID: b9db6a09-f815-4242-32af-68b937919f73
* Content: [Safe Area Layout Guide on iOS - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/platform/ios/page-safe-area-layout)
* Content Source: [docs/xamarin-forms/platform/ios/page-safe-area-layout.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/platform/ios/page-safe-area-layout.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @Tommigun1980 

Thanks for letting me know. Agreed. I've updated the doc in a PR that will go live by the end of the week.

**Comment by trampster** [comment]
OnAppearing is a also a bad solution, because it displays wrong, then is redrawn correct, which is horrible.
