### ISSUE TITLE
XmlnsDefinitionAttribute does work with XamlCompilationOptions.Compile nor Intellisense

### ISSUE THREAD

**Issue by ahmedalejo** [MicrosoftDocs/xamarin-docs#3014]
Please mention that this `XmlnsDefinitionAttribute` doesn´t work work **XamlC** i.e. 
```csharp
[assembly: XamlCompilation(XamlCompilationOptions.Compile)]
```
nor does it enable intellisense

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3a849344-bfe7-89eb-3949-10591484a2cf
* Version Independent ID: 8be4b6ea-3cd8-8d74-58db-b07dcdf78ab6
* Content: [XAML Custom Namespace Schemas in Xamarin.Forms - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/xaml/custom-namespace-schemas)
* Content Source: [docs/xamarin-forms/xaml/custom-namespace-schemas.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/xaml/custom-namespace-schemas.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @ahmedalejo 

I just tried the sample and enabled XAMLC in the MyControls library project. It compiled/ran just fine.

I'll close the issue here as you've also logged it at https://github.com/xamarin/Xamarin.Forms/issues/11721

**Comment by ahmedalejo** [comment]
Thanks for the feedback @davidbritch could point to the sample project you tested it on?

I´ll follow up on xamarin/Xamarin.Forms#11721

**Comment by davidbritch** [comment]
@ahmedalejo 

https://github.com/xamarin/xamarin-forms-samples/tree/master/XAML/CustomNamespaceSchemas

**Comment by ahmedalejo** [comment]
@davidbritch sorry for the delay. I had solved the issue with a workaround and moved forward.

The following seems to work
```csharp
//in: MyCompany.Controls.csproj
[assembly: XamlCompilation(XamlCompilationOptions.Compile)]
[assembly: XmlnsDefinition("http://mycompany.com/schemas/controls", "MyCompany.Controls")]
```
but not the following

```csharp
//in: CustomNamespaceSchemaDemo.csproj
[assembly: XamlCompilation(XamlCompilationOptions.Compile)]
[assembly: XmlnsDefinition(
    "http://mycompany.com/schemas/controls", 
    Na"MyCompany.Controls", 
    AssemblyName: "MyCompany.Controls")]
```
