### ISSUE TITLE
Vague statement: Linker behavior must be set to Don't Link

### ISSUE THREAD

**Issue by spottedmahn** [MicrosoftDocs/xamarin-docs#3017]
>Linker behavior must be set to Don't Link (under iOS Build Project options)

Hello - any chance we can expound upon that?  Perhaps a screen shot?

There's a lot of tabs & options on the project properties.  Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aaddaa8d-6e8e-8b12-bcf4-284175238bbe
* Version Independent ID: 6e3d847c-badc-904d-0ff5-a66e1fc8bc81
* Content: [Inspector Installation and Requirements - Xamarin](https://docs.microsoft.com/en-us/xamarin/tools/inspector/install?tabs=macos#supported-platforms)
* Content Source: [docs/tools/inspector/install.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/tools/inspector/install.md)
* Product: **xamarin**
* Technology: **xamarin-crossplatform**
* GitHub Login: @davidortinau
* Microsoft Alias: **daortin**

**Comment by davidbritch** [comment]
Closing as taken care of by the linked PR.
