### ISSUE TITLE
Code is broken

### ISSUE THREAD

**Issue by educatedcg** [MicrosoftDocs/xamarin-docs#3020]
OnPickPhotoButtonClicked This method now will throw an error on iOS because it attempts to update the UI from a non UI thread. In order to get this to work, I had to do this inside of the viewmodel.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 22cd76be-2702-6a58-498c-a84c723d9588
* Version Independent ID: 9f98549e-ff3d-5b8d-67e6-523834c4dd6d
* Content: [Picking a Photo from the Picture Library - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/dependency-service/photo-picker)
* Content Source: [docs/xamarin-forms/app-fundamentals/dependency-service/photo-picker.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/app-fundamentals/dependency-service/photo-picker.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @educatedcg 

I've just tried this sample on iOS 13.6 and it ran fine for me - I was able to pick a photo and it was displayed.

Can you offer more detail?
