### ISSUE TITLE
API is Obsolete

### ISSUE THREAD

**Issue by koenigm-seattleu** [MicrosoftDocs/xamarin-docs#3023]
The Android api Camera gives obsolete warnings for this sample.  It needs to be updated to the latest api.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e3b172d5-2dc1-88e7-ca23-96e87ae24a42
* Version Independent ID: 1ca93300-738f-4af7-b47c-0e170b7205a4
* Content: [Implementing a View - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/custom-renderer/view)
* Content Source: [docs/xamarin-forms/app-fundamentals/custom-renderer/view.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/app-fundamentals/custom-renderer/view.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @koenigm-seattleu 

I'd been waiting for the `CameraView` control, promised in the Xamarin.Forms 4.x series, to make this article redundant. However, `CameraView` hasn't arrived.

With that said, it's going to be part of the Xamarin Community Toolkit (see https://github.com/xamarin/XamarinCommunityToolkit/issues/211). Once it gets fully merged it'll make this article redundant.

**Comment by koenigm-seattleu** [comment]
The problem with that, is this example is used by us when we want to have a preview of the camera.  The toolkit version does not support preview.  So we will need to continue to use this example.

**Comment by rodrigoalmeidafrancisco** [comment]
It is expected to be updated to version 2 camera ?

**Comment by davidbritch** [comment]
The doc and sample was updated last week to use Camera2.
