### ISSUE TITLE
Missing mediaelement audio functions for picker ...

### ISSUE THREAD

**Issue by gvellanki** [MicrosoftDocs/xamarin-docs#3037]
[What's the equivalent of the following for Audio?
Get<IVideoPicker>().GetVideoFileAsync()]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4485a974-e563-1a00-bc75-50c15942b5ed
* Version Independent ID: b59da204-445a-5019-7be5-ad2cb2f59c0d
* Content: [Xamarin.Forms MediaElement - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/mediaelement)
* Content Source: [docs/xamarin-forms/user-interface/mediaelement.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/mediaelement.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @gvellanki 

You have to write your own. It's largely the same as `GetVideoFileAsync`, except you change the media type being searched for.
