### ISSUE TITLE
Hyper link text.

### ISSUE THREAD

**Issue by brokenjavagit** [MicrosoftDocs/xamarin-docs#304]
The second behavior link text is confusing consider updating it to match the intent, Behavior<T>.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 065e1a1e-af92-486c-78d0-a457876e9074
* Version Independent ID: 72d03409-d9fa-30b8-6f9d-8cf0c9f81bc3
* Content: [Introduction to Behaviors - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/behaviors/introduction)
* Content Source: [docs/xamarin-forms/app-fundamentals/behaviors/introduction.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/app-fundamentals/behaviors/introduction.md)
* Service: **unspecified**
* Product: **xamarin**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by conceptdev** [comment]
@jfversluis fixed this for us! Thanks for noticing.
