### ISSUE TITLE
NotificationEventArgs is not explained where it comes from

### ISSUE THREAD

**Issue by Mackiovello** [MicrosoftDocs/xamarin-docs#3042]
The `NotificationEventArgs` appears in the `MainPage` example but is not explained anywhere else. It would be useful to explain that this class has to be added yourself. I had to go and look at the source code for the example to notice that the class was created for this example and not included in an imported class library.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e1d97b06-848b-73b1-0330-f57662b5c09a
* Version Independent ID: 9bb5fb04-4426-6b7a-4332-3ce86ff21b76
* Content: [Xamarin.Forms local notifications - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/local-notifications)
* Content Source: [docs/xamarin-forms/app-fundamentals/local-notifications.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/app-fundamentals/local-notifications.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @profexorgeek
* Microsoft Alias: **jusjohns**

**Comment by davidbritch** [comment]
Hi @Mackiovello 

Agreed. I've added the `NotificationEventArgs` code to the doc, in a PR that will go live later today.
