### ISSUE TITLE
Pause videos when switching pages at the same URL?

### ISSUE THREAD

**Issue by nrmiller** [MicrosoftDocs/xamarin-docs#3053]
When playing the video on VS 2019 page and switching to VS for Mac, the video keeps running.
I think this could be improved to pause the video so that it doesn't keep the audio playing while on the other page.

**Scenario:** I played the video initially thinking I was on the correct page, then changed to VS for Mac but had to go back to pause the video.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5fc5d4b4-e0c4-7399-8e32-2c2fe935cbbe
* Version Independent ID: 89992fd0-d78a-fc6f-16f9-1ee91cf18485
* Content: [Installing Xamarin - Xamarin](https://docs.microsoft.com/en-us/xamarin/get-started/installation/)
* Content Source: [docs/get-started/installation/index.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/get-started/installation/index.md)
* Product: **xamarin**
* Technology: **xamarin-crossplatform**
* GitHub Login: @conceptdev
* Microsoft Alias: **crdun**

**Comment by davidbritch** [comment]
Hi @nrmiller 

Thanks for your feedback; we appreciate it. You can submit issues related to overall site experience, or suggestions for improved site functionality or design, at [https://aka.ms/sitefeedback/](https://aka.ms/sitefeedback).
