### ISSUE TITLE
Entry carat colour not available.

### ISSUE THREAD

**Issue by Soundman32** [MicrosoftDocs/xamarin-docs#3057]
Changing the carat colour on iOS doesn't appear to be supported any more (at least not in XAML).  I've followed the description, and iOS:Entry.CursorColor has a red underscore and doesn't affect the cursor.

The only iOS specific property available in intellisense is 'AdjustsFontSizeToFitWidth`.

(I'm using Xamarin Forms 4.7.0.1260).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 410f02cf-1671-3a6b-ab3f-a685912b085b
* Version Independent ID: c7461093-3024-84fc-5730-433b7fa18a61
* Content: [Entry Cursor Color on iOS - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/platform/ios/entry-cursor-color)
* Content Source: [docs/xamarin-forms/platform/ios/entry-cursor-color.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/platform/ios/entry-cursor-color.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @Soundman32 

I just tried the sample that the page links to, and the caret color was set to LimeGreen. This is using Xamarin.Forms 4.8.

The red squiggle is still present under `ios:Entry.CursorColor="LimeGreen"`. That's an intellisense error, and unfortunately you can't rely on intellisense as a source of truth.
