### ISSUE TITLE
Linked Project

### ISSUE THREAD

**Issue by Kylar182** [MicrosoftDocs/xamarin-docs#3058]
The linked project is from Xamarin Forms 4.1, has no modern features and cannot run

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 496aefc1-60e7-3484-12d1-ba383cfc099b
* Version Independent ID: 35133eba-8bc2-a54e-b341-d873f9a3c468
* Content: [Dependency Injection - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/enterprise-application-patterns/dependency-injection)
* Content Source: [docs/xamarin-forms/enterprise-application-patterns/dependency-injection.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/enterprise-application-patterns/dependency-injection.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @Kylar182 

The eShopOnContainers app and its content was produced in 2017, and unfortunately will no longer be updated. I've added notes to the docs to indicate this.
