### ISSUE TITLE
Where is the Xamarin.Forms UWP Implementation

### ISSUE THREAD

**Issue by Orgbrat** [MicrosoftDocs/xamarin-docs#3060]
So I can not believe that Microsoft which brags on their UWP applications created this doc without a UWP implementation for Xamarin.Forms. Come on folks...

How about an update to the doc?

Orgbrat

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ddbe4aab-ea07-14fa-09ff-f68e43fe289a
* Version Independent ID: 44dbed2f-fa71-dfee-90e1-422f52ba3891
* Content: [Xamarin.Forms Reusable RoundEffect - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/effects/reusable-roundeffect)
* Content Source: [docs/xamarin-forms/app-fundamentals/effects/reusable-roundeffect.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/app-fundamentals/effects/reusable-roundeffect.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @profexorgeek
* Microsoft Alias: **jusjohns**

**Comment by davidbritch** [comment]
Hi @Orgbrat 

Using an effect to create round controls is no longer necessary. The recommended approach is to set the `Clip` property of a control to a `Geometry` object that clips the control. For more info see https://docs.microsoft.com/xamarin/xamarin-forms/user-interface/shapes/geometries#clip-with-a-geometry

I'll update the doc to this effect.

**Comment by davidbritch** [comment]
I've updated the doc in a PR that will go live later this week.
