### ISSUE TITLE
The Navigated event is fired by the overridable OnNavigating method in the Shell class.

### ISSUE THREAD

**Issue by viktorszekeress** [MicrosoftDocs/xamarin-docs#3062]
Documentation says:
"The **Navigated** event is fired by the overridable **OnNavigating** method in the Shell class."
"The **Navigating** event is fired by the overridable **OnNavigated** method in the Shell class."

Shouldn't it be:
"The **Navigating** event is fired by the overridable **OnNavigating** method in the Shell class."
"The **Navigated** event is fired by the overridable **OnNavigated** method in the Shell class."
?

Which isn't the case anyway for OnNavigated method, since this method is empty in Shell class.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b6efe82d-a8b9-82a8-7d38-98f2f8d5e682
* Version Independent ID: 28d7341e-ae6e-6321-6550-d27ae6b256d2
* Content: [Xamarin.Forms Shell Navigation - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/shell/navigation)
* Content Source: [docs/xamarin-forms/app-fundamentals/shell/navigation.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/app-fundamentals/shell/navigation.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @viktorszekeress 

You may have been right, but as you've also pointed out, the overrides don't fire the events anymore so I've removed the two notes from the doc (in a PR that will go live later in the week).

Thanks for pointing this out!
