### ISSUE TITLE
Drag commands are mentioned but have no instructions for usage

### ISSUE THREAD

**Issue by BurkusCat** [MicrosoftDocs/xamarin-docs#3064]
Several commands are mentioned in this doc: `DragStartingCommand`, `DropCompletedCommand`, `DragOverCommand`, and `DropCommand`. They look to match up with all of the available events for the same functionality. However, there are no clear instructions for how to use these commands. I was able to get the `DragOverCommand` to trigger, but I wasn't able to use it as effectively as the equivalent event because I do not know how to use the `DragOverCommandParameter`.

Instructions (even brief ones) on how to use command equivalents of all these would be great.

Another issue: DropCompletedCommmand has too many "m"s.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f07c1436-d8cf-8f5e-939b-3da68122f83e
* Version Independent ID: ba4d582d-447d-017c-7b36-d18357e83187
* Content: [Add drag and drop gesture recognizers - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/gestures/drag-and-drop)
* Content Source: [docs/xamarin-forms/app-fundamentals/gestures/drag-and-drop.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/app-fundamentals/gestures/drag-and-drop.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @BurkusCat 

I've added two command demos to the sample. It might take a while for the CI to update it in the samples browser, so in the meantime you can find it in the GitHub repo (https://github.com/xamarin/xamarin-forms-samples/tree/master/WorkingWithGestures/DragAndDropGesture).

I'll see what I can add to the doc to help clear command usage up.

**Comment by davidbritch** [comment]
I've updated the doc in a PR that will go live later this week.
