### ISSUE TITLE
Xamarin Azure Notification Hubs Intermittent iOS device registration issues

### ISSUE THREAD

**Issue by donaldashworth** [MicrosoftDocs/xamarin-docs#3065]
Xamarin Intermittent iOS device registration issues on Azure Notification Hubs

I have worked with Microsoft on this issue (case 120051921001604) and Microsoft has claimed that this Azure Notification Hubs intermittent iOS device registration issue is due to a problem with Apple iOS.  The work around is to install the application using the devices Cellular Network (non-Wifi) otherwise the app will experience this issue.

https://developer.apple.com/forums/thread/128172

I believe Microsoft should be forthcoming about this and explain the issue in the Azure Notification Hub sample code README.md file.  Doing so will save developers a lot of frustration, wasted time and money...and, more importantly "confidence in you".

"If" this is a known issue and "if" it is out of your control so solve it, you must tell us about the issue.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 92f390d9-cbd0-ab8c-6c8c-49df76d1b8e0
* Version Independent ID: 15739c2f-afbb-c21d-b96f-fabe7060e410
* Content: [Send and receive push notifications with Azure Notification Hubs and Xamarin.Forms - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/data-cloud/azure-services/azure-notification-hub#feedback)
* Content Source: [docs/xamarin-forms/data-cloud/azure-services/azure-notification-hub.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/data-cloud/azure-services/azure-notification-hub.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @profexorgeek
* Microsoft Alias: **jusjohns**

**Comment by davidbritch** [comment]
Hi @donaldashworth 

Thanks for pointing this out. I've just updated the sample readme.
