### ISSUE TITLE
Problem with SignalR example

### ISSUE THREAD

**Issue by justwooper** [MicrosoftDocs/xamarin-docs#3068]
Just did this example and when I consume the method it says this: 
There was an error: Could not load file or assembly 'Microsoft.IdentityModel.Tokens, Version=5.5.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.  

How can I solve this?

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 99698458-a6cb-0874-bdda-5a3fcb0988b3
* Version Independent ID: 970e5418-c85e-7b4e-adf1-a5ebc411bebc
* Content: [Azure SignalR Service with Xamarin.Forms - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/data-cloud/azure-services/azure-signalr)
* Content Source: [docs/xamarin-forms/data-cloud/azure-services/azure-signalr.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/data-cloud/azure-services/azure-signalr.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @profexorgeek
* Microsoft Alias: **jusjohns**

**Comment by davidbritch** [comment]
Hi @justwooper 

Thanks for your question. It looks like you're having an issue with the product itself, rather than issue with the documentation. Your best bet is to ensure you've installed the required NuGet packages correctly, and to compare your solution against the sample the doc links to.
