### ISSUE TITLE
Cant acceses test flight

### ISSUE THREAD

**Issue by Aleryk** [MicrosoftDocs/xamarin-docs#307]
When i click the "TestFlight registration information" link i get redirected to a page that shows the following error:

Application error
An error occurred in the application and your page could not be served. If you are the application owner, check your logs for details.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 79320e9a-8b52-1c24-0a5b-a7ef6a32b519
* Version Independent ID: 88548723-6f1b-50c1-163c-a9e151b024e8
* Content: [Xamarin Live Player Setup - Xamarin](https://docs.microsoft.com/en-us/xamarin/tools/live-player/install?tabs=ios%2Cwindows#feedback)
* Content Source: [docs/tools/live-player/install.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/tools/live-player/install.md)
* Service: **unspecified**
* Product: **xamarin**
* GitHub Login: @topgenorth
* Microsoft Alias: **toopge**

**Comment by bradumbaugh** [comment]
Hi @Aleryk, this page appears to be working at this point. Please give it another shot and let me know if you don't have any luck.

**Comment by iSamMahoozi** [comment]
@bradumbaugh : The [iOS TestFlight registration link](https://fastring.xamarinliveplayer.com/) is not working, returning the same Heroku error page (same message as OP)

**Comment by Lonefish** [comment]
Same issue here, not working link

**Comment by bradumbaugh** [comment]
Hi @iSamMahoozi and @Lonefish Thanks for calling this out. I'm looking in to this and will respond when I have more info.

**Comment by iwonajs** [comment]
I am looking to access "iOS TestFlight registration" link as well. Please update. Thank you.

**Comment by patch321** [comment]
Same. Commenting for update.

**Comment by 1saeedsalehi** [comment]
same issue, please update

**Comment by budimartoyo** [comment]
It does not work again.

Application error 
An error occurred in the application and your page could not be served. If you are the application owner, check your logs for details.

**Comment by hsnsalhi** [comment]
+1

**Comment by RBaha98** [comment]
Down again.

**Comment by kokoit555** [comment]
+1 Down again

**Comment by jamesatgithub** [comment]
@bradumbaugh please fix this asap

**Comment by bradumbaugh** [comment]
Hi @budimartoyo, @hsnsalhi, @RBaha98, @kokoit555, @xiiumiin, @jamesatgithub – thanks for calling this out. We're looking at it and I'll post something here when we have something figured out. Appreciate the help.

**Comment by cbrenes** [comment]
+1 Down again

**Comment by bradumbaugh** [comment]
Hi everyone, this is back up. Thanks again for the help.

**Comment by srgfraser** [comment]
It seems to be down again... :(

**Comment by mgramley** [comment]
Hmm, the link seems to be down again, I can't register. Any info on when this will be up and running again?

**Comment by zxasm** [comment]
This is down again, any idea when it is likely to be working again?

**Comment by conceptdev** [comment]
Thanks for your interest in the Xamarin Live Player Preview for iOS, and for letting us know about this broken link. As of August 10th we have stopped TestFlight registration and will no longer be distributing the iOS version of the Xamarin Live Player.

Because of this, the page mentioned in this feedback is no longer available. Please visit https://developer.xamarin.com/getting-started-android/ for the Android Preview instructions and download from Google Play.

**Comment by Lonefish** [comment]
@conceptdev Does this mean there will be no Xamarin Live Player Preview on iOS? Or are you just closing registration and finalizing the app for release?

**Comment by conceptdev** [comment]
We will no longer be distributing the iOS version of the Xamarin Live Player.

**Comment by jamesatgithub** [comment]
so Live Player is dead and XAML Reload long live ?

**Comment by dinobu** [comment]
Neither XLP, nor reload, nor Gorilla work.  XAML should die
