### ISSUE TITLE
Doc point to old sharpie version

### ISSUE THREAD

**Issue by tompi** [MicrosoftDocs/xamarin-docs#3072]
Hey, the official docs say latest sharpie version is 3.4, and point to that download.

However, 3.4 is pretty old and lacks a lot of stuff(e.g. doesnt handle header files with "SWIFT_CLASS" annotation).
Please update to point to http://aka.ms/objective-sharpie
(instead of https://dl.xamarin.com/objective-sharpie/ObjectiveSharpie.pkg )

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6511e149-63d3-f287-b8cb-762869ec3fec
* Version Independent ID: ff37d867-002a-6495-1dab-a54878b742f0
* Content: [Getting Started With Objective Sharpie - Xamarin](https://docs.microsoft.com/en-us/xamarin/cross-platform/macios/binding/objective-sharpie/get-started)
* Content Source: [docs/cross-platform/macios/binding/objective-sharpie/get-started.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/cross-platform/macios/binding/objective-sharpie/get-started.md)
* Product: **xamarin**
* Technology: **xamarin-crossplatform**
* GitHub Login: @davidortinau
* Microsoft Alias: **daortin**

**Comment by davidbritch** [comment]
Hi @tompi 

Thanks for pointing this out. I've updated the link in a PR that will go live later this week.
