### ISSUE TITLE
How to specify FontWeights?

### ISSUE THREAD

**Issue by ParsaGachkar** [MicrosoftDocs/xamarin-docs#3077]
[Enter feedback here]
first of all Sry if this option already exists but searching could not help me
 OK I Have 6 different TFF files (One font with 6 different weights)

IRANSans(FaNum)_Bold.ttf
IRANSans(FaNum)_Light.ttf
IRANSans(FaNum)_Medium.ttf
IRANSans(FaNum)_UltraLight.ttf
IRANSans(FaNum).ttf
IRANSans(FaNum)_Black.ttf

Is there a way to assign all these file to single font-family and override their weight?
I'm using different Font-Families for now for each weight!
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe0572c4-91be-fc86-d130-242db2bf470b
* Version Independent ID: 1238fdd7-c378-6d0d-654e-55656a70d386
* Content: [Fonts in Xamarin.Forms - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/text/fonts#use-a-custom-font)
* Content Source: [docs/xamarin-forms/user-interface/text/fonts.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/text/fonts.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @ParsaGachkar 

Afraid not. You have to use separate font families (as you already are doing).
