### ISSUE TITLE
"the bait and switch" link is dead....

### ISSUE THREAD

**Issue by dovholuknf** [MicrosoftDocs/xamarin-docs#3078]
Stage 2 details:
> The wrapper uses 'the bait and switch trick,' described by Paul Betts

I was going to put a PR up to fix the link but in the 1 minute I searched the internet I couldn't find a working link...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e40fbe03-a099-3b24-4654-162103003d6a
* Version Independent ID: 01e8c667-ed94-7054-758d-2399e879714a
* Content: [Use C/C++ libraries with Xamarin - Xamarin](https://docs.microsoft.com/en-us/xamarin/cross-platform/cpp/)
* Content Source: [docs/cross-platform/cpp/index.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/cross-platform/cpp/index.md)
* Product: **xamarin**
* Technology: **xamarin-crossplatform**
* GitHub Login: @mikeparker104
* Microsoft Alias: **miparker**

**Comment by davidbritch** [comment]
Hi @dovholuknf 

Thanks for pointing out the broken link. It looks like the blog no longer exists. I've updated the link to point to the next best example I could find, in a PR that will go live later this week.
