### ISSUE TITLE
Theme instructions don't work.

### ISSUE THREAD

**Issue by smchughinfo** [MicrosoftDocs/xamarin-docs#308]
Using Xamarin Live Player and the snippets provided:

     <?xml version="1.0" encoding="utf-8" ?>
     <Application xmlns="http://xamarin.com/schemas/2014/forms"
                  xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
                  xmlns:light="clr-namespace:Xamarin.Forms.Themes;assembly=Xamarin.Forms.Theme.Light"
                  x:Class="MyApp.App">
         <Application.Resources>
             <ResourceDictionary MergedWith="light:LightThemeResources" />
         </Application.Resources>
     </Application>

     ...
            LoadApplication(new App());

            var x = typeof(Xamarin.Forms.Themes.LightThemeResources);
            x = typeof(Xamarin.Forms.Themes.LightThemeResources);
            x = typeof(Xamarin.Forms.Themes.Android.UnderlineEffect);

I get the following error. It crashes and never loads the theme.

Visualization Error
MergedWith should inherit from ResourceDictionary (ArgumentException)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0b0ba04e-c96b-4c0d-fac5-e449fd7adeb1
* Version Independent ID: 614b2e82-816c-5675-705e-daa302b1a175
* Content: [Light Theme - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/themes/light)
* Content Source: [docs/xamarin-forms/user-interface/themes/light.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/themes/light.md)
* Service: **unspecified**
* Product: **xamarin**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by conceptdev** [comment]
Hey @smchughinfo, Xamarin Live Player is still in preview, and has many [limitations](https://docs.microsoft.com/en-us/xamarin/tools/live-player/limitations). For real-world app building and debugging it is best to use a stable emulator or device.

When you encounter bugs, issues, or have a feature request, please use the [Developer Community site](https://developercommunity.visualstudio.com/). Thanks!
