### ISSUE TITLE
Include guidance on when to consider BindableLayout over CollectionView

### ISSUE THREAD

**Issue by mikeparker104** [MicrosoftDocs/xamarin-docs#3080]
The [documentation for BindableLayout](https://docs.microsoft.com/xamarin/xamarin-forms/user-interface/layouts/bindable-layouts) contains guidance on when to consider virtualizing controls such as CollectionView instead.
 
'Bindable layouts should only be used when the collection of items to be displayed is small, and scrolling and selection isn't required. While scrolling can be provided by wrapping a bindable layout in a [ScrollView](https://docs.microsoft.com/en-us/dotnet/api/xamarin.forms.scrollview), this is not recommended as bindable layouts lack UI virtualization. When scrolling is required, a scrollable view that includes UI virtualization, such as [ListView](https://docs.microsoft.com/en-us/dotnet/api/xamarin.forms.listview) or [CollectionView](https://docs.microsoft.com/en-us/dotnet/api/xamarin.forms.collectionview), should be used. Failure to observe this recommendation can lead to performance issues.'
 
It might be helpful to have equivalent guidance on the [CollectionView documentation](https://docs.microsoft.com/xamarin/xamarin-forms/user-interface/collectionview/) indicating situations where BindableLayout could be a better fit.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9de402a5-a78c-3cfe-f9b1-443a3401574b
* Version Independent ID: 4488127d-8fe9-eef6-c665-106b493f93fd
* Content: [Xamarin.Forms CollectionView - Xamarin](https://docs.microsoft.com/en-gb/xamarin/xamarin-forms/user-interface/collectionview/)
* Content Source: [docs/xamarin-forms/user-interface/collectionview/index.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/collectionview/index.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
This is now done in a PR that will go live tomorrow.
