### ISSUE TITLE
The doc should mentions the Info.plist to avoid confussions

### ISSUE THREAD

**Issue by juanogcx** [MicrosoftDocs/xamarin-docs#3081]
While trying to setup provisioning matching, I was changing the assembly name instead of the bundle identifier. I think it should be good to mention that the bundle identifier is on the plist like this:

"exactly matches your Xamarin.iOS app's bundle identifier found on the Info.plist"

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1a9b2b39-f572-75dc-f022-cada4919f129
* Version Independent ID: 804f0f6d-ed12-18d8-30b8-95b5aaa19d8a
* Content: [Free Provisioning for Xamarin.iOS Apps - Xamarin](https://docs.microsoft.com/en-gb/xamarin/ios/get-started/installation/device-provisioning/free-provisioning?tabs=windows)
* Content Source: [docs/ios/get-started/installation/device-provisioning/free-provisioning.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/ios/get-started/installation/device-provisioning/free-provisioning.md)
* Product: **xamarin**
* Technology: **xamarin-ios**
* GitHub Login: @davidortinau
* Microsoft Alias: **daortin**

**Comment by davidbritch** [comment]
Hi @juanogcx 

Thanks for the suggestion. I've updated the doc as per your suggestion, in a PR that will go live later this week.
