### ISSUE TITLE
Xamarin  Essentials Maps with map app 3 pont location

### ISSUE THREAD

**Issue by MiguelRadaza** [MicrosoftDocs/xamarin-docs#3083]
Good day,

is there  a way that i can redirect to map app with 3 point location (eg. point A, point B, (point c = my location) ).

Thank you.
God bless.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 60e280c8-f7b6-1207-5118-6629bde45766
* Version Independent ID: 5021f76b-f0ba-a129-d2a5-c7190db71a7a
* Content: [Xamarin.Essentials Map - Xamarin](https://docs.microsoft.com/en-us/xamarin/essentials/maps?context=xamarin%2Fandroid&tabs=android)
* Content Source: [docs/essentials/maps.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/essentials/maps.md)
* Product: **xamarin**
* Technology: **xamarin-essentials**
* GitHub Login: @jamesmontemagno
* Microsoft Alias: **jamont**

**Comment by jamesmontemagno** [comment]
There is not currently no, however you can open an feature request over at https://github.com/xamarin/essentials
