### ISSUE TITLE
Code sample for "Populate a CarouselView with data" section doesn't work

### ISSUE THREAD

**Issue by rachelkang** [MicrosoftDocs/xamarin-docs#3085]
The code sample provided under "Populate a CarouselView with data" is a poor example, and fails to render a CarouselView. 

An updated version might look something like:
```
    <CarouselView>
        <CarouselView.ItemsSource>
            <x:Array Type="{x:Type x:String}">
                <x:String>Baboon</x:String>
                <x:String>Capuchin Monkey</x:String>
                <x:String>Blue Monkey</x:String>
                <x:String>Squirrel Monkey</x:String>
                <x:String>Golden Lion Tamarin</x:String>
                <x:String>Howler Monkey</x:String>
                <x:String>Japanese Macaque</x:String>
            </x:Array>
        </CarouselView.ItemsSource>
        <CarouselView.ItemTemplate>
            <DataTemplate>
                <Label Text="{Binding .}"/>
            </DataTemplate>
        </CarouselView.ItemTemplate>
    </CarouselView>
```

The screenshots also do not reflect what the code would actually render, with regard to formatting/layout, which can be misleading to users.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b99d7746-543f-8608-25f3-f5c9b2fb8b0d
* Version Independent ID: c53cec53-1432-d7ee-0694-d66044986156
* Content: [Xamarin.Forms CarouselView Data - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/carouselview/populate-data)
* Content Source: [docs/xamarin-forms/user-interface/carouselview/populate-data.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/carouselview/populate-data.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @rachelkang 

It's too problematic expecting the control to behave the same in subsequent releases, so I've removed this example (which did render content, in an ugly way, on iOS and Android for me without using a template).
