### ISSUE TITLE
Add an example of an Empty View with more customised content

### ISSUE THREAD

**Issue by Axemasta** [MicrosoftDocs/xamarin-docs#3088]
Whilst this page does document the `CollectionView.EmptyView` feature, it does not give adequate examples of more customised views. The presented examples are:

_A simple empty view_

```xaml
<CollectionView ItemsSource="{Binding EmptyMonkeys}"
                EmptyView="No items to display" />
```

![The simple empty view](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/collectionview/emptyview-images/null-itemssource.png)

_A more complicated empty view_

```xaml
<CollectionView.EmptyView>
    <StackLayout>
        <Label Text="No results matched your filter."
                Margin="10,25,10,10"
                FontAttributes="Bold"
                FontSize="18"
                HorizontalOptions="Fill"
                HorizontalTextAlignment="Center" />
        <Label Text="Try a broader filter?"
                FontAttributes="Italic"
                FontSize="12"
                HorizontalOptions="Fill"
                HorizontalTextAlignment="Center" />
    </StackLayout>
</CollectionView.EmptyView>
```

![The more complicated empty view](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/collectionview/emptyview-images/filter-multiple-views.png)

These examples serve well for a chat application, however what happens if you want to display an image and copy the appearance of the native iOS empty table view? A commonly used library on iOS is [DZNEmptyDataSet](https://github.com/dzenbot/DZNEmptyDataSet), I have personally used this library before and was looking to recreate the styling of the platform library with `CollectionView.EmptyView`. Below are the examples of empty views which I think should be provided by the xamarin documentation.

![Screenshots_Row1](https://raw.githubusercontent.com/dzenbot/DZNEmptyDataSet/v2-swift/Examples/Applications/Screenshots/Screenshots_row1.png)

Lets try recreating one of these screens using the documentation. Experience suggests we would just need to define our content:

```xaml
<CollectionView.EmptyView>
    <Grid HorizontalOptions="CenterAndExpand" VerticalOptions="CenterAndExpand">
        <Grid.RowDefinitions>
            <RowDefinition Height="100"/>
            <RowDefinition Height="auto"/>
            <RowDefinition Height="auto"/>
        </Grid.RowDefinitions>

        <Image Source="chat-icon.png"
               Grid.Row="0"/>
        <Label Text="No Chats Available"
               FontAttributes="Bold"
               HorizontalTextAlignment="Center"
               Grid.Row="1"/>
        <Label Text="Once you are sent a message, it will appear in this list"
               HorizontalTextAlignment="Center"
               Grid.Row="2"/>
    </Grid>
</CollectionView.EmptyView>
```

![Incorrectly displayed empty view](https://user-images.githubusercontent.com/33064621/94268819-9ff1e080-ff35-11ea-9107-e03d3ac39ab9.png)

However if we look at the results, the empty view appears at the top of the `CollectionView` **despite** the fact that we set our `HorizontalOptions` and `VerticalOptions` to `CenterAndExpand`. This exact issue has been raised on the main Xamarin repository.

- [5041- cannot arrange content in center.](https://github.com/xamarin/Xamarin.Forms/issues/5041)

In the issue linked the reporter could not center their content. They are told that they will need to embed their view within a `ContentView` in order to center it. This happens because the child of the `EmptyView` does not respect its layout options and will always resize the element to fill all of the available space. As a result to center content a developer would need to wrap their `EmptyView` in a `ContentView` (or something that inherits from, such as `Grid`). 

Our revised view then becomes:

```xaml
<CollectionView.EmptyView>
    <ContentView>
        <Grid HorizontalOptions="CenterAndExpand" VerticalOptions="CenterAndExpand">
            <Grid.RowDefinitions>
                <RowDefinition Height="100"/>
                <RowDefinition Height="auto"/>
                <RowDefinition Height="auto"/>
            </Grid.RowDefinitions>

            <Image Source="chat-icon.png"
                Grid.Row="0"/>

            <Label Text="No Chats Available"
                FontAttributes="Bold"
                HorizontalTextAlignment="Center"
                Grid.Row="1"/>

            <Label Text="Once you are sent a message, it will appear in this list"
                HorizontalTextAlignment="Center"
                Grid.Row="2"/>
        </Grid>
    </ContentView>
</CollectionView.EmptyView>
```

![Empty view with correctly centered](https://user-images.githubusercontent.com/33064621/94268724-8355a880-ff35-11ea-9988-73b6845fefbf.png)

Now the view is correctly centered and the developer can create a view that is similar to look and feel as the existing native empty views. I believe the best way to update this document would be to wrap the existing complex view to be wrapped in a `ContentView` with a sentence explaining how to layout the view.

I believe this change would make the documentation more clear for `CollectionView` and help future developers not get caught out by this simple yet annoying quirk!

Auto Generated
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 12322437-d338-f1b3-a352-ae86d0027992
* Version Independent ID: cbfa2f8f-1b60-4bbd-a945-ee1181cf3613
* Content: [Xamarin.Forms CollectionView EmptyView - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/collectionview/emptyview)
* Content Source: [docs/xamarin-forms/user-interface/collectionview/emptyview.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/collectionview/emptyview.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @Axemasta 

Thanks for pointing this out. I've added it to the doc, in a PR that will go live tomorrow. Two things though:

1. I think it's still a bug as there's a redundant layout (a `ContentView` in this case). I'm checking up on this with the engineers.
1. `CenterAndExpand` only works on a `StackLayout`. It has no effect on a `Grid`. That applies to any of the `...AndExpand` layout options. However, the redundant layout from (1) is still required to get centering working.

**Comment by davidbritch** [comment]
It's not a bug that the `ContentView` is required. It's because internally the `EmptyView` is added to a native container that doesn't provide any context for Xamarin.Forms layout. Therefore, to position the views that comprise your `EmptyView`, you must a root layout, whose child is a layout that can position itself within the root layout.

It's a requirement that will most likely be eliminated in future. There are just more important issues to be dealt with first.

**Comment by Axemasta** [comment]
Thanks for the insight 😁
