### ISSUE TITLE
Image Url is invalid

### ISSUE THREAD

**Issue by fericode** [MicrosoftDocs/xamarin-docs#3092]
Please fix the image Url as it loads nothing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5bbb17d4-dc14-6eb9-8f83-58feba90ca73
* Version Independent ID: 2c3cf6ac-1e80-abd5-7564-b01531c5dbf2
* Content: [Binding a .JAR - Xamarin](https://docs.microsoft.com/en-us/xamarin/android/platform/binding-java-library/binding-a-jar)
* Content Source: [docs/android/platform/binding-java-library/binding-a-jar.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/android/platform/binding-java-library/binding-a-jar.md)
* Product: **xamarin**
* Technology: **xamarin-android**
* GitHub Login: @davidortinau
* Microsoft Alias: **daortin**

**Comment by davidbritch** [comment]
Hi @fericode 

I've updated the image URL in a PR that will go live later this week.
