### ISSUE TITLE
Logs location has changed

### ISSUE THREAD

**Issue by justingden** [MicrosoftDocs/xamarin-docs#3093]
The location for the logs has changed, more recently it appears to be:

C:\Users\[User Name]\AppData\Local\Xamarin\Logs\16.0

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e70c0069-6174-0591-a6e0-8e46dedae1eb
* Version Independent ID: 8a8e8863-9562-211e-fc60-eef9b6a95833
* Content: [Android Emulator Troubleshooting - Xamarin](https://docs.microsoft.com/en-us/xamarin/android/get-started/installation/android-emulator/troubleshooting)
* Content Source: [docs/android/get-started/installation/android-emulator/troubleshooting.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/android/get-started/installation/android-emulator/troubleshooting.md)
* Product: **xamarin**
* Technology: **xamarin-android**
* GitHub Login: @davidortinau
* Microsoft Alias: **daortin**

**Comment by davidbritch** [comment]
Hi @justingden 

Thanks for pointing this out. I've updated the logs location in the doc, in a PR that will go live later this week.

**Comment by justingden** [comment]
Cool! Thank you.

Justin
