### ISSUE TITLE
Is Platform Support macOS still in preview?

### ISSUE THREAD

**Issue by Nii-co** [MicrosoftDocs/xamarin-docs#3095]
Just want to check if this is still in preview? The doc hasn't been updated since 2017 and as I understand, Xamarin.Mac has several stable releases already.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 35a28b49-e47c-fca9-69e4-c261f2869e9a
* Version Independent ID: db9d6201-0042-eb0c-7b86-80089b543674
* Content: [Mac Platform Setup - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/platform/other/mac#known-issues)
* Content Source: [docs/xamarin-forms/platform/other/mac.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/platform/other/mac.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @Nii-co 

Afraid it's still a preview (see https://github.com/xamarin/Xamarin.Forms/wiki/Platform-Support-macOS-Status). Full macOS support is planned for MAUI.
