### ISSUE TITLE
How to set Multi-Bindings programmatically

### ISSUE THREAD

**Issue by yelinzh** [MicrosoftDocs/xamarin-docs#3098]
[Enter feedback here]
How to set Multi-Bindings in code behind, the tutorial doesn't involve this. I want to set MultiBinding for a `Label`, but not get the right way to achieve that.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c61c8325-8abd-145c-93ef-134ec181524a
* Version Independent ID: d3afb734-6d96-274e-7ac8-65e66199af35
* Content: [Xamarin.Forms Multi-Bindings - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/data-binding/multibinding)
* Content Source: [docs/xamarin-forms/app-fundamentals/data-binding/multibinding.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/app-fundamentals/data-binding/multibinding.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @yelinzh 

I've added two code examples to the page, in a PR that will go live in a day or two.
