### ISSUE TITLE
<Image.Clip> with a Path

### ISSUE THREAD

**Issue by michelevirgilio** [MicrosoftDocs/xamarin-docs#3100]
By using <Image.Clip> with a Path, project does not compile with this error:

Cannot assign property "Clip": Property does not exist, or is not assignable, or mismatching type between value and property.

If i use an Ellipse, it works.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ca5d7f83-e91d-fa3a-faa8-a35d44ec919d
* Version Independent ID: 55c3161b-9876-2fc5-4766-d1e8d5bbcfd7
* Content: [Xamarin.Forms Shapes: Geometries - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/shapes/geometries)
* Content Source: [docs/xamarin-forms/user-interface/shapes/geometries.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/shapes/geometries.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @michelevirgilio 

This needs logging in the [engineering repo](https://github.com/xamarin/Xamarin.Forms) so that the engineers are aware of the problem, and can fix it.
