### ISSUE TITLE
Receiving PushNotification when app is not running

### ISSUE THREAD

**Issue by BrunoMoureau** [MicrosoftDocs/xamarin-docs#3101]
Hello,

I am following [this doc](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/data-cloud/azure-services/azure-notification-hub#configure-ios-for-notifications) to be able to receive push notification in my Xamarin.Forms app.

There is a note on this page about how to receive push notification when the app isn't running on Android :

> The Android application will only receive push notifications if it is running in either the background or foreground. To receive push notifications when the main Activity is not running, you must implement a service, which is beyond the scope of this sample. For more information, see [Creating Android Services](https://docs.microsoft.com/en-us/xamarin/android/app-fundamentals/services/)

I don't understand this note as I still receive push notification even if the app is killed (on release build only).

Could you provide more information about this note? Why should it be considered if everything seems to work as expected?

Thank you for your feedback :)

Bruno

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 92f390d9-cbd0-ab8c-6c8c-49df76d1b8e0
* Version Independent ID: 15739c2f-afbb-c21d-b96f-fabe7060e410
* Content: [Send and receive push notifications with Azure Notification Hubs and Xamarin.Forms - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/data-cloud/azure-services/azure-notification-hub#configure-ios-for-notifications)
* Content Source: [docs/xamarin-forms/data-cloud/azure-services/azure-notification-hub.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/data-cloud/azure-services/azure-notification-hub.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @profexorgeek
* Microsoft Alias: **jusjohns**

**Comment by davidbritch** [comment]
Hi @BrunoMoureau 

Apologies for the delayed response. You are correct, and that note needs removing.

**Comment by BrunoMoureau** [comment]
Hi @davidbritch 

No worries for the delay. Thank you for your answer ! 👍

**Comment by davidbritch** [comment]
I've updated the doc in a PR that will go live later this week.
