### ISSUE TITLE
Permissions for KeepScreenOn for Android

### ISSUE THREAD

**Issue by Hamster-ZA** [MicrosoftDocs/xamarin-docs#3106]
For the Android:

In order to make use of the KeepScreenOn = true, the application needs to have the WAKE_LOCK permission. This can be done by adding the permission in code e.g. to the ``Assemblyinfo.cs``
```
[assembly: UsesPermission(Android.Manifest.Permission.WakeLock)]
```
or by adding the permission directly in the ``AndroidManifest.xml``
```
<uses-permission android:name="android.permission.WAKE_LOCK" />
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: baaf5be9-c6c2-5c43-c131-6cb01cda6502
* Version Independent ID: 7020d1c9-9b6b-18af-72b9-3e75c0c26340
* Content: [Xamarin.Essentials: Device Display Information - Xamarin](https://docs.microsoft.com/en-us/xamarin/essentials/device-display?tabs=android)
* Content Source: [docs/essentials/device-display.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/essentials/device-display.md)
* Product: **xamarin**
* Technology: **xamarin-essentials**
* GitHub Login: @jamesmontemagno
* Microsoft Alias: **jamont**

**Comment by jamesmontemagno** [comment]
We don't use wake locks in Xamarin.Essentials, we use the built in Keep Screen On API -> https://developer.android.com/training/scheduling/wakelock
