### ISSUE TITLE
Improperly directed link.

### ISSUE THREAD

**Issue by SungAli** [MicrosoftDocs/xamarin-docs#3107]
the "trouibleshooting" Link in this sentence "If the following error dialog is presented on launch, see the Troubleshooting section for workaround instructions: takes the reader to the summary at the end of the page.  There does not appear to be an actual troubleshooting section on the page.  Please add the section with sufficient advice to address at least the referenced error.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a7a62dcf-aba5-fd75-f6dd-187b03dade95
* Version Independent ID: 4d403c76-8620-c803-8f84-ed0675f401ce
* Content: [Managing Virtual Devices with the Android Device Manager - Xamarin](https://docs.microsoft.com/en-us/xamarin/android/get-started/installation/android-emulator/device-manager?tabs=windows&pivots=windows)
* Content Source: [docs/android/get-started/installation/android-emulator/device-manager.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/android/get-started/installation/android-emulator/device-manager.md)
* Product: **xamarin**
* Technology: **xamarin-android**
* GitHub Login: @davidortinau
* Microsoft Alias: **daortin**

**Comment by SungAli** [comment]
URL of page if Document Details is insufficient:  https://docs.microsoft.com/en-us/xamarin/android/get-started/installation/android-emulator/device-manager?tabs=windows&pivots=windows

**Comment by davidbritch** [comment]
Hi @SungAli 

The troubleshooting link is working fine for me (https://docs.microsoft.com/xamarin/android/get-started/installation/android-emulator/device-manager?tabs=windows&pivots=macos#troubleshooting). It only appears when Visual Studio for Mac is chosen at the top of the page, for your development environment.
