### ISSUE TITLE
Missing semicolon

### ISSUE THREAD

**Issue by h-abukrayem** [MicrosoftDocs/xamarin-docs#311]
missing semicolon at the end of the new EmailMessage statement
var message = new EmailMessage
            {
                Subject = subject,
                Body = body,
                To = recipients,
                //Cc = ccRecipients,
                //Bcc = bccRecipients
            };

---
#### تفاصيل المستند

⚠ *تجنب تحرير هذا القسم. مطلوب لـ docs.microsoft.com ➟ ربط مشكلة GitHub.*

* ID: 51ff7357-2cd8-7988-ed3c-de156cc18211
* Version Independent ID: ff242941-6d92-9523-bd73-ec03dbcb095d
* Content: [Xamarin.Essentials Email - Xamarin](https://docs.microsoft.com/ar-sa/xamarin/essentials/email?context=xamarin/xamarin-forms)
* Content Source: [docs/essentials/email.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/essentials/email.md)
* Service: **unspecified**
* Product: **xamarin**
* GitHub Login: @jamesmontemagno
* Microsoft Alias: **jamont**

**Comment by jfversluis** [comment]
Looks like this is fixed already?

**Comment by bradumbaugh** [comment]
Thanks @h-abukrayem and @jfversluis – it does look like this has been fixed.
