### ISSUE TITLE
Incorrect reference order for watchOS app

### ISSUE THREAD

**Issue by bruno-garcia** [MicrosoftDocs/xamarin-docs#3110]
This part:

> Check that your references are correct: that the Parent app has a reference to the Extension, and that the Extension has a reference to the Watch App.

Contradicts what the link actually says:

![image](https://user-images.githubusercontent.com/1633368/95659684-c183c800-0af0-11eb-9daf-46efbc2381be.png)

It should be:

> Check that your references are correct: that the Parent app has a reference to the Watch App, and that the Watch App has a reference to the Extensions.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4cea9a14-6fb7-6b94-abaa-b0bdbf7cd377
* Version Independent ID: e2fb8669-fc40-8468-a5d8-0de14f2b1c98
* Content: [Hello, watchOS – Walkthrough - Xamarin](https://docs.microsoft.com/en-us/xamarin/ios/watchos/get-started/hello-watch?tabs=macos)
* Content Source: [docs/ios/watchos/get-started/hello-watch.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/ios/watchos/get-started/hello-watch.md)
* Product: **xamarin**
* Technology: **xamarin-ios**
* GitHub Login: @davidortinau
* Microsoft Alias: **daortin**

**Comment by davidbritch** [comment]
Hi @bruno-garcia 

Thanks for pointing this out. I've updated the doc in a PR that will go live later this week.
