### ISSUE TITLE
 ios:Entry.CursorColor

### ISSUE THREAD

**Issue by Skeyss** [MicrosoftDocs/xamarin-docs#3111]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 410f02cf-1671-3a6b-ab3f-a685912b085b
* Version Independent ID: c7461093-3024-84fc-5730-433b7fa18a61
* Content: [Entry Cursor Color on iOS - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/platform/ios/entry-cursor-color)
* Content Source: [docs/xamarin-forms/platform/ios/entry-cursor-color.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/platform/ios/entry-cursor-color.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @Skeyss 

What about `iOS:Entry.CursorColor`?

**Comment by davidbritch** [comment]
Closed due to lack of response.
