### ISSUE TITLE
No Toolbox items draggable into the View

### ISSUE THREAD

**Issue by Jockey4her** [MicrosoftDocs/xamarin-docs#3119]
[Enter feedback here]
I opened an existing Xamarin sample app, which runs fine.  I added a new Tabbed Page to the folder of Pages, then opened the Designer view and the Toolbox.  It wont let me drag a button for example, onto the page.  Or any controls. I dont understand. In a WPF project or a UWP, you drag control and they end on on the Grid, or whatever. But you can go from there. Why cant I drop controls here?  The page should give some clue

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 03a3ae88-7faa-a205-02e5-154df52c628c
* Version Independent ID: f470c37f-ec7d-9056-c663-b2b0f39c5d1b
* Content: [Edit Xamarin.Forms XAML using the toolbox - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/xaml/toolbox?tabs=windows)
* Content Source: [docs/xamarin-forms/xaml/toolbox.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/xaml/toolbox.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @conceptdev
* Microsoft Alias: **crdun**

**Comment by davidbritch** [comment]
Hi @Jockey4her 

There isn't a designer for Xamarin.Forms. Controls are dragged from the toolbox to the XAML editor.

**Comment by Jockey4her** [comment]
I see. Strange.. Not good for first time users I guess. (no error or anything).  Thanks.
