### ISSUE TITLE
Document outdated

### ISSUE THREAD

**Issue by robv8r** [MicrosoftDocs/xamarin-docs#312]
.NET Standard 2.0 is now the default when you create a new .NET Standard project.  The above documentation should be updated to reflect the changes made to the Visual Studio UI when creating a .Net Standard library.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 483b01c5-75b5-a35b-c90c-c564535416f1
* Version Independent ID: dc8b1e89-e8f9-0e50-5d4d-248ccdab9c91
* Content: [.NET Standard - Xamarin](https://docs.microsoft.com/en-us/xamarin/cross-platform/app-fundamentals/net-standard?tabs=vswin)
* Content Source: [docs/cross-platform/app-fundamentals/net-standard.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/cross-platform/app-fundamentals/net-standard.md)
* Service: **unspecified**
* Product: **xamarin**
* GitHub Login: @asb3993
* Microsoft Alias: **amburns**

**Comment by bradumbaugh** [comment]
Thanks @robv8r. I put together a PR to fix this; should be published soon. Appreciate the help!
