### ISSUE TITLE
Missing deploy step

### ISSUE THREAD

**Issue by wilsondy** [MicrosoftDocs/xamarin-docs#3121]
The unitiated won't know they need to deploy the App to a device before running the instrumentation command.  Perhaps this should be added before step 4.

[This SO post helped me.](https://stackoverflow.com/questions/54190035/xamarin-android-unittest-and-instrumentation-test-not-formsl)
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d3cbf4f9-5a3b-0b8e-0508-e7034bbe7a62
* Version Independent ID: f3b6454a-5afa-36e0-b046-f60815705560
* Content: [How do I automate an Android NUnit Test project? - Xamarin](https://docs.microsoft.com/en-us/xamarin/android/troubleshooting/questions/automate-android-nunit-test)
* Content Source: [docs/android/troubleshooting/questions/automate-android-nunit-test.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/android/troubleshooting/questions/automate-android-nunit-test.md)
* Product: **xamarin**
* Technology: **xamarin-android**
* GitHub Login: @davidortinau
* Microsoft Alias: **daortin**

**Comment by davidbritch** [comment]
Hi @wilsondy 

Thanks for pointing this out. I've added it to the doc (the need to deploy the app), in a PR that will go live later this week.
