### ISSUE TITLE
Remove revoked Certificates

### ISSUE THREAD

**Issue by SeriousM** [MicrosoftDocs/xamarin-docs#3122]
In case the apple developer certificate was revoked one can remove the certificate from the path `C:\Users\<user>\AppData\Local\Xamarin\iOS\Provisioning\Certificates`.
I think this is an important information as windows users (like me) search every single place on the computer and local/user certificate manager without success.
Only with a tool (Everything) I was able to find the files because of the most recent changes to them.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6d17e2db-437f-d45f-f78f-f4b32a40c3f3
* Version Independent ID: 44ff0294-e19c-a926-1aa2-338c3b61371a
* Content: [Apple Account Management - Xamarin](https://docs.microsoft.com/en-us/xamarin/cross-platform/macios/apple-account-management?tabs=macos)
* Content Source: [docs/cross-platform/macios/apple-account-management.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/cross-platform/macios/apple-account-management.md)
* Product: **xamarin**
* Technology: **xamarin-crossplatform**
* GitHub Login: @davidortinau
* Microsoft Alias: **daortin**

**Comment by davidbritch** [comment]
Hi @SeriousM 

Good suggestion! I've added it in a PR that will go live later this week.
