### ISSUE TITLE
Grammatical issue

### ISSUE THREAD

**Issue by sms1991** [MicrosoftDocs/xamarin-docs#3125]
A sentence in the doc reads: _It is strongly recommended that each Xamarin.Android application specify an application icon._ 

This should read: It is strongly recommended that each Xamarin.Android application specifies an application icon. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f43472af-a9d3-8bef-0f24-b81f8f6cd2dd
* Version Independent ID: 42cfbea5-0b4c-a0a3-4cce-1edf5523f605
* Content: [Preparing an Application for Release - Xamarin](https://docs.microsoft.com/en-us/xamarin/android/deploy-test/release-prep/?tabs=windows)
* Content Source: [docs/android/deploy-test/release-prep/index.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/android/deploy-test/release-prep/index.md)
* Product: **xamarin**
* Technology: **xamarin-android**
* GitHub Login: @davidortinau
* Microsoft Alias: **daortin**

**Comment by davidbritch** [comment]
Hi @sms1991 

Thanks for pointing this out. I've fixed it in a PR that will go live later this week.
