### ISSUE TITLE
Behavior when TabIndex is 0 on UWP is not as described on this page

### ISSUE THREAD

**Issue by johnshardman** [MicrosoftDocs/xamarin-docs#3127]
Documentation of TabIndex is incorrect (there is also a bug in the XF source code related to this, which I have raised separately).
The default value of TabIndex on UWP is Int.MaxValue, not 0, so the behavior described in this page of XF documentation when TabIndex is 0 is incorrect (for UWP at least).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c1361326-9c23-642d-57f2-988ad4e29f6a
* Version Independent ID: fd9ea4b8-eb96-31dc-602a-24e5f6746fc0
* Content: [Keyboard Accessibility - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/accessibility/keyboard)
* Content Source: [docs/xamarin-forms/app-fundamentals/accessibility/keyboard.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/app-fundamentals/accessibility/keyboard.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by johnshardman** [comment]
Slight typo - should have said int.MaxValue or Int32.MaxValue, not Int.MaxValue

**Comment by davidbritch** [comment]
Hi @johnshardman 

I stand by what the doc says - the default value of the `VisualElement.TabIndex` property is 0 (even on UWP). I confirmed this by examining the value of `TabIndex` on a `Button` on UWP (that doesn't explicitly set `TabIndex`).

Am I missing your point here?

**Comment by johnshardman** [comment]
Hi @davidbritch

The problem is that the current default value of VisualElement.TabIndex is incorrect (it shouldn't be 0 on UWP). There is a separate issue raised for this at https://github.com/xamarin/Xamarin.Forms/issues/12433

Things are made more confusing because the UWP (not XF) documentation contradicts itself. Testing shows that using TabIndex of int.MaxValue as the default (as per one set of UWP documentation) gives the expected behavior, whereas using 0 (as per the UWP documentation that XF source code and documentation was based on) does not. It appears that the XF source code needs to be changed (the most likely change changing the default value of VisualElement.TabIndex). The XF documentation page will need changing too, but you may want to wait to see how the source code is changed first. I don't know who looks after the UWP (not XF) documentation - the contradiction in that needs sorting too, in order to avoid confusion.

**Comment by johnshardman** [comment]
Hi @davidbritch 

Just to clarify further, when I said in the original report that "The default value of TabIndex on UWP is Int.MaxValue, not 0", I was referring to Windows.UI.Xaml.Controls.Control.TabIndex rather than VisualElement.TabIndex

The current implementation of VisualElement.TabIndex has an incorrect default value, hence the issue raised at https://github.com/xamarin/Xamarin.Forms/issues/12433

The behavior described on this documentation page regarding VisualElement.TabIndex values reflects what is shown on one UWP documentation page, but the page that it is based on is itself inaccurate. That inaccuracy only becomes obvious when a page contains controls that do not support TabIndex (such as a WebView), when it becomes apparent that the text "VisualElement instances with a TabIndex equal to 0 are added to the tab order based on their declaration order in XAML" is incorrect. That is the behavior when TabIndex is equal to int.MaxValue. The issue at https://github.com/xamarin/Xamarin.Forms/issues/12433 includes a repro sample that might make this clearer.

**Comment by davidbritch** [comment]
Hi @johnshardman 

So am I right in thinking that the fix for the XF doc (until the source code is updated) is to clarify that to get the correct behaviour on UWP, users will have to set the `TabIndex` property on each control to `int.MaxValue`? Then the tab order will be based on the XAML declaration order.

**Comment by davidbritch** [comment]
Closing here as I've opened the issue in the windows-uwp repo.

**Comment by johnshardman** [comment]
Hi @davidbritch - apologies for the delay, only just seen your question from 18 days ago. The answer is yes :-)

**Comment by davidbritch** [comment]
I've added a note to the doc, in a PR that will go live tomorrow.
