### ISSUE TITLE
Dead link to Android developer preview content for foldables.

### ISSUE THREAD

**Issue by gkarabin** [MicrosoftDocs/xamarin-docs#3128]
There is a link to https://developer.android.com/preview/features/foldables that is now a dead link (404 in the browser).  https://developer.android.com/guide/topics/ui/foldables seems to be a useful updated link.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e0301dd5-7ff9-6f2b-ab83-271b539d46fd
* Version Independent ID: fee54cf8-4cc4-de5d-b00d-302d307545fa
* Content: [Android 10 features - Xamarin](https://docs.microsoft.com/en-us/xamarin/android/platform/android-10)
* Content Source: [docs/android/platform/android-10.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/android/platform/android-10.md)
* Product: **xamarin**
* Technology: **xamarin-android**
* GitHub Login: @JonDouglas
* Microsoft Alias: **jodou**

**Comment by davidbritch** [comment]
Hi @gkarabin 

Thanks for pointing this out. I've updated the link in a PR that will go live later this week.
