### ISSUE TITLE
[Doc] Instructions on VS2019 Do Not Result In .NetCore Project

### ISSUE THREAD

**Issue by BOSnooneTON** [MicrosoftDocs/xamarin-docs#3132]
[Enter feedback here]
The assertion that .NetCore 3 can be relied on is .. mmm ... "not in evidence".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c9da89cd-1206-0d63-4231-b86a427cda0b
* Version Independent ID: 22b11d5f-71fc-82ff-7b75-2f84cc2bf3aa
* Content: [WPF Platform Setup - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/platform/other/wpf)
* Content Source: [docs/xamarin-forms/platform/other/wpf.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/platform/other/wpf.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by Ciders** [comment]
Please update doc to remove note:
"Xamarin.Forms 4.7 includes support for WPF apps that run on .NET Core 3."
It does not appear to support .NET Core 3.
