### ISSUE TITLE
The Author and 

### ISSUE THREAD

**Issue by jvane1** [MicrosoftDocs/xamarin-docs#3134]
The following note seems to be outdated: 

Note

There are a number of NuGet packages with similar names. The correct package has these attributes:

Author(s): Frank A. Krueger
Id: sqlite-net-pcl
NuGet link: sqlite-net-pcl
Despite the package name, this NuGet package can be used in .NET Standard projects.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5ce30880-c4f0-78f7-1ee0-6507e378201e
* Version Independent ID: a6ad2818-c0d2-e3ef-1262-e143d49cc348
* Content: [Store data in a local SQLite.NET database - Xamarin](https://docs.microsoft.com/en-ca/xamarin/get-started/quickstarts/database)
* Content Source: [docs/get-started/quickstarts/database.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/get-started/quickstarts/database.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @jvane1 

How is outdated? That's the name of the NuGet Package.

**Comment by jvane1** [comment]
The author is no longer listed as Frank A. Krueger. This might throw user to download a different NuGet package.

**Comment by davidbritch** [comment]
Hi @jvane1 

Thanks for pointing this out. I've updated the docs in a PR that will go live later this week.
