### ISSUE TITLE
Mistyping a word

### ISSUE THREAD

**Issue by hosseinhadi** [MicrosoftDocs/xamarin-docs#3136]
There is a mistyping:
This makes is [THIS MAKES IT] possible for the sender of the intent to pass values to the broadcast receiver

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bf408f58-3116-0a60-d5f7-dbf4d0c02c9d
* Version Independent ID: aa2b5ea1-6a0c-77a4-6665-49c0505a18e4
* Content: [Broadcast Receivers in Xamarin.Android - Xamarin](https://docs.microsoft.com/en-us/xamarin/android/app-fundamentals/broadcast-receivers)
* Content Source: [docs/android/app-fundamentals/broadcast-receivers.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/android/app-fundamentals/broadcast-receivers.md)
* Product: **xamarin**
* Technology: **xamarin-android**
* GitHub Login: @davidortinau
* Microsoft Alias: **daortin**

**Comment by davidbritch** [comment]
Hi @hosseinhadi 

Thanks for pointing this out. I've fixed the doc in a PR that will go live later this week.
