### ISSUE TITLE
Can’t understand this section

### ISSUE THREAD

**Issue by Tommigun1980** [MicrosoftDocs/xamarin-docs#3138]
Please rewrite the section https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/collectionview/scrolling#control-scroll-position-when-new-items-are-added

I have read the different ItemsUpdatingScrollMode modes over and over and can’t seem to make head or tails of the descriptions.

It says things like "adjusts the scroll offset to keep the first visible item displayed when new items are added." — how does it "keep" the first item in view, what happens if the first item is not visible? Does visible mean scrolled to, or does it mean that it’s visible state is not hidden? What is the "first" visible item? The first visible in the list?  Makes no sense. The uppermost currently displayed item? First added item?

KeepScrollOffset says it calculates a relative offset. Is it before or after adding the items? Or does it merely mean that the view maintains its scroll position? If so please say so.

I don’t think docs should talk at such a low level, they should describe what the various features do on a higher level. Right now the option descriptions read as code, where functionality has to be deducted thereof. It should be the other way around, docs should explain things in a human readable form, and code can be consulted for inner workings if needed.

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6bd3b3b0-0147-f10d-76fe-15eecb8c25cf
* Version Independent ID: 586eee27-63ea-6cbf-b064-6e4a3dde7327
* Content: [Xamarin.Forms CollectionView Scrolling - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/collectionview/scrolling#control-scroll-position-when-new-items-are-added)
* Content Source: [docs/xamarin-forms/user-interface/collectionview/scrolling.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/collectionview/scrolling.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
This is fixed in a PR that will go live tomorrow.
