### ISSUE TITLE
"The TemplateBinding markup extension is an alternative to creating a ControlTemplate that uses the RelativeSource markup extension to set the BindingContext of the root element in the template to its templated parent."

### ISSUE THREAD

**Issue by Tommigun1980** [MicrosoftDocs/xamarin-docs#3143]
It is so wordy and once again explains some low level stuff without introducing the concepts properly. Please add examples, avoid sentences as "_The TemplateBinding markup extension is an alternative to creating a ControlTemplate that uses the RelativeSource markup extension to set the BindingContext of the root element in the template to its templated parent._" <-- I had to read that at least three times before I was able to digest it is really just saying "This is another alternative".

Please cut down on the words everywhere, explain the concepts cleanly, and add more examples. This is a huge problem with all Xamarin.Forms documentation.

Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a4b35f51-7abf-c8cc-2dfb-2cb20a0fc200
* Version Independent ID: f47aa11e-86c3-9387-e1f8-b6ce29fe5eb7
* Content: [Xamarin.Forms control templates - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/templates/control-template)
* Content Source: [docs/xamarin-forms/app-fundamentals/templates/control-template.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/app-fundamentals/templates/control-template.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @Tommigun1980 

Yes, TemplateBinding is just an alternative. But it's an alternative for that specific scenario. Not an alternative to RelativeSource bindings in general.

That doc is already example heavy - 68% of it is code.

What concepts aren't explained clearly in the doc, in your opinion?

**Comment by Tommigun1980** [comment]
Hi David.

It's just so hard to read. Almost all XF documents are like that, they make very simple concepts sound extremely complex. "The TemplateBinding markup extension is an alternative to creating a ControlTemplate that uses the RelativeSource markup extension to set the BindingContext of the root element in the template to its templated parent." is just word salad, and really just says "You can also do this:". The entire explanation refers to the previous section that is somehow condensed into the sentence.

Don't you think sentences like "The TemplateBinding markup extension is an alternative to creating a ControlTemplate that uses the RelativeSource markup extension to set the BindingContext of the root element in the template to its templated parent." are quite tough to comprehend?

Thanks.

**Comment by davidbritch** [comment]
Hi @Tommigun1980 

I agree that it's tough to comprehend.

**Comment by davidbritch** [comment]
I've fixed this in a PR that will go live early next week (the CI server is currently under high load).
