### ISSUE TITLE
Once again fails to convey the concepts and raises more questions than answers

### ISSUE THREAD

**Issue by Tommigun1980** [MicrosoftDocs/xamarin-docs#3144]
The "Set the font in XAML" section explains how to set up a font family. The "Use a custom font" section explains how to import a custom font. Now, the examples in "Use a custom font" are completely different than the ones in "Set the font in XAML". Are both required, or are they different flavours? My guess is that "Use a custom font" explains the new ExportFont annotation and it supersedes "Set the font in XAML", is this correct? In that case please update the documentation and don't just add to it. If you look for font issues on the Xamarin.Forms GitHub there's a ton of reports because nobody knows how to use it, because the documentation is always written in such a way that you are left guessing as to what should be done. Please do better on this front.

Shouldn't the entire "Set the font in XAML" section be removed, or at the very least shouldn't it be placed AFTER the "Use a custom font" with further elaboration that it's a legacy way. Human beings read from top to bottom and they will read the outdated section first, then the new way, and get extremely confused. This nonsense is wasting time on developers fronts and also Xamarin.Forms's devs time as there will be bug reports because people can't follow the documentation.

https://devblogs.microsoft.com/xamarin/embedded-fonts-xamarin-forms/ is an example that explains this in a concise manner.

Also, the "Set font info per platform" section begins with "Alternatively, the Device.RuntimePlatform property can be used to set different font names on each platform". Alternatively to what? It's the first time that topic is discussed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe0572c4-91be-fc86-d130-242db2bf470b
* Version Independent ID: 1238fdd7-c378-6d0d-654e-55656a70d386
* Content: [Fonts in Xamarin.Forms - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/text/fonts)
* Content Source: [docs/xamarin-forms/user-interface/text/fonts.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/text/fonts.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @Tommigun1980 

Yes, "Use a custom font" supersedes "Set the font in XAML". The issue here is that "use a custom font" requires Forms 4.5 or higher. Many users are still on older versions, and so "Set the font in XAML" is required. On top of that custom fonts didn't work very well when they were introduced, and so "Set the font in XAML" was still required as a fallback.

Going back to your overall point, I agree that this doc needs an overhaul. I'll add it to the backlog.

**Comment by Tommigun1980** [comment]
Hi David.

Why not say that in the docs then? It has two sections that explain completely different approaches. How would a user know that one is the old way and one the new way if, you know, the docs don't tell that?

**Comment by davidbritch** [comment]
Hi @Tommigun1980 

It's a result of the messy way custom fonts were introduced into Xamarin.Forms. I agree the doc needs fixing, and it will be.

**Comment by davidbritch** [comment]
I've just refreshed the doc, and it will be live soon.
