### ISSUE TITLE
There's over two year worth of issues here -- will they ever get fixed?

### ISSUE THREAD

**Issue by Tommigun1980** [MicrosoftDocs/xamarin-docs#3145]
Xamarin.Forms is harder to use than it needs to be due to bad and outdated documentation.
Just the reported bugs section contain over two years of open issues, and these are just the ones reported by users.
Will the Xamarin.Forms documentation ever be updated and the issues resolved? Is there even a point to reporting issues?

Mind you that because of the bad and outdated documentation people will report bugs unnecessarily and these open issues will then cross over to Xamarin bug reports.

Thanks.

**Comment by davidbritch** [comment]
Hi @Tommigun1980 

There are only 27 open issues in this repo for Xamarin.Forms docs. They will largely be dealt with.
