### ISSUE TITLE
Need clarification on ThemingDemo for clarification on adding ResourceDictionary with code behind file

### ISSUE THREAD

**Issue by ssteezens** [MicrosoftDocs/xamarin-docs#3146]
> A code behind file is required for each ResourceDictionary, which calls the InitializeComponent method. This is necessary so that a CLR object representing the chosen theme can be created at runtime.

Hello, i'm having an issue with this part of the themeing tutorial.  When attempting to create a code behind file for my resource dictionary I get the error `InitalizeComponent does not exist in the current context`.  

Is there some sort of process for making a resource dictionary with a code behind file that I'm missing?

This is my resource dictionary
```
<ResourceDictionary xmlns="http://xamarin.com/schemas/2014/forms"
                    xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
                    x:Class="SeparationTrainer.DarkTheme">
    <Color x:Key="BackgroundColor">#000000</Color>
    <Color x:Key="SurfaceColor">#121212</Color>
    <Color x:Key="PrimaryColor">#1F1B24</Color>
    <Color x:Key="SecondaryColor">#0097a7</Color>

    <Color x:Key="PrimaryLightColor">#9061e2</Color>
    <Color x:Key="PrimaryDarkColor">#27057f</Color>
    <Color x:Key="PrimaryTextColor">White</Color>
    <Color x:Key="SecondaryTextColor">White</Color>
    <Color x:Key="TertiaryTextColor">WhiteSmoke</Color>
    <Color x:Key="TransparentColor">Transparent</Color>

    <Color x:Key="OnBackgroundColor">White</Color>
    <Color x:Key="OnSurfaceColor">White</Color>
    <Color x:Key="OnPrimaryColor">White</Color>
    <Color x:Key="OnSecondaryColor">White</Color>

    <Color x:Key="Primary">#6200EE</Color>
    <Color x:Key="PrimaryVariant">#3700B3</Color>
    <Color x:Key="Secondary">#03DAC6</Color>
    <Color x:Key="SecondaryVariant">#018786</Color>
    <Color x:Key="Background">#FFFFFF</Color>
    <Color x:Key="Surface">#FFFFFF</Color>
    <Color x:Key="Error">#B00020</Color>

    <Color x:Key="OnPrimary">#FFFFFF</Color>
    <Color x:Key="OnSecondary">#000000</Color>
    <Color x:Key="OnBackground">#000000</Color>
    <Color x:Key="OnSurface">#000000</Color>
    <Color x:Key="OnError">#FFFFFF</Color>

</ResourceDictionary>
```
And my code behind
```
using Xamarin.Forms;

namespace SeparationTrainer.Themes
{
    public partial class DarkTheme : ResourceDictionary
    {
        public DarkTheme()
        {
            InitializeComponent();
        }
    }
}

```

I am however able to run the ThemingDemo without issue so I'm thinking there must be something I'm doing wrong.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3f353ff4-2d18-218c-f0d5-b3110e476c4d
* Version Independent ID: a1cec8f2-969c-23c5-a252-b417afcacff6
* Content: [Theme a Xamarin.Forms Application - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/theming/theming)
* Content Source: [docs/xamarin-forms/user-interface/theming/theming.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/theming/theming.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @ssteezens 

You need to make sure that your XAML and code-behind are in the same namespace. Your XAML class is `SeparationTrainer.DarkTheme`, while your code-behind class is `SeparationTrainer.Themes.DarkTheme`.

**Comment by ssteezens** [comment]
Ah! I knew I must have been doing something wrong, serves me right for working before my morning coffee.  It would be nice though if ResourceDictionary was an item you could add directly from Add -> New Item in visual studio

Thanks a lot David.

**Comment by davidbritch** [comment]
Agreed about the Add > New Item!
