### ISSUE TITLE
UWP specific custom font setup requirements

### ISSUE THREAD

**Issue by chowarth** [MicrosoftDocs/xamarin-docs#3148]
[Enter feedback here]
UWP, using the steps outlined, results in any custom font being excluded from release builds. It would be good to add directions that you also need pass the assembly that the embedded font is in to the `Xamarin.Forms.Init`, see [issue comment here](https://github.com/xamarin/Xamarin.Forms/issues/12404#issuecomment-714500451)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe0572c4-91be-fc86-d130-242db2bf470b
* Version Independent ID: 1238fdd7-c378-6d0d-654e-55656a70d386
* Content: [Fonts in Xamarin.Forms - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/text/fonts)
* Content Source: [docs/xamarin-forms/user-interface/text/fonts.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/text/fonts.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @chowarth 

Thanks for pointing this out. I've just updated the doc (gave it a complete refresh, and included the UWP setup requirements). It'll be live soon.

**Comment by BillyMartin1964** [comment]
So... are  you saying that Fontawesome OTF fonticons won't work in the release build at all?

**Comment by chowarth** [comment]
> So... are you saying that Fontawesome OTF fonticons won't work in the release build at all?

@BillyMartin1964 though I've not specifically used FontAwesome it should work fine. There was just some missing information for UWP that requires some extra setup, without which the fonts would be excluded from release builds.

**Comment by BillyMartin1964** [comment]
@chowarth , Would love to know if you find out. I had to put FA down in the UWP project or I would just get the rectangles in release builds.
