### ISSUE TITLE
Dispatcher doesn't work

### ISSUE THREAD

**Issue by benOnside** [MicrosoftDocs/xamarin-docs#3150]
I downloaded the template, copy-pasted my NotificationHubName and FullAccessConnectionString into the dispatcher.
I correctly set up the app for receiving, since I was able to receive test-send messages from the azure website.

But when I run the dispatcher, on pressing space no push notification arrives and I get this error:

Failed to send template notification: The messaging entity ' No service is hosted at the specified address..TrackingId:29e7ad77-62b5-4f37-9e19-4cd9cc115482_G3,TimeStamp:11/3/2020 11:04:42 PM' could not be found.
Sent messages to 1 tags.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 92f390d9-cbd0-ab8c-6c8c-49df76d1b8e0
* Version Independent ID: 15739c2f-afbb-c21d-b96f-fabe7060e410
* Content: [Send and receive push notifications with Azure Notification Hubs and Xamarin.Forms - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/data-cloud/azure-services/azure-notification-hub)
* Content Source: [docs/xamarin-forms/data-cloud/azure-services/azure-notification-hub.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/data-cloud/azure-services/azure-notification-hub.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @profexorgeek
* Microsoft Alias: **jusjohns**

**Comment by benOnside** [comment]
I found out what the issue is. I had a space in my NotificationHubName. It's a painful error though.

**Comment by davidbritch** [comment]
Glad you were able to unblock yourself @benOnside
