### ISSUE TITLE
Passing parameters with backwards navigation syntax

### ISSUE THREAD

**Issue by stephenhauck** [MicrosoftDocs/xamarin-docs#3153]
Under "Backwards Navigation" you mention ...
"await Shell.Current.GoToAsync("..");"

To pass a parameter it needs to be formed like such ....
"await Shell.Current.GoToAsync($"..?parameterToPassBack={parameterValueToPassBack}");"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b6efe82d-a8b9-82a8-7d38-98f2f8d5e682
* Version Independent ID: 28d7341e-ae6e-6321-6550-d27ae6b256d2
* Content: [Xamarin.Forms Shell Navigation - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/shell/navigation)
* Content Source: [docs/xamarin-forms/app-fundamentals/shell/navigation.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/app-fundamentals/shell/navigation.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @stephenhauck 

Thanks for pointing this out. I've added it to the doc in a PR that will go live later this week.
