### ISSUE TITLE
Audio out of sync

### ISSUE THREAD

**Issue by AdamMarciniec** [MicrosoftDocs/xamarin-docs#3154]
The audio for this video is out of sync.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a415c6da-557c-7556-4461-40feeea9b119
* Version Independent ID: 326f5d03-88d0-4fad-946c-c178bb3bf976
* Content: [Xamarin.Essentials: Version Tracking - Xamarin](https://docs.microsoft.com/en-us/xamarin/essentials/version-tracking)
* Content Source: [docs/essentials/version-tracking.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/essentials/version-tracking.md)
* Product: **xamarin**
* Technology: **xamarin-essentials**
* GitHub Login: @jamesmontemagno
* Microsoft Alias: **jamont**

**Comment by jamesmontemagno** [comment]
Thanks for the feedback I will take a look with the team, however it has been a while since we recorded it.
