### ISSUE TITLE
GeolocationRequest documentation is minimal

### ISSUE THREAD

**Issue by LordBenjamin** [MicrosoftDocs/xamarin-docs#3156]
The `GeolocationRequest ` documentation looks like it needs some love.

For example, consider `GeolocationRequest(GeolocationAccuracy accuracy, TimeSpan timeout)` constructor.

This page describes the constructor as:

> Creates a new instance of GeolocationRequest with the specified accuracy and timeout.

But IMHO this is not enough information to understand how to use it.

What happens when the timeout is reached? Can I expect a null response? Should I be prepared to handle an exception? 

What happens if I pass `TimeSpan.Zero` - should I expect this to act as an infinite timeout or to return instantly (possibly with `null` if this is not enough time to obtain a location fix)?

This level of detail is consistent throughout the various pages related to `GeolocationRequest  members that I checked. Is this on a roadmap to be updated at some point?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ae1a280e-abae-e1cd-b61a-6c5d09e887ae
* Version Independent ID: 2e68b5e5-637d-dd49-9cf4-562652eda0c7
* Content: [GeolocationRequest Constructor (Xamarin.Essentials)](https://docs.microsoft.com/en-us/dotnet/api/xamarin.essentials.geolocationrequest.-ctor?view=xamarin-essentials#Xamarin_Essentials_GeolocationRequest__ctor_Xamarin_Essentials_GeolocationAccuracy_System_TimeSpan_)
* Content Source: [docs/en/Xamarin.Essentials/GeolocationRequest.xml](https://github.com/xamarin/Essentials/blob/live/docs/en/Xamarin.Essentials/GeolocationRequest.xml)
* Product: **xamarin**
* Technology: **xamarin-essentials**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by davidbritch** [comment]
[Microsoft support for Xamarin](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin) will end on May 1, 2024 for all Xamarin SDKs including Xamarin.Forms. In preparation for this, all issues and PRs in this repository are being closed.

.NET MAUI is the replacement for Xamarin.Forms, and it's documentation can be found [here](https://learn.microsoft.com/dotnet/maui/?view=net-maui-8.0).
