### ISSUE TITLE
Error to render a bound Path Data in a CollectionView

### ISSUE THREAD

**Issue by eli191** [MicrosoftDocs/xamarin-docs#3158]
Hi, 

I get this error when I have a `Path` in my `DataTemplate` and want to bind the `Data` to a model. The paths are not displayed.

If I remove the binding to set the` Path.Data` statically in the XAML, then it is working.

```
 <CollectionView
                IsGrouped="true"
                SelectionMode="Single"
                ItemsLayout="VerticalGrid, 3">
                <CollectionView.GroupHeaderTemplate>
                    <DataTemplate>
                        <Label
                            Text="{Binding GroupName}"
                            BackgroundColor="LightGray"
                            FontSize="Large"
                            FontAttributes="Bold" />
                    </DataTemplate>
                </CollectionView.GroupHeaderTemplate>
                <CollectionView.ItemTemplate>
                    <DataTemplate>
                        <Grid
                            RowDefinitions="100,50">
                            <Label
                                Text="{Binding Name}"
                                TextColor="White" />
                            <Path
                                BackgroundColor="Red"
                                Data="{Binding PathData}"
                                Stroke="Black"
                                StrokeThickness="5"
                                Fill="Green"
                                Aspect="Uniform"
                                Scale=".8" />
                        </Grid>
                    </DataTemplate>
                </CollectionView.ItemTemplate>
            </CollectionView>
```

```
[CollectionView] An attempt to prepare a layout while a prepareLayout call was already in progress (i.e. reentrant call) has been ignored. Please file a bug. UICollectionView instance is (<UICollectionView: 0x7f9c5a318c00; frame = (0 0; 414 736); clipsToBounds = YES; autoresize = W+H; gestureRecognizers = <NSArray: 0x600002d1dd10>; layer = <CALayer: 0x6000026654c0>; contentOffset: {0, 0}; contentSize: {414, 0}; adjustedContentInset: {0, 0, 0, 0}; layout: <Xamarin_Forms_Platform_iOS_GridViewLayout: 0x7f9c5477d830>; dataSource: <Xamarin_Forms_Platform_iOS_GroupableItemsViewController_1: 0x7f9c5477e0a0>>)
[Unknown process name] Error: this application, or a library it uses, has passed an invalid numeric value (NaN, or not-a-number) to CoreGraphics API and this value is being ignored. Please fix this problem.
[Unknown process name] If you want to see the backtrace, please set CG_NUMERICS_SHOW_BACKTRACE environmental variable.
```

Is there a workaround to display a `Path` in a `CollectionView` which `Data` is bound to a ViewModel property?

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 12370c4e-0935-d43a-7d28-32a10a30074f
* Version Independent ID: bb1eccf7-c1b8-25b1-5325-3b37a9b1bd94
* Content: [Xamarin.Forms CollectionView Data - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/collectionview/populate-data)
* Content Source: [docs/xamarin-forms/user-interface/collectionview/populate-data.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/collectionview/populate-data.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by eli191** [comment]
Hi,

I found a way out.

It seems that the `Path.Data` syntax is allowed in XAML only. 

I simply had to use a conversion like this
```
Geometry PathData = (Geometry)new PathGeometryConverter().ConvertFromInvariantString("M13.908992,16.207977 L32.000049,16.207977 32.000049,31.999985 13.908992,30.109983Z");
```
Then you can bind the `Path.Data` to this `PathData` property.

Only wished the documentation would just add a line on that conversion instead of just stating it is only available in XAML [here](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/shapes/path#create-a-path-with-path-markup-syntax)


Thanks for the great work, and sorry to have put that in the CollectionView issues.

**Comment by davidbritch** [comment]
Re-opening so I can use the issue as a work item to add your finding to the doc.

Thanks for letting me know about this.

**Comment by davidbritch** [comment]
I've updated the doc in a PR that will go live over the next hour.
