### ISSUE TITLE
XAML Hot Reload for Xamarin.Forms incorrect instructions

### ISSUE THREAD

**Issue by DaveBach** [MicrosoftDocs/xamarin-docs#3160]
Under the section titled "Enable XAML Hot Reload for Xamarin.Forms"

The sentence reading "On Windows, check the Enable Xamarin Hot Reload checkbox at Tools > Options > Xamarin > Hot Reload."

should read "On Windows, check the Enable Xamarin Hot Reload checkbox at Tools > Options > Debugging> Hot Reload." 

AND further explanation of the different options available.

**Comment by davidbritch** [comment]
Hi @DaveBach 

This is fixed in a PR that's going live now.
