### ISSUE TITLE
UWP is now supported

### ISSUE THREAD

**Issue by Avacee** [MicrosoftDocs/xamarin-docs#3161]
The page states "Other Xamarin.Forms targets, such as UWP and macOS, are not yet supported" and provides a link to track implementation status. As of Visual Studio 16.8 UWP is supported and the link shows this as "Completed - Released".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b74184fd-ca8a-11fa-ed37-91235fc59401
* Version Independent ID: 87f197b8-20c6-4825-18e4-86562bb2523c
* Content: [XAML Hot Reload for Xamarin.Forms - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/xaml/hot-reload)
* Content Source: [docs/xamarin-forms/xaml/hot-reload.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/xaml/hot-reload.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @maddyleger1
* Microsoft Alias: **maleger**

**Comment by davidbritch** [comment]
Hi @Avacee 

Afraid the doc is correct. While Hot Reload on UWP is supported, it's currently not supported for Xamarin.Forms UWP projects. However, I believe it's coming in Visual Studio 16.9.
