### ISSUE TITLE
'Permissions' does not contain a definition for 'ShouldShowRationale'

### ISSUE THREAD

**Issue by xshiiiidev** [MicrosoftDocs/xamarin-docs#3162]
### Doc issue description

I just copied the [documention code](https://docs.microsoft.com/en-us/xamarin/essentials/permissions?tabs=android#general-usage) for General usage of the permissions

```
public async Task<PermissionStatus> CheckAndRequestLocationPermission()
{
    var status = await Permissions.CheckStatusAsync<Permissions.LocationWhenInUse>();
    
    if (status == PermissionStatus.Granted)
        return status;
        
    
    if (status == PermissionStatus.Denied && DeviceInfo.Platform == DevicePlatform.iOS)
    {
        // Prompt the user to turn on in settings
        // On iOS once a permission has been denied it may not be requested again from the application
        return status;
    }
    
    if (Permissions.ShouldShowRationale<Permissions.LocationWhenInUse>())
    {
        // Prompt the user with additional information as to why the permission is needed
    }   

    status = await Permissions.RequestAsync<Permissions.LocationWhenInUse>();

    return status;
}
```

The problem is I can't build my code because I got an error in this part of code

![image](https://user-images.githubusercontent.com/19402130/99180996-4a33fa80-2766-11eb-959d-5e611c5318e8.png)

**Comment by DonGlover** [comment]
Per James Montemango in https://docs.microsoft.com/en-us/answers/questions/174018/permissionsshouldshowrationale-doesn39t-exist.html
It requires V 1.6
The topic should note the minimum version requirement.

**Comment by jamesmontemagno** [comment]
A PR was mad to update this
