### ISSUE TITLE
What is the actual CURRENT guidance for shrinking the APK?

### ISSUE THREAD

**Issue by DonGlover** [MicrosoftDocs/xamarin-docs#3163]
I am following the steps to prepare for publishing my app found here
https://docs.microsoft.com/en-us/xamarin/android/deploy-test/release-prep/proguard

I am at the shrink the APK step and it suggests using proguard. I went to this document for instructions:

https://docs.microsoft.com/en-us/xamarin/android/deploy-test/release-prep/proguard

When I compile with the dex compiler setting, I get the following:
2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(556,2): error XA1011: Using ProGuard with the D8 DEX compiler is no longer supported. Please set the code shrinker to r8 in the Visual Studio project property pages or edit the project file in a text editor and set the AndroidLinkTool MSBuild property to r8.
========== Rebuild All: 1 succeeded, 1 failed, 1 skipped ==========

If I set the dex compiler to dx, I get the following:

C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(560,2): warning XA1023: Using the DX DEX Compiler is deprecated. Please update $(AndroidDexTool) to d8.

My question(s): Is proguard not the way to go these days and the docs are out of date?

re: What is the actual CURRENT guidance for this?

**Comment by davidbritch** [comment]
[Microsoft support for Xamarin](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin) will end on May 1, 2024 for all Xamarin SDKs including Xamarin.Forms. In preparation for this, all issues and PRs in this repository are being closed.

.NET MAUI is the replacement for Xamarin.Forms, and it's documentation can be found [here](https://learn.microsoft.com/dotnet/maui/?view=net-maui-8.0).
