### ISSUE TITLE
PhoneDialer.Open wrong Exception for invalid number

### ISSUE THREAD

**Issue by DarkIrata** [MicrosoftDocs/xamarin-docs#3165]
PhoneDialer.Open throws 
`System.NullReferenceException: 'Object reference not set to an instance of an object.'`
instead of 
`ArgumentNullException`
if the given number is invalid.

Tested with number: `01A2312131213`
Used Version;
```
Assembly Xamarin.Essentials, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
// ......\.nuget\packages\xamarin.essentials\1.5.2\lib\netstandard2.0\Xamarin.Essentials.dll
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d7dbc2bf-5c2e-8d23-fe18-4f35f14f2dac
* Version Independent ID: 9293dec4-326a-a2bd-35af-9c2652b1cb2c
* Content: [PhoneDialer.Open(String) Method (Xamarin.Essentials)](https://docs.microsoft.com/en-us/dotnet/api/xamarin.essentials.phonedialer.open?view=xamarin-essentials)
* Content Source: [docs/en/Xamarin.Essentials/PhoneDialer.xml](https://github.com/xamarin/Essentials/blob/live/docs/en/Xamarin.Essentials/PhoneDialer.xml)
* Product: **xamarin**
* Technology: **xamarin-essentials**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by davidbritch** [comment]
[Microsoft support for Xamarin](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin) will end on May 1, 2024 for all Xamarin SDKs including Xamarin.Forms. In preparation for this, all issues and PRs in this repository are being closed.

.NET MAUI is the replacement for Xamarin.Forms, and it's documentation can be found [here](https://learn.microsoft.com/dotnet/maui/?view=net-maui-8.0).
