### ISSUE TITLE
Media Picker Options

### ISSUE THREAD

**Issue by ccarvey** [MicrosoftDocs/xamarin-docs#3167]
The options seem to be MVP level. Are enhancements planned to set the directory, filename, photo size and other options?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e4b43ab7-fd40-ba56-c9ab-5de2eb1aad7f
* Version Independent ID: 6c9c7c48-4401-cb25-5cda-637718a22961
* Content: [Xamarin.Essentials: Media Picker - Xamarin](https://docs.microsoft.com/en-us/xamarin/essentials/media-picker?tabs=ios)
* Content Source: [docs/essentials/media-picker.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/essentials/media-picker.md)
* Product: **xamarin**
* Technology: **xamarin-essentials**
* GitHub Login: @jamesmontemagno
* Microsoft Alias: **jamont**

**Comment by jamesmontemagno** [comment]
Please submit feature requests over at https://www.github.com/xamarin/essentials
