### ISSUE TITLE
font-family and Custom Fonts

### ISSUE THREAD

**Issue by gjkhw** [MicrosoftDocs/xamarin-docs#317]
It's not clear from the specification of Xamarin.Forms CSS how one would encode font-family for custom fonts, given that Custom Fonts have different encodings on different platforms (https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/text/fonts#using-a-custom-font)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7a410a97-17d3-aff7-c875-ee9291658957
* Version Independent ID: f415dc53-c941-b0e5-5823-9bafa53f0d9a
* Content: [Styling Xamarin.Forms Apps using Cascading Style Sheets - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/styles/css/)
* Content Source: [docs/xamarin-forms/user-interface/styles/css/index.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/styles/css/index.md)
* Service: **unspecified**
* Product: **xamarin**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @gjkhw 

It's not currently possible to use `OnPlatform<>` with CSS, so the only other way to handle your scenario would be to detect the platform at runtime and then load a particular CSS file that references the font for the platform. Alternatively, it *may* be possible to load a CSS file from a platform project.
