### ISSUE TITLE
Hello, I need help

### ISSUE THREAD

**Issue by tuilathinh2017** [MicrosoftDocs/xamarin-docs#3171]
[Nhập phản hồi vào đây]
![image](https://user-images.githubusercontent.com/70591678/99926480-76f29e00-2d74-11eb-87a2-a3cf766cc1e2.png)
 I did not find Hot Reload in Xamarin

---
#### Chi tiết tài liệu

⚠ *Không chỉnh sửa phần này. Điều này là bắt buộc cho docs.microsoft.com ➟ Vấn đề khi liên kết GitHub.*

* ID: b74184fd-ca8a-11fa-ed37-91235fc59401
* Version Independent ID: 87f197b8-20c6-4825-18e4-86562bb2523c
* Content: [XAML Hot Reload for Xamarin.Forms - Xamarin](https://docs.microsoft.com/vi-vn/xamarin/xamarin-forms/xaml/hot-reload#feedback)
* Content Source: [docs/xamarin-forms/xaml/hot-reload.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/xaml/hot-reload.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @maddyleger1
* Microsoft Alias: **maleger**

**Comment by davidbritch** [comment]
Hi @tuilathinh2017 

You can find the setting at Tools > Options > Debugging > Hot Reload > Enable XAML Hot Reload > Android and iOS (Xamarin.Forms).
