### ISSUE TITLE
Incorrect description

### ISSUE THREAD

**Issue by viktorszekeress** [MicrosoftDocs/xamarin-docs#3173]
The description says:
"FontAttributes, of type FontAttributes, which is an enumeration with three members: None, **Build**, and Italic."

I believe it should be:
FontAttributes, of type FontAttributes, which is an enumeration with three members: None, **Bold**, and Italic.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe0572c4-91be-fc86-d130-242db2bf470b
* Version Independent ID: 1238fdd7-c378-6d0d-654e-55656a70d386
* Content: [Fonts in Xamarin.Forms - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/text/fonts)
* Content Source: [docs/xamarin-forms/user-interface/text/fonts.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/text/fonts.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @viktorszekeress 

Thanks for pointing this out. I've fixed it in a PR that will go live by the end of the week.
