### ISSUE TITLE
The General Usage code snippet appears to be out of date.

### ISSUE THREAD

**Issue by DonGlover** [MicrosoftDocs/xamarin-docs#3174]
if (Permissions.ShouldShowRationale<Permissions.LocationWhenInUse>())

Permissions does not contain a method ShouldShowRationale.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5b055baf-759f-ed5a-d99d-ae9fed491588
* Version Independent ID: 76f823ff-dd9a-1bb6-8e71-29248ffca0c1
* Content: [Xamarin.Essentials: Permissions - Xamarin](https://docs.microsoft.com/en-us/xamarin/essentials/permissions?context=xamarin%2Fandroid&tabs=android)
* Content Source: [docs/essentials/permissions.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/essentials/permissions.md)
* Product: **xamarin**
* Technology: **xamarin-essentials**
* GitHub Login: @jamesmontemagno
* Microsoft Alias: **jamont**

**Comment by DonGlover** [comment]
Per James Montemango in https://docs.microsoft.com/en-us/answers/questions/174018/permissionsshouldshowrationale-doesn39t-exist.html
It requires V 1.6 
The topic should note the minimum version requirment.

**Comment by DonGlover** [comment]
Fixed by PR https://github.com/MicrosoftDocs/xamarin-docs/pull/3175

**Comment by davidbritch** [comment]
Closing due to the PR being merged.
