### ISSUE TITLE
Example of scheduled notification

### ISSUE THREAD

**Issue by maxkoshevoi** [MicrosoftDocs/xamarin-docs#3176]
Could you please add an example of how to actually do notifications for reminders or calendar events (as mentioned at the top of the article).

In the article itself you are showing only the example of how to create instant notification (you push a button => notification appears), but don't show an example of scheduled notification. And they cannot be implemented in the same way.

For the last couple of years Android discourages developers to run their applications in the background if user is not interacting with them (like with music players or navigation apps), so creating a background thread (service), waiting it's time to push notification, and then do it is not an option.

Could you please add an example of up-to-date way to schedule a notification?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e1d97b06-848b-73b1-0330-f57662b5c09a
* Version Independent ID: 9bb5fb04-4426-6b7a-4332-3ce86ff21b76
* Content: [Xamarin.Forms local notifications - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/local-notifications)
* Content Source: [docs/xamarin-forms/app-fundamentals/local-notifications.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/app-fundamentals/local-notifications.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @profexorgeek
* Microsoft Alias: **jusjohns**

**Comment by davidbritch** [comment]
Hi @maxkoshevoi 

I've just updated the doc and sample to include scheduled local notifications, in a PR that will go live tomorrow.

It's problematic on Android as the only way to schedule a local notification for an exact time is to use the `AlarmManager` class to schedule notifications as alarms. However, any scheduled notifications are lost when the device reboots. This can be handled by re-scheduling alarms when the device restarts, which ensures the `AlarmManager` continues its alarms without the user having to manually restart them. However, it's obviously more complicated logic. This is why some people just opt to use push notifications.
