### ISSUE TITLE
RadioButton page needs to be updated for the change from Label to Content

### ISSUE THREAD

**Issue by AzuxirenLeadGuy** [MicrosoftDocs/xamarin-docs#3178]
The RadioButton had a bug in v4.8.0 (which is now resolved) regarding the "Text" property. It has now be changed/renamed into "Content", but it is not mentioned in the docs.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a688fe91-33ad-efea-aa29-d56b3c11b42a
* Version Independent ID: c0e81ed5-0eb5-a8cc-9eb6-7baf7e464878
* Content: [Xamarin.Forms RadioButton - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/radiobutton)
* Content Source: [docs/xamarin-forms/user-interface/radiobutton.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/radiobutton.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @AzuxirenLeadGuy 

Has Text changed to Content in 4.8? I know it's changed in 5.0, but will have to investigate to see if it was back ported to 4.8.

**Comment by AzuxirenLeadGuy** [comment]
> Has Text changed to Content in 4.8?

@davidbritch  I had a xamarin project in version 4.8.0.1687 that had the property as "Text" in the xaml file compiled successfully, but the bug in Android persisted and was not visible.

On updating to 5.0.0.1487-pre1, the property changed to "Content" and the bug in Android was resolved as well, provided `Forms.SetFlags("Radiobutton_Experimental")` was used. I hope that's what you were asking...

**Comment by davidbritch** [comment]
Hi @AzuxirenLeadGuy 

I checked the `RadioButton` source code. It's still `Text` in 4.8 - the current stable release. It changes to `Content` in 5.0, which is still a pre-release. The published doc will be updated (and already has been, in a branch) when 5.0 moves to a stable release.
