### ISSUE TITLE
Would be nice to have Geofence

### ISSUE THREAD

**Issue by yshteinm** [MicrosoftDocs/xamarin-docs#318]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c420b152-7303-918a-dbc8-8d1e539c64ec
* Version Independent ID: fe85e24f-c3fc-3763-b1db-6b360fb08067
* Content: [Xamarin.Essentials - Xamarin](https://docs.microsoft.com/en-us/xamarin/essentials/)
* Content Source: [docs/essentials/index.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/essentials/index.md)
* Service: **unspecified**
* Product: **xamarin**
* GitHub Login: @jamesmontemagno
* Microsoft Alias: **jamont**

**Comment by conceptdev** [comment]
This has already been added to [GitHub](https://github.com/xamarin/Essentials/issues/270).

**Comment by yshteinm** [comment]
Where? I see geolocation and geocoding but not geofence
