### ISSUE TITLE
Hot Reload is not in the specified location

### ISSUE THREAD

**Issue by NickVerys** [MicrosoftDocs/xamarin-docs#3185]
Microsoft Visual Studio Community 2019 (Windows)
Version 16.8.2

Hot Reload options are not in `Tools > Options > Xamarin` section.

They are in `Tools > Options > Debugging > Hot Reload`

This created quite a time sink to determine how to turn on Hot Reload for Xamarin Forms.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b74184fd-ca8a-11fa-ed37-91235fc59401
* Version Independent ID: 87f197b8-20c6-4825-18e4-86562bb2523c
* Content: [XAML Hot Reload for Xamarin.Forms - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/xaml/hot-reload)
* Content Source: [docs/xamarin-forms/xaml/hot-reload.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/xaml/hot-reload.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @maddyleger1
* Microsoft Alias: **maleger**

**Comment by davidbritch** [comment]
Hi @NickVerys 

This is fixed in a PR that's going live now.
