### ISSUE TITLE
small bug in android version

### ISSUE THREAD

**Issue by ish-1313** [MicrosoftDocs/xamarin-docs#3186]
in this code AndroidNotificationManager.Initialize() never get called , so AndroidNotificationManager.Instance= null , 
so AlarmHandler.OnReceive throws exception 

sample may be altered in three (or more ) possible ways

1. call Initialize from constructor
2. call Initialize from shared code before first use 
3. change the code below to call Initialize(), not CreateNotificationChannel ()

```public void SendNotification(string title, string message, DateTime? notifyTime = null)
        {
            if (!channelInitialized)
            {
                CreateNotificationChannel();
            }```


or may be i missed something, because i didn't use shared code. just read it through ;)
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e1d97b06-848b-73b1-0330-f57662b5c09a
* Version Independent ID: 9bb5fb04-4426-6b7a-4332-3ce86ff21b76
* Content: [Xamarin.Forms local notifications - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/local-notifications#create-a-cross-platform-interface)
* Content Source: [docs/xamarin-forms/app-fundamentals/local-notifications.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/app-fundamentals/local-notifications.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @profexorgeek
* Microsoft Alias: **jusjohns**

**Comment by davidbritch** [comment]
Hi @ish-1313 

You missed something - https://github.com/xamarin/xamarin-forms-samples/blob/c595c5e84dfafd95bb96e0fad6d26e680800d188/LocalNotifications/LocalNotifications/LocalNotifications/App.xaml.cs#L12

:)

**Comment by ish-1313** [comment]
> 
> 
> Hi @ish-1313
> 
> You missed something - https://github.com/xamarin/xamarin-forms-samples/blob/c595c5e84dfafd95bb96e0fad6d26e680800d188/LocalNotifications/LocalNotifications/LocalNotifications/App.xaml.cs#L12
> 
> :)

well, didn't open sample code for that. ;)

**Comment by ish-1313** [comment]
by the way. sample code (on android) is not working if application is in killed state (app crashes receiving broadcast from alarmanager)
few lines of code in documentation and sample will save lot of time ;)

in OnReceive 

```
               cNotificationManager nmanager = cNotificationManager.Instance ?? new cNotificationManager();
                nmanager.Show(title, message, eventId);
```

ctor: 
public cNotificationManager() => Initialize(); 

cNotificationManager in your code is AndroidNotificationManager

**Comment by davidbritch** [comment]
Hi @ish-1313 

Thanks for this. I'll get it into the sample/doc either this week or next.

**Comment by ish-1313** [comment]
> 
> 
> Hi @ish-1313
> 
> Thanks for this. I'll get it into the sample/doc either this week or next.

you welcome 👍 
to be it more complete, you may also with to add

Android side
manifest 
`<uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED" />`

```
    public void DeleteNotification(int eventId)
        {
            Intent intent = new Intent(AndroidApp.Context, typeof(AlarmHandler));
            PendingIntent pendingIntent = PendingIntent.GetBroadcast(AndroidApp.Context, eventId, intent, PendingIntentFlags.CancelCurrent);
            AlarmManager alarmManager = AndroidApp.Context.GetSystemService(Context.AlarmService) as AlarmManager;
            alarmManager.Cancel(pendingIntent);
        }

...
    [BroadcastReceiver(Enabled = true, Label = "Reboot complete receiver")]
    [IntentFilter(new[] { Android.Content.Intent.ActionBootCompleted })]
    public class myBootReceiver : BroadcastReceiver
    {
        public override void OnReceive(Context context, Intent intent)
        {
            if (intent.Action == "android.intent.action.BOOT_COMPLETED")
            {
              // quick code to recreate alarms goes here 
            }
        }
   }
```
interface 
`void DeleteNotification(int eventid);`

i am using database id for alarm id when creating , so it is int;

your sample and docs very useful.

they will be perfect if they mention 
adb commands
dumpsys alarm | grep -i part-of-your-package_name to check alarms 
adb root  - to allow next command in adb shell
am broadcast -a android.intent.action.BOOT_COMPLETED -p package_name - to debug boot_completed receiver

:) 
thank you

**Comment by ish-1313** [comment]
Hi @davidbritch , 
IOS part is also bit different at least with current  IOS

this is deprecated and shows nothing 
UNNotificationPresentationOptions.Alert

WillPresentNotification get called only if is in foreground state, so end up with the code below

```
public class cNotificationReceiver : UNUserNotificationCenterDelegate
    {
        // called if app is in foreground. notify user and ask before switching to event 
        async public override void WillPresentNotification(UNUserNotificationCenter center, UNNotification notification, Action<UNNotificationPresentationOptions> completionHandler)
        {
            var choice = await cStdMessage.YesNoMsg(((App)App.Current).MainPage, "Notification received", $"Do you want to open event now?\n{notification.Request.Content.Body}");
            if (choice) ProcessNotification(notification);

            completionHandler(UNNotificationPresentationOptions.None);
        }

        // called if app is in background or killed state. 
        public override void DidReceiveNotificationResponse(UNUserNotificationCenter center, UNNotificationResponse response, Action completionHandler)
        {
            if (response.IsDefaultAction) ProcessNotification(response.Notification);

            completionHandler();
        }

        void ProcessNotification(UNNotification notification)
        {
            string title = notification.Request.Content.Title;
            string message = notification.Request.Content.Body;
            if (!int.TryParse(notification.Request.Identifier, out int eventId)) eventId = -1;
            DependencyService.Get<INotificationManager>().ReceiveNotification(title, message, eventId);
        }
    }
```

**Comment by ish-1313** [comment]
@davidbritch , and one more thing.. (don't know should it be pointed in docs/samples )
notification channel not supported below api 26, so this code crashes (well, after release ;))

ends up with 
```
    void CreateNotificationChannel()
        {
            manager = (NotificationManager)AndroidApp.Context.GetSystemService(AndroidApp.NotificationService);
            if (Build.VERSION.SdkInt >= Android.OS.BuildVersionCodes.O )
            {
                var channelNameJava = new Java.Lang.String(channelName);

                var channel = new NotificationChannel(channelId, channelNameJava, NotificationImportance.Default)
                {
                    Description = channelDescription
                };
                manager.CreateNotificationChannel(channel);
            }
            channelInitialized = true;
        }```

**Comment by davidbritch** [comment]
Re-opening this so it doesn't get forgotten about.
