### ISSUE TITLE
CarouselView randomly does not center items 

### ISSUE THREAD

**Issue by eli191** [MicrosoftDocs/xamarin-docs#3188]
Hi,

In iOS (not tested in Android), my `CarouselView` does not horizontally center some items in such a way that those items are not entirely visible, when I set `HorizontalOptions="CenterAndExpand"`.
If I set `HorizontalOptions="FillAndExpand"` then it works as expected (items are entered correctly).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f449be86-fbc4-fce9-e347-35b358a3199c
* Version Independent ID: 1254578d-c4d8-6018-e850-f53ece69903b
* Content: [Xamarin.Forms CarouselView Layout - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/carouselview/layout)
* Content Source: [docs/xamarin-forms/user-interface/carouselview/layout.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/carouselview/layout.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @eli191 

This sounds like a product bug, and so needs opening in the [engineering repo](https://github.com/xamarin/Xamarin.Forms). Thanks!
