### ISSUE TITLE
How do I get a provisioning profile installed on Visual Studio for Windows?

### ISSUE THREAD

**Issue by ravenrgg** [MicrosoftDocs/xamarin-docs#319]
You go on and on about using Xcode, but I see nothing about Visual Studio on Windows.  If I wanted to do Mac development I would.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1a9b2b39-f572-75dc-f022-cada4919f129
* Version Independent ID: 804f0f6d-ed12-18d8-30b8-95b5aaa19d8a
* Content: [Free Provisioning - Xamarin](https://docs.microsoft.com/en-us/xamarin/ios/get-started/installation/device-provisioning/free-provisioning)
* Content Source: [docs/ios/get-started/installation/device-provisioning/free-provisioning.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/ios/get-started/installation/device-provisioning/free-provisioning.md)
* Service: **unspecified**
* Product: **xamarin**
* GitHub Login: @asb3993
* Microsoft Alias: **amburns**

**Comment by pierrenortje** [comment]
Any response from Microsoft yet?

**Comment by ravenrgg** [comment]
I friend who uses Xamarin stopped by.  You need to be an official Apple developer and download the profile from Apple via web browser.  I seldom receive useful responses when I post here or in the Xamarin forums.  The response is usually a repetition of what didn't work.

**Comment by asb3993** [comment]
[A Mac with Xcode installed is required for iOS development](https://docs.microsoft.com/en-us/xamarin/ios/get-started/#required-components), even if you are using Visual Studio on Windows. This is required for compiling native iOS applications.

To publish an app you must have an Apple Developer Account, as described in [this guide](https://docs.microsoft.com/en-us/xamarin/ios/get-started/installation/device-provisioning/). However, if you want to quickly test and deploy to a device you _can_ use Free Provisioning (although it's recommend that you use an Apple Developer Account). Free provisioning comes with a lot of [limitations](https://docs.microsoft.com/en-us/xamarin/ios/get-started/installation/device-provisioning/free-provisioning#limitations) and has to be done on Xcode. It can't be done in Visual Studio or Visual Studio for Mac. 

However, once you have generated the provisioning profile on Xcode and downloaded to the macOS keychain, it will be available to select in Visual Studio (when paired to a Mac). To do this, follow the steps in this guide and then for step 9, follow the steps in the [manual provisioning](https://docs.microsoft.com/en-us/xamarin/ios/get-started/installation/device-provisioning/manual-provisioning?tabs=vswin#deploying-to-a-device) guide. 

Thanks for your feedback, I'll make the necessary changes to this doc to update the steps for VS.

**Comment by MobileDevL** [comment]
So, once step 8 above is finished on the Mac, which is the next step on the manual provisioning guide for VS on Windows to test an iOS app on a physical device from a Windows PC? That all looks like Mac instructions to me.

**Comment by asb3993** [comment]
@MobileDevL Once you have created and saved in the Mac keychain, the next step is to then select the provisioning profile in the info.plist file of your Xamarin.iOS project in Visual Studio.

You should follow the steps under "Deploying to Device" in the manual provisioning guide: https://docs.microsoft.com/en-us/xamarin/ios/get-started/installation/device-provisioning/manual-provisioning?tabs=vswin#deploying-to-a-device
This guide has both Mac and Windows instructions so make sure that you select the Visual Studio tab to see the Windows instructions.

**Comment by ravenrgg** [comment]
Thank you.  I am in the process of joining Developer University.  I will try this after joining.
