### ISSUE TITLE
.NET 5 support

### ISSUE THREAD

**Issue by realivanjx** [MicrosoftDocs/xamarin-docs#3191]
Does GTK# backend support net core or .net 5?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 66853f3d-854e-08ad-84d2-b2a98f88c48b
* Version Independent ID: 77ea362d-ef46-f426-3d4a-5f99e39ce160
* Content: [GTK# Platform Setup - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/platform/other/gtk?tabs=windows)
* Content Source: [docs/xamarin-forms/platform/other/gtk.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/platform/other/gtk.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @realivanjx 

It runs against Mono. It requires changes to run against .NET Core and .NET 5.
