### ISSUE TITLE
Multiple channels on Android

### ISSUE THREAD

**Issue by kberawala** [MicrosoftDocs/xamarin-docs#3192]
On Android devices notification "Channel" is created. lets say there are 2 channels created with different config for sound/lights/vibration.

what should be the payload to deliver message to specific channel and notification would behave according to the channel ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 92f390d9-cbd0-ab8c-6c8c-49df76d1b8e0
* Version Independent ID: 15739c2f-afbb-c21d-b96f-fabe7060e410
* Content: [Send and receive push notifications with Azure Notification Hubs and Xamarin.Forms - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/data-cloud/azure-services/azure-notification-hub)
* Content Source: [docs/xamarin-forms/data-cloud/azure-services/azure-notification-hub.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/data-cloud/azure-services/azure-notification-hub.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @profexorgeek
* Microsoft Alias: **jusjohns**

**Comment by davidbritch** [comment]
Hi @kberawala 

Unfortunately we cannot respond to support questions here. The recommended place to seek help is [Microsoft Q&A](https://docs.microsoft.com/en-us/answers/topics/dotnet-android.html).
