### ISSUE TITLE
Please Implement for WPF also

### ISSUE THREAD

**Issue by CRManley** [MicrosoftDocs/xamarin-docs#3193]
Cannot use ths api in a Xamarin.WPF application.

Regards.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2c4b0c52-127c-0e6b-28d1-3071c522e507
* Version Independent ID: 61f6a36e-9c85-bf57-49f0-76719d8a47c1
* Content: [Xamarin.Essentials: App Information - Xamarin](https://docs.microsoft.com/en-us/xamarin/essentials/app-information?context=xamarin%2Fandroid&tabs=android)
* Content Source: [docs/essentials/app-information.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/essentials/app-information.md)
* Product: **xamarin**
* Technology: **xamarin-essentials**
* GitHub Login: @jamesmontemagno
* Microsoft Alias: **jamont**

**Comment by davidbritch** [comment]
Thanks for your feedback.
