### ISSUE TITLE
Myanmar Unicode Embedding Not Showing Correctly at Label and Radio Button

### ISSUE THREAD

**Issue by shinnthant-lab** [MicrosoftDocs/xamarin-docs#3196]
Myanmar Unicode Font (MMRText.TTF) Embed not showing correctly at Xamarin.Forms.Label Cotrol and RadioButton Control, but showing correctly at Xamarin.Forms.Entry Control.
I'm Using XF5 Pre5.
Please see the screenshot for more detail. Red Highlighted are wrong but the underlying Text Boxes are showing correct.
411991
![image](https://user-images.githubusercontent.com/54578974/102884332-d8934e80-447f-11eb-854d-8fe56f8d7ec2.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe0572c4-91be-fc86-d130-242db2bf470b
* Version Independent ID: 1238fdd7-c378-6d0d-654e-55656a70d386
* Content: [Fonts in Xamarin.Forms - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/text/fonts)
* Content Source: [docs/xamarin-forms/user-interface/text/fonts.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/text/fonts.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @shinnthant-lab 

This is an issue with the product, rather than the docs, and so needs logging in the [engineering repo](https://github.com/xamarin/Xamarin.Forms). Thanks!

**Comment by shinnthant-lab** [comment]
Thanks @davidbritch , I'll move to the right repo.
