### ISSUE TITLE
I sure would like an obvious link to the API on this page...  did I miss it?

### ISSUE THREAD

**Issue by bobwhitten** [MicrosoftDocs/xamarin-docs#3197]
Searched for and did not find link to the API itself...  Did I miss it?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bde8b00e-bef2-d10c-268f-2e49e236a89f
* Version Independent ID: dad8b07c-2227-c7ed-6369-d10d9b132e99
* Content: [Xamarin.Essentials: File Picker - Xamarin](https://docs.microsoft.com/en-us/xamarin/essentials/file-picker?context=xamarin%2Fios&tabs=ios)
* Content Source: [docs/essentials/file-picker.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/essentials/file-picker.md)
* Product: **xamarin**
* Technology: **xamarin-essentials**
* GitHub Login: @jamesmontemagno
* Microsoft Alias: **jamont**

**Comment by jamesmontemagno** [comment]
This API is in version 1.6.0
