### ISSUE TITLE
Geolocation.GetLocationAsync from MainPage, Main?

### ISSUE THREAD

**Issue by stewa11** [MicrosoftDocs/xamarin-docs#3198]
I would like to find the users' current location during execution of Events and also 'Xamarin Form Code Behind C#'.
My code works fine when calling Geolocation.GetLocationAsync from an Event (like a Button being pressed)  but I cannot get the async await to work on MainPage Main method. Can you please help me understand how to make this happen?
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3e4b7142-58e2-221e-d4fd-83808c298d89
* Version Independent ID: 24c69ad9-44c2-a89d-608c-ffc9946fb411
* Content: [Geolocation Class (Xamarin.Essentials)](https://docs.microsoft.com/en-us/dotnet/api/xamarin.essentials.geolocation?view=xamarin-essentials)
* Content Source: [docs/en/Xamarin.Essentials/Geolocation.xml](https://github.com/xamarin/Essentials/blob/live/docs/en/Xamarin.Essentials/Geolocation.xml)
* Product: **xamarin**
* Technology: **xamarin-essentials**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by davidbritch** [comment]
Hi @stewa11 

Unfortunately we cannot respond to support questions here. The recommended place to seek help is the [Xamarin.Essentials channel on Microsoft Q&A](https://docs.microsoft.com/en-us/answers/topics/dotnet-xamarinessentials.html).
