### ISSUE TITLE
Ambiguities in Android Debug Log -> Accessing from the command line

### ISSUE THREAD

**Issue by knocte** [MicrosoftDocs/xamarin-docs#32]
https://docs.microsoft.com/en-gb/xamarin/android/deploy-test/debugging/android-debug-log#accessing-from-the-command-line (https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/android/deploy-test/debugging/android-debug-log.md)

This documentation page seems to be focused to experienced Xamarin developers, but very confusing to newbies. For example:

* What's the equivalent path of C:\android-sdk-windows\platform-tools in Mac?
* What does `If only one device is attached` mean exactly? Attached via XamarinLivePlayer? or does this refers to emulators? What if the developer wants to see the logs on a device that is not connected to the Mac?

**Comment by mgmclemore** [comment]
@knocte, thank you for the feedback!  Updated this topic with more content for the Mac, added example screenshots, and improved explanations about the devices. Should be published soon.

**Comment by knocte** [comment]
@mgmclemore thanks, the fixes look great. But it still leaves me with an open question: if you create the APK for your app, and run it independently in your Android (without connecting it to the Mac), and can only reproduce one bug this way, how can you have debug logs? Where would they be saved in the device?

**Comment by knocte** [comment]
(And FYI, ultimately, I think the reason of why I cannot reproduce this bug when debugging from VS4Mac is these 2 Xamarin.Android bugs: https://github.com/xamarin/xamarin-android/issues/1441 & https://github.com/xamarin/xamarin-android/issues/1442 . But I'm not 100% sure and this is why I need debug logs in the device.)

**Comment by mgmclemore** [comment]
@knocte, thank you for submitting those bugs!  Unfortunately, the Debug Log does not support viewing log entries generated while the device is disconnected from Visual Studio, so I've updated the topic to make this clear.
