### ISSUE TITLE
Not found

### ISSUE THREAD

**Issue by tlhintoq** [MicrosoftDocs/xamarin-docs#320]
If you search for xamarin.livereload through Nuget Package Manager GUI the package isn't found. (Yes I have the pre-release check ticked on)
If you use the Nuget Package Manager Console and issue the command:
install-package xamarin.livereload -prerelease -project myprojectname
It installs fine.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e40394ca-9a55-d9b5-d427-7c2a2c00cfc8
* Version Independent ID: 5a5c17e2-a683-88f6-07a9-2002e814d54c
* Content: [Live Reload - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/xaml/live-reload#feedback)
* Content Source: [docs/xamarin-forms/xaml/live-reload.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/xaml/live-reload.md)
* Service: **unspecified**
* Product: **xamarin**
* GitHub Login: @pierceboggan
* Microsoft Alias: **piboggan**

**Comment by yelkereb** [comment]
You need to make sure your Package source is set to 'All'.

![image](https://user-images.githubusercontent.com/39312870/40450368-4a73acee-5e90-11e8-84d0-50e49d02d272.png)

**Comment by conceptdev** [comment]
@tlhintoq the Live Reload NuGet is on a custom feed, and requires the source be set to **All** as noted above by @yelkereb, and also in the doc.

**Comment by btastic** [comment]
In case anyone needs the package source url, it was this after installing: https://nugetized.blob.core.windows.net/live-reload/index.json

**Comment by patsadow2** [comment]
good job Microsoft as always, it doesnt work :)
