### ISSUE TITLE
sample is not running "Connection refused"

### ISSUE THREAD

**Issue by Ali-HA** [MicrosoftDocs/xamarin-docs#3200]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 155a1af2-3ce7-058b-d243-b4d7a9cd6e22
* Version Independent ID: 47f0df9e-ab6a-a38b-5916-991b5110ebf1
* Content: [Consume a RESTful Web Service - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/data-cloud/web-services/rest)
* Content Source: [docs/xamarin-forms/data-cloud/web-services/rest.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/data-cloud/web-services/rest.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @Ali-HA 

You need to run both the TodoAPI and project for your platform of choice simultaneously. Otherwise there isn't a web service running for the mobile app to connect to.
