### ISSUE TITLE
More limitations to uncover and document

### ISSUE THREAD

**Issue by omatrot** [MicrosoftDocs/xamarin-docs#3201]
Using Hotrestart with an existing project does not work and ends with a [native crash](https://github.com/xamarin/Xamarin.Forms/issues/13179). I guess there are more limitations to uncover.

Kudos for this amazing feature though.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8f3eb808-8e6d-4e07-fc75-8d79a7249265
* Version Independent ID: dbb2b9a9-87a6-e473-50e6-f88435d49e88
* Content: [Xamarin Hot Restart - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/deploy-test/hot-restart?WT.mc_id=xamarin-c9-jamont)
* Content Source: [docs/xamarin-forms/deploy-test/hot-restart.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/deploy-test/hot-restart.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @maddyleger1
* Microsoft Alias: **maleger**

**Comment by davidbritch** [comment]
Hi @omatrot 

Thanks for the feedback!
