### ISSUE TITLE
MapService Token Unspecified Warning: Where should my Bing Maps Application Key Go in the code?

### ISSUE THREAD

**Issue by stewa11** [MicrosoftDocs/xamarin-docs#3202]
[Where should my Bing Maps Application Key Go in the code?
I am thinking it should be in the UWP App.caml.cs but what will the corrrect C# code be?

It is something like: 
 Xamarin.Forms.Forms.Init(e, assembliesToInclude);
	                Xamarin.Forms.Forms.Init(e);
	               Xamarin.FormsMaps.Init("YOUR KEY");]

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 19aecf1c-11b6-6920-a37e-817458e52dd1
* Version Independent ID: af9cea8e-800f-c462-7efb-7f048235db3a
* Content: [Customizing a Map Pin - Xamarin](https://docs.microsoft.com/en-gb/xamarin/xamarin-forms/app-fundamentals/custom-renderer/map-pin)
* Content Source: [docs/xamarin-forms/app-fundamentals/custom-renderer/map-pin.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/app-fundamentals/custom-renderer/map-pin.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by stewa11** [comment]
This didnt work (I suspect it will need to reference the Custom Renderer - can you please correct and re-issue the solution including a correct reference to the users AppServiceToken?):
  // just ensure that the window is active
            if (rootFrame == null)
            {
                // Create a Frame to act as the navigation context and navigate to the first page
                rootFrame = new Frame();

                rootFrame.NavigationFailed += OnNavigationFailed;

                Xamarin.Forms.Forms.Init(e);

                var assembliesToInclude = new[] { typeof(Xamarin.Forms.Maps.UWP.MapRenderer).GetTypeInfo().Assembly };
                Xamarin.Forms.Forms.Init(e, assembliesToInclude);
                Xamarin.Forms.Forms.Init(e);
                              Xamarin.FormsMaps.Init("YOUR TOKEN");

**Comment by davidbritch** [comment]
Hi @stewa11 

Take a look at the [sample](https://github.com/xamarin/xamarin-forms-samples/tree/master/WorkingWithMaps).
