### ISSUE TITLE
[Documentation] Publishing to Google Play Documentation - appears to be out of date.

### ISSUE THREAD

**Issue by JoeTomkinson** [MicrosoftDocs/xamarin-docs#3203]
Document in questions: **[docs/android/deploy-test/publishing/publishing-to-google-play/index.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/android/deploy-test/publishing/publishing-to-google-play/index.md)**

From what I can tell this documentation is now out of date; the google play developer console when creating an OAuth Client for the application you're looking to publish from VS 2019 does not provide a client secret and the general process flow for creating an OAuth Client has changed which I suspect may also cause confusion.

Based on the documentation I'd be curious to know if anyone's successfully managed to publish to google play via VS2019. The documentation was last updated in 2018 which is old in comparison to the frequency that google update their developer experiences.

Any thoughts on if this documentation is not being maintained or updated because there is a new implementation of this process in the works for a future Visual studio update?

**Comment by davidbritch** [comment]
[Microsoft support for Xamarin](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin) will end on May 1, 2024 for all Xamarin SDKs including Xamarin.Forms. In preparation for this, all issues and PRs in this repository are being closed.

.NET MAUI is the replacement for Xamarin.Forms, and it's documentation can be found [here](https://learn.microsoft.com/dotnet/maui/?view=net-maui-8.0).
