### ISSUE TITLE
Update Docs To Reflect CollectionView Platform Support

### ISSUE THREAD

**Issue by Axemasta** [MicrosoftDocs/xamarin-docs#3205]
### Doc issue description

`CollectionView` is not supported by the mac platform, the docs should be updated to reflect this.

I raised the issue in the forms repo [here](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/collectionview/)

Here are the official `CollectionView` [docs](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/collectionview/), I believe the following should be added to them to make it clear that macOS is not supported by this control:

> Collection View is supported on the following platforms:
 > - iOS
 > - Android
 > - UWP

**Comment by davidbritch** [comment]
Hi @Axemasta 

Platform support is already mentioned at https://docs.microsoft.com/xamarin/xamarin-forms/user-interface/collectionview/introduction

**Comment by Axemasta** [comment]
Hi David,

`CollectionView` is a premiere Xamarin Forms control. When you go onto the documentation for [`ListView`](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/listview/), it redirects you to `CollectionView` as the preferred component to be using for repeater views:

> ListView is a view for presenting lists of data, especially long lists that require scrolling.
> 
> Important
>
> CollectionView is a view for presenting lists of data using different layout specifications. It aims to provide a more flexible, and performant alternative to ListView. For more information, see Xamarin.Forms CollectionView.

I don't think from the supported message on `CollectionView` that it is obvious enough that this control is limited to a select number of platforms (only 2 are fully supported). I was imagining adding a big obnoxious table that made it incredibly explicit what platforms this control will work on:

Idea 1:
  | Supported ✅ | Partial Support ⚠️ | Not Supported ❌
-- | -- | -- | --
Platform | iOS, Android | UWP | macOS, Tizen, watchOS, tvOS, GTK etc


Idea 2:
Platforms | Supported?
-- | --
iOS | ✅
Android | ✅
UWP | ⚠️
macOS | ❌
Etc | ❌

I've seen numerous threads on external websites with people asking about the support of these components on alternative platforms like macOS. Since when you add a `CollectionView` to a macOS Xamarin Forms app, the app itself will not display anything onscreen or warn you in the console that the component isn't supported. A change like this would make it much clearer not to use this control on unsupported platforms 😊

**Comment by davidbritch** [comment]
Reopening for consideration.

**Comment by davidbritch** [comment]
I'm going to close this for now. Unfortunately the table idea doesn't work very well for users reliant on screen readers.  Information about platform support is in the doc, and is easily consumed by screen readers.

It's something that will be revisited for MAUI, when there should be better feature parity across the platforms.
