### ISSUE TITLE
Setting detail out of date (visual studio 2019 16.8.3)

### ISSUE THREAD

**Issue by chao-master** [MicrosoftDocs/xamarin-docs#3208]
On windows the hot reload setting is stated to be at "Tools > Options > Xamarin > Hot Reload." but is actually at "Tools > Options > **Debugging > Hot Reload > Enable XAML Hot Reload > Android and iOS (Xamarin.Forms)**"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b74184fd-ca8a-11fa-ed37-91235fc59401
* Version Independent ID: 87f197b8-20c6-4825-18e4-86562bb2523c
* Content: [XAML Hot Reload for Xamarin.Forms - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/xaml/hot-reload)
* Content Source: [docs/xamarin-forms/xaml/hot-reload.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/xaml/hot-reload.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @maddyleger1
* Microsoft Alias: **maleger**

**Comment by davidbritch** [comment]
Hi @chao-master 

This is fixed in a PR that's going live now.
