### ISSUE TITLE
Please add Get Emails functionality to outlook, hotmail etc

### ISSUE THREAD

**Issue by stewa11** [MicrosoftDocs/xamarin-docs#3209]
Please add Get Emails functionality to outlook, hotmail etc
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 373b5189-f00c-0b2a-f957-e728e050b687
* Version Independent ID: 77543a6e-3715-fe62-0ddb-fc80bd371207
* Content: [Email Class (Xamarin.Essentials)](https://docs.microsoft.com/en-us/dotnet/api/xamarin.essentials.email?view=xamarin-essentials)
* Content Source: [docs/en/Xamarin.Essentials/Email.xml](https://github.com/xamarin/Essentials/blob/live/docs/en/Xamarin.Essentials/Email.xml)
* Product: **xamarin**
* Technology: **xamarin-essentials**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by davidbritch** [comment]
Hi @stewa11 

This repo is for doc feedback. Product feedback should be made in the [engineering repo](https://github.com/xamarin/Essentials). Thanks!
