### ISSUE TITLE
still don't know how to lock orientation

### ISSUE THREAD

**Issue by BDTomasz** [MicrosoftDocs/xamarin-docs#321]
So I have read the article and still don't know how I can lock the orientation, time to google again and dig through forums and look for plugins...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ee3536ba-80b7-2443-39ec-2082cfd6d557
* Version Independent ID: 6339e8b1-c252-0647-b3ee-d317100940ae
* Content: [Device Orientation - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/layouts/device-orientation?tabs=vswin)
* Content Source: [docs/xamarin-forms/user-interface/layouts/device-orientation.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/layouts/device-orientation.md)
* Service: **unspecified**
* Product: **xamarin**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by charlespetzold** [comment]
If you want to restrict a phone to portrait or landscape mode, that's discussed in Chapter 5 of [_Creating Mobile Apps with Xamarin Forms_](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/creating-mobile-apps-xamarin-forms/), in the several paragraphs above the heading "Metrical sizes".

**Comment by BDTomasz** [comment]
Thank you @charlespetzold , I'll read through that.

**Comment by hyryel** [comment]
Hi, it's explained at the beginning of this page : 
On iOS, device orientation is configured for applications using the Info.plist file
https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/layouts/device-orientation?tabs=vswin#ios

To control the orientation on Android, open MainActivity.cs and set the orientation using the attribute decorating the MainActivity class
https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/layouts/device-orientation?tabs=vswin#android

On the Universal Windows Platform (UWP), supported orientations are set in the Package.appxmanifest file.
https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/layouts/device-orientation?tabs=vswin#universal-windows-platform
