### ISSUE TITLE
Screenshot not working on Android 

### ISSUE THREAD

**Issue by loganwenzel** [MicrosoftDocs/xamarin-docs#3210]
[
Running the latest versions of Xamarin Essentials and Xamarin Forms, I am trying to implement the CaptureScreenshot() method 
described in this post: https://docs.microsoft.com/en-us/xamarin/essentials/screenshot

I have the method linked to a button click, on which it should take a screenshot of the current screen and save it to the memorystream, however I keep getting this error preventing it from working: 
"System.TypeLoadException
  Message=Could not load type of field 'Order_Form_V1.CustomArrayConfiguration+<CaptureScreenshot>d__3:<screenshot>5__2' (6) due to: Could not resolve type with token 01000029 from typeref (expected class 'Xamarin.Essentials.ScreenshotResult' in assembly 'Xamarin.Essentials, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null') assembly:Xamarin.Essentials, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null type:Xamarin.Essentials.ScreenshotResult member:(null)" 

Below is my method: 
        private async void CaptureScreenshot(object sender, EventArgs e)
        {
            var screenshot = await Screenshot.CaptureAsync();
            var stream = await screenshot.OpenReadAsync();
            var array_image = ImageSource.FromStream(() => stream);
            imagetest.Source = array_image;
        }
 Please let me know what I can do to avoid this. Thank you!
]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: beaf425f-b444-b622-b0bb-103b45ec7479
* Version Independent ID: 58f83c25-3541-fc77-0fc8-e9cdeb7eef18
* Content: [Xamarin.Essentials: Screenshot - Xamarin](https://docs.microsoft.com/en-us/xamarin/essentials/screenshot)
* Content Source: [docs/essentials/screenshot.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/essentials/screenshot.md)
* Product: **xamarin**
* Technology: **xamarin-essentials**
* GitHub Login: @jamesmontemagno
* Microsoft Alias: **jamont**

**Comment by davidbritch** [comment]
Hi @loganwenzel 

Unfortunately we cannot respond to support questions here. The recommended place to seek help is the [Xamarin.Essentials channel on Microsoft Q&A](https://docs.microsoft.com/en-us/answers/topics/dotnet-xamarinessentials.html).
