### ISSUE TITLE
remote-notifications-with-fcm.md outdated

### ISSUE THREAD

**Issue by oOICEMANOo** [MicrosoftDocs/xamarin-docs#3211]
when trying to follow the guide "https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/android/data-cloud/google-messaging/remote-notifications-with-fcm.md" it seems it is outdated and does not work.

MyFirebaseIIDService.cs(10,41,10,66): warning CS0618: 'FirebaseInstanceIdService' is obsolete: 'This class is obsoleted in this android platform'
MyFirebaseIIDService.cs(13,30,13,44): warning CS0672: Member 'MyFirebaseIIDService.OnTokenRefresh()' overrides obsolete member 'FirebaseInstanceIdService.OnTokenRefresh()'. Add the Obsolete attribute to 'MyFirebaseIIDService.OnTokenRefresh()'.
MyFirebaseIIDService.cs(15,34,15,52): warning CS0618: 'FirebaseInstanceId' is obsolete: 'This class is obsoleted in this android platform'
MyFirebaseIIDService.cs(15,34,15,67): warning CS0618: 'FirebaseInstanceId.Token' is obsolete: 'deprecated'

**Comment by davidbritch** [comment]
[Microsoft support for Xamarin](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin) will end on May 1, 2024 for all Xamarin SDKs including Xamarin.Forms. In preparation for this, all issues and PRs in this repository are being closed.

.NET MAUI is the replacement for Xamarin.Forms, and it's documentation can be found [here](https://learn.microsoft.com/dotnet/maui/?view=net-maui-8.0).
