### ISSUE TITLE
RemainingItemsThreshold doesn't work!

### ISSUE THREAD

**Issue by javanjoel** [MicrosoftDocs/xamarin-docs#3217]
[Enter feedback here]

I set the threshold to 4 and set the command and even tried using the event handler. Have 30 items shown and it should fire when I scroll down to the 4th item left. Never fires!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 12370c4e-0935-d43a-7d28-32a10a30074f
* Version Independent ID: bb1eccf7-c1b8-25b1-5325-3b37a9b1bd94
* Content: [Xamarin.Forms CollectionView Data - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/collectionview/populate-data#load-data-incrementally)
* Content Source: [docs/xamarin-forms/user-interface/collectionview/populate-data.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/collectionview/populate-data.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @javanjoel 

If you believe the feature isn't working you'll need to log an issue in the [engineering repo](https://github.com/xamarin/Xamarin.Forms).
