### ISSUE TITLE
Please provide information about Adaptive Bitrate Streaming support

### ISSUE THREAD

**Issue by sjorsmiltenburg** [MicrosoftDocs/xamarin-docs#3218]
The docs state that you can bind the video player to a web url.
It does not go into the "advanced" case of adaptive bitrate streaming and if this is supported by the sample player.
Is this only supported by the azure media player and thus only available in a webview?

https://stackoverflow.com/questions/65794024/what-is-the-preferred-way-for-playback-of-a-web-video-in-xamarin-forms?noredirect=1#comment116342246_65794024

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 08231611-5a52-267d-cfc6-0042e5d5c2a3
* Version Independent ID: 6c39962d-a013-a391-9f1f-4a69f3a99de0
* Content: [Playing a Web video - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/custom-renderer/video-player/web-videos)
* Content Source: [docs/xamarin-forms/app-fundamentals/custom-renderer/video-player/web-videos.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/app-fundamentals/custom-renderer/video-player/web-videos.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @sjorsmiltenburg 

I'm actually deleting the docs in question, as they've been superseded by the `MediaElement` control. However, this control has now moved from Xamarin.Forms to the Xamarin Community Toolkit. See https://docs.microsoft.com/xamarin/community-toolkit/views/mediaelement for more info.

However, this still doesn't answer your question. Supported video formats are those offered by the native controls on the underlying platform.

[Xamarin MediaManager](https://github.com/Baseflow/XamarinMediaManager) has more support than `MediaElement`, but again, it's limited by the underlying platforms and uses techniques like using ExoPlayer on Android to deliver DASH/HLS streaming.

Failing that, you'll have to fall back to a `WebView`.
