### ISSUE TITLE
Remove DisplayPromptAsync

### ISSUE THREAD

**Issue by Arie-Kanarie** [MicrosoftDocs/xamarin-docs#3219]
`DisplayPromptAsync` is obsolete so it can be removed from this manual

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3c6e0bb1-26e4-091b-8a99-27d772bed7f6
* Version Independent ID: 57d8ad92-0aa2-9ec4-47bc-8853d9a71d91
* Content: [Display Pop-ups - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/pop-ups)
* Content Source: [docs/xamarin-forms/user-interface/pop-ups.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/pop-ups.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @Arie-Kanarie 

Afraid that isn't correct. While a `DisplayPromptAsync` method has been obsoleted (https://github.com/xamarin/Xamarin.Forms/blob/6f9b1f6169219fafe4ef8a0f3d19ecf468146138/Xamarin.Forms.Core/Page.cs#L230), a second `DisplayPromptAsync` method still exists (https://github.com/xamarin/Xamarin.Forms/blob/6f9b1f6169219fafe4ef8a0f3d19ecf468146138/Xamarin.Forms.Core/Page.cs#L237).
