### ISSUE TITLE
How to theme Display Pop-ups?

### ISSUE THREAD

**Issue by twofingerrightclick** [MicrosoftDocs/xamarin-docs#3220]
It would be great to have a link to how to theme Display Pop-ups. i.e. What properties are used by default to create the colors of text and background for iOS and Android when a display alert is drawn. I am currently getting white text on a white background by default when running DisplayPromptAsync() in Android. I was able to figure out that I can set the  android `alertDialogTheme` to change `DisplayAlert` dialogues and so have black text on white there, but not sure what underlying android view is being used for DisplayPromptAsync() and how to theme in Android xml.

Cheers

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3c6e0bb1-26e4-091b-8a99-27d772bed7f6
* Version Independent ID: 57d8ad92-0aa2-9ec4-47bc-8853d9a71d91
* Content: [Display Pop-ups - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/pop-ups)
* Content Source: [docs/xamarin-forms/user-interface/pop-ups.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/pop-ups.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @twofingerrightclick 

Setting the theme on Android can be messy, as it can be dependent upon your API level. The easiest approach is to use custom renderers to get more control over the popup appearance (see https://stackoverflow.com/questions/60210572/is-there-any-way-in-xamarin-forms-to-change-the-background-color-of-a-dialog-box).

Another approach is to use a third party library such as https://github.com/rotorgames/Rg.Plugins.Popup
