### ISSUE TITLE
Great tutorial, but broken dependencies

### ISSUE THREAD

**Issue by Eltee-Taiwo** [MicrosoftDocs/xamarin-docs#3221]
Great tutorial. However as this [stackoverflow anwer ](https://stackoverflow.com/questions/64428377/java-lang-nosuchmethoderror-no-static-method-checkbuilderrequirement) points out, I had to manually install the latest version of the Xamarin.Google.Dagger nuget package.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 92f390d9-cbd0-ab8c-6c8c-49df76d1b8e0
* Version Independent ID: 15739c2f-afbb-c21d-b96f-fabe7060e410
* Content: [Send and receive push notifications with Azure Notification Hubs and Xamarin.Forms - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/data-cloud/azure-services/azure-notification-hub#register-with-azure-notification-hub-and-subscribe-to-tags)
* Content Source: [docs/xamarin-forms/data-cloud/azure-services/azure-notification-hub.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/data-cloud/azure-services/azure-notification-hub.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @profexorgeek
* Microsoft Alias: **jusjohns**

**Comment by davidbritch** [comment]
Hi @Eltee-Taiwo 

I'm retiring this doc, and in it's place linking to a more detailed Xamarin/Azure Notification Hubs doc. The update has been made in a PR that will go live later today.

**Comment by Eltee-Taiwo** [comment]
Sweet. Thanks David! Would be a bother to ask that you could also send me the link when it goes live?
