### ISSUE TITLE
GetCustomPin based on coordinates is quite dangerous

### ISSUE THREAD

**Issue by cbs-cbt** [MicrosoftDocs/xamarin-docs#3222]
Hello,
Thank you for the great sample!
One thing upsets me in your example.
The GetCustomPin function is based on the coordinates of the item to find.
However, it is possible that two Markers have the same coordinate.
I was able to solve the problem for Android and UWP by storing a reference to the native pin in my CustomPin.
I couldn't find how to do this in the CustomRenderer for iOS.

Do you have an idea?

Thank you in advance for your answer.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 19aecf1c-11b6-6920-a37e-817458e52dd1
* Version Independent ID: af9cea8e-800f-c462-7efb-7f048235db3a
* Content: [Customizing a Map Pin - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/custom-renderer/map-pin#related-links)
* Content Source: [docs/xamarin-forms/app-fundamentals/custom-renderer/map-pin.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/app-fundamentals/custom-renderer/map-pin.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @cbs-cbt 

Unfortunately we cannot respond to support questions here. The recommended place to seek help is the [Xamarin.Forms channel](https://docs.microsoft.com/en-us/answers/topics/dotnet-xamarinforms.html) on Microsoft Q&A.
