### ISSUE TITLE
Xamarin forms problem

### ISSUE THREAD

**Issue by richardwalker3194** [MicrosoftDocs/xamarin-docs#3223]
[Enter feedback here]
The sample Xamarin app deploys to the device. But when run on the device a white screen appears then it drops out. Android 10.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5a064123-54f2-0eb2-c76a-65b36c5ec1a7
* Version Independent ID: dbf4119a-2c24-e0f1-8041-bb3755c29c24
* Content: [Create a single page Xamarin.Forms application - Xamarin](https://docs.microsoft.com/en-us/xamarin/get-started/quickstarts/single-page)
* Content Source: [docs/get-started/quickstarts/single-page.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/get-started/quickstarts/single-page.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @richardwalker3194 

I just tried the sample on an Android 10 device, and it worked just fine for me. Therefore, it looks like you're having an issue with the product itself. The recommended place to seek help is the [Xamarin.Forms channel](https://docs.microsoft.com/en-us/answers/topics/dotnet-xamarinforms.html) on Microsoft Q&A.
