### ISSUE TITLE
How to use a global ResourceDictionary for Styles when using Native Forms?

### ISSUE THREAD

**Issue by kanderson-wellbeats** [MicrosoftDocs/xamarin-docs#3225]
I'm using the Native Forms approach very successfully to migrate an application from fully Xamarin Native to more Forms-based, but as of right now I'm stuck having my ResourceDictionary of Styles and Colors and things which I need to manually include in the Resources of every ContentPage I'm making. I'd like this instead to be as easy as it is in regular Xamarin.Forms, where my ResourceDictionary can be placed in the Resources of the Application, which makes the Styles accessible from any of my ContentPages, no extra step required. Is this possible with Native Forms? It seems like the life cycle of the actual Forms.Application is kind of strange in this Native Forms approach so it needs some special handling.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2e9d651b-6624-f671-16e2-61c28415374b
* Version Independent ID: 61600bb9-66b3-904d-6be3-32029e78bc5a
* Content: [Xamarin.Forms in Xamarin Native Projects - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/platform/native-forms)
* Content Source: [docs/xamarin-forms/platform/native-forms.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/platform/native-forms.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @kanderson-wellbeats 

You can't rely on the `App` class in native forms apps. What you could do though is create a stand-alone `ResourceDictionary` for your shared resources (see https://docs.microsoft.com/xamarin/xamarin-forms/platform/native-forms), then merge it into each `ContentPage` (see https://docs.microsoft.com/xamarin/xamarin-forms/xaml/resource-dictionaries#merged-resource-dictionaries). That way any shared resources are only defined in one place.

**Comment by davidbritch** [comment]
Hi @kanderson-wellbeats 

I did some more digging into this in a native forms project on iOS. The first time you call `CreateViewController`, `Xamarin.Forms.Application.Current` gets set to an `EmbeddedApplication` object. If you add resources to that resource dictionary (Xamarin.Forms.Application.Current.Resources), they can be consumed from multiple pages in the app.

The same approach can be followed on Android, after calling `CreateSupportFragment` for the first time.

**Comment by kanderson-wellbeats** [comment]
Thanks for the response @davidbritch. My current approach is exactly what you suggested in your first comment. That works fine but is a little annoying and seems like it might be inefficient if the resource dictionary is big enough as it gets instantiated on every individual page (though I don't have any real evidence on that efficiency stuff, just a hunch).

In my investigation into this I tried to do what you suggested in your second comment (specifically on Android to start with), but I find that the each Xamarin.Forms.Application.Current only lives until the next time CreateSupportFragment is called. That is, I am successful at assigning a ResourceDictionary to Xamarin.Forms.Application.Current.Resources, but the very next time CreateSupportFragment is called, Application.Current.Resources always ends up empty again. On the line before that call Resources is populated, then on the line after it's empty again. It appears this is probably due to the Application being continually reinstantiated with every CreateSupportFragment call: https://github.com/xamarin/Xamarin.Forms/blob/80a4dbfb1cd897f478c38d0aafa6a5d67940d2f3/Xamarin.Forms.Platform.Android/AppCompat/PageExtensions.cs#L83 but of course I don't really know the reasoning behind that.

**Comment by davidbritch** [comment]
@kanderson-wellbeats 

In my sample, I populate the resource dictionary after the first call to CreateSupportFragment:

```
            AndroidX.Fragment.App.Fragment mainPage = new NotesPage().CreateSupportFragment(this);

            Xamarin.Forms.Application.Current.Resources = new MyDictionary();
```

The style in the RD is consumed on NotesPage. When I navigate to the next page (by calling CreateSupportFragment on NoteEntryPage), the style in the RD is consumed on NoteEntryPage. So the RD still has a style in it.

However, after navigating back from the current page, when examining the RD there are then no entries in it. So it looks like it's the back navigation that's the issue here (to me).

**Comment by davidbritch** [comment]
@kanderson-wellbeats 

Actually, I agree with you now. It's the second call to CreateSupportFragment that's wiping the RD.

**Comment by davidbritch** [comment]
@kanderson-wellbeats 

I've got a solution for you (tried on Android).

Make your first call to CreateSupportFragment as normal. For all subsequent calls to `CreateSupportFragment`, set the `Parent` property of the `ContentPage` object to `Xamarin.Forms.Application.Current` before calling `CreateSupportFragment` e.g.

First call to `CreateSupportFragment`:

```
            AndroidX.Fragment.App.Fragment mainPage = new NotesPage().CreateSupportFragment(this);            
            Xamarin.Forms.Application.Current.Resources = new MyDictionary();
```

All subsequent calls to `CreateSupportFragment`:

```
            NoteEntryPage nep = new NoteEntryPage
            {
                BindingContext = note
            };
            nep.Parent = Xamarin.Forms.Application.Current;
                        
            AndroidX.Fragment.App.Fragment noteEntryPage = nep.CreateSupportFragment(this);
```

I'm leaving this issue open to remind me to update the native forms doc next week.

**Comment by davidbritch** [comment]
Also, set page.Parent to `null` after the support fragment has been created, to stop a memory leak:

```
            NoteEntryPage noteEntryPage = new NoteEntryPage
            {
                BindingContext = note
            };
            noteEntryPage.Parent = Xamarin.Forms.Application.Current;

            AndroidX.Fragment.App.Fragment noteEntryFragment = noteEntryPage.CreateSupportFragment(this);
            SupportFragmentManager
                .BeginTransaction()
                .AddToBackStack(null)
                .Replace(Resource.Id.fragment_frame_layout, noteEntryFragment)
                .Commit();

            noteEntryPage.Parent = null;
```

**Comment by kanderson-wellbeats** [comment]
Thanks @davidbritch, sounds good. It kind of bugs me that if you instantiate and set the RD in one exactly one place (for example where Forms.Init is first called) and then later on even once forget to do the extra handling of the Parent you'll accidentally wipe out the RD for all future pages. I'll do my best to avoid that by bundling this boilerplate into a parent class so I don't have to worry about it but if this could somehow be given a more robust solution I think it would be a valuable addition to the (already great) Native Forms approach.

**Comment by kanderson-wellbeats** [comment]
Actually now that you've given me the solution to my original problem I realize another difficulty. Setting the RD in code and not in XAML means I can't use StaticResource, so I'm left with DynamicResource which may have a larger performance cost without merit and also Intellisense in XAML for Keys breaks. :\

**Comment by kanderson-wellbeats** [comment]
I figured out I can get exactly what I wanted by subclassing Xamarin.Forms.Application and putting my ResourceDictionary in its XAML just like in a normal Forms app. I then manually set the static Xamarin.Forms.Application.Current property to an instance of my Forms.Application near where I do Forms.Init and then did the same Parent property handling described above. I now get:
- Minimum of code repetition
- Minimum number of instances of my ResourceDictionary
- StaticResource (preferred over DynamicResource)
- Intellisense in the XAML on the keys

**Comment by davidbritch** [comment]
Hi @kanderson-wellbeats 

Glad you figured it out. I came to the same realisation after I finished work on Friday, and was going to tell you the exact same thing today.

The doc will get updated, this week, to reflect all this.
