### ISSUE TITLE
Remaing reference to "master" should be removed

### ISSUE THREAD

**Issue by gkarabin** [MicrosoftDocs/xamarin-docs#3226]
This page has one remaining reference to the word "master" in the sentence:

> On iOS, the navigation bar is present at the top of the page and has a button that navigates to the detail page. In addition, the active detail page can be navigated to by swiping the **_master_** page to the left.

Given the recent change to remove the word "master" from Xamarin.Forms, I think this is an oversight.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 74e39183-f10a-d07e-9313-b5b3466dfa09
* Version Independent ID: 6719875a-ef95-b55c-42ef-9e0ab063eb4b
* Content: [Xamarin.Forms FlyoutPage - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/navigation/flyoutpage)
* Content Source: [docs/xamarin-forms/app-fundamentals/navigation/flyoutpage.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/app-fundamentals/navigation/flyoutpage.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @gkarabin 

Agreed! Thanks for pointing this out. I've updated the doc, in a PR that will go live later today.
