### ISSUE TITLE
Missing info.plist references for Visual Studio

### ISSUE THREAD

**Issue by dogoodson** [MicrosoftDocs/xamarin-docs#3227]
### Doc issue description

https://docs.microsoft.com/en-us/xamarin/ios/app-fundamentals/property-lists

These docs for `info.plist` are very specific to VS for Mac. They neglect to reference or provide links to the VS equivalent steps. As someone using VS and new to `info.plist`, I had to dig to find that I need to use a special editor in VS to achieve the same: https://developercommunity.visualstudio.com/comments/651598/view.html 

If such a doc already exists, it should be added under Related Links of this page.

**Comment by davidbritch** [comment]
[Microsoft support for Xamarin](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin) will end on May 1, 2024 for all Xamarin SDKs including Xamarin.Forms. In preparation for this, all issues and PRs in this repository are being closed.

.NET MAUI is the replacement for Xamarin.Forms, and it's documentation can be found [here](https://learn.microsoft.com/dotnet/maui/?view=net-maui-8.0).
