### ISSUE TITLE
project not building due No resource found that matches the given name: attr errors

### ISSUE THREAD

**Issue by BDTomasz** [MicrosoftDocs/xamarin-docs#323]
Using VS2017 - PC (15.7.2), have API level 27 (sdk and google apis intel sys image), same for API 26 and API 21 installed. I tried to follow the article to change the navigation bar back arrow colors, created values-v21 styles.xml file, have a few attributes there, minimum android and target set both to API level 21 and I am unable to build  
No resource found that matches the given name: attr  'statusBarColor'
No resource found that matches the given name: attr  'textColorPrimary'
my proj is using latest Android nuget packages, and Xamarin Forms 2.5... this is just ridiculous!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 87b678e7-5336-db4f-02ac-db6d2115ebec
* Version Independent ID: 5434c705-8fa7-f2ed-e358-6c05d915cde0
* Content: [Material Theme - Xamarin](https://docs.microsoft.com/en-us/xamarin/android/user-interface/material-theme)
* Content Source: [docs/android/user-interface/material-theme.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/android/user-interface/material-theme.md)
* Service: **unspecified**
* Product: **xamarin**
* GitHub Login: @mgmclemore
* Microsoft Alias: **mamcle**

**Comment by mgmclemore** [comment]
Hi @BDTomasz, it looks like you've found a bug. This repository is only for documentation-specific issues: could you please report your build error at [Developer Community](https://developercommunity.visualstudio.com/spaces/8/index.html) (click **Report a problem**). Thank you!
