### ISSUE TITLE
WebView Dynamically Sized

### ISSUE THREAD

**Issue by contravarianceisuseful** [MicrosoftDocs/xamarin-docs#3235]
There seems to be quite a lot of buzz about wanting a way to to view HTML that resizes the WebView to fit the content. Most solution involve custom renderers and are platform specific. Having to explicitly define the width and height when inside stack layouts is frustrating. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ef31dc71-3610-6c18-2bda-d0bb70804c92
* Version Independent ID: 02f7dc7b-541b-4b82-b33c-4e974fb94d8c
* Content: [Xamarin.Forms WebView - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/webview?tabs=windows)
* Content Source: [docs/xamarin-forms/user-interface/webview.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/webview.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @contravarianceisuseful 

That's feedback for the product team. I'd recommend you log an enhancement request in the [engineering repo](https://github.com/xamarin/Xamarin.Forms/). Thanks!
