### ISSUE TITLE
SafeAreaInsets and orientation change

### ISSUE THREAD

**Issue by chrisgull** [MicrosoftDocs/xamarin-docs#3238]
It's not clear from this doc page how display orientation change impacts SafeAreaInsets, and how it should be handled.
Page.Padding obviously follows the page orientation, whereas the physical notches on a display do not.

When I customize my Page.Padding, say for layout reasons, do I update it for each orientation change? 
Or should Page.Padding be reserved for safe area insets only?
Is OnAppearing called for each orientation change? (That does not seem to be the case.)
Thanks,
Lars

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c250f813-4a81-7c22-e42c-eeb328aeaba6
* Version Independent ID: b9db6a09-f815-4242-32af-68b937919f73
* Content: [Safe Area Layout Guide on iOS - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/platform/ios/page-safe-area-layout)
* Content Source: [docs/xamarin-forms/platform/ios/page-safe-area-layout.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/platform/ios/page-safe-area-layout.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
> When I customize my Page.Padding, say for layout reasons, do I update it for each orientation change?

Yes.

> Or should Page.Padding be reserved for safe area insets only?

If you want Xamarin.Forms to manage the safe area insets for you, it's advisable to not change the Padding property. Instead, you could set the Padding or Margin property on your root layout.

> Is OnAppearing called for each orientation change? (That does not seem to be the case.)

No. It's called when the page is about to appear on the screen. See https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/layouts/device-orientation?tabs=macos#reacting-to-changes-in-orientation for how to react to orientation changes. It's not ideal, but it's something that will change in MAUI.
