### ISSUE TITLE
The Application Always records 72BPM

### ISSUE THREAD

**Issue by PatrickRyder** [MicrosoftDocs/xamarin-docs#324]
I have got this application building and working and deploying to a physical iPhone 6 which is paired to a Watch.  Everything builds and appears to run okay.  However, it always records 72BPM, regardless of my actual BPM.  The connection between the application and the Watch appears to be working because the application knows when I turn off heart-rate permission and knows when I re-enable it.

If I open the Apple Health application, the true heart-rate values have been recorded as you would expect.

Any ideas why this application always seems to get 72 BPM?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e64bf78d-d9ed-e631-b96e-08e680c5dde7
* Version Independent ID: e3e79181-5b8e-9746-14ac-9a6fa6420766
* Content: [HealthKit - Xamarin](https://docs.microsoft.com/en-us/xamarin/ios/platform/healthkit)
* Content Source: [docs/ios/platform/healthkit.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/ios/platform/healthkit.md)
* Service: **unspecified**
* Product: **xamarin**
* GitHub Login: @bradumbaugh
* Microsoft Alias: **brumbaug**

**Comment by bradumbaugh** [comment]
Hi @PatrickRyder, this sample doesn't include any code designed to update the heart rate on the iPhone to match what the watch is collecting. Hope this helps!

**Comment by PatrickRyder** [comment]
Sorry, that was a misunderstanding on my part. Now I have got further with Apple Watch development, I realise that a lot more code is needed to get an updating heart-rate.
