### ISSUE TITLE
ControlTemplate.ElementTemplateContent not documented

### ISSUE THREAD

**Issue by Cfun1** [MicrosoftDocs/xamarin-docs#3240]
### Doc issue description

`ControlTemplate.ElementTemplateContent` is not documented.

**Comment by davidbritch** [comment]
I just searched the 5.0 branch. There's no references to `ElementTemplateContent`.

**Comment by Cfun1** [comment]
@davidbritch you're right I cannot find it in the code either, maybe it is a bug in intelisense

![ControlTemplateContent](https://user-images.githubusercontent.com/15718354/108055797-c0d7e100-7050-11eb-8166-d09e39bcc080.png)
