### ISSUE TITLE
No C# examples for RadioButton Constructor

### ISSUE THREAD

**Issue by contravarianceisuseful** [MicrosoftDocs/xamarin-docs#3242]
Page lacks example of a C# example. Only contains XAML examples. An example using calling the RadioButton contructor from C# would be nice. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a688fe91-33ad-efea-aa29-d56b3c11b42a
* Version Independent ID: c0e81ed5-0eb5-a8cc-9eb6-7baf7e464878
* Content: [Xamarin.Forms RadioButton - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/radiobutton)
* Content Source: [docs/xamarin-forms/user-interface/radiobutton.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/radiobutton.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @contravarianceisuseful 

If you take a look at the sample linked to from the page, there's an example of using `RadioButton`s from C# - https://github.com/xamarin/xamarin-forms-samples/blob/master/UserInterface/RadioButtonDemos/RadioButtonDemos/GroupedRadioButtonsPageCode.cs

The vast majority of our users use XAML, hence it's unlikely there'll be C# examples in docs moving forwards.

**Comment by contravarianceisuseful** [comment]
Thanks. That's a shame. I personally find the XAML pretty janky, especially
for dynamic layouts. I use C# wherever I can but I guess I must be in the
minority.
