### ISSUE TITLE
There are two small issues in this page

### ISSUE THREAD

**Issue by michael-hll** [MicrosoftDocs/xamarin-docs#3243]
#1: In step 7, it should be under the Views folder
#2: In the code of step 13, the below line should be removed, or will raise build errors:
using Newtonsoft.Json;

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7dc72705-2668-156f-d214-1a35d5a2ea4d
* Version Independent ID: 993ba392-f860-1a29-7d62-0dc1efbf6f0e
* Content: [Perform navigation in a Xamarin.Forms application - Xamarin](https://docs.microsoft.com/en-us/xamarin/get-started/quickstarts/navigation?pivots=macos)
* Content Source: [docs/get-started/quickstarts/navigation.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/get-started/quickstarts/navigation.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @michael-hll 

Thanks for pointing this out, and apologies for the errors. I've fixed them in a PR that should be live in the next ten minutes.
