### ISSUE TITLE
Incorrect image shown for Step 18

### ISSUE THREAD

**Issue by mlichtenberg** [MicrosoftDocs/xamarin-docs#3244]
Step 18 states "In Solution Explorer, in the Notes project, double-click AppShell.xaml to open it:".  However, the associated image shows App.xaml instead of AppShell.xaml.  

Similary, Step 22 states "In Solution Explorer, in the Notes project, double-click App.xaml to open it:".  The associated image shows AppShell.xaml instead of App.xaml.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 88d9cae7-e913-cf8f-7275-82c3192103bf
* Version Independent ID: 40f2fb5f-25e1-6174-b545-da749f38ed47
* Content: [Create a Xamarin.Forms application quickstart - Xamarin](https://docs.microsoft.com/en-us/xamarin/get-started/quickstarts/app?pivots=windows)
* Content Source: [docs/get-started/quickstarts/app.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/get-started/quickstarts/app.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @mlichtenberg 

Thanks for pointing this out. I've just fixed it in a PR that will go live in about 10 minutes.
