### ISSUE TITLE
Doc says UWP does not support hot reload, but linked issue says it's available...

### ISSUE THREAD

**Issue by blep** [MicrosoftDocs/xamarin-docs#3245]
In limitation section: "Other Xamarin.Forms targets, such as UWP and macOS, are not yet supported."
But linked [issue](https://developercommunity.visualstudio.com/idea/661682/xaml-hot-reload-for-xamarinforms-on-uwp.html) says it's available.

Is this information out of date for UWP? (I'm new to UWP/Xamarin).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b74184fd-ca8a-11fa-ed37-91235fc59401
* Version Independent ID: 87f197b8-20c6-4825-18e4-86562bb2523c
* Content: [XAML Hot Reload for Xamarin.Forms - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/xaml/hot-reload)
* Content Source: [docs/xamarin-forms/xaml/hot-reload.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/xaml/hot-reload.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @maddyleger1
* Microsoft Alias: **maleger**

**Comment by davidbritch** [comment]
Hi @blep 

First the bad news. The doc is correct. While hot reload works for UWP apps, it doesn't work for UWP apps written in Xamarin.Forms.

Now the good news. Hot reload will work for UWP apps written in Xamarin.Forms in Visual Studio 16.9 (currently available as a preview release).

**Comment by blep** [comment]
Thanks for clarifying that. I was really confused why I couldn't get it to work.
