### ISSUE TITLE
Initialization of the database isn't awaited and exceptions will crash your app

### ISSUE THREAD

**Issue by rickclephas** [MicrosoftDocs/xamarin-docs#3247]
# Issues

> **TLDR**: Please don't use the `TodoItemDatabase ` example code.

The example code in the documentation has some major issues that can cause weird exceptions.
Take the following example code:
```c#
var todoItems = await new TodoItemDatabase(). GetItemsAsync();
```
Which can result in the following exception:
```
SQLite.SQLiteException: no such table: TodoItem
```
Since the creation of the `TodoItem` table inside the `InitializeAsync` method isn't await the query inside the `GetItemsAsync` method is run before the table is created.

Due to #2550 that also means the `CreateTablesAsync` call is never executed. 
Which will cause the query to not only fail the first time but every time.

Although not very clear at first why this might happen there is an exception to inform you something went wrong.
It gets worse when you start adding init code that might throw exceptions.

For the sake of this example lets us the following `InitializeAsync`:
```c#
async Task InitializeAsync()
{
    if (!initialized)
    {
        if (!Database.TableMappings.Any(m => m.MappedType.Name == typeof(TodoItem).Name))
        {
            await Database.CreateTablesAsync(CreateFlags.None, typeof(TodoItem)).ConfigureAwait(false);
            // Lets pretend we are doing something that will throw an exception
            throw new Exception("Some exception during init");
        }
        initialized = true;
    }
}
```

Now like a good developer we try to handle exceptions as best as we can so we write the following code:
```c#
try
{
    var database = new TodoItemDatabase();
    // Some code that uses the database (which isn't required to demonstrated the issue) 
}
catch (Exception e)
{
    // We'll catch the exception here right?
}
```

Well due to the way the `InitializeAsync` is called:
```c#
InitializeAsync().SafeFireAndForget(false);
```
this exception isn't caught and will actually crash your app.

# Proposed solution

> Also see #2550

To fix these issue the initialization of the database should be awaited before any operation can be performed.
An easy way to do this would be by creating an async method that returns the database instance. 
Pseudo code:
```c#
public static async Task<TodoItemDatabase> GetInstance()
{
    // 1. (Optionally) check if there is already an instance and return it
    // 2. Create a new instance
    // 3. Run any initialization code
    // 4. Keep track of the instance and return it
}
```

This way you get something like the following to use the database:
```c#
try
{
    var database = await TodoItemDatabase.GetInstance();
    // Some code that uses the database (which isn't required to demonstrated the issue) 
}
catch (Exception e)
{
    // Now we do get the exceptions that are thrown during init
}
```

**Note**: in multithreaded applications the `GetInstance` method should use some kind of lock to prevent the initialization from being run multiple times.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bdcea465-138a-d586-5297-dc93370826b3
* Version Independent ID: a41a6f67-0675-036f-0781-13b9165d3848
* Content: [Xamarin.Forms Local Databases - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/data-cloud/data/databases)
* Content Source: [docs/xamarin-forms/data-cloud/data/databases.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/data-cloud/data/databases.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @profexorgeek
* Microsoft Alias: **jusjohns**

**Comment by davidbritch** [comment]
Hi @rickclephas 

Thanks for opening the issue. I agree that there's a problem here. Because the database is essentially a shared resource, I've used asynchronous lazy initialization to fix the issue. This ensures that if an exception is thrown when the database is initialised, it can be caught and dealt with.

I've made a PR that fixes this issue. However, there's a problem with the CI at the moment so it won't get merged until later in the week. When it gets merged this issue will be closed, so you'll know it's fixed then.
