### ISSUE TITLE
Sample Code Doesn't Work

### ISSUE THREAD

**Issue by Eltee-Taiwo** [MicrosoftDocs/xamarin-docs#3249]
I tried to follow though using the attached video demonstration but couldn't get the deep links to work. I noticed that the documentation also differs from the video in that it says you have to add domain entries to your info.plist file. Since I wasn't sure if that was required or not, I decided to clone the sample repo and ran it on my emulator but I'm also unable to get the deep links to work. Nothing pops up in my search after adding a todo item. Debugging shows that it goes through and creates the app link but with no return type from AppLinks.RegisterLink I don't know if something is failing behind the scenes. Are you able to get this work using just the sample code?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 42da09a1-6b69-6787-487e-e7e9915caec5
* Version Independent ID: d335d34e-4e88-a4c7-cd97-0a7cfbd45269
* Content: [Application Indexing and Deep Linking - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/deep-linking#setup)
* Content Source: [docs/xamarin-forms/app-fundamentals/deep-linking.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/app-fundamentals/deep-linking.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Deep linking has changed since the video was made, so I've removed the video in a PR that will go live later this week.

The sample should work once you set the Entitlements.plist file as the custom entitlements file for signing the bundle. However, it's not possible to do this in the sample and still distribute it, because it will fail to build without having provisioning profiles setup on your machine.

**Comment by Eltee-Taiwo** [comment]
I figured that was the case and created a new project following the documentation. But unfortunately, I still can't get it to work.

My universal links, and clicking on a link opens the app but my deep links still don't seem to work. I know it's not much to go on but do you have any idea why this would be the case?
