### ISSUE TITLE
Consfusing screenshot/statement for DisplayActionSheet() that is the same on all platforms

### ISSUE THREAD

**Issue by Cfun1** [MicrosoftDocs/xamarin-docs#3253]
### Doc issue description
The below screenshot could be confusing/misleading, people might think that the part of the right (dark one) is done on Android (since previous screenshots are showing iOS and Android renderer aside-by-side), although I it is not the case, because native dialogs on Android don't have a similar default look, It is iOS platform specific: https://developer.apple.com/design/human-interface-guidelines/ios/views/action-sheets/ and Xamarin.Forms is not replicating this same design on Android.

So it should be highlighted that the screenshot is not on Android, the same for this paragraph it is only true for iOS:

> The destroy button is rendered differently than the others, and can be left null or specified as the third string parameter. The following example uses the destroy button:

![](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/pop-ups-images/action2.png#lightbox)

[File in question: user-interface/pop-ups.md#L74](https://github.com/MicrosoftDocs/xamarin-docs/edit/live/docs/xamarin-forms/user-interface/pop-ups.md#L74)

Details: https://stackoverflow.com/a/66412914/
Live: https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/pop-ups#guide-users-through-tasks

**Comment by davidbritch** [comment]
Hi @Cfun1 

Thanks for pointing this out. I've fixed it a PR that will go live later this week. When that happens, this issue will be closed.
