### ISSUE TITLE
Video and Audio APIs are missing.

### ISSUE THREAD

**Issue by JakeCroz1** [MicrosoftDocs/xamarin-docs#3254]
Why are there no Video and Audio APIs available in xamarin essentials?
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c420b152-7303-918a-dbc8-8d1e539c64ec
* Version Independent ID: fe85e24f-c3fc-3763-b1db-6b360fb08067
* Content: [Xamarin.Essentials - Xamarin](https://docs.microsoft.com/en-us/xamarin/essentials/?context=xamarin/xamarin-forms)
* Content Source: [docs/essentials/index.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/essentials/index.md)
* Product: **xamarin**
* Technology: **xamarin-essentials**
* GitHub Login: @jamesmontemagno
* Microsoft Alias: **jamont**

**Comment by davidbritch** [comment]
Hi @JakeCroz1 

See https://github.com/xamarin/Essentials/issues/1704 and https://github.com/xamarin/Essentials/issues/1414, particularly the comment "I don't think there's any action here for now, it's simply not high enough in the priority list based on customer feedback we've received at this time."
