### ISSUE TITLE
No description provided for ItemsViewScrolledEventArgs properties

### ISSUE THREAD

**Issue by Cfun1** [MicrosoftDocs/xamarin-docs#3256]
### Doc issue description
There is no definition, no explanation or details about: HorizontalDelta VerticalDelta HorizontalOffset VerticalOffset FirstVisibleItemIndex CenterItemIndex LastVisibleItemIndex in:

### Source:
https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/carouselview/scrolling.md
https://github.com/xamarin/Xamarin.Forms-api-docs/blob/master/docs/Xamarin.Forms/ItemsViewScrolledEventArgs.xml
             
### Live
https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/carouselview/scrolling
https://docs.microsoft.com/en-us/dotnet/api/xamarin.forms.itemsviewscrolledeventargs?view=xamarin-forms

**Comment by davidbritch** [comment]
Hi @Cfun1 

I've added a description of the properties to the doc, in a PR that will go live once it's been built by the CI system. As for the API docs (which also power intellisense), they are a responsibility for the engineers to update.

**Comment by Cfun1** [comment]
@davidbritch thanks, I understand that it will be fixed but out of curiosity I was looking at the pr in question in prs and also in commits of different branches but could not find it. Is there any internal magic behind that or I have just missed something ? :)

**Comment by davidbritch** [comment]
@Cfun1 

This repo only has PRs that community members make. There's also a private repo that we use internally (there's all kinds of tooling that runs on PRs on the internal repo, that's only licensed for Microsoft staff use). The two repos sync with each other whenever a change is made to one of them.

**Comment by Cfun1** [comment]
Thank you for the explanation @davidbritch I appreciate :)
