### ISSUE TITLE
FileSaver API is very needed

### ISSUE THREAD

**Issue by Dmitiry-hub** [MicrosoftDocs/xamarin-docs#3257]
Hello, Microsoft end .NET Xamarin Community!
So, FilePicker API is cool, but Xamarin Forms need a FileSaver API for save files.
Please implement this in Xamarin.Essentials.

Thanks!
Best wishes!

**Comment by davidbritch** [comment]
Hi @Dmitiry-hub 

Please make feature requests in the [Essentials engineering repo](https://github.com/xamarin/Essentials). Thanks!
