### ISSUE TITLE
Media exceptions

### ISSUE THREAD

**Issue by IeuanWalker** [MicrosoftDocs/xamarin-docs#3258]
Would be good if possible exceptions can be listed. At the moment there is no way of knowing what expcetions can be excepted.

Presume they are the same as [GeoLocation](https://docs.microsoft.com/en-us/xamarin/essentials/geolocation?context=xamarin%2Fxamarin-forms&tabs=ios)?
![image](https://user-images.githubusercontent.com/6544051/109982881-3b178f00-7cfa-11eb-927f-bbf3fcc4615e.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e4b43ab7-fd40-ba56-c9ab-5de2eb1aad7f
* Version Independent ID: 6c9c7c48-4401-cb25-5cda-637718a22961
* Content: [Xamarin.Essentials: Media Picker - Xamarin](https://docs.microsoft.com/en-us/xamarin/essentials/media-picker?context=xamarin%2Fxamarin-forms&tabs=android)
* Content Source: [docs/essentials/media-picker.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/essentials/media-picker.md)
* Product: **xamarin**
* Technology: **xamarin-essentials**
* GitHub Login: @jamesmontemagno
* Microsoft Alias: **jamont**

**Comment by jamesmontemagno** [comment]
Added in :)
