### ISSUE TITLE
System language needs to be in english for Windows Hypervisor Platform to be detected

### ISSUE THREAD

**Issue by NadeauJessy** [MicrosoftDocs/xamarin-docs#326]
I tried the solution for the support of Google Android emulator in visual studio preview 15.8.0 Preview 1.1.
Did everything but the message in visual studio preview was still to enable Windows Hypervisor Platform.
In french, the feature name is "Plateforme d'hyperviseur windows"(As i remember).
I thought that it might be the problem so I switched my system language to english and every thing worked after.

You might need to look into this bug since it should be easy to fix.

So far everything works great.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4e37d642-2051-8d70-9968-dfb484122a6a
* Version Independent ID: 178ea80c-2b99-0c44-eeb6-9db319439b33
* Content: [Android Emulator Hardware Acceleration - Xamarin](https://docs.microsoft.com/en-us/xamarin/android/get-started/installation/android-emulator/hardware-acceleration?tabs=vswin)
* Content Source: [docs/android/get-started/installation/android-emulator/hardware-acceleration.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/android/get-started/installation/android-emulator/hardware-acceleration.md)
* Service: **unspecified**
* Product: **xamarin**
* GitHub Login: @mgmclemore
* Microsoft Alias: **mamcle**

**Comment by mgmclemore** [comment]
Hi @NadeauJessy, this repository is only for documentation-specific issues. If you think you've found a bug, please report it at [Developer Community](https://developercommunity.visualstudio.com/spaces/8/index.html) (click **Report a problem**). Thank you!

**Comment by bunstjan** [comment]
Changing the system language to english did the trick for me as well. I couldn't even find the checkbox for "Windows Hypervisor Platform" with system language set to Slovenian.
