### ISSUE TITLE
Better information on NeutralResourcesLanguage setting in the Specify the default culture section

### ISSUE THREAD

**Issue by solomonfried** [MicrosoftDocs/xamarin-docs#3260]
[Enter feedback here]

In the document you state the following

The documentation states that in order for the system to fall back to the default resource file in the event that a resource file for the current culture is not found, the developer must provide a NeutralResourcesLanguage in Assembly.cs as follows.
`[assembly: NeutralResourcesLanguage("en-US")]`

(BTW, a default Xamarin project does not contain an AssemblyInfo,cs file)

However I have found that the statement needs to be added to the project in which the Resource file resides,
In my solution I have a separate "GlobalResource" project that contains  StringResources.resx, StringResources.it.resx, .....

If I place the directive in my App.xaml.cs in the Shared project, and set my Culture to "ko" (I do not have a resource file for "ko")
the application would abend with a null reference exception when I tried to access a resource by name.

To remedy this, I added a Class (AssemblyInfo.cs) to the GlobalResource project, and added the 
`[assembly: NeutralResourcesLanguage("en-US")]`
In that class.

Once I did so, the app falls back to the default as expected and uses a language file if it is present,

So to be clear, the NeutralResourcesLanguage needs to be set in the project containing the resource files used by the application.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: af66394d-81c5-0c2e-1682-a2bb7eeb3c3e
* Version Independent ID: 27542a45-2f25-4042-cf48-b9517025635c
* Content: [String and Image Localization in Xamarin.Forms - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/localization/text)
* Content Source: [docs/xamarin-forms/app-fundamentals/localization/text.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/app-fundamentals/localization/text.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @profexorgeek
* Microsoft Alias: **jusjohns**

**Comment by davidbritch** [comment]
Hi @solomonfried 

I just checked and the blank app Xamarin.Forms template, in both VS2019 and VSMac, creates an *AssemblyInfo.cs** file. Regardless, I see your point about where the neutral resource language attribute needs to be placed. I'll get the doc updated.
