### ISSUE TITLE
Minor tutorial mistake

### ISSUE THREAD

**Issue by rafaelsanchezsouza** [MicrosoftDocs/xamarin-docs#3264]
There's a mistake in the code on the file: NoteEntryPage.xaml.cs

Where it's written:
async void OnSaveButtonClicked(object sender, EventArgs e)
{
    var note = (Note)BindingContext;
    note.Date = DateTime.UtcNow;
    if (!string.IsNullOrWhiteSpace(note.Text))
    {
        await App.Database.SaveNoteAsync(note);
    }

    // Navigate backwards
    await Shell.Current.GoToAsync("..");
}

Should be: 
async void OnSaveButtonClicked(object sender, EventArgs e)
        {
            var note = (Note)BindingContext;
            note.Date = DateTime.UtcNow;

            if (string.IsNullOrWhiteSpace(note.Text))
            {
                await App.Database.SaveNoteAsync(note);
            }
            else
            {
                // Update the file.
                await App.Database.SaveNoteAsync(note);
            }

            // Navigate backwards
            await Shell.Current.GoToAsync("..");
        }

Otherwise the note only gets added if it's a blank note

: )

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5ce30880-c4f0-78f7-1ee0-6507e378201e
* Version Independent ID: a6ad2818-c0d2-e3ef-1262-e143d49cc348
* Content: [Store data in a local SQLite.NET database - Xamarin](https://docs.microsoft.com/en-us/xamarin/get-started/quickstarts/database)
* Content Source: [docs/get-started/quickstarts/database.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/get-started/quickstarts/database.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @rafaelsanchezsouza 

I just double checked and the code in the doc/sample is correct. The `NoteDatabase.SaveNoteAsync` method handles whether to save a new note or update an existing note. All `NoteEntryPage` needs to do is call that method, provided the user has entered a note.

**Comment by rafaelsanchezsouza** [comment]
Hi @davidbritch !

Thanks for your answer. 
I must admit I'm not that proficient in reading code! My observation was made based on experimentation, sorry if it was inappropriate.

However I must point out that the change I suggested actually worked for me (and that all it does is to guarantee ```NoteDatabase.SaveNoteAsync``` will be called), while the actual version doesn't work for me.

Also, you mentioned that the ```NoteDatabase.SaveNoteAsync``` method handles it, however, will it be called if the ```string``` is not null or whitespace?

**Comment by davidbritch** [comment]
Hi @rafaelsanchezsouza 

Here's the method from the doc:

```csharp
async void OnSaveButtonClicked(object sender, EventArgs e)
{
    var note = (Note)BindingContext;
    note.Date = DateTime.UtcNow;
    if (!string.IsNullOrWhiteSpace(note.Text))
    {
        await App.Database.SaveNoteAsync(note);
    }

    // Navigate backwards
    await Shell.Current.GoToAsync("..");
}
```

It's saying that `SaveNoteAsync` will be called provided that `note.Text` isn't null or whitespace. In other words, only save the note if there's some text present. If there isn't any text present, don't save the note because there's no point saving whitespace to the database.

Hope this helps?
