### ISSUE TITLE
Drag and Drop documentation does not mention this feature is experimental

### ISSUE THREAD

**Issue by mnxamdev** [MicrosoftDocs/xamarin-docs#3265]
[Enter feedback here]
However, we just tried to use this feature and it seems to still be in experimental phase. Also, note the following github issue mentioning experimental flags are still in play:
https://github.com/xamarin/Xamarin.Forms/issues/11663

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f07c1436-d8cf-8f5e-939b-3da68122f83e
* Version Independent ID: ba4d582d-447d-017c-7b36-d18357e83187
* Content: [Add drag and drop gesture recognizers - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/gestures/drag-and-drop)
* Content Source: [docs/xamarin-forms/app-fundamentals/gestures/drag-and-drop.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/app-fundamentals/gestures/drag-and-drop.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @mnxamdev 

Afraid it's not experimental. It used to be, but it stopped being experimental once Xamarin.Forms 5.0 was released.
