### ISSUE TITLE
webview source attribuate has http://www.xamarin.com/, missing https which throws the non-secure error

### ISSUE THREAD

**Issue by edwardm** [MicrosoftDocs/xamarin-docs#3266]
In the Layout section, you have some webview sample code with the source attribute having the following value: http://www.xamarin.com/, but because it is not https, is throws a security error. Perhaps you meant for this to happen to showcase the mobile platforms complaining about non-secure sites? Or, maybe the docs need to have https in it?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ef31dc71-3610-6c18-2bda-d0bb70804c92
* Version Independent ID: 02f7dc7b-541b-4b82-b33c-4e974fb94d8c
* Content: [Xamarin.Forms WebView - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/webview?tabs=windows)
* Content Source: [docs/xamarin-forms/user-interface/webview.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/webview.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @edwardm 

Thanks for pointing this out - I've updated the samples and doc to use HTTPS, in a PR that will go live later today.
