### ISSUE TITLE
Sample Project not executable

### ISSUE THREAD

**Issue by krema01** [MicrosoftDocs/xamarin-docs#3268]
[
Unfortunately, after trying everything I could think of, I have to give up trying to run the CognitiveSpeechService Sample Project.
The Program fails to write to the file "CognitiveSpeechService.csproj.FileListAbsolute.txt" as  the filename exceeds the OS max path limit. 
]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2dac850d-ffd6-8007-83b2-376921c809b2
* Version Independent ID: 3d210339-171e-ee8a-98cb-7367e1eb33b5
* Content: [Speech recognition using the Speech Service API - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/data-cloud/azure-cognitive-services/speech-recognition)
* Content Source: [docs/xamarin-forms/data-cloud/azure-cognitive-services/speech-recognition.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/data-cloud/azure-cognitive-services/speech-recognition.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @profexorgeek
* Microsoft Alias: **jusjohns**

**Comment by davidbritch** [comment]
Hi @krema01 

Which platform is your problem on?

**Comment by krema01** [comment]
I am working on windows 10 but executing the android version of the
application leads to the errors

**Comment by davidbritch** [comment]
Hi @krema01 

I managed to run the app in the Android emulator in Windows 10 by copying the sample to the root folder of my drive. Alternatively, you could [Enable long paths](https://docs.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation#enable-long-paths-in-windows-10-version-1607-and-later).
