### ISSUE TITLE
The sample code breaks on UWP

### ISSUE THREAD

**Issue by javanjoel** [MicrosoftDocs/xamarin-docs#3269]
When trying to write the file I get the error message:
System.IOException:
The handle with which this oplock was associated has been closed.  The oplock is now broken

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e4b43ab7-fd40-ba56-c9ab-5de2eb1aad7f
* Version Independent ID: 6c9c7c48-4401-cb25-5cda-637718a22961
* Content: [Xamarin.Essentials: Media Picker - Xamarin](https://docs.microsoft.com/en-us/xamarin/essentials/media-picker?tabs=android)
* Content Source: [docs/essentials/media-picker.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/essentials/media-picker.md)
* Product: **xamarin**
* Technology: **xamarin-essentials**
* GitHub Login: @jamesmontemagno
* Microsoft Alias: **jamont**

**Comment by jamesmontemagno** [comment]
Can you please file and issue at http://github.com/xamarin/essentials  for problems with the library

**Comment by javanjoel** [comment]
@jamesmontemagno I figured since the code was on the page itself that the author would want to know.

But I will go and do as you asked.
