### ISSUE TITLE
Xamarin live player 

### ISSUE THREAD

**Issue by aymanabueideh** [MicrosoftDocs/xamarin-docs#327]
when i connect manually with iPhone and Xamarin live player does not reach the targeted iPhone . why there is not a popup message that tells me that my iPhone is not reachable   

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ca6cca9b-a408-04ba-ee7b-79d439e5d211
* Version Independent ID: 0888c982-7ffb-47aa-d989-952b22b9b756
* Content: [Troubleshooting - Xamarin](https://docs.microsoft.com/en-us/xamarin/tools/live-player/troubleshooting)
* Content Source: [docs/tools/live-player/troubleshooting.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/tools/live-player/troubleshooting.md)
* Service: **unspecified**
* Product: **xamarin**
* GitHub Login: @topgenorth
* Microsoft Alias: **toopge**

**Comment by conceptdev** [comment]
Hi @aymanabueideh, for product feedback and questions please visit the [Developer Community site](https://developercommunity.visualstudio.com/).
Thanks.
