### ISSUE TITLE
Unclear what impact the TranslucencyMode property has

### ISSUE THREAD

**Issue by darshanrampatel** [MicrosoftDocs/xamarin-docs#3270]
The screenshot looks (to me) like all 3 possible values of TranslucencyMode result in the same look:

![image](https://user-images.githubusercontent.com/14162899/111813993-d7808a80-88d1-11eb-8752-871e00bb0bd0.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a52cd5e-2cc8-0398-dcb3-db2607f11c1b
* Version Independent ID: c2586399-6b8c-78c6-e0da-fa3e35adb00a
* Content: [TabbedPage translucent tab bar on iOS - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/platform/ios/tabbedpage-translucent-tabbar)
* Content Source: [docs/xamarin-forms/platform/ios/tabbedpage-translucent-tabbar.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/platform/ios/tabbedpage-translucent-tabbar.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @darshanrampatel 

I see your issue - all three screenshots look the same at a glance. I ran the sample the page links to and when cycling through the translucency modes you can see that the Opaque mode is different. Now I've done that, the screenshot looks different to me - the background of the tab bar in Opaque mode looks white, while it's slightly grey for Default and Transparent.
