### ISSUE TITLE
Async streams must be declared with "await using var" (not "var" nor "using var") to utilize `IAsyncDisposable` implementation

### ISSUE THREAD

**Issue by mmarinchenko** [MicrosoftDocs/xamarin-docs#3273]
To improve code quality in Xamarin.Essentials documentation. See [Always call `FlushAsync` on `StreamWriter`(s) or `Stream`(s) before calling `Dispose`](https://github.com/davidfowl/AspNetCoreDiagnosticScenarios/blob/master/AsyncGuidance.md#always-call-flushasync-on-streamwriters-or-streams-before-calling-dispose) for details.

I file this issue from [File Picker](https://docs.microsoft.com/en-us/xamarin/essentials/file-picker) page but streams are also used on the following Xamarin.Essentials pages:
- [File System Helpers](https://docs.microsoft.com/en-us/xamarin/essentials/file-system-helpers)
- [Media Picker](https://docs.microsoft.com/en-us/xamarin/essentials/media-picker)
- [Screenshot](https://docs.microsoft.com/en-us/xamarin/essentials/screenshot)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bde8b00e-bef2-d10c-268f-2e49e236a89f
* Version Independent ID: dad8b07c-2227-c7ed-6369-d10d9b132e99
* Content: [Xamarin.Essentials: File Picker - Xamarin](https://docs.microsoft.com/en-us/xamarin/essentials/file-picker?context=xamarin%2Fxamarin-forms&tabs=android)
* Content Source: [docs/essentials/file-picker.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/essentials/file-picker.md)
* Product: **xamarin**
* Technology: **xamarin-essentials**
* GitHub Login: @jamesmontemagno
* Microsoft Alias: **jamont**

**Comment by jamesmontemagno** [comment]
@davidfowl is this accurate? Should I update this... is it different on mobile?

**Comment by mmarinchenko** [comment]
@jamesmontemagno I'm not David but still :)

There are async reads and async writes in the code. At the same time it (implicitly) flushes buffers synchronously. This is essentially not a bug but may have some negative performance impact if invoked on main thread in mobile scenario.
