### ISSUE TITLE
DragLeaveCommand and DragLeaveCommandParameter are not covered

### ISSUE THREAD

**Issue by Cfun1** [MicrosoftDocs/xamarin-docs#3277]
### Doc issue description
`DragLeaveCommand` and `DragLeaveCommandParameter` are not covered in the documentation.

Live: https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/gestures/drag-and-drop
Source: https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/app-fundamentals/gestures/drag-and-drop.md

**Comment by davidbritch** [comment]
Hi @Cfun1 

Thanks for pointing this out. I've updated the doc in a PR that will go live later today.
