### ISSUE TITLE
IsVisible is not available for ShellContent

### ISSUE THREAD

**Issue by sstahurski** [MicrosoftDocs/xamarin-docs#3278]
<TabBar>
    <ShellContent Title="Cats"
                  Icon="cat.png"
                  ContentTemplate="{DataTemplate views:CatsPage}" />
    <ShellContent Title="Dogs"
                  Icon="dog.png"
                  ContentTemplate="{DataTemplate views:DogsPage}"
                  IsVisible="False" />
    <ShellContent Title="Monkeys"
                  Icon="monkey.png"
                  ContentTemplate="{DataTemplate views:MonkeysPage}" />
</TabBar>

//CODE EXAMPLE

AppShell.xaml(162,162): Error XFC0009: No property, BindableProperty, or event found for "IsVisible", or mismatching type between value and property. (XFC0009) (DIOLink) XamlC

    <TabBar  x:Name="tabBar">
        <ShellContent Title="Read"      Icon="tab_readdio.png"      Route="ConnectPage"             ContentTemplate="{DataTemplate local:ConnectPage}"/>
        <ShellContent Title="Settings"  Icon="tab_settings.png"     Route="CondensedSettingsPage"   ContentTemplate="{DataTemplate local:CondensedSettingsPage}" IsVisible="False" />
        <ShellContent Title="About"     Icon="tab_about.png"        Route="AboutPage"               ContentTemplate="{DataTemplate local:AboutPage}" />
    </TabBar>

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ef7242a0-d46e-19ea-e22d-f327dcc9b3e9
* Version Independent ID: f050be8e-9413-19e7-5799-90a55c4e5bfb
* Content: [Xamarin.Forms Shell tabs - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/shell/tabs)
* Content Source: [docs/xamarin-forms/app-fundamentals/shell/tabs.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/app-fundamentals/shell/tabs.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @sstahurski 

I just modified Xaminals and tried the following code:

```
    <TabBar>
        <ShellContent Route="monkeys"
                      Style="{StaticResource MonkeysShell}"
                      Title="Monkeys"
                      Icon="monkey.png"
                      ContentTemplate="{DataTemplate views:MonkeysPage}"
                      IsVisible="False" />
        <ShellContent Route="elephants"
                      Style="{StaticResource ElephantsShell}"
                      Title="Elephants"
                      Icon="elephant.png"
                      ContentTemplate="{DataTemplate views:ElephantsPage}" />
        <ShellContent Route="bears"
                      Style="{StaticResource BearsShell}"
                      Title="Bears"
                      Icon="bear.png"
                      ContentTemplate="{DataTemplate views:BearsPage}" />
    </TabBar>
```

As you can see, the first `ShellContent` sets `IsVisible` to `false`. It built, it worked as expected (no Monkeys tab):

![Simulator Screen Shot - iPhone 11 - 2021-04-14 at 10 54 35](https://user-images.githubusercontent.com/8092460/114691860-0262d080-9d10-11eb-8418-1f711fe17346.png)

Normally, when this type of problem occurs it's due to a mismatch in your NuGet packages, so that might be something to look at (along with deleting your bin/obj folders).
