### ISSUE TITLE
Calling Azure AD protected API

### ISSUE THREAD

**Issue by Fresher900** [MicrosoftDocs/xamarin-docs#3280]
Hi,

Can Web Authenticator be used to obtain access_token for calling an Azure AD Protected API?
Also how do we manage the token life cycle? How do we storing access_token and using refresh token when using Web AUthenticator?

Thanks in advance

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1231a1e1-3734-9021-2cc7-eaf99478afca
* Version Independent ID: 01e5fdbe-0b15-4dbe-f8a0-ed40f8593302
* Content: [Xamarin.Essentials: Web Authenticator - Xamarin](https://docs.microsoft.com/en-us/xamarin/essentials/web-authenticator?tabs=android)
* Content Source: [docs/essentials/web-authenticator.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/essentials/web-authenticator.md)
* Product: **xamarin**
* Technology: **xamarin-essentials**
* GitHub Login: @Redth
* Microsoft Alias: **jodick**

**Comment by jamesmontemagno** [comment]
For Azure AD you would want to use the MSAL library which has built in support this. Else you would need to return and parse the data out and then call Azure AD specifically. This is  more of an Azure AD question than web authenticator though.

**Comment by davidbritch** [comment]
[Microsoft support for Xamarin](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin) will end on May 1, 2024 for all Xamarin SDKs including Xamarin.Forms. In preparation for this, all issues and PRs in this repository are being closed.

.NET MAUI is the replacement for Xamarin.Forms, and it's documentation can be found [here](https://learn.microsoft.com/dotnet/maui/?view=net-maui-8.0).
