### ISSUE TITLE
Is this correct? "Color.FromRgb for double RGB values from 0 to 1"

### ISSUE THREAD

**Issue by Auto72** [MicrosoftDocs/xamarin-docs#3281]
Is the following statement, reported on the page,  correct ?

"Color.FromRgb for double RGB values from 0 to 1"

or it should be:

"Color.FromRgb for double RGB values from 0 to 255" ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 94493505-cea9-cb6c-d2d7-cf6c66106558
* Version Independent ID: b416be62-e3ef-f69c-58b1-8fc621e19e0b
* Content: [Summary of Chapter 3. Deeper into text - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/creating-mobile-apps-xamarin-forms/summaries/chapter03)
* Content Source: [docs/xamarin-forms/creating-mobile-apps-xamarin-forms/summaries/chapter03.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/creating-mobile-apps-xamarin-forms/summaries/chapter03.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @Auto72 

Yes, that's correct. The overload that accepts `double` values expects them to be in the range 0-1.
