### ISSUE TITLE
Browse tab not working in default xamarin forms tabbed visual studio 2019 solution quickstart template

### ISSUE THREAD

**Issue by spacecat** [MicrosoftDocs/xamarin-docs#3282]
Hi,

I create a new xamarin forms vs2019 tabbed project but when I navigate to the "Browse" tab on my android device I don't see the list of items - it's just a blank page.

These are the items that should appear I think:

```
public class MockDataStore : IDataStore<Item>
    {
        readonly List<Item> items;

        public MockDataStore()
        {
            items = new List<Item>()
            {
                new Item { Id = Guid.NewGuid().ToString(), Text = "First item", Description="This is an item description." },
                new Item { Id = Guid.NewGuid().ToString(), Text = "Second item", Description="This is an item description." },
                new Item { Id = Guid.NewGuid().ToString(), Text = "Third item", Description="This is an item description." },
                new Item { Id = Guid.NewGuid().ToString(), Text = "Fourth item", Description="This is an item description." },
                new Item { Id = Guid.NewGuid().ToString(), Text = "Fifth item", Description="This is an item description." },
                new Item { Id = Guid.NewGuid().ToString(), Text = "Sixth item", Description="This is an item description." }
            };
        }
.
.
.
```
Am I missing something?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 88d9cae7-e913-cf8f-7275-82c3192103bf
* Version Independent ID: 40f2fb5f-25e1-6174-b545-da749f38ed47
* Content: [Create a Xamarin.Forms application quickstart - Xamarin](https://docs.microsoft.com/en-us/xamarin/get-started/quickstarts/app)
* Content Source: [docs/get-started/quickstarts/app.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/get-started/quickstarts/app.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by spacecat** [comment]
Found the problem:

https://github.com/xamarin/Xamarin.Forms/issues/13088

**Comment by davidbritch** [comment]
Hi @spacecat 

Glad you're all sorted. It wasn't exactly a great experience when I tried. First of all VS spent 5 mins installing some UWP updates (despite building for Android), before then erroring out because I didn't have API level 30 installed. Another 10 mins of installing API level 30, it worked fine.
