### ISSUE TITLE
All what have been explained is different  for What I got on my screen

### ISSUE THREAD

**Issue by tmimy** [MicrosoftDocs/xamarin-docs#3283]
[Enter feedback here]

I can't have Preview screen I tried all steps here with no success, actually many things shown here (like tab menue at the bottom of XAML page) is not shown on my device 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7008caa8-8acd-9d45-9689-f92b48e78bbf
* Version Independent ID: a94b2057-d8c4-eabd-ca9b-b0de07b468b8
* Content: [XAML Previewer for Xamarin.Forms - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/xaml/xaml-previewer/)
* Content Source: [docs/xamarin-forms/xaml/xaml-previewer/index.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/xaml/xaml-previewer/index.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @maddyleger1
* Microsoft Alias: **maleger**

**Comment by davidbritch** [comment]
Hi @tmimy 

The Previewer has been removed from both Visual Studio 2019 and Visual Studio for Mac, and replaced with XAML Hot Reload. A warning has been added to the top of the Previewer doc to point this out.
