### ISSUE TITLE
Missing break; in example code

### ISSUE THREAD

**Issue by JPZV** [MicrosoftDocs/xamarin-docs#3284]
In the [example code](https://docs.microsoft.com/en-us/xamarin/essentials/battery?tabs=android#using-battery) for checking the current battery information, there is a missing `break;` in the `switch` statement for the `Battery.State`:

**Current**:
```cs
switch (state)
{
    case BatteryState.Charging:
        // Currently charging
        break;
    case BatteryState.Full:
        // Battery is full
        break;
    case BatteryState.Discharging:
    case BatteryState.NotCharging:
        // Currently discharging battery or not being charged
        break;
    case BatteryState.NotPresent:
        // Battery doesn't exist in device (desktop computer)
    case BatteryState.Unknown:
        // Unable to detect battery state
        break;
}
```

**Should be**:
```cs
switch (state)
{
    case BatteryState.Charging:
        // Currently charging
        break;
    case BatteryState.Full:
        // Battery is full
        break;
    case BatteryState.Discharging:
    case BatteryState.NotCharging:
        // Currently discharging battery or not being charged
        break;
    case BatteryState.NotPresent:
        // Battery doesn't exist in device (desktop computer)
        break;
    case BatteryState.Unknown:
        // Unable to detect battery state
        break;
}
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 38198725-c8f2-3b90-d179-24f86284c4cb
* Version Independent ID: 1dd34451-25d2-9c50-a7f6-bb5b9f763ba0
* Content: [Xamarin.Essentials: Battery - Xamarin](https://docs.microsoft.com/en-us/xamarin/essentials/battery?tabs=android)
* Content Source: [docs/essentials/battery.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/essentials/battery.md)
* Product: **xamarin**
* Technology: **xamarin-essentials**
* GitHub Login: @jamesmontemagno
* Microsoft Alias: **jamont**

**Comment by jamesmontemagno** [comment]
Fixed up thanks!
