### ISSUE TITLE
The requirements is wrong.

### ISSUE THREAD

**Issue by lywyn** [MicrosoftDocs/xamarin-docs#3285]
System requirements state Xamarin.Forms 5.0 needed for changes only mode

My project was using XF 5.0.0.1931 One down from current version) and Hot Reload output showed;

```
WARN: (XXXXXX.Droid) Hot Reload disabled due to incompatible Xamarin.Forms version
WARN: (XXXXXX.Droid) Hot Reload disabled due to incompatible Xamarin.Forms version
```

I updated the XF package to latest version 5.0.0.2012 and it started working;

```
(XXXXX.Droid) XAML Hot Reload is using 'changes only' mode
XAML Hot Reload initializing...
WARN: (XXXXXX.Droid) Unknown Breakpoint Hit: Android.Runtime.JNIEnv.RegisterJniNatives( typeName_ptr, int typeName_len,  jniClass,  methods_ptr, int methods_len)
(XXXXXX.Droid) HotReload: Initialized Agent.
XAML Hot Reload Connected and Ready.
```

It only works for me on the latest release, if I downgrade a version it stops again.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b74184fd-ca8a-11fa-ed37-91235fc59401
* Version Independent ID: 87f197b8-20c6-4825-18e4-86562bb2523c
* Content: [XAML Hot Reload for Xamarin.Forms - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/xaml/hot-reload)
* Content Source: [docs/xamarin-forms/xaml/hot-reload.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/xaml/hot-reload.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @maddyleger1
* Microsoft Alias: **maleger**

**Comment by davidbritch** [comment]
Hi @lywyn 

Thanks for pointing this out. I've updated the doc to specify the exact version required, in a PR that will go live later today.
