### ISSUE TITLE
TouchEffect Initialization to handle Moved touch actions

### ISSUE THREAD

**Issue by Kazbek** [MicrosoftDocs/xamarin-docs#3286]
I'm making Mobile Blazor Bindings app and use this example to crop images. Moved events doesn`t raised (Only Pressed and Exited) until I change this initialization:

`TouchEffect touchEffect = new TouchEffect();`

to this: 

`TouchEffect touchEffect = new TouchEffect() { Capture = true };`

Sorry if I misunderstand something. It took me a lot of time to find a solution, and I wanna share it with community.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c2103650-966c-ac1f-1422-db102483444e
* Version Independent ID: cf19f39c-5fe6-0fe5-653c-a747579886fa
* Content: [Cropping SkiaSharp bitmaps - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/graphics/skiasharp/bitmaps/cropping)
* Content Source: [docs/xamarin-forms/user-interface/graphics/skiasharp/bitmaps/cropping.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/graphics/skiasharp/bitmaps/cropping.md)
* Product: **xamarin**
* Technology: **xamarin-skiasharp**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @Kazbek 

Which platform did you notice this behaviour on?

**Comment by Kazbek** [comment]
Hi @davidbritch 
Tested only on Android (real device Android 7.0 and emulator 9.0).
Here's nuget packages I used, may be problem with them.
![image](https://user-images.githubusercontent.com/15718432/114861939-9c04ad80-9df6-11eb-919a-18704402a1d2.png)

**Comment by davidbritch** [comment]
I tried it without using mobile Blazor bindings and it worked as expected on Android and iOS, without setting `Capture` to `true`. So maybe it's something to do with the Blazor layer. I'll close the issue for the moment, as the mobile Blazor bindings are unsupported while only available as a preview. But the issue will still appear in search engines for anyone having similar problems. Thanks for reporting it!
