### ISSUE TITLE
FirebaseInstanceIdService is deprecated

### ISSUE THREAD

**Issue by Happypig375** [MicrosoftDocs/xamarin-docs#3287]
### FirebaseInstanceIdService is deprecated

https://docs.microsoft.com/en-us/xamarin/android/data-cloud/google-messaging/remote-notifications-with-fcm?tabs=macos#implement-the-firebase-instance-id-service

`Firebase.Iid.FirebaseInstanceIdService` is deprecated, and according to https://stackoverflow.com/a/51129304/5429648, this is replaced with the overridable instance method `Firebase.Messaging.FirebaseMessagingService.OnNewToken`.

**Comment by alaskanrogue** [comment]
What is expressly needed is an example of the replacement of the associated manifest elements.

**Comment by alaskanrogue** [comment]
In the previous version of the manifest, the following two sections contained the referenced classes. What are their replacements.

-<service android:name="com.google.firebase.iid.FirebaseInstanceIdService" android:exported="true">
    -<intent-filter android:priority="-500">
        <action android:name="com.google.firebase.INSTANCE_ID_EVENT"/>
    </intent-filter>
</service>


<receiver android:name="com.google.firebase.iid.FirebaseInstanceIdInternalReceiver" android:exported="false"/>
<receiver android:name="com.google.firebase.iid.FirebaseInstanceIdReceiver" android:exported="true" />
    <intent-filter>
        <action android:name="com.google.android.c2dm.intent.RECEIVE"/>
        <action android:name="com.google.android.c2dm.intent.REGISTRATION"/>
        <category android:name="$com.identitycheckpoint.sentry"/>
    </intent-filter>
</receiver>

**Comment by alaskanrogue** [comment]
>  
<receiver android:name="com.google.firebase.iid.FirebaseInstanceIdInternalReceiver" android:exported="false"/>
<receiver android:name="com.google.firebase.iid.FirebaseInstanceIdReceiver" android:exported="true" />
    <intent-filter>
        <action android:name="com.google.android.c2dm.intent.RECEIVE"/>
        <action android:name="com.google.android.c2dm.intent.REGISTRATION"/>
        <category android:name="$com.identitycheckpoint.sentry"/>
    </intent-filter>
</receiver>

**Comment by alaskanrogue** [comment]
Section 2

>  
<receiver android:name="com.google.firebase.iid.FirebaseInstanceIdInternalReceiver" android:exported="false"/>
<receiver android:name="com.google.firebase.iid.FirebaseInstanceIdReceiver" android:exported="true" />
    <intent-filter>
        <action android:name="com.google.android.c2dm.intent.RECEIVE"/>
        <action android:name="com.google.android.c2dm.intent.REGISTRATION"/>
        <category android:name="$com.identitycheckpoint.sentry"/>
    </intent-filter>
</receiver>

**Comment by alaskanrogue** [comment]
@davidortinau @davidbritch Was the documentation needed ever created or found?

**Comment by jl-memosoft** [comment]
+1

**Comment by davidbritch** [comment]
[Microsoft support for Xamarin](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin) will end on May 1, 2024 for all Xamarin SDKs including Xamarin.Forms. In preparation for this, all issues and PRs in this repository are being closed.

.NET MAUI is the replacement for Xamarin.Forms, and it's documentation can be found [here](https://learn.microsoft.com/dotnet/maui/?view=net-maui-8.0).
