### ISSUE TITLE
-interpreter Should also be set on Android project

### ISSUE THREAD

**Issue by IngweLand** [MicrosoftDocs/xamarin-docs#3289]
The docs says it should be set on monotouch additional arguments. But it also should be set on Android for Hot reload to start working.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b74184fd-ca8a-11fa-ed37-91235fc59401
* Version Independent ID: 87f197b8-20c6-4825-18e4-86562bb2523c
* Content: [XAML Hot Reload for Xamarin.Forms - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/xaml/hot-reload)
* Content Source: [docs/xamarin-forms/xaml/hot-reload.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/xaml/hot-reload.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @maddyleger1
* Microsoft Alias: **maleger**

**Comment by BretJohnson** [comment]
`-interpreter` is just needed on iOS, not Android. Are you seeing otherwise?

**Comment by IngweLand** [comment]
My bad. You are right. Probably was just a glitch with Hot Reload why it did not work for the first time before I set that argument.
