### ISSUE TITLE
Any Chance of a Basic Working Solution?

### ISSUE THREAD

**Issue by PatrickRyder** [MicrosoftDocs/xamarin-docs#329]
This is such a big subject that anyone coming to it for the first time, as I am, really could do with a complete basic project to show how all the bits fit together.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 12a11bd4-59ff-06a0-a55f-b42d8e73990a
* Version Independent ID: d84cf64f-2111-de35-f747-bb36d743cef6
* Content: [Workout Apps - Xamarin](https://docs.microsoft.com/en-us/xamarin/ios/watchos/platform/workout-apps)
* Content Source: [docs/ios/watchos/platform/workout-apps.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/ios/watchos/platform/workout-apps.md)
* Service: **unspecified**
* Product: **xamarin**
* GitHub Login: @bradumbaugh
* Microsoft Alias: **brumbaug**

**Comment by conceptdev** [comment]
Thanks for the suggestion @PatrickRyder - you can find our current watchOS samples [on GitHub](https://github.com/xamarin/ios-samples/tree/master/watchOS). If we add a full workout sample in future, it will be in this location.

**Comment by onurhazar** [comment]
@conceptdev don't we have a working sample solution for this yet?  :(

**Comment by PatrickRyder** [comment]
It would be nice. I've been working on other stuff for a while but soon I will have to face getting a workout application (to monitor heart-rate mainly) on an Apple Watch, and I would really, really like a working sample application.

Wearables are the future and if Xamarin is serious about being in this  field, they need to do everything they can to help developers attempting to get Xamarin to talk to various wearable devices.
