### ISSUE TITLE
Why Does PickVideoAsync in Xamarin Essentials Prompt for Microphone Access?

### ISSUE THREAD

**Issue by lfeldman65** [MicrosoftDocs/xamarin-docs#3292]
Hi,

I'm using Xamarin Essentials 1.6.1 and PickVideoAsync prompts for microphone access. Why would someone need microphone access when picking from the Photo Album? Is there a way to disable? I've searched to no avail. 

Thanks!
Larry

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e4b43ab7-fd40-ba56-c9ab-5de2eb1aad7f
* Version Independent ID: 6c9c7c48-4401-cb25-5cda-637718a22961
* Content: [Xamarin.Essentials: Media Picker - Xamarin](https://docs.microsoft.com/en-us/xamarin/essentials/media-picker?tabs=android)
* Content Source: [docs/essentials/media-picker.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/essentials/media-picker.md)
* Product: **xamarin**
* Technology: **xamarin-essentials**
* GitHub Login: @jamesmontemagno
* Microsoft Alias: **jamont**

**Comment by jamesmontemagno** [comment]
This is a bug that is fixed and awaiting merge and release -> https://github.com/xamarin/Essentials/pull/1734

**Comment by lfeldman65** [comment]
Thanks!

Larry

**Comment by lfeldman65** [comment]
Thanks!

Larry

**Comment by lfeldman65** [comment]
How many cups of coffee can I buy you for help solving some exceptions with vague descriptions? Haha. Thanks!

Larry

**Comment by lfeldman65** [comment]
I'm too old to be a noob, yet here I am...

Your awesome Media nuget package had a fantastic option to save videos
captured via camera to the album automatically.  Can you please help me add
the code that saves to the album now that I'm using Xamarin Essentials for
Video capture?

Thanks!
Larry

**Comment by lfeldman65** [comment]
Hi!

I appreciate you all, and I'd like to buy you all a cup of coffee.  At
least.

What is the estimated release date of the next update to Essentials that
fixes this microphone issue?

Thanks!
Larry

**Comment by lfeldman65** [comment]
Sorry to bother you again.

1. Other than paypal, do you accept Zelle or Chase Quick Pay?

2. Any status update on when the next version of Essentials will be
available?

3. Is there any way to adjust the video resolution (CaptureVideoAsync)
using Essentials, similar to your media plugin?

4. Is there a way to save videos to the album (CaptureVideoAsync) using
Essentials, similar to your media plug?

5. Is there any time limit on continuing to use your media plugin?

Thanks!
Larry
