### ISSUE TITLE
Following these instructions from a file new leads to a MM0003 error

### ISSUE THREAD

**Issue by ChrisAllisonMalta** [MicrosoftDocs/xamarin-docs#3294]
mm0003: Application name '{0}.exe' conflicts with another user assembly. (MM0023) 

Using Xamarin Forms 5.0.0.2012

I know there is a lot of focus on MAUI but it would be good to still have a popular platform supported properly! 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 35a28b49-e47c-fca9-69e4-c261f2869e9a
* Version Independent ID: db9d6201-0042-eb0c-7b86-80089b543674
* Content: [Mac Platform Setup - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/platform/other/mac)
* Content Source: [docs/xamarin-forms/platform/other/mac.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/platform/other/mac.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @ChrisAllisonMalta 

While the doc is dated in the odd place, it essentially works for me. I was able to follow it to add a Mac app to an existing Xamarin.Forms solution.
Maybe it's a problem with your naming? That error usually occurs if you have an assembly name clash between two projects. Ensuring your project names are unique usually fixes the problem. See https://jim.blacksweb.com/2019/02/01/xamarin-ios-the-root-assembly-conflicts-with-another-assembly/ for an example.
