### ISSUE TITLE
No mention to enable iCloud capability for iOS

### ISSUE THREAD

**Issue by tsequeira-vhs** [MicrosoftDocs/xamarin-docs#3295]
The Xamarin Essentials File Picker uses UIDocumentPickerViewController for accessing files and based on the article [here](https://docs.microsoft.com/en-us/xamarin/ios/platform/document-picker#enabling-icloud-in-xamarin) we need to enable iCloud capability. But there is no mention about it in [this](https://docs.microsoft.com/en-gb/xamarin/essentials/file-picker?context=xamarin%2Fandroid&tabs=ios#pick-file) article.

Does it mean that it is just no longer required or it has been missed in the Xamarin Essentials documentation?

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bde8b00e-bef2-d10c-268f-2e49e236a89f
* Version Independent ID: dad8b07c-2227-c7ed-6369-d10d9b132e99
* Content: [Xamarin.Essentials: File Picker - Xamarin](https://docs.microsoft.com/en-gb/xamarin/essentials/file-picker?context=xamarin%2Fandroid&tabs=ios)
* Content Source: [docs/essentials/file-picker.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/essentials/file-picker.md)
* Product: **xamarin**
* Technology: **xamarin-essentials**
* GitHub Login: @jamesmontemagno
* Microsoft Alias: **jamont**

**Comment by jamesmontemagno** [comment]
Added link to this in setup code. Thanks

**Comment by tsequeira-vhs** [comment]
@jamesmontemagno It is really weird to see that even a file picker functionality requires iCloud capabilities. I tried the Xamarin Essentials File picker **without** the iCloud capabilities on an iPhone XS (iOS 14.4.2) and it worked fine. I was able to pick a file from iCloud Drive. 

Is it only needed in order to be able to submit the app to App Store?
