### ISSUE TITLE
Android SplashScreen implementation

### ISSUE THREAD

**Issue by AlleSchonWeg** [MicrosoftDocs/xamarin-docs#3296]
Hi,

i think you should consider to modify the sample to this approach: https://medium.com/android-news/the-complete-android-splash-screen-guide-c7db82bce565 (1. Using a Launcher Theme (The good))

Because sometimes the SplashScreen (in another activity) isn't show. It depends how android restarts the app.
Reference:
https://stackoverflow.com/questions/50789501/xamarin-android-splash-screen-doesnt-work-on-resume
https://developer.android.com/topic/performance/vitals/launch-time

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a5a4e93b-006f-176e-cf02-108f48bff807
* Version Independent ID: 2d677054-ae70-1eb1-903d-70b4f6cdfc50
* Content: [Xamarin.Forms splash screen - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/splashscreen)
* Content Source: [docs/xamarin-forms/user-interface/splashscreen.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/splashscreen.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @profexorgeek
* Microsoft Alias: **jusjohns**

**Comment by davidbritch** [comment]
Note: the work required is to update the Xamarin.Android splash screen doc.

**Comment by davidbritch** [comment]
[Microsoft support for Xamarin](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin) will end on May 1, 2024 for all Xamarin SDKs including Xamarin.Forms. In preparation for this, all issues and PRs in this repository are being closed.

.NET MAUI is the replacement for Xamarin.Forms, and it's documentation can be found [here](https://learn.microsoft.com/dotnet/maui/?view=net-maui-8.0).
