### ISSUE TITLE
The section "Specify the Application Icon" lacks many important details

### ISSUE THREAD

**Issue by knocte** [MicrosoftDocs/xamarin-docs#33]
https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/android/deploy-test/release-prep/index.md ( https://docs.microsoft.com/en-gb/xamarin/android/deploy-test/release-prep/ ) 

The section The section "Specify the Application Icon" lacks many important details:
* It doesn't mention that @drawable is supposedly referring to a folder name inside the Resources folder of the Xamarin Android project (this might seem overkill to mention it, but for a developer that has created his XamarinAndroid project via the Xamarin.Forms VS template, this is not obvious at all).
* It doesn't mention that "icon" string maps to a file supposedly to be called "icon.png".
* It doesn't mention that the namespace of the Application attribute is `Android.App`.

**Comment by mgmclemore** [comment]
@knocte, thank you for pointing this out! Each of the above omissions has been addressed and the updates should be published very soon. Much appreciated!

**Comment by knocte** [comment]
@mgmclemore thanks, looks better now; but you have addressed only the first 2 bullet points I raised, not the third ;-) The third is important, especially for VSforMac users (for VSforWindows users, if you don't specify a `using Android.App;` at the top, you get a suggestion, but in VSforMac I don't get a suggestion for this when using F#, as I think this feature is not implemented yet for this language; so finding what namespace does ApplicationAttribute belong to, is quite hard).

**Comment by mgmclemore** [comment]
@knocte, sorry, I didn't understand at first (`using Android.App` was already added to **AssemblyInfo.cs**  in my case). I've added a note for the reader to be sure to add this `using` statement if it is not already present. Thanks again!

**Comment by knocte** [comment]
> using Android.App was already added to AssemblyInfo.cs in my case

Maybe because you used the C# Xamarin.Android template of Visual Studio for Windows?

But in my case I used something completely different: the F# Xamarin.Forms template of VS4Mac :)

**Comment by mgmclemore** [comment]
Hi @knocte, that explains it -- thanks again!
