### ISSUE TITLE
Passing data to child page

### ISSUE THREAD

**Issue by ammarsdc** [MicrosoftDocs/xamarin-docs#330]
Hi. May I know if it is possible for a collection at my TabbedPage to be retrieved by all those child page? If possible may I know how?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0c81c589-e81e-d98c-9656-695a3520a12d
* Version Independent ID: c235f6f9-47ce-15f3-b4da-cb12e219df92
* Content: [Tabbed Page - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/navigation/tabbed-page)
* Content Source: [docs/xamarin-forms/app-fundamentals/navigation/tabbed-page.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/app-fundamentals/navigation/tabbed-page.md)
* Service: **unspecified**
* Product: **xamarin**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by conceptdev** [comment]
@ammarsdc this feedback system is intended to provide feedback on the documentation itself, unfortunately we cannot provide general product support.

You might find some tips looking at our [samples](https://docs.microsoft.com/xamarin/cross-platform/samples/), or the information on using a local database in your app.
