### ISSUE TITLE
iOS Launch screen docs are useless and it seems XCode is not able to edit the Xamarin iOS project ?

### ISSUE THREAD

**Issue by stephenhauck** [MicrosoftDocs/xamarin-docs#3300]
### Doc issue description
https://docs.microsoft.com/en-us/xamarin/ios/app-fundamentals/images-icons/launch-screens?tabs=macos

You have removed the storyboard editor from Visual Studio ... 
Your instructions say to use XCode to fix the graphics ...

When you launch XCode to do so you get an error like so ...
![image](https://user-images.githubusercontent.com/12648793/116782917-d8244900-aa59-11eb-9a18-289d6c50f2f3.png)
Then when you select the LaunchScreen.storyboard in XCode it shows and image associated with the splash screen like so 
![image](https://user-images.githubusercontent.com/12648793/116713399-c2a01800-a9a2-11eb-8ce1-bfd1510959eb.png)

We need to know how to associate OUR splash images with the Launch screen ... 

This is preventing me from submitting to the app store !

This is failing the same way on an M1 and Intel based Mac

**Comment by stephenhauck** [comment]
When you open the storyboard it looks like this ...
![image](https://user-images.githubusercontent.com/12648793/116714800-19f2b800-a9a4-11eb-81c8-5054c52379c0.png)

**Comment by stephenhauck** [comment]
I am still blocked by this issue .... someone ... anyone ?

**Comment by stephenhauck** [comment]
Workaround ?
Acknowledge this is an issue ?
HELP!

**Comment by mcumming** [comment]
Hi @stephenhauck,
Thank you for bringing this to our attention. Could you report this issue directly to the product team by using `Help->Report a Problem` feature in Visual Studio? That will give us additional detail we may need to resolve your issue.

**Comment by stephenhauck** [comment]
No ... you can transfer it there on my behalf ... this is 2021 man ...

Stephen

**Comment by stephenhauck** [comment]
THIS IS A CRITICAL ISSUE .....

**Comment by davidbritch** [comment]
Hi @stephenhauck 

Thanks for your feedback. As @mcumming has mentioned, product feedback needs to be logged using `Help->Report a Problem` feature in Visual Studio. That is the only way to get engineer eyes on it. Afraid that docs issues aren't the place to get support, as the support teams don't frequent docs repos.
