### ISSUE TITLE
Explicitly mention updating the version of Xamarin

### ISSUE THREAD

**Issue by mathjeff** [MicrosoftDocs/xamarin-docs#3304]
Hello!

I encountered a bunch of errors when trying to update to Xamarin 5 (including, for example, https://github.com/xamarin/Xamarin.Forms/issues/14268 ).

The combination of these weird errors plus the fact that this page never actually says anywhere "Update the version of Xamarin.Forms to 5+" made me suspect the page was incomplete.

Could this page be updated to explicitly instruct the reader to update their NuGet version of Xamarin to a version 5+ (and that that version must be the same in each project)?

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 44402563-3bc3-f440-1e3a-f822759b1036
* Version Independent ID: e311ff55-3091-2c53-90a0-8447b9ec721e
* Content: [How do I migrate my app to Xamarin.Forms 5.0? - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/troubleshooting/questions/forms5-migration)
* Content Source: [docs/xamarin-forms/troubleshooting/questions/forms5-migration.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/troubleshooting/questions/forms5-migration.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @mathjeff 

I've added a note to the page to instruct people to ensure they update to the same version in each project that references the Xamarin.Forms NuGet package.

I've left the text referring to v5.0. While there are multiple versions of 5.0, they are all service releases. There'll never be a 5.1 release.

**Comment by mathjeff** [comment]
Thanks!
