### ISSUE TITLE
Missing documentation: Connect to local web services from Android device

### ISSUE THREAD

**Issue by esamk** [MicrosoftDocs/xamarin-docs#3306]
### Doc issue description

`Docs/Xamarin/Cross-platform/Deployment & debugging/Connect to local web services`
describes how to connect to local web services from an emulator. No such document exists, AFAIK, for doing the same thing from an android (or IOS) device.

I spent literally days trying to accomplish that and now that I finally found a solution, I thought maybe what I found could be useful to others. And if this is not worth documenting, maybe people struggling with the same issue find my solution here anyway. 

## Connect to local web services from Android device (via USB)

The solution assumes you're using IIS Express to host your local web service (Visual Studio default)

1.  Change the binding in applicationhost.config on your development machine from
`<binding protocol="https" bindingInformation="*:{port}:localhost" />`
to this:
`<binding protocol="https" bindingInformation="*:{port}:127.0.0.1" />`

2. Change your mobile app to use `https://127.0.0.1:{port}/` as a host address instead of `https://localhost:{port}/` when calling web service(s) on your development machine.
 
3. Use Chrome `chrome://inspect` to add port forwarding, i.e. to add a listening port on your device that maps to a port accessible from your development machine.
 
Rationale
1. IIS Express does not accept requests other than localhost by default. You can change that by changing the bindings.  
- applicationhost.config location depends on the visual studio version. In VS 2019 it is located at `/{project folder}/.vs/{solution name}/config/applicationhost.config`
- If you get "Access Denied" after the change, run Visual Studio as Admin. 
- If you get "Unable to connect iisexpress", close Visual Studio and reopen the solution.

2. In context of a mobile app, "localhost" refers to the mobile device and I couldn't get port forwarding work with it. Instead, using 127.0.0.1 as a host address of my web service, port forwarding works just fine.

3. Some stackoverflow answers people suggested using adb (Android Debug Bridge) to configure the mobile device to forward traffic on specific port to the development machine. Port reversing using adb command line did not work for me (adb reverse --list showed the proper config was there, but the device never used it). It turns out, new(ish) versions of Chrome include tool for defining port forwards and it works.

Presumably the Chrome inspect tool uses adb as well so you could in principle do the same thing directly from the adb command line. I just couldn't find a way to make it work.

I've no idea on how this could be done on IOS, so this is only a partial solution.

**Comment by davidbritch** [comment]
[Microsoft support for Xamarin](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin) will end on May 1, 2024 for all Xamarin SDKs including Xamarin.Forms. In preparation for this, all issues and PRs in this repository are being closed.

.NET MAUI is the replacement for Xamarin.Forms, and it's documentation can be found [here](https://learn.microsoft.com/dotnet/maui/?view=net-maui-8.0).
