### ISSUE TITLE
Altitude. Above sea level or WGS 84

### ISSUE THREAD

**Issue by MaximMikhisor** [MicrosoftDocs/xamarin-docs#3308]
Hello,

There is this fraise for location in section "Using Geolocation":
"If the altitude is available, the value is in meters above sea level."

But in section "Platform Differences" for Android you wrote this:
"On Android, altitude, if available, is returned in meters above the WGS 84 reference ellipsoid"
and for iOS you wrote this:
"Positive values indicate altitudes above sea level"

Can you please clarify which statement is right?
In what system does Geolocation return altitude value?

Thank you,
Maxim

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f0acf3fa-b705-f0cc-b676-eeca60176dfa
* Version Independent ID: 1788a5d5-a3cb-15c8-927c-b6a24810245a
* Content: [Xamarin.Essentials: Geolocation - Xamarin](https://docs.microsoft.com/en-us/xamarin/essentials/geolocation?tabs=android)
* Content Source: [docs/essentials/geolocation.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/essentials/geolocation.md)
* Product: **xamarin**
* Technology: **xamarin-essentials**
* GitHub Login: @jamesmontemagno
* Microsoft Alias: **jamont**

**Comment by davidbritch** [comment]
[Microsoft support for Xamarin](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin) will end on May 1, 2024 for all Xamarin SDKs including Xamarin.Forms. In preparation for this, all issues and PRs in this repository are being closed.

.NET MAUI is the replacement for Xamarin.Forms, and it's documentation can be found [here](https://learn.microsoft.com/dotnet/maui/?view=net-maui-8.0).
