### ISSUE TITLE
Which sample does this reference?

### ISSUE THREAD

**Issue by dimitrijevic** [MicrosoftDocs/xamarin-docs#331]
I can't find MonkeyCall app among the samples...it said fictional, but does that mean non-existing, because lack of SIP client or...can't you combine it with something like https://github.com/BelledonneCommunications/linphone-xamarin so as to show how to handle incoming calls on iOS when the SIP client app is in the background/inactive and if so how please?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8ce24684-3989-9cfe-e438-0c71d4a83f3f
* Version Independent ID: 0ab1140f-eda9-6ba8-440e-f1271398e508
* Content: [CallKit - Xamarin](https://docs.microsoft.com/en-us/xamarin/ios/platform/callkit?tabs=vswin#related-links)
* Content Source: [docs/ios/platform/callkit.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/ios/platform/callkit.md)
* Service: **unspecified**
* Product: **xamarin**
* GitHub Login: @bradumbaugh
* Microsoft Alias: **brumbaug**

**Comment by bradumbaugh** [comment]
Hi @dimitrijevic – thanks for calling this out. Unfortunately there isn't a MonkeyCall sample to download, it's just used as a discussion point throughout the doc. I've made a note in our internal backlog to revisit this in the future. Appreciate the help!

**Comment by softsan** [comment]
any samples on Xamarin iOS CallKit?

**Comment by nielscup** [comment]
Sample project needed.

**Comment by softsan** [comment]
I've created an end-to end sample with CallKit,PushKit and Twilio in Xamarin.Forms. Here is the [blog](https://medium.com/@san.thanki/callkit-pushkit-twilio-with-xamarin-83553f93be86) and my [GitHub repo](https://github.com/softsan/callkitsample/).
