### ISSUE TITLE
Clarification of where data is stored on Android with the Secure Storage API

### ISSUE THREAD

**Issue by hammelev** [MicrosoftDocs/xamarin-docs#3313]
Hey,

In the video on the page for the Secure Storage API it is stated in the that the data is saved in respectively the keychain for iOS and the keystore for Android. The description on the page for the Android implementation states that the data is saved in Shared Preferences and that the keystore is used to store a cryptographic key which is used to store this data - see image below.

Just for clarification - the data on Android is stored encrypted in Shared Preferences and not in the keystore, right?

![image](https://user-images.githubusercontent.com/14328199/121332632-578a1f80-c918-11eb-9483-b432891db547.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: da75050f-bfda-4792-40d9-b9a25d649d3e
* Version Independent ID: 5c44f996-765b-f6e4-c807-9446c534d50b
* Content: [Xamarin.Essentials: Secure Storage - Xamarin](https://docs.microsoft.com/en-us/xamarin/essentials/secure-storage?tabs=android#feedback)
* Content Source: [docs/essentials/secure-storage.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/essentials/secure-storage.md)
* Product: **xamarin**
* Technology: **xamarin-essentials**
* GitHub Login: @jamesmontemagno
* Microsoft Alias: **jamont**

**Comment by jamesmontemagno** [comment]
The Android Keystore is used to encrypt and decrypt the data. That data is stored in Preferences as to Android best practice for the data. 

The documentation accurately describes the process.
