### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by stephajn** [MicrosoftDocs/xamarin-docs#3315]
There's a broken link on the page where it is describing the order of events in "Chapter 24" of a Xamarin Forms book.  I clicked on the link where it gives more information about the order of OnAppearing/OnDisappearing etc when pushing or popping a modal page from the stack and wound up at a dead link.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4dbd0d0d-484d-ea90-3a8c-e0780a058017
* Version Independent ID: cf200dae-4d45-cc32-e323-c317e969ac64
* Content: [Xamarin.Forms Modal Pages - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/navigation/modal)
* Content Source: [docs/xamarin-forms/app-fundamentals/navigation/modal.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/app-fundamentals/navigation/modal.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @stephajn 

I've fixed this in a PR that's running through CI at the moment. The link to the full book is: https://aka.ms/xamformsebook
