### ISSUE TITLE
пожалуйста создайте простой проект - образец для пользователей mvs2019

### ISSUE THREAD

**Issue by aaafgcfg** [MicrosoftDocs/xamarin-docs#3317]
### Doc issue description
https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/cross-platform/app-fundamentals/nuget-multiplatform-libraries/single-codebase.md

vs2019 не подерживает NuGetizer3000 
пожалуйста создайте простой проект со всеми платформами в NuGetizer3000 для пользователей mvs2019 и опубликуйте его.

**Comment by davidbritch** [comment]
[Microsoft support for Xamarin](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin) will end on May 1, 2024 for all Xamarin SDKs including Xamarin.Forms. In preparation for this, all issues and PRs in this repository are being closed.

.NET MAUI is the replacement for Xamarin.Forms, and it's documentation can be found [here](https://learn.microsoft.com/dotnet/maui/?view=net-maui-8.0).
