### ISSUE TITLE
Link to download the example

### ISSUE THREAD

**Issue by tonyaom** [MicrosoftDocs/xamarin-docs#332]
How can I download the example? It appears that there is no link or reference to download the app. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 14566929-3da6-5189-694d-cb7d5d7126a2
* Version Independent ID: b8a3de23-26ef-869d-7329-32dbfa748787
* Content: [Understanding the Sample - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/data-cloud/walkthrough)
* Content Source: [docs/xamarin-forms/data-cloud/walkthrough.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/data-cloud/walkthrough.md)
* Service: **unspecified**
* Product: **xamarin**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Thanks for the feedback. The links to download the apps are in the Related Links sections at the end of each doc. However, there's no link in the "Understanding the Sample" doc. Rather, you have to go into each specific doc (WCF, REST, Azure etc.) where you'll find a link to each sample.
