### ISSUE TITLE
Spelling Mistake 

### ISSUE THREAD

**Issue by syedadnanshah7** [MicrosoftDocs/xamarin-docs#3320]
Kindly check for the spelling mistake in following paragraph : "BinableLayout.ItemsSource" should be BindableLayout.ItemsSource

The Layout<T> class exposes a Children collection, to which the child elements of a layout are added. When the **BinableLayout.ItemsSource** property is set to a collection of items and attached to a Layout<T>-derived class, each item in the collection is added to the Layout<T>.Children collection for display by the layout. The Layout<T>-derived class will then update its child views when the underlying collection changes. For more information about the Xamarin.Forms layout cycle, see Creating a Custom Layout.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 59df8b1e-8b94-a79e-25eb-f47ddf38777a
* Version Independent ID: cd195715-e7e3-428f-1061-c550ff960dda
* Content: [Bindable Layouts in Xamarin.Forms - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/layouts/bindable-layouts)
* Content Source: [docs/xamarin-forms/user-interface/layouts/bindable-layouts.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/layouts/bindable-layouts.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
[Microsoft support for Xamarin](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin) will end on May 1, 2024 for all Xamarin SDKs including Xamarin.Forms. In preparation for this, all issues and PRs in this repository are being closed.

.NET MAUI is the replacement for Xamarin.Forms, and it's documentation can be found [here](https://learn.microsoft.com/dotnet/maui/?view=net-maui-8.0).
