### ISSUE TITLE
Should explain how to theme images

### ISSUE THREAD

**Issue by flywhc** [MicrosoftDocs/xamarin-docs#3321]
themes are not only about color but also about images.
Dark mode usually has many different images from Light mode for example.

Xamarin does have support images for dark mode on iOS and Android but no documents explain them.
I did google and found a good article to explain how to do a theme with a complete solution. This should be done by Microsoft officials.
https://intelliabb.com/2019/11/02/how-to-support-dark-mode-in-xamarin-forms/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3f353ff4-2d18-218c-f0d5-b3110e476c4d
* Version Independent ID: a1cec8f2-969c-23c5-a252-b417afcacff6
* Content: [Theme a Xamarin.Forms Application - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/theming/theming)
* Content Source: [docs/xamarin-forms/user-interface/theming/theming.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/theming/theming.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
[Microsoft support for Xamarin](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin) will end on May 1, 2024 for all Xamarin SDKs including Xamarin.Forms. In preparation for this, all issues and PRs in this repository are being closed.

.NET MAUI is the replacement for Xamarin.Forms, and it's documentation can be found [here](https://learn.microsoft.com/dotnet/maui/?view=net-maui-8.0).
