### ISSUE TITLE
Doesn't explain how to add TinyIoC to the project.

### ISSUE THREAD

**Issue by Thorocaine** [MicrosoftDocs/xamarin-docs#3322]
This document describes how to use TinyIoc, but it doesn't actually explain how to add it to the project.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 496aefc1-60e7-3484-12d1-ba383cfc099b
* Version Independent ID: 35133eba-8bc2-a54e-b341-d873f9a3c468
* Content: [Dependency Injection - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/enterprise-application-patterns/dependency-injection)
* Content Source: [docs/xamarin-forms/enterprise-application-patterns/dependency-injection.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/enterprise-application-patterns/dependency-injection.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @Thorocaine 

It's just a case of copying the class into your project. See https://github.com/grumpydev/TinyIoC
