### ISSUE TITLE
It needs an example on the Control Template in it's own resource dictionary

### ISSUE THREAD

**Issue by nick5454** [MicrosoftDocs/xamarin-docs#3324]
The example only show it as a resource embedded in the Content Page. The issue with that is, this will rarely ever happen. Usually it will be in a separate resource dictionary. This would be for the reason of no reusability.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a4b35f51-7abf-c8cc-2dfb-2cb20a0fc200
* Version Independent ID: f47aa11e-86c3-9387-e1f8-b6ce29fe5eb7
* Content: [Xamarin.Forms control templates - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/templates/control-template)
* Content Source: [docs/xamarin-forms/app-fundamentals/templates/control-template.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/app-fundamentals/templates/control-template.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
[Microsoft support for Xamarin](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin) will end on May 1, 2024 for all Xamarin SDKs including Xamarin.Forms. In preparation for this, all issues and PRs in this repository are being closed.

.NET MAUI is the replacement for Xamarin.Forms, and it's documentation can be found [here](https://learn.microsoft.com/dotnet/maui/?view=net-maui-8.0).
