### ISSUE TITLE
Wrong type of property in example for sharing Multiple Files

### ISSUE THREAD

**Issue by JPZV** [MicrosoftDocs/xamarin-docs#3328]
In the example for Multiple Files, there is line for the property `Files` of the class `ShareMultipleFilesRequest`. The problem is that property is of type List<ShareFile>, but the example treats it as an array, meaning that if someone copies that code, the compiling will fail with the error `Cannot implicitly convert type 'Xamarin.Essentials.ShareFile[]' to 'System.Collections.Generic.List<Xamarin.Essentials.ShareFile>`

This is the wrong code for the example:

```cs
var file1 = Path.Combine(FileSystem.CacheDirectory, "Attachment1.txt");
File.WriteAllText(file, "Content 1");
var file2 = Path.Combine(FileSystem.CacheDirectory, "Attachment2.txt");
File.WriteAllText(file, "Content 2");

await Share.RequestAsync(new ShareMultipleFilesRequest
{
    Title = ShareFilesTitle,
    Files = new ShareFile[] { new ShareFile(file1), new ShareFile(file2) }
});
```

And this should be the correct way for it:

```cs
var file1 = Path.Combine(FileSystem.CacheDirectory, "Attachment1.txt");
File.WriteAllText(file, "Content 1");
var file2 = Path.Combine(FileSystem.CacheDirectory, "Attachment2.txt");
File.WriteAllText(file, "Content 2");

await Share.RequestAsync(new ShareMultipleFilesRequest
{
    Title = ShareFilesTitle,
    Files = new List<ShareFile> { new ShareFile(file1), new ShareFile(file2) }
});
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e86cfbdf-277d-29ae-3999-33f73d91efc6
* Version Independent ID: cf9bfb50-9d1e-3c5d-139f-392dfc9550eb
* Content: [Xamarin.Essentials: Share - Xamarin](https://docs.microsoft.com/en-us/xamarin/essentials/share?tabs=ios)
* Content Source: [docs/essentials/share.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/essentials/share.md)
* Product: **xamarin**
* Technology: **xamarin-essentials**
* GitHub Login: @jamesmontemagno
* Microsoft Alias: **jamont**

**Comment by jamesmontemagno** [comment]
Thanks! Fixed up.
