### ISSUE TITLE
android x equivalents of xamarin.android.support.v4 and v7.appcombat

### ISSUE THREAD

**Issue by Vespiyanus** [MicrosoftDocs/xamarin-docs#3329]
Hello;

Is it required to remove the existing xamarin.android.support.v4 and v7.appcombat dependincies and install androidx dependency? If so, can you please advise exact name of new dependencies?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2c3fb215-91c9-b6bb-1f47-558dd2d4801c
* Version Independent ID: 6cf63a49-569d-c910-6b22-6734d99e473a
* Content: [AndroidX Migration in Xamarin.Forms - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/platform/android/androidx-migration)
* Content Source: [docs/xamarin-forms/platform/android/androidx-migration.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/platform/android/androidx-migration.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @profexorgeek
* Microsoft Alias: **jusjohns**

**Comment by davidbritch** [comment]
Hi @Vespiyanus 

Take a look at the following two files that contain the mappings between support lib and AndroidX:

https://github.com/xamarin/AndroidX/blob/main/mappings/androidx-class-mapping.csv

https://github.com/xamarin/AndroidX/blob/main/mappings/androidx-assemblies.csv
