### ISSUE TITLE
coding block issue

### ISSUE THREAD

**Issue by BradenCalderMurphy** [MicrosoftDocs/xamarin-docs#3330]
Hi, issue in the coding block under "Navigation events", requires comment to be removed on last line.
```
protected override void OnNavigating(ShellNavigatingEventArgs args)
{
    base.OnNavigating(args);

    // Cancel any back navigation.
    if (args.Source == ShellNavigationSource.Pop)
    {
        args.Cancel();
    }
// }

```
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b6efe82d-a8b9-82a8-7d38-98f2f8d5e682
* Version Independent ID: 28d7341e-ae6e-6321-6550-d27ae6b256d2
* Content: [Xamarin.Forms Shell navigation - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/shell/navigation)
* Content Source: [docs/xamarin-forms/app-fundamentals/shell/navigation.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/app-fundamentals/shell/navigation.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
[Microsoft support for Xamarin](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin) will end on May 1, 2024 for all Xamarin SDKs including Xamarin.Forms. In preparation for this, all issues and PRs in this repository are being closed.

.NET MAUI is the replacement for Xamarin.Forms, and it's documentation can be found [here](https://learn.microsoft.com/dotnet/maui/?view=net-maui-8.0).
