### ISSUE TITLE
Regarding Middle Tier Recommendation and Client Secrets

### ISSUE THREAD

**Issue by mattallscripts** [MicrosoftDocs/xamarin-docs#3332]
Regarding [the "Why use a server back end?" section](https://docs.microsoft.com/en-us/xamarin/essentials/web-authenticator?tabs=ios#why-use-a-server-back-end);

> Microsoft Authentication Library (MSAL) provides an excellent turn-key solution to adding authentication to your app. There's even support for Xamarin apps in their client NuGet package.
> If you're interested in using your own web service for authentication, it's possible to use WebAuthenticator to implement the client side functionality.
> # Why use a server back end?
> Many authentication providers have moved to only offering explicit or two-legged authentication flows to ensure better security. This means you'll need a 'client secret' from the provider to complete the authentication flow. Unfortunately, mobile apps are not a great place to store secrets and anything stored in a mobile app's code, binaries, or otherwise is generally considered to be insecure.
> The best practice here is to use a web backend as a middle layer between your mobile app and the authentication provider.
>  Important
> We strongly recommend against using older mobile-only authentication libraries and patterns which do not leverage a web backend in the authentication flow due to their inherent lack of security for storing client secrets.

MSAL uses authorization code flow without a middle-tier, with the mobile app talking directly to the Identity Provider (Azure AD), and without using a client secret as far as I know ([unless using PRT](https://docs.microsoft.com/en-us/azure/active-directory/devices/concept-primary-refresh-token#how-is-a-prt-issued)).

Can someone please clarify the difference here and why a middle-tier is being recommended in this article? Specifically, why does the [diagram in this article](https://docs.microsoft.com/en-us/xamarin/essentials/web-authenticator?tabs=ios#using-webauthenticator) look different than the diagram in the [Azure AD Auth Code Flow documentation](https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-auth-code-flow#protocol-diagram) where the mobile app talks directly to AAD using MSAL.

Should we be using Web Authenticator for a Public Client (Native App) using the Authorization Code Flow?

Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1231a1e1-3734-9021-2cc7-eaf99478afca
* Version Independent ID: 01e5fdbe-0b15-4dbe-f8a0-ed40f8593302
* Content: [Xamarin.Essentials: Web Authenticator - Xamarin](https://docs.microsoft.com/en-us/xamarin/essentials/web-authenticator?tabs=ios)
* Content Source: [docs/essentials/web-authenticator.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/essentials/web-authenticator.md)
* Product: **xamarin**
* Technology: **xamarin-essentials**
* GitHub Login: @Redth
* Microsoft Alias: **jodick**

**Comment by jamesmontemagno** [comment]
MSAL is the one providing the web backend that handles all the redirects. That is why we recommend that route if using Azure AD or B2C. 

If you aren't then you would want to setup a backend tt handle this.

**Comment by davidbritch** [comment]
[Microsoft support for Xamarin](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin) will end on May 1, 2024 for all Xamarin SDKs including Xamarin.Forms. In preparation for this, all issues and PRs in this repository are being closed.

.NET MAUI is the replacement for Xamarin.Forms, and it's documentation can be found [here](https://learn.microsoft.com/dotnet/maui/?view=net-maui-8.0).
