### ISSUE TITLE
Xamarin Docs True/False update

### ISSUE THREAD

**Issue by jrahma** [MicrosoftDocs/xamarin-docs#3333]
Hi,

The Xamarin pages needs to update:

<Switch IsToggled="true"/>

to:

<Switch IsToggled="True"/>

for ALL true / False in all controls because VS intellisense shows it with capital F and T

**Comment by davidbritch** [comment]
Hi @jrahma 

It's more that intellisense needs updating - True/False/true/false are all valid. This intellisense error doesn't stop a successful build.
