### ISSUE TITLE
Xamarin.Essentials Geolocation mostly doesn't include speed on android

### ISSUE THREAD

**Issue by trampster** [MicrosoftDocs/xamarin-docs#3335]
The Geolocation inplementation on android doesn't wait for speed. Because of this most location requests on android do not include a speed, as speed is often not know at the first update and Xamarin.Essentials only waits for the first update. This isn't mentioned in the documentation.

This behaviour is by design according to: https://github.com/xamarin/Essentials/issues/742

This is quite surprising to anyone who looked the at API and documentation and assumed that because Xamarin.Essentials.Location includes a speed that it would be returned.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f0acf3fa-b705-f0cc-b676-eeca60176dfa
* Version Independent ID: 1788a5d5-a3cb-15c8-927c-b6a24810245a
* Content: [Xamarin.Essentials: Geolocation - Xamarin](https://docs.microsoft.com/en-us/xamarin/essentials/geolocation?tabs=android)
* Content Source: [docs/essentials/geolocation.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/essentials/geolocation.md)
* Product: **xamarin**
* Technology: **xamarin-essentials**
* GitHub Login: @jamesmontemagno
* Microsoft Alias: **jamont**

**Comment by jamesmontemagno** [comment]
I'll add something to the docs.
