### ISSUE TITLE
Code typo

### ISSUE THREAD

**Issue by GerardFR** [MicrosoftDocs/xamarin-docs#3337]
[Enter feedback here]
In the Data Binding section, the LoadNote code is placed within the ItemId property, which is obviously wrong.
The code should be:

        public string ItemId
        {
            set
            {
                LoadNote(value);
            }
        }

        async void LoadNote(string itemId)
        {
            try
            {
                int id = Convert.ToInt32(itemId);
                // Retrieve the note and set it as the BindingContext of the page.
                Note note = await App.Database.GetNoteAsync(id);
                BindingContext = note;
            }
            catch (Exception)
            {
                Console.WriteLine("Failed to load note.");
            }
        }

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6ab89335-bb35-dd6e-cb41-2d889415a555
* Version Independent ID: 72c891a7-6f2a-45e5-0935-0cdee220305c
* Content: [Xamarin.Forms Quickstart Deep Dive - Xamarin](https://docs.microsoft.com/en-us/xamarin/get-started/quickstarts/deepdive)
* Content Source: [docs/get-started/quickstarts/deepdive.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/get-started/quickstarts/deepdive.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
[Microsoft support for Xamarin](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin) will end on May 1, 2024 for all Xamarin SDKs including Xamarin.Forms. In preparation for this, all issues and PRs in this repository are being closed.

.NET MAUI is the replacement for Xamarin.Forms, and it's documentation can be found [here](https://learn.microsoft.com/dotnet/maui/?view=net-maui-8.0).
