### ISSUE TITLE
In Visual Studio 2019, WPF and UWP Grid lines indicating row definitions and column definitions appears on preview panel but for xamarin Form it doesn't!

### ISSUE THREAD

**Issue by mp3846** [MicrosoftDocs/xamarin-docs#3339]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b74184fd-ca8a-11fa-ed37-91235fc59401
* Version Independent ID: 87f197b8-20c6-4825-18e4-86562bb2523c
* Content: [XAML Hot Reload for Xamarin.Forms - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/xaml/hot-reload)
* Content Source: [docs/xamarin-forms/xaml/hot-reload.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/xaml/hot-reload.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @maddyleger1
* Microsoft Alias: **maleger**

**Comment by davidbritch** [comment]
Hi @mp3846 

Correct. Xamarin.Forms relies on hot reload to preview your UI in the simulator/emulator.
