### ISSUE TITLE
ToRadian() can not use!

### ISSUE THREAD

**Issue by nguyenthanhliemfc** [MicrosoftDocs/xamarin-docs#334]
Please check docs again. I can not use ToRadian() in 
    double latitude = position.Latitude.ToRadians();
    double longitude = position.Longitude.ToRadians();

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 30b9d29c-0918-ca5a-f97f-aef59f679c87
* Version Independent ID: d781998d-549a-3ab6-7dc6-5bcf3f05a128
* Content: [Highlighting a Circular Area on a Map - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/custom-renderer/map/circle-map-overlay)
* Content Source: [docs/xamarin-forms/app-fundamentals/custom-renderer/map/circle-map-overlay.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/app-fundamentals/custom-renderer/map/circle-map-overlay.md)
* Service: **unspecified**
* Product: **xamarin**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by nguyenthanhliemfc** [comment]
I have replace 
ToRadian() by * Math.PI / 180 
and
ToDegree() by 180 * long / Math.PI
And it's worked!

**Comment by davidbritch** [comment]
Thanks for the feedback. We don't include source for the entire app in the documentation, but each doc does have an accompanying sample app (which is linked to in the Related Links section at the end of the doc). If you look in the sample app you'll find code for `ToRadians` and `ToDegrees` extension methods:

https://github.com/xamarin/xamarin-forms-samples/blob/master/CustomRenderers/Map/Circle/UWP/DoubleExtensions.cs

**Comment by nguyenthanhliemfc** [comment]
Thank you!
