### ISSUE TITLE
Error on code line

### ISSUE THREAD

**Issue by upsilondynamics** [MicrosoftDocs/xamarin-docs#3341]
In the initial code sample:

` bitmap = SKBitmap.Decode(stream);`

Should be

` bitmap = SKBitmap.Decode(memStream);`

Just so others do not get mislead.

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0be1b0f7-717e-0f91-1901-20794667c4e6
* Version Independent ID: a6a29e1b-e6a3-16a3-65c5-d47e9561b534
* Content: [Displaying SkiaSharp bitmaps - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/graphics/skiasharp/bitmaps/displaying)
* Content Source: [docs/xamarin-forms/user-interface/graphics/skiasharp/bitmaps/displaying.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/graphics/skiasharp/bitmaps/displaying.md)
* Product: **xamarin**
* Technology: **xamarin-skiasharp**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by adityaoberai** [comment]
Agreed. Considering that the line just below mentions that Android does not allow the `Stream` from the `HttpClient` to be processed by the main thread except in asynchronous methods, I guess it would be necessary to use `memStream` instead of `stream` to lead the Bitmap resource.
