### ISSUE TITLE
[LOC]Not Translated (ja-jp)

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/xamarin-docs#3342]
### Doc issue description
・[LOC]Not Translated (ja-jp)
・Typo "(&quot;MessageIcon");"→"("MessageIcon");" (ja-jp)

ja-jp:"https://docs.microsoft.com/ja-jp/xamarin/ios/app-fundamentals/images-icons/displaying-an-image?tabs=windows#working-with-template-images"
![displaying-an-image_j](https://user-images.githubusercontent.com/40815708/127762629-d57e2d26-5bde-491d-8f16-daeb99373fd1.png)

en-us:"https://docs.microsoft.com/en-us/xamarin/ios/app-fundamentals/images-icons/displaying-an-image?tabs=windows#working-with-template-images"
![displaying-an-image_e](https://user-images.githubusercontent.com/40815708/127762632-f1cba05c-4125-4851-a21f-fad90f727728.png)

#PingMSFTDocs

**Comment by davidbritch** [comment]
[Microsoft support for Xamarin](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin) will end on May 1, 2024 for all Xamarin SDKs including Xamarin.Forms. In preparation for this, all issues and PRs in this repository are being closed.

.NET MAUI is the replacement for Xamarin.Forms, and it's documentation can be found [here](https://learn.microsoft.com/dotnet/maui/?view=net-maui-8.0).
