### ISSUE TITLE
.png is not displayed  (ja-jp)

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/xamarin-docs#3343]
ja-jp:"https://docs.microsoft.com/ja-jp/xamarin/xamarin-forms/user-interface/layouts/grid"
![layouts_grid_j](https://user-images.githubusercontent.com/40815708/127762915-94e4ff4d-4899-4222-b191-0ba7b256496b.png)

en-us:"https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/layouts/grid"
![layouts_grid_e](https://user-images.githubusercontent.com/40815708/127762919-1e7e8fc6-a875-486e-8cbe-6712fbe52b8c.png)

#PingMSFTDocs

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c0902f8-eb40-4c56-958a-f13f064c8293
* Version Independent ID: 1e930440-f312-6301-d786-262b98f9ce2f
* Content: [Xamarin.Forms Grid - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/layouts/grid)
* Content Source: [docs/xamarin-forms/user-interface/layouts/grid.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/layouts/grid.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
[Microsoft support for Xamarin](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin) will end on May 1, 2024 for all Xamarin SDKs including Xamarin.Forms. In preparation for this, all issues and PRs in this repository are being closed.

.NET MAUI is the replacement for Xamarin.Forms, and it's documentation can be found [here](https://learn.microsoft.com/dotnet/maui/?view=net-maui-8.0).
