### ISSUE TITLE
[LOC]English is displayed  (ja-jp)

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/xamarin-docs#3344]
ja-jp:"https://docs.microsoft.com/ja-jp/xamarin/xamarin-forms/user-interface/shapes/fillrules"
![shapes_fillrules_j](https://user-images.githubusercontent.com/40815708/127763062-9c10dd57-1751-4ddb-ab77-48fd027bd433.png)

en-us:"https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/shapes/fillrules"
![shapes_fillrules_e](https://user-images.githubusercontent.com/40815708/127763064-68db23a9-1ee3-4f41-98f4-7549afd8b1a0.png)

#PingMSFTDocs

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e79c4ec0-db39-9ec2-105b-4a903b4528bd
* Version Independent ID: 6470272e-57e7-d0f9-279f-ddfb9ce4bdf4
* Content: [Xamarin.Forms Shapes: Fill rules - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/shapes/fillrules)
* Content Source: [docs/xamarin-forms/user-interface/shapes/fillrules.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/shapes/fillrules.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by hyoshioka0128** [comment]
Addition:"https://docs.microsoft.com/ja-jp/xamarin/xamarin-forms/user-interface/swipeview"

**Comment by hyoshioka0128** [comment]
Addition:
ja-jp:"https://docs.microsoft.com/ja-jp/xamarin/cross-platform/data-cloud/active-directory/graph"
![active-directory_graph_j](https://user-images.githubusercontent.com/40815708/127763364-26926ef8-7e9e-4565-bccc-4444303b8790.png)

**Comment by davidbritch** [comment]
[Microsoft support for Xamarin](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin) will end on May 1, 2024 for all Xamarin SDKs including Xamarin.Forms. In preparation for this, all issues and PRs in this repository are being closed.

.NET MAUI is the replacement for Xamarin.Forms, and it's documentation can be found [here](https://learn.microsoft.com/dotnet/maui/?view=net-maui-8.0).
