### ISSUE TITLE
Dark mode v. light mode

### ISSUE THREAD

**Issue by mprogers** [MicrosoftDocs/xamarin-docs#3345]
I discovered that if the device is set to dark mode, notes doesn't show up (until you highlight them). You _might_ want to mention that ...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7dc72705-2668-156f-d214-1a35d5a2ea4d
* Version Independent ID: 993ba392-f860-1a29-7d62-0dc1efbf6f0e
* Content: [Perform navigation in a Xamarin.Forms application - Xamarin](https://docs.microsoft.com/en-us/xamarin/get-started/quickstarts/navigation)
* Content Source: [docs/get-started/quickstarts/navigation.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/get-started/quickstarts/navigation.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
[Microsoft support for Xamarin](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin) will end on May 1, 2024 for all Xamarin SDKs including Xamarin.Forms. In preparation for this, all issues and PRs in this repository are being closed.

.NET MAUI is the replacement for Xamarin.Forms, and it's documentation can be found [here](https://learn.microsoft.com/dotnet/maui/?view=net-maui-8.0).
