### ISSUE TITLE
Showing "<a name=～"

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/xamarin-docs#3346]
ja-jp:"https://docs.microsoft.com/ja-jp/xamarin/ios/platform/multitasking"
![platform_multitasking_j](https://user-images.githubusercontent.com/40815708/128591094-87364312-5226-4950-91a0-1ecf409d78e7.png)

en-us:"https://docs.microsoft.com/en-us/xamarin/ios/platform/multitasking"
![platform_multitasking_e](https://user-images.githubusercontent.com/40815708/128591001-035c4ebf-7ea9-4962-a5f4-e80232cc8a46.png)

#PingMSFTDocs

**Comment by davidbritch** [comment]
[Microsoft support for Xamarin](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin) will end on May 1, 2024 for all Xamarin SDKs including Xamarin.Forms. In preparation for this, all issues and PRs in this repository are being closed.

.NET MAUI is the replacement for Xamarin.Forms, and it's documentation can be found [here](https://learn.microsoft.com/dotnet/maui/?view=net-maui-8.0).
