### ISSUE TITLE
Missing namespace in registration by attribute sample

### ISSUE THREAD

**Issue by bdrajer** [MicrosoftDocs/xamarin-docs#3347]
Shouldn't the Dependency attribute here state the full namespace of the class? It doesn't compile otherwise in my case...

Instead of this:

[assembly: Dependency(typeof(DeviceOrientationService))]
namespace DependencyServiceDemos.iOS
{
    public class DeviceOrientationService : IDeviceOrientationService
    {

Something like this:

[assembly: Dependency(typeof(DependencyServiceDemos.iOS.DeviceOrientationService))]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e66af026-e933-b091-ef25-8f7bd1399142
* Version Independent ID: e12ebe0d-55ed-9a21-65d3-382efe5bc74e
* Content: [Xamarin.Forms DependencyService Registration and Resolution - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/dependency-service/registration-and-resolution)
* Content Source: [docs/xamarin-forms/app-fundamentals/dependency-service/registration-and-resolution.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/app-fundamentals/dependency-service/registration-and-resolution.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
[Microsoft support for Xamarin](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin) will end on May 1, 2024 for all Xamarin SDKs including Xamarin.Forms. In preparation for this, all issues and PRs in this repository are being closed.

.NET MAUI is the replacement for Xamarin.Forms, and it's documentation can be found [here](https://learn.microsoft.com/dotnet/maui/?view=net-maui-8.0).
