### ISSUE TITLE
Please add guide about Pick one or multi file on Storage, SD Card!

### ISSUE THREAD

**Issue by nguyenthanhliemfc** [MicrosoftDocs/xamarin-docs#335]
Please add guide about Pick one or multi file on Storage, SD Card!
Thank you!

---
#### Chi tiết tài liệu

⚠ *Không chỉnh sửa phần này. Điều này là bắt buộc cho docs.microsoft.com ➟ Vấn đề khi liên kết GitHub.*

* ID: 22cd76be-2702-6a58-498c-a84c723d9588
* Version Independent ID: 9f98549e-ff3d-5b8d-67e6-523834c4dd6d
* Content: [Picking a Photo from the Picture Library - Xamarin](https://docs.microsoft.com/vi-vn/xamarin/xamarin-forms/app-fundamentals/dependency-service/photo-picker)
* Content Source: [docs/xamarin-forms/app-fundamentals/dependency-service/photo-picker.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/app-fundamentals/dependency-service/photo-picker.md)
* Service: **unspecified**
* Product: **xamarin**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by conceptdev** [comment]
Hi @nguyenthanhliemfc - those are Android-specific concepts that wouldn't really apply to iOS, for example. Using the information in the Dependency Service and Custom Renderer docs, you should be able to build a UI that provides those options only on supported platforms (such as Android). We will consider adding some more information about this in the future.
Thanks for your feedback.

**Comment by nguyenthanhliemfc** [comment]
Or could you please add docs How to pick Multi photos from Gallery. Thank you!
