### ISSUE TITLE
Unclear information in "What is Xamarin?" page?

### ISSUE THREAD

**Issue by molant** [MicrosoftDocs/xamarin-docs#3352]
Couple things I've spotted:

In the intro
> Xamarin enables developers to share an average of 90% of their application across platforms.

While in [How Xamarin works](https://docs.microsoft.com/en-us/xamarin/get-started/what-is-xamarin#how-xamarin-works) it says:

> In most cases, 80% of application code is sharable using Xamarin.

Also in the intro:

> for building modern and performant applications for iOS, Android, and Windows with .NET

But later on we have a link to [Xamarin.Mac](https://docs.microsoft.com/en-us/xamarin/mac/) so I guess the first statement is only about [Xamarin.Forms](https://docs.microsoft.com/en-us/xamarin/get-started/what-is-xamarin#xamarinforms) from what I can read in that same page? 

> Xamarin.Forms is an open-source UI framework. Xamarin.Forms allows developers to build Xamarin.iOS, Xamarin.Android, and Windows applications from a single shared codebase. 

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 95f1bfc6-27ee-d6b0-6823-bf44d37ae207
* Version Independent ID: 278e483a-9b38-451c-8b79-5c36da9190fe
* Content: [What is Xamarin? - Xamarin](https://docs.microsoft.com/en-us/xamarin/get-started/what-is-xamarin)
* Content Source: [docs/get-started/what-is-xamarin.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/get-started/what-is-xamarin.md)
* Product: **xamarin**
* Technology: **xamarin-crossplatform**
* GitHub Login: @profexorgeek
* Microsoft Alias: **jusjohns**

**Comment by davidbritch** [comment]
[Microsoft support for Xamarin](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin) will end on May 1, 2024 for all Xamarin SDKs including Xamarin.Forms. In preparation for this, all issues and PRs in this repository are being closed.

.NET MAUI is the replacement for Xamarin.Forms, and it's documentation can be found [here](https://learn.microsoft.com/dotnet/maui/?view=net-maui-8.0).
