### ISSUE TITLE
Typo in 2 architecture images

### ISSUE THREAD

**Issue by molant** [MicrosoftDocs/xamarin-docs#3353]
The images [ios-architecture](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/get-started/what-is-xamarin-images/ios-architecture.png) and [android-architecture.png](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/get-started/what-is-xamarin-images/android-architecture.png) have Kernel misspelled at the bottom.

These images are visible when clicking in the magnifying button of the relevant sections (Xamarin.Android and Xamarin.iOS).

![iOS architecture](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/get-started/what-is-xamarin-images/ios-architecture.png?raw=true)

![Android architecture](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/get-started/what-is-xamarin-images/android-architecture.png?raw=true)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 95f1bfc6-27ee-d6b0-6823-bf44d37ae207
* Version Independent ID: 278e483a-9b38-451c-8b79-5c36da9190fe
* Content: [What is Xamarin? - Xamarin](https://docs.microsoft.com/en-us/xamarin/get-started/what-is-xamarin#xamarinandroid)
* Content Source: [docs/get-started/what-is-xamarin.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/get-started/what-is-xamarin.md)
* Product: **xamarin**
* Technology: **xamarin-crossplatform**
* GitHub Login: @profexorgeek
* Microsoft Alias: **jusjohns**

**Comment by davidbritch** [comment]
[Microsoft support for Xamarin](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin) will end on May 1, 2024 for all Xamarin SDKs including Xamarin.Forms. In preparation for this, all issues and PRs in this repository are being closed.

.NET MAUI is the replacement for Xamarin.Forms, and it's documentation can be found [here](https://learn.microsoft.com/dotnet/maui/?view=net-maui-8.0).
