### ISSUE TITLE
Shell is not showing up for me.

### ISSUE THREAD

**Issue by jdschimmer** [MicrosoftDocs/xamarin-docs#3355]
[Enter feedback here]

I tried installing the Android piece of Visual Studio and still no luck.  Any suggestion?
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 88d9cae7-e913-cf8f-7275-82c3192103bf
* Version Independent ID: 40f2fb5f-25e1-6174-b545-da749f38ed47
* Content: [Create a Xamarin.Forms application quickstart - Xamarin](https://docs.microsoft.com/en-us/xamarin/get-started/quickstarts/app)
* Content Source: [docs/get-started/quickstarts/app.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/get-started/quickstarts/app.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
[Microsoft support for Xamarin](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin) will end on May 1, 2024 for all Xamarin SDKs including Xamarin.Forms. In preparation for this, all issues and PRs in this repository are being closed.

.NET MAUI is the replacement for Xamarin.Forms, and it's documentation can be found [here](https://learn.microsoft.com/dotnet/maui/?view=net-maui-8.0).
