### ISSUE TITLE
Printable Colour Chart Would be Really Useful

### ISSUE THREAD

**Issue by PatrickRyder** [MicrosoftDocs/xamarin-docs#3356]
[Enter feedback here]

A printable version of the colour chart would be fantastic - perhaps as a PDF?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aee8f50b-d6f4-0859-9598-d5498f9c4ede
* Version Independent ID: 36363d89-51e5-f5aa-de25-f6b56f144e3f
* Content: [Xamarin.Forms Brushes: Solid colors - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/brushes/solidcolor)
* Content Source: [docs/xamarin-forms/user-interface/brushes/solidcolor.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/brushes/solidcolor.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
[Microsoft support for Xamarin](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin) will end on May 1, 2024 for all Xamarin SDKs including Xamarin.Forms. In preparation for this, all issues and PRs in this repository are being closed.

.NET MAUI is the replacement for Xamarin.Forms, and it's documentation can be found [here](https://learn.microsoft.com/dotnet/maui/?view=net-maui-8.0).
