### ISSUE TITLE
OAuth 2.0 (AuthenticationState)

### ISSUE THREAD

**Issue by sebas3407** [MicrosoftDocs/xamarin-docs#336]
Hello I have followed the tutorial completely, but I am stuck in one part, when I copy the OpenUrl method, the following line marks me error:

`AuthenticationState.Authenticator.OnPageLoading(uri);`

And the error is: **AuthenticationState does not exist in the current context**

**Comment by conceptdev** [comment]
Referring to:
https://docs.microsoft.com/en-us/xamarin/xamarin-forms/data-cloud/authentication/oauth

**Comment by conceptdev** [comment]
Oh, this is not the answer, this is to help whomever responds to your question better understand what page you are referring to.

**Comment by davidbritch** [comment]
Hi @sebas3407 

At the bottom of each page there's usually a link to the sample for that doc. In this case, take a look at https://developer.xamarin.com/samples/xamarin-forms/WebServices/OAuthNativeFlow/ and hopefully your issue will be resolved.
