### ISSUE TITLE
Typo -> Requst

### ISSUE THREAD

**Issue by winkmichael** [MicrosoftDocs/xamarin-docs#3360]
[Enter feedback here]

Half way down it says;

This can then be used when calling RequstAsync:

Note Requst

It should be 

This can then be used when calling RequestAsync:

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e86cfbdf-277d-29ae-3999-33f73d91efc6
* Version Independent ID: cf9bfb50-9d1e-3c5d-139f-392dfc9550eb
* Content: [Xamarin.Essentials: Share - Xamarin](https://docs.microsoft.com/en-us/xamarin/essentials/share?tabs=android)
* Content Source: [docs/essentials/share.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/essentials/share.md)
* Product: **xamarin**
* Technology: **xamarin-essentials**
* GitHub Login: @jamesmontemagno
* Microsoft Alias: **jamont**

**Comment by davidbritch** [comment]
[Microsoft support for Xamarin](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin) will end on May 1, 2024 for all Xamarin SDKs including Xamarin.Forms. In preparation for this, all issues and PRs in this repository are being closed.

.NET MAUI is the replacement for Xamarin.Forms, and it's documentation can be found [here](https://learn.microsoft.com/dotnet/maui/?view=net-maui-8.0).
