### ISSUE TITLE
Create a Xamarin Forms App

### ISSUE THREAD

**Issue by Kent1945** [MicrosoftDocs/xamarin-docs#3361]
The following URL item 8 cannot be found using Visual Studio 2019.  I'm trying to learn something new and your example does not work with the current release of Visual Studio.

https://docs.microsoft.com/en-us/xamarin/get-started/quickstarts/app?pivots=windows

In Solution Explorer, in the Notes project, select the Views folder, right-click, and select Add > New Item.... In the Add New Item dialog, select Visual C# Items > Xamarin.Forms > Content Page, name the new file NotesPage, and click the Add button:

I just want to create something on my phone that is simple other than "Hello World".  I have a working Windows C# app that I would like to put on my mobile phone.

HELP!!!!
KLC 9/19/21

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 88d9cae7-e913-cf8f-7275-82c3192103bf
* Version Independent ID: 40f2fb5f-25e1-6174-b545-da749f38ed47
* Content: [Create a Xamarin.Forms application quickstart - Xamarin](https://docs.microsoft.com/en-us/xamarin/get-started/quickstarts/app)
* Content Source: [docs/get-started/quickstarts/app.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/get-started/quickstarts/app.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
[Microsoft support for Xamarin](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin) will end on May 1, 2024 for all Xamarin SDKs including Xamarin.Forms. In preparation for this, all issues and PRs in this repository are being closed.

.NET MAUI is the replacement for Xamarin.Forms, and it's documentation can be found [here](https://learn.microsoft.com/dotnet/maui/?view=net-maui-8.0).
