### ISSUE TITLE
Invalid hyperlink to pdf

### ISSUE THREAD

**Issue by joramhowest** [MicrosoftDocs/xamarin-docs#3362]
> "For more information about the [CarouselPage](https://docs.microsoft.com/en-us/dotnet/api/xamarin.forms.carouselpage), see **[Chapter 25](https://developer.xamarin.com/r/xamarin-forms/book/chapter25.pdf)** of Charles Petzold's Xamarin.Forms book."

This seems to be outdated. The link to chapter 25 no longer seems to be working.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b07827d3-68e2-b7e0-173d-f3c7ef581a8e
* Version Independent ID: a19e5c74-5cd4-1291-af4d-a97d7a8d5dd0
* Content: [Xamarin.Forms Carousel Page - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/navigation/carousel-page)
* Content Source: [docs/xamarin-forms/app-fundamentals/navigation/carousel-page.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/app-fundamentals/navigation/carousel-page.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
[Microsoft support for Xamarin](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin) will end on May 1, 2024 for all Xamarin SDKs including Xamarin.Forms. In preparation for this, all issues and PRs in this repository are being closed.

.NET MAUI is the replacement for Xamarin.Forms, and it's documentation can be found [here](https://learn.microsoft.com/dotnet/maui/?view=net-maui-8.0).
