### ISSUE TITLE
Xamarin Hot Restart doesn't appear in my options

### ISSUE THREAD

**Issue by Wuzziie** [MicrosoftDocs/xamarin-docs#3366]
Hello,

Recently I have decided to create a mobile application, but I have a problem, I can't use Xamarin Hot Restart because in my option that doesn't appear.
![visual-problem](https://user-images.githubusercontent.com/91999942/136127822-dfa8244e-85ab-485f-b5d6-03073b0d5baa.PNG)

I check the version of my Visual Studio 2019 and it's the good one to get the Xamarin Hot Restart. 
![visual_version](https://user-images.githubusercontent.com/91999942/136127819-72d72492-c33d-477c-8dd3-5721fe56a323.PNG)

If you have some solution about my problem, thank you so much.

Best regards,
Wuzziie

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8f3eb808-8e6d-4e07-fc75-8d79a7249265
* Version Independent ID: dbb2b9a9-87a6-e473-50e6-f88435d49e88
* Content: [Xamarin Hot Restart - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/deploy-test/hot-restart)
* Content Source: [docs/xamarin-forms/deploy-test/hot-restart.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/deploy-test/hot-restart.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @maddyleger1
* Microsoft Alias: **maleger**

**Comment by davidbritch** [comment]
[Microsoft support for Xamarin](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin) will end on May 1, 2024 for all Xamarin SDKs including Xamarin.Forms. In preparation for this, all issues and PRs in this repository are being closed.

.NET MAUI is the replacement for Xamarin.Forms, and it's documentation can be found [here](https://learn.microsoft.com/dotnet/maui/?view=net-maui-8.0).
