### ISSUE TITLE
Error in code

### ISSUE THREAD

**Issue by domagojmedo** [MicrosoftDocs/xamarin-docs#337]
catch (FeatureNotSupportedException fbsEx)
        {
            // Sms is not supported on this device
        }

Shouldn't message be Email is not supported?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 51ff7357-2cd8-7988-ed3c-de156cc18211
* Version Independent ID: ff242941-6d92-9523-bd73-ec03dbcb095d
* Content: [Xamarin.Essentials Email - Xamarin](https://docs.microsoft.com/en-us/xamarin/essentials/email?context=xamarin/xamarin-forms)
* Content Source: [docs/essentials/email.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/essentials/email.md)
* Service: **unspecified**
* Product: **xamarin**
* GitHub Login: @jamesmontemagno
* Microsoft Alias: **jamont**

**Comment by jamesmontemagno** [comment]
Good find!

**Comment by conceptdev** [comment]
This has been fixed, thanks.
