### ISSUE TITLE
All links to the ebook are broken. 

### ISSUE THREAD

**Issue by GregWoods** [MicrosoftDocs/xamarin-docs#3371]
It doesn't surprise my though.... Microsoft are the worst for shuffling content around,  changing URLs, and renaming or retiring whole sections of their web presence  without maintaining links

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 552cf4bf-553b-d7f4-adc6-7e696029c18b
* Version Independent ID: 67f96253-4908-3f85-fd2f-07563d1b4f7b
* Content: [Creating Mobile Apps with Xamarin.Forms book - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/creating-mobile-apps-xamarin-forms/)
* Content Source: [docs/xamarin-forms/creating-mobile-apps-xamarin-forms/index.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/creating-mobile-apps-xamarin-forms/index.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
[Microsoft support for Xamarin](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin) will end on May 1, 2024 for all Xamarin SDKs including Xamarin.Forms. In preparation for this, all issues and PRs in this repository are being closed.

.NET MAUI is the replacement for Xamarin.Forms, and it's documentation can be found [here](https://learn.microsoft.com/dotnet/maui/?view=net-maui-8.0).
