### ISSUE TITLE
XAML Label Tutorial - Sentence is underlined.

### ISSUE THREAD

**Issue by abhidotnet** [MicrosoftDocs/xamarin-docs#3373]
I was following your Xamarin Label tutorial. The formatted string on the label control is underlined, although a text-decoration is missing on it.

I have taken a screenshot of the XAML and the display in the android emulator. The entire sentence is getting underlined for me. This isn't the case in your screenshot in the tutorial. I have copied the exact same XAML code. Please check the attached screenshot.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b0b433b5-8544-660f-493f-3219c489953e
* Version Independent ID: 6bb8278a-e685-683d-6a35-067eb85b951b
* Content: [X
![xamlUnderline](https://user-images.githubusercontent.com/164457/138961286-47aae2f0-d66e-4e90-90b8-8187b2681775.png)
amarin.Forms Label Tutorial - Xamarin](https://docs.microsoft.com/en-us/xamarin/get-started/tutorials/label/?tabs=vswin)
* Content Source: [docs/get-started/tutorials/label/index.yml](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/get-started/tutorials/label/index.yml)
* Product: **xamarin**
* Technology: **xamarin-crossplatform**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
[Microsoft support for Xamarin](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin) will end on May 1, 2024 for all Xamarin SDKs including Xamarin.Forms. In preparation for this, all issues and PRs in this repository are being closed.

.NET MAUI is the replacement for Xamarin.Forms, and it's documentation can be found [here](https://learn.microsoft.com/dotnet/maui/?view=net-maui-8.0).
