### ISSUE TITLE
Setup guide leads to application crashing with you_should_not_call_base_in_this_method exception.

### ISSUE THREAD

**Issue by ghasszak** [MicrosoftDocs/xamarin-docs#3377]
[Enter feedback here]

Hello,

I've experienced several crashes on my Xamarin Application, due to this code snippet
 public override bool OpenUrl(UIApplication app, NSUrl url, NSDictionary options)
```
{
    if (Xamarin.Essentials.Platform.OpenUrl(app, url, options))
        return true;

    return base.OpenUrl(app, url, options);
}
```

Indeed, UIApplicationDelegate.OpenUrl(app, url, options) throws a you_should_not_call_base_in_this_method exception.

I'm on Xamarin Essentials 1.6 and SDK 13.4

I think the docs need to be updated to adress this issue
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1231a1e1-3734-9021-2cc7-eaf99478afca
* Version Independent ID: 01e5fdbe-0b15-4dbe-f8a0-ed40f8593302
* Content: [Xamarin.Essentials: Web Authenticator - Xamarin](https://docs.microsoft.com/en-us/xamarin/essentials/web-authenticator?tabs=ios)
* Content Source: [docs/essentials/web-authenticator.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/essentials/web-authenticator.md)
* Product: **xamarin**
* Technology: **xamarin-essentials**
* GitHub Login: @Redth
* Microsoft Alias: **jodick**

**Comment by davidbritch** [comment]
[Microsoft support for Xamarin](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin) will end on May 1, 2024 for all Xamarin SDKs including Xamarin.Forms. In preparation for this, all issues and PRs in this repository are being closed.

.NET MAUI is the replacement for Xamarin.Forms, and it's documentation can be found [here](https://learn.microsoft.com/dotnet/maui/?view=net-maui-8.0).
