### ISSUE TITLE
You can add to the manifest some extra-lines

### ISSUE THREAD

**Issue by benjamingranados** [MicrosoftDocs/xamarin-docs#3378]
To be more specific in the Manifest...
```
<uses-feature android:name="android.hardware.camera" android:required="true" />
<uses-feature android:name="android.hardware.camera.autofocus" android:required="false" />
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e4b43ab7-fd40-ba56-c9ab-5de2eb1aad7f
* Version Independent ID: 6c9c7c48-4401-cb25-5cda-637718a22961
* Content: [Xamarin.Essentials: Media Picker - Xamarin](https://docs.microsoft.com/en-us/xamarin/essentials/media-picker?tabs=android)
* Content Source: [docs/essentials/media-picker.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/essentials/media-picker.md)
* Product: **xamarin**
* Technology: **xamarin-essentials**
* GitHub Login: @jamesmontemagno
* Microsoft Alias: **jamont**

**Comment by davidbritch** [comment]
[Microsoft support for Xamarin](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin) will end on May 1, 2024 for all Xamarin SDKs including Xamarin.Forms. In preparation for this, all issues and PRs in this repository are being closed.

.NET MAUI is the replacement for Xamarin.Forms, and it's documentation can be found [here](https://learn.microsoft.com/dotnet/maui/?view=net-maui-8.0).
