### ISSUE TITLE
Multi-Touch Effect -  Crash on Android Platform

### ISSUE THREAD

**Issue by BelightWavre** [MicrosoftDocs/xamarin-docs#3379]
Hello,

Sorry, I'm new to contribute to Xamarin Doc.  So I prefer to open an issue and let you check this. Don't hesitate to give my feed back !

I encouter some crashes on Android platform.
In some circumstances, the Id already exists in the idToEffectDictionary dictionary while an new Down ou PointerDown event is fired (with the same id than an existing one) ... ! So I add some Key checking before insertion (see bold lines below).

It solves the problem and I didn't see any backside effect up to now.
Any better idee or comment ?

```
                case MotionEventActions.Down:
                case MotionEventActions.PointerDown:
                    FireEvent(this, id, TouchActionType.Pressed, screenPointerCoords, true);

                   // Added by Belight on 2021/11/03
                    **if (idToEffectDictionary.ContainsKey(id)) 
                        idToEffectDictionary[id] = this;

                    else**
                    // End of addition
                        idToEffectDictionary.Add(id, this);  // Memorises the id of the touch within the effect who "receive" it

                    capture = libTouchEffect.Capture;
                    break;
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 908530d1-f21d-5532-c530-1727e3356b64
* Version Independent ID: e01f2543-3b7d-0b60-8d79-c012feab83de
* Content: [Invoking Events from Effects - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/effects/touch-tracking)
* Content Source: [docs/xamarin-forms/app-fundamentals/effects/touch-tracking.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/app-fundamentals/effects/touch-tracking.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
[Microsoft support for Xamarin](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin) will end on May 1, 2024 for all Xamarin SDKs including Xamarin.Forms. In preparation for this, all issues and PRs in this repository are being closed.

.NET MAUI is the replacement for Xamarin.Forms, and it's documentation can be found [here](https://learn.microsoft.com/dotnet/maui/?view=net-maui-8.0).
