### ISSUE TITLE
Is using DependencyService for regular IoC the recommended approach or not?

### ISSUE THREAD

**Issue by marwalsch** [MicrosoftDocs/xamarin-docs#3380]
I take the `DependencyService` is responsible for exposing platform-specific implementations to the client app at runtime.

But can the same container be used to register platform agnostic services just for IoC's sake? The docs don't elaborate on that and there appears to be no alternative given.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6e9eecf7-0edb-5b24-964c-a1ae2e7556ba
* Version Independent ID: 8f9243b4-0f7c-6aac-39e2-913173ea472a
* Content: [Xamarin.Forms DependencyService Introduction - Xamarin](https://docs.microsoft.com/en-gb/xamarin/xamarin-forms/app-fundamentals/dependency-service/introduction)
* Content Source: [docs/xamarin-forms/app-fundamentals/dependency-service/introduction.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/app-fundamentals/dependency-service/introduction.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
[Microsoft support for Xamarin](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin) will end on May 1, 2024 for all Xamarin SDKs including Xamarin.Forms. In preparation for this, all issues and PRs in this repository are being closed.

.NET MAUI is the replacement for Xamarin.Forms, and it's documentation can be found [here](https://learn.microsoft.com/dotnet/maui/?view=net-maui-8.0).
