### ISSUE TITLE
Example image is not clear

### ISSUE THREAD

**Issue by mrlacey** [MicrosoftDocs/xamarin-docs#3381]
[The image](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/platform/ios/tabbedpage-translucent-tabbar-images/translucencymodes.png) on this page does not clearly show what the different settings/options do.
I cannot see any visible difference between the three options the image supposedly shows.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a52cd5e-2cc8-0398-dcb3-db2607f11c1b
* Version Independent ID: c2586399-6b8c-78c6-e0da-fa3e35adb00a
* Content: [TabbedPage translucent tab bar on iOS - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/platform/ios/tabbedpage-translucent-tabbar)
* Content Source: [docs/xamarin-forms/platform/ios/tabbedpage-translucent-tabbar.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/platform/ios/tabbedpage-translucent-tabbar.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
[Microsoft support for Xamarin](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin) will end on May 1, 2024 for all Xamarin SDKs including Xamarin.Forms. In preparation for this, all issues and PRs in this repository are being closed.

.NET MAUI is the replacement for Xamarin.Forms, and it's documentation can be found [here](https://learn.microsoft.com/dotnet/maui/?view=net-maui-8.0).
