### ISSUE TITLE
404 error trying to look at the Picker Demo

### ISSUE THREAD

**Issue by samnanduri** [MicrosoftDocs/xamarin-docs#3382]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b47354c0-5630-f56c-4632-d69bbe124b59
* Version Independent ID: 4dda513e-0364-d692-46fb-372e741526fd
* Content: [Adding Data to a Picker's Items Collection - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/picker/populating-items)
* Content Source: [docs/xamarin-forms/user-interface/picker/populating-items.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/picker/populating-items.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
[Microsoft support for Xamarin](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin) will end on May 1, 2024 for all Xamarin SDKs including Xamarin.Forms. In preparation for this, all issues and PRs in this repository are being closed.

.NET MAUI is the replacement for Xamarin.Forms, and it's documentation can be found [here](https://learn.microsoft.com/dotnet/maui/?view=net-maui-8.0).
