### ISSUE TITLE
There should be a simple center and resize example here ...

### ISSUE THREAD

**Issue by stephenhauck** [MicrosoftDocs/xamarin-docs#3383]
This splash is basically the bare bones terrible example.
We should have a resolution independent example here of using image in a splash screen ... Xamarin has been around long enough.

There are lots of hacks out there in Google but there should be a definitive answer here because they are all problematic.

I did not realize what an issue this is until I have to get an app submitted to the store.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a5a4e93b-006f-176e-cf02-108f48bff807
* Version Independent ID: 2d677054-ae70-1eb1-903d-70b4f6cdfc50
* Content: [Xamarin.Forms splash screen - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/splashscreen)
* Content Source: [docs/xamarin-forms/user-interface/splashscreen.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/splashscreen.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @profexorgeek
* Microsoft Alias: **jusjohns**

**Comment by davidbritch** [comment]
[Microsoft support for Xamarin](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin) will end on May 1, 2024 for all Xamarin SDKs including Xamarin.Forms. In preparation for this, all issues and PRs in this repository are being closed.

.NET MAUI is the replacement for Xamarin.Forms, and it's documentation can be found [here](https://learn.microsoft.com/dotnet/maui/?view=net-maui-8.0).
