### ISSUE TITLE
Page still contains reference to Windows Mobile 10

### ISSUE THREAD

**Issue by Waveslam** [MicrosoftDocs/xamarin-docs#3384]
Hi
This page has obviously been edited to remove examples that relate to Windows 10 Mobile (which is no longer supported) but still contains the reference "...These are visible as icons on the top of the iOS and Android screens, and on the bottom of the Windows 10 Mobile screen."

Cheers
Brett

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0951037b-bdc8-f98e-e8c3-fe1f4acaa6bf
* Version Independent ID: 218f322f-ddb1-02a6-9611-63c079b9bbff
* Content: [Summary of Chapter 1. How does Xamarin.Forms fit in? - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/creating-mobile-apps-xamarin-forms/summaries/chapter01)
* Content Source: [docs/xamarin-forms/creating-mobile-apps-xamarin-forms/summaries/chapter01.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/creating-mobile-apps-xamarin-forms/summaries/chapter01.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
[Microsoft support for Xamarin](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin) will end on May 1, 2024 for all Xamarin SDKs including Xamarin.Forms. In preparation for this, all issues and PRs in this repository are being closed.

.NET MAUI is the replacement for Xamarin.Forms, and it's documentation can be found [here](https://learn.microsoft.com/dotnet/maui/?view=net-maui-8.0).
