### ISSUE TITLE
Guess download means something different to you

### ISSUE THREAD

**Issue by sqlguy6212** [MicrosoftDocs/xamarin-docs#3385]
So a link to a download that is not really a link to a download.  Why do you bother?  Just trying to irritate people (it's working).

I am trying to learn Xamarin but mostly I am learning that MS does not know how to do as they say.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 74e39183-f10a-d07e-9313-b5b3466dfa09
* Version Independent ID: 6719875a-ef95-b55c-42ef-9e0ab063eb4b
* Content: [Xamarin.Forms FlyoutPage - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/navigation/flyoutpage)
* Content Source: [docs/xamarin-forms/app-fundamentals/navigation/flyoutpage.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/app-fundamentals/navigation/flyoutpage.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
[Microsoft support for Xamarin](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin) will end on May 1, 2024 for all Xamarin SDKs including Xamarin.Forms. In preparation for this, all issues and PRs in this repository are being closed.

.NET MAUI is the replacement for Xamarin.Forms, and it's documentation can be found [here](https://learn.microsoft.com/dotnet/maui/?view=net-maui-8.0).
