### ISSUE TITLE
Once again a download link with no download

### ISSUE THREAD

**Issue by sqlguy6212** [MicrosoftDocs/xamarin-docs#3386]
Why do you bother?  If there is no download why have a link to it?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a303fbe7-5786-651e-e730-90efb1796e72
* Version Independent ID: 6a6a96eb-7563-8b4f-1272-1eb7bd221fb7
* Content: [Xamarin.Forms Shell flyout - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/shell/flyout)
* Content Source: [docs/xamarin-forms/app-fundamentals/shell/flyout.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/app-fundamentals/shell/flyout.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
@sqlguy6212 Which download link are you referring to? The sample?

**Comment by sqlguy6212** [comment]
The page that is in error is: https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/navigation/flyoutpage There is a download link that just goes to another page. Lloyd Sheen Sent from Mail for Windows From: David BritchSent: November 17, 2021 10:12 AMTo: MicrosoftDocs/xamarin-docsCc: sqlguy6212; MentionSubject: Re: [MicrosoftDocs/xamarin-docs] Once again a download link with no download (Issue ***@***.*** Which download link are you referring to? The sample?—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by davidbritch** [comment]
I can see two download links on the page:

1. Download the sample
2. Download PDF

Both work fine for me.

**Comment by davidbritch** [comment]
Ok, finally think I understand your problem. Download the sample takes you to another page where you can browse the code, but can't download it. Afraid that the ability to download samples was deliberately disabled centrally, and we can't turn it back on.

**Comment by sqlguy6212** [comment]
I see only a Download the sample link, no Download PDF.   The Download the sample link goes to :https://docs.microsoft.com/en-us/samples/xamarin/xamarin-forms-samples/navigation-flyoutpage/ What I am trying to is learn Xamarin and I am having many problems.  I have created all sorts of forms and tried to create a Flyout form from VS 2022 Community.  What is created does not even compile so I have to wonder why this is?  And if downloads are not available why are links to them there? Lloyd Sheen Sent from Mail for Windows From: David BritchSent: November 17, 2021 10:20 AMTo: MicrosoftDocs/xamarin-docsCc: sqlguy6212; MentionSubject: Re: [MicrosoftDocs/xamarin-docs] Once again a download link with no download (Issue #3386) I can see two download links on the page:Download the sampleDownload PDFBoth work fine for me.—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by davidbritch** [comment]
[Microsoft support for Xamarin](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin) will end on May 1, 2024 for all Xamarin SDKs including Xamarin.Forms. In preparation for this, all issues and PRs in this repository are being closed.

.NET MAUI is the replacement for Xamarin.Forms, and it's documentation can be found [here](https://learn.microsoft.com/dotnet/maui/?view=net-maui-8.0).
