### ISSUE TITLE
c# equivalent code missing

### ISSUE THREAD

**Issue by JBoysen1** [MicrosoftDocs/xamarin-docs#3388]
These examples do not have C# equivalent code, only XAML

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b744a13f-16ad-4f35-cdf2-bdfd6fa90df1
* Version Independent ID: 7a08549b-07a5-085b-0c93-255d9e84d7a3
* Content: [Xamarin.Forms Visual State Manager - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/visual-state-manager)
* Content Source: [docs/xamarin-forms/user-interface/visual-state-manager.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/visual-state-manager.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
[Microsoft support for Xamarin](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin) will end on May 1, 2024 for all Xamarin SDKs including Xamarin.Forms. In preparation for this, all issues and PRs in this repository are being closed.

.NET MAUI is the replacement for Xamarin.Forms, and it's documentation can be found [here](https://learn.microsoft.com/dotnet/maui/?view=net-maui-8.0).
