### ISSUE TITLE
Update documentation to match Xamarin Forms 3.0

### ISSUE THREAD

**Issue by DamionGans** [MicrosoftDocs/xamarin-docs#339]
For example the support for WPF is not in preview anymore with the public release for Xamarin.Forms 3.0

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 710e69e5-df3b-c83e-2731-941de51279b5
* Version Independent ID: a4024124-4809-9031-2b3b-e122c765bb4d
* Content: [WPF Platform Setup - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/platform/wpf#issues)
* Content Source: [docs/xamarin-forms/platform/wpf.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/platform/wpf.md)
* Service: **unspecified**
* Product: **xamarin**
* GitHub Login: @charlespetzold
* Microsoft Alias: **chape**

**Comment by conceptdev** [comment]
Hi @DamionGans, WPF support is still in preview. You can view the current status on the [open source repo wiki](https://github.com/xamarin/Xamarin.Forms/wiki/Platform-Support).
Thanks
