### ISSUE TITLE
Samples are missing workability

### ISSUE THREAD

**Issue by sqlguy6212** [MicrosoftDocs/xamarin-docs#3390]
I would be able to tell you more but since this dialog gets rid of the page I am at a loss.

What I can say is  that there is code to create a Image called webImage but no where is there anything to show how to use that Image (C#).

[Enter feedback here]

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7eeb0e65-143b-0f5e-a8fb-c75309689338
* Version Independent ID: 6b984264-a950-4310-483f-99f908b0a8b0
* Content: [Images in Xamarin.Forms - Xamarin](https://docs.microsoft.com/en-ca/xamarin/xamarin-forms/user-interface/images?tabs=windows#Using_Xaml)
* Content Source: [docs/xamarin-forms/user-interface/images.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/images.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
[Microsoft support for Xamarin](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin) will end on May 1, 2024 for all Xamarin SDKs including Xamarin.Forms. In preparation for this, all issues and PRs in this repository are being closed.

.NET MAUI is the replacement for Xamarin.Forms, and it's documentation can be found [here](https://learn.microsoft.com/dotnet/maui/?view=net-maui-8.0).
