### ISSUE TITLE
Lack of Information

### ISSUE THREAD

**Issue by BrienKing** [MicrosoftDocs/xamarin-docs#3393]
It would be really nice to know what HTML tags are currently supported by the Label.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f8a6273c-62b1-ac18-aab3-62f78bdbade8
* Version Independent ID: 746bd180-ae67-313d-b949-538a508807b2
* Content: [Xamarin.Forms Label - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/text/label#styling-labels)
* Content Source: [docs/xamarin-forms/user-interface/text/label.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/text/label.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
[Microsoft support for Xamarin](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin) will end on May 1, 2024 for all Xamarin SDKs including Xamarin.Forms. In preparation for this, all issues and PRs in this repository are being closed.

.NET MAUI is the replacement for Xamarin.Forms, and it's documentation can be found [here](https://learn.microsoft.com/dotnet/maui/?view=net-maui-8.0).
