### ISSUE TITLE
"Intro to Wear" documentation page mentions deprecated APIs

### ISSUE THREAD

**Issue by edetoc** [MicrosoftDocs/xamarin-docs#3395]
### "Intro to Wear" documentation page mentions deprecated APIs

this page of the documentation does mention WearableClass.DataApi and WearableClass.MessageApi :
https://docs.microsoft.com/en-us/xamarin/android/wear/get-started/intro-to-wear#communications

However both appear to be deprecated according to Google Android documentation:
https://developers.google.com/android/reference/com/google/android/gms/wearable/DataApi
https://developers.google.com/android/reference/com/google/android/gms/wearable/MessageApi

Please update documentation to mention the replacement APIs (DataClient / MessageClient).

**Comment by davidbritch** [comment]
[Microsoft support for Xamarin](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin) will end on May 1, 2024 for all Xamarin SDKs including Xamarin.Forms. In preparation for this, all issues and PRs in this repository are being closed.

.NET MAUI is the replacement for Xamarin.Forms, and it's documentation can be found [here](https://learn.microsoft.com/dotnet/maui/?view=net-maui-8.0).
