### ISSUE TITLE
[XForms-UWP]Pinch gesture recognizer not wroking

### ISSUE THREAD

**Issue by SakthivelCapgemini** [MicrosoftDocs/xamarin-docs#3397]
### Doc issue description

https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/gestures/pinch

**Comment by SakthivelCapgemini** [comment]
Any update on this?

**Comment by davidbritch** [comment]
[Microsoft support for Xamarin](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin) will end on May 1, 2024 for all Xamarin SDKs including Xamarin.Forms. In preparation for this, all issues and PRs in this repository are being closed.

.NET MAUI is the replacement for Xamarin.Forms, and it's documentation can be found [here](https://learn.microsoft.com/dotnet/maui/?view=net-maui-8.0).
