### ISSUE TITLE
404 error

### ISSUE THREAD

**Issue by EnricoTirotta** [MicrosoftDocs/xamarin-docs#34]
"Installing Visual Studio for Mac" on left menu returns 404 error

href link : https://docs.microsoft.com/it-it/visualstudio/mac/installation/)%20(Installazione%20di%20Visual%20Studio%20per%20Mac

In the same menu there is a problem with "Istruzioni di configurazione del firewall" link
<img width="268" alt="schermata 2018-03-16 alle 17 47 33" src="https://user-images.githubusercontent.com/33745977/37533605-9a559c8c-2942-11e8-90ab-c5b4c20f7a11.png">

---
#### Dettagli del documento

⚠ *Non modificare questa sezione. È necessaria per i collegamenti relativi ai problemi tra docs.microsoft.com ➟ GitHub.*

* ID: 802a751e-ac74-cb5b-3a40-33044df2c46e
* Version Independent ID: e27cba22-ffae-dd13-3556-ab39fe41213c
* Content: [Installazione - Xamarin](https://docs.microsoft.com/it-it/xamarin/cross-platform/get-started/installation/#)
* Content Source: [docs/cross-platform/get-started/installation/index.md](https://github.com/MicrosoftDocs/xamarin-docs-pr.it-IT/blob/live-sxs/docs/cross-platform/get-started/installation/index.md)
* Service: **unspecified**
* GitHub Login: @asb3993
* Microsoft Alias: **amburns**

**Comment by asb3993** [comment]
Hey @EnricoTirotta, thanks for your report! We're working on fixing this. In the meantime, if you need to install (or know more about) Visual Studio for Mac you can find the information here: https://docs.microsoft.com/en-us/visualstudio/mac/installation

**Comment by nokura** [comment]
Thank you @EnricoTirotta for reporting. I am International PM and have requested the fix. This should be fixed in few days.

**Comment by conceptdev** [comment]
This has now been fixed - thanks for your feedback!
<img width="204" alt="screen shot 2018-04-24 at 9 59 07 am" src="https://user-images.githubusercontent.com/199373/39202229-2604aa30-47a6-11e8-9886-1aed41bdd3d5.png">
