### ISSUE TITLE
Problem: after logging in with Google the browser does NOT disappear .

### ISSUE THREAD

**Issue by rogerms** [MicrosoftDocs/xamarin-docs#340]
After entering my info into google authentication page the page goes away but the browser stays open on top of my app. To get back to my app I need to manually close the browser. I found something that fixes that; I think you guys should update your sample code with that solution.  

file: CustomUrlSchemeInterceptorActivity.cs

protected override void OnCreate(Bundle savedInstanceState)
{
. . .
           var intent = new Intent(this, typeof(MainActivity));
            intent.SetFlags(ActivityFlags.ClearTop | ActivityFlags.SingleTop);
            StartActivity(intent);
     Finish();
}
Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aa8bb9e0-5898-0d11-0213-fd4d8c8d0297
* Version Independent ID: 2f46e1f7-164f-2f32-70c0-f28919d16c5c
* Content: [Authenticating Users with an Identity Provider - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/data-cloud/authentication/oauth)
* Content Source: [docs/xamarin-forms/data-cloud/authentication/oauth.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/data-cloud/authentication/oauth.md)
* Service: **unspecified**
* Product: **xamarin**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by Xcalllibur** [comment]
Any update on whether a proper fix for this will be released?  The above fix is a brute force hack and causes problems when the activity is 're-started'

**Comment by davidbritch** [comment]
Hi @rogerms 

Thanks for pointing this out. While samples work on first publish, updates are required as OS's are updated and backend services change.  I've logged an issue in our backlog to investigate/update the sample/doc.
