### ISSUE TITLE
Inconsistent information.  

### ISSUE THREAD

**Issue by Kbmobi** [MicrosoftDocs/xamarin-docs#3403]
I don't know if the first one is the intended action. It's annoying because that is the function I wanted--press enter on keyboard to fire event; unfortunately, the actual functionality is the 2nd one. Where it calls the event when focus is lost from the editor. I am using Xamarin Forms in UWP. 

https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/text/editor
Completed – raised when the user has ended input by pressing the return key on the keyboard.

https://docs.microsoft.com/en-us/dotnet/api/xamarin.forms.editor.completed?view=xamarin-forms
iOS (Unfocusing the editor or pressing "Done" triggers the event). Android / Windows Phone (Unfocusing the Editor triggers the event)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8881d8f1-1d94-e090-e709-aca80b644a78
* Version Independent ID: 298aeed6-5e3e-f053-10f0-66d1061b4b2e
* Content: [Xamarin.Forms Editor - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/text/editor)
* Content Source: [docs/xamarin-forms/user-interface/text/editor.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/text/editor.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
[Microsoft support for Xamarin](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin) will end on May 1, 2024 for all Xamarin SDKs including Xamarin.Forms. In preparation for this, all issues and PRs in this repository are being closed.

.NET MAUI is the replacement for Xamarin.Forms, and it's documentation can be found [here](https://learn.microsoft.com/dotnet/maui/?view=net-maui-8.0).
