### ISSUE TITLE
The type or namespace name 'Essentials' does not exist in the namespace 'Xamarin' (are you missing an assembly reference?)	BlazorHybrid (net6.0-android)

### ISSUE THREAD

**Issue by nssidhu** [MicrosoftDocs/xamarin-docs#3405]
I am Creating Blazor MAUI Hybrid App. where i am trying to Add Map.

when i try to add the following Line

```
protected override void OnCreate(Bundle savedInstanceState) 
{
    //...
    base.OnCreate(savedInstanceState);
    Xamarin.Essentials.Platform.Init(this, savedInstanceState); // add this line to your code, it may also be called: bundle
    //...
}    
```

I get the following error.

`Error	CS0234	The type or namespace name 'Essentials' does not exist in the namespace 'Xamarin' (are you missing an assembly reference?)	BlazorHybrid (net6.0-android)	`

If i manually add the Xamarin.Essentials Nuget Package, i get the following error.

```
Error	XA4215	The Java type `xamarin.essentials.fileProvider` is generated by more than one managed type. Please change the [Register] attribute so that the same Java type is not emitted.	

Error	XA4215	  `xamarin.essentials.fileProvider` generated by: Microsoft.Maui.Essentials.FileProvider, Microsoft.Maui.Essentials, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null	BlazorHybrid	
	
Error	XA4215	  `xamarin.essentials.fileProvider` generated by: Xamarin.Essentials.FileProvider, Xamarin.Essentials, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null	BlazorHybrid	
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f0acf3fa-b705-f0cc-b676-eeca60176dfa
* Version Independent ID: 1788a5d5-a3cb-15c8-927c-b6a24810245a
* Content: [Xamarin.Essentials: Geolocation - Xamarin](https://docs.microsoft.com/en-us/xamarin/essentials/geolocation?tabs=android)
* Content Source: [docs/essentials/geolocation.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/essentials/geolocation.md)
* Product: **xamarin**
* Technology: **xamarin-essentials**
* GitHub Login: @jamesmontemagno
* Microsoft Alias: **jamont**

**Comment by jamesmontemagno** [comment]
You will want to use .NET MAUI Essentials, which is built into .NET MAUI. Do not use Xamarin.Essentials. 

using Microsoft.Maui.Essentials;
