### ISSUE TITLE
Can Xamarin.Essentials be used in Blazor MAUI HybridApp ?

### ISSUE THREAD

**Issue by nssidhu** [MicrosoftDocs/xamarin-docs#3406]
Can Xamarin.Essentials be used from Blazor MAUI Hybrid App ?
Any documentation on how to use that ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c420b152-7303-918a-dbc8-8d1e539c64ec
* Version Independent ID: fe85e24f-c3fc-3763-b1db-6b360fb08067
* Content: [Xamarin.Essentials - Xamarin](https://docs.microsoft.com/en-us/xamarin/essentials/)
* Content Source: [docs/essentials/index.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/essentials/index.md)
* Product: **xamarin**
* Technology: **xamarin-essentials**
* GitHub Login: @jamesmontemagno
* Microsoft Alias: **jamont**

**Comment by jamesmontemagno** [comment]
.NET MAUI Essentials is part of .NET MAUI :) aka Essentials is now built into .NET MAUI, so you do not need to add the Xamarin.Essentials package.

The namespace is "Microsoft.Maui.Essentials"
