### ISSUE TITLE
NumberOfTapsRequired greater than 2 does not work on Android

### ISSUE THREAD

**Issue by ioiooi** [MicrosoftDocs/xamarin-docs#3412]
Hi,
using a number greater than 2 for NumberOfTapsRequired does not work on Android.
See the following GitHub Issue: https://github.com/xamarin/Xamarin.Forms/issues/6976 .
Having a `Important`, `Note` or `Platform Differences` Element on the Page which describes this behaviour would be really great.

cheers

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1e56a604-3af6-80e9-b9df-382e3102a098
* Version Independent ID: 29cc319e-2736-013c-7934-b4335eb8242d
* Content: [Add a tap gesture recognizer - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/gestures/tap)
* Content Source: [docs/xamarin-forms/app-fundamentals/gestures/tap.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/app-fundamentals/gestures/tap.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
[Microsoft support for Xamarin](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin) will end on May 1, 2024 for all Xamarin SDKs including Xamarin.Forms. In preparation for this, all issues and PRs in this repository are being closed.

.NET MAUI is the replacement for Xamarin.Forms, and it's documentation can be found [here](https://learn.microsoft.com/dotnet/maui/?view=net-maui-8.0).
