### ISSUE TITLE
Connection Troubleshooting for a Xamarin.iOS Build Host doc is missing important troubleshooting step

### ISSUE THREAD

**Issue by vchelaru** [MicrosoftDocs/xamarin-docs#3413]
### Doc issue description

I had a lot of difficulty deploying an iOS application to an iPhone (actual hardware, not simulator) which is connected to my Mac, but through Visual Studio 2022 on Windows. Note that this may not be specific to the Windows version of Visual Studio, as I also had similar problems deploying from Visual Studio Mac 2019.

I worked through the steps here, but none of the steps helped me deploy:

https://docs.microsoft.com/en-us/xamarin/ios/get-started/installation/windows/connecting-to-mac/troubleshooting

The following error was listed in Visual Studio upon deployment:

```
Error error MT1006: Could not install the application '/Users/victor/Library/Caches/Xamarin/mtbs/builds/DeployTest2.iOS/xxxxx/bin/iPhone/Debug/DeployTest2.iOS.app' on the device 'VicsIphone': AMDeviceSecureInstallApplicationBundle returned: 0xe800801c. 0
```

Through searching, I stumbled across this post: 
https://developer.apple.com/forums/thread/131088

The solution suggested there is to make a new XCode application and deploy that. Doing this will result in XCode obtaining the necessary certificates.

I tried this, and after doing so I was able to deploy from Visual Studio no problem!

I feel like this should be a troubleshooting step listed here, as I burned a full day and as a Xamarin developer I always turn to Microsoft documentation first before I look at Apple or Android docs.

**Comment by davidbritch** [comment]
[Microsoft support for Xamarin](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin) will end on May 1, 2024 for all Xamarin SDKs including Xamarin.Forms. In preparation for this, all issues and PRs in this repository are being closed.

.NET MAUI is the replacement for Xamarin.Forms, and it's documentation can be found [here](https://learn.microsoft.com/dotnet/maui/?view=net-maui-8.0).
