### ISSUE TITLE
Event to receive changes on continuous basis ?

### ISSUE THREAD

**Issue by nssidhu** [MicrosoftDocs/xamarin-docs#3414]
Do you have example on how to receive new location updates if the location is changing ?
i.e. user is driving and his location would be continuously changing and i need to get any changes where distance has changed beyond say 10 meters.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f0acf3fa-b705-f0cc-b676-eeca60176dfa
* Version Independent ID: 1788a5d5-a3cb-15c8-927c-b6a24810245a
* Content: [Xamarin.Essentials: Geolocation - Xamarin](https://docs.microsoft.com/en-us/xamarin/essentials/geolocation?tabs=android)
* Content Source: [docs/essentials/geolocation.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/essentials/geolocation.md)
* Product: **xamarin**
* Technology: **xamarin-essentials**
* GitHub Login: @jamesmontemagno
* Microsoft Alias: **jamont**

**Comment by jamesmontemagno** [comment]
There is not tracking updates currently, but is already a feature request at https://github.com/xamarin/essentials
