### ISSUE TITLE
Why provide samples that don't compile

### ISSUE THREAD

**Issue by sqlguy6212** [MicrosoftDocs/xamarin-docs#3415]
So the OpenAppPackageFileAsync example I copied.  It does not compile so as way too many times in the last few weeks a Microsoft page has incorrect information or information for a previous version of a product.  (So many links in VS 2022 go to documentation for VS 2019 and the information on the page is for Win 10 while I use Win 11 and the dialogues are completely different so they are basically useless.

 

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 91d50947-38a1-44b7-2684-63b17d5bac66
* Version Independent ID: b449b3f5-7a68-fdea-041b-71cc39a46a48
* Content: [Xamarin.Essentials: File System Helpers - Xamarin](https://docs.microsoft.com/en-us/xamarin/essentials/file-system-helpers?tabs=android)
* Content Source: [docs/essentials/file-system-helpers.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/essentials/file-system-helpers.md)
* Product: **xamarin**
* Technology: **xamarin-essentials**
* GitHub Login: @jamesmontemagno
* Microsoft Alias: **jamont**

**Comment by jamesmontemagno** [comment]
Thanks for the feedback. I have adjusted the section to specify that you must actually add a file to the specific assets location on each platform.

It will now read:

If you would like to open a file that has been bundled into the application package, you can use teh `OpenAppPackageFileAsync` method to read the contents. In the example below a file named `mybundledfile.txt` has been added to each platform. See the platform implementation specifics section for details.

```csharp
 var fileName = "mybundledfile.txt";
 using (var stream = await FileSystem.OpenAppPackageFileAsync(fileName))
 {
    using (var reader = new StreamReader(stream))
    {
        var fileContents = await reader.ReadToEndAsync();
    }
 }
```
