### ISSUE TITLE
return base.OpenUrl(app, url, options) throws Foundation.You_Should_Not_Call_base_In_This_Method

### ISSUE THREAD

**Issue by somoreingold** [MicrosoftDocs/xamarin-docs#3418]
This line should be removed:
`return base.OpenUrl(app, url, options);`
Otherwise it throws an "Exception of type 'Foundation.You_Should_Not_Call_base_In_This_Method'."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1231a1e1-3734-9021-2cc7-eaf99478afca
* Version Independent ID: 01e5fdbe-0b15-4dbe-f8a0-ed40f8593302
* Content: [Xamarin.Essentials: Web Authenticator - Xamarin](https://docs.microsoft.com/en-us/xamarin/essentials/web-authenticator?tabs=ios)
* Content Source: [docs/essentials/web-authenticator.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/essentials/web-authenticator.md)
* Product: **xamarin**
* Technology: **xamarin-essentials**
* GitHub Login: @Redth
* Microsoft Alias: **jodick**

**Comment by davidbritch** [comment]
[Microsoft support for Xamarin](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin) will end on May 1, 2024 for all Xamarin SDKs including Xamarin.Forms. In preparation for this, all issues and PRs in this repository are being closed.

.NET MAUI is the replacement for Xamarin.Forms, and it's documentation can be found [here](https://learn.microsoft.com/dotnet/maui/?view=net-maui-8.0).
