### ISSUE TITLE
Samples do not work

### ISSUE THREAD

**Issue by sqlguy6212** [MicrosoftDocs/xamarin-docs#3419]
Is there anyone at Microsoft that knows what the term QUALITY means.  I simply copy the code from this page and of course it does not work.

Windows 11/Visual Studio 2022 both products have more holes than swiss cheese.

Lloyd Sheen
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 639e2203-e49e-5673-e2d5-bd2257411656
* Version Independent ID: 43735d55-f808-13bf-7e3b-8e7afbaa4616
* Content: [Xamarin.Forms Button - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/button#using-bitmaps-with-buttons)
* Content Source: [docs/xamarin-forms/user-interface/button.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/button.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
[Microsoft support for Xamarin](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin) will end on May 1, 2024 for all Xamarin SDKs including Xamarin.Forms. In preparation for this, all issues and PRs in this repository are being closed.

.NET MAUI is the replacement for Xamarin.Forms, and it's documentation can be found [here](https://learn.microsoft.com/dotnet/maui/?view=net-maui-8.0).
