### ISSUE TITLE
document update related android

### ISSUE THREAD

**Issue by tenhilltree** [MicrosoftDocs/xamarin-docs#3420]
[Enter feedback here]
According to [https://developer.android.com/reference/android/speech/tts/TextToSpeech.Engine]

Apps targeting Android 11 that use text-to-speech should declare [INTENT_ACTION_TTS_SERVICE](https://developer.android.com/reference/android/speech/tts/TextToSpeech.Engine#INTENT_ACTION_TTS_SERVICE) in the queries elements of their manifest:

```
 <queries>
   ...
  <intent>
      <action android:name="android.intent.action.TTS_SERVICE" />
  </intent>
 </queries>
```

With out this, 'Failed to initialize Text to Speech engine' exception is thrown.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c941b98c-cfe4-a6c9-2117-f5f0d2f5a7f8
* Version Independent ID: 7fe2d995-09dd-2dce-2dbf-7f49e6d7c3f1
* Content: [Xamarin.Essentials: Text-to-Speech - Xamarin](https://docs.microsoft.com/en-us/xamarin/essentials/text-to-speech?context=xamarin/xamarin-forms#feedback)
* Content Source: [docs/essentials/text-to-speech.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/essentials/text-to-speech.md)
* Product: **xamarin**
* Technology: **xamarin-essentials**
* GitHub Login: @jamesmontemagno
* Microsoft Alias: **jamont**

**Comment by jamesmontemagno** [comment]
Thanks! will get this fixed up
