### ISSUE TITLE
Icorrect text

### ISSUE THREAD

**Issue by ederbond** [MicrosoftDocs/xamarin-docs#3421]
[Enter feedback here]

Where the docs says:

> will have its GroupName property set to `fruits`

it should actually says:

> will have its GroupName property set to `colors`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a688fe91-33ad-efea-aa29-d56b3c11b42a
* Version Independent ID: c0e81ed5-0eb5-a8cc-9eb6-7baf7e464878
* Content: [Xamarin.Forms RadioButton - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/radiobutton)
* Content Source: [docs/xamarin-forms/user-interface/radiobutton.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/radiobutton.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
[Microsoft support for Xamarin](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin) will end on May 1, 2024 for all Xamarin SDKs including Xamarin.Forms. In preparation for this, all issues and PRs in this repository are being closed.

.NET MAUI is the replacement for Xamarin.Forms, and it's documentation can be found [here](https://learn.microsoft.com/dotnet/maui/?view=net-maui-8.0).
