### ISSUE TITLE
No overload for method Deserialize takes two arguments

### ISSUE THREAD

**Issue by BretMishler** [MicrosoftDocs/xamarin-docs#3423]
Under the **Retrieve data** section, the following line will not compile:

`Items = JsonSerializer.Deserialize<List<TodoItem>>(content, serializerOptions);`

No overload for method Deserialize takes two arguments

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 155a1af2-3ce7-058b-d243-b4d7a9cd6e22
* Version Independent ID: 47f0df9e-ab6a-a38b-5916-991b5110ebf1
* Content: [Consume a RESTful web service - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/data-cloud/web-services/rest)
* Content Source: [docs/xamarin-forms/data-cloud/web-services/rest.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/data-cloud/web-services/rest.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by grimreaper38uk** [comment]
I don't understand this either - it's obviously not going to work - not without a JSON Reader anyway.

The easiest method is to use the example from NewtonSoft;
`Items = JsonConvert.DeserializeObject<List<TodoItem>>(content);`

**Comment by davidbritch** [comment]
[Microsoft support for Xamarin](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin) will end on May 1, 2024 for all Xamarin SDKs including Xamarin.Forms. In preparation for this, all issues and PRs in this repository are being closed.

.NET MAUI is the replacement for Xamarin.Forms, and it's documentation can be found [here](https://learn.microsoft.com/dotnet/maui/?view=net-maui-8.0).
