### ISSUE TITLE
Code sample for iOS Notification manager (platform-specific) is missing a ctor with a call to Initialize()

### ISSUE THREAD

**Issue by derekvantonder** [MicrosoftDocs/xamarin-docs#3426]
[Enter feedback here]

See my attached image for how I fixed this, it meant that the Android example worked but the iOS one did not. Here is the screenshot: https://1drv.ms/u/s!AmliWtq2L6B8ifQi9cQPsMyJPMeyNg?e=mVWoTI

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e1d97b06-848b-73b1-0330-f57662b5c09a
* Version Independent ID: 9bb5fb04-4426-6b7a-4332-3ce86ff21b76
* Content: [Xamarin.Forms local notifications - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/local-notifications)
* Content Source: [docs/xamarin-forms/app-fundamentals/local-notifications.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/app-fundamentals/local-notifications.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @profexorgeek
* Microsoft Alias: **jusjohns**

**Comment by davidbritch** [comment]
[Microsoft support for Xamarin](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin) will end on May 1, 2024 for all Xamarin SDKs including Xamarin.Forms. In preparation for this, all issues and PRs in this repository are being closed.

.NET MAUI is the replacement for Xamarin.Forms, and it's documentation can be found [here](https://learn.microsoft.com/dotnet/maui/?view=net-maui-8.0).
