### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by lobothegod** [MicrosoftDocs/xamarin-docs#3428]
[at the section "In this example, each RadioButton in the StackLayout will have its GroupName property set to fruits, and will be mutually exclusive.", property should be "colors" like the example in xaml]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a688fe91-33ad-efea-aa29-d56b3c11b42a
* Version Independent ID: c0e81ed5-0eb5-a8cc-9eb6-7baf7e464878
* Content: [Xamarin.Forms RadioButton - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/radiobutton#feedback)
* Content Source: [docs/xamarin-forms/user-interface/radiobutton.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/radiobutton.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by ehsansajjad465** [comment]
@lobothegod  this is fixed currently when I checked, this Issue can be closed.
