### ISSUE TITLE
How to draw second circle on map!

### ISSUE THREAD

**Issue by nguyenthanhliemfc** [MicrosoftDocs/xamarin-docs#343]
I have use this sample but it's only draw circle one time when map is renderer.
I need tap on a location on map and draw another circle. I need draw more than one circle in run time
Please suggest me how to do that!
Thank yoU!

---
#### Chi tiết tài liệu

⚠ *Không chỉnh sửa phần này. Điều này là bắt buộc cho docs.microsoft.com ➟ Vấn đề khi liên kết GitHub.*

* ID: 30b9d29c-0918-ca5a-f97f-aef59f679c87
* Version Independent ID: d781998d-549a-3ab6-7dc6-5bcf3f05a128
* Content: [Highlighting a Circular Area on a Map - Xamarin](https://docs.microsoft.com/vi-vn/xamarin/xamarin-forms/app-fundamentals/custom-renderer/map/circle-map-overlay)
* Content Source: [docs/xamarin-forms/app-fundamentals/custom-renderer/map/circle-map-overlay.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/app-fundamentals/custom-renderer/map/circle-map-overlay.md)
* Service: **unspecified**
* Product: **xamarin**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @nguyenthanhliemfc - this repository is only for issues specifically related to the documentation. For support or to report bugs, please take a look at [Developer Community](https://developercommunity.visualstudio.com/spaces/8/index.html). Thank you!

**Comment by nguyenthanhliemfc** [comment]
@davidbritch Thank!
