### ISSUE TITLE
Control Platform View Cheat Sheet

### ISSUE THREAD

**Issue by twofingerrightclick** [MicrosoftDocs/xamarin-docs#3432]
I think it would be helpful to mention the underlying views that get drawn by `ViewRenderer` for each of the platforms for all default Xamarin.Forms controls. I often get stuck with the default styling of the control not being UX friendly or the view being invisible do to the default color styles.
For the Xamarin.Forms Picker for example I had to look into the source to see that for Android it is an `EditText` and so I needed to style the EditText background to improve the UX, as it was being styled with no indication that it was a picker, (just looked like text).
I don't have much experience with any of the platforms themselves, but a table like this would be helpful as a cheat sheet:

| Platform | Underlying View|
| ----------- | ----------- |
| Android | EditText|
| iOS| UITextField|

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0c3eb3c8-5769-0b04-2b54-c52b1b98b4be
* Version Independent ID: c150f5fe-a0d8-b6ba-8234-ea219ba9f653
* Content: [Xamarin.Forms Picker - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/picker/)
* Content Source: [docs/xamarin-forms/user-interface/picker/index.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/picker/index.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @twofingerrightclick 

Something like https://docs.microsoft.com/xamarin/xamarin-forms/app-fundamentals/custom-renderer/renderers?

**Comment by twofingerrightclick** [comment]
That would be exactly it! Thank you for the link.
