### ISSUE TITLE
Missing information for Android 11 devices

### ISSUE THREAD

**Issue by WilkoSki** [MicrosoftDocs/xamarin-docs#3436]
The Xamarin Essentials Media Picker doesn't include any relevant information for use with Android 11 devices.

For example calling CapturePhotoAsync will generate the following exception on Android 11:

Xamarin.Essentials.FeatureNotSupportedException: 'Either there was no camera on the device or 'android.media.action.IMAGE_CAPTURE' was not added to the element in the app's manifest file. See more: https://developer.android.com/about/versions/11/privacy/package-visibility'

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e4b43ab7-fd40-ba56-c9ab-5de2eb1aad7f
* Version Independent ID: 6c9c7c48-4401-cb25-5cda-637718a22961
* Content: [Xamarin.Essentials: Media Picker - Xamarin](https://docs.microsoft.com/en-us/xamarin/essentials/media-picker?context=xamarin%2Fandroid&tabs=android)
* Content Source: [docs/essentials/media-picker.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/essentials/media-picker.md)
* Product: **xamarin**
* Technology: **xamarin-essentials**
* GitHub Login: @jamesmontemagno
* Microsoft Alias: **jamont**

**Comment by jamesmontemagno** [comment]
Adding to docs:

Open the **AndroidManifest.xml** file under the **Properties** folder and add the following inside of the **manifest** node:

```xml
<queries>
  <intent>
    <action android:name="android.media.action.IMAGE_CAPTURE" />
  </intent>
</queries>
```
