### ISSUE TITLE
Allow the application to open Google Maps in Android 11

### ISSUE THREAD

**Issue by cbs-cbt** [MicrosoftDocs/xamarin-docs#3438]
Hello,
Since Android 11, when the user clicks on the "Google Maps" button that appears at the bottom of the map when selecting a Pin, the following toast is displayed: "Google maps is not installed or is disabled"
In order to allow the application to open Google Maps, the following code must be added to `AndroidManifest.xml`:
```
<manifest package="com.your.package">
  <queries>
    <package android:name="com.google.android.apps.maps" />
  </queries>
  ...
</manifest>
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2a251251-3037-b49f-de79-f820b469321d
* Version Independent ID: 4af74db2-b248-3a02-bf38-0b76ede42ef6
* Content: [Xamarin.Forms Map Initialization and Configuration - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/map/setup)
* Content Source: [docs/xamarin-forms/user-interface/map/setup.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/map/setup.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
[Microsoft support for Xamarin](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin) will end on May 1, 2024 for all Xamarin SDKs including Xamarin.Forms. In preparation for this, all issues and PRs in this repository are being closed.

.NET MAUI is the replacement for Xamarin.Forms, and it's documentation can be found [here](https://learn.microsoft.com/dotnet/maui/?view=net-maui-8.0).
