### ISSUE TITLE
How to interact between Custom Renderer  with PCL (NET Standard)?

### ISSUE THREAD

**Issue by nguyenthanhliemfc** [MicrosoftDocs/xamarin-docs#344]
Please tell me How to interact between Custom Renderer  with PCL (NET Standard)?
Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 391ad081-26f2-e228-1989-48d64529cc49
* Version Independent ID: ca4f1d4d-782f-6a39-8ed8-b31ea91ce008
* Content: [Custom Renderers - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/custom-renderer/)
* Content Source: [docs/xamarin-forms/app-fundamentals/custom-renderer/index.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/app-fundamentals/custom-renderer/index.md)
* Service: **unspecified**
* Product: **xamarin**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
The interaction between custom renderers is identical in PCL-based projects as it is in .NET Standard projects.

**Comment by nguyenthanhliemfc** [comment]
Thanks david!
