### ISSUE TITLE
GenericsDemo has 4 errors

### ISSUE THREAD

**Issue by Chris-DevTeam** [MicrosoftDocs/xamarin-docs#3440]
Severity	Code	Description	Project	File	Line	Suppression State
Error	XLS0414	The type 'scg:KeyValuePair(x' was not found. Verify that you are not missing an assembly reference and that all referenced assemblies have been built.	GenericsDemo	~\GenericsDemo\Views\ListOfKeyValuePairDemo.xaml	13	

Severity	Code	Description	Project	File	Line	Suppression State
Error	XLS0503	A value of type 'KeyValuePair`2' cannot be added to a collection or dictionary of type 'List`1'.	GenericsDemo	~\GenericsDemo\GenericsDemo\Views\ListOfKeyValuePairDemo.xaml	14	

Severity	Code	Description	Project	File	Line	Suppression State
Error	XLS0503	A value of type 'KeyValuePair`2' cannot be added to a collection or dictionary of type 'List`1'.	GenericsDemo	~\GenericsDemo\GenericsDemo\Views\ListOfKeyValuePairDemo.xaml	21	

Severity	Code	Description	Project	File	Line	Suppression State
Error	XLS0503	A value of type 'KeyValuePair`2' cannot be added to a collection or dictionary of type 'List`1'.	GenericsDemo	~\GenericsDemo\GenericsDemo\Views\ListOfKeyValuePairDemo.xaml	28	

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6794d7f5-1352-0119-54fe-a3b33f726377
* Version Independent ID: a224c593-faeb-d88c-0dc7-d58b895f38d2
* Content: [Generics in Xamarin.Forms XAML - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/xaml/generics)
* Content Source: [docs/xamarin-forms/xaml/generics.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/xaml/generics.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
[Microsoft support for Xamarin](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin) will end on May 1, 2024 for all Xamarin SDKs including Xamarin.Forms. In preparation for this, all issues and PRs in this repository are being closed.

.NET MAUI is the replacement for Xamarin.Forms, and it's documentation can be found [here](https://learn.microsoft.com/dotnet/maui/?view=net-maui-8.0).
