### ISSUE TITLE
Issue with '..android/deploy-test/release-prep/index.md' stating ProGuard as an obfuscation tool

### ISSUE THREAD

**Issue by ciarancolgan** [MicrosoftDocs/xamarin-docs#3443]
Can't submit as PR as this line needs re-written by someone who knows the ProGuard tool better than me. 

Page: https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/android/deploy-test/release-prep/index.md

Line with issue: `ProGuard is an Android SDK tool that links and obfuscates Java code.`

Issue: ProGuard does not obfuscate Java code. It says this later in the same document: `The Xamarin.Android ProGuard configuration does not obfuscate the APK, and it is not possible to enable obfuscation, even with custom configuration files`

Solution: Re-write first line to not mention obfuscation

**Comment by davidbritch** [comment]
[Microsoft support for Xamarin](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin) will end on May 1, 2024 for all Xamarin SDKs including Xamarin.Forms. In preparation for this, all issues and PRs in this repository are being closed.

.NET MAUI is the replacement for Xamarin.Forms, and it's documentation can be found [here](https://learn.microsoft.com/dotnet/maui/?view=net-maui-8.0).
