### ISSUE TITLE
This page is no longer accurate

### ISSUE THREAD

**Issue by norton287** [MicrosoftDocs/xamarin-docs#3444]
[Enter feedback here]

Since the launch of Android X, Google Play Store requires all new apps submitted to be set at SDK 30 or higher and can NO LONGER USE READ or WRITE EXTERNAL STORAGE.  They must use the Storage Access Framework now.  I have opened a Github issue regarding this but the lead developer has not responded to whether they are going to update the Picker to allow us to be able to submit our apps to the store.  Every day I am losing money because when Xamarin.Essentials Picker. was released it killed EVERY third-party picker in existence.  NOW THEY DON"T WANT TO UPDATE IT.  So you might as well take your piece of crap instructions down since it will no longer apply for submitting to the Android App Store for SDK 30+.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bde8b00e-bef2-d10c-268f-2e49e236a89f
* Version Independent ID: dad8b07c-2227-c7ed-6369-d10d9b132e99
* Content: [Xamarin.Essentials: File Picker - Xamarin](https://docs.microsoft.com/en-us/xamarin/essentials/file-picker?tabs=android)
* Content Source: [docs/essentials/file-picker.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/essentials/file-picker.md)
* Product: **xamarin**
* Technology: **xamarin-essentials**
* GitHub Login: @jamesmontemagno
* Microsoft Alias: **jamont**

**Comment by jamesmontemagno** [comment]
Linking to -> https://github.com/xamarin/Essentials/pull/1968 which will fix this up.
