### ISSUE TITLE
Spelling mistake

### ISSUE THREAD

**Issue by PhiDolla** [MicrosoftDocs/xamarin-docs#3446]
Hi :)
 
 I found a spelling mistake. First time doing a submission like this.

Can just Ctrl+F to find on page: "When the BinableLayout.ItemsSource property is set"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 59df8b1e-8b94-a79e-25eb-f47ddf38777a
* Version Independent ID: cd195715-e7e3-428f-1061-c550ff960dda
* Content: [Bindable Layouts in Xamarin.Forms - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/layouts/bindable-layouts)
* Content Source: [docs/xamarin-forms/user-interface/layouts/bindable-layouts.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/layouts/bindable-layouts.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by ehsansajjad465** [comment]
@ktn8  I created the PR for this fix: https://github.com/MicrosoftDocs/xamarin-docs/pull/3487/commits

**Comment by davidbritch** [comment]
[Microsoft support for Xamarin](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin) will end on May 1, 2024 for all Xamarin SDKs including Xamarin.Forms. In preparation for this, all issues and PRs in this repository are being closed.

.NET MAUI is the replacement for Xamarin.Forms, and it's documentation can be found [here](https://learn.microsoft.com/dotnet/maui/?view=net-maui-8.0).
