### ISSUE TITLE
Xamarin compenant browsing is better than this.

### ISSUE THREAD

**Issue by rtarta** [MicrosoftDocs/xamarin-docs#345]
we wish to see list of compenants and comments properly  as before..

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f5e0d3ab-3d52-7966-34ac-f04236fe9d20
* Version Independent ID: cc8fb372-39b4-7ec1-5911-1bfbed905daf
* Content: [Updating component references to NuGet - Xamarin](https://docs.microsoft.com/en-us/xamarin/cross-platform/troubleshooting/component-nuget?tabs=vswin)
* Content Source: [docs/cross-platform/troubleshooting/component-nuget.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/cross-platform/troubleshooting/component-nuget.md)
* Service: **unspecified**
* Product: **xamarin**
* GitHub Login: @asb3993
* Microsoft Alias: **amburns**

**Comment by conceptdev** [comment]
Hi @rtarta, as the note on this page says, the Comoponent Store has been closed, and can no longer be accessed from Visual Studio or the website. Please use NuGet (www.nuget.org) to add functionality to your apps.

Product feedback can be provided on the [Developer Community site](https://developercommunity.visualstudio.com/).
