### ISSUE TITLE
Camera and Audio are missing from Xamarin Essentials 

### ISSUE THREAD

**Issue by JakeCroz1** [MicrosoftDocs/xamarin-docs#3451]
I noticed that the camera and audio APIs are missing from the Xamarin Essentials. There are limited and outdated examples on using camera and audio APIs with Xamarin. It would be nice just to plug and play with these APIs. It would be nice be able to create a customized GUI for camera and audio APIs. In addition, it would be nice to customize the properties and functionality for the camera and audio APIs as well. Overall, the camera and audio APIs are essential given the high demand of their use such as Social Media. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c420b152-7303-918a-dbc8-8d1e539c64ec
* Version Independent ID: fe85e24f-c3fc-3763-b1db-6b360fb08067
* Content: [Xamarin.Essentials - Xamarin](https://docs.microsoft.com/en-us/xamarin/essentials/?context=xamarin/xamarin-forms)
* Content Source: [docs/essentials/index.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/essentials/index.md)
* Product: **xamarin**
* Technology: **xamarin-essentials**
* GitHub Login: @jamesmontemagno
* Microsoft Alias: **jamont**

**Comment by JakeCroz1** [comment]
Title updated

**Comment by davidbritch** [comment]
[Microsoft support for Xamarin](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin) will end on May 1, 2024 for all Xamarin SDKs including Xamarin.Forms. In preparation for this, all issues and PRs in this repository are being closed.

.NET MAUI is the replacement for Xamarin.Forms, and it's documentation can be found [here](https://learn.microsoft.com/dotnet/maui/?view=net-maui-8.0).
