### ISSUE TITLE
Broken links to Chapter 24th

### ISSUE THREAD

**Issue by mcmorry** [MicrosoftDocs/xamarin-docs#3453]
[Enter feedback here]
The links to Chapter 24th of the Xamarin book are broken.
I found a new link that seems the correct one here: 
https://xamarin.azureedge.net/developer/xamarin-forms-book/XamarinFormsBook-Ch24-Apr2016.pdf

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4dbd0d0d-484d-ea90-3a8c-e0780a058017
* Version Independent ID: cf200dae-4d45-cc32-e323-c317e969ac64
* Content: [Xamarin.Forms Modal Pages - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/navigation/modal)
* Content Source: [docs/xamarin-forms/app-fundamentals/navigation/modal.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/app-fundamentals/navigation/modal.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
[Microsoft support for Xamarin](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin) will end on May 1, 2024 for all Xamarin SDKs including Xamarin.Forms. In preparation for this, all issues and PRs in this repository are being closed.

.NET MAUI is the replacement for Xamarin.Forms, and it's documentation can be found [here](https://learn.microsoft.com/dotnet/maui/?view=net-maui-8.0).
