### ISSUE TITLE
It doesn't work 

### ISSUE THREAD

**Issue by stephenhauck** [MicrosoftDocs/xamarin-docs#3454]
No one is paying attention to the issues .. someone else is having issues on Android as well ...
I know that MAUI is important but so it production code for the rest of us 

https://github.com/xamarin/Essentials/issues/2006

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 44b2d5f7-bcc1-4561-247e-b3a314738311
* Version Independent ID: 779a0484-4dea-f385-3c5c-708cb8860848
* Content: [Xamarin.Essentials Launcher - Xamarin](https://docs.microsoft.com/en-us/xamarin/essentials/launcher?context=xamarin%2Fandroid&tabs=ios)
* Content Source: [docs/essentials/launcher.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/essentials/launcher.md)
* Product: **xamarin**
* Technology: **xamarin-essentials**
* GitHub Login: @jamesmontemagno
* Microsoft Alias: **jamont**

**Comment by jamesmontemagno** [comment]
I will follow up on the thread in launcher
