### ISSUE TITLE
No luck

### ISSUE THREAD

**Issue by christophedemey** [MicrosoftDocs/xamarin-docs#346]
Didnt work for me :(

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 500cca09-76fd-5df5-6bd9-90cc51fae84d
* Version Independent ID: 3a9bfdcc-ac3a-6cdf-ab20-9fc425c56b71
* Content: [How do I resolve a PathTooLongException error? - Xamarin](https://docs.microsoft.com/en-us/xamarin/android/troubleshooting/questions/path-too-long-exception)
* Content Source: [docs/android/troubleshooting/questions/path-too-long-exception.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/android/troubleshooting/questions/path-too-long-exception.md)
* Service: **unspecified**
* Product: **xamarin**
* GitHub Login: @mgmclemore
* Microsoft Alias: **mamcle**

**Comment by mgmclemore** [comment]
Hi @christophedemey, thanks for the feedback!  I'll add this tip to the topic for readers who are unable to get `UseShortFileNames` to sufficiently shorten the paths.

**Comment by mgmclemore** [comment]
Published.

**Comment by christophedemey** [comment]
Thanks for your effort, i am glad to see my feedback is being used!
