### ISSUE TITLE
Typo in code sample

### ISSUE THREAD

**Issue by jeffschwMSFT** [MicrosoftDocs/xamarin-docs#3460]
Typo in code sample:

```
    SKPaint paint = new SKPaint
    {
        Style = SKPaintStyle.Stroke,
        Color = Color.Red.ToSKColor(),
        StrokeWidth = 25
    };
```

Should be 'Color = Colors.Red.ToSKColor(),' (note the plural Colors)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 261342ea-fd87-d603-fa4e-fcf903e8798b
* Version Independent ID: 477efad7-92bc-5498-c82e-e3305cb33e66
* Content: [Drawing a Simple Circle in SkiaSharp - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/graphics/skiasharp/basics/circle)
* Content Source: [docs/xamarin-forms/user-interface/graphics/skiasharp/basics/circle.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/graphics/skiasharp/basics/circle.md)
* Product: **xamarin**
* Technology: **xamarin-skiasharp**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by ehsansajjad465** [comment]
@jeffschwMSFT I have created PR for this : https://github.com/MicrosoftDocs/xamarin-docs/pull/3486/files

**Comment by davidbritch** [comment]
[Microsoft support for Xamarin](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin) will end on May 1, 2024 for all Xamarin SDKs including Xamarin.Forms. In preparation for this, all issues and PRs in this repository are being closed.

.NET MAUI is the replacement for Xamarin.Forms, and it's documentation can be found [here](https://learn.microsoft.com/dotnet/maui/?view=net-maui-8.0).
