### ISSUE TITLE
Use SKPaint with FilterQuality in canvas.DrawBitmap sample

### ISSUE THREAD

**Issue by rogihee** [MicrosoftDocs/xamarin-docs#3462]
When trying to display a bitmap, I achieved considerably better display quality by using the `canvas.DrawBitmap(webBitmap, x, y, paint);` override with passing a SKPaint object in and setting a FilterQuality option.

Perhaps nice to extend the sample with this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8d5c7b42-6046-1caa-6258-b57f0325bb24
* Version Independent ID: 1c475a56-1410-29e2-52b6-675ca9ef90f3
* Content: [Bitmap Basics in SkiaSharp - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/graphics/skiasharp/basics/bitmaps)
* Content Source: [docs/xamarin-forms/user-interface/graphics/skiasharp/basics/bitmaps.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/graphics/skiasharp/basics/bitmaps.md)
* Product: **xamarin**
* Technology: **xamarin-skiasharp**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
[Microsoft support for Xamarin](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin) will end on May 1, 2024 for all Xamarin SDKs including Xamarin.Forms. In preparation for this, all issues and PRs in this repository are being closed.

.NET MAUI is the replacement for Xamarin.Forms, and it's documentation can be found [here](https://learn.microsoft.com/dotnet/maui/?view=net-maui-8.0).
