### ISSUE TITLE
Docs for obtaining Google Maps API Key should include instructions Play App Signing

### ISSUE THREAD

**Issue by UriHendler** [MicrosoftDocs/xamarin-docs#3464]
The docs ([docs/android/platform/maps-and-location/maps/obtaining-a-google-maps-api-key.md](docs/android/platform/maps-and-location/maps/obtaining-a-google-maps-api-key.md)) for obtaining a Google Maps API Key for Android apps should include a section on what to do when using Google Play Signing.

Under the **Obtaining the API Key** section, instructions are given for adding the SHA-1 certificate fingerprint for the debug keystore and the release keystore.

This won't work if you are using Play App Signing to sign your app. In this case, you need to add the certificate fingerprint from the Play signing certificate.

The Google Maps API docs (https://developers.google.com/maps/documentation/android-sdk/get-api-key) include this detail:

> For information about getting your certificate fingerprint, see [Authenticating Your Client](https://developers.google.com/android/guides/client-auth#using_keytool). If you're using [Play App Signing](https://play.google.com/console/about/keymanagement/) instead, you must go to the app signing page on the Play Console to get your certificate fingerprint.

Here's a blog post which describes the issue in detail: https://blog.johndotnet.nl/why-doesnt-googlemaps-work-after-releasing-it-to-the-google-play-store/

Please update the Xamarin docs 😄

**Comment by davidbritch** [comment]
[Microsoft support for Xamarin](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin) will end on May 1, 2024 for all Xamarin SDKs including Xamarin.Forms. In preparation for this, all issues and PRs in this repository are being closed.

.NET MAUI is the replacement for Xamarin.Forms, and it's documentation can be found [here](https://learn.microsoft.com/dotnet/maui/?view=net-maui-8.0).
