### ISSUE TITLE
Do the SelectionChangedCommand and SelectionChangedCommandParameter work? Are there any examples?

### ISSUE THREAD

**Issue by gfmoore** [MicrosoftDocs/xamarin-docs#3466]
[SelectionChangedCommand](https://docs.microsoft.com/en-us/dotnet/api/xamarin.forms.selectableitemsview.selectionchangedcommand#xamarin-forms-selectableitemsview-selectionchangedcommand), of type ICommand, which is executed when the selected item changes.
[SelectionChangedCommandParameter](https://docs.microsoft.com/en-us/dotnet/api/xamarin.forms.selectableitemsview.selectionchangedcommandparameter#xamarin-forms-selectableitemsview-selectionchangedcommandparameter), of type object, which is the parameter

I note that the links are just stumps. Is there any example of how to use these? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0047e825-1aa1-3383-ce3c-dc3525d38173
* Version Independent ID: 42f1c7a0-6a5a-7f99-3818-3549707bfada
* Content: [Xamarin.Forms CollectionView Selection - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/collectionview/selection)
* Content Source: [docs/xamarin-forms/user-interface/collectionview/selection.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/collectionview/selection.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
[Microsoft support for Xamarin](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin) will end on May 1, 2024 for all Xamarin SDKs including Xamarin.Forms. In preparation for this, all issues and PRs in this repository are being closed.

.NET MAUI is the replacement for Xamarin.Forms, and it's documentation can be found [here](https://learn.microsoft.com/dotnet/maui/?view=net-maui-8.0).
