### ISSUE TITLE
Camera Page screen title

### ISSUE THREAD

**Issue by pdschuller** [MicrosoftDocs/xamarin-docs#3470]
The words "Camera Page" appear in both screen shots of the devices.  It seems that the code examples are leaving out where that string comes from.   ... Maybe I'm just being dense.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c36e7942-65b6-9877-aafd-5f1b1291d37d
* Version Independent ID: 77a599a6-43f2-068f-95ad-0a92ca2b4bca
* Content: [Customizing a ContentPage - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/custom-renderer/contentpage)
* Content Source: [docs/xamarin-forms/app-fundamentals/custom-renderer/contentpage.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/app-fundamentals/custom-renderer/contentpage.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
[Microsoft support for Xamarin](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin) will end on May 1, 2024 for all Xamarin SDKs including Xamarin.Forms. In preparation for this, all issues and PRs in this repository are being closed.

.NET MAUI is the replacement for Xamarin.Forms, and it's documentation can be found [here](https://learn.microsoft.com/dotnet/maui/?view=net-maui-8.0).
