### ISSUE TITLE
How capture the event for the ... (hamburger?) at right side of menu bar

### ISSUE THREAD

**Issue by gfmoore** [MicrosoftDocs/xamarin-docs#3473]
Hi guys, me again ;)

I'm implementing a title bar for a windows app.
In AppShell.xaml
```
   <Shell.TitleView>  
      <Grid ColumnDefinitions="50, 200"
            ColumnSpacing="15">
        <Image Grid.Column="0"
               Source="logo.png"
               HorizontalOptions="Start"
               VerticalOptions="Center" 
               HeightRequest="40"
               WidthRequest="40"
               Margin="10,0,0,0"/>
        
        <Label Grid.Column="1"
               Text="RouteIt"
               TextColor="LightGreen"
               FontSize="30" 
               Margin="0,10,0,0"/>
      </Grid>
    </Shell.TitleView>
```
I notice that there are three dots at right hand side (what I used to know as a hamburger though that was three lines). How do I capture the event for that so that I can use it to display things and options. I didn't spot it in the docs, but might have missed it?

Thanks
G
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b3d1ffa8-e281-11c3-0784-564329adc7fc
* Version Independent ID: 0c6914fa-e2cb-a2b1-1f7c-e65eddcb9c8d
* Content: [Xamarin.Forms Shell pages - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/shell/pages#display-views-in-the-navigation-bar)
* Content Source: [docs/xamarin-forms/app-fundamentals/shell/pages.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/app-fundamentals/shell/pages.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by gfmoore** [comment]
Clicking it does seem to change the height of the very top row of the windows app slightly?

**Comment by gfmoore** [comment]
Ooops, seem to be in a Xamarin forms docs, I thought I was in Maui. Oh well.

**Comment by gfmoore** [comment]
Sorry, I'll go to the Maui docs

**Comment by davidbritch** [comment]
[Microsoft support for Xamarin](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin) will end on May 1, 2024 for all Xamarin SDKs including Xamarin.Forms. In preparation for this, all issues and PRs in this repository are being closed.

.NET MAUI is the replacement for Xamarin.Forms, and it's documentation can be found [here](https://learn.microsoft.com/dotnet/maui/?view=net-maui-8.0).
