### ISSUE TITLE
Learning 

### ISSUE THREAD

**Issue by mrsdykes11** [MicrosoftDocs/xamarin-docs#3475]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5fc5d4b4-e0c4-7399-8e32-2c2fe935cbbe
* Version Independent ID: 89992fd0-d78a-fc6f-16f9-1ee91cf18485
* Content: [Installing Xamarin - Xamarin](https://docs.microsoft.com/en-us/xamarin/get-started/installation/)
* Content Source: [docs/get-started/installation/index.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/get-started/installation/index.md)
* Product: **xamarin**
* Technology: **xamarin-crossplatform**
* GitHub Login: @conceptdev
* Microsoft Alias: **crdun**

**Comment by davidbritch** [comment]
[Microsoft support for Xamarin](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin) will end on May 1, 2024 for all Xamarin SDKs including Xamarin.Forms. In preparation for this, all issues and PRs in this repository are being closed.

.NET MAUI is the replacement for Xamarin.Forms, and it's documentation can be found [here](https://learn.microsoft.com/dotnet/maui/?view=net-maui-8.0).
