### ISSUE TITLE
Great content!

### ISSUE THREAD

**Issue by Witness327** [MicrosoftDocs/xamarin-docs#3478]
[ I like what is being done and looking for the MAUI solution for this as well.

Any help is greatly appreciated. ]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9f4d0869-b5c2-c17b-63d4-f325856d1a79
* Version Independent ID: a5f487c3-4e56-838f-89a9-b8fa0dc13261
* Content: [Xamarin.Essentials: Phone Dialer - Xamarin](https://docs.microsoft.com/en-us/xamarin/essentials/phone-dialer?tabs=android)
* Content Source: [docs/essentials/phone-dialer.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/essentials/phone-dialer.md)
* Product: **xamarin**
* Technology: **xamarin-essentials**
* GitHub Login: @jamesmontemagno
* Microsoft Alias: **jamont**

**Comment by jamesmontemagno** [comment]
You are able to find the .NET MAUI integration here: https://docs.microsoft.com/en-us/dotnet/maui/platform-integration/
