### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by KyleKofoed** [MicrosoftDocs/xamarin-docs#348]
UITapGesturesRecognizer should be UITapGestureRecognizer, right?
Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9a469922-f970-8e48-c4bc-9f2005a1c18b
* Version Independent ID: 4d0f04cd-7558-1bc4-77ee-97a522667136
* Content: [Touch in iOS - Xamarin](https://docs.microsoft.com/en-us/xamarin/ios/app-fundamentals/touch/touch-in-ios)
* Content Source: [docs/ios/app-fundamentals/touch/touch-in-ios.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/ios/app-fundamentals/touch/touch-in-ios.md)
* Service: **unspecified**
* Product: **xamarin**
* GitHub Login: @bradumbaugh
* Microsoft Alias: **brumbaug**

**Comment by Mondonno** [comment]
Good Job, Thanks!!!
