### ISSUE TITLE
Picker documentation obsolete - does not support direct content? ...

### ISSUE THREAD

**Issue by bdcoder2** [MicrosoftDocs/xamarin-docs#3480]
Trying to learn Xamarin Forms and how to use a "Picker".  When copying the code shown in the documentation, i.e.:

      <Picker Title="Select a monkey"
              TitleColor="Red">
        <Picker.Items>
          <x:String>Baboon</x:String>
          <x:String>Capuchin Monkey</x:String>
          <x:String>Blue Monkey</x:String>
          <x:String>Squirrel Monkey</x:String>
          <x:String>Golden Lion Tamarin</x:String>
          <x:String>Howler Monkey</x:String>
          <x:String>Japanese Macaque</x:String>
        </Picker.Items>
      </Picker>

Visual Studio reports the following error message:

      The type 'Picker' does not support direct content.

Please update this page to show how to properly initialize a Picker defined in XAML from code.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b47354c0-5630-f56c-4632-d69bbe124b59
* Version Independent ID: 4dda513e-0364-d692-46fb-372e741526fd
* Content: [Adding Data to a Picker's Items Collection - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/picker/populating-items)
* Content Source: [docs/xamarin-forms/user-interface/picker/populating-items.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/picker/populating-items.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
[Microsoft support for Xamarin](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin) will end on May 1, 2024 for all Xamarin SDKs including Xamarin.Forms. In preparation for this, all issues and PRs in this repository are being closed.

.NET MAUI is the replacement for Xamarin.Forms, and it's documentation can be found [here](https://learn.microsoft.com/dotnet/maui/?view=net-maui-8.0).
