### ISSUE TITLE
AD B2C and WebAuthenticator

### ISSUE THREAD

**Issue by Escoto** [MicrosoftDocs/xamarin-docs#3481]
I need some guidance and could be helpful for others...

This is for a MAUI Hybrid App (needles to say, using Blazor).

I managed to get `id_token` and `code` (my understanding is `code` = `access token`).

Once I have these two guys, how do I query my user's data from Azure B2C? is this even possible?

I did this exercise in AWS Cognito, that was really simple, there is an endpoint and I just send my userid + access token, and that's it. 

Trying to replicate this in Azure B2C has proven to be quite challenging. Now I am wondering if it is actually possible to get data for my logged-in user (specific to this one user, using the `id_token`/`access_token` I get after authentication).

Thanks for any guidance you can send my way!!

Best,
E.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1231a1e1-3734-9021-2cc7-eaf99478afca
* Version Independent ID: 01e5fdbe-0b15-4dbe-f8a0-ed40f8593302
* Content: [Xamarin.Essentials: Web Authenticator - Xamarin](https://docs.microsoft.com/en-us/xamarin/essentials/web-authenticator?tabs=android)
* Content Source: [docs/essentials/web-authenticator.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/essentials/web-authenticator.md)
* Product: **xamarin**
* Technology: **xamarin-essentials**
* GitHub Login: @Redth
* Microsoft Alias: **jodick**

**Comment by davidbritch** [comment]
[Microsoft support for Xamarin](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin) will end on May 1, 2024 for all Xamarin SDKs including Xamarin.Forms. In preparation for this, all issues and PRs in this repository are being closed.

.NET MAUI is the replacement for Xamarin.Forms, and it's documentation can be found [here](https://learn.microsoft.com/dotnet/maui/?view=net-maui-8.0).
