### ISSUE TITLE
Not able to run in iOS 16

### ISSUE THREAD

**Issue by swetaVanjara** [MicrosoftDocs/xamarin-docs#3490]
I have upgraded my visual studio version and trying to run with iOS 16 simulator. Not able to run.

 Error MT4109: Failed to compile the generated registrar code. Please file a bug report at https://github.com/xamarin/xamarin-macios/issues/new

**Comment by davidbritch** [comment]
[Microsoft support for Xamarin](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin) will end on May 1, 2024 for all Xamarin SDKs including Xamarin.Forms. In preparation for this, all issues and PRs in this repository are being closed.

.NET MAUI is the replacement for Xamarin.Forms, and it's documentation can be found [here](https://learn.microsoft.com/dotnet/maui/?view=net-maui-8.0).
