### ISSUE TITLE
zipalign command not working

### ISSUE THREAD

**Issue by 0nly1ken0bi** [MicrosoftDocs/xamarin-docs#3494]
The following command for zipalgin doesn't seem to be working as described in the [documentation](https://learn.microsoft.com/en-us/xamarin/android/deploy-test/signing/manually-signing-the-apk#zipalign-the-apk):

`$ zipalign -f -v 4 mono.samples.helloworld-unsigned.apk helloworld.apk`

Upon running the zipalign command in Microsoft Visual Studio Community 2022 (64-bit) - Current
Version 17.3.5 in the Developer PowerShell Terminal Window I get the following errors:

![ZipAlign Error](https://user-images.githubusercontent.com/54916539/193063181-2e5be978-b1d3-4da6-925e-8cbe653afb9c.PNG)

I've also tried searching the net, but most of the topics are like [this](https://www.telerik.com/blogs/publishing-dotnet-maui-app-android) and [this](https://stackoverflow.com/questions/31048208/zipalign-command-not-found) which is somewhat old.

If there are any other steps that are required please update the documentation accordingly.

I'm unable to get pass this point.

**Comment by davidbritch** [comment]
[Microsoft support for Xamarin](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin) will end on May 1, 2024 for all Xamarin SDKs including Xamarin.Forms. In preparation for this, all issues and PRs in this repository are being closed.

.NET MAUI is the replacement for Xamarin.Forms, and it's documentation can be found [here](https://learn.microsoft.com/dotnet/maui/?view=net-maui-8.0).
