### ISSUE TITLE
CSS

### ISSUE THREAD

**Issue by John-Blair** [MicrosoftDocs/xamarin-docs#3495]
[Enter feedback here]
What about switching CSS themes? How do you switch between 2 style sheets?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3f353ff4-2d18-218c-f0d5-b3110e476c4d
* Version Independent ID: a1cec8f2-969c-23c5-a252-b417afcacff6
* Content: [Theme a Xamarin.Forms Application - Xamarin](https://learn.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/theming/theming)
* Content Source: [docs/xamarin-forms/user-interface/theming/theming.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/theming/theming.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
[Microsoft support for Xamarin](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin) will end on May 1, 2024 for all Xamarin SDKs including Xamarin.Forms. In preparation for this, all issues and PRs in this repository are being closed.

.NET MAUI is the replacement for Xamarin.Forms, and it's documentation can be found [here](https://learn.microsoft.com/dotnet/maui/?view=net-maui-8.0).
