### ISSUE TITLE
.Net Maui Collection view height issue in iOS device 

### ISSUE THREAD

**Issue by Kaushik2107** [MicrosoftDocs/xamarin-docs#3497]
When i run .net Maui project in Android it's showing perfect output, but when i check iOS device it's taking too much height & scroll.

How to solve this for iOS device?

Collection View sample code

<CollectionView
                ItemsSource="{Binding SummaryButton}"
                SelectionMode="Single"
                >
                <CollectionView.ItemsLayout>
                    <GridItemsLayout Orientation="Vertical" Span="2" HorizontalItemSpacing="5" />
                </CollectionView.ItemsLayout>
                <CollectionView.ItemTemplate>
                    <DataTemplate>
                       
                        <Border Padding="5,3" Stroke="{StaticResource GridBorderBrush}" 
                                BackgroundColor="{StaticResource GridWhite}"
                                StrokeThickness="1">
                            <Border.StrokeShape>
                                <RoundRectangle CornerRadius="4"/>
                            </Border.StrokeShape>
                            <Grid RowDefinitions="Auto,Auto" BackgroundColor="Transparent">
                                <StackLayout Spacing="3" Padding="10">
                                    <Label
                                        Text="{Binding Title}" 
                                        Style="{StaticResource TitleTextStyle}"
                                        HorizontalTextAlignment="Center"/>

                                    <Label
                                        Text="{Binding Count}"
                                        Style="{StaticResource TitleTextStyle}" 
                                        HorizontalTextAlignment="Center"/>
                                </StackLayout>

                                <BoxView Grid.Row="1"
                                          Color="{Binding BorderColor}"  HeightRequest="4"  Margin="0,0,-2,0"                        
                                          />
                            </Grid>

                            <VisualStateManager.VisualStateGroups>
                                <VisualStateGroup x:Name="CommonStates">
                                    <VisualState Name="Normal" />
                                    <VisualState x:Name="Selected">
                                        <VisualState.Setters>
                                            <Setter Property="BackgroundColor" Value="Transparent" />
                                        </VisualState.Setters>
                                    </VisualState>
                                </VisualStateGroup>
                            </VisualStateManager.VisualStateGroups>
                        </Border>
                        
                    </DataTemplate>
                </CollectionView.ItemTemplate>
            </CollectionView>

**Comment by patkozlowski** [comment]
I'm having the same issue.  It seems to be a bug.  It only happens on iOS for me as well.

**Comment by Kaushik2107** [comment]
I have used DevExpress .Net Maui Collection View control to resolve my current project requirement, that is working fine, also performance good for data binding & displaying data conditionally 

And that is free tool from DevExpress 

https://docs.devexpress.com/MAUI/403324/collection-view/index
