### ISSUE TITLE
Incorrcet

### ISSUE THREAD

**Issue by ivanicin** [MicrosoftDocs/xamarin-docs#3504]
### Doc issue description

In this document: https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/ios/platform/healthkit.md

There is this code:
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>com.apple.developer.HealthKit</key>
    <true/>
</dict>
</plist>
```
This doesn't allow the app to be deployed at all. The correct entitlement key is mentioned in other parts of the document and should be all lower cased: `com.apple.developer.healthkit`

**Comment by davidbritch** [comment]
[Microsoft support for Xamarin](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin) will end on May 1, 2024 for all Xamarin SDKs including Xamarin.Forms. In preparation for this, all issues and PRs in this repository are being closed.

.NET MAUI is the replacement for Xamarin.Forms, and it's documentation can be found [here](https://learn.microsoft.com/dotnet/maui/?view=net-maui-8.0).
