### ISSUE TITLE
MSBuild property option AndroidVersionCode doesn't have any effect but docs say otherwise

### ISSUE THREAD

**Issue by Sebosek** [MicrosoftDocs/xamarin-docs#3507]
### Doc issue description

The Doc describes [AndroidVersionCode build property](https://learn.microsoft.com/en-us/xamarin/android/deploy-test/building-apps/build-properties#androidversioncode) as an option how to define Android Version Code for Xamarin. However, that's not true, the only way how we were able to change the Version Code was via `ApplicationVersion`.
Not sure, if it's a breaking change/bug coming with the .NET MAUI, but for us, it's the only way how we can change the Version Code in CI/CD.

`MSBuild version 17.4.0+18d5aef85 for .NET Framework`

[Microsoft Q&A thread](https://learn.microsoft.com/en-us/answers/questions/1091797/msbuild-ignores-androidversioncode.html?childToView=1092909)

**Comment by davidbritch** [comment]
[Microsoft support for Xamarin](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin) will end on May 1, 2024 for all Xamarin SDKs including Xamarin.Forms. In preparation for this, all issues and PRs in this repository are being closed.

.NET MAUI is the replacement for Xamarin.Forms, and it's documentation can be found [here](https://learn.microsoft.com/dotnet/maui/?view=net-maui-8.0).
