### ISSUE TITLE
Missing/Incorrect images showing on Xamarin Profiler page

### ISSUE THREAD

**Issue by dwhathaway** [MicrosoftDocs/xamarin-docs#351]
There are several images that are missing or incorrect on the [Xamarin Profiler](https://docs.microsoft.com/en-us/xamarin/tools/profiler/) docs page.

- [x] Issue 1: `Cycles` screenshot for [VSMac](https://docs.microsoft.com/en-us/xamarin/tools/profiler/?tabs=vsmac#cycles) is missing

![screenshot at may 30 10-44-44](https://user-images.githubusercontent.com/2738317/40737753-864c21b8-63f6-11e8-901f-b36d056e3e2d.png)

- [x] Issue 2: Incorrect image is shown when you click to zoom in on the Visual Studio tab in the same `Cycles` section

Inline image:

![screenshot at may 30 10-46-16](https://user-images.githubusercontent.com/2738317/40737830-b422a4e0-63f6-11e8-9cbb-64f932c599cb.png)

Zoomed image:

![screenshot at may 30 10-46-48](https://user-images.githubusercontent.com/2738317/40737857-c6cd465e-63f6-11e8-88e0-9c35c97da014.png)

**Comment by topgenorth** [comment]
Thanks for finding this!  Fixed in https://github.com/MicrosoftDocs/xamarin-docs-pr/pull/344.
