### ISSUE TITLE
platform popup warning messages

### ISSUE THREAD

**Issue by blmiles** [MicrosoftDocs/xamarin-docs#3517]
I use Auth0 at the moment for authentication. They use a web browser and callback similar to this.
When a user registers or logs in, their plugin in my Xamarin Forms app launches the native browser and the user ALWAYS get this popup warning.

![iOSLoginWarning](https://user-images.githubusercontent.com/26257800/208304746-d7737a0f-7897-41b2-972e-e672d53289ab.jpeg)

I'm sure this will happen every time an up launches native browser on platform, regardless of who the authentication provider is.
IF you launch the browser, you get a warning.

It would be great to include these in this page AND provide a workaround for them.

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1231a1e1-3734-9021-2cc7-eaf99478afca
* Version Independent ID: 01e5fdbe-0b15-4dbe-f8a0-ed40f8593302
* Content: [Xamarin.Essentials: Web Authenticator - Xamarin](https://learn.microsoft.com/en-us/xamarin/essentials/web-authenticator?tabs=android)
* Content Source: [docs/essentials/web-authenticator.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/essentials/web-authenticator.md)
* Product: **xamarin**
* Technology: **xamarin-essentials**
* GitHub Login: @Redth
* Microsoft Alias: **jodick**

**Comment by davidbritch** [comment]
[Microsoft support for Xamarin](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin) will end on May 1, 2024 for all Xamarin SDKs including Xamarin.Forms. In preparation for this, all issues and PRs in this repository are being closed.

.NET MAUI is the replacement for Xamarin.Forms, and it's documentation can be found [here](https://learn.microsoft.com/dotnet/maui/?view=net-maui-8.0).
