### ISSUE TITLE
Helped me get started.

### ISSUE THREAD

**Issue by JimRamey** [MicrosoftDocs/xamarin-docs#3526]
Thank you.
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d277d164-ac67-d097-dba9-3be6f3c2534f
* Version Independent ID: 30c44243-738f-b964-81be-deb28928843f
* Content: [Xamarin.Forms Local Database Tutorial - Xamarin](https://learn.microsoft.com/en-us/xamarin/get-started/tutorials/local-database/?tabs=vswin)
* Content Source: [docs/get-started/tutorials/local-database/index.yml](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/get-started/tutorials/local-database/index.yml)
* Product: **xamarin**
* Technology: **xamarin-crossplatform**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
[Microsoft support for Xamarin](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin) will end on May 1, 2024 for all Xamarin SDKs including Xamarin.Forms. In preparation for this, all issues and PRs in this repository are being closed.

.NET MAUI is the replacement for Xamarin.Forms, and it's documentation can be found [here](https://learn.microsoft.com/dotnet/maui/?view=net-maui-8.0).
