### ISSUE TITLE
Permission change for Android 13

### ISSUE THREAD

**Issue by TB-SWG** [MicrosoftDocs/xamarin-docs#3528]
In Android 13
https://developer.android.com/about/versions/13/behavior-changes-13
READ/WRITE_EXTERNAL_STORAGE seem to have been deprecated so the documentation needs an update.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e4b43ab7-fd40-ba56-c9ab-5de2eb1aad7f
* Version Independent ID: 6c9c7c48-4401-cb25-5cda-637718a22961
* Content: [Xamarin.Essentials: Media Picker - Xamarin](https://learn.microsoft.com/en-us/xamarin/essentials/media-picker?tabs=android)
* Content Source: [docs/essentials/media-picker.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/essentials/media-picker.md)
* Product: **xamarin**
* Technology: **xamarin-essentials**
* GitHub Login: @jamesmontemagno
* Microsoft Alias: **jamont**

**Comment by davidbritch** [comment]
[Microsoft support for Xamarin](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin) will end on May 1, 2024 for all Xamarin SDKs including Xamarin.Forms. In preparation for this, all issues and PRs in this repository are being closed.

.NET MAUI is the replacement for Xamarin.Forms, and it's documentation can be found [here](https://learn.microsoft.com/dotnet/maui/?view=net-maui-8.0).
