### ISSUE TITLE
Kindle Link is broken

### ISSUE THREAD

**Issue by vgray42** [MicrosoftDocs/xamarin-docs#3530]
See title. The link takes me to a Bing page introducing "the new Bing".

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 552cf4bf-553b-d7f4-adc6-7e696029c18b
* Version Independent ID: 67f96253-4908-3f85-fd2f-07563d1b4f7b
* Content: [Creating Mobile Apps with Xamarin.Forms book - Xamarin](https://learn.microsoft.com/en-us/xamarin/xamarin-forms/creating-mobile-apps-xamarin-forms/)
* Content Source: [docs/xamarin-forms/creating-mobile-apps-xamarin-forms/index.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/creating-mobile-apps-xamarin-forms/index.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
[Microsoft support for Xamarin](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin) will end on May 1, 2024 for all Xamarin SDKs including Xamarin.Forms. In preparation for this, all issues and PRs in this repository are being closed.

.NET MAUI is the replacement for Xamarin.Forms, and it's documentation can be found [here](https://learn.microsoft.com/dotnet/maui/?view=net-maui-8.0).
