### ISSUE TITLE
Description of Grow behavior is incorrect

### ISSUE THREAD

**Issue by vgray42** [MicrosoftDocs/xamarin-docs#3533]
The documentation says that when the Grow attached property is used, the extra space in the primary axis is allocated proportional to the values of Grow. However when I set the Grow property for all three of the buttons in my FlexLayout (Direction="Row") to 1, the TOTAL horizontal space is allocated evenly across all buttons, not the EXTRA horizontal space. All of my buttons have identical widths despite having very different text lengths.

Based on the description, I would expect that the buttons with longer text would occupy more space than the buttons with shorter text, just as they would in a horizontal StackLayout when each button has HorizontalOptions="FillAndExpand".

I would like to have the behavior I expected, but have so far been unable to make that happen.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b954b795-b38e-61ff-3ba1-26a0623b97e6
* Version Independent ID: 65795b50-24d3-1997-038e-ffdb609eb20b
* Content: [The Xamarin.Forms FlexLayout - Xamarin](https://learn.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/layouts/flex-layout)
* Content Source: [docs/xamarin-forms/user-interface/layouts/flex-layout.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/layouts/flex-layout.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
[Microsoft support for Xamarin](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin) will end on May 1, 2024 for all Xamarin SDKs including Xamarin.Forms. In preparation for this, all issues and PRs in this repository are being closed.

.NET MAUI is the replacement for Xamarin.Forms, and it's documentation can be found [here](https://learn.microsoft.com/dotnet/maui/?view=net-maui-8.0).
