### ISSUE TITLE
Add event binding to document

### ISSUE THREAD

**Issue by nthornton2010** [MicrosoftDocs/xamarin-docs#3537]
This page includes some useful information regarding creating a reusable content view, but it doesn't include an example regarding how to pass an event (like a button click) out of the reusable view to the parent view.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: af1f1088-8c88-49af-ed40-754ba9399aec
* Version Independent ID: dc22574e-e081-b7a5-69f6-00c0144ae222
* Content: [Xamarin.Forms ContentView - Xamarin](https://learn.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/layouts/contentview)
* Content Source: [docs/xamarin-forms/user-interface/layouts/contentview.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/layouts/contentview.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @profexorgeek
* Microsoft Alias: **jusjohns**

**Comment by davidbritch** [comment]
[Microsoft support for Xamarin](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin) will end on May 1, 2024 for all Xamarin SDKs including Xamarin.Forms. In preparation for this, all issues and PRs in this repository are being closed.

.NET MAUI is the replacement for Xamarin.Forms, and it's documentation can be found [here](https://learn.microsoft.com/dotnet/maui/?view=net-maui-8.0).
