### ISSUE TITLE
Update Swift binding walkthrough to use .xcframeworks

### ISSUE THREAD

**Issue by brunck** [MicrosoftDocs/xamarin-docs#3547]
### Doc issue description

The Swift binding walkthrough uses fat binaries which are now difficult (impossible?) to get right and the Apple-supported way to distribute binaries is now .xcframeworks.
Xamarin iOS binding projects now support .xcframeworks as native references. I'd like to update the documentation (as well as the build script and other sample code, but that is in a different repo) to use this approach. This would also be applicable to .NET for iOS if this article is to be migrated at some point.
I can submit a PR if this is acceptable.

The corresponding issue opened in the sample repo is https://github.com/xamcat/xamarin-binding-swift-framework/issues/13.

**Comment by davidbritch** [comment]
[Microsoft support for Xamarin](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin) will end on May 1, 2024 for all Xamarin SDKs including Xamarin.Forms. In preparation for this, all issues and PRs in this repository are being closed.

.NET MAUI is the replacement for Xamarin.Forms, and it's documentation can be found [here](https://learn.microsoft.com/dotnet/maui/?view=net-maui-8.0).
