### ISSUE TITLE
Example would be easier to understand if width and height were different.

### ISSUE THREAD

**Issue by mludlum** [MicrosoftDocs/xamarin-docs#3550]
When looking at the code, the width and height are the same: 256.  Would be easier to make use of the example if they were different.  Also, don't hard-code 256 everywhere.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a8c79fac-da50-ff45-bf07-ff9fd1b2baf2
* Version Independent ID: 536a1cd8-e3ae-1cb1-1927-3c823ad6456a
* Content: [Accessing SkiaSharp bitmap pixel bits - Xamarin](https://learn.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/graphics/skiasharp/bitmaps/pixel-bits)
* Content Source: [docs/xamarin-forms/user-interface/graphics/skiasharp/bitmaps/pixel-bits.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/graphics/skiasharp/bitmaps/pixel-bits.md)
* Product: **xamarin**
* Technology: **xamarin-skiasharp**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
[Microsoft support for Xamarin](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin) will end on May 1, 2024 for all Xamarin SDKs including Xamarin.Forms. In preparation for this, all issues and PRs in this repository are being closed.

.NET MAUI is the replacement for Xamarin.Forms, and it's documentation can be found [here](https://learn.microsoft.com/dotnet/maui/?view=net-maui-8.0).
