### ISSUE TITLE
script to use sd memory with ram on mackbook

### ISSUE THREAD

**Issue by pricamyou** [MicrosoftDocs/xamarin-docs#3552]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a07f8adb-99d9-7399-55c9-9af950045f03
* Version Independent ID: c917e050-482b-5b2a-c716-f4df504bca3b
* Content: [Animation in Xamarin.Forms - Xamarin](https://learn.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/animation/)
* Content Source: [docs/xamarin-forms/user-interface/animation/index.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/animation/index.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
[Microsoft support for Xamarin](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin) will end on May 1, 2024 for all Xamarin SDKs including Xamarin.Forms. In preparation for this, all issues and PRs in this repository are being closed.

.NET MAUI is the replacement for Xamarin.Forms, and it's documentation can be found [here](https://learn.microsoft.com/dotnet/maui/?view=net-maui-8.0).
