### ISSUE TITLE
The name 'editor' does not exist

### ISSUE THREAD

**Issue by DominicMannion** [MicrosoftDocs/xamarin-docs#3555]
I am a newbie but why do I keep getting "The name 'editor' does not exist in the current context" for NotesPage.xaml.cs?

**Comment by davidbritch** [comment]
[Microsoft support for Xamarin](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin) will end on May 1, 2024 for all Xamarin SDKs including Xamarin.Forms. In preparation for this, all issues and PRs in this repository are being closed.

.NET MAUI is the replacement for Xamarin.Forms, and it's documentation can be found [here](https://learn.microsoft.com/dotnet/maui/?view=net-maui-8.0).
