### ISSUE TITLE
Wrong service name mentioned in the documentation

### ISSUE THREAD

**Issue by ksivasenthil** [MicrosoftDocs/xamarin-docs#3556]
The document I was reading was about configuring ADB2C client in Xamarin.Forms project. However in a section reference to Azure Notification Hubs was mentioned. I am confused whether we need to configure Azure Notification Hubs to make Azure ADB2C work with Xamarin.Forms. In my experience it is a no. But since official documentation calls it so, I am questioning myself and also questioning you whether it is a honest mistake?

![image](https://github.com/MicrosoftDocs/xamarin-docs/assets/7167802/7f7acdd4-206e-4884-85ea-b05035663956)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 11f5b457-d99a-06d4-d203-f9eeaa27e0d9
* Version Independent ID: b23b3a5d-b63b-dfe1-bb46-94f57c907be5
* Content: [Authenticate Users with Azure Active Directory B2C - Xamarin](https://learn.microsoft.com/en-gb/xamarin/xamarin-forms/data-cloud/authentication/azure-ad-b2c#android)
* Content Source: [docs/xamarin-forms/data-cloud/authentication/azure-ad-b2c.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/data-cloud/authentication/azure-ad-b2c.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
[Microsoft support for Xamarin](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin) will end on May 1, 2024 for all Xamarin SDKs including Xamarin.Forms. In preparation for this, all issues and PRs in this repository are being closed.

.NET MAUI is the replacement for Xamarin.Forms, and it's documentation can be found [here](https://learn.microsoft.com/dotnet/maui/?view=net-maui-8.0).
