### ISSUE TITLE
FilePicker : Xamarin.Essentials.PermissionException: StorageRead permission was not granted: Denied for Android 13

### ISSUE THREAD

**Issue by rmpQue** [MicrosoftDocs/xamarin-docs#3559]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: bde8b00e-bef2-d10c-268f-2e49e236a89f
* Version Independent ID: dad8b07c-2227-c7ed-6369-d10d9b132e99
* Content: [Xamarin.Essentials: File Picker - Xamarin](https://learn.microsoft.com/en-us/xamarin/essentials/file-picker?tabs=android)
* Content Source: [docs/essentials/file-picker.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/essentials/file-picker.md)
* Product: **xamarin**
* Technology: **xamarin-essentials**
* GitHub Login: @jamesmontemagno
* Microsoft Alias: **jamont**

**Comment by davidbritch** [comment]
[Microsoft support for Xamarin](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin) will end on May 1, 2024 for all Xamarin SDKs including Xamarin.Forms. In preparation for this, all issues and PRs in this repository are being closed.

.NET MAUI is the replacement for Xamarin.Forms, and it's documentation can be found [here](https://learn.microsoft.com/dotnet/maui/?view=net-maui-8.0).
