### ISSUE TITLE
Improve Android SDK setup instructions

### ISSUE THREAD

**Issue by kapsiR** [MicrosoftDocs/xamarin-docs#3567]
## Description
The [Setting up the Android SDK for Xamarin.Android](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/android/get-started/installation/android-sdk.md) documentation seems to be intended for the setup of Visual Studio only.  
There is no information regarding the Visual Studio Build Tools. (typically used in a CI environment)

## Suggested improvement
Add hints for the differences to the VS Build Tools.  
An example:  
 - Problem: Xamarin Android SDK Manager is not available when installing the specified workloads with VS Build Tools
 - Solution: Add a hint, that there is a [CLI tool](https://learn.microsoft.com/en-us/xamarin/android/troubleshooting/sdk-cli-tooling-changes#cli-tools) available instead ([`sdkmanager`](https://developer.android.com/tools/sdkmanager))

## Open question
>  This guide applies to Visual Studio 2022, Visual Studio 2019, Visual Studio 2017, and Visual Studio for Mac.

If we can modify the document despite this notification, I'm willing to provide a small PR for this

**Comment by davidbritch** [comment]
[Microsoft support for Xamarin](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin) will end on May 1, 2024 for all Xamarin SDKs including Xamarin.Forms. In preparation for this, all issues and PRs in this repository are being closed.

.NET MAUI is the replacement for Xamarin.Forms, and it's documentation can be found [here](https://learn.microsoft.com/dotnet/maui/?view=net-maui-8.0).
