### ISSUE TITLE
ActionBootCompleted requires additional permissions

### ISSUE THREAD

**Issue by mattleibow** [MicrosoftDocs/xamarin-docs#3571]
### Doc issue description

There may be additional permissions needed for newer Android versions with regards to the boot completed broadcasts:

https://github.com/dotnet/maui/issues/15009

https://developer.android.com/reference/android/content/Intent#ACTION_BOOT_COMPLETED

> Broadcast Action: This is broadcast once, after the user has finished booting. It can be used to perform application-specific initialization, such as installing alarms. You must hold the [Manifest.permission.RECEIVE_BOOT_COMPLETED](https://developer.android.com/reference/android/Manifest.permission#RECEIVE_BOOT_COMPLETED) permission in order to receive this broadcast.

**Comment by davidbritch** [comment]
[Microsoft support for Xamarin](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin) will end on May 1, 2024 for all Xamarin SDKs including Xamarin.Forms. In preparation for this, all issues and PRs in this repository are being closed.

.NET MAUI is the replacement for Xamarin.Forms, and it's documentation can be found [here](https://learn.microsoft.com/dotnet/maui/?view=net-maui-8.0).
