### ISSUE TITLE
Broken Link: How to Analyze Videos in Real-time

### ISSUE THREAD

**Issue by ksaye** [MicrosoftDocs/xamarin-docs#3572]
The link [How to Analyze Videos in Real-time](https://learn.microsoft.com/en-us/azure/cognitive-services/face/face-api-how-to-topics/howtoanalyzevideo_face/) does not work

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e9fcd5b6-8fb8-6285-74d1-23b49b9cb536
* Version Independent ID: ec38099a-44ee-cabc-1329-e9f6b179b5ae
* Content: [Perceived Emotion Recognition Using the Face API - Xamarin](https://learn.microsoft.com/en-us/xamarin/xamarin-forms/data-cloud/azure-cognitive-services/emotion-recognition)
* Content Source: [docs/xamarin-forms/data-cloud/azure-cognitive-services/emotion-recognition.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/data-cloud/azure-cognitive-services/emotion-recognition.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
[Microsoft support for Xamarin](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin) will end on May 1, 2024 for all Xamarin SDKs including Xamarin.Forms. In preparation for this, all issues and PRs in this repository are being closed.

.NET MAUI is the replacement for Xamarin.Forms, and it's documentation can be found [here](https://learn.microsoft.com/dotnet/maui/?view=net-maui-8.0).
