### ISSUE TITLE
Proyecto final forms

### ISSUE THREAD

**Issue by Alicia2304** [MicrosoftDocs/xamarin-docs#3573]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 90de12ea-e9ac-efe7-f54c-0e67b2df4a0d
* Version Independent ID: 138ee0d6-8d6c-9e56-5f9f-f674b14d6481
* Content: [Xamarin.Forms quickstarts - Xamarin](https://learn.microsoft.com/en-us/xamarin/get-started/quickstarts/)
* Content Source: [docs/get-started/quickstarts/index.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/get-started/quickstarts/index.md)
* Product: **xamarin**
* Technology: **xamarin-forms**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
[Microsoft support for Xamarin](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin) will end on May 1, 2024 for all Xamarin SDKs including Xamarin.Forms. In preparation for this, all issues and PRs in this repository are being closed.

.NET MAUI is the replacement for Xamarin.Forms, and it's documentation can be found [here](https://learn.microsoft.com/dotnet/maui/?view=net-maui-8.0).
