### ISSUE TITLE
Xamarin Forms 

### ISSUE THREAD

**Issue by estrusom** [MicrosoftDocs/xamarin-docs#3574]
If the issue is:
In "Create your first Xamarin.Forms app" tutorial
The android application works with the emulator, but when I install the apk on my phone nothing works!

On the mobile phone the app starts and closes immediately, the message shown on the phone is: The PrimaApp.Android app keeps stopping"

![1700665820519](https://github.com/MicrosoftDocs/xamarin-docs/assets/42372789/7cb5f58f-4f42-4aec-9cae-5c35c41e8bd9)

**Comment by davidbritch** [comment]
[Microsoft support for Xamarin](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin) will end on May 1, 2024 for all Xamarin SDKs including Xamarin.Forms. In preparation for this, all issues and PRs in this repository are being closed.

.NET MAUI is the replacement for Xamarin.Forms, and it's documentation can be found [here](https://learn.microsoft.com/dotnet/maui/?view=net-maui-8.0).
