### ISSUE TITLE
Edits made to example:

### ISSUE THREAD

**Issue by robergfoll** [MicrosoftDocs/xamarin-docs#36]
I changed this so it would work in my environment:
 base.OnCreate(bundle);

            // Set our view from the "main" layout resource
            //SetContentView(Resource.Layout.Main);

            base.OnCreate(bundle);

            ListAdapter = new ArrayAdapter<string>(this, Resource.Layout.list_Item, countries);

            ListView.TextFilterEnabled = true;

            ListView.ItemClick += delegate (object sender, AdapterView.ItemClickEventArgs args)
            {
                Toast.MakeText(Application, ((TextView)args.View).Text, ToastLength.Short).Show();
            };

This adds the data to the list and shows it at runtime

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: feddc216-71a5-30ce-10a5-bbf412f304da
* Version Independent ID: e376d820-7762-5f5d-4585-ae237ade20d2
* Content: [ListView - Xamarin](https://docs.microsoft.com/en-us/xamarin/android/user-interface/layouts/list-view/)
* Content Source: [docs/android/user-interface/layouts/list-view/index.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/android/user-interface/layouts/list-view/index.md)
* Service: **unspecified**
* GitHub Login: @mgmclemore
* Microsoft Alias: **mamcle**

**Comment by mgmclemore** [comment]
Thanks @robergfoll!  I've test/incorporated your suggestion and also updated several other areas that were out of date. The changes should be published soon. Appreciate your time!
