### ISSUE TITLE
Getting the database path

### ISSUE THREAD

**Issue by charlesroddie** [MicrosoftDocs/xamarin-docs#362]
Half of this documentation is about getting the database path. It would be better to get this directly from SQLite.Net. I have raised an issue here: https://github.com/praeclarum/sqlite-net/issues/720

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3ab6098a-39c7-151f-124b-f88aa62c4659
* Version Independent ID: dc27c1e4-ff12-c1af-646a-c2617def0bcd
* Content: [Local Databases - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/databases)
* Content Source: [docs/xamarin-forms/app-fundamentals/databases.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/app-fundamentals/databases.md)
* Service: **unspecified**
* Product: **xamarin**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by charlesroddie** [comment]
Actually you can choose any database path you want. So all the documentation about DependencyServices is unneccessary.

Just choose a consistent path relative to LocalApplicationData and you can get rid of the DependencyServices:

```
Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData), "DB.db")
```

**Comment by davidbritch** [comment]
Thanks for the feedback @charlesroddie 

I've opened an issue in our private repo to mention this next time the doc is updated.
