### ISSUE TITLE
App crashes on Android

### ISSUE THREAD

**Issue by pratyush-19** [MicrosoftDocs/xamarin-docs#363]
In the void sendNotifcation () method, my android app get crashed in this particular line
 var notificationManager = NotificationManager.FromContext(this);

MonoDroid] System.NullReferenceException: Object reference not set to an instance of an object.
[MonoDroid] at PushNotification.Plugin.PushNotificationGcmListener.OnMessageReceived (System.String from, Android.OS.Bundle extras) [0x00095] in C:\xamarin-plugins\PushNotification\PushNotification\PushNotification.Plugin.Android\PushNotificationGcmListener.cs:65 
[MonoDroid] at Android.Gms.Gcm.GcmListenerService.n_OnMessageReceived_Ljava_lang_String_Landroid_os_Bundle_ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_from, System.IntPtr native_data) [0x00017] in <eb44ad118cca47de8c776a05c1e4d8fa>:0 
[MonoDroid] at (wrapper dynamic-method) System.Object.52601fe0-e5ec-40dd-a293-8412400525ca(intptr,intptr,intptr,intptr)

Any help is appreciated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f2f7318c-8cd3-1aea-1f5e-e14955e2fa22
* Version Independent ID: 655cb554-cd03-e6ae-f7dd-9e2ba18a4a28
* Content: [Sending Push Notifications from Azure Mobile Apps - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/data-cloud/push-notifications/azure)
* Content Source: [docs/xamarin-forms/data-cloud/push-notifications/azure.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/data-cloud/push-notifications/azure.md)
* Service: **unspecified**
* Product: **xamarin**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by conceptdev** [comment]
Hi @pratyush-19, this issues list is to comment on/improve the documentation itself. You can visit [the Developer Community site](https://developercommunity.visualstudio.com/) to ask questions or provide product feedback.

I did notice your exception message mentions `Gcm` - Google Cloud Messaging - which is now deprecated and replaced by Firebase (as the doc describes).

**Comment by pratyush-19** [comment]
Hi Craig,

Can we have the documentation on Firebase ?
If it is available, can you share the link.

Thanks.
Pratyush

Regards,
Pratyush
