### ISSUE TITLE
Repositories

### ISSUE THREAD

**Issue by docen67** [MicrosoftDocs/xamarin-docs#365]
Why do you publish the repositories if they are not allowed to be downloaded?.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c6b07535-bcf2-5dbc-e03d-85eaf5cbdfa4
* Version Independent ID: 6b0e3a60-c813-2f24-d813-7bb54dc4c5ce
* Content: [Summary of Chapter 22. Animation - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/creating-mobile-apps-xamarin-forms/summaries/chapter22)
* Content Source: [docs/xamarin-forms/creating-mobile-apps-xamarin-forms/summaries/chapter22.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/creating-mobile-apps-xamarin-forms/summaries/chapter22.md)
* Service: **unspecified**
* Product: **xamarin**
* GitHub Login: @charlespetzold
* Microsoft Alias: **chape**

**Comment by conceptdev** [comment]
@docen67 the samples repository is at https://github.com/xamarin/xamarin-forms-book-samples and you can either download it or clone it using Git. Look for the **Clone or download** button on the top-right above the file/folder list.
