### ISSUE TITLE
教程是截图不符合最新版visual studio for Mac 7.5

### ISSUE THREAD

**Issue by CeciAc** [MicrosoftDocs/xamarin-docs#366]
@hantengx commented on [Thu May 31 2018](https://github.com/MicrosoftDocs/xamarin-docs.zh-cn/issues/1)

In the Configure your Blank Forms app dialog, without the Use Portable Class Library radio button. It is the use .net standard

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 2de3e72c-8948-4dd5-e37f-9cf81e62c127
* Version Independent ID: 7b7c5c7f-4102-8e91-fbe6-7d21fcc8f5be
* Content: [Xamarin.Forms 快速入门 - Xamarin](https://docs.microsoft.com/zh-cn/xamarin/xamarin-forms/get-started/hello-xamarin-forms/quickstart?tabs=vsmac#feedback)
* Content Source: [docs/xamarin-forms/get-started/hello-xamarin-forms/quickstart.md](https://github.com/MicrosoftDocs/xamarin-docs.zh-CN/blob/live/docs/xamarin-forms/get-started/hello-xamarin-forms/quickstart.md)
* Service: **unspecified**
* Product: **xamarin**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

---

@CeciAc commented on [Thu May 31 2018](https://github.com/MicrosoftDocs/xamarin-docs.zh-cn/issues/1#issuecomment-393650651)

Hello, @hantengx,
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by davidbritch** [comment]
I've fixed this in a forthcoming update.
