### ISSUE TITLE
"2. Select iOS Bundle Signing"

### ISSUE THREAD

**Issue by EtienneJuneau** [MicrosoftDocs/xamarin-docs#368]
I was stuck on that step until I found in a Xamarin blog post (https://blog.xamarin.com/automatic-provisioning-visual-studio-2017/) that I needed to go through this step first ("Connecting your Apple Account"). I'm a total newbie, but still, I'm thinking you may want to make that a bit more clear.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bb327a64-010d-dba8-5ebc-546892d739af
* Version Independent ID: 48a24297-7b8f-b1b2-7b25-44f40fe33eac
* Content: [Publishing to the App Store - Xamarin](https://docs.microsoft.com/en-us/xamarin/ios/deploy-test/app-distribution/app-store-distribution/publishing-to-the-app-store?tabs=vswin#building-and-submitting-the-distributable)
* Content Source: [docs/ios/deploy-test/app-distribution/app-store-distribution/publishing-to-the-app-store.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/ios/deploy-test/app-distribution/app-store-distribution/publishing-to-the-app-store.md)
* Product: **xamarin**
* GitHub Login: @bradumbaugh
* Microsoft Alias: **brumbaug**

**Comment by bradumbaugh** [comment]
Hi @EtienneJuneau, I'm currently working on an update to this document. I'll let you know when it has been published!

**Comment by bradumbaugh** [comment]
@EtienneJuneau Automatic provisioning does not yet work with app distribution; you'll need to set up an App Store provisioning profile and manually configure your build to use it. As mentioned on a couple of other issues, I have an update for this doc waiting in the wings; it should be published in the next few days. Hope this helps! Thanks.

**Comment by EtienneJuneau** [comment]
Thanks for taking the time @bradumbaugh. I finally managed to make it work, after much trial, error, and Googling :)

Cheers.
