### ISSUE TITLE
Improve explanation of OAuth2Authenticator configuration

### ISSUE THREAD

**Issue by SabotageAndi** [MicrosoftDocs/xamarin-docs#369]
It's about this chapter: https://docs.microsoft.com/en-us/xamarin/xamarin-forms/data-cloud/authentication/oauth#creating-and-configuring-an-authenticator

For the values of AuthorizeUrl and AccessTokenUrl it is unclear where to get the values. But they are in the example (https://github.com/xamarin/xamarin-forms-samples/blob/master/WebServices/OAuthNativeFlow/OAuthNativeFlow/Constants.cs). What about at least a direct link to the example?

No idea how to get the Redirect URL. I can't find anything in the Google Developer console. The comment in the example (https://github.com/xamarin/xamarin-forms-samples/blob/master/WebServices/OAuthNativeFlow/OAuthNativeFlow/Constants.cs#L18) added confusion.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aa8bb9e0-5898-0d11-0213-fd4d8c8d0297
* Version Independent ID: 2f46e1f7-164f-2f32-70c0-f28919d16c5c
* Content: [Authenticating Users with an Identity Provider - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/data-cloud/authentication/oauth)
* Content Source: [docs/xamarin-forms/data-cloud/authentication/oauth.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/data-cloud/authentication/oauth.md)
* Product: **xamarin**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi Andreas,

Thanks for the feedback. I've created an issue in our internal tracking system to update the doc to provide the `AuthorizeUrl` and `AccessTokenUrl` constants.

The Redirect URL comes from the Google Developers Console. If you follow the instructions at https://docs.microsoft.com/en-us/xamarin/xamarin-forms/data-cloud/authentication/oauth#setup you'll have a Google API project. If you click on the Credentials tab for the project you'll find the RedirectURI as the Client ID. It will look something like `902730282010-ks3kd03ksoasioda93jldas93jjj22kr.apps.googleusercontent.com`. However, this needs reversing to become a valid RedirectURI: `com.googleusercontent.apps.902730282010-ks3kd03ksoasioda93jldas93jjj22kr`. For more info, see https://docs.microsoft.com/en-us/xamarin/xamarin-forms/data-cloud/authentication/oauth#processing-the-redirect-url
