### ISSUE TITLE
grammer{}

### ISSUE THREAD

**Issue by brokenjavagit** [MicrosoftDocs/xamarin-docs#37]
The library is currently available as a cross-platform NuGet Package, you can {ADD} it to your project by adding the NuGet reference.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 671dfb25-d3b4-facf-3c25-824f8c007f90
* Version Independent ID: eeaec2cf-1f69-07e6-d9d5-48a36ddb1c07
* Content: [An Introduction to SkiaSharp - Xamarin](https://docs.microsoft.com/en-us/xamarin/graphics-games/skiasharp/introduction#feedback)
* Content Source: [docs/graphics-games/skiasharp/introduction.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/graphics-games/skiasharp/introduction.md)
* Service: **unspecified**
* GitHub Login: @charlespetzold
* Microsoft Alias: **chape**

**Comment by asb3993** [comment]
Thanks for filing this issue @brokenjavagit. I've pushed the changed at my end. This should be updated shortly.
