### ISSUE TITLE
Getting Null Pointer Excpetion when i recieve a notification from FCM

### ISSUE THREAD

**Issue by vikram-relyfy** [MicrosoftDocs/xamarin-docs#371]
I get proper notification shown in notification bars, OnRecieved() method completes execution and then the app gets crash with the Null Reference Exception.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8d9bfb2a-2e5d-d505-337f-919251a85de3
* Version Independent ID: 695bff64-ae87-8c0f-5616-20b67893fdf0
* Content: [Remote Notifications with Firebase Cloud Messaging - Xamarin](https://docs.microsoft.com/en-us/xamarin/android/data-cloud/google-messaging/remote-notifications-with-fcm?tabs=vswin)
* Content Source: [docs/android/data-cloud/google-messaging/remote-notifications-with-fcm.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/android/data-cloud/google-messaging/remote-notifications-with-fcm.md)
* Product: **xamarin**
* GitHub Login: @mgmclemore
* Microsoft Alias: **mamcle**

**Comment by mgmclemore** [comment]
Hi @vikram-relyfy, it looks like you've found a bug. This repository is only for documentation-specific issues: could you please report the specifics about your null pointer exception at [Developer Community](https://developercommunity.visualstudio.com/spaces/8/index.html) (click Report a problem)? Thank you!
