### ISSUE TITLE
Obsoleted

### ISSUE THREAD

**Issue by CeciAc** [MicrosoftDocs/xamarin-docs#372]
@la99er commented on [Sun Jun 03 2018](https://github.com/MicrosoftDocs/xamarin-docs.de-de/issues/3)

The Webpage console.developers.google.com doesn't look like it is presented here. Probably they just updated their page. But now it's much easier to get the API Key. Just create your project on the page and go to APIs. There you select Maps SK for Android. After adding the API to your project, you can easily generate your API Key and insert in in the manifest file of your xamarin.forms or xamarin.android project. You don't need the keytool anymore. 

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 4d1bc9be-4365-8015-1c11-a9ab1770ea01
* Version Independent ID: 82abd821-8fe1-4204-be15-bf3d8a92abd7
* Content: [Abrufen einer Google-API-Schlüssel zugeordnet ist - Xamarin](https://docs.microsoft.com/de-de/xamarin/android/platform/maps-and-location/maps/obtaining-a-google-maps-api-key?tabs=vswin)
* Content Source: [docs/android/platform/maps-and-location/maps/obtaining-a-google-maps-api-key.md](https://github.com/MicrosoftDocs/xamarin-docs.de-DE/blob/live/docs/android/platform/maps-and-location/maps/obtaining-a-google-maps-api-key.md)
* Product: **xamarin**
* GitHub Login: @mgmclemore
* Microsoft Alias: **mamcle**

**Comment by mgmclemore** [comment]
Hi @CeciAc , thank you for the feedback! We're in the process of updating this topic to be in sync with Google's latest changes -- should be published soon.
