### ISSUE TITLE
Stuck at "2. From the Build menu, select Archive for Publishing:"

### ISSUE THREAD

**Issue by EtienneJuneau** [MicrosoftDocs/xamarin-docs#373]
Not sure if I'm the problem, but after step 2 "From the Build menu, select Archive for Publishing", VS  for Mac outputs "Done building project" and the archive does not seem to be created or displayed. The archives screen still shows "Use Build &gt; Archive"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bb327a64-010d-dba8-5ebc-546892d739af
* Version Independent ID: 48a24297-7b8f-b1b2-7b25-44f40fe33eac
* Content: [Publishing to the App Store - Xamarin](https://docs.microsoft.com/en-us/xamarin/ios/deploy-test/app-distribution/app-store-distribution/publishing-to-the-app-store?tabs=vsmac#submitting-your-app-to-apple)
* Content Source: [docs/ios/deploy-test/app-distribution/app-store-distribution/publishing-to-the-app-store.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/ios/deploy-test/app-distribution/app-store-distribution/publishing-to-the-app-store.md)
* Product: **xamarin**
* GitHub Login: @bradumbaugh
* Microsoft Alias: **brumbaug**

**Comment by bradumbaugh** [comment]
Hi @EtienneJuneau, I have an update coming to this doc that will hopefully help you out. My suspicion is that this may have to do with provisioning profile confusion. I'm hoping the update will be published in the next few days.

In the meantime, you might try configuring your build to use a distribution provisioning profile for the build configuration you are attempting to archive. I'm not certain if this will make a difference, but it might be worth a shot.

If that doesn't work, feel free to post on [Developer Community](https://developercommunity.visualstudio.com/spaces/8/index.html) for support.

**Comment by EtienneJuneau** [comment]
Hi again @bradumbaugh. This problem ended up being related to my Mac. I fixed the Mac, and the building and archiving process worked. Thx!
