### ISSUE TITLE
Vizualisation error with Live Player

### ISSUE THREAD

**Issue by CharbonnFc** [MicrosoftDocs/xamarin-docs#374]
The sample work well with Iphone Simulator. 
With Live Player, a nullexception about instance of object  at the beginning.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3869aaed-63b6-64b5-b817-0331748f554d
* Version Independent ID: 0345d352-6ebb-b239-cdfe-1a562bd955ca
* Content: [Walkthrough - Using Background Location - Xamarin](https://docs.microsoft.com/en-us/xamarin/ios/app-fundamentals/backgrounding/ios-backgrounding-walkthroughs/location-walkthrough)
* Content Source: [docs/ios/app-fundamentals/backgrounding/ios-backgrounding-walkthroughs/location-walkthrough.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/ios/app-fundamentals/backgrounding/ios-backgrounding-walkthroughs/location-walkthrough.md)
* Product: **xamarin**
* GitHub Login: @bradumbaugh
* Microsoft Alias: **brumbaug**

**Comment by bradumbaugh** [comment]
Hi @CharbonnFc – Xamarin Live Player is in preview, and has some [limitations](http://docs.microsoft.com/xamarin/tools/live-player/limitations).

Please post any bugs you encounter on [Developer Community](https://developercommunity.visualstudio.com/spaces/8/index.html).

Thank you!
