### ISSUE TITLE
Sorry for stupid question!

### ISSUE THREAD

**Issue by nguyenthanhliemfc** [MicrosoftDocs/xamarin-docs#375]
Thank for your docs!
But I'm not good in English and Translate tool can't translate some word in development app.
1. What is "MainPage" here:
MessagingCenter.Send&lt;MainPage&gt; (this, "Hi");
2. Now I want to send message from Android Started Service. Which word I will put in Send&lt;???&gt;
Thank for help!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4d80a771-2198-328b-b9fa-fe25f16261cd
* Version Independent ID: be0408fe-d00b-baf6-8a9c-e24659029c4b
* Content: [MessagingCenter - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/messaging-center)
* Content Source: [docs/xamarin-forms/app-fundamentals/messaging-center.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/app-fundamentals/messaging-center.md)
* Product: **xamarin**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @nguyenthanhliemfc,

1. `MainPage` is the name of the page class, and is used here as the type of the sender sending the message.
2. Put the type name for the Android service, and make sure you use the same type when subscribing to receive messages.

Hope this helps!

**Comment by nguyenthanhliemfc** [comment]
Thank you!

**Comment by nguyenthanhliemfc** [comment]
It's mean:
Page 2: MessagingCenter.Send<Page2, string>(this, "Geofence", "Entered");
Page 1: MessagingCenter.Subscribe<Page2, string>(this, "Hi", (sender, arg) => { LabelStatus.Text = arg; });
I'm right sir?

**Comment by nguyenthanhliemfc** [comment]
Thank you Sir!

**Comment by nguyenthanhliemfc** [comment]
Now I don't care which page I only use object

MessagingCenter.Send<object, string>(this, "Hi", "Entered");
MessagingCenter.Subscribe<object, string>(this, "Hi", (sender, arg) => { LabelStatus.Text = arg; });

It's work fine. Is it good when use "object"?
