### ISSUE TITLE
In-house Enterprise deployment - limited distribution?

### ISSUE THREAD

**Issue by clcProjects** [MicrosoftDocs/xamarin-docs#376]
Hi,

We have an Apple Enterprise license and are developing apps for our enterprise. Am I misreading the above regarding Devices. The instructions seem to indicate that the Enterprise distribution is limited to specific devices. Is this correct?  We have several hundred users in our organization and will deploy via our MDM - do we need to add the UDID of each device to our device list?  

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 07728df6-593b-0060-20c6-156a835a78e6
* Version Independent ID: c2e3247b-2223-90f8-073e-3b3164b58a75
* Content: [In-House Distribution - Xamarin](https://docs.microsoft.com/en-us/xamarin/ios/deploy-test/app-distribution/in-house-distribution?tabs=vswin)
* Content Source: [docs/ios/deploy-test/app-distribution/in-house-distribution.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/ios/deploy-test/app-distribution/in-house-distribution.md)
* Product: **xamarin**
* GitHub Login: @bradumbaugh
* Microsoft Alias: **brumbaug**

**Comment by bradumbaugh** [comment]
Hi @clcProjects, thanks for the question. We have a few screenshots that need to be updated on this page, so I'll add that to our internal backlog to fix those and clarify this process. In the meantime, to answer your question: In House distribution of enterprise apps doesn't require UDIDs, as discussed in this [2014 WWDC presentation](https://developer.apple.com/videos/play/wwdc2014/705/).

**Comment by clcProjects** [comment]
Excellent info.  Thanks!
