### ISSUE TITLE
Tutorial Does not Compile

### ISSUE THREAD

**Issue by Khilborn** [MicrosoftDocs/xamarin-docs#378]
I went step by step (bypassed IIS since the WCF Service will be hosted as a Windows Service) and the following is not known HelloWorldServiceClient

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6b6d6bd0-71b7-f141-2eed-9f99e5d30099
* Version Independent ID: 37b4dd5f-4f41-d850-6be1-be92fcb3b739
* Content: [Walkthrough - Working with WCF - Xamarin](https://docs.microsoft.com/en-us/xamarin/cross-platform/data-cloud/web-services/walkthrough-working-with-wcf)
* Content Source: [docs/cross-platform/data-cloud/web-services/walkthrough-working-with-wcf.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/cross-platform/data-cloud/web-services/walkthrough-working-with-wcf.md)
* Product: **xamarin**
* GitHub Login: @asb3993
* Microsoft Alias: **amburns**

**Comment by bradumbaugh** [comment]
Hi @Khilborn – I have it on our backlog to take a look at this doc to see how we need to update it. In the meantime, take a look at the [associated sample](https://developer.xamarin.com/samples/mobile/WCF-Walkthrough/). I'll also capture your feedback here so it isn't lost when we do revisit it.

Appreciate you calling this out.
