### ISSUE TITLE
The link from the images are broken

### ISSUE THREAD

**Issue by gosali** [MicrosoftDocs/xamarin-docs#379]
@vhoyer commented on [Tue Jun 05 2018](https://github.com/MicrosoftDocs/xamarin-docs.pt-br/issues/5)

O link das imagens está quebrado

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: 711d54ad-842b-2141-95b3-fc71d053dbac
* Version Independent ID: be8e8253-7014-1065-ee9b-27a41d35b1ec
* Content: [Temas - Xamarin](https://docs.microsoft.com/pt-br/xamarin/xamarin-forms/user-interface/themes/)
* Content Source: [docs/xamarin-forms/user-interface/themes/index.md](https://github.com/MicrosoftDocs/xamarin-docs.pt-BR/blob/live/docs/xamarin-forms/user-interface/themes/index.md)
* Product: **xamarin**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

---

@gosali commented on [Tue Jun 05 2018](https://github.com/MicrosoftDocs/xamarin-docs.pt-br/issues/5#issuecomment-394861829)

Hello, @vhorne , 

Your contribution is much appreciated. Your feedback is related to the original documentation. 

Hence, we are migrating this issue to the English repo. Please review the status of the issue here - XXX. 

We truly appreciate your contribution to our articles.  

Kind regards, 

Microsoft DOCS International Team

**Comment by vhoyer** [comment]
No, its not releated to the original english repo, actually, in the english version, it works just fine, see:

[en-us](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/themes/)
[pt-br](https://docs.microsoft.com/pt-br/xamarin/xamarin-forms/user-interface/themes/)

**Comment by davidbritch** [comment]
Closing as this isn't an issue for the English repo.

**Comment by conceptdev** [comment]
looks like the space in the `![ ](` image markdown causes an issue in **localized** repos??

```
![](images/standard-none-sml.png "Controles sem temas") ![ ] (images/standard-light-sml.png "controles com tema claro") ![ ] (images/standard-dark-sml.png "controles com tema escuro")
```

<img width="668" alt="screen shot 2018-06-20 at 9 33 10 am" src="https://user-images.githubusercontent.com/199373/41671791-00780c6e-746d-11e8-999a-5dded049a628.png">

> NOTE: there is no space in the English markdown, not sure where that is being introduced in the workflow

```
![](images/standard-none-sml.png "Controls without Theming") ![](images/standard-light-sml.png "Controls with Light Theme") ![](images/standard-dark-sml.png "Controls with Dark Theme")
```

## another example...

```
![](images/boxview-light-sml.png "BoxView com um tema claro StyleClass") ![ ] (images/boxview-dark-sml.png "BoxView com StyleClass um tema escuro")
```

<img width="661" alt="screen shot 2018-06-20 at 9 33 14 am" src="https://user-images.githubusercontent.com/199373/41671793-02cd22b0-746d-11e8-813c-3e621fbf7a07.png">

**Comment by DavidPrio** [comment]
Hello, @conceptdev ,
 
Thank you for your feedback. Since this is a different problem, please kindly open a new Issue. For this reason we need to close this issue. Thanks for understanding.

Kind regards,
Microsoft DOCS International Team

**Comment by DavidPrio** [comment]
#please-close

**Comment by conceptdev** [comment]
per @DavidPrio's request, this will be addressed via the original issue at https://github.com/MicrosoftDocs/xamarin-docs.pt-br/issues/5
