### ISSUE TITLE
Naming convention

### ISSUE THREAD

**Issue by brokenjavagit** [MicrosoftDocs/xamarin-docs#380]
Why is this called Grid and not GridLayout?  For semantics sake.  Is there a more appropriate forum to ask questions such as these for future reference?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c0902f8-eb40-4c56-958a-f13f064c8293
* Version Independent ID: 1e930440-f312-6301-d786-262b98f9ce2f
* Content: [Grid - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/layouts/grid#feedback)
* Content Source: [docs/xamarin-forms/user-interface/layouts/grid.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/layouts/grid.md)
* Product: **xamarin**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @brokenjavagit 

Most of the layout classes are named after native layouts in iOS/Android. However, the `Grid` layout was so named to keep syntactic parity with the WPF platform, from which it came.

**Comment by conceptdev** [comment]
Xamarin.Forms is open-source and available at https://github.com/xamarin/Xamarin.Forms - that is a good place to start investigating technical questions on the API.

**Comment by brokenjavagit** [comment]
Thank you David, and Craig for answering my question.  The impact of your responses is overwhelming, profound and much appreciated even if they seem trivial and pedantic.  Thank you for your time.
