### ISSUE TITLE
Changing background color of splash screen as theme preference as users options.

### ISSUE THREAD

**Issue by ma17961363** [MicrosoftDocs/xamarin-docs#381]
How can we change the background color of the splash screen programmatically that applicable to preview window?

We know when windowDisablePreview is false (as its default value), launching the app quickly shows the theme of the activity as a MainLauncher. Now the question is here, how can we change the background color of the preview window? When it is changed programmatically in the activity's OnCreate method before base.OnCreate method it works but first for a moment it shows the background color that exists in the layer-list then changes the color according to the code.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5823a3fa-87be-0b27-155b-b44130c67e84
* Version Independent ID: c90633f5-22b9-f7dd-fd08-c9affc251dd4
* Content: [Splash Screen - Xamarin](https://docs.microsoft.com/en-us/xamarin/android/user-interface/splash-screen)
* Content Source: [docs/android/user-interface/splash-screen.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/android/user-interface/splash-screen.md)
* Product: **xamarin**
* GitHub Login: @mgmclemore
* Microsoft Alias: **mamcle**

**Comment by mgmclemore** [comment]
Hi @ma17961363, unfortunately we can't answer specific questions here; your best bet is to visit https://developercommunity.visualstudio.com/spaces/8/index.html to get help. (Also, it looks like the answer to your specific question has been provided [here](https://stackoverflow.com/questions/50714975/changing-xamarin-android-launcher-theme-that-even-applicable-to-preview-window).)
