### ISSUE TITLE
Dead link "Including a NuGet in your Project"

### ISSUE THREAD

**Issue by rarrarrarr** [MicrosoftDocs/xamarin-docs#383]
In the `Related Links` section, the third link "Including a NuGet in your Project" links to https://docs.microsoft.com/en-us/visualstudio/mac/nuget-walkthrough/index.md, which is a dead link.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 41c84374-f2c0-0c70-5acf-15f51e6075ae
* Version Independent ID: 64d29811-909e-4ac9-9ecc-a01e46cdbbb5
* Content: [Manually Creating NuGet Packages for Xamarin - Xamarin](https://docs.microsoft.com/en-us/xamarin/cross-platform/app-fundamentals/nuget-manual)
* Content Source: [docs/cross-platform/app-fundamentals/nuget-manual.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/cross-platform/app-fundamentals/nuget-manual.md)
* Product: **xamarin**
* GitHub Login: @asb3993
* Microsoft Alias: **amburns**

**Comment by bradumbaugh** [comment]
Thanks @rarrarrarr - I put together a fix for this. Should be published soon. Appreciate the help!
