### ISSUE TITLE
Step 18 outdated

### ISSUE THREAD

**Issue by HarlowBurgess** [MicrosoftDocs/xamarin-docs#384]
Visual Studio 15.7.3 no longer has Add (to iOS project) &gt; New Item... &gt; Visual C# &gt; Code &gt; Class. It is now under Add &gt; New Item... &gt; *Apple* &gt; Code &gt; Class.

Note: "Add (to iOS project) &gt; Class..." would have been a simpler way to do this and, one would think, less likely to change across VS versions, but it is actually broken in 15.7.3 (probably because of the change from "Visual C#" to "Apple"), but I will add that to Product Feedback.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2de3e72c-8948-4dd5-e37f-9cf81e62c127
* Version Independent ID: 7b7c5c7f-4102-8e91-fbe6-7d21fcc8f5be
* Content: [Xamarin.Forms Quickstart - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/get-started/hello-xamarin-forms/quickstart?tabs=vswin)
* Content Source: [docs/xamarin-forms/get-started/hello-xamarin-forms/quickstart.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/get-started/hello-xamarin-forms/quickstart.md)
* Product: **xamarin**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
I've fixed this in a forthcoming update.
