### ISSUE TITLE
Deprecated Value "fill_parent"

### ISSUE THREAD

**Issue by khabubu** [MicrosoftDocs/xamarin-docs#387]
I just wanted to give a heads up that since the values in layout_width and height have the value of "fill_parent" isn't it now advisable to use "match_parent" since fill_parent is deprecated 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 55fad6d6-46c2-60e6-5071-e8f33473930f
* Version Independent ID: 60057c47-79a4-336b-e50e-84198c7210cc
* Content: [LinearLayout - Xamarin](https://docs.microsoft.com/en-us/xamarin/android/user-interface/layouts/linear-layout)
* Content Source: [docs/android/user-interface/layouts/linear-layout.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/android/user-interface/layouts/linear-layout.md)
* Product: **xamarin**
* GitHub Login: @mgmclemore
* Microsoft Alias: **mamcle**

**Comment by mgmclemore** [comment]
Hi @khabubu, thank you for the feedback! That topic has been updated and the changes should be published soon.
