### ISSUE TITLE
Error : No resource found that matches the given name (at 'icon' with value '@drawable/icon')

### ISSUE THREAD

**Issue by mikegordon** [MicrosoftDocs/xamarin-docs#388]
If you run into this error when compiling the Phoneword.Android project, edit the MainActivity.cs file and replace "@drawable/icon" with "@mipmap/icon".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2de3e72c-8948-4dd5-e37f-9cf81e62c127
* Version Independent ID: 7b7c5c7f-4102-8e91-fbe6-7d21fcc8f5be
* Content: [Xamarin.Forms Quickstart - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/get-started/hello-xamarin-forms/quickstart?tabs=vswin)
* Content Source: [docs/xamarin-forms/get-started/hello-xamarin-forms/quickstart.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/get-started/hello-xamarin-forms/quickstart.md)
* Product: **xamarin**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by mikegordon** [comment]
Replace (AT)drawable/icon with (AT)mipmap/icon in MainActivity.cs.

**Comment by davidbritch** [comment]
I've fixed this in a forthcoming update.
