### ISSUE TITLE
SetWatchFaceStyle.Builder.Set<property>(value) is obsolete

### ISSUE THREAD

**Issue by varyamereon** [MicrosoftDocs/xamarin-docs#390]
In the Implement the Engine OnCreate Method section, the class SetWatchFaceStyle is used. The methods described appear to be deprecated in Visual Studio.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7d9ff426-b104-f601-851c-f5839b12f85f
* Version Independent ID: 86baed37-7896-4f4a-0859-cb07fafa7d53
* Content: [Creating a Watch Face - Xamarin](https://docs.microsoft.com/en-gb/xamarin/android/wear/platform/creating-a-watchface?tabs=vswin)
* Content Source: [docs/android/wear/platform/creating-a-watchface.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/android/wear/platform/creating-a-watchface.md)
* Product: **xamarin**
* GitHub Login: @mgmclemore
* Microsoft Alias: **mamcle**

**Comment by mgmclemore** [comment]
Hi @varyamereon, thanks for the feedback! Wear 2.0 has deprecated a few methods since this topic since was written. I've added a task to our backlog to have this topic updated to explain the Wear 2.0 way to create a watch face.
