### ISSUE TITLE
Attribute already declared

### ISSUE THREAD

**Issue by docen67** [MicrosoftDocs/xamarin-docs#391]
I'm following the instructions correctly but aparently there is a problem with the schemas in xamarin visual studio.can you help me?
"You can see the image here"
&lt;a href="http://es.tinypic.com?ref=2zdujir" target="_blank"&gt;&lt;img src="http://i68.tinypic.com/2zdujir.jpg" border="0" alt="Image and video hosting by TinyPic"&gt;&lt;/a&gt;

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 077a373a-710a-4514-ba04-dee36309d7b3
* Version Independent ID: f8357c4d-8711-457a-3577-cce29464b51e
* Content: [Replacing the Action Bar - Xamarin](https://docs.microsoft.com/en-us/xamarin/android/user-interface/controls/tool-bar/replacing-the-action-bar)
* Content Source: [docs/android/user-interface/controls/tool-bar/replacing-the-action-bar.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/android/user-interface/controls/tool-bar/replacing-the-action-bar.md)
* Product: **xamarin**
* GitHub Login: @mgmclemore
* Microsoft Alias: **mamcle**

**Comment by mgmclemore** [comment]
Hi @docen67, thanks for your feedback!  Unfortunately this is a [known issue](https://developercommunity.visualstudio.com/content/problem/101707/android-layout-attribute-is-not-declared.html) that has not yet been resolved (there's nothing we can add to the topic to work around this problem). Hopefully it will be fixed soon.
