### ISSUE TITLE
LiveReload does not work on simple project

### ISSUE THREAD

**Issue by prapicault** [MicrosoftDocs/xamarin-docs#393]
Hello,
I've installed the VS extension (version 0.3.27) on VS Enterprise 15.7.3, created a new project (blank app with .net standard), added the nuget package to the project, deployed the application to a local android emulator, saw the "connected to localhost:1883" message on top of my xaml editor, and yet when I change the xaml file (e.g. change the text in the labe), the change is not reflected in the running app. 

Could you please indicate if this feature is still supported?

Thanks

Pascal

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e40394ca-9a55-d9b5-d427-7c2a2c00cfc8
* Version Independent ID: 5a5c17e2-a683-88f6-07a9-2002e814d54c
* Content: [Live Reload - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/xaml/live-reload)
* Content Source: [docs/xamarin-forms/xaml/live-reload.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/xaml/live-reload.md)
* Product: **xamarin**
* GitHub Login: @pierceboggan
* Microsoft Alias: **piboggan**

**Comment by pierceboggan** [comment]
Hi @prapicault,

Live Reload is currently in preview, and is definitely still supported and being worked on (it was only introduced last month).

I'm adding @kzu who can help diagnose exactly what is happening here.

Thanks,
Pierce Boggan

**Comment by pierceboggan** [comment]
Better yet - send me an email at pierce.boggan@microsoft.com and we'll investigate.

**Comment by ronyelago** [comment]
I was able to install with the Install-package command Xamarin.LiveReloa but it is not working with the Genymotion emulator. Does anyone know how to configure?

**Comment by kzu** [comment]
@ronyelago you can also chat with us at https://gitter.im/xamarin/live-reload to figure out what's going on. Thanks!
