### ISSUE TITLE
Great and Concise Tutorials

### ISSUE THREAD

**Issue by techmanDAV** [MicrosoftDocs/xamarin-docs#394]
I am new to iOS development. I have been using Visual Studio for web development for over 20 years. I did the quickstart for Hello iOS and was able to develop my first iOS app.  Thank you and keep up the good work!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 47bac7e2-616d-1b05-4b48-01b4f7170e7a
* Version Independent ID: eccbc16d-b8f0-2ad7-6597-b89965f07795
* Content: [Hello, iOS – Deep Dive - Xamarin](https://docs.microsoft.com/en-us/xamarin/ios/get-started/hello-ios/hello-ios-deepdive?tabs=vsmac)
* Content Source: [docs/ios/get-started/hello-ios/hello-ios-deepdive.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/ios/get-started/hello-ios/hello-ios-deepdive.md)
* Product: **xamarin**
* GitHub Login: @bradumbaugh
* Microsoft Alias: **brumbaug**

**Comment by bradumbaugh** [comment]
Hi @techmanDAV – thanks for the kind words! Glad you're having success getting started with iOS development using Xamarin. Please be sure to let us know if you find anything unclear in the docs!
