### ISSUE TITLE
other gestures?

### ISSUE THREAD

**Issue by echuck66** [MicrosoftDocs/xamarin-docs#40]
Are there any plans to add other gestures such as swipe? I see a pull request in the GitHub repository, but it appears to be held up by a spaces vs. tabs issue on a unit test class. (not sure I'm following the comments correctly on this or not)

Anyway, I would think a swipe gesture recognizer would be pretty standard on most mobile devices by this point.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b1d849b9-e4a6-1507-4532-26daa94ffaae
* Version Independent ID: 07ae51c4-93fe-377e-ad12-41246a6f2e10
* Content: [Gestures - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/gestures/)
* Content Source: [docs/xamarin-forms/app-fundamentals/gestures/index.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/app-fundamentals/gestures/index.md)
* Service: **unspecified**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Yes, the swipe gesture recogniser you've alluded to will be included in Xamarin.Forms, and is currently scheduled for vNext+1.

There are also plans for the Q3 release to include a long press gesture, and a new custom gesture implementation that doesn't require platform code.

Of course, dates are subject to change.

**Comment by weitzhandler** [comment]
@davidbritch it's so nice to read your comment, and besides I'm now discovering that docs fired the annoying LiveFyre comments plug-in. Finally!
