### ISSUE TITLE
Great Post!

### ISSUE THREAD

**Issue by abhijitv** [MicrosoftDocs/xamarin-docs#400]
I tried the ICommand way and worked for me right away

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1e56a604-3af6-80e9-b9df-382e3102a098
* Version Independent ID: 29cc319e-2736-013c-7934-b4335eb8242d
* Content: [Adding a Tap Gesture Gesture Recognizer - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/gestures/tap)
* Content Source: [docs/xamarin-forms/app-fundamentals/gestures/tap.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/app-fundamentals/gestures/tap.md)
* Product: **xamarin**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @abhijitv 

Thanks for the feedback and glad it worked for you!

**Comment by abhijitv** [comment]
Sure ,.thanks so much!
    On Tuesday, 19 June 2018, 9:51:59 PM GMT+8, David Britch <notifications@github.com> wrote:  
 
 
Hi @abhijitv

Thanks for the feedback and glad it worked for you!
