### ISSUE TITLE
Cannot find documentation on how to add files to Xamarin.* projects (like what the contentFiles folder does)

### ISSUE THREAD

**Issue by dfoulk** [MicrosoftDocs/xamarin-docs#403]
I'm going to explain our scenario so that you can understand what appears to be missing from the NuGet documentation...

We are trying to create a NuGet package using a .NET Standard 2.0 project. With this generated NuGet package, we want to update 'styles.xml' and add a file named 'colors.xml' in a Xamarin.Android project (in the Xamarin.Forms solution that will be installing our NuGet package). Similar to this functionality: https://docs.microsoft.com/en-us/nuget/reference/nuspec#package-folder-structure

That being said; we cannot find any documentation on the following:
- How do we create and populate the contentFiles folder when using a .NET Standard 2.0 library?
    - Do we create a contentFiles folder in our .NET Standard Library (the source of our NuGet package)?
    - Do we somehow create the folder with some MSBuild tag in our .csproj file?
- Do we need to use a .nuspec file (instead of the convenient '.NET Standard Project &gt; Package window) to generate a NuGet package if we want to insert/update files in the installing project?
- Should the resulting contentFiles path be '/contentFiles/any/monoandroid/Resources/values/styles.xml.transform' & '/contentFiles/any/monoandroid/Resources/values/colors.xml.transform' (getting the transform idea from here: https://docs.microsoft.com/en-us/nuget/create-packages/source-and-config-file-transformations#xml-transforms)

All-in-all it has proven very difficult to find the necessary documentation for us because we are new to NuGet package creation. We don't even know what we need to search the docs for, thus finding the applicable docs is darn near impossible.

It would be great if there was a more explanatory (beginner-friendly) doc for how to use contentFiles in packages targeting Xamarin when using .NET Standard to generate said packages.

Thank you,
-Derek

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 41c84374-f2c0-0c70-5acf-15f51e6075ae
* Version Independent ID: 64d29811-909e-4ac9-9ecc-a01e46cdbbb5
* Content: [Manually Creating NuGet Packages for Xamarin - Xamarin](https://docs.microsoft.com/en-us/xamarin/cross-platform/app-fundamentals/nuget-manual)
* Content Source: [docs/cross-platform/app-fundamentals/nuget-manual.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/cross-platform/app-fundamentals/nuget-manual.md)
* Product: **xamarin**
* GitHub Login: @asb3993
* Microsoft Alias: **amburns**

**Comment by bradumbaugh** [comment]
Hi @dfoulk, unfortunately I don't have an immediate answer for you. I have added a note in our backlog to revisit this topic to see what we can add regarding ContentFiles – thank you for the suggestion. 

In the meantime, you might try posting on [Developer Community](https://developercommunity.visualstudio.com/spaces/8/index.html) or the [Xamarin Forums](https://forums.xamarin.com/) for support.
