### ISSUE TITLE
Works perfectly

### ISSUE THREAD

**Issue by nhwilly** [MicrosoftDocs/xamarin-docs#404]
Made my month!  Thanks, Microsoft!!!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e40394ca-9a55-d9b5-d427-7c2a2c00cfc8
* Version Independent ID: 5a5c17e2-a683-88f6-07a9-2002e814d54c
* Content: [Live Reload - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/xaml/live-reload)
* Content Source: [docs/xamarin-forms/xaml/live-reload.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/xaml/live-reload.md)
* Product: **xamarin**
* GitHub Login: @pierceboggan
* Microsoft Alias: **piboggan**

**Comment by IbrahimElshafey** [comment]
Does the App class must be inherited directly from "Xamarin.Forms.Application" class?

**Comment by davidbritch** [comment]
Hi @nhwilly 

Thanks, for the feedback. Glad you like it.
