### ISSUE TITLE
OAuth redirection from the browser tab to android app is not working 

### ISSUE THREAD

**Issue by xamarinrk1** [MicrosoftDocs/xamarin-docs#405]
I am using custom OAuth identity provider and also used the above document but after clicking the IDP's authorize button its not going to OnAuthComplete event it simply stays at IDP's Authorization screen. I am using the following redirectUrl scheme,
 ex: com.xxx.xamarin.oauth:/oauth2redirect  (android project package name : / oauth2redirect)

I am seeing NullReferenceException for AuthenticationState.Authenticator used in CustomUrlSchemeInterceptorActivity
            //AuthenticationState.Authenticator.OnPageLoading(uri);

so I removed the above and calling static variable Authenticator directly from OAuthAuthentication 
            Authenticator.OnPageLoading(uri)
     
copied all the code that I am trying, any help would be greatly appreciated and thanks in advance.

-------------------------
AuthenticationState.cs
-------------------------
using System;
using System.Collections.Generic;
using System.Text;
using Xamarin.Auth;
 
namespace Xam2OAuthDemo
{
    public class AuthenticationState
    {
        public static OAuth2Authenticator Authenticator;
    }
}

-----------------
MainPage.xaml
-----------------
&lt;?xml version="1.0" encoding="utf-8" ?&gt;
&lt;ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:local="clr-namespace:Xam2OAuthDemo"
             x:Class="Xam2OAuthDemo.MainPage"&gt;

    &lt;StackLayout&gt;
        &lt;!-- Place new controls here --&gt;
    	&lt;Label Text="Welcome to Xamarin.Forms!" 
           HorizontalOptions="Center"
           VerticalOptions="CenterAndExpand" /&gt;
        &lt;Button x:Name="Login" Text="Login" Clicked="Login_Clicked" /&gt;
    &lt;/StackLayout&gt;

&lt;/ContentPage&gt;

--------------------
MainPage.xaml.cs
--------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Xamarin.Forms;

namespace Xam2OAuthDemo
{
	public partial class MainPage : ContentPage
	{
		public MainPage()
		{
			InitializeComponent();
		}

                private void Login_Clicked(object sender, EventArgs e)
                {
                       OAuthAuthentication.ConfigureOAuthAuthenticator();

                       var presenter = new Xamarin.Auth.Presenters.OAuthLoginPresenter();
                       presenter.Login(OAuthAuthentication.Authenticator);
                }
    }
}

--------------------------
OAuthAuthentication.cs
--------------------------
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Text;
using Xamarin.Auth;

namespace Xam2OAuthDemo
{
    public static class OAuthAuthentication
    {        
        public static OAuth2Authenticator Authenticator;
        private static string clientId = "XXXXXXXXX";
        private static string clientSecret = "XXXXXXXXXX";
        private static string redirectUri = "com.xyz.xamarin.oauth:/oauth2redirect";
        private static string authorizeUrl = "https://xxxx.xx.xxx/xxxws/XXXXX/oidc/authorize";
        private static string accesstokenUrl = "https://xxxx.xx.xxx/xxxws/XXXXX/oidc/token";
        public static string scope = "email Contact profile";

        public static void ConfigureOAuthAuthenticator()
        {
            Authenticator = new OAuth2Authenticator(
                clientId, clientSecret,
                scope,
                new Uri(authorizeUrl),
                new Uri(redirectUri),
                new Uri(accesstokenUrl),
                null, true
                );

            Authenticator.Completed += OnAuthCompleted;
            Authenticator.Error += OnAuthError;
        }

        private static async void OnAuthCompleted(object sender, AuthenticatorCompletedEventArgs e)
        {
            if (Authenticator != null)
            {
                Authenticator.Completed -= OnAuthCompleted;
                Authenticator.Error -= OnAuthError;
            }

            if (e.IsAuthenticated)
            {
                var httpClient = new HttpClient();
                httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue(e.Account.Properties["token_type"], e.Account.Properties["access_token"]);
                var json = await httpClient.GetStringAsync("https://xxxx.xx.xxx/xxxws/XXXXX/oidc/token");
                var email = JsonConvert.DeserializeObject&lt;string&gt;(json);                
            }
        }

        private static void OnAuthError(object sender, AuthenticatorErrorEventArgs e)
        {
            if (Authenticator != null)
            {
                Authenticator.Completed -= OnAuthCompleted;
                Authenticator.Error -= OnAuthError;
            }

        }

        public static void OnPageLoading(Uri uri)
        {
            Authenticator.OnPageLoading(uri);
        }
    }
}

-----------------
MainActivity.cs
-----------------
using System;
using Android.App;
using Android.Content.PM;
using Android.Runtime;
using Android.Views;
using Android.Widget;
using Android.OS;

namespace Xam2OAuthDemo.Droid
{
    [Activity(Label = "Xam2OAuthDemo", Icon = "@mipmap/icon", Theme = "@style/MainTheme", MainLauncher = true, ConfigurationChanges = ConfigChanges.ScreenSize | ConfigChanges.Orientation)]
    public class MainActivity : global::Xamarin.Forms.Platform.Android.FormsAppCompatActivity    
    {
        protected override void OnCreate(Bundle bundle)
        {
            TabLayoutResource = Resource.Layout.Tabbar;
            ToolbarResource = Resource.Layout.Toolbar;

            base.OnCreate(bundle);

            global::Xamarin.Forms.Forms.Init(this, bundle);
            global::Xamarin.Auth.Presenters.XamarinAndroid.AuthenticationConfiguration.Init(this, bundle);      
            
            LoadApplication(new App());
        }        
    }
}

-------------------------------------
CustomUrlSchemeInterceptorActivity.cs
-------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Android.App;
using Android.Content;
using Android.Content.PM;
using Android.OS;
using Android.Runtime;
using Android.Views;
using Android.Widget;
using static Xam2OAuthDemo.OAuthAuthentication;

namespace Xam2OAuthDemo.Droid
{
    [Activity(Label = "CustomUrlSchemeInterceptorActivity", NoHistory = true, LaunchMode = LaunchMode.SingleTop)]
    [IntentFilter(
       new[] { Intent.ActionView },
       Categories = new[] { Intent.CategoryDefault, Intent.CategoryBrowsable },
       DataSchemes = new[] { "com.xxxx.xamarin.oauth" }, 
       DataPath = "/oauth2redirect")]
    public class CustomUrlSchemeInterceptorActivity : Activity
    {
        protected override void OnCreate(Bundle savedInstanceState)
        {
            base.OnCreate(savedInstanceState);

            // Convert Android.Net.Url to Uri
            var uri = new Uri(Intent.Data.ToString());
            
            // Load redirectUrl page
            //AuthenticationState.Authenticator.OnPageLoading(uri);
            Authenticator.OnPageLoading(uri);
            //MainActivity.Auth?.OnPageLoading(uri);

            Finish();
        }
    }
}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aa8bb9e0-5898-0d11-0213-fd4d8c8d0297
* Version Independent ID: 2f46e1f7-164f-2f32-70c0-f28919d16c5c
* Content: [Authenticating Users with an Identity Provider - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/data-cloud/authentication/oauth)
* Content Source: [docs/xamarin-forms/data-cloud/authentication/oauth.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/data-cloud/authentication/oauth.md)
* Product: **xamarin**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by xamarinrk1** [comment]
Thanks David, appreciate your response. I found the real problem as the Identity Provider in our scenario doesn't like redirectUrl pattern when requesting for access token. The same redirect Url pattern is fine when requesting for Authorization Code. Once we figured that out we made changes and it is working fine now. Thanks again.

**Comment by RobinLeblond** [comment]
I'm having the same problem, how do you implement the corrective ?

**Comment by XamarinIOT** [comment]
Hello Davide , I am having same problem after authentication it will redirect to google.com !
it does not return to my application , only after I close google.com it will return to my application logged out  !

**Comment by nosmalldreams** [comment]
FYI to those who posted in this thread, this solved the issue with the browser not closing on Android after authentication for me: https://github.com/xamarin/Xamarin.Auth/issues/226
