### ISSUE TITLE
How to get Image file name

### ISSUE THREAD

**Issue by thanguc** [MicrosoftDocs/xamarin-docs#408]
Please guide us how to get Filestream instead of Stream to get image file name.
Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 22cd76be-2702-6a58-498c-a84c723d9588
* Version Independent ID: 9f98549e-ff3d-5b8d-67e6-523834c4dd6d
* Content: [Picking a Photo from the Picture Library - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/dependency-service/photo-picker)
* Content Source: [docs/xamarin-forms/app-fundamentals/dependency-service/photo-picker.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/app-fundamentals/dependency-service/photo-picker.md)
* Product: **xamarin**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @thanguc - this repository is only for issues specifically related to the documentation. For support or to report bugs, please take a look at [Developer Community](https://developercommunity.visualstudio.com/spaces/8/index.html). Thank you!
