### ISSUE TITLE
AlarmManager hyperlink is broken

### ISSUE THREAD

**Issue by a-v-kalabuhov** [MicrosoftDocs/xamarin-docs#41]
I got 404 error.
https://developer.android.com/reference/android/app/AlarmManager

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: faf37247-a5cb-c988-7577-a50e0cd6a0c9
* Version Independent ID: 5c6955b2-8466-0a64-3981-bc8189569cdf
* Content: [Firebase Job Dispatcher - Xamarin](https://docs.microsoft.com/en-us/xamarin/android/platform/firebase-job-dispatcher)
* Content Source: [docs/android/platform/firebase-job-dispatcher.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/android/platform/firebase-job-dispatcher.md)
* Service: **unspecified**
* GitHub Login: @mgmclemore
* Microsoft Alias: **mamcle**

**Comment by mgmclemore** [comment]
Thanks @a-v-kalabuhov, the link is fixed (should be propagated soon).
