### ISSUE TITLE
Please document Device Guard limitation

### ISSUE THREAD

**Issue by mfeingol** [MicrosoftDocs/xamarin-docs#411]
The Hyper-V support doesn't appear to work when Device Guard is enabled. Please confirm and document. Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4e37d642-2051-8d70-9968-dfb484122a6a
* Version Independent ID: 178ea80c-2b99-0c44-eeb6-9db319439b33
* Content: [Hardware Acceleration for Emulator Performance - Xamarin](https://docs.microsoft.com/en-us/xamarin/android/get-started/installation/android-emulator/hardware-acceleration?tabs=vswin)
* Content Source: [docs/android/get-started/installation/android-emulator/hardware-acceleration.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/android/get-started/installation/android-emulator/hardware-acceleration.md)
* Product: **xamarin**
* GitHub Login: @mgmclemore
* Microsoft Alias: **mamcle**

**Comment by mgmclemore** [comment]
Hello @mfeingol: yes, Hyper-V support doesn't work when Device Guard is enabled -- this is documented [here](https://docs.microsoft.com/en-us/xamarin/android/deploy-test/debugging/android-sdk-emulator/troubleshooting?tabs=vswin#disabling-device-guard). We'll update the hardware acceleration topic to also mention this (and link to this troubleshooting topic so it's easier to find). Thanks for your feedback!

**Comment by mfeingol** [comment]
Thanks for doing that. I saw the article you mentioned and it tipped me off to the potential issue. But it certainly wasn't obvious that in addition to nerfing HAXM, it would also nerf the new Hyper-V support.
