### ISSUE TITLE
Missing documentation for error case

### ISSUE THREAD

**Issue by taimila** [MicrosoftDocs/xamarin-docs#413]
It would be good to specify what happens if value with key is not found when `SecureStorage.GetAsync(key)` is called. Do I get null, empty string or perhaps some type of exception?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: da75050f-bfda-4792-40d9-b9a25d649d3e
* Version Independent ID: 5c44f996-765b-f6e4-c807-9446c534d50b
* Content: [Xamarin.Essentials: Secure Storage - Xamarin](https://docs.microsoft.com/en-us/xamarin/essentials/secure-storage?context=xamarin%2Fxamarin-forms&tabs=android)
* Content Source: [docs/essentials/secure-storage.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/essentials/secure-storage.md)
* Product: **xamarin**
* GitHub Login: @Redth
* Microsoft Alias: **jodick**

**Comment by taimila** [comment]
Checked it from code. Seems to throw `ArgumentNullException`

**Comment by bradumbaugh** [comment]
Hi @taimila, thanks for calling this out. I've filed [an issue](https://github.com/MicrosoftDocs/xamarin-docs/issues/413) over on the Xamarin.Essentials repo. Once there is a definitive direction there I will update the doc. Thanks again!

**Comment by bradumbaugh** [comment]
Hi @taimila, thanks again for calling this out. The [Xamarin.Essentials 0.8.0-preview release](https://github.com/xamarin/Essentials/releases/tag/0.8.0-preview) includes [a fix](https://github.com/xamarin/Essentials/pull/320) such that `GetAsync` returns `null` for keys with no value on all platforms. I've also updated the docs to call this out, and the change should be published soon. Appreciate your help in improving the library and the docs!
