### ISSUE TITLE
Is there source code available for this?

### ISSUE THREAD

**Issue by AuriR** [MicrosoftDocs/xamarin-docs#414]
Can you post the code for this example, please? It looks like some pieces are missing, such as CustomMKAnnotationView and GetCustomPin().

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 591d1079-dec9-5797-eb4f-4d11b56fcbd9
* Version Independent ID: 0169a2c9-a004-d5fd-7a24-855664f2d8b5
* Content: [Customizing a Map Pin - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/custom-renderer/map/customized-pin#feedback)
* Content Source: [docs/xamarin-forms/app-fundamentals/custom-renderer/map/customized-pin.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/app-fundamentals/custom-renderer/map/customized-pin.md)
* Product: **xamarin**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Looks like you found the sample :)

**Comment by AuriR** [comment]
Nope. I thought I did, and replied to soon. Clicking "View on GitHub" only brings you to the "source" for the article itself, not the code that was discussed. Am I missing something obvious? :)

**Comment by AuriR** [comment]
And there it is... right when I hit comment. Please, send me some coffee. :) https://github.com/xamarin/xamarin-forms-samples/tree/master/CustomRenderers/Map/Pin

Can you add the classes / missing code to the article, though, please?
