### ISSUE TITLE
Sorry, just saw the hard to see link for View on GitHub :) 

### ISSUE THREAD

**Issue by AuriR** [MicrosoftDocs/xamarin-docs#415]
Please disregard #414, thanks! It would be helpful if the link was at the top of the page, too.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 591d1079-dec9-5797-eb4f-4d11b56fcbd9
* Version Independent ID: 0169a2c9-a004-d5fd-7a24-855664f2d8b5
* Content: [Customizing a Map Pin - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/custom-renderer/map/customized-pin#feedback)
* Content Source: [docs/xamarin-forms/app-fundamentals/custom-renderer/map/customized-pin.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/app-fundamentals/custom-renderer/map/customized-pin.md)
* Product: **xamarin**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by AuriR** [comment]
Just kidding... there's still no code... That was a link to the docs. I should have clicked the link first. Would be helpful to have source code because it appears code is missing. It looks like you closed a similar entry, but I still don't see the option.

**Comment by davidbritch** [comment]
What code do you think is missing?

The Related Links section at the bottom of the doc links to the sample, which contains complete code.

**Comment by AuriR** [comment]
I hear ya. I'm saying it's less work for someone to follow the example if all the code referenced is in the code samples in the article. For example, GetCustomPin() isn't in there. Maybe something that would help would provide the sample source code link at the beginning of the article, since not all the code is included in the article text itself.

**Comment by davidbritch** [comment]
Understood. Thanks for the feedback. There are plans afoot to link to the sample near the top of each guide.

**Comment by AuriR** [comment]
Awesome. GREAT article - I didn't say that, and should have. It really helped me out, and will be used in a medical app to help save lives :)
