### ISSUE TITLE
Doesn't seem to work in 2018 Xamarin.Forms 3

### ISSUE THREAD

**Issue by tlhintoq** [MicrosoftDocs/xamarin-docs#418]
This documentation is 2 years old. There are countless StackOverflow threads about needing to including `BindingContext` as part of the path off `Parent` but as of June2018 I can't seem to find the magic combination syntax that makes this work.

I'm trying to include a `PageHeader` control on each page via ControlTemplate - but can't make any of the binding on the PageHeaderContentView actually bind to properties on the ViewModel assigned to the Page.  Its as if the controls in the ControlTemplate aren't receiving the BindingContext from the parent view.

                    &lt;controls:PgHeader Description="{TemplateBinding Parent.BindingContext.Description}" Grid.Row="0" /&gt;

        #region Description (Bindable string)
        public static readonly BindableProperty DescriptionProperty =
            BindableProperty.Create(propertyName: "Description",
                                    returnType: typeof(string),
                                    declaringType: typeof(ViewBase),
                                    defaultValue: "Description");
        public string Description
        {
            get { return (string)GetValue(DescriptionProperty); }
            set { SetValue(DescriptionProperty, value); }
        }
        #endregion Description (Bindable string)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cab55939-7f2e-1342-116b-b59272c5a891
* Version Independent ID: a62f69b7-5a96-2d27-e6d2-47a6c17ad7c7
* Content: [Binding from a Xamarin.Forms ControlTemplate - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/templates/control-templates/template-binding)
* Content Source: [docs/xamarin-forms/app-fundamentals/templates/control-templates/template-binding.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/app-fundamentals/templates/control-templates/template-binding.md)
* Product: **xamarin**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @tlhintoq 

You're correct that the `BindingContext` needs to be set to an instance of the class containing the properties you're binding to. See the [sample](https://developer.xamarin.com/samples/xamarin-forms/templates/controltemplates/simplethemewithtemplatebindingandviewmodel/) for more info.
