### ISSUE TITLE
Following instructions (step-by-step) results in launch screen without image on iOS

### ISSUE THREAD

**Issue by dfoulk** [MicrosoftDocs/xamarin-docs#419]
After following these instructions (exactly), I am shown a launch screen that does not contain my image.

What the instructions should result in:
A simple launch screen that displays your custom image (in place of the Xamagon icon).

Actual result:
A blank screen whose background color is set properly, but no image displayed.

Before you jump to the conclusion that I am just messing up constraints on the image (thus it is not rendered in the expected place), let me say that I have created a few of these launch screens- but after not having luck (initially) using this document, I have been forced to use this video for direction instead:

[Xamarin iOS splash screen](https://www.youtube.com/watch?v=ZY87V4o8qNc)

I'm not sure why this alternate method works and why this document's method does not work is beyond me. The main difference appears to be that in the video above, we add a PNG into the **Resources** directory (for use in the storyboard), as opposed to using an image from an Asset Catalog. Shouldn't both ways work?

Anyways, please create a new Xamarin.Forms app using the latest version of VS2017 and try to use this documentation to create a custom launch screen (complete with custom image and background color). You'll find that something is missing...

Thank you,
-Derek

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5eaa7bed-8577-a8d2-06e9-3909ac8a4520
* Version Independent ID: e31b68bb-76de-6c63-883b-b1fd386cf001
* Content: [Launch Screens for Xamarin.iOS Apps - Xamarin](https://docs.microsoft.com/en-us/xamarin/ios/app-fundamentals/images-icons/launch-screens?tabs=vswin#managing-launch-screens-with-storyboards)
* Content Source: [docs/ios/app-fundamentals/images-icons/launch-screens.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/ios/app-fundamentals/images-icons/launch-screens.md)
* Product: **xamarin**
* GitHub Login: @bradumbaugh
* Microsoft Alias: **brumbaug**

**Comment by bradumbaugh** [comment]
Hi @dfoulk. I gave this a shot and was able to create a launch screen storyboard with an image for a Xamarin.Forms app from Visual Studio 2017. At first I did see the issue you mentioned, where the image didn't show up; however, manually deleting the app and then rebooting the simulator resolved the issue. 

Searching around a bit seems to indicate that Xcode issues sometimes face this issue as well, which suggests to me that this isn't Xamarin-specific. That said, please report this on [Developer Community](https://developercommunity.visualstudio.com/spaces/8/index.html) for support.

**Comment by dfoulk** [comment]
@bradumbaugh Thank you for your reply. I did notice that creating a new app and simply running it on iOS (before editing anything) also shows a blank screen (no image). It should show the Icon60.png image. Oh well, thanks man!

**Comment by LeonSweden** [comment]
This is still the case with VS 2019.
Though does @bradumbaugh coment resolve.
