### ISSUE TITLE
Regarding Screenlock functionality

### ISSUE THREAD

**Issue by 07101994** [MicrosoftDocs/xamarin-docs#421]
I tried Screenlock in one of my Xamarin.Forms Android app and added the code described in docs to keep the screen but it seems it doesn't keep the screen active. Also I noticed that even after calling ScreenLock.RequestActive() method, the ScreenLock.IsActive flag still remains false. 

Let me know if I am missing something.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e90e3c57-988a-f47d-61e1-4e6995829d2d
* Version Independent ID: a7e72751-83c2-e5ff-415d-c89344ae623d
* Content: [Xamarin.Essentials: Screen Lock - Xamarin](https://docs.microsoft.com/en-us/xamarin/essentials/screen-lock?context=xamarin/xamarin-forms)
* Content Source: [docs/essentials/screen-lock.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/essentials/screen-lock.md)
* Product: **xamarin**
* GitHub Login: @jamesmontemagno
* Microsoft Alias: **jamont**

**Comment by jamesmontemagno** [comment]
Could you open an issue: https://github.com/xamarin/Essentials/issues and provide a sample project if possible for us to test.

**Comment by 07101994** [comment]
@jamesmontemagno - Thanks for your reply. It seems I have missed calling Init method on application start due to which the ScreenLock was not working expected. After adding Init method call on application start it's working fine. We can close this issue.

**Comment by jamesmontemagno** [comment]
I'll open an issue though to actually throw an exception perhaps.

**Comment by 07101994** [comment]
@jamesmontemagno - Thanks, can you please provide the created issue link, so that I will try to create a pull request for the same.

Once again thanks for your good work.

**Comment by topgenorth** [comment]
Closing the issue, see related Essentials issue provided by @jamesmontemagno
