### ISSUE TITLE
Is this identical to Xamarin.Forms.Device.BeginInvokeOnMainThread?

### ISSUE THREAD

**Issue by mfeingol** [MicrosoftDocs/xamarin-docs#422]
Presumably it is, so it might be worth mentioning that.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8708011b-cd22-b26b-bfe3-271e46d18815
* Version Independent ID: 0f503018-bfdf-7e77-6193-b010bb2d2746
* Content: [Xamarin.Essentials Platform - Xamarin](https://docs.microsoft.com/en-us/xamarin/essentials/platform?content=xamarin/xamarin-forms)
* Content Source: [docs/essentials/platform.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/essentials/platform.md)
* Product: **xamarin**
* GitHub Login: @charlespetzold
* Microsoft Alias: **chape**

**Comment by bradumbaugh** [comment]
Hi @mfeingol – while this method does the same thing, it's not actually calling out to the Xamarin.Forms method. 

However, they are implemented similarly under the hood, as you can see by looking at the [Xamarin.Forms open source repository](https://github.com/xamarin/Xamarin.Forms). For example, here's the [iOS implementation in Xamarin.Forms](https://github.com/xamarin/Xamarin.Forms/blob/master/Xamarin.Forms.Platform.iOS/Forms.cs#L184), and here's the [iOS implementation in Xamarin.Essentials](https://github.com/xamarin/Essentials/blob/master/Xamarin.Essentials/Platform/Platform.ios.cs#L14).

Given that the Essentials library isn't Xamarin.Forms-specific, I don't think it makes sense to call out the similarity here.

Thanks for the comment – appreciate the help in making the docs better.

**Comment by mfeingol** [comment]
Brad: that all makes sense and I was probably unclear with my comment. My main concern is that as a developer using Xamarin Forms I don't know whether I should use this call or `Device.BeginInvokeOnMainThread`. Maybe it doesn't matter, but even that isn't quite clear.

**Comment by bradumbaugh** [comment]
@mfeingol Thanks for the clarification - definitely understand what you're saying now. I'll add a note to the doc indicating that you can use either method. I have a PR ready for this, so it should be published soon. Thanks again for your help!
