### ISSUE TITLE
Minor Typo

### ISSUE THREAD

**Issue by samiam236** [MicrosoftDocs/xamarin-docs#423]
This is an excellent document. I did notice a minor typo in the section "Platform Differences with OnPlatform" where it says "For each onem".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e80791df-0605-587f-74cd-ebc4c9fd0f74
* Version Independent ID: 76736d2a-f450-4607-55b9-e7f547c0c775
* Content: [Part 2. Essential XAML Syntax - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/xaml/xaml-basics/essential-xaml-syntax)
* Content Source: [docs/xamarin-forms/xaml/xaml-basics/essential-xaml-syntax.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/xaml/xaml-basics/essential-xaml-syntax.md)
* Product: **xamarin**
* GitHub Login: @charlespetzold
* Microsoft Alias: **chape**

**Comment by davidbritch** [comment]
Hi @samiam236 

Thanks for pointing out the typo. I've fixed it in a PR that should go live in a day or two.
