### ISSUE TITLE
Push Notification Localization and Resx files.

### ISSUE THREAD

**Issue by ryanlpoconnell** [MicrosoftDocs/xamarin-docs#424]
More information on using Resx files with Localization would be good.

I'm currently working on iOS Push Notifications which will use a payload with localization key values for title etc.  The PCL project already has a resx file... 

So I'm trying to work out if the resx file can be used for remote push notifications received in Background / Not Running states, rather than duplicating the resource entries in Localizable.strings.

Is this possible considering Force-Quit state does not allow App Push Received callbacks to run?

Does Xamarin somehow _compile_ resx files as Localizable.strings file?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 629ae54b-10fe-61ff-6a6e-cb54b5206079
* Version Independent ID: fcb311ea-1552-86e4-d648-5fe7832d863a
* Content: [Localization in Xamarin.iOS - Xamarin](https://docs.microsoft.com/en-us/xamarin/ios/app-fundamentals/localization/)
* Content Source: [docs/ios/app-fundamentals/localization/index.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/ios/app-fundamentals/localization/index.md)
* Product: **xamarin**
* GitHub Login: @bradumbaugh
* Microsoft Alias: **brumbaug**

**Comment by bradumbaugh** [comment]
Thanks, @ryanlpoconnell – I've added this idea to our internal backlog as a potential future doc idea. 

Regarding your question, I don't have an immediate answer for you, but FWIW the resx files are not compiled down to strings files.

Feel free to post on [Developer Community](https://developercommunity.visualstudio.com/spaces/8/index.html) for support.
