### ISSUE TITLE
Does not work. Out of memory exception and once you fix that Android.Views.InflateException: Binary XML file line #1: Binary XML file line #1: Error inflating class android.support.design.widget.TabLayout

### ISSUE THREAD

**Issue by smchughinfo** [MicrosoftDocs/xamarin-docs#428]
The first error is fixed by increasing the android heap size to a number.  You are expected to know the unit and convention or at least be able to find that information somewhere. My visual studio (2017 community) doesn't have the label underneath that tells you what convention to use. Additionally, I wouldn't know what number to use but thankfully a commenter gave the magic number, 1G (can't be 2 because that throws more errors). Right click your Android Project &gt; Properties &gt; Android Options &gt; Advanced &gt; Java Max Heap Size &gt; 1G. https://stackoverflow.com/questions/36835790/getting-outofmemoryexception-in-xamarin

I am guessing the second issue it has is because I'm using a TabbedPage. The error is

Unhandled Exception:

Android.Views.InflateException: Binary XML file line #1: Binary XML file line #1: Error inflating class android.support.design.widget.TabLayout

Since there is no support for UWP I can't really use these themes anyhow.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 711d54ad-842b-2141-95b3-fc71d053dbac
* Version Independent ID: be8e8253-7014-1065-ee9b-27a41d35b1ec
* Content: [Xamarin.Forms Themes - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/themes/index#loadtheme)
* Content Source: [docs/xamarin-forms/user-interface/themes/index.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/themes/index.md)
* Product: **xamarin**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @smchughinfo 

As you've pointed out, Themes is for iOS/Android only, and on top of that is still a pre-release.

The requirement to set the heap size on Android is dependent upon whether you have 32 bit of 64 bit Java installed on your dev machine, and the amount of code and packages in your project.

As for the view inflation error, my gut feeling here is your MainActivity lacks the following lines:

```
TabLayoutResource = Resource.Layout.Tabbar;
ToolbarResource = Resource.Layout.Toolbar;
```
