### ISSUE TITLE
ListView protection level

### ISSUE THREAD

**Issue by RomanV0703** [MicrosoftDocs/xamarin-docs#430]
If ListView is defined through XAML (like "&lt;ListView x:Name="listView"&gt;") it won't be accessible via C# code (like "masterPage.ListView.SelectedItem = null;") unless you set protection level to public (like "&lt;ListView x:Name="listView" x:FieldModifier="public"&gt;".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ec31ee56-e3b9-a70a-a4ef-80fdf58e7249
* Version Independent ID: 766b5774-50bf-f43f-800d-48b5c6c66509
* Content: [Xamarin.Forms Master-Detail Page - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/navigation/master-detail-page)
* Content Source: [docs/xamarin-forms/app-fundamentals/navigation/master-detail-page.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/app-fundamentals/navigation/master-detail-page.md)
* Product: **xamarin**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Thanks for the feedback. I've updated the sample and will get the doc updated.

**Comment by danilkurkin1** [comment]
This is not possible to do in XF at the moment

**Comment by danilkurkin1** [comment]
Sorry, my bad - it is possible
