### ISSUE TITLE
broken links

### ISSUE THREAD

**Issue by birbilis** [MicrosoftDocs/xamarin-docs#432]
two of the links here resulted in 404 errors (the 404 url parameter points to the broken link)
https://developer.xamarin.com/404?link=%2Fapi%2Ftype%2FObjCRuntime.MonoNativeFunctionWrapperAttribute%2F
https://developer.xamarin.com/404?link=%2Fapi%2Ftype%2FObjCRuntime.MonoPInvokeCallbackAttribute%2F

---
#### Λεπτομέρειες εγγράφου

⚠ *Μην επεξεργαστείτε αυτή την ενότητα. Απαιτείται για σύνδεση θεμάτων docs.microsoft.com ➟ GitHub.*

* ID: 500b8f87-12fb-9f14-9655-06cd3f1d91d2
* Version Independent ID: b199d974-6356-af0e-9d96-81e54953b65d
* Content: [Limitations of Xamarin.iOS - Xamarin](https://docs.microsoft.com/el-gr/xamarin/ios/internals/limitations)
* Content Source: [docs/ios/internals/limitations.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/ios/internals/limitations.md)
* Product: **xamarin**
* GitHub Login: @bradumbaugh
* Microsoft Alias: **brumbaug**

**Comment by bradumbaugh** [comment]
Hi @birbilis – thanks for the report. This is a known issue that we're tracking; the links are correct, but there's an internal issue preventing them from rendering correctly. I'm tracking this issue here: https://github.com/MicrosoftDocs/xamarin-docs/issues/140.

Again, thanks for the report.
