### ISSUE TITLE
Invalid resource folder names

### ISSUE THREAD

**Issue by ctacke** [MicrosoftDocs/xamarin-docs#433]
The screen shot shows folders named "drawable-xdpi" and "drawable-xxdpi" which are invalid and will yield compiler errors.  The folders should be "drawable-xhdpi" and "drawable-xxhdpi" (not the added 'h' in there).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0ee3ee1d-3a0c-cd7c-3f86-a3a1d1e0b9cf
* Version Independent ID: 60ffaae7-775a-b15f-e7c9-230cf5b5eeac
* Content: [Creating Resources for Varying Screens - Xamarin](https://docs.microsoft.com/en-us/xamarin/android/app-fundamentals/resources-in-android/resources-for-varying-screens?tabs=vswin)
* Content Source: [docs/android/app-fundamentals/resources-in-android/resources-for-varying-screens.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/android/app-fundamentals/resources-in-android/resources-for-varying-screens.md)
* Product: **xamarin**
* GitHub Login: @mgmclemore
* Microsoft Alias: **mamcle**

**Comment by mgmclemore** [comment]
Hi @ctacke, thanks for your feedback!  Yes, these screenshots are too old and need to be updated to reflect the latest templates (the naming is currently `mipmap-*`). I've added a task to our backlog to update this topic accordingly.
