### ISSUE TITLE
Are these emulators a part of VS?

### ISSUE THREAD

**Issue by zipswich** [MicrosoftDocs/xamarin-docs#434]
I am not sure the relationship between these emulators and VS.  I am a heavy user of VS, but I use it only for UWP apps.  The Visual Studio Emulator for Android, which was released a few years ago and is literally the best on earth, does not require VS at all. Its only relationship with VS is its name containing "Visual Studio".    Could anyone clarify this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4e37d642-2051-8d70-9968-dfb484122a6a
* Version Independent ID: 178ea80c-2b99-0c44-eeb6-9db319439b33
* Content: [Hardware Acceleration for Emulator Performance - Xamarin](https://docs.microsoft.com/en-us/xamarin/android/get-started/installation/android-emulator/hardware-acceleration?tabs=vswin)
* Content Source: [docs/android/get-started/installation/android-emulator/hardware-acceleration.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/android/get-started/installation/android-emulator/hardware-acceleration.md)
* Product: **xamarin**
* GitHub Login: @mgmclemore
* Microsoft Alias: **mamcle**

**Comment by mgmclemore** [comment]
Hi @zipswich, Visual Studio Emulator for Android was released with Visual Studio 2015 but is not supported with Visual Studio 2017. Because the Google Android Emulator has been updated to work with Hyper-V, it is now the standard emulator to use with Visual Studio for Android development. Yes, the emulator does not require Visual Studio in order to run, but Visual Studio installs the emulator as part of the mobile development workload. Hope this helps!

**Comment by zipswich** [comment]
Thank you for the clarification. 
Is Visual Studio Preview the only means to install these emulators?  I am asking this because I hesitate to use VS Preview (I have already had enough headache with .Net Native that seems to have new problems with every new version of VS).   

I took a look at SDK tools under Android Studio and saw Android Emulator 27.2.9 has already been installed automatically.

![image](https://user-images.githubusercontent.com/6095671/41563811-c98f2d4e-731e-11e8-9d4f-fa381a11eff2.png)

**Comment by mgmclemore** [comment]
Hi @zipswich, Visual Studio 2017 (both stable and preview) automatically installs the Google Android emulator when you enable the mobile development workload.  As you pointed out, Android Studio can also install the Google Android emulator.

**Comment by zipswich** [comment]
As the screenshot shows, Android Emulator 27.2.9 has already been installed. I have also created advancedFeatures.ini according to the instructions, but I get the following when trying to start an emulator:
![image](https://user-images.githubusercontent.com/6095671/41573242-b860b3c8-7349-11e8-97d3-d956dd9eafa0.png)

**Comment by mgmclemore** [comment]
Hi @zipswich, the Hyper-V feature is still in Preview, which means that you may have run into a bug. Please report the specifics about your issue at [Developer Community](https://developercommunity.visualstudio.com/spaces/8/index.html) (click **Report a problem**). Thanks!
