### ISSUE TITLE
Color instantiation question

### ISSUE THREAD

**Issue by samiam236** [MicrosoftDocs/xamarin-docs#436]
There's a sentence under **Interactive MVVM** which reads "Notice that the Color property is set to Blue when the ViewModel is instantiated." When I look at the XAML example however, I only see the color being instantiated to "Aqua." Is this a typo?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ed970855-6db1-6838-12cf-5a6f58b8ebf4
* Version Independent ID: edfe1b4d-58d2-477d-89b2-2641789cf2db
* Content: [Part 5. From Data Bindings to MVVM - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/xaml/xaml-basics/data-bindings-to-mvvm)
* Content Source: [docs/xamarin-forms/xaml/xaml-basics/data-bindings-to-mvvm.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/xaml/xaml-basics/data-bindings-to-mvvm.md)
* Product: **xamarin**
* GitHub Login: @charlespetzold
* Microsoft Alias: **chape**

**Comment by davidbritch** [comment]
Hi @samiam236 

Thanks for the feedback. You're correct - the ViewModel is instantiated to Aqua, rather than Blue. I've updated the doc in a PR, which should go live in a day or two.
