### ISSUE TITLE
Please explain doFinal() and the significance of the SECRET_BYTES variable

### ISSUE THREAD

**Issue by KristofferBerge** [MicrosoftDocs/xamarin-docs#437]
Can't see that the SECRET_BYTES variable is mentioned in the documentation at all. Why do we use this when calling doFinal()?

Also getting an exception regarding the state of the cipher in the doFinal-method when using the sample callback handler: 
> Java.Lang.IllegalStateException: Cipher not initialized for encryption/decryption

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f0eb1d39-e65c-e60b-0890-a13df58c8068
* Version Independent ID: fe06d001-1693-f137-4650-e5a23557a2e0
* Content: [Responding to Authentication Callbacks - Xamarin](https://docs.microsoft.com/en-us/xamarin/android/platform/fingerprint-authentication/fingerprint-authentication-callbacks)
* Content Source: [docs/android/platform/fingerprint-authentication/fingerprint-authentication-callbacks.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/android/platform/fingerprint-authentication/fingerprint-authentication-callbacks.md)
* Product: **xamarin**
* GitHub Login: @mgmclemore
* Microsoft Alias: **mamcle**

**Comment by topgenorth** [comment]
Fingerprint authentication relies on the underlying Java APIs for cryptography (a detailed explanation of which is beyond the scope of this article). Hopefully I can summarize this in a way that makes sense.  This example uses AES which will break the data to be encrypted in to blocks of a fixed size, and encrypt each of these blocks.  The `DoFinal` method is called as a matter of housekeeping; this will close off the cipher and pad out the last block of data using the `SECRET_BYTES` array.  With Fingerprint authentication, we don't care about the data that was just decrypted, the important thing is that the `OnAuthenticationSucceeded` callback was invoked.  

As for the exception you're getting, I'm looking into that.  I might just be that the sample needs updating.

**Comment by topgenorth** [comment]
I just tried the sample app after updating the NuGet packages on Visual Studio 2017 (with an Android Pixel device). I know this doesn't help you, but the app worked for me.

**Comment by bharder** [comment]
I'm also getting the IllegalStateException mentioned by @KristofferBerge when DoFinal() is called...

**Comment by BradThater** [comment]
@bharder did you ever find a solution to this? Could you please post it if you have I am also getting this error. My device is running API v 28.0
