### ISSUE TITLE
No need to uninstall JDK 9 or 10

### ISSUE THREAD

**Issue by pmahend1** [MicrosoftDocs/xamarin-docs#438]
No need to uninstall latest JDK on your machine. The documentation asks to **uninstall** JDK 9 

>After uninstalling JDK 9, ensure that the following path is not set on your PATH environment variable as it will still point to JDK 9: C:\ProgramData\Oracle\Java\javapath. After removing it, java -version at a command line should show JDK 8.

To avoid the errors and let the Xamarin pick JDK 8 just point it to use JDK 8

1. Install JDK 8
2. Go to Tools --&gt; Options --&gt; Xamarin --&gt; Android Settings
Change the Java Development Kit Location to point to JDK 8

It would be something like "C:\Program Files\Java\jdk1.8.0_172" on Windows machine.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f65a389e-9c7a-a51e-aad2-487fdeb28069
* Version Independent ID: 9117116b-f129-0dbd-2a6e-bb641e2fabc3
* Content: [Xamarin.Android and JDK 9 - Xamarin](https://docs.microsoft.com/en-us/xamarin/android/troubleshooting/questions/jdk9-errors)
* Content Source: [docs/android/troubleshooting/questions/jdk9-errors.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/android/troubleshooting/questions/jdk9-errors.md)
* Product: **xamarin**
* GitHub Login: @mgmclemore
* Microsoft Alias: **mamcle**

**Comment by mgmclemore** [comment]
Hi @pmahend1, thank you for your feedback! I have removed "After uninstalling JDK9" and added a paragraph explaining how to ensure that the JDK location is set to JDK 8 when JDK 9 is installed. The changes should be published soon.
