### ISSUE TITLE
Simple formula for 99% of our needs.

### ISSUE THREAD

**Issue by tlhintoq** [MicrosoftDocs/xamarin-docs#439]
I just want to know if the device is Portrait, PortraitFlipped, Landscape, LandscapeFlipped - without taking a course in Galifraean Hyperspacial Geometry.
Is there a direct and human understandable way to to take the OrientationSensorChangeEventArgs and tell if the user has the phone in landscape or portrait orientation?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ffb3c390-fe71-9f05-ce4f-938745f698df
* Version Independent ID: a258e102-f689-7ba2-c509-e47b47b6f623
* Content: [Xamarin.Essentials OrientationSensor - Xamarin](https://docs.microsoft.com/en-us/xamarin/essentials/orientation-sensor?context=xamarin/xamarin-forms)
* Content Source: [docs/essentials/orientation-sensor.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/essentials/orientation-sensor.md)
* Product: **xamarin**
* GitHub Login: @charlespetzold
* Microsoft Alias: **chape**

**Comment by charlespetzold** [comment]
The `OrientationSensor` is not intended for determining whether the display is in portrait or landscape mode. What you probably want is the [DeviceDisplay](https://docs.microsoft.com/en-us/xamarin/essentials/device-display?context=xamarin/xamarin-forms> class. The `Orientation` property of the `Metrics` object indicates the display mode.

**Comment by tlhintoq** [comment]
@charlespetzold 
Thank you for that clarification.  Since `orientation` is nested within `DeviceDisplay`, I bet I won't be the first person that jumps onto `OrientationSensor` with the wrong assumption.  And I admit it was a wrong assumption on my part.

I might suggest adding that same redirection to the top of the microsoft documentation page, if only to cut down on the number of ticket support gets.

**Comment by charlespetzold** [comment]
Good idea! Thanks!
