### ISSUE TITLE
"To specify multiple Font settings" example DOES NOT SHOW what it claims to show.

### ISSUE THREAD

**Issue by MappingSteve** [MicrosoftDocs/xamarin-docs#440]
Re: "To specify multiple Font settings, combine the required settings into a single font attribute string."  
The XAML shown is separate fields "FontAttributes", "FontSize". That is NOT "combining". What it SHOULD show is a single "Font" property (NOT a "font attribute string"), with font family, font attributes, and font size, e.g. Font="Tahoma, Bold, 24".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe0572c4-91be-fc86-d130-242db2bf470b
* Version Independent ID: 1238fdd7-c378-6d0d-654e-55656a70d386
* Content: [Fonts in Xamarin.Forms - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/text/fonts)
* Content Source: [docs/xamarin-forms/user-interface/text/fonts.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/text/fonts.md)
* Product: **xamarin**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @MappingSteve 

Thanks for pointing this out. I've fixed it in a PR] that should go live in a day or two.
