### ISSUE TITLE
Documentation about ClickGestureRecognizer

### ISSUE THREAD

**Issue by johannes-schmitt** [MicrosoftDocs/xamarin-docs#442]
Documentation about [ClickGestureRecognizer](https://github.com/xamarin/Xamarin.Forms/blob/master/Xamarin.Forms.Core/ClickGestureRecognizer.cs) is missing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b1d849b9-e4a6-1507-4532-26daa94ffaae
* Version Independent ID: 07ae51c4-93fe-377e-ad12-41246a6f2e10
* Content: [Xamarin.Forms Gestures - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/gestures/)
* Content Source: [docs/xamarin-forms/app-fundamentals/gestures/index.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/app-fundamentals/gestures/index.md)
* Product: **xamarin**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @johannes-schmitt 

We have written some documentation for the `ClickGestureRecognizer` (which is available for desktop platforms such as Mac), and desktop support in general, but have held of from publishing it until some of the bugs in this area have been addressed.

**Comment by johannes-schmitt** [comment]
HI @davidbritch, can you point me to the bugs you mentioned because we are going to use `ClickGestureRecognizer` and would like to avoid to run in known issues.

**Comment by davidbritch** [comment]
Hi @johannes-schmitt 

It looks like the only remaining bug that's open for `ClickGestureRecognizer` stops it working on views contained in an `ItemTemplate` being used by a `ListView`: https://github.com/xamarin/Xamarin.Forms/issues/1658
