### ISSUE TITLE
Binding not working.

### ISSUE THREAD

**Issue by gmoney494** [MicrosoftDocs/xamarin-docs#444]
Im trying to bind a native ios library fro Adobe called AccessEnabler. Ive followed this docs and some of the others on how to do it. Now my binding project builds and compiles no problem, but when i insert it into my test ios project, it doesnt work. The app crashes without starting or output, i have to navigate to the console logs to get something. It says its looking for the framework "Library not loaded: @rpath/AccessEnabler.framework/AccessEnabler" which is also weird as i created it into a libAccessEnabler.a fat binary as per the instructions on most docs (confirmed with lipo commmand as well). I've lost a couple days on this and im totally lost. 

PS. Another developer from another team did the binding to the same SDK (much earlier version) and got it working over a year ago that this same test ios app also can ingest and use with no errors or isseus, however i need to use the latest version of the SDK and its giving me issues. Any help or advice would be greatly appreciated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd6324b2-d690-3265-39e2-d5a57fcc1083
* Version Independent ID: b7553f1b-1ed1-27fb-5e11-b91f609d32b1
* Content: [Referencing Native Libraries in Xamarin.iOS - Xamarin](https://docs.microsoft.com/en-us/xamarin/ios/platform/native-interop)
* Content Source: [docs/ios/platform/native-interop.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/ios/platform/native-interop.md)
* Product: **xamarin**
* GitHub Login: @bradumbaugh
* Microsoft Alias: **brumbaug**

**Comment by bradumbaugh** [comment]
Hi @gmoney494 – this repository is only for issues specifically related to the documentation. For support or to report bugs, please take a look at [Developer Community](https://developercommunity.visualstudio.com/spaces/8/index.html). Thank you!
