### ISSUE TITLE
Information obsoleted.

### ISSUE THREAD

**Issue by shoshins** [MicrosoftDocs/xamarin-docs#449]
APNS-Sharp - obsoleted in 2014.

Main links to Apple documentation are invalid:
Refer to Apple’s In-App Purchase Receipt Validation documentation - can’t be found
See Apple’s Verifying Store Receipts documentation for additional information - can’t be found

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2e14a13a-7e19-9745-2165-bcb89359f54f
* Version Independent ID: ff948ecb-078f-b633-679d-bfc8ca435340
* Content: [Transactions and Verification in Xamarin.iOS - Xamarin](https://docs.microsoft.com/en-us/xamarin/ios/platform/in-app-purchasing/transactions-and-verification)
* Content Source: [docs/ios/platform/in-app-purchasing/transactions-and-verification.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/ios/platform/in-app-purchasing/transactions-and-verification.md)
* Product: **xamarin**
* GitHub Login: @bradumbaugh
* Microsoft Alias: **brumbaug**

**Comment by bradumbaugh** [comment]
Thanks @shoshins. I've removed the outdated information and updated the links; should be published soon. Appreciate your help!
