### ISSUE TITLE
Incorrect image

### ISSUE THREAD

**Issue by varyamereon** [MicrosoftDocs/xamarin-docs#45]
The image for customized grouping seems to be the incorrect one as it does not reflect the described code and seems to be the same as the previous image.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7c0643eb-b23e-9283-39eb-6fb0b97a1b83
* Version Independent ID: c1f024de-3443-d7a2-7c0a-1d78d619aea4
* Content: [List Appearance - Xamarin](https://docs.microsoft.com/en-gb/xamarin/xamarin-forms/user-interface/listview/customizing-list-appearance#feedback)
* Content Source: [docs/xamarin-forms/user-interface/listview/customizing-list-appearance.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/listview/customizing-list-appearance.md)
* Service: **unspecified**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by conceptdev** [comment]
You're right! New images are required for the doc - we will fix as soon as we can!
