### ISSUE TITLE
Importance of solution/project name could be better emphasized 

### ISSUE THREAD

**Issue by StuartArmstrong** [MicrosoftDocs/xamarin-docs#451]
I spent at least thirty minutes attempting to fix errors after originally calling the solution and projects "HelloWorldXamarin". Renaming them after the fact left issues with auto generated files. After changing old references in .csproj files didn't work, I ended up deleting the whole thing and starting again.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2de3e72c-8948-4dd5-e37f-9cf81e62c127
* Version Independent ID: 7b7c5c7f-4102-8e91-fbe6-7d21fcc8f5be
* Content: [Xamarin.Forms Quickstart - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/get-started/hello-xamarin-forms/quickstart?tabs=vswin)
* Content Source: [docs/xamarin-forms/get-started/hello-xamarin-forms/quickstart.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/get-started/hello-xamarin-forms/quickstart.md)
* Product: **xamarin**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @StuartArmstrong 

I've made a PR to address the issue. Once it's merged there'll be notes in the doc explaining the need to name the solution Phoneword.

Thanks for logging this issue.
