### ISSUE TITLE
Option to open XAML Previewer for not showing up Xamarin.Forms

### ISSUE THREAD

**Issue by PinkoAgrawal** [MicrosoftDocs/xamarin-docs#452]
Hi,
I am using VS2017 15.7.4 Enterprise in Windows 10, I am not able to find option to open XAML Previewer window at  **View > Other Windows > Xamarin.Forms Previewer**. Here _Xamarin.Forms Previewer_ not available.
Article : [https://docs.microsoft.com/en-us/xamarin/xamarin-forms/xaml/xaml-previewer?tabs=vswin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/xaml/xaml-previewer?tabs=vswin)
How can I solve this issue ?

![xamlpreviewer](https://user-images.githubusercontent.com/38238586/41663484-2b4a6ae6-74c1-11e8-82f1-c6f8363f82d3.png)

**Comment by davidbritch** [comment]
Hi @PinkoAgrawal 

Most odd. I'm also running VS2017 15.7.4 Enterprise in Windows 10 and do have the Preview menu option:

![vs2017](https://user-images.githubusercontent.com/8092460/41669273-5718d31e-74a9-11e8-83dc-58b49190c3e6.PNG)

If running a repair on Visual Studio fails to resolve this issue, I suggest you raise it on [Developer Community](https://developercommunity.visualstudio.com/spaces/8/index.html).
