### ISSUE TITLE
PanGesture don't allow scroll

### ISSUE THREAD

**Issue by BRomeroT** [MicrosoftDocs/xamarin-docs#453]
If you attach PanGesture to a View that is into a ScrollView or as ItemTemplate for ListView, the scroll don't response.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2c99b3d4-31db-a5e2-6328-b63a4d72e33d
* Version Independent ID: cfa31576-88ee-0585-377b-f170fda35615
* Content: [Adding a Pan Gesture Recognizer - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/gestures/pan)
* Content Source: [docs/xamarin-forms/app-fundamentals/gestures/pan.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/app-fundamentals/gestures/pan.md)
* Product: **xamarin**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @BRomeroT 

You won't be able use a pan gesture recogniser on a view in a `ScrollView` as the `ScrollView` will receive any gestures, not the view. Similarly, in a `ListView` containing a pan gesture the `ListView` will receive any gestures, rather than the pan gesture recogniser.
