### ISSUE TITLE
For those using Visual Studio 2017

### ISSUE THREAD

**Issue by maparaschivei** [MicrosoftDocs/xamarin-docs#454]
As of Visual Studio 2017 Version 15.7.x Xamarin.Android has introduced new project templates. When creating a new Android App you'll have to choose between Single View App, Navigation Drawer App, Tabbed App, and Blank App template selections. Using the "Blank App" template appears to be the best choice if you're following along with this guide, however, the generated layout file (Resources/layout/activity_main.axml) defaults to RelativeLayout instead of LinearLayout. In order to follow along with this quickstart walkthrough you'll have to change all references of "RelativeLayout" to "LinearLayout" in acitvity_main.axml. This can be done easily using the "source" view.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 660b0f7c-9941-2db3-63bf-fc8a97765b1e
* Version Independent ID: 5aa1e6f6-534a-05b9-c44a-1f62b24c201a
* Content: [Hello, Android: Quickstart - Xamarin](https://docs.microsoft.com/en-us/xamarin/android/get-started/hello-android/hello-android-quickstart?tabs=vswin#feedback)
* Content Source: [docs/android/get-started/hello-android/hello-android-quickstart.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/android/get-started/hello-android/hello-android-quickstart.md)
* Product: **xamarin**
* GitHub Login: @mgmclemore
* Microsoft Alias: **mamcle**

**Comment by maparaschivei** [comment]
It is also necessary to add the following property to the root LinearLayout element.

`android:orientation="vertical"`

The complete root element may look similar to the following:

```
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:minWidth="25px"
    android:minHeight="25px"
    android:orientation="vertical">
```

**Comment by mgmclemore** [comment]
Hello @maparaschivei, thanks for the feedback!  Yes, this quick-start guide needs to be updated to the latest templates. I've added a task to our backlog to update this topic, incorporating your suggestions.

**Comment by mprogers** [comment]
This was posted two years ago. Is this product no longer supported?

**Comment by conceptdev** [comment]
This page was updated a few months after the issue was raised. Please create a new issue if you have feedback about the existing content – Xamarin.Android is definitely still a supported product.
