### ISSUE TITLE
Update documentation for Xamarin Forms 3.1

### ISSUE THREAD

**Issue by tomh4** [MicrosoftDocs/xamarin-docs#455]
In Forms 3.1 the Bottom Tab Support for Android was added, please update the docuementation on how to use it 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0c81c589-e81e-d98c-9656-695a3520a12d
* Version Independent ID: c235f6f9-47ce-15f3-b4da-cb12e219df92
* Content: [Xamarin.Forms Tabbed Page - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/navigation/tabbed-page)
* Content Source: [docs/xamarin-forms/app-fundamentals/navigation/tabbed-page.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/app-fundamentals/navigation/tabbed-page.md)
* Product: **xamarin**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @tomh4 

Docs for all of Xamarin.Forms 3.1 will be published once they're complete. In the meantime, for a code example of Android bottom tab support, see https://github.com/xamarin/Xamarin.Forms/blob/3.1.0/Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/BottomTabbedPageTests.cs#L30

**Comment by tomh4** [comment]
Alright thanks!
