### ISSUE TITLE
Wrong link in iOS section

### ISSUE THREAD

**Issue by Krumelur** [MicrosoftDocs/xamarin-docs#456]
The link to "Keychain" in the iOS tab is pointing to Android's keychain docs at https://developer.xamarin.com/api/type/Android.Security.KeyChain/ and not to https://developer.xamarin.com/api/type/MonoTouch.Security.SecKeyChain/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: da75050f-bfda-4792-40d9-b9a25d649d3e
* Version Independent ID: 5c44f996-765b-f6e4-c807-9446c534d50b
* Content: [Xamarin.Essentials: Secure Storage - Xamarin](https://docs.microsoft.com/en-us/xamarin/essentials/secure-storage?tabs=ios)
* Content Source: [docs/essentials/secure-storage.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/essentials/secure-storage.md)
* Product: **xamarin**
* GitHub Login: @Redth
* Microsoft Alias: **jodick**

**Comment by bradumbaugh** [comment]
Thanks @Krumelur – just updated the link to: https://developer.xamarin.com/api/type/Security.SecKeyChain/. Should be published soon.

Appreciate the help!
