### ISSUE TITLE
Please add more information about using Property

### ISSUE THREAD

**Issue by PinkoAgrawal** [MicrosoftDocs/xamarin-docs#457]
Hi, 
I have doubt where to use Property Height,  is it with YConstraint or XConstraint & same doubt with Width?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 35a0e591-622a-aa3f-a289-7896af574a81
* Version Independent ID: 8e796318-0fa6-d67f-1de3-f3b0a5feb49c
* Content: [Xamarin.Forms RelativeLayout - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/layouts/relative-layout)
* Content Source: [docs/xamarin-forms/user-interface/layouts/relative-layout.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/layouts/relative-layout.md)
* Product: **xamarin**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @PinkoAgrawal 

Thanks for the suggestion. I've created an issue in our backlog about this. Width is often used with XConstraint, and Height with YConstraint. However, it also depends on the layout you're trying to create.
