### ISSUE TITLE
Xamarin Forms Previewer window not getting refreshed

### ISSUE THREAD

**Issue by PinkoAgrawal** [MicrosoftDocs/xamarin-docs#458]
I am using VS2017 Enterprize 15.7.4 Windows 10.
When I started using Xamarin.Fomrs previewer, up to half an hour it worked fine after that stooped showing changes made in xaml, I Rebuild, Closed & reopen visual studio than i got pink color window.
Here if i clean project than I am getting another error but not getting output.
Screenshots:

![xampreviewer](https://user-images.githubusercontent.com/38238586/41725871-86992ef0-758e-11e8-8c0c-5c863651650c.png)

After rebuild success if I clean project getting another issue below however **project have not errors**

![xampreviewer2](https://user-images.githubusercontent.com/38238586/41725998-c444ee24-758e-11e8-9bc9-0adce4981a10.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7c68dedd-a9ba-8c0e-ffa0-3ea5c50cde24
* Version Independent ID: fc61bfbb-f86b-c5dd-fa57-0e55fce4683f
* Content: [XAML Previewer for Xamarin.Forms - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/xaml/xaml-previewer?tabs=vswin)
* Content Source: [docs/xamarin-forms/xaml/xaml-previewer.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/xaml/xaml-previewer.md)
* Product: **xamarin**
* GitHub Login: @charlespetzold
* Microsoft Alias: **chape**

**Comment by conceptdev** [comment]
Hi @PinkoAgrawal - sorry to see you having issues with the XAML Previewer.

Bugs, issues, and suggestions can be reported on the [Developer Community site](https://developercommunity.visualstudio.com/) (or via the **Help** menu in Visual Studio). We appreciate all feedback as it helps us build a better product.

**Comment by PinkoAgrawal** [comment]
ok than what type issues should I open here? as I am able to see options to open issue.

**Comment by conceptdev** [comment]
Hi @PinkoAgrawal, we use the MicrosoftDocs GitHub repo to manage the documentation itself, so this is where customers provide feedback on our guides and API reference. This helps us improve our communication in how to use our stuff. 

At the bottom of each docs page there is also a **Product Feedback** button, which for Xamarin and Visual Studio takes you to [Developer Community](https://developercommunity.visualstudio.com/). This is where we gather bugs, issues, and feature suggestions for the products themselves. Customers can vote and discuss posts there, and get feedback from engineering and PMs.

Hope that helps.
