### ISSUE TITLE
Xamarin Live Reloading throwing Error : Device disconnected: Android phone, Android SDK built for x86 Google 8.1.0 (emulator)

### ISSUE THREAD

**Issue by HarshChaurasia** [MicrosoftDocs/xamarin-docs#461]
Xamarin Live Reloading throwing Error : Device disconnected: Android phone, Android SDK built for x86 Google 8.1.0 (emulator)

Log
Starting local MQTT server on port 1883
Started local MQTT server on port 1883
Connected to localhost:1883
Connected to localhost:1883
Connected to localhost:1883
Connected to localhost:1883
Connected to localhost:1883
Connected to localhost:1883
Device disconnected: Android phone, Android SDK built for x86 Google 8.1.0 (emulator)

**Comment by davidbritch** [comment]
Hi @HarshChaurasia 

Live Reload is currently in preview, and is definitely still supported and being worked on (it was only introduced last month).

I'll hand you over to @pierceboggan who may be able to help.

**Comment by kzu** [comment]
Could you please report the issue via the "Send Feedback" in Visual Studio for tracking and follow-up?

Thanks!
