### ISSUE TITLE
so ... how do you deploy the app for testing ???  ie just get it from VS onto the device 

### ISSUE THREAD

**Issue by trevor-smith-nanotechsoftware-co-uk** [MicrosoftDocs/xamarin-docs#462]
on a virgin app with no code of mine in it I get :- AMDeviceSecureInstallApplicationBundle returned: 0xe8008015.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 49697029-1702-60cb-fc60-aff52951d32c
* Version Independent ID: 2fb4336e-ae1f-d023-ffc3-33a0315f3287
* Content: [Xamarin.Forms Deployment and Testing - Xamarin](https://docs.microsoft.com/en-gb/xamarin/xamarin-forms/deploy-test/)
* Content Source: [docs/xamarin-forms/deploy-test/index.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/deploy-test/index.md)
* Product: **xamarin**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
You need to provision your (iOS) device first. See https://docs.microsoft.com/en-us/xamarin/ios/deploy-test/provisioning/index

**Comment by trevor-smith-nanotechsoftware-co-uk** [comment]
I had forgotten its not the same device I provisioned a few months ago ..

Thanks


Best Regards


Trevor Smith


NanoTech Software Ltd


01603 851 707         (Direct)
07535 447394          (mobile)
 
www.nanotechsoftware.co.uk <http://www.nanotechsoftware.co.uk/>




This e-mail, including any attachments, is intended for the above named recipient(s) only and may be confidential. If it has come to you in error you must take no action based on it, nor must you copy it or use it for any other purposes, or disclose the content of the e-mail to any other person, or store or copy the information in any medium. If you have received this email in error, please notify info@nanotechsoftware.co.uk <mailto:info@nanotechsoftware.co.uk>  immediately quoting the name of the sender and the addressee then delete it from your system.

Any views or opinions expressed within this email are those of the author and do not necessarily represent those of nanoTech Software Ltd.
