### ISSUE TITLE
clarify NAMESPACE vs ASSEMBLY

### ISSUE THREAD

**Issue by MappingSteve** [MicrosoftDocs/xamarin-docs#464]
Re "In this example, compile-time checking of all the XAML contained within the PhotoApp namespace will be performed".  
Actually, compilation will be in ALL namespaces WITHIN THE ASSEMBLY, not just in the one namespace.  
This can be verified by attempting to add that annotation to a source file that declares a different namespace.  compiler will complain that this is a DUPLICATE declaration of that directive.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 18750a4a-7a18-60c6-206e-b5740a7902e3
* Version Independent ID: a1cd5eac-0f69-4304-88b1-ed17d128ff84
* Content: [XAML Compilation in Xamarin.Forms - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/xaml/xamlc)
* Content Source: [docs/xamarin-forms/xaml/xamlc.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/xaml/xamlc.md)
* Product: **xamarin**
* GitHub Login: @charlespetzold
* Microsoft Alias: **chape**

**Comment by davidbritch** [comment]
Hi @MappingSteve 

Thanks for the feedback and well spotted! I've fixed the doc, and it will go live once the PR is merged.
