### ISSUE TITLE
Please add C# examples, especially how to search both app and local dictionaries

### ISSUE THREAD

**Issue by MappingSteve** [MicrosoftDocs/xamarin-docs#465]
Sometimes code behind wants to lookup a resource.  Locally this is `this.Resources[ name ];`.  Searching in app is `Application.Current.Resources[ name ];`.  XAML is smart enough to search locally, then up the visual element tree, then finally in App Resources. Would be good to know what c# equivalent of that search is.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1d23ce09-1c59-1482-036a-f7348090fd00
* Version Independent ID: 9b4213b5-8278-5bea-c73d-0e172d7c0a89
* Content: [Resource Dictionaries - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/xaml/resource-dictionaries)
* Content Source: [docs/xamarin-forms/xaml/resource-dictionaries.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/xaml/resource-dictionaries.md)
* Product: **xamarin**
* GitHub Login: @charlespetzold
* Microsoft Alias: **chape**

**Comment by davidbritch** [comment]
Hi @MappingSteve 

The ability to search the visual tree for a resource is functionality that's provided by the XAML parser, rather than by the `ResourceDictionary` class, and so is specific to XAML. There's no equivalent functionality when using a `ResourceDictionary` in C#.
