### ISSUE TITLE
This does not work for me

### ISSUE THREAD

**Issue by PingPongSet** [MicrosoftDocs/xamarin-docs#468]
myListView is on ListItem.axml, it is not on MainActivity.cs. Thus the code below results in listView being null.

  listView = FindViewById&lt;ListView&gt; (Resource.Id.myListView);

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 927aa51c-a373-2e12-6208-4f6a9dd370d2
* Version Independent ID: 3a1c72c3-f0a8-e330-0c71-dd4e2a3258bb
* Content: [Using the Android Designer - Xamarin](https://docs.microsoft.com/en-us/xamarin/android/user-interface/android-designer/designer-walkthrough?tabs=vswin#summary)
* Content Source: [docs/android/user-interface/android-designer/designer-walkthrough.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/android/user-interface/android-designer/designer-walkthrough.md)
* Product: **xamarin**
* GitHub Login: @mgmclemore
* Microsoft Alias: **mamcle**

**Comment by mgmclemore** [comment]
Hello @PingPongSet, thank you for the feedback! We are working on an updated version of this topic that fixes this issue. Should be published soon.

**Comment by mgmclemore** [comment]
Hi @PingPongSet, I'll add a note here when the new version is published and that should send an email.

**Comment by Hutch07** [comment]
All of my tools from the toolbox stack up in the upper left corner and cannot be moved.  I have tried several things like reloading and updating.

**Comment by abqsteve2** [comment]
I think I am having the same issue as @PingPongSet.  Line 22 (copied from above) gives an error:
listView = FindViewById<ListView>(Resource.Id.myListView);
Visual Studio reports the error on this line as:
'Resource.ID' does not contain a definition for 'myListView'
