### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by xavier-rigau** [MicrosoftDocs/xamarin-docs#47]
In Xamarin.Mac Version: 4.4.0.14  on Mac OSX 10.13.3

-Managed handler doesn't work behind proxy servers
-NSUrlSession does
-CFNetwork doesn't.

A mechanism is needed to use the project handler and still inspect/change some properties like like AutomaticDecompression. Otherwise the client is forced to do platform dependent code.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 81501010-a37c-6e4e-e2c4-c3f7d55549ea
* Version Independent ID: 446dd633-9046-fa86-f756-07a02bc7a2de
* Content: [HttpClient Stack and SSL/TLS Implementation Selector for iOS/macOS - Xamarin](https://docs.microsoft.com/en-us/xamarin/cross-platform/macios/http-stack)
* Content Source: [docs/cross-platform/macios/http-stack.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/cross-platform/macios/http-stack.md)
* Service: **unspecified**
* GitHub Login: @asb3993
* Microsoft Alias: **amburns**

**Comment by bradumbaugh** [comment]
Hi @xavier-rigau, thanks for the comment. Please file enhancement requests such as this on [GitHub](https://github.com/xamarin/xamarin-macios/issues). Appreciate your help!

**Comment by bradumbaugh** [comment]
@xavier-rigau I'm going to close this issue, but feel free to reply again if you have anything further and we can reopen it. Thank you!

**Comment by xavier-rigau** [comment]
I gave feedback once. You can copy and past it in the proper forum. What is the point to provide feedback right on the document. I am confused and have no time now to followup.

**Comment by bradumbaugh** [comment]
@xavier-rigau Sorry for the confusion - this repository is intended to be used for feedback about the docs themselves, not enhancement requests for the product. If you have a specific enhancement request for Xamarin.iOS or Xamarin.Mac, it's best to file it [here](https://github.com/xamarin/xamarin-macios/issues). 

That said, I'll note on this thread the next time this document is updated.
