### ISSUE TITLE
More details are required regarding how to get the Android Device Manager to not use HAXM

### ISSUE THREAD

**Issue by lf-** [MicrosoftDocs/xamarin-docs#471]
This section notably doesn't state how to actually set the preferred emulator as the Google Emulator instead of HAXM. Currently, the Device Manager demands that HAXM be installed and refuses to start devices.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 440a1c4c-31dd-5120-fd35-5ac1ffa287b9
* Version Independent ID: 14c189a9-9a57-472d-2f4a-0d47f40ce536
* Content: [Google Android Emulator Setup - Xamarin](https://docs.microsoft.com/en-us/xamarin/android/get-started/installation/android-emulator/)
* Content Source: [docs/android/get-started/installation/android-emulator/index.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/android/get-started/installation/android-emulator/index.md)
* Product: **xamarin**
* GitHub Login: @mgmclemore
* Microsoft Alias: **mamcle**

**Comment by mgmclemore** [comment]
Hi @lf-, thanks for the feedback!  We have some emulator doc changes in the pipeline that should help to eliminate the confusion about multiple emulators (to be published soon).

Separately, if the Device Manager is giving HAXM errors and refusing to start devices, that could be a bug that needs to be investigated. Could you please report the specifics about your issue at [Developer Community](https://developercommunity.visualstudio.com/spaces/8/index.html) (click **Report a problem**). Thank you!
