### ISSUE TITLE
This is deprectated!

### ISSUE THREAD

**Issue by Cyberspy** [MicrosoftDocs/xamarin-docs#472]
Seems new PCL solutions are not supported anymore - not that you'd guess from the description above.
Seems now Microsoft announces changes like this, as answers to questions about the missing feature.

This article seems to be the main 'announcement' of this - https://developercommunity.visualstudio.com/content/problem/161033/vs-2017-1550-community-edition-no-pcl-option-when.html?childToView=161169#comment-161169

Way to go Microsoft - make major changes, and announce them only when people notice!

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 271e134d-3069-e673-3874-faf6930a19ee
* Version Independent ID: 0c84a593-80cf-6195-c082-6752736f386b
* Content: [Introduction to Portable Class Libraries - Xamarin](https://docs.microsoft.com/en-gb/xamarin/cross-platform/app-fundamentals/pcl?tabs=vsmac)
* Content Source: [docs/cross-platform/app-fundamentals/pcl.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/cross-platform/app-fundamentals/pcl.md)
* Product: **xamarin**
* GitHub Login: @asb3993
* Microsoft Alias: **amburns**

**Comment by bradumbaugh** [comment]
Hi @Cyberspy, .NET Standard is now the preferred way to share code. There's a good blog post about Xamarin.Forms support for .NET Standard [here](https://blog.xamarin.com/net-standard-comes-xamarin-forms-project-templates/).

That said, it is still possible to create PCL libraries from **File > New**, but you're correct that it's no longer surfaced as a project template for a new Xamarin.Forms project.
