### ISSUE TITLE
Errors in code snippets of Markers section

### ISSUE THREAD

**Issue by na2axl** [MicrosoftDocs/xamarin-docs#475]
There are errors in code snippets of Marker section... Marker options are created with variable name **markerOpt1**, but added in the map with the name **marker1**.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 746db42d-9af7-06b3-b059-cced44c12bc1
* Version Independent ID: 84e72b26-cb39-145b-44e7-d73c325c04a2
* Content: [Maps API - Xamarin](https://docs.microsoft.com/en-us/xamarin/android/platform/maps-and-location/maps/maps-api)
* Content Source: [docs/android/platform/maps-and-location/maps/maps-api.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/android/platform/maps-and-location/maps/maps-api.md)
* Product: **xamarin**
* GitHub Login: @mgmclemore
* Microsoft Alias: **mamcle**

**Comment by mgmclemore** [comment]
Hi @na2axl, thank you for the feedback! This topic has been updated and the changes should be published soon.
