### ISSUE TITLE
canca

### ISSUE THREAD

**Issue by Veinder55** [MicrosoftDocs/xamarin-docs#478]
enhrebtn[oerno[

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a0047ac3-d92a-dcb0-18ba-a0a8db2331db
* Version Independent ID: 8a479a1b-f3c8-a627-97a8-3d9e1f8573ee
* Content: [Time Picker - Xamarin](https://docs.microsoft.com/en-us/xamarin/android/user-interface/controls/pickers/time-picker)
* Content Source: [docs/android/user-interface/controls/pickers/time-picker.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/android/user-interface/controls/pickers/time-picker.md)
* Product: **xamarin**
* GitHub Login: @mgmclemore
* Microsoft Alias: **mamcle**

**Comment by mgmclemore** [comment]
Hi @Veinder55: perhaps you opened this in error (not sure what _enhrebtn[oerno[_ means)? Closing -- please reopen if you need to re-comment. Thanks!
