### ISSUE TITLE
Is sample code project available for download?

### ISSUE THREAD

**Issue by PingPongSet** [MicrosoftDocs/xamarin-docs#479]
It will be helpful to download the sample code project if available.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4c0e5b65-7fdc-2917-174a-f87978345314
* Version Independent ID: 8f189410-c914-8605-953e-5574f0a9dcbd
* Content: [Auto Complete - Xamarin](https://docs.microsoft.com/en-us/xamarin/android/user-interface/controls/auto-complete)
* Content Source: [docs/android/user-interface/controls/auto-complete.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/android/user-interface/controls/auto-complete.md)
* Product: **xamarin**
* GitHub Login: @mgmclemore
* Microsoft Alias: **mamcle**

**Comment by topgenorth** [comment]
Hi there.  This particular content is  derived from some docs that came with the AOSP a while ago. It seems that this particular example has been deprecated and removed from Google's examples. 

We do have a recipe that demonstrates how to use the AutoComplete textview. You can find it at https://github.com/xamarin/recipes/tree/master/Recipes/android/controls/autocomplete_text_view/add_an_autocomplete_text_input.

The code in this recipe doesn't exactly follow the code in the idea, but it follows the exact sample APIs and principles.
