### ISSUE TITLE
Additional troubleshooting if a physical apple watch does not show up in the device list. 

### ISSUE THREAD

**Issue by jgold6** [MicrosoftDocs/xamarin-docs#480]
In trying to debug an Apple Watch app on a physical apple watch device, I ran into a snag. In the past I had accidentally told my watch to not trust my work computer, and had semi-forgotten about that as I did not need the watch to trust the computer up until this point. The iPhone was set to trust the computer, it was just the watch that did not trust the computer. This prevented the apple watch device from being shown in the device list in Visual Studio 2017 for Windows or Visual Studio for Mac. There was no good error message shown for this even when testing with XCode and a simple swift apple watch app. XCode just told me that the watch was not paired, which it was. See this issue for details: https://github.com/xamarin/xamarin-macios/issues/4345

Eventually the macOS Console.app gave me better info that the watch was not set to trust this computer. To fix this I reset the location and privacy settings on my iPhone (**Settings &gt; General &gt; Reset &gt; Reset Location and Privacy**) and unpaired and re-paired my apple watch to my iPhone, then connect the iPhone to my computer to get the "trust this computer" prompt on my iPhone and my Apple watch again, making sure to trust the computer this time. 

I perhaps found a simpler way to cause the "trust this computer" dialog to show on the iPhone and the Watch again, but have not tested this. In  **Settings &gt; Developer** I discovered a button to "Clear trusted computers" so hopefully that is an easier way to get the "trust this computer" dialog to show up again allowing one to change their answer. A quick test seems to indicate that this only clears the trusted computers for the iPhone though, not the paired apple watch, so I think you will still have to unpair and re-pair the watch after doing the above, just as I had to after using the "Reset Location and Privacy" button on the iPhone. 

Once the watch trusted the computer, the Apple Watch showed up in the device list when the watch app was selected as the startup project AND the iPhone was plugged in via USB. One of the Xamarin iOS Engineers also said that the Watch should be connected to the charger when debugging to the watch, but I did not find that tp be necessary on my end. 

It is also important to make sure that "Enable Debugging" is set on the watch app project in the **Project Options/Properties -&gt; watchOS Debug** settings page for the Debug | iPhone configuration if you want to debug the watch app on the watch. This does not seem to be set by default.

In addition to adding the above to the troubleshooting section, albeit in a more concise way, I might suggest that the "Testing on a Watch device" section be modified to allow for debugging to a watch device. Right now it says to select the iOS app as the startup project and manually launch the watch app once it is installed. This does not allow debugging of the watch app, instead I suggest it says to select the watch app as the startup project and select the physical watch in the device list.e.g.:

## Testing on a Watch device
Once you have configured your Device, App IDs, and Provisioning Profiles, you are ready to test.
1. Make sure your iPhone is plugged in, and the Watch is already paired with the iPhone. 
2. Ensure the configuration is set to Debug or Debug | iPhone (if available) or Release (if you do not want to debug)
3. Right-click on the watch project and choose Set As Startup Project.
4. Ensure the connected Watch device is selected in the target list.
5. Click the Run button (or choose a Start option from the Run menu).
6, The solution will build and the iOS app will be deployed to the iPhone and the watch app will be deployed to the watch (this can be very slow). If the iOS app or watch extension provisioning is not set correctly then deployment to the iPhone will fail.
7. You need to keep the watch awake until the watch app starts.
8. If deployment completes successfully, your app icon will appear on the watch screen with a circular installing progress indicator.
9. If the watch app is successfully installed, the watch app should launch and you can start debugging (if Debug configuration was selected). 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d68ed473-c5c3-26db-af97-858acb914542
* Version Independent ID: ed3a816c-77f3-4aad-b393-7d8186b9d7eb
* Content: [Testing on Apple Watch Devices - Xamarin](https://docs.microsoft.com/en-us/xamarin/ios/watchos/deploy-test/device#testing-on-a-watch-device)
* Content Source: [docs/ios/watchos/deploy-test/device.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/ios/watchos/deploy-test/device.md)
* Product: **xamarin**
* GitHub Login: @bradumbaugh
* Microsoft Alias: **brumbaug**

**Comment by bradumbaugh** [comment]
Thanks for the detailed explanation and ideas, @jgold6 – agree we should update this content. I've captured an item on our internal backlog to take a look at updating this content to discuss debugging on physical Apple Watch devices (and the associated troubleshooting information to make sure they appear in the device list). Thanks again.
