### ISSUE TITLE
SQLite.NET PCL Vs Entity Framework Core

### ISSUE THREAD

**Issue by tmt242001** [MicrosoftDocs/xamarin-docs#481]
Why use "SQLite.NET PCL" rather than "Entity Framework Core SQLite" ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3ab6098a-39c7-151f-124b-f88aa62c4659
* Version Independent ID: dc27c1e4-ff12-c1af-646a-c2617def0bcd
* Content: [Xamarin.Forms Local Databases - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/databases)
* Content Source: [docs/xamarin-forms/app-fundamentals/databases.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/app-fundamentals/databases.md)
* Product: **xamarin**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @tmt242001 

You could use either. For simplicity, Entity Framework Core SQLite is a good choice. However, there's an additional overhead to using EFCore SQLite as opposed to SQLite. Therefore, for raw performance, SQLite is a good choice.

**Comment by lnaie** [comment]
What is the overhead? Nonetheless we still need a good example. Thanks!

**Comment by nk54** [comment]
Hello, I know this thread is closed but have you found some numbers about the overhead @lnaie ? It's hard to find documentation about such things.

Right now, I got an app which use SQLite PCL but I consider to use EF to add the possibility to perform migration without having to handle everything myself.
I don't plan to use tracking or such things.

Are there any pitfall to be aware before spending time to use EF ?

Thanks.
