### ISSUE TITLE
Android Device Manager won't open

### ISSUE THREAD

**Issue by DamianSuess** [MicrosoftDocs/xamarin-docs#483]
After installing Visual Studio 2017 (15.7.4) enterprise on a new laptop with "Mobile development with .NET", Android Device Manager will not open. It does not throw an error and there is no logging either. Is there a way to get a verbose output as to why this won't launch?

Android SDK Tools and Android Emulator are installed.  If this is the wrong place to post this, let me know.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e70c0069-6174-0591-a6e0-8e46dedae1eb
* Version Independent ID: 8a8e8863-9562-211e-fc60-eef9b6a95833
* Content: [Android Emulator Troubleshooting - Xamarin](https://docs.microsoft.com/en-us/xamarin/android/get-started/installation/android-emulator/troubleshooting?tabs=vswin)
* Content Source: [docs/android/get-started/installation/android-emulator/troubleshooting.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/android/get-started/installation/android-emulator/troubleshooting.md)
* Product: **xamarin**
* GitHub Login: @mgmclemore
* Microsoft Alias: **mamcle**

**Comment by mgmclemore** [comment]
Hello @DamianSuess, our team can only answer feedback related to documentation. Please report the specifics about your issue by using the **Product Feedback** button at the bottom of the topic page. This takes you to [Developer Community](https://developercommunity.visualstudio.com/spaces/8/index.html), where we gather bugs, issues, and feature suggestions for products. Thank you!

**Comment by DamianSuess** [comment]
@mgmclemore, thank you for the heads up
