### ISSUE TITLE
Error in File for Android: PhoneDialer.cs

### ISSUE THREAD

**Issue by koustavtub** [MicrosoftDocs/xamarin-docs#485]
var context = MainActivity.Instance;

`MainActivity does not contain a definition for instance`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2de3e72c-8948-4dd5-e37f-9cf81e62c127
* Version Independent ID: 7b7c5c7f-4102-8e91-fbe6-7d21fcc8f5be
* Content: [Xamarin.Forms Quickstart - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/get-started/hello-xamarin-forms/quickstart?tabs=vswin#feedback)
* Content Source: [docs/xamarin-forms/get-started/hello-xamarin-forms/quickstart.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/get-started/hello-xamarin-forms/quickstart.md)
* Product: **xamarin**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @koustavtub 

If you proceed to the next step in the tutorial, you'll update your `MainActivity` class with an `Instance` property and your compiler error will vanish.
