### ISSUE TITLE
404 error on link in page

### ISSUE THREAD

**Issue by PhenoNL** [MicrosoftDocs/xamarin-docs#486]
In the topic 'Related Links' is a link to SwitchDemo (sample), this link isn't working anymore (404 error).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 06362667-c374-dfc5-ea7a-77023492065b
* Version Independent ID: 62931423-8168-8df7-23fb-ad48f2029c4c
* Content: [Switch - Xamarin](https://docs.microsoft.com/en-us/xamarin/android/user-interface/controls/switch)
* Content Source: [docs/android/user-interface/controls/switch.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/android/user-interface/controls/switch.md)
* Product: **xamarin**
* GitHub Login: @mgmclemore
* Microsoft Alias: **mamcle**

**Comment by mgmclemore** [comment]
Hi @PhenoNL, thank you for the feedback! This topic has been updated and the changes should be published soon.
