### ISSUE TITLE
The value "fill_parent" is deprecated

### ISSUE THREAD

**Issue by wierikr** [MicrosoftDocs/xamarin-docs#487]
Please use "match_parent" in the example

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5fbbd04c-fbe3-f6d9-fc7b-1df151f788d1
* Version Independent ID: e1829e6f-d78c-5542-718d-1e23858259bf
* Content: [Using the RelativeLayout in Xamarin.Android - Xamarin](https://docs.microsoft.com/en-us/xamarin/android/user-interface/layouts/relative-layout)
* Content Source: [docs/android/user-interface/layouts/relative-layout.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/android/user-interface/layouts/relative-layout.md)
* Product: **xamarin**
* GitHub Login: @mgmclemore
* Microsoft Alias: **mamcle**

**Comment by mgmclemore** [comment]
Hello @wierikr, thank you for the feedback! This topic has been updated and the changes should be published soon.
