### ISSUE TITLE
Camera support

### ISSUE THREAD

**Issue by RobSchoenaker** [MicrosoftDocs/xamarin-docs#490]
Great library, but adding cross platform camera support would be even cooler. And while you're at it, please provide a sample for barcode scanning (QR and others)

**Comment by bradumbaugh** [comment]
Hi @RobSchoenaker, thanks for the comments. This repository is specifically for issues regarding the documentation; for feature requests, it's better to comment on the [Xamarin.Essentials GitHub repository](https://github.com/xamarin/Essentials). That said, it looks like there has already been [an issue created](https://github.com/xamarin/Essentials/issues/176) regarding camera support. Thanks again!
