### ISSUE TITLE
How to do radio options in Xamarin for cross plataform ?

### ISSUE THREAD

**Issue by andersonnsantos** [MicrosoftDocs/xamarin-docs#491]
I need to do radio options in Xamarin for cross plataform with MVVM.
Have you any sample ? 
I'm looking for about this , but find only older components and not cool code for implement it.
Are there any easy way to do it?
Thank for your attention.

**Comment by davidbritch** [comment]
@andersonnsantos 

There's no `RadioButton` control for Xamarin.Forms. So to use radio buttons you'll have to either create your own custom control (http://bsubramanyamraju.blogspot.com/2018/03/how-to-create-radiobutton-in_13.html) or use a third party control (such as the `BindableRadioGroup` in XLabs).
