### ISSUE TITLE
it works on Android, but on iOS

### ISSUE THREAD

**Issue by bakemycode** [MicrosoftDocs/xamarin-docs#494]
I am working on this on my Mac. After the build, it works in Android Emulator, but it doesn't in iOS simulator. When I click the button, Translate, it does and pops up a window to ask me if I want to make a call to the number. After clicking 'Yes', it leads me to

in Main.cs of Phoneword.iOS
UIApplication.Main(args, null, "AppDelegate");

and Visual Studio said there's an exception.

**Comment by davidbritch** [comment]
@bakemycode 

Does the solution in the xamarin-forms-samples repo (https://github.com/xamarin/xamarin-forms-samples/tree/master/Phoneword) have the same problem on your machine?

**Comment by bakemycode** [comment]
@davidbritch 
Hi
Yes, it has same problem. I reviewed source codes in the repo, my source codes and source codes in Microsoft. Everything is fine but  in step 8 and 9, 

<StackLayout VerticalOptions="FillAndExpand"
             HorizontalOptions="FillAndExpand"
             Orientation="Vertical"
             Spacing="15">

it seems these lines are added but it isn't applied to the source code in the repo. Also, it makes same result if I add the lines or not

**Comment by davidbritch** [comment]
The solution in the repo runs perfectly for me. Therefore it sounds more like a problem with your install. You should make sure that your XCode and VSMac installs are fully up to date.
