### ISSUE TITLE
copy and paste error

### ISSUE THREAD

**Issue by DirkMaas** [MicrosoftDocs/xamarin-docs#495]
The phrase "To access the Target Framework setting in Visual Studio for Mac" is used 3 times.  I think the last 2 are errors.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 433a2ad1-1ba6-7860-2012-7fe24e79f254
* Version Independent ID: 5c817523-a465-9818-7411-af390402afce
* Content: [Understanding Android API Levels - Xamarin](https://docs.microsoft.com/en-us/xamarin/android/app-fundamentals/android-api-levels?tabs=vsmac)
* Content Source: [docs/android/app-fundamentals/android-api-levels.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/android/app-fundamentals/android-api-levels.md)
* Product: **xamarin**
* GitHub Login: @mgmclemore
* Microsoft Alias: **mamcle**

**Comment by mgmclemore** [comment]
Hi @DirkMaas, Thank you for the feedback! This topic has been updated and the changes should be published soon.
