### ISSUE TITLE
Win7 Xamarin?

### ISSUE THREAD

**Issue by michaelvsprague** [MicrosoftDocs/xamarin-docs#496]
Is Windows 10 and the newest Visual Studio necessary to take a stab at Windows Phone app development?

Seems odd, coming from the company that leveraged open standards to dominate the PC market space back in the day.

So perhaps I can just develop on the Mac OS version, but that seems wrong.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d8ef5687-ac87-e450-5d84-f17bc91788fe
* Version Independent ID: 1fd9e99d-1119-f1ff-a5d9-d8c58b5c47be
* Content: [Xamarin.Forms Requirements - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/get-started/installation?tabs=vswin)
* Content Source: [docs/xamarin-forms/get-started/installation.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/get-started/installation.md)
* Product: **xamarin**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @michaelvsprague 

Windows Phone 8.1 and 8.0 are not supported in Visual Studio 2017. To maintain these apps, continue to use Visual Studio 2015. To maintain Windows Phone 7.x projects, use Visual Studio 2012.
