### ISSUE TITLE
I guess the first one is Android?

### ISSUE THREAD

**Issue by derKosi** [MicrosoftDocs/xamarin-docs#497]
Platform Differences iOS twice, Android missing.

please delete or comment this post after fixing, thanke.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 38198725-c8f2-3b90-d179-24f86284c4cb
* Version Independent ID: 1dd34451-25d2-9c50-a7f6-bb5b9f763ba0
* Content: [Xamarin.Essentials: Battery - Xamarin](https://docs.microsoft.com/en-us/xamarin/essentials/battery?context=xamarin%2Fxamarin-forms&tabs=android)
* Content Source: [docs/essentials/battery.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/essentials/battery.md)
* Product: **xamarin**
* GitHub Login: @jamesmontemagno
* Microsoft Alias: **jamont**

**Comment by jamesmontemagno** [comment]
This is correct, there are 2 differences for iOS and 1 for UWP.

Maybe we could combine line 2 and 3. That would probably help a bit. Let me do that.

**Comment by jamesmontemagno** [comment]
Addressed, can now be closed @davidbritch as the change should be rolling out for any apis that have platform differences.
