### ISSUE TITLE
XAML Previewer docs are no longer correct.

### ISSUE THREAD

**Issue by CliffAgius** [MicrosoftDocs/xamarin-docs#498]
The XAML Previewer docs are for an older version of VS_Win so the method of turning them on and using them is incorrect.

I have edited and created a PR for the way they are from the current version of VS.

**Comment by davidbritch** [comment]
It exists in 15.7.4 for me.

![previewer](https://user-images.githubusercontent.com/8092460/42317407-3698a406-8044-11e8-8036-32dc98c33b40.PNG)

**Comment by conceptdev** [comment]
Thanks for the PR @CliffAgius, although as noted we cannot merge it until 15.8 is officially released.

Going to close this issue, but if you continue to see an issue with the menu item in the stable version please raise it at [Developer Community](https://developercommunity.visualstudio.com/) via the **Report a problem** feature in Visual Studio.

**Comment by CliffAgius** [comment]
@conceptdev thanks for the update and looking forward to 15.8 being the stable it's much nicer and this tools works, it's never worked for my in 15.7.  Is it because my stable release is Professional but @davidbritch shows a screen shot of Enterprise version?

**Comment by conceptdev** [comment]
There _should_ not be a difference between the SKUs in this area... so perhaps there is an issue. I'm happy to hear the 15.8 previews are better.
