### ISSUE TITLE
Excited to use this but...

### ISSUE THREAD

**Issue by tayminator** [MicrosoftDocs/xamarin-docs#501]
Hi,

This API looks amazing. I make the following call but the application just waits forever and never gets a location:

var location = await Geolocation.GetLocationAsync(request);

I think I followed all the steps correctly:
1) Added Xamarin.Essentials to all of my three projects (shared, Android, iOS) - note: I am only focused on the iOS app right now so did not implement any of the Android-specific pre-requisites
2) Added Privacy - Location When In Use Usage Description to Info.plist
3) Added using Xamarin.Essentials
4) Copy pasted the code to call GetLocationAsync (again, this call never returns)

Is this because I am working in the iOS Simulator, even though I did specify a custom location via Debug &gt; Location &gt; Custom Location?

Looking forward to hearing back!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f0acf3fa-b705-f0cc-b676-eeca60176dfa
* Version Independent ID: 1788a5d5-a3cb-15c8-927c-b6a24810245a
* Content: [Xamarin.Essentials: Geolocation - Xamarin](https://docs.microsoft.com/en-us/xamarin/essentials/geolocation?context=xamarin%2Fios&tabs=ios)
* Content Source: [docs/essentials/geolocation.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/essentials/geolocation.md)
* Product: **xamarin**
* GitHub Login: @jamesmontemagno
* Microsoft Alias: **jamont**

**Comment by bradumbaugh** [comment]
Hi @tayminator, I just tried following the instructions on doc (and using each of the the code snippets there, `GetLocationAsync` and `GetLastKnownLocationAsync`) with the iOS 11 simulator and Xamarin.Essentials 0.8.0-preview, and the location is coming back with a value. I triggered the code by creating an async handler for a button in **Main.storyboard**.

`async partial void UIButton197_TouchUpInside(UIButton sender)`

This repository is only intended for issues with the docs; if you need further support, please take a look at [Developer Community](https://developercommunity.visualstudio.com/spaces/8/index.html).

**Comment by jamesmontemagno** [comment]
Make sure that you have the location set to something such as Apple and it will return for you. 

Else would need to see an example of your code. Also ensure that you added the information to your info.plist that is in the documentation.

**Comment by tayminator** [comment]
Thank you both for your prompt replies. I figured out my issue - I had the code in the constructor of my App.MainPage ContentPage class where I'm guessing the app is not yet ready for invocation of a geolocation request. After moving it into OnAppearing, it works.
