### ISSUE TITLE
Wrong step description.

### ISSUE THREAD

**Issue by Rhywden** [MicrosoftDocs/xamarin-docs#504]
"2. Open the Provisioning options by selecting Project &gt; Provisioning Properties…"

This is wrong. It should be:
"2. Select the iOS project and then Project &gt; ProjectName Properties &gt; iOS Bundle Signing"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5ccadd93-fcc8-6a15-9670-d5af7ee7f6f8
* Version Independent ID: 188007d3-cf20-97ba-137f-64ff25a88e7c
* Content: [Automatic Provisioning for Xamarin.iOS - Xamarin](https://docs.microsoft.com/en-us/xamarin/ios/get-started/installation/device-provisioning/automatic-provisioning?tabs=vswin)
* Content Source: [docs/ios/get-started/installation/device-provisioning/automatic-provisioning.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/ios/get-started/installation/device-provisioning/automatic-provisioning.md)
* Product: **xamarin**
* GitHub Login: @asb3993
* Microsoft Alias: **amburns**

**Comment by bradumbaugh** [comment]
Thanks @Rhywden – appreciate the help! I've fixed this; the update should be published soon.
