### ISSUE TITLE
ProgressBar

### ISSUE THREAD

**Issue by davidortinau** [MicrosoftDocs/xamarin-docs#505]
We are missing guides/docs for ProgressBar and ActivityIndicator. I can only find them in the API docs.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8fdac83c-6d89-7423-b09c-d9a8c7e77d92
* Version Independent ID: 1888bc98-338a-dba3-58bd-96023925b5a7
* Content: [Xamarin.Forms User Interface Views - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/#feedback)
* Content Source: [docs/xamarin-forms/user-interface/index.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/index.md)
* Product: **xamarin**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
We're missing additional docs beyond the two you've identified. However, I'm closing this issue as it is on our radar.
