### ISSUE TITLE
Suggestion : Walkthrough to create binding library from framework

### ISSUE THREAD

**Issue by ananthasivanvk** [MicrosoftDocs/xamarin-docs#506]
It would be of great help for many developers if you could create a  walkthrough on How to create xamarin binding library dll from xcode framework library like Adobe Creative SDK Framework. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cff38c64-d7ea-807e-8382-119b8996dce1
* Version Independent ID: ca4ef9d6-3111-d1b6-030a-642c07bfd29a
* Content: [Binding Native Frameworks - Xamarin](https://docs.microsoft.com/en-us/xamarin/cross-platform/macios/binding/objective-sharpie/platform/native-frameworks#feedback)
* Content Source: [docs/cross-platform/macios/binding/objective-sharpie/platform/native-frameworks.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/cross-platform/macios/binding/objective-sharpie/platform/native-frameworks.md)
* Product: **xamarin**
* GitHub Login: @asb3993
* Microsoft Alias: **amburns**

**Comment by bradumbaugh** [comment]
Thanks for the suggestion @ananthasivanvk. I'll make a note that a better example of binding a framework would be helpful.

In the meantime, there are some updated Xamarin University classes about creating bindings for Objective-C that might be worth taking a look at if you have access to them:

- https://university.xamarin.com/classes/track/all#building-an-objective-c-bindings-library
- https://university.xamarin.com/classes/track/all#build-an-objective-c-bindings-library-with-objective-sharpie
