### ISSUE TITLE
Adding project reference step causes compilation problems.

### ISSUE THREAD

**Issue by KevM** [MicrosoftDocs/xamarin-docs#508]
&gt; Add a project reference from the UITest project to the Xamarin.Android project

On VS 2017 15.7.4 this step causes the test project to not get past the nuget restore phase of the build with the following error(s):
```
NU1201	Project Android2.Android is not compatible with net461 (.NETFramework,Version=v4.6.1) / win-x64. Project Android2.Android supports: monoandroid71 (MonoAndroid,Version=v7.1)

NU1201	Project Android2.Android is not compatible with net461 (.NETFramework,Version=v4.6.1) / win-x86. Project Android2.Android supports: monoandroid71 (MonoAndroid,Version=v7.1)				
		
NU1201	Project Android2.Android is not compatible with net461 (.NETFramework,Version=v4.6.1) / win. Project Android2.Android supports: monoandroid71 (MonoAndroid,Version=v7.1)

NU1201	Project Android2.Android is not compatible with net461 (.NETFramework,Version=v4.6.1). Project Android2.Android supports: monoandroid71 (MonoAndroid,Version=v7.1)
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b2f6b353-936e-2536-37cb-b8190aea7743
* Version Independent ID: 4f27ec32-a6f7-3de5-2635-87bacf04e724
* Content: [Automating Xamarin.Forms Testing with App Center - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/deploy-test/uitest-and-test-cloud?tabs=vswin)
* Content Source: [docs/xamarin-forms/deploy-test/uitest-and-test-cloud.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/deploy-test/uitest-and-test-cloud.md)
* Product: **xamarin**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by topgenorth** [comment]
Hi @KevM - I just tried this out  with VS2017 15.7.5, and I didn't get the same error.  However, my solution was created fairly recently (in the past week).  This doesn't sound like an issue with the docs, but perhaps a problem that existed in VS2017 15.7.4 and/or possibly project files that were created with an out-of-date template.  

I'd suggest updating to 15.7.5 and seeing if this happens again.  If it does, then the next best course of action would be to file a bug on [Developer Community](https://developercommunity.visualstudio.com/spaces/8/index.html).

**Comment by DamianSuess** [comment]
I too am having the same exact issue, even with vs 15.7.5. I assume, there is no way to run UITest offline anymore?

**Comment by bytemi** [comment]
I also had this issue. It ended up working after i removed the references to android and ios project (only reference the shared project)

**Comment by kchan4** [comment]
I also having the same problem.  
My visual studio is 15.8.1, Shared project, Android and iOS is using .NET Standard 2.
@bytemi Can you please tell me how are you able to run the UI Test offine without referencing the android and ios project?

**Comment by seansparkman** [comment]
I am still getting this error.  When creating a new Xamarin.Forms project and then creating a new "Xamarin.UITest Cross-Platform Test Project."  I am not the only one.  There is a stackoverflow issue on this.  (https://stackoverflow.com/questions/51296837/xamarin-uitesting-nu1201-error-android-8-1-is-incompatible-with-netframework-4)  They are recommending that you just install the app and run it with the bundle id.

**Here is the error message.**
Severity	Code	Description	Project	File	Line	Suppression State
Error	NU1201	Project Automated.Testing.Android is not compatible with net461 (.NETFramework,Version=v4.6.1). Project Automated.Testing.Android supports: monoandroid81 (MonoAndroid,Version=v8.1)	Automated.Testing.Test	C:\Users\seans\source\repos\Automated.Testing\Automated.Testing.Test\Automated.Testing.Test.csproj	1	

**Here is the visual studio information:**
Microsoft Visual Studio Enterprise 2017 
Version 15.8.7
VisualStudio.15.Release/15.8.7+28010.2046
Microsoft .NET Framework
Version 4.7.03056

Installed Version: Enterprise

Visual C++ 2017   00369-60000-00001-AA052
Microsoft Visual C++ 2017

Application Insights Tools for Visual Studio Package   8.13.10627.1
Application Insights Tools for Visual Studio

ASP.NET and Web Tools 2017   15.8.05085.0
ASP.NET and Web Tools 2017

ASP.NET Core Razor Language Services   15.8.31590
Provides languages services for ASP.NET Core Razor.

ASP.NET Web Frameworks and Tools 2012   4.0.30625.0
For additional information, visit https://www.asp.net/

ASP.NET Web Frameworks and Tools 2017   5.2.60618.0
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   15.8.05023.0
Azure App Service Tools v3.0.0

Azure Data Lake Node   1.0
This package contains the Data Lake integration nodes for Server Explorer.

Azure Data Lake Tools for Visual Studio   2.3.3000.2
Microsoft Azure Data Lake Tools for Visual Studio

Azure Functions and Web Jobs Tools   15.8.05023.0
Azure Functions and Web Jobs Tools

Azure Stream Analytics Tools for Visual Studio   2.3.3000.2
Microsoft Azure Stream Analytics Tools for Visual Studio

Bundler & Minifier   2.8.396
Adds support for bundling and minifying JavaScript, CSS and HTML files in any project.

C# Tools   2.9.0-beta8-63208-01
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Extensibility Message Bus   1.1.49 (remotes/origin/d15-8@ee674f3)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

Fabric.DiagnosticEvents   1.0
Fabric Diagnostic Events

JavaScript Language Service   2.0
JavaScript Language Service

JavaScript Project System   2.0
JavaScript Project System

JustDecompilePackage2017 Extension   1.0
JustDecompilePackage2017 Visual Studio Extension Detailed Info

Microsoft Azure HDInsight Azure Node   2.3.3000.2
HDInsight Node under Azure Node

Microsoft Azure Hive Query Language Service   2.3.3000.2
Language service for Hive query

Microsoft Azure Service Fabric Tools for Visual Studio   2.3
Microsoft Azure Service Fabric Tools for Visual Studio

Microsoft Azure Stream Analytics Language Service   2.3.3000.2
Language service for Azure Stream Analytics

Microsoft Azure Stream Analytics Node   1.0
Azure Stream Analytics Node under Azure Node

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 2017 - v2.9.10730.2

Microsoft Continuous Delivery Tools for Visual Studio   0.4
Simplifying the configuration of Azure DevOps pipelines from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft Library Manager   1.0
Install client-side libraries easily to any web project

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ Wizards   1.0
Microsoft Visual C++ Wizards

Microsoft Visual Studio Tools for Containers   1.1
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

MLGen Package Extension   1.0
MLGen Package Visual Studio Extension Detailed Info

Mono Debugging for Visual Studio   4.11.11-pre (8fb558f)
Support for debugging Mono processes with Visual Studio.

Node.js Tools   1.4.20907.4 Commit Hash:f048d52e417a8902dea9e42828b7fdab92d4aaaa
Adds support for developing and debugging Node.js apps in Visual Studio

NuGet Package Manager   4.6.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

Redgate ReadyRoll   1.17.18155.10346
Extend DevOps processes to your SQL Server databases and safely automate database deployments.

Visit https://www.red-gate.com/readyroll for more information.

Copyright (C) 2011 Red Gate Software Ltd. All rights reserved.

This software contains components from Component Owl.
SQL Server is a registered trademark of Microsoft Corporation.
Visual Studio is a registered trademark of Microsoft Corporation.

ReadyRoll contains code from the following open source software:

NuGet https://www.nuget.org/
SQL LocalDB Wrapper https://github.com/martincostello/sqllocaldb
Autofac https://autofac.org/
Json.NET https://json.net/
MahApps.Metro http://mahapps.com/
SemVer https://github.com/maxhauser/semver
Log4Net http://logging.apache.org/log4net/
StringTemplate https://github.com/antlr/stringtemplate4
Extended WPF Toolkit https://wpftoolkit.codeplex.com/
Code InfoBox VSX http://www.codeproject.com/Articles/55196/Code-InfoBox-Visual-Studio-Extension-VSX
OctoPack https://github.com/OctopusDeploy/OctoPack
SQLite https://sqlite.org/

This product contains icons from http://www.visualpharm.com distributed under a free backlink license.

For license details or other notices relating to the above software, please see NOTICE.TXT and EULA.rtf in the ReadyRoll application folder.
    

Redgate SQL Prompt   9.2.0.5601
Write, format, and refactor SQL effortlessly

ResourcePackage Extension   1.0
ResourcePackage Visual Studio Extension Detailed Info

ResourcePackage Extension   1.0
ResourcePackage Visual Studio Extension Detailed Info

Snapshot Debugging Extension   1.0
Snapshot Debugging Visual Studio Extension Detailed Info

SQL Server Data Tools   15.1.61808.07020
Microsoft SQL Server Data Tools

ToolWindow Extension   1.0
ToolWindow Visual Stuido Extension Detailed Info

ToolWindowHostedEditor   1.0
Hosting json editor into a tool window

TypeScript Tools   15.8.20822.2001
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   2.9.0-beta8-63208-01
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools 10.2 for F# 4.5   15.8.0.0.  Commit Hash: 55a3dc3231c95c77f81ee53f7d29152029da7408.
Microsoft Visual F# Tools 10.2 for F# 4.5

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Tools for Containers   1.0
Visual Studio Tools for Containers

Visual Studio Tools for Universal Windows Apps   15.0.28010.2046
The Visual Studio Tools for Universal Windows apps allow you to build a single universal app experience that can reach every device running Windows 10: phone, tablet, PC, and more. It includes the Microsoft Windows 10 Software Development Kit.

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

Xamarin   4.11.0.776 (d15-8@1ae9b59d7)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   4.15.9 (d000f568b)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Live Reload   0.3.27 (remotes/origin/dev@207abf7)
Provides live reload capabilities for Xamarin XAML.

Xamarin Templates   1.1.116 (9619170)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   9.0.0.19 (HEAD/a8a3b0ec7)
Xamarin.Android Reference Assemblies and MSBuild support.

Xamarin.iOS and Xamarin.Mac SDK   12.0.0.15 (84552a4)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.
