### ISSUE TITLE
Has Microsoft.data.Sqlite replaced Mono.data.sqlite?

### ISSUE THREAD

**Issue by ALEITZINGER** [MicrosoftDocs/xamarin-docs#509]
Hi,
I'm new to Xamarin. I'm building new Xamarin app and want to use the correct (latest) libraries and packages.
I believe that Xamarin Forms + .NET Standard 2.0 + Microsoft.data.Sqlite is the correct combination? 
Is this correct?  
The Mono.data.Sqlite package on github looks out of date (stale), no updates or changes in quite some time and from various posts and forum feedback it appears that the Microsoft.data.sqlite package should be used instead?
If this is correct then it would be helpful if this documentation was updated to reflect that.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 260d25e8-089b-b8df-07fc-60e9c039cd21
* Version Independent ID: 5907b2dd-9368-2f7f-5f5d-f9bcc9623e35
* Content: [Using ADO.NET with Android - Xamarin](https://docs.microsoft.com/en-us/xamarin/android/data-cloud/data-access/using-adonet?tabs=vswin)
* Content Source: [docs/android/data-cloud/data-access/using-adonet.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/android/data-cloud/data-access/using-adonet.md)
* Product: **xamarin**
* GitHub Login: @mgmclemore
* Microsoft Alias: **mamcle**

**Comment by topgenorth** [comment]
@ALEITZINGER I've asked around, and it seems that the best choice for an Android app is still `Mono.Data.Sqlite`.  I believe that `Microsoft.Data.Sqlite` is primary for desktop apps and/or ASP.NET.

**Comment by bricelam** [comment]
Microsoft.Data.Sqlite is supported on Xamarin.

See these Microsoft.Data.Sqlite docs:

* [Comparison to System.Data.SQLite](https://docs.microsoft.com/dotnet/standard/data/sqlite/compare) (and Mono.Data.Sqlite)
* [Xamarin](https://docs.microsoft.com/dotnet/standard/data/sqlite/xamarin)

**Comment by conceptdev** [comment]
thanks @bricelam - i don't suppose you have a sample anywhere? i tried this before (there's another issue in our backlog) but wasn't able to immediately get it working... planning to take another look at some point

**Comment by bricelam** [comment]
No samples specific to Xamarin, but there are some general ones here: https://github.com/dotnet/samples/tree/master/snippets/standard/data/sqlite
