### ISSUE TITLE
Is there a link to the full code?

### ISSUE THREAD

**Issue by MSBassSinger** [MicrosoftDocs/xamarin-docs#510]
The code snippets are helpful in explaining the basics, but insufficient for making a working example.  Was a link to the code inadvertently left off?

It would be appreciated if this article were revised to include that link, perhaps a little more explicitly for those of us not used to the format.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ec31ee56-e3b9-a70a-a4ef-80fdf58e7249
* Version Independent ID: 766b5774-50bf-f43f-800d-48b5c6c66509
* Content: [Xamarin.Forms Master-Detail Page - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/navigation/master-detail-page#creating-a-masterdetailpage)
* Content Source: [docs/xamarin-forms/app-fundamentals/navigation/master-detail-page.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/app-fundamentals/navigation/master-detail-page.md)
* Product: **xamarin**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @MSBassSinger 

The links to the samples are at the end of each doc, in the Related Links section.
