### ISSUE TITLE
Outdated classes

### ISSUE THREAD

**Issue by FiskaniC** [MicrosoftDocs/xamarin-docs#511]
Hi Guys,

There seems to be outdated classes that are being referenced which doesn't allow for some things to work. 

Could we please get an updated version.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 11f5b457-d99a-06d4-d203-f9eeaa27e0d9
* Version Independent ID: b23b3a5d-b63b-dfe1-bb46-94f57c907be5
* Content: [Authenticating Users with Azure Active Directory B2C - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/data-cloud/authentication/azure-ad-b2c)
* Content Source: [docs/xamarin-forms/data-cloud/authentication/azure-ad-b2c.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/data-cloud/authentication/azure-ad-b2c.md)
* Product: **xamarin**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by conceptdev** [comment]
Hi @FiskaniC while we're investigating, did you see this [alternative sample](https://azure.microsoft.com/en-us/resources/samples/active-directory-b2c-xamarin-native/)?

**Comment by davidbritch** [comment]
Hi @FiskaniC 

What classes are outdated?

The sample the doc links to, from the Related Links section at the end of the doc, builds fine.

**Comment by davidbritch** [comment]
Closing this issue due to lack of a response.
