### ISSUE TITLE
Useless Documentation

### ISSUE THREAD

**Issue by markolbert** [MicrosoftDocs/xamarin-docs#512]
Among many other problems, there is not "Project -&gt; Provisioning Properties..." menu item. Does anyone at Microsoft bother to check this junk before they post it?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5ccadd93-fcc8-6a15-9670-d5af7ee7f6f8
* Version Independent ID: 188007d3-cf20-97ba-137f-64ff25a88e7c
* Content: [Automatic Provisioning for Xamarin.iOS - Xamarin](https://docs.microsoft.com/en-us/xamarin/ios/get-started/installation/device-provisioning/automatic-provisioning?tabs=vswin#feedback)
* Content Source: [docs/ios/get-started/installation/device-provisioning/automatic-provisioning.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/ios/get-started/installation/device-provisioning/automatic-provisioning.md)
* Product: **xamarin**
* GitHub Login: @asb3993
* Microsoft Alias: **amburns**

**Comment by bradumbaugh** [comment]
Hi @markolbert – thanks for pointing out the mistake! I've fixed this, and it should be published soon.  

In the mean time, to get to the bundle signing options, right-click on your project name in the **Solution Explorer**, choose **Properties**, and navigate to the **iOS Bundle Signing** tab. 

Thanks again for calling this out.
