### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by PaulWWeaver** [MicrosoftDocs/xamarin-docs#513]
I get the following error when I try to compile the custom control:

Error CS0246	The type or namespace name 'CameraOptions' could not be found (are you missing a using directive or an assembly reference?)	

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e3b172d5-2dc1-88e7-ca23-96e87ae24a42
* Version Independent ID: 1ca93300-738f-4af7-b47c-0e170b7205a4
* Content: [Implementing a View - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/custom-renderer/view)
* Content Source: [docs/xamarin-forms/app-fundamentals/custom-renderer/view.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/app-fundamentals/custom-renderer/view.md)
* Product: **xamarin**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @PaulWWeaver 

Have you tried looking at the sample that accompanies this guide? There's a link to it in the Related Links section at the end of the doc.

**Comment by davidbritch** [comment]
The sample builds fine so closing this issue.
