### ISSUE TITLE
What is TodoItemManager

### ISSUE THREAD

**Issue by c-lamont** [MicrosoftDocs/xamarin-docs#514]
There is no information on the 'TodoItemManager'.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f2f7318c-8cd3-1aea-1f5e-e14955e2fa22
* Version Independent ID: 655cb554-cd03-e6ae-f7dd-9e2ba18a4a28
* Content: [Sending Push Notifications from Azure Mobile Apps - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/data-cloud/push-notifications/azure#feedback)
* Content Source: [docs/xamarin-forms/data-cloud/push-notifications/azure.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/data-cloud/push-notifications/azure.md)
* Product: **xamarin**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
See https://docs.microsoft.com/en-us/xamarin/xamarin-forms/data-cloud/walkthrough

Also see the sample for that doc (linked from the Related Links section at the end of the doc).
