### ISSUE TITLE
Build host connected and valid Apple ID in Fastlane, but Apple ID shows as None and Team dropdown box is empty 

### ISSUE THREAD

**Issue by zanoo** [MicrosoftDocs/xamarin-docs#515]
I'm connected to my Mac build host, which I've used before for building this project. I have the same Apple ID I've used to build the project as well. But after updating to Visual Studio 15.7.4, when I go to iOS Project Properties -&gt; iOS Bundle Signing and select Automatic Provisioning, the Apple ID label text is "None" and the Team dropdown box is empty. What can I do to troubleshoot this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5ccadd93-fcc8-6a15-9670-d5af7ee7f6f8
* Version Independent ID: 188007d3-cf20-97ba-137f-64ff25a88e7c
* Content: [Automatic Provisioning for Xamarin.iOS - Xamarin](https://docs.microsoft.com/en-us/xamarin/ios/get-started/installation/device-provisioning/automatic-provisioning?tabs=vswin)
* Content Source: [docs/ios/get-started/installation/device-provisioning/automatic-provisioning.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/ios/get-started/installation/device-provisioning/automatic-provisioning.md)
* Product: **xamarin**
* GitHub Login: @asb3993
* Microsoft Alias: **amburns**

**Comment by bradumbaugh** [comment]
Hi @zanoo, try this: in Visual Studio 2017, select **Tools > Options**. Then, in the **Options** window, select **Xamarin > Apple Accounts** ([docs about Xamarin's tools for Apple account management](https://docs.microsoft.com/en-us/xamarin/cross-platform/macios/apple-account-management?tabs=vsmac)). Make sure that your Apple account is still listed here; if not, add it. Then, go back to the **iOS Bundle Signing** tab and see if it's available there. If this doesn't work, please feel free to post on [Developer Community](https://developercommunity.visualstudio.com/spaces/8/index.html) for support. Thank you!
