### ISSUE TITLE
Spelling error

### ISSUE THREAD

**Issue by aldrashan** [MicrosoftDocs/xamarin-docs#516]
"USe an Image for a button" has to be "Use an image for a button".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2c77edb3-e48a-5483-6129-ee40fd60d54b
* Version Independent ID: c25825c9-4339-84a6-4ad4-9255b5b6a0d0
* Content: [Buttons in Xamarin.iOS - Xamarin](https://docs.microsoft.com/en-us/xamarin/ios/user-interface/controls/buttons)
* Content Source: [docs/ios/user-interface/controls/buttons.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/ios/user-interface/controls/buttons.md)
* Product: **xamarin**
* GitHub Login: @bradumbaugh
* Microsoft Alias: **brumbaug**

**Comment by bradumbaugh** [comment]
Hi @aldrashan – thanks for calling this out. I've fixed this and a few other things about this doc. Should be published soon!
