### ISSUE TITLE
missed important step for Non-Xamarin people

### ISSUE THREAD

**Issue by nkolchakov** [MicrosoftDocs/xamarin-docs#517]
I think it's important step to be added, for people who are not experienced in Xamarin and read this tutorial.
It took me long time to figure that I need to change this line to the new WebViewPage

public partial class App : Application
	{
		public App ()
		{
			InitializeComponent();
			MainPage = new HybridWebViewPage();
		}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9c1bd30c-6e7a-df38-8c20-dff7361e901f
* Version Independent ID: 013c6027-db9a-6039-3404-2e4f717133a9
* Content: [Implementing a HybridWebView - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/custom-renderer/hybridwebview)
* Content Source: [docs/xamarin-forms/app-fundamentals/custom-renderer/hybridwebview.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/app-fundamentals/custom-renderer/hybridwebview.md)
* Product: **xamarin**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @nkolchakov 

Every Xamarin.Forms guide includes a sample, that has full code. The link to each sample is in the Related Links section at the end of the doc. Did you look at the sample?

**Comment by nkolchakov** [comment]
Yes but and found that missing line right after I deleted MainPage.xaml since it wasn't present in the sample project either, and it didn't build at that line in the code snippet int App class.
It's just hard to find that line of code alone in the whole sample.

But that may just be result of my incopetence  in Xamarin, although If I had this problem, someone else might too.
Nice tutorial tho, very detailed.

**Comment by conceptdev** [comment]
Thanks for your feedback @nkolchakov, I'm glad you were able to resolve your issue. The structure of a Xamarin.Forms app (like `MainPage`) is discussed in the getting started and introduction docs, and the [App class](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/application-class). We'll certainly consider how we can make this information more discoverable for new users.
