### ISSUE TITLE
Typo in URL text

### ISSUE THREAD

**Issue by Powerhelmsman** [MicrosoftDocs/xamarin-docs#520]
This issue was created by @nishanthmahe from https://github.com/MicrosoftDocs/feedback/issues/501 

Typo in URL text
Typo in URL text in the below mentioned site:
https://docs.microsoft.com/en-us/xamarin/android/app-fundamentals/services/foreground-services
Screenshot attached:

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 14dfecf6-b596-61af-ef6c-c0b65838bd45
* Version Independent ID: 7e1e4994-270d-5383-7d2d-f6d1cd1e1992
* Content: [Foreground Services - Xamarin](https://docs.microsoft.com/en-us/xamarin/android/app-fundamentals/services/foreground-services)
* Content Source: [docs/android/app-fundamentals/services/foreground-services.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/android/app-fundamentals/services/foreground-services.md)
* Product: **xamarin**
* GitHub Login: @topgenorth
* Microsoft Alias: **toopge**

**Comment by conceptdev** [comment]
Thanks @nishanthmahe, this has been fixed!
