### ISSUE TITLE
Can't install SDK

### ISSUE THREAD

**Issue by pedroyan** [MicrosoftDocs/xamarin-docs#521]
Hi,

I tried modifying my Visual Studio Enterprise IDE and on the Individual components tab there is no such option as "Android SDK Manager"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dac28e18-875a-cb51-a031-717692255d0a
* Version Independent ID: f2e625c7-18a7-c090-fa92-9d635ac39164
* Content: [Setting up the Android SDK for Xamarin.Android - Xamarin](https://docs.microsoft.com/en-us/xamarin/android/get-started/installation/android-sdk?tabs=vswin)
* Content Source: [docs/android/get-started/installation/android-sdk.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/android/get-started/installation/android-sdk.md)
* Product: **xamarin**
* GitHub Login: @mgmclemore
* Microsoft Alias: **mamcle**

**Comment by pedroyan** [comment]
![image](https://user-images.githubusercontent.com/11574849/42523323-ce191eca-8443-11e8-810e-be9ec91bf12f.png)

**Comment by mgmclemore** [comment]
Hi @pedroyan, thank you for the feedback!  The Android SDK Manager is no longer a separate option as it is now installed as part of the **Mobile development with .NET** workload. We've updated the docs with this change &ndash; it should be published soon.
