### ISSUE TITLE
iOS Player ignores Directory.Build.props

### ISSUE THREAD

**Issue by robv8r** [MicrosoftDocs/xamarin-docs#522]
When deploying an iOS app to the new Xamarin Live Player (Preview), the compiler ignores Directory.Build.props and Directory.Build.targets files.  Our build process uses these files extensively.  For more information about Directory.Build.props (and targets), see https://docs.microsoft.com/en-us/visualstudio/msbuild/customize-your-build

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 79320e9a-8b52-1c24-0a5b-a7ef6a32b519
* Version Independent ID: 88548723-6f1b-50c1-163c-a9e151b024e8
* Content: [Xamarin Live Player Setup - Xamarin](https://docs.microsoft.com/en-us/xamarin/tools/live-player/install?tabs=ios%2Cwindows)
* Content Source: [docs/tools/live-player/install.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/tools/live-player/install.md)
* Product: **xamarin**
* GitHub Login: @topgenorth
* Microsoft Alias: **toopge**

**Comment by robv8r** [comment]
I should also add that I'm using the latest versions of Xamarin.Forms, Visual Studio 2017, and have updated all NuGet packages.  I received the above error while working on a brand new Xamarin.Forms project with a NetStandard library on Windows 10 1803.

In my case, I'm including common source code files in all projects.  For instance, a common SharedAssemblyInfo.cs file.  I'm also setting common MSBuild Properties for all projects.

Because the iPhone Live Player ignores the Directory.Build.props/targets files, the iOS build initiated by the Live Player fails.

An easy way to reproduce the issue is to add a file named Directory.Build.targets in the same directory as your iOS csproj file.  Add the following contents:

```
<Project>
  <Target Name="BeforeBuild" BeforeTargets="Build">
    <WriteLinesToFile
      File="$(TargetDir)Build.txt"
      Overwrite="false"
      Lines="$([System.DateTime]::Now.ToString()) [Before Build]" />
  </Target>
</Project>
```

When you build the application in Visual Studio, you will see a file added to your bin\Debug directory (or where ever your TargetDir points to).  The file is named "Build.txt" and will have a single entry:

```
7/10/2018 12:00:00 PM [Before Build]
```

A similar entry will be added every time you build.

When you attempt to Debug the application in an iPhone Live Player (pre-release), no entry in the file is made.  

You can also test this with a ```<Message Importance="High" Text="Blah" />``` instead of writing to a file.  In any case, Directory.Build.props/targets are ignored when attempting to debug on Live Player.

**Comment by bradumbaugh** [comment]
Hi @robv8r – thanks for calling this out, and for the detail. That said, this repository is only for issues related specifically to the documentation. To report bugs and feature requests, and get support, take a look at [Developer Community](https://developercommunity.visualstudio.com/spaces/8/index.html). Thanks for your help in improving the products!

**Comment by robv8r** [comment]
[Added](https://developercommunity.visualstudio.com/content/problem/308904/ios-live-player-ignores-directorybuildprops.html) to Developer Community.
