### ISSUE TITLE
Error in Phoneword.UWP PhoneDialer.cs

### ISSUE THREAD

**Issue by casender** [MicrosoftDocs/xamarin-docs#523]
Error said didn't offer "PhoneCallHistoryManager.RequestStoreAsync(PhoneCallHistoryStoreAccessType)" accessType ....
I have checked my code and it should be the same as the tutorial, anyone help?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2de3e72c-8948-4dd5-e37f-9cf81e62c127
* Version Independent ID: 7b7c5c7f-4102-8e91-fbe6-7d21fcc8f5be
* Content: [Xamarin.Forms Quickstart - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/get-started/hello-xamarin-forms/quickstart?tabs=vswin)
* Content Source: [docs/xamarin-forms/get-started/hello-xamarin-forms/quickstart.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/get-started/hello-xamarin-forms/quickstart.md)
* Product: **xamarin**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by casender** [comment]
After I put one accessType, another error occurs, "PhoneCallHistoryStore" doesn't have method "GetDefaultLineAsync". Is this tutorial compatible to the latest version?

**Comment by JKleinsasser** [comment]
I just went completely through the entire article hand coding it yesterday and it worked perfectly... I had a couple small type errors I had to patch up and then it worked. So yes, if you don't miss a step it should work fine

**Comment by JKleinsasser** [comment]
Also make sure that the namespaces at the top match with the ones used in the project.
That was my main problem, as well as making sure to check all the device specific phone and calling options they want you too.

**Comment by dadamnoel** [comment]
The UWP/PhoneDialer.cs references PhoneLine and PhoneCallManager that are throwing errors during build.  Where are these supposed to be declared/defined?

**Comment by dadamnoel** [comment]
Sorry my comment wasn't meant for this post.

**Comment by conceptdev** [comment]
@casender the Types you mention are only for the UWP version of the project (see step 26).

You can view the code on GitHub https://github.com/xamarin/xamarin-forms-samples/tree/master/Phoneword to verify everything is in the right place (or get the ZIP from the *Download* button on the [sample page](https://developer.xamarin.com/samples/xamarin-forms/Phoneword/)).

**Comment by casender** [comment]
@conceptdev Thanks for the comment, will check the code you mentioned.

**Comment by casender** [comment]
@JKleinsasser thanks for your confirmation, will double check document and other resources.

**Comment by mbalcerzyk** [comment]
@dadamnoel, double check the references for UWP project. Even if you build for desktop it had to be Mobile package. My list of extensions was much longer, I had the same error.
