### ISSUE TITLE
Intellisense package for Xamarin

### ISSUE THREAD

**Issue by JKleinsasser** [MicrosoftDocs/xamarin-docs#525]
Intellisense for Xamarin doesn't come with the Visual Studio package.
This can cause a bit of discomfort and end up awkward for newer developers like myself heading into a newer area of development, so I would suggest you put a notice somewhere about the Nuget package you can download for the project.
Lucky for me  had read several forums where people had this problem so I got intellisense installed in my project right as I started.
Thank You and have a good day :)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2de3e72c-8948-4dd5-e37f-9cf81e62c127
* Version Independent ID: 7b7c5c7f-4102-8e91-fbe6-7d21fcc8f5be
* Content: [Xamarin.Forms Quickstart - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/get-started/hello-xamarin-forms/quickstart?tabs=vswin)
* Content Source: [docs/xamarin-forms/get-started/hello-xamarin-forms/quickstart.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/get-started/hello-xamarin-forms/quickstart.md)
* Product: **xamarin**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @JKleinsasser 

You don't need to install an additional package to get intellisense for Xamarin.Forms. It ships as part of Xamarin.Forms.

**Comment by JKleinsasser** [comment]
It doesn't come with just the visual studio package though... I installed Visual studio and added the Xamarin packages. You probably have to download directly from Xamarin to get the intellisense which is probably why it's confusing

**Comment by davidbritch** [comment]
Xamarin.Forms ships as a NuGet package, available from the NuGet gallery. That NuGet package includes the intellisense data.

**Comment by davidbritch** [comment]
Hi @JNickVA1 

I just tried VS2017 15.8.1 and Xamarin.Forms 3.1.0.697729 and received intellisense in the XAML editor.
