### ISSUE TITLE
Code Locations

### ISSUE THREAD

**Issue by sirwes** [MicrosoftDocs/xamarin-docs#529]
I'm very confused as to where in my Xamarin Forms application I put all of these code pieces. For instance, I don't know if the Custom Map should go in my App section, App.Droid section or App.IOS section. That as well as the Custom Pin class and the Custom Renderer classes

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 591d1079-dec9-5797-eb4f-4d11b56fcbd9
* Version Independent ID: 0169a2c9-a004-d5fd-7a24-855664f2d8b5
* Content: [Customizing a Map Pin - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/custom-renderer/map/customized-pin)
* Content Source: [docs/xamarin-forms/app-fundamentals/custom-renderer/map/customized-pin.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/app-fundamentals/custom-renderer/map/customized-pin.md)
* Product: **xamarin**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by sirwes** [comment]
Following the code provided, everything works except my CustomMapRenderer classes inside of my App.Droid and App.iOS. They don't recognize CustomMap as a class inside my App section. Nor do they recognize the CustomPin class

**Comment by davidbritch** [comment]
Hi @sirwes 

Most docs have an accompanying sample. If you go to the Related Links section at the bottom of each page there's a link to the sample. The sample contains full code for the app discussed in the doc. So you should be able to get the answers you seek from the sample.
