### ISSUE TITLE
OnEventNameChanged

### ISSUE THREAD

**Issue by c-lamont** [MicrosoftDocs/xamarin-docs#53]
No explanation of `OnEventNameChanged` and is not implemented anywhere.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b06aff09-e5dd-9bba-d158-f3b61984d735
* Version Independent ID: 72c8ef2a-01f3-aee4-9a84-11995565b2d3
* Content: [Reusable EventToCommandBehavior - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/behaviors/reusable/event-to-command-behavior)
* Content Source: [docs/xamarin-forms/app-fundamentals/behaviors/reusable/event-to-command-behavior.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/app-fundamentals/behaviors/reusable/event-to-command-behavior.md)
* Service: **unspecified**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi Chris,

The `OnEventNameChanged` method can be found in the linked sample for the page (link at the bottom of the page in the Related Links section.

**Comment by c-lamont** [comment]
Hi David,

Thanks, did not see that.
