### ISSUE TITLE
Live Reload not available for VS 17 Enterprise?

### ISSUE THREAD

**Issue by stealthcold** [MicrosoftDocs/xamarin-docs#531]
Hello,

Live Reload is not available for VS17 Enterprise?
It gives me an error:

VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.

**Comment by bradumbaugh** [comment]
Hi @stealthcold, I just gave the installation process a try on Visual Studio 2017 Enterprise and didn't have any problems, so I believe the doc is correct  – I'm not sure why that wouldn't have worked for you. For support, please leave a comment on [Developer Community](https://developercommunity.visualstudio.com/spaces/8/index.html). Thank you1

**Comment by stealthcold** [comment]
Helllo @bradumbaugh ! 
After your answer, I updated my VS through the installer to the latest version (I was 2 releases behind).

And the plugin installation worked! Maybe had some missing package.. who knows!

Anyway, thanks for the help!

**Comment by bradumbaugh** [comment]
Great to hear that it's working for you @stealthcold – and thanks for the update in case anyone else hits the same issue. Much appreciated.
