### ISSUE TITLE
Xamarin.EssentialsGeolocation: CalculateDistance example error

### ISSUE THREAD

**Issue by djaus2** [MicrosoftDocs/xamarin-docs#532]
The Calculate distance example on the Xamarin.Essentials Geolocation page seems to be in error. You get a Error Mesaage:

No Overload for method **CalculateDistance** takes 3 arguments

Location boston = new Location(42.358056, -71.063611);
Location sanFrancisco = new Location(37.783333, -122.416667);
**double miles = Location.CalculateDistance(boston, sanFrancisco, DistanceUnits.Miles);**

Change the last line to:
**double miles = boston .CalculateDistance(sanFrancisco, DistanceUnits.Miles);**

:)
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f0acf3fa-b705-f0cc-b676-eeca60176dfa
* Version Independent ID: 1788a5d5-a3cb-15c8-927c-b6a24810245a
* Content: [Xamarin.Essentials: Geolocation - Xamarin](https://docs.microsoft.com/en-us/xamarin/essentials/geolocation?tabs=android)
* Content Source: [docs/essentials/geolocation.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/essentials/geolocation.md)
* Product: **xamarin**
* GitHub Login: @jamesmontemagno
* Microsoft Alias: **jamont**

**Comment by bradumbaugh** [comment]
Hi @djaus2, thanks for the comment. I tried the code as it stands in the docs, using the latest version of Xamarin.Essentials (0.8.0-preview), and it does work correctly. 

It looks like there was [a bug](https://github.com/xamarin/Essentials/issues/306) fixed for 0.8.0-preview that might be related to the issue you're seeing?

However, the approach you mentioned works as well.

**Comment by jamesmontemagno** [comment]
Both are actually valid as we do have https://github.com/xamarin/Essentials/blob/master/Xamarin.Essentials/Types/LocationExtensions.shared.cs

We can add documentation to this too.

**Comment by wltdaniel** [comment]
How do we track LocationChangedEvent? need to get periodic location updates,or can we use a timer that fetches location

**Comment by jamesmontemagno** [comment]
We have a feature request open to add this capability into a future release.
