### ISSUE TITLE
FlexLayout Padding

### ISSUE THREAD

**Issue by SlyOtis** [MicrosoftDocs/xamarin-docs#534]
Adding padding to a flexlayout just skews the content to the right and does not work as intended.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b954b795-b38e-61ff-3ba1-26a0623b97e6
* Version Independent ID: 65795b50-24d3-1997-038e-ffdb609eb20b
* Content: [The Xamarin.Forms FlexLayout - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/layouts/flex-layout)
* Content Source: [docs/xamarin-forms/user-interface/layouts/flex-layout.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/layouts/flex-layout.md)
* Product: **xamarin**
* GitHub Login: @charlespetzold
* Microsoft Alias: **chape**

**Comment by davidbritch** [comment]
Hi @SlyOtis 

Thanks for reporting this issue. It's already logged with the engineering team [here](https://github.com/xamarin/Xamarin.Forms/issues/2663), so I'll close this issue.
