### ISSUE TITLE
Unsubscribe from OnItemClick

### ISSUE THREAD

**Issue by varyamereon** [MicrosoftDocs/xamarin-docs#535]
By subscribing to method OnItemClick in OnCreate, should it also not be unsubscribed from in OnDestroy?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b78bfd80-d055-e016-4fa2-f3507663f0bc
* Version Independent ID: 745365c9-7396-3ad7-7688-101b8b1af0d3
* Content: [Extending the RecyclerView Example - Xamarin](https://docs.microsoft.com/en-us/xamarin/android/user-interface/layouts/recycler-view/extending-the-example)
* Content Source: [docs/android/user-interface/layouts/recycler-view/extending-the-example.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/android/user-interface/layouts/recycler-view/extending-the-example.md)
* Product: **xamarin**
* GitHub Login: @mgmclemore
* Microsoft Alias: **mamcle**

**Comment by mgmclemore** [comment]
Hi @varyamereon, thank you for the feedback!  A production app will typically subscribe in `OnResume()` and unsubscribe in `OnPause()`. There is no guarantee that `OnDestroy()` will be called (see [Activity Lifecycle](https://docs.microsoft.com/en-us/xamarin/android/app-fundamentals/activity-lifecycle/#ondestroy) for more info) .

As typical of conceptual topics, we strive to avoid complicating examples with extra production-level code overhead &ndash; we want the reader to try out and learn the concepts with a minimum of fuss. However, I'll add a note to remind readers that, in a production situation, subscription/unsubscription is best handled by `OnResume()` and `OnPause()`.
