### ISSUE TITLE
JsonElement.FromFile

### ISSUE THREAD

**Issue by docen67** [MicrosoftDocs/xamarin-docs#536]
From where is this fuction? (JsonElement.FromFile)  ,does i need any plugin to use this function?.
Help me please.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9edd2c91-a05e-aa43-8522-c29f43f468ee
* Version Independent ID: 955ddebc-6eda-f688-e953-99faa62f6360
* Content: [Using JSON to create a User Interface in Xamarin.iOS - Xamarin](https://docs.microsoft.com/en-us/xamarin/ios/user-interface/monotouch.dialog/json-element-walkthrough)
* Content Source: [docs/ios/user-interface/monotouch.dialog/json-element-walkthrough.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/ios/user-interface/monotouch.dialog/json-element-walkthrough.md)
* Product: **xamarin**
* GitHub Login: @bradumbaugh
* Microsoft Alias: **brumbaug**

**Comment by conceptdev** [comment]
Hey @docen67 there is a link to the completed sample at the end of the page -- you can see the code [in the AppDelegate.cs file](https://github.com/xamarin/ios-samples/blob/master/MTDJsonDemo/AppDelegate.cs#L27).

To answer your question: `JsonElement.FromFile` requires `using MonoTouch.Dialog;`

If that namespace isn't available, you might need to add the reference. Right-click on the **References** node in the iOS project and tick `MonoTouch.Dialog-1`:

![screen shot 2018-07-13 at 10 43 44 am](https://user-images.githubusercontent.com/199373/42705894-b723f49a-8689-11e8-9c09-0c76627c46fc.png)
