### ISSUE TITLE
Some missing clarity for a newer user

### ISSUE THREAD

**Issue by lkmcdo** [MicrosoftDocs/xamarin-docs#541]
Xamarin in VS 2017 offers two options when creating a new project. This appears to be a shared project; it would be nice to have documentation on how which options to choose for a .NET Standard class library project instead.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2bbded77-0d91-3707-2d36-d8c7de4e840d
* Version Independent ID: 6fae8fd3-298e-bddb-0ba5-4fb37d817a53
* Content: [GTK# Platform Setup - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/platform/gtk?tabs=vswin)
* Content Source: [docs/xamarin-forms/platform/gtk.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/platform/gtk.md)
* Product: **xamarin**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @lkmcdo 

The GTK# doc covers adding a GTK# project to an existing project. For information about creating a new project, see https://docs.microsoft.com/en-gb/xamarin/xamarin-forms/get-started/

For information about code sharing options (shared project vs .NET Standard) see https://docs.microsoft.com/en-gb/xamarin/cross-platform/app-fundamentals/
