### ISSUE TITLE
It should explicitly mention that this does not work at all for Free Provisioning

### ISSUE THREAD

**Issue by Rhywden** [MicrosoftDocs/xamarin-docs#543]
Just so that people trying to follow the "advice" in the Free Provisioning section don't get frustrated. For example, the very first link to "Certificates, Identifiers, and Profiles section of the Developer Portal" instead lands a free account here:
https://developer.apple.com/account/#/welcome

From there I don't have any options like you describe. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2f798d8c-b191-34a4-55dd-02005b0b6332
* Version Independent ID: 2f6ec8bd-359d-a5a6-891a-6c60ff52adb7
* Content: [Manual Provisioning for Xamarin.iOS - Xamarin](https://docs.microsoft.com/en-us/xamarin/ios/get-started/installation/device-provisioning/manual-provisioning?tabs=vsmac)
* Content Source: [docs/ios/get-started/installation/device-provisioning/manual-provisioning.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/ios/get-started/installation/device-provisioning/manual-provisioning.md)
* Product: **xamarin**
* GitHub Login: @asb3993
* Microsoft Alias: **amburns**

**Comment by bradumbaugh** [comment]
Thanks @Rhywden. I've made an update to this document – should be published soon. Appreciate you calling out anything confusing so that we can clarify things!
