### ISSUE TITLE
Link to Flyout Navigation Controller is unhelpful

### ISSUE THREAD

**Issue by Crwth** [MicrosoftDocs/xamarin-docs#544]
The link to the Flyout Navigation Controller goes to the old Component Store, which has been discontinued; if a Nuget package for the Flyout Navigation Controller exists, a link to that should replace the one on this page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f960f02f-b51e-fa98-a74c-a842518510a2
* Version Independent ID: be0af449-b28c-1042-fe1a-1c9a21d2d170
* Content: [Hello, iOS Multiscreen – Deep Dive - Xamarin](https://docs.microsoft.com/en-us/xamarin/ios/get-started/hello-ios-multiscreen/hello-ios-multiscreen-deepdive)
* Content Source: [docs/ios/get-started/hello-ios-multiscreen/hello-ios-multiscreen-deepdive.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/ios/get-started/hello-ios-multiscreen/hello-ios-multiscreen-deepdive.md)
* Product: **xamarin**
* GitHub Login: @bradumbaugh
* Microsoft Alias: **brumbaug**

**Comment by bradumbaugh** [comment]
Thanks @Crwth. I've made an update to this doc to remove this reference. Should be published soon. Appreciate the help!
