### ISSUE TITLE
UWP unavailable

### ISSUE THREAD

**Issue by tonyphiri** [MicrosoftDocs/xamarin-docs#545]
Is it just me or the latest VS version doesn't have Windows (UWP) selectable on start up of a  project? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2de3e72c-8948-4dd5-e37f-9cf81e62c127
* Version Independent ID: 7b7c5c7f-4102-8e91-fbe6-7d21fcc8f5be
* Content: [Xamarin.Forms Quickstart - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/get-started/hello-xamarin-forms/quickstart?tabs=vswin)
* Content Source: [docs/xamarin-forms/get-started/hello-xamarin-forms/quickstart.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/get-started/hello-xamarin-forms/quickstart.md)
* Product: **xamarin**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by conceptdev** [comment]
@tonyphiri you can check the [UWP set up docs](https://docs.microsoft.com/en-us/windows/uwp/get-started/get-set-up#1-download-or-update-visual-studio) to make sure VS is configured correctly. If you are still experiencing issues, check the [Developer Community site](https://developercommunity.visualstudio.com/).
