### ISSUE TITLE
Code CS0117 'Resource.Layout' does not contain a definition for 'Main' File: MainActivity.cs

### ISSUE THREAD

**Issue by RobertHastings** [MicrosoftDocs/xamarin-docs#549]
Followed instructions to the "T"...

**Comment by topgenorth** [comment]
This problem an intermittently occur (for no apparently) reason when Visual Studio experiences a problem processing an Android AXML file. Typically there are three things that can be done to clear up the issue:

1. Perform a Build > Clean All
2. Manually delete the bin & obj directory for the Android project
3. Restart the IDE.

If the problem persists, the next best course of action is to report a bug at [Developer Community](https://developercommunity.visualstudio.com/spaces/8/index.html.
