### ISSUE TITLE
Out of date

### ISSUE THREAD

**Issue by clharrysmith** [MicrosoftDocs/xamarin-docs#551]
This stuff is so out of date virtually every line can not be converted to the new Xamarin as of  july 2018. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 85d5d1c5-9b5b-0e6c-0ac2-0cc76dff410b
* Version Independent ID: 21a07f8c-706c-e69e-43db-8f5c61dd6be1
* Content: [Permissions In Xamarin.Android - Xamarin](https://docs.microsoft.com/en-us/xamarin/android/app-fundamentals/permissions?tabs=vswin)
* Content Source: [docs/android/app-fundamentals/permissions.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/android/app-fundamentals/permissions.md)
* Product: **xamarin**
* GitHub Login: @topgenorth
* Microsoft Alias: **toopge**

**Comment by topgenorth** [comment]
We endeavour to keep our docs accurate and up to date. It would be helpful if you could tell us what parts of this guide you believe are out-of-date or inaccurate.
