### ISSUE TITLE
Default resources are no longer valid

### ISSUE THREAD

**Issue by wutever0** [MicrosoftDocs/xamarin-docs#557]
This is a bit confusing to follow because the "default resources" created by an Android Project are not actually what are being generated. There is no drawable folder being created and there are mipmap-xx folders which are not mentioned.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4db71a47-f7c4-e619-af5d-f173d97df1bd
* Version Independent ID: 1f6af9fe-e53f-de92-041a-4340b1ae45a4
* Content: [Android Resource Basics - Xamarin](https://docs.microsoft.com/en-us/xamarin/android/app-fundamentals/resources-in-android/android-resource-basics?tabs=vswin)
* Content Source: [docs/android/app-fundamentals/resources-in-android/android-resource-basics.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/android/app-fundamentals/resources-in-android/android-resource-basics.md)
* Product: **xamarin**
* GitHub Login: @mgmclemore
* Microsoft Alias: **mamcle**

**Comment by mgmclemore** [comment]
Hi @wutever0, thank you for your feedback!  You are correct: this topic has become outdated because the names of the default resources have changed since it was written. I've added a task to our backlog to get it updated.

**Comment by syedkutubahmed** [comment]
@mgmclemore, if I want to access an image from the resource folder in the shared project to set icon for a toolbar item, do i access this way "@mipmap\icon.png"? I keep getting image not found in the output window.

**Comment by mgmclemore** [comment]
Hello @syedkutubahmed, our team can only answer feedback related to documentation issues. To get help, please visit the [Developer Community](https://developercommunity.visualstudio.com/spaces/8/index.html) forum.
