### ISSUE TITLE
 deprecated method

### ISSUE THREAD

**Issue by edwinmuraya** [MicrosoftDocs/xamarin-docs#56]
var cursor = ManagedQuery (uri, projection, null, null, null); could be replaced with var cursor = this.ContentResolver.Query(uri, projections, null, null, null);

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4bef7b64-660b-22b1-3fc1-020a3c1d2869
* Version Independent ID: 292a4d41-3ebc-2726-e469-5d824f00b132
* Content: [User Profile - Xamarin](https://docs.microsoft.com/en-us/xamarin/android/user-interface/user-profile)
* Content Source: [docs/android/user-interface/user-profile.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/android/user-interface/user-profile.md)
* Service: **unspecified**
* GitHub Login: @mgmclemore
* Microsoft Alias: **mamcle**

**Comment by mgmclemore** [comment]
Hello @edwinmuraya, thanks for the feedback (and good catch)!  We'll update the topic and the sample app to use `ContentResolver.Query`.  Much appreciated!

**Comment by mgmclemore** [comment]
@edwinmuraya, I've updated the [sample app](https://developer.xamarin.com/samples/monodroid/ContactsProviderDemo/) to use the correct non-deprecated methods. The associated topic should be published soon.

**Comment by mgmclemore** [comment]
Topic and sample code updated to new APIs and tested.

**Comment by edwinmuraya** [comment]
works great thanks for the update
