### ISSUE TITLE
Debug iPhone architecture

### ISSUE THREAD

**Issue by shalinasanga** [MicrosoftDocs/xamarin-docs#560]
which is the Debug iPhone support architecture ? that's missing

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 71d598ff-7608-abe8-5b39-34ae7e88026d
* Version Independent ID: c5230902-3bff-16df-e06c-a32b70476e3e
* Content: [Architecture Changes in iOS 11 - Xamarin](https://docs.microsoft.com/en-us/xamarin/ios/platform/introduction-to-ios11/updating-your-app/architecture-changes)
* Content Source: [docs/ios/platform/introduction-to-ios11/updating-your-app/architecture-changes.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/ios/platform/introduction-to-ios11/updating-your-app/architecture-changes.md)
* Product: **xamarin**
* GitHub Login: @bradumbaugh
* Microsoft Alias: **brumbaug**

**Comment by bradumbaugh** [comment]
Hi @shalinasanga, this is listed in the third bullet in this doc – hope this helps.

>>> 
3. Set the Supported architectures drop-down to x86_64 for the Debug|iPhoneSimulator and Release|iPhoneSimulator:
