### ISSUE TITLE
In ASP.NET Forms Master pages are used to create a template for detail pages.

### ISSUE THREAD

**Issue by smchughinfo** [MicrosoftDocs/xamarin-docs#562]
In ASP.NET Forms Master pages are used to create a template for detail pages. Personally, I would prefer to have that functionality over this functionality. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ec31ee56-e3b9-a70a-a4ef-80fdf58e7249
* Version Independent ID: 766b5774-50bf-f43f-800d-48b5c6c66509
* Content: [Xamarin.Forms Master-Detail Page - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/navigation/master-detail-page)
* Content Source: [docs/xamarin-forms/app-fundamentals/navigation/master-detail-page.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/app-fundamentals/navigation/master-detail-page.md)
* Product: **xamarin**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by smchughinfo** [comment]
Found it https://xamarinhelp.com/xamarin-forms-page-templates/

**Comment by davidbritch** [comment]
Hi @smchughinfo 

We have similar content at https://docs.microsoft.com/xamarin/xamarin-forms/app-fundamentals/templates/control-templates/index
