### ISSUE TITLE
Live Player vs Live Reload

### ISSUE THREAD

**Issue by pfedotovsky** [MicrosoftDocs/xamarin-docs#563]
It's a bit unclear - is Live Reload a replacement for Live Player? Both have similar names, and it's a bit confusing. I think it's worth mentioning what's the relation between Live Player & Live Reload in the article.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e40394ca-9a55-d9b5-d427-7c2a2c00cfc8
* Version Independent ID: 5a5c17e2-a683-88f6-07a9-2002e814d54c
* Content: [Live Reload - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/xaml/live-reload)
* Content Source: [docs/xamarin-forms/xaml/live-reload.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/xaml/live-reload.md)
* Product: **xamarin**
* GitHub Login: @pierceboggan
* Microsoft Alias: **piboggan**

**Comment by bradumbaugh** [comment]
Hi @pfedotovsky, thanks for the feedback. Live Player and Live Reload are separate tools; it's worth trying Live Reload if you come up against any limitations with Live Player. I'll add an item to our internal backlog to revisit this doc to clarify. Thanks again.
