### ISSUE TITLE
Emulator no longer included in SDK

### ISSUE THREAD

**Issue by mungojam** [MicrosoftDocs/xamarin-docs#568]
It seems that the Xamarin Android SDK Manager will no longer pick up newer versions of the emulator since it isn't part of SDK anymore:

https://developer.android.com/studio/releases/emulator
> Android Emulator is included with Android Studio.
> 
> Versions of the emulator prior to 25.3.0 were distributed as part of the Android SDK Tools.

It feels like this should be noted here or somewhere else. Hopefully you find a solution to it too

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7bc7444e-f943-836c-943e-c598143deb8b
* Version Independent ID: 0f78356e-a089-3ac1-0c85-2697ba1d41e0
* Content: [Changes to the Android SDK Tooling - Xamarin](https://docs.microsoft.com/en-us/xamarin/android/troubleshooting/sdk-cli-tooling-changes)
* Content Source: [docs/android/troubleshooting/sdk-cli-tooling-changes.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/android/troubleshooting/sdk-cli-tooling-changes.md)
* Product: **xamarin**
* GitHub Login: @mgmclemore
* Microsoft Alias: **mamcle**

**Comment by mgmclemore** [comment]
Hi @mungojam, the SDK Manager uses a "Xamarin feed" by default, which does not include the latest packages by Google. To switch to the latest emulator, there is a gear icon at the bottom right that you can change to Google's feed: **Gear > Repository > Google**. This is probably not mentioned in the SDK Manager documentation, so I've added a task to our backlog to get it updated. Thanks for the feedback!
