### ISSUE TITLE
System Requirements for Xamarin still mention Visual Studio 2015

### ISSUE THREAD

**Issue by brendanzagaeski** [MicrosoftDocs/xamarin-docs#573]
On &lt;https://docs.microsoft.com/xamarin/cross-platform/get-started/requirements&gt;, there are still a few mentions of Visual Studio 2015, such as "supports any Visual Studio 2015 or 2017." But as of the Visual Studio 2017 version 15.7 release, the latest Visual Studio Tools for Xamarin version is [only available in Visual Studio 2017](https://releases.xamarin.com/release-15-7/), so I would recommend that all the mentions of Visual Studio 2015 be removed from the Xamarin requirements page at this time.

In case it might be convenient to make one more little change at the same time, I would also recommend that the name of the tools for Xamarin be updated to "Visual Studio Tools for Xamarin" uniformly across the page.

Thanks much!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6ff553e1-6e04-6e8c-cf00-a2dd68f64413
* Version Independent ID: acea309d-9c48-a1b4-e5bc-31b62739f6b6
* Content: [System Requirements - Xamarin](https://docs.microsoft.com/en-us/xamarin/cross-platform/get-started/requirements)
* Content Source: [docs/cross-platform/get-started/requirements.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/cross-platform/get-started/requirements.md)
* Product: **xamarin**
* GitHub Login: @asb3993
* Microsoft Alias: **amburns**

**Comment by Rick-Anderson** [comment]
Recommend you `Lock conversation` as this doesn't provide any useful information. Locking it hides it from the integrated doc/GitHub open/closed .

![image](https://user-images.githubusercontent.com/3605364/56385643-77e84480-61bb-11e9-9044-a28cbaf05fdf.png)

**Comment by Rick-Anderson** [comment]
![image](https://user-images.githubusercontent.com/3605364/56385794-d3b2cd80-61bb-11e9-8369-c18da3aa5128.png)

**Comment by conceptdev** [comment]
TIL! thanks
