### ISSUE TITLE
Please add more details explaining difference and xamarin studio avaialable now

### ISSUE THREAD

**Issue by pmahend1** [MicrosoftDocs/xamarin-docs#574]
Please differentiate PCL, *".NET and Shared projects more clearly. 
Documentation lacks clarity for beginners."* ?

Everything is Visual studio now. "NET Standard projects are supported in Xamarin Studio 6.2"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aedc1485-7897-9a80-f396-ff00c998fce7
* Version Independent ID: 3e4bdb14-5b7c-4504-e40c-b835d029d91f
* Content: [Sharing Code On Multiple Platforms - Xamarin](https://docs.microsoft.com/en-us/xamarin/cross-platform/app-fundamentals/index)
* Content Source: [docs/cross-platform/app-fundamentals/index.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/cross-platform/app-fundamentals/index.md)
* Product: **xamarin**
* GitHub Login: @asb3993
* Microsoft Alias: **amburns**

**Comment by bradumbaugh** [comment]
Thanks for calling this out, @pmahend1. I've made some updates to clarify this a bit, and cleaned up references to Xamarin Studio. Appreciate your help! The PR is in review but should be published soon.

**Comment by pmahend1** [comment]
Just out of curiosity could you please link the commit ID associated with the change because the update hasn't been published yet and also it takes time to get approved too.

**Comment by bradumbaugh** [comment]
Hi @pmahend1, unfortunately the PR is not publicly visible. If it helps, here's a bit of a brief description of the three main code-sharing strategies (these descriptions may not make it into the final doc):

-------------------

**Portable Class Libraries** contain code that can be used on multiple platforms. A PCL's _profile_ determines the specific platforms it supports, and therefore the subset of the .NET Framework that it can make use of. There are many PCL profiles to choose from when creating a PCL, and each surfaces a different selection of .NET APIs.

**Shared Projects** contain code that can be referenced by and compiled directly in to other .NET projects. Unlike PCLs or .NET Standard libraries, Shared Projects do not generate assemblies, and they frequently make use of compiler directives to incorporate platform-specific functionality.

**The [.NET Standard](https://docs.microsoft.com/dotnet/standard/net-standard)** is a [specification](https://github.com/dotnet/standard) that defines a set of .NET APIs that must be available on any platform that chooses to support the standard. There are multiple versions of the .NET Standard, each exposing a more comprehensive set of .NET APIs that its predecessor.

A .NET Standard Library targets a specific version of the .NET Standard, and can be used by any .NET platform that supports that version of the standard. This means that .NET Standard Libraries, unlike PCLs, need not have any knowledge about the specific platforms on which they will be used – and can therefore be adopted more broadly.
