### ISSUE TITLE
Where is Pivot PivotItem equivalent?

### ISSUE THREAD

**Issue by pmahend1** [MicrosoftDocs/xamarin-docs#575]
Where is Pivot PivotItem equivalent?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a8daea50-6274-cf1d-54b0-1a8235e37c95
* Version Independent ID: eb075324-8e41-b3c1-072c-1971a7747d84
* Content: [UI Controls Comparison - Xamarin](https://docs.microsoft.com/en-us/xamarin/cross-platform/desktop/controls/index)
* Content Source: [docs/cross-platform/desktop/controls/index.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/cross-platform/desktop/controls/index.md)
* Product: **xamarin**
* GitHub Login: @asb3993
* Microsoft Alias: **amburns**

**Comment by davidbritch** [comment]
Hi @pmahend1 

The Xamarin.Forms `TabbedPage` on UWP is implemented by the `Pivot` control, with each `Page` being a `PivotItem`.
