### ISSUE TITLE
Localization issue Upon Exit

### ISSUE THREAD

**Issue by aviaknel** [MicrosoftDocs/xamarin-docs#577]
Thanks for the coding you have designed. Really helpful. But the issue that I am facing is my changed language is again set to default upon application exit.

Can you please help me to direct from here?

Thanks in advance.

Thanks
aViAkNeL

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 661223d7-0e8a-721b-0045-35ce981421ca
* Version Independent ID: 1b084f04-91b3-0d7e-7a9f-c296c978ec14
* Content: [Android Localization - Xamarin](https://docs.microsoft.com/en-us/xamarin/android/app-fundamentals/localization)
* Content Source: [docs/android/app-fundamentals/localization.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/android/app-fundamentals/localization.md)
* Product: **xamarin**
* GitHub Login: @mgmclemore
* Microsoft Alias: **mamcle**

**Comment by mgmclemore** [comment]
Hello @aviaknel, by default Android will attempt to load resources depending on the system language that is set on the phone. Are you trying to have the app start with a language that is different from the system language?

**Comment by topgenorth** [comment]
If I may chime in: what you're describing is how Android was designed. Each time an app starts up, Android will load resources that are appropriate for the locale.  However, it is possible to programmatically change the locale that the app will use. 

I haven't tried this myself, but perhaps this post, [How to change the language on Android at runtime and don’t go mad
](https://proandroiddev.com/change-language-programmatically-at-runtime-on-android-5e6bc15c758), will help you out (note that you might need to convert from Java to C#).

**Comment by aviaknel** [comment]
Hi Tom,

I have already been through the link you shared but that did not meet
my requirement.

What I have done in my project is: I have designed an app with
multilanguage functionality. My primary language is English as per my
device. I have added two more languages viz French and Japanese. Everything
is working as expected. During Runtime, I can change the language but the
problem is when I exit the app again all changes are set to default.

My concern is how to fix the code so that it will start with the language I
set before exiting the app.

*Best Regards*
aViAkNeL

**Comment by mgmclemore** [comment]
Hi @aviaknel, unfortunately, that scenario is beyond the scope of the [Localization](https://docs.microsoft.com/en-us/xamarin/android/app-fundamentals/localization) topic (which is intended for the usual case of Android finding and loading resources that correspond to the system locale). As the [post](https://proandroiddev.com/change-language-programmatically-at-runtime-on-android-5e6bc15c758) linked above points out, programmatically changing to a locale that is different from the system locale can be done but is tricky and is dependent on Android version. Your best bet for getting help with implementing this is to post your question to the [Developer Community](https://developercommunity.visualstudio.com/spaces/8/index.html) forum.
