### ISSUE TITLE
Missing explanation. 

### ISSUE THREAD

**Issue by BrayanKhosravian** [MicrosoftDocs/xamarin-docs#580]
In my opinion there is a lack of information.
What if there is a need of static field inside the platform specific class?

Or what if the class has a constructor? How would i pass data to the constructor while using dependency service? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6e9eecf7-0edb-5b24-964c-a1ae2e7556ba
* Version Independent ID: 8f9243b4-0f7c-6aac-39e2-913173ea472a
* Content: [Introduction to DependencyService - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/dependency-service/introduction)
* Content Source: [docs/xamarin-forms/app-fundamentals/dependency-service/introduction.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/app-fundamentals/dependency-service/introduction.md)
* Product: **xamarin**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @BrayanKhosravian 

See [Dependency resolution](https://docs.microsoft.com/xamarin/xamarin-forms/internals/dependency-resolution) for how to gain more control over the creation of classes in platform projects.
