### ISSUE TITLE
Spelling Mistake

### ISSUE THREAD

**Issue by abhiongithub** [MicrosoftDocs/xamarin-docs#581]
Xpirit Nederland B.V. | Hilversum, Netherlands | Passionate technology professionals, willing and able to do things differently. Xpirit are **nnovators**, transformation enablers, and early adopters who embrace change. Experts in new Microsoft technology.
-- | -- | --

Spelling of Innovators

**Comment by conceptdev** [comment]
fixed in your PR, thanks again.
