### ISSUE TITLE
Offline Google map not working on version 2

### ISSUE THREAD

**Issue by GolfMan2000** [MicrosoftDocs/xamarin-docs#584]
I have tried various version 2 Google map Xamarin Android sample. If there is no wifi and cell data then samples fail to update the map and create fizzy maps. This is despite downloading offline maps in Google map app.

However if I use sample that uses the Google API directly then the offline downloaded maps are used and maps are responsive despite there is no cell or wifi data. So this is perfect except there is no documentation how to add many markers to Google API using Activity and Intent.

I don't care what method I use but I must have many icon markers on a offline Google map.

Please give me reference to a working sample/example.

Thanks

**Comment by topgenorth** [comment]
Thanks for reporting this to us. We try to keep our samples updated and current. However, this sample is fairly out of date and in need of an update. We've add this to our backlog of items to address.

**Comment by GolfMan2000** [comment]
Can you please point me to working current samples that show multiple circle icon markers on google map in offline airplane mode.

**Comment by GolfMan2000** [comment]
The Version 3 sample works fine under offline maps using Activity and Intent. Can you show me how to add multiple markers to that sample.

**Comment by GolfMan2000** [comment]
Please how can you close this when I am not asking you to fix a problem...i am merely asking you to point me to a solution.

**Comment by topgenorth** [comment]
Right now, the best I can do is to point you to the [MapWithMarker](https://github.com/googlemaps/android-samples) sample.
