### ISSUE TITLE
InitializeComponent(); doesn't exist in Application?

### ISSUE THREAD

**Issue by zezba9000** [MicrosoftDocs/xamarin-docs#585]
The InitializeComponent() method doesn't exist in the Application class?
How do we use an App.xaml file for global styles?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f9c4a77e-2256-cfe7-42b2-63041b588b68
* Version Independent ID: 5ade4bab-b189-eeeb-b8c8-1f6546d287d5
* Content: [Xamarin.Forms App Class - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/application-class)
* Content Source: [docs/xamarin-forms/app-fundamentals/application-class.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/app-fundamentals/application-class.md)
* Product: **xamarin**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @zezba9000 

See [Anatomy of a XAML File](https://docs.microsoft.com/xamarin/xamarin-forms/xaml/xaml-basics/get-started-with-xaml?tabs=vswin#anatomy-of-a-xaml-file) for information about where `InitializeComponent` comes from.

See [Global Styles](https://docs.microsoft.com/xamarin/xamarin-forms/user-interface/styles/xaml/application) for info about putting styles in the `App` class.

**Comment by zezba9000** [comment]
**InitializeComponent** does NOT exist in **Xamarin.Forms.Application** which is the issue in the docs.

**From the docs: This does NOT compile in Xamarin.Forms 3.1.**
```
public partial class App : Application
{
    public App ()
    {
        InitializeComponent ();
        MainPage = new HomePage ();
    }
    ...
}
```

**Comment by davidbritch** [comment]
The code above does compile on my machine. What compiler error are you getting?

The `InitializeComponent` method exists in the generated `App` class, which inherits from `Xamarin.Forms.Application`. I just picked a solution at random, and in the folder for the .NET Standard library, browse to obj/debug/netstandard2.0/ you should see a **App.xaml.g.cs** file containing:

```
    [global::Xamarin.Forms.Xaml.XamlFilePathAttribute("App.xaml")]
    public partial class App : global::Xamarin.Forms.Application {
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Forms.Build.Tasks.XamlG", "2.0.0.0")]
        private void InitializeComponent() {
            global::Xamarin.Forms.Xaml.Extensions.LoadFromXaml(this, typeof(App));
        }
    }
```

This file is created when your solution is built.

**Comment by zezba9000** [comment]
Because (unless I missed it) there is no template I manually created the App.xaml in the .csproj XML to be the same as a page, set it up as an embedded resource, etc. Everything looked as though it should be working in every place I checked.

So this time I created a ContentPage and changed the type to Application and it works. Its odd I can't just edit the csproj in .NET Standard to get it to work? Not sure where this hidden special magic is happening.

**Comment by zezba9000** [comment]
My x:Class name was wrong FYI: "x:Class="AMP.App.MainApplication""

Would be nice if there was a App.xaml template in VS 2017.

Tnx for baring with me.

**Comment by davidbritch** [comment]
`App.xaml` is created by VS2017 when you create a new Forms project. It's not something there's really a need to add after a project is created.

**Comment by zezba9000** [comment]
I had an existing .NET Standard 2.0 proj I was adding XamForms to.
I didn't see a template proj in VS 2017.
