### ISSUE TITLE
Rename OpenJDK Distribution to Xamarin OpenJDK

### ISSUE THREAD

**Issue by brunoborges** [MicrosoftDocs/xamarin-docs#587]
Given this distribution is specifically designed for Xamarin/Android apps and not a general purpose OpenJDK for any kind of Java application (e.g. server-side Java apps on Azure; desktop Java apps on Windows), it is important to name this as *Xamarin OpenJDK Distribution*.

See PR #586.

**Comment by topgenorth** [comment]
Thanks for your thoughts on this matter. As there is already a PR in place for this, I'm closing this issue off  so that the conversation will occur there.

**Comment by brunoborges** [comment]
This was fixed in commit 9d90c732
