### ISSUE TITLE
OnPageLoading doesn't exist anymore?

### ISSUE THREAD

**Issue by jasperzig** [MicrosoftDocs/xamarin-docs#589]
In the section: https://docs.microsoft.com/en-us/xamarin/xamarin-forms/data-cloud/authentication/oauth#android

It references AuthenticationState.Authenticator.OnPageLoading(uri);
OnPageLoading doesn't appear to be a current method anymore, and AuthenticationState seems to be referencing a class definition from another Feedback, and doesn't appear anywhere else in the sample code.

See https://github.com/xamarin/Xamarin.Auth/blob/master/source/Core/Xamarin.Auth.Common.LinkSource/OAuth2Authenticator.cs
It may need to be updated to OnPageEncountered method.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aa8bb9e0-5898-0d11-0213-fd4d8c8d0297
* Version Independent ID: 2f46e1f7-164f-2f32-70c0-f28919d16c5c
* Content: [Authenticating Users with an Identity Provider - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/data-cloud/authentication/oauth#feedback)
* Content Source: [docs/xamarin-forms/data-cloud/authentication/oauth.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/data-cloud/authentication/oauth.md)
* Product: **xamarin**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @jasperzig 

It seems you're right - `OnPageLoading` was the correct method at the time of writing, but seems to have been replaced with `OnPageEncountered`. Thanks for letting me know.

I've created an issue for this in our backlog.
