### ISSUE TITLE
API links to Xamarin.Interactive namespace are broken in Workbooks documentation

### ISSUE THREAD

**Issue by HankiDesign** [MicrosoftDocs/xamarin-docs#59]
The broken links are all located in the Building an Integration section:

- [IAgentIntegration](https://docs.microsoft.com/en-us/api/type/Xamarin.Interactive.IAgentIntegration/)
- [RepresentationProvider](https://docs.microsoft.com/en-us/api/type/Xamarin.Interactive.Representations.RepresentationProvider/)
- [ProvideRepresentations](https://docs.microsoft.com/en-us/api/member/Xamarin.Interactive.Representations.RepresentationProvider.ProvideRepresentations/p/System.Object/)
- [Color](https://docs.microsoft.com/en-us/api/type/Xamarin.Interactive.Representations.Color/)
- [AddProvider overloads](https://docs.microsoft.com/en-us/api/member/Xamarin.Interactive.Representations.IRepresentationManager.AddProvider/)

 I suppose that the content just hasn't been migrated yet? Anyway, right now the links listed above lead to a 404 page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2d2da656-b0bd-63f9-2280-14e80cf84492
* Version Independent ID: bbce91a3-e249-e52c-30ed-b0a2e6669c74
* Content: [Getting Started with the Xamarin Workbooks SDK - Xamarin](https://docs.microsoft.com/en-us/xamarin/tools/workbooks/sdk/?tabs=vsmac#building-an-integration)
* Content Source: [docs/tools/workbooks/sdk/index.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/tools/workbooks/sdk/index.md)
* Service: **unspecified**
* GitHub Login: @topgenorth
* Microsoft Alias: **toopge**

**Comment by conceptdev** [comment]
they have not been migrated, but the links should still work, on the developer.xamarin.com site!
