### ISSUE TITLE
DefaultValue, Category attributes

### ISSUE THREAD

**Issue by samsudeenks** [MicrosoftDocs/xamarin-docs#590]
Attributes like DefaultValue, Category are not working. Are they not supported?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ce7901b8-c995-7ca7-a0ff-0505ceac4115
* Version Independent ID: 5feed282-65ea-ca9c-a2b4-eb304d644a03
* Content: [Custom Controls in the Xamarin Designer for iOS - Xamarin](https://docs.microsoft.com/en-us/xamarin/ios/user-interface/designer/ios-designable-controls-overview)
* Content Source: [docs/ios/user-interface/designer/ios-designable-controls-overview.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/ios/user-interface/designer/ios-designable-controls-overview.md)
* Product: **xamarin**
* GitHub Login: @bradumbaugh
* Microsoft Alias: **brumbaug**

**Comment by bradumbaugh** [comment]
Hi @samsudeenks, the doc mentions `CategoryAttribute`, which changes the section in the **Toolbox** where the custom component appears. Attributes in your component marked as `[Browsable]` are listed in a section of the **Properties Pad** specific to your custom control.

The `DefaultValueAttribute` isn't used by the iOS Designer (though looking at some [other](https://support.microsoft.com/en-us/help/311339/msdn-documentation-for-the-defaultvalueattribute-class-may-be-confusin) [docs](https://msdn.microsoft.com/en-us/library/system.componentmodel.defaultvalueattribute(v=vs.110).aspx), it doesn't seem like the intention for this attribute is to actually set the default value automatically).
