### ISSUE TITLE
[Xamarin.Essentials] DeviceInfo add DeviceId

### ISSUE THREAD

**Issue by jitendrajadav** [MicrosoftDocs/xamarin-docs#592]
DeviceInfo add DeviceId

**Comment by bradumbaugh** [comment]
Hi @jitendrajadav, thanks for the comment. Please file feature requests in the [Xamarin.Essentials GitHub repository](https://github.com/xamarin/Essentials/issues), as this repository is specifically intended for documentation issues. Thank you!
