### ISSUE TITLE
setting array/list of string in XAML

### ISSUE THREAD

**Issue by pmahend1** [MicrosoftDocs/xamarin-docs#593]
Please include equivalent of setting `ItemSource` to List&lt;string&gt; or string[] binding in XAML also.

            <ListView ItemsSource="{Binding list1, Mode=TwoWay}"
                      HorizontalOptions="FillAndExpand"
                      VerticalOptions="FillAndExpand">
                <ListView.ItemTemplate>
                    <DataTemplate>
                        <TextCell Text="{Binding .}"/>
                    </DataTemplate>
                </ListView.ItemTemplate>

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f9bb8625-60a7-2d18-86aa-501c64a71073
* Version Independent ID: 4891a28f-63b1-dca9-0467-fc81f32363cf
* Content: [ListView Data Sources - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/listview/data-and-databinding)
* Content Source: [docs/xamarin-forms/user-interface/listview/data-and-databinding.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/listview/data-and-databinding.md)
* Product: **xamarin**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
I've fixed this in a PR, which should get merged into the repo in a day or two.

In the meantime, here's the example:

```
<ListView>
       <ListView.ItemsSource>
           <x:Array Type="{x:Type x:String}">
             <x:String>mono</x:String>
             <x:String>monodroid</x:String>
             <x:String>monotouch</x:String>
             <x:String>monorail</x:String>
             <x:String>monodevelop</x:String>
             <x:String>monotone</x:String>
             <x:String>monopoly</x:String>
             <x:String>monomodal</x:String>
             <x:String>mononucleosis</x:String>
           </x:Array>
       </ListView.ItemsSource>
 </ListView>
```
