### ISSUE TITLE
DialogViewController

### ISSUE THREAD

**Issue by titonton** [MicrosoftDocs/xamarin-docs#594]
I'm trying to create the subclass of the DialogViewController but my project doesn't have a reference to it. I'm using Xamarin Forms

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 318b9810-7586-4f88-0d5a-a598e196a716
* Version Independent ID: 80da412f-4a26-3021-21fe-da30afc61bee
* Content: [EventKit in Xamarin.iOS - Xamarin](https://docs.microsoft.com/en-us/xamarin/ios/platform/eventkit)
* Content Source: [docs/ios/platform/eventkit.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/ios/platform/eventkit.md)
* Product: **xamarin**
* GitHub Login: @bradumbaugh
* Microsoft Alias: **brumbaug**

**Comment by bradumbaugh** [comment]
Hi @titonton, the sample code for that document, which you can find [here](https://developer.xamarin.com/samples/monotouch/Calendars/), makes use of [MonoTouch.Dialog](https://docs.microsoft.com/xamarin/ios/user-interface/monotouch.dialog/), a UI development toolkit for Xamarin (it's different from and predates Xamarin.Forms). You won't want to use Xamarin.Forms and MonoTouch.Dialog at the same time.

`DialogViewController` isn't a requirement for using EventKit, it's just what happens to be used in this sample.

Hope this helps.

**Comment by titonton** [comment]
Thank makes sense. Thank you very much!
