### ISSUE TITLE
It would be useful to have guidance on manually putting things in manifest file where necessary

### ISSUE THREAD

**Issue by mungojam** [MicrosoftDocs/xamarin-docs#595]
> Our goal is that 99% of our users should never need to manually modify AndroidManifest.xml.
I've now hit a case that isn't covered as described [here](https://github.com/MicrosoftDocs/xamarin-docs/issues/591). I guess I'm in the 1%.

What isn't clear from this doc is whether just taking the auto-generated XML as described above and manually putting it into the XML would work. i.e. will Xamarin wire up the md5 name to the right class automatically, or do we also need to have the attribute for that to work.

I think it's worth adding a small note about this edge case.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 50a4c45c-34a0-9fa7-5916-f9c3a85c5558
* Version Independent ID: c03c4a7a-fdec-ffd0-cacc-17cf329454f8
* Content: [Working with the Android Manifest - Xamarin](https://docs.microsoft.com/en-us/xamarin/android/platform/android-manifest)
* Content Source: [docs/android/platform/android-manifest.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/android/platform/android-manifest.md)
* Product: **xamarin**
* GitHub Login: @mgmclemore
* Microsoft Alias: **mamcle**

**Comment by mgmclemore** [comment]
Hello @mungojam, Thank you for your feedback! I've added a task to our backlog to update this topic accordingly.
