### ISSUE TITLE
Can I apply Fluent Design for MasterDetailPage?

### ISSUE THREAD

**Issue by nguyenthanhliemfc** [MicrosoftDocs/xamarin-docs#596]
Hi! As the title, can I apply Fluent Design for MasterDetailPage?
Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5280a99e-bdcd-2de4-c84a-0eebf73bf3f1
* Version Independent ID: adbe9ca3-4898-5ebe-2253-d603fbd6e216
* Content: [Windows Platform-Specifics - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/platform/platform-specifics/consuming/windows#collapsable_navigation_bar)
* Content Source: [docs/xamarin-forms/platform/platform-specifics/consuming/windows.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/platform/platform-specifics/consuming/windows.md)
* Product: **xamarin**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @nguyenthanhliemfc 

At the moment the fluent design packages are only a preview (https://blogs.windows.com/buildingapps/2018/07/23/windows-ui-library-preview-released/#2tWAAI3QFXCuhOxO.97) and Xamarin.Forms isn't built against them. So the answer, at the moment, is no.

Any requests for Xamarin.Forms to support fluent design should be made to the [engineering team](https://github.com/xamarin/Xamarin.Forms).
