### ISSUE TITLE
Items not showing up on iOS

### ISSUE THREAD

**Issue by mohammedwed** [MicrosoftDocs/xamarin-docs#597]
Hi,

I have followed the tutorial step by step but I'm unable to get this to work properly on iPhone X iOS 11.4.
It works fine on android, I get to see the items and click them to view page details, while on iOS I get an empty screen with "sessions" title.

I've also downloaded the code sample from GitHub and it yields the same problem.

I really hope to see this fixed soon because I could make use of it in one of my apps.

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 055a0283-e820-8cc8-786c-589b0bd59a1f
* Version Independent ID: 69023bfc-1bb8-e651-2bca-e980c7bab6d1
* Content: [Layout Compression - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/layouts/layout-compression)
* Content Source: [docs/xamarin-forms/user-interface/layouts/layout-compression.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/layouts/layout-compression.md)
* Product: **xamarin**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by mohammedwed** [comment]
![screen shot 2018-07-28 at 3 13 50 pm](https://user-images.githubusercontent.com/13167945/43356880-0c97580e-9279-11e8-98ee-2edf3f773f73.png)

**Comment by mohammedwed** [comment]
![screen shot 2018-07-28 at 3 16 15 pm](https://user-images.githubusercontent.com/13167945/43356889-38fddac6-9279-11e8-9de0-cb7412421be3.png)

**Comment by davidbritch** [comment]
Hi @mohammedwed 

What sample are you running there? The [LayoutCompression](https://developer.xamarin.com/samples/xamarin-forms/userinterface/layoutcompression/) sample only has a single page, and it doesn't have a Sessions title.

**Comment by mohammedwed** [comment]
Thanks for your reply.

Somehow the wrong links ended up in my thread.

Here's the correct links for the issue:

Original DataPages tutorial:

https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/datapages/get-started

Code sample:

https://github.com/xamarin/xamarin-forms-samples/tree/master/Pages/DataPagesDemo

**Comment by mohammedwed** [comment]
I've closed this issue and opened a new issue #601 with correct information
