### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by TravyDale** [MicrosoftDocs/xamarin-docs#599]
Under the 'Getting Started' section and within the 'Android' tab, at the bottom, Android is spelled incorrectly -- Anroid.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 33758e0e-bd5d-0829-b458-6cdfabe98b44
* Version Independent ID: d3ed3057-798b-44b9-b5a0-35e657f7a4b8
* Content: [Xamarin.Essentials: Connectivity - Xamarin](https://docs.microsoft.com/en-us/xamarin/essentials/connectivity?context=xamarin%2Fxamarin-forms&tabs=android#getting-started)
* Content Source: [docs/essentials/connectivity.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/essentials/connectivity.md)
* Product: **xamarin**
* GitHub Login: @jamesmontemagno
* Microsoft Alias: **jamont**

**Comment by jamesmontemagno** [comment]
I have a PR for this thanks!
