### ISSUE TITLE
not in my case

### ISSUE THREAD

**Issue by ms666** [MicrosoftDocs/xamarin-docs#60]
Some other reason?
I have permission in the manifest but it does not solve the problem.
After installing on the phone permissions are visible in the application details - but it does not connect to the internet ...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2d84ae95-09e8-e59e-88d7-eb8dd493cdef
* Version Independent ID: 39431014-6797-8371-57d6-03c86127062c
* Content: [Why can't my Android release build connect to the Internet? - Xamarin](https://docs.microsoft.com/en-us/xamarin/android/troubleshooting/questions/android-internet)
* Content Source: [docs/android/troubleshooting/questions/android-internet.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/android/troubleshooting/questions/android-internet.md)
* Service: **unspecified**
* GitHub Login: @mgmclemore
* Microsoft Alias: **mamcle**

**Comment by mgmclemore** [comment]
Hi @ms666, thanks for your feedback!  We'll see if we can reproduce your observations on our end and update the workaround instructions accordingly.

**Comment by ms666** [comment]
I found the culprit. HTTPS and ignoring certificates.
Works in DEBUG mode and RELASE does not ...

**Comment by mgmclemore** [comment]
Hi @ms666, thanks for the update!  Are you using a self-signed certificate?  If so, perhaps this [forum discussion](https://forums.xamarin.com/discussion/52394/self-signed-certificates-and-httpclient) may be useful to you.

**Comment by mgmclemore** [comment]
Hi @ms666, we didn't hear back from you, so we're closing this issue (however, it can be re-opened if further discussion or action is needed). Thank for your feedback!

**Comment by titonton** [comment]
Try changing the SSL/TLS implementation in the Android Options in the project properties. You hit the Advanced button on the bottom to get to it.
