### ISSUE TITLE
DataPages Items not showing up on iOS

### ISSUE THREAD

**Issue by mohammedwed** [MicrosoftDocs/xamarin-docs#601]
Hi,

I have followed the data pages tutorial step by step but I'm unable to get this to work properly on iPhone X iOS 11.4.
It works fine on android, I get to see the items and click them to view page details, while on iOS I get an empty screen with "sessions" title.

I've also downloaded the code sample from GitHub and it yields the same problem.

I really hope to see this fixed soon because I could make use of it in one of my apps.

Thanks.

DataPages tutorial:

https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/datapages/get-started

Code sample:

https://github.com/xamarin/xamarin-forms-samples/tree/master/Pages/DataPagesDemo

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 507fbdb0-8534-0e4a-bbcb-456ce3539e1d
* Version Independent ID: f9da2705-a98d-7e5e-665d-ee8c801a3dfc
* Content: [Xamarin.Forms DataPages - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/datapages/)
* Content Source: [docs/xamarin-forms/user-interface/datapages/index.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/datapages/index.md)
* Product: **xamarin**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @mohammedwed 

I've updated the sample and confirm it now works. It was simply a case of updating the URL from http:// to https://. Apple Transport Security (ATS) blocks http:// URLs by default.

**Comment by mohammedwed** [comment]
Many thanks!
