### ISSUE TITLE
Show some gif image to explain each easing function

### ISSUE THREAD

**Issue by jessejiang0214** [MicrosoftDocs/xamarin-docs#603]
It will be better to show some gif image of each easing function. It will be easier for developers to choose the right one.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 69c636fb-a8de-6d1e-53c2-54d0ae5e9795
* Version Independent ID: a711b942-3009-6d0b-c96b-ba21dcb638b0
* Content: [Easing Functions in Xamarin.Forms - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/animation/easing#feedback)
* Content Source: [docs/xamarin-forms/user-interface/animation/easing.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/animation/easing.md)
* Product: **xamarin**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by charlespetzold** [comment]
Exactly what you want are a click away in the API documentation for the `Easing` class:

https://docs.microsoft.com/dotnet/api/xamarin.forms.easing

**Comment by jessejiang0214** [comment]
Hi @charlespetzold , no we want a gif image, think of if you want to rotate an image with easing function, can you see how the image rotating based on that document?
