### ISSUE TITLE
Can not create a multiplatform nuget project with nugetizer 3000 

### ISSUE THREAD

**Issue by HansUrschel** [MicrosoftDocs/xamarin-docs#604]
If i want to create a new project ( new -> project -> cross paltform -> class library ( multiplatform ) ), i get an error . I select Implementation: Platform specific and Target platfoprms are iOS and Android. Then i click Accept. After a millisecond i get the error message ( i translate it from german ):
Error on packageinstallation. The following packages could not be installed from C:\Users\HUrschel\AppData\Local\Microsoft\VisualStudio\15.0_abee00e5\Extensions\kgc5vu4t.y00\Packages: NuGet.Build.Packaging.0.2.5-dev1 error restore pckage.

In the above path there is a file
NuGet.Build.Packaging.0.2.5-dev.1+sha.abbff50.nupkg

I use VS2017 CommunityEdition 15.7.5 underWindows 10 64 bit.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 44cfe14b-198c-56d5-0b63-de00dd08bafe
* Version Independent ID: 39eea43d-d7b5-1659-1583-dc23d099c9f8
* Content: [NuGet Multiplatform Library Projects (aka Nugetizer 3000) - Xamarin](https://docs.microsoft.com/en-us/xamarin/cross-platform/app-fundamentals/nuget-multiplatform-libraries/?tabs=windows)
* Content Source: [docs/cross-platform/app-fundamentals/nuget-multiplatform-libraries/index.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/cross-platform/app-fundamentals/nuget-multiplatform-libraries/index.md)
* Product: **xamarin**
* GitHub Login: @conceptdev
* Microsoft Alias: **crdun**

**Comment by bradumbaugh** [comment]
Hi @HansUrschel, sorry to hear you've hit an issue here. However, this repository is for documentation-specific issues; for support, please feel free to post on [Developer Community](https://developercommunity.visualstudio.com/spaces/8/index.html). Thank you!
