### ISSUE TITLE
Where I have to create MenuItem? 

### ISSUE THREAD

**Issue by nguyenthanhliemfc** [MicrosoftDocs/xamarin-docs#606]
Where I have to create MenuItem: item 1, item 2, item 3? 
Thank you!

---
#### Chi tiết tài liệu

⚠ *Không chỉnh sửa phần này. Điều này là bắt buộc cho docs.microsoft.com ➟ Vấn đề khi liên kết GitHub.*

* ID: e224639d-2b49-2da2-46b4-82546578949b
* Version Independent ID: 988a9c6f-13a9-5ca7-830c-cbd20c67df33
* Content: [PopUp Menu - Xamarin](https://docs.microsoft.com/vi-vn/xamarin/android/user-interface/controls/popup-menu)
* Content Source: [docs/android/user-interface/controls/popup-menu.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/android/user-interface/controls/popup-menu.md)
* Product: **xamarin**
* GitHub Login: @mgmclemore
* Microsoft Alias: **mamcle**

**Comment by mgmclemore** [comment]
Hi @nguyenthanhliemfc, thank you for the feedback!  Unfortunately, the article skips this step &ndash; I have added the missing step (along with some other updates) and the changes should be published soon.
