### ISSUE TITLE
Outdated

### ISSUE THREAD

**Issue by dbatemanstl** [MicrosoftDocs/xamarin-docs#607]
WSDL generated no longer includes Begin and End but rather ASYNC and COMPLETED - content needs to be expanded to reflect currents WSDLs generated when using VS 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fc95e57a-607f-4236-3f6e-3b882152c1ae
* Version Independent ID: b9b95584-5e82-5904-df6c-3bbf7fc59c59
* Content: [Introduction to Web Services - Xamarin](https://docs.microsoft.com/en-us/xamarin/cross-platform/data-cloud/web-services/)
* Content Source: [docs/cross-platform/data-cloud/web-services/index.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/cross-platform/data-cloud/web-services/index.md)
* Product: **xamarin**
* GitHub Login: @asb3993
* Microsoft Alias: **amburns**

**Comment by bradumbaugh** [comment]
Thanks for the heads-up, @dbatemanstl. I've added an issue in our internal backlog to revisit / update this content, so I'm going to close this issue. Appreciate your help.
