### ISSUE TITLE
Stopping, no Google Credentials

### ISSUE THREAD

**Issue by YordanYanakiev** [MicrosoftDocs/xamarin-docs#610]
When I try to complete the procedure, right after signing the application - I am receiving "Stopping, no Google Credentials"
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d22ceddd-69d4-3a5d-2947-a5abddbbd3aa
* Version Independent ID: e238051f-b809-5541-4049-f1205dd0a3a5
* Content: [Signing the Android Application Package - Xamarin](https://docs.microsoft.com/en-us/xamarin/android/deploy-test/signing/?tabs=vswin)
* Content Source: [docs/android/deploy-test/signing/index.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/android/deploy-test/signing/index.md)
* Product: **xamarin**
* GitHub Login: @mgmclemore
* Microsoft Alias: **mamcle**

**Comment by topgenorth** [comment]
Hi @YordanYanakiev, could you provide some more details about this issue?  It's a bit unclear from this message if this is an issue with the docs or perhaps a bug with the IDE. It would help us triage this issue if you could provide some details about your IDE, what you were doing when you encountered the problem.

**Comment by YordanYanakiev** [comment]
Sorry about that, but It was unclear what I need to provide initially ( or at least I was unable to find the requirements ).
So - VS IDE version is 4.6.01590. ( 15.4.3 )
The project is PCL based:
Target .NET : 111
The Android is targeting 8.0 SDK
..
still not sure what I need to provide additionally. Please tell me, and I will post it.

**Comment by YordanYanakiev** [comment]
![sledi](https://user-images.githubusercontent.com/6534199/43569303-b594b3e2-963f-11e8-8202-a2646932c481.png)

**Comment by YordanYanakiev** [comment]
1. The newer versions coming with ginormous for our company issue with PCL projects.
For now higher version of VS for us is a big no-no. ( We actually downgraded to this version after everything turns upside down with 15.5.
2. It was working flawlessly until recently, and we did no changes in there. Anyway I will double check it again according to these notes. Than You for which :)

**Comment by topgenorth** [comment]
I can appreciate your concerns in your first point.  If publishing is broken in Visual Studio 15.5 I would suggest the following:
1. Publish Manually.
2. Raise an issue over at the [Visual Studio Developer Community](https://developercommunity.visualstudio.com/spaces/8/index.html).

**Comment by YordanYanakiev** [comment]
Publish is not broken in 15.5. PCL architecture is messed up in 15.5.
We are publishing currently manually, and this is the thing I am trying to fix, since it tooks additionally time.

**Comment by CSAJakub** [comment]
Mac Xamarin having issues signing APKs since update this week.

**Comment by conceptdev** [comment]
@CSAJakub as noted above, the best place to report issues is on the [Developer Community site](https://developercommunity.visualstudio.com/) which can also be reached in the Help menu from the IDE (Report a problem) or from docs, press the **Product Feedback** button:

![screen shot 2018-08-30 at 1 14 47 pm](https://user-images.githubusercontent.com/199373/44876722-afb77180-ac56-11e8-885f-a746366b7fca.png)

**Comment by ispysoftware** [comment]
I ran into this today after migrating to a new PC. You need to remove and then add the google play account in the distribute process.

**Comment by procopio** [comment]
> I ran into this today after migrating to a new PC. You need to remove and then add the google play account in the distribute process.

This solved my problem too, thanks!
