### ISSUE TITLE
Sadly having some real issues with the second half of this walk though

### ISSUE THREAD

**Issue by mintyhighway** [MicrosoftDocs/xamarin-docs#611]
Ive experienced some real issues with the second half of this walk through. Visual Studio now addeds a launch screen storyboard by default and i cant seem to get the main part of the storyboard to run / connect after the launch screen is triggered. ive been pulling my hair out with this one.

Also some clear advice or a sentence might be helpful as i was creating class files automatically with the attribute tag,  instead of naming the  view controllers class name attribute. 

so the biggest problem im having is that i just cant get the main story board to trigger after the launch screen. I just get a black screen after the launch story board 

any advice would be most helpful

thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8853aece-5bbb-6121-ce6d-f600719ad820
* Version Independent ID: 8037b07e-5bdd-390c-e3be-b3c9233d5249
* Content: [Tab Bars and Tab Bar Controllers in Xamarin.iOS - Xamarin](https://docs.microsoft.com/en-us/xamarin/ios/user-interface/controls/creating-tabbed-applications)
* Content Source: [docs/ios/user-interface/controls/creating-tabbed-applications.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/ios/user-interface/controls/creating-tabbed-applications.md)
* Product: **xamarin**
* GitHub Login: @bradumbaugh
* Microsoft Alias: **brumbaug**

**Comment by bradumbaugh** [comment]
Hi @mintyhighway – sorry to hear you've hit a snag here. I've filed an issue in our internal backlog to review this content for accuracy. Thanks for calling it out.

Unfortunately I can't troubleshoot problems here, but here's one suggestion: maybe open the **Info.plist** file and check that **Main Interface** is set to the name of your main storyboard ( (not the launch screen).

If that doesn't work, and you need further support, please feel free to post on [Developer Community](https://developercommunity.visualstudio.com/spaces/8/index.html).

**Comment by mintyhighway** [comment]
Hi Brad

Many thanks for the reply. Sadly that wasnt he issue. Ive checked list.plist and this was point at the mainstory board. 
Ive been using vS2017 version running on windows 10. 

So not sure problem is. 

Will get onto dev team. 

Thanks :0)
