### ISSUE TITLE
Missing "Async" word in method's name

### ISSUE THREAD

**Issue by Lapinou42** [MicrosoftDocs/xamarin-docs#613]
Hi, 

First of all, thanks a lot for Xamarin.Essentials ! 
I checked this page and I think you should change the method's name:

```
    public async Task OpenRideShare()
    {
        var supportsUri = await Launcher.CanOpenAsync("lyft://");
        if (supportsUri)
            await Launcher.OpenAsync("lyft://ridetype?id=lyft_line");
    }
```

into =>

```
    public async Task OpenRideShareAsync()
    {
        var supportsUri = await Launcher.CanOpenAsync("lyft://");
        if (supportsUri)
            await Launcher.OpenAsync("lyft://ridetype?id=lyft_line");
    }
```

Regards,
Christophe.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 44b2d5f7-bcc1-4561-247e-b3a314738311
* Version Independent ID: 779a0484-4dea-f385-3c5c-708cb8860848
* Content: [Xamarin.Essentials Launcher - Xamarin](https://docs.microsoft.com/en-us/xamarin/essentials/launcher?context=xamarin/xamarin-forms)
* Content Source: [docs/essentials/launcher.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/essentials/launcher.md)
* Product: **xamarin**
* GitHub Login: @jamesmontemagno
* Microsoft Alias: **jamont**

**Comment by bradumbaugh** [comment]
Thanks @Lapinou42 – makes sense to me! I put a PR together for this; should be merged soon. I appreciate the help.
