### ISSUE TITLE
Does not seem to work with control templates

### ISSUE THREAD

**Issue by timahrentlov** [MicrosoftDocs/xamarin-docs#614]
As of 3.10 -&gt; No matter how you angle it, controls templates can't be put in merged dictionaries

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1d23ce09-1c59-1482-036a-f7348090fd00
* Version Independent ID: 9b4213b5-8278-5bea-c73d-0e172d7c0a89
* Content: [Resource Dictionaries - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/xaml/resource-dictionaries)
* Content Source: [docs/xamarin-forms/xaml/resource-dictionaries.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/xaml/resource-dictionaries.md)
* Product: **xamarin**
* GitHub Login: @charlespetzold
* Microsoft Alias: **chape**

**Comment by davidbritch** [comment]
Hi @timahrentlov 

I've just managed to put a `ControlTemplate` in a `ResourceDictionary` file and merge it into the `Application` `ResourceDictionary`:

```
	<Application.Resources>
             <ResourceDictionary Source="Dave.xaml" />
	</Application.Resources>
```

```
<ResourceDictionary xmlns="http://xamarin.com/schemas/2014/forms" xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml">
    <ControlTemplate x:Key="TealTemplate">
        <Grid>
            <Grid.RowDefinitions>
                <RowDefinition Height="0.1*" />
                <RowDefinition Height="0.8*" />
                <RowDefinition Height="0.1*" />
            </Grid.RowDefinitions>
            <Grid.ColumnDefinitions>
                <ColumnDefinition Width="0.05*" />
                <ColumnDefinition Width="0.95*" />
            </Grid.ColumnDefinitions>
            <BoxView Grid.ColumnSpan="2" Color="Teal" />
            <Label Grid.Column="1" Text="Control Template Demo App" TextColor="White" VerticalOptions="Center" />
            <ContentPresenter Grid.Row="1" Grid.ColumnSpan="2" />
            <BoxView Grid.Row="2" Grid.ColumnSpan="2" Color="Teal" />
            <Label Grid.Row="2" Grid.Column="1" Text="(c) Xamarin 2016" TextColor="White" VerticalOptions="Center" />
        </Grid>
    </ControlTemplate>
    <ControlTemplate x:Key="AquaTemplate">
        <Grid>
            <Grid.RowDefinitions>
                <RowDefinition Height="0.1*" />
                <RowDefinition Height="0.8*" />
                <RowDefinition Height="0.1*" />
            </Grid.RowDefinitions>
            <Grid.ColumnDefinitions>
                <ColumnDefinition Width="0.05*" />
                <ColumnDefinition Width="0.95*" />
            </Grid.ColumnDefinitions>
            <BoxView Grid.ColumnSpan="2" Color="Aqua" />
            <Label Grid.Column="1" Text="Control Template Demo App" TextColor="Blue" VerticalOptions="Center" />
            <ContentPresenter Grid.Row="1" Grid.ColumnSpan="2" />
            <BoxView Grid.Row="2" Grid.ColumnSpan="2" Color="Aqua" />
            <Label Grid.Row="2" Grid.Column="1" Text="(c) Xamarin 2016" TextColor="Blue" VerticalOptions="Center" />
        </Grid>
    </ControlTemplate>
</ResourceDictionary>
```

It worked without any problems with 3.1. Am I missing something from what you're trying to achieve?

**Comment by timahrentlov** [comment]
Hi David,

Thanks for having a look at this.

I tried with a rather large customer app with a *lot* of styles. I will try to return to this issue when I get the time for another try and can refine this issue.

**Comment by timahrentlov** [comment]
I tried moving just colors out to a XAML folder

`<?xml version="1.0" encoding="UTF-8"?>
<ResourceDictionary
	xmlns="http://xamarin.com/schemas/2014/forms"
	xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml">

	
	<Color
		x:Key="identityColor">
		#00A0D6
	</Color>
    
	
	<Color
		x:Key="whiteColor">
		#FFFFFF
	</Color>
	<Color
		x:Key="brightGreyColor">
		#F5F5FA
	</Color>
	<Color
		x:Key="mediumGreyColor">
		#BEBEBE
	</Color>
	<Color
		x:Key="bgrGreyColor">
		#ECECEC
	</Color>
	<Color
		x:Key="mediumBlue1Color">
		#007CB8
	</Color>
	<Color
		x:Key="mediumBlue2Color">
		#006090
	</Color>
	<Color
		x:Key="darkGreyColor">
		#5E5E5E
	</Color>
	<Color
		x:Key="darkBlueColor">
		#25335E
	</Color>
	<Color
		x:Key="blackColor">
		#1E1E1E
	</Color>
	<Color
		x:Key="allBlackColor">
		#000000
	</Color>
    
	
	<Color
		x:Key="greenColor">
		#17AC39
	</Color>
	<Color
		x:Key="purpleColor">
		#A505CC
	</Color>
	<Color
		x:Key="orangeColor">
		#FF7200
	</Color>
	<Color
		x:Key="redColor">
		#EE2222
	</Color>
	
	<Color
		x:Key="disabledGreenColor">
		#94E0BA
	</Color>
	<Color
		x:Key="disabledRedColor">
		#FFBABC
	</Color>
	<Color
		x:Key="disabledBlueColor">
		#9FDDF1
	</Color>

</ResourceDictionary>`

and then replacing them with a

`<?xml version="1.0" encoding="utf-8" ?>
<prism:PrismApplication
	x:Class="MyApp"
	xmlns="http://xamarin.com/schemas/2014/forms"
	xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
	xmlns:local="clr-namespace:MyApp"
	xmlns:prism="clr-namespace:Prism.DryIoc;assembly=Prism.DryIoc.Forms">
	<prism:PrismApplication.Resources>
		<ResourceDictionary>
		
			<ResourceDictionary Source="XAML/Colors.xaml" />
			
			
			<local:BarcodeToStringConverter
				x:Key="BarcodeToStringConverter" />
			<local:GreaterThanZeroConverter
				x:Key="GreaterThanZeroConverter" />
			<local:StringNullOrEmptyConverter
				x:Key="StringNullOrEmptyConverter" />
			<local:InvertBoolConverter
				x:Key="InvertBoolConverter" />

etc. (monster app.xaml continues) ..
`
but the app is then no longer able to push pages. 

Can you spot what I'm doing wrong?

**Comment by davidbritch** [comment]
My *guess* is that you need to change:

```
	<prism:PrismApplication.Resources>
		<ResourceDictionary>		
			<ResourceDictionary Source="XAML/Colors.xaml" />
                        ...
```

to:

```
	<prism:PrismApplication.Resources>
		<ResourceDictionary Source="XAML/Colors.xaml">		
                ...
```

**Comment by timahrentlov** [comment]
Hmm. Does not seem to work. Seems like page instantiation is not working.

**Comment by davidbritch** [comment]
I'd recommend narrowing this down to the simplest repo case e.g. don't use Prism.

**Comment by timahrentlov** [comment]
I understand. Unfortunately the current focus is to simplify a very large XAML repo in a customer project. If I get a chance during a new project, I will introduce merged dictionaries early in process so that I become aware when/if the dictionaries fail. For now I will be hesitant adding merged dictionaries to existing large projects.

Thanks David.
