### ISSUE TITLE
Behaviours does not work in control templates

### ISSUE THREAD

**Issue by timahrentlov** [MicrosoftDocs/xamarin-docs#615]
https://forums.xamarin.com/discussion/88518/behaviors-in-controltemplates

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cab55939-7f2e-1342-116b-b59272c5a891
* Version Independent ID: a62f69b7-5a96-2d27-e6d2-47a6c17ad7c7
* Content: [Binding from a Xamarin.Forms ControlTemplate - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/templates/control-templates/template-binding)
* Content Source: [docs/xamarin-forms/app-fundamentals/templates/control-templates/template-binding.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/app-fundamentals/templates/control-templates/template-binding.md)
* Product: **xamarin**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @timahrentlov 

You need to file an issue for this, including a simple reproduction in the [Xamarin.Forms](github.com/xamarin/Xamarin.Forms) repo.
