### ISSUE TITLE
TabbedPage ToolbarPlacement

### ISSUE THREAD

**Issue by ClintBrown1** [MicrosoftDocs/xamarin-docs#616]
The TabbedPage ToolbarPlacement isn't working in either the XAML or the C# for me. It is saying the property ToolbarPlacement was not found in type TabbedPage. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a4281f61-1386-2c1d-57fa-9fd66bf64cd7
* Version Independent ID: c762cb60-96b6-a123-37cb-f118da81773b
* Content: [Android Platform-Specifics - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/platform/platform-specifics/consuming/android#tabbedpage-toolbar)
* Content Source: [docs/xamarin-forms/platform/platform-specifics/consuming/android.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/platform/platform-specifics/consuming/android.md)
* Product: **xamarin**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @ClintBrown1 

I've just tried the [sample](https://developer.xamarin.com/samples/xamarin-forms/userinterface/platformspecifics/) and it works fine for me in both XAML and C#. Have you tried the sample?

Note that Xamarin.Forms 3.1 is required to use this platform-specific.

**Comment by grsmvmsk** [comment]
I have same issue. Xamarin.Forms v3.1.0.697729

**Comment by davidbritch** [comment]
Hi @grsmvmsk 

If you think there's a bug in the feature you need to report it in the [Xamarin.Forms](https://github.com/xamarin/Xamarin.Forms/) repo, with a reproduction case that demonstrates it failing.

**Comment by grsmvmsk** [comment]
Hi @davidbritch 
I rebuilded solution and problem has gone
