### ISSUE TITLE
VideoPlayer not referenced in XAML

### ISSUE THREAD

**Issue by titonton** [MicrosoftDocs/xamarin-docs#619]
My XAML file can't find the VideoPlayer. I tried cleaning and Rebuilding, still can't find it

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 08231611-5a52-267d-cfc6-0042e5d5c2a3
* Version Independent ID: 6c39962d-a013-a391-9f1f-4a69f3a99de0
* Content: [Playing a Web video - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/custom-renderer/video-player/web-videos)
* Content Source: [docs/xamarin-forms/app-fundamentals/custom-renderer/video-player/web-videos.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/app-fundamentals/custom-renderer/video-player/web-videos.md)
* Product: **xamarin**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @titonton 

Try loading the sample, which is linked to from the "Related Links" section at the end of the doc.
