### ISSUE TITLE
Documentation should be more clear

### ISSUE THREAD

**Issue by RazvanEmilR** [MicrosoftDocs/xamarin-docs#620]
What is the difference between the channel name and the channel ID and how should it appear in Resources/Strings (where I assume it should be located) because this documentation assumes Resource.String.noti_chan_urgent already exists, but it does not specify how to create it and how it should look. Since it is part of this documenation it should be covered as well.

Second issue is, at what point is this code incorporated into the project flow, for example within OnMessageReceived() ? It is out of context without any linking advice within an app.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 78e442e3-b387-f538-5430-e4538cf60cb9
* Version Independent ID: 44dc930e-09e2-56e8-e693-18a69af0a747
* Content: [Local Notifications - Xamarin](https://docs.microsoft.com/en-us/xamarin/android/app-fundamentals/notifications/local-notifications)
* Content Source: [docs/android/app-fundamentals/notifications/local-notifications.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/android/app-fundamentals/notifications/local-notifications.md)
* Product: **xamarin**
* GitHub Login: @mgmclemore
* Microsoft Alias: **mamcle**

**Comment by mgmclemore** [comment]
Hi @RazvanEmilR, thank you for the feedback!  This topic is currently being updated, so I've added your comments to ensure that your questions are covered when the new version is published.
