### ISSUE TITLE
Minor mistake in docs above

### ISSUE THREAD

**Issue by devmikew** [MicrosoftDocs/xamarin-docs#621]
It says;
 or just before the ContentPage-derived page is constructed

I don't think that is correct, surely the page needs to be constructed before one can use it?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2e9d651b-6624-f671-16e2-61c28415374b
* Version Independent ID: 61600bb9-66b3-904d-6be3-32029e78bc5a
* Content: [Xamarin.Forms in Xamarin Native Projects - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/platform/native-forms)
* Content Source: [docs/xamarin-forms/platform/native-forms.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/platform/native-forms.md)
* Product: **xamarin**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Closed due to https://github.com/MicrosoftDocs/xamarin-docs/issues/622
