### ISSUE TITLE
Once again Xamarin fails.

### ISSUE THREAD

**Issue by aarcoraci** [MicrosoftDocs/xamarin-docs#623]
Followed these steps. Nothing fancy. Just added a simple theme changing one color. Added style.xml on both: values and values-21. Trying to run the app and I get:
: Error inflating class android.support.v7.widget.Toolbar

The only thing I regret is not starting my current project with react native. Ive been working with .Net for 13 years now and every single time I have to deal with Xamarin is the most stressful one ever. I cannot believe the alpha stage of everything, even the documentation.

version 15.7.6

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 87b678e7-5336-db4f-02ac-db6d2115ebec
* Version Independent ID: 5434c705-8fa7-f2ed-e358-6c05d915cde0
* Content: [Material Theme - Xamarin](https://docs.microsoft.com/en-us/xamarin/android/user-interface/material-theme)
* Content Source: [docs/android/user-interface/material-theme.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/android/user-interface/material-theme.md)
* Product: **xamarin**
* GitHub Login: @mgmclemore
* Microsoft Alias: **mamcle**

**Comment by topgenorth** [comment]
Sorry that you're experiencing these difficulties. I believe that you also need the [Xamarin.Android.Support.v7.AppCompat](https://www.nuget.org/packages/Xamarin.Android.Support.v7.AppCompat/) NuGet package as well. 

I've added your concern to our list of things to review, and we'll review this guide for accuracy and correctness.
