### ISSUE TITLE
Something went wrong, please contact the application owner: 

### ISSUE THREAD

**Issue by psimec** [MicrosoftDocs/xamarin-docs#624]
I'm getting error message every time

"Something went wrong, please contact the application owner: {"code"=&gt;"ITC.apps.tf.max.app.testers", "description"=&gt;"Failed to create tester."}"
Can someone help me

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 79320e9a-8b52-1c24-0a5b-a7ef6a32b519
* Version Independent ID: 88548723-6f1b-50c1-163c-a9e151b024e8
* Content: [Xamarin Live Player Setup - Xamarin](https://docs.microsoft.com/en-us/xamarin/tools/live-player/install?tabs=android%2Cwindows)
* Content Source: [docs/tools/live-player/install.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/tools/live-player/install.md)
* Product: **xamarin**
* GitHub Login: @topgenorth
* Microsoft Alias: **toopge**

**Comment by bradumbaugh** [comment]
This should be fixed. Please give it another try!

**Comment by ColinNg** [comment]
It's broken again today. :( 
Something went wrong, please contact the application owner: {"code"=>"ITC.apps.tf.max.app.testers", "description"=>"Failed to create tester."}

**Comment by psimec** [comment]
Plus I didnt get my mail since monday :(

**Comment by erhanalankus** [comment]
I just got this error
https://i.imgur.com/QOhN2qK.png

**Comment by AviralGarg1993** [comment]
I am getting this error as well.

**Comment by AviralGarg1993** [comment]
Same error as @erhanalankus, no email either.

**Comment by CaliberMengsk** [comment]
Same for me, can't register to get it. Error sounds like too many users have registered for however it is suppose to get downloaded or what not.

**Comment by ColinNg** [comment]
As of this moment it is working again!
