### ISSUE TITLE
The first image in the "Creating the Bindings Library" section is wrong.

### ISSUE THREAD

**Issue by yanxiaodi** [MicrosoftDocs/xamarin-docs#626]
We should use the Android Bindings Library template but the image highlights the Android App (Xamarin) template. Is it wrong?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5bbb17d4-dc14-6eb9-8f83-58feba90ca73
* Version Independent ID: 2c3cf6ac-1e80-abd5-7564-b01531c5dbf2
* Content: [Binding a .JAR - Xamarin](https://docs.microsoft.com/en-us/xamarin/android/platform/binding-java-library/binding-a-jar)
* Content Source: [docs/android/platform/binding-java-library/binding-a-jar.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/android/platform/binding-java-library/binding-a-jar.md)
* Product: **xamarin**
* GitHub Login: @mgmclemore
* Microsoft Alias: **mamcle**

**Comment by topgenorth** [comment]
Good catch - seems some images got mixed up. A fix is working it's way through our publishing pipeline.
