### ISSUE TITLE
Would be worth noting that this does not support physical Android devices

### ISSUE THREAD

**Issue by GregHDC** [MicrosoftDocs/xamarin-docs#627]
It would have saved me a step or two if it was clear that this only works on emulators.

Edit: I misinterpreted the "physical devices not supported" message to assume it works on emulators. 
When running on an emulator, the 'inspect' toolbar button is disabled.

Clearly some clarity around what's required would be of benefit here.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aaddaa8d-6e8e-8b12-bcf4-284175238bbe
* Version Independent ID: 6e3d847c-badc-904d-0ff5-a66e1fc8bc81
* Content: [Inspector Installation and Requirements - Xamarin](https://docs.microsoft.com/en-us/xamarin/tools/inspector/install?tabs=windows)
* Content Source: [docs/tools/inspector/install.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/tools/inspector/install.md)
* Product: **xamarin**
* GitHub Login: @topgenorth
* Microsoft Alias: **toopge**

**Comment by topgenorth** [comment]
Hi there.  We try to keep our docs as clear and understandable as possible.   I do see that the [Installation and requirements](https://docs.microsoft.com/en-us/xamarin/tools/inspector/install?#supported-app-platforms) guide does state:
> Must use Google, Visual Studio, or Xamarin Android emulators

Is there something different that you feel would have been more helpful or clear?
