### ISSUE TITLE
Example?

### ISSUE THREAD

**Issue by PatrickRyder** [MicrosoftDocs/xamarin-docs#628]
An example or link to example code would make the article a lot more useful.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5db8edac-1e3c-80e4-98f3-ac7c750715fd
* Version Independent ID: c45c9369-3fcc-aac3-7ecd-9eb1f0d7fcb7
* Content: [Introduction to Effects - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/effects/introduction)
* Content Source: [docs/xamarin-forms/app-fundamentals/effects/introduction.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/app-fundamentals/effects/introduction.md)
* Product: **xamarin**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
The sample is linked to from the [Effect Creation](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/effects/creating) page.
