### ISSUE TITLE
override void OnLayout

### ISSUE THREAD

**Issue by pmahend1** [MicrosoftDocs/xamarin-docs#629]
Seems verride void OnLayout is also needed. Worked for me when I added that too. 
Please review

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c36e7942-65b6-9877-aafd-5f1b1291d37d
* Version Independent ID: 77a599a6-43f2-068f-95ad-0a92ca2b4bca
* Content: [Customizing a ContentPage - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/custom-renderer/contentpage)
* Content Source: [docs/xamarin-forms/app-fundamentals/custom-renderer/contentpage.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/app-fundamentals/custom-renderer/contentpage.md)
* Product: **xamarin**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @pmahend1 

On which platform?

**Comment by pmahend1** [comment]
@davidbritch Android

**Comment by davidbritch** [comment]
Hi @pmahend1 

If you look in the Related Links section in each doc, there's a link to a sample that has full source code for what's being discussed in the doc. The Android renderer already overrides `OnLayout`. It just doesn't get a mention in the doc. I've given it an update, which should go live within a few days.
