### ISSUE TITLE
Clarify "Step 4 - Testing and loading new languages"

### ISSUE THREAD

**Issue by alfredmyers** [MicrosoftDocs/xamarin-docs#63]
After skimming through the [Step 4 - Testing and loading new languages](https://docs.microsoft.com/en-us/xamarin/android/platform/speech#step-4---testing-and-loading-new-languages) section of the Android Speech article, I was under the impression that it would be possible to download a new language, let's say Brazilian Portuguese, to Google's stock AVD for KitKat.

Only after a closer look at the sample code I noticed that the language/country pair isn't passed to the Activity that would be responsible for downloading the language/voice data.

Given that the sample code is similar to the code found on the TTS's [announcement](https://android-developers.googleblog.com/2009/09/introduction-to-text-to-speech-in.html) on Android Developer's blog, my current understanding is that:
- If not already present on the device, supported ([`TextToSpeech.IsLanguageAvailable`](https://developer.xamarin.com/api/member/Android.Speech.Tts.TextToSpeech.IsLanguageAvailable/p/Java.Util.Locale/) >= [`LanguageAvailableResult.Available`](https://developer.xamarin.com/api/field/Android.Speech.Tts.LanguageAvailableResult.Available/)) language/voice data can be downloaded using the sample code provided.
- [`TextToSpeech.IsLanguageAvailable`](https://developer.xamarin.com/api/member/Android.Speech.Tts.TextToSpeech.IsLanguageAvailable/p/Java.Util.Locale/) == [`LanguageAvailableResult.NotSupported`](https://developer.xamarin.com/api/field/Android.Speech.Tts.LanguageAvailableResult.NotSupported/) is kind of final: there's no language/voice package available (even for download) for that language.

Either way, the text or the sample code could be improved to make it more clear what we should expect from the API.

**Comment by mgmclemore** [comment]
Hi @alfredmyers, this topic has been updated to better explain how the above APIs work (with screenshots of the activity that gets launched). The changes should be published soon. Thanks again for pointing this out!
