### ISSUE TITLE
Persistance and syncing across devices

### ISSUE THREAD

**Issue by nhwilly** [MicrosoftDocs/xamarin-docs#630]
I'm having some trouble figuring out under what conditions my cross platform app might be sharing data across devices.  It's entirely plausible (in fact, likely) that our users will have both a mobile and desktop (UWP) version of the same product.

We do *not* want to share certain portions of the data between devices, even it if is the same user and same app.

Will preferences or secure storage accomplish this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a7a399b1-a8a2-9cbd-c479-1bd98af46988
* Version Independent ID: 91a6ae06-508b-b668-52aa-cbdeabb2b46a
* Content: [Xamarin.Essentials: Preferences - Xamarin](https://docs.microsoft.com/en-us/xamarin/essentials/preferences?tabs=ios#persistence)
* Content Source: [docs/essentials/preferences.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/essentials/preferences.md)
* Product: **xamarin**
* GitHub Login: @jamesmontemagno
* Microsoft Alias: **jamont**

**Comment by jamesmontemagno** [comment]
Secure Storage and Preferences do not have any sync with iCloud or data backup at all. Just local to the device. They would be backed up when upgrading from device to device on backup.

**Comment by nhwilly** [comment]
Wow. Thanks for the quick reply, and for all the libraries.  Exactly what I needed to know and I know exactly what to do next.
