### ISSUE TITLE
if you are having problem in the UMP file this could help 

### ISSUE THREAD

**Issue by mohaned1001** [MicrosoftDocs/xamarin-docs#631]
if you have problem in UMP file and you cant build because of it 
and the problem is the "PhoneLine"
then you need to go back to the step 28 and make sure to download the same version of  Windows Mobile Extensions for UWP that they downloaded 
if you downloaded the version 10.0.17xxx it will not work  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2de3e72c-8948-4dd5-e37f-9cf81e62c127
* Version Independent ID: 7b7c5c7f-4102-8e91-fbe6-7d21fcc8f5be
* Content: [Xamarin.Forms Quickstart - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/get-started/hello-xamarin-forms/quickstart?tabs=vswin)
* Content Source: [docs/xamarin-forms/get-started/hello-xamarin-forms/quickstart.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/get-started/hello-xamarin-forms/quickstart.md)
* Product: **xamarin**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @mohaned1001 

Thanks for pointing this out. It's fixed in a PR that will be published within a few days.
