### ISSUE TITLE
Link into this article appears misleading

### ISSUE THREAD

**Issue by PatrickRyder** [MicrosoftDocs/xamarin-docs#633]
The link I followed in here was about events to commands but I can't find anything about this in this article.  This was the page I came from: https://developer.xamarin.com/samples/xamarin-forms/Behaviors/EventToCommandBehavior/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: de196cde-8c57-8c92-4495-fcfa066682f9
* Version Independent ID: 50986b5c-9e22-fd23-aed7-2d3b15ae0dbf
* Content: [Xamarin.Forms Behaviors - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/behaviors/creating)
* Content Source: [docs/xamarin-forms/app-fundamentals/behaviors/creating.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/app-fundamentals/behaviors/creating.md)
* Product: **xamarin**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @PatrickRyder 

The page you want is: https://docs.microsoft.com/en-gb/xamarin/xamarin-forms/app-fundamentals/behaviors/reusable/event-to-command-behavior

I'll update the link.
