### ISSUE TITLE
Some images not showing

### ISSUE THREAD

**Issue by sirwes** [MicrosoftDocs/xamarin-docs#634]
I'm using a data template to show different images in android. They are all png's in the Resources/drawable folder, and I use the same source call to implement them, but only two of them show up. Are there any hidden requirements about what the image needs to be? All of them are 512x512, the same color and everything. The only difference is that the image is different

**Comment by conceptdev** [comment]
@sirwes please use **Help > Send Feedback > Report a Problem** [in Visual Studio](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio-2017) to submit issues and bug reports to the [developer community site](https://developercommunity.visualstudio.com/). This feedback is intended for dealing with issues in the docs, thanks.
