### ISSUE TITLE
Maybe remove the Windows Phone screenshot or replace with UWP?

### ISSUE THREAD

**Issue by JeroMiya** [MicrosoftDocs/xamarin-docs#635]
Having the Windows Phone screenshot makes the documentation look out of date. Perhaps remove it, or replace it with the equivalent UWP version?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 27fe1735-8c68-df52-a550-cf6f41f9544d
* Version Independent ID: 819283af-b1ec-ed39-12db-9bd81981a9cb
* Content: [Reusable EffectBehavior - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/behaviors/reusable/effect-behavior)
* Content Source: [docs/xamarin-forms/app-fundamentals/behaviors/reusable/effect-behavior.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/app-fundamentals/behaviors/reusable/effect-behavior.md)
* Product: **xamarin**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by conceptdev** [comment]
@JeroMiya agreed - we are gradually going through and updating to use Windows UWP screenshots - there are a lot to change! For now, I'll just remove the Windows Phone item here.
