### ISSUE TITLE
Live reload not working in UWP

### ISSUE THREAD

**Issue by anirudhagupta** [MicrosoftDocs/xamarin-docs#636]
It's work fine for android but didn't seem working for UWP, Please check, I tried with run without debugging

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e40394ca-9a55-d9b5-d427-7c2a2c00cfc8
* Version Independent ID: 5a5c17e2-a683-88f6-07a9-2002e814d54c
* Content: [Live Reload - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/xaml/live-reload)
* Content Source: [docs/xamarin-forms/xaml/live-reload.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/xaml/live-reload.md)
* Product: **xamarin**
* GitHub Login: @pierceboggan
* Microsoft Alias: **piboggan**

**Comment by conceptdev** [comment]
@anirudhagupta please use **Help > Send Feedback > Report a Problem** [in Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio-2017) to submit issues and bug reports to the [developer community site](https://developercommunity.visualstudio.com/). Also, this feature is still in Preview. This feedback is intended for dealing with issues in the docs, thanks.
