### ISSUE TITLE
Document markdown formatting syntax wrong

### ISSUE THREAD

**Issue by CeciAc** [MicrosoftDocs/xamarin-docs#637]
@inascf commented on [Wed Aug 08 2018](https://github.com/MicrosoftDocs/xamarin-docs.zh-cn/issues/7)

``` 
![拖放 framework]Images/hello-from-csharp-ios-drag-drop-framework.png)
```
miss a "("

[在此处输入反馈]

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: e624548b-1611-c17b-0984-1344c7585ffc
* Version Independent ID: 684e167e-49fd-3f06-9a9c-1ee253635086
* Content: [IOS 入门 - Xamarin](https://docs.microsoft.com/zh-cn/xamarin/tools/dotnet-embedding/get-started/objective-c/ios)
* Content Source: [docs/tools/dotnet-embedding/get-started/objective-c/ios.md](https://github.com/MicrosoftDocs/xamarin-docs.zh-CN/blob/live/docs/tools/dotnet-embedding/get-started/objective-c/ios.md)
* Product: **xamarin**
* GitHub Login: @topgenorth
* Microsoft Alias: **toopge**

---

@inascf commented on [Wed Aug 08 2018](https://github.com/MicrosoftDocs/xamarin-docs.zh-cn/issues/7#issuecomment-411296921)

```
![拖放 framework](ios-images/hello-from-csharp-ios-drag-drop-framework.png)
```  
 maybe is right

**Comment by CeciAc** [comment]
Hi team, 
I moving this here since it seems there's a missing "(" in the code which replicates in localized versions

Kind regards,
Microsoft DOCS International Team

**Comment by conceptdev** [comment]
Thanks @CeciAc fixed in the original doc!
