### ISSUE TITLE
Manual Provisioning location is wrong.

### ISSUE THREAD

**Issue by Keboo** [MicrosoftDocs/xamarin-docs#638]
Under [Update the Release build configuration](https://docs.microsoft.com/en-us/xamarin/ios/deploy-test/app-distribution/app-store-distribution/publishing-to-the-app-store?tabs=vswin#update-the-release-build-configuration) inside of the Visual Studio tab, step 1. It says: "From the Solution Explorer, open Info.plist. Select Manual Provisioning. Save and close the file."

This is not where you configuring the provisioning profile in Visual Studio. It should be something more like:
Right-click on the Project Name in the Solution Explorer, select Properties, and navigate to the iOS Bundle Signing tab. Select Manual Provisioning. Save and close the file.

This mistake is repeated in step 12 in the same section.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bb327a64-010d-dba8-5ebc-546892d739af
* Version Independent ID: 48a24297-7b8f-b1b2-7b25-44f40fe33eac
* Content: [Publishing Xamarin.iOS apps to the App Store - Xamarin](https://docs.microsoft.com/en-us/xamarin/ios/deploy-test/app-distribution/app-store-distribution/publishing-to-the-app-store?tabs=vswin)
* Content Source: [docs/ios/deploy-test/app-distribution/app-store-distribution/publishing-to-the-app-store.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/ios/deploy-test/app-distribution/app-store-distribution/publishing-to-the-app-store.md)
* Product: **xamarin**
* GitHub Login: @bradumbaugh
* Microsoft Alias: **brumbaug**

**Comment by Keboo** [comment]
![image](https://user-images.githubusercontent.com/952248/43862511-c4be35ea-9b0e-11e8-8836-6a611d0363fc.png)

**Comment by bradumbaugh** [comment]
Thanks for calling this out @Keboo – looks like the VSMac instructions were incorrectly duplicated for VS2017. Fixed this in a PR that's working it's way through the publishing system now. Appreciate your help.
