### ISSUE TITLE
Different screenshots in the Release build configuration

### ISSUE THREAD

**Issue by Keboo** [MicrosoftDocs/xamarin-docs#639]
Under [Update the Release build configuration](https://docs.microsoft.com/en-us/xamarin/ios/deploy-test/app-distribution/app-store-distribution/publishing-to-the-app-store?tabs=vswin#update-the-release-build-configuration) there are screenshots shots showing what the final result of the iOS Build settings should look like. On the Visual Studio for Mac screenshot the "Perform all 32-bit float operations as 64-bit float" checkbox is unchecked while on the Visual Studio tab it shows checked.
I believe the Visual Studio settings are correct as this is the default setting with the latest Xamarin.iOS project templates.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bb327a64-010d-dba8-5ebc-546892d739af
* Version Independent ID: 48a24297-7b8f-b1b2-7b25-44f40fe33eac
* Content: [Publishing Xamarin.iOS apps to the App Store - Xamarin](https://docs.microsoft.com/en-us/xamarin/ios/deploy-test/app-distribution/app-store-distribution/publishing-to-the-app-store?tabs=vswin#update-the-release-build-configuration)
* Content Source: [docs/ios/deploy-test/app-distribution/app-store-distribution/publishing-to-the-app-store.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/ios/deploy-test/app-distribution/app-store-distribution/publishing-to-the-app-store.md)
* Product: **xamarin**
* GitHub Login: @bradumbaugh
* Microsoft Alias: **brumbaug**

**Comment by bradumbaugh** [comment]
Thanks @Keboo. I've updated the VS2017 screenshot to turn off this option. Take a look at [this blog post](https://tirania.org/blog/archive/2018/Apr-11.html) for details. The update should be published soon.
