### ISSUE TITLE
why do none of your test solutions work?

### ISSUE THREAD

**Issue by graftedin** [MicrosoftDocs/xamarin-docs#64]
Why don't you have an android emulator in visual basic that works.  None of this stuff works?  Why would anyone want to PAY for this when we can't even get it to work for free.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2de3e72c-8948-4dd5-e37f-9cf81e62c127
* Version Independent ID: 7b7c5c7f-4102-8e91-fbe6-7d21fcc8f5be
* Content: [Xamarin.Forms Quickstart - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/get-started/hello-xamarin-forms/quickstart?tabs=vswin)
* Content Source: [docs/xamarin-forms/get-started/hello-xamarin-forms/quickstart.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/get-started/hello-xamarin-forms/quickstart.md)
* Service: **unspecified**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by conceptdev** [comment]
@graftedin getting an emulator set up can be challenging, we have tried to cover all the details and potential problems in our setup docs:

https://docs.microsoft.com/en-us/xamarin/android/get-started/installation/android-emulator/

For getting started, you might also wish to try the Android Xamarin Live Player, which will let you "try out" Xamarin.Forms without requiring the emulator:

https://docs.microsoft.com/en-us/xamarin/tools/live-player/
