### ISSUE TITLE
Typo in mtouch arguments

### ISSUE THREAD

**Issue by Keboo** [MicrosoftDocs/xamarin-docs#640]
In the [Simulator Tricks](https://docs.microsoft.com/en-us/xamarin/ios/deploy-test/ios-build-mechanics?tabs=vsmac#simulator-tricks) the last bullet point says: "When in doubt, use the `–time –time` flag to measure your change". The correct argument should have two hyphens: "When in doubt, use the `--time --time` flag to measure your change". This is how it is displayed in the screenshot just below the aforementioned line, as well as elsewhere on the page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1efe78cc-e734-4e9c-f43e-df3fcdfb2e3b
* Version Independent ID: dc42f7ee-52bd-5666-2fdf-4c03144524a4
* Content: [iOS Build Mechanics - Xamarin](https://docs.microsoft.com/en-us/xamarin/ios/deploy-test/ios-build-mechanics?tabs=vsmac#tips)
* Content Source: [docs/ios/deploy-test/ios-build-mechanics.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/ios/deploy-test/ios-build-mechanics.md)
* Product: **xamarin**
* GitHub Login: @bradumbaugh
* Microsoft Alias: **brumbaug**

**Comment by bradumbaugh** [comment]
Thanks for the help, @Keboo – fix should be published soon.
