### ISSUE TITLE
Wrong code sample format for Edit Text?

### ISSUE THREAD

**Issue by Tennyleaz** [MicrosoftDocs/xamarin-docs#643]
The first code block in Docs/Xamarin/Xamarin.Android/User Interface/Controls/EditText looks formatted wrongly:

    <pre><code class=" syntax brush-C#">&lt;EditText
        android:id="@+id/edittext"
        android:layout_width="fill_parent"
        android:layout_height="wrap_content"/&gt;</code></pre>

I think it should be:

    <EditText
        android:id="@+id/edittext"
        android:layout_width="fill_parent"
        android:layout_height="wrap_content"/>

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fbed39db-9267-20b8-2e14-8bdcdb7acba2
* Version Independent ID: 6b35fc6c-93af-b8d7-7749-7ecdba5102b5
* Content: [Edit Text - Xamarin](https://docs.microsoft.com/en-us/xamarin/android/user-interface/controls/edit-text#feedback)
* Content Source: [docs/android/user-interface/controls/edit-text.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/android/user-interface/controls/edit-text.md)
* Product: **xamarin**
* GitHub Login: @mgmclemore
* Microsoft Alias: **mamcle**

**Comment by mgmclemore** [comment]
Hi @Tennyleaz, thank you for the feedback!  Yes, the formatting is wrong -- we'll have that fixed shortly.
