### ISSUE TITLE
add documentation for - displaying images within folders 

### ISSUE THREAD

**Issue by pmahend1** [MicrosoftDocs/xamarin-docs#644]
what if I create a folder within Android `res&gt;drawable` as `icons` and then try to load the image.

- icons.image_name.png - does not work
- icons/image_name.png - does not work
- icons\image_name.png - does not work

Is it simply not possible within XAML at this point of time?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7eeb0e65-143b-0f5e-a8fb-c75309689338
* Version Independent ID: 6b984264-a950-4310-483f-99f908b0a8b0
* Content: [Images in Xamarin.Forms - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/images?tabs=vswin#related-links)
* Content Source: [docs/xamarin-forms/user-interface/images.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/images.md)
* Product: **xamarin**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @pmahend1 

On iOS and Windows you can place your image in subfolders of the root image folder. However, this isn't possible on Android. Images have to be directly in the drawable* folders.

**Comment by mauner10** [comment]
I'm working with Xamarin/Android/Xaml and created a phone app that takes pictures using the camera and stores them in a new folder on my phone called "Sample".  This all works fine and I'm able to re-display that new image. My issue is I have not been successful trying to display "all" the images in the "Sample" folder.  Most of the sample code above displays photos stored locally.  I'm trying display photos/images from a folder on my phone.  I'm able to display the "complete path" used in a DisplayAlert.  I tried photo.Path and photo.AlbumPath.  Neither work.  Below is a portion of my code: 

var photo = await CrossMedia.Current.TakePhotoAsync(new StoreCameraMediaOptions
{
	Directory = "Sample",
	Name = "test.jpg",
	PhotoSize = PhotoSize.Medium,
	CompressionQuality = 92,
	SaveToAlbum = true
});

if (photo != null)
{
	// Works OK - Displays picture taken back on the home screen
	PhotoImage.Source = ImageSource.FromStream(() =>
	{
		var stream = photo.GetStream();
		return stream;
         });

          MainCarouselView.ItemsSource = photo.AlbumPath;  // Does not work
          photo.Dispose();

	   return;   // *** Needed - otherwise the Camera App closes
};
---------------

<Label Text="IMAGES BELOW" TextColor="Black" FontSize="20" Margin="2"/>
		
<forms:CarouselView x:Name="MainCarouselView">
	<forms:CarouselView.ItemTemplate>
		<DataTemplate>
			<Image Source="{Binding .}" x:Name="image"   
                                                          Aspect="AspectFill"/>
							   
		</DataTemplate>
	</forms:CarouselView.ItemTemplate>
</forms:CarouselView>

**Comment by mauner10** [comment]
The bottom portion of MainPage.xaml is:

<Label Text="IMAGES BELOW" TextColor="Black" FontSize="20" Margin="2"/>
		
<forms:CarouselView x:Name="MainCarouselView"     
    <forms:CarouselView.ItemTemplate>
	  <DataTemplate>
		           <Image Source="{Binding .}" x:Name="image" Aspect="AspectFill" 
              RelativeLayout.XConstraint="{ConstraintExpression Type=RelativeToParent, Property=Width, Factor=0.15}" 	
              RelativeLayout.YConstraint="{ConstraintExpression Type=RelativeToParent, Property=Height, Factor=0.10}"
               RelativeLayout.WidthConstraint="{ConstraintExpression Type=RelativeToParent, Property=Width, Factor=0.7}"
               RelativeLayout.HeightConstraint="{ConstraintExpression Type=RelativeToParent, Property=Height, Factor=0.7}"/>
	 </DataTemplate>
  </forms:CarouselView.ItemTemplate>
</forms:CarouselView>
