### ISSUE TITLE
Where is Visual Studio Tools for Xamarin?

### ISSUE THREAD

**Issue by JNickVA1** [MicrosoftDocs/xamarin-docs#646]
The Requirements section states that Visual Studio Tools for Xamarin, version 4.10.0 or later, must be installed. I have searched the Marketplace and I cannot find such a thing. Please either fix the section or put in a link to the Visual Studio Tools for Xamarin.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dac28e18-875a-cb51-a031-717692255d0a
* Version Independent ID: f2e625c7-18a7-c090-fa92-9d635ac39164
* Content: [Setting up the Android SDK for Xamarin.Android - Xamarin](https://docs.microsoft.com/en-us/xamarin/android/get-started/installation/android-sdk?tabs=vswin#Requirements)
* Content Source: [docs/android/get-started/installation/android-sdk.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/android/get-started/installation/android-sdk.md)
* Product: **xamarin**
* GitHub Login: @mgmclemore
* Microsoft Alias: **mamcle**

**Comment by mgmclemore** [comment]
Hi @JNickVA1, Visual Studio Tools for Xamarin is now automatically installed when you select the **Mobile development with .NET** workload during Visual Studio installation. This clarification will be added to the Requirements section. Thank you for the feedback!

**Comment by JNickVA1** [comment]
Thank you for the quick response.

**Comment by JNickVA1** [comment]
I had been hoping that my failure to locate and install the Visual Studio Tools for Xamarin was the reason for the error I keep getting when trying to create the "Hello, Android" quickstart application. I'm on my third attempt at it and I will add comments and questions as I go along following (again) the instructions for setup and application creation.

**Comment by mgmclemore** [comment]
OK, your feedback will be appreciated -- reopening.

**Comment by JNickVA1** [comment]
I've made it through this step, Android SDK Setup. without any further questions. or comments or issues.

**Comment by mgmclemore** [comment]
Thanks!
