### ISSUE TITLE
Binding to resource files stored on the device

### ISSUE THREAD

**Issue by jamesplmr1** [MicrosoftDocs/xamarin-docs#647]
I would like to store files in the applications resource folder and then using data binding retrieve the files. it is for a recipe app and i'd like to store videos locally on the phone but only draw the correct one for each object. how would I do this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 893106ba-4179-f54b-07df-139ea24b72dd
* Version Independent ID: 1553363e-fef4-9049-57b5-1f6311529041
* Content: [Binding video sources to the player - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/custom-renderer/video-player/source-bindings)
* Content Source: [docs/xamarin-forms/app-fundamentals/custom-renderer/video-player/source-bindings.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/app-fundamentals/custom-renderer/video-player/source-bindings.md)
* Product: **xamarin**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @jamesplmr1 

See [Loading application resource videos](https://docs.microsoft.com/xamarin/xamarin-forms/app-fundamentals/custom-renderer/video-player/loading-resources).

**Comment by jamesplmr1** [comment]
thank you david,

I already have that in place and it works for a single video, however when I put

<On Platform="Android" Value="Binding VideoURL" />

Instead of

<On Platform="Android" Value="AndroidApiVideo.mp4" />

it throws an exception. 

how could you use the On Platform statement with data binding?
