### ISSUE TITLE
Infinite list scrolling

### ISSUE THREAD

**Issue by RobDaPraia** [MicrosoftDocs/xamarin-docs#648]
Can you also use FlexLayout to create an infinite list of pictures, for example each time after showing 20 pictures, load the next 20 pictures, and show all a scrollable list using FlexLayout?

Would be nice if possible to see an example

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b954b795-b38e-61ff-3ba1-26a0623b97e6
* Version Independent ID: 65795b50-24d3-1997-038e-ffdb609eb20b
* Content: [The Xamarin.Forms FlexLayout - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/layouts/flex-layout)
* Content Source: [docs/xamarin-forms/user-interface/layouts/flex-layout.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/layouts/flex-layout.md)
* Product: **xamarin**
* GitHub Login: @charlespetzold
* Microsoft Alias: **chape**

**Comment by davidbritch** [comment]
Hi @RobDaPraia 

`FlexLayout` doesn't support that behaviour out of the box. However, it is possible. You have to implement incremental loading. See https://jmillerdev.net/incremental-listview-control-and-plugin-for-xamarin-forms/ for an example of doing this with a `ListView`.

**Comment by RobDaPraia** [comment]
HI David, 

thanks for the fast response
