### ISSUE TITLE
Link issue?

### ISSUE THREAD

**Issue by jrgsc** [MicrosoftDocs/xamarin-docs#649]
The link that says "Image Sizes and Filenames" just links back to the same page?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8546adbb-ebc5-6275-82ac-3f52842cb2d4
* Version Independent ID: 1b5c925c-74b5-5450-65b4-a08cc342d06a
* Content: [Displaying an Image in Xamarin.iOS - Xamarin](https://docs.microsoft.com/en-us/xamarin/ios/app-fundamentals/images-icons/displaying-an-image?tabs=vsmac)
* Content Source: [docs/ios/app-fundamentals/images-icons/displaying-an-image.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/ios/app-fundamentals/images-icons/displaying-an-image.md)
* Product: **xamarin**
* GitHub Login: @bradumbaugh
* Microsoft Alias: **brumbaug**

**Comment by bradumbaugh** [comment]
Thanks for calling this out, @jrgsc. I removed those links (for both VSMac and VS2017). Also updated a link in the 'Related links' section. These changes should be published soon. Appreciate the help!
