### ISSUE TITLE
Cant register for Xamarin Live Player beta

### ISSUE THREAD

**Issue by LostJ3ster** [MicrosoftDocs/xamarin-docs#651]
Everytime I try to register, the following message appears:
"Something went wrong, please contact the application owner: {"code"=&gt;"ITC.apps.tf.max.app.testers", "description"=&gt;"Failed to create tester."}"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 79320e9a-8b52-1c24-0a5b-a7ef6a32b519
* Version Independent ID: 88548723-6f1b-50c1-163c-a9e151b024e8
* Content: [Xamarin Live Player Setup - Xamarin](https://docs.microsoft.com/en-us/xamarin/tools/live-player/install?tabs=ios%2Cmacos)
* Content Source: [docs/tools/live-player/install.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/tools/live-player/install.md)
* Product: **xamarin**
* GitHub Login: @topgenorth
* Microsoft Alias: **toopge**

**Comment by LostJ3ster** [comment]
Tested again, works now!

**Comment by JasonM72** [comment]
I am still getting this message.
Something went wrong, please contact the application owner: {"code"=>"ITC.apps.tf.max.app.testers", "description"=>"Failed to create tester."} 
I have tested three different email addresses each time on Firefox, edge , ie and chrome and this is all I keep getting.
