### ISSUE TITLE
Screen shot of Android in Listview Functionality section seems broken? 

### ISSUE THREAD

**Issue by ChrisAllisonMalta** [MicrosoftDocs/xamarin-docs#653]
It does not show more or delete as Windows or iOS do

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3218187d-58a5-a214-4a23-bd2093e771b7
* Version Independent ID: 7a506e7e-e8c9-2bc4-148b-34529ce3afad
* Content: [Xamarin.Forms ListView - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/listview/)
* Content Source: [docs/xamarin-forms/user-interface/listview/index.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/listview/index.md)
* Product: **xamarin**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @ChrisAllisonMalta 

It shows more and delete buttons up in the toolbar.
