### ISSUE TITLE
Typos discrepancies

### ISSUE THREAD

**Issue by tyobrien98** [MicrosoftDocs/xamarin-docs#655]
"Note that the [Register("CodeBasedViewContoller")] [DOES NOT MATCH] the value that you specified for the NSPrincipalClass above." There is a missing 'R' in 'Controller'.  Always be careful when copying code.  Also another discrepancy is that in the tutorial they use the key 'NSPrincipalClass' when that seems to be wrong.  I believe that it is supposed to be 'NSExtensionPrincipalClass'.  You can even see this being used in the second screenshot (https://docs.microsoft.com/en-us/xamarin/ios/platform/extensions-images/registerandprincipalclass.png). Maybe this is just a version discrepancy.  Still with fixing these issues in my project, I am getting either the "Unable to load" popping up or nothing at all.  Doing it with the storyboard would work sometimes, but not every time.  I still don't know what to do.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8d278733-2d2b-1f5e-e18c-4dbf7536b4ac
* Version Independent ID: 366ce08a-c2b6-5b85-4326-7e74243b272d
* Content: [iOS Extensions in Xamarin.iOS - Xamarin](https://docs.microsoft.com/en-us/xamarin/ios/platform/extensions)
* Content Source: [docs/ios/platform/extensions.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/ios/platform/extensions.md)
* Product: **xamarin**
* GitHub Login: @bradumbaugh
* Microsoft Alias: **brumbaug**

**Comment by bradumbaugh** [comment]
Hi @tyobrien98, thanks for calling these things out! A couple of changes are working their way through the publishing pipeline:

- I've updated the misspelled controller name in a couple of places in the doc
- I changed `NSPrincipalClass` to `NSExtensionPrincipalClass` throughout the doc

Also, I've made a note in our internal backlog that we need to review and update this document as necessary.

If you believe you're encountering a bug, please file it on [Developer Community](https://developercommunity.visualstudio.com/spaces/8/index.html). 

Thanks again for your help!
Brad
