### ISSUE TITLE
Android screenshots are out of date and Windows Phone screenshots need to be removed/replaced w/UWP

### ISSUE THREAD

**Issue by JeroMiya** [MicrosoftDocs/xamarin-docs#657]
The latest control templates and stylings of stock android 8/9 look very different from the screenshots here - it might be time to update them (note: I'm not sure if the iOS screenshots are similarly out of date). Also the Windows Phone screenshots need to be removed and preferably replaced with UWP versions.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7ad16e14-5abd-7115-a64a-69db1178d58a
* Version Independent ID: 1602a6ea-3968-006b-9d63-63c25051b5b4
* Content: [Xamarin.Forms TableView - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/tableview)
* Content Source: [docs/xamarin-forms/user-interface/tableview.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/tableview.md)
* Product: **xamarin**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @JeroMiya 

Agreed. The screenshots will gradually be updated, but it's a big task.
