### ISSUE TITLE
The "Writing to the Debug Log" section should not only recommend using "Android.Util.Log class"

### ISSUE THREAD

**Issue by knocte** [MicrosoftDocs/xamarin-docs#66]
The "Writing to the Debug Log" section should not only recommend using "Android.Util.Log class", because in a cross-platform scenario such as Xamarin.Forms, you don't want to (or cannot, even) link to an Android type from your XamarinForms library (as it's a common-UI-logic library that runs in all targeted platforms, e.g. in iOS too).

The best way to improve this section, in my opinion, is also note that calls to `Console.WriteLine` do end up in logcat in a special way. For example `Console.WriteLine("foo bar baz");` ends up in the logcat this way: `03-22 12:46:03.178 32174 32174 I mono-stdout: foo bar baz`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 09e1d8d5-3255-fb48-e3ed-1878671c1035
* Version Independent ID: 134e021a-e314-b47f-e92e-94671c57c678
* Content: [Android Debug Log - Xamarin](https://docs.microsoft.com/en-us/xamarin/android/deploy-test/debugging/android-debug-log?tabs=vsmac#feedback)
* Content Source: [docs/android/deploy-test/debugging/android-debug-log.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/android/deploy-test/debugging/android-debug-log.md)
* Service: **unspecified**
* GitHub Login: @mgmclemore
* Microsoft Alias: **mamcle**

**Comment by mgmclemore** [comment]
@knocte, thank you for your feedback!  This topic is intended for Xamarin.Android rather than Xamarin Forms. However, you have an excellent suggestion to also mention the use of  `Console.WriteLine` as you describe -- we'll add that soon.

**Comment by knocte** [comment]
> This topic is intended for Xamarin.Android rather than Xamarin Forms

But ultimately any Xamarin.Forms user is a Xamarin.Android user (except in the rare case you don't deploy in Android), and there's no Logs documentation page for Xamarin.Forms ;-)

**Comment by mgmclemore** [comment]
Hi @knocte, *excellent* point!  I've updated the doc with your suggestions above; the changes will be published soon. Thanks again!
