### ISSUE TITLE
New Device and Edit Device Sections

### ISSUE THREAD

**Issue by JNickVA1** [MicrosoftDocs/xamarin-docs#660]
The text and images need to be updated to reflect what is available in the current VS2017 15.8.0, Preview 5

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a7a62dcf-aba5-fd75-f6dd-187b03dade95
* Version Independent ID: 4d403c76-8620-c803-8f84-ed0675f401ce
* Content: [Managing Virtual Devices with the Android Device Manager - Xamarin](https://docs.microsoft.com/en-us/xamarin/android/get-started/installation/android-emulator/device-manager?tabs=vswin)
* Content Source: [docs/android/get-started/installation/android-emulator/device-manager.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/android/get-started/installation/android-emulator/device-manager.md)
* Product: **xamarin**
* GitHub Login: @mgmclemore
* Microsoft Alias: **mamcle**

**Comment by mgmclemore** [comment]
Hello @JNickVA1, thank you for your feedback! I've added a task to our backlog to update this topic accordingly.
