### ISSUE TITLE
Walkthrough breaking mistake noticed

### ISSUE THREAD

**Issue by tomShoutTheSecond** [MicrosoftDocs/xamarin-docs#662]
All through the walkthrough you mention TitlesFragment, but in the activity_main.axml code you have the line android:name="FragmentSample.TitleFragment" which needs to be changed to android:name="FragmentSample.TitlesFragment" for the walkthrough to work (there is a missing s in your code). Changing this solves the issue.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4bc28ea1-445a-7229-ab8d-6d6159fe9bfd
* Version Independent ID: 97b9c884-ff5c-e78f-415c-decfb270ea53
* Content: [Xamarin.Android Fragments Walkthrough - Part 1 - Xamarin](https://docs.microsoft.com/en-us/xamarin/android/platform/fragments/implementing-with-fragments/walkthrough?tabs=vswin)
* Content Source: [docs/android/platform/fragments/implementing-with-fragments/walkthrough.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/android/platform/fragments/implementing-with-fragments/walkthrough.md)
* Product: **xamarin**
* GitHub Login: @mgmclemore
* Microsoft Alias: **mamcle**

**Comment by mgmclemore** [comment]
Hi @tomShoutTheSecond, thank you for your feedback! I've added a task to our backlog to update this topic accordingly.
