### ISSUE TITLE
Dependency Resolution sample: Problem with IComponentContext in ios previewer

### ISSUE THREAD

**Issue by lnaie** [MicrosoftDocs/xamarin-docs#663]
Hi,
This example works fine at runtime, but at design time it breaks complaining about Autofac.
Any advice?

<img width="517" alt="screen shot 2018-08-10 at 17 47 03" src="https://user-images.githubusercontent.com/1276077/44045286-57dd2e36-9f28-11e8-8931-d645f501659b.png">

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4ebfa3fe-4312-3b5f-83f0-a2a34088b565
* Version Independent ID: ebc6d0a4-f26a-f836-f4d5-fd2c8248c00a
* Content: [Dependency resolution in Xamarin.Forms - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/internals/dependency-resolution)
* Content Source: [docs/xamarin-forms/internals/dependency-resolution.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/internals/dependency-resolution.md)
* Product: **xamarin**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @lnaie 

The Previewer doesn't tend to work with the different DI containers. Making it do so involves adding support for each DI container to the Previewer. You should open an issue in the [Xamarin.Forms](https://github.com/xamarin/Xamarin.Forms/) repository if that's something you'd like to see happen.

**Comment by lnaie** [comment]
ok. done.

thanks!

**Comment by jamesmontemagno** [comment]
@davidbritch can we added troubleshooting to previewer docs for this? and how to get around it with ensuring there is a constructor with no params
