### ISSUE TITLE
Default Android Emulator can now run with Hyper-V (plus VS Emulator looks discontinued)

### ISSUE THREAD

**Issue by jamesbluecrow** [MicrosoftDocs/xamarin-docs#664]
Those links are not useful neither necessary anymore, now you can have docker with hyper-V activated and run the Android emulators at the same time https://stackoverflow.com/questions/31550628/visual-studio-emulator-for-android-install-gapps-google-play-services/51831784#51831784

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c5b55faf-1a5a-e7a4-3a37-f5f3c86d9b01
* Version Independent ID: c1381c49-aa90-38b5-5cec-f58fe0a8736a
* Content: [How do I install Google Play Services in an emulator? - Xamarin](https://docs.microsoft.com/en-us/xamarin/android/troubleshooting/questions/install-gps)
* Content Source: [docs/android/troubleshooting/questions/install-gps.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/android/troubleshooting/questions/install-gps.md)
* Product: **xamarin**
* GitHub Login: @mgmclemore
* Microsoft Alias: **mamcle**

**Comment by mgmclemore** [comment]
Hi @jamesbluecrow, thank you for your feedback! I've added a task to our backlog to update this out-of-date topic.
