### ISSUE TITLE
Getting Context inside ButtonOnClick

### ISSUE THREAD

**Issue by Caltor** [MicrosoftDocs/xamarin-docs#665]
Shouldn't 
```
    NotificationManager notificationManager =
        (NotificationManager)GetSystemService(Context.NotificationService);
    notificationManager.Notify(ButtonClickNotificationId, builder.Build());

```
be
```
    NotificationManager notificationManager =
        (NotificationManager)GetSystemService(MainActivity.NotificationService);
    notificationManager.Notify(ButtonClickNotificationId, builder.Build());

```
??? Note the change from Context to MainActivity.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bfbead94-9441-acc3-8559-6d09713f5274
* Version Independent ID: 15fb3cb2-7408-ba72-4795-c7889caeb8da
* Content: [Walkthrough - Using Local Notifications in Xamarin.Android - Xamarin](https://docs.microsoft.com/en-us/xamarin/android/app-fundamentals/notifications/local-notifications-walkthrough)
* Content Source: [docs/android/app-fundamentals/notifications/local-notifications-walkthrough.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/android/app-fundamentals/notifications/local-notifications-walkthrough.md)
* Product: **xamarin**
* GitHub Login: @mgmclemore
* Microsoft Alias: **mamcle**

**Comment by mgmclemore** [comment]
Hi @Caltor, thank you for the feedback!  We have an updated Local Notifications topic in the pipeline that includes this correction (to be published soon).

**Comment by stuatquipp** [comment]
I am getting:
Error	CS0176	Member 'Class.FromType(Type)' cannot be accessed with an instance reference; qualify it with a type name instead.

I just don't know what to put instead.  Not familiar with "FromType"

**Comment by stuatquipp** [comment]
nevermind.   I added java.lang in front of Class.  Seems to be happy now.
