### ISSUE TITLE
Code for Implementing a Date Picker is wrong.

### ISSUE THREAD

**Issue by wutever0** [MicrosoftDocs/xamarin-docs#667]
Code for Implementing a Date Picker is wrong.
It says that it is implemented by instantiating a new UIDatePickerView then goes and uses a UIPickerView??

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 90056eb2-9e03-92ef-7781-d3b4a62ce7fb
* Version Independent ID: 053965cd-d524-65c4-a7bd-3f7673f6495c
* Content: [Picker Control in Xamarin.iOS - Xamarin](https://docs.microsoft.com/en-us/xamarin/ios/user-interface/controls/picker#date-picker)
* Content Source: [docs/ios/user-interface/controls/picker.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/ios/user-interface/controls/picker.md)
* Product: **xamarin**
* GitHub Login: @bradumbaugh
* Microsoft Alias: **brumbaug**

**Comment by bradumbaugh** [comment]
Hi @wutever0, you're right – it's `UIDatePicker` for dates, not `UIDatePickerView`. I've made a number of changes to this doc that are now working their way through the publishing system and should be published soon. Also be sure to download the sample code in the related links section! Thanks again.
