### ISSUE TITLE
No such thing as UIDatePickerView

### ISSUE THREAD

**Issue by wutever0** [MicrosoftDocs/xamarin-docs#668]
There is only UIDatePicker

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 90056eb2-9e03-92ef-7781-d3b4a62ce7fb
* Version Independent ID: 053965cd-d524-65c4-a7bd-3f7673f6495c
* Content: [Picker Control in Xamarin.iOS - Xamarin](https://docs.microsoft.com/en-us/xamarin/ios/user-interface/controls/picker#date-picker)
* Content Source: [docs/ios/user-interface/controls/picker.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/ios/user-interface/controls/picker.md)
* Product: **xamarin**
* GitHub Login: @bradumbaugh
* Microsoft Alias: **brumbaug**

**Comment by bradumbaugh** [comment]
Closing this - left a comment on https://github.com/MicrosoftDocs/xamarin-docs/issues/667. Thanks for your help!
