### ISSUE TITLE
Android Emulator package 27.2.9 is not available from Android SDKs and Tools (only 27.2.7 is available)

### ISSUE THREAD

**Issue by cbs-cbt** [MicrosoftDocs/xamarin-docs#669]
Hello,
I want to install Hyper-V Emulator, in point "4. Install the Android Emulator package 27.2.9 or later", the Android SDKs and Tools does not purpose me to install Android Emulator 27.2.9, the last version purposed is 27.2.7
Can you please point me in the right direction to solve that problem?
Thank you in advance
Greetings
J-D Gasser

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4e37d642-2051-8d70-9968-dfb484122a6a
* Version Independent ID: 178ea80c-2b99-0c44-eeb6-9db319439b33
* Content: [Hardware Acceleration for Emulator Performance - Xamarin](https://docs.microsoft.com/en-us/xamarin/android/get-started/installation/android-emulator/hardware-acceleration?tabs=vswin)
* Content Source: [docs/android/get-started/installation/android-emulator/hardware-acceleration.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/android/get-started/installation/android-emulator/hardware-acceleration.md)
* Product: **xamarin**
* GitHub Login: @mgmclemore
* Microsoft Alias: **mamcle**

**Comment by Timothy-Liu** [comment]
Same here.

**Comment by mgmclemore** [comment]
Apologies for the confusion, it looks like 27.2.7 is indeed the correct version rather than 27.2.9. We'll get this updated ASAP. Thanks again!

**Comment by mgmclemore** [comment]
Fixed, changes to be published soon.
