### ISSUE TITLE
how to use this on xamarin forms

### ISSUE THREAD

**Issue by shalinasanga** [MicrosoftDocs/xamarin-docs#672]
can i use this in xamarin forms ios project ?
i just create class with this extension but notifications are not hitting "DidReceiveNotificationRequest", do i need to initialize my class or something ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4f2ee7c5-fd5e-3c28-31d8-e01820850feb
* Version Independent ID: 5b886a57-3d74-57a7-7726-a740f1efb328
* Content: [Enhanced User Notifications in Xamarin.iOS - Xamarin](https://docs.microsoft.com/en-us/xamarin/ios/platform/user-notifications/enhanced-user-notifications?tabs=vswin#working-with-service-extensions)
* Content Source: [docs/ios/platform/user-notifications/enhanced-user-notifications.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/ios/platform/user-notifications/enhanced-user-notifications.md)
* Product: **xamarin**
* GitHub Login: @bradumbaugh
* Microsoft Alias: **brumbaug**

**Comment by shalinasanga** [comment]
talking about how to use "UNNotificationServiceExtension ", 
"UNUserNotificationCenterDelegate" working fine in xamarin forms

**Comment by conceptdev** [comment]
An [iOS extension](https://docs.microsoft.com/en-us/xamarin/ios/platform/extensions) is a separate project type, you cannot implement it inside your Xamarin.Forms app. If you follow the [instructions](https://docs.microsoft.com/en-us/xamarin/ios/platform/user-notifications/enhanced-user-notifications?tabs=vsmac#implementing-a-service-extension) to add an extension project _in addition_ to your Xamarin.Forms iOS project, ensure the bundle identifiers are set correctly and that the [`mutable-content`](https://docs.microsoft.com/en-us/xamarin/ios/platform/user-notifications/enhanced-user-notifications?tabs=vsmac#triggering-a-service-extension) key is set.

If you believe you have found a bug or issue with Xamarin.iOS, please use the [report a problem](https://docs.microsoft.com/en-us/visualstudio/mac/report-a-problem) feature in Visual Studio.

**Comment by Muthutc** [comment]
Hi @conceptdev  Please tell me How do i enable/disable sound and Vibrate in Xamarin forms iOS.
