### ISSUE TITLE
Surface Book 2

### ISSUE THREAD

**Issue by brinawebb** [MicrosoftDocs/xamarin-docs#674]
This doesn't work for me at all. My emulator is still VERY slow. I have the latest Surface Book 2 that I have confirmed supports virtualization. I run this at the commandline to verify that the service is started:
sc query intelhaxm

After I install Windows Hypervisor Platform it says the service is stopped and I also get the performance warning when starting the emulator that there's no acceleration. 

I'm using emulator version 27.3.9 and have tried both with and without the ini file (ini file instructions in a separate doc).

Also, the docs here are incorrect or missing information. In step 4 I don't see a dialog box as the emulator starts with any method that I try.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4e37d642-2051-8d70-9968-dfb484122a6a
* Version Independent ID: 178ea80c-2b99-0c44-eeb6-9db319439b33
* Content: [Hardware Acceleration for Emulator Performance - Xamarin](https://docs.microsoft.com/en-us/xamarin/android/get-started/installation/android-emulator/hardware-acceleration?tabs=vswin#hyper-v-overview)
* Content Source: [docs/android/get-started/installation/android-emulator/hardware-acceleration.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/android/get-started/installation/android-emulator/hardware-acceleration.md)
* Product: **xamarin**
* GitHub Login: @mgmclemore
* Microsoft Alias: **mamcle**

**Comment by mgmclemore** [comment]
Hi @brinawebb, thank you for the feedback! It sounds like you are trying to enable both Hyper-V and HAXM -- actually, you can only use one or the other (we'll add a note to the the doc to make this clearer).  Also, yes, the emulator progress dialog box is no longer displayed in the latest emulator version (we're in the process of updating the doc to reflect this change).

**Comment by mgmclemore** [comment]
Topic has been updated.
