### ISSUE TITLE
Project contains resources that were not compiled successfully

### ISSUE THREAD

**Issue by JNickVA1** [MicrosoftDocs/xamarin-docs#675]
I have used both the VS 2017 15.8 Preview, version 5 and now the new VS 2017 15.8 Release and on both I get the error when I build a new Android project that states "This project contains resources that were not compiled successfully. Rendering might be affected" I've verified that all resources are set to Build as AndroidResource. Any idea what is causing this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 660b0f7c-9941-2db3-63bf-fc8a97765b1e
* Version Independent ID: 5aa1e6f6-534a-05b9-c44a-1f62b24c201a
* Content: [Hello, Android: Quickstart - Xamarin](https://docs.microsoft.com/en-us/xamarin/android/get-started/hello-android/hello-android-quickstart?tabs=vswin)
* Content Source: [docs/android/get-started/hello-android/hello-android-quickstart.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/android/get-started/hello-android/hello-android-quickstart.md)
* Product: **xamarin**
* GitHub Login: @mgmclemore
* Microsoft Alias: **mamcle**

**Comment by topgenorth** [comment]
I've had similar experiences with Xamarin.Android  where it seems to have issues compiling the Android Resource ID's for various things.  Somethings to try:

* Rebuild all
* Close Visual Studio, then manually delete the bin & obj directories for the project. Restart VS.
* Update NuGet packages

If this problem persists, then please raise an issue using the "Report Issue" feature in Visual Studio.

**Comment by Hutch07** [comment]
I have the same issue.

**Comment by son0nline** [comment]
I have the same issue.
Designer tab only black screen 
![u0YEEJP 1](https://user-images.githubusercontent.com/8395344/54869573-3f786500-4dcd-11e9-8383-07badff7aa54.png)

**Comment by marekpetak** [comment]
same issue here. blank page
