### ISSUE TITLE
Ambiguous Reference in MainActivity.cs in new project

### ISSUE THREAD

**Issue by JNickVA1** [MicrosoftDocs/xamarin-docs#676]
I create a new Blank App in VS 2017 15.8.0 and I immediately get an ambiguous reference in the OnCreate event handler in the MainActivity class. It seems that the Resource.Layout.activity_main constant is defined in two places. Any ideas?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 660b0f7c-9941-2db3-63bf-fc8a97765b1e
* Version Independent ID: 5aa1e6f6-534a-05b9-c44a-1f62b24c201a
* Content: [Hello, Android: Quickstart - Xamarin](https://docs.microsoft.com/en-us/xamarin/android/get-started/hello-android/hello-android-quickstart?tabs=vswin)
* Content Source: [docs/android/get-started/hello-android/hello-android-quickstart.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/android/get-started/hello-android/hello-android-quickstart.md)
* Product: **xamarin**
* GitHub Login: @mgmclemore
* Microsoft Alias: **mamcle**

**Comment by mgmclemore** [comment]
Hello @JNickVA1, from your description, this appears to be a problem with the product. However, our team can only answer feedback related to documentation. Please report the specifics about your issue at [Developer Community](https://developercommunity.visualstudio.com/spaces/8/index.html) (click **Report a problem**). Thank you!
