### ISSUE TITLE
Xamarin Forms requirements

### ISSUE THREAD

**Issue by sephius1999** [MicrosoftDocs/xamarin-docs#677]
I wanted to know what version(s) of Xamarin Forms is supported by Xamarin.Essentials.

I'm currently using Xamarin.Forms 2.3.4.270 and cannot chance an update to this version.

Please advise

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 78e6dee8-1182-bf1e-fd3a-e8d1aecc094a
* Version Independent ID: 81202c69-317a-f0fa-7324-5316f7c1ceb7
* Content: [Get Started with Xamarin.Essentials - Xamarin](https://docs.microsoft.com/en-us/xamarin/essentials/get-started?tabs=windows%2Candroid#feedback)
* Content Source: [docs/essentials/get-started.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/essentials/get-started.md)
* Product: **xamarin**
* GitHub Login: @jamesmontemagno
* Microsoft Alias: **jamont**

**Comment by jamesmontemagno** [comment]
Xamarin.Essentials works with any version of Xamarin or Xamarin.Forms. You may need to adjust some of your settings and ensure your support libraries when installing: https://montemagno.com/resolving-android-support-library-nuget-installation-issues/
