### ISSUE TITLE
Reduced performance

### ISSUE THREAD

**Issue by mfeingol** [MicrosoftDocs/xamarin-docs#678]
I'm seeing very slow performance from Hyper-V compared to HAXM. The docs note that some Intel and AMD-based processors will see reduced performance. Can you document which processors are affected, and why?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4e37d642-2051-8d70-9968-dfb484122a6a
* Version Independent ID: 178ea80c-2b99-0c44-eeb6-9db319439b33
* Content: [Hardware Acceleration for Emulator Performance - Xamarin](https://docs.microsoft.com/en-us/xamarin/android/get-started/installation/android-emulator/hardware-acceleration?tabs=vswin#known-issues)
* Content Source: [docs/android/get-started/installation/android-emulator/hardware-acceleration.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/android/get-started/installation/android-emulator/hardware-acceleration.md)
* Product: **xamarin**
* GitHub Login: @mgmclemore
* Microsoft Alias: **mamcle**

**Comment by mgmclemore** [comment]
Hi @mfeingol, thank you for the feedback!  Currently, there is no definitive list from Google as to which Intel or AMD-based processors exhibit reduced performance with their emulator. If we are able to locate such a list, we will certainly link to it from this topic. Meanwhile, [this topic](https://developer.android.com/studio/run/emulator-acceleration) may be able to help you understand why you are seeing slow performance.

**Comment by mungojam** [comment]
I see the same on my recent i7 CPU, which has all the pre-reqs. HAXM is fine but Hyper-V is painfully slow so I'm sticking with HAXM. The link you sent is presumably for issues that affect HAXM too.

I understand from a call just now that this issue might be fixed with a Windows update later in the year and that it is due to spectre/meltdown

**Comment by mfeingol** [comment]
By Windows update do you think they meant Redstone 5?

**Comment by mungojam** [comment]
Could be yeah, or maybe there is some spectre mop up update coming or something
