### ISSUE TITLE
Xamarin.Forms version supported

### ISSUE THREAD

**Issue by sephius1999** [MicrosoftDocs/xamarin-docs#679]
I'm current using Xamarin.Forms v2.3.4.270

Can I use this version of Xamarin.Essentials?

I cannot update the forms since we have production clients on certain on this version, so will this trigger an update of the forms if I install it?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c420b152-7303-918a-dbc8-8d1e539c64ec
* Version Independent ID: fe85e24f-c3fc-3763-b1db-6b360fb08067
* Content: [Xamarin.Essentials - Xamarin](https://docs.microsoft.com/en-us/xamarin/essentials/?context=xamarin/ios)
* Content Source: [docs/essentials/index.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/essentials/index.md)
* Product: **xamarin**
* GitHub Login: @jamesmontemagno
* Microsoft Alias: **jamont**

**Comment by bradumbaugh** [comment]
Hi @sephius1999 – looks like this question was answered over on another issue: https://github.com/MicrosoftDocs/xamarin-docs/issues/677.
