### ISSUE TITLE
xamarin forms compatibility

### ISSUE THREAD

**Issue by shalinasanga** [MicrosoftDocs/xamarin-docs#680]
Translation doing using this "https://docs.microsoft.com/en-us/xamarin/ios/app-fundamentals/localization/#getlocalizedstring-method", is this way comatible with xamarin forms ? Base.lproj and .String file

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 629ae54b-10fe-61ff-6a6e-cb54b5206079
* Version Independent ID: fcb311ea-1552-86e4-d648-5fe7832d863a
* Content: [Localization in Xamarin.iOS - Xamarin](https://docs.microsoft.com/en-us/xamarin/ios/app-fundamentals/localization/#getlocalizedstring-method)
* Content Source: [docs/ios/app-fundamentals/localization/index.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/ios/app-fundamentals/localization/index.md)
* Product: **xamarin**
* GitHub Login: @bradumbaugh
* Microsoft Alias: **brumbaug**

**Comment by bradumbaugh** [comment]
Hi @shalinasanga, while you can use platform-specific methods in custom renderers, for Xamarin.Forms it likely makes more sense to consider localization approaches discussed here: [cross-platform localization](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/localization/).  Hope this helps.
