### ISSUE TITLE
FirebaseInstanceIdService and OnTokenRefresh() are deprecated

### ISSUE THREAD

**Issue by kcprabase** [MicrosoftDocs/xamarin-docs#681]
On FCM documenation, I have found that we can use OnNewToken() of FirebaseMessagingService class to get token from now on. But I have tried it and OnNewToken is not hit when app is newly installed or anytime after that. This document still shows the deprecated method. Are there any updated documents. Do I need to make changes in AndroidManifest file as well? Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8d9bfb2a-2e5d-d505-337f-919251a85de3
* Version Independent ID: 695bff64-ae87-8c0f-5616-20b67893fdf0
* Content: [Remote Notifications with Firebase Cloud Messaging - Xamarin](https://docs.microsoft.com/en-us/xamarin/android/data-cloud/google-messaging/remote-notifications-with-fcm?tabs=vswin)
* Content Source: [docs/android/data-cloud/google-messaging/remote-notifications-with-fcm.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/android/data-cloud/google-messaging/remote-notifications-with-fcm.md)
* Product: **xamarin**
* GitHub Login: @mgmclemore
* Microsoft Alias: **mamcle**

**Comment by topgenorth** [comment]
Thanks for reporting this.  You are correct, in the latest Firebase Cloud Messaging APIs (17.1.0) `OnNewToken` in the `FirebaseInstanceId` was deprecated.  Apps should now use the `OnNewToken` method of the `FirebaseMessagingService` class.

The current release version of [Xamarin.Firebase.Messaging](https://www.nuget.org/packages/Xamarin.Firebase.Messaging/60.1142.1) is bound to the older APIs (11.4.2). There is a [preview release](https://www.nuget.org/packages/Xamarin.Firebase.Messaging/70.1710.0-preview2) which binds version 17.1.0 of the Firebase Cloud Messaging APIs.  

We will update this guide and published the new version when the Xamarin.Android bindings are promoted out of pre-release.

**Comment by maxserbia** [comment]
Any news on this?

**Comment by rodsjo** [comment]
@topgenorth I'm using the [preview package](https://www.nuget.org/packages/Xamarin.Firebase.Iid/70.1620.0-preview2). What is the C# Xamarin Android equivalent when it comes to getting the token? 

```java
FirebaseInstanceId.getInstance().getInstanceId().addOnSuccessListener( MyActivity.this,  new OnSuccessListener<InstanceIdResult>() {
     @Override
     public void onSuccess(InstanceIdResult instanceIdResult) {
           String newToken = instanceIdResult.getToken();
           Log.e("newToken", newToken);

     }
 });
```

https://firebase.google.com/docs/reference/android/com/google/firebase/iid/FirebaseInstanceId#getInstanceId()

**Comment by AntRemo** [comment]
@rodsjo I haven't used it but found this here

```
class TestService: FirebaseMessagingService
{
    public override void OnNewToken(string p0)
    {
        base.OnNewToken(p0);
    }
}
```

https://forums.xamarin.com/discussion/comment/343725/#Comment_343725

**Comment by rodsjo** [comment]
@antremo I know about that one. I was wondering how the new Xamarin implementation/binding is when it comes to getting the token through FirebaseInstanceId.Instance...

**Comment by kcprabase** [comment]
For now I am still using the deprecated version because I have not found a reliable source. I hope this document will be updated soon when the Xamarin.Android bindings are promoted out of pre-release.

**Comment by Laumania** [comment]
...and here we are in end of July 2019 and the documentation still uses a sample with the depricated FirebaseInstanceIdService.

I found this, because I have the same problem, it doesn't work and the sample tells me to use something that is now deprecated.

Any news on this?

**Comment by kyluke** [comment]
When is the documentation going to be updated? Your current documentation does not match up with the current version of the nuget and leads to broken implementations.

**Comment by Laumania** [comment]
@kyluke Yeah I see the same, it's really confusing.

@jamesmontemagno FYI - in relation to what I wrote to you about on twitter 2 weeks ago.

**Comment by jamesmontemagno** [comment]
@redth is there someone from the team that can look at the docs here?

**Comment by Redth** [comment]
@moljac can you have a look at this please?

**Comment by Laumania** [comment]
I'm following a long here too, as I need this too :(

**Comment by iBobb** [comment]
I spent a few hours on this but I finally got it to work for me. One of my issues was I added a <service> tag in the Manifest as instructed by Firebase docs.
So, considering you have implemented the FirebaseInstanceIdService and FirebaseMessagingService as per the old scenario like me, here's all I needed to do to change to the new stuff:
1. Removed all GCM/Firebase related entries from the Android Manifest. You still need the INTERNET permission of course but nothing about gcm/fcm or a InstanceIdService/MessagingService
2. Delete my InstanceIdListenerService and instead use that in the FirebaseMessagingService 
`        public override void OnNewToken(string newToken)
        {
            base.OnNewToken(newToken);
            Log.Info("MyFirebaseMessagingService", "Firebase Token: " + newToken);
            saveToken(newToken); // send to server or store somewhere
        }
`
3. I have NuGet packages Xamarin.Firebase.Messaging, Xamarin.GooglePlayServices.Base
4. There's no step 4

I'm using VS 2019 (16.2.3), Xamarin 16.2.0.95, Xamarin.Android SDK 9.4.1.0

**Comment by Laumania** [comment]
Very interesting @iBobb  - I will give that a try. Right now I have to release this update of my app without PUSH, as the old app is falling about (4 years since I updated it :P)

Anyway, are the two mentioned Nugetpacked the only ones you installed to support PUSH? And what version of these do you use?

**Comment by iBobb** [comment]
We were also using very old code but I started a new project to use the newest Xamarin templates, copying over code and now I am updating everything to latest in that project. Nuget package versions are Xamarin.Firebase.Messaging (71.1740.0) and Xamarin.GooglePlayServices.Base (71.1610.0)
We have other nuget packages but I'm pretty sure only the Messaging one and PlayServices are needed. We have Xamarin.Essentials also but I don't think it is related. Basically Firebase made it a lot easier to be implemented.
Forgot to mention, with the new version also the OnMessageReceived changed a bit, has a new argument of type RemoteMessage. You can read how they use this object but because of the server that sends notifications for me it is a bit different:
`
        public override void OnMessageReceived(RemoteMessage remoteMessage)
        {
            base.OnMessageReceived(remoteMessage);
            var message = remoteMessage.Data["message"];
            Log.Debug("MyFirebaseMessagingService", "From:    " + remoteMessage.From);
            Log.Debug("MyFirebaseMessagingService", "Message: " + message);
            sendNotification(defaultNotificationTitle, message); // i just use same title for everything
        }
`
I get the message from the Data dictionary and in the docs they usually take it like that:
`
remoteMessage.getNotification().getBody()
`

**Comment by jaspervanmegroot** [comment]
Do you have a example project?

**Comment by Laumania** [comment]
@iBobb Ok interesting, will give it a try at some point. However, I still think Microsoft should update the documentation, as it's not working at all if you follow that.

A side note, my code is not old eventhough my app it. It's a complete rewrite, which I do every 3-4 years for so :D

**Comment by iBobb** [comment]
I created an example project, I didn't test it because I have to generate a new google-services file for it to work but it compiles. It has code to send a push notification and handling the new token. Just follow the online guides to generate a google-services.json file with the package name matching the one you used and put it in the root of the Android project setting the build action to GoogleServicesJson and it should work: my profile and the repo is xamarin_firebaseapi

**Comment by VincentH-Net** [comment]
@Redth Here we are in June **2020**, the docs are still not updated and still can't find a reliable example of this:

> @topgenorth I'm using the [preview package](https://www.nuget.org/packages/Xamarin.Firebase.Iid/70.1620.0-preview2). What is the C# Xamarin Android equivalent when it comes to getting the token?
> 
> ```java
> FirebaseInstanceId.getInstance().getInstanceId().addOnSuccessListener( MyActivity.this,  new OnSuccessListener<InstanceIdResult>() {
>      @Override
>      public void onSuccess(InstanceIdResult instanceIdResult) {
>            String newToken = instanceIdResult.getToken();
>            Log.e("newToken", newToken);
> 
>      }
>  });
> ```
> 
> https://firebase.google.com/docs/reference/android/com/google/firebase/iid/FirebaseInstanceId#getInstanceId()

So I _can_ find examples on how to use `OnNewToken`, but I **can't** find a reliable example how to force a token refresh. This is the obsolete implementation:
```csharp
string ForceTokenRefresh()
{
    FirebaseInstanceId.Instance.DeleteInstanceId(); // TODO: obsolete, fix 
    return FirebaseInstanceId.Instance.Token;
}
```

**Comment by pedroreglero** [comment]
> @Redth Here we are in June **2020**, the docs are still not updated and still can't find a reliable example of this:
> 
> > @topgenorth I'm using the [preview package](https://www.nuget.org/packages/Xamarin.Firebase.Iid/70.1620.0-preview2). What is the C# Xamarin Android equivalent when it comes to getting the token?
> > ```java
> > FirebaseInstanceId.getInstance().getInstanceId().addOnSuccessListener( MyActivity.this,  new OnSuccessListener<InstanceIdResult>() {
> >      @Override
> >      public void onSuccess(InstanceIdResult instanceIdResult) {
> >            String newToken = instanceIdResult.getToken();
> >            Log.e("newToken", newToken);
> > 
> >      }
> >  });
> > ```
> > 
> > 
> > https://firebase.google.com/docs/reference/android/com/google/firebase/iid/FirebaseInstanceId#getInstanceId()
> 
> So I _can_ find examples on how to use `OnNewToken`, but I **can't** find a reliable example how to force a token refresh. This is the obsolete implementation:
> 
> ```cs
> string ForceTokenRefresh()
> {
>     FirebaseInstanceId.Instance.DeleteInstanceId(); // TODO: obsolete, fix 
>     return FirebaseInstanceId.Instance.Token;
> }
> ```

Yes, Microsoft needs to change the documentation.

**Comment by VincentH-Net** [comment]
@davidbritch could you reopen this issue?
It is two years later and I still have all these ugly `obsolete` warnings because this MS documentation is obsolete.

As said above, most info I can find but missing info is:
> I can find examples on how to use OnNewToken, but I can't find a reliable example how to force a token refresh. This is the obsolete implementation:
```csharp 
string ForceTokenRefresh()
{
    FirebaseInstanceId.Instance.DeleteInstanceId(); // TODO: obsolete, fix 
    return FirebaseInstanceId.Instance.Token;
}
```

Just a reply here for that piece would also help others. Thanks!

**Comment by Cacata** [comment]
@iBobb you are my savior! Just adding something to receive the message from Firebase Server:

`public override void OnMessageReceived(RemoteMessage remoteMessage)
        {
            base.OnMessageReceived(remoteMessage); 
            var message = "From: " + "\n" + remoteMessage.From + "\n" + "Message: " + "\n" + remoteMessage.GetNotification().Body;
            new NotificationHelper().CreateNotification(remoteMessage.GetNotification().Title, message); //My own way to shoow the notification!
        }` 

Thanks a lot bro!

**Comment by devology-rob** [comment]
I've also found that suggestions of using FirebaseInstanceId.Instance.GetInstanceId(); are deprecated.  

The closest pattern I've found to this is the code below...

```
var firebaseListener = new FirebaseListener();
FirebaseInstallations.Instance.GetToken(false).AddOnCompleteListener(firebaseListener);
var token = await firebaseListener.GetToken();
Log.Debug(TAG, $"FCM push token:'{token}'");

...

private class FirebaseListener : Java.Lang.Object, Android.Gms.Tasks.IOnCompleteListener
{
    private TaskCompletionSource<String> tcs = new TaskCompletionSource<String>(TaskCreationOptions.RunContinuationsAsynchronously);

    public Task<String>GetToken()
    {
        return tcs.Task;
    }

    public void Disposed()
    {
    }

    public void DisposeUnlessReferenced()
    {
    }

    public void Finalized()
    {
    }

    public void OnComplete(Android.Gms.Tasks.Task task)
    {
        if (task.IsSuccessful)
        {
            string theToken = task.Result.ToString();
            tcs.SetResult(theToken);
        } else
        {
            tcs.SetResult(null);
        }
    }

    public void SetJniIdentityHashCode(int value)
    {
    }

    public void SetJniManagedPeerState(JniManagedPeerStates value)
    {
    }

    public void SetPeerReference(JniObjectReference reference)
    {
    }
}```

But the string returned is not the push token but some sort of install ID

> InstallationTokenResult{token=eyJhbGciOiJFUzI1NiIsInR5c<redacted>DfT5WlBa-gn8yOzhPbKdNmEczEddw, tokenExpirationTimestamp=604800, tokenCreationTimestamp=1616180234}

Any other routes seem to be marked deprecated.

I am however having success by declaring a FirebaseMessagingService that's listening for     

```
[IntentFilter(new[] { "com.google.firebase.MESSAGING_EVENT" })]
[IntentFilter(new[] { "com.google.firebase.INSTANCE_ID_EVENT" })]
```

But the OnNewToken method will only be invoked under certain circumstances and although I persist it immediately I'm concerned that if the app crashes for whatever reason the token will not be persisted.

This is why I was looking for mechanisms to query it at any time.

**Comment by WilkoSki** [comment]
@Redth @moljac @jamesmontemagno 2 years guys and no real solution and no updated documentation or sample code.

Being reliant upon overriding OnNewToken from Firebase.Messaging.FirebaseMessagingService is poor.  It's only fired once per app install.  If the push token cannot be sent to a backend server (numerous legitimate reasons) then there is no mechanism to obtain the current token next time the app is started and retry.  Leaves the user in a poor state with the only option to re-install.

**Comment by grounch** [comment]
@Redth @jamesmontemagno  Hi guys still no proper fix on this issue?
Trying to get the token refresh work with the suggestions above but it doesn't, at the end it's all hacky workarounds and a clean resolution would be really appreciated to be able to use the plugin properly.

**Comment by sandeepani** [comment]
I found this sample on the official Xamarin's  GooglePlayServicesComponents Repository. It has an implementation for OnNewToken() method. [https://github.com/xamarin/GooglePlayServicesComponents/tree/main/samples/com.google.firebase/firebase-messaging](url)

**Comment by ryanlpoconnell** [comment]
For anyone interested, when using Xamarin.Firebase.Messaging (V 123.1.1 tested) "FirebaseMessagingService.**OnNewToken**" is firing on install and is NOT deprecated.

Firebase documentation outlines how to retrieve and monitor token changes here: https://firebase.google.com/docs/cloud-messaging/android/client#retrieve-the-current-registration-token

To retrieve the current token make use of 
`FirebaseMessaging.Instance.GetToken()`

To monitor changed token make use by overriding "FirebaseMessagingService.**OnNewToken**"
`public override void OnNewToken(string token)`

**Workaround:** However if you are still finding OnNewToken not firing for some reason, you could use GetToken periodically and compare it to the last token you stored.
