### ISSUE TITLE
iOS project file add

### ISSUE THREAD

**Issue by shalinasanga** [MicrosoftDocs/xamarin-docs#684]
How to add ".Iproj" and ".strings" files using visual studio for mac ? can not see such options.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 629ae54b-10fe-61ff-6a6e-cb54b5206079
* Version Independent ID: fcb311ea-1552-86e4-d648-5fe7832d863a
* Content: [Localization in Xamarin.iOS - Xamarin](https://docs.microsoft.com/en-us/xamarin/ios/app-fundamentals/localization/#getlocalizedstring-method)
* Content Source: [docs/ios/app-fundamentals/localization/index.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/ios/app-fundamentals/localization/index.md)
* Product: **xamarin**
* GitHub Login: @bradumbaugh
* Microsoft Alias: **brumbaug**

**Comment by bradumbaugh** [comment]
Hi @shalinasanga – I responded to you over on: https://github.com/MicrosoftDocs/xamarin-docs/issues/685. I'll add a todo item to update the doc with instructions on how to do this. Thanks!
