### ISSUE TITLE
iOS project folder adding

### ISSUE THREAD

**Issue by shalinasanga** [MicrosoftDocs/xamarin-docs#685]
how to add .Iproj and .strings file using VS for mac ? can not see such options.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: af66394d-81c5-0c2e-1682-a2bb7eeb3c3e
* Version Independent ID: 27542a45-2f25-4042-cf48-b9517025635c
* Content: [String and Image Localization - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/localization/text?tabs=vswin)
* Content Source: [docs/xamarin-forms/app-fundamentals/localization/text.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/app-fundamentals/localization/text.md)
* Product: **xamarin**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by bradumbaugh** [comment]
Hi @shalinasanga, there's no IDE support in Visual Studio for Mac specifically for adding .lproj or .strings files. Instead, for the .lproj folders, right-click on the project in the **Solution Pad** and choose **Add > New Folder** and add each folder manually. For .strings files, again right-click on the project in the **Solution Pad** and choose **Add > New File... > Misc > Empty Text File**.

Hope this helps!

**Comment by shalinasanga** [comment]
I did that, change folder name to ".Iproj" and add empty text file and change it name to(extension) ".strings" , then project is not building
