### ISSUE TITLE
Please add a bindable Source property

### ISSUE THREAD

**Issue by tlhintoq** [MicrosoftDocs/xamarin-docs#686]
`FlexLayout`
Nifty control but I'm stunned that a brand new control in 2018 is not bindable.  It would be terrific if I could bind an `ObservableCollection<image>` or whatever to it, provide a `DataTemplate` and get a good live dynamic UI out of this.  

Everyone keeps **begging** for a horizontal `ListView` or a bindable `WrapPanel`.  If this control were bindable it could be a replacement for for both and make _so many_ developers happy.

**Comment by davidbritch** [comment]
Hi @tlhintoq 

`FlexLayout` is a layout, rather than a view. Just as you don't bind a `StackLayout` or `Grid` to a collection, you can't bind a `FlexLayout` to a collection. However, it can be easily extended to support this if you wish to do so.

It sounds like you are after a `CollectionView`. See the [spec](https://github.com/xamarin/Xamarin.Forms/issues/3172) to keep an eye on its progress.

**Comment by tlhintoq** [comment]
@davidbritch 
I'm not sure I concur with the pattern of Layout is not bindable and View is.
There is no `BindingSource` for `ContentView` or `PageView` for example. I can't bind a collection of `Widget` to `PageView` along with an `ItemTemplate`. 

Thanks for the link to the `CollectionView`.  Its a shame there are nearly 800 issues reported on it and its still only a spec in discussion with no actual coding started yet.  Clearly that project isn't going to be part of Xamarin within the next 12 months.

Maybe y'all should just buy this fairly well done package and get it main stream as a `BindableFlexLayout`.  
https://github.com/SuavePirate/DynamicWrapLayout
FYI: Its called `Layout` but its bindable.

**Comment by davidbritch** [comment]
Hi @tlhintoq 

I've extended the `FlexLayout` myself, with `ItemsSource` and `ItemTemplate` properties. However, it's not that straight forward. There's no UI or data virtualization so if you bind to (for example) a collection of 100 images, your app is going to eat memory.

`CollectionView` isn't just a spec. It's in active development. Once it's in a previewable form it'll be released.

**Comment by tlhintoq** [comment]
Hi @davidbritch,
I'm a bit unclear if this is just a spec at this point.  And it seems there is confusion on the site for it as well.  Its was moved to sprint 140, which to any other company would mean its actively being worked on.  But as @opcodewriter asked on the page "How can it be in development if the spec is still being ironed out.?"

Do you have any deeper insight on that question?  Is it _really_ being worked on at this time and if so, how since the spec and even naming for it isn't decided?
![image](https://user-images.githubusercontent.com/11351506/44465223-f9ff7980-a5ea-11e8-8a5a-867037b9dbc4.png)

> so if you bind to (for example) a collection of 100 images, your app is going to eat memory.
Well yeah. The same can be said for a `ListView` too.  I don't think anyone expects Xamarin to keep kids from hurting themselves if they are running with scissors.  The individual developer using the controls has to take some responsibility for not dropping 100 images at 12megs each.  Paging... memory management... scaling thumbnails... basic good practices from a developer that isn't just whacking about on their coffee table should be the responsibility of the developer.  If the controls get so overloading with constraints and "brains" they get so loaded down they aren't performant and aren't worth using.  Not to mention all that extra time that could be devoted to the _next_ project.

By the same token, this control should also be able to take a class such as `Employee` and a template to lay them all out - it isn't just about one use case of a bunch of photos.  Right?

**Comment by davidbritch** [comment]
Hi @tlhintoq 

It's not just a spec - it's in active development. We're currently in sprint 140 and there have been internal demos of implementation progress. Naming is still under discussion, as is the API. Those won't be finalised until the feature lands in a release.

Re: FlexLayout

I hear what you're saying.  However, it's not difficult to add this functionality yourself (see https://www.davidbritch.com/2018/06/binding-flexlayout-to-collection.html). On top of that, it's an implementation of the CSS flex-box. To that end, it doesn't venture beyond the [flex-box spec](https://www.w3.org/TR/css-flexbox-1/).
