### ISSUE TITLE
.SetSound is deprecated

### ISSUE THREAD

**Issue by RazvanEmilR** [MicrosoftDocs/xamarin-docs#687]
.SetSound (RingtoneManager.GetDefaultUri(RingtoneType.Ringtone))

is deprecated. Why update with a deprecated line, because this has been recently updated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 78e442e3-b387-f538-5430-e4538cf60cb9
* Version Independent ID: 44dc930e-09e2-56e8-e693-18a69af0a747
* Content: [Local Notifications - Xamarin](https://docs.microsoft.com/en-us/xamarin/android/app-fundamentals/notifications/local-notifications#Enabling_Sound_and_Vibration)
* Content Source: [docs/android/app-fundamentals/notifications/local-notifications.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/android/app-fundamentals/notifications/local-notifications.md)
* Product: **xamarin**
* GitHub Login: @mgmclemore
* Microsoft Alias: **mamcle**

**Comment by RazvanEmilR** [comment]
unless it's a Visual Studio Xamarin bug, because it underlines it green as deprecated.

**Comment by topgenorth** [comment]
You're correct `.SetSound` was deprecated in API 26. Ideally, apps should be using `NotificationChannel.SetSound` instead.  

Thanks for reporting this, we'll add it to our list of things to fix up.
