### ISSUE TITLE
Permisos en android a partir de la versión 23

### ISSUE THREAD

**Issue by DavidPrio** [MicrosoftDocs/xamarin-docs#688]
@sergioacortes commented on [Sat Aug 18 2018](https://github.com/MicrosoftDocs/xamarin-docs.es-es/issues/18)

A partir de la versión 23 se deben de especificar los permisos AccessCoarseLocation y AccessFineLocation en runtime, estaría bien que actualizaran la guía de ejemplo.

https://blog.xamarin.com/requesting-runtime-permissions-in-android-marshmallow/

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: 732de335-2b07-a3f1-dad1-88bf6c77b80a
* Version Independent ID: a0979276-6fb0-fede-805b-ad7cc80a6d4d
* Content: [Mapa de Xamarin.Forms - Xamarin](https://docs.microsoft.com/es-es/xamarin/xamarin-forms/user-interface/map)
* Content Source: [docs/xamarin-forms/user-interface/map.md](https://github.com/MicrosoftDocs/xamarin-docs.es-ES/blob/live/docs/xamarin-forms/user-interface/map.md)
* Product: **xamarin**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by DavidPrio** [comment]
Hi @davidbritch This contribution from es-es repo basically reports that:
_As of version 23, you must specify the AccessCoarseLocation and AccessFineLocation permissions in runtime, it would be nice to have the example guide updated._
Can you please check this? Thanks!
@sergioacortes FYI

**Comment by davidbritch** [comment]
Hi @DavidPrio 

The user is right, in the context of accessing location in a map from Xamarin.Forms. I've created an issue in our backlog to address this.

**Comment by ianthetechie** [comment]
Why is this issue closed? The docs still seem wrong to me. I get a crash on launch.
