### ISSUE TITLE
Where is NamedColor class?

### ISSUE THREAD

**Issue by wayne-kim** [MicrosoftDocs/xamarin-docs#69]
this docs and XamlSamples project not create NamedColor. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 969d1fbd-aeab-0c4f-8e1b-f7f3c139fd78
* Version Independent ID: 6ea369b2-0654-27ac-5911-aaf77e1c1495
* Content: [Part 4. Data Binding Basics - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/xaml/xaml-basics/data-binding-basics#feedback)
* Content Source: [docs/xamarin-forms/xaml/xaml-basics/data-binding-basics.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/xaml/xaml-basics/data-binding-basics.md)
* Service: **unspecified**
* GitHub Login: @charlespetzold
* Microsoft Alias: **chape**

**Comment by charlespetzold** [comment]
The `NamedColor` class is part of the **XamlSamples** sample:
https://github.com/xamarin/xamarin-forms-samples/blob/master/XamlSamples/XamlSamples/XamlSamples/NamedColor.cs
