### ISSUE TITLE
Heads up: Don't use == to compare two NSUuids

### ISSUE THREAD

**Issue by jmosbech** [MicrosoftDocs/xamarin-docs#690]
In `ActiveCallManager.FindCall` you are comparing two NSUuids by value. The [apple documentation](https://developer.apple.com/documentation/foundation/nsuuid) states:

&gt; Two NSUUID objects are not guaranteed to be comparable by pointer value (as CFUUID is); use isEqual(_:) to compare two NSUUID instances.

So you should rather use `call.UUID.Equals(uuid)` when you check for equality.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8ce24684-3989-9cfe-e438-0c71d4a83f3f
* Version Independent ID: 0ab1140f-eda9-6ba8-440e-f1271398e508
* Content: [CallKit in Xamarin.iOS - Xamarin](https://docs.microsoft.com/en-us/xamarin/ios/platform/callkit?tabs=vsmac)
* Content Source: [docs/ios/platform/callkit.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/ios/platform/callkit.md)
* Product: **xamarin**
* GitHub Login: @bradumbaugh
* Microsoft Alias: **brumbaug**

**Comment by bradumbaugh** [comment]
Thanks @jmosbech – good catch! I updated this; fix should be published soon. Appreciate the help!
