### ISSUE TITLE
Is Stackview still not supported in Stable?

### ISSUE THREAD

**Issue by lvita** [MicrosoftDocs/xamarin-docs#691]
It's been a year since the support notice

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ab435eee-6ac4-e582-e502-25892640b749
* Version Independent ID: 8a3cf85a-1fa7-1ce7-e717-2247e43f9427
* Content: [Stack Views in Xamarin.iOS - Xamarin](https://docs.microsoft.com/en-us/xamarin/ios/user-interface/controls/uistackview#feedback)
* Content Source: [docs/ios/user-interface/controls/uistackview.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/ios/user-interface/controls/uistackview.md)
* Product: **xamarin**
* GitHub Login: @bradumbaugh
* Microsoft Alias: **brumbaug**

**Comment by bradumbaugh** [comment]
Hi @lvita – thanks for calling this out. This document is in need of a refresh, as stack views are indeed now supported by the iOS Designer. I'll add an item to our backlog to refresh this.

Thanks again!
