### ISSUE TITLE
oAuth redirection issue on Android version less than 7 (API 24) 

### ISSUE THREAD

**Issue by xamarinrk1** [MicrosoftDocs/xamarin-docs#694]
We implemented oAuth successfully using Xamarin.Auth and works fine on Android version 8.1 (OREO API 27) and on iOS, but with the same code base redirection fails on android devices with version less than 7 and redirection is throwing the following error,   ERR_UNKNOWN_URL_SCHEME

Any help would be appreciated.

**Comment by topgenorth** [comment]
See https://github.com/MicrosoftDocs/xamarin-docs/issues/696
