### ISSUE TITLE
ERR_UNKNOWN_URL_SCHEME on oAuth redirection

### ISSUE THREAD

**Issue by xamarinrk1** [MicrosoftDocs/xamarin-docs#696]
Successfully implemented oAuth flow working on Xamarin forms app, works fine on Android versions 8.1, 8, 7.1 and 7  and also iOS. but seeing ERR_UNKNOWN_URL_SCHEME error on android version less than 7

**Comment by davidbritch** [comment]
Hi @xamarinrk1 

This is a question for the Xamarin.Auth engineering [repo](https://github.com/xamarin/Xamarin.Auth).
