### ISSUE TITLE
getting error that "TranslationHistoryActivity" could not be found

### ISSUE THREAD

**Issue by xdrx** [MicrosoftDocs/xamarin-docs#699]
var intent = new Intent(this, typeof(TranslationHistoryActivity));

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 672a11c0-fb8f-4b75-f42c-23429f52c35a
* Version Independent ID: 51f9c1e4-fa5d-b6ac-6081-c4c3189191f7
* Content: [Hello, Android Multiscreen: Quickstart - Xamarin](https://docs.microsoft.com/en-us/xamarin/android/get-started/hello-android-multiscreen/hello-android-multiscreen-quickstart?tabs=vswin)
* Content Source: [docs/android/get-started/hello-android-multiscreen/hello-android-multiscreen-quickstart.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/android/get-started/hello-android-multiscreen/hello-android-multiscreen-quickstart.md)
* Product: **xamarin**
* GitHub Login: @mgmclemore
* Microsoft Alias: **mamcle**

**Comment by xdrx** [comment]
TranslationHistoryActivity.cs appears in the same folder (phoneworld) as MainActivity.cs, however it does not appear in the solution explorer. Any ideas why?

**Comment by mgmclemore** [comment]
Hello @xdrx,  the **Hello, Android** series is currently being updated to be in sync with the new templates introduced in Visual Studio 15.8. The changes should be published soon. Thank you for your feedback and for your patience!

**Comment by ShazwieHar** [comment]
i still have this issue
