### ISSUE TITLE
Supported assemblies table is cut off on narrow display

### ISSUE THREAD

**Issue by lambdageek** [MicrosoftDocs/xamarin-docs#7]
I'm using Chrome.  The "main content" element is 689 pixels wide.  The only columns from the "Supported Assemblies" table that I can see are "Assembly" "API Compatablity" and "Xamarion.iOS".  There is no horizontal scroll bar.  The remaining columns are invisible and there's no indication they're there.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e52e0570-6cf1-3004-46fa-10c4d5a63c8d
* Version Independent ID: 8b628e08-acd1-95fe-a8ed-b0708d407d78
* Content: [Available Assemblies - Xamarin | Microsoft Docs](https://docs.microsoft.com/en-us/xamarin/cross-platform/internals/available-assemblies)
* Content Source: [docs/cross-platform/internals/available-assemblies.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/cross-platform/internals/available-assemblies.md)
* Service: **unspecified**
* GitHub Login: @asb3993
* Microsoft Alias: **amburns**

**Comment by conceptdev** [comment]
Thanks @lambdageek, this is a side-effect of the default styling on the site.

While not an ideal solution, it can help to make the page narrower, which forces wrapping in the first two columns and allows the availability ticks to be visible.

![screen shot 2018-03-13 at 3 50 58 pm](https://user-images.githubusercontent.com/199373/37374006-6e8609b6-26d6-11e8-9bd5-85dfc9f063a8.png)

We'll investigate options for improving this.

**Comment by conceptdev** [comment]
Changes have been made to allow wrapping of the first two columns, which should improve readability at all browser widths.
