### ISSUE TITLE
inconsistencies between lessons. this is just one of MANY.

### ISSUE THREAD

**Issue by xdrx** [MicrosoftDocs/xamarin-docs#700]
In Part one the string was was called:
    &lt;string name="translationHistory"&gt;Translation History&lt;/string&gt;
In the Deep Dive it showed the string as:
    &lt;string name="translationHistory"&gt;Call History&lt;/string&gt;

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f4b7d0a1-1c45-0ef1-c11e-491e85d32991
* Version Independent ID: c7acc4e2-78a4-98f0-2e64-5e395c974c81
* Content: [Hello, Android Multiscreen: Deep Dive - Xamarin](https://docs.microsoft.com/en-us/xamarin/android/get-started/hello-android-multiscreen/hello-android-multiscreen-deepdive)
* Content Source: [docs/android/get-started/hello-android-multiscreen/hello-android-multiscreen-deepdive.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/android/get-started/hello-android-multiscreen/hello-android-multiscreen-deepdive.md)
* Product: **xamarin**
* GitHub Login: @mgmclemore
* Microsoft Alias: **mamcle**

**Comment by mgmclemore** [comment]
Hello @xdrx,  the **Hello, Android** series is currently being updated to be in sync with the new templates introduced in Visual Studio 15.8. The changes should be published soon. Thank you for your feedback and for your patience!
