### ISSUE TITLE
Out of date

### ISSUE THREAD

**Issue by LindaLawton** [MicrosoftDocs/xamarin-docs#701]
This document is out of date a lot of the buttons to find things are not here.    

Issue is with 

4. While Mobile development with .NET is selected, have a look at the Summary panel on the right.

I cant find a summary panel. the panel i have does not have the same options seen in this picture.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9f14a6f0-b8b3-972e-83ee-101d73a29b5c
* Version Independent ID: 998e7f1b-b932-5aa0-d0d9-3b7add5f9073
* Content: [Installing Xamarin in Visual Studio 2017 - Xamarin](https://docs.microsoft.com/en-us/xamarin/cross-platform/get-started/installation/windows)
* Content Source: [docs/cross-platform/get-started/installation/windows.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/cross-platform/get-started/installation/windows.md)
* Product: **xamarin**
* GitHub Login: @asb3993
* Microsoft Alias: **amburns**

**Comment by bradumbaugh** [comment]
Hi @LindaLawton – thanks for calling this out. That summary pane is now called "Installation details." I've updated the screenshot in the doc to match (and made a few other minor tweaks to this doc). Updates should be published soon. Thank you!
