### ISSUE TITLE
Dead links

### ISSUE THREAD

**Issue by KristofferBerge** [MicrosoftDocs/xamarin-docs#702]
Seems like all links to developer.apple.com in this guide results in a 404

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 38f45c59-a1e0-0100-710c-11236e95c68a
* Version Independent ID: 215ff2da-b1d5-a83a-67fc-29cb81a7c216
* Content: [Objective-C Selectors in Xamarin.iOS - Xamarin](https://docs.microsoft.com/en-us/xamarin/ios/internals/objective-c-selectors)
* Content Source: [docs/ios/internals/objective-c-selectors.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/ios/internals/objective-c-selectors.md)
* Product: **xamarin**
* GitHub Login: @bradumbaugh
* Microsoft Alias: **brumbaug**

**Comment by bradumbaugh** [comment]
Thanks @KristofferBerge – appreciate you calling this out. I've updated the links on this doc - should be published soon. Appreciate the help!
