### ISSUE TITLE
Update Init Parameter name

### ISSUE THREAD

**Issue by LanceMcCarthy** [MicrosoftDocs/xamarin-docs#703]
The Xamarin.Android MainActivity uses the parameter name `bundle` instead of `savedInstanceState`. I suggest that the code snippet:

`Xamarin.Essentials.Platform.Init(this, savedInstanceState);`

be updated to 

`Xamarin.Essentials.Platform.Init(this, bundle);`

A less experienced developer might not know how to read the Init method overload to figure out what is supposed to be in the 2nd parameter.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 78e6dee8-1182-bf1e-fd3a-e8d1aecc094a
* Version Independent ID: 81202c69-317a-f0fa-7324-5316f7c1ceb7
* Content: [Get Started with Xamarin.Essentials - Xamarin](https://docs.microsoft.com/en-us/xamarin/essentials/get-started?tabs=windows%2Candroid)
* Content Source: [docs/essentials/get-started.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/essentials/get-started.md)
* Product: **xamarin**
* GitHub Login: @jamesmontemagno
* Microsoft Alias: **jamont**

**Comment by LanceMcCarthy** [comment]
To better explain what I'm referring to, here's a screenshot:

![image](https://user-images.githubusercontent.com/3520532/44602378-780b7e00-a7ad-11e8-835e-0fb8262d5660.png)

**Comment by jamesmontemagno** [comment]
The latest versions of VS 2017 use savedInstanceState, this is why it was updated.

Perhaps we should write a note in there that it may also be called bundle.

**Comment by jamesmontemagno** [comment]
Which specific template were you using? I am on 15.8.1 here. @conceptdev can we clean this up a bit?

**Comment by LanceMcCarthy** [comment]
Thanks James. I created that project a couple hours ago. Maybe my templates are outdated, even though I'm running 15.8.1

**Comment by LanceMcCarthy** [comment]
Found the culprit. That project was generated with our Wizard (which is based off the Xamarin's File > New template in 15.7.x).

**Comment by conceptdev** [comment]
I've made a tweak to the page, hopefully it'll be clearer
