### ISSUE TITLE
Update UI example

### ISSUE THREAD

**Issue by jgscherber** [MicrosoftDocs/xamarin-docs#704]
The UI examples for many of the sections show very old versions of Android

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b6deff31-ea26-96a9-b201-b199a5fc4144
* Version Independent ID: ea7509c3-2f29-8775-b100-b94594d9f2f8
* Content: [Android Controls (Widgets) - Xamarin](https://docs.microsoft.com/en-us/xamarin/android/user-interface/controls/)
* Content Source: [docs/android/user-interface/controls/index.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/android/user-interface/controls/index.md)
* Product: **xamarin**
* GitHub Login: @mgmclemore
* Microsoft Alias: **mamcle**

**Comment by topgenorth** [comment]
Thanks for reporting this. We strive to keep our documentation as current and relevant as possible. We've added an item to our backlog to address this issue.
