### ISSUE TITLE
Content Importing needs an update

### ISSUE THREAD

**Issue by BenjaminRichardson** [MicrosoftDocs/xamarin-docs#706]
Very helpful, I'm appreciate the guide a great deal. However, the information about getting the character sprite is out of date. At least link to the Monogame docs somewhere http://www.monogame.net/documentation/?page=adding_content 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 68f143ce-fcb0-172a-625d-3b26523c9fae
* Version Independent ID: 9694d752-dc85-9871-e40c-d4e1451dd777
* Content: [Part 2 – Implementing the WalkingGame - Xamarin](https://docs.microsoft.com/en-us/xamarin/graphics-games/monogame/introduction/part2#rendering-our-first-sprite)
* Content Source: [docs/graphics-games/monogame/introduction/part2.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/graphics-games/monogame/introduction/part2.md)
* Product: **xamarin**
* GitHub Login: @charlespetzold
* Microsoft Alias: **chape**

**Comment by bradumbaugh** [comment]
Thanks @BenjaminRichardson – I've made a note on an internal backlog that we need to review this doc for accuracy and update. Appreciate the help.
