### ISSUE TITLE
placing tabbed page on bottom

### ISSUE THREAD

**Issue by vhnatyk** [MicrosoftDocs/xamarin-docs#707]
Somehow windows:Page.ToolbarPlacement="Bottom" doesn't work on a page instance for a tabbed page. 
"The result is that the specified toolbar placement is applied to the Page instance" - it still on 3.1.0.6977 works as on 2.3.3 - just if set in App.cs for the whole application only for navigation pages. So "The result is..." - it just doesn't work, it's even worse that somehow I'm not even surprised:( 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5280a99e-bdcd-2de4-c84a-0eebf73bf3f1
* Version Independent ID: adbe9ca3-4898-5ebe-2253-d603fbd6e216
* Content: [Windows Platform-Specifics - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/platform/platform-specifics/consuming/windows#changing-the-page-toolbar-placement)
* Content Source: [docs/xamarin-forms/platform/platform-specifics/consuming/windows.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/platform/platform-specifics/consuming/windows.md)
* Product: **xamarin**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @vhnatyk 

Thanks for the feedback. Broken functionality in Xamarin.Forms needs reporting to the [engineering](https://github.com/xamarin/Xamarin.Forms) team.
