### ISSUE TITLE
Update OnPlatform docs with new declaration

### ISSUE THREAD

**Issue by akamud** [MicrosoftDocs/xamarin-docs#708]
PR [2615](https://github.com/xamarin/Xamarin.Forms/pull/2615) just got merged for Xamarin.Forms, it provides a simpler way of defining `OnPlatform` in XAML.

I'm wondering how this can be added to the documentation. I mean, this will be released only in XF 3.2, so how are these kind of issues treated? I don't see a `3.2` or `vnext` branch, so if I want to send a PR with theses changes, would I send it to `live` branch?

When these kind of changes are added to the documentation? After the release? Before with a disclaimer that it will only be available in new versions?

Lot of questions, but I'm trying to understand how one should update the Docs with these kind of information.

**Comment by conceptdev** [comment]
Updated documentation is not published until after a feature has shipped. 

For now, the branches we work on for new release documentation are not public, so unfortunately you cannot see or contribute to them directly. 

The process to add new content is [briefly outlined in the readme](https://github.com/MicrosoftDocs/xamarin-docs#contribute-to-xamarin-documentation), but basically it starts with a GitHub issue (create from an existing page on docs.microsoft.com/xamarin, if that page is where you want to add the new content). This way the internal team can work with you, and ensure that the effort is not being duplicated (ie. we are writing the new feature documentation as well).

Thanks for your interest!
