### ISSUE TITLE
Is Live Player still available for iPad?

### ISSUE THREAD

**Issue by DavidPressman** [MicrosoftDocs/xamarin-docs#709]
Live Player was once available for iOS, but I cannot locate an installer anywhere. Has it been abandoned?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0c2e54f0-7761-c7fb-7de7-6680782dc771
* Version Independent ID: 323dd999-d78a-819a-cc93-8cf6a6b36fac
* Content: [Xamarin Live Player App - Xamarin](https://docs.microsoft.com/en-us/xamarin/tools/live-player/player?tabs=windows)
* Content Source: [docs/tools/live-player/player.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/tools/live-player/player.md)
* Product: **xamarin**
* GitHub Login: @topgenorth
* Microsoft Alias: **toopge**

**Comment by bradumbaugh** [comment]
Hi @DavidPressman,

Thanks for your interest in the Xamarin Live Player Preview for iOS. As of August 10th we have stopped TestFlight registration and will no longer be distributing the iOS version of the Xamarin Live Player.

Please visit https://developer.xamarin.com/getting-started-android/ for the Android Preview instructions and download from Google Play.

Thanks!
