### ISSUE TITLE
ReadAllText not working in .netstandard 2.0 Xamarin Forms projects

### ISSUE THREAD

**Issue by rocketbob** [MicrosoftDocs/xamarin-docs#712]
ReadAllText isn't working but reading from a stream works fine.  Not sure where to log the issue.
var x = File.ReadAllText("myapp.file.xml"); ,&lt;-- doesn't work
var x = assembly.GetManifestResourceStream("myapp.file.xml");
                        using (var reader = new System.IO.StreamReader(x))
                        {
                            y = reader.ReadToEnd();
                        } &lt;--works fine

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8fb68890-cda3-6b2a-deba-55a171963da5
* Version Independent ID: 675d1663-d7ea-3e47-dbdd-772944acce5a
* Content: [File Handling in Xamarin.Forms - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/files?tabs=vsmac)
* Content Source: [docs/xamarin-forms/app-fundamentals/files.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/app-fundamentals/files.md)
* Product: **xamarin**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by topgenorth** [comment]
Sorry this isn't working as you expected. We can only respond to issues that deal with the docs. This sounds like something unexpected with `StreamReader`.  The best place to log bugs or issues with Visual Studio, Xamarin, or .NET would be the [Visual Studio Developer Community](https://developercommunity.visualstudio.com/spaces/8/index.html).
