### ISSUE TITLE
Mistake

### ISSUE THREAD

**Issue by niico100** [MicrosoftDocs/xamarin-docs#714]
At least on my Huawei phone, 'About Phone' isn't in Settings, it's in Settings &gt; System.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0fe8d6a6-7a42-810a-d5d4-e3bd162ae09a
* Version Independent ID: c7851826-27c9-9126-cb46-9300c57c440b
* Content: [Set Up Device for Development - Xamarin](https://docs.microsoft.com/en-us/xamarin/android/get-started/installation/set-up-device-for-development)
* Content Source: [docs/android/get-started/installation/set-up-device-for-development.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/android/get-started/installation/set-up-device-for-development.md)
* Product: **xamarin**
* GitHub Login: @mgmclemore
* Microsoft Alias: **mamcle**

**Comment by niico100** [comment]
The path under "Install USB Drivers" isn't present on my machine:
C:\Users\[username]\AppData\Local\Android\android-sdk
This does exist
C:\Users\[username]\AppData\Local\Android\sdk

But there's no android.bat file in that location. There is an android.bat file in:
C:\Users\[username]\AppData\Local\Android\sdk\Tools

Is this the file I need to run?

**Comment by niico100** [comment]
I posted the comment under the original issue by mistake - can't see any way to delete the comment which I moved - why not?

**Comment by mgmclemore** [comment]
Hi @niico100, thank you for the feedback! The Android SDK is now installed at **C:\Program Files (x86)\Android\android-sdk** as seen [here](https://docs.microsoft.com/en-us/xamarin/android/get-started/installation/android-sdk?tabs=vswin#sdk-manager). I've added a task to our backlog to update this topic. We endeavour to keep our docs accurate and up to date, but this topic looks to be in need of a refresh.
