### ISSUE TITLE
Wrong path

### ISSUE THREAD

**Issue by niico100** [MicrosoftDocs/xamarin-docs#715]
The path under "Install USB Drivers" isn't present on my machine:
C:\Users[username]\AppData\Local\Android\android-sdk
This does exist
C:\Users[username]\AppData\Local\Android\sdk

But there's no android.bat file in that location. There is an android.bat file in:
C:\Users[username]\AppData\Local\Android\sdk\Tools

Is this the file I need to run?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0fe8d6a6-7a42-810a-d5d4-e3bd162ae09a
* Version Independent ID: c7851826-27c9-9126-cb46-9300c57c440b
* Content: [Set Up Device for Development - Xamarin](https://docs.microsoft.com/en-us/xamarin/android/get-started/installation/set-up-device-for-development)
* Content Source: [docs/android/get-started/installation/set-up-device-for-development.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/android/get-started/installation/set-up-device-for-development.md)
* Product: **xamarin**
* GitHub Login: @mgmclemore
* Microsoft Alias: **mamcle**

**Comment by topgenorth** [comment]
That is the file you need to run.

Sorry about the confusion. Sometimes the exact path to where the Android SDK is located (and how the Android SDK organizes its files) changes over time.  We'll add this to our backlog to fixup .  Thanks for reporting this.
