### ISSUE TITLE
Icon not present

### ISSUE THREAD

**Issue by niico100** [MicrosoftDocs/xamarin-docs#716]
The Play button with the device name next to it isn't present in my Visual Studio. How do you add this? Where it is in Toolbar customization?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77d86088-d5e6-d80c-8787-51486345943f
* Version Independent ID: 083e4369-c9c9-d21f-0600-77389a946408
* Content: [Debug on Device - Xamarin](https://docs.microsoft.com/en-us/xamarin/android/deploy-test/debugging/debug-on-device?tabs=vswin)
* Content Source: [docs/android/deploy-test/debugging/debug-on-device.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/android/deploy-test/debugging/debug-on-device.md)
* Product: **xamarin**
* GitHub Login: @mgmclemore
* Microsoft Alias: **mamcle**

**Comment by mgmclemore** [comment]
Hi @niico100, if Visual Studio is installed correctly, you should be able to see, at minimum, some pre-configured emulator virtual devices in the device drop-down next to the Play button (without having to make any customizations). Unfortunately, we can only answer feedback related to documentation issues, so your best bet to get help is to visit the [Developer Community](https://developercommunity.visualstudio.com/spaces/8/index.html) forum.

**Comment by niico100** [comment]
In a correct Visual Studio installation toolbar icons can be turned on and off and rearranged. You can't assume any item will be on the user's toolbar.

I don't see a 'Devices' dropdown in the toolbar customization - I've found and added 'Solution Platforms' - is that it? If so just saying this in the documentation will help many users.

However, I don't see my android device listed in that dropdown. I've installed the Huawei USB Driver.

I want to 'Debug on Device' - the title of this document. My Android phone is setup for development and connected to my PC - as stated in the doc.

However, it doesn't really tell me how to do this at all - it's not clear how the phone name should be next to the Start arrow.

This documentation isn't fulfilling its role IMHO.

**Comment by mgmclemore** [comment]
Hi @niico100, thanks again for your feedback! We have created a task in our backlog to get the documentation updated. Meanwhile, to get help, please visit the [Developer Community](https://developercommunity.visualstudio.com/spaces/8/index.html) forum.
