### ISSUE TITLE
--registrar:legacystatic not working

### ISSUE THREAD

**Issue by alexmantaut** [MicrosoftDocs/xamarin-docs#717]
For compatibility reasons, I am trying to compile a Xamarin project with the --registrar:legacystatic flag, as specified in this documentation, but it fails with the following error:

Error MT0020: The valid options for '--registrar' are 'static, dynamic or default'. (MT0020)

How can I fix this? Do I need a different version of Xamarin.iOS?

I am using:
- Visual Studio Community: 7.6.1 (build 9)
- Xamarin.iOS: 11.14.0.13
- Xcode: 9.4.1

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 71d4e877-4fe6-075a-e812-186658ed9324
* Version Independent ID: a99afca7-8008-9400-d6a6-1e477580a6d9
* Content: [Type Registrar for Xamarin.iOS - Xamarin](https://docs.microsoft.com/en-us/xamarin/ios/internals/registrar)
* Content Source: [docs/ios/internals/registrar.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/ios/internals/registrar.md)
* Product: **xamarin**
* GitHub Login: @bradumbaugh
* Microsoft Alias: **brumbaug**

**Comment by bradumbaugh** [comment]
Hi @alexmantaut – this doc needs an update to indicate that the option you've mentioned doesn't work with the Unified API. 

I see there's a further discussion about this [here](https://github.com/xamarin/xamarin-macios/issues/4721) (in case anyone else looks at this issue and would find it helpful).

I've updated this doc in a number of ways; should be published soon. Thanks for calling this out.
