### ISSUE TITLE
Public, local and user accessible path

### ISSUE THREAD

**Issue by BrayanKhosravian** [MicrosoftDocs/xamarin-docs#718]
Hi i am looking for a path which points to a local, public and user accessible directory?

i have researched a lot, and tried variouse enum members of specialfoler. 
for example:
- Environment.GetFolderPath(Environment.SpecialFolder.Personal)
- Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData)
- Android.OS.Environment.GetExternalStoragePublicDirectory(Android.OS.Environment.DirectoryDownloads);
-Android.OS.Environment.GetExternalStoragePublicDirectory(Android.OS.Environment.DirectoryDocuments).AbsolutePath;

But I always get a path wich is somewhat like data/data/user/0/xamarin.live......blah
Which is only accessible via rooted devices -.-

The directories/folers have to be part of my interface of an observable collection, where the user should be able to add folders/directories to a public, local and user accessible directory.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8fb68890-cda3-6b2a-deba-55a171963da5
* Version Independent ID: 675d1663-d7ea-3e47-dbdd-772944acce5a
* Content: [File Handling in Xamarin.Forms - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/files?tabs=vswin)
* Content Source: [docs/xamarin-forms/app-fundamentals/files.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/app-fundamentals/files.md)
* Product: **xamarin**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by topgenorth** [comment]
Although this isn't cross-platform, on Android you can place the files on [external storage](https://docs.microsoft.com/en-ca/xamarin/android/platform/files/external-storage).

**Comment by conceptdev** [comment]
All the platforms supported by Xamarin.Forms have different file systems and capabilities. I recommend reviewing the link from Tom above, and the [iOS File System](https://docs.microsoft.com/en-us/xamarin/ios/app-fundamentals/file-system) guide to understand how each platform works. In general, all the mobile platforms have apps running in a sandbox that prevents file sharing by default, and will require code and configuration specific to each platform.
