### ISSUE TITLE
Shows incorrect not found warning in XAML for android properties

### ISSUE THREAD

**Issue by pmahend1** [MicrosoftDocs/xamarin-docs#719]
```
android:TabbedPage.ToolbarPlacement
android:TabbedPage.BarItemColor
android:TabbedPage.BarSelectedItemColor
``` 

all show warning as **The attachable property xyz not found in type `TabbedPage `**
But works as expected.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a4281f61-1386-2c1d-57fa-9fd66bf64cd7
* Version Independent ID: c762cb60-96b6-a123-37cb-f118da81773b
* Content: [Android Platform-Specifics - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/platform/platform-specifics/consuming/android#tabbedpage-toolbar)
* Content Source: [docs/xamarin-forms/platform/platform-specifics/consuming/android.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/platform/platform-specifics/consuming/android.md)
* Product: **xamarin**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by conceptdev** [comment]
Thanks for the info @pmahend1 – I'm glad it is working for you, at least. If you believe this is a product issue, please report it at [Developer Community](https://developercommunity.visualstudio.com/) - also available from the **Product Feedback** button in the docs, and the **Help > Report a problem** menu item in Visual Studio.
