### ISSUE TITLE
Add an article/section on macOS High Sierra

### ISSUE THREAD

**Issue by HankiDesign** [MicrosoftDocs/xamarin-docs#72]
I was reading through the Xamarin.Mac documentation and noticed that macOS Sierra has a [dedicated page](https://docs.microsoft.com/en-us/xamarin/mac/platform/introduction-to-macos-sierra/) on the [Platform Features](https://docs.microsoft.com/en-us/xamarin/mac/platform/) section but High Sierra is missing.

Some of the interesting topics that could be covered:

- Core ML (Vision for image analysis, Foundation for NLP, GameplayKit for evaluating learned decision trees)
- Metal 2 (Metal Performance Shaders framework, machine learning capabilities, debugging and optimization tools)
- Photos Project Extensions
- HEIF (High Efficiency Image Format)
- HEVC (H.265) video format

**Comment by bradumbaugh** [comment]
Thanks for the suggestion, @HankiDesign, and for the detail.

**Comment by bradumbaugh** [comment]
@HankiDesign I'm going to close this out and track it on our internal backlog. Thanks again for bringing it up!
