### ISSUE TITLE
Please, check if the example still works

### ISSUE THREAD

**Issue by preslavrachev** [MicrosoftDocs/xamarin-docs#720]
I tested it yesterday, and it came up with the following error: `Failed to run pod list`

In fact, there has been an open StackOverflow question for over 6 months and no answer. I started a bounty for it, with the hope that someone would provide an explanation.

Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7e5521ad-2f05-4dc4-e070-fbfd2e0cd200
* Version Independent ID: cba6b549-9f01-0964-3c1f-60e825cab870
* Content: [Real-world example using CocoaPods - Xamarin](https://docs.microsoft.com/en-us/xamarin/cross-platform/macios/binding/objective-sharpie/examples/cocoapod)
* Content Source: [docs/cross-platform/macios/binding/objective-sharpie/examples/cocoapod.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/cross-platform/macios/binding/objective-sharpie/examples/cocoapod.md)
* Product: **xamarin**
* GitHub Login: @asb3993
* Microsoft Alias: **amburns**

**Comment by bradumbaugh** [comment]
Hi @preslavrachev, sorry you've hit a snag here. Can you please take a look at this [similar issue](https://github.com/MicrosoftDocs/xamarin-docs/issues/173) to see if it helps? Appreciate it!

**Comment by preslavrachev** [comment]
@bradumbaugh the example seems to be working, but ObjectiveSharpie seems to be failing at binding,  when I tried it with another well-known library (FolioReaderKit):

```
Parsing 1 header files...
While building module 'FolioReaderKit' imported from /private/var/folders/fn/_nb7q_453t1dsd32ydrxm73h0000gn/T/com.xamarin.ObjectiveSharpie/634bb67175be4b0f9e3841266345875d.h:1:
In file included from <module-includes>:2:
/path_to_dir/pods/build/Release-iphoneos/FolioReaderKit/FolioReaderKit.framework/Headers/FolioReaderKit-Swift.h:171:9: fatal error: module 'RealmSwift' not found
@import RealmSwift;
 ~~~~~~~^~~~~~~~~~
/private/var/folders/fn/_nb7q_453t1dsd32ydrxm73h0000gn/T/com.xamarin.ObjectiveSharpie/634bb67175be4b0f9e3841266345875d.h:1:9: fatal error: could not build module 'FolioReaderKit'
@import FolioReaderKit;
 ~~~~~~~^~~~~~~~~~~~~~

Binding...
2 errors generated.
Error while processing /private/var/folders/fn/_nb7q_453t1dsd32ydrxm73h0000gn/T/com.xamarin.ObjectiveSharpie/634bb67175be4b0f9e3841266345875d.h.
```
It is a Swift library. but still, it seems to be having all the necessary `objC` annotations.
Should I open a separate issue for this?

**Comment by bradumbaugh** [comment]
Hi @preslavrachev – this repository is intended for documentation-related issues; if you need support, please use **Report a Problem** in [Visual Studio 2017](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio-2017) or [Visual Studio for Mac](https://docs.microsoft.com/visualstudio/mac/report-a-problem) to report issues in [Developer Community](https://developercommunity.visualstudio.com/spaces/8/index.html). That said, Objective Sharpie doesn't support Swift libraries.
