### ISSUE TITLE
Few issues regarding the explaination in this article

### ISSUE THREAD

**Issue by dinobu** [MicrosoftDocs/xamarin-docs#722]
1. The note above says "Attached behaviors are written for a specific control type (or a superclass that can apply to many controls), and they should only be added to a compatible control. Attempting to...".  So, which controls are supported and which are not?

2. The example uses an Entry to demonstrate attached behavior yet it uses Entry's provided event TextChanged?  If the purpose of behariors is to *add* functionality to user interface controls, why then use an already provided functionality (TextChanged) by Entry view?

3. Why not provide an example of adding a non-existing functionality since that is the purpose of attached behavior?  For example, there is no KeyDown or KeyUp event on ContentView like there was in Windows Forms, what about an example demonstrating how to add that behavior to ContentView?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cb2689ae-852d-9add-2b1e-ad527289530c
* Version Independent ID: 28779ffb-6581-8045-b6fd-305d0494465d
* Content: [Attached Behaviors - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/behaviors/attached)
* Content Source: [docs/xamarin-forms/app-fundamentals/behaviors/attached.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/app-fundamentals/behaviors/attached.md)
* Product: **xamarin**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @dinobu 

Thanks for the feedback. In answer to your questions:

1. You can write attached behaviors for any UI controls. If you write a behavior for a `Entry` you can only apply it to a `Entry`. Similarly, if you write a behavior for a `DatePicker` you can only apply it to a `DatePicker`. However, if you write a behavior for a `View` you could apply it to any UI controls that derive from `View` - in this case `Entry`, `DatePicker`, and all of the other Xamarin.Forms UI controls. This is the point the note you've alluded to is attempting to make.

2. The example does add functionality to a UI control. The `Entry` view doesn't provide any validation functionality. The attached behavior adds this validation functionality (checking that the input is a `double`).

3. As above, the attached behavior does add non-existing functionality to the `Entry` - validation. If you want to add additional events to a control you'd be better sub-classing the control, or using an [Effect](https://docs.microsoft.com/xamarin/xamarin-forms/app-fundamentals/effects/).
