### ISSUE TITLE
Targetted Updates?

### ISSUE THREAD

**Issue by dinobu** [MicrosoftDocs/xamarin-docs#723]
From reading this article, my understanding is as follows
Device gets notification that something has changed in my Azure SQL database
Device then shows a notification in form of a pop up dialog or notification icon

But if my Azure web app has done some CRUD operations such as added a record in database or deleted it or updated it, will this notification contain the record in question and allow device to update UI automatically?  For example, I am viewing a list of Employees and new employee is added.  Will the notification care Employee data and allow device to update list automatically and add that employee to it so it is in the list?

Or is this notification just letting device know something on backend has changed?  In that case, will it have exact information on what has changed so device can issue a pull to do targeted update (download only what changed)?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f2f7318c-8cd3-1aea-1f5e-e14955e2fa22
* Version Independent ID: 655cb554-cd03-e6ae-f7dd-9e2ba18a4a28
* Content: [Sending Push Notifications from Azure Mobile Apps - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/data-cloud/push-notifications/azure)
* Content Source: [docs/xamarin-forms/data-cloud/push-notifications/azure.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/data-cloud/push-notifications/azure.md)
* Product: **xamarin**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by topgenorth** [comment]
Generally speaking, a push notification contain what ever data that the developers want it to have. There are limitations on how big a push notification can be, this size limitation will vary from platform to platform. 

At it's simplest, a notification will only tell the client (a mobile device) in this case that something has happened, i.e. record(s) updated, deleted, or inserted. It is up to the client respond to that in an appropriate fashion.  Depending on how the push notification is created, it might have something like a key value or id that identifies the change to help the client out.

As some examples:
* Another user deletes an employee from a list.  A push notification goes out with the employee ID. The device could then remove that employee without contacting the backend.
* Several new employees are added. A push notification could either be a simple message and the client refreshes the entire list, or it might contain all the new employee IDs which the client requests and adds to it's own database.

Hope this answers your question.
