### ISSUE TITLE
Must launch Emulator + deploy ..and then enable Live Reload for it to work.

### ISSUE THREAD

**Issue by StanleyBroo** [MicrosoftDocs/xamarin-docs#724]
VS2017 Enterprise Stable Channel everything updated 30-aug

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e40394ca-9a55-d9b5-d427-7c2a2c00cfc8
* Version Independent ID: 5a5c17e2-a683-88f6-07a9-2002e814d54c
* Content: [Live Reload - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/xaml/live-reload)
* Content Source: [docs/xamarin-forms/xaml/live-reload.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/xaml/live-reload.md)
* Product: **xamarin**
* GitHub Login: @pierceboggan
* Microsoft Alias: **piboggan**

**Comment by StanleyBroo** [comment]
If you stop emulator and choose another emulator it wont work.
Same procedure ...start new emulator + deploy + enable Live Reload ->Works

**Comment by StanleyBroo** [comment]
Really need Live Reload to also reflect C# code changes  without a new compilation. Prio
The Emulator / Real device compilation is the biggest time thief in developing Xamarin.Forms projects

**Comment by topgenorth** [comment]
Thanks for your feedback. I'm sorry that you're experiencing issues with Live Reload.  We can only respond to issues that deal with the documentation. If you're experiencing problems with Live Reload, the best place to seek help is to raise an issue on the [Visual Studio Developer Community](https://developercommunity.visualstudio.com/spaces/8/index.html).
