### ISSUE TITLE
Is is current at 30.08.2018?

### ISSUE THREAD

**Issue by ticotaco72** [MicrosoftDocs/xamarin-docs#725]
I think not, cause on other place at microsoft webpage you say xamarin.android is netstandard 2.0 so why System.Drawing.dll is blank at android column?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e52e0570-6cf1-3004-46fa-10c4d5a63c8d
* Version Independent ID: 8b628e08-acd1-95fe-a8ed-b0708d407d78
* Content: [Available Assemblies - Xamarin](https://docs.microsoft.com/en-us/xamarin/cross-platform/internals/available-assemblies)
* Content Source: [docs/cross-platform/internals/available-assemblies.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/cross-platform/internals/available-assemblies.md)
* Product: **xamarin**
* GitHub Login: @asb3993
* Microsoft Alias: **amburns**

**Comment by conceptdev** [comment]
Xamarin.Android can consume .NET Standard 2.0 libraries. Here is a thread about System.Drawing on the [.NET Standard github](https://github.com/dotnet/standard/issues/222).

The table is referring to the mono System.Drawing assembly, parts of which were _historically_ available in Xamarin.iOS and Xamarin.Mac. As noted, it is no longer directly supported on those platforms either. We will clarify this in the table.

Thanks for your feedback.
