### ISSUE TITLE
Using Android FusedLocationProvider in Background

### ISSUE THREAD

**Issue by TonyLugg** [MicrosoftDocs/xamarin-docs#728]
How do we use the FusedLocationProviderClient in the background.  Need to track location in foreground and background.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e091d4a3-b105-70f5-38d2-5b2de109ed04
* Version Independent ID: 7081d0bd-9061-eda8-dac2-1f6f42bffd02
* Content: [Location Services - Xamarin](https://docs.microsoft.com/en-us/xamarin/android/platform/maps-and-location/location)
* Content Source: [docs/android/platform/maps-and-location/location.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/android/platform/maps-and-location/location.md)
* Product: **xamarin**
* GitHub Login: @mgmclemore
* Microsoft Alias: **mamcle**

**Comment by mgmclemore** [comment]
Hi @TonyLugg, thank you for your feedback! I've added a task to our backlog to research this question and update this topic with additional information. Meanwhile, to get help with your question, please visit [Developer Community](https://developercommunity.visualstudio.com/spaces/8/index.html).

**Comment by TonyLugg** [comment]
Also, the notification code does not work with Oreo+ OSs.  They require creation of a notification channel.



Get Outlook for Android<https://aka.ms/ghei36>

________________________________
