### ISSUE TITLE
ForegroundServiceDemo does not include StartForegroundService

### ISSUE THREAD

**Issue by TonyLugg** [MicrosoftDocs/xamarin-docs#729]
ForegroundServiceDemo does not include StartForegroundService, which is what this article says we should use for Android 8+.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 14dfecf6-b596-61af-ef6c-c0b65838bd45
* Version Independent ID: 7e1e4994-270d-5383-7d2d-f6d1cd1e1992
* Content: [Foreground Services - Xamarin](https://docs.microsoft.com/en-us/xamarin/android/app-fundamentals/services/foreground-services)
* Content Source: [docs/android/app-fundamentals/services/foreground-services.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/android/app-fundamentals/services/foreground-services.md)
* Product: **xamarin**
* GitHub Login: @topgenorth
* Microsoft Alias: **toopge**

**Comment by topgenorth** [comment]
Thanks for bringing this to our attention, you're completely right.  I've added this to our list of items to fix.
