### ISSUE TITLE
Not all solution folders are described.

### ISSUE THREAD

**Issue by jraldrin** [MicrosoftDocs/xamarin-docs#732]
No descriptions for Packages, Connected Services, and Component folders.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ba4ac72b-0c09-80b8-7210-c77f1d2a6f42
* Version Independent ID: f39106cc-ec1f-55ea-002a-8928e742b551
* Content: [Hello, Android: Deep Dive - Xamarin](https://docs.microsoft.com/en-us/xamarin/android/get-started/hello-android/hello-android-deepdive?tabs=vsmac)
* Content Source: [docs/android/get-started/hello-android/hello-android-deepdive.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/android/get-started/hello-android/hello-android-deepdive.md)
* Product: **xamarin**
* GitHub Login: @mgmclemore
* Microsoft Alias: **mamcle**

**Comment by topgenorth** [comment]
Thanks for reporting this.  Developers don't need to worry about these folders as they are not a part of developing a Xamarin.Android app. These folders are used by Visual Studio to support the development of .NET projects.  

We'll update the guide and make a mention of this to help minimize confusion for future readers.
