### ISSUE TITLE
Is there a convention based relationship between a MyContentPage and MyContentPageCS?

### ISSUE THREAD

**Issue by StingyJack** [MicrosoftDocs/xamarin-docs#735]
Many of the xamarin forms samples will have three seemingly related ContentPage files... 

for example, the [EffectsDemo](https://github.com/xamarin/xamarin-forms-samples/tree/master/Behaviors/EffectBehavior/EffectsDemo)  has...

- HomePage.xaml  
- HomePage.xaml.cs  
- HomePageCS.cs  

... and there is some C# code in the HomePageCS.cs file that appears as if it should work together with the xaml but I don't see any reference to it or that the .xaml.cs page derives from it.  What is the relationship between these three content pages, and why not just use the code behind or an MVVM?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c36e7942-65b6-9877-aafd-5f1b1291d37d
* Version Independent ID: 77a599a6-43f2-068f-95ad-0a92ca2b4bca
* Content: [Customizing a ContentPage - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/custom-renderer/contentpage)
* Content Source: [docs/xamarin-forms/app-fundamentals/custom-renderer/contentpage.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/app-fundamentals/custom-renderer/contentpage.md)
* Product: **xamarin**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by conceptdev** [comment]
It is an exact copy of **HomePage.xaml**, but implemented in C# instead of XAML. It is intended to demonstrate how to accomplish the use of Effects using only code, ie.

```
label.Behaviors.Add (new EffectBehavior {
	Group = "Xamarin",
	Name = "LabelShadowEffect"
});
```

It is not referenced anywhere in the rest of the app. To try it out, replace [this line in App.cs](https://github.com/xamarin/xamarin-forms-samples/blob/master/Behaviors/EffectBehavior/EffectsDemo/App.cs#L11) with this:

```
MainPage = new HomePageCS ();
```

**Comment by nguyenthanhliemfc** [comment]
@StingyJack  You can create UI in C# don't need XAML!

**Comment by StingyJack** [comment]
@nguyenthanhliemfc - I get that but was confused about the presentation of the code in this repo. Examples of two ways to do the UI are present in the same folder.

**Comment by dannyjr894** [comment]
Send all files to dannyjr894@gmail.com

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by dannyjr894** [comment]
No man I thought u were someone else I apologise to you

**Comment by dannyjr894** [comment]
No I'm the real owner to this account if I'm not how did I even keep about
this can u tell me how

**Comment by dannyjr894** [comment]
What's the problem name?

**Comment by dannyjr894** [comment]
Scared of something

**Comment by conceptdev** [comment]
@dannyjr894 comments unrelated to the original issue will be deleted. Please do not spam these threads.
