### ISSUE TITLE
Enable profiling checkbox is missing

### ISSUE THREAD

**Issue by MJRomka** [MicrosoftDocs/xamarin-docs#738]
In my Visual Studio for Mac I don't see the checkbox under iOS Debug settings. See attachment
![projectoptions](https://user-images.githubusercontent.com/3237392/44972681-b7328f80-af62-11e8-9807-7ca8ec740354.png)

**Comment by bradumbaugh** [comment]
Hi @MJRomka, to use the profiler, you'll need a [Visual Studio Enterprise](https://visualstudio.microsoft.com/vs/compare/) subscription (look in the "Cross-platform Development" section). This is also [mentioned in the docs](https://docs.microsoft.com/en-us/xamarin/tools/profiler/?tabs=vsmac#download-and-install).

Hope this helps!
