### ISSUE TITLE
Resalvas:

### ISSUE THREAD

**Issue by LisandroSu** [MicrosoftDocs/xamarin-docs#739]
@makepag commented on [Sun Sep 02 2018](https://github.com/MicrosoftDocs/xamarin-docs.pt-br/issues/10)

Sendo uma versão 'Hello', acredito que poderia deixar claro que ao instalar o Xamarin, o template vem com o CoordinatorLayout, que não é simplesmente arrastar e soltar os widgets como mostrou no artigo.

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: 660b0f7c-9941-2db3-63bf-fc8a97765b1e
* Version Independent ID: 5aa1e6f6-534a-05b9-c44a-1f62b24c201a
* Content: [Hello, Android: início rápido - Xamarin](https://docs.microsoft.com/pt-br/xamarin/android/get-started/hello-android/hello-android-quickstart?tabs=vswin)
* Content Source: [docs/android/get-started/hello-android/hello-android-quickstart.md](https://github.com/MicrosoftDocs/xamarin-docs.pt-BR/blob/live/docs/android/get-started/hello-android/hello-android-quickstart.md)
* Product: **xamarin**
* GitHub Login: @mgmclemore
* Microsoft Alias: **mamcle**

**Comment by LisandroSu** [comment]
Hi team,

Please check the issue reported by the user. Rough translation:

_Being a 'Hello' version, I believe I could make it clear that when installing Xamarin, the template comes with the CoordinatorLayout, which is not simply drag and drop the widgets as shown in the article._

Thanks!

**Comment by topgenorth** [comment]
Thanks for the feedback. We're currently in the process of an update to these guides, and will see about incorporating this.
