### ISSUE TITLE
Tabs NavigationPage title in proper case xamarin forms

### ISSUE THREAD

**Issue by arvindrajachourasiya** [MicrosoftDocs/xamarin-docs#741]
Using below xaml

```
<TabbedPage.Children>
<NavigationPage Title="Browse" Icon="tab_feed.png">     
    <x:Arguments>
        <views:ItemsPage />
    </x:Arguments>
</NavigationPage>    
</TabbedPage.Children>
</TabbedPage>
```
The title `Title="Browse"` totally showing in Capital letter. How can I make it in Title case.

**Comment by conceptdev** [comment]
This occurs by design on Android. See the [Material design guidelines](https://material.io/design/components/tabs.html) for more information.

**Comment by arvindrajachourasiya** [comment]
So you want to tell that this is standard to not show tab title in in proper case?
My question is, is it possible to do it from xamarin.forms shared project? Like by applying styles etc. without using custom renderer. 
Thank you
