### ISSUE TITLE
Download links are not working.

### ISSUE THREAD

**Issue by samsudeenks** [MicrosoftDocs/xamarin-docs#742]
Setup download links are not working. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e9e9c055-6a8e-5e81-00c7-e57c8c912a8b
* Version Independent ID: 28ac7239-a6c2-e31e-d423-b5268fd95c65
* Content: [Xamarin Profiler - Xamarin](https://docs.microsoft.com/en-us/xamarin/tools/profiler/?tabs=vsmac)
* Content Source: [docs/tools/profiler/index.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/tools/profiler/index.md)
* Product: **xamarin**
* GitHub Login: @topgenorth
* Microsoft Alias: **toopge**

**Comment by conceptdev** [comment]
We are aware of an issue that is causing installer failures, and are working to mitigate and resolve. Thanks for the heads-up; we hope to be back online soon.
