### ISSUE TITLE
Issues with Keychain

### ISSUE THREAD

**Issue by PorkiePie** [MicrosoftDocs/xamarin-docs#744]
I am using secure storage for holding logon details on a device so the user doesn't have to enter them each time - the assumption is a phone already has security access, and the app isn't a critical one regarding security of data. 
I set this up on Android and it worked like a dream. 
On iOS I followed the directions regarding Keychain and it broke the app. Something to do with permissions not being sufficient with the dev profile, but I couldn't find how to permit keychain to be used ( and also iOS is a black hole with me knowledge wise!).
I identified the issue was being caused when Enable Keychain was selected in the Entitlements. Reading this carefully Keychain access Groups 'Allow multiple apps to share passwords' which isn't what I need or want, so I deselected Enable Keychain and the app worked. 
I think you should make it clear regarding Enable Keychain, and also perhaps give some more guidance as to how this would work in a Groups environment and explain what profile permissions are required.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: da75050f-bfda-4792-40d9-b9a25d649d3e
* Version Independent ID: 5c44f996-765b-f6e4-c807-9446c534d50b
* Content: [Xamarin.Essentials: Secure Storage - Xamarin](https://docs.microsoft.com/en-us/xamarin/essentials/secure-storage?tabs=ios)
* Content Source: [docs/essentials/secure-storage.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/essentials/secure-storage.md)
* Product: **xamarin**
* GitHub Login: @Redth
* Microsoft Alias: **jodick**

**Comment by jamesmontemagno** [comment]
Thanks for the feedback and sorry for the delay. This entitlements setting is only required for iOS Simulator builds. When you are going to a device in dev or release you do not need these and they should be removed. The reason for this is because you are trying to access the macOS keychain for the simulator. I will work to update this document to specify this.

**Comment by PorkiePie** [comment]
Thanks. Understood.
