### ISSUE TITLE
EM1052 issue

### ISSUE THREAD

**Issue by galilov** [MicrosoftDocs/xamarin-docs#745]
//Source:
public class TestIOSClass
{
    public void CurrentValue()
    {
    }
}

Command:
../../../packages/Embeddinator-4000.0.4.0/tools/objcgen  --debug  --target=framework --platform=iOS --outdir=../../../output-ios  TestIOSLib.dll TestCrossPlatformLib.dll

Output:
Parsing assemblies...
	Parsed 'TestIOSLib.dll'
	Parsed 'TestCrossPlatformLib.dll'
Processing assemblies...
	4 types found
warning EM1052: Element CurrentValue is not generated as its name conflicts with other elements on the same class.

Question: What should I do to make CurrentValue available for Objective C ?

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ca90d1f9-50ac-86a0-d7fe-6686750308f6
* Version Independent ID: af7d6eb9-33a8-3318-ef1f-175f034ff211
* Content: [.NET Embedding errors - Xamarin](https://docs.microsoft.com/en-us/xamarin/tools/dotnet-embedding/errors#em1052-element-e-is-not-generated-its-name-conflicts-with-other-elements-on-the-same-class)
* Content Source: [docs/tools/dotnet-embedding/errors.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/tools/dotnet-embedding/errors.md)
* Product: **xamarin**
* GitHub Login: @topgenorth
* Microsoft Alias: **toopge**

**Comment by bradumbaugh** [comment]
Hi @galilov, sorry to hear you've hit a snag here. Unfortunately, this repository is intended for documentation-specific issues only. For support, use **Report a Problem** in [Visual Studio 2017](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio-2017) or [Visual Studio for Mac](https://docs.microsoft.com/visualstudio/mac/report-a-problem) to start a thread in [Developer Community](https://developercommunity.visualstudio.com/spaces/8/index.html). Thank you!
