### ISSUE TITLE
This is not working in Xamarin forms (Cross Platform)

### ISSUE THREAD

**Issue by pritish5** [MicrosoftDocs/xamarin-docs#746]
How to use this scenario Xamarin Form (Cross-platform project). I am trying to add reference of .aar project file into Android cross-platform I am able to add its reference but I am not able to get is a namespace. So how can I handle this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 53218ae9-ea6c-b958-9a78-e29a831fa630
* Version Independent ID: 7ed2930a-03d2-8a9c-0e62-e109b29acb92
* Content: [Binding an .AAR - Xamarin](https://docs.microsoft.com/en-us/xamarin/android/platform/binding-java-library/binding-an-aar)
* Content Source: [docs/android/platform/binding-java-library/binding-an-aar.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/android/platform/binding-java-library/binding-an-aar.md)
* Product: **xamarin**
* GitHub Login: @mgmclemore
* Microsoft Alias: **mamcle**

**Comment by mgmclemore** [comment]
Hi @pritish5, thank you for your feedback! I've added a task to our backlog to research this question and update this topic with additional information. Meanwhile, to get help with your question, please visit [Developer Community](https://developercommunity.visualstudio.com/spaces/8/index.html).

**Comment by aismaniotto** [comment]
Hi, some update? I didn't find about Xamarin Forms.
