### ISSUE TITLE
Outdated samples?

### ISSUE THREAD

**Issue by pmahend1** [MicrosoftDocs/xamarin-docs#747]
These solutions seem to be outdated when there was Xamarin Studio.  Could you please add new samples in which one does not have to modify project files for sniffing? I am getting DLLNotFoundException.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: faceb6c2-41b1-0285-3d61-ba6190567384
* Version Independent ID: 10e6c274-db30-8ba8-32f0-72d194348d3a
* Content: [Using Native Libraries - Xamarin](https://docs.microsoft.com/en-us/xamarin/android/platform/native-libraries)
* Content Source: [docs/android/platform/native-libraries.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/android/platform/native-libraries.md)
* Product: **xamarin**
* GitHub Login: @mgmclemore
* Microsoft Alias: **mamcle**

**Comment by mgmclemore** [comment]
Hi @pmahend1, thank you for your feedback! I've added a task to our backlog to update this sample or perhaps provide a newer one.

**Comment by pmahend1** [comment]
Thanks. I have added sample when I was checking this. [XamarinNDKSample](https://github.com/pmahend1/Xamarin/tree/master/XamarinNDKSample) if anyone is looking for working sample for Android
