### ISSUE TITLE
Material Design Patterns - Launch Screens incorrect.

### ISSUE THREAD

**Issue by ahoffmanvenado** [MicrosoftDocs/xamarin-docs#748]
The link for the Material Design Patterns - Launch Screens is incorrect and reroutes to https://material.io/design/ . From there, you still have to search for launch screen to get to the correct page. It looks like the correct link should be https://material.io/design/communication/launch-screen.html#usage . 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5823a3fa-87be-0b27-155b-b44130c67e84
* Version Independent ID: c90633f5-22b9-f7dd-fd08-c9affc251dd4
* Content: [Splash Screen - Xamarin](https://docs.microsoft.com/en-us/xamarin/android/user-interface/splash-screen)
* Content Source: [docs/android/user-interface/splash-screen.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/android/user-interface/splash-screen.md)
* Product: **xamarin**
* GitHub Login: @mgmclemore
* Microsoft Alias: **mamcle**

**Comment by topgenorth** [comment]
Thanks for reporting this. We'll fix this up ASAP and publish the updates as soon as se can.
