### ISSUE TITLE
Listing of XAML namespaces

### ISSUE THREAD

**Issue by davehax** [MicrosoftDocs/xamarin-docs#751]
It would be incredibly helpful if a listing of common Xamarin XAML namespaces could be compiled. For reference, I'm very new to XAML and am finding it incredibly difficult to locate helpful documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8cb234b9-b1c1-e43e-6015-466de8ff0ce3
* Version Independent ID: e66ed6aa-c7fa-8ead-e828-73c17a15320c
* Content: [XAML Namespaces in Xamarin.Forms - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/xaml/namespaces)
* Content Source: [docs/xamarin-forms/xaml/namespaces.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/xaml/namespaces.md)
* Product: **xamarin**
* GitHub Login: @charlespetzold
* Microsoft Alias: **chape**

**Comment by davidbritch** [comment]
Hi @davehax 

In Xamarin.Forms there are only two main XAML namespaces, as mentioned in the [Namespaces](https://docs.microsoft.com/xamarin/xamarin-forms/xaml/namespaces) doc. Any additional XAML namespaces are to access [platform-specifics](https://docs.microsoft.com/xamarin/xamarin-forms/platform/platform-specifics/index) or access your own types.
