### ISSUE TITLE
Incorrect instructions for Visual Studio Mac

### ISSUE THREAD

**Issue by petemillermultimedia** [MicrosoftDocs/xamarin-docs#752]
Visual Studio Community for Mac (v.7.6.3) does not have "Tools &gt; Options". Where is the Java Development Kit Location?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b71b3fd4-5a96-bc4b-77b8-f7b3f4a104c7
* Version Independent ID: 6da505ea-c6c6-f24c-3f1c-552c44a064a7
* Content: [How do I update the Java Development Kit (JDK) version? - Xamarin](https://docs.microsoft.com/en-us/xamarin/android/troubleshooting/questions/update-jdk?tabs=vswin)
* Content Source: [docs/android/troubleshooting/questions/update-jdk.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/android/troubleshooting/questions/update-jdk.md)
* Product: **xamarin**
* GitHub Login: @mgmclemore
* Microsoft Alias: **mamcle**

**Comment by mgmclemore** [comment]
Topic has been updated, changes should be published sometime early next week.
