### ISSUE TITLE
Add section describing whats not supported

### ISSUE THREAD

**Issue by jraldrin** [MicrosoftDocs/xamarin-docs#753]
Would be nice to have a section that describes what is not supported.  Best I can tell "constraint-layout" is not supported very well.  Maybe a comparison of designer features between android studio and xamarin product.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 927aa51c-a373-2e12-6208-4f6a9dd370d2
* Version Independent ID: 3a1c72c3-f0a8-e330-0c71-dd4e2a3258bb
* Content: [Using the Xamarin.Android Designer - Xamarin](https://docs.microsoft.com/en-us/xamarin/android/user-interface/android-designer/designer-walkthrough?tabs=vsmac)
* Content Source: [docs/android/user-interface/android-designer/designer-walkthrough.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/android/user-interface/android-designer/designer-walkthrough.md)
* Product: **xamarin**
* GitHub Login: @mgmclemore
* Microsoft Alias: **mamcle**

**Comment by mgmclemore** [comment]
Hi @jraldrin, thank you for the suggestion! I've added a task to our backlog to have this topic updated with the additional information.
