### ISSUE TITLE
ToView method

### ISSUE THREAD

**Issue by hanseltime** [MicrosoftDocs/xamarin-docs#754]
In Adding Platform Specific Views, the examples all imply that there is a ToView() method on each C# Platform Specific View.  Is this actually the case, or is this pseudo-code for "implement this in an inherited class"? My libraries do not present this functionality.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 74c821e6-ae09-bbe7-7bc5-0062c2bb29fb
* Version Independent ID: 0daa9061-aebb-529f-2bf1-f2c7b883bcc3
* Content: [Native Views in C# - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/platform/native-views/code)
* Content Source: [docs/xamarin-forms/platform/native-views/code.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/platform/native-views/code.md)
* Product: **xamarin**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @hanseltime 

The `ToView` method is implemented in Xamarin.Forms as an extension method - on iOS in LayoutExtensions.cs - https://github.com/xamarin/Xamarin.Forms/blob/9fe5372c1d80ca8fcff0c4fc397d25f91f6b61d3/Xamarin.Forms.Platform.iOS/Extensions/LayoutExtensions.cs#L31

Therefore, to use this method you have to add a `using` statement for the appropriate platform namespace - e.g. `using Xamarin.Forms.Platform.iOS`.
