### ISSUE TITLE
Invalid Link

### ISSUE THREAD

**Issue by TonyLugg** [MicrosoftDocs/xamarin-docs#755]
The link to Using SQLite.NET is not correct.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3ab6098a-39c7-151f-124b-f88aa62c4659
* Version Independent ID: dc27c1e4-ff12-c1af-646a-c2617def0bcd
* Content: [Xamarin.Forms Local Databases - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/databases)
* Content Source: [docs/xamarin-forms/app-fundamentals/databases.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/app-fundamentals/databases.md)
* Product: **xamarin**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @TonyLugg 

Thanks for the feedback. I've just updated the link and the change should be live within a few days.
