### ISSUE TITLE
 v10.0.16299.0 Mobile Extensions for UWP

### ISSUE THREAD

**Issue by bbassett3914** [MicrosoftDocs/xamarin-docs#756]
There is no  v10.0.16299.0 option to choose. Can I add it somehow? Only version 10.0.17134.0 is listed

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2de3e72c-8948-4dd5-e37f-9cf81e62c127
* Version Independent ID: 7b7c5c7f-4102-8e91-fbe6-7d21fcc8f5be
* Content: [Xamarin.Forms Quickstart - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/get-started/hello-xamarin-forms/quickstart?tabs=vswin)
* Content Source: [docs/xamarin-forms/get-started/hello-xamarin-forms/quickstart.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/get-started/hello-xamarin-forms/quickstart.md)
* Product: **xamarin**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by reidsci** [comment]
This tutorial seems obsolete because of that. A tutorial based on a key feature that has been removed in the latest release? Not good.

**Comment by bbassett3914** [comment]
All of the other documentation I've looked at has been succinct, in depth and well thought out. But a gigantic error is a very off-putting way to start things.

**Comment by davidbritch** [comment]
Hi @bbassett3914 and @reidsci 

Thanks for reporting this issue. This can be fixed with a configuration change. If you use v10.0.17134.0 of the Windows Mobile Extensions package, you need to set the target and min version of the UWP project to build against Windows 10 build 17134 (via project properties). Then everything builds as expected.

I've updated the samples and am in the process of updating the docs, so I'll close this issue.

**Comment by reidsci** [comment]
I will note that it is working. But instruction 28 says to select and click OK, which in my case didn't work. Selecting just selects and clicking OK means nothing (though you can do it at this point), unless you have also checked the checkbox.

**Comment by mbalcerzyk** [comment]
Can I still build for Windows 10 Mobile for Lumia phone? Mine runs Windows 10 Mobile 10.0.15254.538, does that mean to set minimum version as 1709 (I don't see the build version for this)?
