### ISSUE TITLE
Bad design??

### ISSUE THREAD

**Issue by scastria** [MicrosoftDocs/xamarin-docs#757]
Regarding the UWP example:  If I have a series of XF Pages created, maybe from an Android or iOS XF application, and I want to use one or more of those XF Pages in a native UWP app, I think it is bad to require the XF Page to be modified with UWP specific stuff.  In the example above, the PhonewordPage would already have an event handler for the Call History button that probably does a standard XF Navigation.PushAsync().  But in order for that button to now navigate when used in a native UWP app, it must be changed with UWP specific: Phoneword.UWP.MainPage.Instance.NavigateToCallHistoryPage();.  This means this PhonewordPage can no longer be used in Android or iOS.  Is there not a better way?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2e9d651b-6624-f671-16e2-61c28415374b
* Version Independent ID: 61600bb9-66b3-904d-6be3-32029e78bc5a
* Content: [Xamarin.Forms in Xamarin Native Projects - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/platform/native-forms)
* Content Source: [docs/xamarin-forms/platform/native-forms.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/platform/native-forms.md)
* Product: **xamarin**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @scastria 

While with Native Forms you can still use data binding and other Xamarin.Forms features, you can't use the Xamarin.Forms navigation API. You have to use the native navigation API. I thought this was explained in the doc, but it doesn't appear to be so I'll get it updated.
