### ISSUE TITLE
Link to MonoPInvokeCallbackAttribute is dead

### ISSUE THREAD

**Issue by lambdageek** [MicrosoftDocs/xamarin-docs#76]
The link to `MonoPInvokeCallbackAttribute` goes to https://developer.xamarin.com/api/type/MonoPInvokeCallbackAttribute/ which 404s

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 500b8f87-12fb-9f14-9655-06cd3f1d91d2
* Version Independent ID: b199d974-6356-af0e-9d96-81e54953b65d
* Content: [Limitations - Xamarin](https://docs.microsoft.com/en-us/xamarin/ios/internals/limitations)
* Content Source: [docs/ios/internals/limitations.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/ios/internals/limitations.md)
* Service: **unspecified**
* GitHub Login: @bradumbaugh
* Microsoft Alias: **brumbaug**

**Comment by lobrien** [comment]
`MonoPInvokeCallbackAttribute` should be at [https://developer.xamarin.com/api/type/ObjCRuntime.MonoPInvokeCallbackAttribute](https://developer.xamarin.com/api/type/ObjCRuntime.MonoPInvokeCallbackAttribute). That page 404s, despite the fact that the documentation file exists. We are investigating why that is. 

In the meantime, not to leave @lambdageek twisting in the wind, this is the documentation for the class (forgive the formatting):


       This attribute is valid on static functions and it is used by
       Mono's Ahead of Time Compiler to generate the code necessary to
       support native call calling back into managed code.

	In regular ECMA CIL programs this happens automatically, and
	it is not necessary to flag anything specially, but with pure
	Ahead of Time compilation the compiler needs to know which
	methods will be called from the unmanaged code.

	In the current version of MonoTouch, only static functions can
	be called back from unmanaged code.

	  You must specify the type of the delegate that this code
	  will be called as.  The following example shows the scenario
	  in which this is used:

	 using System;
	delegate void DrawPatternCallback (IntPtr voidptr, IntPtr cgcontextref);

	[StructLayout (LayoutKind.Sequential)]
	struct SetupStruct {
	 	int x, y;
		DrawPatternCallback draw;
	}

	[MonoPInvokeCallback (typeof (DrawPatternCallback))]
	static void DrawCallback (IntPtr voidptr, IntPtr cgcontextptr)
	{
		// This method is called from the C library
	}


And this is the documentation for the `.ctor(class System.Type t)`:

   	  You must specify the type of the delegate that this code
	  will be called as.  The following example shows the scenario
	  in which this is used:

        using System;
	delegate void DrawPatternCallback (IntPtr voidptr, IntPtr cgcontextref);

	[StructLayout (LayoutKind.Sequential)]
	struct SetupStruct {
	 	int x, y;
		DrawPatternCallback draw;
	}

	[MonoPInvokeCallback (typeof (DrawPatternCallback))]
	static void DrawCallback (IntPtr voidptr, IntPtr cgcontextptr)
	{
		// This method is called from the C library
	}

**Comment by bradumbaugh** [comment]
Hi @lambdageek, the link in the docs is now correct. Once the issue that @lobrien mentioned above is fixed, it will work correctly. Thanks for pointing this out!
