### ISSUE TITLE
Function name mismatch between code example and content description

### ISSUE THREAD

**Issue by jraldrin** [MicrosoftDocs/xamarin-docs#760]
In the IOS part of section Launching the Initial Xamarin.Forms Page on Each Platform the code shows function "FinishedLaunching" and the content description calls out "FinishedLoading"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 87f6cba8-cbf6-c849-66f7-ede66d51fb42
* Version Independent ID: 61922ab9-6ee6-ab3f-effe-b3f1f112000b
* Content: [An Introduction to Xamarin.Forms - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/get-started/introduction-to-xamarin-forms)
* Content Source: [docs/xamarin-forms/get-started/introduction-to-xamarin-forms.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/get-started/introduction-to-xamarin-forms.md)
* Product: **xamarin**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @jraldrin 

Thanks for the feedback. I've updated the doc, which should go live within a few days.
