### ISSUE TITLE
Storyboard Image Doesn't Show in Designer

### ISSUE THREAD

**Issue by TonyLugg** [MicrosoftDocs/xamarin-docs#761]
I've tried numerous times and the image does not show after I've selected it from disk.  I would have thought it would list the images from the asset catalog in the drop down but that does not happen.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5eaa7bed-8577-a8d2-06e9-3909ac8a4520
* Version Independent ID: e31b68bb-76de-6c63-883b-b1fd386cf001
* Content: [Launch Screens for Xamarin.iOS Apps - Xamarin](https://docs.microsoft.com/en-us/xamarin/ios/app-fundamentals/images-icons/launch-screens?tabs=vswin)
* Content Source: [docs/ios/app-fundamentals/images-icons/launch-screens.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/ios/app-fundamentals/images-icons/launch-screens.md)
* Product: **xamarin**
* GitHub Login: @bradumbaugh
* Microsoft Alias: **brumbaug**

**Comment by conceptdev** [comment]
@TonyLugg  Please report product issues to the engineering team so they can be fixed. This can be done by clicking the **Product feedback** button at the bottom of the docs, via **Help > Report a problem** in Visual Studio, or on [Developer Community](https://developercommunity.visualstudio.com/).
