### ISSUE TITLE
Why are there spaces between method name and the opening peren?

### ISSUE THREAD

**Issue by StingyJack** [MicrosoftDocs/xamarin-docs#762]
.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4bb713b4-53a5-e5c4-1155-0562ffd34960
* Version Independent ID: daad2dfe-3e42-88f6-6f25-8f66c435a6f6
* Content: [Consuming a RESTful Web Service - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/data-cloud/consuming/rest)
* Content Source: [docs/xamarin-forms/data-cloud/consuming/rest.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/data-cloud/consuming/rest.md)
* Product: **xamarin**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @StingyJack 

It's the old coding standard used by Mono, that used to be enforced by Xamarin Studio.
