### ISSUE TITLE
Setting automatic provisioning disables Custom Entitlements selection

### ISSUE THREAD

**Issue by nhwilly** [MicrosoftDocs/xamarin-docs#763]
The instructions say to select the custom entitlements file after enabling keychain.

I use the automatic provisioning feature and it disables the ability to select the custom entitlements file.

Workaround?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: da75050f-bfda-4792-40d9-b9a25d649d3e
* Version Independent ID: 5c44f996-765b-f6e4-c807-9446c534d50b
* Content: [Xamarin.Essentials: Secure Storage - Xamarin](https://docs.microsoft.com/en-us/xamarin/essentials/secure-storage?context=xamarin%2Fios&tabs=ios)
* Content Source: [docs/essentials/secure-storage.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/essentials/secure-storage.md)
* Product: **xamarin**
* GitHub Login: @Redth
* Microsoft Alias: **jodick**

**Comment by conceptdev** [comment]
@nhwilly I cannot reproduce the behavior you describe. Please report product issues to the engineering team so they can be fixed. This can be done by clicking the **Product feedback** button at the bottom of the docs, via **Help > Report a problem** in Visual Studio, or on [Developer Community](https://developercommunity.visualstudio.com/).

**Comment by zizusoft** [comment]
I have the same issue!
