### ISSUE TITLE
Unable to start emulator on azure D4s v3 VM

### ISSUE THREAD

**Issue by JaimeOnGit** [MicrosoftDocs/xamarin-docs#765]
After following detailed instructions more than 3 times from https://docs.microsoft.com/en-us/xamarin/android/get-started/installation/android-emulator/hardware-acceleration?tabs=vswin

Windows 10 Enterprise N
Version 1803
OS Build 17134.254
VS 2017 version 15.8.3
Emulator 27.3.9

Emulator wont start throwing below error message:
emulator: WHvGetCapability found. Querying WHPX capabilities...
emulator: WHvGetCapability failed. hr=0x00000000 whpx_cap.HypervisorPresent? 0
emulator: WHPX is either not available or not installed.
emulator: CPU Acceleration: DISABLED
emulator: CPU Acceleration status: Unable to open HAXM device: ERROR_FILE_NOT_FOUND
emulator: ERROR: x86 emulation currently requires hardware acceleration!
Please ensure Windows Hypervisor Platform (WHPX) is properly installed and usable.

**Comment by conceptdev** [comment]
Hi @JaimeOnGit, unfortunately we cannot resolve specific product errors here -- these issues are intended for feedback and improvements in the documentation.

You might need to reach out to Azure to confirm that the VMs you are using are capable of having Hyper-V configured.

We have some [troubleshooting guidance](https://docs.microsoft.com/en-us/xamarin/android/get-started/installation/android-emulator/troubleshooting?tabs=vswin#accel-issues-win) which is regularly updated, in case that helps.

If the product continues to fail, use the **Product feedback** button at the bottom of the doc, or go to [Developer Community](https://developercommunity.visualstudio.com/) to report.
