### ISSUE TITLE
google_app_id not in String.xml by default, this is not explained

### ISSUE THREAD

**Issue by dpuckett** [MicrosoftDocs/xamarin-docs#766]
I spent quite some time trying to figure out why google_app_id was not available when trying to log to it, and how to make it so. With no prior Android experience this was rather confusing. 
Please could you put a note into the tutorial to explain how to add it for use for those that don't inherently already know.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8d9bfb2a-2e5d-d505-337f-919251a85de3
* Version Independent ID: 695bff64-ae87-8c0f-5616-20b67893fdf0
* Content: [Remote Notifications with Firebase Cloud Messaging - Xamarin](https://docs.microsoft.com/en-us/xamarin/android/data-cloud/google-messaging/remote-notifications-with-fcm?tabs=vswin#background-notifications)
* Content Source: [docs/android/data-cloud/google-messaging/remote-notifications-with-fcm.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/android/data-cloud/google-messaging/remote-notifications-with-fcm.md)
* Product: **xamarin**
* GitHub Login: @mgmclemore
* Microsoft Alias: **mamcle**

**Comment by nhwilly** [comment]
Were you going to share that?  I'd like to know, too.  :)

**Comment by conceptdev** [comment]
Thanks for the feedback, this will be taken into considering for the next update to this doc.
