### ISSUE TITLE
Great Designer

### ISSUE THREAD

**Issue by ramin0011** [MicrosoftDocs/xamarin-docs#767]
its the most comprehensive solution for designing xamarin.forms apps 
it worked perfectly fine and applies any changes in your code and has no limitations comparing with xamarin previewer 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e40394ca-9a55-d9b5-d427-7c2a2c00cfc8
* Version Independent ID: 5a5c17e2-a683-88f6-07a9-2002e814d54c
* Content: [Live Reload - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/xaml/live-reload#getting-started)
* Content Source: [docs/xamarin-forms/xaml/live-reload.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/xaml/live-reload.md)
* Product: **xamarin**
* GitHub Login: @pierceboggan
* Microsoft Alias: **piboggan**

**Comment by davidbritch** [comment]
@ramin0011 

Thanks for the feedback.
