### ISSUE TITLE
Check conditions

### ISSUE THREAD

**Issue by jfren484** [MicrosoftDocs/xamarin-docs#768]
I think the only condition you can check once and store the result is #2 - hardware. The API level could change if the user updates to a newer version of the OS. Granted, that's not going to happen often, and probably unlikely that someone has hardware WITH a fingerprint reader that is on API 22 or lower, but it's still a possibility. And who knows - someone could create an external fingerprint reader that plugs into the USB port or audio port, so maybe even the hardware check needs to be done every time.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: febd430b-faf9-e25d-1bc8-de82a8453423
* Version Independent ID: 100f9740-a1f6-38de-57bb-e954c533dd92
* Content: [Getting Started with Fingerprint Authentication - Xamarin](https://docs.microsoft.com/en-us/xamarin/android/platform/fingerprint-authentication/get-started?tabs=vswin)
* Content Source: [docs/android/platform/fingerprint-authentication/get-started.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/android/platform/fingerprint-authentication/get-started.md)
* Product: **xamarin**
* GitHub Login: @mgmclemore
* Microsoft Alias: **mamcle**

**Comment by conceptdev** [comment]
@jfren484 fair call, it's always dangerous to make assumptions about the future! Going to rewrite that paragraph to address your feedback, thanks.

**Comment by conceptdev** [comment]
Wording has been updated in the doc, thanks again.
