### ISSUE TITLE
iOS Simulator is not supported

### ISSUE THREAD

**Issue by taimila** [MicrosoftDocs/xamarin-docs#771]
It would be good to state in the documentation that  `Email.ComposeAsync(message)` does not work in the iOS simulator.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 51ff7357-2cd8-7988-ed3c-de156cc18211
* Version Independent ID: ff242941-6d92-9523-bd73-ec03dbcb095d
* Content: [Xamarin.Essentials: Email - Xamarin](https://docs.microsoft.com/en-us/xamarin/essentials/email?context=xamarin/ios)
* Content Source: [docs/essentials/email.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/essentials/email.md)
* Product: **xamarin**
* GitHub Login: @jamesmontemagno
* Microsoft Alias: **jamont**

**Comment by conceptdev** [comment]
Thanks for the feedback @taimila
