### ISSUE TITLE
what's the comparison for UWP?

### ISSUE THREAD

**Issue by bubba9999** [MicrosoftDocs/xamarin-docs#772]
I feel there's a column missing for UWP... is Microsoft switching to Xamarin and dropping support for UWP?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a8daea50-6274-cf1d-54b0-1a8235e37c95
* Version Independent ID: eb075324-8e41-b3c1-072c-1971a7747d84
* Content: [UI Controls Comparison - Xamarin](https://docs.microsoft.com/en-us/xamarin/cross-platform/desktop/controls/)
* Content Source: [docs/cross-platform/desktop/controls/index.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/cross-platform/desktop/controls/index.md)
* Product: **xamarin**
* GitHub Login: @asb3993
* Microsoft Alias: **amburns**

**Comment by conceptdev** [comment]
We have chosen not to complicate the diagram with UWP - there is a separate [XAML Standard](https://docs.microsoft.com/xamarin/xamarin-forms/xaml/standard/) preview that shares the same element names across UWP and Xamarin.
