### ISSUE TITLE
estilos

### ISSUE THREAD

**Issue by merygarxiatekieroJp** [MicrosoftDocs/xamarin-docs#773]
interesanante

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cd6c1880-db99-6686-d58c-d771a3fb5d90
* Version Independent ID: cdb40411-2c31-57e9-7df3-c953f233c12f
* Content: [Explicit Styles in Xamarin.Forms - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/styles/xaml/explicit)
* Content Source: [docs/xamarin-forms/user-interface/styles/xaml/explicit.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/styles/xaml/explicit.md)
* Product: **xamarin**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by conceptdev** [comment]
Thanks for the feedback.
