### ISSUE TITLE
Project is dead?

### ISSUE THREAD

**Issue by MihaMarkic** [MicrosoftDocs/xamarin-docs#774]
Seems like CocosSharp has been abandoned as there hasn't been any activity for three years and nuget packages have been unlisted. Perhaps you might update the documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8f2c5446-f22b-8a7c-b200-7ebe6545562d
* Version Independent ID: e28405f0-a191-c724-4e0b-13c6dcb4023a
* Content: [CocosSharp 2D Game Engine - Xamarin](https://docs.microsoft.com/en-us/xamarin/graphics-games/cocossharp/)
* Content Source: [docs/graphics-games/cocossharp/index.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/graphics-games/cocossharp/index.md)
* Product: **xamarin**
* GitHub Login: @charlespetzold
* Microsoft Alias: **chape**

**Comment by conceptdev** [comment]
@MihaMarkic we are investigating ways to keep it available to the community, in case anyone still uses it. Thanks.
