### ISSUE TITLE
How to do this for iOS ?

### ISSUE THREAD

**Issue by leonmeijer** [MicrosoftDocs/xamarin-docs#775]
How to do this for iOS ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e994a1e6-78e2-1bed-f815-e4136b9b4206
* Version Independent ID: ee8093c5-80f1-63bb-cfbf-0cc70c27e49c
* Content: [App-Linking in Android - Xamarin](https://docs.microsoft.com/en-us/xamarin/android/platform/app-linking)
* Content Source: [docs/android/platform/app-linking.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/android/platform/app-linking.md)
* Product: **xamarin**
* GitHub Login: @mgmclemore
* Microsoft Alias: **mamcle**

**Comment by conceptdev** [comment]
Please see the [search APIs](https://docs.microsoft.com/xamarin/ios/platform/search/) section for Xamarin.iOS. The two platforms have different capabilities.
