### ISSUE TITLE
Font sizes per style

### ISSUE THREAD

**Issue by shalinasanga** [MicrosoftDocs/xamarin-docs#777]
1) What are the font sizes text get when we applied device style ? explain bit
2) What happened in system when we choose FontSize with Named Size or by explicitly with device style ?
ex: FontSize="Large" Style="{DynamicResource TitleStyle}"
         OR
       FontSize="42" Style="{DynamicResource TitleStyle}"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 84a125d3-c9cc-6189-b96c-a02430243107
* Version Independent ID: b3d8f24c-471d-f2ff-e2bc-85c36ab9687f
* Content: [Device Styles in Xamarin.Forms - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/styles/xaml/device)
* Content Source: [docs/xamarin-forms/user-interface/styles/xaml/device.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/styles/xaml/device.md)
* Product: **xamarin**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @shalinasanga 

1. The font sizes are dependent on the platform, OS release, and OS settings. For example, the `TitleStyle` on Android is equal to `global::Android.Resource.Attribute.TextAppearanceLarge` and on iOS equal to `UIFont.PreferredHeadline`. The values of the native members can change dependent on accessibility settings.
2. Setting the `FontSize` with a `Device` style will respect accessibility preferences. Setting `FontSize` to a named size will set a specific size, dependent upon the platform.
