### ISSUE TITLE
google play requirements

### ISSUE THREAD

**Issue by poparosa** [MicrosoftDocs/xamarin-docs#778]
google play now requires x32 and x64 builds to submit apps.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 78d11702-9a6f-ce25-3807-299f4905a00e
* Version Independent ID: f14945d8-62b4-7417-2f6d-02050ec2a927
* Content: [CPU Architectures - Xamarin](https://docs.microsoft.com/en-us/xamarin/android/app-fundamentals/cpu-architectures?tabs=vswin)
* Content Source: [docs/android/app-fundamentals/cpu-architectures.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/android/app-fundamentals/cpu-architectures.md)
* Product: **xamarin**
* GitHub Login: @mgmclemore
* Microsoft Alias: **mamcle**

**Comment by suggyd** [comment]
Hi Jon, I read your linked issue log about changing the build configuration, but my question is whether the "it's experimental" statement in the note above is still true?  Can you confirm that 64-bit runtime support is now production ready?  

Thanks for all your great work on Xamarin!

**Comment by ChristopheOosterlynck** [comment]
@JonDouglas Just as @suggyd I'm wondering If this is a documentation issue or in fact an issue with the current support for 64bit.

**Comment by conceptdev** [comment]
This page was updated in https://github.com/MicrosoftDocs/xamarin-docs/pull/1743 to mention the 64-bit requirement. Thanks again.
