### ISSUE TITLE
Conditional Compilation Directive for UWP?

### ISSUE THREAD

**Issue by dan-meier** [MicrosoftDocs/xamarin-docs#779]
Is there a conditional compilation directive for UWP? It's not explicitly mentioned in this document. Perhaps a table showing all platform (i.e., __IOS__, etc.) conditional compilation directives would be helpful.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d54ff3f6-796e-2f2b-4719-ac8c9a623455
* Version Independent ID: 9368f048-524d-fc8a-493f-47f60b34e20e
* Content: [Part 4 - Dealing with Multiple Platforms - Xamarin](https://docs.microsoft.com/en-us/xamarin/cross-platform/app-fundamentals/building-cross-platform-applications/platform-divergence-abstraction-divergent-implementation)
* Content Source: [docs/cross-platform/app-fundamentals/building-cross-platform-applications/platform-divergence-abstraction-divergent-implementation.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/cross-platform/app-fundamentals/building-cross-platform-applications/platform-divergence-abstraction-divergent-implementation.md)
* Product: **xamarin**
* GitHub Login: @asb3993
* Microsoft Alias: **amburns**

**Comment by conceptdev** [comment]
Thanks @dan-meier yeah it looks like this doc is a little out-of-date. I think the symbol you're after is `WINDOWS_UWP` -- need to do a little more research, then will update the doc. Appreciate the heads-up!

**Comment by conceptdev** [comment]
This page has been updated - thanks again for the feedback.
