### ISSUE TITLE
Unable to use On<Android>() 

### ISSUE THREAD

**Issue by jordan-hewitt** [MicrosoftDocs/xamarin-docs#780]
Inside the constructor of my TabbedPage I am trying to implement On&lt;Android().SetOffscreenPageLimit(2).SetIsSwipePagingEnabled(true);

When I do, it says 'IPlatformElementConfiguration&lt;Android, TabbedPage&gt; does not contain a definition for 'SetOffscreenPageLimit' and the best extension overload 'TabbedPage.SetOffscreenPageLimit(IPlatformElementConfiguration&lt;Android, TabbedPage&gt;, int)' requires a receiver of type 'IPlatformElementConfiguration&lt;Android, TabbedPage&gt;'.  I'm not sure what exactly sure what the receiver means, do I need to inherit off of it or what? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a4281f61-1386-2c1d-57fa-9fd66bf64cd7
* Version Independent ID: c762cb60-96b6-a123-37cb-f118da81773b
* Content: [Android Platform-Specifics - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/platform/platform-specifics/consuming/android#enable_swipe_paging)
* Content Source: [docs/xamarin-forms/platform/platform-specifics/consuming/android.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/platform/platform-specifics/consuming/android.md)
* Product: **xamarin**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by jordan-hewitt** [comment]
I also am using both Xamarin.Forms.PlatformConfiguration and Xamarin.Forms.PlatformConfiguration.AndroidSpecific along along with that error I am receiving another on the same line saying 'Android is a namespace but is used like a type'.

**Comment by jordan-hewitt** [comment]
I added Xamarin.Forms.PlatformConfiguration before Android and now there are no errors, but the behavior expected does not work... for any of these.

**Comment by davidbritch** [comment]
Hi @jordan-hewitt 

If you go to the "Related Links" section at the end of the doc, there's a link to a sample that demos all the platform-specifics in the doc. You should be able to extract what you need from there.
