### ISSUE TITLE
ViewDidLoad

### ISSUE THREAD

**Issue by mikequinlan** [MicrosoftDocs/xamarin-docs#785]
The image of the overridden ViewDidLoad method shows a call to base.AwakeFromNib(); This line isn't automatically generated when the overridden method is created (it calls base.ViewDidLoad instead) and it isn't explained in the text. Should we add this line to the method? What is its purpose?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b1614d24-dfaa-0fff-fcd2-c3c4844164f3
* Version Independent ID: b606b65a-2396-b25e-66d0-d0f099736882
* Content: [Hello, Mac – Walkthrough - Xamarin](https://docs.microsoft.com/en-us/xamarin/mac/get-started/hello-mac#creating-the-interface)
* Content Source: [docs/mac/get-started/hello-mac.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/mac/get-started/hello-mac.md)
* Product: **xamarin**
* GitHub Login: @bradumbaugh
* Microsoft Alias: **brumbaug**

**Comment by conceptdev** [comment]
It is _probably_ a copy paste error, and intended to be `base.ViewDidLoad`. Will do some research and see if the code snippet needs to be fixed. Thanks for pointing it out.

**Comment by conceptdev** [comment]
Update: the [linked sample code](https://github.com/xamarin/mac-samples/blob/master/Hello_Mac/Hello_Mac/ViewController.cs#L35) agrees with you:

```
public override void ViewDidLoad ()
{
	base.ViewDidLoad ();

	// Set the initial value for the label
	ClickedLabel.StringValue = "Button has not been clicked yet.";
}
```
