### ISSUE TITLE
Bug link needs to be updated from bugzilla to github

### ISSUE THREAD

**Issue by outbred** [MicrosoftDocs/xamarin-docs#787]
https://github.com/xamarin/xamarin-android/issues/1950

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0ec8f75f-1f2d-cd95-0e0a-4fe4e1f62bac
* Version Independent ID: 6babd81f-07a2-f569-c204-be6a021c0029
* Content: [Running Android Services in Remote Processes - Xamarin](https://docs.microsoft.com/en-us/xamarin/android/app-fundamentals/services/out-of-process-services)
* Content Source: [docs/android/app-fundamentals/services/out-of-process-services.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/android/app-fundamentals/services/out-of-process-services.md)
* Product: **xamarin**
* GitHub Login: @topgenorth
* Microsoft Alias: **toopge**

**Comment by conceptdev** [comment]
Updated the link as suggested, thanks.
