### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by birbilis** [MicrosoftDocs/xamarin-docs#788]
should say "clone the repository", not "close the repository"

---
#### Λεπτομέρειες εγγράφου

⚠ *Μην επεξεργαστείτε αυτή την ενότητα. Απαιτείται για σύνδεση θεμάτων docs.microsoft.com ➟ GitHub.*

* ID: 78e6dee8-1182-bf1e-fd3a-e8d1aecc094a
* Version Independent ID: 81202c69-317a-f0fa-7324-5316f7c1ceb7
* Content: [Get Started with Xamarin.Essentials - Xamarin](https://docs.microsoft.com/el-gr/xamarin/essentials/get-started?tabs=windows%2Candroid)
* Content Source: [docs/essentials/get-started.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/essentials/get-started.md)
* Product: **xamarin**
* GitHub Login: @jamesmontemagno
* Microsoft Alias: **jamont**

**Comment by conceptdev** [comment]
Thanks! I've updated the doc.
