### ISSUE TITLE
OnCreate not firing

### ISSUE THREAD

**Issue by RedCreole** [MicrosoftDocs/xamarin-docs#789]
Hi All, OnCreate in MainActivity.cs is never triggered and therefore Instance stays null.
Therefore (PhoneDialer.cs) MainActivity.Instance is always null :
var context = MainActivity.Instance;            if (context == null)                return false;
This seems to be an alternative way: var context = Android.App.Application.Context;

Why is OnCreate not triggered? 
Many thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 540c35eb-3db5-7e73-e6eb-07c4b70df1b0
* Version Independent ID: d8bd33e1-164d-2b2a-75de-42a95c75e6ad
* Content: [Xamarin.Forms Deep Dive - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/get-started/hello-xamarin-forms/deepdive?pivots=windows)
* Content Source: [docs/xamarin-forms/get-started/hello-xamarin-forms/deepdive.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/get-started/hello-xamarin-forms/deepdive.md)
* Product: **xamarin**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @RedCreole 

I just tried the [Phoneword sample]() and a breakpoint in `OnCreate` is triggered. I suggest you try the sample and if your breakpoint isn't hit it's most likely that you have issues with your Android install (check that you have the correct platform, build, and sdk tools installed).

**Comment by davidbritch** [comment]
Sample link - [Phoneword sample](https://developer.xamarin.com/samples/xamarin-forms/Phoneword/)

**Comment by RedCreole** [comment]
Hi David, 

Thanks for the quick feedback. I've downloaded the solution previously
but that didn't help (did it again though just in case). 

The Xamarin Live connection isn't sterling, and sometimes I've to run it
a few times before it actually gets a session. 

I'm using a Samsung and if I use the Samsung SM (Android 8.0) on VS to
run/debug it usually does not create a session, but the Samsung SM
PLAYER (Android 8.0) usually connects first time. 
(new to this so I'm not sure if that's the platform you're referring
too? I am assuming so).
Actually the former worked the first time today and created an app on
the device. This worked, and also triggers the OnCreate.
The latter (Samsung SM PLAYER (Android 8.0)) works except for calling
(aka failure to hit OnCreate). So perhaps something to do with the
Xamarin live (Player) platform/device that's got a kink in the cable.. 

Thanks. 

On 2018-09-21 10:04, David Britch wrote:

> Hi @RedCreole [1] 
> 
> I just tried the Phoneword sample and a breakpoint in OnCreate is triggered. I suggest you try the sample and if your breakpoint isn't hit it's most likely that you have issues with your Android install (check that you have the correct platform, build, and sdk tools installed). 
> 
> --
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub [2], or mute the thread [3].
 

Links:
------
[1] https://github.com/RedCreole
[2]
https://github.com/MicrosoftDocs/xamarin-docs/issues/789#issuecomment-423450055
[3]
