### ISSUE TITLE
version mismatch

### ISSUE THREAD

**Issue by pmahend1** [MicrosoftDocs/xamarin-docs#792]
Installer downloads version 8.0.1120 and download links point to1.8.0.9
Isnt the preview version should be higher than latest stable versions? Can you make dynamic links for latest OpenJDK instead of just 8.0.9

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 97e1cd96-e7a2-ec22-8d79-ac949e890ccb
* Version Independent ID: 922a3fdf-7bab-7d9d-5518-904db9e75ee3
* Content: [Microsoft's Mobile OpenJDK Distribution Preview - Xamarin](https://docs.microsoft.com/en-us/xamarin/android/get-started/installation/openjdk)
* Content Source: [docs/android/get-started/installation/openjdk.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/android/get-started/installation/openjdk.md)
* Product: **xamarin**
* GitHub Login: @vyedin
* Microsoft Alias: **vyedin**

**Comment by vyedin** [comment]
Are you sure version 8.0.1120 is not Oracle JDK? In which case, it's an entirely different package with its own versioning system.

Please let me know if you're referring to Mac or Windows installer, and which release.

**Comment by vyedin** [comment]
And there's only one version of OpenJDK available right now - 1.8.0.9

**Comment by pmahend1** [comment]
Visual studio installer 1.17.1298.831 - Windows. It shows Java development kit 1.8.0.1120.15

**Comment by iglesiasp** [comment]
Links provided should not point to a specific version, but rather to a "...-lastest-stable.zip" and the like (unstable, nightly, whatever -- idk the build/release criteria), OR enable the directory navigation for this site/folder, etc as if it was an old-school FTP.

**Comment by conceptdev** [comment]
This is a preview, and the direct link points to a specific "known-good" download. Once this feature is considered stable, the download mechanism is sure to be more flexible.

The discussion above is confusing the Java version installed by default with the OpenJDK "replacement" which we are previewing. The default Java version will be 8.0.* while the OpenJDK version will be 1.8.*

If you continue to experience problems, please provide additional information including operating system, versions, etc. and ideally submit to the [Developer Community](https://developercommunity.visualstudio.com/) website which is intended for reporting product issues.
