### ISSUE TITLE
Custom Font examples for WPF, macOS and GTK+

### ISSUE THREAD

**Issue by lmcdougald** [MicrosoftDocs/xamarin-docs#793]
Please offer examples for adding custom fonts to WPF, macOS and GTK+ Xamarin.Forms applications.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe0572c4-91be-fc86-d130-242db2bf470b
* Version Independent ID: 1238fdd7-c378-6d0d-654e-55656a70d386
* Content: [Fonts in Xamarin.Forms - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/text/fonts#Using_a_Custom_Font)
* Content Source: [docs/xamarin-forms/user-interface/text/fonts.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/text/fonts.md)
* Product: **xamarin**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by conceptdev** [comment]
@lmcdougald thanks for your feedback. WPF and GTK support is community driven and we do not currently include them in the official documentation or samples. In general, the APIs should work the same across all platforms, however there can be differences especially with things like font names that might be platform specific. You can learn more about the implementation for each platform on the [Xamarin.Forms open source github](https://github.com/xamarin/xamarin.forms).
