### ISSUE TITLE
Please add Customizing a MasterDetailPage to the docs!

### ISSUE THREAD

**Issue by nguyenthanhliemfc** [MicrosoftDocs/xamarin-docs#795]
Thank you for your docs!
I have search on Internet but I can not see any sample about Custom MasterDetaiPage.
Please add Customizing a MasterDetailPage to the docs!
Thank!

---
#### Chi tiết tài liệu

⚠ *Không chỉnh sửa phần này. Điều này là bắt buộc cho docs.microsoft.com ➟ Vấn đề khi liên kết GitHub.*

* ID: c36e7942-65b6-9877-aafd-5f1b1291d37d
* Version Independent ID: 77a599a6-43f2-068f-95ad-0a92ca2b4bca
* Content: [Customizing a ContentPage - Xamarin](https://docs.microsoft.com/vi-vn/xamarin/xamarin-forms/app-fundamentals/custom-renderer/contentpage)
* Content Source: [docs/xamarin-forms/app-fundamentals/custom-renderer/contentpage.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/app-fundamentals/custom-renderer/contentpage.md)
* Product: **xamarin**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @nguyenthanhliemfc 

Thanks for the suggestion. I've added it to our backlog.

**Comment by pmahend1** [comment]
@davidbritch Has it been added to docs?
Couldn't find much details except what native pagerenderer implement them.
