### ISSUE TITLE
There is a typo in Xamarin Forms swipe doc

### ISSUE THREAD

**Issue by jpbrocca** [MicrosoftDocs/xamarin-docs#796]
There is a typo in the "SwipeContainer" section:

**Current text**
`<BoxView olor="Teal" ... />`

**Should say**
`<BoxView Color="Teal" ... />`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 982e8dc1-6510-7c1a-4dbe-71a11187cbd1
* Version Independent ID: 5ffc11cb-1b8a-4f52-9f8e-ec63f1701832
* Content: [Adding a swipe gesture tecognizer - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/gestures/swipe)
* Content Source: [docs/xamarin-forms/app-fundamentals/gestures/swipe.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/app-fundamentals/gestures/swipe.md)
* Product: **xamarin**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @jpbrocca 

Thanks for pointing out the typo! I've fixed it in a PR that should be published later.

**Comment by jpbrocca** [comment]
You are welcome @davidbritch!
Have a nice day.
