### ISSUE TITLE
Binding an AAR - wrong screenshot

### ISSUE THREAD

**Issue by LisandroSu** [MicrosoftDocs/xamarin-docs#797]
@Mikilll94 commented on [Sun Sep 23 2018](https://github.com/MicrosoftDocs/xamarin-docs.pl-pl/issues/1)

There is a mistake on a screen below.

![image](https://user-images.githubusercontent.com/17653648/45930435-95746900-bf60-11e8-86d0-aad917e140ad.png)

As you can see tutorial says to create a new **Binding Library** project. However the screenshot marks **Android App** project.

---
#### Szczegóły dokumentu

⚠ *Nie edytuj tej sekcji. Jest ona wymagana dla docs.microsoft.com ➟ Dołączanie problemu w usłudze GitHub.*

* ID: 53218ae9-ea6c-b958-9a78-e29a831fa630
* Version Independent ID: 7ed2930a-03d2-8a9c-0e62-e109b29acb92
* Content: [Powiązanie. AAR - Xamarin](https://docs.microsoft.com/pl-pl/xamarin/android/platform/binding-java-library/binding-an-aar)
* Content Source: [docs/android/platform/binding-java-library/binding-an-aar.md](https://github.com/MicrosoftDocs/xamarin-docs.pl-PL/blob/live/docs/android/platform/binding-java-library/binding-an-aar.md)
* Product: **xamarin**
* GitHub Login: @mgmclemore
* Microsoft Alias: **mamcle**

**Comment by LisandroSu** [comment]
Hi team,

Please check on this issue.

Thanks!

**Comment by jamesmontemagno** [comment]
@conceptdev, saw this pop up on a stream. Here is a replacement image on VS 2019
![image](https://user-images.githubusercontent.com/1676321/64130028-88691800-cd74-11e9-84d1-54a1c9d94b70.png)

**Comment by conceptdev** [comment]
updated, thanks for letting us know!
