### ISSUE TITLE
Is Bluetooth Function available in Xamarin.Mac

### ISSUE THREAD

**Issue by SkyeYuan** [MicrosoftDocs/xamarin-docs#799]
I created a Xamarin.Mac project with Visual Studio for Mac.
In Entitlements.plist, there is no "Bluetooth" item in "App Sandbox-&gt;Hardware"， I wanna know that is Bluetooth function not available for Xamarin.Mac app?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b1614d24-dfaa-0fff-fcd2-c3c4844164f3
* Version Independent ID: b606b65a-2396-b25e-66d0-d0f099736882
* Content: [Hello, Mac – Walkthrough - Xamarin](https://docs.microsoft.com/en-us/xamarin/mac/get-started/hello-mac)
* Content Source: [docs/mac/get-started/hello-mac.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/mac/get-started/hello-mac.md)
* Product: **xamarin**
* GitHub Login: @bradumbaugh
* Microsoft Alias: **brumbaug**

**Comment by conceptdev** [comment]
Hi @SkyeYuan, you can visit [Developer Community](https://developercommunity.visualstudio.com/) to ask questions about Xamarin.Mac, or else visit the [open-source GitHub repo](https://github.com/xamarin/xamarin-macios/wiki/Submitting-Bugs-&-Suggestions).
