### ISSUE TITLE
What is x:FieldModifier="public"?

### ISSUE THREAD

**Issue by nguyenthanhliemfc** [MicrosoftDocs/xamarin-docs#801]
Thank you for your sample about Xamarin Forms!
Sorry for noob question. What is x:FieldModifier="public"?
Thank you!

---
#### Chi tiết tài liệu

⚠ *Không chỉnh sửa phần này. Điều này là bắt buộc cho docs.microsoft.com ➟ Vấn đề khi liên kết GitHub.*

* ID: ec31ee56-e3b9-a70a-a4ef-80fdf58e7249
* Version Independent ID: 766b5774-50bf-f43f-800d-48b5c6c66509
* Content: [Xamarin.Forms Master-Detail Page - Xamarin](https://docs.microsoft.com/vi-vn/xamarin/xamarin-forms/app-fundamentals/navigation/master-detail-page)
* Content Source: [docs/xamarin-forms/app-fundamentals/navigation/master-detail-page.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/app-fundamentals/navigation/master-detail-page.md)
* Product: **xamarin**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by conceptdev** [comment]
@nguyenthanhliemfc please see the page on [field modifiers](https://docs.microsoft.com/xamarin/xamarin-forms/xaml/field-modifiers).

**Comment by nguyenthanhliemfc** [comment]
Thank you @conceptdev
