### ISSUE TITLE
iOS whitelist for CanOpenAsync

### ISSUE THREAD

**Issue by breyed** [MicrosoftDocs/xamarin-docs#803]
There should be an iOS-specific section that mentions that for `CanOpenAsync` to work on iOS, you need to include the scheme in [LSApplicationQueriesSchemes](https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/LaunchServicesKeys.html#//apple_ref/doc/uid/TP40009250-SW14).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 44b2d5f7-bcc1-4561-247e-b3a314738311
* Version Independent ID: 779a0484-4dea-f385-3c5c-708cb8860848
* Content: [Xamarin.Essentials Launcher - Xamarin](https://docs.microsoft.com/en-us/xamarin/essentials/launcher?context=xamarin/xamarin-forms)
* Content Source: [docs/essentials/launcher.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/essentials/launcher.md)
* Product: **xamarin**
* GitHub Login: @jamesmontemagno
* Microsoft Alias: **jamont**

**Comment by jamesmontemagno** [comment]
I think this is more of a bug and implementation detail. Can we open a bug on the essentials repo.

**Comment by breyed** [comment]
I'm not aware of any bug. My point was just to document the need to declare the schemes, since otherwise, the user would get unexpected errors.

**Comment by jamesmontemagno** [comment]
Yeah, I am reading through it now and looks like we can add links to this doc from Apple: https://developer.apple.com/documentation/uikit/uiapplication/1622952-canopenurl

**Comment by conceptdev** [comment]
This doc has been updated according to the suggestions above - thanks everyone.
