### ISSUE TITLE
Document when CanOpenAsync completes immediately

### ISSUE THREAD

**Issue by breyed** [MicrosoftDocs/xamarin-docs#804]
On iOS and Android the async task for CanOpenAsync always completes immediately. The only reason the method isn't just `CanOpen` is because for whatever undocumented reason, the underlying call in UWP is async. For apps that don't care about UWP for purposes of calling `CanOpenAsync`, it can simplify their design to not have figure out what user experience to present while "waiting" to see if a URI can be opened. Documenting the platform-specific completion behavior would help in this regard.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 44b2d5f7-bcc1-4561-247e-b3a314738311
* Version Independent ID: 779a0484-4dea-f385-3c5c-708cb8860848
* Content: [Xamarin.Essentials Launcher - Xamarin](https://docs.microsoft.com/en-us/xamarin/essentials/launcher?context=xamarin/xamarin-forms)
* Content Source: [docs/essentials/launcher.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/essentials/launcher.md)
* Product: **xamarin**
* GitHub Login: @jamesmontemagno
* Microsoft Alias: **jamont**

**Comment by jamesmontemagno** [comment]
This is by design due to how we implement our APIs. If one needs async then we mark it as async. Thanks for the suggestion though.

**Comment by breyed** [comment]
The design makes sense. If any one of the platforms requires async, then that bubbles up to the x-plat abstraction.

My point is that it's useful for the platform specifics to leak through the abstraction - but just in the documentation. That way, devs who only need platforms that provide immediate results don't have to deal with the added complexity of a delay while waiting for an answer.

For example, I was using CanOpenAsync in iOS-specific code, so I knew I could safely use the `Result` property without first awaiting. Likewise, I knew I didn't have to provide feedback to the user while awaiting, since there was nothing to wait for. However, I had to look at the CanOpenAsync source to know that it provided a result immediately. That's why I suggested documenting the behavior for the various platforms.

**Comment by jamesmontemagno** [comment]
Ahhhhhhhhhh I see what you are saying here. Can you make this a Feature Request or do the PR on the Xamarin.Essentials repo.

**Comment by breyed** [comment]
I don't think the Xamarin.Essentials needs to change. The only change I am suggesting is that the docs should state that for the iOS and Android (and other?) platforms, the async task completes immediately. It's a performance guaranty, like documenting that indexing into `List<T>` is an O(1) operation; only in this case, it's guaranteeing that there is no async "down time" before the task completes on certain platforms. If I understand correctly, that documentation would go here in xamarin-docs, not in the main Xamarin.Essentials repo.

**Comment by conceptdev** [comment]
This page was updated with suggestions from the thread above. Thanks everyone.
