### ISSUE TITLE
Documentation needs fixed

### ISSUE THREAD

**Issue by warwlf** [MicrosoftDocs/xamarin-docs#805]
Drop 
object sender,
from the docs... it's wrong.
Thanks.

void OrientationSensor_ReadingChanged(object sender, OrientationSensorChangedEventArgs e)
   
  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ffb3c390-fe71-9f05-ce4f-938745f698df
* Version Independent ID: a258e102-f689-7ba2-c509-e47b47b6f623
* Content: [Xamarin.Essentials: OrientationSensor - Xamarin](https://docs.microsoft.com/en-us/xamarin/essentials/orientation-sensor?context=xamarin/xamarin-forms)
* Content Source: [docs/essentials/orientation-sensor.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/essentials/orientation-sensor.md)
* Product: **xamarin**
* GitHub Login: @charlespetzold
* Microsoft Alias: **chape**

**Comment by LanceMcCarthy** [comment]
@warwlf Can you explain further on what needs to be changed? The event is invoked with a sender and an instance of the event args. https://github.com/xamarin/Essentials/blob/89c55374934de12da9404802f7eb202cfff884d1/Xamarin.Essentials/OrientationSensor/OrientationSensor.shared.cs#L62-L65

**Comment by warwlf** [comment]
I guess nothing... it builds today finally after VS saying I needed to add a reference to assembly containing Quaternion. Weird... sorry for the bother.


________________________________

**Comment by LanceMcCarthy** [comment]
I'm happy to see you're up and running!  Side note: Submitting an issue is never a bother! Here's why:

- Best case scenario, nothing is wrong and everything works.
- Worst case scenario: the docs needed a fix and you helped everyone, win-win!

**Comment by warwlf** [comment]
Great!  Thanks you!

Sent from my iPhone

On Oct 2, 2018, at 3:50 PM, Lance McCarthy <notifications@github.com<mailto:notifications@github.com>> wrote:


I'm happy to see you're up and running! Side note: Submitting an issue is never a bother! Here's why:

  *   Best case scenario, nothing is wrong and everything works.
  *   Worst case scenario: the docs needed a fix and you helped everyone, win-win!
