### ISSUE TITLE
No RaisePropertyChange trigered

### ISSUE THREAD

**Issue by aliegeni** [MicrosoftDocs/xamarin-docs#806]
Property change on derived class never occured, becouse ValidatableObject has its own inner T type 'Value' property
public ValidatableObject&lt;string&gt; UserName  
{  
    get  
    {  
        return _userName;  
    }  
    set  
    {  
        _userName = value;  
        RaisePropertyChanged(() =&gt; UserName);  // this is not triggered
    }  
}  
RaisePropertyChange indeed occure in ValidatableObject base class but i need to do some logic when UserName.Value changed in my ModeView class not in ValidatableObject base class.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b7433934-d5da-72be-7f79-f1f33259cf44
* Version Independent ID: 022fbc39-4a57-7ed7-91e4-463086e9a401
* Content: [Validation in Enterprise Apps - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/enterprise-application-patterns/validation)
* Content Source: [docs/xamarin-forms/enterprise-application-patterns/validation.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/enterprise-application-patterns/validation.md)
* Product: **xamarin**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @aliegeni 

Thanks for reporting this - you're right.

As this is primarily a coding/architecture issue, I've moved this issue to the [eShopOnContainers](https://github.com/dotnet-architecture/eShopOnContainers/issues/793) repo.
