### ISSUE TITLE
Link broken in note section

### ISSUE THREAD

**Issue by wegascee** [MicrosoftDocs/xamarin-docs#809]
In the note section the link is broken:

> It is possible to detect whether the device is in portrait or landscape orientation in shared code, as demonstrated in [Device Orientation]/guides/xamarin-forms/user-interface/layouts/device-orientation/#changes-in-orientation). The method described in this article uses native features to get more information about orientation, including whether the device is upside down.

I believe this should link to:
https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/layouts/device-orientation?tabs=vswin#reacting-to-changes-in-orientation
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 54b9e0c6-7539-cbe0-81a3-0342f1fe9907
* Version Independent ID: 742a82e9-8cdc-4df7-5f41-5c37d1311556
* Content: [Checking Device Orientation - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/dependency-service/device-orientation)
* Content Source: [docs/xamarin-forms/app-fundamentals/dependency-service/device-orientation.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/app-fundamentals/dependency-service/device-orientation.md)
* Product: **xamarin**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @wegascee 

Thanks for reporting this. I've fixed it in a PR that should go live within a few days.
