### ISSUE TITLE
Great Video!

### ISSUE THREAD

**Issue by delaney31** [MicrosoftDocs/xamarin-docs#810]
This is a great video. I finally understand the need to move from PCL to .Net Standard. One question.. I want to my move my existing PCL to .Net Standard 2.0 but its only allowing me to target 1.5? Why?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 483b01c5-75b5-a35b-c90c-c564535416f1
* Version Independent ID: dc8b1e89-e8f9-0e50-5d4d-248ccdab9c91
* Content: [Use .NET Standard Libraries to Share Code - Xamarin](https://docs.microsoft.com/en-us/xamarin/cross-platform/app-fundamentals/net-standard?tabs=macos)
* Content Source: [docs/cross-platform/app-fundamentals/net-standard.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/cross-platform/app-fundamentals/net-standard.md)
* Product: **xamarin**
* GitHub Login: @conceptdev
* Microsoft Alias: **crdun**

**Comment by davidbritch** [comment]
Hi @delaney31 

My guess is that .NET Standard 1.5 is the latest release of have installed of .NET Standard. Check your system is up to date. Failing that, try editing your .csproj manually to make it a .NET Standard 2.0 project, and see if it builds.
