### ISSUE TITLE
CornerRadius exists without custom theme or effects settings.

### ISSUE THREAD

**Issue by nhwilly** [MicrosoftDocs/xamarin-docs#812]
I think this information is a little out of date with respect to `CornerRadius`, although I only tested it with UWP.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f28d1a17-189a-7791-b44b-b84e94d8f7b6
* Version Independent ID: 3ad8e76d-eaa6-18f9-c121-9cf4c2c1720f
* Content: [Creating a Custom Xamarin.Forms Theme - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/themes/custom)
* Content Source: [docs/xamarin-forms/user-interface/themes/custom.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/themes/custom.md)
* Product: **xamarin**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @nhwilly 

Thanks for reporting this. Unfortunately Themes has never moved from a pre-release to a final release, and the doc is based on the pre-release code. As the doc reflects the only Themes release that's out there, there are no plans to update it.

**Comment by nhwilly** [comment]
@davidbritch I didn't really express myself very clearly.  What I wanted to say was that `CornerRadius` has replaced `BorderRadius` in the standard package and doesn't require all the extra code.

But so that I am totally clear on this, I should just disregard everything in the `themes` subsection, correct?

![untitled](https://user-images.githubusercontent.com/7560842/46347162-92404380-c618-11e8-8db2-170768863c08.png)
