### ISSUE TITLE
Debugging Embedded Resources - causes App abort

### ISSUE THREAD

**Issue by BrayanKhosravian** [MicrosoftDocs/xamarin-docs#813]
i notices a strange behaviour when calling the method from:
 System.Reflection.Assembly assembly = IntrospectionExtensions.GetTypeInfo(typeof(App)).Assembly;
var resourceList = assembly.GetManifestResourceNames();

this method is located in the overriden OnStart method of the App class.
1.) when i debug the application from a emulator everything works just fine. and "assembly" is of type "System.Reflection.MonoAssembly".

2.) when i debug via the xamarin live app the app aborts without throwning a exception and the type of "assembly" is "NInterpret.InterpretedClrAssembly".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8fb68890-cda3-6b2a-deba-55a171963da5
* Version Independent ID: 675d1663-d7ea-3e47-dbdd-772944acce5a
* Content: [File Handling in Xamarin.Forms - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/files?tabs=vswin#related-links)
* Content Source: [docs/xamarin-forms/app-fundamentals/files.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/app-fundamentals/files.md)
* Product: **xamarin**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by BrayanKhosravian** [comment]
I have also noticed that the assembly version is version "0.0.0.0" when using the camarin live app and when using the emulator the assembly version is "1.0.0.0".
i ave never changed the version.

**Comment by BrayanKhosravian** [comment]
this can be closed. i found the reason here: https://docs.microsoft.com/en-us/xamarin/tools/live-player/limitations
-> The Xamarin life player does not support embeded resources
the team could maybe add this to the repo. this would save some troubleshooting time.

im still bit curiouse if only embeded resources are not available or if reflection in general is unavailable, because of the return types of "assembly".

**Comment by davidbritch** [comment]
Hi @BrayanKhosravian 

As you've identified, embedded resources aren't supported in Live Player. In addition, there's only limited support for reflection in Live Player. Live Player runs app in a sandboxed environment, and is only really designed for people getting started with Xamarin.Forms. It's really recommended that you use an emulator/device during app development.
