### ISSUE TITLE
Themes examples

### ISSUE THREAD

**Issue by joshk6** [MicrosoftDocs/xamarin-docs#814]
I like the idea of themes, but it would be helpful to provide more than 2 possible themes, so people who are looking to do quick and dirty apps could pick a suitable theme and have it look OK without a lot of twiddling.  Right now the choices are quite thin.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f28d1a17-189a-7791-b44b-b84e94d8f7b6
* Version Independent ID: 3ad8e76d-eaa6-18f9-c121-9cf4c2c1720f
* Content: [Creating a Custom Xamarin.Forms Theme - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/themes/custom)
* Content Source: [docs/xamarin-forms/user-interface/themes/custom.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/themes/custom.md)
* Product: **xamarin**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @joshk6 

Thanks for the suggestion. Ideally that suggestion should be made in the Xamarin.Forms [engineering](https://github.com/xamarin/Xamarin.Forms) repo. This repo is just for issues with docs.

Thanks!
