### ISSUE TITLE
Data Binding

### ISSUE THREAD

**Issue by ttirrell** [MicrosoftDocs/xamarin-docs#818]
I've been using data binding with the Settings Plugin.  Would I use a similar setup or is there a better way?

https://jamesmontemagno.github.io/SettingsPlugin/DataBindingToSettings.html#approach-2-more-magical-way

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a7a399b1-a8a2-9cbd-c479-1bd98af46988
* Version Independent ID: 91a6ae06-508b-b668-52aa-cbdeabb2b46a
* Content: [Xamarin.Essentials: Preferences - Xamarin](https://docs.microsoft.com/en-us/xamarin/essentials/preferences?tabs=android)
* Content Source: [docs/essentials/preferences.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/essentials/preferences.md)
* Product: **xamarin**
* GitHub Login: @jamesmontemagno
* Microsoft Alias: **jamont**

**Comment by jamesmontemagno** [comment]
Yup! The same code basically would work for you here.

**Comment by LanceMcCarthy** [comment]
@jamesmontemagno I submitted a PR to add a simple snippet to clarify  https://github.com/MicrosoftDocs/xamarin-docs/pull/824

**Comment by jamesmontemagno** [comment]
Based on feedback from #824 I have created a Wiki entry for this: https://github.com/xamarin/Essentials/wiki/FAQ-%7C-Preferences as it is outside of the docs scope to document use of the core API.
