### ISSUE TITLE
What about when there are no tabs to display?

### ISSUE THREAD

**Issue by nvmkpk** [MicrosoftDocs/xamarin-docs#82]
Can I show a custom text saying there is nothing to display?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0c81c589-e81e-d98c-9656-695a3520a12d
* Version Independent ID: c235f6f9-47ce-15f3-b4da-cb12e219df92
* Content: [Tabbed Page - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/navigation/tabbed-page)
* Content Source: [docs/xamarin-forms/app-fundamentals/navigation/tabbed-page.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/app-fundamentals/navigation/tabbed-page.md)
* Service: **unspecified**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by conceptdev** [comment]
This is not a feature of the TabbedPage control.

**Comment by nvmkpk** [comment]
Do you mean we cannot add text without adding a page?

**Comment by conceptdev** [comment]
Correct - the each tab represents a page. The TabbedPage is intended for navigation use, not for 'document tabs' as you might think of in a desktop app. The functionality is limited to what's described in the docs.

This list is for documentation feedback; please see this page for customer support options: https://www.visualstudio.com/vs/support/

**Comment by nvmkpk** [comment]
Thanks for the clarification. No, I am not trying to use it for document tabs but I have a need for using variable no of tabs. I will look for other options to render my content.
