### ISSUE TITLE
.lproj directories

### ISSUE THREAD

**Issue by shaiGalooli** [MicrosoftDocs/xamarin-docs#821]
When following this tutorial i created a folder named Base.Iproj instead of Base.lproj..
Confused? so was I.. I would suggest emphasizing that "lproj" = "Lproj" in lower case.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 629ae54b-10fe-61ff-6a6e-cb54b5206079
* Version Independent ID: fcb311ea-1552-86e4-d648-5fe7832d863a
* Content: [Localization in Xamarin.iOS - Xamarin](https://docs.microsoft.com/en-us/xamarin/ios/app-fundamentals/localization/index)
* Content Source: [docs/ios/app-fundamentals/localization/index.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/ios/app-fundamentals/localization/index.md)
* Product: **xamarin**
* GitHub Login: @lobrien
* Microsoft Alias: **laobri**

**Comment by conceptdev** [comment]
Thanks @shaiGalooli, I have added a hint as you suggested. It will be published soon.
