### ISSUE TITLE
File Name Changed

### ISSUE THREAD

**Issue by alarimer** [MicrosoftDocs/xamarin-docs#822]
At some undocumented point "activity_main.axml" was renamed to "Main.axml" between parts one and two of the tutorial. :/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ba4ac72b-0c09-80b8-7210-c77f1d2a6f42
* Version Independent ID: f39106cc-ec1f-55ea-002a-8928e742b551
* Content: [Hello, Android: Deep Dive - Xamarin](https://docs.microsoft.com/en-us/xamarin/android/get-started/hello-android/hello-android-deepdive?tabs=vswin)
* Content Source: [docs/android/get-started/hello-android/hello-android-deepdive.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/android/get-started/hello-android/hello-android-deepdive.md)
* Product: **xamarin**
* GitHub Login: @conceptdev
* Microsoft Alias: **crdun**

**Comment by conceptdev** [comment]
Thanks @alarimer it looks like the Windows part of the tutorial is referring to an old version/template. The online sample code [on GitHub](https://github.com/xamarin/monodroid-samples/tree/master/Phoneword/Phoneword/Resources/layout) looks correct -- we'll schedule an update to fix the doc too!

**Comment by conceptdev** [comment]
So... it turns out the **File > New** template is different on Mac and Windows! I've updated the docs to reflect the correct name (depending on which platform you've selected), and separately let the team know, since these should probably match.

Thanks again for pointing out the inconsistency.

**Comment by alarimer** [comment]
The name now changes in the middle of Part 1 between the "Create a layout" and "Wire up the user interface" sections.  The inconsistency exists in the code examples of the "On Create" subsection in the "Activities and the Activity Lifecyle" section.  The controls (Views) change to full-width and the background changes from white to dark between Part 1 and Part 2.

I appreciate the difficulties in maintaining accurate and clean documentation.  Thanks.
