### ISSUE TITLE
Viewmodel inheritence discussion

### ISSUE THREAD

**Issue by jraldrin** [MicrosoftDocs/xamarin-docs#826]
Hi,
I think it would be helpful to mention if data binding works with view model inheritance. If vm inheritance is supported a reference to an example would be nice.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ed970855-6db1-6838-12cf-5a6f58b8ebf4
* Version Independent ID: edfe1b4d-58d2-477d-89b2-2641789cf2db
* Content: [Part 5. From Data Bindings to MVVM - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/xaml/xaml-basics/data-bindings-to-mvvm)
* Content Source: [docs/xamarin-forms/xaml/xaml-basics/data-bindings-to-mvvm.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/xaml/xaml-basics/data-bindings-to-mvvm.md)
* Product: **xamarin**
* GitHub Login: @charlespetzold
* Microsoft Alias: **chape**

**Comment by davidbritch** [comment]
Hi @jraldrin 

Data binding does work with view model inheritance.

I'll create an issue in our backlog to mention this. Thanks for mentioning it.
