### ISSUE TITLE
Is this package still being maintained?

### ISSUE THREAD

**Issue by JeroMiya** [MicrosoftDocs/xamarin-docs#827]
Latest release on NuGet for the theme packages are quite old and depend on an old preview version of Xamarin.Forms. Are these libraries being maintained? Were they replaced with something else?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e53c4b90-c722-c5e7-cdd9-bbafe9ffda53
* Version Independent ID: 9a34a63b-82c9-bf48-fd36-f47bff300a6c
* Content: [Xamarin.Forms Dark Theme - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/themes/dark)
* Content Source: [docs/xamarin-forms/user-interface/themes/dark.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/themes/dark.md)
* Product: **xamarin**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by conceptdev** [comment]
DataPages and Themes are still considered to be in Preview. Visit the [Xamarin.Forms open source repo](https://github.com/xamarin/Xamarin.Forms) for information on the project backlog.

Consider the new CSS functionality added in Xamarin.Forms 3.0.
