### ISSUE TITLE
Xamarin Inspector Docs Incomplete

### ISSUE THREAD

**Issue by Valance23322** [MicrosoftDocs/xamarin-docs#829]
This document is incomplete, lacking any meaningful information on how to install or use the feature.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 380aa443-44a4-3d2f-4354-a3b5be3585ed
* Version Independent ID: abeed00d-c782-ee71-739f-53ff16a7b5ba
* Content: [Xamarin Inspector - Xamarin](https://docs.microsoft.com/en-us/xamarin/tools/inspector/index)
* Content Source: [docs/tools/inspector/index.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/tools/inspector/index.md)
* Product: **xamarin**
* GitHub Login: @lobrien
* Microsoft Alias: **laobri**

**Comment by conceptdev** [comment]
@Valance23322 thanks for your feedback. If you have any questions about the Inspector, I would encourage you to visit the [forum](https://forums.xamarin.com/categories/inspector).
