### ISSUE TITLE
Update?

### ISSUE THREAD

**Issue by warthenr** [MicrosoftDocs/xamarin-docs#830]
Is there any update on this?  I don't see the Xcode 10 channel anymore.  Does that mean it's in the Beta or Alpha?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8d2cc0ff-a223-c1da-fc07-1a0f394c465c
* Version Independent ID: 120713f7-69de-afd6-65d2-1546e414cc53
* Content: [Introduction to macOS Mojave - Xamarin](https://docs.microsoft.com/en-us/xamarin/mac/platform/introduction-to-macos-mojave/)
* Content Source: [docs/mac/platform/introduction-to-macos-mojave/index.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/mac/platform/introduction-to-macos-mojave/index.md)
* Product: **xamarin**
* GitHub Login: @lobrien
* Microsoft Alias: **laobri**

**Comment by conceptdev** [comment]
@warthenr yes, the mac support shipped in the latest Stable release (earlier this week). Looks like we missed a doc update, but will take care of that ASAP. Thanks for letting us know!
