### ISSUE TITLE
Absence of PhoneCallManager at Windows Mobile Extension for the UWP ver 10.0.17134.0

### ISSUE THREAD

**Issue by soejdtodxn** [MicrosoftDocs/xamarin-docs#831]
[Enter feedback here]

When i add reference "Windows Mobile Extensions for the UWP" ver 10.0.17134.0
accordance with the document for run example code
PhoneCallManager class (also PhoneLine class) was absence.

i think need to change reference version on document or example code properly.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2de3e72c-8948-4dd5-e37f-9cf81e62c127
* Version Independent ID: 7b7c5c7f-4102-8e91-fbe6-7d21fcc8f5be
* Content: [Xamarin.Forms Quickstart - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/get-started/hello-xamarin-forms/quickstart?tabs=vswin)
* Content Source: [docs/xamarin-forms/get-started/hello-xamarin-forms/quickstart.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/get-started/hello-xamarin-forms/quickstart.md)
* Product: **xamarin**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by cobaltsoftware** [comment]
Were you using the updated version of VS 2017?

**Comment by davidbritch** [comment]
The instructions/sample is working perfectly for me using 10.0.17134.0. I recommend trying the [sample](https://developer.xamarin.com/samples/xamarin-forms/Phoneword/), and if that fails it's most likely that your system isn't up to date.
