### ISSUE TITLE
UWP Async Issue

### ISSUE THREAD

**Issue by cobaltsoftware** [MicrosoftDocs/xamarin-docs#832]
In the UWP portion of the Demo, in the PhoneDialer class, the DialNumber (line 21) is an asynchronous Task. This has the potential to cause issues in functionality fr the application as a whole. 

The actual Warning reads: "Because this call is not awaited, execution of the current method continues before the call is completed. Consider applying the 'await' operator to the result of the call". If that is done, the IDialer interface is no longer implemented as defined. Changing the interface then cascades down to the Android, and iPhone implementations as well.  

Given that the Windows Phone has been deprecated as a product line (unless MS is considering the integration of Skype into the remaining W10-based products, there may need to be a workaround to remove the warning, and increase the efficiency of the demo at the same time

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2de3e72c-8948-4dd5-e37f-9cf81e62c127
* Version Independent ID: 7b7c5c7f-4102-8e91-fbe6-7d21fcc8f5be
* Content: [Xamarin.Forms Quickstart - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/get-started/hello-xamarin-forms/quickstart?pivots=windows)
* Content Source: [docs/xamarin-forms/get-started/hello-xamarin-forms/quickstart.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/get-started/hello-xamarin-forms/quickstart.md)
* Product: **xamarin**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by conceptdev** [comment]
@cobaltsoftware thanks for the suggestion - we'll take a look at the code.
