### ISSUE TITLE
Why isn't this documentation isn't in the Requirements, get started or some place more obvious.

### ISSUE THREAD

**Issue by mxplante** [MicrosoftDocs/xamarin-docs#833]
I'm surprised to realize how little the emphasis in the doc is put on how important it is to understand how all these concepts and such work with the platform. I have a hard time understanding why it's buried in the doc in the "Advanced" concepts, or architecture.
 
I get that, a part of the doc is to onboard people and understand how the big lines works. But still, when you get serious about using Xamarin, I feel there should be something that mentions how important those are, especially if mobile dev is new to you.)

Is there any way we can improve this ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2553ca72-7627-eb9b-e5f6-51c84fd7c4b9
* Version Independent ID: 50cd62a7-83f5-73f0-409a-57135a5e5704
* Content: [Cross-Platform Performance - Xamarin](https://docs.microsoft.com/en-us/xamarin/cross-platform/deploy-test/memory-perf-best-practices)
* Content Source: [docs/cross-platform/deploy-test/memory-perf-best-practices.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/cross-platform/deploy-test/memory-perf-best-practices.md)
* Product: **xamarin**
* GitHub Login: @asb3993
* Microsoft Alias: **amburns**

**Comment by conceptdev** [comment]
@mxplante the intention is not for this content to be buried in an _Advanced_ section - it is surfaced in the Deployment and Testing sections for each Xamarin platform, and we try hard to SEO such that people can find it easily if they search for "xamarin performance". 

Having said that, we are always looking for ways to improve. We'll see what we can do to improve the discoverability of this information. Thanks for the suggestion.
