### ISSUE TITLE
doesn't make sense.

### ISSUE THREAD

**Issue by kalexanderman** [MicrosoftDocs/xamarin-docs#835]
should not MainPage in the line MessagingCenter.Subscribe&lt;MainPage,...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4d80a771-2198-328b-b9fa-fe25f16261cd
* Version Independent ID: be0408fe-d00b-baf6-8a9c-e24659029c4b
* Content: [Xamarin.Forms MessagingCenter - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/messaging-center)
* Content Source: [docs/xamarin-forms/app-fundamentals/messaging-center.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/app-fundamentals/messaging-center.md)
* Product: **xamarin**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by conceptdev** [comment]
@kalexanderman can you explain your question further?

**Comment by kalexanderman** [comment]
It's ok, I would have preferred to delete the comment entirely.

Regards,
Kevin

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by conceptdev** [comment]
Thanks for letting me know.
