### ISSUE TITLE
AIDL content

### ISSUE THREAD

**Issue by PingPongSet** [MicrosoftDocs/xamarin-docs#836]
Please provide information and example code on using AIDL. 

Please elaborate on this
"This strikes terror into the heart of most Android developers, and will not be covered in this guide."

Please provide pros and cons of various services (e.g. Messenger vs AIDL vs Content Providers)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ed0a6ecd-980c-c2dd-433b-ab3c5f7f467c
* Version Independent ID: 458fb06e-8a5e-adc1-a75d-03b04180fe9f
* Content: [Bound Services in Xamarin.Android - Xamarin](https://docs.microsoft.com/en-us/xamarin/android/app-fundamentals/services/creating-a-service/bound-services)
* Content Source: [docs/android/app-fundamentals/services/creating-a-service/bound-services.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/android/app-fundamentals/services/creating-a-service/bound-services.md)
* Product: **xamarin**
* GitHub Login: @conceptdev
* Microsoft Alias: **crdun**

**Comment by conceptdev** [comment]
@PingPongSet thanks for your feedback. I've updated the page to include a link to Google's AIDL docs, which discuss some reasons to use one over the other.
