### ISSUE TITLE
Downloadable Example code for running IntentService as either foreground or background

### ISSUE THREAD

**Issue by PingPongSet** [MicrosoftDocs/xamarin-docs#837]
Please provide downloadable example code for running IntentService as either foreground or background.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d28665cc-a195-5da8-4d78-1b77611307c2
* Version Independent ID: 4718bda8-aae3-dcef-d3bc-930ac987b2f0
* Content: [Intent Services in Xamarin.Android - Xamarin](https://docs.microsoft.com/en-us/xamarin/android/app-fundamentals/services/creating-a-service/intent-services)
* Content Source: [docs/android/app-fundamentals/services/creating-a-service/intent-services.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/android/app-fundamentals/services/creating-a-service/intent-services.md)
* Product: **xamarin**
* GitHub Login: @conceptdev
* Microsoft Alias: **crdun**

**Comment by conceptdev** [comment]
There is are a number of service demos [on github](https://github.com/xamarin/monodroid-samples/tree/master/ApplicationFundamentals/ServiceSamples) including [bound service demo](https://developer.xamarin.com/samples/monodroid/ApplicationFundamentals/ServiceSamples/BoundServiceDemo/) and a [started service demo](https://developer.xamarin.com/samples/monodroid/ApplicationFundamentals/ServiceSamples/StartedServicesDemo/). We have additional samples in progress at this time, but we value your suggestions as we plan future work.

**Comment by kkarakk** [comment]
@PingPongSet IntentServices always run on backgroundthread, if you run them as foreground it's the same as having a running service with an asynctask/separate thread.
