### ISSUE TITLE
ForegroundServiceDemo (sample)

### ISSUE THREAD

**Issue by PingPongSet** [MicrosoftDocs/xamarin-docs#838]
The example code in ForegroundServiceDemo (sample) is a bit overcomplicated. Is it possible to provide a Hello world example?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 14dfecf6-b596-61af-ef6c-c0b65838bd45
* Version Independent ID: 7e1e4994-270d-5383-7d2d-f6d1cd1e1992
* Content: [Foreground Services - Xamarin](https://docs.microsoft.com/en-us/xamarin/android/app-fundamentals/services/foreground-services)
* Content Source: [docs/android/app-fundamentals/services/foreground-services.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/android/app-fundamentals/services/foreground-services.md)
* Product: **xamarin**
* GitHub Login: @conceptdev
* Microsoft Alias: **crdun**

**Comment by conceptdev** [comment]
Thanks for the suggestion @PingPongSet. Generally we try to keep the samples as simple as possible, while still providing a good basis for real apps.

**Comment by pmuchars** [comment]
ForegroundServceDemo is not working on Android 9.0 - can you update this demo to work with current android version? Adding permission "foreground_service" doesn't solve the problem.
