### ISSUE TITLE
Please explain how to override existing renderer

### ISSUE THREAD

**Issue by weitzhandler** [MicrosoftDocs/xamarin-docs#84]
For example, I only want to provide the UWP renderer due to a bug.
I tried 
```c#
[assembly: ExportRenderer(typeof(Frame), typeof(FixedFrameRenderer))]
namespace Xamarin.Forms.Platform.UWP
{       
  public class FixedFrameRenderer : FrameRenderer { /*...*/ }
}
```

But it didn't seem to have any effect. So is the only solution to pollute my entire project with a custom control in all platforms?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b708ef67-2a65-558b-7dc9-5df5a222dfd4
* Version Independent ID: df2f7e71-aa4b-dbb6-1d54-4f9b75ad8177
* Content: [Customizing an Entry - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/custom-renderer/entry)
* Content Source: [docs/xamarin-forms/app-fundamentals/custom-renderer/entry.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/app-fundamentals/custom-renderer/entry.md)
* Service: **unspecified**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by conceptdev** [comment]
Hi @weitzhandler, unfortunately we cannot respond to individual help requests via this site. There are a number of custom renderer docs available that attempt to address the many different aspects of this feature.

If you have found a bug, please report it at https://developercommunity.visualstudio.com/, or if you prefer at the open-source repository for Xamarin.Forms: https://github.com/xamarin/xamarin.forms

You can find information on the available support options here: https://www.visualstudio.com/vs/support/
