### ISSUE TITLE
IServiceConnection implemenation and Java.Lang.Object

### ISSUE THREAD

**Issue by PingPongSet** [MicrosoftDocs/xamarin-docs#842]
Can anyone explain why extending Java.Lang.Object is required?
" In addition to implementing the IServiceConnection interface, the class must extend Java.Lang.Object."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ed0a6ecd-980c-c2dd-433b-ab3c5f7f467c
* Version Independent ID: 458fb06e-8a5e-adc1-a75d-03b04180fe9f
* Content: [Bound Services in Xamarin.Android - Xamarin](https://docs.microsoft.com/en-us/xamarin/android/app-fundamentals/services/creating-a-service/bound-services)
* Content Source: [docs/android/app-fundamentals/services/creating-a-service/bound-services.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/android/app-fundamentals/services/creating-a-service/bound-services.md)
* Product: **xamarin**
* GitHub Login: @conceptdev
* Microsoft Alias: **crdun**

**Comment by JonDouglas** [comment]
@PingPongSet To implement Android interfaces, one must inherit from `Java.Lang.Object` so the Xamarin.Android build process can generate an [Android Callable Wrapper](https://docs.microsoft.com/en-us/xamarin/android/platform/java-integration/android-callable-wrappers).

You can read more about this [here](https://docs.microsoft.com/en-us/xamarin/android/platform/java-integration/android-callable-wrappers#implementing-interfaces).

**Comment by davehump** [comment]
Closing as Bound services is an advanced subject and typical users at this level would would understand the need to inherit from Java.Lang.Object
