### ISSUE TITLE
Missing C# examples

### ISSUE THREAD

**Issue by spaddlewit** [MicrosoftDocs/xamarin-docs#85]
You have XAML code for ListView groups, but no sample C# code.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7c0643eb-b23e-9283-39eb-6fb0b97a1b83
* Version Independent ID: c1f024de-3443-d7a2-7c0a-1d78d619aea4
* Content: [List Appearance - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/listview/customizing-list-appearance#Grouping)
* Content Source: [docs/xamarin-forms/user-interface/listview/customizing-list-appearance.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/listview/customizing-list-appearance.md)
* Service: **unspecified**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
The linked sample (https://developer.xamarin.com/samples/xamarin-forms/UserInterface/ListView/Grouping/) from this page has the C# code.
