### ISSUE TITLE
"Application Launcher" typo

### ISSUE THREAD

**Issue by Romans-I-XVI** [MicrosoftDocs/xamarin-docs#856]
This is super minor but under the "Build and submit your app" section, step 6 says to open "Application Launcher" this is repeated later in the sentence and in step 7. This should be "Application Loader".

It's super small, but being completely new to iOS I'll admit I was looking for "Application Launcher" for a bit ;)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bb327a64-010d-dba8-5ebc-546892d739af
* Version Independent ID: 48a24297-7b8f-b1b2-7b25-44f40fe33eac
* Content: [Publishing Xamarin.iOS apps to the App Store - Xamarin](https://docs.microsoft.com/en-us/xamarin/ios/deploy-test/app-distribution/app-store-distribution/publishing-to-the-app-store?tabs=vswin)
* Content Source: [docs/ios/deploy-test/app-distribution/app-store-distribution/publishing-to-the-app-store.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/ios/deploy-test/app-distribution/app-store-distribution/publishing-to-the-app-store.md)
* Product: **xamarin**
* GitHub Login: @lobrien
* Microsoft Alias: **laobri**

**Comment by conceptdev** [comment]
@james-alt kindly updated the text, thanks both for the suggestion and the fix.
