### ISSUE TITLE
Xamarin Studio?

### ISSUE THREAD

**Issue by pmahend1** [MicrosoftDocs/xamarin-docs#860]
Its Visual studio now, there is no Xamarin Studio folder now a days. and Microsoft Visual Studio 12.0?  We are in 15 now, arent we?

You guys need to update this documentation. This is misleading and outdated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bf73df52-2914-95a9-f0e6-58a3626a744d
* Version Independent ID: 0fb93b93-a2d6-35ad-685c-58492d9a679d
* Content: [How do I enable Intellisense in Android .axml files? - Xamarin](https://docs.microsoft.com/en-us/xamarin/android/troubleshooting/questions/enable-axml-intellisense)
* Content Source: [docs/android/troubleshooting/questions/enable-axml-intellisense.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/android/troubleshooting/questions/enable-axml-intellisense.md)
* Product: **xamarin**
* GitHub Login: @conceptdev
* Microsoft Alias: **crdun**

**Comment by conceptdev** [comment]
Thanks for your feedback. This step is not required for Visual Studio 2017, we're removing the page.
