### ISSUE TITLE
Native Views feature throw error when use native splitview wrap forms'control

### ISSUE THREAD

**Issue by jingliancui** [MicrosoftDocs/xamarin-docs#863]
Detail at GitHub issue here:
https://github.com/xamarin/Xamarin.Forms/issues/4050

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a781e5d5-c0c4-4bc0-2049-97442139bee3
* Version Independent ID: 94e2df3f-c624-98d8-2edb-ef98134835b9
* Content: [Native Views in XAML - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/platform/native-views/xaml)
* Content Source: [docs/xamarin-forms/platform/native-views/xaml.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/platform/native-views/xaml.md)
* Product: **xamarin**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by conceptdev** [comment]
Thanks for raising the issue. Once engineering has resolved that, we'll make any updates required to the docs.
