### ISSUE TITLE
Feature name Microsoft-Hyper-V is unknown.

### ISSUE THREAD

**Issue by pmahend1** [MicrosoftDocs/xamarin-docs#867]
Enable-WindowsOptionalFeature : Feature name Microsoft-Hyper-V is unknown. 
but the Enable-WindowsOptionalFeature -Online -FeatureName HypervisorPlatform -All works. 
Does this mean we have to install some software tool to get Hyper-V 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e70c0069-6174-0591-a6e0-8e46dedae1eb
* Version Independent ID: 8a8e8863-9562-211e-fc60-eef9b6a95833
* Content: [Android Emulator Troubleshooting - Xamarin](https://docs.microsoft.com/en-us/xamarin/android/get-started/installation/android-emulator/troubleshooting?pivots=windows)
* Content Source: [docs/android/get-started/installation/android-emulator/troubleshooting.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/android/get-started/installation/android-emulator/troubleshooting.md)
* Product: **xamarin**
* GitHub Login: @conceptdev
* Microsoft Alias: **crdun**

**Comment by conceptdev** [comment]
We cover Hyper-V on the [hardware acceleration page](https://docs.microsoft.com/en-us/xamarin/android/get-started/installation/android-emulator/hardware-acceleration), and at the end of the [troubleshooting](https://docs.microsoft.com/en-us/xamarin/android/get-started/installation/android-emulator/troubleshooting) section, there is a link to the [Windows Hyper-V page](https://docs.microsoft.com/en-us/virtualization/hyper-v-on-windows/quick-start/enable-hyper-v). We have no additional information on the underlying Hyper-V technology, but I hope that reference helps.

**Comment by pmahend1** [comment]
> @pmahend1 is this solved??, please let me know, I am trying to install WSL2 but this error is interrupting me

All I remember is that you need to be on Windows Pro and have CPU that can enable Hyper-V to make it work. It wont work on Windows Home .
