### ISSUE TITLE
NamedSize mapping to platform sizes

### ISSUE THREAD

**Issue by breyed** [MicrosoftDocs/xamarin-docs#868]
The documentation should show the mapping of `NamedSize` enum values to their respective named sizes on the various platforms. For example, iOS has 7 [Dynamic Type Sizes](https://developer.apple.com/design/human-interface-guidelines/ios/visual-design/typography/#dynamic-type-sizes) ranging from xSmall to xxxLarge. What do the 4 Xamarin.Forms sizes map into?

This mapping should be easily discoverable from this doc page, from the `NamedSize` API page and from the `Device.GetNamedSize` API page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe0572c4-91be-fc86-d130-242db2bf470b
* Version Independent ID: 1238fdd7-c378-6d0d-654e-55656a70d386
* Content: [Fonts in Xamarin.Forms - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/text/fonts)
* Content Source: [docs/xamarin-forms/user-interface/text/fonts.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/text/fonts.md)
* Product: **xamarin**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @breyed 

Thanks for the suggestion. I've added it to our backlog.
