### ISSUE TITLE
How to do this from c# page?

### ISSUE THREAD

**Issue by ananthasivanvk** [MicrosoftDocs/xamarin-docs#870]
How we can add a video player to ContentPage ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ab2d81c2-6cff-729b-b5c0-a8783d96377b
* Version Independent ID: e1228412-623c-e208-eace-4c48f59fee1f
* Content: [Loading application resource videos - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/custom-renderer/video-player/loading-resources)
* Content Source: [docs/xamarin-forms/app-fundamentals/custom-renderer/video-player/loading-resources.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/app-fundamentals/custom-renderer/video-player/loading-resources.md)
* Product: **xamarin**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by conceptdev** [comment]
In the [associated sample](https://developer.xamarin.com/samples/xamarin-forms/customrenderers/VideoPlayerDemos/) you could recreate the PlayVideoResourcePage.xaml in C# **PlayVideoResourcePageCS.cs** like this:

```
using System;
using Xamarin.Forms;
using FormsVideoLibrary;

namespace VideoPlayerDemos
{
    public class PlayVideoResourcePageCS : ContentPage
    {
        public PlayVideoResourcePageCS()
        {
            ResourceVideoSource rvs = new ResourceVideoSource();
            switch (Device.RuntimePlatform)
            {
                case Device.iOS:
                    rvs.Path = "Videos/iOSApiVideo.mp4";
                    break;
                case Device.Android:
                    rvs.Path = "AndroidApiVideo.mp4";
                    break;
                case Device.UWP:
                    rvs.Path = "Videos/UWPApiVideo.mp4";
                    break;
            }

            VideoPlayer vp = new VideoPlayer();
            vp.Source = rvs;

            Content = vp;
        }
    }
}
```

**Comment by ananthasivanvk** [comment]
Thanks @conceptdev,
I do have 1 more doubt, How  we can bind the path text "Videos/iOSApiVideo.mp4" from Xaml page

 If I give like <On Platform="iOS" Value="{Binding VideoUrl}" />its not working in the way it works when you give directly

**Comment by luisssebas** [comment]
use this on the cs of the view

videoPlayer.Source = new FileVideoSource
{
      File = filename
};
