### ISSUE TITLE
Compatibility wont work anymore

### ISSUE THREAD

**Issue by pmahend1** [MicrosoftDocs/xamarin-docs#876]
It still wont maintain compatibility. Errors saying we need to use theme based on AppCompat theme for the Activity.
Changing base class of MainActivity to FormsApplicationActivity leads in timeout exception.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 87b678e7-5336-db4f-02ac-db6d2115ebec
* Version Independent ID: 5434c705-8fa7-f2ed-e358-6c05d915cde0
* Content: [Material Theme - Xamarin](https://docs.microsoft.com/en-us/xamarin/android/user-interface/material-theme)
* Content Source: [docs/android/user-interface/material-theme.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/android/user-interface/material-theme.md)
* Product: **xamarin**
* GitHub Login: @conceptdev
* Microsoft Alias: **crdun**

**Comment by conceptdev** [comment]
Please see the Xamarin.Forms [docs on material design](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/platform/android/appcompat). If you have issues with the product, please visit [Developer Community](https://developercommunity.visualstudio.com/) or the open source repo at https://github.com/xamarin/Xamarin.Forms/issues/
