### ISSUE TITLE
Trailing sentence on the font resource type explanation

### ISSUE THREAD

**Issue by GarrettManley** [MicrosoftDocs/xamarin-docs#877]
The sentence here seems to trail off without completing the thought being expressed...

"font – Starting in API level 26, it is possible to embed fonts as a resource in an Android application. The Support Library 26 will backport fonts to API level 14. Embedding fonts allows applications to"

It sounds like it should continue to explain what embedding fonts allows applications to do.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7d118756-bf0f-0fc9-b6df-c3437397b2cf
* Version Independent ID: 37627877-5b22-e8c2-f22b-252afb12e78b
* Content: [Default Resources - Xamarin](https://docs.microsoft.com/en-us/xamarin/android/app-fundamentals/resources-in-android/default-resources?tabs=vsmac)
* Content Source: [docs/android/app-fundamentals/resources-in-android/default-resources.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/android/app-fundamentals/resources-in-android/default-resources.md)
* Product: **xamarin**
* GitHub Login: @conceptdev
* Microsoft Alias: **crdun**

**Comment by jcfi** [comment]
@GarrettManley There are other inconsistencies between the VS for Mac/Windows sections (e.g. `drawable` is only on the Windows description, `mipmap` is only on the Mac description), so it might be the case that the Windows and Mac versions of VS actually have different resources available. After all, if they did have the same resources available, why would the docs page need to have two separate lists?

I don't have VS for Windows installed to verify this, but it should probably be opened as a separate issue.

**Comment by conceptdev** [comment]
Thanks @jcfi for fixing up the content.
