### ISSUE TITLE
Your service also has to implement OnBind

### ISSUE THREAD

**Issue by dangibson** [MicrosoftDocs/xamarin-docs#879]
The example doesn't say that you have to implement OnBind, but you do since it's an abstract method:

public override IBinder OnBind(Intent intent)
{
    what am I supposed to do here?
}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4c7b8d9b-b6a9-62f8-28fb-971bb39d4c99
* Version Independent ID: 7893ffeb-dc5c-8cb4-1e05-31315d4adf31
* Content: [Creating a Service - Xamarin](https://docs.microsoft.com/en-us/xamarin/android/app-fundamentals/services/creating-a-service/)
* Content Source: [docs/android/app-fundamentals/services/creating-a-service/index.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/android/app-fundamentals/services/creating-a-service/index.md)
* Product: **xamarin**
* GitHub Login: @conceptdev
* Microsoft Alias: **crdun**

**Comment by conceptdev** [comment]
This is covered in the related documents, eg [Bound Services](https://docs.microsoft.com/en-us/xamarin/android/app-fundamentals/services/creating-a-service/bound-services#extend-the-service-class):

```
public override IBinder OnBind(Intent intent)
{
       // This method must always be implemented
       Log.Debug(TAG, "OnBind");
       this.Binder = new TimestampBinder(this);
       return this.Binder;
}
```

See the [services samples](https://github.com/xamarin/monodroid-samples/tree/master/ApplicationFundamentals/ServiceSamples) for working code.
