### ISSUE TITLE
What to do about this????

### ISSUE THREAD

**Issue by dparizek** [MicrosoftDocs/xamarin-docs#88]
/Users/dave/projects/Phoneword/Droid/obj/Debug/android/manifest/AndroidManifest.xml(0,0): Error APT0000: No resource found that matches the given name (at 'theme' with value '@style/MainTheme'). (APT0000) (Phoneword.Droid)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2de3e72c-8948-4dd5-e37f-9cf81e62c127
* Version Independent ID: 7b7c5c7f-4102-8e91-fbe6-7d21fcc8f5be
* Content: [Xamarin.Forms Quickstart - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/get-started/hello-xamarin-forms/quickstart?tabs=vswin)
* Content Source: [docs/xamarin-forms/get-started/hello-xamarin-forms/quickstart.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/get-started/hello-xamarin-forms/quickstart.md)
* Service: **unspecified**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by conceptdev** [comment]
@dparizek thanks for raising this. @Miraxz is correct - you can change the value as suggested.

It looks like the default value in the **File>New** templates has changed from `MainTheme` to `MyTheme` - we will have to update this doc and the sample to match.

If you wish to check the correct value in your solution, look in **Phoneword/Droid/Resources/values/styles.xml** for `<style name="MainTheme" parent="MainTheme.Base">` or `<style name="MyTheme" parent="MyTheme.Base">`
