### ISSUE TITLE
xamarin forms的单位转成android和ios的像素有没有具体的转换公式

### ISSUE THREAD

**Issue by zhanglinx** [MicrosoftDocs/xamarin-docs#885]
“针对Apple iPhone和iPad设备的程序员继续以点为单位工作，但这些点数中有160个。根据设备的不同，该点可能有1个，2个或3个像素”
有没有具体的转换公式

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 43ca5aa8-6294-ae0a-78e0-07cb096adddc
* Version Independent ID: 0ff2e1bb-8c4e-c8cf-7087-3c4fa8b391a5
* Content: [Summary of Chapter 5. Dealing with sizes - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/creating-mobile-apps-xamarin-forms/summaries/chapter05)
* Content Source: [docs/xamarin-forms/creating-mobile-apps-xamarin-forms/summaries/chapter05.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/creating-mobile-apps-xamarin-forms/summaries/chapter05.md)
* Product: **xamarin**
* GitHub Login: @charlespetzold
* Microsoft Alias: **chape**

**Comment by davidbritch** [comment]
Hi @zhanglinx 

This book was published in the spring of 2016, and has not been updated since then. There is much in the book that remains valuable, but some of the material is outdated, and some topics are no longer entirely correct or complete.

**Comment by conceptdev** [comment]
See Apple's image size guidelines
https://developer.apple.com/design/human-interface-guidelines/ios/icons-and-images/image-size-and-resolution/
