### ISSUE TITLE
Being started other than via OnLaunched

### ISSUE THREAD

**Issue by johnshardman** [MicrosoftDocs/xamarin-docs#886]
It would be useful to mention that OnLaunched is not the only way a UWP app gets started, and to show what code might be required in, for example, OnActivated to initialise Xamarin.Forms and to show something more than the splash screen.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2ec3998b-c321-10e6-8e06-b10900c3a549
* Version Independent ID: de666c26-6261-7762-2c18-1576499b5fac
* Content: [Setup Windows Projects - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/platform/windows/installation/index)
* Content Source: [docs/xamarin-forms/platform/windows/installation/index.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/platform/windows/installation/index.md)
* Product: **xamarin**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by conceptdev** [comment]
This page merely explains how to manually accomplish what the **File > New** template does automatically for new Xamarin.Forms projects.

If you believe there is a bug in the templates, please visit the [Developer Community](https://developercommunity.visualstudio.com/) site to report it.
