### ISSUE TITLE
Clarification of assembliesToInclude

### ISSUE THREAD

**Issue by johnshardman** [MicrosoftDocs/xamarin-docs#887]
"Add a reference to each assembly that is referenced by the app." needs clarification. Does this mean every single assembly that can be seen being loaded in the VS Output window, or a subset thereof? How does the developer identify the assemblies to include in the Forms.Init call? Even if it were every assembly rather than a subset, some might be loaded dynamically some time after starting the app.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2ec3998b-c321-10e6-8e06-b10900c3a549
* Version Independent ID: de666c26-6261-7762-2c18-1576499b5fac
* Content: [Setup Windows Projects - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/platform/windows/installation/index)
* Content Source: [docs/xamarin-forms/platform/windows/installation/index.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/platform/windows/installation/index.md)
* Product: **xamarin**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by conceptdev** [comment]
It's specifically referring to references added by the developer; which is discussed in the opening paragraph of that section (eg. third party controls). I've tweaked the wording.
