### ISSUE TITLE
CocoSharp not compatible with Visual Studio 2017

### ISSUE THREAD

**Issue by frangagn** [MicrosoftDocs/xamarin-docs#894]
When trying to install the CocoSharp 2D game engine, following the instructions on GitHub to the t I get a error message that "This extension is not compatible with Visual Studio 2017". There are many threads about this on many developers forums and no answers. Either the library is dying or outdated and you should specify it to avoid that we waste our time, or the installation instructions are outdated, which does not make a new developer trust the toolset. Please do something...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8f2c5446-f22b-8a7c-b200-7ebe6545562d
* Version Independent ID: e28405f0-a191-c724-4e0b-13c6dcb4023a
* Content: [CocosSharp 2D Game Engine - Xamarin](https://docs.microsoft.com/en-us/xamarin/graphics-games/cocossharp/)
* Content Source: [docs/graphics-games/cocossharp/index.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/graphics-games/cocossharp/index.md)
* Product: **xamarin**
* GitHub Login: @conceptdev
* Microsoft Alias: **crdun**

**Comment by frangagn** [comment]
And as far as I'm concerned, I'm going to go with another library. Developers time is money, and I have no time to waste.

**Comment by conceptdev** [comment]
@frangagn you're right, the [CocosSharp repo](https://github.com/mono/CocosSharp) has not been updated in some time, and we are currently evaluating how this affects our content. Your feedback is helpful to us, in helping us to understand that people are still finding and following these pages. Thanks for taking the time to let us know about your experience.

**Comment by frangagn** [comment]
Please confirm.... is it outdated or am I just not looking at the right thing?

**Comment by conceptdev** [comment]
CocosSharp is a community-supported project, and judging by the dates on the [github repo](https://github.com/mono/CocosSharp) it does seem like it's out-of-date.

**Comment by nguyenthanhliemfc** [comment]
Can we use Unity3D/2D in Xamarin.Forms?

**Comment by conceptdev** [comment]
@nguyenthanhliemfc no, while Unity utilizes Mono and C# for it's scripting, and Visual Studio for editing, there is currently no easy way to embed Unity within a Xamarin project.
