### ISSUE TITLE
trail

### ISSUE THREAD

**Issue by viswatej44** [MicrosoftDocs/xamarin-docs#897]
good

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a69fb577-b84c-d286-345a-386fea7647cc
* Version Independent ID: 696c3963-53dc-47d8-387f-7d19c7f941dd
* Content: [Get Started With Xamarin - Xamarin](https://docs.microsoft.com/en-us/xamarin/cross-platform/get-started/)
* Content Source: [docs/cross-platform/get-started/index.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/cross-platform/get-started/index.md)
* Product: **xamarin**
* GitHub Login: @asb3993
* Microsoft Alias: **amburns**

**Comment by conceptdev** [comment]
Thanks for your feedback.
