### ISSUE TITLE
Grauenhafte Übersetzung

### ISSUE THREAD

**Issue by hb9tws** [MicrosoftDocs/xamarin-docs#90]
Die deutsche Übersetzung ist einfach grauenhaft.

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von Problemen docs.microsoft.com ➟ GitHub erforderlich.*

* ID: 969ae3fb-fa08-217b-a62f-105317ea811a
* Version Independent ID: 49deb3eb-6726-62d1-1684-6816d4b4b1cb
* Content: [HttpClient-Stapel und Implementierung von SSL/TLS-Selektor für Android - Xamarin](https://docs.microsoft.com/de-ch/xamarin/android/app-fundamentals/http-stack?tabs=vswin#feedback)
* Content Source: [docs/android/app-fundamentals/http-stack.md](https://github.com/MicrosoftDocs/xamarin-docs.de-DE/blob/live/docs/android/app-fundamentals/http-stack.md)
* Service: **unspecified**
* GitHub Login: @topgenorth
* Microsoft Alias: **toopge**

**Comment by MagicAndre1981** [comment]
always use an English Visual Studio and read en-us resources. translated error messages and documentation are always a pain.

**Comment by conceptdev** [comment]
Thanks for the feedback @MagicAndre1981.

**Comment by Sara-Nicolini** [comment]
@MagicAndre1981, thanks for your feedback. The page in question was machine-translated which we understand it is not always ideal and fully understandable. We have recently added a toggle "Auf Englisch lesenon" on the right nav of the topic that allows you to switch to the English version of the topic without having to change the language settings.

**Comment by CeciAc** [comment]
Hello, @MagicAndre1981 

Your feedback is much appreciated.
Since your comments are specific to the localization of the documentation, we have moved this issue to the corresponding localization repository and we will close this one: 

Please review the status of this issue here https://github.com/MicrosoftDocs/xamarin-docs.de-de/issues/1

Kind regards,
Microsoft DOCS International Team

**Comment by Sara-Nicolini** [comment]
Hallo, @hb9tws,

vielen Dank für Ihren Beitrag. Ihr Feedback bezieht sich auf die ursprüngliche Dokumentation. 
Deshalb verschieben wir dieses Problem in das englische Repository. Sehen Sie sich den Status des Problems hier an: https://github.com/MicrosoftDocs/xamarin-docs.de-de/issues/1.

Vielen Dank, dass Sie eine gute Qualität unserer Artikel gewährleisten.  

Mit freundlichen Grüßen 
das Microsoft DOCS International Team.

@conceptdev, please close this issue.

**Comment by DavidPrio** [comment]
@conceptdev #please-close
