### ISSUE TITLE
Keeping Device.GetNamedSize results up to date

### ISSUE THREAD

**Issue by breyed** [MicrosoftDocs/xamarin-docs#902]
The instructions on using Device.GetNamedSize should indicate how to hook into an event that reports when the user has changed system text size. Otherwise, the value from return from Device.GetNamedSize can become out of date without the app acquiring the new named size and updating the display accordingly.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe0572c4-91be-fc86-d130-242db2bf470b
* Version Independent ID: 1238fdd7-c378-6d0d-654e-55656a70d386
* Content: [Fonts in Xamarin.Forms - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/text/fonts)
* Content Source: [docs/xamarin-forms/user-interface/text/fonts.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/text/fonts.md)
* Product: **xamarin**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @breyed 

Thanks for the suggestion. I've added it to our backlog.

**Comment by davidbritch** [comment]
Closing as named sizes update on iOS as of 4.1, and have updated on Android for a while.
