### ISSUE TITLE
Hyper V

### ISSUE THREAD

**Issue by domagojmedo** [MicrosoftDocs/xamarin-docs#906]
When running systeminfo in cmd, hyper-v requirements info says "A hypervisor has been detected. Features required for Hyper-V will not be displayed." instead of all yes values. Is this ok? Maybe that scenario can be added to the article 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4e37d642-2051-8d70-9968-dfb484122a6a
* Version Independent ID: 178ea80c-2b99-0c44-eeb6-9db319439b33
* Content: [Hardware Acceleration for Emulator Performance (Hyper-V & HAXM) - Xamarin](https://docs.microsoft.com/en-us/xamarin/android/get-started/installation/android-emulator/hardware-acceleration?tabs=vswin&pivots=windows)
* Content Source: [docs/android/get-started/installation/android-emulator/hardware-acceleration.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/android/get-started/installation/android-emulator/hardware-acceleration.md)
* Product: **xamarin**
* GitHub Login: @conceptdev
* Microsoft Alias: **crdun**

**Comment by ncarandini** [comment]
The result is the same (as expected): "A hypervisor has been detected. Features required for Hyper-V will not be displayed." I don't think is a problem, I'm (almost happily) using Docker + Hypervisor + Android Emulator.

**Comment by domagojmedo** [comment]
![screenshot_88](https://user-images.githubusercontent.com/12157224/47986508-41bb7a80-e0dd-11e8-8ceb-7e4fa8f82096.png)

@JonDouglas as @ncarandini said it's the same message, I'm just wondering because this android hyper-v emulator is much slower than the Visual studio emulator for android I was using before. So I'm just trying to figure out if everything is setup correctly

**Comment by ncarandini** [comment]
Not only is much slower, but lately I'm facing lots of problems that I'm trying to understand. As an example, I have flickering problems when the device is locked (and I do need to set PIN because I need to import a self signed certificate for testing purposes).

**Comment by JonDouglas** [comment]
@domagojmedo @ncarandini 

For the hyper-v emulator performance items, I would highly recommend updating to the latest Windows version(Insiders if you can). I believe some of these performance issues you are seeing are loosely related to recent spectre/meltdown fixes. There were a few recent reports on certain machines seeing less than idea performance for the Hyper-V emulator. These users updated to the latest Windows version and found performance to be similar to HAXM.  

@ncarandini As for these other issues, I would highly recommend opening up a new issue via the `Help->Send Feedback -> Report a Problem` feature inside Visual Studio 2017.

**Comment by claudiocleberson** [comment]
Same here, the android emulator run slow as hell.  I have docker running on my machine, so be switching on and off to use HAXM  is a bother.

**Comment by Codezil** [comment]
hello im having this problem
Could not launch the emulator.
Please file an issue by choosing "Report a Problem" in the Help menu, and attach your logs.
Error message: "There are one or more open sessions."

**Comment by Mimisss** [comment]
FWIW, I used to get the "YES,YES,YES,YES" messsage but after running the command: `bcdedit /set hypervisorlaunchtype off` I get "A hypervisor has been detected. Features required for Hyper-V will not be displayed." and cannot get it back to work no matter what.

**Comment by xyfy** [comment]
I got the same message.and I already run docker as well.
已检测到虚拟机监控程序。将不显示 Hyper-V 所需的功能。	
but when I run the Android Emulator ,  the system says that it didn't detect hyper-v enabled.
I am use windows 10  professional with version 1903

**Comment by conceptdev** [comment]
If you feel like you've hit a bug in the product, please [report it from within Visual Studio](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2019) as this provides additional information (with your permission) to help the team learn more about the issue.

**Comment by xyfy** [comment]
Yes，it may be a soft bug.

but I think  your document also has an error. not suit my case(or ours).

When running systeminfo in cmd,  I got the same display with @domagojmedo @Mimisss 

which is diffrent from your document mentioned

**Comment by conceptdev** [comment]
The documentation has been updated a number of times since these issues, so I'm closing this thread. Please open a new issue if there are still problems, thanks.

**Comment by ruffin--** [comment]
@conceptdev But the documentation still doesn't include the "A hypervisor has been detected. Features required for Hyper-V will not be displayed," situation, which is what I'm (and others in this thread) were experiencing. I'm not sure why you closed this. That this situation (and string) is still missing in the docs is pretty easy to vet.
