### ISSUE TITLE
AllowBackup should be FALSE in the example code

### ISSUE THREAD

**Issue by moritzm** [MicrosoftDocs/xamarin-docs#907]
The example might be confusing. You are talking about diabling it for the hole app, but the example shows it the other way round.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: da75050f-bfda-4792-40d9-b9a25d649d3e
* Version Independent ID: 5c44f996-765b-f6e4-c807-9446c534d50b
* Content: [Xamarin.Essentials: Secure Storage - Xamarin](https://docs.microsoft.com/en-us/xamarin/essentials/secure-storage?context=xamarin%2Fxamarin-forms&tabs=android)
* Content Source: [docs/essentials/secure-storage.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/essentials/secure-storage.md)
* Product: **xamarin**
* GitHub Login: @jamesmontemagno
* Microsoft Alias: **jamont**

**Comment by conceptdev** [comment]
Fixed courtesy of @james-alt, thanks for notifying us.
