### ISSUE TITLE
Support for Android 7 and above.

### ISSUE THREAD

**Issue by rcunniffe** [MicrosoftDocs/xamarin-docs#908]
Hey, I

I have been using this plugin for some some, but the playstore now require an app to target android version 7 at a minimum. When i target this, the application cannot "Open the database" it only works for lower version of android. 

you can see discussion in various forums that recommend against the official plugin for xamarin forms?https://stackoverflow.com/questions/41785097/sqlite-net-pcl-not-working-properly-on-android-7-0-xamarin

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c07438f1-7799-35a5-c6aa-86ce411694b1
* Version Independent ID: 7d3ccdcd-5165-99cf-9184-dcc966dbd25e
* Content: [Using SQLite.NET with Android - Xamarin](https://docs.microsoft.com/en-us/xamarin/android/data-cloud/data-access/using-sqlite-orm)
* Content Source: [docs/android/data-cloud/data-access/using-sqlite-orm.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/android/data-cloud/data-access/using-sqlite-orm.md)
* Product: **xamarin**
* GitHub Login: @conceptdev
* Microsoft Alias: **crdun**

**Comment by conceptdev** [comment]
@rcunniffe in the answer to that stackoverflow question, it is explained that:

> We ran into the same issue and have since switched to the SQLite-Net-PCL library (notice the dash instead of the period) which works the exact same way and has an almost identical API. A link for that library can be found [here](https://github.com/praeclarum/sqlite-net).

This is the same library we recommend on this page. There are many different SQLite NuGet packages, so it can be tricky to find the exact one that you should be using. As shown on [our page](https://docs.microsoft.com/en-us/xamarin/android/data-cloud/data-access/using-sqlite-orm), check the package name, author, and "NuGet Id" all match.

**Comment by rcunniffe** [comment]
@conceptdev sorry forgot to update. I was not actively asking for user's permission to access external storage. ticking th permissions in the manifest is not enough. Seem ok now. I used James's permission plugin.
