### ISSUE TITLE
MainActivity.cs

### ISSUE THREAD

**Issue by CeciAc** [MicrosoftDocs/xamarin-docs#911]
@skyscience commented on [Wed Sep 26 2018](https://github.com/MicrosoftDocs/xamarin-docs.zh-cn/issues/16)

MainActivity.cs的Resource.Layout.main  因该改为 Resource.Layout.activity_main。因为文件名是' activity_main.axml '

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 660b0f7c-9941-2db3-63bf-fc8a97765b1e
* Version Independent ID: 5aa1e6f6-534a-05b9-c44a-1f62b24c201a
* Content: [Hello，Android：快速入门 - Xamarin](https://docs.microsoft.com/zh-cn/xamarin/android/get-started/hello-android/hello-android-quickstart?tabs=vswin)
* Content Source: [docs/android/get-started/hello-android/hello-android-quickstart.md](https://github.com/MicrosoftDocs/xamarin-docs.zh-CN/blob/live/docs/android/get-started/hello-android/hello-android-quickstart.md)
* Product: **xamarin**
* GitHub Login: @mgmclemore
* Microsoft Alias: **mamcle**

---

@LisandroSu commented on [Thu Sep 27 2018](https://github.com/MicrosoftDocs/xamarin-docs.zh-cn/issues/16#issuecomment-425127436)

你好，@skyscience
 
感谢你的反馈。 
 
我们正在积极查看你的评论，并会很快地再次和你取得联系。 
 
深深的祝福， 
Microsoft DOCS International Team 

---

@CeciAc commented on [Mon Oct 08 2018](https://github.com/MicrosoftDocs/xamarin-docs.zh-cn/issues/16#issuecomment-427859965)

你好，@skyscience
 
感谢你的反馈。 
 
我们正在积极查看你的评论，并会很快地再次和你取得联系。 
 
深深的祝福， 
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hi team, 
The user reports an accuracy issue regarding a filename.

Rough translation:
_Resource.Layout.main of MainActivity.cs is changed to Resource.Layout.activity_main. Because the file name is 'activity_main.axml'_

Kind regards, 

Microsoft DOCS International Team

**Comment by conceptdev** [comment]
Thankyou! There is currently a mismatch between the **File>New** templates on macOS and Windows - one creates a `Main.axml` file, and the other creates an `activity_main.axml` file. 

We are planning to fix this problem, first by updating the docs; and eventually by making the templates match across macOS and Windows.

Thanks for the feedback.
