### ISSUE TITLE
Why setting Target Android version to Automatic.

### ISSUE THREAD

**Issue by hlogmans** [MicrosoftDocs/xamarin-docs#914]
Setting Target to automatic does have problematic side-effects when publishing to the Play Store. Better specify up to which target version this works instead of setting it to Automatic which does no do what it says it does. See https://github.com/xamarin/xamarin-android/issues/1163. Bottom line: as of new rules for the play store, you cannot publish an app that uses this. Please specify up to which Target this works, and what to do if you need to specify a newer target.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9c1bd30c-6e7a-df38-8c20-dff7361e901f
* Version Independent ID: 013c6027-db9a-6039-3404-2e4f717133a9
* Content: [Implementing a HybridWebView - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/custom-renderer/hybridwebview)
* Content Source: [docs/xamarin-forms/app-fundamentals/custom-renderer/hybridwebview.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/app-fundamentals/custom-renderer/hybridwebview.md)
* Product: **xamarin**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by hlogmans** [comment]
The problem is, Javascript code is not persisted when loading a new URL for the latest targets. And it is not executed when injecting too fast after loading. Injecting could be done in the PageLoaded event, but beware PageLoaded is not called when loading pages from string sources.

**Comment by davidbritch** [comment]
Hi @hlogmans 

Thanks for reporting this. I've made a PR to fix it.
