### ISSUE TITLE
Image not displaying in ImageCell from external path

### ISSUE THREAD

**Issue by yawarali** [MicrosoftDocs/xamarin-docs#918]
I'm using ListView with ImageCell. Binded With ObservableCollection, ListView shows images from resources but when I add new ImageSource of external Image -- Out of the project, Gallary on Android, other drives or directory on UWP, Does not display.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3218187d-58a5-a214-4a23-bd2093e771b7
* Version Independent ID: 7a506e7e-e8c9-2bc4-148b-34529ce3afad
* Content: [Xamarin.Forms ListView - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/listview/)
* Content Source: [docs/xamarin-forms/user-interface/listview/index.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/listview/index.md)
* Product: **xamarin**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by conceptdev** [comment]
@yawarali please report product issues by clicking on the **Product feedback** button at the bottom of the documentation page, or visit the [Developer Community site](https://developercommunity.visualstudio.com/) directly to search and add issues or suggestions.
