### ISSUE TITLE
Can't get a newer version than the one provided

### ISSUE THREAD

**Issue by LisandroSu** [MicrosoftDocs/xamarin-docs#924]
@iglesiasp commented on [Thu Oct 18 2018](https://github.com/MicrosoftDocs/xamarin-docs.es-es/issues/28)

You say "This example uses build 1.8.0.9; however, the version you download may be newer", but the link you provide is "hardwired" to that specific version download, and there's no way (e.g directory navigation) to obtain a newer release. Search in home page also does not work.

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: 97e1cd96-e7a2-ec22-8d79-ac949e890ccb
* Version Independent ID: 922a3fdf-7bab-7d9d-5518-904db9e75ee3
* Content: [Versión preliminar de la distribución OpenJDK Mobile de Microsoft - Xamarin](https://docs.microsoft.com/es-es/xamarin/android/get-started/installation/openjdk)
* Content Source: [docs/android/get-started/installation/openjdk.md](https://github.com/MicrosoftDocs/xamarin-docs.es-ES/blob/live/docs/android/get-started/installation/openjdk.md)
* Product: **xamarin**
* GitHub Login: @vyedin
* Microsoft Alias: **vyedin**

**Comment by LisandroSu** [comment]
Hi team,

Please check the issue reported.

Thanks!

**Comment by conceptdev** [comment]
This feature is in Preview. The hardcoded link is to the only version currently available; and which we have tested.

In future, when the product is stable, there will be the possibility of newer versions being downloaded and installed.
