### ISSUE TITLE
BehaviorBase

### ISSUE THREAD

**Issue by horse80** [MicrosoftDocs/xamarin-docs#926]
I struggled for a while to find the definition for BehaviorBase&lt;T&gt;, didn't know if it was part of the framework or was defined somewhere in the examples; found in none of them.

So, in case someone else also has the same issue, i eventually found a definition following the _EventToCommand Behavior (sample)_ at _Related Links_ at the bottom of this page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b06aff09-e5dd-9bba-d158-f3b61984d735
* Version Independent ID: 72c8ef2a-01f3-aee4-9a84-11995565b2d3
* Content: [Reusable EventToCommandBehavior - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/behaviors/reusable/event-to-command-behavior#related-links)
* Content Source: [docs/xamarin-forms/app-fundamentals/behaviors/reusable/event-to-command-behavior.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/app-fundamentals/behaviors/reusable/event-to-command-behavior.md)
* Product: **xamarin**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @horse80 

Thanks for the feedback. There's a sample associated with most Xamarin.Forms docs, and the sample always contains full code, including the code in the doc.
