### ISSUE TITLE
Extension not found

### ISSUE THREAD

**Issue by asdiomar1** [MicrosoftDocs/xamarin-docs#927]
I'm trying to download the extension through Visual Studio Marketplace but it says that the requested page cannot be found

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e40394ca-9a55-d9b5-d427-7c2a2c00cfc8
* Version Independent ID: 5a5c17e2-a683-88f6-07a9-2002e814d54c
* Content: [Live Reload - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/xaml/live-reload)
* Content Source: [docs/xamarin-forms/xaml/live-reload.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/xaml/live-reload.md)
* Product: **xamarin**
* GitHub Login: @pierceboggan
* Microsoft Alias: **piboggan**

**Comment by anirudhagupta** [comment]
the extension is not in the marketplace. Is this removed parmanently or temporarily. was lookin for it for UWP

**Comment by conceptdev** [comment]
As mentioned in the [linked issue](https://github.com/xamarin/Xamarin.Forms/issues/4155), it has been removed from the marketplace. Try the [XAML Previewer](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/xaml/xaml-previewer) for an alternative way to see your UI during development.
