### ISSUE TITLE
Windows 10 Performance

### ISSUE THREAD

**Issue by eltiare** [MicrosoftDocs/xamarin-docs#93]
How is the performance of Webview under Windows 10?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ef31dc71-3610-6c18-2bda-d0bb70804c92
* Version Independent ID: 02f7dc7b-541b-4b82-b33c-4e974fb94d8c
* Content: [WebView - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/webview?tabs=vswin#Performance)
* Content Source: [docs/xamarin-forms/user-interface/webview.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/webview.md)
* Service: **unspecified**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by conceptdev** [comment]
@eltiare here's a link to the UWP WebView control docs

https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.webview

I have no insight into how it performs.

**Comment by eltiare** [comment]
I thought it would be helpful to include this information in the "performance" section since it listed other platforms and Windows 8.

**Comment by conceptdev** [comment]
Ah, I see. We don't have much to add there, UWP devices should run Edge just fine, embedded or not. Good point, though. I've added a paragraph to the doc to clarify.
