### ISSUE TITLE
ValidatableObject Class - where is it defined?  

### ISSUE THREAD

**Issue by dinobu** [MicrosoftDocs/xamarin-docs#933]
I thought this class is comming from Xamarin but I does not seem so.  Where is this class coming from?  If I add it to my Xamarin.Forms project as a property type, VS-for-Mac complains that the class is not defined but does not give any option to import a namespace, so it is basically nowhere defined???

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b7433934-d5da-72be-7f79-f1f33259cf44
* Version Independent ID: 022fbc39-4a57-7ed7-91e4-463086e9a401
* Content: [Validation in Enterprise Apps - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/enterprise-application-patterns/validation)
* Content Source: [docs/xamarin-forms/enterprise-application-patterns/validation.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/enterprise-application-patterns/validation.md)
* Product: **xamarin**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @dinobu 

`ValidatableObject` isn't a Xamarin.Forms class. Instead, it's included in the eShopOnContainers [app](https://github.com/dotnet-architecture/eShopOnContainers), specifically [here](https://github.com/dotnet-architecture/eShopOnContainers/tree/dev/src/Mobile/eShopOnContainers/eShopOnContainers.Core/Validations) .

**Comment by kensykora** [comment]
Hi @davidbritch -- could you at least link to the source for that somewhere in the document? It feels like that is a critical part of this guide and is absent without either a google search or the dive into the github issues here.

**Comment by dinobu** [comment]
> 
> 
> Hi @davidbritch -- could you at least link to the source for that somewhere in the document? It feels like that is a critical part of this guide and is absent without either a google search or the dive into the github issues here.

@davidbritch First of all, thanks for the great guide!  I also think @kensykora 's suggestion would further improve it.
