### ISSUE TITLE
Xamarin Speech Recognition Document issue report

### ISSUE THREAD

**Issue by aixiaozi** [MicrosoftDocs/xamarin-docs#934]
I tried to implement Speech to Text function in Xamarin.Formsas the document said: https://docs.microsoft.com/en-us/xamarin/xamarin-forms/data-cloud/cognitive-services/speech-recognition. 

As the document said, we only need to update the API keys for the different services in Constants.cs: https://github.com/xamarin/xamarin-forms-samples/blob/master/WebServices/TodoCognitiveServices/TodoCognitive/Constants.cs.  Then, we should able to use the Speech service. 

The problem is when I get the API key as the document said and use it in the sample project, the project didn’t work as expected.

Expected Behavior:
================
Works fine as the document said.

Actual Behavior:
================
When I tap the record icon, it shows the loader on the screen and nothing will happen

Reproduce Steps:
================
1.	Download the Todo Cognitive Service Sample: https://developer.xamarin.com/samples/xamarin-forms/WebServices/TodoCognitiveServices/

2.	Get the Microsoft Speech API key as the document said: An API key must be obtained to use the Microsoft Speech API. This can be obtained at Try Cognitive Services: https://azure.microsoft.com/try/cognitive-services/ 

![1](https://user-images.githubusercontent.com/18043540/47276119-95ab6700-d5e7-11e8-8e67-cf93725b3e56.jpg)
![2](https://user-images.githubusercontent.com/18043540/47276120-96dc9400-d5e7-11e8-8acb-3b716ff08577.jpg)
![3](https://user-images.githubusercontent.com/18043540/47276121-97752a80-d5e7-11e8-9ffa-13080dfdf8a4.jpg)
![4](https://user-images.githubusercontent.com/18043540/47276122-980dc100-d5e7-11e8-8d23-b120c32930a7.jpg)

3.	When I use the API key in the Todo Cognitive Service Sample, it didn’t work. And when I debug the project I found the error:
a.	"{ \"statusCode\": 401, \"message\": \"Access denied due to invalid subscription key. Make sure to provide a valid key for an active subscription.\" }" 

Workaround:
================
I found the article: HTTP 401 Access Denied when calling Azure Cognitive Services APIs: https://blogs.msdn.microsoft.com/kwill/2017/05/17/http-401-access-denied-when-calling-azure-cognitive-services-apis/, so I tried create a Azure Cognitive Services Resource in Azure portal,  get the KEY in Azure portal. When I use this KEY in the Todo Cognitive Service Sample, everything works fine as excepted.

Can you help to investigate this?

---
#### Document Details

? *Do not edit this section. It is required for docs.microsoft.com ? GitHub issue linking.*

* ID: 360463cc-0d30-522b-db5b-bd49a670f7af
* Version Independent ID: 2be2c545-1452-9333-a466-4d58c5cdf715
* Content: [Speech Recognition Using the Microsoft Speech API - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/data-cloud/cognitive-services/speech-recognition)
* Content Source: [docs/xamarin-forms/data-cloud/cognitive-services/speech-recognition.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/data-cloud/cognitive-services/speech-recognition.md)
* Product: **xamarin**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @aixiaozi 

You're right that using the Speech API requires a key from inside the Azure Portal. I've updated the doc, which will be pushed out as part of a larger PR.
