### ISSUE TITLE
Error en el código del documento

### ISSUE THREAD

**Issue by CeciAc** [MicrosoftDocs/xamarin-docs#937]
@Luismi1601 commented on [Sat Oct 20 2018](https://github.com/MicrosoftDocs/xamarin-docs.es-es/issues/29)

Buenos días,

El código que se ha expuesto en este articulo para aprender a programar en xamarin tiene un error wn la parte de UWP, concretamente en la parte del código del final (async task<Phoneline>...) que hace que no se peuda seguir adelante con el curso.

Gracias,
Un saludo,
---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: 2de3e72c-8948-4dd5-e37f-9cf81e62c127
* Version Independent ID: 7b7c5c7f-4102-8e91-fbe6-7d21fcc8f5be
* Content: [Inicio rápido de Xamarin.Forms - Xamarin](https://docs.microsoft.com/es-es/xamarin/xamarin-forms/get-started/hello-xamarin-forms/quickstart?tabs=vswin)
* Content Source: [docs/xamarin-forms/get-started/hello-xamarin-forms/quickstart.md](https://github.com/MicrosoftDocs/xamarin-docs.es-ES/blob/live/docs/xamarin-forms/get-started/hello-xamarin-forms/quickstart.md)
* Product: **xamarin**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by CeciAc** [comment]
Hi team, 
I moving this here since the user is reporting an error in the example code:

Rough translation: _"The code that has been exposed in this article to learn to program in xamarin has an error in the part of UWP, specifically in the part of the code of the end (async task ...) that makes that it is not possible to go ahead with the course ."_

Kind regards,
Microsoft DOCS International Team

**Comment by conceptdev** [comment]
The code in the `GetDefaultPhoneLineAsync` is designed for UWP running on mobile phone devices. 

It will not work on desktop and tablet computers. We will update the example to remove this.

Thank you @Luismi1601 for your feedback.
