### ISSUE TITLE
All buttons and Text stacking up in the top left.

### ISSUE THREAD

**Issue by Hutch07** [MicrosoftDocs/xamarin-docs#939]
Using Visual Studio Community 15.7.5 with Xamarin 4.10.10.2 (Xamarin Designer 4.12.1) on Windows 10.

My issue is that when I try to place any tool (button, plain text, Text large) onto the app, they all stack up in the upper left corner on top of each other.  The app will only let me place them just below the previous tool but when I click, they are stacked on top of the previous tool.

Is there a setting like "object snap" or something that handles this?

**Comment by conceptdev** [comment]
Documentation for the [Android Designer](https://docs.microsoft.com/xamarin/android/user-interface/android-designer/) includes a [walkthrough](https://docs.microsoft.com/xamarin/android/user-interface/android-designer/designer-walkthrough) to help learn how to use it.
