### ISSUE TITLE
Clarification of terms

### ISSUE THREAD

**Issue by Phlash1989** [MicrosoftDocs/xamarin-docs#942]
Hello, in the "Performance" section you are comparing "compiled binding that uses property-change notification" with "compiled binding that doesn't use property-change notification". I'm not sure when one or the other will be generated from my Xaml, as it is not stated anywhere. Can you please clarify this terms?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f6dded20-b246-945c-63ce-0e349afac9a2
* Version Independent ID: 1e24cfb3-a124-e001-5eb5-9410834bf3a1
* Content: [Xamarin.Forms Compiled Bindings - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/data-binding/compiled-bindings)
* Content Source: [docs/xamarin-forms/app-fundamentals/data-binding/compiled-bindings.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/app-fundamentals/data-binding/compiled-bindings.md)
* Product: **xamarin**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Noting here clarifications to make to the doc:

1. As above.
2. BindingContext can be set in code-behind.
3. General purpose object inspection = reflection.
4. TL;DR at top of doc saying you'll get a perf gain.

**Comment by davidbritch** [comment]
Hi @Phlash1989 

Thanks for the feedback. This is done and will be published as part of a larger PR.

**Comment by Phlash1989** [comment]
Thank you, you guys are awesome!
