### ISSUE TITLE
How can I disable hours in time-picker

### ISSUE THREAD

**Issue by arvindrajachourasiya** [MicrosoftDocs/xamarin-docs#943]
Hi, I have a requirement to accept only minutes 1 to 59, but time picker showing hours too. How can I disable hours. Add that information as well.
Thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a0047ac3-d92a-dcb0-18ba-a0a8db2331db
* Version Independent ID: 8a479a1b-f3c8-a627-97a8-3d9e1f8573ee
* Content: [Time Picker - Xamarin](https://docs.microsoft.com/en-us/xamarin/android/user-interface/controls/pickers/time-picker)
* Content Source: [docs/android/user-interface/controls/pickers/time-picker.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/android/user-interface/controls/pickers/time-picker.md)
* Product: **xamarin**
* GitHub Login: @conceptdev
* Microsoft Alias: **crdun**

**Comment by conceptdev** [comment]
This functionality may not be supported by Android. Please refer to the [Google documentation](https://developer.android.com/reference/android/widget/TimePicker).
