### ISSUE TITLE
Xamarin Live Reload doesn't exist

### ISSUE THREAD

**Issue by ArunSivaR** [MicrosoftDocs/xamarin-docs#947]
Hi Team,

I am unable to find Xamarin Live Reload, i have searched for this in visual studio extension and updates, and even the official link posted top of the page (https://marketplace.visualstudio.com/items?itemName=Xamarin.XamarinLiveReload) doesn't work, it shows that "We're sorry, the page you requested cannot be found" where can i get the Xamarin Live Reload.

Regards,
Arun Siva R

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e40394ca-9a55-d9b5-d427-7c2a2c00cfc8
* Version Independent ID: 5a5c17e2-a683-88f6-07a9-2002e814d54c
* Content: [Live Reload - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/xaml/live-reload#feedback)
* Content Source: [docs/xamarin-forms/xaml/live-reload.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/xaml/live-reload.md)
* Product: **xamarin**
* GitHub Login: @pierceboggan
* Microsoft Alias: **piboggan**

**Comment by davidbritch** [comment]
Hi @ArunSivaR 

Live Reload is no longer an active project and was removed last week. I recommend looking at https://www.livexaml.com/ and https://grialkit.com/gorilla-player/ for runtime iteration on your UI. Our tooling team is working hard at making the Previewer a robust and performant tool for design-time UI iteration, so please be sure to follow Visual Studio previews for improvements there.
