### ISSUE TITLE
Binding now does support OneTime

### ISSUE THREAD

**Issue by Keboo** [MicrosoftDocs/xamarin-docs#948]
The comment "Binding.Mode does not support OneTime, instead just use OneWay." is no longer correct. Since PR 1805, Binding does support OneTime.

https://github.com/xamarin/Xamarin.Forms/pull/1805

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2491ac06-9f2a-6129-a64d-2c765dcd5780
* Version Independent ID: 84ee4f5c-85a2-7815-8397-9d8890a37581
* Content: [WPF vs. Xamarin.Forms: Similarities & Differences - Xamarin](https://docs.microsoft.com/en-us/xamarin/cross-platform/desktop/controls/wpf)
* Content Source: [docs/cross-platform/desktop/controls/wpf.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/cross-platform/desktop/controls/wpf.md)
* Product: **xamarin**
* GitHub Login: @asb3993
* Microsoft Alias: **amburns**

**Comment by davidbritch** [comment]
Hi @Keboo 

Thanks for pointing this out. I've updated the doc, which will be pushed out as part of a larger PR.
