### ISSUE TITLE
more docs request

### ISSUE THREAD

**Issue by edwinmuraya** [MicrosoftDocs/xamarin-docs#95]
nice docs ..please someone help out with firebase/azure authentication with google and facebook demo..would be very helpful thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 360c5865-2902-68da-5a8d-7252c26394c6
* Version Independent ID: d9df0129-27be-54dc-3c82-bb407b9f8c5b
* Content: [Firebase Cloud Messaging - Xamarin](https://docs.microsoft.com/en-us/xamarin/android/data-cloud/google-messaging/firebase-cloud-messaging)
* Content Source: [docs/android/data-cloud/google-messaging/firebase-cloud-messaging.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/android/data-cloud/google-messaging/firebase-cloud-messaging.md)
* Service: **unspecified**
* GitHub Login: @mgmclemore
* Microsoft Alias: **mamcle**

**Comment by mgmclemore** [comment]
Thanks @edwinmuraya!  Also, thank you for your suggestion: we will consider adding more Xamarin.Android firebase/azure authentication docs and sample code in a future release.

Meanwhile, there is a [Xamarin.Forms topic](https://docs.microsoft.com/en-us/azure/app-service-mobile/app-service-mobile-xamarin-forms-get-started-push#configure-the-mobile-apps-back-end-to-send-push-requests-by-using-fcm) that explains how to use FCM with Azure Notification Hub -- it may help to answer some of your questions.

**Comment by ithiredguns** [comment]
How about FCM for iOS ? Can you point me to the doc that shows for iOS also ? (Using FCM)

**Comment by conceptdev** [comment]
We do _not_ have documentation on using Firebase Cloud Messaging with iOS. For Firebase documentation refer to Google.

Alternatively, you can use App Center Push or Azure Notification Hubs on iOS.
