### ISSUE TITLE
Document that this code is not part of framework

### ISSUE THREAD

**Issue by jraldrin** [MicrosoftDocs/xamarin-docs#951]
As noted in previous comments this section reads like this topic is part of the framework.  Do us a solid and make crystal clear that this content is not part of the framework.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b06aff09-e5dd-9bba-d158-f3b61984d735
* Version Independent ID: 72c8ef2a-01f3-aee4-9a84-11995565b2d3
* Content: [Reusable EventToCommandBehavior - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/behaviors/reusable/event-to-command-behavior)
* Content Source: [docs/xamarin-forms/app-fundamentals/behaviors/reusable/event-to-command-behavior.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/app-fundamentals/behaviors/reusable/event-to-command-behavior.md)
* Product: **xamarin**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @jraldrin 

Fixed in a PR that will go out later.
