### ISSUE TITLE
No such test templates in VS 2017

### ISSUE THREAD

**Issue by bgavrilMS** [MicrosoftDocs/xamarin-docs#952]
I am not able to find any unit test templates for Xamarin. I am using VS 2017 version 15.8.7 and also 15.9.0 Preview 4. 

Could you provide guidance on how to run unit tests inside Visual Studio when targetting MonoAndroid and Xamarin.iOS10 ?

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 567dedb7-7aab-fa56-0fc1-2350a8e2f59b
* Version Independent ID: f92f0b63-02af-2258-8eb0-e62309ed8d70
* Content: [Unit Testing Xamarin.iOS Apps - Xamarin](https://docs.microsoft.com/en-gb/xamarin/ios/deploy-test/touch.unit?tabs=windows)
* Content Source: [docs/ios/deploy-test/touch.unit.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/ios/deploy-test/touch.unit.md)
* Product: **xamarin**
* GitHub Login: @lobrien
* Microsoft Alias: **laobri**

**Comment by conceptdev** [comment]
I also cannot find the unit test templates in the latest versions of VS2017 (although they seem to be available in Visual Studio for Mac, for both iOS and Android).

This ebook chapter on [unit testing](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/enterprise-application-patterns/unit-testing) is the only other content that comes to mind.

We will review the available features with the product team, and update these docs as required.

Thanks for the feedback.

**Comment by conceptdev** [comment]
I have discovered that the templates were indeed removed from Visual Studio on Windows. I am updating the doc to reflect this. For now, the template is still available in Visual Studio for Mac.

Thanks again for raising this issue.
