### ISSUE TITLE
Again, no Database and how about Async

### ISSUE THREAD

**Issue by mike-01** [MicrosoftDocs/xamarin-docs#953]
Why do these demo projects never include a comprehensive, local database implementation (using SQLite)? The demos that do include a database implementation are trivial implementations and don't implement async/await.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 68284ce9-61dc-d8fb-6c25-452aedab8292
* Version Independent ID: 15fc9629-a008-3f49-8c0b-83f992b14372
* Content: [Enterprise Application Patterns using Xamarin.Forms eBook - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/enterprise-application-patterns/)
* Content Source: [docs/xamarin-forms/enterprise-application-patterns/index.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/enterprise-application-patterns/index.md)
* Product: **xamarin**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by conceptdev** [comment]
Hi @mike-01, the eShopOnContainers sample has a [small (4 class) model](https://github.com/dotnet-architecture/eShopOnContainers/tree/dev/src/Mobile/eShopOnContainers/eShopOnContainers.Core/Models/User), but it does use Azure to store in the cloud. The goal is to demonstrate patterns without building _too_ complex an app, such that people can't easily learn from it.

You might be interested in other samples listed at https://docs.microsoft.com/en-us/xamarin/cross-platform/samples/ such as SmartHotel and BikeSharing, and also the [Azure MyDriving demo](https://docs.microsoft.com/en-us/xamarin/cross-platform/samples/).
