### ISSUE TITLE
errors with Phoneword 

### ISSUE THREAD

**Issue by jlt911** [MicrosoftDocs/xamarin-docs#955]
Hi, I have a new installation of Visual Studio Community 2017 for Mac
Version 7.6.10 (build 27).
I entered the code on this page. When I build I get two errors:
-MainPage.xaml.cs(17,32,17,51): error CS0103: The name 'PhonewordTranslator' does not exist in the current context
-MainPage.xaml.cs(38,52,38,59): error CS0246: The type or namespace name 'IDialer' could not be found (are you missing a using directive or an assembly reference?)
I'm new to this. This is my very first app and I'm lost. Please help.
Thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2de3e72c-8948-4dd5-e37f-9cf81e62c127
* Version Independent ID: 7b7c5c7f-4102-8e91-fbe6-7d21fcc8f5be
* Content: [Xamarin.Forms Quickstart - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/get-started/hello-xamarin-forms/quickstart?pivots=macos)
* Content Source: [docs/xamarin-forms/get-started/hello-xamarin-forms/quickstart.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/get-started/hello-xamarin-forms/quickstart.md)
* Product: **xamarin**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @jlt911 

It looks like you've missed step 11 (to create the PhonewordTranslator) and step 14 (to create IDialer).

If in doubt, look at the fully working sample that's linked from the bottom of the document (in the Related Links section).
