### ISSUE TITLE
Very interesting

### ISSUE THREAD

**Issue by GT85** [MicrosoftDocs/xamarin-docs#96]
Examples are good and clear. Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 08c274f5-e72f-067b-6cdc-81c50acc7616
* Version Independent ID: 5b0d048a-83d0-98a4-d4d0-027befc40365
* Content: [Creating iOS User Interfaces in Code - Xamarin](https://docs.microsoft.com/en-us/xamarin/ios/app-fundamentals/ios-code-only?tabs=vswin)
* Content Source: [docs/ios/app-fundamentals/ios-code-only.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/ios/app-fundamentals/ios-code-only.md)
* Service: **unspecified**
* GitHub Login: @bradumbaugh
* Microsoft Alias: **brumbaug**

**Comment by bradumbaugh** [comment]
Thanks for the positive feedback, @GT85 - it helps us to know what's working well! Thanks again.
