### ISSUE TITLE
XamlPlusCodePage: The slider is not accessible on iOS 12 simulator 

### ISSUE THREAD

**Issue by SergeyADoroshenko** [MicrosoftDocs/xamarin-docs#962]
in iOS 12, UIScreenEdgePanGestureRecognizer is picked so the UISlider element cannot be dragged. Adding margin to the UISlider element helps to work around that.

Sample: XamlPlusCodePage

**Comment by davidbritch** [comment]
Hi @SergeyADoroshenko 

I was able to drag the `Slider` just fine in this sample, using the iPhone 8 (iOS 12.0) simulator. Were you having issues with a particular simulator?

**Comment by conceptdev** [comment]
I noticed the same behavior on iPhone X simulator. Updated the sample with some spacing to the left & right of sliders. Thanks for the suggestion @SergeyADoroshenko
