### ISSUE TITLE
Très bon, mais le français laisse à désirer

### ISSUE THREAD

**Issue by GT85** [MicrosoftDocs/xamarin-docs#97]
Par exemples : "Ajour" au lieu de "Ajout".
"e/s des interfaces utilisateur sont constitués d’une hiérarchie de la vue." Mieux vaut revenir à l'anglais.

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 08c274f5-e72f-067b-6cdc-81c50acc7616
* Version Independent ID: 5b0d048a-83d0-98a4-d4d0-027befc40365
* Content: [Création d’Interfaces utilisateur d’iOS dans le Code - Xamarin](https://docs.microsoft.com/fr-fr/xamarin/ios/app-fundamentals/ios-code-only?tabs=vsmac#adding-a-controller)
* Content Source: [docs/ios/app-fundamentals/ios-code-only.md](https://github.com/MicrosoftDocs/xamarin-docs.fr-FR/blob/live/docs/ios/app-fundamentals/ios-code-only.md)
* Service: **unspecified**
* GitHub Login: @bradumbaugh
* Microsoft Alias: **brumbaug**

**Comment by Sara-Nicolini** [comment]
@GT85, Merci pour vos commentaires. La page en question a été traduite automatiquement, ce qui n'est n'est pas toujours parfaitement compréhensible. Nous avons récemment ajouté une option "Lire en anglais" sur la droite qui vous permet de passer à la version anglaise sans avoir à changer les paramètres de langue.
