### ISSUE TITLE
Default row and column spacing is undocumented

### ISSUE THREAD

**Issue by breyed** [MicrosoftDocs/xamarin-docs#971]
The default row and column spacing are each 6. However, this important detail is undocumented. It should be documented here and on the pages for the RowSpacing and ColumnSpacing properties.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c0902f8-eb40-4c56-958a-f13f064c8293
* Version Independent ID: 1e930440-f312-6301-d786-262b98f9ce2f
* Content: [Xamarin.Forms Grid - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/layouts/grid)
* Content Source: [docs/xamarin-forms/user-interface/layouts/grid.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/user-interface/layouts/grid.md)
* Product: **xamarin**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @breyed 

Fixed in a PR that will go out later.
