### ISSUE TITLE
64-bit and experimental status

### ISSUE THREAD

**Issue by gjkhw** [MicrosoftDocs/xamarin-docs#972]
I feel like the information about 64-bit support being experimental and not required is dated and could use a refresh. In particular, the statement "Note that 64-bit runtimes are not required to run your app on 64-bit devices." is now dated. 

In December of 2017, Google announced "In August 2019, Play will require that new apps and app updates with native libraries provide 64-bit versions in addition to their 32-bit versions." (https://android-developers.googleblog.com/2017/12/improving-app-security-and-performance.html)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a32491c7-24a6-ae8e-5d9a-79815b6d5806
* Version Independent ID: 5d6f6635-9cae-2969-9aa7-38dc4c549b7d
* Content: [Multi-Core Devices & Xamarin.Android - Xamarin](https://docs.microsoft.com/en-us/xamarin/android/deploy-test/multicore-devices)
* Content Source: [docs/android/deploy-test/multicore-devices.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/android/deploy-test/multicore-devices.md)
* Product: **xamarin**
* GitHub Login: @conceptdev
* Microsoft Alias: **crdun**

**Comment by conceptdev** [comment]
Hi @gjkhw, thanks for bringing this to our attention, definitely needs an update.

**Comment by conceptdev** [comment]
Made some updates - thanks for the info.

**Comment by gjkhw** [comment]
Nicely done. Good succinct doc links help me justify spending time on tech debt to my managers. ;-)
