### ISSUE TITLE
Example Image broken?

### ISSUE THREAD

**Issue by garrettbass** [MicrosoftDocs/xamarin-docs#974]
The example image of the "ToDoService.asmx.cs" seems to have an image of the two phone screens overlapped on top it, cutting off a lot of the code in the image. The example solution provided also doesn't seem to be an actual Xamarin.Forms Cross-Platform solution as the main project has features that are missing in a cross-platform solution such as the ability to add References which is very frustrating.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72b7ac73-7fd9-4abe-e73a-e1a88e1d2b11
* Version Independent ID: bd6ee8cf-dd83-c974-8849-83a27553b378
* Content: [Consuming an ASP.NET Web Service (ASMX) - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/data-cloud/consuming/asmx)
* Content Source: [docs/xamarin-forms/data-cloud/consuming/asmx.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/data-cloud/consuming/asmx.md)
* Product: **xamarin**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by conceptdev** [comment]
The image is intentionally formatted to show the app running on two platforms. The code is included in the remainder of the article, and is also available to download from the sample link at the end ([TodoASMX](https://developer.xamarin.com/samples/xamarin-forms/WebServices/TodoASMX/)). 

The main project - **TodoASMX** - is a Xamarin.Forms .NET Standard 2.0 library, which includes a reference to the Xamarin.Forms NuGet (see screenshot below). You should be able to reference other libraries or NuGets that are .NET Standard-compatible.

![screen shot 2018-10-31 at 9 17 58 am](https://user-images.githubusercontent.com/199373/47802616-e577e580-dced-11e8-9eab-be7b2d7f8ca8.png)
