### ISSUE TITLE
regarding Remote Simulator to Windows discussion

### ISSUE THREAD

**Issue by patesuj** [MicrosoftDocs/xamarin-docs#975]
Hi,
Thanks for sharing this article:
https://docs.microsoft.com/en-us/xamarin/tools/ios-simulator/index

When I run my Xamarin iOS test via Visual Studio 2017, I got the following message: “iOS tests are not supported on Windows”. I have set up Remote Simulator to Windows option so it should open simulator but it didn't happen so please tell me what's wrong? 

Here is my test configuration:
I have installed Visual Studio 2017 Enterprise Version 15.8.5 with Xamarin version 4.11.
I have created new Test Project using Xamarin.UITest Cross-Platform Test Project template.
I have also configured Mac Book using Pair to Mac option and it is connected fine.
I have checked Remote Simulator to Windows option in IOS Settings via VS Tools options in order to run my test on remote simulator.
I have following code in my Test.cs file
    if (platform == Platform.iOS)
            {
                return ConfigureApp
                    .iOS
     .InstalledApp("com.example.yourappbundleid")
                    .EnableLocalScreenshots()
                    .StartApp();
                    
            }
When I run the test, I got the following message: iOS tests are not supported on Windows.
As I have said earlier, I have set up Remote Simulator to Windows option so it should open simulator but it didn't happen so please tell me what's wrong? 
I knew we can't run test directly on windows machine using actual device but I should open the remote simulator.
Please suggest me the solution or any updated information you have regarding running iOS test on Remote Simulator.
Many thanks in advance.
SPatel

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e014d765-cca5-5b2a-af53-50b5a0f4aa5d
* Version Independent ID: de44c2d0-7146-b204-6ff7-9fed0da21aaf
* Content: [Deploying to the Remoted iOS Simulator - Xamarin](https://docs.microsoft.com/en-us/xamarin/tools/ios-simulator/deploy)
* Content Source: [docs/tools/ios-simulator/deploy.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/tools/ios-simulator/deploy.md)
* Product: **xamarin**
* GitHub Login: @conceptdev
* Microsoft Alias: **crdun**

**Comment by conceptdev** [comment]
As explained in the [App Center Test documentation](https://docs.microsoft.com/en-us/appcenter/test-cloud/preparing-for-upload/uitest#visual-studio-windows):

>Xamarin.UITests for iOS apps cannot be executed locally on Windows. You can still create, compile and upload to App Center Test from Windows.

You cannot run iOS tests on Windows, even with the remoted iOS Simulator.

**Comment by patesuj** [comment]
Thank you for your quick reply. Can I run the same test on Mac Book using Visual Studio for Mac? 
Also please share document regarding uploading to App Center from Windows.
Thanks in advance

**Comment by conceptdev** [comment]
Please refer to the [App Center documentation](https://docs.microsoft.com/appcenter/) for details on using Xamarin.UITest.

**Comment by patesuj** [comment]
Sure thank you but please answer following question too.
Can I run the same test on Mac Book using Visual Studio for Mac?
