### ISSUE TITLE
Icons in the action sheet

### ISSUE THREAD

**Issue by MJRomka** [MicrosoftDocs/xamarin-docs#977]
Are there any plans to support icons with DisplayActionSheet?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c8f4c43c-c05b-1eee-7cf1-671917adf530
* Version Independent ID: 46b37e30-1549-d2bb-6c8d-23c6db97ed35
* Content: [Displaying Pop-ups - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/navigation/pop-ups)
* Content Source: [docs/xamarin-forms/app-fundamentals/navigation/pop-ups.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/app-fundamentals/navigation/pop-ups.md)
* Product: **xamarin**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @MJRomka 

You should consult the [roadmap](https://github.com/xamarin/Xamarin.Forms/wiki/Feature-Roadmap). If the feature isn't present, consider opening a feature proposal.
