### ISSUE TITLE
Clearing the List of Build Servers Doesn't Work

### ISSUE THREAD

**Issue by PatrickRyder** [MicrosoftDocs/xamarin-docs#978]
I have carefully followed the instructions for deleting the list of Mac build servers listed in Visual Studio but an old (broken) entry persists.  If I right-click it, the 'Forget' option is greyed-out so there appears to be no way to fix this short of a complete reinstall of Visual Studio and possibly all related stuff on the Mac.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 992a68e4-2f19-9cb5-d3b6-4f682ee8a1f4
* Version Independent ID: 61923335-63c3-cc42-f310-eb090e09497b
* Content: [Connection Troubleshooting for a Xamarin.iOS Build Host - Xamarin](https://docs.microsoft.com/en-us/xamarin/ios/get-started/installation/windows/connecting-to-mac/troubleshooting#clearing)
* Content Source: [docs/ios/get-started/installation/windows/connecting-to-mac/troubleshooting.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/ios/get-started/installation/windows/connecting-to-mac/troubleshooting.md)
* Product: **xamarin**
* GitHub Login: @lobrien
* Microsoft Alias: **laobri**

**Comment by conceptdev** [comment]
Hi @PatrickRyder, that sounds annoying, and possibly a bug. You can [report it via Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio-2017?view=vs-2017) or go directly to [Developer Community](https://developercommunity.visualstudio.com/spaces/8/index.html). Supplying all the version info and logs there could help diagnose the issue, so it's really helpful if you do that before taking drastic action like reinstalling everything (of course, if it's blocking your work, it would be understandable if you wanted to keep experimenting for a fix asap).
