### ISSUE TITLE
Visual Studio Pair a Mac Error - OPENSSH IS Not Supported

### ISSUE THREAD

**Issue by liliyashka** [MicrosoftDocs/xamarin-docs#979]
I get an error when trying to connect to my mac. I can connect with putty and I can ping my mac ip address but I can not pair with visual studio. Visual studio connected and even installed missing mono files but when it trys to further connect I get this error. I spent about 10 hours on this one issue. I reinstalled OSX. Im running OSX Mojave clean booted. I cleaned caches, restarted pc and mac. Created new ip address and so on and nothing works. 
I breaks right after it says starting connection to ........ 

So I can see that the connection works and I can input login info each time no problem. But while trying to connect I get this OPENSSH is not supported error. Please help me solve this issue as soon as possible as I can not continue IOS development. Thank you.

**Comment by conceptdev** [comment]
@liliyashka this issues list is for feedback relating to the documentation. 

In case you did not already see it, there is [connection troubleshooting info](https://docs.microsoft.com/en-us/xamarin/ios/get-started/installation/windows/connecting-to-mac/troubleshooting) available.

For product issues, you can click the **Product feedback** at the bottom of each doc page, or [report a problem via Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio-2017?view=vs-2017) which will submit it to the [Developer Community site](https://developercommunity.visualstudio.com/spaces/8/index.html).

**Comment by liliyashka** [comment]
> @liliyashka this issues list is for feedback relating to the documentation.
> 
> In case you did not already see it, there is [connection troubleshooting info](https://docs.microsoft.com/en-us/xamarin/ios/get-started/installation/windows/connecting-to-mac/troubleshooting) available.
> 
> For product issues, you can click the **Product feedback** at the bottom of each doc page, or [report a problem via Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio-2017?view=vs-2017) which will submit it to the [Developer Community site](https://developercommunity.visualstudio.com/spaces/8/index.html).

I went over that troubleshooting guide like a million times. Nothing there helps me. I cant get passed:
OPENSSH is not supported error

**Comment by liliyashka** [comment]
Here is my output on Visual Studio

Checking host configuration for connecting to '192.168.213.130'...
Checking SSH configuration...
Checking available disk space...
Checking Mono installation...
Checking Xamarin iOS installation...
Checking host configuration for connecting to '192.168.213.130'...
Host '192.168.213.130' is configured correctly
Starting connection to '192.168.213.130'...
Starting connection to '192.168.213.130'...
Starting disconnection from 192.168.213.130...
Starting disconnection from 192.168.213.130...
The connection to '192.168.213.130' has been finished
Couldn't connect to 192.168.213.130. Please try again.

**Comment by liliyashka** [comment]
Here is a video to the problem.
https://www.youtube.com/watch?v=KTobenSKUm8&t=1s
