### ISSUE TITLE
Missing a vital piece of info

### ISSUE THREAD

**Issue by serzhikivanov** [MicrosoftDocs/xamarin-docs#980]
There's no specific mention that the assembly containing this extension Translate class should be a separate assembly. I have created this class in the PCL, supplied correct namespace and assembly names and spent a lot of time trying to figure out why it crashes with notice that it couldn't find the Translate extension 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: af66394d-81c5-0c2e-1682-a2bb7eeb3c3e
* Version Independent ID: 27542a45-2f25-4042-cf48-b9517025635c
* Content: [String and Image Localization - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/localization/text?tabs=macos#feedback)
* Content Source: [docs/xamarin-forms/app-fundamentals/localization/text.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/app-fundamentals/localization/text.md)
* Product: **xamarin**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by davidbritch** [comment]
Hi @serzhikivanov 

The `TranslateExtensions` class doesn't have to be in a separate assembly. It can be in the PCL/.NET Standard Library. If you look at the [sample](https://developer.xamarin.com/samples/xamarin-forms/UsingResxLocalization/) the page references, that's how it's done.
