### ISSUE TITLE
Add "HasNotchedDisplay" property

### ISSUE THREAD

**Issue by AuriR** [MicrosoftDocs/xamarin-docs#981]
It would be helpful to know if the device has a notched display.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c918dea8-217e-8886-73ad-c1dcb9cc1e1e
* Version Independent ID: 238f8427-325c-dc77-caaf-1f3a8e44df88
* Content: [Xamarin.Essentials: Device Information - Xamarin](https://docs.microsoft.com/en-us/xamarin/essentials/device-information?context=xamarin%2Fxamarin-forms&tabs=ios)
* Content Source: [docs/essentials/device-information.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/essentials/device-information.md)
* Product: **xamarin**
* GitHub Login: @jamesmontemagno
* Microsoft Alias: **jamont**

**Comment by conceptdev** [comment]
Thanks for your feedback @AuriR. 

In future, for product feedback, use the **Product feedback** at the bottom of the page, which will take you to [the open source GitHub repo](https://github.com/xamarin/Essentials/blob/master/PRODUCT-FEEDBACK.md)

![screen shot 2018-11-02 at 11 39 31 am](https://user-images.githubusercontent.com/199373/47934223-fe220000-de93-11e8-8d49-81f87f6b6440.png)
