### ISSUE TITLE
This doesn't work 

### ISSUE THREAD

**Issue by ChrisMcdonald** [MicrosoftDocs/xamarin-docs#983]
Please update the documentation to a working example. For example a custom label text property getting set by a bindable property

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b054a909-6f7f-0b32-5059-eb5c8a9b366b
* Version Independent ID: 723af07b-8f4e-ebe3-a520-99cdcf5efc5a
* Content: [Bindable Properties - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/xaml/bindable-properties)
* Content Source: [docs/xamarin-forms/xaml/bindable-properties.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/xaml/bindable-properties.md)
* Product: **xamarin**
* GitHub Login: @charlespetzold
* Microsoft Alias: **chape**

**Comment by davidbritch** [comment]
Hi @ChrisMcdonald 

What code doesn't work for? All the code in this doc comes from the samples that are linked to at the end of the doc.

**Comment by ChrisMcdonald** [comment]
This is a terrible example is this how it is suppose to look
![screen shot 2018-11-09 at 11 00 27 am](https://user-images.githubusercontent.com/25333688/48236627-c45e7580-e40e-11e8-8cee-0ed607858e9c.png)

**Comment by davidbritch** [comment]
Hi @ChrisMcdonald 

Confirmed that the sample is misbehaving. I'll get it fixed.

**Comment by davidbritch** [comment]
I've fixed this issue in both the doc and sample. It'll be later in the day before the doc update PR goes live.
