### ISSUE TITLE
Clarification: what is a Business license?

### ISSUE THREAD

**Issue by ztl8702** [MicrosoftDocs/xamarin-docs#986]
The documentation says:

&gt; The LLVM Optimizing Compiler option requires a Business license.

What counts as a business license? Visual Studio Professional? or Enterprise only?

Does the ["Visual Studio Professional monthly subscription"](https://marketplace.visualstudio.com/items?itemName=ms.vs-professional-monthly) count as well?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f43472af-a9d3-8bef-0f24-b81f8f6cd2dd
* Version Independent ID: 42cfbea5-0b4c-a0a3-4cce-1edf5523f605
* Content: [Preparing an Application for Release - Xamarin](https://docs.microsoft.com/en-us/xamarin/android/deploy-test/release-prep/?tabs=macos#Set_Packaging_Properties)
* Content Source: [docs/android/deploy-test/release-prep/index.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/android/deploy-test/release-prep/index.md)
* Product: **xamarin**
* GitHub Login: @conceptdev
* Microsoft Alias: **crdun**

**Comment by ztl8702** [comment]
@conceptdev any updates?

**Comment by ztl8702** [comment]
@conceptdev ping

**Comment by conceptdev** [comment]
Hi @ztl8702 it looks like in this case, the correct license is a Visual Studio Enterprise license. I'll be updating the page too.

**Comment by ztl8702** [comment]
All right. Good to know. Thanks!
