### ISSUE TITLE
There are requirements missing in the doco

### ISSUE THREAD

**Issue by Chris-Marassovich** [MicrosoftDocs/xamarin-docs#987]
I am on latest 2017 (15.8.9).  When I create a Xamarin Forms app from scratch the previewer works fine.

When I use a solution that is quite old in creation, I think created using Xamarin Studio, and I have modernized it such as PCL's to .netstandard, updated NuGets to current and so on.  The previewer does not light up.  I get no errors.  The previewer controls are not present.

I can see no obvious difference between my simple XF new solution and my old solution.
My old solution is very large and I am sure there is something I am missing but for the life of me I cannot see it.
Are you able to update the doco as there is quite clearly another requirement that I do not satisfy.

Cheers
Chris ..

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7c68dedd-a9ba-8c0e-ffa0-3ea5c50cde24
* Version Independent ID: fc61bfbb-f86b-c5dd-fa57-0e55fce4683f
* Content: [XAML Previewer for Xamarin.Forms - Xamarin](https://docs.microsoft.com/en-au/xamarin/xamarin-forms/xaml/xaml-previewer?tabs=windows)
* Content Source: [docs/xamarin-forms/xaml/xaml-previewer.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/xaml/xaml-previewer.md)
* Product: **xamarin**
* GitHub Login: @charlespetzold
* Microsoft Alias: **chape**

**Comment by conceptdev** [comment]
Hey @Chris-Marassovich, perhaps you've uncovered a bug in Visual Studio. If you could use the [**Help > Report a problem**](https://docs.microsoft.com/en-us/visualstudio/mac/report-a-problem) feature, the product team can take a look. Thanks!
