### ISSUE TITLE
The link to android original doc doesn't exist any more.

### ISSUE THREAD

**Issue by winffee** [MicrosoftDocs/xamarin-docs#988]
The link at the end of this Doc, doesn't exist any more.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d07ac01b-c1bd-e616-4d3e-b759885d3b9c
* Version Independent ID: c24c15b1-a814-cd82-3ef7-9fc463397a2f
* Content: [Command Line Emulator - Xamarin](https://docs.microsoft.com/en-us/xamarin/android/deploy-test/command-line-emulator)
* Content Source: [docs/android/deploy-test/command-line-emulator.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/android/deploy-test/command-line-emulator.md)
* Product: **xamarin**
* GitHub Login: @conceptdev
* Microsoft Alias: **crdun**

**Comment by conceptdev** [comment]
Thanks, this has been updated to the new link https://developer.android.com/studio/run/emulator-commandline
