### ISSUE TITLE
Problem with "Shared Resources" section.

### ISSUE THREAD

**Issue by PaulWWeaver** [MicrosoftDocs/xamarin-docs#99]
In the "final complete XAML file with three buttons..." section:
    FontSize"{StaticResource fontSize}"
              Should be
    FontSize="{StaticResource fontSize}"

Also, any time I try to use a StaticResource for FontSize, the UWP app crashes.  (Haven't tried Android or ios).  This is with VStudio 15.6.5, Xamarin 4.9.0.752 (0faa808ee).  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 673a2420-3d41-aa5d-a8e4-3383cf10da6e
* Version Independent ID: ecdf7b35-97d1-524d-d448-9b7865b5b66a
* Content: [Part 3. XAML Markup Extensions - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/xaml/xaml-basics/xaml-markup-extensions#shared-resources)
* Content Source: [docs/xamarin-forms/xaml/xaml-basics/xaml-markup-extensions.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/xaml/xaml-basics/xaml-markup-extensions.md)
* Service: **unspecified**
* GitHub Login: @charlespetzold
* Microsoft Alias: **chape**

**Comment by charlespetzold** [comment]
Thank you! Defining a `FontSize` resource as an `x:String` worked once but does not work any longer. It's much safer to define the resource as an `x:Double` with a numeric value. I have made that change in this article and the **XamlSamples** code sample. The changes should show up within a day or so.

**Comment by EduardoMX** [comment]
Problem with "Shared Resources" section.

its giving me an error, Value cannot be null

**Comment by XfHua** [comment]
In the paragraph: Here’s the final complete XAML file with three buttons accessing six shared values....

<x:String x:Key="fontSize">Large</x:String> is not work right now.
