### ISSUE TITLE
Incorrect Package for FusedLocationProviderClient

### ISSUE THREAD

**Issue by te0d** [MicrosoftDocs/xamarin-docs#990]
The article says to install the package Xamarin.GooglePlayServices.Maps when really Xamarin.GooglePlayServices.Location is the required package.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e091d4a3-b105-70f5-38d2-5b2de109ed04
* Version Independent ID: 7081d0bd-9061-eda8-dac2-1f6f42bffd02
* Content: [Location Services - Xamarin](https://docs.microsoft.com/en-us/xamarin/android/platform/maps-and-location/location)
* Content Source: [docs/android/platform/maps-and-location/location.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/android/platform/maps-and-location/location.md)
* Product: **xamarin**
* GitHub Login: @conceptdev
* Microsoft Alias: **crdun**

**Comment by davehump** [comment]
I have created PR #2705 to fix this issue
