### ISSUE TITLE
Using WKWebView on iOS 8 and newer

### ISSUE THREAD

**Issue by CeciAc** [MicrosoftDocs/xamarin-docs#991]
@ncarandini commented on [Sun Nov 04 2018](https://github.com/MicrosoftDocs/xamarin-docs.it-it/issues/5)

As reported by David Ortinau on his [blog post](https://blog.xamarin.com/xamarin-forms-3-3-0-little-things-huge-difference/), Xamarin Forms 3.3.0 has added the availability of WKWebView without the need of a custom control.
Simply add this directive to your AssemblyInfo.cs:
`[assembly: ExportRenderer(typeof(WebView), typeof(WKWebViewRenderer))]`

I think this should be added to the document, to correct and extend the sentence:
"If that's a problem, you'll need to write a custom renderer that uses WKWebView, which supports faster browsing" in the Performance section.

Note that this is only for the English version of the Italian page, that is oddly NOT the same version of the English page!

Compare the [English page](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/webview) to the [Italian page](https://docs.microsoft.com/it-it/xamarin/xamarin-forms/user-interface/webview?tabs=vswin), after switching to the English version

![image](https://user-images.githubusercontent.com/139274/47962698-e3c95d00-e020-11e8-83bb-4a89b4656d0d.png)

---
#### Dettagli del documento

⚠ *Non modificare questa sezione. È necessaria per i collegamenti relativi ai problemi tra docs.microsoft.com ➟ GitHub.*

* ID: ef31dc71-3610-6c18-2bda-d0bb70804c92
* Version Independent ID: 02f7dc7b-541b-4b82-b33c-4e974fb94d8c
* Content: [WebView di xamarin. Forms - Xamarin](https://docs.microsoft.com/it-it/xamarin/xamarin-forms/user-interface/webview?tabs=vswin)
* Content Source: [docs/xamarin-forms/user-interface/webview.md](https://github.com/MicrosoftDocs/xamarin-docs.it-IT/blob/live/docs/xamarin-forms/user-interface/webview.md)
* Product: **xamarin**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by CeciAc** [comment]
Hi team, 
I'm moving this here because the user reports an issue in the original documentation BUT the one it appears in the it-IT page after changing it to english.
Please, check this issue
@JasonCard

**Comment by ncarandini** [comment]
I can confirm that now the English page shown selecting "leggere in inglese" on the Italian page is in sync with the latest English version.

This wasn't true on my browser at the time of writing my issue, on Nov, 4th. Maybe some proxy mechanism postponed the sync. Anyway, now is ok so you can close the issue, many thanks for time and effort you all put in response of the issues we write. When I can, I also like to contribute with PRs.
Docs rocks! 😸

**Comment by davidbritch** [comment]
Closing as requested.
