### ISSUE TITLE
Live Player for UWP?

### ISSUE THREAD

**Issue by mbalcerzyk** [MicrosoftDocs/xamarin-docs#996]
1. Any chance that Live Player for UWP x86 , x64, ARM for Windows 10.0.15063 (and please not higher) will ever be developed? Live Player is not on GitHub I see. 
2. In VS there was Live Previewer once, but I never got it working for Android. Can this be revived?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0c2e54f0-7761-c7fb-7de7-6680782dc771
* Version Independent ID: 323dd999-d78a-819a-cc93-8cf6a6b36fac
* Content: [Xamarin Live Player App - Xamarin](https://docs.microsoft.com/en-us/xamarin/tools/live-player/player?tabs=windows)
* Content Source: [docs/tools/live-player/player.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/tools/live-player/player.md)
* Product: **xamarin**
* GitHub Login: @lobrien
* Microsoft Alias: **laobri**

**Comment by conceptdev** [comment]
Live Player currently only supports Android, and remains a Preview technology only. There are no plans to extend it to other platforms at this time.

Live Reload was also a Preview technology, but the preview has ended.
