### ISSUE TITLE
The `RESX files` link is outdated and its content only has a VB sample (not C# or F#)

### ISSUE THREAD

**Issue by knocte** [MicrosoftDocs/xamarin-docs#997]
Seems the link where `RESX files` leads to is outdated, because its URL contains "previous-versions/" in it: https://docs.microsoft.com/en-us/previous-versions/visualstudio/visual-studio-2008/ekyft91f(v=vs.90)

Plus, that page only seems to have a VB sample. I would expect at least it to have a C# sample and default to it (F# desirable).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: afe74e14-16a6-08f7-bf4d-e8e3b0d0f0c4
* Version Independent ID: f466d02e-f83f-fb32-76fa-bd010366bf41
* Content: [Xamarin.Forms Localization - Xamarin](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/localization/)
* Content Source: [docs/xamarin-forms/app-fundamentals/localization/index.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/xamarin-forms/app-fundamentals/localization/index.md)
* Product: **xamarin**
* GitHub Login: @davidbritch
* Microsoft Alias: **dabritch**

**Comment by conceptdev** [comment]
Perhaps this link/section is more useful: [Resources in RESX files](https://docs.microsoft.com/en-us/dotnet/framework/resources/creating-resource-files-for-desktop-apps#resources-in-resx-files)?

Thanks for the feedback - we will definitely update the doc.
