### ISSUE TITLE
Share between solutions

### ISSUE THREAD

**Issue by freerider7777** [MicrosoftDocs/xamarin-docs#998]
What's the recommended way to reference code in other solution? Reference to dll?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4cc8f83c-a8f5-ab4e-76f5-b617b65fe1ed
* Version Independent ID: 43dfad72-eea2-7607-9bee-b43f1cbab255
* Content: [Sharing Code Overview - Xamarin](https://docs.microsoft.com/en-us/xamarin/cross-platform/app-fundamentals/code-sharing)
* Content Source: [docs/cross-platform/app-fundamentals/code-sharing.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/cross-platform/app-fundamentals/code-sharing.md)
* Product: **xamarin**
* GitHub Login: @conceptdev
* Microsoft Alias: **crdun**

**Comment by conceptdev** [comment]
Producing an assembly (.NET Standard or PCL) is the easiest way to share .NET code. Don't forget to take advantage of [versioning](https://docs.microsoft.com/dotnet/framework/app-domains/assembly-versioning) to keep track of updates to the code.

For enterprises or other situations where you might want to share the code with a large internal group (with support for updates), many [host their own NuGet feed](https://docs.microsoft.com/nuget/hosting-packages/overview) and then publish the code they want to share as a NuGet package. You can [create a NuGet manually](https://docs.microsoft.com/nuget/create-packages/creating-a-package), from [Visual Studio on Windows](https://docs.microsoft.com/en-us/nuget/quickstart/create-and-publish-a-package-using-visual-studio) or [Visual Studio for Mac](https://docs.microsoft.com/xamarin/cross-platform/app-fundamentals/nuget-multiplatform-libraries/).
